### ISSUE TITLE
Deleted note remains in sidebar until browser refresh

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#1007]
I'm running the latest version (0.42.1) and have been noticing some issues when deleting notes using the web interface. 

Firefox 76 (latest)

Normally when deleting a note, the web interface will refresh and the note will be gone from the left sidebar, but recently the note will remain in the left sidebar until I refresh the browser tab.

**Comment by meichthys** [comment]
It looks like creating a new note also doesn't show the note in the sidebar until after i refresh. 
When i right click on a node in the sidebar and choose "Insert Child Note", nothing happens, but after a refresh, the "new note" appears in the sidebar and i can edit it like normal.

Also, i can confirm that the desktop version of Trilium does _not_ exhibit this behavior.

**Comment by zadam** [comment]
Hello, sounds like the websocket commmunication is broken (often reverse proxy issue) ... Can you take a look into browser console if you see some errors?

**Comment by meichthys** [comment]
Sure enough..
![image](https://user-images.githubusercontent.com/10717998/81565874-0cde5280-9368-11ea-9e64-7be3ab1d9c7a.png)

I wonder why the desktop client would work but the browser wouldn't?

**Comment by zadam** [comment]
Desktop client uses websocket only locally and does not have to connect to the remote server.

Check your server config (apache, nginx), websocket might be unsupported/blocked or whatever.

**Comment by meichthys** [comment]
That did the trick! With @jc21's [NginxProxyManager ](https://nginxproxymanager.com/)it was too easy!
![image](https://user-images.githubusercontent.com/10717998/81567329-2b454d80-936a-11ea-9791-8bd0ddcfddd2.png)
