### ISSUE TITLE
Promoted attribute getting duplicated

### ISSUE THREAD

**Issue by erdnaxeli** [zadam/trilium#1008]
I am using v0.42. I noticed changing the value of a promoted attribute actually duplicates it.

![2020-05-11-145749_729x407_scrot](https://user-images.githubusercontent.com/479441/81564350-e1735c00-9397-11ea-9b39-e98b115300cd.png)

I don't really know why boolean attributes show twice, while text attribute show only once (but there is actually two of them!).

The problem comes from `attributeId` never been sent in the `PUT` call, so the server create a new attribute. And it is never sent because it is not set on the html object, because `isOwned` is not present (so always undefined, hence false).

**Comment by erdnaxeli** [comment]
Oh, the publicationYear not being shown twice was just because I did not do a refresh.

**Comment by zadam** [comment]
Hello, are you using 0.42.0-beta? Since I believe this bug has been already fixed and should not appear in 0.42.1

**Comment by erdnaxeli** [comment]
I think so, I can reproduce the bug with on master (2e837642e2f747b4404a83216baf5fa1778e7aee).

**Comment by erdnaxeli** [comment]
To reproduce:

1. create a new note
2. add a promoted label-definition test, type boolean
3. refresh the note to see the promoted attribute
4. check it
5. refresh the note again
6. uncheck it
7. refresh
8 => you new see to "test" attribute, one checked and one not

The this is at step 4, when we check, the id is set so if we uncheck it now it will work. But if we refresh, it rebuilds the note without setting the attribute id, so the step 6 create a new attribute.

**Comment by zadam** [comment]
Thanks, now I was able to reproduce it. I committed the fix, but I chose a different approach than what you proposed in your PR (which was helpful in identifying the problem though!) - `isOwned` is clearly contextual and depends on the note, I removed this property and it's detected on the fly now. This saves the memory as we don't need to clone the attribute object itself ...

Thank you for your help!
