### ISSUE TITLE
[ ] or [x] not resulting in a checkbox

### ISSUE THREAD

**Issue by thansk** [zadam/trilium#1010]
Similar to how `- ` results in an unordered list, or `1. ` results in an ordered list, I think `[ ] ` and `[x] ` or `- [ ]` and `- [x]` (but the latter 2 would probably break the unordered list functionality) should result in a "task list"

**Comment by tmaleshafske** [comment]
I have the same question.

**Comment by zadam** [comment]
This would have to be implemented as auto formatting in CKEditor.

**Comment by zadam** [comment]
This already works in CKEditor.
