### ISSUE TITLE
Migrate from OneNote to Trilium

### ISSUE THREAD

**Issue by DimitriyPro** [zadam/trilium#1013]
So... There is a question - how to do it?
There is a similar program with this feature: https://github.com/laurent22/joplin
Did you know a way to migrate on Trilium?

**Comment by zadam** [comment]
There isn't any specific OneNote import.

Trilium supports importing (zipped) directory structure with HTML/Markdown files with images etc. But I don't know if OneNote can export such directory structure.

**Comment by DimitriyPro** [comment]
Thank you zadam!
But I think there is a way to use already done solution:
https://github.com/laurent22/joplin/blob/e399474b4e2e2dffc625a0414232031ed290b81c/ReactNativeClient/lib/import-enex-md-gen.js
https://github.com/laurent22/joplin/blob/e399474b4e2e2dffc625a0414232031ed290b81c/ReactNativeClient/lib/import-enex.js
Import from Evernote (Evernote can import from many other programs for note taking). We have solution for Evernote but do you know how to integrate it to Trilium? I have some skills in web-programming but not in so complecated projects. Thank you!

**Comment by zadam** [comment]
ENEX is already supported as an import format so if you have ENEX, just use import dialog ...

**Comment by DimitriyPro** [comment]
Wow! Brilliant!
But I can't find Import page on https://github.com/zadam/trilium/wiki

**Comment by zadam** [comment]
Just right click on a note where you want to import the ENEX:  
  
 

![](https://user-images.githubusercontent.com/617641/81709938-924e2980-9472-11ea-8663-02a3ab615d4f.png)

**Comment by meichthys** [comment]
@DimitriyPro There is [this ](https://github.com/Danmou/onenote_export) script as well. I used it a slightly modified version of it a few months ago to migrate from Onenote to Trilium. Three were a few side-effects, but nothing that couldn't be cleaned up once imported into Trilium.

**Comment by DimitriyPro** [comment]
@meichthys thank you! It's very useful script!

**Comment by meichthys** [comment]
@DimitriyPro If the above links helped, could you mark this issue as resolved?

**Comment by tejasvi** [comment]
I trying multiple methods, I can attest to the superior conversion using Evernote's .enex as the intermediary. I had reasonably complex note structures, and the translation has been much better than I could expect.

**Comment by tejasvi** [comment]
After trying multiple methods, I can attest to the superior conversion using Evernote's .enex as the intermediary. I had reasonably complex note structures, and the translation has been much better than I could expect.

**Comment by yllekz** [comment]
Putting in a +1 for looking into a cleaner way to import OneNote content. I've been manually migrating pages, but it very quickly became clear that it would be cumbersome; a lot of formatting either gets changed or doesn't paste in correctly.

OneNote on the desktop has a decent amount of export options, including the .mht format which is html-adjacent. Perhaps an import utility can be leveraged by that?

**Comment by meichthys** [comment]
@yllekz If you're willing to put in a bit of work, [this ](https://github.com/Danmou/onenote_export) script should help out significantly. I used it with some modifications to export Onenote to HTML and then import into Trilium.

**Comment by zadam** [comment]
I've added the content, also added you as a collaborator, so you can update the wiki if you wish. Feel free to make changes, I've just pasted it there.

**Comment by Beexx** [comment]
Hello,
The link to download Evernote Legacy no longer exists. The page may have been deleted by Evernote. 
I was able to download the Evernote Legacy installer though, by fetching a cached version on https://web.archive.org.
You might want to try the same, until Evernote decides to publish it again...
https://web.archive.org/web/20230327110646/https://help.evernote.com/hc/en-us/articles/360052560314
Cheers,

**Comment by swissbuechi** [comment]
Windows:
[https://cdn1.evernote.com/win6/public/Evernote_6.25.3.9348.exe](https://web.archive.org/web/20221129135013mp_/https://cdn1.evernote.com/win6/public/Evernote_6.25.3.9348.exe)

Mac:
[https://cdn1.evernote.com/mac-smd/public/EvernoteLegacy_RELEASE_7.14.1_458325.zip](https://web.archive.org/web/20221129135013mp_/https://cdn1.evernote.com/mac-smd/public/EvernoteLegacy_RELEASE_7.14.1_458325.zip)

Check sum (md5):
6f77a09b933ad0b895b10fad137dcee1 *Evernote_6.25.3.9348.exe
5feefa52d54ac6ef09bd9017814a17dd *EvernoteLegacy_RELEASE_7.14.1_458325.zip

The web page:
https://web.archive.org/web/20230326100256/https://help.evernote.com/hc/en-us/articles/360052560314-Install-an-older-version-of-Evernote
