### ISSUE TITLE
Build Trilium

### ISSUE THREAD

**Issue by DimitriyPro** [zadam/trilium#1017]
Could you help me please, I want to try build Trilium by myself. Do you have instructions for this case? Thank you!

**Comment by zadam** [comment]
There's a guide for manual server setup: https://github.com/zadam/trilium/wiki/Manual-server-installation

Otherwise checkout scripts in bin directory - e.g. `build-linux-x64.sh` will build the linux desktop build.

**Comment by DimitriyPro** [comment]
Thank you for your reply!
But I'm using Windows and want to try add some features.

**Comment by zadam** [comment]
There's also `build-win-x64.sh` which you can follow.
