### ISSUE TITLE
stats not rendering with 0.42.2

### ISSUE THREAD

**Issue by mursilsayed** [zadam/trilium#1019]
I started using the latest version 0.42.2 Kubuntu 20.0.4 and found out that stats are not rendering with docker based installation. I first got this issue with the docker based triliium but then I was also able to reproduce it with a fresh installation of desktop application via deb pacakage.

**Comment by zadam** [comment]
Hello, thank you for reporting this issue - yes, this is unfortunately a regression introduced in 0.42.2. This was fixed and will be released in 0.42.3.
