### ISSUE TITLE
Export / Sync Options?

### ISSUE THREAD

**Issue by BeecherNetworks** [zadam/trilium#1020]
Is there a way of syncing options, or exporting / importing them, from server to desktop?

**Comment by zadam** [comment]
Which options do you have in mind?

Actually there are 2 kinds of options - synced and local - synced options (e.g. code none MIME types) are synced automatically across instances, while other ones (e.g. keyboard shortcuts) are local as it is expected user might want to have different settings on different instances ...

**Comment by BeecherNetworks** [comment]
I realise it's just a few clicks but the theme in particular is likely to be the same for most people across devices, although perhaps not the fonts (I haven't tried it on a laptop yet). And I don't the the filetypes were synced when I added my Windows install? Again though, it's just a few clicks and a once-off thing, not a big deal. I'm just lazy. :)

Really liking Trilium though, I've been using Joplin for a while but I don't like the single level hierarchy, the reliance on markdown and the sync setup. Trilium bothers me in some ways too but it's much closer to what I'm looking for.
