### ISSUE TITLE
Uncaught Exception: Error: ENOENT, node_sqlite3.node not found in app.asar

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1023]
Hi, using last version trilium 0.42.2 i get an ENOENT error displayed in a window.
I can't copy-paste text, so here is a screenshot:

![Screenshot_2020-05-16_18-39-08](https://user-images.githubusercontent.com/3504393/82127651-d314ae00-97a4-11ea-8bc3-2be283ccc7af.png)

**Comment by zadam** [comment]
Hello, is this an "official" build from the release page or did you perhaps build it yourself?

**Comment by nil0x42** [comment]
It's the official build (trilium-linux-x64-0.42.2.tar.xz)

**Comment by zadam** [comment]
That's very strange - MD5 sum matches mine. Also when I unpack the asar file I can see the sql file being there ... (and I can't reproduce the issue ...)

**Comment by nil0x42** [comment]
I just rebooted my machine, and now it works.... may be some obscure cache was breaking things....

**Comment by zadam** [comment]
Ok, good to hear the problem is solved!
