### ISSUE TITLE
[Question] Migrating from WordPress to Trilium

### ISSUE THREAD

**Issue by ifethereal** [zadam/trilium#1027]
What would be the best way to go about this? I am no JavaScript developer but am okay with basic scripting. Not expecting an easy or complete solution, but would be great to hear some ideas.

From the WordPress end, exporting is not an issue. The WordPress REST API can produce a JSON of all posts. There is also the option to export into an XML file. Both formats seem to include a lot of metadata, which is good.

I am wondering about how much data and metadata it would be possible to preserve during an import to Trilium.

Would it be feasible to create a fake Trilium `.tar` archive of these WordPress posts and try to import that?

- Raw content should not be a huge issue, since the basic format for WordPress would be HTML. At worst I could maybe attempt to turn the WordPress post content into Markdown?
- Tags and categories can probably turn into attributes — I'm thinking relations rather than labels.
- What about other metadata like _publish time_ or _last modified time_?
- For an extra challenge: revision history?
- Images? Personally I am not so concerned about this, since most of what I'm trying to migrate is text.

**Comment by zadam** [comment]
I'm not too familiar with Wordpress but if it can export JSON/XML then it should not be difficult to transform it into ZIP/TAR file which could be imported.

*   content itself should be extracted to HTML files (or Markdown) - can be in directory structure but probably wordpress articles don't have a hierarchy ...
*   meta data and attributes should be converted into special `!!!meta.json` which is stored in the root of tar/zip file. You'll need to reverse engineer a bit from e.g. [demo document](https://github.com/zadam/trilium/raw/master/db/demo.zip)
*   _publish time_ or _last modified time_ probably makes sense to store as labels
*   revision history - in Trilium import/export does not handle revision history so there you would probably have to import revisions as notes.
*   Images and other files should be in the ZIP/TAR as normal files and will be imported ...
