### ISSUE TITLE
createNoteInto cause the screen hang

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#1028]
When I select some words( the first line is a paragraph , not a heading) in note "AAA", then click "copy and paste to subnote", the trilium will delete those words in "AAA" and create the child note.

But the child note name is "new note"(it doesn't apply the first line words) ,and trilium screen is alway stay at note "AAA". I try active other notes, the editor alway stay at "AAA". I need to 
reload FrontendApp to fix it evertime.

If the first line is a heading line , the function will work well.

Win10, trilium 0.42

**Comment by zadam** [comment]
Hello, thanks fro reporting this issue, the bug should be fixed in 0.42.3
