### ISSUE TITLE
How to edit a cloned note without edit original?

### ISSUE THREAD

**Issue by Raphapere** [zadam/trilium#1029]
I want to clone a note to another place but I need to edit just that copy. I do not want to do any change on the "original" note. Is this possible?

**Comment by zadam** [comment]
That's a different concept - "clone" is actually just placing the same note into multiple places in the tree.

But there's a "duplicate note" action which will create a completely separate copy of the original:

![](https://user-images.githubusercontent.com/617641/82342189-9e496680-99f1-11ea-83aa-e11bcc317d36.png)

**Comment by Raphapere** [comment]
Thanks!!
