### ISSUE TITLE
Note contents pane stops updating when switching notes

### ISSUE THREAD

**Issue by safesparrow** [zadam/trilium#1031]
v42.2

Log: [trilium-2020-05-19.log](https://github.com/zadam/trilium/files/4652645/trilium-2020-05-19.log)

It happened a few times now. Restarting the app resolves. Not sure what reproduction steps are. Usually happens after a few minutes of using the UI.

The issue is:
The UI seems to be working, link map, attributes, title are all updating, but the note contents panel is hung at a particular note and I'm unable to make it show anything else.
This is all with text notes. However, selecting a code note in the tree does show its contents properly. Also the 'weight' input from the demo correctly shows up when I open a 'today' note and disappears when other notes are opened.
This is also restricted to the current tab - other (existing & new) tabs work just fine

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, I think it might be the same bug affecting #1030 and #1028 

Could you please try 0.42.3?

Thanks.
