### ISSUE TITLE
Multiple notes side by side in the same window

### ISSUE THREAD

**Issue by en3r0** [zadam/trilium#1032]
It would be great to be able to open multiple notes in the same window. This would avoid a lot of extra duplicate UI features that come with using a whole second browser window.

I imagine the Tree sidebar on the left and Note Info sidebar on the right not getting duplicated. The Note Info section might become "Name of Note" Info, reflecting the current note that is active / selected. The Tree would remain the same.

Thoughts?

**Comment by DimitriyPro** [comment]
Why you don't like tabs for it?

**Comment by en3r0** [comment]
I would like to see notes side by side, so I can reference one while writing another.
