### ISSUE TITLE
Add trilium-sessions & log folder settings in config.ini

### ISSUE THREAD

**Issue by HiFiPhile** [zadam/trilium#1033]
`Version: v0.42.3`

When we run multiple instances of trilium on a linux server, `/tmp/trilium-sessions` folder could be conflict between users due to permission issue.

Even if I can use TRILIUM_DATA_DIR to put data in `/var/lib`, it's nice to be able to put log files in `/var/log`.

**Comment by zadam** [comment]
Hello, I can see how shared session folder could be a problem with multiple instances. One option would be to just put it into the trilium's data dir, this would solve the conflict, but I'm not sure if it makes sense ...

The second question regarding the log folder - isn't this achievable using symling to `/var/log`?

**Comment by HiFiPhile** [comment]
> One option would be to just put it into the trilium's data dir, this would solve the conflict

Indeed it's one solution.

>  isn't this achievable using symlink to /var/log

Yes, but with an option in config.ini we can make it more clean :)
