### ISSUE TITLE
"Add note link" dialog -> "Note" autocomplete list not visible

### ISSUE THREAD

**Issue by safesparrow** [zadam/trilium#1034]
v42.2 (haven't tried with v42.3 yet)

Normally as soon as I start typing in the "Note" input, the autocomplete list pops up.

Here is a screenshot showing me typing something in the "Note" input, but no autocomplete list poping up:
![image](https://user-images.githubusercontent.com/2478401/82637882-a5dd5b00-9bfd-11ea-8756-697fcce27a87.png)

However, I can see the autocomplete does work, because once I type something in and hit 'enter' once, the "best" suggestion is selected. It's just that the UI showing the list is missing.

Logs (happened on 22th in the morning, but I woke the PC up from hibernation, hence attaching 21st logs as well):
[trilium-2020-05-21.log](https://github.com/zadam/trilium/files/4666420/trilium-2020-05-21.log)
[trilium-2020-05-22.log](https://github.com/zadam/trilium/files/4666421/trilium-2020-05-22.log)

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. I can confirm this happens randomly to me as well, but so far I was not able to figure out why. I will keep working on it ..

**Comment by zadam** [comment]
fixed in stable branch.
