### ISSUE TITLE
[web] require is not defined

### ISSUE THREAD

**Issue by Wingysam** [zadam/trilium#1035]
I'm using the :latest tag on docker (pulled image today), viewing in Firefox and Chrome.

When loading Trilium, I see this error:
![image](https://user-images.githubusercontent.com/18403742/82700767-d98ba580-9c3c-11ea-81e7-9b09a250709c.png)

When I use the today button for example, nothing happens. I think the entire frontend scripting system doesn't work if you can't require electron.

**Comment by zadam** [comment]
Hello, this was fixed in 0.42.3, but I checked dockerhub and this release was not correctly uploaded and that's why :latest still had this bug. I reuploaded the image.

**Comment by Wingysam** [comment]
Thank you! 😄
