### ISSUE TITLE
More concise / dense layout of promoted attributes

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#1037]
I realize this might just be me...

... but for me the customizable and 'templatable' metadata of Trilium is a gift from heaven.
because they lend themselves so well for internal structuring, profiling of notes, visual support, and now also retrieval, I rather make extensive use.

thing is, with 6 'promoted' attributes depending on layout opions, easily half of the notebody is already gone. at the same time I feel the attribute field display is rather lavish (size of value-fields; strictly 1 row).

I wonder if there could be a more dense display? this would lend itself to a more extensive use of promoted attirbutes, and I´d suppose to attributes generally.

... and it would for sure help in use cases like mine :-)

thx for considering! oliver

**Comment by zadam** [comment]
Hello, yes, I understand the issue. It's something I have thought about but I did not come up with a satisfactory solution. Anyway for 0.43 I'm working on a big overhaul of attributes and this might come up as part of that ...

**Comment by zadam** [comment]
Here's what I'm working on - promoted attributes are responsibly fitted into the available space:

![](https://user-images.githubusercontent.com/617641/88465748-8bf21a00-cec5-11ea-9f2f-26ca4cb023c5.gif)
