### ISSUE TITLE
Latest Version Does Not Launch

### ISSUE THREAD

**Issue by washere** [zadam/trilium#104]
* Deleted trilium folder in roaming too and reinstalled clean but still does not launch. 

* Tried offline but same problem.

.
![bug](https://user-images.githubusercontent.com/5448047/39024887-8c78ff46-443b-11e8-8f47-dd38247632ca.jpg)

**Comment by zadam** [comment]
I occasionally see this error, but after I click OK I can continue to the application. I'm not sure what causes this, I think it started recently after upgrade to electron 2.0. I'll try to reproduce this. Thanks for report.

**Comment by zadam** [comment]
trilium-data folder is actually in your home directory, so in windows in c:\Users\[username]\trilium-data

**Comment by washere** [comment]
Thanks. Deleting document.db fixed it. Launches into it.

But it is still giving error messages. I deleted the whole trilium-data folder, gives less error. 

But it still gives them on: db changes, some session startups, session exits, etc. App still works.

errors seem to be same, see pic attached here from 2 diff types of situations:

![errors](https://user-images.githubusercontent.com/5448047/39091405-38933ef8-45eb-11e8-8259-30b87265f4bf.png)


BTW, this is my CSS Dark Mode look:

![my dark mode](https://user-images.githubusercontent.com/5448047/39091406-483e6e5e-45eb-11e8-8c33-fb674119282c.png)

Would be nice not to have so many error messageboxes, therwise seems OK, but only been using the latest ver for a few minutes. Needs more testing.
