### ISSUE TITLE
Open image in external editor

### ISSUE THREAD

**Issue by DimitriyPro** [zadam/trilium#1040]
Dear team
Do you know if there is an oppotunity to open image in external editor. It needs to crop, resize and edit captured image.
Thank you!

**Comment by zadam** [comment]
You can download the image locally, edit in external editor and upload again as a new revision of the image note. Currently there isn't a way to make this more automatic unfortunately.

**Comment by DimitriyPro** [comment]
Thank you @zadam !
Could you a little explain about it, please.
I'm interested in Trilium so much)))

**Comment by zadam** [comment]
See e.g. here:

![](https://user-images.githubusercontent.com/617641/82832897-cbe45300-9ebc-11ea-97ac-ab14a7e91072.png)

there's a button to download the image, after you finish your changes there's another button to upload the edited image as a new revision of this image note.
