### ISSUE TITLE
[wish] copying attribute-sets (metadata) from one note to another

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#1044]
[realizing that this might be based on my very personal system, I thought I throw that up nevertheless:]

the **templates system in Trilium** is great, as it allows for assignment of multiple simultaneous templates – and thus **allows for** something that in other systems would be called **a (metadata) 'stamp'.** that is cool.

... then there are **cases** where the economy of cultivating one´s own system (and being as streamlined/efficient as possible) **demands for some attributes to be copied from an existing note to another**. – that is also why many (advanced) DAMs allow for something like that.
– it would be nice to have something likewise in Trilium.

note: I am aware there is – besides 'templating' (which demands a 'step to the side' in terms of extra effort) – the way of doing it by _copying/duplicating_ existing notes. that is why I phrased it as copying attributes (metadata) "between existing notes". – ... simply because in practical use (or in hindsight) one later notices that there already is an existing re-usable attribute-set; or another case: the attribute sets/ontologies meanwhile evolved.

again: it might be very special. but given Triliums vector + affordances it still seems to make sense to think in that direction...

**Comment by zadam** [comment]
I plan very soon (perhaps as part of 0.43) to change the UI for adding attributes and labels - I want it less "clicky" and more textual oriented - so essentially you write `#book #year=1950` with the help of autocompletes. Since this will be essentially a text box, you can easily text-select attributes you want, CTRL-C, then CTRL-V into another note.

**Comment by zadam** [comment]
This has been released in 0.44 so closing.
