### ISSUE TITLE
AGPL license question

### ISSUE THREAD

**Issue by waldenn** [zadam/trilium#1047]
If I were to embed this web app in an iframe inside of own app, would the AGPL influence the copyright of my app (towards the AGPL)? So the two apps run in completely separate processes.

If so, please consider using the GPL instead, so any modifications would still need to be shared, but the web app  can be used in existing works of other people.

Thanks!

**Comment by zadam** [comment]
I'm not a lawyer, so it's hard to answer this question.

The problem with GPL on the web is that modifications don't have to be shared. Imagine Bob forks Trilium and makes his own modifications, deployes it on his own servers and starts offering "Trilium clone as a service". He's not obliged to provide source code to his customers. He's only obliged to provide source code to the people who run the software on their computers (which in this case is only Bob). AGPL was created specifically to cover this hole ...

**Comment by waldenn** [comment]
Hi, thanks for the quick response.

The client-side JS modifications would need to shared in the GPL-case (software is being distributed) and if the client-side code runs in the same process its considered a derivative (and then the whole app would need to be GPL) - as I understand this legally. Why not apply the GPL to the frontend and apply a more liberal license to the backend? From what I see the frontend is done really well and backends are not that special these days (though I could be missing something special here).

The major issue in the current licensing setup is that EVEN IF I would like to contribute and share any modifications made, I would never allow this project to dictate all of my own code licensing. I think many people would feel the same. The license hurts any normal adoption, as it can only be used in the most minimal of use cases, that is if the WHOLE service goes AGPL (and that assumes this is even possible legally in the first place). Do you know _any_ project which has done that outside of the entity that has created that AGPL project?

I think the AGPL license will hurt the project much more than it will help the project moving forward. As the people who take the license seriously will not be able to use it in many cases, and many people who do use it will not really think about the copyright implications of all their service code.

Kind regards.

**Comment by zadam** [comment]
Could you perhaps for context shortly describe the kind of app you'd like to develop where Trilium would be integrated? In my view Trilium is sort of self-contained and it's difficult for me to imagine where this would it would be useful as a component of something larger ...

**Comment by waldenn** [comment]
I am making an non-free encyclopedia web app [Conzept](https://conze.pt) using mainly Wikipedia data.

It uses a variety of other self-contained (embedded) iframe-apps to render special views of that data. See eg. the [link-graph app](https://conze.pt/explore/GNU%20Affero%20General%20Public%20License?l=en&t=link-split&s=true&i=1131681&u=https%3A%2F%2Fconze.pt%2Fapp%2Flinks%2F%3Fl%3Den%26t%3DGNU%2520Affero%2520General%2520Public%2520License) or the Wikidata SPARL query app.

Some of these apps have been GPL-licensed and I have contributed code / shared the fork with the authors in all cases. Some projects are using the MIT-license (like the wtf_wikipedia library), and I am working with that author also to improve the project.

I would like to embed add a note-taking app in the future (other priorities for the moment), and yours technically looks like a good option. However I could never use it in any way I'm using the other embedded apps due to the AGPL license. It would require all the service code would need to be AGPL licensed, which I don't even think is legally possible (as there are many kinds of free licenses in use and probably not all of them are compatible with such a re-licensing) - nor do I want to be thinking about all those things when I embed just one app in the service. If I were able to use the note-taking app, I would really not have any reason to hold on the patches for myself if they were deemed useful for the project. it would just create more and more patch maintenance burden for little to no value.

I understand your reasoning about other companies outcompeting you with your own code, but if me and many of other people are using your app and contributing to it, it will have much more 'cloud  and momentum' than any company can create on its own. Also, why not differentiate the project based on some non-free special feature / support service / saas option? This would allow other projects to use the note-taking feature in their app, and also limit some forms of direct competition. I think this could be a win-win. The frontend needs to be shared under the GPL in all cases anyway(!), and if some backend features are deemed commercially viable would perhaps not released under a free license (for a while or never). The AGPL is in some form already doing the latter, as many people will not be able to use it anyway, so it might not even exist.

**Comment by waldenn** [comment]
I feel the message of this blog [post](https://jessitron.com/2019/10/13/dont-build-systems-build-subsystems/) ("_Don’t build systems. Build subsystems._") is also relevant to this discussion.

**Comment by waldenn** [comment]
Feel free to close this issue if you want. Thanks.

**Comment by zadam** [comment]
Ok, closing, no license change away from AGPL is planned at this time.
