### ISSUE TITLE
Attached file with long name overlap right section

### ISSUE THREAD

**Issue by Nihisil** [zadam/trilium#1052]
App version: `trilium_0.42.3_amd64.deb`

Issue:
![image](https://user-images.githubusercontent.com/475367/83262171-16ccd600-a1ef-11ea-8008-cbe038d726a4.png)

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, it has been fixed.

**Comment by Nihisil** [comment]
Thank you!
