### ISSUE TITLE
Display children summary even when content exists in parent

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#1053]
I reallllly like the fact that Trilium shows children in a parent when the parent is empty:

![image](https://user-images.githubusercontent.com/10717998/83263023-e7d14880-a18b-11ea-9707-4404b95c42a0.png)

It would be nice however to have the option to add text to a parent note and still be able to view the children summary. I often use a parent note to describe or give an overview of what the children notes contain, so it would be very nice to be able to do something like this:

![image](https://user-images.githubusercontent.com/10717998/83263928-58c53000-a18d-11ea-9ef0-1c5169f37c3c.png)

Maybe this is already possible. If so, please let me know so i can be even more impressed with Trilium!

**Comment by zadam** [comment]
Unfortunately this is not possible ATM. 

Interestingly this is how it worked in 0.35 and earlier (IIRC) before the view was replaced with book notes. If the note had not much text, the children were displayed below the text. This was causing some issues though.

I understand why this would be nice, but technical solution would be probably have to be different. Perhaps it would make sense to be able to insert a widget with children overview - similarly how you can include a note.

**Comment by meichthys** [comment]
I could see how it could cause issues when there is a lot of text on the parent node.
I looked at the book note, but honestly i didn't see any benefit to that since it doesn't seem to be any different than an empty parent note with it's child notes fully zoomed in:

Book note:
![image](https://user-images.githubusercontent.com/10717998/83267494-4ef1fb80-a192-11ea-859b-4c08a4a8e27c.png)

Empty parent note with child note zoomed in:
![image](https://user-images.githubusercontent.com/10717998/83267523-5913fa00-a192-11ea-82a9-6bfc142e90ee.png)

I think the "include note" feature may be a good option, but for my use case there would need to be a way to include all children notes and to dynamically add new notes when they are created. It's possible my use case isn't common, if so, we can drop the idea. I'm entirely ok with just browsing the tree instead of having direct links to children notes in the parent note.

**Comment by zadam** [comment]
> I think the "include note" feature may be a good option, but for my use case there would need to be a way to include all children notes and to dynamically add new notes when they are created. 

What I meant is that there would be a new widget which would show all the children, so no need to add them separately and ofc. it would be automatically updated.

**Comment by meichthys** [comment]
Sounds like a welcome feature in my book!

**Comment by zadam** [comment]
In 0.46 children are shown also when there's (little) content.
