### ISSUE TITLE
Drag-drop is broken

### ISSUE THREAD

**Issue by skorokithakis** [zadam/trilium#1058]
This bug report isn't going to be very useful because I just spent a very frustrating hour trying to get Trilium to work, to no avail.

I had two imported images and various notes into the server version (I'm using Firefox on Linux), and had some very odd problems:

I would try to move note A into note B by dragging/dropping the note until the "line in vertical middle" icon appeared, but when I dropped note A, the unrelated note C would instead show up as moved under A.

I tried to move the image into another note but got a "moving cloned note would create circle" message, even though there were no circles and I only had 7ish notes in total.

I would insert one of the images in the note by dragging it and dropping it in the note, which would embed a filename link instead of the actual image. Trying to remove it with ctrl+Z, Backspace or Delete would sometimes not work, and other times would create a state where the entire edit control was frozen.

Ctrl+Z doesn't undo anything anywhere that I could see.

All in all, I was very excited about Trilium being exactly what I wanted, but these bugs frustrated me greatly and I ended up uninstalling it.

**Comment by zadam** [comment]
Hello, sometimes these weird errors show up when websocket is not working because of server misconfiguration. When you open the browser console, do you see some errors showing up there?

**Comment by skorokithakis** [comment]
I did, but I fixed them by letting websockets pass through Caddy as normal. Before fixing this, the UI wouldn't update at all without a refresh, so I think it's a different problem.

**Comment by zadam** [comment]
I went over your issue with drag & drop and I think I know what was the problem - this was a problem when you were dragging note which is not active - which is probably not typical (or rather not tested) but valid case.

You can try 0.42.4 if you want where this issue should be fixed.

Undo (CTRL-Z) on tree operations is not supported. Perhaps sometime in the future, but it's not easy to get this right. CTRL-Z should still work in the editor component.

**Comment by skorokithakis** [comment]
That does fix the issue, thanks! Initially, the UI wouldn't update and needed a refresh, but now everything works, thank you! I will file another issue for the other bug I'm running into.
