### ISSUE TITLE
Text is deleted and caret moved when typing into new note

### ISSUE THREAD

**Issue by sammoth** [zadam/trilium#1063]
Hi, when I create a new text note and start typing into it, after a few seconds the cursor jumps to the beginning of the line and some of the text I entered is deleted. I tried in Firefox and Chromium and the desktop app on Linux and it's the same.

version: 0.42.3 build: 04c573e212db06e1dd60c74707e40f6912c85aab

![output](https://user-images.githubusercontent.com/3324352/83327613-1119d380-a275-11ea-9044-e09a30fe6c62.gif)

[trilium-2020-05-30.log](https://github.com/zadam/trilium/files/4705572/trilium-2020-05-30.log)

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, the bug is now fixed in stable branch.

Weirdly I didn't notice it since I was probably too slow to type out the title before editing the note content. It happens only once few seconds after creating a note.

**Comment by sammoth** [comment]
Thank you for your swift help, and this tool! I'm pretty excited about starting to use it
