### ISSUE TITLE
Self Signed Certificates Despite Being Trusted Do Not Work With Synchronization

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium#1065]
Version: v0.42.3
Log:

```
20:43:06.359 INFO  sync failed: Request to GET https://rpi4-argon:8080/api/setup/status failed, error: Error: unable to get local issuer certificateError: Request to GET https://rpi4-argon:8080/api/setup/status failed, error: Error: unable to get local issuer certificate
    at generateError (/home/solidity/Programs/trilium-linux-x64-server/src/services/request.js:170:12)
    at ClientRequest.<anonymous> (/home/solidity/Programs/trilium-linux-x64-server/src/services/request.js:48:47)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) 
```

I'm using self-signed certificates generated with [smallstep/certificates](https://github.com/smallstep/certificates) which are trusted by my system, as when navigating to the remote host (rpi4-argon) via the browser, or when using curl the certificate is accepted.

I've made sure to install the certificate as a trusted cert on the remote host (rpi4-argon) as well as my laptop but get the above mentioned error.

**Comment by zadam** [comment]
Hi, I'm not 100% sure, but I think that node.js is not using host system trust store.

See this: https://medium.com/trabe/monkey-patching-tls-in-node-js-to-support-self-signed-certificates-with-custom-root-cas-25c7396dfd2a

> ## Solution 1: Disable certificate validation (Don’t do this)
> 
> Setting the [`NODE_TLS_REJECT_UNAUTHORIZED`](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value) environment variable to `0` disables all checks, therefore all self-signed certificates will be trusted. Don’t do this. You are opening yourself to man in the middle attacks. Please, don’t do it. Even inside your intranet network. Just don’t.
> 
> env NODE\_TLS\_REJECT\_UNAUTHORIZED=0 node client.js
> 
> ## Solution 2: Add extra root certificates to node
> 
> Pointing the [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) environment variable to the path to a file with more root certificates (in PEM format) will make node add them to its list of hardcoded certificates.
> 
> env NODE\_EXTRA\_CA\_CERTS=./rootCA.crt node client.js

Second option would be ofc. better.

However these days (with let's encrypt) self signed certificates are not really necessary ...

**Comment by bonedaddy** [comment]
Thanks for the link I'll check it out. As for using lets encrypt, I'm using an internal homelab with no public connectivity outside of an overlay network using nebula, which means lets encrypt would be a PITA because I would need to periodically expose the homelab to the internet every 90 days just to renew the cert.

Much easier to use the homelab CA :joy:

**Comment by bonedaddy** [comment]
Solution 2 worked, thanks

**Comment by tyu1996** [comment]
I hosted my own private server with self-signed cert, it's also unable to sync from my client app with `ERR_CERT_AUTHORITY_INVALID`.

I am no NodeJS developer, is this possible to do the same thing on existing binary client app?

**Comment by kraft-nix** [comment]
I have the same issue, I have a cert signed with my own CA, which is trusted by my devices. Trilium works fine from firefox but when I try to sync it from the desktop client it will fail with `error: Error: net::ERR_CERT_INVALID`.

I have tried adding the ENV variable by running  `NODE_EXTRA_CA_CERTS=./homeserv.pem trilium` (also tried exporting prior to running) but this does not help. I only have access to the electron binary from my packaging system, is it possible to pass the root CA through, or allow the app to use the system's trusted CA store?

**Comment by kraf1nix** [comment]
Yes, I still get the same `ERR_CERT_INVALID` error. Note the electron binary is taken directly from this repository's release.
