### ISSUE TITLE
moveNoteDownInHierarchy issue

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#1066]
When I use moveNoteDownInHierarchy(ctrl+right) to move the note to child postion, will pop up a message "undefined".  in 0.42.4.
It's work in 0.42.3

**Comment by zadam** [comment]
Hello, thank you for the bug report. Yes, it looks like I broke some move operations in 0.42.4 (while trying to fix other issue). Bugs should now be fixed and I'll release them soon.
