### ISSUE TITLE
Question about labels

### ISSUE THREAD

**Issue by msadowski** [zadam/trilium#1067]
Hi!

I've just started exploring trilium and so far I love it! I've read through the documentation however didn't find a clear answer on how to apply labels.

To be specific I was thinking of adding labels to my notes in order to make them more searchable. Let's say I would label the notes with words "navigation", "localization" and a bunch more, according to [Search documentation](https://github.com/zadam/trilium/wiki/Search) I should be able to do:

> @abc - returns notes with label abc

What's not clear to me is how I would add a label for this search to work? I think I've read through all the pages and didn't find a clear answer.

**Comment by zadam** [comment]
Hi, you can add those labels in the Attributes dialog (in the Note actions menu or through `ALT-A`).

When searching then just put `@abc` into the search box ...

However note that this area of the application is currently under a revision, you can see #1041 and #1068 to see some near-future changes.

**Comment by msadowski** [comment]
Many thanks for your answer! I think the main issue I had was not realizing that label can have an empty value field. It seems that if I just input the name for the label it works as I would expect. For the record here is how I was adding them:
![image](https://user-images.githubusercontent.com/6543766/83519414-31979700-a4dc-11ea-8d17-f6390e49206d.png)

I'll close this issue now. Looking forward to your new changes and becoming a full time user!
