### ISSUE TITLE
RFC: attributes UI

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#1068]
Hello, in 0.44 besides search re-work discussed in #1041 I also plan to change the way the attributes (labels and relations) will be defined. Currently, you can add labels and relations only through Attributes dialog which seems to bring slow workflow and takes a person out of flow.

See screenshot of an alternative WIP UI for adding labels and relations:

![](https://user-images.githubusercontent.com/617641/83362460-b5913800-a391-11ea-9d61-cfd32d87e3cd.png)

So the basic idea is that it's just a text field (separate from main content though) where you can just freely type labels and relations (with the help of autocomplete). No dialog needed. You can copy and paste attributes from one note to another with just clipboard.

For now, this will be just preferred alternative and Attributes dialog will stay as it is for the old experience for now.

It's still not clear how to present inherited attributes here but I have some ideas.

What do you think?

**Comment by Nihisil** [comment]
Looking forward for it.

**Comment by PAK90** [comment]
How would you see this working for multi-attributes? I'd imagine it's either multi-defined (e.g. `#a=1 #a=2 #a=3`) or defined with an array (e.g. `#a=[1,2,3])?

**Comment by zadam** [comment]
@PAK90 same as now, you will define the label multiple times, so `#a=1 #a=2 #a=3`

**Comment by lerone-b** [comment]
great!

– would the same approach work for secondary annotations / aka 'side notes' of a note?
( see #527 )

**Comment by jaroet** [comment]
Hello,

I like this new way of showing and editing attributes.
A few remarks. I would like some kind of larger input box (like Excel when
you click on a dropdown icon at the end of the input field) for example 4
rows with on each row only 1 attribute. I like the single line, single
attribute you have now (although now it has to much 'lost space' around
it).

I would prefer having it in the sidebar as a widget but then freely
editable. I do not need to see the attributes constantly as your screenshot
suggests.

For showing inherited attributes I guess you can use alternative colors or
gradients. Might be configurable through CSS also.

Just MHO.

Regards,
JeRoen

Op zo 31 mei 2020 om 22:55 schreef zadam <notifications@github.com>:

**Comment by chncho** [comment]
The interface looks good, and the storage form in the database will not change, isn't it ?

**Comment by zadam** [comment]
Schema in the database is not affected by these changes - attributes will be stored exactly as before.

There will be some changes in how promoted attribute definitions are represented in the schema, but this shouldn't affect anybody.

**Comment by leeyaunlong** [comment]
> Schema in the database is not affected by these changes - attributes will be stored exactly as before.
> 
> There will be some changes in how promoted attribute definitions are represented in the schema, but this shouldn't affect anybody.
How to show relate links ?
Current, my notes will link many other notes. 
the relate link include "relation internalLink" (20 chars) + URI string(assume length is 10 chars) = 30 chars.
if  a note include 5 links, the label input box will fill over 150 chars ( 30 * 5).
It is hard to add other labels in input box.

**Comment by zadam** [comment]
The input box will automatically grow with number of notes. Probably with some upper limit (scrollbar will be shown then).

Regarding the `internalLink` relations (and similar) - I still think about how to show them there - probably these won't be shown by default and only on click, since these relations are only derived from the content and also shown better in the link map...

**Comment by JakeCoxon** [comment]
Will the attributes input always be visible there? I wonder if it's better to hide by default?

**Comment by zadam** [comment]
I'm thinking about adding some expanded so the user can keep it visible or hide it as they want, but not yet exactly sure how to do it ...

**Comment by twh270** [comment]
I agree the existing way of editing attributes takes one out of the 'flow', this looks like it will work much better. Agree with @jaroet that a larger input box / one attribute per line would at least sometimes be nicer. Here's my thoughts on user stories:

1. (MVP) A single line, always visible, that allows space-separated attributes. 
1. Allow quotes around attribute values, e.g. %location="Paris, France". (Bonus: support escaping for quote characters inside the value.)
1. Multi-line support, multiple attributes per line.
1. Collapsible attribute box. Hover over a drop-down arrow / chevron / something to display, click on it to "pin" it open.
1. An attribute that, if present, means "always pin open the attributes for this note".
1. Keyboard navigation (Ctrl-U doesn't seem to be bound to anything?)
1. Custom CSS styling around the entire attribute box and for individual attributes.

I realize that's a long wish list. I've never worked on an Electron app before but might could have a go at a couple of these once you have the basic support in place.

(Also, unrelated, I grew up on a steady diet of science fiction and was probably in my early teens when I encountered The Last Question. Young me was quite surprised at the ending!)

**Comment by lerone-b** [comment]
just to mention / add an observation:
I just realized there is a not too obvious implicit consequence of changing the attributs input UI:
until now the (very helpful) note hover previews were automatically showing all (propagated) attributes.
– as in my case this can take up to 100% of the preview.

I am not sure what is preferable / intended, but wanted to flag that a decision on attribute display for the thumbs/previews is also inherent in such an overhaul.
– and maybe that is a good opportunity to reflect on wanted behaviour here.

**Comment by zadam** [comment]
![](https://user-images.githubusercontent.com/617641/86499973-5490c180-bd8e-11ea-8e71-2340e2691dad.gif)

GIF showing some progress and new features of the attribute view:

*   expandable "owned" and "inherited" attribute view
*   you can click on an attribute which also allows you to edit the attribute in more GUI way without needing to know the syntax
    *   besides that it also shows you list of notes with the same attribute (and value)

**Comment by zadam** [comment]
Functionality described in this issue has been implemented and will be released soon in v0.44 so closing ...
