### ISSUE TITLE
Links cannot be deleted or moved around

### ISSUE THREAD

**Issue by skorokithakis** [zadam/trilium#1069]
I'm using 0.42.5, here's the steps to reproduce this bug:

* Open a new note
* Type @ and select one link and press enter
* Press backspace, left arrow and delete, or anything, really. I can't delete that link at all, the mouse doesn't work, ctrl+Z leads to the link being duplicated

See video below, the editor is basically unusable for me after linking:

![recording](https://user-images.githubusercontent.com/23648/83364497-525fcf80-a3aa-11ea-8276-e5a866665ff6.gif)

**Comment by zadam** [comment]
Thanks for reporting I had to consult in ckeditor/ckeditor5#7357 and it turned out I implemented the plugin wrong but it coincidentally worked correctly until last CKEditor upgrade. Now it should work fine.

**Comment by skorokithakis** [comment]
Thank you, is the fix in the latest Docker image?

**Comment by zadam** [comment]
Fix was not yet released.
