### ISSUE TITLE
How change listening IP address and port?

### ISSUE THREAD

**Issue by agent-kimbley** [zadam/trilium#1070]

**Comment by zadam** [comment]
For server installation host and port can be configured in `config.ini`

**Comment by agent-kimbley** [comment]
yeah,I got it.But I find out another bug,That’s the setup page can’t working with my iPad safari browser after all of manual and docker install documents guide.

**Comment by agent-kimbley** [comment]
yeah,I got it.But I find out another bug,That’s the setup page can’t working with my iPad safari browser after all of manual and docker install documents guide.

**Comment by agent-kimbley** [comment]
I have totally tested  that‘s.The setup page just display nothing of content,Just blank without title and icon.
