### ISSUE TITLE
setup page can’t working with iPad

### ISSUE THREAD

**Issue by agent-kimbley** [zadam/trilium#1071]
I find out another bug,That’s the setup page can’t working with my iPad safari browser after all of manual and docker install documents guide.

**Comment by zadam** [comment]
Do you have some errors from the console or some debug info?

Safari is normally not supported browser since I can't test on it. Chrome and Firefox are tested and recommended (sadly not avaible on iOS AFAIK).

**Comment by agent-kimbley** [comment]
Console is normally output.I guess the setup page can’t working with Ipad.Even I use chrome on Ipad.

**Comment by zadam** [comment]
Chrome on iOS is not a real Chrome, only a chrome-like UI built on webkit. Apple does not allow any alternative rendering engines on iOS.

**Comment by meichthys** [comment]
I can also confirm that the setup page is blank on iOS. Unfortunately I wasn’t able to debug it to find out why.

**Comment by meichthys** [comment]
@zadam Here's the console output from the iOS device:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/10717998/87228687-d70e1800-c370-11ea-83bc-bd28b371a01e.png">

**Comment by meichthys** [comment]
The source of the page shows the following even though javascript is enabled on the iOS device:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/10717998/87228732-163c6900-c371-11ea-80ef-62b5cb180581.png">

**Comment by zadam** [comment]
@meichthys thanks, that helped! Looks like some global variables were not declared correctly and Safari's behavior was less lenient than Chrome or Firefox.
