### ISSUE TITLE
[Feature Request] Deep duplicate / Unlink cloned notes

### ISSUE THREAD

**Issue by Propolisa** [zadam/trilium#1076]
First of all, thanks to the zadam and other developers for an incredible note taking and organization experience. 👏 I looked for a long time for a modern replacement for CherryTree as a pentester and this one is incredible for the purpose.

My request: often in my field (and surely others) we need to generate reports frequently with similar tree / section / contents. It would be great if we could do a deep copy (unlinked from the original template) of some part of the note tree. Saving a note tree as a 'Template' with a name would be a pretty way to implement this, but letting users manually creating a folder [e.g. 'Templates' / 'Reports'] and defining their structures there is also perfectly acceptable. 
Only the deep duplicate (unlinked) functionality needs to be available.

If this is already possible, I would be happy to be corrected as this would make my workflow much easier! 😀

**Comment by zadam** [comment]
Hi, deep duplicate is not supported yet, but it's fairly often requested feature so I will put it on the back log.

**Comment by zadam** [comment]
This has been implemented in stable branch and will be released in 0.45.5 soon.
