### ISSUE TITLE
[issue] cannot scroll To ActiveNote

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#1079]
steps:
1. alt+c collapse all notes
2. ctrl+j : search a note (like debug-page"), then enter
it will expand the left tree, and focus correct note, then show  "debug-page" note panel.
then, the trilium will auto collapse left tree, right note "debug-page" is fine.
3. try to use ctrl+. to scroll to active note again. the trilium no any action.
4. try search another note, the left tree no any actions, the right note will go to correct note.
win10+0.4.2.5

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. It looks like a recent bug, it should be now fixed in stable branch and I will release it soon.

**Comment by leeyaunlong** [comment]
> Hi, thanks for reporting this issue. It looks like a recent bug, it should be now fixed in stable branch and I will release it soon.

0.4.2.6 so fast, thanks.
