### ISSUE TITLE
How do  If I want follow latest version of trilium?

### ISSUE THREAD

**Issue by agent-kimbley** [zadam/trilium#1083]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by agent-kimbley** [comment]
Just git Pull?or additional npm install again?

**Comment by zadam** [comment]
The easiest is to watch the project on github, you'll get email notifications about new versions.

**Comment by voidplayer** [comment]
Are there instructions to compile it? The wiki seems to only show the [server installation](https://github.com/zadam/trilium/wiki/Manual-server-installation)

**Comment by zadam** [comment]
There isn't any guide but if you have a git project checkedout and `npm install`'d then you can trigger `bin/build-linux-x64.sh` (or whatever is your platform) and follow the problems ...

**Comment by agent-kimbley** [comment]
Witch script should be trigger on raspberry?build-server.sh or build-debian.sh
And the act doesn’t hurt my Trilium data,right?

**Comment by zadam** [comment]
You should start with `build-server.sh`, however building on ARM is not tested. There are also some scripts to build docker for ARM here: https://gitea.e9g.rocks/howard/trilium-daily-build/src/branch/master/bin

This won't affect trilium data at all.

**Comment by zadam** [comment]
You should start with `build-server.sh`, however building on ARM is not tested. There are also some scripts to build docker for ARM here: https://gitea.e9g.rocks/howard/trilium-daily-build/src/branch/master/bin

This won't affect trilium data at all.
