### ISSUE TITLE
ctrl + alt + p shortcut isn't focusing the note title field

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#1084]
This seems to have started happening with the 42.6 version

OS is Windows 10

Steps to Re-create:
1. Press ctrl + alt + p to create a new day note

Expected: The title field on the new note should be focused by default

Actual: The title field is not focused, you need to manually click in the field to enter a title for the new note

**Comment by bwat47** [comment]
Actually, I notice that it does seem to very briefly focus the field, and then the focus seems to switch to something else (the tree view?) immediately after

**Comment by zadam** [comment]
Yes, this is a regression in the latest release (cause by fixing a different bug). I have a fix committed, will release soon.

**Comment by zadam** [comment]
Should be fixed in [v0.42.7](https://github.com/zadam/trilium/releases/tag/v0.42.7)
