### ISSUE TITLE
Is it possible to reference a JS frontend function defined in another note?

### ISSUE THREAD

**Issue by twh270** [zadam/trilium#1085]
Example: I have two add-on buttons that both create a new note. I'd like to factor out a `createNote(parentNote, title, content)` function and reference it from the two notes that need it. Is this possible?

**Comment by zadam** [comment]
Hi, yes, this is possible, but not well documented :(

Trilium implements module system very similar and mostly compatible with CommonJS - a module (note) exposes `module.exports` which defines what functionality can be imported. You can require/import the "module" (note) by just including it as a subchild. If you want to reuse it in multiple places, clone it underneath each place where you need it.

You can see how it works in the demo document of the "Task manager" - search for note "attribute changed" and how it uses function "reconcileAssignments" from the identically named child note.

**Comment by twh270** [comment]
I see now, thanks. Documenting for future reference:

Assume a Button note with a Library child note. The Library note defines and exports:

```
async function foo() {}
exports.foo = foo;
```
The code in Button can use it by calling `Library.foo()`.
