### ISSUE TITLE
Unexpected readonly note (Read only text view is shown. Click here to edit the note.)

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1088]
Hi, i'm using trilium 0.42.6

I just created a text note from trilium web clipper, via the `copy selection to trilium` option.
And for some reason. my note is readonly even tough i did not add the `readOnly` label to it.

This message appears on top of my note:
`Read only text view is shown. Click here to edit the note.`, and i must click everytime i want to edit my note.

**Comment by zadam** [comment]
Yes, that's a feature. Loading very long notes into the text editor can take a lot of time so by default they are shown as read only and editable on demand.

For specific notes you can override this behavior by using adding label `autoReadOnlyDisabled`

**Comment by nil0x42** [comment]
Oh, nice feature ! Sounds good to me.
Therefore it might be interesting for the error message to explains such beavior, it's always nice to understand why things happen.

**Comment by zadam** [comment]
You're right, I added link to wiki explanation on the read only notes ...
