### ISSUE TITLE
Error: npm run start-server in Windows 7 

### ISSUE THREAD

**Issue by smelike** [zadam/trilium#1091]
$ npm run start-server

> trilium@0.42.6 start-server D:\workplace\trilium
> TRILIUM_ENV=dev node ./src/www

'TRILIUM_ENV' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trilium@0.42.6 start-server: `TRILIUM_ENV=dev node ./src/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trilium@0.42.6 start-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zadam** [comment]
server version is for linux hosts only.

This does not mean it can't run on windows, but I don't test it on non-linux platforms and there might be some issues (like this one I guess). PRs are welcome.

**Comment by smelike** [comment]
> server version is for linux hosts only.
> 
> This does not mean it can't run on windows, but I don't test it on non-linux platforms and there might be some issues (like this one I guess). PRs are welcome.

I am trying to fix it.
