### ISSUE TITLE
Ctrl-clicking an internal link opens clicked note in two new tabs

### ISSUE THREAD

**Issue by kard32** [zadam/trilium#1094]
Hey there! Using 0.42.7. Just a quick bug - it appears that when I ctrl-click an internal link to another note, that note pops open in two new tabs (instead of one, as it should). This behavior does not occur when I right click on the link then select "open new tab" - in that case, it only opens one new tab. I think this was also happening in 0.42.6. Is there a setting I should change? Thanks!

**Comment by zadam** [comment]
Hello, thank you for reporting this bug! I just fixed it and it will be released soon.
