### ISSUE TITLE
Hide archived notes (from tree) not working (?)

### ISSUE THREAD

**Issue by msbentley** [zadam/trilium#1095]
I have labelled a top-level note in the tree as "archived" - I see it is greyed out. But if I select "Hide archived notes" from the gear menu in the tree, the note is not hidden. Is this expected?

Version: 0.42.7
OS: linux/ubuntu

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. It looks like I mistakenly deactivated the feature recently when doing some performance optimizations. This should be now fixed.
