### ISSUE TITLE
UnRAID Support

### ISSUE THREAD

**Issue by LilTrublMakr** [zadam/trilium#1096]
UnRAID has Docker support built in but from what I can tell, there is no way to use a compose file to create containers. They however use what they call 'templates' which kind of acts like a compose file but more of you define the variables and the end user fills them in. (If I understand them correctly.) 

It looks like it can be pretty straight forward to implement. Here is some reading material that I have found:
https://forums.unraid.net/topic/57181-docker-faq/#comment-566084
https://forums.unraid.net/topic/57181-docker-faq/page/2/#comment-566095
https://forums.unraid.net/topic/36057-noobie-docker-setup-guide/#comment-345882

I definitely would like to see this to be able to be ported to UnRAID. I have been using Trilium to make documentation notes for just about everything I have been doing lately.

**Comment by Ricostyle21** [comment]
There is now a CA template.

Easy to install.

**Comment by LilTrublMakr** [comment]
I saw that. Thank you!
