### ISSUE TITLE
Recent changes has no order by time

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#1099]
Recent changes has no order by time

![snipaste20200609_161416](https://user-images.githubusercontent.com/19405648/84123479-78513800-aa6c-11ea-80d4-21056b14ed05.png)

**Comment by leeyaunlong** [comment]
## for example
### The note "01 - Monday" show at  first record 6/9

![snipaste20200609_162256](https://user-images.githubusercontent.com/19405648/84124374-b7cc5400-aa6d-11ea-8fcc-a8e697d4ed7e.png)

### The note also show at tail of 6/9 

![snipaste20200609_162321](https://user-images.githubusercontent.com/19405648/84124371-b733bd80-aa6d-11ea-934d-23074379a093.png)

### but the note change history show: 6/9 just modify one time.

![snipaste20200609_162346](https://user-images.githubusercontent.com/19405648/84124362-b438cd00-aa6d-11ea-8827-0f689c9f0774.png)

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. I refactored the code and now I believe there shouldn't be issues with the sorting.
