### ISSUE TITLE
"Datetime" type promoted label

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1103]
I'd love to see the possibility for a "datetime" type of promoted label (a "date" option is already available). 

Use case: I want to keep a daily journal, registering my day activities by creating various subnotes under each day, with varying templates like "meeting", "trip", "labwork". 
If I could add a "datetime" promoted label to these subnotes, it would be possible to completely situate these notes chronologically throughout the day.

Something for an upcoming release?

**Comment by BeatLink** [comment]
Would love to see this feature implemented. Is there any timeframe?

**Comment by zadam** [comment]
Date & Time is in 0.61
