### ISSUE TITLE
Server-installation on shared hosting - possible without dependencies?

### ISSUE THREAD

**Issue by tomthe** [zadam/trilium#1105]
I was not able to test this: Is it possible to install and run the server as described here:
https://github.com/zadam/trilium/wiki/Manual-server-installation
without installing the dependencies? Where would it fail?

I ask because I would like to install trilium-server on a shared-hosting provider without the possibility to install the dependencies with sudo apt install.

**Comment by zadam** [comment]
I'm not sure if sqlite needs to be compiled or not. No sqlite means no trilium at all. But then again I'm not sure about this one.

Other dependencies are for image support so generally saving images would fail. However for normal usage you should use packaged installation - https://github.com/zadam/trilium/releases/download/v0.42.7/trilium-linux-x64-server-0.42.7.tar.xz

That one has everything built-in and you don't need to install any dependencies. Just unpack and run `trilium.sh`

**Comment by tomthe** [comment]
Thank you very much!
I just tried the packaged installation but it failed because my glibc is outdated. I will probably change my hosting provider, as my node.js is also older than 10.5 and the provider won't update.

And thanks again for this great piece of software! I will probably move my tens of thousands notes mindmap to trilium.

**Comment by tejasvi** [comment]
@tomthe May I ask, which provider are you using, and how are you handling database storage?

**Comment by tomthe** [comment]
@tejasvi I don't have trilium running on a server yet. I will use either Netcup or Uberspace or Hetzner probably.

**Comment by mlthlschr** [comment]
> @tejasvi I don't have trilium running on a server yet. I will use either Netcup or Uberspace or Hetzner probably.

I am currently running trilium on Netcup webhosting without any problems. Plesk is able to resolve and load all dependencies required for `start-server`.
