### ISSUE TITLE
Updating Included Note

### ISSUE THREAD

**Issue by raytracer** [zadam/trilium#1106]
I have a question regarding updating/rerendering included notes. I have a note that consists of a table where one column contains prices. The last row contains a included note that shows a render note which renders a html note, which in turn has a frontend script to sum up all the prices and render it to the html note.

In principle it works exactly as intended, but currently i have to reopen the note every time i make a change to see the changed sum. Is there a way to rerender the included note on a change? I experimented with all kinds of combinations of "runOnNoteChange" but could not get it to work.

(Version 0.42.7)

![summation](https://user-images.githubusercontent.com/1621631/84439642-e3e80080-ac38-11ea-8360-d90d4512e573.png)

**Comment by zadam** [comment]
Hello, I added frontend API method to be able to force refresh the note's included boxes:

```javascript
api.refreshIncludedNote(noteId);
```

However then I realized this is not all - you need also to detect the change to be able to trigger this. I see you experimented with `runOnNoteChange` but that's unfortunately backend-only event and does not work on the frontend. I've been thinking about how to observe these changes to be able to trigger the update and the best I've been able to come up is to define an invisible custom widget:

```javascript
const TPL = `<div style="display:none;"></div`;

class UpdateWidget extends api.TabAwareWidget {
    get position() { return 100; }
    
    get parentWidget() { return 'center-pane'; }
    
    doRender() {
        this.$widget = $(TPL);
        return this.$widget;
    }
    
    async entitiesReloadedEvent({loadResults}) {
        if (loadResults.isNoteContentReloaded(this.noteId)) {
            for (const includeNoteRelation of this.note.getRelations('includeNoteLink')) {
                api.refreshIncludedNote(includeNoteRelation.value);
            }
        }
    }
}

module.exports = new UpdateWidget();
```

See https://github.com/zadam/trilium/wiki/Custom-Widget for some details.

Having said that using scripts for essentially formula support in tables seems very heavyweight.

Recently I've been thinking about integrating some smart table support - e.g. https://bossanova.uk/jexcel/v4/ which allows you to work with tables like in (limited) excel.
