### ISSUE TITLE
Include note API?

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1109]
Is there a way to create "[include notes](https://github.com/zadam/trilium/wiki/Text-notes#include-note)" via the API?

**Comment by zadam** [comment]
Include note in effect is only a special tag (plus derived relation) so you could just use the `note.setContent(awat note.getContent() + '<section ...'))`

to add the included note. You can see the actual special tag with Note actions -> Show note source ...

**Comment by wwwald** [comment]
Nice - thanks for that.
And apologies - I should have had the reflex to check the note source first and dig in... Quite new to this, still finding my way in Trilium and the API.
