### ISSUE TITLE
Promoted label clicked value doesn't stick

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1112]
I'm on Trilium 0.42.7.
I have a template page with a promoted text label "project", to be filled out with a project name.  I've used this on a number of pages now, and I get a dropdown with previous values when clicking the "project" input field. 

The issue: clicking one of these previous values from the list seems to fill the label value, but clicking away from and back to this note shows an empty "project" label again. So the chosen value wasn't really saved, apparently.

I don't see any error messages in the logs - dev console stays silent, the backend log simply does not show any PUT operations for the attribute (it does when I actually _type_ the project name).

**Comment by zadam** [comment]
Hello, this sounds very much like #699 which was very recently fixed and is available in 0.43.0-beta

**Comment by wwwald** [comment]
Duplicate of #699 
You're completely right. Just installed the beta, thanks!
