### ISSUE TITLE
Rendering SVG images

### ISSUE THREAD

**Issue by lluchs** [zadam/trilium#1114]
Currently, SVG images are shown as text files:

![image](https://user-images.githubusercontent.com/516527/84799960-52dca500-affd-11ea-8d8f-c1daa8979b60.png)

...which is not very useful. It would be nice if they could be rendered just like PNG or JPG images.

I see that there are some references to SVG images in the code, so maybe I'm just doing something wrong?

Trilium version: 0.42.7

**Comment by zadam** [comment]
Hi, thanks for reporting this problem, it has been fixed. SVG was not recognized as image and imported as "file". 

Fix will not work on existing SVG notes, it will be necessary to import those again.
