### ISSUE TITLE
Is there a way to get "Edited notes on this day" widget back

### ISSUE THREAD

**Issue by idelem** [zadam/trilium#1115]
I upgraded recently and noticed that the widget is removed from day notes. Personally I find this feature quite useful so I'd like to know if there's any plan or motivation to put it back in future versions. If that's not preferable, can you perhaps release it as a custom widget? Any guide or help on that is appreciated.

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. It looks like the widget was just forgotten to be included into layout during the 0.41 redesign, I now put it back.
