### ISSUE TITLE
[Feature request] Add timestamp and fold/unfold features in notes

### ISSUE THREAD

**Issue by The-Inamati** [zadam/trilium#1116]
Hi,
I really love trilium but there are two features I need for work that are keeping me from taking the leap. I need the ability to add timestamp to the text at any time (like the F5 feature in notepad) and also I need to be able to fold and unfold text.

**Comment by zadam** [comment]
Hi,

> I need the ability to add timestamp to the text at any time (like the F5 feature in notepad

There's `ALT-T` shortcut which adds timestamp.

> I need to be able to fold and unfold text.

Can you go into more detail what this should be?

**Comment by Raphapere** [comment]
I think what @The-Inamati wants is the possibility to hide/unhide some part of text in a note with a click.
Something like this:
![Trilium fold unfold](https://user-images.githubusercontent.com/20495934/85131803-11c7d900-b227-11ea-9766-330fd123c433.gif)

This would be really useful!

**Comment by The-Inamati** [comment]
Yes. Exactly like that.

**Comment by The-Inamati** [comment]
Closing this feature request. It has been too long and I changed to Obsidian
