### ISSUE TITLE
text not selectable when a note is included

### ISSUE THREAD

**Issue by voidplayer** [zadam/trilium#1117]
v0.42.7

Is there a reason for this?

My use case:
I need to copy and paste text all the time

You cant search Protected notes, so i created a root note where i include every child note so i can ctrl + f all the child notes

But when notes are included, you cant select the text

It feels like such an random limitation :(

**Comment by zadam** [comment]
Hi, this is coming from CKEditor which is used as an editing component. I opened an issue (ckeditor/ckeditor5#7468) to get some better understanding why is this the case.

**Comment by voidplayer** [comment]
Thank you for followup this problem upstream :)

**Comment by zadam** [comment]
Based on info provided in [ckeditor/ckeditor5#7468](https://github.com/ckeditor/ckeditor5/issues/7468) I was able to fix it in stable branch.
