### ISSUE TITLE
export + print do not work (on OSX)

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#1118]
hey,

at least on my side and with an OSX install it seems export and print both do not work any more.
– could this be a re-enty of older bug?

thx for any hints + feedback!

Trilium 0.42.7 | OSX 10.14.6

**Comment by zadam** [comment]
Hi, can you give more details on each problem?

**Comment by lerone-b** [comment]
hey zadam, thx for quick response!
I have to 'backtrack' on the 'export' problem. it now works - I don´t know what happened inbetween. before it would just be a 'no show', i.e. meaning the panel with the different export options wouldn´t even appear (and I tried several times, restart etc. :-}).
– but now it does work. so that is good news!

but on print it is still the same: hitting the shortkey simply nothing happens. – also
a)  I am not aware there is another way to print than via shortcut
b) I tried re-assigning the print shortcuts

**Comment by zadam** [comment]
It looks like handling of keyboard shortcut for printing was broken - this was fixed.

However it should still be possible to trigger printing through menu:

![](https://user-images.githubusercontent.com/617641/85182698-be3aa700-b289-11ea-87e6-fdfdb6c33436.png)

**Comment by lerone-b** [comment]
thx, zadam.

this helps to know! (even though I should have found this on my own, I guess)
