### ISSUE TITLE
Remember zoom level when notes dont have content and show children

### ISSUE THREAD

**Issue by voidplayer** [zadam/trilium#1121]
v0.42.7

When a note doesn't have any content, it displays its children with a small zoom level

If you set a different level and click in another note, you lose the zoom level. I would hope it would remember it forever, but at least, it would be nice if it remembered for the session

The work around is leave a tab open with the desired zoom level :)

Thanks!!!

**Comment by netnem** [comment]
Make sure the bookZoomLevel label attribute doesn't meet your needs if you like the zoom level to be the same every time you load that note.

**Comment by voidplayer** [comment]
```@bookZoomLevel=1``` worked thanks!

**Comment by zadam** [comment]
Zooming concept has been reworked a bit in 0.46, but the settings is now always remembered so closing ...
