### ISSUE TITLE
[Bug] CRC error on Markdown Export

### ISSUE THREAD

**Issue by sharifkhalladi** [zadam/trilium#1122]
When exporting a note and its descendants to markdown, the resulting archive contains a corrupted .md file (CRC error). When extracting the archive with 7zip it seems the last bit of the .md file is cut off. When using native Windows 10 extraction it refuses to extract the .md file at all. All the images are archived and extract just fine. 

When exporting just the note without its descendants, it exports the .md file without any issues. 

The Trilium log files do not display any errors and show the task as succeeded:

```
23:07:04.673 INFO  GET /api/notes/yUxLew36y8DM/export/subtree/markdown/1.0/rJKdrx803T?1592687224670 
23:07:04.675 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"rJKdrx803T","taskType":"export","progressCount":0} 
23:07:04.926 INFO  Sending message to all clients: {"type":"task-succeeded","taskId":"rJKdrx803T","taskType":"export"} 
```

This is on version 0.42.7 (Windows)

**Comment by zadam** [comment]
Hello, thank you for reporting this issue. I'm wondering if it might be caused by some asynchronicity related issue since normally I don't see such behavior.

If you try to export the same note subtree again, is the exported ZIP again broken?

**Comment by sharifkhalladi** [comment]
Yes, same issue with the second export.

**Comment by zadam** [comment]
Interesting, that would mean it should be reproducible. I will look into this.

**Comment by RahulHP** [comment]
This bug still exists in version 0.43.1 (Windows 10). Even the second export had a broken ZIP. 
File structure
```
Note1 #An empty note, just a folder
- File1
- File2
- File3
- File4
- File5
- File6
```
On trying to export Note1 as markdown files, 2 files had a `CRC failed` error, 3 files had a `Data error` error and 1 file was exported correctly. The 5 error files had the last few characters missing.

**Comment by Tenebrous** [comment]
@zadam Any luck with this? Exports still create a problematic ZIP file with CRC failures & Data errors.

**Comment by Tenebrous** [comment]
@zadam Sorry no, I'm using the docker container on Linux.  I'll try and extract some ZIPs with non-sensitive info.

**Comment by lpd743663** [comment]
Hi   @zadam 

I encountered the same problem on  `trilium-windows-x64-0.45.6`  and  `trilium-windows-x64-0.45.7`

[export-test.zip](https://github.com/zadam/trilium/files/5732787/export-test.zip)
[document.db.zip](https://github.com/zadam/trilium/files/5732788/document.db.zip)

**Comment by zadam** [comment]
@lpd743663 thanks, but the ZIP file seems to be just fine:

```
$ unzip -t export-test.zip 
Archive:  export-test.zip
    testing: !!!meta.json             OK
    testing: export-test.html         OK
    testing: navigation.html          OK
    testing: index.html               OK
    testing: style.css                OK
```

**Comment by Tenebrous** [comment]
@zadam I started up a new instance using "Open in GitPod" option, and immediately exported the root node giving the .zip attached here.
[root.zip](https://github.com/zadam/trilium/files/5737244/root.zip)

**Comment by lpd743663** [comment]
> @lpd743663 thanks, but the ZIP file seems to be just fine:
> 
> ```
> $ unzip -t export-test.zip 
> Archive:  export-test.zip
>     testing: !!!meta.json             OK
>     testing: export-test.html         OK
>     testing: navigation.html          OK
>     testing: index.html               OK
>     testing: style.css                OK
> ```

Yes， the ZIP file is fine : I can import it into other trilium databases and the data is all intact.

However, on Windows 10

 ```
7zip        ❎️ The extracted content is incomplete
Winrar      ❎️ The extracted content is incomplete

Bandzip     ✅️ prompts "The extracted file size and the archive header information are different", but the extracted content is complete
 ```

**Comment by zadam** [comment]
Yes, it's pretty weird, ZIP files work just fine on linux and pass all checks, but on windows they fail in most file archive applications.

**Comment by chdh** [comment]
This error occurred because a string instead of a buffer was passed to `ZipFile.addBuffer()`. 
see https://github.com/thejoshwolfe/yazl/issues/66#issuecomment-896921865

**Comment by zadam** [comment]
I believe ZIP issues have been resolved a while ago.
