### ISSUE TITLE
[Bug?] html element in title is rendered in tree

### ISSUE THREAD

**Issue by idelem** [zadam/trilium#1127]
I use version 0.42. When I typed `full width <hr>` in title section, the document tree looks like:

![image](https://user-images.githubusercontent.com/25763288/85510411-dc0d6080-b629-11ea-8316-612ce61d1a56.png)

Not sure if this is the intended behavior. 

And, as expected, `<div style="color:red">red</div>` gives:

![image](https://user-images.githubusercontent.com/25763288/85510662-46be9c00-b62a-11ea-91a9-d2dba9d97bed.png)

I think it's useful in some cases. I'm fine with that staying as a feature, but maybe with some limits.

**Comment by zadam** [comment]
Hi, this not expected and is actually a bug. Thanks for reporting this, it has been fixed.
