### ISSUE TITLE
Feature request - Option to disable authentication

### ISSUE THREAD

**Issue by achaussier** [zadam/trilium#1132]
Hello,

First, thanks for this tool.

It could be useful to have an option to disable authentication completely, using environment variables or config key.

I use Keycloak to manage SSO for all my services, and I can't integrate Trilium properly (or I don't see how do that ;)).
In my use case, I prefer have no authentication on Trilium and delegate it to a gatekeeper in front of the service, capable to do the link with the provider and add additional restrictions.

Because Trilium has a single user approch, this method seems more suitable than add a more complicated link with an authentication provider.

What do you think about this request ?

**Comment by luketainton** [comment]
I also like this idea. It could be worth allowing header authentication, so Gatekeeper can pass the username of the authenticated user to Trilium via a header (`X-Forwarded-User` maybe?).

**Comment by zhdenny** [comment]
+1 on this request. I too use Single-Sign On (Authelia) and would prefer to have the OPTION to remove authentication from Trilium.

**Comment by jrruethe** [comment]
+1, I also use Authelia and I am the only user. I would also prefer an option to remove authentication.

**Comment by zadam** [comment]
Hello, this has been implemented in master and will be released in 0.44.

To disable authentication, you'll need to put the following into the `config.ini`:

```
[General]
noAuthentication=true
```

https://github.com/zadam/trilium/wiki/Server-installation#disable-authentication

**Comment by achaussier** [comment]
Thanks for this feature
