### ISSUE TITLE
[Enhancement]Configuration option for offline image download

### ISSUE THREAD

**Issue by mursilsayed** [zadam/trilium#1134]
As part of #765, any image data is automatically downloaded so that it can be viewed in offline mode. This is good implementation but it will be great if there can be a configuration/option for this behavior.
This configuration option will allow the user to keep the db as compact as possible with text data.

**Comment by lilanze** [comment]
when we use phtoto gallery, just want use the markdown url, the whole note is text data, but now it will auto download the img from the url.

**Comment by zadam** [comment]
This is now configurable in the Options:

![image](https://user-images.githubusercontent.com/617641/182671424-569a0358-f0a0-4756-b577-ac985b79331b.png)
