### ISSUE TITLE
Evernote import fails on some images

### ISSUE THREAD

**Issue by nhendin** [zadam/trilium#1136]
I am seeing some similar issues to issue #288 --- only some enex files import and others seem to hang Trilium when used from the web interface.

I have attached one that fails. I am running Trilium (0.43.1) on docker hosted on ubuntu 18.04 LTS, and see time out errors, as well as some errors in the logs seeming to indicate missing libraries for images in the container.

**Workaround:** was to use the windows version of Trilium and sync back to the server -- the windows version imported these correctly.  There were other import issues, unrelated, but I'll file a separate issue for those.

With some other small workarounds I was able to get ~500MB of Evernote notes migrated. **Goodbye Evernote!** 

Mostly what I did was reduce the size of some notebooks by splitting them into years (I've been using it since 2009) and then categorizing others to keep the file sizes down.  There were some notes that imported strangely --- I'll file a separate issue for those.

Thank you for the amazing bit of software!  Loving it so far.  It fits how I mentally organize information and has a lot of features I think I will grow into over time. 

Best regards.

--Neil.

Logs:
[docker-container.log.gz](https://github.com/zadam/trilium/files/4842878/docker-container.log.gz)
[trilium-2020-06-27.log.gz](https://github.com/zadam/trilium/files/4842879/trilium-2020-06-27.log.gz)

Evernote files:
[fails.zip](https://github.com/zadam/trilium/files/4842880/fails.zip)

**Comment by zadam** [comment]
Hi, I suspect that the source of the problem are the minifying binaries which are platform dependent. This was used to attempt to squeeze the image as much as possible for storage. However these native binaries are causing issues so I removed them from master branch.

Thanks for reporting this.
