### ISSUE TITLE
Some imported HTML notes format over the Trilium UI causing it to be hard to use

### ISSUE THREAD

**Issue by nhendin** [zadam/trilium#1137]
Runnnig Trilium 0.43.1 in docker container hosted on Ubuntu 18.04.

I've just completed migrating from Evernote, and had a handful of notes where the formatting got really strange. I suspect poorly formatted HTML in the note itself, but they overlay over the Trilium UI in such a way that you can not  access most of the UI --- so import with caution, and have a way to delete the imported notes via another means before testing. What I did was expand enough notes that the note tree is visible below the overlay and be able to select another note to close this one.

I have attached a screnshot and 2 misbehaving notes as an enex file (no problem with sharing these, no personal info should be in them).  Enex file is zipped per github upload policy. I am happy to provide logs, but I didn't think they would be as useful in debugging a display issue such as this one. Please let me know and I can get them. 

[ProblemNotes.zip](https://github.com/zadam/trilium/files/4842949/ProblemNotes.zip)
![Screenshot from 2020-06-28 13-07-38](https://user-images.githubusercontent.com/3143787/85957282-f05e9f80-b940-11ea-82e9-5091ee011503.png)

**Comment by zadam** [comment]
Hi, yes, that's a problem. I just committed a fix which will sanitize HTML before importing it to Trilium which should strip out all script elements and most of the styling.

**Comment by nhendin** [comment]
Awesome, Thanks!   If I may ask, what is the process by which the docker
image on docker hub gets updated? More specifically when should I do a
docker pull and test it out?

Thanks again for the great tool. I think the reason I like it is that fits
the way I organize my thoughts, a tree structure with lots of links between
things.

--Neil.

**Comment by zadam** [comment]
docker image gets updated as part of release process. These changes have been made in master branch which is rather far from release though ...
