### ISSUE TITLE
icon to extend the note tree is top of the notes on the bottom of the box

### ISSUE THREAD

**Issue by voidplayer** [zadam/trilium#1138]
![Screenshot from 2020-06-29 18-13-56](https://user-images.githubusercontent.com/4019910/86030240-81627300-ba34-11ea-9046-0de1cd3b92e0.png)

Its not very important detail, but its a little annoying because its on top of the icon and you cant directly see if there are subnotes

**Comment by zadam** [comment]
Yes, that's unfortunate limitation. Better UX proposals are welcome :-)

**Comment by voidplayer** [comment]
How about making it float to the right instead? Or not making it float at all

The good thing about making it float to the other side is that you can make the column bigger if something big is in there. 

Same thing probably applies to the extend right column, although i havent had any problem with that one :)

**Comment by zadam** [comment]
Yes, I originally wanted to have them floating on the right side (for left column) but that's not easy, IIRC it was because the button is absolutely positioned relative to window.

**Comment by voidplayer** [comment]
I see

Theres a button with a gear (tree settings) on the right of the same column. Maybe theres a hint of how to do it there?

**Comment by voidplayer** [comment]
Yeah, i see the problem, you want to the button outside of the wrap-tree because you want the button to show when you collapse the tree (unlike the tree settings gear button)

One solution is to have the button on the note side, which of course gets on top of the note text itself (which already happens anyway when hide the tree with the current position fixed)

Another would be to have two buttons. Having an extra button inside the wrap-tree and hiding the fixed one when the wrap-tree is open

And a third one would be to move the buttons somewhere else where they dont have the chance to sit on top of content :)
