### ISSUE TITLE
Using search to organize and move notes

### ISSUE THREAD

**Issue by vilim** [zadam/trilium#1140]
Thanks a lot to the developer(s), I love this knowledge management system!
In Trilium 0.42.5 when searching the test results are a list of links. I could not find a way to use this interface to organize the notes (move them to another parent note) or apply attributes to multiple found notes. Am I missing something or is this not possible right now?

**Comment by zadam** [comment]
Hi, yes, search is quite limited in the sense that there isn't much what you can do other than open the results.

Search results can be saved into "saved search", which will then allow you to e.g. copy the notes into clipboard.

I plan larger search UI overhaul for later this year so things might change then ...

**Comment by zadam** [comment]
Search now provides "actions" which can be applied on the results.
