### ISSUE TITLE
[Feature request] add 2 quick create note method

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#1143]
1. quick add a note to trilium with cmd or some api call (like use alfred to add a note)

2. in jump search or add note link dialog, add quick add new note function
for example :
I input the word "nobody", but nothing be found. 
then I can direct create it with shortcut or click button at dialog, I don't need to leave the dialog.
![snipaste20200701_083331](https://user-images.githubusercontent.com/19405648/86190422-e7efaa00-bb76-11ea-8bb1-c4d487e5d250.png)

**Comment by zadam** [comment]
Released in 0.44.4.

More details in #1237
