### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by AquilaFasciata** [zadam/trilium#1150]
Alright, second issue this week, I apologize (I am new). I am currently running Version 0.43.1 on Ubuntu as server. I'm using Let's Encrypt with Apache, and I'm using it behind Cloudflare. I trimmed my log to the problem:
```
03:44:02.359 INFO  JS Error: Error when calling POST notes/vKzMcGzBPqzM/link-map: error - Bad Gateway
Stack: logError@https://notes.mrzach.org/app/services/ws.js:29:20
throwError@https://notes.mrzach.org/app/services/toast.js:87:8
error@https://notes.mrzach.org/app/services/server.js:119:30
```

This usually happens after a few minutes of using Trilium with no issues. Thanks!

EDIT: After waiting a few minutes and refreshing, Trilium loads fine again.

**Comment by zadam** [comment]
502 Bad Gateway is not used by Trilium, it's usually used by proxy to indicate network or other kind of error ...
