### ISSUE TITLE
Checkbox with internal link turns into bullet point

### ISSUE THREAD

**Issue by kb173** [zadam/trilium#1151]
I like to use checkboxes with links to other notes to plan my day. However, when I add a checkbox and the only text of that checkbox is the internal link, it turns into an unordered list bullet (•) when switching to another note and back.

This is pretty easy to reproduce:

1. Add a checkbox
2. Add an internal link (Ctrl+L)
3. Switch to another note
4. Switch back
5. Instead of "[ ] Internal Link", you have "• Internal Link"

This only happens when the checkbox is immediately followed by the internal link. If there is some other plain text before the link, the checkbox remains intact. It also only happens with internal links (not external ones), which is why I assume this is an issue with Trilium, not CKEditor. 

Version: v0.43.1 release

**Comment by zadam** [comment]
Hello, thank you for reporting this issue. I can confirm this is happening on my side as well.

The reason there's a difference in behavior between internal link and external link is that the external link is sort of ordinary HTML link but internal link is actually small inline widget (at least the "reference link" variant). But I don't see why this should not work, IMHO it's a bug in CKEditor that it somehow does not support widgets in a list or something. I will need to go deeper on this.

**Comment by kb173** [comment]
True, that does sound more like an issue in CKEditor then. Thank you for taking a look at this!
