### ISSUE TITLE
FR: Create dated note in the future?

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1152]
Hi

Is it possible to create a dated note (similar to `today`) but set a future date or a past date with a button or a shortcut?

thanks

**Comment by zadam** [comment]
Hi, the easiest way is to use a calendar widget (by default present on other day notes) just by clicking on future date.

But yeah, it's been on my roadmap for a long time to make this more accessible.

**Comment by gerroon** [comment]
Why not add the cal widget to the regular notes at least?

**Comment by zadam** [comment]
The calendar widget is accessible from anywhere since redesign.
