### ISSUE TITLE
Heading 1 has disappeared

### ISSUE THREAD

**Issue by nigelsim** [zadam/trilium#1156]
After upgrade from Trilium 0.43.1 to 0.43.2 the Heading 1 has gone missing both from the style selector, and from any document that previously used it. This was installed from the Docker 0.43-latest image

![missing-heading1](https://user-images.githubusercontent.com/2869/87773772-fb815d00-c866-11ea-84e2-286aa1ae03a4.png)

**Comment by zadam** [comment]
Yes, this was done intentionally. Semantically the note title is the H1 (even though it is not represented as such). The distinction becomes important when handling imports/exports.

I understand this can cause some annoyance with existing headings though :-/

**Comment by nigelsim** [comment]
Fair enough. It does make sense thinking about how markdown pages work too
(which I guess is based in the same semantics).

This might be worth a note in the release notes though. I just had a quick
search and couldn't see it.

Thanks for all the hard work. It's really appreciated.

**Comment by Wingysam** [comment]
I'm still on 0.43.1, and have dozens  of H1s. Is there a way to automatically migrate all H1 to H2, H2 to H3, etc? I think I have some H6, so those will have to become plain text.
