### ISSUE TITLE
Share a note with a public URL

### ISSUE THREAD

**Issue by regomne** [zadam/trilium#1158]
I know multi-user support is not possible right now, but how about sharing?
With sharing feature, I can create a public URL for one note so that anyone who knows the URL can read it.

**Comment by rmdes** [comment]
That would be so useful, having some sort of "token" that allow the note to shared publicly and even the ability to configure when the public share should be terminated, rendering the token invalid to access the note...This is the single feature I miss the most :/

**Comment by zadam** [comment]
This is currently being worked on.

**Comment by rmdes** [comment]
Great News, thanks for the quick reaction !

**Comment by sigaloid** [comment]
This has been implemented in v0.49.0-beta release: https://github.com/zadam/trilium/wiki/Sharing

**Comment by meichthys** [comment]
@regomne @zadam I believe this can be closed.

**Comment by regomne** [comment]
thanks!
