### ISSUE TITLE
Pasting base64 image from Google Keep export hardlocks Trilium Notes

### ISSUE THREAD

**Issue by Firehawke** [zadam/trilium#1159]
Trilium Notes 0.43.2 on Windows

I used Google Takeout to export a bunch of notes so I could migrate them into Trilium Notes, and I hit a problem with the one note that had a picture in it. I didn't realize the picture was included as base64 in the HTML, so when I did a copy/paste into Trilium Notes, the client hardlocked.

I eventually figured out to save the picture to disk, then copy/paste it in and that worked fine. The log definitely shows where the point of no return was, though.

**Comment by zadam** [comment]
Hi, thanks for the report. When encountering inline base64 images, Trilium attempts to parse them out and save them as image note. I guess this is the point where things fail.

Could you look into the HTML file and find the point with the base64 image and put an excerpt here? It doesn't have to be whole image, just first 100 bytes or so of the \<img tag 

Alternatively, if this particular HTML file is not too sensitive it would be great if you could send it to zadam.apps@gmail.com but of course I will understand if that's not possible ...

**Comment by Firehawke** [comment]
Sincerely sorry for delay on responding to this.

I'll get that for you in a bit tonight.

**Comment by Firehawke** [comment]
[2020-03-03T13_09_50.250-07_00.zip](https://github.com/zadam/trilium/files/4977389/2020-03-03T13_09_50.250-07_00.zip)

Here's one example. I removed some personal text I was using while researching, but the picture is intact.

**Comment by Firehawke** [comment]
[2020-03-03T13_09_50.250-07_00.zip](https://github.com/zadam/trilium/files/4977389/2020-03-03T13_09_50.250-07_00.zip)

Here's one example. I removed some personal text I was using while researching, but the picture is intact.

..and somehow I managed to actually NOT upload this. Let's fix that.

**Comment by zadam** [comment]
Hi, thanks for help, I located the bug and fixed it in stable branch.
