### ISSUE TITLE
[Request] Editing the inherited attribute's values

### ISSUE THREAD

**Issue by terra9** [zadam/trilium#1160]
Hey, Zadam. Awesome app. 
I just wanted to ask you is there is a way to edit the inherited attribute's value in child notes. Because I am following the zettelkasten method of note creation, so I am adding multiple attributes to each note, and hence it takes a lot of time to add those attributes one by one. 
If inherited attribute's values are editable then instead of adding label name and value for each new note, we would only need to change the value of the already available attributes. It would save a ton of time while taking notes. And would also aid in having fixed tag structure for a specific note tree.
And Thank you so much for creating such an excellent notetaking app.

**Comment by zadam** [comment]
Hi, take a look at [promoted attributes](https://github.com/zadam/trilium/wiki/Promoted-attributes), that seems like what you want ...

**Comment by terra9** [comment]
It does take care of my needs, but it has its issues. Like when I add around eight tags or more, it covers the whole screen. And there are no ways to hide those promoted tags temporarily or scroll down to the content of the notes. My contents in note gets trapped.

**Comment by zadam** [comment]
Yes, it has its issues and was designed with just few attributes in mind. This was also discussed in #1037

**Comment by terra9** [comment]
I see. I read the #1068 issue, it will most definitely cover my needs. so how long will it be implemented?

**Comment by zadam** [comment]
First beta in probably few weeks ...

**Comment by popey456963** [comment]
I'm probably going to close this as a combination of answered, but wwith enhancements requested under #1037 & #1068.
