### ISSUE TITLE
[Question] sort into Folders by Attributes

### ISSUE THREAD

**Issue by Sebiann** [zadam/trilium#1161]
I have around 1000 notes that are in a folder that either have the attribute @"5E General Rules" or @"Monster Manual" and id like too sort them into folders.

So everything with @"Monster Manual" into Monster Manual and @"5E General Rules" into Rules

**Comment by zadam** [comment]
Hi, look at [saved search](https://github.com/zadam/trilium/wiki/Search#saved-search) \- you can search for such attribute (so search for e.g. `@"Monster Manual"` and then "save" that search - that will create a virtual folder with the search results as its children.

**Comment by popey456963** [comment]
This question appears to be answered, so am thus closing the issue.  If you're looking for another solution feel free to reopen it.
