### ISSUE TITLE
[BUG] .deb package adds 2 desktop entries in GNOME 3.36

### ISSUE THREAD

**Issue by Ricostyle21** [zadam/trilium#1173]
When you install the .deb package adds the file `trilium-notes.desktop` to the path `/home/%user$/.local/share/applications` and also the file `trilium.desktop` to the path `/usr/share/applications` while in reality only one is necessary.
Installed with Eddy

**Comment by gtsiam** [comment]
It isn't a problem with the deb package in particular. Apparently trillium notes automatically creates the `trillium-notes.desktop` file in `~/.local/share/applications`. I think I saw a config option to turn that off somewhere in the trillium-data folder.

**Comment by zadam** [comment]
@gtsiam yes, you're correct. This was intended mainly for non-deb distros where user needs to download .tar.xz so there's no installation per-se. 

But now it does not really seem that great of an idea. Not sure what to do ...

Anyway, to disable this behavior, you just need to add `noDesktopIcon=true` to "General" section of config.ini in the trilium-data directory.

**Comment by Ricostyle21** [comment]
Of course it's easily fixed, but not before there are already 2 desktop shortcuts... The app only creates config.ini after being launched and thus having created another shortcut. But I certainly understand why you did it.
