### ISSUE TITLE
Neon Theme

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1175]
Here is a theme I created. Code based on other themes and color scheme tweaked. 

https://github.com/Engr-AllanG/trilium-theme-Neon_Dark

**Comment by jaroet** [comment]
Nice ... you might also add it to the page your linking to for installation
...

See at the bottom of the themes page
https://github.com/zadam/trilium/wiki/Themes

Op do 6 aug. 2020 om 08:34 schreef Allan Glover <notifications@github.com>:
