### ISSUE TITLE
Ctrl + A and Ctrl + K should not be bound in macOS

### ISSUE THREAD

**Issue by iwinux** [zadam/trilium#1177]
**VERSION:** 0.43.3 on macOS 10.14.6

Currently there're at least two actions in note editor that are bound to modifier <kbd>Ctrl</kbd> *and* <kbd>Command (Meta)</kbd> on macOS, which is unnecessary and prevents the system level key bindings from working:

1. Select All - bound to <kbd>Ctrl + A</kbd> and <kbd>Command + A</kbd>. <kbd>Ctrl + A</kbd> in macOS is supposed to be "move cursor to line start".

2. Link - bound to <kbd>Ctrl + K</kbd> and <kbd>Command + A</kbd>. <kbd>Ctrl + K</kbd> in macOS is supposed to be "kill characters from cursor to line end".

It would be great if I can unbind these unwanted key bindings so that I can edit notes smoothly.

Related issues:

* https://github.com/zadam/trilium/issues/290
* https://github.com/zadam/trilium/issues/511
* https://github.com/ckeditor/ckeditor5/issues/5705

It seems weird that https://github.com/zadam/trilium/commit/3ff3021acd91d55f767c266f61e54b808812a8eb does not resolve this issue.

**Comment by zadam** [comment]
Hi, I think both of these are handled by ckeditor itself without any handling on trilium side so I guess this depends mainly on [ckeditor/ckeditor5#5705](https://github.com/ckeditor/ckeditor5/issues/5705)

**Comment by oleq** [comment]
Hi there, we addressed this issue in ckeditor/ckeditor5#5705. The fix will be included in the upcoming release of CKEditor 5. Thanks!
