### ISSUE TITLE
Clarification of Template definition for day Journal

### ISSUE THREAD

**Issue by msadowski** [zadam/trilium#1178]
Hi!

I've gone through the wiki and already existing issues (e.g. https://github.com/zadam/trilium/issues/943, https://github.com/zadam/trilium/issues/670).

Basically I would like to have a checkbox list as a template, so that every time I execute CTRL+ALT+P the new day note has the same content as my template. I'm running version 0.43.3.

Here is what I was trying:

1. I created Day note as a child to Calendar:
![image](https://user-images.githubusercontent.com/6543766/89518999-00895a80-d7dc-11ea-946a-c7a800c27d4e.png)
2. I modified Calendar note attributes as follows:
![image](https://user-images.githubusercontent.com/6543766/89519119-2878be00-d7dc-11ea-9638-0f05dc78165d.png)

My expectation after reading the wiki was that this would allow me to pre-populate every new day note, however on pressing ctrl+p an empty note is created:
![image](https://user-images.githubusercontent.com/6543766/89519266-5e1da700-d7dc-11ea-856f-ef2c90ddcfef.png)

Obviously I've missed something but I can't seem to be able to figure it out.

**Comment by idelem** [comment]
The relation name is `child:child:child:template` since the day note is a great-grand child of the calendar. Also, Ctrl+P creates a note nested under the current one. Try Ctrl+O after you make the change.

**Comment by zadam** [comment]
Yes, it is like @idelem says, what you want to do is to set the template relation on the newly created note and you can do that by specifying the `child:child:child:template` relation. 

Also `CTRL-ALT-P` creates a new note underneath the current day note, while as fas as I understand you want to set the template on the day note itself. To create/navigate to current day note you can use the "today" button or calendar widget.

**Comment by msadowski** [comment]
Hi! Many thanks for the answers! Unfortunately this doesn't seem to work for me for some reason. Am I doing something wrong?

Here is how the note structure looks like:
![image](https://user-images.githubusercontent.com/6543766/89763595-2623a600-daf3-11ea-99e8-53eab6a223d7.png)

Here are the attributes on the calendar note:
![image](https://user-images.githubusercontent.com/6543766/89763679-49e6ec00-daf3-11ea-9ca5-8e23365f9acd.png)

Here are the attributes on the Day note:
![image](https://user-images.githubusercontent.com/6543766/89763711-59fecb80-daf3-11ea-8d94-f657354e016a.png)

Here is a gif on what happens when I create a new note by clicking on the calendar:
![Peek 2020-08-10 10-25](https://user-images.githubusercontent.com/6543766/89764053-02ad2b00-daf4-11ea-9373-ec093886febe.gif)

Did I miss anything? I'll appreciate any insights!

**Comment by zadam** [comment]
So the important thing to understand about using this "child:" prefixes is that it's essentially copy-inheritance. When a new note is created, Trilium looks into the parents and looks for these "child:" relations and copies them (while stripping a single instance of child: prefix). 

So when you change/add such "child:" attribute, it will have an effect only on new notes - specifically here only on new year (2021), and then new month, and then new date. To fix your existing structure, you can either delete the old 2020 year and start anew or you can add the missing relations yourself manually (so add `child:child:template` relation to 2020, add `child:template` to the August and then `template` to existing date notes.

**Comment by zadam** [comment]
Actually I found out there's a simpler way - since defining template for day notes is quite common task and this `child:` copy inheritance is relatively complicated, there's a shortcut - you just need to define `dateTemplate` relation on the calendar root (in your case "Calendar" note) and this will be then added as a template.

**Comment by msadowski** [comment]
Many thanks for the advice! It is working now! What I ended up doing was deleting the 2020 note as you suggested and then I hit CTRL-ALT-P to regenerate it and all the new day notes are using the template now.
