### ISSUE TITLE
Trilium is spelled wrong?

### ISSUE THREAD

**Issue by lanslans** [zadam/trilium#1180]
Trillium (the flower) has two Ls

This has 1 L.

**Comment by zadam** [comment]
Yeah, but this software is a note taker, not a flower.

Joking aside, one L is on purpose.

**Comment by casidiablo** [comment]
Since you are here, and the issue is still open... why the name? What does trilium mean?

**Comment by zadam** [comment]
Naming software is hard. I lived in Ontario when I first started the project and Trillium (the flower) is sort of a provincial logo, many institutions in Ontario are named "Trillium \[something\]". So I kept hearing/reading it almost everyday, I liked the sound of it and its nature motif, so I just reused it.
