### ISSUE TITLE
Cut and Paste Selection into Subnote only works once

### ISSUE THREAD

**Issue by accelfuture** [zadam/trilium#1182]
When using this function I can only use it once, then I have to restart Trilium to get the tool working correctly. I can only make one sub-note with content. Subsequent attempts create sub-notes with no content and the text remains on the source note.

Trilium ver. 0.43.3 Build date 2020-07-31T23:34:05+02:00
Linux Mint MATE 19.1 64-bit

00:44:38.082 INFO  POST /api/notes/PpmN0axavomO/link-map 
00:44:38.246 INFO  GET /api/autocomplete?query=&activeNoteId=null 
00:44:38.294 INFO  PUT /api/options 
00:44:38.402 INFO  GET /api/clipper/handshake 
00:44:39.296 INFO  PUT /api/options 
00:44:39.302 INFO  GET /api/notes/VsLPelJdMUS1/revisions 
00:44:39.303 INFO  GET /api/similar-notes/VsLPelJdMUS1 
00:44:39.312 INFO  POST /api/notes/VsLPelJdMUS1/link-map 
00:44:43.301 INFO  POST /api/recent-notes 
00:44:52.536 INFO  POST /api/notes/VsLPelJdMUS1/children?target=into&targetBranchId=undefined 
00:44:52.582 INFO  POST /api/tree/load 
00:44:52.632 INFO  GET /api/notes/XF6xTDGAe16S 
00:44:52.688 INFO  PUT /api/options 
00:44:53.634 INFO  GET /api/notes/XF6xTDGAe16S/revisions 
00:44:53.635 INFO  GET /api/similar-notes/XF6xTDGAe16S 
00:44:53.648 INFO  POST /api/notes/XF6xTDGAe16S/link-map 
00:44:57.631 INFO  POST /api/recent-notes

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. I have to admit I did observe similar behavior in the past, but at the moment I can't reproduce it - it seems to work everytime as intended :( So I'm pretty sure there's a bug somewhere but it's hiding from me ...

**Comment by accelfuture** [comment]
Oddly enough, I checked today and it's working correctly now. I checked yesterday and it wasn't working. Quite strange.

**Comment by terra9** [comment]
It happens with me too.
When I use it, it doesn't work the first time. But after doing a refresh using Ctrl + R, it works. But last line stays in place becoming Header 2. But newly created note has all the content.

**Comment by Engr-AllanG** [comment]
I have experienced similar behavior in the past but didn't create a bug
report, probably a few releases ago. I just tested again though and it is
working fine currently. Server install, .43.3
-Allan

**Comment by popey456963** [comment]
Adding 'blocked' until we work out reproduction steps.

**Comment by zadam** [comment]
This has been fixed a while ago.
