### ISSUE TITLE
Problem discovering Local Search

### ISSUE THREAD

**Issue by LorenAmelang** [zadam/trilium#1184]
I've finally discovered the clue I was missing, and I'm so glad - Trilium looks like exactly what I need! 

But I really think 
https://github.com/zadam/trilium/wiki/Search
needs an improvement - the inclusion of "Local Search". The rest of this post gives the long story of the two hours I just spent discovering it. I'm sure I must have typed Ctrl+F a few times during my exploration - guess I just missed seeing the box appear in its current location up in what for most apps is a title bar. Yes, I'm half blind...  

I do have one question...  Local Search often finds invisible instances of the search term - nothing highlighted. They retain their position in the list. Often the very first result is invisible, which makes it more likely the user will miss the effect. Browsers tend to call out text that is currently hidden, not expanded into view. Is Trilium doing something like that? 

...

Since it is already written, I'll leave my pre-enlightenment whine here...  Maybe some of my terms will lead other searchers here.

I save lots of long, complex academic papers, and Trilium is amazing for finding the ones with my search terms. But some papers are many screenfulls of text, and actually spotting the search result is difficult. I really need something like a browser "find in page" function - with highlighting. Really obvious or at least configurable highlighting. 

The only clue I've found is here: 

https://github.com/zadam/trilium/issues/868
-----
Global search #868
dan-2019 commented on Feb 11

Make text highlighting (and result navigation) for global search similar to local search. At the moment after, a note was found in a global search, it needs to be searched again locally to find the text location within it. I wish this could be combined into one handling.
-----

"It needs to be searched again locally to find the text location within it."

If I select only one of the notes in the initial global search results, and search again, the other notes disappear from the list, but I still see the full note with no highlighting or scrolling to the found search text. 

At least I did before learning Ctrl+F...  

App version: | 0.43.3

**Comment by zadam** [comment]
Hi, yes, you have a good point that the discoverability isn't the best. I added a mention in the wiki page and also added a "Search in note" to the "Note actions" menu which will trigger this functionality.
