### ISSUE TITLE
Scripting - New note if Label.value not listed in child notes

### ISSUE THREAD

**Issue by Potjoe-97** [zadam/trilium#1188]
Hi all. 

First of all, thank you for all the work done. As a researcher, trilium is really handy and is the best tool I ever had to use for this purpose. 

In order to organize a bibliography, I would like to set a promoted label to a note (Ex: Author), check if in a Root "directory" a subnote is already present with this label as a title or create it if needed, and then clone the note into this subnote. 
In a nutshell : replicate the behaviour from the task manager, dividing between tags location etc. And here is my issue : looking at the code in the demo and the script API, I can't figure out what does the const isTaskDone in reconcileAssignment ? 

While trying to replicate the code with two text labels, Author and Date, I could'nt figure out what to do with this variable. Thus I had mixed result, with only one of the two subnotes were created. Here is my code : 
```
if (!["Livre", "Auteur", "Date"].includes(api.originEntity.name)) {
    return;
}
const auteurRootNote = await api.getNoteWithLabel('auteurRoot');
const dateRootNote = await api.getNoteWithLabel('dateRoot');


if (!auteurRootNote || !dateRootNote) {
    console.log("One of the tagRootNote, doneRootNote or todoRootNote does not exist");
    return;
}

const note = await api.originEntity.getNote();
const attributes = await note.getAttributes();

const checkAuteur = await note.getLabelValue('Auteur');
const isTaskDone = !!checkAuteur;

const auteur = attributes.filter(attr => attr.type === 'label' && attr.name === 'Auteur').map(attr => attr.value);

await reconcilebook(note, auteurRootNote, auteur, 'auteurNote', isTaskDone);

const date = attributes.filter(attr => attr.type === 'label' && attr.name === 'Date').map(attr => attr.value);

await reconcilebook(note, dateRootNote, date, 'dateNote', isTaskDone);
```

**Comment by zadam** [comment]
Hi, so if I recall correctly, if `isTaskDone` is true, then the task is removed from most places since it's already done so it doesn't need to fill the categories (which are supposed to show non-finished tasks).

So I would just experiment with setting this variable to false.

**Comment by Potjoe-97** [comment]
Sorry for the late reply, my laptop died in the meantime. 
Thanks for your answer, indeed I had a look and just removed the variable, and now it's working well! I have a good basis to filter different labels, it's perfect. 
Are you ok if I share the version I ended up with ? It's nothing more than your modified code, but I removed everything task-related to have it "neutral".

**Comment by zadam** [comment]
Sure, go ahead.

**Comment by Potjoe-97** [comment]
Great!
So here is the replacement for "Attribute changed"
```
if (!["Book", "Author", "Year"].includes(api.originEntity.name)) {
    return;
}

const authorRootNote = await api.getNoteWithLabel('authorRoot');
const yearRootNote = await api.getNoteWithLabel('yearRoot');


if (!authorRootNote || !yearRootNote) {
    console.log("One of the root note does not exist");
    return;
}

const note = await api.originEntity.getNote();
const attributes = await note.getAttributes();

const author = attributes.filter(attr => attr.type === 'label' && attr.name === 'Author').map(attr => attr.value);
await reconcilebook(note, authorRootNote, author, 'authorNote');

const year = attributes.filter(attr => attr.type === 'label' && attr.name === 'Year').map(attr => attr.value);
await reconcilebook(note, yearRootNote, year, 'yearNote');

```

And the "reconcilebook" subnote function :

```
module.exports = async function(note, categoryRootNote, assignedCategories, labelName) {
    const found = {};
    
    for (const categoryNote of await categoryRootNote.getChildNotes()) {
        const label = await categoryNote.getLabel(labelName);
        
        if (label) {
            found[label.value] = assignedCategories.includes(label.value);

            await api.toggleNoteInParent(found[label.value], note.noteId, categoryNote.noteId);
        }
    }    
    for (const assignedCategory of assignedCategories) {
            if (!found[assignedCategory]) {
                const categoryNote = (await api.createNote(categoryRootNote.noteId, assignedCategory, "", {
                    attributes: [ { type: "label", name: labelName, value: assignedCategory } ]
                })).note;

                await api.ensureNoteIsPresentInParent(note.noteId, categoryNote.noteId);
            }
        }
 }
```

For those who wish to use it as it is to filter books for instance, you just need to set an authorRoot label def in the author "folder" note. When you create a new note with the label Author, if it has the attribute runOnAttributeChange pointing to 'Attribute Changed' note, it will be filtered automatically.

Thanks again @zadam !

**Comment by Potjoe-97** [comment]
It seems that 0.44.4 broke this code. Since the new release, category notes which aren't already present are created twice. I was not able to fix the issue.

**Comment by Potjoe-97** [comment]
Actually, `runOnAttributeChange` was inherited twice, from the parent and the template, which caused the code to be executed twice.
