### ISSUE TITLE
When I insert a gif animated picture, trilium is not well recognized, it is still

### ISSUE THREAD

**Issue by R0FGV** [zadam/trilium#1194]
When I insert a gif animated picture, trilium does not recognize it well, it is still. Is this a software problem?

**Comment by zadam** [comment]
Hi, yes, partially - trilium tries to very aggressively compress the images - with that effect that large animated GIFs might be compressed to still image instead.

However the approach has changed in the upcoming 0.44 and the aggressive compression was dropped (it caused various problems including this one) so in (not yet released) 0.44 this problem should go away.

**Comment by Micosilent** [comment]
This is currently working in 0.48, maybe it should be closed?
![b39b5433cce5508e5814da08421216be](https://user-images.githubusercontent.com/18470759/141534531-b4bbb0a7-21a0-422c-90bb-171a75a4819b.gif)
