### ISSUE TITLE
Promoted attributes preview bugs

### ISSUE THREAD

**Issue by idelem** [zadam/trilium#1195]
version: 0.43.2

1. If you click on a page with promoted attributes, the popup preview window will remain on screen until you click again.
2. Preview of pages with empty promoted attributes are not rendered properly; see:

![image](https://user-images.githubusercontent.com/25763288/90584759-e7ce6b00-e205-11ea-9790-f0ba70651c82.png)
![image](https://user-images.githubusercontent.com/25763288/90584823-11879200-e206-11ea-9a49-734974161f8b.png)

**Comment by zadam** [comment]
Hello, promoted attributes and preview handling has been significantly refactored in master branch (future 0.44) and these bugs should be fixed so I'm going to close this issue.
