### ISSUE TITLE
Update Installed Trilium App

### ISSUE THREAD

**Issue by bhavesh29** [zadam/trilium#1197]
How does one upgrade there existing application to a newer version. I dont see any documentation for it.
A link, **"Update Application"** in the **Options -> About Trilium** will make this process much easier.

**Currently Installed Version**
---------------------------------
App version:  0.27.3
DB Version: 121
Sync version: 3
Build date: 2019-01-05T22:48:11+01:00
Build revision: 9fca7f09a564c719c834d38d76c3b595c8579b2a

**Comment by zadam** [comment]
Hi, "the old way" - you download new version, unpack it, run it.

I see that you're using very old version though. Trilium will attempt data migration on startup, hopefully everything will go fine.
