### ISSUE TITLE
Create Android app for submitting notes and images

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#12]
The idea is to provide quick way to share text and images from your phone to Trilium. For example you take a picture with phone camera and share it to the Trilium app which uploads it to the Trilium server. Content will be uploaded to either fixed location or e.g. to "date" note.

App won't allow reading notes/content, it's essentially "write-only".

**Comment by zadam** [comment]
Created separate repo for this: https://github.com/zadam/trilium-sender

**Comment by gerroon** [comment]
Any word on this? it seems like the repo nevber took off?

**Comment by zadam** [comment]
The basic app is there, but frankly I'm not using it and I'm not sure if it still works or not.
