### ISSUE TITLE
[BUG] Child note displayed twice

### ISSUE THREAD

**Issue by Ricostyle21** [zadam/trilium#1203]
Trilium version 0.43.3

Sometimes, for example when using `CTRL + J`, when accessing a note that itself doesn't contain text but it has one child note, the same child note is displayed twice, when it should be displayed only once.
![Annotation 2020-08-24 212028](https://user-images.githubusercontent.com/28575471/91086945-ee1e7600-e64f-11ea-9eed-027502af8835.jpg)

**Comment by terra9** [comment]
Try restarting the Application. It happens with me too, sometimes.

**Comment by zadam** [comment]
Hello, this was already reported in #1191 and fixed in master (future v0.44).
