### ISSUE TITLE
[BUG] Cannot remove auto-indent in text editor

### ISSUE THREAD

**Issue by Ricostyle21** [zadam/trilium#1204]
Trilium version: 0.43.3

This one's really annoying...

Repeat following steps:

1. Create new text note
2. Type something on the first line
3. Press `ENTER` and immediately press `TAB`. Type something on line 2
4. Press `ENTER` again and realize that you cannot remove the automatically created indent on line 3.

See attached image for a bit more detail.

![image](https://user-images.githubusercontent.com/28575471/91088150-d0521080-e651-11ea-8178-59aa97816468.png)

**Comment by Ricostyle21** [comment]
Hmmm, I do fee stupid for not trying that out. Nevertheless, in my opinion a backspace should also be possible, like with common text editors.

**Comment by zadam** [comment]
Besides what @terra9 said, it's also possible to use UI to decrease indent.

![](https://user-images.githubusercontent.com/617641/91231112-031d0700-e72d-11ea-9ac5-212170ad2031.png)

While I understand that the current behavior might seem confusing for some, I don't really think that backspace removing indent would not be confusing for other people.

This is also CKEditor's default behavior and I prefer to not deviate from baseline as much as possible.
