### ISSUE TITLE
Protected Notes Sync Questions

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium#1205]
I checked the [wiki](https://github.com/zadam/trilium/wiki/Protected-notes) for protected notes and it doesn't mention anything about how they are handled during sync. If the sync server is comrpomised and an encrypted note is synced to the server, is this a security risk?

Also if you are in a protected session and a sync occurs, is the note synced "unprotected" or is it synced protected?

**Comment by zadam** [comment]
Protected notes are synced just like they are stored - encrypted.

> If the sync server is comrpomised and an encrypted note is synced to the server, is this a security risk?

No, at least as far as protected notes are concerned (unprotected notes are of course compromised in this case). Sync server has notes in encrypted form and it's not possible to decrypt them without password.

> Also if you are in a protected session and a sync occurs, is the note synced "unprotected" or is it synced protected?

No, "protected session" does not affect sync process or database at all. Decrypted notes and encryption key are stored in memory only.

**Comment by bonedaddy** [comment]
makes sense, thanks
