### ISSUE TITLE
Migration 161 may fail

### ISSUE THREAD

**Issue by 0xADD1E** [zadam/trilium#1207]
The JSON.parse steps in migration 161 fail on fields with empty value (seems to only be for records where `name='deleted'`)

The terrible 1am hack I used to get things up and running is
```sql
DELETE FROM attributes WHERE value = '' AND (type = 'label-definition' OR type = 'relation-definition')
```

**Comment by zadam** [comment]
Hello, thanks for reporting this problem. I added error handling code for these cases which reset the attribute to a default state.

Word of warning, it looks like you're running master branch which is not yet released and fully tested (although first beta is quite near).
