### ISSUE TITLE
PDF preview not working

### ISSUE THREAD

**Issue by chadkennedyonline** [zadam/trilium#1208]
Using version 0.43.3 via docker image

The PDF preview appears to not be working in the sample page "The Last Question". I looked at the "Note Source" and saw the "data-note-id" is "6bgGsivB8kLZ", while the note "The Last Question by Issac Asimov.pdf" has ID "3XoiSv0SeijR". So, I created a new "Include Note" to that ID with size full. The PDF preview still didn't work.

I'm using Chrome on Windows. I verified I get the same behavior in an Incognito window with all plugins disabled.

I looked at "trilium-data/log/trilium-2020-08-27.log" on the server, but there's nothing interesting there. Just "GET" and "POST" lines.

I also tried restarting the docker container, but it didn't help.

I'm happy to work with you to debug.

**Comment by zadam** [comment]
Hello, for some reason I thought PDF preview works only in Electron and therefore I didn't activate the feature in server build.

I fixed that now, new version will be released soon.

Thanks for reporting!

**Comment by chadkennedyonline** [comment]
I just wanted to say "Wow!" You are doing an amazing job! I wasn't even expecting a response so quickly, much less a fix to be implemented and released. I'm super impressed. Thank you!

**Comment by pencina** [comment]
Hi guys, I am new using this cool tool, for the example The last Question, how do you create the small pdf preview with the two buttons "Download" and "Open"

Regards

**Comment by zadam** [comment]
It's the "include note" functionality:

![](https://user-images.githubusercontent.com/617641/110703697-60256980-81f4-11eb-8237-dd56a0166b0a.png)

**Comment by pencina** [comment]
Thanks
