### ISSUE TITLE
attributes tooltip is persistent in beta release.

### ISSUE THREAD

**Issue by terra9** [zadam/trilium#1214]
Tooltip is persistent for attributes. This issue was before too, but it would go away itself after we change notes or do something that involves refresh of the screen.

**Comment by terra9** [comment]
It is now not occuring all the time. Will comment about reproducible step later when i encounter it again.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue.

I believe the corner case you stumbled upon was activating the note from relation - this did not blur the attribute editor which is normally the trigger to hide the tooltip. This was now fixed.
