### ISSUE TITLE
How do I setup server version of trilium on aws ec2 instance?

### ISSUE THREAD

**Issue by avinashkanaujiya** [zadam/trilium#1215]
Problem right now i have is that after running docker of trilium, it is telling me to go to http://[myhostserver]:8080, but it just keep on connecting and then says that connection refused.
I have changed the security group setting to any IP and any Protocol.
But still the same issue.
I installed apache2 and checked by going to http://[myhostserver] and it loads the server page.
I dont know what to do at this point.

**Comment by popey456963** [comment]
Did you update the security group to use the port 8080 instead of 80?

Does your EC2 instance have a firewall on it disabling port 8080 (e.g. `ufw`).
