### ISSUE TITLE
Change DB version

### ISSUE THREAD

**Issue by bored-user** [zadam/trilium#1218]
I was recently doing some experiments with Trilium: I cloned the repo and built it using `npm` commands. It worked fine on the browser, but now I'm not able to enter the application on desktop - it says "Current DB version 167 is newer than app db version 159 which means that it was created by newer and incompatible version of Trilium. Upgrade to latest version of Trilium to resolve this issue."
Is there a way to fix that? I'm on v0.43, btw.

**Comment by zadam** [comment]
Hi, the best way to resolve this is to upgrade to the latest beta version - 0.44.1-beta.

**Comment by bored-user** [comment]
> Hi, the best way to resolve this is to upgrade to the latest beta version - 0.44.1-beta.

It worked perfectly, thanks!!
