### ISSUE TITLE
DB not initialized, please visit setup page - http://[your-server-host]:[object Promise] to see instructions on how to initialize Trilium.

### ISSUE THREAD

**Issue by Skarlso** [zadam/trilium#1219]
Hi. This is a docker setup. And I can see this in the logs:

```
DB not initialized, please visit setup page - http://[your-server-host]:[object Promise] to see instructions on how to initialize Trilium.
```
I have no idea what's missing. :)

**Comment by zadam** [comment]
Hi, so there's a small bug which causes the "\[object Promise\]" while normally there should be a port number (by default 8080). However this doesn't have any functional implications.

I'm not sure if your question was about this bug or something else. To finish your setup you need to open the web page on your docker host on port 8080 (by default).

**Comment by Skarlso** [comment]
Everything is fine here. The setup when okay. This is just a about the promise bug and I didn't know what I needed to open. But it opened itself at the right location. :-)

**Comment by zadam** [comment]
Great, the promise bug was fixed, so we can close this.
