### ISSUE TITLE
Sync setup failed: Could not setup sync since local sync protocol version is 14 while remote is 16. To fix this issue, use same Trilium version on all instances.

### ISSUE THREAD

**Issue by Skarlso** [zadam/trilium#1220]
Hi. This is a docker setup using the latest docker image.

I just tried syncing up with a local trilium desktop client and this is the error message I'm getting. Which one is now out of date? :)

**Comment by Skarlso** [comment]
Never mind. Got it. I downloaded a too early desktop client. :)

**Comment by SenfMeister78** [comment]
But why this issue in the first place. That will force you to use old versions in some situations. Might be a security issue solved that you then can't until both are in same version, which obviously aren't a proprity
