### ISSUE TITLE
Note linking balloon is not big enough to accomodate the title and its address.

### ISSUE THREAD

**Issue by terra9** [zadam/trilium#1221]
Note linking balloon is too small to accomodate notes title, if notes is located too deep into the tree.
This issue is in current beta release.

**Comment by zadam** [comment]
Hi, I'm not sure what is the problem here - in the autocomplete too long note paths will just wrap, on the input it doesn't wrap, but you can scroll within it ...

**Comment by terra9** [comment]
I guess I didn't say it correctly. 
I meant that when I link a note using @ so the balloon or dialog that appears suggesting the notes to be linked, there the names are not completely visible.
Like this image below.
![image](https://user-images.githubusercontent.com/24972285/92613631-cdede880-f2d8-11ea-88f7-0009f80360e4.png)
Second & third suggestion has cut off.
And also can't do horizontal scrolling to bring it in view.

**Comment by zadam** [comment]
Hi, this was fixed by allowing long text in autocomplete to wrap to the next line.

**Comment by terra9** [comment]
Thanks!
