### ISSUE TITLE
'Tree Setting' button should be moved onto the same row as the 'Hide Siderbar' button.

### ISSUE THREAD

**Issue by aak9t9** [zadam/trilium#1223]
Tree Setting Icon/Button can be moved down on same row as Hide Sidebar Button. Because right now, it feels annoying sometimes, if i want to unhoist the note. 
Also at bottom, where Hide Sidebar Button is located, space is wasted, since it is empty. So Tree setting button can be moved their. Just opposite to where Hide button is.

**Comment by zadam** [comment]
Hi, putting the button on the bottom seems kind of weird, but I will think about it. Especially since I do plan to actually put more buttons there in the future.

But what you mentioned with the unhoisting is true, I moved the "unhoist" button to the left so that long note title won't push it out.

**Comment by terra9** [comment]
Thanks.

**Comment by aak9t9** [comment]
I am closing since it is resolved.
