### ISSUE TITLE
Please add a sync function.

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1225]
I highly suggest that you develop an online sync function.It's very difficult for people like us who cannot build our own servers, I've been trying all day and still haven't got the DOCKER set up right!
The main problem: MAC and windows can't sync data, and I don't know what's wrong with it.
I recommend two possible solutions.
1 - I'd be more than willing to pay a monthly or annual fee if I could make the sync feature work down!
2- Is it possible to perform online sync function with DROPBOX? It seems like the exported ZIP packages can only be exported and imported, and if you've used DROPBOX's online sync function you can see the use very clearly. (For example, DROPBOX has an excel document I directly open the EXCEL document for editing, and then, after saving and exit,DROPBOX will automatically synchronize the updated EXCEL document)

Thansk in advance
Waiting for a Reply!

**Comment by zadam** [comment]
Hi, I understand the pain, but the solution for this is difficult:

1.  hosting a public sync service is a big commitment and large time sink. Sorry, but I don't plan to go this route.
2.  there are technical issues with using dropbox or other general purpose syncing services. See #913, #995 for other discussions on this topic.

**Comment by Rsose** [comment]
> Hi, I understand the pain, but the solution for this is difficult:
> 
> 1. hosting a public sync service is a big commitment and large time sink. Sorry, but I don't plan to go this route.
> 2. there are technical issues with using dropbox or other general purpose syncing services. See #913, #995 for other discussions on this topic.

thanks I risolved the problem
1-**Mac** using symbolic link:Run [**the ln command**](https://www.howtogeek.com/297721/how-to-create-and-use-symbolic-links-aka-symlinks-on-a-mac/) in the following form. You can specify either a path to a directory or file:
` ln -s /path/to/original /path/to/link` 
` E.g: ln -s /user/name/dropbox/trilium ~/trilium-data(This is Trilium-data directory path)` 
Add a cloud folder path (Dropbox,Google,OneDrive)

2-**Windows** it's easy to modify Environment Variables.[**Check Guide**](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0)
You should check **System variables** on Windows
Create a new environment variable:
-Set Variable name as **_TRILIUM_DATA_DIR_**
-Set Value as **_C:\dropbox\trilium_** (dipends on where your cloud folder path is)

Then We can easily sync across platforms(Windows and Mac)
Question:Is it impossible to modify trilium-data directory on **Mac**?I tried all the ways but it still havent changed.
It seems that only the webserver(Manual Installation) can modify the TRILIUM_DATA_DIR using .zshrc file.

**Comment by zadam** [comment]
> Question:Is it impossible to modify trilium-data directory on **Mac**?I tried all the ways but it still havent changed.  
> It seems that only the webserver(Manual Installation) can modify the TRILIUM\_DATA\_DIR using .zshrc file.

I don't know how to do that on Mac, but another way would be creating a symlink.

**Comment by Rsose** [comment]
> > Question:Is it impossible to modify trilium-data directory on **Mac**?I tried all the ways but it still havent changed.
> > It seems that only the webserver(Manual Installation) can modify the TRILIUM_DATA_DIR using .zshrc file.
> 
> I don't know how to do that on Mac, but another way would be creating a symlink.

Yeah,that's working fine for me.(symlink)
great software hope Trilium gets better and better
