### ISSUE TITLE
QUESTION: If I am writing custom code, can I extend the database?

### ISSUE THREAD

**Issue by scwagner** [zadam/trilium#1226]
I have some ideas for how I would like to add some functionality to Trilium, and I feel that being able to create a table in the database to cache some information rather than having to dynamically scan through notes or a note containing a giant JSON blob.

I see that the `sql` object is available in the backend API object.  If I were to execute queries to create tables and insert rows, would that work or would it run the risk of potentially breaking something in the future.

Also, would this work properly with server synchronization?  If one of my instances is modifying the database directly, would that get sent to the server?  I went through the documentation about Document as well as Synchronization, and didn't find anything that steered me towards the answers.

Thank you!

**Comment by zadam** [comment]
Hi, it should be safe to create extra tables in the SQLite - Trilium will simply ignore them but that also means they won't get synchronized across instances.

I'm doing quite a lot of scripting and persistence in Trilium and I didn't find the combination of "data" notes (for structured data) with attributes (for querying and relationships) very limiting. It's sort of like an object database on top of SQLite. It's also IMHO pretty useful that the persisted data are still represented in the UI with all its metadata and relations ...

**Comment by scwagner** [comment]
Ok, I'll try it out with using Notes and attributes first.  Thanks for the reply!
