### ISSUE TITLE
Enable Sorting Sidebar Alphabetically

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium#1227]
It would be cool to be able to sort the sidebar alphabetically, instead of the order in which notes are created. It does appear possible to move the notes around, but to sort alphabetically this way would be very tedious.

**Comment by scwagner** [comment]
If you add an attribute of type `Label` where the name is `sorted`, then it will sort the children items alphabetically, even as new ones are added.

If you wanted the entire tree sorted, then maybe you could add it to the root node and mark it inheritable and the whole tree would auto-sort?  I haven't tested this, as I don't want to have my whole tree sorted.

**Comment by bonedaddy** [comment]
Interesting I didnt know this was possible,  thank you.
