### ISSUE TITLE
display children notes

### ISSUE THREAD

**Issue by sdlytcl** [zadam/trilium#1228]
Hi, I like this software very much. When a note doesn't have any content，IT displays its children. If a note has written something, can its children be displayed below? This is useful for Toggle Zen mode. Thank you.

**Comment by zadam** [comment]
Hi, unfortunately is this not currently possible. But I understand the need and it is possible that this will in some form come in the future.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.

**Comment by sdlytcl** [comment]
thank you. It is a way to write an article.  Put the relevant notes in a new note in a “clone” way, and you can combine them into a new article. I believe that this feature will be helpful.thank you.
