### ISSUE TITLE
How can I add notes into tree on mobile version?

### ISSUE THREAD

**Issue by brianbloom** [zadam/trilium#1229]
[ First off, this app is fantastic.  I have migrated my existing notes content from the ancient PHP app I wrote decades ago, but still use daily (http://notetoself.sourceforge.net/)..  I even themed Trilium to match my old app. ]

I am running the "latest" docker image (I think that's 0.43-latest) and am trying to figure out how to add a note (text) somewhere in the tree on my android phone.

On desktop, I can easily right-click and do "Insert Note After". But on phone, there's no right-click ability. Whether I use the mobile view or the desktop version, I can't figure out how to create any notes other than the "Create New Top Level Note" button.
**Am I missing something about a way to say "no, add a note _here_" on a mobile device?**

Here's example use case.  I have all my note contents in simple category/note tree under "Note To Self" top level node.
Trying to add a new note under "Jobhunt" for example:
![image](https://user-images.githubusercontent.com/4336947/93022523-e2bbcc00-f5b7-11ea-8541-6a7fda290aa8.png)

**Comment by zadam** [comment]
Hi, it's a bit awkward, but you need to first open detail of the note, click on hamburger menu and then you can create a child note:

![](https://user-images.githubusercontent.com/617641/93025530-fccccd00-f5fe-11ea-956d-da8e7a20d8da.png)
