### ISSUE TITLE
Maybe add line to TLS wiki page about Docker paths?

### ISSUE THREAD

**Issue by brianbloom** [zadam/trilium#1230]
I wasn't sure if I should directly update your wiki and saw no other info about how to submit suggestions for that, so using this issue to ask/suggest...

On the wiki page [https://github.com/zadam/trilium/wiki/TLS-configuration](https://github.com/zadam/trilium/wiki/TLS-configuration) I wanted to propose an addition after "Your paths may be completely different.":

`Note that if you are using a Docker installation, these paths should be in a volume or other path understood by the docker container.
`

(I spent a good half hour troubleshooting why I kept getting ENOENT  "no such file or directory" errors when I could clearly see the key and cert files on my server.)

**Comment by zadam** [comment]
Hi, feel free to update the wiki directly.

**Comment by brianbloom** [comment]
Updated wiki as indicated. Shall I close issue or is that something someone else does?

**Comment by zadam** [comment]
As an author you can close the issue, but I can do it too :)

**Comment by Myzel394** [comment]
Could you give me an example, please? I'm facing the same issue for about an hour now :C
