### ISSUE TITLE
"Export all" button suggestion

### ISSUE THREAD

**Issue by bored-user** [zadam/trilium#1231]
I find it would be incredibly helpful if there was a "Export all" button, to export all notes at once. The user could select the export format (and maybe that "export descendents" option as well) only one time.
Anyway, this is just a suggestion, not an actual issue with the application - which is great, btw :)

**Comment by zadam** [comment]
Hi, you can right click on the "root" note, click export and this will export all notes.

Or do you mean something else?

**Comment by bored-user** [comment]
> Hi, you can right click on the "root" note, click export and this will export all notes.
> 
> Or do you mean something else?

Ah, didn't know that lmao 😅
Thank you, once again!
