### ISSUE TITLE
Question:: Does similiar notes algo looks into tags of notes too?

### ISSUE THREAD

**Issue by a22a-dev** [zadam/trilium#1232]
If yes, then does it takes into consideration tags like autoReadOnlyDisabled.

**Comment by zadam** [comment]
Hi, since 0.44 it does consider attributes (labels and relations) too. However the results from the algorithm are not good in some cases, this is something I want to address in the next version.

**Comment by leeyaunlong** [comment]
> Hi, since 0.44 it does consider attributes (labels and relations) too. However the results from the algorithm are not good in some cases, this is something I want to address in the next version.

When I create a empty note, it will relate to some demo notes, they have no any relations. 
And In many cases, the note have 200 similiar notes, just cause they are web clip type. but those notes has not any relates.
The old the similiar is not smart, but we can know that they have some relations. 
So, I suggest we have a way to customize the similiar notes logic with SQL or advanced search syntax.
Let user make it personally smart similiar notes.

**Comment by zadam** [comment]
> And In many cases, the note have 200 similiar notes, just cause they are web clip type.

The fact that both are web clips make them a bit similar. We shouldn't put too much weight on that, but a little bit is appropriate IMHO. The same thing is done also with e.g. note type and MIME, creation date...

The algorithm is currently immature and needs work regarding special cases, weights and thresholds.

> So, I suggest we have a way to customize the similiar notes logic with SQL or advanced search syntax.  
> Let user make it personally smart similiar notes.

Customizing the similar notes feature is not really feasible. What user can do though is to create their own widget which will display what they believe are the relevant notes.
