### ISSUE TITLE
UX Problem: Immediately delete mistakenly created Note

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1235]
While using Trilium Notes, i very often face the following annoying problem:

I press Ctrl+P by accident (or in the wrong place), an Empty note is then created and opened on foreground, and it's somewhat complicated to just remove it (like a `Ctrl+Z`).

By reflex, i tend to press `Esc` to delete the unwanted empty note, but it only removes the `new note` (default title).

Having an intuitive way to remove an empty note would IMHO improve the overall user experience.

In order to prevent unwanted note deletions, such shortcut should only work on a totally empty note.

**Comment by terra9** [comment]
It is a valid problem, i was thinking about opening a issue.

**Comment by egalanos** [comment]
Agreed. I have also been annoyed by the lack of `Esc` working to dismiss/undo dialogs/actions

**Comment by zadam** [comment]
There has been a support for Escape showing delete dialog for just created note.
