### ISSUE TITLE
Feature Request: CKEditor Toolbar enablement - Remove formatting 

### ISSUE THREAD

**Issue by sitepodmatt** [zadam/trilium#1239]
Please enable CKEditor's "remove formatting" feature on the toolbar for inline text:

https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html

![image](https://user-images.githubusercontent.com/1687145/93288095-53a3f380-f805-11ea-99ec-1556796f6926.png)

A bit of a faff removing the formatting from these email addresses pasted from different sources - colours, underlines

Thanks

**Comment by zadam** [comment]
As a workaround you can use CTRL-SHIFT-V to paste without formatting ...

**Comment by sitepodmatt** [comment]
Great thanks
