### ISSUE TITLE
Read only text view is shown - Missing Heading1 Style

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#1240]
I'm using the latest version on OSX & Web interface: 0.43.4

I recently came across a page that was being changed to read-only. I read #1088 which indicates this is a feature for long notes. The issue i have is that as soon as i click "Edit" every Heading1 is reformatted and looks like the 'Paragraph' style (This includes Heading1 on every single note in the entire Trilium instance. I no longer have any Heading1 - it doesn't even show up as an option in the editor. See below: both 'Overview' and 'Configuration' used to be Heading1, but now look like 'Paragraph'. Also, Heading1 no longer exists in the dropdown.

<img width="251" alt="Screen Shot 2020-09-16 at 12 04 19 AM" src="https://user-images.githubusercontent.com/10717998/93291082-2f69f780-f7b0-11ea-8c4b-ddd0872c6873.png">

I've tried refreshing/reloading the page, i've tried loading it on a different device, but it still looks the same :(

[trilium-2020-09-15.log](https://github.com/zadam/trilium/files/5229557/trilium-2020-09-15.log)

**Comment by Engr-AllanG** [comment]
Heading 1 was removed a few releases back. If I remember correctly, its because when exporting, the note title becomes heading 1.

I had to go through and manually fix all of my headings and format as heading 2

**Comment by meichthys** [comment]
@Engr-AllanG Did you have an automated way of doing this? I have a few thousand notes, so a manual change isn't really an option for me.

**Comment by meichthys** [comment]
To add a little information, the note's page source still shows the H1 tag, but the formatting still seems to be gone:
<img width="789" alt="Screen Shot 2020-09-16 at 12 28 54 AM" src="https://user-images.githubusercontent.com/10717998/93292509-bc628000-f7b3-11ea-8594-90c0f496179b.png">

**Comment by Engr-AllanG** [comment]
@meichthys no I did it manually. At the time I wasn't really using headings for some reason so I only had maybe 50 notes to update. I have since added hundreds of notes so I can understand your pain!  If it is leaving the tag in, then maybe you could do a find/replace with notepad++ or something..? Still, that is very tedious. Without writing a script, i'm not sure the best solution.

**Comment by zadam** [comment]
Hello, yes, this was first brought up in #1156 

Unfortunately there isn't any automated way to fix that yet. Perhaps I can make a migration script to fix that as part of version upgrade - I guess it would make sense to just change H1 into H2, right?

**Comment by meichthys** [comment]
@zadam  Yes, i suppose a migration script would be helpful, but i think we would need to change H1 >H2 > H3 ..etc in order to keep the headings hierarchically accurate. This may be an issue though for the final H6 which wouldn't have an H7 to be changed to(?) - This may be irrelevant though since the H6 is probably very uncommon.

**Comment by zadam** [comment]
I wouldn't go that way - since the "heading downgrade" could also affect headings which are already set correctly.

Instead I would treat H1 as a special case and downgrade it to H2. In some cases it would disrupt the hierarchy but still better than letting CKEditor to convert it to just paragraph.

**Comment by meichthys** [comment]
@zadam Ok, fair enough 👍

**Comment by meichthys** [comment]
The note preview does currently show correctly, just not in the note itself:
![image](https://user-images.githubusercontent.com/10717998/93378665-c378a500-f82a-11ea-9da3-8a9ee721f0ff.png)

**Comment by zadam** [comment]
Yes, the issue is actually with the editing component - there the H1 is disabled so it does not even show it. Read only will display H1 normally...

**Comment by meichthys** [comment]
H1 and H2 were always so close in size anyway, so i don't think i'll even notice a difference when seeing H1 and H2 side by side!

**Comment by meichthys** [comment]
I can confirm that this has been resolved. All `H1`'s have been changed to `H2`'s
