### ISSUE TITLE
Feature Request - Easier VCS integration

### ISSUE THREAD

**Issue by ArisKallergis** [zadam/trilium#1241]
Would it be possible to store notes in separate files, in order to accomodate usage with a Git (or other) repo?

**Comment by zadam** [comment]
Hi, there's a [FAQ entry](https://github.com/zadam/trilium/wiki/FAQ#why-database-instead-of-flat-files) explaining why this is not planned.

**Comment by ArisKallergis** [comment]
Thanks for answering! I just read the FAQ entry (sorry for not doing that earlier).
I wonder if there could be an "export as plain text" option for that use-case. 
Could the structure of the notes and their relations be preserved in plain text metadata?

**Comment by zadam** [comment]
That's sort of what ZIP export does - it contains the tree directory structure with notes in flat files with metadata stored in one big JSON file.
