### ISSUE TITLE
Feature Comparison between Label and Relation for Author filtering

### ISSUE THREAD

**Issue by Potjoe-97** [zadam/trilium#1242]
Hi, 

Not reporting a bug, just asking for some clarifications/advices to organize a library.

Is there any advantages in using relation attributes instead of label attributes to link an author and a book ?
In the wiki, both are mentionned for this particular use case, but I do not really understand what possibility relation attribute adds. For those who take advantage of this feature, do you have any real use case to share ? 

Thanks

**Comment by zadam** [comment]
Hi, label is just a piece of text while relation points to another note.

So if you e.g. want to define a book's author you can use either:

*   label - e.g. \`#author="Peter Watts" - this allows you to e.g. filter based on author etc.
*   relation - here the `~author` relation points to a note called "Peter Watts" - in that note you can e.g. have the author's biography etc.

**Comment by Potjoe-97** [comment]
Thanks for the clarification! Actually, It would be nice to have a kind of midway, and to be able to filter notes with relations, to have the best of two worlds (filtering, and linking).

**Comment by zadam** [comment]
Sure, you can also filter with relations, e.g. for existence with just `~author` or also based on the target note like `~author.title *=* Tolkien`

You could say that relation is a functional superset of labels but with the disadvantage that it requires a target note.

**Comment by Potjoe-97** [comment]
Oh that's great ! I tried various way to filter without finding it. I understand the difference, actually the case of "authors" is a good example to illustrate the various way to tackle indexing in trilium. My bad, I had not seen the wiki update.
Thank you again!
