### ISSUE TITLE
Getting super laggy when document.db>1GB

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1243]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

I've imported all notes from OneNote、Evernote and other platforms
I think there are more than 5k notes in my Trilium notes
It becomes super laggy my mouse is uncontrollable(both Mac&Windows)
Idk if anyone else is in the same situation
Waiting for reply
Thanks

**Comment by zadam** [comment]
Hi, 5K notes shouldn't be a problem, I'm working and testing with larger datasets.

Sometimes the app is temporarily overwhelmed after large import and it's better to restart it, did you try that?

**Comment by Rsose** [comment]
> Hi, 5K notes shouldn't be a problem, I'm working and testing with larger datasets.
> 
> Sometimes the app is temporarily overwhelmed after large import and it's better to restart it, did you try that?

I've added to **Main Note** a label(**archived**) then hide it going faster as before.
