### ISSUE TITLE
Upgrade new version fails!

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1244]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

Download 4.42 version unpack it and run it as admin then I get error warning!
AJavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE: address already in use:::37840
at Server.setupListenHandle [as_listen2] (net.js:1306:16)
at listenlnCluster (net.js:1354:12)
at Server.listen (net.js:1442:7)
at startTrilium

![image](https://user-images.githubusercontent.com/51273534/93358462-cc28a580-f841-11ea-9819-be27cfcd3854.png)

**Comment by Rsose** [comment]
> This normally means there's an older process still running. Check your process list and kill the old trilium process before trying again ...
Hi,I got a bug on importing files(new beta version 0.44.2)
Actually I can't import evernote.enex with new beta version.
but it's working with old version 0.43.4 (I've downgraded the vesion it's ok now)
Check out the error warning.
Hope this will hep:
Uncaught Exception:
TypeError: Cannot set property 'error' of undefined
at SAXStream.<anonymous>
AJavaScript error occurreu "

![image](https://user-images.githubusercontent.com/51273534/93373445-a2797980-f855-11ea-9c42-db99bb50daec.png)

**Comment by zadam** [comment]
Are you sure this is happening on 0.44.2? The error says that it's in 0.43.4 ...

**Comment by Rsose** [comment]
Yeah,I'm sure that's 0.44.2 cos I put all zip files(old & new version) into one folder which named **trilium-windows-x64-0.43.4**
Sorry to have you confused
Look at this screenshot(Version 0.43.4),it's still importing evernote files.(that means works on old version)
I think you should try to import some evernote.enex file on 0.44.2. Importing doesnt work on mine(0.44.2 beta version)

![image](https://user-images.githubusercontent.com/51273534/93377069-d014f180-f85a-11ea-8bee-f2460c6241c8.png)

**Comment by Rsose** [comment]
> Are you sure this is happening on 0.44.2? The error says that it's in 0.43.4 ...

Hi,there is another bug.
When I import larger files will cause duplicate importing files by lags
![image](https://user-images.githubusercontent.com/51273534/93378708-22efa880-f85d-11ea-8060-c10772f4e6aa.png)

**Comment by Rsose** [comment]
After importing evernote.enex on 0.43.4
I've Tried to Switch to new beta version 0.44.2 then failed to start Trilium notes(Software)
![image](https://user-images.githubusercontent.com/51273534/93385657-d610cf80-f866-11ea-84f5-cd66bc8b6152.png)

**Comment by Rsose** [comment]
> After importing evernote.enex on 0.43.4
> I've Tried to Switch to new beta version 0.44.2 then failed to start Trilium notes(Software)
It's pretty weird Idk how to handle them.I think it's tough to fix 
> ![image](https://user-images.githubusercontent.com/51273534/93385657-d610cf80-f866-11ea-84f5-cd66bc8b6152.png)
