### ISSUE TITLE
Adding List Ordering Feature with Frontend Script

### ISSUE THREAD

**Issue by Wingysam** [zadam/trilium#1245]
I'm attempting to add list ordering like VSCode Control+Arrows to order lines. I know this would be done with a Frontend Script and the internal instance of CKEditor but I can't figure out how to actually do it. This API seems relevant:

https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_view-View.html

**Comment by zadam** [comment]
Hi, frankly this seems to be rather advanced thing to do and I don't know myself. AFAIK CKEditor team has some plans regarding reordering list items/paragraphs, see e.g. ckeditor/ckeditor5#2060

**Comment by Wingysam** [comment]
Okay, thank you :)
