### ISSUE TITLE
Question - how to find number of notes in database?

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1246]
I don't see how to find the number of individual notes in the database

**Comment by zadam** [comment]
Since some time ago part of demo document are some stat scripts:

![](https://user-images.githubusercontent.com/617641/93389616-af559780-f86c-11ea-8a17-6cc48c5f93ff.png)

Alternatively this info is also periodically logged:

```
00:00:57.604 Notes deleted: 438, not deleted 14315
00:00:57.612 Note revisions deleted: 70, not deleted 2866
00:00:57.634 Branches deleted: 536, not deleted 14849
00:00:57.655 Attributes deleted: 5497, not deleted 29290
00:00:57.655 API tokens deleted: 0, not deleted 4
```

**Comment by Engr-AllanG** [comment]
Awesome, thanks
