### ISSUE TITLE
How I can remove notes' label？

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1248]
I noticed my imported notes there are tons of labels!
Is there some way like selecting all of them(ALT+A) then remove all labels at once!
Processing 1 by 1 is too time-consuming
Waiting for reply
thanks!

**Comment by zadam** [comment]
In 0.44 (beta), it's possible:

![](https://user-images.githubusercontent.com/617641/83362460-b5913800-a391-11ea-9d61-cfd32d87e3cd.png)

It's just input box so exactly ALT+A, backspace/delete and enter will save the changes. In 0.43 and older this is not possible.
