### ISSUE TITLE
What's the maximum number of search results?

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1249]
For example, my search results are 80-90 notes (but,actually the results should be more than these numbers)
But after I deleted some of them. Refreshing the **Saved Search** just shows some other results that are different.
So the search does not search the entire content of the results, but only a portion of the number of results.
test on 0.43.2

**Comment by zadam** [comment]
The result list is limited to 200 entries.

**Comment by Rsose** [comment]
> The result list is limited to 200 entries.

Thanks
Is this amount customizable?Sometimes I may need more entries to find the desired result

**Comment by zadam** [comment]
This limit is currently hardcoded. However, for the next release (0.45) I plan large overhaul of search UI and some form of paging could be included.

**Comment by Rsose** [comment]
> This limit is currently hardcoded. However, for the next release (0.45) I plan large overhaul of search UI and some form of paging could be included.
OK many thanks
