### ISSUE TITLE
 A question about buttons

### ISSUE THREAD

**Issue by yunzhongci** [zadam/trilium#1250]
I can't speak English, so this text is translated by machine. If the description is not accurate, I'm very sorry.

In use, I also made a button in the style of weight tracker, and then found a problem. If there are multiple buttons at the same time, and the name of the button（title） is Chinese, and the number of Chinese characters is the same, only one of them can be displayed.
![image](https://user-images.githubusercontent.com/49399931/93467749-a7efc600-f920-11ea-8b6e-265a0fe13346.png)

When the name of (title) is Chinese and the number of characters is the same, the button can only display one, and it cannot be displayed at the same time.
In addition, counting the number of characters is not good for Chinese support, which should be the same reason

-------------

Put a paragraph of Chinese, if there is a Chinese can better describe this problem better
放一段中文吧，如果有会中文的能更好的描述一下这个问题就更好了
我不会英语，所以这一段文字是用机器翻译的，如果描述不准确，非常抱歉。
我在使用中，使用Weight tracker 的样式同样制作了一个按钮，然后发现了一个问题，如果同时存在多个按钮，且按钮的名字（title）为中文，且中文的字数相同的时候，只能显示其中一个。
当（title）的名字为中文，和字数一样的时候，按钮只能显示一个，无法同时显示。
另外，统计字数对中文支持不好，应该也是同样原因

**Comment by zadam** [comment]
Hi, this is now fixed and will be released in 0.44.3.

From text we computed element ID, but unicode was not supported here and then the resulting IDs clashed.
