### ISSUE TITLE
Can't export large files as html in zip or Markdown

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1251]
I tried to export all my notes(4k-8k notes)
It's stopped at some point I was waiting for hours with no response, and in the end I just closed the program.
Hope there will be improvements for large number of files
test on (both versions 0.43 & 0.44)

**Comment by zadam** [comment]
Hi, can you post the application logs?

**Comment by Rsose** [comment]
> Hi, can you post the application logs?
sure
[trilium0917.log](https://github.com/zadam/trilium/files/5241223/trilium0917.log)

**Comment by zadam** [comment]
Weird, the log suggests that the export has finished successfully:

> 17:40:23.724 INFO  Sending message to all clients: {"type":"task-succeeded","taskId":"AVahr5a1mX","taskType":"export"} 

Although there is a weird long pause of 8 minutes:

> 17:32:30.689 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"AVahr5a1mX","taskType":"export","progressCount":4214}
> 
> 17:40:23.719 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"AVahr5a1mX","taskType":"export","progressCount":4319}

**Comment by Rsose** [comment]
> Weird, the log suggests that the export has finished successfully:
> 
> > 17:40:23.724 INFO  Sending message to all clients: {"type":"**task-succeeded**","taskId":"AVahr5a1mX","taskType":"export"}
> 
> Although there is a weird long pause of 8 minutes:
> 
> > 17:32:30.689 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"AVahr5a1mX","taskType":"export","progressCount":4214}
> > 17:40:23.719 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"AVahr5a1mX","taskType":"export","progressCount":4319}

I know but nothing is exported...and the state of Trilium Notes was always running in the backgroud!
The file that was supposed to be exported has the extension
However, in my case there are no extensions, and the exported folder doesn't take any files(zip or html). 
Multiple attempts with the same result
