### ISSUE TITLE
How to change my backup directory in Windows?

### ISSUE THREAD

**Issue by Magic-King** [zadam/trilium#1253]
Hi,
I am using the trilium in windows for a long time , but  I have some question with backup.
As the title, I wanna know how to backup my note in trilium in the path I want?It's upset me that trilium in windows always backup the note in the C:\ where  as we know it's a danger place.

**Comment by zadam** [comment]
You can change the [Data directory](https://github.com/zadam/trilium/wiki/Data-directory) with `TRILIUM_DATA_DIR` which will also change the backup location.

> It's upset me that trilium in windows always backup the note in the C:\\ where as we know it's a danger place.

Why is C:\\ a dangerous place?

**Comment by Magic-King** [comment]
> You can change the Data directory with TRILIUM_DATA_DIR which will also change the backup location.

I find `path\to\AppData\Roaming\trilium-data\config.ini` ,but it seems  that there is no suitable place to write `TRILIUM_DATA_DIR=`  :(
And I wonder if there exist any place to change my backup location in the trilium for windows.I just wanna to change it in the Application in place of finding the `config.ini` to change.

P.S. emmm,my windows may often crush by windows update, and C;\ is where I have installed my windows

**Comment by zadam** [comment]
`TRILIUM_DATA_DIR` is not in a config.ini, it is an environment variable. After you change that you should also move your original `trilium-data` directory to a new target directory, otherwise Trilium won't find it.

**Comment by Magic-King** [comment]
It means that I set `TRILIUM_DATA_DIR` in my windows' environment  variable ？

**Comment by zadam** [comment]
Yes.

**Comment by Magic-King** [comment]
Thank you for your help.I have successfully solve this problem.  👍 👍 👍
