### ISSUE TITLE
Note revision timestamp is always equal to note creation time

### ISSUE THREAD

**Issue by FliegendeWurst** [zadam/trilium#1254]
New revisions are not saved with the correct timestamp (the note creation time is copied).

I'm using the latest beta release (v0.44.2).

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it has been fixed now.

**Comment by FliegendeWurst** [comment]
Just tried the new beta v0.44.3.
When editing an old note, the revision timestamp is set to the time I opened Trilium.

**Comment by FliegendeWurst** [comment]
Just figured out why: DB migration 169 changed the content of every note (fixing #1240), which updated the note content timestamps.

**Comment by FliegendeWurst** [comment]
Some SQL to correct the DB (should be used on the client and the sync server):
```sql
UPDATE note_contents
SET dateModified=notes.dateModified, utcDateModified=notes.utcDateModified
FROM (SELECT noteId, dateModified, utcDateModified FROM notes) AS notes
WHERE note_contents.noteId=notes.noteId AND note_contents.dateModified LIKE "2020-MM-DD hh:mm:ss.___+____"
```
The `LIKE` parameter has to be set to the migration time.

**Comment by zadam** [comment]
Good catch, I fixed the migration script to update only the notes with changes, thus mitigating the issue for people who did not upgrade yet.
