### ISSUE TITLE
Can we add a quick note-entries feature？

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1255]
Sometimes I need to create many notes at once about 50-100 notes（notes + childnotes)
Similar to the import feature, but, is the quick create(import)notes feature
Note tree form:( i.e. **Rapid note entries**)
```
1 (1st Main Note)
    1.1(Child note)
    1.2(Child note)
        1.2.1(Child-Child-Note)
    1.3(Child note)
2(2nd Main note)
    1.1(Child note)
    1.2(Child note)
        1.2.1(Child-Child-Note)
            1.2.1.1（Child-child-child-note)
    1.3(Child note)
    etc…
```
Each **TAB** represents a new child note.
This makes it easy to create quickly, otherwise, it's too tedious to create new notes' names one by one.
I can write the Note Tree's name in advance in Excel or Trilium's Outline then use Rapid Note entries to create all of them.
Waiting for a reply
Thanks

**Comment by zadam** [comment]
Using keyboard shortcuts `CTRL-P` and `CTRL-O` should provide fast enough workflow IMHO ...
