### ISSUE TITLE
No Rust code highlight

### ISSUE THREAD

**Issue by junknet** [zadam/trilium#1256]
the latest version;
![2020-09-20_13-58](https://user-images.githubusercontent.com/55597646/93702235-b967e680-fb49-11ea-917f-bdf93af5a688.png)
If you really can't figure it out, I think you can add a button that opens with some other editor software.
Or add a shortcut to open the external editor.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it is now fixed

**Comment by mydoghasfleas** [comment]
Not sure what I am missing, but I don't see Rust as an option for a code block:

![image](https://github.com/zadam/trilium/assets/125179869/1dd690f4-47a7-459a-98e4-03178613281d)
