### ISSUE TITLE
Multi-notes Duplicate Feature

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1259]
I notice that can't duplicate(batch) many notes at once
I tried to select multi-notes then copy(Not clone) or duplicate them
Neither way seems to be working.
E.g I need many notes(type:HTML) how Can I copy or duplicate them,is not easy by far!
If I use Copy feature Trilium gives warning tip:**This note already exist in the target.**
Solution: Now is duplicate them by clicking
Waiting For a Reply
Thanks

**Comment by zadam** [comment]
Context menu "Duplicate" action now allows multiple notes at once.
