### ISSUE TITLE
Search - duplicate results for note title + body

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1262]
Running the 0.44.3-beta.

When a search term occurs in both the title and the body of a note, that note is listed twice in the search results.

Example note:

> test-note with specific-search-term
> ----
> This note is about specific-search-term.

Screenshot of the search issue:

![image](https://user-images.githubusercontent.com/39531/93983634-1d292400-fd83-11ea-8c68-fe4ca9081d12.png)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it has been fixed.
