### ISSUE TITLE
How to search Note ID on new beta version?

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1263]
Hi
Idk how to search NOTE ID on 0.44.3 beta version
I tried doing #in or @in = （Input Note's ID）but it didnt work.
Reading **[New Search Rule](https://github.com/zadam/trilium/wiki/Search) ** I haven't found any context about Note's ID
Seems it doesnt support on new beta version

Only way is to search Note ID directly(e.g X9rS3bvWh99e)
(but this way is imperfect,cos they can't combine with != operator.)
Waiting for a reply
thanks

**Comment by zadam** [comment]
You can search with `note.noteId=0OIpfS8v1MSn` or with negation `note.noteId != 0OIpfS8v1MSn`

**Comment by Rsose** [comment]
> You can search with `note.noteId=0OIpfS8v1MSn` or with negation `note.noteId != 0OIpfS8v1MSn`

Test on 0.44.3 beta
Search in subtree appeared old search rule in the Search Pane

![image](https://user-images.githubusercontent.com/51273534/94196768-24504f00-feb5-11ea-9317-bdd2523952a1.png)
![image](https://user-images.githubusercontent.com/51273534/94196641-f834ce00-feb4-11ea-93c9-c8efc27e1dd4.png)

**Comment by zadam** [comment]
Thanks, fixed now. Correct expression to limit search in a subtree is now `note.ancestors.noteId=0OIpfS8v1MSn`

**Comment by Rsose** [comment]
Another question:
1)For Old Search this way works (test on 0.43.4)
>@in=5YJAoTs9AfRU AND @in!=5xf3f5UczuOP AND @text*=*history
5YJAoTs9AfRU(The folder(Parent note) where I put normal notes
5xf3f5UczuOP(The folder(Parent note) where I put SAVED SEARCH results.
This allows me to search all results without SAVED SEARCH results

2)But in the same condition **New Search** wont work (test on 0.44.2)
>note.noteId=5YJAoTs9AfRU AND note.noteId!=5xf3f5UczuOP AND note.text*=*history

I can't figure out where is the problem.
Can you check it out?
Thanks

**Comment by zadam** [comment]
There was a bug in `note.text` searching, this is now fixed.

But you should be able to do almost exactly same search with `history note.noteId=5YJAoTs9AfRU AND note.noteId!=5xf3f5UczuOP`

**Comment by Rsose** [comment]
> history note.noteId=5YJAoTs9AfRU AND note.noteId!=5xf3f5UczuOP

This method doesn't work either
![image](https://user-images.githubusercontent.com/51273534/94201889-ea834680-febc-11ea-95f4-1fa5688b4bc6.png)

**Comment by zadam** [comment]
I didn't read your original query correctly. You need to replace old `@in` with `note.ancestors.noteId` so it should be this:

`history note.ancestor.noteId=5YJAoTs9AfRU AND not(note.ancestor.noteId=5xf3f5UczuOP)`

Although I'm not sure I fully understand your system with saved search results so ...

**Comment by Rsose** [comment]
> I didn't read your original query correctly. You need to replace old `@in` with `note.ancestors.noteId` so it should be this:
> 
> `history note.ancestors.noteId=5YJAoTs9AfRU AND not(note.ancestors.noteId=5xf3f5UczuOP)`
> 
> Although I'm not sure I fully understand your system with saved search results so ...

Thanks it works.Search expression becomes such long
