### ISSUE TITLE
Can we add an option to Search tips?

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1265]
Hi
Can we add an option(DO NOT SHOW AGAIN)
When the display is too narrow, these tips will override the Search Bar（Search Pane)
It's annoying to popup everytime
Cos I will not read these tips...

Thanks

![image](https://user-images.githubusercontent.com/51273534/94248123-51851780-ff1e-11ea-9f70-3ebc5ce2aa2e.png)

**Comment by zadam** [comment]
Focus for 0.45 is new search UI and this will disappear / move elsewhere.

**Comment by Rsose** [comment]
> Focus for 0.45 is new search UI and this will disappear / move elsewhere.

Great!
