### ISSUE TITLE
[bug] entering internal note link does nothing (@0.44.4 / OSX )

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#1268]
[trilium-2020-09-25.log](https://github.com/zadam/trilium/files/5282131/trilium-2020-09-25.log)
all in the title :-)

maybe worth mentioning: it seems all pre-44.4 internal links do not register/show at 'What Links Here'-panel.
– is that expected because of the new search+syntax system? or possibly part of the bug?

oh, an GREAT many thanks for this new version w/ all its leaps forward!

**Comment by zadam** [comment]
Hi, which method of entering link do you use?

**Comment by lerone-b** [comment]
hey,
+ thx for attention,

- was trying via formatting panel, first of all. ('@' doesn´t work for this any longer, if I am getting it right? :-) )
see attach
![Screenshot - 2020-09-25 17 12 37](https://user-images.githubusercontent.com/11589804/94284357-88752080-ff52-11ea-8c8e-95c2a5cd99b9.jpg)

**Comment by lerone-b** [comment]
ok - after retrying with alt-L I have to say: semi-wise at least my fault / confusion. it works now.
– but maybe its instructive why I 'failed': the 'internal link' + 'cut' icons were active w/o anything marked. thus it led me to think I can insert a link w/o marking text before. which it doesn´t.

so, if that is by design, this kind of behaviour seems fine. but maybe then also 'grey out' the (non-working) options.

+ sry, if I was not looking deep enough initially... :-}
