### ISSUE TITLE
URL Preview visual issue

### ISSUE THREAD

**Issue by Heniker** [zadam/trilium#1272]
Url preview should be below **jump to** dialog or closed when **jump to** dialog opens.
![image](https://user-images.githubusercontent.com/22645200/94370131-c1e69100-00f6-11eb-8f3a-b22c6bdeaebf.png)

It should probable behave in the same way as formatting options.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it has been fixed and balloon is now on a lower z-index level than dialogs.
