### ISSUE TITLE
inherited iconClass attribute not honored in 0.44.4

### ISSUE THREAD

**Issue by elementc** [zadam/trilium#1273]
I identified this issue after upgrading to 0.44.4.
I'm on Ubuntu 20.04 linux and using the deb package.

My day note template (and my other templates!) have iconClass specified as an attribute:
![daytemplate](https://user-images.githubusercontent.com/4315099/94374179-5503d480-00bf-11eb-9bea-48a7d5d97550.png)

Indeed, my various templates show up in the tree with their selected icons:
![templates](https://user-images.githubusercontent.com/4315099/94374223-91cfcb80-00bf-11eb-8785-78960ec787b7.png)

However, after the upgrade, my various template instances are only displaying their default note/folder icons, but manually adding iconClass to any of them (observe the "Journal" root node) does still work.

![journal](https://user-images.githubusercontent.com/4315099/94374320-4964dd80-00c0-11eb-9599-a2c72b68d0a1.png)

If you're a little underwater, I'm happy to take a look at putting together a PR on this one. Trilium has been super helpful to me in just the short month I've been using it and I'm excited to be able to give back.

**Comment by zadam** [comment]
Hi, unfortunately I'm not able to reproduce this issue - inherited iconClass seems to work correctly for me.

Does the iconClass show up among inherited attributes in the "templated" notes, like this?

![](https://user-images.githubusercontent.com/617641/94376046-4c8bb800-0118-11eb-9514-75480eb138aa.png)

**Comment by elementc** [comment]
Indeed it is! Here's a screenshot from the web UI, synced with the same client.
![inherited](https://user-images.githubusercontent.com/4315099/94376105-3c022000-00cd-11eb-953b-3652d703d688.png)

Any particular logs that would be helpful for me to share?

**Comment by zadam** [comment]
That is pretty weird since Trilium seems to be aware of that inherited attribute...

Just to be sure - reload of the page in the browser does not help, right?

**Comment by elementc** [comment]
Refreshing did not help, no.
I changed the iconClass on the template and it did propagate out, however. Is there perhaps a cache that I invalidated in that change?

**Comment by zadam** [comment]
Yes, there is a cache and the code to choose icon uses it. However this cache is in frontend memory and is reloaded together with the page.

There is also a backend cache which has longer lifetime (until restart/stop of backend) but then this cache is not used for choosing icons ...

So the mystery remains ...

**Comment by elementc** [comment]
Let me see if I can use anonymize-database against a backup to get you a useful repro :)

**Comment by elementc** [comment]
Zipped video of repro steps:

1. Load anonymized db (I anonymized my before-upgrade backup)
2. Click around in a number of day notes, which all use the default icons.
3. F5 a few times.
4. Close and reopen.
5. Observe the default icons are still used.
5. Open the template.
6. F5.
7. Observe that the correct custom icons have propagated (I guess my earlier "changing the iconClass on the template" was actually "open the template at all".)
8. Close. 
9. Replace the active document with the anonymized DB again.
10. Repeat for good measure.

[trilium_repro.zip](https://github.com/zadam/trilium/files/5289198/trilium_repro.zip)

And here's a copy of the anonymized DB:
[anonymized-document.zip](https://github.com/zadam/trilium/files/5289205/anonymized-document.zip)

**Comment by wwwald** [comment]
Just confirming that I'm currently having the same problem with 0.44.4.

- for me, it's a mix: some notes/subtrees show default icons, some a mix of default + template ones, some are completely correct. See screenshot below.
- refreshing the page _sometimes_ helps but not systematically

![image](https://user-images.githubusercontent.com/39531/94396227-c72cf580-0161-11eb-8881-59bc6a30731e.png)

Nothing strange to be seen in frontend or backend logs. 
Just noticing this:

    08:09:39.190 Slow POST /api/tree/load took 10ms

in the backend log, but that's probably not related?

**Comment by zadam** [comment]
@elementc , thanks a lot for the anonymized database, this allowed me to reproduce and fix the issue!
