### ISSUE TITLE
It seems that I've lost my changes.

### ISSUE THREAD

**Issue by alohaia** [zadam/trilium#1274]
**Log file:** [trilium-2020-09-28.log](https://github.com/zadam/trilium/files/5292839/trilium-2020-09-28.log)

**Version**: 0.43.4
**System**: manjaro linux with cinnamon

I wonder if there is any function to save my changes manually and I just don't find it. If not, can you add this function?

**Comment by zadam** [comment]
Hi, ordinary changes to notes are saved automatically every second so there's no need for explicit/manual save button.

Could you describe in more detail the problems you're observing? Does it happen everytime or was it a single problem?

**Comment by alohaia** [comment]
It only happened once. The Auto save function work ed well in the previous use. But it just doesn't works for this time. I exited after I finish ed my work. And when I opened it again, most of my changes disappeared.

And unfortunately, I'm not able to find out more information. If there's nothing seemingly wrong, I suppose that this problem may be caused by my operating system. It seems not really compatible with trilium.

P.S Trilium works well on my linux system with  with KDE without this problem.

**Comment by alohaia** [comment]
It seems not the fault of trilium.

**Comment by ice1000** [comment]
> It seems not the fault of trilium.

Care to elaborate? What actually happened?

**Comment by alohaia** [comment]
> Care to elaborate? What actually happened?

I knew few details, it just disappeared, but it doesn't happen again, fortunately.
