### ISSUE TITLE
Wish to add a function to collapse after expand the notes (which  is book note or empty note).

### ISSUE THREAD

**Issue by chncho** [zadam/trilium#1276]
Wish to add a function to collapse after expand the notes(which  is book note or empty note)..We can only expand it , but cannot collapse it after that.

![2020-09-29_11-10](https://user-images.githubusercontent.com/6135686/94510773-29612580-024a-11eb-970d-eb67cc640fd7.png)

**Comment by zadam** [comment]
Not the same but you can collapse individual expanded notes.

**Comment by chncho** [comment]
> Not the same but you can collapse individual expanded notes.

Thanks to reply, I found it , but it is a bit troublesome.
