### ISSUE TITLE
API - What is replacing api.createNote in 0.44.4 ?

### ISSUE THREAD

**Issue by Potjoe-97** [zadam/trilium#1277]
Hi, 

I've been struggling to update my scripts to 0.44.4, especially regarding the new version of api.createNote.

In the current state, the line: 
```
const categoryNote = (await api.createNote(categoryRootNote.noteId, assignedCategory, "", {
                    attributes: [ { type: "label", name: labelName, value: assignedCategory } ]
                })).note;
```

returns the error :
`ERROR: Execution of script "Livre Code" (bN80XWBZhdo3) failed with error: Load of script note "Livre Code" (bN80XWBZhdo3) failed with: Cannot read property 'note' of undefined`

(full script in #1188)

In the API documentation, createNote is labelled deprecated, but we're told to use "createNote" instead...
What have been replacing this method in 0.44.4 ? I retested in 0.43.4, no issue. 

Thanks

**Comment by zadam** [comment]
Hi, as mentioned in #1275, there was a regression in the deprecated .createNote() API call.

Otherwise I updated the JSDoc:

> please use createTextNote() with similar API for simpler use cases or createNewNote() for more complex needs

**Comment by Potjoe-97** [comment]
Thanks for the updated doc!
