### ISSUE TITLE
Can we use CKEditor‘s function of “Export to Word” or "Export to PDF"  in any note?

### ISSUE THREAD

**Issue by huwei96** [zadam/trilium#1279]
<img width="508" alt="Snipaste_2020-09-30_20-43-38" src="https://user-images.githubusercontent.com/28172625/94686655-b517a680-035d-11eb-98a8-f1cb14546944.png">

**Comment by zadam** [comment]
Hi, two things:

*   not all CKEditor's features are enabled
*   both of these export features are premium - you need to pay for them to CKSource. For that reason Trilium can't possibly enable them.
