### ISSUE TITLE
Richt-click context-menu, and text format menu overlap.

### ISSUE THREAD

**Issue by generic-user** [zadam/trilium#1281]
![doTHQ6NJuW](https://user-images.githubusercontent.com/1516035/94811162-4b4adb80-03f5-11eb-979b-0de6f733b68d.gif)

App version: 0.44.4 (2020-09-24T23:33:36+02:00) (748979eafd44704af42df54f4195d118dec891ae)

**Comment by zadam** [comment]
Hi, thanks for reporting. Unfortunately I was not able to figure out how this could be fixed - how to stop propagation of the event from electron. This seems to be platform dependent - on the server edition this problem does not seem to occur.

So for the time being I implemented workaround only - context menu has higher z-index so it will cover the balloon editor toolbar.

**Comment by generic-user** [comment]
Hi, thanks for the quick workaround. I can live with that until you find a permanent solution.
