### ISSUE TITLE
Broken SingleFile2Trilium Render Notes 

### ISSUE THREAD

**Issue by Airradda** [zadam/trilium#1282]
Trilium Version: 0.44.4

After upgrading from 0.43 to 0.44, my render notes from the SingleFile2Trilium script no longer render properly and appear [blank](https://i.imgur.com/9P7VIbX.png). I'm guessing that it the new sanitation because they seemingly have no <body> to them [anymore](https://i.imgur.com/17qaso3.png). The only other thing of note that I could see was this line in the Dev Tools Console:
 `Refused to frame '' because it violates the following Content Security Policy directive: "default-src *". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback`

Log:
23:21:28.446 DB size: 970543 KB
23:21:29.214 App HTTP server starting up at port 37840
23:21:29.214 {
  "appVersion": "0.44.4",
  "dbVersion": 170,
  "syncVersion": 16,
  "buildDate": "2020-09-24T23:33:36+02:00",
  "buildRevision": "748979eafd44704af42df54f4195d118dec891ae",
  "dataDirectory": "/home/airradda/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
23:21:29.214 CPU model: AMD Ryzen 7 2700X Eight-Core Processor, logical cores: 16 freq: 4140 Mhz
23:21:29.216 Listening on port 37840
23:21:29.289 Keyboard action showAttributes found in database, but not in action definition.
23:21:29.290 Could not register global shortcut Ctrl+Alt+P
23:21:29.304 Generated CSRF token ENmelqVM-rCITOWnfiQT5XQfDow8wAgjj_uU with secret _csrf=8IACEJkJXPugvc5Wrn8RpfOn; Path=/
23:21:29.317 Slow GET / took 14ms
23:21:29.698 GET /api/options took 0ms
23:21:29.710 Slow GET /api/tree took 11ms
23:21:29.714 Keyboard action showAttributes found in database, but not in action definition.
23:21:29.715 GET /api/keyboard-actions took 1ms
23:21:29.717 GET /api/keyboard-shortcuts-for-notes took 0ms
23:21:29.718 GET /api/script/widgets took 1ms
23:21:29.722 GET /api/notes/download/XTZOzyRS5IfN took 2ms
23:21:30.153 GET /api/notes/qbOcrpQcuvHi took 1ms
23:21:30.155 POST /api/tree/load took 1ms
23:21:30.173 Slow GET /api/script/bundle/AvgP3XRYVlEn took 17ms
23:21:31.196 Slow GET /api/similar-notes/qbOcrpQcuvHi took 44ms
23:21:31.198 GET /api/notes/qbOcrpQcuvHi/revisions took 1ms
23:21:31.238 Slow POST /api/tree/load took 18ms
23:21:31.798 GET /api/script/startup took 1ms
23:21:32.336 Nothing to push
23:21:32.346 Finished pull
23:21:32.347 Nothing to push
23:21:33.224 Slow query took 388ms: SELECT noteId AS id, hash FROM note_contents  ORDER BY noteId
23:21:33.247 Content hash computation took 415ms
23:21:33.247 Content hash checks PASSED
23:21:35.153 Slow POST /api/recent-notes took 12ms
23:21:49.145 Notes deleted: 394, not deleted 1883
23:21:49.145 Note revisions deleted: 18, not deleted 271
23:21:49.146 Branches deleted: 803, not deleted 1884
23:21:49.147 Attributes deleted: 4063, not deleted 4016
23:21:49.148 API tokens deleted: 0, not deleted 3
23:21:49.770 Slow query took 614ms: 
                    SELECT noteId
                    FROM notes
                      JOIN note_contents USING (noteId)
                    WHERE isDeleted = 0
                      AND isProtected = 0
                      AND content IS NULL
23:21:49.793 All consistency checks passed (took 649ms)
23:22:04.641 GET /api/notes/FyjdYwTdHXxj took 0ms
23:22:04.666 PUT /api/options took 1ms
23:22:05.738 Slow GET /api/similar-notes/FyjdYwTdHXxj took 97ms
23:22:05.750 GET /api/notes/FyjdYwTdHXxj/revisions took 1ms
23:22:05.761 Slow POST /api/tree/load took 11ms
23:22:06.884 GET /api/notes/CItFr9UFYugx took 0ms
23:22:06.888 GET /api/script/bundle/laRKzmBrVJnd took 2ms
23:22:06.903 POST /api/tree/load took 0ms
23:22:06.933 POST /api/tree/load took 1ms
23:22:06.939 PUT /api/options took 0ms
23:22:07.900 Slow GET /api/similar-notes/CItFr9UFYugx took 16ms
23:22:07.902 GET /api/notes/CItFr9UFYugx/revisions took 1ms
23:22:07.913 POST /api/tree/load took 1ms
23:22:11.882 POST /api/recent-notes took 0ms

**Comment by zadam** [comment]
Hi, this is probably caused by helmet library upgrade which started enforcing stronger default CSP than before which doesn't allow iframe. I will look at this.

**Comment by zadam** [comment]
Fixed by disabling CSP in helmet.
