### ISSUE TITLE
Gap between Title & content.

### ISSUE THREAD

**Issue by 404-unf** [zadam/trilium#1286]
![image](https://user-images.githubusercontent.com/24972285/95013181-4340a500-065c-11eb-82aa-1557235dfa77.png)
The above image shows a gap between titile and first line of content... it is kind of annoying to have so much empty space inbetween them.

**Comment by 404-unf** [comment]
![image](https://user-images.githubusercontent.com/24972285/95014365-f9f45380-0663-11eb-80ed-4acf21c58ed1.png)
This is how it should look like.

**Comment by zadam** [comment]
Hi, yes, I agree, I reduced the top margin of first paragraph in text.
