### ISSUE TITLE
Use iframe instead of frame in exported html?

### ISSUE THREAD

**Issue by idelem** [zadam/trilium#1289]
I noticed that the exported html documents use `<frame>` which is deprecated and replaced by `<iframe>` in html5. I want to deploy some pages to the web and make them responsive, so it'd be nice to have modern web elements. 

An example html snippet would be:

```
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <iframe name="navigation" class="navigation" src="navigation.html"></iframe>
    <iframe name="detail" class="detail" src="something.html"></iframe>
</body>
```

and the rest can be done in css.

---

edit:

For mobile support, the following meta is favorable:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

This will help with page scaling.

**Comment by zadam** [comment]
Hi, iframes and frames are functionally almost equivalent, but to use iframes I would have to apply extra styling to get the same look while that is "for free" with frames (since splitting the screen is what frames are intended for). So I'm not sure what would we gain with switch to iframe.

BTW I added the meta tag.

**Comment by idelem** [comment]
@zadam Thanks for adding that meta tag. I experimented a little yesterday, and I think the main problem with frames (and iframes) is external links. Most browsers won't allow opening links in a frame by default. So perhaps something like `<a href="..." target="_blank"></a>` which opens the link in another tab/window?

**Comment by zadam** [comment]
Interesting, I didn't know about this limitation. Anyway changing the \<a> elements has some issues, I solved it by adding `<base target="_parent">` element which will allow opening the external links in the whole frame.
