### ISSUE TITLE
Changed Tab Behavior in Tables

### ISSUE THREAD

**Issue by ThomasWeber** [zadam/trilium#1290]
I generally use tables within most of my notes, recently upgraded from 0.33.7 and noticed that the tab behavior has changed a lot.

**Old Behavior in v0.33.7, consistent with Excel and tables in other notetaking apps like OneNote**
Tab, Shift+Tab = Switch between cells
Tab in the last column = moves to next row; creates a new row if one doesn't exist

**New Behavior in 0.44.5**
Tab = indents the contents of the cell (regardless of where the cursor is), not sure there is ever a use case for this in tables, but maybe?
Tab in the last row = also indents, creating a new row requires switching to mouse input
I have found that ctrl+left, ctrl+right does navigate left and right between cells, but this is not consistent with tables in other software.

Is this the intended behavior? Is there a way to restore the previous behavior? is there any way to create a row with keyboard input now? 

Thanks!

**Comment by zadam** [comment]
Hi, yes, I recently noticed this as well and find it also annoying.

this is caused by feature where TAB in normal text should indent the text, but this "works" also in table cells which is not intended. I will take a look if this is possible to fix.

**Comment by zadam** [comment]
TAB handler now detects if the current selection is within table cell, in such case standard handling of tab switching will be executed. Outside of table, TAB will indent.
