### ISSUE TITLE
Statistics -> Largest notes error ? 

### ISSUE THREAD

**Issue by LorenAmelang** [zadam/trilium#1291]
0.44.4

I was looking for a list of tag= values. All the other Statistics items worked, but "Largest notes" fails: 

15:00:19.429 GET /api/notes/j4Vc2ceoSDNQ took 1ms
15:00:19.527 GET /api/script/bundle/E7DW03Etib1k took 1ms
15:00:19.549 POST /api/script/exec took 1ms
15:00:19.551 PUT /api/options took 1ms
15:00:19.559 JS Error: Execution of JS note "template" with ID E7DW03Etib1k failed with error: Load of script note "js" (GCYvt1cNs0j1) failed with: notes is not iterable
Stack: Error
    at Object.v [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:1:74499)
    at Object.showAndLogError (http://127.0.0.1:37840/app-dist/desktop.js:1:55470)
    at Object.executeBundle (http://127.0.0.1:37840/app-dist/desktop.js:1:21665)
15:00:20.450 Slow GET /api/similar-notes/j4Vc2ceoSDNQ took 21ms
15:00:20.451 GET /api/notes/j4Vc2ceoSDNQ/revisions took 0ms
15:00:20.454 POST /api/notes/j4Vc2ceoSDNQ/link-map took 1ms

![2020-10-05 (1)](https://user-images.githubusercontent.com/1297090/95137254-8a8e6a80-071c-11eb-8204-da90cd26aed7.png)

Not a huge problem, but there are times it would be nice to know...  

Also, "Attribute count" shows the number of tag= items in the pie chart, but under that it shows "Attribute name" and Count for 36 items that are not in the chart, not things I'm aware of using. What does that mean?

**Comment by FliegendeWurst** [comment]
The database schema was modified a while ago. Open the javascript file (location: Largest Notes / template / js) and replace the SQL query at the beginning of the file with:
```sql
SELECT
    notes.noteId,
    LENGTH(note_contents.content) + COALESCE(SUM(LENGTH(note_revision_contents.content)), 0) AS size
FROM notes
JOIN note_contents ON notes.noteId=note_contents.noteId
LEFT JOIN note_revisions ON note_revisions.noteId=notes.noteId AND note_revisions.isErased = 0
LEFT JOIN note_revision_contents ON note_revisions.noteRevisionId=note_revision_contents.noteRevisionId
WHERE notes.isDeleted = 0
GROUP BY notes.noteId
ORDER BY size DESC
LIMIT 100
```
@zadam: the latest demo document doesn't contain this statistic. Is that intentional?

**Comment by zadam** [comment]
@FliegendeWurst I can't remember but I might have removed it because of the removal of contentLength. Anyway I added it back (and fixed with your modified query).
