### ISSUE TITLE
Can you support code highlighting?

### ISSUE THREAD

**Issue by R0FGV** [zadam/trilium#1292]
In version 0.44.6, when I insert a piece of code, can the code be highlighted?

![image](https://user-images.githubusercontent.com/19688305/95410348-0aa81080-0967-11eb-8a9b-cbd1970931e8.png)

**Comment by zadam** [comment]
Code snippets inside text notes can't be highlighted. That's a CKEditor issue.

For longer snippets I recommend using code notes which support highlighting:

![](https://user-images.githubusercontent.com/617641/95434979-42588d80-0952-11eb-9c94-f2140bdd0025.png)
