### ISSUE TITLE
can it open local files by default programs in “link”？

### ISSUE THREAD

**Issue by sdlytcl** [zadam/trilium#1293]
hi， can it open local files by default programs in “link”？thanks.

**Comment by zadam** [comment]
Currently this is an unexplored area - see #965

**Comment by generic-user** [comment]
Hi, first off: thanks for the application. I am **loving** it so far!

I was actually wondering the same question. When click the 'open' button on an atachement it keeps getting handled by the browser ... 

I am not at all familiar nor proficient in JavaScript or Electron, but...

Should this not be an easy task using the electron API? Something like [this](https://www.electronjs.org/docs/api/shell#shellopenpathpath)?
```
shell.openPath(path)
```
> Open the given file in the desktop's default manner.
> path String
> Returns Promise<String> - Resolves with an string containing the error message corresponding to the failure if a failure occurred, otherwise "".

Or is that not possible?

**Comment by zadam** [comment]
Yes, something like that could be used to open the links, but so far it's actually not even possible to create local file links ... (see ckeditor/ckeditor5#8248)

**Comment by generic-user** [comment]
Oh, I see, this issue is about an actual link syntax. My bad!

I was talking about the behaviour that occurs when clicking the open button in an attached file.

Best if I make a separate issue for that. → https://github.com/zadam/trilium/issues/1304
Thanks.

**Comment by zDEFz** [comment]
Wouldn't it be possible to simply host the file locally and then linking to it via localhost ?

**Comment by laundmo** [comment]
i made a script to allow doubleclicking file paths. its limited to italicized paths to make sure its intentionally linked.

https://gist.github.com/laundmo/de1f386fac9f9e797fd77022d63967c9
