### ISSUE TITLE
mobile mode - blank page

### ISSUE THREAD

**Issue by thehotery** [zadam/trilium#1300]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

https://pastebin.com/0gt5y2CB  ~/.local/share/trillium-data/trilium-2020-10-10.log

note: i'm trying it in wsl2 with  trilium-linux-x64-server-0.44.6.tar.xz, untar it and ./trillium.sh

On desktop with Chrome (and firefox) it Works great. On Ipad (safari) after log in it shows blank page, but with "force desktop mode" and it works.  So I'm trying on Chrome in desktop with http://localhost:8080/login?mobile and same as on ipad, after log in it shows blank page.

```
mobile.js:1 Uncaught ReferenceError: Cannot access 's' before initialization
    at Object.Z (mobile.js:1)
    at Object.5491 (collapsible_widget.js:23)
    at __webpack_require__ (bootstrap:18)
    at Object.394 (mobile.js:1)
    at __webpack_require__ (bootstrap:18)
    at Object.8702 (mobile.js:1)
    at __webpack_require__ (bootstrap:18)
    at Object.986 (mobile.js:1)
    at __webpack_require__ (bootstrap:18)
    at mobile.js:1
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/libraries/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

maybe i'm doing something wrong? :)

PS. Strange thing, mobile gui (on desktop Chrome with http://localhost:8080/login?mobile) working on 0.43.4, on next realeases of "server-**.tar.gz" package - blank page..

**Comment by zadam** [comment]
Hi, thank you for reporting this issue.

It looks like a problem with webpack packaging the mobile frontend, I managed to work around the issue. I will release new patch version tomorrow.
