### ISSUE TITLE
When I copy content with text & picture from MS Word to Triulium , it catched a TyperError.  

### ISSUE THREAD

**Issue by huwei96** [zadam/trilium#1302]
the alert like this:
![image](https://user-images.githubusercontent.com/28172625/95755035-79be9580-0cd6-11eb-8529-589879511f13.png)

**Comment by huwei96** [comment]
After that alert，Texts can be input into trilium note，but picture can not be input into note.
If only copy single picture from word into trilium，it works.

**Comment by huwei96** [comment]
I checked the picture's format ,it is a jpg file.

**Comment by meichthys** [comment]
I wasn't able to reproduce this error. I was able to copy text and photos at the same time into Trillium. I was able to do it using the web interface and the Windows desktop application. 🤷‍♂️
