### ISSUE TITLE
Is there a way to stop the a child note from inheriting a attributes?

### ISSUE THREAD

**Issue by a22a-dev** [zadam/trilium#1303]
When we make attributes inheritable to it's child, sometimes we don't want a child to inherit it and also cannot move the child note someplace else. So for that use case, I think their should be a tag like `noInheriting`, which would make the child and it's childs to drop all the inherited attributes.

**Comment by zadam** [comment]
Please add details to this issue, otherwise we can close this ...

**Comment by a22a-dev** [comment]
Added the details.

**Comment by zadam** [comment]
So this does not exist yet and frankly I'm not sure if this is a good/necessary feature.

You might also consider alternatives - copy and template inheritance which are naturally "stopping": https://github.com/zadam/trilium/wiki/Attribute-inheritance

**Comment by a22a-dev** [comment]
Ok look like that is what I wanted.
