### ISSUE TITLE
Open TYPE:FILE in the desktop's default manner.

### ISSUE THREAD

**Issue by generic-user** [zadam/trilium#1304]
Hi, currently when clicking the 'open' button on an attachment it keeps getting handled by the browser ...

Could we make use of the Electron API to open a file with the default file handler of the OS?

Or in other words: use the electron API when clicking the open button on an attachment? 
![image](https://user-images.githubusercontent.com/1516035/95825141-b1f2c200-0d30-11eb-9947-cd06facb4c6e.png)

Maybe the file needs to be available on the OS first, so we need to write it to disk somewhere before opening? 
Temporally, read only? Or add new revision on change ... ?

<details>
  <summary>Using the electron API? Something like <a href="https://www.electronjs.org/docs/api/shell#shellopenpathpath">shell.openpath</a><br/></summary>
  
  Spoiler text. Note that it's important to have a space after the summary tag. You should be able to write any markdown you want inside the `<details>` tag... just make sure you close `<details>` afterward.
  
```js
// shell.openPath(path)
...
this.$openButton.on('click', () => {
            if (utils.isElectron()) {
                const electron = utils.dynamicRequire('electron'); //<-- something like this?

                electron.shell.openPath(this.getFileUrl());  //<-- something like this?
            }
            else {
                window.location.href = this.getFileUrl();
            }
...
```

> Open the given file in the desktop's default manner.
> path String
> Returns Promise<String> - Resolves with an string containing the error message corresponding to the failure if a failure occurred, otherwise "".

</details>

**Comment by zadam** [comment]
> Maybe the file needs to be available on the OS first, so we need to write it to disk somewhere before opening?

Yes, that is the actual issue - to be able to call `shell.openPath` you need to specify file path, but at that point file doesn't exist yet.

Perhaps as you suggest first storing it in a temp folder would make sense ...

**Comment by zadam** [comment]
Ok, this is now implemented and will be in next stable release, however this works with only default associated applications. In case there's none, then a fallback via browser is used as before.

**Comment by generic-user** [comment]
# Thank u!
Thanks for tackling this issue so fast, really appreciate it!

## Some remarks
I do have a few remarks concerning the implementation. 😁 

### 1. Invalid filenames
https://github.com/zadam/trilium/commit/18cc9f24753eff9120fe5f928d296a3e70929a72#diff-1f2dcbdb2303c79f5e577d371ff17500481e854d0debb0c2c04f5a5174b52f81R36-R41

The title of a note is **not** always a **valid** filename, so if u really want to use the title as a filename make sure to validate it before usage. Something like this [here](https://github.com/sindresorhus/valid-filename/blob/master/index.js). When it is not valid, u can make it valid by replacing illegal characters.

If the reason for using title is backwards compatibility would it not be a better approach to check if an original filename is available. Making the **new approach** the **default approach** but _fall back to the title if it is not available_. Either way we should always check if a file path is valid before writing to disk.

#### Example
Currently, I have a note of the type **FILE** that has a tittle like: `ABC E1.2: example of some title`.
This results in the following error message displaying:
![image](https://user-images.githubusercontent.com/1516035/96118571-fd9d9b00-0eeb-11eb-923b-177c2225961f.png)

The reason for that message is of course that the file does not exist. It could not be created because is has an invalid file path.

### 2. Cluttering temporally folder with duplicates of the same file
After extensive testing I noticed a temp file was generated every time I clicked the button. Even though a previous _downloaded file_ was already there. Would it not be possible to override the file that was already there? 
Instead of using a random name each time we click the button, we could build up the filename using the `note.Id` . That `note.id` is already unique. That way you can identify an already existing version of the file. Then overriding it with the _new version_.


### 3. Cleaning up of the files that were created? 

I know this makes it all a bit more complicated, but it would be beneficial in the long run. [It is common practice, on the Windows platform, to leave this kind of housekeeping to the applications themselves.](https://stackoverflow.com/questions/3158605/length-of-time-temporary-file-kept)

#### Proposition for fixing temporary folder size
I think the easiest approach to tackle this is to claim your own folder inside the temp folder. That way you're 100% certain that all files in there are created by Trillium. 
Now to perform the actual clean-up u can use _a multitude of solutions_, each with their **own complexity**. The easiest solution is to periodic clean-up the folder by file creation date (delete all files older than 7 days?).

## Final
Anyway, I really appreciate the time invested in this application, so again, thanks 🎉
