### ISSUE TITLE
ability to unhoist from any child notes of the hoisted note

### ISSUE THREAD

**Issue by a22a-dev** [zadam/trilium#1305]
I am asking for this because when I am working under a hoisted note and I need to lookup another note that is not under the hoisted note, then I have to move to that hoisted note & unhoist it and then open my lookup note and then hoist the note again and then get back to working.
This is a little bit too lengthy process.
I was hoping to have some key combination to be able to unhoist the parent note and stay at the current note and do my lookup and then hoist the parent note back again. And it is evident in my request that trilium would have to remember the last hoisted note, to be able to rehoist the parent note. But again it will interfere with normal process of hoisting and unhoisting. So having a key combination other than `ALT + H`, would have to do.

**Comment by zadam** [comment]
Hi, the first part makes sense to me - the need to switch notes to unhoist is annoying - I added a new shortcut `ALT-U` to unhoist while staying at your current note.

But then the second part seems to me sort of specialized and I'm not sure how generally useful would that be ...

**Comment by aak9t9** [comment]
Thank you for the quick fix!
And yes it does seem a little bit specialized, but having it would make the `ALT+U` complete or symmetric.
