### ISSUE TITLE
0.44.7 server, blank white screen after login

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1306]
I run server version on ubuntu 16.04. 0.44.6 has been working fine. I upgrade to 0.44.7 and I get the login screen, but after entering credentials it goes to blank white screen. This is both behind a nginx reverse proxy or directly via port 8080. I downgraded to 0.44.6 and verified that worked fine, then promptly went back to 0.44.7 with the same white blank screen. 

Attached is the log file for today. I didn't see anything obvious. I also restarted computer I use to access the server
[trilium-2020-10-14.log](https://github.com/zadam/trilium/files/5375565/trilium-2020-10-14.log)

**Comment by zadam** [comment]
Hello, thank you for the report, unfortunately 0.44.7 is broken, I will release fixed version soon.

**Comment by Engr-AllanG** [comment]
No problem! I'm back to 44.6. 

Thanks
