### ISSUE TITLE
0.44.7 win: blank white screen while setup

### ISSUE THREAD

**Issue by tyskink** [zadam/trilium#1307]
version: 0.44.7 win
issue: blank screen

 **log files**
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows

```13:09:47.392 DB not initialized, please visit setup page
13:09:47.393 DB size: 4 KB
13:09:48.518 App HTTP server starting up at port 37840
13:09:48.518 {
  "appVersion": "0.44.7",
  "dbVersion": 170,
  "syncVersion": 16,
  "buildDate": "2020-10-13T23:45:39+02:00",
  "buildRevision": "893b6053d22c159d6197900c988f0007eca4840d",
  "dataDirectory": "C:\\Users\\tyski\\AppData\\Roaming/trilium-data",
  "clipperProtocolVersion": "1.0"
}
13:09:48.519 CPU model: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, logical cores: 4 freq: 2904 Mhz
13:09:48.543 Listening on port 37840
13:09:48.928 Slow GET /setup took 13ms
```

![image of the blank screen](https://user-images.githubusercontent.com/22754217/95946079-60286580-0e1e-11eb-898a-1066cf6a8f2a.png)

but it is ok while using 0.43.4

**Comment by zadam** [comment]
Hello, thank you for the report, unfortunately 0.44.7 is broken, I will release fixed version soon.

Please use/download 0.44.6 in the meantime.
