### ISSUE TITLE
Windows: Electron: About: DataDirectory path using forward "/" instead of backwards "\".

### ISSUE THREAD

**Issue by generic-user** [zadam/trilium#1308]
## Data Directory

OS: Windows --> Electron
Where: The about page 
What: the DataDirectory path using forward "/" instead of backwards "\\".

![image](https://user-images.githubusercontent.com/1516035/95971211-30bf2c00-0e11-11eb-9773-34b204411001.png)

**Comment by zadam** [comment]
fixed in 0.44.8
