### ISSUE TITLE
[Feature Request] Include CKEditor 5 'List styles' UI features

### ISSUE THREAD

**Issue by cbop-dev** [zadam/trilium#1311]
CKEditor 5 includes various [list style options](https://ckeditor.com/docs/ckeditor5/latest/features/lists.html#demo-2), including using letters or roman-numberals ("a., b., c.,", "i., ii.," etc.) for ordered lists. this becomes important for nested, ordered lists like the following:

1. Item 1
   1. subitem 
   1. another sub-item
      1. sub-sub-item
1. Item 2
   1. subitem

Currently, Trilium (v. 0.44.8) does not use this feature of CKEditor 5 in the UI (in neither the desktop version on Linux nor the web version). All nested ordered lists use numerals (1, 2, 3), which is unsightly. Can this feature be made available?

**Comment by zadam** [comment]
Hi, support for list styles has been committed, will be in 0.45.
