### ISSUE TITLE
Mobile Interface: Can't see bottom part of a note 

### ISSUE THREAD

**Issue by Marenz** [zadam/trilium#1312]
I just updated from 0.34 to 0.44.8. Now I can no longer see the bottom part of a note which also means I can no longer see what I am typing except when I am typing something in the middle of the existing text.
See the images below for an example. I have scrolled down as far as possible in the pictures. The browser used is firefox:

![image](https://user-images.githubusercontent.com/424752/96248672-33a25400-0fac-11eb-9043-40bd1ddb1b49.png)
![image](https://user-images.githubusercontent.com/424752/96248659-2e450980-0fac-11eb-966d-5b3a3a340cda.png)

**Comment by HiFiJ** [comment]
Hi,
FWIW I stumbled upon this as well on Firefox Mobile with Tab Bar set to bottom. Setting the Tabbar to top  works around this problem.
Thanks for everyone's work on Trilium!
Joost

**Comment by meichthys** [comment]
Changing the tab at to the top doesn't seem to be possible in the iOS Firefox app.

I end up using the desktop view on my iPhone to avoid this issue and to have access to search.

**Comment by finzzz** [comment]
@zadam can you reopen this issue, there are some notes in mobile view that still have this issue.

**Comment by meichthys** [comment]
I believe this is covered in https://github.com/zadam/trilium/issues/1936 where you confirmed this to still be an issue.

**Comment by finzzz** [comment]
@meichthys yes, but it has 2 issues in one issue. Similarly, I can't reproduce first issue he mentioned in the latest version.
