### ISSUE TITLE
Label issues (Test on 0.44.8)

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1313]
Hi Zadam
I find out there is no Select Box when I added a label with TYPE boolean (I mean it should be **TRUE** or **FALSE**)
![image](https://user-images.githubusercontent.com/51273534/96306072-43975380-0fff-11eb-86dd-cb54ef170d95.png)
I don't know if the font is too big!

**Comment by zadam** [comment]
Hi, thanks for the report, there was a styling issue which made the checkbox invisible. Fixed now in stable branch.
