### ISSUE TITLE
[Feature Request] Get Editor Better

### ISSUE THREAD

**Issue by Magic-King** [zadam/trilium#1314]
As I have used trilium for some days, I am still not used to trilium and the normal markdown editor(such as typora), including some formats. Can you make it more suitable for markdown?
On the other hand, I think that in this editor, I can't distinguish the difference between the head1 and head3.They are no difference except the font size.

**Comment by zadam** [comment]
> Can you make it more suitable for markdown?

Basic editing experience is more or less set by the upstream CKEditor project. There are some nice markdown-like shortcuts etc. but fundamentally it is not a markdown editor.

> I can't distinguish the difference between the head1 and head3.They are no difference except the font size.

Hmm, size is supposed to be the main difference between different headings.

**Comment by Magic-King** [comment]
emmmmmmmm
after update I think it's more suitable for me.
I will try my best to be used to it
By the way ,do you consider making mind map (such as xx.xmind) visible in trilium view? I think it's a good idea to make it more thoughtful.

**Comment by cyannuremagik** [comment]
I am jumping in to provide a suggestion. 
First, i have the same issue, I find the difference in size not sufficient to distinguish two consecutive levels.

A nice and, I think, elegant way to make the header level more explicit is to show the pound key. This is inspired by Zettlr (see [https://zettlr.com/](https://zettlr.com/)), another note taking app which has its pros and cons.

When autoformatting happens, the poundkey disappears as expected from autoformatting. I think it would help differentiate headers if the autoformatting still happened, and that the poundkey(s) remained with them
## Header 2 (first level available)
### Header 3 
#### Header 4, etc..

If this is not a good solution, is it possible to increase the size difference between each header level?

Thanks for the app btw; it's great! The interface could enjoy some refinement but it is good as it is right now.

**Comment by zadam** [comment]
Using CSS it's quite easy to prepend headings like this:

![](https://user-images.githubusercontent.com/617641/100674301-3642e800-3365-11eb-8d63-126177b0bad8.png)

However I'm not sure if it's actually desirable for majority of users. Some might consider it distracting etc. especially if they are not familiar with markdown ...

**Comment by cyannuremagik** [comment]
Thanks Zadam,
I didn't know it was possible to show the pound key through CSS. It may not be desirable for the majority of user indeed, it is only one solution to make the headers more distinct. 
My current solution was to increase the amplitude in font size between headers, it works well enough.
Cheers

**Comment by zadam** [comment]
for the record this is CSS I'm experimenting with:

```css
    .note-detail-editable-text h2 { font-size: 1.8em; } 
    .note-detail-editable-text h2::before { content: "##\00a0\00a0"; color: var(--muted-text-color); }
    .note-detail-editable-text h3 { font-size: 1.6em; }
    .note-detail-editable-text h3::before { content: "###\00a0\00a0"; color: var(--muted-text-color); }
    .note-detail-editable-text h4 { font-size: 1.4em; }
    .note-detail-editable-text h4::before { content: "####\00a0\00a0"; color: var(--muted-text-color); }
    .note-detail-editable-text h5 { font-size: 1.2em; }
    .note-detail-editable-text h5::before { content: "#####\00a0\00a0"; color: var(--muted-text-color); }
    .note-detail-editable-text h6 { font-size: 1.1em; }
    .note-detail-editable-text h6::before { content: "######\00a0\00a0"; color: var(--muted-text-color); }
```

**Comment by Magic-King** [comment]
> Using CSS it's quite easy to prepend headings like this:

aha, CSS is a good choice.But when note is readOnly ,the CSS is invalid.Is there any solution for it except setting label autoReadOnlyDisable.
The following picture shows the probolem.
![image](https://user-images.githubusercontent.com/44387077/101280938-1436e300-3807-11eb-8051-9693b4945e5d.png)

**Comment by zadam** [comment]
You can just make CSS with corresponding read only classes (use element inspector with `CTRL-SHIFT-I` to find out correct selectors)
