### ISSUE TITLE
When I am creating a note within a note who's parent or grand parent is hoisted, it asks to unhoist the note to create a new note.

### ISSUE THREAD

**Issue by a22a-dev** [zadam/trilium#1318]
I am creating note using `CTRL+P`

**Comment by aak9t9** [comment]
New Note is still being created at right place but it is asking for unhoisting the notes.

**Comment by zadam** [comment]
Hi, could you record a video/gif showing this? I have trouble reproducing this bug ...

**Comment by aak9t9** [comment]
Sure

**Comment by aak9t9** [comment]
The problem is not visible for notes hoisted directly under root, but it is there for notes below that level.

**Comment by aak9t9** [comment]
[Link of the gif](https://imgur.com/a/fwRUpJZ)
