### ISSUE TITLE
Stripping of evernote:// links on ENEX import

### ISSUE THREAD

**Issue by msbentley** [zadam/trilium#1319]
Currently, imported .enex files appears to remove any `evernote://` type links, used by Evernote for internal note-to-note linking. This makes sense, since the enex files do **not** include the note GUID, which is needed to resolve the link to a note.

However, I'm currently working on a small python project using the Evernote API to get around this. Currently I get the GUID, title and creation date of each note in a user's account using the API, and then either write this to disk, or "fix" the issue. I have currently implemented the last for Joplin, which maintains the "dead" links on import. I find notes with such links, resolve the GUID to a name+creation date using the data from Evernote, find the matching note ID in Joplin, and re-write the link in the note body using the Joplin API.

I plan to also add a function to do the same for a directory of Markdown files, which I _could_ then import into Trilium. But my prefered way would be to leverage the import mechanism already in place, and then use the Trilium API or even query the database directly to resolve/re-write the links, as per Joplin. But this would require that the links are not stripped.

Any thoughts on the best approach here @zadam?

Many thanks!

**Comment by zadam** [comment]
Hi, I tested this and found out the evernote links are stripped because of HTML sanitization done as part of import - `evernote://` scheme was not recognized and therefore stripped.

I just added it into the whitelist, so the links are preserved.

**Comment by msbentley** [comment]
Fantastic, thanks @zadam. For the note searching/re-writing which do you recommend (for someone with zero js knowledge):
1. Use the https://github.com/zadam/trilium/wiki/Custom-request-handler
2. Wait for a "default" REST API
3. Attack the sqlite database

I think the last would be easiest for me, but perhaps the most dangerous ;-) Otherwise if 2 is likely in the coming months, I would wait for that. But if you strongly recommend against the dbase I'll try 1!

**Comment by zadam** [comment]
If you're comfortable with SQLite, then I would recommend that approach. There aren't really any gotchas, just transform `note_contents.content` based on your need. There aren't any derived data / indexes so no need to update anything else.

(assuming you don't have sync setup, with that you would need some additional steps for the changes to get recognized and synced)

**Comment by msbentley** [comment]
OK, great. I'm using a local instance, so I'd aim to get all this fixed first before syncing.

I haven't really considered `internalLink` but I'll have a play and shout if I have questions - many thanks!
