### ISSUE TITLE
Zen Mode is too wide for good reading experience

### ISSUE THREAD

**Issue by aak9t9** [zadam/trilium#1320]
When notes are small it is spread out across the screen, which does not make for a good reading experience.
Also having to read the big notes by moving from extreme left to extreme right puts strain on eyes. 
So padding the note from both sides by around 100 to 150px might be good.

**Comment by zadam** [comment]
Hi, you're right, long lines are not readable. I've now set a max width to the content in zen mode.

**Comment by aak9t9** [comment]
What's the max width?

**Comment by zadam** [comment]
1000px

**Comment by aak9t9** [comment]
Ok, lets see how it looks
