### ISSUE TITLE
[Question] External API

### ISSUE THREAD

**Issue by JulienSambre** [zadam/trilium#1321]
Hi!

I discovered recently Trilium and for now I love it (moved from QOwnNotes, imported all my private and work md notes in Trilium like a charm).

I would like to go futher and integrate Trilium with my own AI, creating/updating a note in Trilium when I ask special things to my AI (like "question to the Internet").

I saw in #928 that there was no REST API in march but it was on the roadmap. The possibility to create a custom API seemed a little complicated and strange to me, especially the security part.

Do you have any news on this REST API feature?

**Comment by zadam** [comment]
There is no news except for the fact it is still planned :-/

**Comment by zadam** [comment]
Trilium now has ETAPI - github.com/zadam/trilium/wiki/ETAPI
