### ISSUE TITLE
[Improvement] Web Clipper : add source URL

### ISSUE THREAD

**Issue by JulienSambre** [zadam/trilium#1322]
Hi!

I was asking myself if it would be possible to add source URL when web clipping a whole page ("save whole page to Trilium").

I ask that because it is exactly the usage of tools like Pocket / Wallabag / ... and it would be awesome if Trilium could do it. The web clipper is already so great as it is, this little more things would remove the need of this kind of tool. It is already so much great at web clipping than these tools, but saving the source URL.

What do you think?

**Comment by zadam** [comment]
Hi, "sourceUrl" is already saved as "pageUrl" label:

![](https://user-images.githubusercontent.com/617641/96508236-91f45e80-125a-11eb-8711-ae5fd6fb8d04.png)

**Comment by JulienSambre** [comment]
Thanks!

I didn't saw that labels!
