### ISSUE TITLE
How does ckeditor code block support highlighting

### ISSUE THREAD

**Issue by zhaiyujin** [zadam/trilium#1326]
How does ckeditor code block support highlighting
```php
function helloWorld() {
	alert("Hello world");
}
```

**Comment by zadam** [comment]
The answer is simple: it doesn't. Syntax highlighting is supported only in code notes.

**Comment by zhaiyujin** [comment]
I know that there are too few code blocks, and I don't want to create code Notes for him. I prefer to record code blocks in text notes

**Comment by AkselAllas** [comment]
Big sad on this issue. RIP
