### ISSUE TITLE
Same as #1320 but for the notes in new window other than main trilium window.

### ISSUE THREAD

**Issue by a22a-dev** [zadam/trilium#1327]
1000px width works for main window, but for the ones created using right click on tab and then selecting open in new window, there the width is still as before, not 1000px.

**Comment by zadam** [comment]
weird, seems to work for me:

![image](https://user-images.githubusercontent.com/617641/97045322-d7c06800-1575-11eb-897d-cc5179fe83a7.png)

**Comment by a22a-dev** [comment]
My bad! Without using zen mode, the notes in new window spans the whole width of the screen. Forgot to get into zen mode.
