### ISSUE TITLE
FR: Git based template/theme/etc marketplace

### ISSUE THREAD

**Issue by patrickjm** [zadam/trilium#1328]
I think Trilium has a huge number of clever uses/layouts that would be useful but don't occur to me. It would be interesting to have a git based "marketplace" repo which is by default hard-coded to some public repo that you (@zadam) own, but maybe users could configure their instances to additionally point to private repos. Standard Notes has a [similar system](https://github.com/sn-extensions).

For example, maybe the repo's file structure could look like this:

```
/My Super Awesome Theme
  /metadata.json
  /... some file based representation of notes to import
/My Cool Render Note
  /metadata.json
  /... some file based representation of notes to import
```

Metadata could have information like markdown description, author, tags, etc.

As it's laid out above, there wouldn't be installing/uninstalling, just importing them somewhere into the tree.

If Trilium ever has its own website someday, the marketplace could live on some subdomain and statically generate from this public git repository.

**Comment by zadam** [comment]
Hi, something similar was already brought up in #986, the points in my response there are sitll valid.

**Comment by patrickjm** [comment]
Moving over there
