### ISSUE TITLE
Issue about "add new relation" (test on 0.45.0 beta)

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1329]
Hi Zadam
I can't add new relation when save&close it as I usually do with other older versions.
But new beta version doesn't work well! look at screenshots
1)**First Screenshot** you see is the error message,which is what I see when I type normaly(However,I've already selected the target note)
![image](https://user-images.githubusercontent.com/51273534/97119177-b8107780-170e-11eb-827e-3c9f68657228.png)

2)**Second Screenshot** Before save&close it I choose Inheritable then relation works!
![image](https://user-images.githubusercontent.com/51273534/97119186-c9598400-170e-11eb-87a2-559a3befac46.png)

3)**Third Screenshot** This is what I finally want to my note,Now I need to make note inheritable then delete it**(inheritable)**
![image](https://user-images.githubusercontent.com/51273534/97119190-ce1e3800-170e-11eb-8432-f0413c96f592.png)

Please Check it out
Thanks

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it has been fixed and will be released in next stable version.
