### ISSUE TITLE
Feature requirement:Link maps for children notes(Hierarchy)

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1330]
Hi Zadam
Is there any possibility to add a new feature like [foambubble](https://foambubble.github.io/foam/) does?
Their link maps,in addition to linking the 1' level of subnotes,it can also link to all other subnotes(2^lvl,3^lvl,4^lvl etc....)
For example,My link map connected to A.1 subnote but it will be appead all other sublinks of A.1

You can refer to the gif below
![foam-navigation-demo](https://user-images.githubusercontent.com/51273534/97119512-f4dd6e00-1710-11eb-9ef2-86e2ede57a6b.gif)
But can we make a simple link-map just to show all the sub links?
I think this can be a tough demand to make.
It would be better if it happened
Thanks in advance
Keep going!

**Comment by sdlytcl** [comment]
yes, I need this.

**Comment by zadam** [comment]
Maybe I don't understand this correclty, but link map dialog shows also other "levels" - see e.g. Trilium Demo -> Code blocks -> Steel Blue

![](https://user-images.githubusercontent.com/617641/97218849-85778500-17c9-11eb-8921-68e35d28edcc.png)

The widget in sidebar shows only one level of relationship since it's too small ...

**Comment by Rsose** [comment]
> Maybe I don't understand this correclty, but link map dialog shows also other "levels" - see e.g. Trilium Demo -> Code blocks -> Steel Blue
> 
> ![](https://user-images.githubusercontent.com/617641/97218849-85778500-17c9-11eb-8921-68e35d28edcc.png)
> 
> The widget in sidebar shows only one level of relationship since it's too small ...

Wow great
I haven't been watching that before
The link map looks twisted,It's not as neat as it should be
But it's ok
Thanks for reply

**Comment by sdlytcl** [comment]
> Maybe I don't understand this correclty, but link map dialog shows also other "levels" - see e.g. Trilium Demo -> Code blocks -> Steel Blue
> 
> ![](https://user-images.githubusercontent.com/617641/97218849-85778500-17c9-11eb-8921-68e35d28edcc.png)
> 
> The widget in sidebar shows only one level of relationship since it's too small ...
sorry， where is “other level“？

**Comment by sdlytcl** [comment]
sorry， i can not find “other level“.  
？

> Maybe I don't understand this correclty, but link map dialog shows also other "levels" - see e.g. Trilium Demo -> Code blocks -> Steel Blue
> 
> ![](https://user-images.githubusercontent.com/617641/97218849-85778500-17c9-11eb-8921-68e35d28edcc.png)
> 
> The widget in sidebar shows only one level of relationship since it's too small ...

**Comment by Engr-AllanG** [comment]
@sdlytcl I think what you may be missing is you can change the "max notes" that is displayed. After enlarging the link map widget, it is at the top.
