### ISSUE TITLE
click ”recent change“ one time，it can not open，need one more time.

### ISSUE THREAD

**Issue by sdlytcl** [zadam/trilium#1331]
hi, when I click ”recent change“ one time，it can not open, need one more time.
v0.44.9

**Comment by zadam** [comment]
Hi, is there something in the browser console? (`CTRL-SHIFT-I`?)

**Comment by sdlytcl** [comment]
yes, but i don't understand.
![Uploading 111.png…]()

**Comment by sdlytcl** [comment]
yes, but i don't understand.
![111](https://user-images.githubusercontent.com/69014708/97202846-17de4f80-17ef-11eb-8336-0ec0dd1d960f.png)

**Comment by sdlytcl** [comment]
Cannot find action logout
:37840/app-dist/desktop.js:1 Cannot find action createTopLevelNote
:37840/app-dist/desktop.js:1 Cannot find action renderActiveNote
:37840/app-dist/desktop.js:1 Uncaught (in promise) TypeError: t.filter is not a function
    at Object.getNotes (:37840/app-dist/desktop.js:1)
    at Object.reloadNotes (:37840/app-dist/desktop.js:1)
    at async Object.getNotes (:37840/app-dist/desktop.js:1)
    at async Module.u (:37840/app-dist/583.desktop.js:1)
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:37840/libraries/bootstrap/css/bootstrap.min.css.map: Unknown error
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:37840/libraries/bootstrap/js/bootstrap.bundle.min.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:37840/libraries/split.min.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:37840/libraries/ckeditor/ckeditor.js.map: Unknown error
﻿
​

**Comment by zadam** [comment]
Hi, thanks for the logs, I believe I found the problem and managed to fix it, this will appear in the next stable version.
