### ISSUE TITLE
Can't import OPML file which is exported from MINDMANAGER (ON 0.45.0)

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1333]
Hi Zadam
I'm trying to import a OPML file but the trilium notes give me this error message:
![image](https://user-images.githubusercontent.com/51273534/97196095-5b639a00-17ac-11eb-96c4-abc5e00b0247.png)

Look at this OPML [file[](url)](https://tmpfiles.org/download/91591/TEST.opml)
I don't know where is the problem that can't import
Please check it out
Thanks

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it looks like a regression. I plan to release a new stable version later today...
