### ISSUE TITLE
Title does not change when using the "Go to next note" and "Go to previous note" buttons.

### ISSUE THREAD

**Issue by funnisquares** [zadam/trilium#1334]
This is a pretty minor bug, and I'm sure it was just a small oversight and an easy fix. When navigating notes, the window title does not change to the name of the note when using the "Go to next note" and "Go to previous note" buttons, I assume this is not intended, because other ways of navigating through notes do change the window title.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it has been fixed and will be in the next stable release.
