### ISSUE TITLE
ALT+R is not working, ALT+L is working fine.

### ISSUE THREAD

**Issue by a22a-dev** [zadam/trilium#1335]
Relation creation shortcut is not working. 
0.44.9

**Comment by zadam** [comment]
Hi, could you check in the options if the shortcut is set correctly?

![](https://user-images.githubusercontent.com/617641/97352555-1a928080-1893-11eb-996a-400dc99006d3.png)

Also, what platform do you use?

**Comment by a22a-dev** [comment]
So Sorry... It was my fault. I created a global setting with ALT+R a while ago and forgot about. After I saw the your reply, it clicked why it wasn't working.
