### ISSUE TITLE
Improved webclipper tool

### ISSUE THREAD

**Issue by Waxwood** [zadam/trilium#1336]
Currently, the Trlium webclipper can:

1. enable selection of an entire webpage and save to a note
2. take a screenshot in jpeg or png to save as an image file in a note
3. copy text into a note-box to quickly save to a note. 

These features are great, but the clipper would be better if it can incorporate features of the Joplin webclipper including:

1. user can select a portion of a website and save it to a note in Trilium
2. user can add tags/keywords to webclippings prior to saving in Trilium
3. include the URL of the clipped material into the note

A screenshot of the Joplin webclipper is here: https://aws1.discourse-cdn.com/standard14/uploads/cozic/original/2X/d/dbfe74b8921b9f51b54863f97460114afcc08e78.png

**Comment by zadam** [comment]
Hi, 

first point is possible with the context menu click:

![](https://user-images.githubusercontent.com/617641/97351704-67c22280-1892-11eb-8430-02564ec0592b.png)

> include the URL of the clipped material into the note

URL is saved in a label:

![](https://user-images.githubusercontent.com/617641/97352026-d606e500-1892-11eb-9012-0c7b3c41b00f.png)

**Comment by Waxwood** [comment]
Thank you for showing this to me. I missed that somehow. Outstanding!! Maybe include this feature in the browser plugin options as well so users don't miss it.

**Comment by nil0x42** [comment]
Including feature in browser plugin options would really help to remember the `save selection` option.

But the biggest improvment IMHO would be to be able to add labels from browser plug-in
