### ISSUE TITLE
Search with dateCreated/dateModified not working - v45.1

### ISSUE THREAD

**Issue by blumpcus** [zadam/trilium#1337]
**Trilium Version v45.1**
I'm not able to use the note.Date_x_ search strings anymore.

I've tried all variations that I can think of, including the official recommendation in the **_Search tips_**:
`note.dateCreated >= MONTH-1`, as an example. It doesn't show anything, regardless of whether I use MONTH, TODAY, etc. 

I've also searched the documentation for the new search syntax to make sure I'm getting it right. 
Regardless of note.dateCreated, note.dateModified, and any values thereafter (=TODAY, etc) the search result is empty. 

Am I doing something wrong?
I'd appreciate your help.
As always, thanks for the work you've put into Trilium, it's a wonderful application.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it looks like using these "smart" values has been broken for dateCreated and dateModified. This is now fixed in 8c4ff7e
