### ISSUE TITLE
Feature requirement:Default Note

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1338]
Hi Zadam
Is it possible make some note as default note?
I know that evernote have Default Notebook and Global shortcut to create notes(CTRL+ZLT+N)
E.g take some notes,jot down some thoughts what I need is to create note in the shortest possible time.
Evernote they got Default note and Global Shortcut that's exactly what I needed(Set note as default)
I also want The Trilium Notes make it possible

Something like this:
When I set a default note in the Trilium,then I use global shortcut to create notes.But all notes are created to Default Note(As a subnote of Default note.)
**1)Set Default Notes**
![image](https://user-images.githubusercontent.com/51273534/97360012-e83a5080-189d-11eb-9ceb-74a20c5173f6.png)
**2)Set Global Shortcuts**
![image](https://user-images.githubusercontent.com/51273534/97359934-d193f980-189d-11eb-934d-6fa26733055e.png)

Waiting for a reply
Thanks

**Comment by a22a-dev** [comment]
It already kinda works like that only difference is that in trilum it is created under calender notes (default note in evernote) using CTRL+ALT+P.
And if you need to go to the newly created notes on the same day, you can write a "today" script or use it from demo script.

**Comment by Rsose** [comment]
> It already kinda works like that only difference is that in trilum it is created under calender notes (default note in evernote) using CTRL+ALT+P.
> And if you need to go to the newly created notes on the same day, you can write a "today" script or use it from demo script.

Nice wow that's what I want
Sorry,How to create a new "today" widget script?
I deleted it long time ago,I don't know how to recover it!
Thanks
