### ISSUE TITLE
No autoformat for math

### ISSUE THREAD

**Issue by funnisquares** [zadam/trilium#1339]
Inserting inline math does not have autoformat syntax. In most markdown editors and also latex, inline math is added using $someexpression$. It would be great if we could write math expressions by using dollar signs, seeing as it is so common that most will type math in this format by reflex, I assume.
Also in this topic, math-blocks would be great.

**Comment by zadam** [comment]
Hi, I created an issue for this in the relevant library: isaul32/ckeditor5-math#11

As a sort of similar work flow you can use `CTRL-M` shortcut to show the math dialog.

> Also in this topic, math-blocks would be great.

Do you mean this?

![](https://user-images.githubusercontent.com/617641/97422915-c4632300-190e-11eb-87da-ce16a406018e.png)

That's controlled with "Display mode" in the dialog ...

**Comment by funnisquares** [comment]
That is what I mean, yes. But I think math-blocks need to have a bigger input box than inline math.
![image](https://user-images.githubusercontent.com/43013384/97444604-1a35cc00-190b-11eb-8b7d-8919ef92527e.png)
As you can see, it can get pretty crowded, even when doing something simple. I'm also not able to break lines, so it gets pretty difficult to read.

**Comment by zadam** [comment]
Ok, yeah, that would make sense.

Yes, this would have to be implemented in ckeditor5-math so I think it makes sense to open an issue there as well.

**Comment by funnisquares** [comment]
[There was already a similar issue there](https://github.com/isaul32/ckeditor5-math/issues/10), so I just replied to it.

**Comment by martinkoutecky** [comment]
@zadam @funnisquares I have a similar request so let me hijack this thread... [ZIM desktop wiki](https://github.com/zim-desktop-wiki/zim-desktop-wiki) has an autoformat feature where automatically upon writing e.g. \alpha or \le plus space, it replaces them with the corresponding UTF-8 symbols α and ≤.

I like this feature very much (while keeping the option of writing "real" math by pressing Ctrl-M or, ideally, between dollar signs). It seems that it might not be that hard extending ckeditor in this way (creating a [custom inline autoformatter](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html)). What would be the best way to go about having this functionality in Trilium?

**Comment by zadam** [comment]
@martinkoutecky best way would be probably to open a PR in ckeditor5-math repo ...

**Comment by grissiom** [comment]
@zadam , ck-math has added this feature in 23.3.0 (https://github.com/isaul32/ckeditor5-math/issues/11 , https://github.com/isaul32/ckeditor5-math#display-mode), but the autoformat feature is still not ready in trilium-0.47.5 . Maybe we need some configuration for ck-math?

**Comment by zadam** [comment]
Hi, you're right, extra plugin needed to be enabled. Will be in the next release. Thanks for the heads up.
