### ISSUE TITLE
Math does not display correctly in note includes

### ISSUE THREAD

**Issue by funnisquares** [zadam/trilium#1340]
![image](https://user-images.githubusercontent.com/43013384/97378537-4d437580-18a1-11eb-87ee-9614befcbddd.png)

I have this note, when including it to another note, the math is not rendered.

![image](https://user-images.githubusercontent.com/43013384/97378584-6e0bcb00-18a1-11eb-9265-cd07654e9828.png)

Same happens on the auto-generated cards, eg
![image](https://user-images.githubusercontent.com/43013384/97378690-b4612a00-18a1-11eb-91f5-f89917e93d48.png)

**Comment by Engr-AllanG** [comment]
Same result here. Server 45.0-beta

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it has been fixed and will be in the next stable release.
