### ISSUE TITLE
downloaded newest version, but it made it make a username AGAIN - where did ALLL our notes go ??

### ISSUE THREAD

**Issue by needhelpfulanswers-spectrumchat** [zadam/trilium#1342]
downloaded newest version, but it made it make a username AGAIN - where did ALLL our notes go ??

**Comment by zadam** [comment]
If the app asks to create username & password again, it means it can't find data anymore - perhaps you moved them / deleted them or perhaps you have custom `TRILIUM_DATA_DIR` environment variable which changes the default data directory?

This might be also helpful: https://github.com/zadam/trilium/wiki/Data-directory

**Comment by needhelpfulanswers-spectrumchat** [comment]
i didnt do anything, software the notes/data whereever is default

you're using too many big words

**Comment by needhelpfulanswers-spectrumchat** [comment]
dont know what you mean it cant find data anymore

it was right there 1 second before i updated

so it's suppose to be somewhere unless the update replaced/deleted all the notes...

**Comment by a22a-dev** [comment]
If you didn,t change anything then look into `/home/{your-user-name-here}/.local/share/trilium-data`. This is where trilium notes store all the data.

**Comment by needhelpfulanswers-spectrumchat** [comment]
what is 'home'

there's no 'home' on here

what's full file path/name/url

**Comment by zadam** [comment]
That depends on your platform and is described in the link I posted above: https://github.com/zadam/trilium/wiki/Data-directory

**Comment by needhelpfulanswers-spectrumchat** [comment]
clearly os is C:\Users\[user]\AppData\Roaming
says in log file also

where exactly is all the notes here ??

cos seems updated deleted/replaced everything ??

**Comment by needhelpfulanswers-spectrumchat** [comment]
what in here am i suppose to look for ????

it's 6.42 mb in size, it that a lot little ???

**Comment by zadam** [comment]
My patience with your communication style is running out.

I don't see any bug here, most probable source of problem has been described in the first comment: https://github.com/zadam/trilium/issues/1342#issuecomment-717829602

**Comment by needhelpfulanswers-spectrumchat** [comment]
???????????

i dont see any .txt files or anything else normal

like all software have normal ways of having notes

where's solution ????

there's no solution anywhere still

**Comment by needhelpfulanswers-spectrumchat** [comment]
problem is this software

and i still dont know where allll my notes are
