### ISSUE TITLE
[Feature request] Show notice to emphasis password importance.

### ISSUE THREAD

**Issue by quakeboy** [zadam/trilium#1344]
I lost my password (forgot it). I didn't even think of forgetting it as I was using it everyday for many weeks. Then there was a gap and when I got back I realized I had set a new password before my break.

This is clearly my fault and no complaints about the password security itself. Just a big red notice when changing passwords to insist on writing down the password else where would be nice. Also you can state that - "if you lose it, there is no way to get it back"

**Comment by zadam** [comment]
Hi, I added some warning text explaining the importance to the change password dialog.
