### ISSUE TITLE
Label value not applied.

### ISSUE THREAD

**Issue by haha205** [zadam/trilium#1345]
Trilium version 0.45.1

1. Create two tyoe of  label as #label:myLabelA=promoted,single,text #label:myLabelB=promoted,multi,text
2. Apply this attribute to an exist note, For example, input "XXXX" in text box of myLabelA, "ABCD" in text box of myLabelB. [Correct]
3. Apply this attribute to another exist note, For example, input "XXXX" in text box of myLabelA, "BCDE" in text box of myLabelB. [Correct]
4. Apply this attribute to another exist note, For example, input "XXXX" in text box of myLabelA, select "ABCD" in droplist of the text box of myLabelB. Operation success, "ABCD" appeared in the text box of myLabelB, but in the field of "x owned attributes"， there is no "#myLabelB=ABCD".
5. Switch to another note, then switch back to the note in step 4. The myLabelB is blank. Information is missing.
6. In step 4, If I type "ABCD" in the text box of myLabelB, everything is OK. After step 5, there is no ERR.

Due to security rule in the company, I can't provide the **log files**. Sorry.

For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by patrickjm** [comment]
I have a similar issue, I'm on 0.45.1. My day notes have `#label:journalType=promoted,multi,text` and `#child:label:journalType=promoted,multi,text`. As a workaround, I've been manually applying the journalType attribute on the child notes and using the promoted input as display only.

**Comment by zadam** [comment]
Hi, thank you for reporting this issue - the problem happens because when you select item from autocomplete, the change event is not triggered so the Trilium doesn't notice something changed and needs to be saved.

This bug has been now fixed and will be released in the next stable version
