### ISSUE TITLE
Can you please provide a summary view of Label, thx

### ISSUE THREAD

**Issue by haha205** [zadam/trilium#1346]
When labels are increasing, I forget which labels are set before, which results in some approximate labels that should be merged.

**Comment by cebas** [comment]
+1 for this request.

Meanwhile, you can open SQL Console and type this query:

`select distinct name from attributes
where type='label'
order by name;`

or if you need more data about labels:

`select name,value,* from attributes
where type='label';`

**Comment by zadam** [comment]
Hi, part of the demo document is Attribute count statistic which provides following view which should be helpful:

![](https://user-images.githubusercontent.com/617641/97482776-e385a300-1956-11eb-8989-89aa82703c99.png)

Next minor version (0.46) might bring a way to merge/rename existing labels.

**Comment by haha205** [comment]
> +1 for this request.
> 
> Meanwhile, you can open SQL Console and type this query:
> 
> `select distinct name from attributes where type='label' order by name;`
> 
> or if you need more data about labels:
> 
> `select name,value,* from attributes where type='label';`

It works, thanks very much.
