### ISSUE TITLE
Importing Evernote notebook with images - no images shown but I can download them

### ISSUE THREAD

**Issue by aashish108** [zadam/trilium#1348]
Hi, I tried to import an Evernote notebook with images. Import seems to work, downloading images works but I can't see any type of preview of the image anywhere? I read toe documentation but nothing much to see. Anyone know what I should do pls? Thanks!

# Info
Version 0.45.1
[trilium-2020-10-28.log](https://github.com/zadam/trilium/files/5453790/trilium-2020-10-28.log)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. I've tested the import and it seems like it does not recognize image resources in the ENEX. I've improved this and now the recognition should work better so the images should show up as images ...

**Comment by aashish108** [comment]
Thanks @zadam . So I believe there will be a new Docker image coming up? Didn't see a new release?

**Comment by zadam** [comment]
Yes, this will be in 0.45.2. 

I have currently issues with building docker image unfortunately, that's why there isn't one for 0.45.1. I will try to fix that.
