### ISSUE TITLE
Support for Cherrytree import

### ISSUE THREAD

**Issue by koutto** [zadam/trilium#1351]
Hey,
This is an awesome project, thanks a lot for the active dev !
It would be great to have an import feature that supports Cherrytree notes. Or copying/pasting from Cherrytree notes with images and formatting copy.

**Comment by zadam** [comment]
Hi, unfortunately there's too many note taking software and it's quite difficult to properly support each of them for import.

On the other hand, based on cherrytree homepage it should be possible to export all notes into HTML files, you can then zip them and import into Trilium.

**Comment by koutto** [comment]
Yes I understand, this is a good idea, thanks
