### ISSUE TITLE
add tagging/ keywording

### ISSUE THREAD

**Issue by Waxwood** [zadam/trilium#1352]
I cannot find any way to assign tags / keywords to notes in Trilium. 
Please add the ability to add hierarchical keywords to items in Trilium.
The best keywording tool I have ever seen is in the photo management tool IMatch
See: https://www.photools.com/portfolio/imatch-categories-3/

Also, please consider including the ability to add keywords to selected blocks of text in a note. 
This would enable Trilium to serve partially as a Qualitative Data Analysis tool.

**Comment by zadam** [comment]
Hi, "tags" are called labels in Trilium:

![](https://user-images.githubusercontent.com/617641/97614821-b7335a80-1a1a-11eb-9be9-1350ae7f312d.png)

**Comment by ehopps** [comment]
> Also, please consider including the ability to add keywords to selected blocks of text in a note.

I know this issue is already closed, but I just wanted to draw attention to this part of the request, which would be helpful for me as well.

**Comment by Waxwood** [comment]
> > Also, please consider including the ability to add keywords to selected blocks of text in a note.
> 
> I know this issue is already closed, but I just wanted to draw attention to this part of the request, which would be helpful for me as well.

I will post a detailed outline of the type of keywording system that would make Trilium very useful to researchers. I hope the suggestions will be useful for the development of Trilium and increase its appeal to a wider audience. So far, its outstanding.

**Comment by TheNomad11** [comment]
I also thought tagging was not an available feature. I was searching the demo document and did not find any documentation about it. The most logical place to add tags would be in the note info. For me it is  unintuitive to add hashtags at the beginning of the note, it disturbs reading flow and the visual impression. Just my 20 c

**Comment by b8kings0ga** [comment]
I think tagging/keywording function is good, because I wan't to be search not whole text but some text with the same tag in it
