### ISSUE TITLE
Search result is incorrect.

### ISSUE THREAD

**Issue by haha205** [zadam/trilium#1353]
1. Create a new task named TTT, tododate = 2020/10/29.
2. Create a search string as : #todoDate <= TODAY and #cssClass *=* todo orderBy #todoDate asc
3.  Create a search string as : #todoDate > TODAY and #cssClass *=* todo orderBy #todoDate asc
4. TTT appears in both of 2 and 3 query results.

**Comment by zadam** [comment]
Hi, the first thing which I can notice is that you use "2020/10/29" format while search supports only ISO format - "2020-10-29".

Otherwise, I tried to reproduce your problem but I keep getting correct results :/

**Comment by haha205** [comment]
Thank you, I'll keep tracking it.
The date format just because of my writing habits. Actually it's 2020-10-29 in trilium.
I tried again just now, but issue can't be reproduced.

**Comment by nil0x42** [comment]
Just for the record, it looks like this issue can now be deleted.
