### ISSUE TITLE
Search results not refreshed.

### ISSUE THREAD

**Issue by haha205** [zadam/trilium#1354]
1. Search string "#todoDate <= TODAY and #cssClass *=* todo orderBy #todoDate asc" save as "Todo(Expired)".
2. Create a new task, tododate = TODAY
3. Refresh the "Todo(Expired)", task appeared.
4. Set doneDate = TODAY, the task color changes from red to green.
5. Refresh the "Todo(Expired)", task still appeared(Should disappear).
6. Close the Trilium program, re-open, everything is OK.

**Comment by zadam** [comment]
Hi, yes, removal of old search results after refresh was broken, 0.45.2 should behave correctly now.
