### ISSUE TITLE
Used a faulty script, now I am stuck on white screen on startup of trilium.

### ISSUE THREAD

**Issue by a22a-dev** [zadam/trilium#1363]
Can't open anything other than DevTools
How to do i recover from here?
Is there a way to remove the script by loading the db into db browser?

**Comment by zadam** [comment]
Yes, you can open `document.db` in e.g. DB Browser for SQLite, find the offending row (tables `notes` and `note_contents` and fix/comment out the script ...

**Comment by a22a-dev** [comment]
Thank you so much for the quick reply!!!. Everything is good now.
From now on, I would definitely make backup before attempting to do any scripting.

**Comment by zadam** [comment]
I added a note to: https://github.com/zadam/trilium/wiki/Document#manually-modifying-the-document since this might be a common issue.

**Comment by a22a-dev** [comment]
That is great!
