### ISSUE TITLE
[Feature request / Bug Report] Open file directly, provide Open file shortcut, new Keybinds not saving

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1370]
**OS**: MacOS
**Ver**: 0.45.2

Currently, I'm facing an issues. Here is how to reproduce:

1. Add any executable file into a node.
2. In the parent node, click open on the file that was priorly uploaded
3. Observe

Result:File is Downloaded in the Web Browser (Chrome)
Expected* File is opened by the default application

1. Add any executable file into a node.
2. In the parent node, click Download on the file that was priorly uploaded
3. Observe

Result: SaveFileAs dialog opens, where I can specify output file
Expected: File is opened by the default application

Workaround: Make Internal Trilium link and then click "Open". The file is being executed by the default application.

Currently we also don't have a shortcut for opening files, right? 
Would be great to have a key binding.
Before I forget it, when I enter new Keybinds and press apply, saving and re-opening the key-binds dialog, my new Keybinds are lost.

[trilium-2020-11-01.log](https://github.com/zadam/trilium/files/5471886/trilium-2020-11-01.log)

**Comment by zDEFz** [comment]
I have observed, that open files are sent to the programs as copy, which is pretty great for me, as this way I never alter the original. Maybe this is not wanted, in which case I would like to retain open as 'copy'.

**Comment by zadam** [comment]
> 1.  Add any executable file into a node.
> 2.  In the parent node, click open on the file that was priorly uploaded
> 3.  Observe
> 
> Result:File is Downloaded in the Web Browser (Chrome)  
> Expected\* File is opened by the default application

Normal action after clicking "Open" is to open it in a default application. But if there isn't a normal application, then fallback is to open it in a browser which will offer you more actions to do with that file.

**Comment by zDEFz** [comment]
>Normal action after clicking "Open" is to open it in a default application. But if there isn't a normal application, then fallback is to open it in a browser which will offer you more actions to do with that file.

That is not true in my case @zadam . A small screencast in whats happening for me:
https://streamable.com/q696sf

**Comment by zadam** [comment]
Thanks, I thought you're opening from file note itself, the logic in the "book view" was separate. Screencast cleared that up and I fixed that in stable branch ...

Keyboard shortcuts also fixed.
