### ISSUE TITLE
Questions about attributes.

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1377]
Hi Zadam
I wanna ask 2 questions about attribute
**1st**:
Is there any possible make Prefix inheritable (e.g If parent note has WORK as prefix then all other children notes will have it too)
**2nd**:
When I create a **Promoted label** I just want inpu field will show only specific notes (It means will not show recent notes)
Specific note means input field will show only those notes that I want them be there.(e.g. all children notes of Work-note)
Because this way that make things much easier,I don't need to look them up again or type in a spefic name.All specific notes will be shown when I click on input field.
For example I have work-note(Specific note) then there are TODAY/TOMORROW/1 WEEK as subnotes.But these subnotes will be shown directly below the input field,so I easily select it as desire

Waiting for a reply 
Thanks

**Comment by zadam** [comment]
Hi,

1st: no, not possible.

2nd: no, this is not supported. Input field shows recent notes by default and then based on what you input it filters notes further ...
