### ISSUE TITLE
[Feature Request] Split vertically and horizontally panes

### ISSUE THREAD

**Issue by ghost** [zadam/trilium#1379]
It would be great the possibility to split the pane vertically and horizontally as you can do in obsidian. 
![Obsidian multiple panes](https://user-images.githubusercontent.com/70155661/97964079-7a6bb880-1db8-11eb-8005-f9dcee3cf98f.png)

**Comment by zadam** [comment]
Hi, split screen is not supported, but you can open note in new window and then use window manager to position windows next to each other. See also discussion in #950

**Comment by libantas** [comment]
Ok. Thanks.

**Comment by Cubius** [comment]
Perhaps with the introduction of split view this ought to be revisited.

**Comment by zadam** [comment]
Trilium can now split panes in one direction.

**Comment by alpiua** [comment]
Lovely, thank you.
Can you add a vertical split in the future? 
My use case is to have Trilium permanently opened on a separate portrait-mode monitor.
