### ISSUE TITLE
[Bug] Word count widget is not working well

### ISSUE THREAD

**Issue by libantas** [zadam/trilium#1381]
**OS**: Linux
**Version**: 0.45.2

The word count is cut:
![wordcount](https://user-images.githubusercontent.com/70155661/97965696-10a0de00-1dbb-11eb-9aef-1b099ccc1765.png)

**Comment by zadam** [comment]
Hi, you probably have an older version of the script. The problem has been already reported and can be fixed with simple change described in #1224

**Comment by libantas** [comment]
Thanks!!!
