### ISSUE TITLE
[Bug-Feature Request] Pdf download name = note name instead of open.pdf

### ISSUE THREAD

**Issue by libantas** [zadam/trilium#1383]
**OS**: Linux
**Version**: 0.45.2

When you try to download a pdf its name, by default, is open.pdf. What I am asking for is to make the default name the notes name

**Comment by zadam** [comment]
Hmm, that is strange. The intended behavior should be to name the PDF based on its title (just tested on my pc). Not sure where is this "open.pdf" coming from ...

**Comment by libantas** [comment]
When I add a pdf called "xxxxxxxxxx" to trilium it automatically renames as "open". I don't know how to solve this...

**Comment by libantas** [comment]
It is working well. The problem was with the pdf download not with trilium download button.
