### ISSUE TITLE
[Question] How to sort words alphabetically

### ISSUE THREAD

**Issue by libantas** [zadam/trilium#1385]
Is there any way of alphabetically sorting words?

**Comment by zadam** [comment]
Inside a note? Could you describe in more detail what you ask for?

**Comment by libantas** [comment]
Yes, inside a note.

**Comment by libantas** [comment]
I want to sort alphabetically words (with their respective definitions).

**Comment by zadam** [comment]
Well, this is not really a standard editor feature. So not supported.
