### ISSUE TITLE
[Question] Do we have all Boxicons in our Arsenal?

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1390]
Ver. 0.45.2
OS MacOS

Found out that when defining an icon for a node, some Icons are not implemented.
For instance, #iconClass="bx bx-piano"
Simply wanted to use as Icon for my Piano stuff.

Of course,  users could wanted an icon for each instrument. That's why an sorta icon picker or simply inherit from css code would be easier to use.

**Comment by zadam** [comment]
In general yes, all of the box icons are available.

In your case I assume this was caused by the fact that the box icons in Trilium were not in the latest version. I just updated it so e.g. piano should be available in the next version.

**Comment by zDEFz** [comment]
I found out, you must change the way u write a bit.

#iconClass="bx bxs-piano" , in contast to bx-piano, which isn't found. I add it to the Wiki
