### ISSUE TITLE
[Question / possible bug] What exactly are similar Notes?

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1391]
OS:MacOS
Ver: 0.45.2

I have in the bottom a section called 'similar notes'. I tried to find it in the Wiki, but failed.
So, currently, a clipped HTML note is defined "similar" to PDF, MID, MSCZ etc.

But the labels are completely different. Let's have a look:  https://i.imgur.com/D0SISgA.png

Vibration - Health Effects : OSH Answers has the labels : "#clipType=clippings #pageUrl="https://www.ccohs.ca/oshanswers/phys_agents/vibration/vibration_effects.html"

Child of Are has the labels : "#originalFileName="Child of Are.mid" 

How come 200 files are called similar, when at first glance they have nothing in common?

**Comment by zadam** [comment]
It is mostly based on textual similarities between notes - note title, attributes, headings in the text. Sometimes the predicted similar notes are way off, in that case just ignore them (you can also hide the section). The algorithm will also be tweaked for better results ...
