### ISSUE TITLE
[Bug Report] - if #customResourceProvider is empty, we have some funny side-effects

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1393]
[trilium-2020-11-06.log](https://github.com/zadam/trilium/files/5500461/trilium-2020-11-06.log)
OS:MacOS
Ver:0.45.2

I spare you much description.
It's basically like this: 

Set one file with #customResourceProvider but no parameter -> Any file that tries to access any resource from a PATH search will get instead the path of that resource

Set two files with #customResourceProvider but no parameter -> Now we are having two paths concatenated together, our playback will no longer work

Set one file with #customResourceProvider but no parameter AND one file with valid #customResourceProvider="value"-> 
The validly linked video will no longer load, when any file in the application is having an empty #customResourceProvider tag.

https://streamable.com/8sr09v

**Comment by zDEFz** [comment]
Heres my html for the renderNote https://www.w3schools.com/code/tryit.asp?filename=GKFAVC9LHAF6

**Comment by zadam** [comment]
Hi, yes, thanks for reporting, fixed.
