### ISSUE TITLE
Attributes dialog not working from 0.44.9 onwards

### ISSUE THREAD

**Issue by arunabha** [zadam/trilium#1394]
Trilium version 0.44.9, 0.45.2

After version 0.44.9, the note attributes dialog has stopped working. Hitting ALT-A does nothing. The option of 'Note Attributes' is also missing from the note menu (see attached screenshots). This works as expected in 0.42.7 (last version I was using). The other attribute related keyboard shortcuts ALT-L etc work fine.

This behavior occurs even with a fresh install of Trilium.

I am using the portable Trilium script.

[trilium-2020-11-06.log](https://github.com/zadam/trilium/files/5503668/trilium-2020-11-06.log)

![45 2-screenshot](https://user-images.githubusercontent.com/549722/98418989-f4aa7000-2038-11eb-8267-ed648e6ad8bf.jpg)

Any ideas on how to debug this is greatly appreciated.

**Comment by a22a-dev** [comment]
Why do you need attributes dialog? With current labeling and relation setup, the dialog seems redundant.

**Comment by zadam** [comment]
Hello, attribute dialog was removed in 0.44 because it was replaced with attribute widget:

![](https://user-images.githubusercontent.com/617641/98451281-8d79e200-2144-11eb-9200-eddbd56a4e2a.png)

**Comment by arunabha** [comment]
Thanks for the reply folks. Greatly appreciated!
@zadam.
Thanks for the reply!

@a22a-dev the dialog was useful for looking at the cumulative set of attributes set on a note with one action (vs the couple of clicks it will take with the widget). Not a major issue though.

I was wondering if it would be useful to have something like the old attribute dialog in the sidebar? The previous versions had a link in the note info section on the sidebar. If this is something that will benefit others, I'll be happy to volunteer to add the old attributes dialog back as a link on the sidebar.

**Comment by Tukks** [comment]
Hello,
Same wondering, now how do I add attribute to my note?
I don't find the attribute widget.

Thanks for your help

**Comment by zadam** [comment]
@Tukks 

See: 

![](https://user-images.githubusercontent.com/617641/98451281-8d79e200-2144-11eb-9200-eddbd56a4e2a.png)

that's editable list of attributes ...

**Comment by arunabha** [comment]
Closing the issue. Thanks for the help @zadam !
