### ISSUE TITLE
[HTML5 Bug] Video Seeking forward doesn't work inside Trilium, exported files missing?

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1395]
Ver:0.45.2
OS:MacOS

Do the following:

Give customResourceProvider to your video

Create a RenderNote, link a HTML file to it
Insert:

 
```
<video  controls>
 <source src="custom/video/video.mp4" type="video/mp4">
</video>

```
Now try to seek. No support given.

**Edit: However, it works when the file comes over HTTP, via the browser. This is super weird!**

Screencast:
https://streamable.com/nu4ggp
[trilium-2020-11-07.log](https://github.com/zadam/trilium/files/5504982/trilium-2020-11-07.log)

Another Question I have here:

I have exported this node, but the linked Videos that come from the custom path aren't included nor transformed into the exported HTML.
The files linked are in another note, however, I think video/ should be exported nonetheless.

**Comment by zDEFz** [comment]
Edit: The funny thing is, https://videojs.com/ does work.

Working example, copied from:
https://github.com/videojs/video.js/releases/tag/v7.10.2

```
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Video.js | HTML5 Video Player</title>
    <link href="http://vjs.zencdn.net/7.0/video-js.min.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/7.0/video.min.js"></script>

</head>
<body>

  <video id="example_video_1" class="video-js" controls preload="none" width="640" height="264" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
    <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4">
    <source src="http://vjs.zencdn.net/v/oceans.webm" type="video/webm">
    <source src="http://vjs.zencdn.net/v/oceans.ogv" type="video/ogg">
    <track kind="captions" src="../shared/example-captions.vtt" srclang="en" label="English">
    <track kind="subtitles" src="../shared/example-captions.vtt" srclang="en" label="English">
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>

</body>

</html>
```

**Comment by zadam** [comment]
Trilium itself has no control over \<video> tag, that's handled by the rendering engine so I expect the differences in behavior there ...

> I have exported this node, but the linked Videos that come from the custom path aren't included nor transformed into the exported HTML.  
> The files linked are in another note, however, I think video/ should be exported nonetheless.

Export works only on the selected subtree (or single note), it won't pull linked notes to the export. This is intentional.

**Comment by zDEFz** [comment]
I see. But this makes it a bit harder to implement, I guess, we can't make use of HTML5 players for Trilium when they only work over HTTP/webservers.

I'm still for the direct link to the file, that opens it directly, without going into the node where the file is named. 
I forgot, was it implemented already, or will it?

**Comment by zadam** [comment]
> I'm still for the direct link to the file, that opens it directly, without going into the node where the file is named.  
> I forgot, was it implemented already, or will it?

Not implemented. Perhaps it would make sense to provide user a choice to link to the file note, or the file directly. But this is not a high priority issue.
