### ISSUE TITLE
The container linked to arm64v8 doesn't really work (binary is not compatibable)

### ISSUE THREAD

**Issue by hysci** [zadam/trilium#1399]
I would recommend either removing the link to arm64v8 docker hub and explicitly claiming this platform is not supported, or adding the support for the platform. The binary doesn't work for arm64v8.

I also tried `npm install` in arm64v8, the error message is
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/share/nodejsv8/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.2.8
gyp ERR! command "/share/nodejsv8/node/bin/node" "/share/nodejsv8/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/share/Web/trilium/trilium-0.45.2/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node" "--module_name=lzma_native" "--module_path=/share/Web/trilium/trilium-0.45.2/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /share/Web/trilium/trilium-0.45.2/node_modules/lzma-native

I guess the reason is lzma-native doesn't support arm64v8 yet. When it falls back to rebuild, the process is buggy.

**Comment by jokajak** [comment]
I pushed an image of v0.46 to https://hub.docker.com/repository/docker/jokajak/trilium
Verified it works in my kubernetes cluster too.

**Comment by Myzel394** [comment]
Doesn't work on Pi 3B+ :(

**Comment by jokajak** [comment]
womp womp. What is the error you received? I built it using podman on a Pi 3B+ so I'm curious what went wrong.

**Comment by Myzel394** [comment]
Exactly the same as @hysci mentioned. But I ended up using https://hub.docker.com/r/hlince/trilium - which worked perfectly. Hopefully official docker files will work soon :C

**Comment by jokajak** [comment]
Ah, perfect. That means this issue is *slightly* different than your's. Specifically, the https://hub.docker.com/r/hlince/trilium is built for armv6 (32bit) whereas the one I built is arm64v8 (64bit).

**Comment by Myzel394** [comment]
Wait a minute - I also got the Pi 3B+, why did it work on yours but not on mine? Because of podman?

**Comment by jokajak** [comment]
Great question. It's because I configured my Pi 3B+ with a 64bit kernel. I'm trying out docker buildx to automagically create multi-arch images and will submit a PR with the github action that enables it.

**Comment by jokajak** [comment]
I just pushed a new latest version that is multi-arch compatible. Need to figure out mapping releases to tags though.

**Comment by Myzel394** [comment]
Tried 0.46-latest, didn't work on Raspberry PI 3B+, 32bit Raspbian. error: `standard_init_linux.go:207: exec user process caused "exec format error"`
