### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by tmaleshafske** [zadam/trilium#1400]
Having issues with syncing on Windows package of 0.45.2

Linux Server instance of the same version and Linux desktop version loaded from the .deb have no issues.

> A JavaScript error occurred in the main process
Uncaught Exception:
 Error: net::ERR_CONTENT_LENGHT_MISMATCH      
          at SimpleURLLoaderWrapper.<anoymous> (electron/js2c/browser_init.js:93:6365)
          at SimpleURLLoaderWrapper.emit (events.js:223:5) 

[trilium-2020-11-10.log](https://github.com/zadam/trilium/files/5518504/trilium-2020-11-10.log)
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by tmaleshafske** [comment]
I did attempt to delete and re-download all data, but it didn't resolve the issue.

**Comment by zadam** [comment]
This is a network error - the data is (typically) shorter than advertised by `Content-Length` header.

Usually something in the network (usually proxy servers) are messing with the network payload.

I remember having that problem with nginx, but that was quite specific (low disk space on proxy server).
