### ISSUE TITLE
Promoted date attribute stops saving after entering an invalid date

### ISSUE THREAD

**Issue by mabeyj** [zadam/trilium#1404]
If you type an invalid date for a promoted attribute and then correct it to a valid date, the valid date doesn't get saved. This seems to break saving the attribute until the note is reloaded.

1. Create a promoted attribute with type Date.
2. Type an invalid date like 2020-11-99 using the promoted attribute UI.
3. Type or select any valid date like 2020-11-12. The attribute doesn't save.
4. Switch to a different note then switch back. The attribute will now save a valid date.

![invalid-date](https://user-images.githubusercontent.com/773401/98850700-86e0b880-242b-11eb-8721-af5d84d2f690.gif)

* Version 0.45.3
* No error in console or logs

**Comment by zadam** [comment]
Hi, thanks for reporting this bug, it has been fixed and will be released in the next stable version.
