### ISSUE TITLE
Promoted relations add duplicate values when changed

### ISSUE THREAD

**Issue by mabeyj** [zadam/trilium#1405]
If you change the value of a relation using the promoted attributes UI, duplicate attributes get added to the note even when the relation is set to single-value multiplicity.

1. Create a promoted relation.
2. Select a note using the promoted relation UI. A single value correctly gets set for the relation.
3. Change the relation to a different note. This correctly updates the relation value.
4. Unfocus the relation input field (e.g., clicking note content). A second value gets added for the relation.
5. Change the relation a third time. A third value gets added (and previous values are not updated).
6. Unfocus and a fourth value gets added.

![duplicate-relations](https://user-images.githubusercontent.com/773401/98853581-b8f41980-242f-11eb-9863-ed97629bfdc6.gif)

* Version 0.45.3
* No error in console or logs

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it's now fixed in stable branch.
