### ISSUE TITLE
Changing attributes unhides images included in the note

### ISSUE THREAD

**Issue by mabeyj** [zadam/trilium#1406]
If you have the "Hide images included in a note" tree setting enabled and you make any change to a note's attributes, the images included in the note become visible in the tree.

![change-attribute-unhides-images](https://user-images.githubusercontent.com/773401/98855740-e0001a80-2432-11eb-9974-242f8d8ca835.gif)

* Version 0.45.3
* No error in console or logs

**Comment by zadam** [comment]
Hi, I appreciate your nice bug reports, thanks! This one has also been fixed ...
