### ISSUE TITLE
can include note and link map each have a shortcut for quick use?

### ISSUE THREAD

**Issue by zengshenghai** [zadam/trilium#1410]
sorry for my english.

**Comment by zadam** [comment]
You can configure Link map shortcut here:

![](https://user-images.githubusercontent.com/617641/98948317-92e57c80-24f6-11eb-85f4-55ade18dbf75.png)

Include note is currently not supported.

**Comment by zengshenghai** [comment]
Thanks. Include note can't?

**Comment by zengshenghai** [comment]
Thanks.

**Comment by zadam** [comment]
added keyboard shortcut for the include note to stable branch.
