### ISSUE TITLE
Error exporting notes like at all. 

### ISSUE THREAD

**Issue by kokomo123** [zadam/trilium#1411]
I'm using the latest version, which of this writing is 0.45.3, my DB version is 170 and I am using the binary option on Ubuntu 20.04.1 LTS in a LXC on Proxmox. I've been having issues exporting notes, and when i look in devtools it says this error in screenshot below, its in the log as well. 
Reproduction steps:
1.Go to note in question, right click and export note
2.press export in html. Hit the export button
3.Nothing happens, get error. 
Some 404s for missing files, which i was able to download from the repo, but that didn't help either. Not sure what i'm doing wrong. 
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:
[trilium-2020-11-12.log](https://github.com/zadam/trilium/files/5531719/trilium-2020-11-12.log)
* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS
![image](https://user-images.githubusercontent.com/70863536/98963895-29ee0c80-24d6-11eb-976b-9c9f88b4788f.png)
![image](https://user-images.githubusercontent.com/70863536/98964105-69b4f400-24d6-11eb-98a8-73121efd608e.png)
Hope this helps. I'll be able to provide more info if needed. Thanks.

**Comment by zadam** [comment]
Hi, this seems to be a regression in 0.45.3. I will release fixed version tonight. If you can't wait, you can downgrade to 0.45.2.

Thanks for reporting.

**Comment by kokomo123** [comment]
Sounds good. I'll wait for the upgrade tonight, thanks a bunch for the quick response.
