### ISSUE TITLE
Add the ability to set or update label

### ISSUE THREAD

**Issue by Tukks** [zadam/trilium#1412]
I have label like :
kanban:todo
kanban:done
and a html board, when I drag the note from todo to done, I want to update the label note.

How I can do that with the script API?

Thanks for your help

**Comment by zadam** [comment]
See the API docs here: https://zadam.github.io/trilium/backend_api/Note.html

There are methods like `setLabel` etc.

BTW, for such questions consider discussion forum instead: https://github.com/zadam/trilium/discussions
