### ISSUE TITLE
[Question / Suggestion] Release note

### ISSUE THREAD

**Issue by hysci** [zadam/trilium#1415]
Trilium is an excellent software, however, there is no release note in the link: https://github.com/zadam/trilium/releases/tag/v0.45.4
The users don't know if it deserves to upgrade to this version. 
Besides, it is safe to directly override the old version with the latest binary?

**Comment by zadam** [comment]
Yeah, I'm just too lazy to compile the list. Anyway, if there are no release notes, then it's usually bugfixes only.

You can also check commits on the stable branch which usually references fixed issues: https://github.com/zadam/trilium/commits/stable

I will try to get less lazy though ...
