### ISSUE TITLE
Export fails, then succeeds

### ISSUE THREAD

**Issue by Linecutterx** [zadam/trilium#1417]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

Using the latest version (today's autobuild docker image for arm)
Export as html (zip) fails, but a subsequent export to markdown succeeds & after that html export functions. The logs show an uncaught error (or two)

14:48:21.227 Slow POST /api/recent-notes took 13ms
14:48:32.943 JS Error: Uncaught error: Message: Uncaught TypeError: openService.download is not a function, URL: https://<redacted>/app/dialogs/export.js, Line: 79, Column: 17, Error object: {}, TypeError: openService.download is not a function
    at exportBranch (https://<redacted>/app/dialogs/export.js:79:17)
    at HTMLFormElement.<anonymous> (https://<redacted>/app/dialogs/export.js:69:5)
    at HTMLFormElement.dispatch (https://<redacted>/libraries/jquery.min.js:2:43090)
    at HTMLFormElement.v.handle (https://<redacted>/libraries/jquery.min.js:2:41074)
Stack: Error
    at Object.logError (https://<redacted>/app/services/ws.js:28:20)
    at window.onerror (https://<redacted>/app/services/glob.js:65:12)
14:48:33.009 Generated CSRF token <redacted> with secret undefined
14:48:33.101 Slow GET /?export-type=subtree&export-subtree-format=html&opml-version=2.0 took 101ms
14:48:35.961 Slow GET /api/tree took 16ms
14:48:36.078 GET /api/options took 4ms
14:48:36.086 GET /api/keyboard-actions took 7ms
14:48:36.095 GET /api/notes/download/bgDSDuL0il6m took 8ms
14:48:36.098 GET /api/keyboard-shortcuts-for-notes took 2ms
14:48:36.103 GET /api/script/widgets took 5ms
14:48:36.106 GET /api/notes/download/stOKcNaOB9Ui took 1ms
14:48:36.335 POST /api/tree/load took 4ms
14:48:38.860 GET /api/script/startup took 4ms
14:48:38.976 GET /api/notes/ArpLw8RhGPdZ took 2ms
14:48:39.123 POST /api/tree/load took 3ms
14:48:39.872 POST /api/tree/load took 8ms
14:48:40.095 Slow GET /api/similar-notes/ArpLw8RhGPdZ took 92ms
14:48:40.106 GET /api/notes/ArpLw8RhGPdZ/revisions took 2ms
14:48:40.110 POST /api/tree/load took 3ms
14:48:40.374 Slow POST /api/tree/load took 22ms
14:48:43.986 Slow POST /api/recent-notes took 11ms
14:49:48.949 Slow GET /api/options took 10ms
14:49:49.362 Slow GET /api/keyboard-actions took 11ms
14:49:49.457 GET /api/options/user-themes took 3ms
14:52:48.450 Slow PUT /api/options took 12ms
14:52:48.457 GET /api/notes/root took 5ms
14:52:48.814 GET /api/notes/1jAMK8CbG5aH took 2ms
14:52:49.002 GET /api/images/BDTVLb9OZsh2/trilium-small.png took 2ms
14:52:49.089 GET /api/notes/aLb9KSey9Xi1 took 2ms
14:52:49.261 Slow GET /api/similar-notes/root took 43ms
14:52:49.269 GET /api/notes/root/revisions took 2ms
14:52:53.273 Slow POST /api/recent-notes took 12ms
14:56:40.871 GET /api/notes/ArpLw8RhGPdZ took 6ms
14:56:40.986 Slow PUT /api/options took 13ms
14:56:41.793 Slow GET /api/similar-notes/ArpLw8RhGPdZ took 45ms
14:56:41.811 GET /api/notes/ArpLw8RhGPdZ/revisions took 4ms
14:56:42.053 POST /api/notes/ArpLw8RhGPdZ/link-map took 3ms
14:56:45.396 Slow POST /api/recent-notes took 13ms
14:56:51.016 JS Error: Uncaught error: Message: TypeError: (intermediate value).download is not a function, URL: https://<redacted>/app/dialogs/export.js, Line: 79, Column: 17, Error object: {}, exportBranch@https://<redacted>/app/dialogs/export.js:79:17
@https://<redacted>/app/dialogs/export.js:69:17
dispatch@https://<redacted>/libraries/jquery.min.js:2:43090
add/v.handle@https://<redacted>/libraries/jquery.min.js:2:41074

Stack: logError@https://<redacted>/app/services/ws.js:28:20
setupGlobs/window.onerror@https://<redacted>/app/services/glob.js:65:12

14:56:51.151 Generated CSRF token <redacted> with secret undefined
14:56:51.189 Slow GET /?export-type=subtree&export-subtree-format=html&opml-version=2.0 took 40ms
14:56:58.011 Slow GET /api/tree took 10ms
14:56:58.021 GET /api/options took 3ms
14:56:58.028 GET /api/keyboard-actions took 5ms
14:56:58.031 GET /api/keyboard-shortcuts-for-notes took 2ms
14:56:58.130 GET /api/notes/download/bgDSDuL0il6m took 2ms
14:56:58.133 GET /api/notes/download/stOKcNaOB9Ui took 2ms
14:56:58.136 GET /api/script/widgets took 2ms
14:56:58.226 POST /api/tree/load took 3ms
14:57:00.102 GET /api/notes/ArpLw8RhGPdZ took 2ms
14:57:02.204 GET /api/script/startup took 7ms
14:57:02.362 Slow GET /api/similar-notes/ArpLw8RhGPdZ took 145ms
14:57:02.371 GET /api/notes/ArpLw8RhGPdZ/revisions took 3ms
14:57:02.556 POST /api/tree/load took 3ms
14:57:02.658 Slow POST /api/tree/load took 15ms
14:57:02.914 POST /api/tree/load took 7ms
14:57:03.064 POST /api/tree/load took 3ms
14:57:05.090 POST /api/recent-notes took 6ms
14:57:05.711 GET /api/notes/FTRI26OJtti2 took 2ms
14:57:06.018 GET /api/notes/0WjsZ4kIc1q7 took 2ms
14:57:06.158 GET /api/images/0WjsZ4kIc1q7/Screenshot%202020-11-12%20134531.png took 2ms
14:58:50.249 Sending message to all clients: {"type":"task-progress-count","taskId":"bqYIMUtMkM","taskType":"export","progressCount":0}
14:58:50.396 Slow query took 35ms: SELECT content, hash FROM note_contents WHERE noteId = ?
14:58:50.671 Sending message to all clients: {"type":"task-progress-count","taskId":"bqYIMUtMkM","taskType":"export","progressCount":91}
14:58:50.895 Sending message to all clients: {"type":"task-succeeded","taskId":"bqYIMUtMkM","taskType":"export"}
14:58:50.898 Slow GET /api/notes/Y5LpH6BxRjqg/export/subtree/markdown/1.0/bqYIMUtMkM took 655ms
14:59:01.689 Slow GET /api/notes/FTRI26OJtti2 took 23ms
14:59:01.981 GET /api/notes/0WjsZ4kIc1q7 took 2ms
14:59:02.120 GET /api/images/0WjsZ4kIc1q7/Screenshot%202020-11-12%20134531.png took 2ms
14:59:04.199 GET /api/notes/0WjsZ4kIc1q7 took 5ms
14:59:04.592 GET /api/notes/FTRI26OJtti2 took 5ms
15:00:23.529 Sending message to all clients: {"type":"task-progress-count","taskId":"wXmvm0mj5b","taskType":"export","progressCount":0}
15:00:23.829 Sending message to all clients: {"type":"task-progress-count","taskId":"wXmvm0mj5b","taskType":"export","progressCount":94}
15:00:24.059 Sending message to all clients: {"type":"task-succeeded","taskId":"wXmvm0mj5b","taskType":"export"}
15:00:24.060 Slow GET /api/notes/Y5LpH6BxRjqg/export/subtree/html/1.0/wXmvm0mj5b took 532ms
15:00:31.421 GET /api/notes/FTRI26OJtti2 took 6ms

**Comment by zadam** [comment]
That looks like a bug fixed in latest version - 0.45.4. I don't know what docker image are you using, but it's probably not the latest version.

**Comment by Linecutterx** [comment]
0.45.4 according to the "About" menu.
