### ISSUE TITLE
https to http proxy failed

### ISSUE THREAD

**Issue by hysci** [zadam/trilium#1419]
It works directly accessing http://10.8.50.8:8080 to a trilium server, however, when using nginx https configured as follows (nginx.conf):

```
server {
    listen 443 ssl http2;
    server_name xxx.yyy.com;
    include ./nginx.ssl.conf;
    location / {
        proxy_pass http://10.8.50.8:8080/;
    }
} # server
```

There is no response to the server in the web browser (either for chrome or firefox) https://xxx.yyy.com. The log in the node console is:
```
GET /login took 7ms    
Generated CSRF token z7MxcmE5-NPYIyZYLFIY84RxpsLdpjTHRhvk with secret undefined 
Slow GET / took 14ms   
Generated CSRF token b0P3iC8r-koEZfFJqSbIzsbuFjDlFKDBGcpA with secret undefined
Slow GET / took 10ms   
GET /login took 1ms  
Generated CSRF token wlR6vnEm-NY_BOQ9KB0wAfhiPhNmUL3ZFCHg with secret undefined
GET / took 7ms  
Generated CSRF token ynkOFKn4-5cH2IrBucuEgj3AVHArTby0ZG_A with secret undefined GET / took 7ms
```

Environment:
trilium 0.45.x (master)
node 10.19
npm 6.14.4
OS: ubuntu 20.04

**Comment by zadam** [comment]
Seems like a nginx config issue. Search issues, many people have used nginx and had various problems.

There's also this example config which should work: https://github.com/zadam/trilium/wiki/Server-installation#reverse-proxy-setup

**Comment by hysci** [comment]
I used the same nginx config to proxy https to http on nextcloud and wordpress. 
They work fine.
So I guess there could be some missing implementation in trilium.

**Comment by taxidis** [comment]
This works for me. You may omit ssl options.

`server {

    listen 443;
    server_name my.trilium.server;
    ssl_certificate /path/to/cert
    ssl_certificate_key /path/to/cert/key
    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/access.log;
    location / {
               proxy_pass https://127.0.0.1:8080/;
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection 'upgrade';
               proxy_set_header Host $host;
               proxy_cache_bypass $http_upgrade;
    }
}
`

**Comment by hysci** [comment]
Isn't `listen 443` only allow the http access? e.g., `http://my.trilium.server` but not `https://my.trilium.server`
