### ISSUE TITLE
Fails to sync from desktop app to server

### ISSUE THREAD

**Issue by hysci** [zadam/trilium#1420]
Steps:

- Download v0.45.4 source code
- npm install && npm audit fix
- npm run start-server
- Access http://localhost:8080, choose option 2 (sync with desktop app)
- Open desktop app (windows 10, v0.45.3), fill in http://localhost:8080 in options -> Sync -> Server instance address
- Click "save", then click "Test sync", it shows successful
- Click "Sync now"

The message in the node console is:
`
GET /setup took 2ms                                                                                                     Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 0ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}                        GET /api/sync/stats took 1ms                                                                                            Returning sync stats: {"initialized":false,"stats":{"outstandingPushes":0,"outstandingPulls":0}}        `

Looks like the sync doesn't end within 30min.

**Comment by zadam** [comment]
Hi, maybe I don't understand, but was your desktop app initialized (meaning it already has some data ...)?

**Comment by hysci** [comment]
Yes, it has some data. The process is as follows:
> Setup a new server, it works.
> Setup a desktop app initialized/synchronized from the server. (desktop app has data)
> Setup another new server, initialize it from the desktop app, it failed.

**Comment by rmdes** [comment]
Having the same problem, my server is running just fine but when I try to sync it with my desktop app, I have the exact same log output and I have this error on the desktop interface : 
Sync setup failed: Request to get https://note.my.domain/api/setup/sync-seed failed, error: 401
