### ISSUE TITLE
[Feature Request] Back to index

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1428]
Hey guys,

I was wondering why I have to manually create "Back to Index" with link to my index file foreach single file manually and why it isn't an option to turn on.

What do you think?

Best.

**Comment by zadam** [comment]
I don't understand what you mean by "Back to index".

**Comment by zDEFz** [comment]
Hey zadam. It's basically go back to file X and display an detailed overview of specified sections.

My Index currently looks like this... and you see why I want an index.

![image](https://user-images.githubusercontent.com/24463722/99443485-2b2a9980-291b-11eb-8d3d-63e5db3c830c.png)

**Comment by zadam** [comment]
Why do you need such a link? I mean there's a back button also a back button here:

![](https://user-images.githubusercontent.com/617641/99444059-f8cd6c00-291b-11eb-8e5b-005cffcdba3e.png)

**Comment by zDEFz** [comment]
Cause it doesn't always bring me to the same location always. When you do two actions before, it then takes twice as long to get back.

Also, the back button is strategically in a bad place. Super small, hard to see.

Laws of UX, big surface = more likely to be seen and used.

To start with, a mouse is needed and not optional for using Trilium-Notes, because the editor can't be set in read-only mode, so that tab order would be followed, correct?
Because of that, I think it's kinda important to get such functionality more in focus...

**Comment by meichthys** [comment]
I go mouseless all the time. I find it to be super quick to do:
`ctrl-j` then type `index` then hit `down arrow` then smash `Enter`.
It only takes about a second once it becomes muscle memory!

**Comment by meichthys** [comment]
> 
> 
> Why do you need such a link? I mean there's a back button also a back button here:
> 
> ![](https://user-images.githubusercontent.com/617641/99444059-f8cd6c00-291b-11eb-8e5b-005cffcdba3e.png)

These arrows don't exist in the Web UI, is this because we can use the built-in browser forward/back buttons?

**Comment by zDEFz** [comment]
Thanks. I wasn't aware!

**Comment by zDEFz** [comment]
I had to change META+J to CTRL+J, because the shortcut was not functioning with META+J

**Comment by Engr-AllanG** [comment]
This seems more of a workflow specific feature. Maybe this could be achieved with a script.

I use a similar workflow/layout - I have one index, and a bunch of MOC' (Map Of Contents). The MOC's are basically lists of links for whatever the MOC is about. I think I can relate to you wanting to put a link back to index in every note and how that becomes tiresome. The way I use MOC's makes it so I generally have links to just about everything from an MOC, which provides useful backlinks from the "What Links Here" side pane. What I'm trying to get at is you might consider changing your workflow and change/improve how you are linking to see if you can build in more value without requiring that specific feature. Just some thoughts

**Comment by zadam** [comment]
> These arrows don't exist in the Web UI, is this because we can just use the built-in browser forward/back buttons?

Yes, browser back/forward button work the same and that's the reason they are missing in the web UI.
