### ISSUE TITLE
[Bug Report] HTML Style overrides Theme

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1429]
Ver 0.45.4
OS: macOS Big Sur

as Title.

Video: https://streamable.com/fbzy41

log in attachment

What can I do to prevent this behavior? It's not the app theme, the css should only affect the container in the right with the renderNote...
I even added some lines so at least I can identify what is a link and what is not..

Sample code (affecting already)

<!DOCTYPE html>
```
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<style>  
```

By the way, exposing my files through a local fileserver and then using the media tags works for seeking. I think it's cause electron... custom/video ... does not allow for seek.

[trilium-2020-11-17.log](https://github.com/zadam/trilium/files/5553927/trilium-2020-11-17.log)

**Comment by zadam** [comment]
If you include a CSS into a page, it's applied on that whole page. That's just how CSS works.

Ways around it are using iframe or better to control the css yourself and scope it using CSS classes (so e.g. `.note-detail` as a prefix for all declarations).

**Comment by zDEFz** [comment]
I'm not sure if you understood me. What I'm saying the rendered HTML should be isolated from the other components. 
e.g the tree everything but the rendered HTML page should remain the complete same, except it's defined as appTheme or something.

**Comment by zadam** [comment]
Yes, I understood you and the answer is that that is not possible unless you use an iframe. HTML/CSS alone do not support such isolation.

**Comment by zDEFz** [comment]
Interesting. So that would mean, in order to have one behavior, I have to host it locally on a http server, make the changes, then embed it again via iframe?

I also tried to use the w3 css as app-theme, but upon entering my HTML renders, it still looked different. I want one look, not two. And the reason I use the css is because I want my videos to be embedded full,halved, thirds etc.

**Comment by zadam** [comment]
> Interesting. So that would mean, in order to have one behavior, I have to host it locally on a http server, make the changes, then embed it again via iframe?

I guess that would be one way?

Personally I would just copy he stylesheets and embed them into Trilium with `#appCss`

**Comment by zDEFz** [comment]
The thing is, I did that, but it didn't affect Trilium-Notes... 
![image](https://user-images.githubusercontent.com/24463722/99445041-4f877580-291d-11eb-993f-f0f0fdcde2df.png)
