### ISSUE TITLE
How to change the line spacing?

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1432]
Hi

Is there a way to change the line spacing globally and per page? I fill out pages way too quickly because the lines are way to apart. This is especially and issue with indented lines.

thanks

**Comment by zadam** [comment]
You could play with custom appCss: https://github.com/zadam/trilium/wiki/Themes#custom-css

**Comment by gerroon** [comment]
Thanks for the reply. Is it possible to provide a basic example for those who knows nothing about this stuff? 

Thanks

**Comment by yllekz** [comment]
Is there any way to add line spacing as a GUI option? Having a user dive into CSS code to fix it isn't a very good user experience in my opinion.
