### ISSUE TITLE
Day Note Children

### ISSUE THREAD

**Issue by tmaleshafske** [zadam/trilium#1434]
I attempted to create a child day not and it doesn't appear to be working on 0.45.2  

Here is how I have it and doesn't generate an additional note under the main day note

`#iconClass="bx bx-notepad" #label:TAGS=promoted,multi,text ~child:template=Habit tracker template`

>  I just enabled this in f5f48ef so it should be possible in the next release.
> 
> _Originally posted by @zadam in https://github.com/zadam/trilium/issues/1236#issuecomment-69225552

**Comment by zadam** [comment]
> Here is how I have it and doesn't generate an additional note under the main day note

That's not what it's supposed to do. This will just set the template relation for any potential child note you create.

**Comment by tmaleshafske** [comment]
Fair enough I guess the better question is whether it's possible to automatically create them then?

**Comment by zadam** [comment]
Actually I just implemented this functionality and it will be in the 0.45.5.

All children notes of a template will be duplicated into the "instance" note.

**Comment by tmaleshafske** [comment]
I will try it out when released.  With the way I had the relation set, is that how it's implemented or will it be different?

**Comment by zadam** [comment]
Just create the desired structure under the template and it will be then copied (including all attributes etc.) into day notes:

![](https://user-images.githubusercontent.com/617641/99718416-1e3cb000-2aab-11eb-961d-abdfa9a7acd1.png)

**Comment by tmaleshafske** [comment]
Awesome

**Comment by tmaleshafske** [comment]
@zadam doesn't appear to be working on 0.45.5  It still only creates the one note and none of the subnotes.

**Comment by zadam** [comment]
For me it's working ... Can you post a screenshot how the date template note looks like?

**Comment by tmaleshafske** [comment]
![Capture](https://user-images.githubusercontent.com/11547277/100014463-06f80e00-2d9c-11eb-8d89-0e32332c0e27.PNG)

**Comment by zadam** [comment]
Perhaps one important point is that the template is activated at the point of creation of a new note. Meaning to have this in effect the note must be created. Was the day note you're checking perhaps created before you upgraded to 0.45.5?

**Comment by tmaleshafske** [comment]
I ended up having to delete and recreate it a few times then it started working.
