### ISSUE TITLE
Is there a view-only mode in trilium

### ISSUE THREAD

**Issue by hysci** [zadam/trilium#1435]
It is painful to change the contents by mistake, while I only want to view but not edit the contents most of the time. Is there a view-only mode in trilium?

**Comment by tmaleshafske** [comment]
if I am not mistaken you can set a note to read-only by applying an attribute. please reference the wiki at this [page](https://github.com/zadam/trilium/wiki/Attributes) and also looking at #371

**Comment by zadam** [comment]
Yes, per note it's possible to set, globally not. (unless you set `readOnly` on root note and as inheritable)

**Comment by hysci** [comment]
It is not convinient as it is per note attribute and it is only applicable to text node, but it is better than nothing. Thanks.
