### ISSUE TITLE
Is collaborative edit possible (assume there is no simultaneous edit at the same time)?

### ISSUE THREAD

**Issue by hysci** [zadam/trilium#1436]
I still didn't find a good way to sync local notes among different devices: Mac PC1, Windows PC2, Linux Server, etc.  (Refer to issue: https://github.com/zadam/trilium/issues/1420)

Is it practical to sync "trilium-data" and "Trilium Notes" folder on the cloud (e.g., owncloud/nextcloud)? 
Is the config/DB compatible with cross-platform?
Is it safe to do so in case that SQLite DB is a single file? There could be a potential issue that the conflict can't be resolved if I edit one page on one PC and edit another page on another PC unless I do a full synchronization before a new change.

**Comment by tmaleshafske** [comment]
@hysci That is what I am currently doing since I was having issues with sync.  The biggest issue I am having with this is remembering to close down instances to avoid conflict. You will not be able to have multiple instances pulling from the same document.db  The other thing you have to do is set a system variable for Trillium to the correct directory with each individual instance. Instructions on this are located [here](https://github.com/zadam/trilium/wiki/Data-directory)

**Comment by zadam** [comment]
> Is the config/DB compatible with cross-platform?

Yes.

> Is it safe to do so in case that SQLite DB is a single file? There could be a potential issue that the conflict can't be resolved if I edit one page on one PC and edit another page on another PC unless I do a full synchronization before a new change.

That's a problem and you need to be very careful in your usage (as @tmaleshafske ). In general I do not recommend this approach.

**Comment by tmaleshafske** [comment]
@zadam Couldn't agree with you more.  It has been extremely challenging.  My Internet at home finally goes on fiber today and I am hoping that will help the network throughput issues I was having with sync.

**Comment by Flashwalker** [comment]
It would be nice to have an option to sync the db to owncloud/nextcloud as a folders tree of separate plain .md files

**Comment by zadam** [comment]
@Flashwalker that's a bit off topic, but here's some rationale: https://github.com/zadam/trilium/wiki/FAQ#why-database-instead-of-flat-files

**Comment by Flashwalker** [comment]
Well...
how about to:
- store the note as a file or as a folder with index.md file, if it has content, and with a folder of sub-notes, if it has sub-notes.
- store clones as relative symlinks/hardlinks to .md files.
- store relations about clones, links, attributes, etc in metadata DB.

So we have a flat files and all power of DB at once
