### ISSUE TITLE
[Suggestion] Update backup instead of creating it anew

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1440]
Hello guys,

I have observed that MEGA.NZ doesn't version my files for more than 2 versions.
Essentially triggers MEGA.NZ to delete the old file on the server.

This could be assumedly because of... :

- Trilium-Notes does delete the old file and create a new backup

Whereas, for versioning, I would need that Trilium-Notes simply updates the file, rather than replacing it.
If I am correct, please let me know if you could make this tiny change.

It would make it possible for me, to have file versioning for my backup databases, in common cloud backup platforms.

Sometimes, I face the difficulty that:

- deleted files are not showing up in History
- changing text quickly in a script doesn't show up in file history
- reverting simple changes back when whole nodes where deleted feels difficult to impossible,

**Comment by zadam** [comment]
Frankly I have trouble understanding your post.

What files and backups are you talking about?

> Whereas, for versioning, I would need that Trilium-Notes simply updates the file, rather than replacing it.

What do you mean by that?

**Comment by zDEFz** [comment]
@zadam When you edit a `text file` in a `text editor`, the files content is being `updated`

Upon file change, cloud services such as `mega.nz` sync the file.
However, in my case, only `two versions` are stored at a time for `trilium-notes`
Assumedly, because the files `backup-daily, backup-weekly, backup-now` are being deleted upon recreation if they are already present, rather than updated/overwritten. When a file is deleted using such a `cloud service`, it's deleted also on the cloud.
But for the routine: You probably have the better insight.

**Comment by zadam** [comment]
Trilium uses native SQLite backup function which overwrites the existing file. Nothing to do here. (seems like an issue with Mega anyway)

**Comment by zDEFz** [comment]
Thanks. I will escalate it to MEGA, debugging the process and come back at you with the results.

**Comment by zDEFz** [comment]
You must reload your account on MEGA.NZ, seems to be working now. Sample: 
![image](https://user-images.githubusercontent.com/24463722/100091338-c3150f80-2e54-11eb-8031-9ba66222459d.png)
