### ISSUE TITLE
[Request] Easier way to set the data directory

### ISSUE THREAD

**Issue by Fastidious** [zadam/trilium#1441]
Would it be possible to implement an easier way to set the data directory? I understand this is not a priority—and I don't have ability to code a contributing PR—but perhaps adding it as an enhancement to a future TODO list? Thank you so much for such useful application!

**Comment by zadam** [comment]
Where would you store this setting though?

**Comment by Fastidious** [comment]
@zadam perhaps under advanced options? Or on the right of the “Data directory:” under “About Trilium Notes?” Something like a “Set” button, or “Change” bottom, which will allow to browse to a new location, maybe?

**Comment by Fastidious** [comment]
Oh, I misunderstood. Where to store it, was the question. Hmm, I am not knowledgeable on how the other app settings are saved, or where—like the theme, font size, etc. for example—but I would store the setting somewhere (I know, a very lose term) around the same area. 🙈

**Comment by zadam** [comment]
> I am not knowledgeable on how the other app settings are saved, or where—like the theme, font size, etc. for example—but I would store the setting somewhere (I know, a very lose term) around the same area. :see\_no\_evil:

Those settings are stored in data directory though. We can't store path to data directory in data directory.

There isn't a good solution. You could think of setting this e.g. in Windows registry or similar global place, but this produces complications when you want to use multiple instances, use the "portable" version and is also platform specific ...

But in the end this is also pretty corner case feature - why do you want to change the default path?

**Comment by zDEFz** [comment]
@zadam I'd also like to see such a feature. You could store it simply in a `config.ini` file or something.
Reason? Portability, easier to alter the path for backup scheduling etc.

**Comment by zadam** [comment]
config.ini is stored in the data directory so it can't contain configuration to data directory.

**Comment by zDEFz** [comment]
The idea was to have the configuration file within a subdirectory of a trilium-installation path. Having both Trilium and the data-path in one path.
Having it configurable over the config.ini, putting any path you want. Trilium reads that config.ini, then knows where the path referenced is at.

**Comment by zadam** [comment]
That's not cross platform since on some platforms (linux), installation path is usually not writable.

environment variables are platform agnostic and not difficult to use.

**Comment by Fastidious** [comment]
@zadam standardising its location could be a good start, while the hurdle of how to make it configurable gets solved. For example, on Linux it is:

`~/.local/share`

Could it be on the same location on macOS and Windows?

**Comment by zadam** [comment]
Each platform has different standard directories for user data:

*   `/home/[user]/.local/share` for Linux
*   `C:\Users\[user]\AppData\Roaming` for Windows Vista and up
*   `/Users/[user]/Library/Application Support` for Mac OS

(mentioned in https://github.com/zadam/trilium/wiki/Data-directory)

**Comment by Fastidious** [comment]
@zadam yes, I read it. Each one of those three has variables for the user’s home (where the user can write without impediments). That is, `$HOME` for Linux and macOS, and `%HOMEPATH%` for Windows.

**Comment by zadam** [comment]
Yes, but then I don't understand where is the problem? Trilium has default standardized location on each supported platform ...

**Comment by Fastidious** [comment]
@zadam they are not the same for the three platforms. If you use `$HOME`, for Linux and macOS (and any other UNIX alike platform that supports, or might support Node), and `%HOMEPATH%` for Windows, then Trilium data will always be `~/.local/share/my-trilium-data/` for each supported platform.

**Comment by zDEFz** [comment]
I support that idea especially since the default on macOS is broken and I need to manually load a `plist` file after each `logon` for trilium not falling back to the proper folder.

References https://github.com/zadam/trilium/issues/1342 and https://github.com/zadam/trilium/issues/1367 and the wiki change I did: https://github.com/zadam/trilium/wiki/Data-directory#mac-os-x

**I think, we absolutely need the path to be properly loaded, and if not found, throw an error message, instead of loading the default empty database with samples!

Where are all my notes? shouldn't be a situation.**

**Comment by zadam** [comment]
@Fastidious but there isn't any `~/.local/share` on windows (and mac AFAIK). 

Standard paths currently respect conventions of each platform separately.

**Comment by zDEFz** [comment]
@zadam on mac `~/.local/share` exists. It leads to `/Users/def/.local/share`

**Comment by Fastidious** [comment]
@zadam I did not meant it literally. What I meant was, you can set the data directory to be:

`$HOME/.local/share/my-trilium-data/` on Linux, macOS, FreeBSD, etc.

and:

`%HOMEPATH/.local/share/my-trilium-data/` on Windows.

If the `.local` directory doesn’t already exist, just create it.

**Comment by zDEFz** [comment]
Have to intervene. ```cd: no such file or directory: /Users/def/.local/share/my-trilium-data/
def@Pascals-iMac-2 ~ % cd $HOME/.local/share/my-trilium-data/```

**Comment by zDEFz** [comment]
Nevermind. You can use both `~/.local/share` or `$HOME/.local/share/`
It leads to the same directory. However, if using finder, only the first will work.

**Comment by zadam** [comment]
> `%HOMEPATH%` on Windows is the user’s home directory, similar to `$HOME` on UNIX alike operating systems.

Yes, of course. On Windows we use home directory as well (`C:\Users\[user]\AppData\Roaming`)

> If the `.local` directory doesn’t already exist, just create it.

I can create it, but it's meaningless on windows. I don't understand why do you think that it always needs to go to `.local` instead of respecting platform preferred directories for user data...

**Comment by Fastidious** [comment]
> I can create it, but it's meaningless on windows, such directory has no special significance on windows.

It will hold Trilium Notes data directory. You are giving it a significance now. I have `.ssh` on my `%HOMEPATH%`, which Putty created and uses. Other than for SSH, it has no special significance on Windows.

It doesn’t need to go to `.local`. What I am after is—_originally_, and **foremost**—to be able to set its location in an easier way. But if that is an impossibility, I am looking to standardise it to the same location, under the user’s home directory, for all platforms. Using `$HOME` for UNIX alike systems, and `%HOMEPATH%` for Windows does just that. Whether you use `.local`, or `.config`, or anything else you like is irrelevant.

**Comment by zadam** [comment]
> But if that is an impossibility, I am looking to standardise it to the same location, under the user’s home directory, for all platforms.

But why? What's the benefit compared to respecting platform conventions?

**Comment by zadam** [comment]
> But if that is an impossibility, I am looking to standardise it to the same location, under the user’s home directory, for all platforms.

But why? What's the benefit compared to respecting platform conventions?

**Comment by cebas** [comment]
@Fastidious to set an alternate data directory, you can set the environment variable TRILIUM_DATA_DIR to any dir you want before running Trilium. I tested on Linux and guess that will work on Mac too:

TRILIUM_DATA_DIR=/tmp/my-trilium-data /usr/bin/trilium

or set that variable at the OS level

**Comment by cebas** [comment]
@zadam you can use some standard config dir to save a global config file and set there the data directory.
In Linux it can be:

~/.config/trilium.conf or ~/.config/trilium/trilium.conf

with something like

```
[global]
trilium-data-dir=/my/trilium/data/dir

```

I think it's best so separate configuration from data.

I'm sure there must be a platform independent way to get the ~/config directory.

**Comment by JIeJaitt** [comment]
> > I can create it, but it's meaningless on windows, such directory has no special significance on windows.
> 
> It will hold Trilium Notes data directory. You are giving it a significance now. I have `.ssh` on my `%HOMEPATH%`, which Putty created and uses. Other than for SSH, it has no special significance on Windows.
> 
> It doesn’t need to go to `.local`. What I am after is—_originally_, and **foremost**—to be able to set its location in an easier way. But if that is an impossibility, I am looking to standardise it to the same location, under the user’s home directory, for all platforms. Using `$HOME` for UNIX alike systems, and `%HOMEPATH%` for Windows does just that. Whether you use `.local`, or `.config`, or anything else you like is irrelevant.

hi，Can Trilium be deployed on freebsd systems?
