### ISSUE TITLE
Is there any chance to support the native markdown editor?

### ISSUE THREAD

**Issue by ravenxrz** [zadam/trilium#1445]
It's an amazing application, but there is no code highlight and table of contents feature supports.
**Is there any chance to support the native markdown editor？**

**Comment by zadam** [comment]
Code highlight is available in the code notes:

![](https://user-images.githubusercontent.com/617641/99775163-1ca4d380-2b0f-11eb-8839-61e327cd6457.png)

Markdown editor is not planned.

**Comment by ravenxrz** [comment]
Thank you for your reply, but if I use code note, other editor features will be disabled.

**Comment by zadam** [comment]
yes, it's not possible to get syntax highlighting in rich text editor.

**Comment by gerroon** [comment]
There is code hilight in markdown. Not what you want?

https://i.imgur.com/SCT8isG.png

**Comment by ravenxrz** [comment]
I know that. The question is triliu doesn't support native markdown. Code note is a way to get  syntax highlighting, but other features will be disabled.
Thank you anyway.
