### ISSUE TITLE
Duplicate (not clone) notes and tokens terms (variables)

### ISSUE THREAD

**Issue by legion1978** [zadam/trilium#1446]
Hello. 
I'm trying to setup Trilium as a sort of CRM with contacts and other information.

So I find very useful the clone function the way its designed, but i was wondering if it could be possible to duplicate notes in the conventional way, in order to replace the sub-notes (contents) later. This is because many notes will have the same subtree structure, but content will be obviously different. I looked at the template feature, but it seems to be for the notes themselves and their content, not their position/naming in the tree. 

The other think i was trying to achieve was use some sort of tokens, like a note containing a few variables (?) and their values, so they can be referenced in other notes in some way.. something like {{total_sale_price}}, meaning i could just change that value and it will be updated everywhere its used. i figure its like the cloning functionality, but just for words. im not sure if theres already something like this available.

(hopefully i explain myself well enough) thank you :)

**Comment by zadam** [comment]
> So I find very useful the clone function the way its designed, but i was wondering if it could be possible to duplicate notes in the conventional way, in order to replace the sub-notes (contents) later. This is because many notes will have the same subtree structure, but content will be obviously different. I looked at the template feature, but it seems to be for the notes themselves and their content, not their position/naming in the tree.

Hi, in the context menu there's a "duplicate" command:

![](https://user-images.githubusercontent.com/617641/99783065-3861a700-2b1a-11eb-9162-b652380af4fd.png)

Currently, it works only for the individual notes, but coincidentally yesterday I extended the implementation so it duplicates the whole subtree so it's coming in the next version.

> The other think i was trying to achieve was use some sort of tokens, like a note containing a few variables (?) and their values, so they can be referenced in other notes in some way.. something like {{total\_sale\_price}}, meaning i could just change that value and it will be updated everywhere its used. i figure its like the cloning functionality, but just for words. im not sure if theres already something like this available.

I understand what you mean, but this is not supported. Could you mention some use cases for such functionality?

**Comment by zDEFz** [comment]
Hey @zadam I know a good case.

You want to have the same file twice available, but with minor changes. By default, you are not actually duplicating it, but just put a reference of a file in another tree. Upon deleting the file cause you assume you have it somewhere else, your file is magically missing in all referenced sections. This is not good, and there is no hint for the user.

May consider not call it cloning, rather call it "Copy Reference", "Paste Reference"

**Comment by legion1978** [comment]
> Currently, it works only for the individual notes, but coincidentally yesterday I extended the implementation so it duplicates the whole subtree so it's coming in the next version.

Exactly. The idea was to copy the whole subtree-- cool.
 
> I understand what you mean, but this is not supported. Could you mention some use cases for such functionality?

Yes. As i mentioned, im trying to come up with a sort of CRM, so it displays appropriate info about a project or client with ease. When setting a given price for a certain product that is common to several clients, i would have to update it in each of them if it changes, whereas a token would help speed up the process and avoid errors and dated values. 

i was even thinking about increasing one of those values automatically for renewal dates, through javascript. the idea is that if for example i have set an anual cicle for a service, it would show the correct next date once it reaches the deadline unless disabled (canceled). 

thanks

**Comment by zadam** [comment]
There is a feature in the context menu to duplicate a subtree now.
