### ISSUE TITLE
Export Html does not export with images

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1447]
Hi

It seems like exporting as html does not include the images embedded in the note. 

new rich note
add content
paste some images
export as html from the note actions dorpdown

Thanks

**Comment by zadam** [comment]
Do you export a single note, like this?

![](https://user-images.githubusercontent.com/617641/99844055-d1bca780-2b72-11eb-92fd-e77787733681.png)

If so, that's the reason - images are children notes and you need to use the "this note and all of its descendants" for the images to be included as well.
