### ISSUE TITLE
Printing adds some weird boxes before tables

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1448]
Hi

I am trying to print this rich text document and it seems to me that printing (as PDF on Linux in this case) process adds these giant boxes just before any tables presents. These boxes added above any tables and they almost cover the whole page. There is nothing in between the line above the tables and the tables themselves. I am not sure why this is inserted. See the image please

https://i.imgur.com/r6hKj7d.png

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it's now fixed. It was the table's selection handle which wasn't properly hidden for printing.
