### ISSUE TITLE
[Feature request] Key-binding for. 'Duplicate subtree(s) here'

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1451]
Scenario: 

Want to copy an item and alter it afterwards, but being existent without the original being deleted.  Don't want to use the context menu with the mouse.

Copy/Clone makes me a clone which does no longer exist if the original is deleted.

Correct me if I'm wrong.

Proposal: Also rename it to 'duplicate selected node/s'

Proposal#2 : Rename "Copy / clone" to "Create blind copy" or "Create Note shortcut"

**Comment by zadam** [comment]
> Copy/Clone makes me a clone which does no longer exist if the original is deleted.

That's wrong. Clone is completely equal to the original, actually once the clone is created it's no longer meaningful to talk about "original" and "clone".

For that reason it doesn't really make sense to call it "shortcut" or similar. Having said that I'm aware that "clone" is not a good name for this concept either, but I didn't find a better name yet.

> Proposal: Also rename it to 'duplicate selected node/s'

There isn't a concept called "node" so I assume you mean "note". But such rename would not reflect the fact that the whole note subtree is getting duplicated now.

**Comment by zDEFz** [comment]
@zadam But this doesn't seems to be the problem on my site.
Those copies or clone behave like shortcut to the original entry/node what ever you call it. They aren't unique! Only if I use the "Duplicate subtree(s) here" I have a proper copy.

Heres the video:

 https://streamable.com/fnw66l

**Comment by legion1978** [comment]
i believe thats the intended behavior for clones. maybe "instance" would be a better word... or maybe not: whereas nodes implies an origin with independent ramifications (a master note), clones are all instances between themselves. it means that no matter which one is edited, all clones are synced. so it would be something like "synced clones" or "twin instances".

**Comment by zadam** [comment]
yes, @legion1978 is right, this is intended behavior. It's perhaps better think about this as "placements" and not "clones".

The **same note** is "placed" into several positions in the note tree. Very similar to file system concept of [hard link](https://en.wikipedia.org/wiki/Hard_link).

If you want to have separate contents then you need to use "duplicate subtree", that will create completely independent note subtree.

**Comment by zDEFz** [comment]
Thanks @legion1978 and @zadam 
I think in the best case, it needs a rename. Because modal dialogs are too invasive, just to hint that. Most people going to copy and think it has the same functionality, like they know from OS Level. Be it Linux, Windows, or even MAC.

**Comment by legion1978** [comment]
Proposal 1 seems about right 

+1

**Comment by zadam** [comment]
Duplicate subtree does not behave as a clipboard and therefore is not a good candidate for `CTRL+C`

Anyway I added the keyboard shortcut for duplicate subtree so you'll be able to redefine this as you wish ...

**Comment by legion1978** [comment]
i would disagree, since the expected behavior of ctrl+C **is** the 'classic' object copy (to paste later, content independent, which is in practice what the duplication does), and not this particular cloning feature. this in fact was a thing that confused me at first, then i read the wiki :)
having said that, i would probably map it as ctrl+D or ctrl+shift+D as i have it set in other apps.

**Comment by zDEFz** [comment]
+1 Point to @legion1978 (this is totally not a Harry Potter reference)
