### ISSUE TITLE
[FR] Create new note from jump list

### ISSUE THREAD

**Issue by thehotery** [zadam/trilium#1452]
I so happy with the app and one (ok, not one, but major) thing i'm cant find is a way to quickly create note in some plase of tree.
For example, i'm currently in root/Journal and want to add a note about xcp-ng. So what to do - press CTRL + J -> "virt"  -> <arrrow down> to select "Computers/Servers/virt".
![image](https://user-images.githubusercontent.com/62539068/99933830-2f1c4880-2d6d-11eb-8012-8412682a91c3.png)

How to create new note "xcp-ng" in "Computers/Servers/Virt/"? Okay, its very possible to press <enter> -> <ctrl + p> -> type in "xcp-ng" -> <enter>,<tab> to start writing new note.
It can be very helpful to just add name of new note in the "path like "Computers/servers/Virt"  -> add "/mynewnote" -> <enter> and start writing new note.
Now jump list already allow to create new note but
![image](https://user-images.githubusercontent.com/62539068/99933852-422f1880-2d6d-11eb-838d-b76f2c2435e5.png)
it creating a new note in current location "root/Journal" with name "Computers / Servers / virt / xcp-ng" that obviously not what i'm trying to do...
![image](https://user-images.githubusercontent.com/62539068/99933877-5246f800-2d6d-11eb-8b52-50dba21f935d.png)

_p.s. Maybe someone using that behaviour so it can be nice to have some kind of checkbox options to change what <enter> in this dialog do.. or with keyboard shortcut.._

**Comment by meichthys** [comment]
The trick is to navigate to the `virt` note first and then hit `ctrl + p`.
I'm not sure how that is any harder than trying to type in the whole path of the note like `Computers /Servers /virt/ xcp-ng`
I guess it's a workflow issue, but probably the best thing to do is to learn the intended Trilium workflow. IMO, too many features can cause confusion and make Trilium loose it's elegance.
