### ISSUE TITLE
[Feature request] Ability to merge back changes on opened files (e.g. PDF comments)

### ISSUE THREAD

**Issue by MShekow** [zadam/trilium#1456]
I understand that PDF files are actually saved within the SQLite database, not as separate files. This makes it impossible to open a PDF stored in Trilium, make a few highlights, and save the document again. Opened documents are temporary files, whose changes are not detected and merged back into Trilium after closing (or saving changes to) the file from my PDF viewer.

The desktop app (tested only on Windows) does show a Pen icon (between the the + and - zoom buttons and the "Fit to page" button), which suggests such a marking functionality. But clicking it doesn't do anything, and the tool tip says "undefined".

**Comment by zadam** [comment]
Hi, I think that button is some relict from the chrome PDF viewer.

Trilium does not support editing/annotating PDFs unfortunately.

**Comment by MShekow** [comment]
In this case I think it would make sense to consider this ticket a feature request. As an implementation idea, Trilium could monitor the temporary file's last modified timestamp of the temporary file, if it changed, update the internally stored file.

**Comment by zDEFz** [comment]
But then, it doesn't reflect in the title. please rename ticket accordingly.

**Comment by MShekow** [comment]
OK, I updated the title and made it more generic, as this problem generally affects all kinds of file notes (not just PDF, also Word docs, etc.).

**Comment by zadam** [comment]
Thanks, I will think about it. It's relatively often requested and it's a valid use case ...

**Comment by zadam** [comment]
This has been implemented a while ago:

![image](https://user-images.githubusercontent.com/617641/152648001-4a0b691f-0b40-4bb1-9da1-49842f049b00.png)
