### ISSUE TITLE
[issue] high cpu hang, note detail cannot refresh issues with 0.4.5.x

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#1457]
#ENV:
win10
trilium0.4.5.5
no custom plugins
default white theme 
the nodes add many diffrent icons, like: #iconClass="bx bx-xxxx"   

# Issue:
When I click some special text node , 
the trilium will trigger 2 types issues:
a) high cpu 80% , the trilium hang , after a few mintues, the trilium will work.
b) note detail cannot  change : ( click other notes , the note title , attr will update , but the note detail still keep the special note text.)

## debug log info
1. the backend log is normal no any warning or errors;
2. the developer tool will show below error:
![image](https://user-images.githubusercontent.com/19405648/100063615-750c0600-2e6c-11eb-8224-e10b816894c3.png)

## the special note info:
title include "#" like: #today | xxxx , yyyy #tags 
attr: clipType=clipings pageUrl=some https url
text content: normal text clip, or I inputed some text.

**Comment by zadam** [comment]
Hi, would it be possible to export some of the nodes causing problems into ZIP and send them to me to zadam.apps@gmail.com for analysis?

**Comment by zDEFz** [comment]
maybe closely related. I have also had Trilium hang / be unresponsive and I couldn't do anything anymore.

What I did was, downloading https://github.com/gchq/CyberChef, import the release as zip, then creating a render note for the index.html. And voila. As long as it was in Trilium, I barely could do anything...

**Comment by leeyaunlong** [comment]
> Hi, would it be possible to export some of the notes causing problems into ZIP and send them to me to [zadam.apps@gmail.com](mailto:zadam.apps@gmail.com) for analysis?
I find the root cause, 
for some case, the saved web page  if use "autoReadOnlyDisabled=1" edit mode to view content, will trigger the trilium web view component crash. Just inthe 0.45.x version. The old 0.44.x is good.
set the readonly=1 will crash.
unset, show the orgion webpage, is good.

**Comment by zadam** [comment]
Could you export the note which causes the crash and send it to me? It's probably rendering of that note in readOnly view which will cause Trilium crash.

**Comment by leeyaunlong** [comment]
> Could you export the note which causes the crash and send it to me? It's probably rendering of that note in readOnly view which will cause Trilium crash.

I have sent you the export db to your gmail. please help me check it.
