### ISSUE TITLE
[Feature request] Support partial content for HTTP-Server #customResourceProvider

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1459]
Topic was started on #1459  and I requested to close that to focus more here.

### First
I suggest to implement partial content for the server, or whatever it is that hosts currently, so that we are allowed to use
HTML5 Media controls https://www.w3schools.com/tags/att_video_controls.asp
Otherwise, seeking won't work ever.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

I don't know how to exactly do it, but here are the resources again.

https://stackoverflow.com/questions/10583931/cant-seek-html5-video-or-audio-in-chrome

[snip]

As it turns out, looping (or any sort of seeking, for that matter) in <video> elements on Chrome only works if the video file was served up by a server that understands partial content requests. i.e. the server needs to honor requests that contain a "Range" header with a 206 "Partial Content" response. This is even the case if the video is small enough to be fully buffered by chrome, and no more server-round trips are made: if your server didn't honor chrome's Range request the first time, the video will not be loopable or seekable.

[/snip]

**Comment by zadam** [comment]
To be frank, I consider this to be a rather low priority so it's not likely I will work on this soon. Best option to advance this is to submit a PR.

There are 2 parts to this: 

*   handling HTTP headers in the router
*   implement custom range on the database level. I'm not sure if the `substr` function is applicable on the binary data.

**Comment by zadam** [comment]
IIRC there has been a support for this for a while.
