### ISSUE TITLE
Many images in the Link Map

### ISSUE THREAD

**Issue by lpd743663** [zadam/trilium#1461]
I clipped a web page that has lots of images

and Link Map looks like this

![image](https://user-images.githubusercontent.com/4426804/100102502-a7365b80-2e9e-11eb-9956-b967ba79c19d.png)

I think it may not be necessary to display the images in the notes (the attached images do)

Or put all the images together on one side

![image](https://user-images.githubusercontent.com/4426804/100104301-f8474f00-2ea0-11eb-8842-ad33b57cf753.png)

**Comment by zadam** [comment]
Hi, yes, in this case images are cluttering the view.

In the note tree widget there was a similar problem and it was mitigated by hiding (by default) images which are included in the parent note.

I now used the same approach here - so if the text note includes images which are its own children (which is the case for clipped pages), then link map won't show them. If you include an image from somewhere else in the tree this link will still show up.
