### ISSUE TITLE
[Bug report/api request] note.getLabelValue only return first value when I want to get all the multi-number label values

### ISSUE THREAD

**Issue by buglong** [zadam/trilium#1463]
Hello,
I had added a multi number label like this: "#something=15.5 #something=29 #something=6", and I want to get all the numbers using backend API. 

Code like below only returns the first number three times.

const notes = api.getNotesWithLabel('something');
for (const note of notes) {
    const weight = parseFloat(note.getLabelValue('something'));
}

Is this a bug or there is other api that I can use to get all the number values with the same label name?

Thanks!

**Comment by zadam** [comment]
Yes, you can use `note.getLabels('something')` which will return array of label objects, each of which has value property.

See API docs: https://zadam.github.io/trilium/backend_api/Note.html

**Comment by buglong** [comment]
Thank you!

**Comment by zDEFz** [comment]
> Yes, you can use `note.getLabels('something')` which will return array of label objects, each of which has value property.
> 
> See API docs: https://zadam.github.io/trilium/backend_api/Note.html

Hey zadam.

I've read the API thing but I couldn't figure how to get the current title of the current note. Can you help out?

Thanks.

**Comment by zadam** [comment]
```
api.getActiveTabNote().title
```

**Comment by zDEFz** [comment]
> ```
> api.getActiveTabNote().title
> ```

This works in pure JS, but I am doing something wrong, trying to use it on HTML type of node.

I'm sorry if you feel that I waste your time. I wish I would understand more.
Hopefully it's an easy fix. Maybe I just need to call it a different way?

```
<!DOCTYPE html>
<html>
<body>

<h1>The script type attribute</h1>

<p id="demo"></p>

<script type="application/javascript">
var answer = api.getActiveTabNote().title;

var temp = window.confirm(answer);

</script>

</body>
</html>

```

**Comment by zadam** [comment]
Yes, API object is not available in the HTML note (since it's not a global object). You need to use JS note.

**Comment by zDEFz** [comment]
Good day @zadam 

Any way to grab the value from HTML? Can I not somehow get access to the value? Or is this simply not implemented?

Can I not somehow get access to the JS value? I would think of running the JS standalone, but somehow accessing the variable from another HTML node. 

Or is it really that I won't able to parse that?
Really, what I want is that the HTML always takes the title of the node as heading level 1 page title.

**Comment by zadam** [comment]
Standard way to do this is to have this structure:

*   HTML note
    *   JS note

JS note is automatically included into the HTML, can manipulate it's DOM by CSS classes etc. and has access to the `api` object. Demo document has scripts which use this pattern.

**Comment by zDEFz** [comment]
@zadam Thanks for your response.

I've dug an hour into it now with no success. I've looked at the demos and the API again.

https://zadam.github.io/trilium/backend_api/Branch.html

Since the JS is now the child, I'd need to get the instead the parents note title.

I've tried, but it didn't work.

```
var attrCounts = await api.runOnBackend(() => {
return api.getParentNote().title
});
```

or
`
document.write(api.getParentNote().title);`

**Comment by zDEFz** [comment]
Hey @zadam , not that it makes too much sense to use the page title on HTML on the parent node, but is there any easy way todo this in the forementioned structure?

->HTML
-->JS

Thanks

**Comment by zadam** [comment]
```
var attrCounts = await api.runOnBackend(() => {
return api.getParentNote().title
});
```

There's no `.getParentNote()` directly on the api object. You probably want to use `api.currentNote.getParentNote()`

See https://zadam.github.io/trilium/backend_api/BackendScriptApi.html

**Comment by zDEFz** [comment]
Hey @zadam , you said priorly the JS is available in the HTML if it's a child of the node.

But it isn't working for me https://streamable.com/kk803n
