### ISSUE TITLE
[issue][template Inherited attributes in v0.45.x]

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#1464]
Issue: 
# 1. the subnote of day note with inherited day template define in 0.45.x
In 0.44.x , just the daliy note will inherited the template define.
sample:
template define "autoReadOnlyDisabled" and set inherite, 
trilium will copy the "autoReadOnlyDisabled" to the today note without inherite.
but I created subnote of today's note will inherite the autoReadOnlyDisabled attr. 

## template
![image](https://user-images.githubusercontent.com/19405648/100406710-8ee25e80-30a1-11eb-9ed9-57a7612afbe3.png)

### today
![image](https://user-images.githubusercontent.com/19405648/100406636-4d51b380-30a1-11eb-9cc1-fbd4263f8b3e.png)

#### subnote
![image](https://user-images.githubusercontent.com/19405648/100406827-da950800-30a1-11eb-92f3-d7bd502ff2dd.png)

# 2. for above case, the subnote cannot remove the inherited the attr (from template ) , is different with 0.44

**Comment by zadam** [comment]
Removing inherited attributes was never possible, there's no difference in comparison to 0.44.

I'm not sure what you end goal is, but often you don't want attributes defined on a template be inheritable - that way only day note will get the attribute and children not.
