### ISSUE TITLE
copy image and pastet into the web frontend

### ISSUE THREAD

**Issue by lpd743663** [zadam/trilium#1470]
trilium-windows-x64

[trilium-2020-12-02-from-server.log](https://github.com/zadam/trilium/files/5627079/trilium-2020-12-02.log)

Hi

Is there a way to copy an image without having to double-click on it?

and

when pasting images from elsewhere into the web frontend, after a while, the image is brokend

As shown below

![image](https://user-images.githubusercontent.com/4426804/100830792-6e4e4600-349f-11eb-8065-1ee9daabe408.png)

**Comment by zDEFz** [comment]
Hey. 

I believe this is because currently, copy/paste is only done on 'symlink / alias' basis.
I had similar situations, where the file wasn't kept as a single image, and if the original was gone, so was the image within the note.

So if you have an image pasted that is shown within a note, the action isn't immediately reflected and theres no warning whatsoever if deleting that will remove it also from a note.

I also have this on a regular basis, that notes are vanishing... I think thats the reason for it.

**Comment by zadam** [comment]
I believe that the problem with broken images stems from this:

> 04:21:52.511 ERROR: Download of file:///D:/Downloads/Trilium%20%E4%BD%BF%E7%94%A8%E8%AE%B0%E5%BD%95/Trilium%20%E4%BD%BF%E7%94%A8%E8%AE%B0%E5%BD%95/Trilium%20%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE/Docker/2\_image.png for note fjonlVHJm3QD failed with error: Unrecognized protocol "file:" Error: Unrecognized protocol "file:"
> 
>    at getClient (/usr/src/app/src/services/request.js:168:19)
> 
>    at Object.getImage (/usr/src/app/src/services/request.js:94:20)
> 
>    at downloadImage (/usr/src/app/src/services/notes.js:262:43)
> 
>    at downloadImages (/usr/src/app/src/services/notes.js:341:42)
> 
>    at saveLinks (/usr/src/app/src/services/notes.js:397:19)
> 
>    at Object.updateNote (/usr/src/app/src/services/notes.js:494:31)
> 
>    at updateNote (/usr/src/app/src/routes/api/notes.js:54:24)
> 
>    at Function.cb (/usr/src/app/src/routes/routes.js:94:34)
> 
>    at Function.sqliteTransaction (/usr/src/app/node\_modules/better-sqlite3/lib/transaction.js:58:24)
> 
>    at Object.transactional (/usr/src/app/src/services/sql.js:230:48)

I assume you had opened locally saved web page and copy pasted from that to Trilium - but clipboard contains only the image link and not the image itself. Then the original file on the disk was moved/deleted and the link was broken. I don't think this is solveable when the originating application puts only an image link into the clipboard ...

**Comment by zDEFz** [comment]
since file links aren't working anyways, won't the correct behavior be to parse it as a file to circumvent such problems?

**Comment by lpd743663** [comment]
> I believe that the problem with broken images stems from this:
> 
> > 04:21:52.511 ERROR: Download of file:///D:/Downloads/Trilium%20%E4%BD%BF%E7%94%A8%E8%AE%B0%E5%BD%95/Trilium%20%E4%BD%BF%E7%94%A8%E8%AE%B0%E5%BD%95/Trilium%20%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE/Docker/2_image.png for note fjonlVHJm3QD failed with error: Unrecognized protocol "file:" Error: Unrecognized protocol "file:"
> >    at getClient (/usr/src/app/src/services/request.js:168:19)
> >    at Object.getImage (/usr/src/app/src/services/request.js:94:20)
> >    at downloadImage (/usr/src/app/src/services/notes.js:262:43)
> >    at downloadImages (/usr/src/app/src/services/notes.js:341:42)
> >    at saveLinks (/usr/src/app/src/services/notes.js:397:19)
> >    at Object.updateNote (/usr/src/app/src/services/notes.js:494:31)
> >    at updateNote (/usr/src/app/src/routes/api/notes.js:54:24)
> >    at Function.cb (/usr/src/app/src/routes/routes.js:94:34)
> >    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
> >    at Object.transactional (/usr/src/app/src/services/sql.js:230:48)
> 
> I assume you had opened locally saved web page and copy pasted from that to Trilium - but clipboard contains only the image link and not the image itself. Then the original file on the disk was moved/deleted and the link was broken. I don't think this is solveable when the originating application puts only an image link into the clipboard ...

Thank you for your quick response :) 

I have 2 database files, one backed up on November 30 （document-2020-11-30.db）, and one that is up-to-date（document-latest.db）.


document-latest.db  previously gave me an error when importing a large file. After that, the sync to the server has some problems.

document-2020-11-30.db  syncs to the server with no problem.

I have reset the server several times to test the sync data and the results are always the same.

I think there is a similarity in this issue.

Server sync failure log：

[trilium-2020-12-02-from-server.log](https://github.com/zadam/trilium/files/5633004/trilium-2020-12-02.log)
[trilium-2020-12-03-from-server.log](https://github.com/zadam/trilium/files/5633005/trilium-2020-12-03.log)

**Comment by lpd743663** [comment]
> I believe that the problem with broken images stems from this:
> 
> > 04:21:52.511 ERROR: Download of file:///D:/Downloads/Trilium%20%E4%BD%BF%E7%94%A8%E8%AE%B0%E5%BD%95/Trilium%20%E4%BD%BF%E7%94%A8%E8%AE%B0%E5%BD%95/Trilium%20%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE/Docker/2_image.png for note fjonlVHJm3QD failed with error: Unrecognized protocol "file:" Error: Unrecognized protocol "file:"
> >    at getClient (/usr/src/app/src/services/request.js:168:19)
> >    at Object.getImage (/usr/src/app/src/services/request.js:94:20)
> >    at downloadImage (/usr/src/app/src/services/notes.js:262:43)
> >    at downloadImages (/usr/src/app/src/services/notes.js:341:42)
> >    at saveLinks (/usr/src/app/src/services/notes.js:397:19)
> >    at Object.updateNote (/usr/src/app/src/services/notes.js:494:31)
> >    at updateNote (/usr/src/app/src/routes/api/notes.js:54:24)
> >    at Function.cb (/usr/src/app/src/routes/routes.js:94:34)
> >    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
> >    at Object.transactional (/usr/src/app/src/services/sql.js:230:48)
> 
> I assume you had opened locally saved web page and copy pasted from that to Trilium - but clipboard contains only the image link and not the image itself. Then the original file on the disk was moved/deleted and the link was broken. I don't think this is solveable when the originating application puts only an image link into the clipboard ...

![pasteimage](https://user-images.githubusercontent.com/4426804/101119399-358ca900-3626-11eb-9a78-3ca7d1326585.gif)

**Comment by zDEFz** [comment]
Something tells me this is because of the lack of support of special characters. I've decoded your image string.

It says: 'file:///D:/Downloads/Trilium 使用记录/Trilium 使用记录/Trilium 服务器配置/Docker/2_image.png ' 

Note the special characters in the path..
I say this because I have the issue that trilium is renaming files that contain unsupported letters.

**Comment by lpd743663** [comment]
> Something tells me this is because of the lack of support of special characters. I've decoded your image string.
> 
> It says: 'file:///D:/Downloads/Trilium 使用记录 / Trilium 使用记录 / Trilium 服务器配置 / Docker/2_image.png '
> 
> Note the special characters in the path..
> I say this because I have the issue that trilium is renaming files that contain unsupported letters.


Thank you.

Um, are  you referring to the[ image broken problem](https://github.com/zadam/trilium/issues/1470#issue-754944953) or the [server synchronization problem](https://github.com/zadam/trilium/issues/1470#issuecomment-737592859)?

For the first question, I've uploaded a new image to illustrate the following

The image in the demo was placed under the root directory and had the same problem.

![pasteimage](https://user-images.githubusercontent.com/4426804/101119399-358ca900-3626-11eb-9a78-3ca7d1326585.gif)

**Comment by zDEFz** [comment]
@lpd743663 Yea, referring to this problem. 
So, your file isn't anymore containing any special characters, right?

**Comment by lpd743663** [comment]
> @lpd743663 Yea, referring to this problem.
> So, your file isn't anymore containing any special characters, right?

I am pasting the image from the clipboard into Trilium-windows-x64-0.45.5 . In Trilium-windows-x64-0.45.5the image is fine.

I just ran a new test, and this time Trilium-windows-x64-0.45.5 was able to synchronize with the server.

The images were fine at first, but when I refreshed the page, the images were corrupted, and after the database was synchronized, the images were fine again.

**Comment by zadam** [comment]
Thanks for providing the screencast - I was able to reproduce this.

The issue is again with the clipboard - when you click on "Copy to clipboard", Trilium copies a link to the image and not the image itself. This is fine and desirable when you intend to copy it to another note in Trilium (for this it was designed), but doesn't work when you copy it to another application (or another instance of Trilium as shown here). For copying it outside Trilium the image would have to be copied into the clipboard, but there isn't a programmatic way to do this in javascript, although it should be possible to do this using electron APIs.

As a workaround, if you want to copy an image outside of Trilium, you should use "download" button.
