### ISSUE TITLE
Some images are not hidden

### ISSUE THREAD

**Issue by koutto** [zadam/trilium#1472]
Hello,
Even when "Hide images included in note" is ticked, some images (not all) are still displayed as child. As shown in the screenshot:
![bug-trilium](https://user-images.githubusercontent.com/26327909/101174821-a93dae80-3644-11eb-8d55-6b0e01a0a9f0.png)

**Comment by zadam** [comment]
The images are hidden only if they are linked (displayed) in the parent. Are they displayed in the parent note?
