### ISSUE TITLE
Sync fails

### ISSUE THREAD

**Issue by lpd743663** [zadam/trilium#1474]
Hi,

Syncing with my server fails.

> trilium-windows-x64-0.45.6

> CentOS 7.6 64bit
> docker pull zadam/trilium:0.45.6

I have 2 database files, one backed up on November 30 （document-2020-11-30.db）, and one that is up-to-date（document-latest.db）.

document-latest.db previously gave me an error when importing a large file. After that, the sync to the server has some problems. Refer to [https://github.com/zadam/trilium/issues/732#issuecomment-559945708](https://github.com/zadam/trilium/issues/732#issuecomment-559945708) I think there may be a problem with the database file.

document-2020-11-30.db syncs to the server with no problem.

I have reset the server several times to test the sync data and the results are always the same.

Log：

From console：
> Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.

[trilium-2020-12-06-server.log](https://github.com/zadam/trilium/files/5648373/trilium-2020-12-06-swever.log)
[trilium-2020-12-06-windows-64.log](https://github.com/zadam/trilium/files/5648374/trilium-2020-12-06-windows-64.log)

**Anonymized database**：[document-clean.zip](https://github.com/zadam/trilium/files/5648378/document-clean.zip)

**Comment by zadam** [comment]
Hi, thanks for the log.

This from the log seems to be causing the problems:

> BadRequestError: request aborted

The request is getting rejected because it's malformed or does not conform to limits (e.g. size). You mention that problems started to occur after import of a big file and this seems to be consistent with the request size limit.

How large was the file? Trilium has its own limit for sync requests of 500 MB, but your reverse proxy (or some other network component) may have its own (lower) limit and e.g. truncate the request which would then also lead to this error.

**Comment by lpd743663** [comment]
> Hi, thanks for the log.
> 
> This from the log seems to be causing the problems:
> 
> > BadRequestError: request aborted
> 
> The request is getting rejected because it's malformed or does not conform to limits (e.g. size). You mention that problems started to occur after import of a big file and this seems to be consistent with the request size limit.
> 
> How large was the file? Trilium has its own limit for sync requests of 500 MB, but your reverse proxy (or some other network component) may have its own (lower) limit and e.g. truncate the request which would then also lead to this error.


Thanks.

document.db    661 MB

Largest attachment is around  40 MB

The previous 172MB  file that caused the error was not imported into the database.

On the server side, docker and trilium are currently installed, but everything else is default.

Now I transfer the database files directly to the server via Xftp, for now, it works  :)

**Comment by zadam** [comment]
> The previous 172MB file that caused the error was not imported into the database.

Are you sure it's not imported? When I test the import crash with big files, Trilium crashes, but the file is actually imported.

> Largest attachment is around 40 MB

If that's the case, there must be some other problem since 40MB should work fine based on my testing ...

> On the server side, docker and trilium are currently installed, but everything else is default.

What is "default"? Is there some reverse proxy set up?

**Comment by lpd743663** [comment]
> > The previous 172MB file that caused the error was not imported into the database.
> 
> Are you sure it's not imported? When I test the import crash with big files, Trilium crashes, but the file is actually imported.
> 
> > Largest attachment is around 40 MB
> 
> If that's the case, there must be some other problem since 40MB should work fine based on my testing ...
> 
> > On the server side, docker and trilium are currently installed, but everything else is default.
> 
> What is "default"? Is there some reverse proxy set up?

**This is the result**
![image](https://user-images.githubusercontent.com/4426804/101300937-37e34300-3872-11eb-9a93-d22eccdb7b1a.png)

---

The following is about the **server**, and since I'm not a programmer, I don't know exactly what the setup looks like.

I'm using Tencent Cloud (similar to Amazon EC2). And I didn't use a domain name, I accessed the IP directly.

---
I did the following and nothing else.

> sudo yum install -y yum-utils \
                      device-mapper-persistent-data \
                      lvm2

> sudo yum-config-manager \
   --add-repo \
   https://download.doc

> sudo sed -i 's+download.docker.com+mirrors.tuna.tsinghua.edu.cn/docker-ce+' \
   /etc/yum.repos.d/docker-ce.repo

> sudo yum makecache fast 

> sudo yum install docker-ce docker-ce-cli containerd.io

> sudo systemctl start docker

> sudo docker run hello-world

> docker pull zadam/trilium:0.45.6

> sudo docker run -itd -p 0.0.0.0:8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:0.45.6

**Comment by zadam** [comment]
Thanks for the detailed info. If the largest note is 40 MB, then I think the problem must lie in some network limits between you and your server instance. Personally I've tested notes up to 100 MB and they've worked fine with sync.

If you have time, you could also try to set up the server version locally (e.g. in local docker environment) to confirm/disprove this hypothesis. If the sync would work locally then the problem must lie somewhere in the network.

**Comment by lpd743663** [comment]
@zadam 

Thanks, I'll try it out.

**Comment by lpd743663** [comment]
Hi @zadam ，
The local server works fine. :)

While testing the local server, I encountered a strange thing：

I backed up the database files to another folder.

Then I restarted to sync the data to the server and had problems when the sync was almost finished 
(since the database file size on Windows 10 is 667 MB and the file size on the server is 668 MB, the two files are about the same size, so I think the sync is almost done)

At this point, I close Trilium, replace the database I just used with the one I backed up ( the database changes as soon as I open Trilium ), and run Trilium again, Trilium prompts  this

![image](https://user-images.githubusercontent.com/4426804/101358235-8544cc00-38d5-11eb-802b-36c69a093cf8.png)

which was not shown before.

After a while, the sync is successful.

This is a really strange thing.

**Comment by zadam** [comment]
> (since the database file size on Windows 10 is 667 MB and the file size on the server is 668 MB, the two files are about the same size, so I think the sync is almost done)

This is not a good heuristic. Due to how SQLite (de)allocates space, even "equal" databases can differ in size significantly.

> This is a really strange thing.

Why do you think it's strange?

If I understand this correctly, you take a DB file from client and put it on a server. Server opens it, it sees configured sync server (DB including this config originally comes from the client) and starts the sync - it will detect that the sync server is pointing to itself and end.

**Comment by lpd743663** [comment]
> > (since the database file size on Windows 10 is 667 MB and the file size on the server is 668 MB, the two files are about the same size, so I think the sync is almost done)
> 
> This is not a good heuristic. Due to how SQLite (de)allocates space, even "equal" databases can differ in size significantly.
> 
> > This is a really strange thing.
> 
> Why do you think it's strange?
> 
> If I understand this correctly, you take a DB file from client and put it on a server. Server opens it, it sees configured sync server (DB including this config originally comes from the client) and starts the sync - it will detect that the sync server is pointing to itself and end.

What actually happens is this.
1. there are two database files on the client : db1, db2,   and db2 is a backup of db1. 
2. db1 is in the trilium-data folder.
2. on the client,  run Trilium to synchronize db1 to the server (it took about 30 minutes, but the sync failed).
3. on the client,  close Trilium and replace db1 with db2.
4. on the client,  run Trilium again for synchronization. 
5. after 3-4 minutes, the sync is successful

There are no other actions.
