### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1480]
Running Trilium 0.45.6.

I recently imported a large batch of HTML notes (from my previous note-taking app, WikidPad). This comes down to some 7000-8000 notes that currently reside directly under a top-level note "wikidpad-export".

Since then, I notice that startup (and Trilium refresh) has gotten very slow. It takes 10s of seconds for the interface to show up.

Front-end dev console does show me that's it's waiting a long time to get a response via the websocket:

    16:24:42 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.

This seems to be confirmed by the network requests:
![image](https://user-images.githubusercontent.com/39531/101503813-cccd6580-3972-11eb-80e3-73ffd427fdce.png)

Backend log shows me the following sequence
```
16:28:28.916 Generated CSRF token 64GhVLs8-XEIoWtVPgXsVElcYSbr4p0_BPgE with secret undefined
16:28:28.930 Slow GET / took 14ms
16:28:31.980 Slow recursive query took 2409ms.
16:28:32.375 Slow GET /api/tree took 2805ms
16:28:32.379 GET /api/options took 1ms
16:28:32.381 Keyboard action showAttributes found in database, but not in action definition.
16:28:32.381 GET /api/keyboard-actions took 2ms
16:28:32.382 GET /api/keyboard-shortcuts-for-notes took 0ms
16:28:32.383 GET /api/script/widgets took 1ms
16:28:32.386 GET /api/notes/download/7Ik51id1pCLu took 1ms
16:28:32.398 GET /api/notes/download/sHyxaCyfuRjw took 1ms
16:28:32.728 Slow POST /api/tree/load took 42ms
16:28:32.785 POST /api/tree/load took 3ms
16:28:32.811 POST /api/tree/load took 4ms
16:29:03.440 GET /api/attributes/values/project took 1ms
16:29:03.444 GET /api/notes/qVkUzUtehb23 took 0ms
16:29:04.483 Slow GET /api/similar-notes/qVkUzUtehb23 took 35ms
16:29:04.490 GET /api/notes/qVkUzUtehb23/revisions took 1ms
16:29:04.696 GET /api/script/startup took 2ms
16:29:04.704 POST /api/tree/load took 1ms
16:29:04.711 POST /api/tree/load took 1ms
16:29:08.393 POST /api/recent-notes took 0ms
```
The large 30-second gap in the middle seems suspicious, but I'm not sure what heavy operation is keeping things busy there...

Any thoughts?

**Comment by zadam** [comment]
Hi,

```
16:28:31.980 Slow recursive query took 2409ms.
16:28:32.375 Slow GET /api/tree took 2805ms
```

This is very slow and hints at some bottleneck in the note tree structure.

To have some context, what is the hardware (SSD or not, CPU...)?

Would it be possible to send me an anonymized database on zadam.apps@gmail.com for analysis? If the problem is in the tree structure then this should help ...

![](https://user-images.githubusercontent.com/617641/101542686-6c0a5100-39a3-11eb-9f9f-9c772c8434c6.png)

Also, do you have many (thousands) of notes displayed / expanded in the note tree?

**Comment by wwwald** [comment]
Hardware shouldn't be the problem - Trilium DB is on a regular 7200rpm hard drive (no SSD), CPU is 6-core Intel Core i7 with 32G of RAM.

At startup, there's not a lot of notes actually showing - about 10-20 top-level collapsed notes usually. The "wikidpad-export" with 7000+ children does take a while when I expand it, but it's not open at startup.

I've sent an anonymized DB via email. Thanks a lot for looking into it!

**Comment by zadam** [comment]
Hi, thank you for the anonymized DB!

The good news is that I can reproduce the issue now. Initial analysis suggests that Trilium (frontend) does not scale well to such large number of children of a particular note, but it should be fixable. I will look into this deeper ...

**Comment by wwwald** [comment]
In any case - I'm planning to bring some hierarchy to that note, probably the year-month-day structure just like the Trilium journal. Seems to be pretty straightforward with some regex and SQL queries, so that will probably solve things in my case.

In any case - improving performance would of course be the more structural approach 👍

**Comment by zadam** [comment]
Fixed on the stable branch.
