### ISSUE TITLE
Hiring Support for Server Setup

### ISSUE THREAD

**Issue by 2pascal** [zadam/trilium#1481]
Hobbyist/student seeking to hire help for server setup. I attempted to configure the server on a local Linux VM and then on a Linux 18.04 server I purchased online. Was having an issue setting up certificates with nginx/SSL and the following steps. My experience is limited, enough to get me this far, but not enough to complete the server setup. Please let me knows if anyone would be interested in being hired to finish the configuration, as it would take me eons. Thank you.

**Comment by lflare** [comment]
I'm not sure if it's socially acceptable to accept hires like these, but have you tried following https://github.com/zadam/trilium/wiki/Server-installation ?

**Comment by 2pascal** [comment]
Hi Lflare,
I did try this guide but got stuck due to a lack of experience. Any idea of a website or person who would be able to help me? Either looking for guidance through the process or a full setup. After a day of work, I realized my time was better spent on other projects, and that I should find someone already familiar with this work to help me get it set up.

**Comment by ehamminga** [comment]
I've tried some of the guides in the wiki and [this](https://community.hetzner.com/tutorials/install-trilium-notes-using-docker) guide but never got SSL to work using either nginx or traefik. Hopefully with the steps below you can get it to work.

I started off with a with a online server running Ubuntu 20.04, so my steps should be similar to yours. Follow step 1-3 of [this](https://community.hetzner.com/tutorials/debian-base-configuration-docker) quide on the Hetzer Community for a Docker base config.

I've used the [Apache guide](https://github.com/zadam/trilium/wiki/Apache-proxy-setup) on the Trilium wiki that basically explains all the steps to get Trilium fully working on Docker with SSL. It's little bit tucked away in the wiki and I did not expect a full guide, so I ignored it at first. Hopefully, together with the notes mentioned in [my issue](https://github.com/zadam/trilium/issues/1479) you can get it up and running

**Comment by Engr-AllanG** [comment]
@2pascal do you still need help? I can explain my setup and share my nginx configuration if it would help you. I am running a proxmox server, so my nginx reverse proxy is in one container using letsencrypt, and Trilium is in another Ubuntu 16.04 container.

**Comment by 2pascal** [comment]
@Engr-AllanG I'd greatly appreciate any configuration help you can share. I can't get it setup on my Linux Server VM or on a hosted server.

**Comment by zDEFz** [comment]
Hello, is this still relevant? Have gotten mine to work, including HTTPS with Nginx.

**Comment by Engr-AllanG** [comment]
Shoot I forgot I offered to supply my configuration. I'll try and throw
mine into a Gist or something and it could be linked to from the Trilium
Wiki
-Allan
