### ISSUE TITLE
Failed to protect note tree

### ISSUE THREAD

**Issue by lpd743663** [zadam/trilium#1483]
> trilium-windows-x64-0.45.6

![image](https://user-images.githubusercontent.com/4426804/101592166-be418580-3a28-11eb-8217-e0ff8ff32e63.png)

As shown in the figure: the progress is always 0, and after a while, the prompt is gone.

However, I can protect any of the notes. :)

I tried to protect the note tree in the demo：

When I exported my notes and imported them into the demo, I can protect the note tree, it worked, the progress changed, and I was prompted that the protection was successful. 

But I had another problem: some notes could not be displayed:
![display](https://user-images.githubusercontent.com/4426804/101595141-e1baff00-3a2d-11eb-8deb-795bbb18f7cd.gif)

Log:

> 14:25:51.935 Sending message to all clients: {"type":"task-progress-count","taskId":"YzP0myc6xS","taskType":"protect-notes","data":{"protect":true},"progressCount":0}
14:25:52.064 ERROR: put /api/notes/:noteId/protect/:isProtected threw exception: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
>    at Function.from (buffer.js:305:9)
>    at Object.encrypt (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\services\data_encryption.js:38:36)
>    at Object.encrypt (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\services\protected_session.js:46:34)
>    at NoteRevision.updatePojo (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\entities\note_revision.js:139:54)
>    at Object.updateEntity (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\services\repository.js:101:16)
>    at NoteRevision.save (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\entities\entity.js:57:25)
>    at Object.protectNoteRevisions (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\services\note_revisions.js:19:22)
>    at protectNote (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\services\notes.js:199:25)
>    at protectNoteRecursively (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\services\notes.js:176:5)
>    at protectNoteRecursively (C:\Program Files\Trilium-windows-x64\resources\app.asar\src\services\notes.js:182:13)
> 14:25:52.064 Slow PUT /api/notes/2MEdzZVfvUUi/protect/1?subtree=1 took 130ms
> 14:25:52.802 Slow POST /api/notes/2MEdzZVfvUUi/link-map took 13ms

[trilium-2020-12-09.log](https://github.com/zadam/trilium/files/5663991/trilium-2020-12-09.log)

---
2020-12-12

2 new cases

1. The journal is already protected：created new journal  by CALENDAR and the new journal is not protected. (If you use `CTRL-P` to create a new sub-note, the new sub-note is protected)

2. The search results for a protected note（after unprotecting it）, look like this

![image](https://user-images.githubusercontent.com/4426804/101979060-a837fd00-3c94-11eb-8d46-0be5fbc4f71f.png)

---
2020-12-14
For which protected up notes

`Ctrl-L`

![image](https://user-images.githubusercontent.com/4426804/102032289-51950500-3df3-11eb-81cd-c948815c022f.png)

**After unprotecting all notes, everything works fine**

**Comment by zadam** [comment]
Hi, thanks for reporting these issues:

1.  issue with protecting subtree of notes - fixed in 0.45 branch
2.  "But I had another problem: some notes could not be displayed:" - unfortunately this is a problem with the CKEditor that it sometimes crashes like that. Currently can't do anything about it, hopefully future update will fix it.
3.  "created new journal by CALENDAR and the new journal is not protected." - fixed in 0.46 branch
4.  "The search results for a protected note（after unprotecting it）, look like this" - unfortunately can't reproduce this at the moment

**Comment by lpd743663** [comment]
> Hi, thanks for reporting these issues:
> 
> 1. issue with protecting subtree of notes - fixed in 0.45 branch
> 2. "But I had another problem: some notes could not be displayed:" - unfortunately this is a problem with the CKEditor that it sometimes crashes like that. Currently can't do anything about it, hopefully future update will fix it.
> 3. "created new journal by CALENDAR and the new journal is not protected." - fixed in 0.46 branch
> 4. "The search results for a protected note（after unprotecting it）, look like this" - unfortunately can't reproduce this at the moment


![esnie-o7eg0](https://user-images.githubusercontent.com/4426804/102846485-0f02a680-444b-11eb-8d4f-1cc4e7d51b87.gif)

This is the database for testing
> Account and password are: 123456


[document.db.zip](https://github.com/zadam/trilium/files/5727614/document.db.zip)

**Comment by zadam** [comment]
Hi, thanks for GIF. I was not able to reproduce it on stable branch, but when I checked out 0.45.6 tag I had the same behavior.

So it turns out this was already fixed in stable branch, but not released yet. I will make a release soon.

**Comment by lpd743663** [comment]
> Hi, thanks for GIF. I was not able to reproduce it on stable branch, but when I checked out 0.45.6 tag I had the same behavior.
> 
> So it turns out this was already fixed in stable branch, but not released yet. I will make a release soon.

thanks
