### ISSUE TITLE
Inserting math expression after link causes wierd behaviour

### ISSUE THREAD

**Issue by funnisquares** [zadam/trilium#1486]
As the title says, inserting a math expression right after a link will cause the editor to stop working.
![ezgif-1-25502bbc9e61](https://user-images.githubusercontent.com/43013384/97752029-0dafa000-1ad2-11eb-9a9e-459684a564b9.gif)

**Comment by funnisquares** [comment]
[logs.log](https://github.com/zadam/trilium/files/5683577/logs.log)
These are the logs when reproducing this issue.

**Comment by zDEFz** [comment]
I think this is a CKEditor5 Bug, not a Trilium-Notes Bug. 
@zadam what do you think?

**Comment by wwwald** [comment]
I recently filed a bug about editor behavior after inserting a link - see #1427. 

Could this be related? Do you only get these errors _after_ a link has been inserted?

**Comment by zadam** [comment]
Yes, looks like a CKEditor bug. Potentially ckeditor5-math bug.

Frankly my strategy for these minor bugs in CKEditor is to just wait it out, usually they get fixed sooner or later.
