### ISSUE TITLE
I can not input when use bulleted list sometimes

### ISSUE THREAD

**Issue by fbout** [zadam/trilium#1490]
I can not input anything when i use bulleted list sometimes

The log shows someting error
![20201217142441](https://user-images.githubusercontent.com/4409602/102451550-a8107680-4073-11eb-8728-f196f57476bf.png)

[127.0.0.1-1608185907847.log](https://github.com/zadam/trilium/files/5707353/127.0.0.1-1608185907847.log)

Trilium 0.45.6
[trilium-2020-12-17.log](https://github.com/zadam/trilium/files/5707321/trilium-2020-12-17.log)

**Comment by wwwald** [comment]
Same error messages as #1427 - seems to be linked to a bug in Ckeditor, the editing component in Trilium: ckeditor/ckeditor5#4959.

I'm a bit afraid that this will take a while to get fixed there - it's been open and silent since 2017.

**Comment by zadam** [comment]
I'm not sure if [ckeditor/ckeditor5#4959](https://github.com/ckeditor/ckeditor5/issues/4959) is really the root cause of the error. My guess is that the actual error is the "getStyle", CKEditor error handling is trying to gather more info (using JSON.stringify()) which triggers this secondary error ...

**Comment by wwwald** [comment]
OK. I'm actually a bit triggered to dive into this and see where things could go wrong.

But: my JS game is not very strong. Are there instructions somewhere on how to run Trilium from source? Or a generic tutorial somewhere?

**Comment by zadam** [comment]
```
npm install
npm run start-electron
```

should do the trick for the most part.

But debugging CKEditor is more difficult - it lives in a separate repo and then is built with webpack. Debugging that might be challenging ...

**Comment by lpd743663** [comment]
I may have encountered the same problem

 When using ordered lists,  entering Chinese characters: Type the letters, press esc to cancel, and encounter problems

![chinese](https://user-images.githubusercontent.com/4426804/102495905-ac5b8480-40b1-11eb-9b61-2f0d4faf84db.gif)
