### ISSUE TITLE
FR: Disable regular sync popup

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1492]
Hi

Is it possible to have an option for this so that we cna enable or disable this popup? In my opinion it is very distracting to have some thing show up and disappear frequently. I realize it is very useful but when it does the opposite when it is so frequent,\

thanks

**Comment by zadam** [comment]
How often does it show to you? I usually see it only during startup, afterwards it's hidden ...

**Comment by gerroon** [comment]
I see pretty frequently on Windows, I cant tell but couple times a minute or once a min maybe?

**Comment by zadam** [comment]
I looked into this deeper and it's weird. This message is displayed only if there are some changes coming from a sync server - if it keeps getting displayed it seems like there are new changes all the time being created. So what you're observing is probably some kind of bug or weird setup.

Could you post your backend log (~/trilium-data/log/...) here or to my email zadam.apps@gmail.com? That should help to figure out the problem with the sync. Thanks.

**Comment by gerroon** [comment]
Ok that kind of makes sense, becasue I have multiple users here using the same sync server. In that case one edits frequently and while other was just looking at the notes without editing. While it explains it does not solve the issue, so  I guess not a bug but more of a feature request.

**Comment by zadam** [comment]
There is no popup now.
