### ISSUE TITLE
Backend Scheduled Tasks

### ISSUE THREAD

**Issue by lflare** [zadam/trilium#1494]
As someone who both uses the local and server version of the application, I've noticed my @hourly and @daily tasks for the backend script running twice, once locally and once on the server. Is there a better way to go about properly implementing this?

For example, if I have a script that downloads and creates a note with a date time, my local Trilium instance executes it once, and my server hosted Trilium also executes it again, resulting in two notes.

**Comment by zadam** [comment]
Hi, sorry for late response.

For this purpose there's a "instanceName" in backend api:

```javascript
    /**
     * Instance name identifies particular Trilium instance. It can be useful for scripts
     * if some action needs to happen on only one specific instance.
     *
     * @returns {string|null}
     */
    this.getInstanceName = () => config.General ? config.General.instanceName : null;
```

And define instanceName in config.ini:

```
[General]
instanceName=whatever
```

You can then use this in `if` to execute only on the desired instance.

**Comment by lflare** [comment]
Ah, thanks, much appreciated.
