### ISSUE TITLE
[Feature request] Show full date in Linkmap and What links here

### ISSUE THREAD

**Issue by lpd743663** [zadam/trilium#1496]
When linking to multiple diaries, I think it would be better to know the specific dates directly

like this
![image](https://user-images.githubusercontent.com/4426804/102679418-c187fe80-41ea-11eb-852d-c9a897535d47.png)

**Comment by zadam** [comment]
Hi, so the underlying problem is that "day note" title is only "24 Monday" and these other widgets don't know it actually represents a calendar date.

The real solution would be to create the day note as "2020-12-20 Monday" and then it will display like that everywhere. I added this possibility and documented it in https://github.com/zadam/trilium/wiki/Day-notes#date-pattern (this will be in 0.46 once released)

**Comment by lpd743663** [comment]
> Hi, so the underlying problem is that "day note" title is only "24 Monday" and these other widgets don't know it actually represents a calendar date.
> 
> The real solution would be to create the day note as "2020-12-20 Monday" and then it will display like that everywhere. I added this possibility and documented it in https://github.com/zadam/trilium/wiki/Day-notes#date-pattern (this will be in 0.46 once released)


Thanks  
In this case, the link in the notes can also be solved.

Also, will this rename the previous diary?

Some of the names of the previous diaries have been changed, e.g.  `04 - Monday - Going to Grandma's house`


![image](https://user-images.githubusercontent.com/4426804/102730891-266d6100-4371-11eb-97b6-2669e3fa3a74.png)

**Comment by zadam** [comment]
> And, will this rename the previous diary?

No, this will affect new day notes only.

(The whole calendar system is really only quite thin layer over normal notes ...)

**Comment by lpd743663** [comment]
> > And, will this rename the previous diary?
> 
> No, this will affect new day notes only.
> 
> (The whole calendar system is really only quite thin layer over normal notes ...)


Thanks 😄️

**Comment by lpd743663** [comment]
Hi @zadam 

Can you tell me how to set this attribute ( on  trilium-docker-0.45.7 ) 

---


The current settings are not working and the result is this：

---
![image](https://user-images.githubusercontent.com/4426804/103069944-74959500-45fb-11eb-802b-531343c27ab6.png)


![image](https://user-images.githubusercontent.com/4426804/103070140-d8b85900-45fb-11eb-8608-94b655ba6ada.png)

**Comment by zadam** [comment]
`isoDate` was committed to master, it will be available only in 0.46
