### ISSUE TITLE
[BUG] Cannot automatically create inverse relationships

### ISSUE THREAD

**Issue by Grygon** [zadam/trilium#1498]
Version: 0.45.6

Can reproduce on both Web -> Server and Windows -> Server versions. Server is running via Docker.

I'm unable to automatically create inverse relationships as the wiki/demo describes. I even re-imported the demo environment to see if there were issues with my tests, but that doesn't seem to be working either.
See gif here:
![invRelISsue](https://user-images.githubusercontent.com/647846/102745415-8a683900-4321-11eb-809a-8459fd8f5eb4.gif)

Server log:
[trilium-2020-12-21.log](https://github.com/zadam/trilium/files/5722588/trilium-2020-12-21.log)

**Comment by zadam** [comment]
Hello, thanks for reporting this bug, it has been fixed and will be released in next stable version.
