### ISSUE TITLE
Trilium behind htpasswd

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#1501]
Is it possible to sync Trilium with a password-protected webpage? I tried supplying the login in https://user:password@mydomain.com, but that didn't work and isn't secure anyway. It would be great if it were possible to supply a user/pass when syncing.

**Comment by zadam** [comment]
The sync is authenticated, so I don't think this is necessary. Authentication is done by an internal secret token stored in the document database.

(To set up the initial sync you will need to provide username/password)

**Comment by jbhanks** [comment]
OK, but what if I want to hide the Trilium login page, so that unauthorized visitors can't even see that it is a Trilium instance?

**Comment by zadam** [comment]
In that case something like htpasswd (basic auth) could be used. There's no specific support for this in Trilium and it would be handled on the reverse proxy.

**Comment by jbhanks** [comment]
Yes, I currently have htpasswd set up on the reverse proxy, but it blocks sync. How do I pass the htpasswd login info for the purposes of sync?

**Comment by zadam** [comment]
I was thinking about the "https://user:password@mydomain.com" but you wrote in the original post that this doesn't work.

Does this URL form of authentication work when you use curl / wget / your browser?

**Comment by zadam** [comment]
I was thinking about the "https://user:password@mydomain.com" but you wrote in the original post that this doesn't work.

Does this URL form of authentication work when you use curl / wget / your browser?

**Comment by jbhanks** [comment]
You are correct. The problem was that my login contained a character that needed to be replaced with a utf encoding when sent as a url. My understanding is that this is still not as secure as if the login/pass were supplied in response to a request, but as an extra layer of security it will do.
