### ISSUE TITLE
Sync version mismatch

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#1502]
I pulled the docker image for Trilium 0.45.7 and also downloaded Trilium desktop 0.45.7. However, sync failed because the local sync version was 16 and the remote was 18. I solved the problem by using 0.45.6 of the server docker image, but I was wondering if that was a mistake or if I'm not understanding something about the version nomenclature.

**Comment by zadam** [comment]
Hi, not sure what's going on, I just tested 0.45.7 image and I get:

{  
 "appVersion": "0.45.7",  
 "dbVersion": 170,  
 **"syncVersion": 16,**  
 "buildDate": "2020-12-22T20:21:15+01:00",  
 "buildRevision": "bdfd760",  
 "dataDirectory": "/root/trilium-data",  
 "clipperProtocolVersion": "1.0"  
}  
 

syncVersion 18 would correspond to current master (unreleased development version), but I don't build any docker images for that yet ...

**Comment by jbhanks** [comment]
Strange.
My command:
```
sudo nohup docker run --restart unless-stopped -p 127.0.0.1:8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:0.45.7 1>~/trilium_stdout.txt 2>~/trilium_stderr.txt &
```
but when I sync I get: 
![image](https://user-images.githubusercontent.com/12942318/103164686-6a7ebc80-47dc-11eb-84ce-0493ae983446.png)


The log from inside the container:

```
05:41:45.015 App HTTP server starting up at port 8080
05:41:45.015 {
  "appVersion": "0.45.7",
  "dbVersion": 178,
  "syncVersion": 18,
  "buildDate": "2020-12-22T20:21:15+01:00",
  "buildRevision": "bdfd760b9d428dc29c45a0e016d12a25af220043",
  "dataDirectory": "/home/node/trilium-data",
  "clipperProtocolVersion": "1.0"
}
```

**Comment by cerivitas** [comment]
I also have similar problem.. I download the desktop version of latest release (0.45.8) and install the server instance to heroku with latest code, but when trying to sync I have error sync desktop is version 16 and server is version 19... how do I fix this?
Thank you

![image](https://user-images.githubusercontent.com/22749283/104815508-94f5ef80-5847-11eb-82a2-aa6b7dee25c0.png)

**Comment by zadam** [comment]
@cerivitas you checked out master branch, but that's a development unreleased version. You need to use `stable` branch.

**Comment by jbhanks** [comment]
I am confused about how to get the stable docker image though. I don't see any docker images with the "stable" tag, as recommended in the wiki:

```
Replace [VERSION] for actual latest version or use "series" tag - e.g. 0.39-latest.

It's not recommended to use "latest" tag since it may upgrade your Trilium instance to new minor version which may potentially break your sync setup or cause other issues.
```

```
$ sudo docker pull zadam/trilium:0.45-stable
Error response from daemon: manifest for zadam/trilium:0.45-stable not found: manifest unknown: manifest unknown
```

**Comment by zadam** [comment]
Hi @jbhanks, from what @cerivitas wrote I inferred he cloned a git repo and there he needs to use stable branch.

But terminology in docker is different, there you should use 0.45-latest tag.

**Comment by Potjoe-97** [comment]
Actually, my last issue #1629 could be related to this one. I noticed that my docker installation, which has been running for quite some time, is still using sync version 16, whereas I'm using zadam/trilium:latest image.
