### ISSUE TITLE
Proxy-auth

### ISSUE THREAD

**Issue by Typhonragewind** [zadam/trilium#1513]
I couldn't find this information on the documentation or github issues, but forgive me for asking it again if it is a common question/knowledge.

Is it possible to pass authentication information to Trilium via a reverse proxy header to login automatically? For example, i login into my reverse proxy (nginx) environment using Authelia and for most of the services I'm able to pass the credentials via a HTTP header (such as Remote-User) and have them auto login into the service.
This is a great QOL feature since it prevents me from entering my credentials twice.

**Comment by zadam** [comment]
For this use case you can disable the Trilium auth completely in `trilium-data/config.ini`

> \[General\]  
> \# Instance name can be used to distinguish between different instances using backend api.getInstanceName()  
> instanceName=
> 
> \# set to true to allow using Trilium without authentication (makes sense for server build only, desktop build doesn't need password)  
> **noAuthentication=false**

**Comment by Typhonragewind** [comment]
Yup, that'll do the trick nicely. I hadn't thought of disabling auth itself.

Thank you so much for the help :)
