### ISSUE TITLE
[Feature Request] Automatically search for selected text when adding an internal link

### ISSUE THREAD

**Issue by dzerus3** [zadam/trilium#1515]
The way I take notes, I often type up a piece of text and go back to add internal links to other notes once I am finished. Every time I add a new link, however, I have to type at least part of the linked note's name to search for it. I noticed that the note's title is often the same, or similar to the text I am using as the link. I suggest that as a quality of life improvement Trilium automatically paste in whatever text was selected when adding an internal link into the search bar.

**Comment by zadam** [comment]
Hi, yes, this makes sense and has been added to the master branch. Thanks for suggestion.
