### ISSUE TITLE
[Feature Request] Exclude pages from search via attribute

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1519]
I have a Trilium database that includes a subtree of imported pages, basically my notes taken in other software over the last 10+ years. There are a number of page types in there, that I don't want to show up in search results.

I guess this could be implemented, for instance, by adding an `#excludeFromSearch` attribute that can be added to these pages.

Is this something worth considering?

**Comment by zadam** [comment]
Hi, you can use `archived` label to mark notes which should not show up in search results. Can be also set as inheritable to apply to whole subtree ...

**Comment by wwwald** [comment]
Awesome - didn't think of that. Thanks a lot!
