### ISSUE TITLE
[Feature Request] Consolidate link functionality (addLinkToText) - URL & Trilium Link

### ISSUE THREAD

**Issue by mbafford** [zadam/trilium#1521]
Currently meta+L (`addLinkToText`) allows you to create a new link in your current document to a Trilium note, but you need to use different functionality to create a URL link. This works _fine_, but it adds cognitive overload (which shortcut do I use?).

Propose making the `addLinkToText` popup have a special case for URLs - if you paste in an, e.g. http(s):// link - have it offer to just make a URL like like meta+K (not sure what function this is, as it's not in my keyboard shortcuts list) does.

This should still do a search of existing notes - which could be very powerful - maybe you forgot you already created a note for http://amazingproject.com/ - and instead of linking to the website you want to link to your previous note instead.  

Mockup:
![image](https://user-images.githubusercontent.com/713813/104035395-14c4ef80-51a0-11eb-9d77-c7f45e2f7200.png)

Challenges/issues:
* recognizing what's a link (`http://`, `https://` are obvious, what about `sftp://`, or other less common ones? - should be safe enough to just add this new option if `scheme://` is encountered)
* maybe ckeditor doesn't make this easy

Related:
* https://github.com/zadam/trilium/issues/263
* https://github.com/zadam/trilium/issues/567

If you'd accept a PR for this, let me know some pointers where to start poking, and I might try implementing this myself.
(thanks for the first note taking project that almost 100% resonates with me - I want to help contribute back!)

**Comment by zadam** [comment]
Hi, I implemented recognizing absolute URLs as you described:

![](https://user-images.githubusercontent.com/617641/104062527-f04a3100-51fa-11eb-8006-e08ad6e50d75.png)

I will probably keep the CKEditor's native external link dialog in some form because it also allows editing existing links.

**Comment by mbafford** [comment]
Thank you for the quick turnaround on this!

I agree with keeping CKEditor's current edit interface. It's very helpful for editing an existing document's linkes. I was thinking about your comment while editing some recent notes - and was using that link editor - and I agree it's still needed.
