### ISSUE TITLE
[Feature Request] Populate selected text in add note link (addLinkToText) popup

### ISSUE THREAD

**Issue by mbafford** [zadam/trilium#1522]
**Feature Request**

When text is selected in a note and meta+L (`addLinkToText`) is invoked, copy the selected text into the resulting "Add note link" popup as the default input.  Ideally selected so typing something else will wipe it out.

**Comments**

This has been mentioned in some issues and seems to have been a feature once. This would be very helpful:

* typing quick notes to enrich - when you want to retroactively link to existing notes you have to select the text to link, copy the text, invoke the popup, paste the text
* creating a quick outline - using the (very useful) "Create and link child note" functionality in the `addLinkToText` popup - this would simplify typing out the outline then going back and creating the relevant child notes

The existing functionality "cut & paste selection to sub-note" does not accomplish the desired goal for two reasons:
* The selection goes to the sub-note body, not the title - these accomplish different purposes
* This means I have to remember which workflow I want - vs. using a single shortcut key for all links

Combined with #1521 this would simplify linking existing URLs (and doing the "search for other notes mentioning this URL" workflow mentioned in that FR).

Related:
* https://github.com/zadam/trilium/issues/1521
* #263 ( https://github.com/zadam/trilium/issues/263#issuecomment-450561681 )
* #567 ( https://github.com/zadam/trilium/issues/567#issuecomment-501445669 )

**Comment by zadam** [comment]
Hi, if I understand this request correctly then the same was asked for (and subsequently implemented) couple of days ago in #1515 

This is going to be released as part of 0.46

**Comment by mbafford** [comment]
Duplicate of #1515
