### ISSUE TITLE
Weird Behavior When Using Back Ticks In Bullet Points Causing Loss Of Functionality And Small Data Loss

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium#1523]
# Version

Version: 0.45.7

# Information

When using backticks (``) within bullet points after the final backtick is entered, I lose the ability to have my enter, or backspace keyboard presses recognized. Additionally when refreshing the page all text changes made after the final backtick are lost. This behavior does not happen if the backticks are used outside of bullet points. 

I've included a short screen capture to show the issue
![Peek 2021-01-08 16-49](https://user-images.githubusercontent.com/17089485/104078157-95bdce80-5214-11eb-989a-3d7a41468533.gif)

I use Trilium on my Linux laptop by having cloned the repository locally, checking out the appropriate git tag, running `npm install` and `npm build` to update between releases. I have the following systemd service to start trilium:

```systemd
[Unit]
Description=trilium service
After=network.target

[Service]
User=solidity
Group=solidity
Type=simple
LimitNOFILE=65535
ExecStart=/media/solidity/DATA/trilium_start.sh
Environment="TRILIUM_DATA_DIR=/media/solidity/DATA/trilium"
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
```

**Comment by zadam** [comment]
Hi, this is probably a CKEditor bug. My strategy is to wait a bit and these bugs get usually fixed sooner rather than later ...

**Comment by wwwald** [comment]
Resembles some previously reported issues - e.g., #1427 which describes similar behavior after entering links via @.

**Comment by bonedaddy** [comment]
> Hi, this is probably a CKEditor bug. My strategy is to wait a bit and these bugs get usually fixed sooner rather than later ...

Is there anyway to workaround this? It is definitely putting a slow-down to my note taking. Not entirely problematic as I can adjust my note-taking style, and the pros of Trilium vastly out-weight this, but any possible work around (other than adjusting note style if at all possible) would be great.

**Comment by ashtneoi** [comment]
Since this bug can potentially cause silent data loss, is there any way for Trilium to detect the problem, save the user's data, and tell the user to reload the frontend? I've lost some notes already (and had a few close calls), so I'd be motivated to work on this myself if I had some guidance.

**Comment by zadam** [comment]
@ashtneoi unfortunately I don't know how to detect this. CKEditor crashes and prints an error to the console but otherwise the application is not informed. Maybe there is some event/listener though but I did not find it.
