### ISSUE TITLE
Question: Way to share Trilium-Notes ...

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1527]
Hello,

at the creation of Trilium, we create a user, right? Can that one user be used by two people at once?
But if we expose the database through HTTP for instance.

I haven't seen yet that I had to login there.
If I loaded Trilium Notes into a server and then exposed it

- would I be able to share the contents with my teacher?
- can two people at once browse through the same database?

The reason is somewhat simple.
I have a list of musical pieces I work on and the PDFS are linked with internal Trilium links.
It would be so nice to give my teacher a simple way to always have the latest overview of my music work.

**Comment by zadam** [comment]
> at the creation of Trilium, we create a user, right? Can that one user be used by two people at once?

Technically yes, but you're going to have issues once both start to edit same note.

Trilium doesn't support sharing or collaboration between multiple users. You can give your teacher credentials to your shared instance, that way he/she will "impersonate" you.

There's a tentative plan which will allow the server instance "publish" a note subtree as a read only website.

**Comment by zDEFz** [comment]
That sounds neat! Now I only have to set it up on a server...
