### ISSUE TITLE
[Feature Request] Option to stop backups

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1533]
Scenario:
Running on storage limit on a VPS, instead wanting to pull from ssh and making the backups this way instead.

Want to stop backups from happening.

If it's no option, I have to upgrade my VPS at some point.

**Comment by wwwald** [comment]
Workaround would be to configure a CRON job on your VPS, to clean out the backups on a specified schedule?  
Could that work?

**Comment by zDEFz** [comment]
thanks for your suggestion wwwald
I think it will work as long as I have traffic... But long term I would fancy it if I could stop it from happening.
I wonder. How will Trilium-Notes behave if backups folder would be read only? I'm going to try.

**Comment by zadam** [comment]
It's now possible to disable backups via config.ini:  
 

```
[General]
# Instance name can be used to distinguish between different instances using backend api.getInstanceName()
instanceName=

# set to true to allow using Trilium without authentication (makes sense for server build only, desktop build doesn't need password)
noAuthentication=false

# set to true to disable backups (e.g. because of limited space on server)
noBackup=false
```
