### ISSUE TITLE
Please update Linux instructions

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1534]
Followed the instructions. Wasn't possible to set two different instances, passing the folder through `docker run -t -d -i -p 80:80 -v ~/trilium-data://root/trilium-instances/pianostudy/trilium-data zadam/trilium` yielded no success.

I basically moved it to there...

It would always take `root/trilium-data`, no matter what.

Whats more is that the arguments like the port etc aren't respected and instead it assumes from the config.ini.
If trilium-data directory path was altered like in the wiki shown with the `export` command, trilium would still not initialize the database.

By the way, `echo $TRILIUM_DATA_DIR` returns nothing at all.

Ubuntu 18.04 was used.

**Comment by zadam** [comment]
I think you're misunderstand how docker works. You probably want to change `~/trilium-data` of the path mapping.

> Whats more is that the arguments like the port etc aren't respected and instead it assumes from the config.ini.

You mean docker port mapping? Of course that has no effect on Trilium configuration.

> If trilium-data directory path was altered like in the wiki shown with the `export` command, trilium would still not initialize the database.

Not sure what you mean, but `export` executed in the host has no effect on the container

**Comment by zDEFz** [comment]
@zadam even if you put ```docker run -t -d -i -p root/trilium-instances/pianostudy/trilium-data zadam/trilium```

It still uses root/trilium-data

**Comment by zadam** [comment]
> `docker run -t -d -i -p -v root/trilium-instances/pianostudy/trilium-data zadam/trilium`

That does not seem to be correct syntax (missing first `/` in front of `root`, where's `:` and second path in the mapping?)

Anyway I tested the example in the wiki, and it behaves as expected.

**Comment by zDEFz** [comment]
I put on a screencast

**Comment by zDEFz** [comment]
@zadam https://streamable.com/1uq40i

Please tell me whats wrong there. I made an exact copy of my old folder, too and linked that... 

Used that command ``` sudo docker run -t -i -v ~/trilium-data:/root/trilium-test zadam/trilium```

**Comment by zadam** [comment]
Why do you remove port mapping and then try to open port 90?

You're changing container mapped path. If you want to change the host path, you need to edit the first path.

Please read docker documentation. It looks like you don't really know what you're doing.

**Comment by zDEFz** [comment]
>Why do you remove port mapping and then try to open port 90?

Cause I set port in trilium config.ini...

Anyways, why is the path not updating? Database not loading?

**Comment by zadam** [comment]
> Cause I set port in trilium config.ini to port 90.

You clearly don't understand docker, but it's not my job to educate you. Sorry.

**Comment by zDEFz** [comment]
I got it....
