### ISSUE TITLE
Question - Add child notes under parent document

### ISSUE THREAD

**Issue by aviral-batra** [zadam/trilium#1535]
Hi, I've only started using this app but it has so much functionality and scripting potential - thanks for making it!

In a note which has no content, the children are displayed in the note, e.g. -

![image](https://user-images.githubusercontent.com/68279653/104665376-09eeeb00-56c9-11eb-8ed8-851e4cae4c49.png)

 Is there a way to retain these after you have added content?

**Comment by zadam** [comment]
Hi, the approach changed in the current master version (not yet released 0.46) and this "children overview" will not disappear when you add some content. Stay tuned.

**Comment by aviral-batra** [comment]
And is there a way of editing these children directly from the overview?

**Comment by zadam** [comment]
No, overview is read only.

**Comment by aviral-batra** [comment]
Ok thanks.
