### ISSUE TITLE
Make window title "{note title} - Trilium Notes" not "Trilium Notes - {note title}"

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#1551]
Just so those of us with smaller window names at the bottom can better see the name of the note :smile: 

Example: 
![image](https://user-images.githubusercontent.com/69441971/105045137-75d1aa80-5a5f-11eb-9b92-58427307b13b.png)

What it should be: 

![image](https://user-images.githubusercontent.com/69441971/105045402-c6e19e80-5a5f-11eb-8b74-8420e830b504.png)

**Comment by leeyaunlong** [comment]
```
let tmp = $("title").html();
$("title").html(tmp.replace("Trilium Notes - ",""));
```

> Just so those of us with smaller window names at the bottom can better see the name of the note 😄
> 
> Example:
> ![image](https://user-images.githubusercontent.com/69441971/105045137-75d1aa80-5a5f-11eb-9b92-58427307b13b.png)
> 
> What it should be:
> 
> ![image](https://user-images.githubusercontent.com/69441971/105045402-c6e19e80-5a5f-11eb-8b74-8420e830b504.png)
``` js
let tmp = $("title").html();
$("title").html(tmp.replace("Trilium Notes - ",""));
```

**Comment by sigaloid** [comment]
Oh yeah, electron... Thanks :smile:

**Comment by zadam** [comment]
I'm reopening the issue since it is actually something I want to fix.

@leeyaunlong I think this works one time only, once you switch note, it will be reset to the old form.
