### ISSUE TITLE
Heading 1 markdown not working

### ISSUE THREAD

**Issue by rsheftel** [zadam/trilium#1552]
Using Trilium v0.45.8 in a text note, the "#" markdown for a Heading1 does not work. It just shows "# heading", while any of the high order headers like "##" or "###" work fine.

**Comment by sigaloid** [comment]
>By default this feature is configured to support <h2>, <h3> and <h4> elements which are named: “Heading 1”, “Heading 2” and “Heading 3”, respectively. The rationale behind starting from <h2> is that <h1> should be reserved for the page’s main title and the page content will usually start from <h2>. 

>By default, when your editor build does not include the title plugin, a <h1> element pasted into the rich-text editor is converted to <h2> (“Heading 1”).

https://ckeditor.com/docs/ckeditor5/latest/features/headings.html#heading-levels

**Comment by zadam** [comment]
@sigaloid good find, I didn't even know that is the CKEditor's team reasoning, but it's the exact same reason why I configured CKEditor without H1 support.

**Comment by rsheftel** [comment]
Thanks for this.
