### ISSUE TITLE
[Bug] Note footer info (word count, character count) cut off

### ISSUE THREAD

**Issue by Grymas** [zadam/trilium#1556]
Version 0.45.8, on Kubuntu using the .deb release.

The Note footer with word count and character count info is cut-off at the bottom of the app.
![image](https://user-images.githubusercontent.com/12102823/105253769-6a29d500-5b80-11eb-977b-5b46b89ebc28.png)

Changing fullscreen mode or font options didn't fix the problem.

Playing around with the dev console, on the specific <div> changing the value of the "contain" css rule for .component fixes it (removing it or setting the value to "content" instead of "size").

**Comment by sigaloid** [comment]
If this is #1224 (sounds like it) the docs have been updated to reflect that IIRC.

https://github.com/zadam/trilium/wiki/Custom-Widget

**Comment by Grymas** [comment]
Worked like a charm, thanks!
