### ISSUE TITLE
[Question] Authentification is lost opening a second instance in the browser while signed in into another

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1559]
Ver 0.45.8

Uncertain why this is happening. Tried to recreate the instance. Same problem. 
Instance has seperate folder with own database. Both have distinguishable instance names.
Both don't use HTTPS.

Tried to use different passwords for each and unique ones. Didn't make a difference.

What I basically do is to sign in into <Server:80> then sign into <Server:81>
Then I get those authorization "problems" even though each runs their own unique database and unique instance.

Any nice explanation?

[...]
01:47:35.125 Slow GET /api/similar-notes/XSIdj20iNnvL took 247ms
01:47:35.137 GET /api/notes/XSIdj20iNnvL/revisions took 8ms
01:47:35.718 GET /api/script/startup took 2ms
01:47:35.994 Slow POST /api/tree/load took 68ms
01:47:39.159 POST /api/recent-notes took 6ms
01:47:40.454 POST /api/recent-notes took 3ms
01:47:40.458 POST /api/recent-notes took 3ms
01:47:40.461 POST /api/recent-notes took 2ms
01:48:13.110 GET /api/notes/0CiWAX6vmNQz rejected with 401 Not authorized
01:48:13.116 PUT /api/options rejected with 401 Not authorized
01:48:13.130 JS Error: Error when calling GET notes/0CiWAX6vmNQz: error - Unauthorized

**Comment by zDEFz** [comment]
Hmm, just realized it's due to my browser making the same cookie for Trilium, even when the port is different.

**Comment by zadam** [comment]
Yes. Workaround is to create a separate host alias for localhost (in linux in `/etc/hosts`), then browser will store cookies separately.

**Comment by zadam** [comment]
Yes. Workaround is to create a separate host alias for localhost (in linux in `/etc/hosts`), then browser will store cookies separately.
