### ISSUE TITLE
[Bug] Adding a reference link (mirrored title) breaks typing unless frontend is refreshed

### ISSUE THREAD

**Issue by QuentinLeCaignec** [zadam/trilium#1564]
Version 0.45.8, on Kubuntu.

After adding a reference link (with the mirrored title), either with the @ symbol or by doing CTRL+L and selecting mirror title, typing gets weird if you immediately continue typing.
In my case, after adding the link I can partially type but can't backspace on the line (sometimes I can backspace somewhere else in the note, it seems unreliable) unless I do a frontend reload.

This might not be related, but i've sometimes experienced a strange "stuck" state where I can't select or edit text on a note (and it's not in read-only mode, it is in edit mode) unless I reload, and another kind of bug where selecting other notes doesn't update the note display on the main screen and it stays stuck on it until I reload.

**Comment by zadam** [comment]
Hi, does this happen in normal paragraph or perhaps in a bullet list? Is this reproducible (for me it seems to work OK). This sounds like a CKEditor bug somebody reported earlier.

Second issue sounds also like a CKEditor bug where the editing component crashes and gets stuck. CKEditor 5 is relatively young and sometimes there are unstabilities like that :(

**Comment by Grymas** [comment]
I tested this again, you're correct it seems to happen inside a bullet list, after adding a second reference link (the first was fine) frontend needs a refresh or the typing is broken, also when refreshed anything typed after the second link didn't save.

**Comment by meichthys** [comment]
To add to this, i've noticed this usually in bulleted lists, but not necessarily after any link or @ symbol like another issue here mentioned. The result is the same, once the bug happens it prevents me from backspacing but usually i can continue to type (although i've found that if i do continue, the data typed after the bug happens is usually lost)

**Comment by ch4ser-go** [comment]
It seems that the problem still remain at version 0.47.5, on arch linux.

**Comment by ShadowKyogre** [comment]
I can confirm the same problem happens to me on 0.47.7 and 0.47.8 . The strange part about the error is that sometimes I'm able to get a good backlog of what happened, sometimes not (error message doesn't always show). Definitely is a CKEditor issue since the error logs complained about nodes not being found in the hierarchy. Will post them after work.

**Comment by abitofevrything** [comment]
This is fixed, or at least not as easy to reproduce, on latest master but not on latest release.
