### ISSUE TITLE
aarch64: standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Erriez** [zadam/trilium#1569]
docker-compose.yml:

```yaml
version: "3"

services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    restart: always
    networks:
      - web
    ports:
      - 8080:8080
    volumes:
      - ./trilium_data:/data

networks:
  web:
    driver: bridge
```

Output:
```bash
# docker-compose up
trilium           | standard_init_linux.go:211: exec user process caused "exec format error"

# uname -a
Linux raspberry 5.4.0-1026-raspi #29-Ubuntu SMP PREEMPT Mon Dec 14 17:01:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

How can this be executed on an ARM64?

**Comment by zadam** [comment]
There's no official support for ARM, sorry.

Somebody has been producing (unofficial) builds for ARM64 here; [https://hub.docker.com/r/hlince/trilium/](https://hub.docker.com/r/hlince/trilium/)

(use at your own risk)

**Comment by Erriez** [comment]
@zadam Thanks for your fast reply. I tried the `image: hlince/trilium:latest-stable-arm` but results in the same error. I switched to 64-bit ARM recently which is the way forward on a Raspberry Pi. 
I'll wait for an image, because I've no experience and time to create it.

**Comment by Erriez** [comment]
@zadam I found a solution to build the image manually on the ARM64 Raspberry Pi 4 with 8GB memory:

```bash
# Clone project
git clone https://github.com/zadam/trilium.git
cd trilium
cat package.json | grep -v electron > server-package.json

# Build image manually (this takes several minutes and lots of warnings)
docker build . -t trilium --network host

# Run temporary
docker run --rm --name trilium -p 8080:8080 trilium
```

**docker-compose.yml**
```bash
version: "3"

services:
  trilium:
    image: trilium
    container_name: trilium
    restart: always
    networks:
      - web
    ports:
      - 8080:8080
    volumes:
      - $PWD/trilium_data:/data

networks:
  web:
    driver: bridge
```

```bash
docker-compose up
```

I have to play around with this great software. Thanks!

**Comment by jokajak** [comment]
I pushed an image of v0.46 to https://hub.docker.com/repository/docker/jokajak/trilium
Verified it works in my kubernetes cluster too. Thanks for instructions on how to build it!

**Comment by jokajak** [comment]
This is related to https://github.com/zadam/trilium/issues/1399
