### ISSUE TITLE
[Bug] Inconsistent drag-drop reordering/moving of notes

### ISSUE THREAD

**Issue by Grymas** [zadam/trilium#1587]
(version 0.45.8, on Kubuntu)

I've noticed strange and inconsistent inability to drag and drop specific notes, to reorder or move them. Sometimes it works, sometimes it doesn't. Usually by moving around I'll be able to move a note in some other spots or notes but not all. Also sometimes dragging something on or inside of the parent note has weird results (dropping the child *outside* of the parent note).

Here's a recording or this :

![output](https://user-images.githubusercontent.com/12102823/106169580-cfd51d00-618f-11eb-8dcc-135e448d8739.gif)

I don't remember having this issue before. Seems similar to #1296

**Comment by zadam** [comment]
Hi, yes, I did notice this too. Seems to be related to lazy loading of note children, I switched `preventLazyParents` to false and it seems to help.

**Comment by yllekz** [comment]
Yeah this is really frustrating for me as well. I imported a bunch of stuff and am trying to organize and nest notes. The drag/drop action seems unpredictable on my end. I even thought maybe it was Firefox but it's doing it in Edge as well.
