### ISSUE TITLE
[Bug] Included notes not resizing around aligned images

### ISSUE THREAD

**Issue by Grymas** [zadam/trilium#1590]
(Version 0.45.8, on Kubuntu)

I love the Include Note feature, allows me to split a note into a bunch of other notes and it looks super clean.
However, I often have an image at the beginning of the text that I align to the right (wiki style, often a portrait for characters), and i've noticed the Included Notes ignore the aligned image and render on top of it rather than resizing like the rest of the text.

While i'm at it, images aligned to the **left** seem to somehow have 0 margin in between the image and the text to the right, which looks weird or even hard to read. I think it's the same when aligned to the right but less noticeable because of how text tends to align itself.

**Comment by Grymas** [comment]
Oh slight correction, the text *inside* the included note aligns fine like normal text, but the "box" of the included note doesn't resize along with it, and appears in front of the image.

**Comment by Grymas** [comment]
Playing around with the CSS in console, this seems fixable by displaying the Include Note element as flex (display: flex), and giving .image a small margin (like 0.5em) instead of auto (which for me ends up being none).
The extra margin on the image also makes the Included Note background not touch/clip into the image (which it does even displayed as flex, if there is no margin).

**Comment by zadam** [comment]
Hi, thanks for reporting these issues, both have been fixed in stable branch.

**Comment by Grymas** [comment]
Thanks. I've looked at the fix, and it seems like it'll just force the included notes lower down leaving a lot of empty space, which means a note that has a lot of left/right aligned images will just have huge gaps of empty space.
This is probably pretty tricky to fix without breaking the CSS of something else, did you try my potential fix of displaying it as flex and adding a bit more of a margin to images?

**Comment by zadam** [comment]
I tried that but frankly I don't understand how (why) it works and what possible side effects it might have. It's mixing floating elements with flex which is completely new to me. Also what surprises me is that `display: flex` has an effect on the element itself while normally it influences the positioning of the children elements.

**Comment by Grymas** [comment]
You're right that combining flex with others things might have strange results.
The reason adding flex to include-note works is because it makes the <section> a flex container, which means the child (<div> "include-note-wrapper") which actually contains the text is affected.

While i agree that side effects might appear, given the fact this only applies to and inside of included notes, I feel like there's not much chance of this breaking something else. I've applied it on my end with a appCss note and I've not seen any issues in normal, book or included notes, with or without images.

If you're still uncertain I understand, your fix is functional, and it's not too difficult to modify on my end anyway.

**Comment by zadam** [comment]
Ok, let's try `display: flex` and we can revert back to `clear: both` if problems appear ...
