### ISSUE TITLE
How to upload js file as attachment instead of code note?

### ISSUE THREAD

**Issue by v587ygq** [zadam/trilium#1591]
I want to upload a large js file as attachment , but it is shown as code note.

accoding to  this issue https://github.com/zadam/trilium/issues/66 ， may be there are some ways to solve it?

my trilium version: 0.45.8

**Comment by zadam** [comment]
Hi, in the import dialog, uncheck "Import recognized code files (e.g. `.json`) as code notes if it's unclear from metadata":

![](https://user-images.githubusercontent.com/617641/106318817-c2439400-6270-11eb-9c2b-a5b60802eee8.png)
