### ISSUE TITLE
Can Chinese or other language support be added? Or open api to provide other language support by other developers.

### ISSUE THREAD

**Issue by dejavudwh** [zadam/trilium#1597]
Can Chinese or other language support be added? Or open interface to provide other language support by other developers.

In addition, thank you for your contribution to this software, it helped me a lot

**Comment by zadam** [comment]
Hi, there isn't any localization/internationalization support and also none is planned ATM.

See also related: #1287, #583

**Comment by sepwolves** [comment]
I don't think there is any need for Chinese language suport. Anyone who uses triulium should master English well.

**Comment by zadam** [comment]
I created a FAQ entry: https://github.com/zadam/trilium/wiki/FAQ#translation--localization-support

Since this is not planned to be done, I'm going to close this.
