### ISSUE TITLE
Is there a way to assign an attribute to many notes at once?

### ISSUE THREAD

**Issue by rosewills** [zadam/trilium#1607]
I would like to archive an entire subtree of notes. I can easily assign the "archived" attribute to the top note, but there are 50+ notes in this subtree. Is there a way to do this en masse?

Similarly, there is a way to select certain specific notes (not necessarily from the same subtree) and apply the "archived" attribute to those notes only?

**Comment by wwwald** [comment]
I think you can label the parent tree as archived and make that inheritable. That way, the whole subtree will be archived.

See the wiki: [Archived notes](https://github.com/zadam/trilium/wiki/Archived-notes)  and [Attribute inheritance](https://github.com/zadam/trilium/wiki/Attribute-inheritance)

**Comment by zadam** [comment]
@wwwald is correct, for archiving the inheritance works the best.

However in 0.46 there's new support for labeling multiple notes (and doing other things).

**Comment by rosewills** [comment]
Ah, super! Thanks so much!
