### ISSUE TITLE
Template made me stuck.

### ISSUE THREAD

**Issue by sepwolves** [zadam/trilium#1608]
After I used a template, the note got stuck. The "not responding" prompt appears constantly.

**Comment by sepwolves** [comment]
Is it because the template will generate sub-notes, resulting in an endless loop of notes?

**Comment by zadam** [comment]
Hi, yes, if you applied a template relation to the child of that template then such situation could arise. There was also related bug mentioned here: #1592 

Are you able to delete the note or somehow recover from the situation?
