### ISSUE TITLE
License change request

### ISSUE THREAD

**Issue by zDEFz** [zadam/trilium#1610]
Hello zadam.

Would you be able to change the license to a less restrictive one, for the next version? The AGPL is quite problematic because:

- The License might affect products on productive Systems
and potentially enforces the commercialized products to be licensed under the AGPL as well. Which is a unacceptable risk within Networks where there could be an Interaction with closed source products.

see: AGPL 3.0 -en 6d)

As the other libraries, used within Trilium-Notes, are licensed under MIT, I recommend to use a similar permissive license, for instance, such as the MIT / GPL instead of the AGPL.

With a restrictive license, such as the AGPL, many people cannot integrate your solution within a product.

That means, that if you have a server, that generates any type of income, then if the server contains an instance of an AGPL licensed software, all content of the server, must now be open-source for everyone.

Best regards and thanks a lot for your support.

**Comment by zadam** [comment]
Hi.

> With a restrictive license, such as the AGPL, many people cannot integrate your solution within a product.

I don't really think that Trilium is suitable for integration into other products. 

> That means, that if you have a server, that generates any type of income...

AGPL has nothing to do with income. Doesn't matter if it's commercial or not-for-profit, the license applies all the same.

> ... then if the server contains an instance of an AGPL licensed software, all content of the server, must now be open-source for everyone.

That's not true. License applies to Trilium, all other applications running on the same system are unaffected.

AGPL will affect you basically only if you 1) make code changes to Trilium itself which you want to keep for yourself and at the same time 2) want to resell/provide this modified Trilium to other people.

**Comment by zDEFz** [comment]
> > ... then if the server contains an instance of an AGPL licensed software, all content of the server, must now be open-source for everyone.
> 
> That's not true. License applies to Trilium, all other applications running on the same system are unaffected.
> 
> AGPL will affect you basically only if you 1) make code changes to Trilium itself which you want to keep for yourself and at the same time 2) want to resell/provide this modified Trilium to other people.

Hello again :)

the problem is that one could have the idea to cross a product with Trilium-Notes. That means that a product would integrate Trilium-Notes in any form, then the whole product had to be open-sourced, not just Trilium-Notes.
For that 'possibility' of an overlap, big companies usually forbid the usage of AGPL licensed software.
As far as I'm aware, even Google does. 

Nevertheless, would a big company still want to use an AGPL licensed software, single persons would be only allowed to use the software, under very strict, sealed off environments.

That is a big effort, and would rule out the usage for the broad amount of people, which isn't really what open-source software is meant for, in my opinion.

**Comment by zDEFz** [comment]
https://opensource.google/docs/using/agpl-policy/#:~:text=WARNING%3A%20Code%20licensed%20under%20the,NOT%20be%20used%20at%20Google.&text=Even%20if%20you%20think%20you,risks%20heavily%20outweigh%20the%20benefits.

**Comment by zadam** [comment]
> That means that a product would integrate Trilium-Notes in any form, then the whole product had to be open-sourced, not just Trilium-Notes.

Yes, but I'm ok with that. Non-OSS probably means commercial software, if they want to resell Trilium then we might arrange some mutually beneficial dual licensing arrangement :-) (but realistically I don't see this happening)

> For that 'possibility' of an overlap, big companies usually forbid the usage of AGPL licensed software.

Careful with terms. No big company forbids **usage** of A/GPL licensed software - all of them use GPL licensed Linux in some form after all. What they forbid is to develop their products while linking to A/GPL licensed software.

Note that there isn't a big difference between GPL and AGPL in spirit. AGPL is just "GPL for web apps". Both target the same - users (customers) should be able to see and modify the source code.

> Nevertheless, would a big company still want to use an AGPL licensed software, single persons would be only allowed to use the software, under very strict, sealed off environments.

So e.g. if you work at google, you can download Trilium for your personal use no problem. Nobody cares because usage of such software has no implication on anything else. What they would forbid is to e.g. base their next generation of Google Keep on Trilium because then Keep would need to be AGPL licensed as well. But again, such restriction is OK for me.

> That is a big effort, and would rule out the usage for the broad amount of people, which isn't really what open-source software is meant for, in my opinion.

As explained above, nobody is limited in the usage of Trilium.

**Comment by zDEFz** [comment]
>So e.g. if you work at google, you can download Trilium for your personal use no problem. Nobody cares because usage of such software has no implication on anything else. What they would forbid is to e.g. base their next generation of Google Keep on Trilium because then Keep would need to be AGPL licensed as well. But again, such restriction is OK for me.

"Personal usage" is a broad term. If by that is meant - the working machines, then no, I cannot use Trilium-Notes on those.
Personally, I have opened this ticket, because I cannot use your software also at work, due to the AGPL license.
Really - the only way you can use the software nonetheless, is by getting an exception - where you would only be capable to use the software in a sealed-off environment.

**Comment by zadam** [comment]
It turns out you're right. The problem however seems to lie in Google's paranoia rather than in AGPL itself.

**Comment by zDEFz** [comment]
> It turns out you're right. The problem however seems to lie in Google's paranoia rather than in AGPL itself.

I'm not working at google ^. I think it isn't only applicable to google. I really want to use your software, because I'm not feeling positive towards other products available. To be honest, I also had not found an alternative.
I am disabled Trilium-Notes would help me a lot.

**Comment by zadam** [comment]
I've worked at a couple of large corporations and plenty of them were very weary of linking against A/GPL code, but none of them forbid usage of AGPL licensed software since it does not affect anything. So I'd say google is rather the exception than a norm.

If not, then I would just ignore it and install anyway. Nobody will know and if by chance they will find out just claim ignorance.

**Comment by zDEFz** [comment]
> I've worked at a couple of large corporations and plenty of them were very weary of linking against A/GPL code, but none of them forbid usage of AGPL licensed software since it does not affect anything. So I'd say google is rather the exception than a norm.
> 
> If not, then I would just ignore it and install anyway. Nobody will know and if by chance they will find out just claim ignorance.

I would not feel good about that.
I'd rather then get an 'exception', which is quite a bit of bureaucracy.
That means, the usage would be very restrictive and special rules have to be followed.

**Comment by zadam** [comment]
No, I'm not.
