### ISSUE TITLE
[bug] Frontend is getting stuck after continous toggleNoteInParent calls

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#1611]
**Version**
Latest 0.45.8

**Reproduction Steps**

1. Create two parent notes A and B
2. Create note C as child of A
3. Clone C to child of B
4. Create frontend code note D, insert the following code:
```js
api.addButtonToToolbar({
    title: 'Exec',
    action: async function() {
        await api.runOnBackend(() => {
            api.toggleNoteInParent(false, "[noteId of C]", "[noteId of A]");
            api.toggleNoteInParent(true, "[noteId of C]", "[noteId of A]", "prefix");
        });
    }
});
```
Replace [] with corresponding note ID
5. Execute note D, you should see a button called "Exec" in the toolbar
6. Activate note C which is the child of **note A** in the note tree (make it shown in the right panel)
7. Press the button "Exec"

**Expected Bahavior**
Prefix of note C changed.

**Actual Behavior**
Prefix of note C changed, but frontend got stuck and was automatically reloaded after a short period of time.

The backend log is as follows:
```
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://xxx/app-dist/desktop.js:1:74748)
    at http://xxx/app-dist/desktop.js:1:77834
    at WebSocket.$ (http://xxx/app-dist/desktop.js:1:81198), reloading frontend.
Stack: Error
    at w (http://xxx/app-dist/desktop.js:1:77260)
    at http://xxx/app-dist/desktop.js:1:80582
```
The Dev Console is as follows:
```
Uncaught (in promise) recursion
Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://xxx/app-dist/desktop.js:1:74748)
    at http://xxx/app-dist/desktop.js:1:77834
    at WebSocket.$ (http://xxx/app-dist/desktop.js:1:81198), reloading frontend.
```
You may need to check "Preserve log" in the Dev Console to see the entire frontend log.

**Comment by zadam** [comment]
Hello, thank you for reporting this bug.

I tested this on 0.45 and managed to reproduce this issue, however it does not look obvious where's the issue.

master (future 0.46) has rewritten large part of the tree handling and there I could not reproduce the issue and it seems to work correctly. Since first 0.46 beta is coming soon, I'm not sure if it makes sense to invest time in tracking down this bug in the old 0.45 line ...

**Comment by WPum** [comment]
Then I'll test it in the 0.46 release. Thanks for your great work!

**Comment by WPum** [comment]
BTW I wonder if there's another way to change a note's prefix since this method could actually delete the note when there's only one clone.

**Comment by zadam** [comment]
Sure:

```
const branch = note.getBranches()[0];
branch.prefix = 'whatever';
branch.save();
```

**Comment by jobidon** [comment]
Not sure if this is related to the previous issue, but I get the same error message:
`JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:15), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)`
I am running 0.49.2-beta
If that helps, I seem to be getting this error whenever I am creating a new note, whether by script or through the UI, anywhere in the tree.

**Comment by zadam** [comment]
@jobidon this is actually a symptom of a different error which should be in the console before it. Could you take a look and share the original error?

**Comment by jobidon** [comment]
I've captured a few instances of that error, not sure if it help.

`Slow 204 PUT /api/notes/gVynCWaL1WYi/attributes with 0 bytes took 32ms
304 GET /api/notes/c26aGnFJVju8/backlink-count with 11 bytes took 1ms
304 GET /api/notes/c26aGnFJVju8 with 428 bytes took 2ms
204 PUT /api/options with 0 bytes took 1ms
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at async WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:9), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at async WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:9), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
200 GET /api/notes/WJXm3JnweAhN/backlink-count with 13 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
200 GET /api/notes/WJXm3JnweAhN with 5715 bytes took 0ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 5ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 3ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 6ms
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Slow 200 POST /api/script/exec with 76 bytes took 9317ms
200 POST /api/tree/load with 10960 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
200 GET /api/notes/4AT25R1Y8lYB/backlink-count with 11 bytes took 1ms
200 GET /api/notes/4AT25R1Y8lYB with 435 bytes took 1ms
200 PUT /api/notes/4AT25R1Y8lYB/change-title with 288 bytes took 6ms
200 GET /api/notes/4AT25R1Y8lYB with 426 bytes took 2ms
200 PUT /api/notes/4AT25R1Y8lYB/change-title with 291 bytes took 5ms
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
BBBB undefined
Script "attribute changed" (WJXm3JnweAhN): Removing note from parent Id #MnUFmDbUmQgt
Sending message to all clients: {"type":"taskProgressCount","progressCount":0}
Slow 200 PUT /api/notes/4AT25R1Y8lYB/attribute with 30 bytes took 4073ms
Slow 200 POST /api/search-related with 24 bytes took 39ms
304 GET /api/attributes/names/?type=label&query=myLabel with 2 bytes took 2ms
304 GET /api/attributes/names/?type=label&query=repeat with 10 bytes took 2ms
Slow 200 POST /api/search-related with 24 bytes took 22ms
Slow 200 POST /api/search-related with 24 bytes took 25ms
304 GET /api/attributes/names/?type=label&query=r with 1086 bytes took 5ms
304 GET /api/attributes/names/?type=label&query=re with 444 bytes took 3ms
304 GET /api/attributes/names/?type=label&query=rep with 10 bytes took 5ms
Slow 200 POST /api/search-related with 24 bytes took 20ms
304 GET /api/attributes/values/repeat with 16 bytes took 2ms
Slow 200 POST /api/search-related with 1368 bytes took 23ms
Slow 200 POST /api/search-related with 1368 bytes took 20ms
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:15), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
BBBB Branch {
  branchId: 'W4vTlcecZ942',
  noteId: '4AT25R1Y8lYB',
  parentNoteId: 'yMhCRs9bd0YT',
  prefix: undefined,
  notePosition: 30,
  isExpanded: false,
  utcDateModified: '2022-01-11 03:04:47.681Z'
}
Script "attribute changed" (WJXm3JnweAhN): Removing note from parent Id #yMhCRs9bd0YT

....

Slow 204 PUT /api/notes/4AT25R1Y8lYB/attributes with 0 bytes took 75234ms
Erased notes: ["TolTRG0ppyzi","o0acDr7L85lR","tpDoUu590E5E","vZPcUFTOGHDL","BpjYybBlSNDY","TuYEKpplm3uW","AylbS9twgEBQ","XyK6RCwnZepZ","3SKJT3SqOBhY","X9tF5tSlOBm2","6NnexbEsX0jk","aCkdGgONd5ay","OeWspxkmzAPV","hxXZvNnf53mg"]
JS Error: Error when calling PUT notes/4AT25R1Y8lYB/attributes: timeout - timeout
Stack: logError@http://10.0.1.10:8080/app/services/ws.js:23:20
throwError@http://10.0.1.10:8080/app/services/toast.js:87:8
reportError@http://10.0.1.10:8080/app/services/server.js:106:18
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at async WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:9), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
200 GET /api/notes/c26aGnFJVju8/backlink-count with 11 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
304 GET /api/notes/c26aGnFJVju8 with 428 bytes took 0ms
200 GET /api/notes/WJXm3JnweAhN with 5729 bytes took 1ms
304 GET /api/notes/WJXm3JnweAhN/backlink-count with 13 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 2ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 3ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 6ms
Slow 200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 24ms
Slow 200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 10ms
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:15), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 2ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 3ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 2ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 5ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 2ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 6ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 4ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 7ms
200 PUT /api/notes/WJXm3JnweAhN with 92 bytes took 9ms
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Slow 200 POST /api/script/exec with 76 bytes took 10522ms
200 POST /api/tree/load with 10960 bytes took 2ms
200 GET /api/notes/QIIdAWwN1cRg/backlink-count with 11 bytes took 1ms
200 GET /api/notes/QIIdAWwN1cRg with 435 bytes took 1ms
204 PUT /api/options with 0 bytes took 1ms
200 PUT /api/notes/QIIdAWwN1cRg/change-title with 288 bytes took 7ms
200 GET /api/notes/QIIdAWwN1cRg with 426 bytes took 1ms
200 PUT /api/notes/QIIdAWwN1cRg/change-title with 291 bytes took 4ms
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
BBBB undefined
Script "attribute changed" (WJXm3JnweAhN): Removing note from parent Id #MnUFmDbUmQgt
Sending message to all clients: {"type":"taskProgressCount","progressCount":0}
Slow 200 PUT /api/notes/QIIdAWwN1cRg/attribute with 30 bytes took 2412ms
Slow 200 POST /api/search-related with 24 bytes took 33ms
304 GET /api/attributes/names/?type=label&query=myLabel with 2 bytes took 3ms
304 GET /api/attributes/names/?type=label&query=repeat with 10 bytes took 2ms
Slow 200 POST /api/search-related with 24 bytes took 21ms
Slow 200 POST /api/search-related with 24 bytes took 26ms
304 GET /api/attributes/names/?type=label&query=r with 1086 bytes took 5ms
304 GET /api/attributes/names/?type=label&query=re with 444 bytes took 5ms
304 GET /api/attributes/names/?type=label&query=rep with 10 bytes took 6ms
Slow 200 POST /api/search-related with 24 bytes took 28ms
Slow 200 POST /api/search-related with 1368 bytes took 22ms
304 GET /api/attributes/values/repeat with 16 bytes took 1ms
Slow 200 POST /api/search-related with 1368 bytes took 23ms
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
Script "attribute changed" (WJXm3JnweAhN): today [2022-01-10] < dueDate [2022-01-12]
Slow 204 PUT /api/notes/QIIdAWwN1cRg/attributes with 0 bytes took 10940ms
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:15), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
Slow 200 POST /api/search-related with 1552 bytes took 29ms
200 GET /api/notes/QIIdAWwN1cRg with 429 bytes took 1ms
304 GET /api/notes/c26aGnFJVju8/backlink-count with 11 bytes took 1ms
304 GET /api/notes/c26aGnFJVju8 with 428 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
200 POST /api/delete-notes-preview with 60 bytes took 3ms
Sending message to all clients: {"type":"taskProgressCount","taskId":"KDEgMi5rvK","taskType":"delete-notes","progressCount":0}
Deleting note c26aGnFJVju8

...

Slow 200 DELETE /api/branches/mBmhvPzBUr5N?taskId=2wzTzLspBs&eraseNotes=false&last=true with 20 bytes took 23ms
200 POST /api/tree/load with 42 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
Slow 304 GET /api/search/%23workspace with 2 bytes took 15ms
200 GET /api/notes/32TqfmlPlgZe/backlink-count with 11 bytes took 1ms
200 GET /api/notes/32TqfmlPlgZe with 465 bytes took 2ms
200 GET /api/autocomplete?query=&activeNoteId=32TqfmlPlgZe with 11312 bytes took 7ms
200 GET /api/autocomplete?query=&activeNoteId=32TqfmlPlgZe with 11312 bytes took 6ms
204 PUT /api/options with 0 bytes took 2ms
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at async WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:9), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
200 GET /api/notes/yMhCRs9bd0YT/backlink-count with 11 bytes took 2ms
204 PUT /api/options with 0 bytes took 1ms
200 GET /api/notes/yMhCRs9bd0YT with 439 bytes took 1ms
304 GET /api/notes/32TqfmlPlgZe with 465 bytes took 2ms
304 GET /api/notes/32TqfmlPlgZe/backlink-count with 11 bytes took 2ms
304 GET /api/notes/32TqfmlPlgZe with 465 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task is NOT completed
200 PUT /api/notes/32TqfmlPlgZe/attribute with 30 bytes took 4ms
200 PUT /api/notes/32TqfmlPlgZe with 92 bytes took 3ms
200 PUT /api/notes/32TqfmlPlgZe with 92 bytes took 3ms
200 PUT /api/notes/32TqfmlPlgZe with 92 bytes took 5ms
JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (http://localhost:8080/app/services/utils.js:313:19)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:165:25)
    at executeFrontendUpdate (http://localhost:8080/app/services/ws.js:89:35)
    at async WebSocket.handleMessage (http://localhost:8080/app/services/ws.js:113:9), reloading frontend.
Stack: Error
    at logError (http://localhost:8080/app/services/ws.js:23:20)
    at consumeFrontendUpdateData (http://localhost:8080/app/services/ws.js:168:13)
200 PUT /api/notes/32TqfmlPlgZe with 92 bytes took 5ms
200 PUT /api/notes/32TqfmlPlgZe with 92 bytes took 2ms
Script "attribute changed" (WJXm3JnweAhN): Detected an attribute change in a task note...
Script "attribute changed" (WJXm3JnweAhN): task was just completed
Script "attribute changed" (WJXm3JnweAhN): Current branch position is #0
ERROR: Execution of script "attribute changed" (WJXm3JnweAhN) failed with error: Load of script note "attribute changed" (WJXm3JnweAhN) failed with: newNote is not defined
Slow 200 PUT /api/notes/32TqfmlPlgZe/attribute with 30 bytes took 11ms
200 GET /api/notes/32TqfmlPlgZe with 495 bytes took 0ms
BBBB undefined
`

**Comment by zadam** [comment]
Hi, sorry, what I meant was log in the browser console/electron window. You can open it with `CTRL-SHIFT-I` and there should be some errors preceding this "Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000".

**Comment by jobidon** [comment]
Sorry for the confusion. There isn't a whole lot going on in the frontend, except for this:
`
Unhandled command focusOnDetail, converting to event.
`
This seems to be triggered about 30 sec before the error pops up in the backend
This occurred when using a FF browser
