### ISSUE TITLE
Adding new line in note results in loss of cursor/ability to input without repositioning cursor

### ISSUE THREAD

**Issue by Waxwood** [zadam/trilium#1626]
Hi 
I have been using release  all day and found a problem.
When adding a new line in a note by pressing RETURN, only one hard return appears and the cursor disappears from the current window. I must first reposition the cursor to the exact location at which I want to add text. 

Version: 0.45.9
OS: Manjaro Linux
Log is attached
[trilium-2021-02-08.log](https://github.com/zadam/trilium/files/5947748/trilium-2021-02-08.log)

Had anyone else had this problem?

**Comment by zadam** [comment]
Hi, I can't reproduce this. It would be helpful if you could record screencast showing this behavior ...

**Comment by Waxwood** [comment]
Today I can't replicate it either. Yesterday, I unzipped 0.45.9 into the trilium directory in /home and ran it. It misbehaved like that all day. Today, after a reboot, its functioning perfectly.
