### ISSUE TITLE
Use system electron

### ISSUE THREAD

**Issue by Dialga** [zadam/trilium#1627]
Can you provide a build which uses the installed version of electron rather than bundling it with trilium?
That would slim down the installed size immensely.

**Comment by zadam** [comment]
Is there such a thing as "system electron"? I've never seen it yet ...

**Comment by Dialga** [comment]
For example on Arch Linux there is an electron package in the repository which other packages can depend on rather than bundling their own version of electron.

**Comment by zDEFz** [comment]
No update on this?

**Comment by zadam** [comment]
This is not planned so I guess it's better to close this.

**Comment by Dialga** [comment]
That's really unfortunate, you could offer a slimmed down build of trilium that uses the existing electron package installed rather than bundling another one.
