### ISSUE TITLE
Cannot setup server sync on 0.45.9 - Windows Build, Docker server

### ISSUE THREAD

**Issue by Potjoe-97** [zadam/trilium#1629]
Hi, I'm having an issue configuring my new W10 laptop with the docker server. Both are using latest 0.45.9, and I have another desktop, also in 0.45.9, which was previously synced and still working. 

During the setup wizard, I type the address and credentials (which are correct, for sure) and I'm having the following error : `Sync setup failed: Request to get http://trilium.home:8080/api/setup/sync-seed failed, error: 401 Unauthorized`
 I tried to setup the sync with then android app (I don't have any other machine to test it) with no issue. 

Here are the logs : 
```
21:40:38.977 DB not initialized, please visit setup page
21:40:38.978 DB size: 4 KB
21:40:39.263 Generated session secret
21:40:41.409 App HTTP server starting up at port 37840
21:40:41.409 {
  "appVersion": "0.45.9",
  "dbVersion": 170,
  "syncVersion": 16,
  "buildDate": "2021-02-05T21:38:32+01:00",
  "buildRevision": "9d7d79ef94bc7734393ae7f89993e76bbc7d97e3",
  "dataDirectory": "C:\\Users\\giann\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0"
}
21:40:41.410 CPU model: Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz, logical cores: 4 freq: 1696 Mhz
21:40:41.448 Listening on port 37840
21:40:44.754 Slow GET /setup took 29ms
21:40:51.666 GET /setup took 4ms
21:41:15.744 GET /api/clipper/handshake took 2ms
21:42:15.753 GET /api/clipper/handshake took 2ms
21:43:15.725 GET /api/clipper/handshake took 2ms
21:43:36.331 Getting document options FROM sync server.
21:43:36.335 POST /api/setup/sync-from-server took 5ms
21:43:36.351 ERROR: Sync failed: Request to get http://trilium.home:8080/api/setup/sync-seed failed, error: 401 Unauthorized
21:43:36.355 ERROR: Failed to deserialize sync response: Incorrect username and/or password
21:44:15.719 GET /api/clipper/handshake took 1ms
21:45:15.722 GET /api/clipper/handshake took 1ms
21:46:02.968 Getting document options FROM sync server.
21:46:02.969 POST /api/setup/sync-from-server took 1ms
21:46:02.986 ERROR: Sync failed: Request to get http://trilium.home:8080/api/setup/sync-seed failed, error: 401 Unauthorized
21:46:02.988 ERROR: Failed to deserialize sync response: Incorrect username and/or password
21:46:15.715 GET /api/clipper/handshake took 2ms
21:47:15.738 GET /api/clipper/handshake took 2ms
21:48:15.735 GET /api/clipper/handshake took 2ms
21:49:15.727 GET /api/clipper/handshake took 1ms
21:50:15.728 GET /api/clipper/handshake took 1ms
21:51:15.721 GET /api/clipper/handshake took 1ms

```
I know logs seems to be pointing to bad credentials, but I'm sure of them... I can log in and log out from the web instance without any issue. 

Thanks for your help

**Comment by Potjoe-97** [comment]
Quick update: minor updates seems to have broken sync configuration. My desktop with functionning sync is still running version 16, as my docker server is. I guess the solution is then to recreate a server and to import the db back. Is there a prefered and clean way to do it ? And, generally speaking, how to handle incremental updates to avoid breaking sync again in the future ?

**Comment by zadam** [comment]
Hi, I think I know where's the problem and it affects the 0.45.9 of Docker image. I think downgrade of Docker image to 0.45.8 should help. No data migration or anything like that should be needed.

**Comment by Potjoe-97** [comment]
Confirmed, rollback to 0.45.8 allowed to configure server sync. Thank you! I hope it won't be too much of a hassle to tacckle.
