### ISSUE TITLE
 TypeError: Cannot read property 'syncServerHost' of undefined

### ISSUE THREAD

**Issue by p-rintz** [zadam/trilium#163]
In the docker install, the error message 

> TypeError: Cannot read property 'syncServerHost' of undefined
>     at get (/usr/src/app/src/services/sync_options.js:14:26)
>     at Object.isSyncSetup (/usr/src/app/src/services/sync_options.js:19:38)
>     at updatePushStats (/usr/src/app/src/services/sync.js:306:27)
>     at /usr/src/app/node_modules/cls-hooked/context.js:118:13
>     at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:)
>     at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
>     at init (/usr/src/app/src/services/cls.js:5:28)
>     at Timeout._onTimeout (/usr/src/app/src/services/cls.js:9:30)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)

will continously be printed into the error log. Sync is not set to anything, since its a server instance anyway.

Im running trilium on a docker swarm instance with the following stack config:

> version: "3.4"
> 
> networks:
>   traefikproxy:
>     external: true
>     
> volumes:
>   notes:
>     driver: wetopi/rbd
>     driver_opts:
>       size: 512
> 
> services:
>   server:
>     image: zadam/trilium:latest
>     restart: always
>     networks:
>       - traefikproxy
>     volumes:
>       - notes:/root/trilium-data
>     deploy:
>       mode: replicated
>       replicas: 1
>       placement:
>         constraints: 
>           - node.role == worker
>       labels:
>         - "traefik.enable=true"
>         - "traefik.backend.loadbalancer.stickiness=true"
>         - "traefik.backend.loadbalancer.swarm=true"
>         - "traefik.backend=notes"
>         - "traefik.docker.network=traefikproxy"
>         - "traefik.entrypoints=https"
>         - "traefik.frontend.passHostHeader=true"
>         - "traefik.frontend.rule=Host:trilium.example.com"
>         - "traefik.port=8080"

Everything works, but the error log will be flooded with the above message.

**Comment by zadam** [comment]
Oh, sorry about that. This bug has been already fixed, but docker images for the latest release was not yet released because of some global npm issues.

**Comment by zadam** [comment]
npm works now, so I was able to build and push up to date docker image for 0.20.2
