### ISSUE TITLE
Sync fails for unknown reason

### ISSUE THREAD

**Issue by koutto** [zadam/trilium#1632]
Hey,
- I have several notes on my machine using the Desktop client offline. (document.db is about 90 MB).
- I am running latest version of Desktop client (0.45.9), on Windows.
- I have set up Server using Docker, latest version also (0.45.9).
- I went to http://myserver:8080/, selected the option saying "I have desktop..."
- Configured sync options accordingly in my Desktop client, Sync is reported as working correctly when clicking on "Test Sync".
- But then I see it is not syncing, I got these error messages :
```
00:17:53.619 GET /api/backend-log took 1ms
00:17:54.134 sync failed: Process exceeded time limit 100000
stack: Error: Process exceeded time limit 100000
    at Object.timeLimit (C:\Users\koutto\Tools\trilium-windows-x64\resources\app.asar\src\services\utils.js:249:19)
    at syncRequest (C:\Users\koutto\Tools\trilium-windows-x64\resources\app.asar\src\services\sync.js:268:24)
    at pushChanges (C:\Users\koutto\Tools\trilium-windows-x64\resources\app.asar\src\services\sync.js:208:15)
    at C:\Users\33689\Tools\trilium-windows-x64\resources\app.asar\src\services\sync.js:37:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.doExclusively (C:\Users\koutto\Tools\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async Object.sync (C:\Users\koutto\Tools\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
00:17:57.109 Slow query took 42ms: SELECT * FROM note_contents WHERE noteId = ?
00:17:59.377 GET /api/backend-log took 1ms
```
- After, I increased timeout value in settings, to 500000. But I got these new error messages:
```
00:29:10.340 sync failed: Request to PUT http://myserver:8080/api/sync/update failed, error: Error: net::ERR_CONNECTION_RESET
stack: Error: Request to PUT http://myserver:8080/api/sync/update failed, error: Error: net::ERR_CONNECTION_RESET
    at generateError (C:\Users\koutto\Tools\trilium-windows-x64\resources\app.asar\src\services\request.js:174:12)
    at ClientRequest.<anonymous> (C:\Users\koutto\Tools\trilium-windows-x64\resources\app.asar\src\services\request.js:49:47)
    at ClientRequest.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
00:29:10.593 Slow query took 41ms: SELECT * FROM note_contents WHERE noteId = ?
```

- Note that I am connected on http://myserver:8080 at the same time, and there is no connection issue !

Do you have any idea of the cause of the problem ?

**Comment by zadam** [comment]
Hi, docker image for 0.45.9 is broken, please use 0.45.10. (other builds were not affected and don't need upgrade from 0.45.9).

**Comment by koutto** [comment]
Hi, thanks for the quick reply.
I updated both client and server to 0.45.10.
Then did the same procedure as before.
And I still got exactly the same issues / same error messages.

Note that I was using offline version without any trouble so far.

**Comment by zDEFz** [comment]
> Hi, docker image for 0.45.9 is broken, please use 0.45.10. (other builds were not affected and don't need upgrade from 0.45.9).

Hi Zadam. Running docker image 0.45.9 without any issue. What exactly does 0.45.10 fix? Should I upgrade?

**Comment by zadam** [comment]
0.45.9 has broken sync with desktop clients. If you don't use sync then it can work fine for you.

**Comment by zDEFz** [comment]
> Docker image v0.45.9 has broken sync with desktop clients. If you don't use sync then it can work fine for you.

Haven't had Desktop Sync with 0.45.9, but can say the sync is not robust, and should prevent more edge cases from happening.

But it's still interesting, that we didn't get a readout of the actual problem. 
Can you implement a routine that checks if the files are eligible for commit to the server first, and warn if it's a big database? 

Recently, however, I run a test-unit on the version 0.45.9, and I could import a zip with a lot of japanese characters no problem.

**Comment by koutto** [comment]
Well, I have made a try with the server packaged version too, adjusted some parameters like timeout value.
But I keep getting the same errors.
I will stick to the offline version for now, sync seems not be working well, will give it a try later.
