### ISSUE TITLE
[BUG] invalid `<small>` tags on algolia-autocomplete (Jump to note)

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1635]
# Overview

Hi,
While improving my theme i came to the `Jump to note` functionality, and i found out that the `<small>` tags (used for note labels) are not properly generated:
```html
        <div class="aa-suggestion" role="option" id="option-47315226">Tasks / Recurring Tasks 
          <small< small="" style="white-space: normal;">
            ~runonattrib<b>ut</b>echange=…
          </small<>
        </div>
```

For me it means i can't change CSS style for
```css
.algolia-autocomplete .aa-suggestion small
```
For trilium it's a bug, event if chrome renders it properly due to invalid tag correction.

# Steps to reproduce
1. set timeout breakpoint on developer tools console: `setTimeout(function(){debugger;}, 5000)`
2. press Ctrl+J to open `Jump to Note` modal window.
3. start typing something on search bar.
4. wait for breakpoint to be set.
5. inspect elements.

# Possible bug location:
I suck at JS but the following code might be related to the issue:
https://github.com/zadam/trilium/blob/6068bd7c44789511d8369a19582136056739ba62/src/services/search/services/search.js#L224-L230

**Comment by zadam** [comment]
Hi, good catch. Should be fixed now, although in a hacky way.
