### ISSUE TITLE
Extremely Resource Hungry?

### ISSUE THREAD

**Issue by Nachtfeuer** [zadam/trilium#1636]
Hi Trilium Team,

Using https://github.com/zadam/trilium/releases/tag/v0.45.10
I experiences following issues:

 - the start of the application took extremely long. I see setup in the title and a window that remains white for a very long time
 - After I was able to enter my name and password again it took a while and then I was able to navigate and edit some some stuff
 - Now leaving the application the computer simply didn't react anymore. Total freeze. After a few minutes I forced my Computer to shutdown pressing a few seconds the "off button".

For a "note taking" (even with a lot of features) application absolutely not acceptable.
It behaves much worse than any high resolution game with several GB loading into memory.

I have a Dell Laptop with i7-6700HQ CPU @ 2.60GHz with 16GB RAM (Inspiron 7559) and Windows 10 Home.

Kind Regards,
Thomas

**Appendix**:

That's all in the logs:

```
10:28:55.288 DB not initialized, please visit setup page
10:28:55.289 DB size: 4 KB
10:28:55.458 Generated session secret
10:29:04.726 App HTTP server starting up at port 37840
10:29:04.726 {
  "appVersion": "0.45.10",
  "dbVersion": 170,
  "syncVersion": 16,
  "buildDate": "2021-02-11T23:05:48+01:00",
  "buildRevision": "5b679930de787efc2f70dfe7961cd1677ec2fa0f",
  "dataDirectory": "C:\\Users\\Thomas Lehmann\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0"
}
10:29:04.728 CPU model: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, logical cores: 8 freq: 2592 Mhz
10:29:04.753 Listening on port 37840
```

**Comment by zadam** [comment]
Hi, your experience is not typical so there is probably some issue.

Could you check the logs again? There should be definitely more, it's possible you took a look before log cache was flushed perhaps? Log could give some hints what went wrong.

But I'm also wondering if there could be something else at play - Trilium on its own should not crash the computer, that's what is OS for after all.
