### ISSUE TITLE
[REGRESSION:v0.46.0-beta] Dynamic attribute promotion not reflected in the UI

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1646]
Hi !
I've just started using `v0.46.0-beta` and i'm testing it.

First thing i found is a regression with a custom shortcut i heavily use:
```js
api.bindGlobalShortcut('alt+p',
    async function () {
        const noteId = api.getActiveTabNote().noteId;
    
        // BACKEND
        await api.runOnServer(async noteId => {
            const note = await api.getNote(noteId);
            const has_label = await note.hasLabel("label:cssClass");
            await note.toggleLabel(!has_label, "label:cssClass", "promoted,multi,text");
        }, [noteId]);
    });
```

With this shortcut, i could easily `promote` cssClass attribute, which i use for tagging.
Until v0.45.*, toggling attribute promotion with `alt+p` used to immediately show/hide promoted attribute.
Now i need to entierly refresh trilium with `f5` in order for the promoted attribute to show up.

A possible fix would be to always have `<div class="section-title section-title-real">` loaded for promoted attributes (even if it shows `Promoted attrs (0)`, maybe unsetting its visibility while there is no content.

Thank you !

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
