### ISSUE TITLE
[BUG] relation map GUI: prevent invalid chars from `add relation` prompt

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1649]
When creating a relation between 2 notes from `relation map` GUI, spaces and any char are allowed in relation name, resulting to bugs & possible weird behavior.

# Steps to reproduce
* create a relation map
* add `son` note
* add `mother` note
* create `parent #of` (with space and `#`) relation from `mother` to `son`
```
Error when calling PUT /api/notes/5KhGRahRlfOG/relations/child #of/to/aYkjAAPoZlwv: 404 - [object Object]
```

# Fix suggestion
prevent insertion of spaces, `#`, `~`, and any char that's not within allowed attribute name charset in `Specify new relation name` prompt.

# Comment
I've purposely set a weird & unlikely relation name `parent #of` to showcase, but note it would be very likely for any non technical user to set some relation name containing a space (e.g: `parent of`).
So i think this is worth fixing.

**Comment by zadam** [comment]
Yeah, that makes sense. Originally attribute name was allowed to be any string, but this was recently made more strict.
