### ISSUE TITLE
Investigate moving trilium-data directory into .local

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#165]

**Comment by JordyScript** [comment]
I believe in Windows the expected/conventional location would be the Roaming folder.

This link explains it very briefly. https://www.thewindowsclub.com/local-localnow-roaming-folders-windows-10

Linux probably has a similar convention. What do you think?

**Comment by zadam** [comment]
I think that it will be the best to use platform specific directories (.local for Linux, Roaming for Windows) if they exist with fallback to the old location ~/trilium-data That way there shouldn't be any migration issues.

**Comment by zadam** [comment]
Fixed in https://github.com/zadam/trilium/commit/8cbb29ee251c432f437f3afe620e0a7d27ca0cc3

**Comment by StoltHD** [comment]
Data directories should be 100% configurable, i.e. It should be asked for first time an application starts...

On windows you could as a solution use the "start in" for a short cut...

But to force a user to have their data on the system disk are not good practice, even though Microsoft have a habit to do so...

As a minimum, you should use the document folders, either private or shared on windows..

The roaming folder should be only for configuration/app data, not user data.

**Comment by zadam** [comment]
User is not "forced" to use the default location, by setting `TRILIUM_DATA_DIR`, you can set any directory for storage.

Documents doesn't seem to be a good choice because trilium data files are not something you can directly open or access without trilium app. Roaming seems to match well for what we use it for.

**Comment by StoltHD** [comment]
I think you have misunderstud the term "documents", a document can be anything holding users data... An Access database, a sqlite database, a xlm document/database, a text file, an image, a word document, an excel spreadsheet, a mp3 music file, a movie file, all of them are Documents.
Any digital file containing an users data is a document in the world of archives and storage.
Files that should be easily backed up, should also be easily found...
Therefore, best practice an windows is to provide the user with a dialog to choose the path for where the user data will be stored..
________________________________
