### ISSUE TITLE
[REGRESSION:v0.46.0-beta] No more `add new child note` in `link note` & `include note`

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1653]
One of the features i most use in trilium, i ability to create a child nte on the fly within text editor.
Previously, they were 3 ways of quickly link to a note (or create a new one):
* type '@', and next word searches/creates a note
* `Internal Trilium link` (Ctrl+L) feature
* `Include note` feature

Since v0.46.0-beta, only the `@` autocompletion offers possibility to create a child note and link to it.
The top-most option to create a child note and link to it has been lost in other note inclusion systems.

This feature was a real game changer in easy note creation & linking, so i hope it will go back :)

Thank you

**Comment by zadam** [comment]
Hi, I removed this option from places where I thought it does not really make sense (e.g. now "ancestor" in search), but I was probably overeager and now I returned it back for a couple of cases.
