### ISSUE TITLE
[FEATURE REQUEST] Implement `note.linkCount` note property

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1658]
Hi ! It would be useful to be able to search notes by how many link they have (how many results are returnes by the `what links here` widget)

**Comment by zadam** [comment]
Added as "targetRelationCount" to be consistent with existing APIs.

**Comment by nil0x42** [comment]
Hi ! After watching your commit, it looks like is still have some limitations.
I don't know if it is easy to implement, but if you can implement something like `targetRelationCountIncludingLinks` it would also take into account `imageLink`, etc.. right ?

In my case i was trying to list `all orphan images` (e.g: images that are note included by at least 1 text note).
So i tried this search `note.targetRelationCount=0 note.type = image`, but it looks like it ignores `imageLink`

**Comment by zadam** [comment]
Yes, actually there is already `targetRelationCountIncludingLinks` in 0.46.1-beta, you inferred the naming correctly :-)
