### ISSUE TITLE
TypeError upon trying to run Trilium Server on Google Could Run

### ISSUE THREAD

**Issue by XrenynTheMage** [zadam/trilium#1663]
After pushing the zadam/trilium:0.45.8 and zadam/trilium Docker images to my Google Cloud Platform Container Registry, trying to run them in Google Cloud Run, and waiting a couple of seconds, the container exits with the following error message

```TypeError: Cannot read property 'length' of undefined at getRowOrNull (/usr/src/app/src/services/sql.js:83:16) at Object.getValue (/usr/src/app/src/services/sql.js:87:17) at Object.<anonymous> (/usr/src/app/src/services/sql_init.js:140:28) at Module._compile (internal/modules/cjs/loader.js:1015:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10) at Module.load (internal/modules/cjs/loader.js:879:32) at Function.Module._load (internal/modules/cjs/loader.js:724:14) at Module.require (internal/modules/cjs/loader.js:903:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.<anonymous> (/usr/src/app/src/services/notes.js:2:17)```

Sorry I have no idea how to access any of Trilium's internal logs using Cloud Run, so that's all the information I can give for now.

**Comment by zadam** [comment]
Hi, so 2 things come to my mind:

*   you could try the latest stable 0.45.10. There were some issues with built docker images in the past
*   do you have some mounted volume / writable space connected to the docker so that Trilium can write data there?

**Comment by XrenynTheMage** [comment]
I'm sorry that I still have no idea how Google Cloud Run actually works and that I can't investigate this issue any further. I recently canceled my billing account after I was charged a couple dozen € for what I can only imagine as the VM hosting the crashed Trilium instance idling away for a couple of months, now I can't figure out how to create a new temporary billing account that uses my Paypal as a payment method. I mean I could research how to do that, but honestly I'm too fed with the complexity of Google Cloud to even try. I figure it's going to be more fun to just buy a Raspberry Pi instead and host my private Trilium Notes Server on there.
