### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by TungstenOxide** [zadam/trilium#167]
On Arch Linux, after unpacking version 0.20.2, attempting to run it results in a segmentation fault.

**Comment by TungstenOxide** [comment]
After inspecting other versions, it seems that all of them result in segmentation fault.
`Segmentation fault (core dumped)`

Instructions to replicate:
On Arch Linux running KDE, download the Linux x64 package, extract it to a folder, open a terminal in that directory, and type ./trilium

Am I doing something wrong?

**Comment by zadam** [comment]
Hello, thanks for report. I think it's probably related to some glibc / toolchain issue: https://github.com/electron/electron/issues/13972
