### ISSUE TITLE
[BUG] Boolean promoted attributes are parsed as Strings

### ISSUE THREAD

**Issue by oxdc** [zadam/trilium#1670]
Version: 0.45.10

I added an attribute to a template note:
`#label:Finished=promoted,single,boolean`
and read it from the backend script:
```javascript
var note = api.originEntity.getNote();
var finished = note.getLabelValue('Finished');
api.log(typeof(finished));
```
It prints,
`Script "js" (**********): string`

It would be more intuitive to return a boolean value.

**Comment by zadam** [comment]
Label values are always strings and the typing (meaning) must be handled by the code.
