### ISSUE TITLE
[UX] chained copying inheritance only works BEFORE the tree creates

### ISSUE THREAD

**Issue by oxdc** [zadam/trilium#1671]
version: 0.45.10

As the size of the notebook expands, we'd like to add some utilities to it. Suppose we already have some daily notes WITHOUT any inheritable attributes:

- Calendar
  - 2021
    - 02 - February
      - 21 - Sunday
 
Now, if we add `#child:child:child:label=value`, intermediate notes such as `2021` would not inherit `#child:child:label=value`. It would be annoy to manually add all those attributes.

**Comment by zadam** [comment]
Yes, this is also design decision. `child:` is a "copy inheritance" and is triggered only when creating new notes.

However in 0.46 (currently in beta), it's pretty simple to mass assign an attribute to all notes in a subtree using the new Search (& Actions).
