### ISSUE TITLE
[BUG:v0.46.1-beta] `Edited notes on this day` freezes

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1672]
# Steps to reproduce:
* go to `today` onte, `notes edited on this day` appear correctly
* go to a day note where no notes were edited (e.g: some date in the future): now it shows `no edited notes on this day yes` (as expected)
* go back to `today`, or any other day in which notes were edited. now the widget is frozen to `no edited notes on this day yet` (unless we reload UI with `F5)

**Comment by zadam** [comment]
Hi, good catch, fixed.
