### ISSUE TITLE
[v0.46] Tree doesn't show more than 100 child notes

### ISSUE THREAD

**Issue by mabeyj** [zadam/trilium#1673]
When expanding a parent note that has more than 100 child notes, only the first 100 child notes are displayed in the tree. In v0.45, the tree would show all child notes.

Note: Refresh after adding child notes. I'm guessing a limit was introduced when the child notes are fetched from the server.

![tree-child-note-limit](https://user-images.githubusercontent.com/773401/108640844-55d44300-7472-11eb-9786-60cd7855925a.gif)

Version: 0.46.1-beta

**Comment by zadam** [comment]
Hi, yes, this was added recently, was basically necessary because "saved search" now allows to query all notes which could kill the app when you have tens of thousands of notes e.g.

Also the usability of tree gets lower with higher number of children ...

This limit could be raised to some higher (but still reasonable) number.

BTW, I'm curious what's your use case to have so many notes as children?

**Comment by mabeyj** [comment]
Hi zadam, my use case is tracking my video game collection (and some smaller collections like TV shows and movies). Right now, I have ~300 child notes, one per game, mostly consisting of personal notes, to-do lists, and such, possibly some grandchild notes. I use attributes to track things like completion status, system/platform, rating, purchase date, etc.

I was using a Notion database for this, but I migrated to Trilium since performance is significantly better and scripting support is very powerful. To get around the usability issues with browsing this many notes, I have some custom Render Notes that implement views similar to Notion databases (something I'll be sharing soon). Otherwise, I just use the tree for accessing grandchild notes and hoisting.

I could definitely get around this limit by organizing notes by series or genre instead of a flat structure. For reference, I didn't notice any performance issues with this large of a tree in v0.45 (local desktop install).

**Comment by zadam** [comment]
I removed this limitation for normal notes - 100 children limit is now enforced only on search note results (this was initially intended anyway).

**Comment by mabeyj** [comment]
@zadam Thanks for the change, but I'm still seeing this limit after upgrading to 0.46.2. Seems like this code needs to be updated as well:

https://github.com/zadam/trilium/blob/060d4fc27b29058d5bfaccbcaf10402ba1a18c06/src/public/app/widgets/note_tree.js#L598-L600

**Comment by zadam** [comment]
You're right, fixed. Thanks for the heads up.
