### ISSUE TITLE
[FEATURE] Filter out InternalLink on Relation Map note

### ISSUE THREAD

**Issue by Grymas** [zadam/trilium#1674]
(On Version 0.45.9)

The Relation Map is a cool idea, but the current way it works makes it kinda functionally useless to me.
Currently, trying to visualize the relation between notes that already have Hyperlinks between each other (generating Internal Links) on top of actual specified Relations automatically adds all those Internal Links to the map with no possibility of removing them from the Relation Map or disabling their display.

I understand the specific use of the Relation Map, but even in the basic example of having two notes representing two people being in the same family for example, they'd have a two-way Relation as "Family", maybe a one-way "Brother" and a one-way "Sister", but in my case the *text content* of the note also mentions the other note directly, saying something like "This person is a sibling of @Other Note" which also generates an InternalLink relation.

The result is a lot of redundant relations, or even unintended relations. If a note mentions another note with an InternalLink but I want to make a Relation Map only showing the Relation attributes I personally created (to represent particular relations that might be more precise), I can't.

Is there a current way of disabling the display of those Internal Links/Hyperlinks on the Relation Map, so I can only focus on manually declared relation attributes and not the auto-generated relations?
Beyond just filtering out InternalLink, is there a way to specify which Relations are displayed on a Relation Map note, so you could potentially make multiple Relation Map notes including the same notes but for different purposes (for example a Relation Map note showing the family/sibling relations between notes, and another more abstract Relation Map note showing relations like "is allied with", or "distrusts", etc..) without having the clutter of all the other relations?

**Comment by zadam** [comment]
Hi, you bring up good points.

I think it was originally intended that internal links will not be displayed - I fixed that.

I also added a possibility to specify a comma delimited list of displayed relations in `displayRelations` label.

**Comment by Grymas** [comment]
> Hi, you bring up good points.
> 
> I think it was originally intended that internal links will not be displayed - I fixed that.
> 
> I also added a possibility to specify a comma delimited list of displayed relations in `displayRelations` label.

Amazing! Exactly what I wanted, thank you.
