### ISSUE TITLE
0.46.1-beta Markdown now only partially WYSIWYG

### ISSUE THREAD

**Issue by hokutonanto** [zadam/trilium#1678]
Hi there,

I installed the latest beta, 0.46.1
I noticed that now when I type ### the number sign remains visible whereas in the previous versions it would hide automatically.
The text, instead, is formatted properly.

Has something changed or is this a bug?

**Comment by nil0x42** [comment]
Hi ! This is a feature recentrly implemented to make more clear what is an h2, h3, etc..
https://github.com/zadam/trilium/blob/08cba1e1ce5d711bcdb9036f8548e8371199aa9f/src/public/app/widgets/type_widgets/editable_text.js#L51-L60

If you want to disable it, you can override it with your custom CSS:
https://github.com/zadam/trilium/wiki/Themes#custom-css

You can disable it with some CSS rule like that:
```css
.note-detail-editable-text h2::before,
.note-detail-editable-text h3::before,
.note-detail-editable-text h4::before,
.note-detail-editable-text h5::before,
.note-detail-editable-text h6::before {
    content: "";
}
```

**Comment by hokutonanto** [comment]
Thank you @nil0x42 

I added the CSS with the appCss label. Does it also need to be inheritable? 

Anyway, I tried inheritable and not to no avail. I also moved the CSS under root but still no luck (of course, always refreshing and restarting Trillium).

Not sure what I'm doing wrong.

**Comment by zadam** [comment]
@hokutonanto what's missing is probably application restart.

And @nil0x42 mentioned, it's an intentional feature to better distinguish different heading levels. But I consider it experimental and I'm curious about the feedback ...

**Comment by hokutonanto** [comment]
> @hokutonanto what's missing is probably application restart.
> 
> And @nil0x42 mentioned, it's an intentional feature to better distinguish different heading levels. But I consider it experimental and I'm curious about the feedback ...

@zadam thanks, as I wrote in my msg I refreshed and also restarted Trillium but it didn't work.

As personal feedback, I'm not a big fan of seeing that part of the markdown in the editor and I know it's common for many other markdown editors. The very reason I started using Trillium was because of the WYSIWYG type of approach which I find very handy when it comes to focusing on the note itself. I think as it was before was the right balance: seeing the code while I was typing it and then being hidden once I was done. But, again, just my personal opinion.

**Comment by zadam** [comment]
So I tested the CSS snippet posted by @nil0x42 and there's `!important` missing. Should be like this:

```css
.note-detail-editable-text h2::before,
.note-detail-editable-text h3::before,
.note-detail-editable-text h4::before,
.note-detail-editable-text h5::before,
.note-detail-editable-text h6::before {
    content: "" !important;
}
```

**Comment by zadam** [comment]
@hokutonanto focusing too much on the fact it's markdown syntax is IMHO misleading. The problem I was trying to solve is that it's pretty difficult to visually differentiate between different heading levels. I chose markdown-like syntax for this because it's widely recognized, but I'm pretty open to better suggestions to fix this issue ...

**Comment by hokutonanto** [comment]
Thank you, @zadam 
the `!important` does the trick, it works now.

As for the markdown, I'm not sure what to say, I can differentiate between the different heading levels. I mean, once I decided what heading level I need (usually ## for titles, ### for sub-titles) I'm good with that and I don't think about it anymore. But I can see others may have different needs.
So, perhaps an option to toggle this on and off? Or simply the CSS already provided here, at least, that works for me :)

**Comment by nil0x42** [comment]
@zadam for the feedback, i have indeed the issue of easily differentiate heading levels. I don't mind so much on default implementation because i can change it with `#appCss`, but here is a trick i personally use to at easily distinguish `<h2>` from others:
```css
body.theme-notionless .ck-content h2 {
    margin-top: 1em;
    font-weight: 700;
}
body.theme-notionless .ck-content h2:after {
    content:' ';
    display:block;
    border-bottom:1px solid rgba(255, 255, 255, 0.07);
}
```
It makes `<h2>` bold, with a big margin before, and a discrete horizontal rule at bottom. My life is better thank to these rules.

Of course it's more related to my personal use, and my theme, and the fact that i rarely use more than 2 heading levels.

**Comment by git-steve-git** [comment]
Just to leave my own feedback on this issue:

I, too, would prefer if the # symbols were not visible.  I understand the intent of the change, but personally, if I'm having trouble telling different header sizes apart, I just jump more than one step.  (ie: h2 for "big headers", h4 for "subheaders" and h6 -- if I even need it -- for "sub-subheaders.")

I don't think I've ever written a document where I needed more than 3 sizes of header.  Especially not in Trilium, where individual notes tend to be on the shorter side anyway.

If some people do want this feature, perhaps add an option to "show markup characters" or something?  Then it can be toggled on or off as people prefer.

**Comment by Engr-AllanG** [comment]
I too particularly do not like the "#" showing. It clutters my notes up as I tend to use a lot of headings. I don't have any additional suggestions unfortunately. I would prefer the solution that @git-steve-git  suggested - make this an optional setting. I am comfortable enough making css changes, but this is not something I think should require the user to customize.

**Comment by zadam** [comment]
Add an option to configure this:

![](https://user-images.githubusercontent.com/617641/110538131-eb82fa00-8123-11eb-9d44-0f4cfead11e4.png)
