### ISSUE TITLE
Copy/Pasting Markdown

### ISSUE THREAD

**Issue by StructByLightning** [zadam/trilium#168]
Alright, so I know inline import isn't a feature yet. But there's some oddities when pasting in markdown that I wouldn't expect regardless.

***Case 1:*** "\*\*\*test\*\*\*"
- Pasting this string into trilium results in the string "\*\*\*test\*\*\*". 
- Editing one of the first three asterisks (removing then adding it) does nothing.
- Editing the fourth asterisk does nothing.
- Editing the fifth asterisk formats it to "\***test**\*".
- Editing the sixth asterisk does nothing.

***Case 2:*** "\*\*test\*\*"
- Pasting this string into trilium results in the string "\*\*test\*\*". 
- Editing the first asterisk does nothing.
- Editing the second asterisk does nothing.
- Editing the third asterisk does nothing.
- Editing the fourth asterisk formats it to "**test**"

***Case 3:*** "\*test\*"
- Pasting this string into trilium results in the string "\*test\*". 
- Editing the first asterisk does nothing.
- Editing the second asterisk formats it to "*test*"

Also, if you introduce the bug in #51 (copy something with newlines into trilium) then typing in the string "test" on the second line does nothing. Typing it into the first line works as expected.

**Comment by zadam** [comment]
So this isn't really meant to work for copy & paste, but as an aid for typing. That's why situations like "editing first asterisk in `*test*` aren't covered.

BTW, I'm not actually developing this feature, it's part of CKEditor 5 - https://github.com/ckeditor/ckeditor5-autoformat
