### ISSUE TITLE
[UX] `scrollToActiveNote` should set current note tree node as `fancytree-active`

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1685]
When a note is opened, it's fancytree node is normally set with class `fancytree-active`, making clear which note is currently opened in the tree.
But after "cleaning" tree, with combination of `Alt+C` & `Ctrl+.`, current note node looses `fancytree-active` class.

It becomes then a lot less obvious which note is currently active in `#center-pane` view.

**Comment by zadam** [comment]
Fixed now, thanks.
