### ISSUE TITLE
[UX] Jump to note shouldn't favor virtual (saved seach) paths

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1686]
Hi ! As a big user of saved searches, a lot of my notes have at least 1 path that's result of a saved search (virtual path?).
So, when jumping to a note, i seems that the chosen `path` is frequently a virtual one.

For example, i press `Alt+D` to open today's note, and my note opens with path `Tasks / Pending Tasks ! / 42 - Wednesday`:
![Screenshot_2021-02-24_10-31-42](https://user-images.githubusercontent.com/3504393/108988162-0f5a3080-768c-11eb-9dc3-ea244c171868.png)

(`Pending Tasks !` is a saved search)

## Fix proposal:
During the step of choosing default path for note being opened, ignore virtual paths

**Comment by zadam** [comment]
Hi, yeah, that makes sense. Should be fixed now. Thanks for suggestion.
