### ISSUE TITLE
[UX] `local search` dialog lacks usability

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1687]
Hi !

The `local search` dialog (in electron desktop version) is not very practical:
1. It searches in the entire `<body>` of the page, instead of only searching note content.
2. After doing a full-text search with `Ctrl+S` and opening a note, it could scroll to first entry by default
3. UX is terrible. Example:
  * I search for `git push` string in `Ctrl+S`, it finds a `dev cheat sheet` note.
  * I then must press `Ctrl+F`, and search for `git push` again to show entries in page.
  * after getting scrolled to correct location, if i try to add some text the focus is taken again by `local search dialog`, and my note re-scrolls to the top.
  * so i need to search again for `git push` in `local search`, then after getting to the right location, i must remember to press `Esc` to close search dialog, and only after that i can edit my text.

**Comment by zadam** [comment]
Yes, unfortunately this is very complicated to get right in electron apps.

I have tentative plans to replace current implementation with editor specific search using [CKEditor in-editor search](https://github.com/antoniolucasnobar/ckeditor5-find-replace) and [CodeMirror in-editor search](https://codemirror.net/demo/search.html).

**Comment by zadam** [comment]
In the recent versions a new in-editor find dialog has been implemented.
