### ISSUE TITLE
[REGRESSION:v0.46.1-beta] Note with clones indicator (' *' suffix) is not updated in tree view

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1688]
No sure if it's only since v0.46.*, but the tree used to be responsive about updating ' *' suffix of fancytree nodes to show which ones have at least another clone.

Now, if i clone an `alone` note, or delete other clones of a note, the ` *` suffix is onlu updated after i press `F5` to reload UI.

**Comment by zadam** [comment]
Thanks for reporting, fixes.
