### ISSUE TITLE
[0.46.1-beta] "Show in full search" returns empty note

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1689]
Running the latest 0.46.1 beta.

The quick search works as expected, returning a number of hits.  
Clicking "Show in full search" just creates a new "Text" type note next to the current one, named "Search: " with 1 owned attribute `#searchString=<my search string>`.

Screenshot:
![image](https://user-images.githubusercontent.com/39531/109120315-147bb600-7746-11eb-8f5b-9edc752d3b5c.png)

With the recent changes, I'm not sure what's missing to make this a proper "search" note, with actual results?

**Comment by zadam** [comment]
Hi, so the missing thing here is the note type - everything looks fine, but the note should have been created as "search" type and not "text" type.

This is quite baffling for me and I don't know how this could happen. This is not configurable in any way, the quick search "show in full search" should always create notes of "search" type.

I wonder, if you try to do that again, does it again create a text note? Is there perhaps some error in frontend console? (`CTRL-SHIFT-I`)

Thanks for reporting ...

**Comment by wwwald** [comment]
It systematically produces a Text type note.

On every search listing in the Quick Search, I do see an error in `tree.js:73`:

    Did not find parent root (root) for child <noteId> (<note title>), available parents: <note ID of immediate parent>

This error appears for every page in the "quick search" results listing.
Example: 

    20:55:17 Did not find parent root (root) for child VbDa7wBxRFsx (2020-09-14 11:50 xxxx xxxx xx), available parents: UFK7RYY5u80E (14 - Monday)          tree.js:73 
    20:55:17 Did not find parent root (root) for child UOyzvPaDBTGd (Projectpage), available parents: EWDz8O9Q8P9i (projects)                                tree.js:73
    20:55:17 Did not find parent root (root) for child IGHfmztP7GeT (2020-06-04 09:13 xxxx xxxx xx), available parents: kKdk4wMPN1fC (04 - Thursday)          tree.js:73
    20:55:17 Did not find parent root (root) for child hwURtbgp5VUI (2020-06-04 10:15 xxxx xxxx xx), available parents: kKdk4wMPN1fC (04 - Thursday)          tree.js:73
    20:55:17 Did not find parent root (root) for child fHKVIsf0cgjI (2020-06-04 10:34 xxxx xxxx xx), available parents: kKdk4wMPN1fC (04 - Thursday)          tree.js:73
    20:55:17 Did not find parent root (root) for child cNyEyJjdDKx4 (2020-06-10 17:16 xxxx xxxx xx), available parents: tcpKq1XkeVch (10 - Wednesday)          tree.js:73 
    20:55:17 Did not find parent root (root) for child eAzz1qzRVrFO (2020-06-15 13:37 xxxx xxxx xx), available parents: KZNgcpYPjgQg (15 - Monday)          tree.js:73
    20:55:17 Did not find parent root (root) for child 7PVWApw19zsg (2020-06-16 16:37 xxxx xxxx xx), available parents: BX5z9ozaKD57 (16 - Tuesday)          tree.js:73
    20:55:17 Did not find parent root (root) for child 00EFALc0f90C (2020-06-17 09:29 xxxx xxxx xx), available parents: I401w9Pkj6Lp (17 - Wednesday)          tree.js:73
    20:55:17 Did not find parent root (root) for child c3UQ6dUhuDWF (2020-06-22 09:17 xxxx xxxx xx), available parents: T8BPFjbM31a6 (22 - Monday)          tree.js:73
    20:55:17 Did not find parent root (root) for child DNsHMNcCcofj (2020-06-24 13:48 xxxx xxxx xx), available parents: CX3yrzwRvLWT (24 - Wednesday)          tree.js:73
    20:55:17 Did not find parent root (root) for child BDSdMzfVn8vw (2020-06-30 09:26 xxxx xxxx xx), available parents: cyZyfcoF174C (30 - Tuesday)          tree.js:73
    20:55:17 Did not find parent root (root) for child Fdc0qqvaFAi1 (2020-06-30 13:49 xxxx xxxx xx), available parents: cyZyfcoF174C (30 - Tuesday)          tree.js:73
    20:55:17 Did not find parent root (root) for child GFZ9gWiQuxGM (2020-07-15 08:13 xxxx xxxx xx), available parents: UhwsnXJCQoUF (15 - Wednesday)          tree.js:73
    20:55:17 Did not find parent root (root) for child E7RhNWu1mQPN (2020-07-15 08:27 xxxx xxxx xx), available parents: UhwsnXJCQoUF (15 - Wednesday)

So it seems to be looking for the absolute root note of the full tree, but searches the direct parent note?  
Most of these are subnotes of day pages in the journal, but other kinds of notes show the same problem, see line 2 which is not in the journal subtree.

**Comment by zadam** [comment]
> By the way, should I be able to switch the note type to "Search" myself via the Type dropdown menu? In any case, "Search" type is not listed there.

No, some note types are not changeable - e.g. search (also file, image) note can be only created and then can't be changed from/to another type.

The console messages are not actually errors and in this situation are expected.

I will keep investigating how this can happen ...

**Comment by zadam** [comment]
@wwwald do you have some script or some special behavior attached to the created day notes? I can see from the screenshot that day note children have some special look / date-time prefix ...

**Comment by wwwald** [comment]
No special scripts, just using the regular journal, the datetime prefixes are manually added using Autohotkey shortcuts.

The day note children are assigned a custom template, which is defined as a `child:template` relation on the day notes.

Only thing I can think of is a "Today" toolbar button & shortcut key:
```
api.addButtonToToolbar({
    title: 'Today',
    icon: 'calendar',
    shortcut: 'alt+t',
    action: async function() {
        const todayNote = await api.getTodayNote();

        await api.waitUntilSynced();
    
        api.activateNote(todayNote.noteId);
    }
});
```
Let me know if I can help, always prepared to check logs, provide db, test things...

**Comment by zadam** [comment]
I managed to reproduce this issue - it's the template which is trying to copy the note type, but that shouldn't be possible in this case.

Thanks for help!
