### ISSUE TITLE
Indicator on server sync

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#1692]
As my network conditions are very poor occasionally while away on my laptop (100-150 kbps with significant latency), each change can take up to 5 seconds to sync in the browser version according to the network console. The local version I don't worry about since it's stored locally but if I preemptively close the browser version this will cause data loss. 

I just pasted in an API key into a pretty big note and closed the tab after ~2 seconds and when I reopened it, it was not there. I assume this is the fault of my poor network conditions. I know this seems like an insignificant issue but it has already caused data loss for me :/.  Something small like an asterisk on the tab while an edit is still being synced would be greatly appreciated. Maybe something more subtle though since as you're typing it might be flashing as it syncs each change every few keystrokes.

![image](https://user-images.githubusercontent.com/69441971/109346948-500fa080-786a-11eb-862e-7fdaab82e32e.png)

![image](https://user-images.githubusercontent.com/69441971/109347034-6fa6c900-786a-11eb-9241-eff68590067b.png)

As an aside, the syncing seems very heavy; from what I can tell it sends the entire note on every edit and seemingly keystroke. Is it possible to `POST` a delta/diff of the changes + a hash of the resulting note, and on server complaint of mismatch, resend full note when necessary? When I'm editing large notes these requests can get large in size despite most of the note staying the same.

I'll take a look at the code if I get the chance to understand how it works (not a node guy though, no promises). Hopefully there's an easier way to sync larger notes besides "split up your notes and don't use one big one" (though that cut and paste to sub-note is a life saver!).

**Comment by zadam** [comment]
I'd treat this rather as a bug report - it shouldn't be possible to close a tab and lose some edits.

There's an event handler which will first save any outstanding changes and only then allow to close the tab. I will look at this and try to reproduce. (this should work for both trilium tab and browser tab, but to be clear which one did you mean?)

> As an aside, the syncing seems very heavy; from what I can tell it sends the entire note on every edit and seemingly keystroke.

It's actually time based - once per second. This was done with the desktop app in mind where 1 second interval is OK, but perhaps for web version it is too much traffic.

> Is it possible to `POST` a delta/diff of the changes + a hash of the resulting note, and on server complaint of mismatch, resend full note when necessary?

Theoretically yes, but it results in increased complexity and has a few corner cases so if possible I'd try to avoid it.

Especially given you have a bad connection I would recommend to use a desktop version and setup syncing to the web version...

**Comment by sigaloid** [comment]
Able to replicate slow sync times on a note with ~9k words: 
![image](https://user-images.githubusercontent.com/69441971/109361970-02069700-7882-11eb-82fc-70d61feebca0.png)
25 seconds to sync note when simulating a _very_ poor connection (think this was 2g). 
![image](https://user-images.githubusercontent.com/69441971/109362202-6aee0f00-7882-11eb-8932-4d5fc0a5c18e.png)
10 seconds to sync same note when simulating good 3g.
![image](https://user-images.githubusercontent.com/69441971/109362286-9d980780-7882-11eb-8fc2-2913b2439bef.png)
3 seconds to sync same note while simulating 4g. 

Now for my final trick: I'll simulate extreme network delay with `throttle --up 330 --down 780 --rtt 200` to show the data loss: https://litter.catbox.moe/43ywce.mkv

**Comment by zadam** [comment]
Hi, the measurements are pretty strange. My testing on Firefox with "Regular 3g" (IMHO the slowest network connection worth supporting) on a rather large text note (~60 KB):

![](https://user-images.githubusercontent.com/617641/109398426-2ffce180-793d-11eb-8691-ef002cf287c0.png)

3 seconds on 4G/LTE would mean that the note is several megabytes large which seems quite unrealistic.

Possible explanation would be (very) slow server.

**Comment by sigaloid** [comment]
>3 seconds on 4G/LTE would mean that the note is several megabytes large which seems quite unrealistic.

No, it was small. The issue was that I had the `throttle` command running in the background this whole time. I was very confused why my email wouldn't load this whole time :angry: 

Anyway, what about the data loss? The event handler seems to not stop when a tab is trying to be closed and the sync is still completing.

**Comment by zadam** [comment]
So the thing is that browser can cancel outstanding async requests if the tab is closing. When do the browsers do that is not clear though ...

I just implemented a different workaround to prompt user whether they really want to close/refresh the tab when there are outstanding changes. If user chooses to close the tab anyway then it's the same issue again though...

**Comment by sigaloid** [comment]
Is it like this which is implemented in browsers already? 
![image](https://user-images.githubusercontent.com/69441971/109403185-5fb6e400-7953-11eb-9b11-a14324c16bb8.png)

**Comment by zadam** [comment]
Yes, it's the same dialog (it's actually not programatically changeable).

**Comment by sigaloid** [comment]
Thanks- closing
