### ISSUE TITLE
[UX:v0.46.2-beta] `Quick Search` weird behaviors

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1694]
**Quick Search** (`<div class=quick-search>`) feature suffers some UX weird behaviors.

### Issue 1: Search not refreshed when pressing `Enter` a second time
If i search `foo` then press `Enter`, it shows results.
Then if i want to change my search string to `bar`, then press `Enter`, the results list is not updated.

### Issue 2: Using `Show in full search` button while hoisted is not UX friendly
The `Show in full search` button create a new `Saved search` as a child of `TodayNote`.
I can understand the behavior, but it becomes wierd when we are hoisted into a note.
In such case, we always need to confirm to exit the current hoist to go back to day note and show results.
And a search from a hoisted note is meant to return results in this scope, so it's even weirder to see results only appear for previously hoisted note, then click `refresh` and now see all results for all trilium notes (as we are no longer hoisted).

**Possible solution**: When hoisted somehwere that makes `TodayNote` out of scope, create saved search as direct child of hoisted note instead.

**Comment by zadam** [comment]
Hi, fixed both issues. Second one probably isn't ideal but should suffice for now ...
