### ISSUE TITLE
[BUG:v0.46.2-beta] Inconsistent Tree `No data.`

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1699]
## Issue
Tree in hoisted note disapears completely and shows `No data.` message

## Steps to reproduce
1. Go into any subnote (`N1`), and hoist into it.
2. Open a new tab, open a note in a different path (`N2`), then click `Collapse note tree` button.
3. go back to `N1` tab. The tree is now completely unavailable, and shows `No data.`

## Possible fix
No sure, but maybe when focusing an opened tab, always ensure it's corresponding `fancytree-node` is expanded (`scrollToActiveNote` ?)

**Comment by zadam** [comment]
Thanks for the bug report, fixed.
