### ISSUE TITLE
Few questions about the desktop version for Windows, just getting started.

### ISSUE THREAD

**Issue by toastonrye** [zadam/trilium#1700]
Where is the database saved? If I want to use my Google Drive to backup this database on a locally installed desktop.
Edit I found the info here: https://github.com/zadam/trilium/wiki/Data-directory

How do I make a new document? I have the root directory that lists Trilium Demo, but I can't figure out a way to make a new personal notebook?

**Comment by toastonrye** [comment]
I have since deleted the Trilium Demo, and I only have root. I can not see a way to make a folder. I can only insert various child notes.

**Comment by zadam** [comment]
Yes, Trilium doesn't make a distinction between a note and a folder. Any note can have children and thus fulfill the function of folder ...
