### ISSUE TITLE
[UI] Allow `link map` nodes titles to inherit `#cssClass` value

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1702]
Hi ! To have a better understanding of my notes, i have some 'cssClass' values which help me know if a note is of certain type ("cheatsheet", "documentation", "tool", etc..).

It's very useful to be able to set `#cssClass` to one of these values, so my notes in tree have a specific color and styling:
![Screenshot_2021-03-01_11-51-09](https://user-images.githubusercontent.com/3504393/109493950-2088b000-7a85-11eb-8335-79488d32ce21.png)
(here i have "attack" notes in orange, and "tool" notes in cyan)

But in the link map, note nodes do not inherit `#cssClass`, and it would be very nice/convenient/practical to have such class applied to note titles in link map as well.

**Comment by zadam** [comment]
Added.

**Comment by blumpcus** [comment]
@nil0x42 
Is there anyway you could share how you specifically color the notes in the tree? 
I understand that you're using cssClass but I have no idea how I would go about applying this to my own, including how to define the types, colors (for e.g. cheatsheet, tool, etc).
I would love to replicate this for myself.
Thanks for your time.
