### ISSUE TITLE
[BUG:v0.46.*] Internal bug in searches

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1706]
## Introduction
I use labels a lot to categorize my notes, and i frequently use search to find notes with these labels.
Something i heavily use is `cssClass`, which i use as some kind of `tagging system` for `what kind of content has this note ?`.
For example, i have a lot of notes with `#cssClass=tool`, so notes like `git`, `Firefox` have such label.

## Issue description
After some time using trilium, most of my `Saved searches` simply return nothing. For example, my saved search `#cssClass = tool` returns nothing, even if i have dozens of such notes.
If i press F5, the issue remains
If i close, then reopen trilium, the bug disapears for some time

This issue may be related to https://github.com/zadam/trilium/discussions/1651#discussioncomment-400816

## How to reproduce
It was somewhat difficult to figure out how to reproduce, but here is a list of actions that seem to trigger the bug:
1. Create 3 notes:
    1. "note1" having `#cssClass=bugtest1` label
    2. "note2" having `#cssClass=bugtest2` label
    3. "note3" having `#cssClass=bugtest2` label
2. Search for `#cssClass = bugtest2` on `Quick Search` or `Saved search`, it correctly finds "note2" and "note3".
3. Go to one of these notes, and remove `#cssClass=bugtest2` label from it
4. Now go back to saved search (or `Quick Search` again for `#cssClass = bugtest2`): It finds **nothing**
5. Even worse, from now, ALL notes with `#cssClass` label cannot be found if searched from this label:
    1. For example, search for `#cssClass = bugtest1`: It finds **nothing**
    2. Simply search for `#cssClass` (to get ALL notes with that attribute), it finds **nothing**

## Suggestion
I have no idea, no strange error appears in logs, but maybe some deadlock or unserved promise is behind that bug. Anyway, i hope you'll be able to reproduce with my steps.

**Comment by adamcodemaker** [comment]
I have similar problem but with relations
## To reproduce:
1. Create note "test1"
2. create child notes "test2" and "test3"
4. add relation ~testRelation=test1 to "test2"
5. add relation ~testRelation=test1 to "test3"
6. search for ~testRelation.title *=* test1
7. result is 2 notes
8. remove relation from test2
9. result is 0 notes (expected 1 note)

**Comment by zadam** [comment]
Hi, thanks to both of you for detailed bug report, I was able to replicate the issue and fix it.

For speed up of many operations (including search), Trilium has in-memory views on the data (caches) which need to be kept in sync with database which is somewhat complex. There was a bug which caused that when attribute was deleted then the index for all same-named attributes was dropped which caused exactly this issue (empty index => nothing was found).
