### ISSUE TITLE
AGPLv3 only or AGPLv3+ ?

### ISSUE THREAD

**Issue by FliegendeWurst** [zadam/trilium#1708]
This question came up when packaging Trilium Notes for NixOS (https://github.com/NixOS/nixpkgs/pull/114844). The main license file is (obviously) AGPLv3. Usually AGPLv3+ is intended, but there is no copyright notice in any source file:

```
To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
```

**Comment by zadam** [comment]
Hi, I'm not against AGPLv3+ but I also don't want to pollute all the sources with license text ...

Is there a way to declare AGPLv3+ without mentioning it everywhere?

**Comment by FliegendeWurst** [comment]
Yes, you can specify the license in the readme.

**Comment by zadam** [comment]
@FliegendeWurst lol, who would have thought? Added ...
