### ISSUE TITLE
ERROR: migration failed, crashing hard

### ISSUE THREAD

**Issue by LorenAmelang** [zadam/trilium#1709]
Just tried to start Trilium after a Windows restart. No window, log full of errors. Had v0.45.8, just tried v0.45.10, same errors. 

Found a log 2020-09-27 with similar segment, but that one worked:

13:36:28.440 App db version is 170, while db version is 159. Migration needed.
13:36:28.442 DB size: 33439 KB

13:36:31.089 Attempting migration to version 170
13:36:31.113 Migration to version 170 has been successful.
13:36:31.116 Created missing option "attributeListExpanded" with default value "false"
(And a bunch more missing options...)

Tonight, while Trilium was not running, its log shows:
20:45:53.588 App db version is 170, while db version is 159. Migration needed.
20:45:53.591 DB size: 28655 KB

20:45:55.596 Created backup at C:\Users\loren\AppData\Roaming\trilium-data\backup/backup-before-migration.db
20:45:55.598 Attempting migration to version 160
20:45:55.601 ERROR: error during migration to version 160: SqliteError: database disk image is malformed
    at Object.executeScript (C:\Apps\trilium-windows-x64\resources\app.asar\src\services\sql.js:195:25)
    at Function.<anonymous> (C:\Apps\trilium-windows-x64\resources\app.asar\src\services\migration.js:52:25)
    at Function.sqliteTransaction (C:\Apps\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\transaction.js:58:24)
    at Object.transactional (C:\Apps\trilium-windows-x64\resources\app.asar\src\services\sql.js:230:48)
    at migrate (C:\Apps\trilium-windows-x64\resources\app.asar\src\services\migration.js:46:17)
    at async Object.migrateIfNecessary (C:\Apps\trilium-windows-x64\resources\app.asar\src\services\migration.js:105:9)
    at async initDbConnection (C:\Apps\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:39:5)
20:45:55.602 ERROR: migration failed, crashing hard

And similar segments for each version up to 170. Then:
20:45:55.632 TypeError: results is not iterable

That repeats every time I try to run Trilium. 

Seems strange it is attempting the same migration, numerically at least, as six months ago...

Help!

[trilium-2021-03-03.log](https://github.com/zadam/trilium/files/6081403/trilium-2021-03-03.log)
[trilium-2020-09-27.log](https://github.com/zadam/trilium/files/6081409/trilium-2020-09-27.log)

**Comment by LorenAmelang** [comment]
I must have clicked the Trilium icon at 20:45 tonight and gotten distracted before realizing it didn't start...  Had to be running to try the migration...

**Comment by LorenAmelang** [comment]
Sorry for thinking slowly here...  

Looks to me like the db is trashed:
![Trilium db](https://user-images.githubusercontent.com/1297090/109925881-2645e780-7c77-11eb-835b-3d47dc06eca6.PNG)

I've never poked into this, but my DB Browser shows only 3 top level notes, and 23 deleted ones. The recent_notes table has 286 reasonable looking ones. 

So maybe I copy backup-daily.db up to document.db, which is tiny like tonight's backup? Or maybe copy backup-weekly? They're the same size, but different hash...  Weekly is newer?

**Comment by zadam** [comment]
Hi, that's pretty unfortunate. Really looks like the document.db is corrupted on some pretty basic level - it's not clear how it could lose 2/3 of its size (without `VACUUM`ing the sqlite databases don't normally get smaller).

Way forward would be restoring the backup - in your case the weekly backup seems to be slightly newer than the daily, so I would use that. The whole guide to restore is [https://github.com/zadam/trilium/wiki/Backup#restoring-backup](https://github.com/zadam/trilium/wiki/Backup#restoring-backup) specifically note that you need to delete the remaining index files (-wal and -shm).

**Comment by LorenAmelang** [comment]
Working again, Thank You! 

Checked Event Viewer - at the moment of the first Trilium error:

Log Name:      System
Source:        Microsoft-Windows-DistributedCOM
Date:          3/3/2021 8:45:55 PM
Event ID:      10016
Task Category: None
Level:         Warning
Keywords:      Classic
User:          DESKTOP-OMMHHCL\loren
Computer:      DESKTOP-OMMHHCL
Description:
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user DESKTOP-OMMHHCL\loren SID (S-1-5-21-2642381790-255542418-257213659-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

(The rest goes crazy here - see file.)

[Trilium Warning.txt](https://github.com/zadam/trilium/files/6087597/Trilium.Warning.txt)

Similar Warnings each time I tried Trilium last night, which makes sense. 

But the same Warning today after I'd swapped in the good db and it seemed to work! 

Actually, looks like every time I've accessed Trilium for months I get one of those! Sometimes five or six within a couple minutes. Hard to know for sure if the relationship is exact, but yesterday and today certainly line up. So they usually aren't a serious problem...  But apparently sometimes...  

Do you understand what the warning is trying to say?

**Comment by zadam** [comment]
No, unfortunately I'm not really wiser from that warning.

The truncation of the database file seems like some quite serious low level error, perhaps something with filesystem. Normally this shouldn't happen, especially with transaction based database like SQLite ...

**Comment by LorenAmelang** [comment]
https://docs.microsoft.com/en-US/troubleshoot/windows-client/application-management/event-10016-logged-when-accessing-dcom

These 10016 events are recorded when Microsoft components try to access DCOM components without the required permissions. In this case, this behavior is expected and by design.

A coding pattern has been implemented where the code first tries to access the DCOM components with one set of parameters. If the first attempt is unsuccessful, it tries again with another set of parameters. The reason why it doesn't skip the first attempt is because there are scenarios where it can succeed. In those scenarios, it's preferable.

These events can be safely ignored because they don't adversely affect functionality and are by design. It's the recommend action for these events.


Good Grief! I guess they are intended to appear on every Trilium access...  Most Windows "events" are useless.
