### ISSUE TITLE
[Bug] Opening cloned note or its children doesn't open the shortest path or the first in order

### ISSUE THREAD

**Issue by QuentinLeCaignec** [zadam/trilium#1711]
(version 0.45.9)
When opening a note from a link (jumping from one note to another), if the note is cloned in multiple places in the hierarchy, the one taking priority doesn't seem consistent.

I have a note with a lot of child notes buried deep into a large note-tree, so I cloned this note at the root to be able to access it's children without opening the entire parent hierarchy. However when jumping into this note or a child note from somewhere else, it will often (but not always!) go through the longest path instead of the shortest, opening the entire hierarchy of the note is cloned in the deepest tree, instead of opening the cloned tree at the root with the shortest path.

I've tried deleting one or the other and recloning it, i've also tried putting the note I want to be in priority at the beginning of the list (ordered before the other one) but the behaviour seems inconsistent.

Is there a way to fix this, is this intended behaviour?

**Comment by zadam** [comment]
Hi, this is a bit complex topic. Notes are identified by `noteId` and in some places this is all we have - e.g. relations point to a `noteId` and when you click on the target, Trilium will find pick any of the available paths from this note to the root. Which one is generally undefined behavior.

Then there's a concept of `notePath`, which is essentially detailing exact path from root over each ancestor note. This is used in e.g. internal links to note. In such case you should always arrive at the target note by the exact same path.

Coincidentally just yesterday I was working on converting some cases of `noteId` usage to `notePath` usage to lower the amount of cases of picking just any path.

But in some cases (relation targets) I don't plan to use `notePath` (it has some disadvantages too) and in that case some improved heuristics would probably make sense (like the shortest path).

**Comment by nil0x42** [comment]
Hi ! I've also had some annoying experience with this

Let me suggest some algorithm (but i'm totally unaware of its potential overhead):
* a request to open `noteId` is made
* if this `noteId` has a path that's already expanded (in tree), pick this one
* otherwise, pick shortest path, excluding virtual paths (paths from saved searches)

We could go even deeper:
* if multiple paths are expanded (in tree), pick the shortest one among them
