### ISSUE TITLE
[FEATURE] Allow to hide custom notes from tree

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1713]
## description
Trilium has two wonderful tree options:
![Screenshot_2021-03-04_16-10-07](https://user-images.githubusercontent.com/3504393/110026195-441f5500-7d28-11eb-842b-1dd87a6f50c6.png)

Therefore, as trilium's main feature is being able to adapt to each user's workflow with its great plasticity, it would be great to have option to hide notes tagged as "to hide from tree".
For example, i often use "checklist" notes, with a lot of one-line TODOs, and when i've done some task i use to `log` what i did for each task into a `OUT` subnote:
![Screenshot_2021-03-04_20-33-25](https://user-images.githubusercontent.com/3504393/110026808-125abe00-7d29-11eb-9578-46a15468a2aa.png)

At the end of the day, my checklist has dozens of `OUT notes`, whose only purpose is to be linked from my checklist.
It would be great if there was some `#hidden` label, and "Hide #hidden notes from tree" option in `Tree settings`.

The difference from `#archived` would be that `#hidden` notes can be hidden, but are still searchable in full-text-search.

## conclusion
Of course it can be implemented in many other ways, but here is the main issue: being more flexible about what kind of notes can be hidden in tree.

**Comment by zadam** [comment]
> The difference from `#archived` would be that `#hidden` notes can be hidden, but are still searchable in full-text-search.

Full text search by default does not list archived notes but you can change it in "full search" via "include archived".

Otherwise the way I would approach this would be probably via some script which would move all notes with a `#hidden` label into some archiving note on the side ...

**Comment by abitofevrything** [comment]
I have created a script which hides notes with the `#hidden` attribute from the note tree and a couple other places - [check it out](https://github.com/zadam/trilium/discussions/2072)!
