### ISSUE TITLE
[UX] Inherited attrs not updated after defining a promoted template value

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1717]
## How to reproduce
* create a note `test-template` with `#tplattr` label.
* create a note `test-newnote` with a promoted relation definition: `#relation:template=promoted,single`
* on `promoted attrs`, set template value to `test-template`
* `test-newnote` has now inherited `#tplattr` from `test-template`, but it's not displayed in `inherited attrs` section
* only way to get current `inherited attrs` is to reload UI with `F5`

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.

> only way to get current `inherited attrs` is to reload UI with `F5`

BTW, often it's enough to refresh the current view by e.g. activating a different note and coming back.
