### ISSUE TITLE
[BUG] Trilium internal link triggers "oustide of hoisted note" box unexpectedly

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#1718]
## Issue
when a trilium internal link is clicked inside a hoisted note, configuration message asking to unhoist appears, even if link is to a note that exists within hoisted note childs.

## Steps to reproduce
* create a note `hoistable` somewhere
* create a note `foo` AT ROOT
* clone `foo` into `hoistable`
* into `hoistable` text note, create an internal link (Ctrl+K) to `foo`
* hoist into `hoistable`
* click in link to `foo`

## Recomendation
make sure noteId doesn't have a path inside currently hoisted note before showing "unhoist confirmation" message.

**Comment by zadam** [comment]
Hi, yes, this happens because of the "just take random note path" with cloned notes. In the past days I've improved the heuristics to choose a note path and it takes into account hoisted state - so if there is note path going through the hoisted note, then it's given a priority ...

**Comment by nil0x42** [comment]
Hi ! Just for the record, it looks like this issue is still present in v0.46.3-beta

**Comment by zadam** [comment]
Hi, so I didn't read very closely and this was actually a separate issue. In this case the link already contains a full path to a clone outside of hoisting. Now this should be handled.
