### ISSUE TITLE
Reload while typing

### ISSUE THREAD

**Issue by danieldaeschle** [zadam/trilium#172]
I want to write a note. then he's saving my written text and after that he tells me that he is reloading the note because of background changes. That isn't good because it breaks my write flow.

**Comment by zadam** [comment]
Right, this shouldn't happen normally (it may happen when e.g. your current note is being synced from sync server). Did you do anything special? I suppose you lost a bit of content you just wrote?

**Comment by danieldaeschle** [comment]
Yes, right. I lost a little bit of content and my cursor got reset.

I didn't used it many. So i just tested writing notes :O

**Comment by zadam** [comment]
Would it be possible for you to attach the log file for today so I can look for anything suspicious?

It should be in the [home]/trilium-data/log directory

**Comment by danieldaeschle** [comment]
i will take a look at it tomorrow.
