### ISSUE TITLE
How can I copy markdown format text to become rich text

### ISSUE THREAD

**Issue by starsareintherose** [zadam/trilium#1720]
How can I copy markdown format text to become rich text?
Because the evernote format is written by markdown format, but when I copy them to the text format, they are not auto-tranfer to rich text.
How can I do? Just re-write them?

**Comment by zadam** [comment]
Hi, you can copy the markdown into a clipboard and click on this button:

![](https://user-images.githubusercontent.com/617641/110377424-ad6ad500-8054-11eb-9efa-6fed571a219b.png)

Alternatively you can import markdown files (or Evernote's ENEX) via import dialog:

![](https://user-images.githubusercontent.com/617641/110377588-e0ad6400-8054-11eb-9d4e-cbfe53524e80.png)

**Comment by starsareintherose** [comment]
Thanks, it's really helpful.
