### ISSUE TITLE
I want to add code highlights

### ISSUE THREAD

**Issue by finding** [zadam/trilium#1721]
[https://ckeditor.com/docs/ckeditor4/latest/features/codesnippet.html](url)

**Comment by zadam** [comment]
Trilium uses CKEditor 5 and this is not supported in this version. You need to create a code note, that one has code highlighting.

**Comment by finding** [comment]
Thank you, I know there are code note, but I want the inserted code snippets in the text note to be highlighted. Can we achieve this function in the future

**Comment by finding** [comment]
> Trilium uses CKEditor 5 and this is not supported in this version. You need to create a code note, that one has code highlighting.

Thank you, I know there are code note, but I want the inserted code snippets in the text note to be highlighted. Can we achieve this function in the future

**Comment by zadam** [comment]
That depends on CKEditor itself. I remember reading some discussions regarding this on their github and it sounded improbable and pretty difficult.
