### ISSUE TITLE
how to change the code type

### ISSUE THREAD

**Issue by MasakiOvO** [zadam/trilium#1722]
![image](https://user-images.githubusercontent.com/15852828/110312695-61ae3080-8040-11eb-89bf-d717f5cb3dc8.png)

**Comment by zadam** [comment]
click on the button:

![](https://user-images.githubusercontent.com/617641/110376926-130a9180-8054-11eb-9308-47567558f40d.png)

**Comment by MasakiOvO** [comment]
I tried, but clicking that button doesn't show the menu.
