### ISSUE TITLE
Select text or try edit table using mouse in windows 10 does not work at first

### ISSUE THREAD

**Issue by pencina** [zadam/trilium#1726]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:
I am using the following version 
![image](https://user-images.githubusercontent.com/28844991/110509209-dd0af300-80cf-11eb-84d9-edb3f83d74cf.png)
while I am writing this issue the mouse in trilium start working, the only thing that I did enable a document as protected and suddenly it start working with all the documents

**Comment by zadam** [comment]
Hi, could you please record a video/gif of this behavior? I'm not sure what you mean and it seems to work OK here...

Thanks.

**Comment by zadam** [comment]
Hi, could you please record a video/gif of this behavior? I'm not sure what you mean and it seems to work OK here...

Thanks.
