### ISSUE TITLE
Color is not preserved when copy and pasting from trilium

### ISSUE THREAD

**Issue by hue-ctrl** [zadam/trilium#1727]
While most formatting is copied to (e.g libreoffice) just fine, color is not preserved. v0.46.3-beta on Linux.

**Comment by abitofevrything** [comment]
Trilium does not support coloured text, so I am not sure what you are referring to

**Comment by zadam** [comment]
that's not exactly true:

![image](https://user-images.githubusercontent.com/617641/127386147-da9ec6e0-8bc0-4e5b-927f-91c12bbf3a4c.png)

I guess it depends on how exactly is the color specified in the HTML in the clipboard (CSS, `<font>` tag etc.)
