### ISSUE TITLE
[Feature] Automatically compress PDFs

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#1728]
I would also have created my own scripts which automatically compresses pdfs, but as far as I know scripts only work with Javascript.

I would be really nice to have this feature since we already have image compression available.

**Comment by wwwald** [comment]
Seems like quite a task, image compression can be done with relatively light-weight libraries. 

PDF compression is a whole other beast - not sure if it can be done without dedicated packages like GhostScript or similar options. But those are quite niche and heavy dependencies to incorporate.

Anyway, just my 2 cents. @zadam probably has a much better view on those things.

**Comment by Myzel394** [comment]
Maybe we could use an API service? Not the best option IMO but better than nothing.

Btw. in what programming languages is Trilium written? Couldn't find anything about it.

**Comment by zadam** [comment]
Trilium is written mostly in JavaScript.

I view this issue rather skeptically - this seems like quite a niche use case with pretty high cost as @wwwald already mentioned.

**Comment by Myzel394** [comment]
Only Javascript? I thought there's also a Rust part in it?

**Comment by Myzel394** [comment]
Another idea (for future readers) would be to create a little script (e.g Python or Node.js) and to run it every few days which automatically compresses pdfs.

**Comment by zadam** [comment]
Nope, no Rust.

**Comment by wwwald** [comment]
@Myzel394: The nice thing about Trilium is that the database is completely accessible - it's a plain SQLite database living in Trilium's data directory (see "About" dialog). 

You can find all PDF files in your database with a query like:

```sql
SELECT n.title, nc.content FROM notes n
	JOIN note_contents nc on nc.noteId = n.noteId 
	WHERE  n.mime = 'application/pdf'
```

Producing a Python script to save the PDF's content to file, compress it using Ghostscript and saving back to the database wouldn't be too hard. Quick Google turned up [this example](https://github.com/theeko74/pdfc/blob/master/pdf_compressor.py) that shows how to compress the PDF on disk.

But as mentioned - you'll need Ghostscript installed, make a backup of your database file first and run the script with Trilium closed to avoid concurrent access to the database file.
