### ISSUE TITLE
[bug] quick search not working - 0.46.3-beta

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1729]
0.46.3-beta server, on Ubuntu 16.04

The quick search mostly doesn't work. Most anything I type in, it returns an empty tiny window. This is using Chrome or Firefox. There are a few notes it does find, but I don't see any reason why these notes will be returned as results and others not.

A possibly related bug, is two of the right sidebar widgets with links don't work. 

- The calendar sidebar widget does not open the note when selecting a date that has a note. 
- The link map will not open notes when selecting links from the link map

[trilium-2021-03-09.log](https://github.com/zadam/trilium/files/6112022/trilium-2021-03-09.log)

**Comment by zadam** [comment]
Hi, thank you for reporting this issue.

Unfortunately I'm not able to reproduce this. There's a possibility this is caused by the same bug as #1730 but it's difficult to say.

Some context - are you hoisted? Does the search problem go away if you restart the application and quick-search again?

**Comment by Engr-AllanG** [comment]
Recent update seems to have fixed this. thanks!
