### ISSUE TITLE
[bug] search button opens new tab 0.46.3-beta

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1730]
0.46.3-beta server edition, on ubuntu 16.04. Accessed via Chrome

When clicking on the search button (top left), it opens a blank new tab out of focus (current tab stays active).

This isn't intended behavior, is it?

[trilium-2021-03-09.log](https://github.com/zadam/trilium/files/6112062/trilium-2021-03-09.log)

**Comment by zadam** [comment]
Hi, thank you for testing beta versions and reporting issues!

Opening a new tab is intentional but the search note should be displayed in it and this part was failing. Should be fixed now.
