### ISSUE TITLE
About the index of one note

### ISSUE THREAD

**Issue by starsareintherose** [zadam/trilium#1731]
1. When I search for anything, I can only jump to that note but I need to find the word in the note.
2. No index can help me find if the note is long. So, heading2 and heading3 etc. can't be completely used for the software.
3. Could I use '@' to cite the heading2 or heading3?

**Comment by zadam** [comment]
Hi, there's a per-note search you can open with `CTRL-F`. It sucks a bit but should do the trick.

> *   So, heading2 and heading3 etc. can't be completely used for the software.
> *   Could I use '@' to cite the heading2 or heading3?

Unfortunately I don't understand these points. Could you elaborate?

**Comment by starsareintherose** [comment]
>  - Could I use '@' to cite the heading2 or heading3?
![image](https://user-images.githubusercontent.com/37733075/110735762-5ee05500-8265-11eb-8900-fe42dd6d6350.png)
For example, I want to link internal link on one note, I'm searching the heading3 (figure 2) of note called typecho
![image](https://user-images.githubusercontent.com/37733075/110735788-6a338080-8265-11eb-96cc-4c498af2a480.png)
Like this, figure 1 shows no result, so I can't use heading as the internal link.
>  - So, heading2 and heading3 etc. can't be completely used for the software.
![image](https://user-images.githubusercontent.com/37733075/110736024-df9f5100-8265-11eb-8f41-0d782b92d643.png)
The red line circles the index (= Navigation Bar) of headings.
For example, you set several heading2, then the note will produce something similar to the navigation bar, you can easily reach the locality of any headings.

**Comment by zadam** [comment]
> Could I use '@' to cite the heading2 or heading3?

I see, now I understand. No, that's not possible, you can link only to whole notes. In Trilium you are supposed to create smaller notes in a hierarchy so theoretically it should not be an issue.

> So, heading2 and heading3 etc. can't be completely used for the software.

Ok, I understand. It's usually called Table of Contents. It's been discussed e.g. here: #533

In short, this is rather a CKEditor feature and it would have to be implemented first there ...

**Comment by starsareintherose** [comment]
Thanks for your nice explanation. Hope the great tool better. And I will try smaller notes.
