### ISSUE TITLE
[BUG] Paste breaks on pasting lists

### ISSUE THREAD

**Issue by qxygen6** [zadam/trilium#1732]
Version: 0.45.9

To reproduce:

Open a note (works with a new and old one), select the bolded items at once:
- test
- **copy this**
  - **copy this**
  - **copy this**
  - **copy this**
- test
- test

Paste them in the note.
Nothing seems to happen.

You can't delete/cut text, you can't paste normal text and switching to another note from the side menu doesn't change the content of the note. Title, attributes and related notes change.
Restarting the app fixes the issue of being able to only enter text but text written after the bug is gone and pasted text never appeared in the first place.

Pasting nonbold nested unordered lists works and so does pasting bold text from multiple elements in an HTML page, for example.

Logs are not included since there is nothing there of value.

**Comment by zadam** [comment]
Hi, this sounds like a bug in CKEditor which is used as an editing component.

Next version of Trilium (0.47) will contain an up-to-date version of CKEditor, perhaps it's going to be fix there. If not, it might be worthwile to report this to CKEditor team.
