### ISSUE TITLE
[bug] Pasting anything into owned attrs freezes Trilium

### ISSUE THREAD

**Issue by dzerus3** [zadam/trilium#1733]
Experienced on version 0.46.3 Beta, on Linux. To reproduce, navigate to a note, click on the `Owned attrs` tab at the top, and paste any piece of text in using `Ctrl + V`. The application freezes completely for around 10-20 seconds. It is probably worth noting that once the application unfreezes, the pasted text does not get inserted (owned attrs remain exactly as they were before).

I have been able to reliably reproduce this with multiple notes from the same database and using any kind of text, from URLs to single words. Restarting the application does not resolve this issue.

Log is attached:
[trilium-2021-03-10.log](https://github.com/zadam/trilium/files/6120118/trilium-2021-03-10.log)

**Comment by zadam** [comment]
Hi, could you post an example of the string causing the freezing? Or even better record a video/gif?

As a test, I pasted URL of this issue and there's no freezing:

![](https://user-images.githubusercontent.com/617641/110842705-c0291800-82a7-11eb-8731-8f07d682c7fe.png)

**Comment by dzerus3** [comment]
Can't reproduce the issue anymore (I suppose rebooting helped?), but this would apply to any string. Originally I tried to paste a URL into an attribute of the header, after which pasting any word, combination of words, URL, or anything of the sort would cause the freeze.
