### ISSUE TITLE
[bug] Using Trilium Web Clipper causes a series of errors when saving specific page

### ISSUE THREAD

**Issue by dzerus3** [zadam/trilium#1736]
Experienced on desktop app, release 0.46.3-beta on Linux. Attempting to use the "Save whole page option" on [this page](https://www.foodtimeline.org/foodbeverages.html) results in an error from the web clipper: `Your request failed because we could not contact Trilium instance. Please make sure Trilium is running and is accessible.` Simultaneously, the desktop app produces a stream of JavaScript errors from Trilium. Log is attached, it should have the errors listed there.

It is notable that this issue does *not* apply if I copy the page contents and paste them using the `Create text note` button in the clipper. Furthermore, the error occurs on [other similar](https://www.foodtimeline.org/foodeggs.html) pages on the same site, but [some links work fine](https://www.foodtimeline.org/index.html). This seems to imply that there is an issue the website itself, not with Trilium. However, I think Trilium should handle this more gracefully rather than handing out a series of error popups.

[trilium-2021-03-11.log](https://github.com/zadam/trilium/files/6125070/trilium-2021-03-11.log)

**Comment by dzerus3** [comment]
Also of note: Trilium does appear to create the corresponding text notes in the calendar, but navigating to these notes causes a 404 error.

**Comment by zadam** [comment]
Hi, for me the clipping work OK on that specific page. Do you have latest clipper version installed? (0.2.0) Also what browser do you use?

**Comment by dzerus3** [comment]
Clipper version 0.20, on Firefox. I can't appear to reproduce this issue either anymore. However, the 404-inducing notes are still present, so I suppose that's there.

**Comment by dzerus3** [comment]
Here's the log including the errors from opening the created pages (starting at line 477)

[trilium-2021-03-11.log](https://github.com/zadam/trilium/files/6125793/trilium-2021-03-11.log)

**Comment by zadam** [comment]
hi, thank you for logs, but it's not really clear how this happens.

To get this 404 error how do you navigate to this note? Through calendar widget?

![](https://user-images.githubusercontent.com/617641/110857229-e1463480-82b8-11eb-9044-30e93f4ff927.png)

Or through the tree?

Would you be willing to create an anonymized database and send it to zadam.apps@gmail.com?

**Comment by dzerus3** [comment]
They were present on the log tree on the left, I click on them and an error pops out on top and in the log.

As for the anonymized database, I'll do it, but those notes... disappeared now. The way that it happened was I was trying to export the notes to HTML to try and see whether I could find any more info about them. When I looked inside the archive, however, the broken notes were not there (only a couple of valid test notes I created were present). I then tried deleting one of them to see what happens, but I deleted the parent instead. Upon restoring the parent, I discovered that only the valid children of the parent were restored with it.

I apologize for my poor handling of this whole thing. I feel as if there's some secret agent intentionally fixing stuff behind my back just so that I can't file the bug report properly.

**Comment by zadam** [comment]
Hi, no need to apologize! You're doing a good job with the reports!

I think the problem itself is quite elusive. I have a working hypothesis on what happened - all operations in Trilium are transactional, upon comitting the changes to the database these changes are pushed towards the frontend SPA through WebSocket so that the frontend will update itself.

But what happened here is that the import broke, transaction was therefore rollbacked, but the WebSocket updates were published anyway so the frontend then thinks that a note exists even though it does not actually exist.

I added some special handling to make sure that the uncommitted changes are not sent to the SPA clients so that they don't show these fantom notes. Hopefully it will help.

**Comment by dzerus3** [comment]
I don't think this will get fixed at this point, unless someone else can reproduce. Closing.
