### ISSUE TITLE
SQL Database

### ISSUE THREAD

**Issue by danieldaeschle** [zadam/trilium#174]
Sorry for opening another issue xD

I really want to have the choice between an MySQL/PostgreSQL and SQLite.

**Comment by zadam** [comment]
This would introduce extra complexity while providing close to zero benefit for the user. SQLite is perfectly fine for the Trilium workload.

**Comment by danieldaeschle** [comment]
use an orm and you have no more complexitivity

**Comment by jakerr** [comment]
I agree that an ORM is probably overkill for Trilium. I also agree that SQLite is more than adequate for the workload - however adding an abstraction layer would make it easier deploy a Trilium server on a cloud provider that has ephemeral storage as many of them do. Heroku and App Engine for example both support hosted databases but don't give you direct filesystem access to persistent storage as sqlite requires.

Maybe a framework like the [anydb-sql - npm](https://www.npmjs.com/search?q=anydb-sql) or [sql-client - npm](https://www.npmjs.com/package/sql-client) could provide an abstraction to make using PostgreSQL or MySQL possible without adding to much complexity to the project.

**Comment by OJFord** [comment]
Another benefit would be that if you already have the pg (or whatever) DBMS then Trilium can just slide in to the existing backup policy etc. rather than also backing up the disk storage, or adding a job to dump from sqlite.

**Comment by YQGong** [comment]
> Another benefit would be that if you already have the pg (or whatever) DBMS then Trilium can just slide in to the existing backup policy etc. rather than also backing up the disk storage, or adding a job to dump from sqlite.

agreed!
