### ISSUE TITLE
[Question] Is there a way to make this work in android (mobile)

### ISSUE THREAD

**Issue by JunkyardCat** [zadam/trilium#1741]
Hi I really like to try this out and wanted to know if theres a way to edit notes on the go like on a smartphone so sync and edit. what kind of file does trillium have? is it .md or a db or something? also is there something like a community forum or something where i can ask these kinds of questions

**Comment by zadam** [comment]
Hi, there's discussion forum right here on github: [https://github.com/zadam/trilium/discussions](https://github.com/zadam/trilium/discussions)

If you install the web/server version then that one provides also a mobile frontend which is somewhat usable on Android. There's no Trilium app for Android.

Trilium uses SQLite DB so it can't be edited with e.g. Markdown editor ...

**Comment by JunkyardCat** [comment]
where is the installer for the mobile front end

**Comment by zadam** [comment]
There's no specific installer for mobile frontend. You just need server installation, mobile frontend is part of it: https://github.com/zadam/trilium/wiki/Server-installation
