### ISSUE TITLE
UI does not display properly when it is not full screen

### ISSUE THREAD

**Issue by dzerus3** [zadam/trilium#1745]
Trilium desktop app, version 0.46.4-Beta on Linux. Attempting to make the app half-sized vertically makes the top bar look strange. It appears as if the buttons with the description are to big to fit in such a small space, and put their description text on a new line. This causes some buttons to get cut off, while others move over other parts of the UI. This is what it looks like:

![image](https://user-images.githubusercontent.com/60197566/111107410-05518200-8514-11eb-8923-088f804a25b8.png)

In similar circumstances, the browser version of Trilium (same version) looks a little better, though not ideal:

![image](https://user-images.githubusercontent.com/60197566/111107464-1bf7d900-8514-11eb-8aa9-fc61f64b47a4.png)

**Comment by dzerus3** [comment]
This is probably a low priority issue, but I think the easiest way to fix this would be to make the description text next to the buttons disappear when the window is below a certain size.

**Comment by zadam** [comment]
Yep, noticed this as well with the addition of Quick search which lowered the amount of available space.

It's not a high priority issue, I might tackle it as part of the planned visual redesign ...

**Comment by zDEFz** [comment]
Have to say, I cannot live with those changes and will revert back.

![image](https://user-images.githubusercontent.com/24463722/111252410-5a26f280-8611-11eb-911c-a6e72d0d0b08.png)

**Comment by dzerus3** [comment]
> BTW, can we hide those # hashtags?

There is an option in the settings, under appearance called Heading Style. Setting it to plain will remove the hashes.

**Comment by zDEFz** [comment]
> > BTW, can we hide those # hashtags?
> 
> There is an option in the settings, under appearance called Heading Style. Setting it to plain will remove the hashes.

thanks.
But I still wonder why the amount of items displayed in a single screen has grown so vast.
Should rather be as little as possible but as much as needed.
