### ISSUE TITLE
Request: paste tables

### ISSUE THREAD

**Issue by Vaelek** [zadam/trilium#175]
Being able to paste from Excel into table format would greatly increase the usability for me as a lot of my notes would be focused around Excel data and tables.

Even if I have to massage the data first, being able to paste into tables from any format would be an improvement.

**Comment by zadam** [comment]
This is mainly editing component responsibility and it looks like they started working on it: https://github.com/ckeditor/ckeditor5-paste-from-office

Right now what you can do is to export the sheet to HTML and open it in web browser - copy & paste tables from web browser already works.

**Comment by zadam** [comment]
pasting tables from excel seems to work now
