### ISSUE TITLE
[Question] CLI commands

### ISSUE THREAD

**Issue by Typhonragewind** [zadam/trilium#1757]
Is there any way/documentation on CLI commands for Trillium? For the life of me i couldn't find them, but I'm known to be airheaded, so if it exists in an obvious place, please pardon me.

My end goal here is to periodically and automatically export notes from trilium (even if it has to be the entire root folder i'm happy with it). Would this be possible ?

Also, i've been using this software a lot lately, it's pretty amazing!

**Comment by zadam** [comment]
Hi, currently there's no CLI and it's possible to trigger export only from the UI. Having CLI or similar interface (perhaps REST) implemented is planned but there isn't any clear timeline.

**Comment by Typhonragewind** [comment]
> 
> 
> Hi, currently there's no CLI and it's possible to trigger export only from the UI. Having CLI or similar interface (perhaps REST) implemented is planned but there isn't any clear timeline.

Alright, thanks for the confirmation!
