### ISSUE TITLE
Click on search button create new sub-pages

### ISSUE THREAD

**Issue by cmuench** [zadam/trilium#1759]
![20210317175054](https://user-images.githubusercontent.com/211294/111506162-a5442100-8749-11eb-813b-b4ba870a5979.png)

OS: Arch Linux
Trilium Version: 0.46.5
DB version: 183
Build date: 2021-03-14T22:56:27+01:00

[trilium-2021-03-17.log](https://github.com/zadam/trilium/files/6158171/trilium-2021-03-17.log)

**Comment by zadam** [comment]
Hi, so this is a feature actually. Full search is now always "saved search". There are some advantages to it like automatic search history and unification of "normal search" and "saved search".

If you don't want these notes to pollute your day notes you can create create some other note somewhere aside and add `searchHome` label to it - all the search notes will be then created there.

**Comment by Engr-AllanG** [comment]
This isn't my favorite feature due to all the clones. Perhaps this isn't a big deal, but I don't like having pretty much my entire tree cloned. I have been using the quick search more because of this, and maybe thats the solution

**Comment by cmuench** [comment]
@zadam Thanks for clarification.

**Comment by zadam** [comment]
> This isn't my favorite feature due to all the clones.

@Engr-AllanG that's actually not (fully) intended. Search notes are supposed to be lazy and "clone" from a search note should appear only when the search was explicitly triggered. So far the search note results loading was not fully lazy so the "clones" appeared also when not needed. This has been now fixed in master.

**Comment by Engr-AllanG** [comment]
@zadam That's great! I think that will fix my "issue".

thanks
