### ISSUE TITLE
Blank "Read-Only" notes are uneditable. 

### ISSUE THREAD

**Issue by netnem** [zadam/trilium#1760]
V46.5 - node v12

On my root Note, I have #readOnly(inheritable) to apply to all subnotes by default.  So even new notes I have to hit "edit" before adding the first line.

When adding a new note, the "Edit" button is masked. When "Read-only" is applied to a blank note, it is uneditable.  Workaround is to remove read-only. Write anything into the note, then reapply read-only.

Steps to reproduce:

- Create a parent note with #readOnly(inheritable) 
- Create a new blank note
- Try to edit the new note.

**Comment by zadam** [comment]
Hi, fixed, will be in the next stable version.
