### ISSUE TITLE
installation failed on RPI4

### ISSUE THREAD

**Issue by rundon** [zadam/trilium#1761]
trilium:v0.46.5
nodejs:v12.21.0
[trilum.log](https://github.com/zadam/trilium/files/6161511/trilum.log)

**Comment by Myzel394** [comment]
Maybe you can take a look at docker. Since 0.48 docker versions also work on a raspberry pi.

Example configuration
```docker
version: '3'
services
    trilium:
        container_name: trilium
        image: zadam/trilium:0.48.5
        restart: on-failure:5
        volumes:
            - ./trilium:/home/node/trilium-data
```
