### ISSUE TITLE
[Probably Bug] Cut & paste section to sub-note

### ISSUE THREAD

**Issue by 1andro1** [zadam/trilium#1765]
Hello,

I am using Trilium Note 0.46.5 on windows 10. When I try to make a Cut & paste section to sub-note, the programs crates new note, with default name, but the note is empty. The selected text is also not cut.

In the old 0.46 version the problem was also present.

[trilium.log](https://github.com/zadam/trilium/files/6172362/trilium.log)

Best Regards

**Comment by zadam** [comment]
Hmm, unfortunately I can't reproduce this. It always seems to work correctly for me ...

**Comment by 1andro1** [comment]
In another computer the problem is also not present. I guess it has to do with the windows on the other computers.

Many Thanks!

**Comment by NorPhi** [comment]
I can confirm that the cut to new note feature randomly breaks on Arch Linux, too. It then takes a restart (or several) of Trilium to get it working again. This is probably related to issue #1182 . I was pasting text formatted in a different markdown flavour as into notes and tried to move sections of those before fixing the _bad_ markdown.  Maybe that crashes the cut&move script?

**Comment by damscal** [comment]
Same bug, Windows 10 0.47.2 , restart did not fix it

relevant log:

```
21:55:55.642 200 GET /api/notes/gMP0qMjxCCyh took 1ms
21:55:55.684 204 PUT /api/options took 1ms
21:55:55.687 200 GET /api/notes/ygeRNMYErNCg took 0ms
21:55:56.671 Slow 200 GET /api/similar-notes/gMP0qMjxCCyh took 37ms
21:55:56.681 200 GET /api/notes/gMP0qMjxCCyh/revisions took 1ms
21:56:00.626 204 POST /api/recent-notes took 1ms
21:56:02.017 200 POST /api/notes/gMP0qMjxCCyh/children?target=into&targetBranchId=undefined took 6ms
21:56:02.021 200 POST /api/tree/load took 0ms
21:56:02.087 200 GET /api/notes/qRuxLuUqVA5v took 0ms
21:56:02.129 204 PUT /api/options took 1ms
21:56:03.084 Slow 200 GET /api/similar-notes/qRuxLuUqVA5v took 10ms
21:56:03.086 200 GET /api/notes/qRuxLuUqVA5v/revisions took 1ms
21:56:03.871 200 PUT /api/notes/qRuxLuUqVA5v/change-title took 4ms
21:56:03.884 200 GET /api/notes/qRuxLuUqVA5v took 2ms
21:56:03.913 Slow 200 GET /api/similar-notes/qRuxLuUqVA5v took 27ms
21:56:04.874 200 PUT /api/notes/qRuxLuUqVA5v/change-title took 4ms
21:56:04.911 Slow 200 GET /api/similar-notes/qRuxLuUqVA5v took 28ms
21:56:05.542 200 GET /api/notes/ygeRNMYErNCg took 0ms
21:56:05.576 204 PUT /api/options took 1ms
21:56:06.546 Slow 200 GET /api/similar-notes/ygeRNMYErNCg took 14ms
21:56:06.550 200 GET /api/notes/ygeRNMYErNCg/revisions took 1ms
```
