### ISSUE TITLE
shortcuts for search not work

### ISSUE THREAD

**Issue by tomjamescn** [zadam/trilium#1769]
shortcuts for search not work, including: Ctrl + s and Ctrol + Alt +s.

version:  0.46.5
os: windows 10 and mac OS X
browser: chrome

**Comment by zadam** [comment]
Hi, `CTRL+S` will by default focus the quick search input in the top right (this is a change from 0.45 and older). Does this not work?

About `CTRL+ALT+S`, what should it do? It's not a default shortcut.

**Comment by tomjamescn** [comment]
@zadam thanks for your response. CTRL+S works for focusing the quick search input, I'm not familar with the 0.46.5 😅.

I think Ctrl+Alt+S open a new search tab for root node if possible.

I'll close this issue.

PS: trilium this a very great project, thanks you!
