### ISSUE TITLE
Markdown Import Headers

### ISSUE THREAD

**Issue by StructByLightning** [zadam/trilium#177]
Fourth level headers and beyond are imported as plain text. 

"#### Emotional Motivation"
becomes
"Emotional Motivation"

I also noticed Trilium's GUI only supports up to third level headers, and that typing "#### test" character by character does nothing.

**Comment by zadam** [comment]
You're right. Interestingly this is blocked by [CKEditor missing icons for H4-H6](https://github.com/ckeditor/ckeditor5-heading/issues/112) - maybe I shouldn't wait for them and create some myself.

**Comment by StructByLightning** [comment]
Do you have the svg file for the icons? I can probably put something together in Inkscape if you want.

**Comment by zadam** [comment]
SVG icons for H1-H3 are here: https://github.com/ckeditor/ckeditor5-heading/tree/master/theme/icons

It would be awesome if you could create them for H4-H6, I'd then include them into Trilium asap.

**Comment by zadam** [comment]
Eventually I solved this by using dropdown instead of individual icons for each heading.
