### ISSUE TITLE
Safari map bug

### ISSUE THREAD

**Issue by mopsicus** [zadam/trilium#1773]
Seems Safari 14.0.3 (16610.4.3.1.7) render map with bug:
<img width="605" alt="Снимок экрана 2021-03-20 в 23 31 47" src="https://user-images.githubusercontent.com/17999592/111884770-bce30a00-89d4-11eb-9d2c-4b98a01e6e54.png">

**Comment by zadam** [comment]
Hi, Safari browser is not supported (mainly because it's not available on non-Mac platforms). Only Blink (Chrome) and Gecko (Firefox) are supported.
