### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by StructByLightning** [zadam/trilium#178]
This is a feature request, not a bug report.

Since Trilium is Electron, how about letting the user inject custom CSS? This [StackOverflow](https://stackoverflow.com/questions/15505225/inject-css-stylesheet-as-string-using-javascript) page suggests ways to apply a string of CSS to the view and since Trilium isn't a cloud app you don't have to worry about sanitizing it for malicious attacks.

**Comment by zadam** [comment]
[This is already supported](https://github.com/zadam/trilium/wiki/Themes#custom-css).

**Comment by StructByLightning** [comment]
Awesome! I must have overlooked that section.
