### ISSUE TITLE
[Feature] Auto-hide large code notes until you click "show anyway"

### ISSUE THREAD

**Issue by patrickjm** [zadam/trilium#1781]
For example, when installing the Allure theme, the UI can become very laggy when displaying the code editor for such a large CSS file.

Over some arbitrary size limit, maybe the UI can show a warning with a link to display the code note if you really want to.

An example from VS Code of what I imagine this would look like (but using different copy):

![image](https://user-images.githubusercontent.com/4460805/112074072-66480e00-8b43-11eb-829e-5a8a0bda53d3.png)

**Comment by zadam** [comment]
Hi, this is already implemented - for code notes over 30 KB Trilium displays:

![](https://user-images.githubusercontent.com/617641/112220052-1a21ca00-8c26-11eb-86a6-12dd2aaac929.png)

... and you need to click on Edit button to activate full editor.

Can you link to / attach here the big CSS which is slow?
