### ISSUE TITLE
password can be changed to an empty string

### ISSUE THREAD

**Issue by NorPhi** [zadam/trilium#1785]
Not sure if this is a bug or a feature but the password can be changed to an empty string in the options. Usually this is a bad thing, although for desktop only use it may be acceptable? I mean I would switch off password and encryption anyway if I could... I didn't find any mention of this so I felt like I should bring it up.

Version 0.46.5 on Arch Linux

**Comment by zadam** [comment]
There's just no strength/length password validation - use can choose any password they want, including empty string or "password".

**Comment by NorPhi** [comment]
As annoying as it may be, there usually is merit in forcing users to pick a safe password otherwise there is no point in forcing passwords. I found this by hitting enter after typing the old password, assuming the cursor would jump to the next field, not confirming the change with two empty strings. So it's easily done by accident. Not sure what implications that has but to me it seems like something that probably shouldn't happen.

That aside, great work, it already reduced the clutter of notes on my desk by a lot.

**Comment by phoenixbug** [comment]
> There's just no strength/length password validation - use can choose any password they want, including empty string or "password".

When creating an account the frontend checks the password length and won't allow an empty password
