### ISSUE TITLE
Markdown autoformatting "[]" does not create a new task

### ISSUE THREAD

**Issue by jiri-matejka** [zadam/trilium#1787]
While editing a note, I'd like to create a task with autoformatting feature, but the shortcut ("[]") followed by a space does not do anything. Other shortcuts like *,-,1.,## and > works normally.

I am on Trilium 0.45.10, log file:
[trilium-2021-03-24.log](https://github.com/zadam/trilium/files/6195696/trilium-2021-03-24.log)

**Comment by zadam** [comment]
This is supported in newer version of CKEditor which is not yet in stable Trilium release but will be in the future 0.47 (already is in master).

**Comment by jiri-matejka** [comment]
Great, thank you!
