### ISSUE TITLE
Cannot use just any icon with TODO notes

### ISSUE THREAD

**Issue by morciej** [zadam/trilium#1791]
Trilium Ver. 0.46.5
[trilium-2021-03-24.log](https://github.com/zadam/trilium/files/6200939/trilium-2021-03-24.log)

When trying to **replace the default icon for a TODO note**, some icons, when selected, are not displayed.

For example #iconClass="`bx bxs-low-vision`" works, but "`bx bx-low-vision`" **does not show, instead the default "DOC" icon** shows. The attribute is nonetheless is saved correctly. These same icons **are displayed fine when replaced on plain notes**.

Same after reload.

**Comment by morciej** [comment]
When I created an "Empty Task" note, and removed its attributes, the other notes inheriting from it can set icon without any problems.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. The problem was in the conflict between icon defined in the task template and on the task itself -  algorithm attempted to use both which is silly of course and (random) one won.

This is fixed now - the icon defined on the note has a higher priority.
