### ISSUE TITLE
How find duplicate or cloned notes?

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1795]
Hi Zadam
I'm looking for a **find cloned notes** feature
I have trouble with these cloned notes,Sometimes I can't manage to find the original location of my clones notes
Wish there was a button to retrieve the original ones and all cloned notes
Thanks for a reply

**Comment by zadam** [comment]
Hi you can find all the cloned notes with search:

![](https://user-images.githubusercontent.com/617641/112732549-eb179b00-8f3a-11eb-923c-0b233d85fc3d.png)

Explanation: cloned note has multiple parent notes since it's placed into multiple places in the tree.

**Comment by Rsose** [comment]
> Hi you can find all the cloned notes with search:
> 
> ![](https://user-images.githubusercontent.com/617641/112732549-eb179b00-8f3a-11eb-923c-0b233d85fc3d.png)
> 
> Explanation: cloned note has multiple parent notes since it's placed into multiple places in the tree.

It seems to not work though this way
I tried it but it came out all sub-notes

Is there any way to find the same clonen notes via note's name?
E.g I want to find note "Mobile-device" and all cloned notes that have name"Mobile-device"

**Comment by Rsose** [comment]
The problem is that the result found in this way(**note.title=Mobile-device**)will only be few results or just one
In fact, there are many cloned notes as results, but the search does not work at all

Now there are a lot of **starred**(*) notes(**which are cloned notes**),they will make me more and more confused in my trilium notes!

**Comment by zadam** [comment]
I'm not sure what exactly is the problem ...

Anyway `note.title=Mobile-device` probably doesn't do what you want, correct syntax would be `note.title="Mobile-device"`

**Comment by Rsose** [comment]
Another thing is that sometimes the notes are cloned (**duplicated them to another path**)
but when I try to create subnotes under **cloned notes** in another path, but they(**subnotes**) are not synced to the original path.
e.g
- test 1 *
  -subnotes
  -subnotes

- test 1 * 
  -subnotes
  -subnotes
  -takeaway
Sometime it just wont sync with original one!
I don't know this is an issue or I'm doing something wrong

**Comment by Rsose** [comment]
> I'm not sure what exactly is the problem ...
> 
> Anyway `note.title=Mobile-device` probably doesn't do what you want, correct syntax would be `note.title="Mobile-device"`

![image](https://user-images.githubusercontent.com/51273534/112733937-0b4b5800-8f43-11eb-9bad-2cfca4317686.png)

Look at this pic

**Comment by zadam** [comment]
> but when I try to create subnotes under **cloned notes** in another path, but they(**subnotes**) are not synced to the original path.

This sounds like a bug. They should be "synced" across all clones. I can't reproduce it, but that of course doesn't mean it can't happen. In that case it would affect only the display and app reload (CTRL-R) should fix it.

> just one but should be 2

There's some misunderstanding somewhere.

All clones are actually just one note, but it's cloned into multiple places in the tree. Search will show notes, not the placements (clones). Since there's just one note, search shows 1 "Device" result.

I did not get what the image with "They are subnotes" is supposed to mean ...

**Comment by Rsose** [comment]
>All clones are actually just one note, but it's cloned into multiple places in the tree. Search will show notes, not the placements (clones). Since there's just one note, search shows 1 "Device" result.

Well my request is finding all positions(paths) of same cloned notes...Cos I should delete some of them not all cloned notes

>I did not get what the image with "They are subnotes" is supposed to mean ...

It doesn't matter it just makes you understand there are subnotes under Device note XD

**Comment by zadam** [comment]
There's a button to get list of clones for a given note:

![](https://user-images.githubusercontent.com/617641/112736123-9ed75580-8f50-11eb-8061-1ff8b3185aff.png)

perhaps that's what you're looking for?

**Comment by Rsose** [comment]
> There's a button to get list of clones for a given note:

Yes 🍡  that's what I want
