### ISSUE TITLE
Decompress file(Markdown zip file) with error meta.json

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1798]
Hi Zadam
I tried to export my notes as Markdown zip file,I got problem when I decompress them
look at this follow pic:
![image](https://user-images.githubusercontent.com/51273534/112736409-a0a21880-8f52-11eb-93c4-ec58e7081640.png)

It appeared many data errors don't know how to solve them

**Comment by zadam** [comment]
Hi, this is a known problem, see e.g. #1734 and #1122.

ZIP files are not actually corrupted but windows unzip has problems with them ... :(

**Comment by zadam** [comment]
Fixed in https://github.com/zadam/trilium/issues/1938
