### ISSUE TITLE
cssClass does not affect note title

### ISSUE THREAD

**Issue by Mangiola** [zadam/trilium#1799]
As far as I know, `cssClass` only applies to a note's body, its tab, and the tree. Having it also affect a note's title (and possibly the attribute container underneath it) would open up a lot of possibilities for theming.

**Comment by zadam** [comment]
Hi, so the way I fixed that is that CSS classes will be set on the root widget instead of some selected widgets. This allows controlling the whole screen per-note.

This is a potentially breaking change though. It's been committed to master, so in future 0.47.
