### ISSUE TITLE
Notifications / alarms

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#18]
Add ability to add simple alarms into notes, ideally by just inserting text into note, e.g. something like 

@notify tomorrow at five

We don't need to provide any text since that's what the surrounding note is supposed to be.

This has a problem of being relative to present time, but when this is evaluated in the future, value will be different. It would be easier to always specify full date/time like "2018-02-01 17:00:00" but that's way more cumbersome.

At specified date/time, user is notified - with electron we can trigger native notification, in webapp we need to provide some fallback. Once the user "acknowledges" the notification, this is saved and synced across instances. There should be also some way to see all past and upcoming alarms/notifications.

**Comment by zadam** [comment]
Pretty unclear and not aligned to current concepts, closing.

**Comment by safesparrow** [comment]
I was about to raise a new issue when I saw this one. I know it's closed, but I would like to ask:
Is there a way to show notifications from the Scripts API?
NOTE: I'm not familiar with how Electron works
I was able to show a notification, but it's not a persistent one, it doesn't show up in the system UI (I'm using Ubuntu 18.04), it goes away after a few seconds and you can't use things like actions.

Sample code:
```
Notification.requestPermission().then(function(result) {
    let myNotification = new Notification('Title', {
      body: 'Lorem Ipsum Dolor Sit Amet',
      requireInteraction: true,
      actions: [
        {
          action: 'archive',
          title: 'Archive'
        }
      ]
  });
});
```

@zadam Do you have any information on how to make this work?
I was thinking of having some kind of reminders functionality in Trilium based on notes with date&time specified.

**Comment by zadam** [comment]
I have not tried it, but it should be possible either from electron APIs or even from HTML5 spec. Known electron apps like Slack are using this extensively ...

**Comment by fivestones** [comment]
Has anyone tried this and made it work? I'd like to do exactly what @safesparrow describes wanting to do.
I'm not familiar with how Electron works either.

**Comment by ewlnwtz** [comment]
I really would love to see the @zadam request implemented in Trillium. Has there been any workaround maybe as @safesparrow  suggested that one could implement in the meantime?
