### ISSUE TITLE
[macOS] No clipboard integration

### ISSUE THREAD

**Issue by Reinmar** [zadam/trilium#180]
I've built trilium using the steps described in https://github.com/zadam/trilium/issues/115.

When I opened the app and tried to copy/paste anything, it doesn't work. Neither does Cmd+C fill the clipboard nor Cmd+V allows pasting anything. 

Additionally, there's no context menu but I'll report this in a separate ticket (https://github.com/zadam/trilium/issues/181).

**Comment by zadam** [comment]
Unfortunately, MacOS is not supported since I don't have a mac to test Trilium on (and there's no legal to have a Mac VM).

**Comment by Reinmar** [comment]
I understand. I could test it. But I was curious first whether the clipboard integration works fine on other OSes.

**Comment by cadorn** [comment]
Without clipboard integration Trilium is useless. Looking forward to when this works on macOS.

**Comment by zadam** [comment]
@cadorn CTRL-C / CTRL-V should work in 0.25.1-beta

I also just released 0.25.2 which should support also CMD+C/CMD+V etc., but I could not test it myself since I'm not an owner of any keyboard with CMD key.

**Comment by cadorn** [comment]
@zadam Tested CMD+C/CMD+V with 0.25.2 on macOS and it is working! Thanks! Now I can try things out more.
