### ISSUE TITLE
Hover over internal links broken theme background on pop-up.

### ISSUE THREAD

**Issue by reefland** [zadam/trilium#1802]
Version 0.46.6.

I use theme "PurpleRain". When I hover over an Internal Trilium Link, the popup of the page rendered has a white background which is fairly unreadable when using a dark them like PurpleRain.  I can't get the pop-up to respect the background color of the selected theme.

I have two instances using Trilium Desktop and one instance using Trilium Server.  The behavior happens on all 3 instances.  I even tried Firefox vs Chromium against the Trilium Server page same result in both.

**Comment by zadam** [comment]
"PurpleRain" is not an official theme. I guess it would be best to report this (and fix it) by the theme's author.

**Comment by reefland** [comment]
Doh..  my bad. Closing issue.
