### ISSUE TITLE
How to make folders uneditable?

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1804]
Hi Zadam
I usually use **Obsidian** to plot my graph views
But Obsidian doesn't support folder's content(that's not Editable),when I export Trilium MD files then open them with Obsidian.The problem is that Obsidian will lose or will not recognize all contents of Folders which are exported by Trilium.
Trilium is my main tool to write and manage files,but,is it possible to add a feature that makes Trilium Folders uneditable?
Make folder like an **TOGGLE BUTTON**
Probally my explanation will confuse you,I suggest you download Obsidian then you will get it what I mean

I think this way also makes Trilium and Obsidian an compatible solution for datas(Markdown files)

**_NOTE:_**Obsidian's folder is like a **TOGGLE BUTTON** and it's just used for expanding and collapsing notes.

**Trilium** for managing all of my files
**Obsidian** for platting my graph views

Waiting for a reply 
Thanks

**Comment by zadam** [comment]
Sorry, but this feature doesn't really make sense beyond solving a corner case for integration with one specific tool.

Beyond that there would be obvious problems - you have an ordinary note, fill it with content and create a child note ... and now you have "folder" with content anyway.

If you have limited number of folders you want to protect then you can manually assign them a `readOnly` label which will make then "uneditable".
