### ISSUE TITLE
Trilium 0.46.6 - Can not scroll note content on mobile view (Android Chrome & Firefox)

### ISSUE THREAD

**Issue by HiFiJ** [zadam/trilium#1807]
Hello everyone & esp. Zadam,
with version 0.46.6 it seems impossible for me to scroll any opened note (protected or not) when on mobile browsers like Firefox or Chrome on Android. Deleting website data did not solve the issue, not sure what else to do to possibly fix this...
Is this something on my end, or a more general problem?
Thanks again for your great work,
best regards

Joost

**Comment by zadam** [comment]
Hi, are you sure your server has 0.46.6? I'm asking because scrolling was broken on older releases but should be fixed specifically in 0.46.6. Just tested it myself and seems to work fine for me ...
