### ISSUE TITLE
"sync status" "sync update in progress" constantly flashing on desktop version (windows) 

### ISSUE THREAD

**Issue by andreabolandrina** [zadam/trilium#1809]
Hi,

As per title, the "sync status" popup is constantly flashing on the desktop version (windows) saying "sync update in progress".

This started happening after upgrading the server to 0.46.6.
The Windows client I'm running is 0.46.5 (as that's the latest provided by chocolatey at this point).

This also causes the following command to be using 30/40% of CPU (normally is less than 5%).
`
node ./src/www
`

Here is the logs from the server when the client is running:
```
07:34:52.876 Content hash computation took 27ms
07:34:52.877 Slow 200 GET /api/sync/check took 28ms
07:34:52.953 Added sector z of notes to sync queue in 2ms.
07:34:52.954 204 POST /api/sync/queue-sector/notes/z took 3ms
07:34:52.968 Added sector z of note_contents to sync queue in 1ms.
07:34:52.968 204 POST /api/sync/queue-sector/note_contents/z took 1ms
07:34:52.980 Added sector F of branches to sync queue in 2ms.
07:34:52.981 204 POST /api/sync/queue-sector/branches/F took 3ms
07:34:52.991 304 GET /api/setup/status took 0ms
07:34:52.999 200 POST /api/login/sync took 2ms
07:34:53.054 204 PUT /api/sync/update took 2ms
07:34:53.068 Returning 34 entity changes in 2ms
07:34:53.069 200 GET /api/sync/changed?lastEntityChangeId=325718 took 3ms
07:34:53.088 200 GET /api/sync/changed?lastEntityChangeId=325752 took 1ms
07:34:53.139 204 POST /api/sync/finished took 1ms
07:34:53.175 Content hash computation took 23ms
07:34:53.175 Slow 200 GET /api/sync/check took 23ms
07:34:53.265 Added sector z of notes to sync queue in 1ms.
07:34:53.266 204 POST /api/sync/queue-sector/notes/z took 3ms
07:34:53.280 Added sector z of note_contents to sync queue in 1ms.
07:34:53.280 204 POST /api/sync/queue-sector/note_contents/z took 1ms
07:34:53.292 Added sector F of branches to sync queue in 1ms.
07:34:53.293 204 POST /api/sync/queue-sector/branches/F took 2ms
07:34:53.302 304 GET /api/setup/status took 0ms
07:34:53.309 200 POST /api/login/sync took 1ms
07:34:53.362 204 PUT /api/sync/update took 2ms
07:34:53.377 Returning 34 entity changes in 2ms
07:34:53.379 200 GET /api/sync/changed?lastEntityChangeId=325752 took 4ms
07:34:53.403 200 GET /api/sync/changed?lastEntityChangeId=325786 took 1ms
07:34:53.454 204 POST /api/sync/finished took 1ms
07:34:53.490 Content hash computation took 24ms
07:34:53.490 Slow 200 GET /api/sync/check took 24ms
07:34:53.520 Added sector z of notes to sync queue in 1ms.
07:34:53.520 204 POST /api/sync/queue-sector/notes/z took 1ms
07:34:53.531 Added sector z of note_contents to sync queue in 1ms.
07:34:53.531 204 POST /api/sync/queue-sector/note_contents/z took 1ms
07:34:53.543 Added sector F of branches to sync queue in 2ms.
07:34:53.543 204 POST /api/sync/queue-sector/branches/F took 2ms
07:34:53.554 304 GET /api/setup/status took 1ms
07:34:53.562 200 POST /api/login/sync took 2ms
07:34:53.614 204 PUT /api/sync/update took 1ms
07:34:53.628 Returning 34 entity changes in 2ms
07:34:53.629 200 GET /api/sync/changed?lastEntityChangeId=325786 took 3ms
07:34:53.648 200 GET /api/sync/changed?lastEntityChangeId=325820 took 1ms
07:34:53.698 204 POST /api/sync/finished took 1ms
07:34:53.732 Slow query took 23ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
07:34:53.738 Content hash computation took 29ms
07:34:53.738 Slow 200 GET /api/sync/check took 29ms
07:34:53.821 Added sector z of notes to sync queue in 1ms.
07:34:53.822 204 POST /api/sync/queue-sector/notes/z took 3ms
07:34:53.835 Added sector z of note_contents to sync queue in 1ms.
07:34:53.836 204 POST /api/sync/queue-sector/note_contents/z took 2ms
07:34:53.847 Added sector F of branches to sync queue in 1ms.
07:34:53.848 204 POST /api/sync/queue-sector/branches/F took 2ms
07:34:53.858 304 GET /api/setup/status took 1ms
07:34:53.865 200 POST /api/login/sync took 1ms
07:34:53.918 204 PUT /api/sync/update took 2ms
07:34:53.933 Returning 34 entity changes in 2ms
07:34:53.934 200 GET /api/sync/changed?lastEntityChangeId=325820 took 4ms
07:34:53.954 200 GET /api/sync/changed?lastEntityChangeId=325854 took 0ms
07:34:54.007 204 POST /api/sync/finished took 1ms
```

The web client works fine though.

Thanks for the amazing tool!

Regards,
Andrea

**Comment by zadam** [comment]
Hi, this activity is caused by the fact that client and server think that they have some sync inconsistency and are trying to fix it. Fix does not help, they try again ...

May I ask, do you use protected notes? There was a fix in 0.46.6 related to sync of protected notes so I wonder if that might have something to do with this ...

Otherwise it would be worth trying to downgrade the server to 0.46.5 to see if the problem disappears.

**Comment by andreabolandrina** [comment]
Hi,

I don't remember ever using protected notes, no.

I've downgraded the server to the "zadam/trilium:0.46.5" tag but made no difference...

Let me know if you can think of anything I can run to debug further.

Maybe some permission issues related to the upgrade from 0.45 to 0.46... not sure why this would affect only the desktop version though.

**Comment by diegomachadosoares** [comment]
Hi, guys.

Firts, THANKS for the awesome tool, @zadam!

Same problem here after upgrading server version from 0.45.10 to 0.46.5 (docker).
Just upgraded server to 0.46.6 to no avail.
The clients are also on 0.46.6 (but the same thing happened with the clients on 0.45.5).
I do use (very few) protected notes.

Let me know if you need more info.

Best regards,

**Comment by zadam** [comment]
Thank you both for information.

There's a bit involved way to help me debug this issue - I would need an anonymized database from both client and server:

![](https://user-images.githubusercontent.com/617641/113358359-f3f6db00-9345-11eb-878f-e18bd9b02ac0.png)

Even with an anonymized database I should be able to detect the difference which is causing the issue.

In case you would be willing to do that, please send both of them to [zadam.apps@gmail.com](mailto:zadam.apps@gmail.com)

If you just want to fix the problem then a solution which should work would be to copy `document.db` from client to server (or server to client), thus "syncing" them manually. I believe the problem originated from 0.45 -> 0.46 database migration (which did change quite a lot of things) and I assume it won't reappear after this manual sync.

**Comment by andreabolandrina** [comment]
Hi Zadam,

I've emailed you the dbs as per request.

Let me know if there is anything else I can do.

Regards,
Andrea

**Comment by andreabolandrina** [comment]
by the way, after exporting the dbs I've run "Force full sync" from the desktop client and the issue has gone away.
I hope I have not lost any note...

**Comment by zadam** [comment]
@andreabolandrina Thank you very much, I received the anonymized databases and based on that I will be able to fix the issue.

I'm happy that full sync managed to fix the issue for you, there shouldn't be any data loss. The initial analysis looks like the sync problem was caused by deleted notes trails/metadata so it didn't even affect "real data".

**Comment by diegomachadosoares** [comment]
Sorry for the delay. Passing just to say that the "Force full sync" did the trick for me as well. Thanks.
