### ISSUE TITLE
No context menu

### ISSUE THREAD

**Issue by Reinmar** [zadam/trilium#181]
I've built trilium using the steps described in #115.

I tried to use context menu in the editor but it does not open. I actually looked for copy/paste options (https://github.com/zadam/trilium/issues/180), but there's one more missing thing due to that – spellchecking (I'll report it on another ticket because it seems unrelated: https://github.com/zadam/trilium/issues/182).

**Comment by zadam** [comment]
This is because Electron by default doesn't provide context menu. 

I've never felt the need for it, but it's true that some people prefer context menu for e.g. clipboard operation so it might be worthwhile to add it.

**Comment by Reinmar** [comment]
I'd normally use keystrokes for copy/paste, but spellchecking would require the context menu.

From what I understand from https://ourcodeworld.com/articles/read/485/how-to-implement-and-enable-the-grammar-and-spellchecker-in-electron-framework, that package also handles showing context menus so perhaps those two things can be solved at once.

**Comment by zadam** [comment]
Context menu has been provided since one of the previous releases ...
