### ISSUE TITLE
Overlapping layout on mobile

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1815]
Currently running Trilium 0.46.6, desktop version on Windows 10 that syncs with the 0.46.6 Docker server image on a Ubuntu server.

When visiting the server instance in my desktop browser, everything looks great:

![image](https://user-images.githubusercontent.com/39531/113408900-8207ab80-93b0-11eb-90d6-d04624d3cf29.png)

Visiting it on mobile shows me this garbled interface: 

![image](https://user-images.githubusercontent.com/39531/113409260-3570a000-93b1-11eb-8614-7fd9ecb0bc0c.png)

This also happens with the default white theme.

Any clues?

**Comment by zadam** [comment]
Are you sure this is happening with plain unmodified mobile theme? I'm a bit suspicious since mobile frontend does not support theming so clearly some changes must have been made to the code base ...

**Comment by wwwald** [comment]
Well - the screenshot above indeed shows the results with my own custom theming enabled. The "plain unmodified mobile" theme, would that be the regular "White" option then?

With "White", I still see the same issue:
![image](https://user-images.githubusercontent.com/39531/113454882-9a57e480-9409-11eb-95e9-70d3e9dbae7e.png)

**Comment by zadam** [comment]
There's clearly still some custom styling in action - e.g. the green icons/carets are not achievable without custom CSS AFAIK.

**Comment by chee** [comment]
@wwwald try checking if any of your notes have the `#appCss` label. i had this on a note i'd forgotten about and just realised that was what was breaking my fonts ^_^

**Comment by chee** [comment]
also! check that the theme you were using was being a good citizen and defining everything under its `body.theme-name` selector in the CSS! all of the themes are loaded in and are expected to be well behaved

**Comment by wwwald** [comment]
Aha!

Turns out that I haven't been too good of a citizen all this time, not all my CSS rules were prepended by `body.theme-name`. 

Seems that the mobile view is fixed now! Thanks!
