### ISSUE TITLE
[Question] Sync to a remote server readonly

### ISSUE THREAD

**Issue by olivier-mauras** [zadam/trilium#1819]
For my use case, I want to add notes to my local instance, but make them available publicly.
I would ideally sync my local instance to a remote public one, I see there is a flag to remove auth from a server instance, but is it possible to make an instance readonly?

**Comment by zadam** [comment]
Hi, no, this is not possible ATM.

I have some plans to support publishing (sharing) notes as read-only website, but this is not going to come soon.

**Comment by olivier-mauras** [comment]
Any easy hack to prevent edition from the code side?

**Comment by zadam** [comment]
No. I really don't recommend that. Trilium is not built to be used as a publicly accessible website.

**Comment by oxdc** [comment]
@zadam Hi, is that possible to implement a custom API which returns rendered notes? Since we can [create notes outside of Trillium by an API](https://github.com/zadam/trilium/wiki/Custom-request-handler#create-note-from-outside-trilium), I think it can be used to retrieve notes, too.

**Comment by zadam** [comment]
Yes, that is indeed possible. 

With custom handlers you can provide a public website but it would be of course a bit more involved.

**Comment by olivier-mauras** [comment]
> I have some plans to support publishing (sharing) notes as read-only website, but this is not going to come soon.
Would that speed it up if it would be sponsored?

**Comment by zadam** [comment]
Sorry, no.

**Comment by zadam** [comment]
Added recently: https://github.com/zadam/trilium/wiki/Sharing
