### ISSUE TITLE
No spellchecking

### ISSUE THREAD

**Issue by Reinmar** [zadam/trilium#182]
I believe the problem is that, unlike e.g. Chrome, Electron does not provide it by default.

Some links I found:

* https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider
* https://github.com/mixmaxhq/electron-spell-check-provider
* https://github.com/electron-userland/electron-spellchecker 
* https://ourcodeworld.com/articles/read/485/how-to-implement-and-enable-the-grammar-and-spellchecker-in-electron-framework

**Comment by Reinmar** [comment]
To make spell checking work, https://github.com/zadam/trilium/issues/181 would need to be resolved first.

**Comment by zadam** [comment]
Spellcheck is provided in 0.36 (beta for now).
