### ISSUE TITLE
Feature: remove 'template' and 'relationMapLink' relations from link map

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#1820]
These two relations make my link map messy, especially when there're a lot of notes using one template or there's a relation map containing many notes.
How about just not showing them on link map?

**Comment by zadam** [comment]
Hi, this came up few times already. It's bit difficult since it can be sometimes useful to see these relations too.

But I agree that usually it's not very useful, so I removed them. Let's see how it goes ...
