### ISSUE TITLE
Bug : Heading of Edit block

### ISSUE THREAD

**Issue by oopo0** [zadam/trilium#1821]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS
[trilium-2021-04-04.log](https://github.com/zadam/trilium/files/6253799/trilium-2021-04-04.log)
![图片](https://user-images.githubusercontent.com/67009994/113494819-b4cfb200-951e-11eb-972c-05776d8e1dfe.png)
![图片](https://user-images.githubusercontent.com/67009994/113494841-f1031280-951e-11eb-8aff-34fb0b2ae08d.png)
![图片](https://user-images.githubusercontent.com/67009994/113494822-c022dd80-951e-11eb-9cb9-640e7af94714.png)
![图片](https://user-images.githubusercontent.com/67009994/113494851-1001a480-951f-11eb-9caf-5c5ff12e1c40.png)
![图片](https://user-images.githubusercontent.com/67009994/113494860-20b21a80-951f-11eb-91fa-56e37edc0c57.png)
![图片](https://user-images.githubusercontent.com/67009994/113494866-30316380-951f-11eb-993e-182d7cb71041.png)

**Comment by zadam** [comment]
Hi, it's not clear to me, what's the bug again?

**Comment by oopo0** [comment]
Sorry, I didn't clarify the problem. I just wrote "Portable Method", which is normal in Paragragh, but there will be more # symbols in Heading.
![图片](https://user-images.githubusercontent.com/67009994/113528287-b9659a80-95f2-11eb-8322-c0c506d5484f.png)

**Comment by zadam** [comment]
> I just wrote "Portable Method"

There's no text in the original bug. I still don't understand what is the problem you're reporting.

**Comment by abitofevrything** [comment]
This is due to the markdown-style editing in Trilium. Preceding lines with `#`s will cause the line to be rendered at different heading levels depending on the number of symbols. These are rendered even if they are just styling characters for clarity.

Example: 
```
## This is a secondary heading
```
Produces
## This is a secondary heading
