### ISSUE TITLE
Task manager defocus date labels before the date is completely entered

### ISSUE THREAD

**Issue by U-Bren** [zadam/trilium#1823]
Hello,
Currently, if you select the first "field" in a date label and start typing, once two characters are typed the cursor automatically goes to the next field, allowing for quickly typing a date.
However, in the task manager, once the cursor goes to the last field and a single number is typed, it refocus on the note in the tree as if the date was entirely entered, causing this kind of issues
![this](https://user-images.githubusercontent.com/30356110/113512918-4b27c600-9567-11eb-83e7-b6c7cbd4d0ed.png)
, which are especially annoying since they create antediluvian years in the journal
![journal](https://user-images.githubusercontent.com/30356110/113512939-62ff4a00-9567-11eb-9347-3f05c02361ae.png). 
Could this be fixed in trillium or is this linked to a dependency?

~~Also, could the insertDateTimeToText shortcut (alt+t) be made to also work in labels?~~ #1826

Thanks.

**Comment by zadam** [comment]
Hi, the date picker is HTML5 native input type, meaning it's handled completely in the Blink/Gecko engines and is not under application control.

> Also, could the insertDateTimeToText shortcut (alt+t) be made to also work in labels?

This is possible but please create a separate issue to track that.

**Comment by U-Bren** [comment]
Hi,
My mistake, I assumed that this behavior happens for every date field, which is not the case. I think that the code that clone the task into the journal execute every time that the date is changed instead of every time the label is unfocused.

You can test that easily by creating a task with for example a done date of 01-01-0001, selecting the year and then typing "2", "3"... What happens is a number of years are created in the journal, which should not happen seeing as we did not unfocus from the label.

![image](https://user-images.githubusercontent.com/30356110/113520648-ce134580-9594-11eb-8e3e-603015ee585a.png)

Also for some reason if one of the field in the date ever become empty (using the del key), the note seems to be refocused in the tree and so we lose the focus on the label.

It's kind of difficult to explain. Perhaps a video would be more clear?

> This is possible but please create a separate issue to track that.

Sure. Please see #1826 🙂

**Comment by zadam** [comment]
Hi, ok, I understand now what you mean.

This is an issue - task manager is listening on changes and changes are propagated immediately. I changed the demo document to allow only certain year range to mitigate this issue. You can use that as well.

Please note though, that "task manager" is meant only as an example for scripting capabilities. It's not really a "production ready" task manager.

`attribute changed`:

```javascript
if (!["task", "location", "tag", "todoDate", "doneDate"].includes(api.originEntity.name)) {
    return;
}

const tagRootNote = api.getNoteWithLabel('taskTagRoot');
const doneRootNote = api.getNoteWithLabel('taskDoneRoot');
const todoRootNote = api.getNoteWithLabel('taskTodoRoot');

if (!tagRootNote || !doneRootNote || !todoRootNote) {
    console.log("One of the tagRootNote, doneRootNote or todoRootNote does not exist");
    return;
}

const note = api.originEntity.getNote();
    
const attributes = note.getAttributes();

const todoDate = note.getLabelValue('todoDate');
const doneDate = note.getLabelValue('doneDate');

function isWithinExpectedRange(date) {
    if (!date) {
        return true;
    }
    
    const year = parseInt(date.substr(0, 4));
    
    return year >= 2010 && year < 2050;
}

if (!isWithinExpectedRange(todoDate) || !isWithinExpectedRange(doneDate)) {
    console.log(`One or both dates - ${todoDate}, ${doneDate} - is outside of expected range`);
    
    return;
}

const isTaskDone = !!doneDate;

api.toggleNoteInParent(isTaskDone, note.noteId, doneRootNote.noteId);
api.toggleNoteInParent(!isTaskDone, note.noteId, todoRootNote.noteId);

const location = note.getLabelValue('location');
const locationRootNote = api.getNoteWithLabel('taskLocationRoot');

reconcileAssignments(note, locationRootNote, location ? [location] : [], 'taskLocationNote', isTaskDone);

const tags = attributes.filter(attr => attr.type === 'label' && attr.name === 'tag').map(attr => attr.value);

reconcileAssignments(note, tagRootNote, tags, 'taskTagNote', isTaskDone);

note.toggleLabel(isTaskDone, "cssClass", "done");

const doneTargetNoteId = isTaskDone ?  api.getDateNote(doneDate).noteId : null;
api.setNoteToParent(note.noteId, 'DONE', doneTargetNoteId);

note.toggleLabel(!isTaskDone, "cssClass", "todo");

const todoTargetNoteId = (!isTaskDone && todoDate) ? api.getDateNote(todoDate).noteId : null;
api.setNoteToParent(note.noteId, 'TODO', todoTargetNoteId);
```

**Comment by U-Bren** [comment]
Thanks you very much.
I think that only the > check is really necessary, since we are entering numbers from the end in the date field, however this can't hurt anything for a few decades anyway 😃.
Please feel free to close this issue.
