### ISSUE TITLE
Note.hasLabel() does not recognize compound inheritance

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#1828]
Note A has a label `#myLabel(inheritable)`
Note B has a template relation `~template=@NoteA`
Note C is a child of Note B
myLabel is correctly shown in Inherited attrs column of Note C, however NoteC.hasLabel("myLabel") produces false
Version: 0.46.7

**Comment by zadam** [comment]
Hi, thank you for reporting this issue.

It is indeed a bug / inconsistency with frontend algorithm. It's been fixed and will be released in the next patch version.
