### ISSUE TITLE
Book note zoom level not doing anything

### ISSUE THREAD

**Issue by jstebenne** [zadam/trilium#1829]
I have a statistics book note with the attribute `#bookZoomLevel=3` set, but whatever value I put in, nothing changes. Here are two screenshots showing my issue. Between those, I did a full refresh with cache cleared.

![Screenshot from 2021-04-06 09-34-12](https://user-images.githubusercontent.com/1571895/113719332-7de2d300-96bb-11eb-993e-af39b1e3df4a.png)

![Screenshot from 2021-04-06 09-34-45](https://user-images.githubusercontent.com/1571895/113719337-80452d00-96bb-11eb-83e6-75af4652a5b4.png)

Am I not understanding what the attribute is supposed to do, or is there something wrong?

Here is the Trilium info I have:
App version: 0.46.6
DB Version: 183
Build date: 2021-03-23T23:57:48+01:00
Build revision: 1862acd1ff9261536ebc7118d35bbbd8449ba94d

**Comment by zadam** [comment]
Hi, previous versions of Trilium (up to 0.45 IIRC) supported different zoom levels for the book notes, but in 0.46 there was a big redesign and this feature was dropped. You can choose only between card view and list view. The attribute remained though, maybe I should delete the attribute in the migration script since it is currently useless ...

**Comment by TheBird956** [comment]
Good to know, is there an alternative to it? I'd like to be able to change the width of the grid items so I can see more in the preview.

**Comment by zadam** [comment]
No, there isn't an alternative beyond overriding the width with a custom CSS: [https://github.com/zadam/trilium/wiki/Themes#custom-css](https://github.com/zadam/trilium/wiki/Themes#custom-css) (but such "hacks" are not really recommended).

If you want to see more content in the preview it's better to switch to the list view.

**Comment by BrinzaBezrukoff** [comment]
I was trying to understand label, until idea to search in issues didn't come in my head )))
Seems wiki should be changed too, if you really want to deprecate this label.
