### ISSUE TITLE
Inverse relation isn't automatically created in template+inheritable inherited notes

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#1832]
Similar to #1828
The template note (Note A) has a inverse relation definition and Note C inherited it through template+inheritable. When I set NoteC->NoteD, the reverse relation doesn't appear in NoteD.
Does caa11b8 fix this?

**Comment by zadam** [comment]
Hi, I tested this scenario and after [caa11b8](https://github.com/zadam/trilium/commit/caa11b8f7e9c77c9d7514267d3d9a74e651a9c0a) it seems to create inverse relation. This makes sense since it uses the same code to retrieve labels as the fixed code. So closing ...
