### ISSUE TITLE
SqliteError: database disk image is malformed

### ISSUE THREAD

**Issue by ckocyigit** [zadam/trilium#1835]
For bug reports, docker image sha256:c34c19b40638fec4290fa9018fc38915137c464795a36c422f6156b8cb0d8917
[trilium-2021-04-02.log](https://github.com/zadam/trilium/files/6285581/trilium-2021-04-02.log)
 and also include **log files** from following location:

After updating trilium to latest the sql database got malformed and even the backups wont wo
[stdout.txt](https://github.com/zadam/trilium/files/6285589/stdout.txt)
rk. I've lost all my data.

**Comment by zadam** [comment]
Hi, did you follow the restore instructions here? [https://github.com/zadam/trilium/wiki/Backup#restoring-backup](https://github.com/zadam/trilium/wiki/Backup#restoring-backup)

It's a common mistake to not delete -shm and -wal which can cause sqlite3 to report the database as malformed ...

**Comment by obbardc** [comment]
can you check if https://github.com/zadam/trilium/issues/1837 could be your problem?

Seems like the data directory path changed.

**Comment by ckocyigit** [comment]
deleting the shm and wal file did resolve this issue. Thank you!
