### ISSUE TITLE
Latest Docker image has changed dataDirectory from /root => /home/node

### ISSUE THREAD

**Issue by obbardc** [zadam/trilium#1837]
originally `dataDirectory` was `/root/trilium-data`.

new logs:
```
App HTTP server starting up at port 8080
{
  "appVersion": "0.46.7",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-04-03T22:37:04+02:00",
  "buildRevision": "ef37a52a06b471e60f9c0f11da704283bbcef6ab",
  "dataDirectory": "/home/node/trilium-data",
  "clipperProtocolVersion": "1.0"
}
```

This caused my installation to appear as if it was not installed. There was no data loss.

To fix this I had to change the mount path the data directory and chown the files inside.

**Comment by zadam** [comment]
Hi, yes, this was caused by #1422 which made a reasonable change to drop privileges, but at the same time required manual step to migrate. Unfortunately I didn't realize this at the point of merging ...

Also discussed in #1747

**Comment by obbardc** [comment]
whoops, I should have checked the issue tracker for duplicates first!
