### ISSUE TITLE
[Feature Request] Keyboard shortcut to open link

### ISSUE THREAD

**Issue by capi** [zadam/trilium#1842]
I'm a very keyboard centric user and I'd really like to have a shortcut like `Ctrl+Enter` to open the link where the cursor currently is located (if there is one). Ideally this would behave exactly like clicking the link with the mouse.

**Comment by zadam** [comment]
Hi, I agree, this would be nice. Unfortunately this requires some knowledge of CKEditor. I would need to look into this a bit deeper. I'll add it to the backlog.

**Comment by chee** [comment]
here's a scrappy bit of jquery you can use in a `JS Frontend` note (with `#run=frontendStartup`) to be able to open an internal or external link with `alt+l` until a native solution comes along

```js
api.addButtonToToolbar({
    title: "Open Link",
    icon: "globe",
    shortcut: "alt+l",
    action() {
        let href = $(document.getSelection().anchorNode)
            .closest("a")
            .attr("href")
        if (!href) return
        if (href.startsWith("#root")) {
            api.activateNote(href)
        } else {
            open(href)
        }
    }
})
```

**Comment by capi** [comment]
@chee This works surprisingly well, thanks! Only case where it does not work for me is when it's an internal links et to follow the title of the linked page. Still, awesome and a nice work-around, until it might be natively integrated!

**Comment by zadam** [comment]
This has been implemented for while:

![image](https://user-images.githubusercontent.com/617641/174481286-8217c3a6-8c54-4345-ac6a-f7da97be1b50.png)
