### ISSUE TITLE
Sync is reported as failed on launch until manually triggered

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#1844]
v0.47.0-beta release

Connection says: 
![image](https://user-images.githubusercontent.com/69441971/114468607-4acca200-9bdb-11eb-9558-2a279a7baeae.png) until I manually trigger a sync. no server issues or anything like that. Perhaps while it is trying a sync display a different message like a spinning loading symbol?

**Comment by zadam** [comment]
Hi, after an application starts the frontend doesn't actually know what's the sync status until the next sync attempt starts. In the mean time it displayed this "unsuccessful" status but I agree that it is confusing.

I've added an extra "sync status unknown" state with better explanation ...

**Comment by sigaloid** [comment]
Thanks, feel free to close!
