### ISSUE TITLE
47.0-beta workspace?

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#1845]
47.0-beta server

When open a blank new tab, it just has the search bar to type the name of the note. The release indicated there would be workspaces to jump into...Could you show a demo of what its supposed to do?

**Comment by zadam** [comment]
![image](https://user-images.githubusercontent.com/617641/114616414-20e0b180-9ca7-11eb-97c6-69a860bd8f20.png)

It will display list of existing workspaces as quick "enter workspace" buttons. If you don't see anything then you probably don't have any [workspaces](https://github.com/zadam/trilium/wiki/workspace) defined.

**Comment by sigaloid** [comment]
To define it, paste 
 `#workspace` 
or 
 `#workspace #workspaceIconClass="bx bx-ICON" `  

with the icon name from https://boxicons.com/ into the attributes field.

**Comment by Engr-AllanG** [comment]
I guess I missed the new workspace feature when it was implemented in 0.46, and that is why I was confused. It is working properly now that I have a workspace defined. Thanks! 

This is great. I'll get a lot of mileage out of this feature
