### ISSUE TITLE
How can I cooperate to support Chinese?

### ISSUE THREAD

**Issue by starsareintherose** [zadam/trilium#1852]
How can I cooperate to support Chinese? Which file should be created?

**Comment by zadam** [comment]
There isn't any support for adding translations. Trilium is available in English only. In the short/medium term I don't plan to add such a feature, sorry.

**Comment by sigaloid** [comment]
@zadam - I'm curious why the home page has a translated readme for Chinese, but Chinese is not supported in the interface. Is that mentioned in the Chinese-language readme?

**Comment by zadam** [comment]
Chinese (and Russian) README translations are user contributed. Translating README is trivial, supporting translations in the application is not easy and requires continuous maintenance effort. It's a trade off of course. But given I'm mostly targeting technical users I think it's not that far fetched to require passive english knowledge.

**Comment by starsareintherose** [comment]
Based on the latest version, the supported language is listed.
```
Available language codes: af, bg, ca, cs, cy, da, de, el, en-AU, en-CA, en-GB, en-US, es, es-419, es-AR, es-ES, es-MX, es-US, et, fa, fo, fr, he, hi, hr, hu, hy, id, it, ko, lt, lv, nb, nl, pl, pt-BR, pt-PT, ro, ru, sh, sk, sl, sq, sr, sv, ta, tg, tr, uk, vi
```
It‘s not fair actually. Chinese is the second popular language.
But there is no way, I must respect your wishes.
Reference: https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers

**Comment by zadam** [comment]
@starsareintherose that's a list of available languages for spell check. Trilium uses Chrome's spell check, I don't know why (Mandarin) Chinese is not among the supported languages.

Trilium's UI is available in english only.

**Comment by starsareintherose** [comment]
@zadam thanks, maybe that's difficult for Chrome

**Comment by qaqland** [comment]
@zadam hi
Do you agree I change all the hard coded string in view(*.ejs) to variable strings thus it is easy to support locales. I want to do the locale part of this awesome project. 

:D

**Comment by zadam** [comment]
Hi @qaqland , sorry, support for localization is not planned. Reasons are outlined here: https://github.com/zadam/trilium/wiki/FAQ#translation--localization-support
