### ISSUE TITLE
Slow 200 GET /api/similar-notes

### ISSUE THREAD

**Issue by fravid-git** [zadam/trilium#1855]
I'm using trilium (0.46.7) in a docker container on my local server with a cname forwarding and a Dynamic DNS Service.

So I can accces my trilium instance with a subdomain like trilium.mydomain.net

In my log files I discovered a slow http-get for similar-notes for every note selection:

15:02:04.713 204 PUT /api/options took 4ms
15:02:04.717 304 GET /api/notes/MCq919T4nNiw took 2ms
**15:02:05.739 Slow 200 GET /api/similar-notes/MCq919T4nNiw took 44ms**
15:02:05.744 304 GET /api/notes/MCq919T4nNiw/revisions took 2ms

So my question is: can I hide the similar notes display completely like the sidebar to get rid of the corresponding http get request.

**Comment by zadam** [comment]
Hi, there's a way to disable it completely by creating a `similarNotesWidgetDisabled` label on a root note and making it inheritable:

![image](https://user-images.githubusercontent.com/617641/115080120-82508c80-9f02-11eb-8c1d-53f2db8107cf.png)

**Comment by fravid-git** [comment]
thx 👍
