### ISSUE TITLE
How to delete the search results!

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1860]
Hi Zadam
I found that the search results cannot be edited or deleted, I may need a delete function.(If possible, it would be best to add an editable function as well)
It's too much trouble to try to delete them one by one!
![image](https://user-images.githubusercontent.com/51273534/115135440-bf0ea780-a018-11eb-914f-5dbda68caa89.png)
Thanks

**Comment by zadam** [comment]
You can delete search results but it's done a bit differently:

![image](https://user-images.githubusercontent.com/617641/115141069-c47ce980-a03a-11eb-862f-b0166d31377c.png)

So you need to add in the "Add search option" onto "action" and choose "delete note". After that "Search & Execute actions" button.

**Comment by Rsose** [comment]
> You can delete search results but it's done a bit differently:
> 
> ![image](https://user-images.githubusercontent.com/617641/115141069-c47ce980-a03a-11eb-862f-b0166d31377c.png)
> 
> So you need to add in the "Add search option" onto "action" and choose "delete note". After that "Search & Execute actions" button.

Well thanks
I just want to selectively delete them, can I?
The way you described will delete all the searches.
For example, I got 50 results, but I only need to delete some or one or two of them,not all.

**Comment by zadam** [comment]
Yes, it will delete them all.

Deleting them selectively is currently not supported.
