### ISSUE TITLE
Export OPML v1.0 plain text only Issue

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1861]
Hi Zadam
1-**Exported OPML v1.0 but there is only title but without note's context.**
![image](https://user-images.githubusercontent.com/51273534/115137008-b1aaea80-a023-11eb-99e8-c171fbe2d8f9.png)

2-**Exported OPML v2.0 it works fine but there are HTML codes inside !**
![image](https://user-images.githubusercontent.com/51273534/115137070-123a2780-a024-11eb-8b96-4acf150e3487.png)

**ORIGINAL COPY FROM TRILIUM**
![image](https://user-images.githubusercontent.com/51273534/115137123-4c0b2e00-a024-11eb-8090-5722482ddc5c.png)

My request is to export an identical OPML to trilium notes (Even without formatting fonts will be ok!)
The main thing is to be able to export **THE TITLE AND TEXT CONTENT!(WITHOUT HTML CODES)**

**_NOTE:_** **I NEED EXPORT THEM FROM TRILIUM IN ORDER TO SYNC MY MOBILE APP** , Because, I'm writing notes on my phone with another APP, and then syncing between TRILIUM and the other software with OPML format!

THANKS IN ADVANCE
Waiting for a reply

**Comment by zadam** [comment]
If you explore the OPML v1 files you can see that the note content is there, your app just doesn't read it.

Unfortunately it seems like OPML has a lot of variations across software. I don't see implementing all the differences, sorry.
