### ISSUE TITLE
Export HTML in zip issue

### ISSUE THREAD

**Issue by Rsose** [zadam/trilium#1868]
Hi Zadam
I've been using Trilium note to write the user manual written in 4 languages(French/German/English/Chinese)
and I want to export them to HTML(in zip) format after then import them into another software.(It accepts only HTML format)
Found some export problems with HTML,well I will explain it step by step:

- **STEP1:Export Trilium Notes using HTML in zip option:**
![image](https://user-images.githubusercontent.com/51273534/115305739-128f0b80-a167-11eb-9f74-8bc7f7bb996b.png)

- **STEP2:I have an ZIP file exported called"[Oustatt Fallo](https://tmpfiles.org/19621/oustattfallo.zip)"** https://tmpfiles.org/19621/oustattfallo.zip this is link to download this TEST zip file

- **STEP3:I need to uncompress ZIP file using a open-source free software [7-zip](https://www.7-zip.org/)**
![image](https://user-images.githubusercontent.com/51273534/115306302-ee7ffa00-a167-11eb-874f-3a46fb9a792c.png)
Now we got dataerror,but the main problem is another

- **STEP4:After uncompressed file but these HTML files there are no closing tags in the end (</body> or </html>)**
![image](https://user-images.githubusercontent.com/51273534/115306996-e8d6e400-a168-11eb-962a-22b37e2cc664.png)
![image](https://user-images.githubusercontent.com/51273534/115307198-276c9e80-a169-11eb-836e-a24616962d7f.png)
![image](https://user-images.githubusercontent.com/51273534/115307284-45d29a00-a169-11eb-8fa3-d3a521b63fd1.png)
![image](https://user-images.githubusercontent.com/51273534/115307392-6bf83a00-a169-11eb-84c2-d7058816df99.png)
![image](https://user-images.githubusercontent.com/51273534/115307468-87fbdb80-a169-11eb-82c9-b1384fac19f3.png)

- **STEP5:I'm going to attach a compressed zip file by 7-zip, https://tmpfiles.org/19639/oustattfallo.zip.  Please check this zip file where you can find all these html files without CLOSING TAGS**

If you don't get it just repeat the steps that I did.Download a 7-zip software and umpressed a HTML file exported from Trilium notes.
7-zip is a good and reliable tool I don't use any other compressed file softwares.
My hope is that exported HTML files within **closing tags** ,It's trouble for me there are no closing tags !!
Could you please fix it
Thanks 
Waiting for a reply!

**Comment by Mirwaisse** [comment]
The zip file is bugged when you try to decompress it on Windows (see #1798).

My solution is to use WSL (Windows Subsystem for Linux) to unzip the exported files.

**Comment by Rsose** [comment]
> The zip file is bugged when you try to decompress it on Windows (see #1798).
> 
> My solution is to use WSL (Windows Subsystem for Linux) to unzip the exported files.

Thanks for advice Mirwaisse!
I'm not familar with Linux I think that's hard for me to do it
I still hope Zadam has the ability to solve the problem of decompression, even if the possibility is very small
But I can now open HTML files manually using Visual Studio and add missing closing tags into the file content.There are many html files exported(without CLOSING TAGS),modify them one by one will be very time-consuming and troublesome.

**Comment by Mirwaisse** [comment]
I found another solution that does not use any external software.

1. Open Powershell (Windows+R then type Powershell).
2. In the Powershell window, go the folder containing your zip file by using the command `cd`. For example, type
`cd C:\Users\YourUserName\` and press enter if `C:\Users\YourUserName\` contains the zip file.
3. Type `Expand-Archive YourFile.zip` and press enter (replace `YourFile.zip` by the actual name of the zip file).

This should unzip your archive without error (with no missing closing tags in your HTML files!)

**Comment by Rsose** [comment]
> I found another solution that does not use any external software.
> 
> 1. Open Powershell (Windows+R then type Powershell).
> 2. In the Powershell window, go the folder containing your zip file by using the command `cd`. For example, type
>    `cd C:\Users\YourUserName\` and press enter if `C:\Users\YourUserName\` contains the zip file.
> 3. Type `Expand-Archive YourFile.zip` and press enter (replace `YourFile.zip` by the actual name of the zip file).
> 
> This should unzip your archive without error (with no missing closing tags in your HTML files!)

Hi Mirwaisse
Good way to unzip files but still have problem with these missing closing tags...
Please Check this link to download my test zip file (Exported by trilium). https://file.io/4wZq5kn4v6PZ 
Could you check it for me?I have no idea where is the problem
Thanks

**Comment by Mirwaisse** [comment]
With your zip file and the method using Powershell, everything seems to be OK (no missing tags).

I rezipped the unzipped folder if you want to check: [https://file.io/QeiJxeexfp7y](url)

**Comment by Rsose** [comment]
> With your zip file and the method using Powershell, everything seems to be OK (no missing tags).
> 
> I rezipped the unzipped folder if you want to check: https://file.io/QeiJxeexfp7y
> 
> edit: I think the problem is that you tried the method using Powershell when there was already a folder called "OustattFallo". It didn't overwrite the previous files (which were missing the closing tags). Try again, but this time put your zip file in a empty folder first.

1)**7-zip**
The weirdest thing is that I use 7-ZIP to unzipp the file, and add the CLOSING TAGS into html files manually then I imported all these HTML files and folders into another software and it displayed everything perfectly.(7-zip software will work if I add these closing tags)

2)**Powershell**
However, with POWERSHELL it seems to be impossible, when I import these files there will always be some special characters displayed as garbled text.

I think it may be the special characters that cause the problem of exporting HTML from Trilium notes.
7-zip seems to be the only solution that works in my case.

**Comment by zadam** [comment]
Fixed in https://github.com/zadam/trilium/issues/1938
