### ISSUE TITLE
Include Render Note

### ISSUE THREAD

**Issue by cidious** [zadam/trilium#1869]
In 0.47.1 beta
When you include the Render Note it doesn't show the content of the note, just Title and [Download] and [Open] buttons. The Box Size option can be set to any value, no matter

In 0.46
the content of the Render Note shown in the block -- really helpful

Please revert it back, or add the option to switch on rendering.

Thank you.

**Comment by chee** [comment]
that feature seems to come back if i revert this commit: https://github.com/zadam/trilium/commit/d3cccae2dfaef9deae5d22acac4324d7fc3d5526

**Comment by zadam** [comment]
Yes, thanks to @chee for quickly pointing out the bug!

**Comment by chee** [comment]
@zadam i felt personally responsible, it was my feature request ^_^
