### ISSUE TITLE
Syntax error in #widget makes it impossible to load trilium

### ISSUE THREAD

**Issue by chee** [zadam/trilium#1874]
i'm writing a widget, and i accidentally refreshed while it was in an incomplete state:

![Execution of JS note "sidebar notes" with ID U68Hug0IShQT failed with error: Unexpected token '{'](https://user-images.githubusercontent.com/178266/115411897-663f3a80-a1e3-11eb-99ef-7fd0bdeb59d7.png)

Now trilium can't load at all, and so I can't fix the broken note

using 0.46

**Comment by zadam** [comment]
Hi, set following environment variable which will exclude all custom scripts and widgets from startup:

> TRILIUM_SAFE_MODE=true ./trilium

https://github.com/zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup

**Comment by chee** [comment]
> Hi, set following environment variable which will exclude all custom scripts and widgets from startup:
> 
> > TRILIUM_SAFE_MODE=true ./trilium
> 
> [zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup](https://github.com/zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup)

the error message should probably mention safe mode
