### ISSUE TITLE
About the shortCut to activate editBlock

### ISSUE THREAD

**Issue by Nobellcq** [zadam/trilium#1878]
It is not a bug, just a question.I like trilium, i am a hot-fan user for shortCut, so i would not like to use mouse to click editBlock icon to activate editBlock state. So how to activate editBlock status in shortCut? 
e.g. I want to insert a code block, i had to click the editBlock icon, and click the insert code block.
I want to simplify this procedure.

**Comment by zadam** [comment]
Hi, I don't think this is possible right now. I created a feature request in the CKEditor repository: https://github.com/ckeditor/ckeditor5/issues/9541

**Comment by Nobellcq** [comment]
> Hi, I don't think this is possible right now. I created a feature request in the CKEditor repository: [ckeditor/ckeditor5#9541](https://github.com/ckeditor/ckeditor5/issues/9541)

Oh great, I really appreciate it.
