### ISSUE TITLE
Drawing tools?

### ISSUE THREAD

**Issue by Gooberpatrol66** [zadam/trilium#188]
Is it planned to add drawing tools to trilium?

**Comment by zadam** [comment]
Hello, some kind of drawing support is planned, but it's still in conceptual phase and there's no date yet.

**Comment by MaxInertia** [comment]
Ditto. If drawing support is added this can be a full replacement for OneNote (for me at least).

**Comment by XXXJetfireXXX** [comment]
I guess it's now implemented as the "Canvas" note type?

**Comment by zadam** [comment]
Yes, closing.
