### ISSUE TITLE
Ctrl-space to toggle checkbox doesn't work on 0.47.1-beta

### ISSUE THREAD

**Issue by martinkoutecky** [zadam/trilium#1880]
In 0.47.1-beta (where CKeditor has been updated) the ctrl-space shortcut to toggle a checkbox stopped working. (On the other hand the shortcut "[] ..." to create a checkbox started working, which I like...).

**Comment by chee** [comment]
nice tip about `[]` to make a checkbox!!
for me, ctrl+enter toggles the checkbox?

**Comment by martinkoutecky** [comment]
@chee I see - but in 0.46 it used to be (also?) ctrl-space... I can relearn, but still it seems like a regression, no? Anyway, I guess I'm OK with ctrl-enter.

**Comment by zadam** [comment]
Hi, this seems to come from https://github.com/ckeditor/ckeditor5/pull/9057 which also provides some rationale.
