### ISSUE TITLE
Strange behavior in searching with orderBy

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#1881]
This issue needs some improvement since I can't work out a reproduction step works under any circumstances.

The following usage of orderBy may result in incorrect ordering of notes:
1. Order by more than one attribute
2. Order by an attribute not existing in all of the result notes

**Comment by zadam** [comment]
Hi, I checked order by implementation in those cases and I can confirm that there was probably incorrect behavior. I did some fixed in the master branch so you can test those once they come out in the next 0.47.X release.

Thanks for pointing this out.
