### ISSUE TITLE
"Cannot be opened because the developer cannot be verified"

### ISSUE THREAD

**Issue by fuzzthink** [zadam/trilium#1885]
Getting '"Trilium Notes" Cannot be opened because the developer cannot be verified' after trying to run the latest version 9.4.4 in macOS Catalina 10.15.4.

EDIT version file downloaded says 9.4.4. Downloaded via https://github.com/zadam/trilium/releases/tag/v0.46.9 trilium-mac-x64-0.46.9.zip

**Comment by chee** [comment]
You should be able to open it if you right click on the .app and select "open", rather than double clicking.

Alternately, you may have some success signing the app yourself:

```
sudo codesign --force --deep --sign - "/path/to/Trilium Notes.app"
```

you might need xcode (or at least xcode command line tools) installed to self-sign, i'm not sure

**Comment by fuzzthink** [comment]
Right clicking worked. Thank you!
