### ISSUE TITLE
Error when export notes with subnotes as markdown

### ISSUE THREAD

**Issue by starsareintherose** [zadam/trilium#1886]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:
Version 0.46.7
When I export notes with subnotes as markdown and I unzip the file and found all md files are empty.
logfiles are attached here
[trilium-2021-04-23.log](https://github.com/zadam/trilium/files/6362540/trilium-2021-04-23.log)
[trilium-2021-04-22.log](https://github.com/zadam/trilium/files/6362533/trilium-2021-04-22.log)

**Comment by zadam** [comment]
That's quite strange. So all the files in the ZIP are 0 size?

**Comment by starsareintherose** [comment]
[📶Manjaro指令.zip](https://github.com/zadam/trilium/files/6369006/Manjaro.zip)
See here

**Comment by zadam** [comment]
@starsareintherose 
![image](https://user-images.githubusercontent.com/617641/115952583-0698a600-a4e7-11eb-91b4-f1900a947996.png)

You can see in the screenshot that the sizes are > 0 and when I open the files I can see the content just fine ...

**Comment by starsareintherose** [comment]
> @starsareintherose
> ![image](https://user-images.githubusercontent.com/617641/115952583-0698a600-a4e7-11eb-91b4-f1900a947996.png)
> 
> You can see in the screenshot that the sizes are > 0 and when I open the files I can see the content just fine ...
> 
> What app/platform do you use to extract the ZIP?

I know what's wrong, I use windows 10 PeaZip to unzip it though one error is reported. all is well. And then I return my Archlinux, then I found it's okay to use the command unzip, but fail to use gnome unzip software. It would be the error of the gnome.
