### ISSUE TITLE
Log failed connections to sync server more gracefully

### ISSUE THREAD

**Issue by dzerus3** [zadam/trilium#1888]
Observed when running v0.46.9 on Linux, but platform should not affect this.

This is a fairly inconsequential issue, however I use a server on my LAN for sync purposes. Upon having it taken down for a day or two, I noticed that Trilium's logs now appear to be littered with a large amount of errors related to that the server is now unreachable.

Although being unable to connect to a previously working sync server is unexpected behavior, it doesn't really seem to warrant being logged as an exception when it can happen for a variety of reasons outside the scope of the program.

On a related side note, it may also be worth notifying the user that the sync server is unreachable rather than silently logging the issue.

The errors are all as follows:
```
sync failed: Request to GET http://192.168.1.154:8080/api/setup/status failed, error: Error: net::ERR_ADDRESS_UNREACHABLE
stack: Error: Request to GET http://192.168.1.154:8080/api/setup/status failed, error: Error: net::ERR_ADDRESS_UNREACHABLE
    at generateError (/home/user/.bin/trilium-linux-x64/resources/app.asar/src/services/request.js:191:12)
    at ClientRequest.<anonymous> (/home/user/.bin/trilium-linux-x64/resources/app.asar/src/services/request.js:58:47)
    at ClientRequest.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by zadam** [comment]
Hi, there's a list of exception in sync error handler which handles these more gracefully. I just added "ERR_ADDRESS_UNREACHABLE" to the list.

> On a related side note, it may also be worth notifying the user that the sync server is unreachable rather than silently logging the issue.

0.47 has a new sync status icon which will indicate that the Trilium is not connected to sync server at the moment:

![image](https://user-images.githubusercontent.com/617641/115952495-90943f00-a4e6-11eb-8529-d3ecdd64615d.png)
