### ISSUE TITLE
[Feature request] Add support for markdown checklist and table syntax 

### ISSUE THREAD

**Issue by aspieln3r** [zadam/trilium#1890]
Trilium as of now, doesnt seem to recognise markdown checklist and table syntax. I'm requesting to add this
eg of markdown checklist and table
```
### Solar System Exploration, 1950s – 1960s

- [ ] Mercury
- [x] Venus
- [x] Earth (Orbit/Moon)
- [x] Mars
- [ ] Jupiter
- [ ] Saturn
- [ ] Uranus
- [ ] Neptune
- [ ] Comet Haley

| First Header                | Second Header                |
|-----------------------------|------------------------------|
| Content from cell 1         | Content from cell 2          |
| Content in the first column | Content in the second column |

```

**Comment by zadam** [comment]
Hi, I assume you mean Markdown import.

These features are not part of CommonMark standard and therefore not recognized/parsed correctly. [This](https://github.com/commonmark/commonmark.js/) library is used for importing Markdown.

**Comment by aspieln3r** [comment]
I meant typing directly. I checked the commonmark spec and it seems that check boxes and tables are not part of the spec. 
These two are very common in markdown languages and is there any way to directly type to get these two in trilium? Like how putting a # automatically makes it a heading.

**Comment by zadam** [comment]
Ok, then it's weird since typing `[ ]` will create checkbox for me. But table syntax is not supported.

Anyway I'm not the one who develops this functionality - it's already provided in the [CKEditor](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) and that's where it would have to be added.

**Comment by aspieln3r** [comment]
oh thanks for the clarification. any idea why its not working for me?
![image](https://user-images.githubusercontent.com/48161833/115988615-2d82d500-a5d8-11eb-9401-5bfcb4691c5c.png)
