### ISSUE TITLE
Is there a visitor mode for trilium deployed on the web?

### ISSUE THREAD

**Issue by frapples** [zadam/trilium#1892]
Hello, thank you for creating this excellent product.
I deployed this product on my server, and I want to share it with my friends, but I don’t want my friends to have the permission to modify it.
Does trilium provide the feature?

**Comment by zadam** [comment]
Hi, there isn't a visitor mode yet, but it's on the roadmap in one of the next few releases.

**Comment by zadam** [comment]
Added recently: https://github.com/zadam/trilium/wiki/Sharing
