### ISSUE TITLE
Deleting a task from task manager doesnt delete it from other places like journal

### ISSUE THREAD

**Issue by aspieln3r** [zadam/trilium#1893]
Version: 0.46.9
When I add a new task, it gets automatically added to places like jornal and the tags folder. But when I delete a task from journal, or the TODO folder, its not getting deleted automatically from other places and leaves zombie files.
To reproduce: 
1. create a new task from the 'new task' button
2. delete the task from any of the folders which it was added automatically
Expected result:
The task, upon deletion from one place, gets deleted from from all the places it was automatically added to

I'm doing this from the trilium demo

**Comment by zadam** [comment]
When you're deleting the note there's a checkbox "delete all clones" (unchecked by default). If you check it, it will delete the note from all other places as well.
