### ISSUE TITLE
Unable to jump from note editing to the tree pane

### ISSUE THREAD

**Issue by cidious** [zadam/trilium#1897]
version 0.47.2 for Windows
could not jump from the editing pane to the tree pane by keyboard,
`Ctrl+.` does not work.
thanks.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue.

At first I could not reproduce this - focusing seemed to work the first time after startup. But then it stopped working.

I'm not sure what exactly is behind it, but I recently also solved another tree focus issue. With this fix the focusing seems to work for me consistently.
