### ISSUE TITLE
[Bug]Page is totally blank after start trilium when using 0.47.2

### ISSUE THREAD

**Issue by aihuasxy** [zadam/trilium#1899]
0.46.9 is OK

### screenshot

![image](https://user-images.githubusercontent.com/6761242/116332172-d7927500-a803-11eb-9b28-ad8d86d42882.png)

### Info

OS:win10
version:0.47.2
Log:
09:16:11.717 DB size: 261775 KB
09:16:14.511 Created missing option "keyboardShortcutsOpenNoteExternally" with default value "[]"
09:16:14.547 Note cache load took 31ms
09:16:15.238 App HTTP server starting up at port 37840
09:16:15.238 {
  "appVersion": "0.47.2",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-04-26T22:32:54+02:00",
  "buildRevision": "6f1b0b92fe8dcea736c15217c69512c7fee769cb",
  "dataDirectory": "C:\\Users\\XXXX\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0"
}
09:16:15.240 CPU model: Intel Core Processor (Haswell, no TSX, IBRS), logical cores: 4 freq: 2494 Mhz
09:16:15.262 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
09:16:15.262 Listening on port 37840
09:16:34.551 Table counts: notes: 1296, note_revisions: 103, branches: 1440, attributes: 777, api_tokens: 0
09:16:35.256 Slow query took 694ms: SELECT noteId FROM notes JOIN note_contents USING (noteId) WHERE isDeleted = 0 AND isProtected = 0 AND content IS NULL
09:16:35.316 All consistency checks passed (took 765ms)
09:16:37.216 Generated CSRF token UlTCie7Z-09NkHu3NSDzro2SE35LVRmMRfrw with secret _csrf=pSg4hlsFCM6ocYHzUlgz4VCK; Path=/
09:16:37.257 Slow 200 GET / took 44ms
09:16:43.992 304 GET /api/clipper/handshake took 3ms
09:17:43.989 304 GET /api/clipper/handshake took 1ms
09:18:43.984 304 GET /api/clipper/handshake took 2ms
09:19:43.981 304 GET /api/clipper/handshake took 1ms
09:20:43.987 304 GET /api/clipper/handshake took 7ms
09:21:43.985 304 GET /api/clipper/handshake took 2ms
09:22:43.987 304 GET /api/clipper/handshake took 1ms

**Comment by zadam** [comment]
Hi, that's quite weird. For now just downgrade back to 0.46.9 ...

**Comment by aihuasxy** [comment]
After rebooting os， it's ok.
