### ISSUE TITLE
Sync server handshake failed

### ISSUE THREAD

**Issue by frankcbliu** [zadam/trilium#1900]
- use trilium on Mac OS
- version 0.47.2 (0.47.2)

i run the sync server by docker:
![image](https://user-images.githubusercontent.com/36353894/116343579-46c59480-a817-11eb-9ae8-48555198b2cd.png)

but i can not visit the url [127.0.0.1:8080] on another server window:

![image](https://user-images.githubusercontent.com/36353894/116343691-83918b80-a817-11eb-8d05-e998a3e5ae3b.png)

it just pending here and return nothing.

when i try to test trilium's sync:

it show the error like this:
```
Sync server handshake failed, error: Request to GET [myserver-ip]:8080/api/setup/status failed, error: Error: net::ERR_INVALID_URL
```
 
i couldn't find solution in other issue, and my English is poor, maybe some places are not clearly described.
thanks for your help.

**Comment by zadam** [comment]
Hi, perhaps it's just missing `http://` or `https://`? The error complains about format of the URL so it's not even a network error, just wrongly typed URL ...

**Comment by frankcbliu** [comment]
> Hi, perhaps it's just missing `http://` or `https://`? The error complains about format of the URL so it's not even a network error, just wrongly typed URL ...

thanks for your reply. But i think it it not a format error, curl is support `ip:port` format like this:
<img width="659" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/36353894/116835861-df348e00-abf6-11eb-9fc8-7b4a14b6a180.png">

here i serve a vue project, and use `curl 127.0.0.1:8080` to visit, it has return.

for the problem i raised earlier, i use the [Manual server installation](https://github.com/zadam/trilium/wiki/Manual-server-installation) version and it work.

anyway, thanks for your help and your nice project.
