### ISSUE TITLE
Error when calling PUT /api/notes/lxqJvGblKttL: 500 - attempt to write a readonly database

### ISSUE THREAD

**Issue by oopo0** [zadam/trilium#1902]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

[trilium-2021-04-29.log](https://github.com/zadam/trilium/files/6395728/trilium-2021-04-29.log)
![图片](https://user-images.githubusercontent.com/67009994/116490620-68338880-a8ca-11eb-9d04-33b373c818a5.png)
![图片](https://user-images.githubusercontent.com/67009994/116490635-7386b400-a8ca-11eb-8dd9-02c46af6fa2a.png)

**Comment by zadam** [comment]
Hi, this could be caused by wrong permissions on the database file ... or perhaps you have 2 trilium instances open? Or the `document.db` open in another application? Restarting the PC might help ...
