### ISSUE TITLE
v0.47.2 fails to preview all PDF 

### ISSUE THREAD

**Issue by veritatis** [zadam/trilium#1904]
updated to v0.47.2, everything works fine, but all attached PDF files fail to load for preview in the app
![tmp1](https://user-images.githubusercontent.com/33884471/116498673-d4b78300-a8dc-11eb-9eda-4a5a15e29b8c.png)

problem solved when downgraded back to 0.46.9

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. I assume you're using windows, right? Seems to be Windows specific. I will look into this.

**Comment by veritatis** [comment]
Thank you. I'm using windows 10 pro 20H2 build 19042.964. My sync server has been down for quite a while so the sync always fails, but I guess that's not the reason for this issue. 

I think this is the log of opening a node with pdf. 

11:10:14.936 DB size: 92975 KB
11:10:15.710 Note cache load took 16ms
11:10:15.803 App HTTP server starting up at port 37840
11:10:15.803 {
  "appVersion": "0.47.2",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-04-26T22:32:54+02:00",
  "buildRevision": "6f1b0b92fe8dcea736c15217c69512c7fee769cb",
  "dataDirectory": "C:\\Users\\***\\OneDrive\\Trilium\\\\trilium-data",
  "clipperProtocolVersion": "1.0"
}
11:10:15.803 CPU model: AMD Ryzen 5 PRO 4650G with Radeon Graphics, logical cores: 12 freq: 3693 Mhz
11:10:15.813 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
11:10:15.815 Listening on port 37840
11:10:15.834 Generated CSRF token a2HZJl7w-Wtiv0mKR-mL7rdau7p1Gmx0-AzU with secret _csrf=IJUpRS06Kt9Gb3-aADWPFPT_; Path=/
11:10:15.847 Slow 200 GET / took 14ms
11:10:16.016 304 GET /api/notes/download/46632YfSLjfk took 1ms
11:10:16.019 304 GET /api/notes/download/85FmTjQmifLi took 1ms
11:10:16.026 200 GET /api/options took 0ms
11:10:16.028 200 GET /api/tree took 1ms
11:10:16.031 200 GET /api/keyboard-actions took 1ms
11:10:16.032 200 GET /api/keyboard-shortcuts-for-notes took 0ms
11:10:16.033 200 GET /api/script/widgets took 0ms
11:10:16.035 200 POST /api/tree/load took 0ms
11:10:16.398 200 GET /api/notes/Gm5b8MctEJwM took 1ms
11:10:16.432 304 GET /api/notes/Gm5b8MctEJwM/open took 1ms
11:10:17.404 Slow 200 GET /api/similar-notes/Gm5b8MctEJwM took 27ms
11:10:17.406 200 GET /api/notes/Gm5b8MctEJwM/revisions took 1ms
11:10:17.414 200 POST /api/tree/load took 3ms
11:10:17.497 200 POST /api/notes/Gm5b8MctEJwM/link-map took 1ms
11:10:18.065 200 GET /api/script/startup took 0ms
11:10:18.067 200 POST /api/tree/load took 1ms
11:10:18.069 200 POST /api/tree/load took 0ms
11:10:18.071 200 POST /api/tree/load took 0ms
11:10:19.322 200 GET /api/app-info took 0ms
11:10:21.328 204 POST /api/recent-notes took 3ms
11:10:21.498 204 POST /api/recent-notes took 0ms
11:10:28.565 200 GET /api/tree?subTreeNoteId=5Kjh1uFD57KU took 0ms
11:10:28.784 204 PUT /api/branches/WqiPENJJyGIE/expanded/1 took 0ms
11:10:29.985 204 PUT /api/branches/WqiPENJJyGIE/expanded/0 took 0ms
11:10:30.622 304 GET /api/clipper/handshake took 1ms
11:10:32.164 200 GET /api/tree?subTreeNoteId=N11Yx43pKmk3 took 1ms
11:10:32.387 204 PUT /api/branches/AVTvE4ApY9gW/expanded/1 took 0ms
11:10:34.268 200 GET /api/tree?subTreeNoteId=QZo94JxzzG3W took 1ms
11:10:34.489 204 PUT /api/branches/1fFvRPxW0hCm/expanded/1 took 1ms
11:10:35.093 200 GET /api/notes/fI3Qi1kSSyaC took 1ms
11:10:35.108 204 PUT /api/options took 1ms
11:10:36.137 Slow 200 GET /api/similar-notes/fI3Qi1kSSyaC took 57ms
11:10:36.141 200 GET /api/notes/fI3Qi1kSSyaC/revisions took 1ms
11:10:36.142 200 POST /api/notes/fI3Qi1kSSyaC/link-map took 1ms
11:10:36.143 200 POST /api/tree/load took 1ms
11:10:36.168 200 GET /api/notes/ZREpaINYDTSF took 0ms
11:10:36.182 204 PUT /api/options took 0ms
11:10:37.188 Slow 200 GET /api/similar-notes/ZREpaINYDTSF took 29ms
11:10:37.190 200 GET /api/notes/ZREpaINYDTSF/revisions took 1ms
11:10:37.191 200 POST /api/notes/ZREpaINYDTSF/link-map took 1ms
11:10:37.192 200 POST /api/tree/load took 1ms
11:10:41.151 204 POST /api/recent-notes took 1ms

**Comment by xh542428798** [comment]
I wonder whether can we add a new feature to mark pdf file like remnote pro and marginnote

**Comment by zadam** [comment]
Fixed in 0.47.5 (just being released). Also discussed in #1976
