### ISSUE TITLE
Some ckeditor features not working

### ISSUE THREAD

**Issue by aspieln3r** [zadam/trilium#1907]
version : 0.46.9
From previous discussions, I have understood that the trilium editor uses ckeditor.
But some features like using --- to create and horizontal line and [ ] to create check boxes automatically are not working for me. They remain as how I typed without getting automatically formatted into the intended feature. These two work fine on the ckeditor preview given here https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html

**Comment by zadam** [comment]
Hi,  you should update to the newest version - 0.47.2 since only newest version will contain up to date CKEditor.
