### ISSUE TITLE
How stop dodcker with all tihe data saved of Trilium

### ISSUE THREAD

**Issue by altitr** [zadam/trilium#1908]

**Comment by altitr** [comment]
Follow the command `docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/home/node/trilium-data zadam/trilium:[VERSION]`
and when reset my computer open angin,All the data is lost.
I don't want deep dive in Docker document.So just tell me ho do I do can be save all the data of Trilium。
Thank your.

**Comment by zadam** [comment]
The data should be in your`trilium-data` subdirectory of your home directory. If you run the same docker command, it will mount the directory on the same path and no data should be lost - it should just keep working ...

**Comment by altitr** [comment]
sudo docker run -d -p 0.0.0.0:8080:8080 -v ~/trilium-data:/home/node/trilium-data hlince/trilium:0-stable-arm
My user's home directory really has `trilium-data` that created by the command.
But it is always empty(no any file).
And after `sudo docker stop ` and `sudo docker run` again,I need recreate the username of trilium.

**Comment by altitr** [comment]
What's the hell？

**Comment by altitr** [comment]
It seems I have bind wrong virtual path of `hlince/trilium` image.
So what the right virtual path of trilium-data of hlince/trilium` image.

**Comment by zadam** [comment]
`hlince/trilium` is a third party image made by somebody else, it would be the best to seek the support from its author.

**Comment by altitr** [comment]
but,where he is？

**Comment by delight** [comment]
https://github.com/Howard3 ... you could have simply looked at some other images of that docker user. In the meantime he seems to have stopped pushing docker images.

@zadam close this issue - nothing to fix here !

**Comment by zadam** [comment]
We now have official ARM/x86 images: https://hub.docker.com/r/zadam/trilium/tags
