### ISSUE TITLE
Non-protected title for protected note

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#1915]
I think it would be nice to add an attribute like `#unprotectedTitle=Passwords` and have that display as the note title (with all the normal signs that it's a protected note) when not in a protected session. 99% of the time the title is not a secret and I'd like to be able to see it.

**Comment by zadam** [comment]
Hi, a workaround which might work for you (it does work for me) is adding a prefix:

![image](https://user-images.githubusercontent.com/617641/117065063-44879c80-ad27-11eb-963b-6de9fea3fe66.png)

Prefix is not part of the note (it's a property of the note's placement into the tree) and as such is not encrypted and it's visible in the tree:

![image](https://user-images.githubusercontent.com/617641/117065238-86184780-ad27-11eb-9878-cf21b1e17c48.png)

**Comment by sigaloid** [comment]
Thanks, this works great for me! If you don't have any additional plans regarding this feel free to close.
