### ISSUE TITLE
It is difficult to use Trilium on iPadOS

### ISSUE THREAD

**Issue by yllekz** [zadam/trilium#1918]
(Version 0.45.5)

This isn't a bug report as much as it's just a general user experience issue I observed. I loaded up my instance of Trilium in Safari on iOS, and tried to create a new note. I found that there was no UI button to easily create one, and any menu element that was inside a right-click menu was inaccessible to me with the touch screen alone. On a Microsoft Surface with its touch screen, you can access right click menus by long-pressing the screen in the spot where you would right-click, but on iPadOS there is no such equivalent action. As a result, I found I was unable to get to a lot of options such as creating a new note, resizing the panels, moving notes, or formatting text.

I really want to start moving away from OneNote to Trilum but when I was just offhandedly testing it on iPadOS I was sort of taken aback by what I couldn't do in the interface with iOS touch methodologies. Is there anything on the roadmap to make the UI work better with this OS?

**Comment by chee** [comment]
I use an iPad with Trilium. I have had some success creating new notes by clicking the "New note" button on the top left of the menu bar

**Comment by zadam** [comment]
Hi, in general Apple devices / software are not well-supported. I don't own any Apple hardware and have close to 0 experience with it anyway. Since the project is essentially a one-man show, these personal facts then reflect on the project.

So, in other words, there isn't any plan to improve the UX on iOS. In fact iOS actually isn't even a supported platform since it has the unfortunate combination of having only one browser option (Safari) which isn't available anywhere else (Linux, Windows). (I'm somewhat surprised that it works though)

**Comment by chee** [comment]
It works quite well except for not being able to open a context menu, and some scrolling stuff in the tree that I was able to patch with a css note.

iOS has plenty of browsers, but they all share a rendering engine. that rendering engine (WebKit) is available to use on Linux in apps such as Gnome Web.

**Comment by chee** [comment]
>  Since the project is essentially a one-man show
off-topic but what is your plan here? would you be interested in receiving help, or would you prefer that interested parties fork Trilium?

**Comment by yllekz** [comment]
Hello, just to offer some color to this...Just because iOS standardizes on WebKit as a singular rendering engine does not put it outside the bounds of supported territories; in terms of rendering and functionality, Trilium works well on this platform and I don't see how that is related to what I'm speaking of.  WebKit is somewhat similar to Chromium, which is available on other platforms such as Linux.  At the same time, again Trilium works well on Safari/WebKit as it stands, and the issue is rather a menu accessibility topic.

I guess where I'm going with this is I think the menu could or should have alternate single-click elements or options to accommodate for the possibility that folks might be using it on widely adopted platforms such as iOS or iPadOS, with the case study of myself or chee states above. I know I would personally appreciate it as well as strive to adopt to Trilium as my preferred platform over OneNote.

I understand you are saying it is a "one-man show" operation, but optics-wise, I feel to shut iOS/iPadOS out of the picture is not a good long-term idea. I don't mean to come off as condescending, but I just wanted to be clear.

**Comment by zadam** [comment]
> off-topic but what is your plan here? would you be interested in receiving help, or would you prefer that interested parties fork Trilium?

If you mean this in the context of Mac/Apple support then I'm happy to merge compatibility fixes (crashes etc.) but "features" specifically for Apple and Mac would find a better place in a fork. The problem is with long term maintenance (measured in years) where any untested feature will deteriorate with time.

If you mean this in general then I welcome outside contributors, however larger changes/features should be discussed/aligned beforehand (not every feature will be accepted).

**Comment by zadam** [comment]
> Just because iOS standardizes on WebKit as a singular rendering engine does not put it outside the bounds of supported territories; in terms of rendering and functionality, Trilium works well on this platform and I don't see how that is related to what I'm speaking of. WebKit is somewhat similar to Chromium, which is available on other platforms such as Linux. At the same time, again Trilium works well on Safari/WebKit as it stands, and the issue is rather a menu accessibility topic.

Yes, my comment has been off topic. But still the concern remains. Blink has been forked many years ago and the two engines diverged, in many ways WebKit is behind both Blink and Gecko (at least that's what I hear). I'm happy that Trilium works right now, but I don't provide any guarantees this will remain so.

> I guess where I'm going with this is I think the menu could or should have alternate single-click elements

I assume you're talking about the full "desktop UI" and not about the limited "mobile UI". With the desktop UI I don't really have plans to make it tablet friendly. It's just not good for this purpose. 

> I feel to shut iOS/iPadOS out of the picture is not a good long-term idea.

From my POV it's mainly Apple shutting their users out by being very developer unfriendly. To be clear, I would like to fully support  Apple devices, it's just so expensive in both monetary terms and time that I just give up. Not worth it for me.

**Comment by chee** [comment]
> If you mean this in general then I welcome outside contributors, however larger changes/features should be discussed/aligned beforehand (not every feature will be accepted).

off-topic again but, how and where does this discussion/alignment happen? the gitter is not very active, and conversations like this don't always lend themselves well to github issues

**Comment by zadam** [comment]
There hasn't been that many such conversations yet, but so far mostly here in issues/PRs or over email (zadam.apps@gmail.com). I'm not active anywhere else.

**Comment by andrejdam** [comment]
> (Version 0.45.5)
> 
> This isn't a bug report as much as it's just a general user experience issue I observed. I loaded up my instance of Trilium in Safari on iOS, and tried to create a new note. I found that there was no UI button to easily create one, and any menu element that was inside a right-click menu was inaccessible to me with the touch screen alone. On a Microsoft Surface with its touch screen, you can access right click menus by long-pressing the screen in the spot where you would right-click, but on iPadOS there is no such equivalent action. As a result, I found I was unable to get to a lot of options such as creating a new note, resizing the panels, moving notes, or formatting text.
> 
> I really want to start moving away from OneNote to Trilum but when I was just offhandedly testing it on iPadOS I was sort of taken aback by what I couldn't do in the interface with iOS touch methodologies. Is there anything on the roadmap to make the UI work better with this OS?

A question, though: how did you manage to make Trillium work on your iPad? Did you install a server instance and then opened it through your browser, or did you somehow miraculously made it work directly on your iPad?

**Comment by yllekz** [comment]
I have a Raspberry Pi NAS running Docker. I set up a Trilum container which just serves out Trilium via a web interface. No apps utilized. On the iPad I just browse to IP:port and I'm there.

**Comment by andrejdam** [comment]
> I have a Raspberry Pi NAS running Docker. I set up a Trilum container which just serves out Trilium via a web interface. No apps utilized. On the iPad I just browse to IP:port and I'm there.

Thanks, I assumed it was that way. Hope it's not too difficult to setup.

**Comment by Kels307** [comment]
> I use an iPad with Trilium. I have had some success creating new notes by clicking the "New note" button on the top left of the menu bar.
> 
> You can also tap a note's name in the tree, and then press the `+` to add a note inside

Can you share how you imported onto the iOS system? I have it installed on my macbook pro but for some reason Im not able to get the application to open on my ipad. Im not super familiar with self hosting yet so still learning and likely overlooking something simple. I'd appreciate the insite! Thanks
