### ISSUE TITLE
Syntax highlighting in blocks of code

### ISSUE THREAD

**Issue by z3roonctf** [zadam/trilium#1926]
Good day.

When I am using "Text" as a main type of my node's paper, I can insert code block, choosing different languages. But is it possible to turn on syntax highlithing on it?

Thank you for your attention.

**Comment by z3roonctf** [comment]
Sorry. My bad. I have found prev issue described that problem. Good luck in development of this great tool :)

**Comment by zadam** [comment]
See https://github.com/zadam/trilium/issues/1803 for details.
