### ISSUE TITLE
When you export a Markdown file, the caption is displayed in the post

### ISSUE THREAD

**Issue by olunju** [zadam/trilium#1935]
![](https://bj.bcebos.com/im-cs/b5ef1840bdad643f7bfb1bbd0acb1a5f.png)

The text at the bottom of the image indicates that the title of the image should be entered, but when exported as a Markdown file, the title is displayed below the image. I think it is better to output it into the Markdown code, or not output it directly, because it will cause layout confusion

**Comment by zadam** [comment]
Hi, could you include screenshot/example export demonstrating the issue. It's not exactly clear what you mean ....

**Comment by olunju** [comment]
<img width="851" alt="my notes" src="https://user-images.githubusercontent.com/67050602/118063735-3f33ed00-b3cc-11eb-8fe1-c831b3403d22.png">
<img width="614" alt="markdown file" src="https://user-images.githubusercontent.com/67050602/118063785-570b7100-b3cc-11eb-9582-4a201f432ba3.png">

**Comment by zadam** [comment]
I see, thanks. This seems to be either limitation of Markdown (not supporting captions) and / or the conversion library [turndown](https://github.com/domchristie/turndown).

**Comment by olunju** [comment]
OK, I see. Thank you
