### ISSUE TITLE
Problems in mobile version 0.47.2

### ISSUE THREAD

**Issue by ScarletBlizzard** [zadam/trilium#1936]
1. Can’t delete notes on both Android (Firefox) and iOS (Safari). Pressing button “delete this note” does nothing.
2. Can’t view the bottom of note on both Android (Firefox) and iOS (Safari).

**Comment by meichthys** [comment]
2. There were a few other issues about not being able to see the bottom of a note: #1312
I believe it has been resolved in the latest versions.

**Comment by Haetsal-Lee** [comment]
1. persists in the latest stable release v0.47.5.

**Comment by finzzz** [comment]
2. Still persists in the latest stable release v0.48.5

**Comment by meichthys** [comment]
I cannot reproduce #1 on safari iOS mobile view as of 0.48.4
