### ISSUE TITLE
Why doesn't the title display properly?

### ISSUE THREAD

**Issue by Yattoo** [zadam/trilium#1943]
![微信截图_20210514100658](https://user-images.githubusercontent.com/50452856/118210240-cbade080-b49c-11eb-9aa2-0cd6197c2443.png)

**Comment by Yattoo** [comment]
为什么"###"不自动隐藏?

**Comment by Yattoo** [comment]
Why does "###" not auto-hide?

**Comment by sigaloid** [comment]
It shows you the text used to create that markdown text (in this case, header). It would be nice to have it auto hide if you leave that line or something similar though

**Comment by Mirwaisse** [comment]
Go to Options > Appearance and set "Heading style" to "plain".
