### ISSUE TITLE
Cannot Open Imported Files in Trilium

### ISSUE THREAD

**Issue by Creling** [zadam/trilium#1945]
Hello:

I just imported a PDF file to Trilium and to found that I could not preview it in Trilium. The progress bar has been sticky here for too long.

![image](https://user-images.githubusercontent.com/43109504/118269573-810a8380-b4f1-11eb-8f55-2c9c89212266.png)

However, when I get the file link from the dev tools and visit the link directly, the file is just there! I could access it without any latency. 

The file link is `http://127.0.0.1:37840/api/notes/t777J7kF2IC4/open` and here are some related logs:
```
20:12:55.929 200 GET /api/notes/IxfqltSpgYSw took 1ms
20:12:55.975 204 PUT /api/options took 2ms
20:12:55.984 304 GET /api/notes/t777J7kF2IC4/open took 2ms
20:12:56.926 200 GET /api/notes/IxfqltSpgYSw/revisions took 1ms
20:12:56.951 200 POST /api/notes/IxfqltSpgYSw/link-map took 1ms
20:13:01.031 204 POST /api/recent-notes took 1ms
20:13:16.081 Slow query took 77ms: SELECT content FROM note_contents WHERE noteId = ?
20:13:16.081 Slow 200 GET /api/notes/bVugc2bljkYp/open-partial took 77ms
20:13:16.082 TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
```

Trilium Version: 0.47.2 for PC, not a online version.
OS: Windows10
CPU: AMD 4800H

**Comment by zadam** [comment]
Hi, this is a PDF bug in 0.47.X. Please click on "open" button instead which will open the PDF in an external application.

**Comment by Creling** [comment]
Thank you for your reply.
