### ISSUE TITLE
inherited attributes renaming

### ISSUE THREAD

**Issue by damscal** [zadam/trilium#1947]
Situation: I have a template, and some notes based on it. I rename attribute "my_attribute" to "new_attribute" in the template

Expected behaviour: attribute "my_attribute" is renamed to "new_attribute" in all notes related to the template, and the attributes values are conserved

Observed behaviour: for the notes which had "my_attribute" already given some value, "new_attribute" is inherited without any value, and "my_attribute" is kept

What are other possible solutions (other than manually fixing each note) ?

**Comment by zadam** [comment]
In full search you can rename an attribute with "search action":

![image](https://user-images.githubusercontent.com/617641/118317233-10b33080-b4f8-11eb-81d7-38e836718527.png)
