### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by AndiLeni** [zadam/trilium#195]
Hello,

How can I change the port which the service is using?

Regards 
Andi

**Comment by AndiLeni** [comment]
Restarting means running the trilium.sh file with nohup again?

**Comment by zadam** [comment]
Yes, but the old instance should be killed. I typically use `killall node` (which isn't good idea if you run more node apps though) ... I should probably take care of that so user doesn't have to kill it themselves.

**Comment by AndiLeni** [comment]
Mhmm. I tried several things to install trilium.
But I obviously failed to start it. I still recieve the 503 error when opening the page.
I'm using node v9.11.2. Is this causing the trouble?

**Comment by zadam** [comment]
@AndiLeni, @JordyScript node 10.X requirement is actually for new unreleased version (0.24). Current version (0.23) should work with latest 8.X and 10.X. I don't know about 9.X (I test only with even - LTS versions).

But anyway, to run server installation it's recommended to use either [packaged installation](https://github.com/zadam/trilium/wiki/Packaged-server-installation) or [docker image](https://github.com/zadam/trilium/wiki/Docker-server-installation) which both come with bundled node.js runtime.

Alternatively you can attach latest files from trilium-data/log directory, this might help to find the source of the problem.

**Comment by AndiLeni** [comment]
Ah thanks. I didn't look in that wiki site. Just in the page for the recommended installation.

**Comment by AndiLeni** [comment]
Thanks for our answer!
I looked into the log file - but it was empty. I guess the service couldn't be started at all. 
My server provider is pretty open and lets the user do what the want. But this seems to be more complicated than expected.
I tried to run a simple app with `node `and it worked fine.
I'm gonna contact the support. Maybe they know what the problem could be.

**Comment by AndiLeni** [comment]
I took a look at the log file, which was empty. I guess trilium couldn't be started at all.
Maybe the problem is caused by the node.js runtime which comes with the app. I tried a simple hello world app to test nodejs on my server and it was working fine.
Maybe the support knows something which might help me.

**Comment by zadam** [comment]
@AndiLeni yeah, if the log is empty then it looks like node couldn't start at all.

When debugging these issues, it's good to try it out first without "nohup" which reroutes all the output from the terminal. So if you run it with just `node src/www`, it should output some kind of error.

**Comment by AndiLeni** [comment]
I tried what you said and this is the console output:

````
Error: Cannot find module '/var/www/virtual/andileni/trilium.lenhardt.eu/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/www/virtual/andileni/trilium.lenhardt.eu/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
````

**Comment by zadam** [comment]
Oh, so you are using "package binary distribution" (judging by that you mentioned extracting 7z). It wasn't clear to me before.

In that case my advice wasn't good since `node src/www` used system-wide node instead of bundled node. So please run just `./trilium.sh` which will use the bundled nodejs.

**Comment by AndiLeni** [comment]
Okay, 
I tried what you said but I still get this error:

````
Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/www/virtual/andileni/trilium.lenhardt.eu/node_modules/@mlink/scrypt/build/Release/scrypt.node)
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/var/www/virtual/andileni/trilium.lenhardt.eu/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/var/www/virtual/andileni/trilium.lenhardt.eu/node_modules/@mlink/scrypt/index.js:3:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
````

**Comment by zadam** [comment]
Good, I think we got to the crux of the problem. I think I had the same issue when deploying on my server. The issue was in old-ish version of my debian - node required newer glibc which wasn't available. Upgrading the distro to up-to-date version solved the issue for me.

If you want to avoid the upgrade, you may try either [docker image](https://github.com/zadam/trilium/wiki/Docker-server-installation) or doing the [manual server installation](https://github.com/zadam/trilium/wiki/Manual-server-installation), then it will compile with your system GLibc and should work, but there might be some other possible issues ...

**Comment by AndiLeni** [comment]
Ah thanks. Finally I know what's causing the problem. 
I'm gonna ask my hoster if they can install the missing dependencies.  Currently I'm on centos 6. Unfortunately I'm sure upgrading isn't possible. 
Also they prohibit docker.
I guess, I have to take a look at some other solutions :(

**Comment by ffywhxf** [comment]
it's any way to run Tilium sever on windows?

**Comment by zadam** [comment]
It's possible in the principle if you checkout the project from git (which is somewhat advanced) and build it yourself, but it's not a supported use case.

**Comment by gerroon** [comment]
Hi

I am trying to run this (server binary) on non-8080 , so i added a config ini based on the sample but trilium.sh does not respect the new port.
Did this setting change?  It was said to put under trilium-data/config but I see no such folder in the expanded folder.

**Comment by zadam** [comment]
This did not change and still is in `trilium-data/config.ini`, e.g.:

```
[General]
# Instance name can be used to distinguish between different instances
instanceName=

[Network]
# port setting is relevant only for web deployments, desktop builds run on random free port
port=4000
```

**Comment by gerroon** [comment]
Ok thanks, because it was the server app I thought that the data would be under the server's app folder not the user folder. It is clear now.

**Comment by ApplePie420** [comment]
I have a problem too, using packaged installation, Trilium just refuses to accept anything that is in the `config.ini` file. It is in the proper place (where the installation is), literally copied the sample file, changed port, nothing..

**Comment by zadam** [comment]
@ApplePie420 that sounds like it's looking at some different path. Try to force the specific path by setting `TRILIUM_DATA_DIR=/home/xxx/trilium-data` environment variable explicitly.

**Comment by sheeceq** [comment]
> You can change this in trilium-data/config.ini file:
> 
> ```
> [Network]
> # port setting is relevant only for web deployments, desktop builds run on random free port
> port=8080
> ```
> 
> And then restart trilium.
> 
> This only works for server installation. For desktop, random free port is used.

where is the config.ini file located

```
cd /opt/trilium
find . -type f -name "config.ini"
```


return nothing!

**Comment by eliandoran** [comment]
@sheeceq ,

The `config.ini` file is in your data directory. You need to run Trilium at least once for it to get generated. You can find the data directory in the About screen.

**Comment by sheeceq** [comment]
Thanks @eliandoran worked like a charm!

```

on ubunut this was the location
cd   /home/$USER/.local/share/trilium-data
```
