### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by seedrick** [zadam/trilium#1956]
Using version 0.47.2. Trying to sync from a server to desktop instance, this is what I see on the desktop log.  I've triple checked that the credentials are correct so I don't see why I'm getting an auth error. I'm sure it's some sort of environment issue--if somebody could point me in the right direction I would very much appreciate it. Thank you.

> `10:20:19.282 DB not initialized, please visit setup page
> 
> 10:20:19.283 DB size: 167 KB
> 10:20:21.567 App HTTP server starting up at port 37840
> 10:20:21.567 {
>   "appVersion": "0.47.2",
>   "dbVersion": 183,
>   "syncVersion": 20,
>   "buildDate": "2021-04-26T22:32:54+02:00",
>   "buildRevision": "6f1b0b92fe8dcea736c15217c69512c7fee769cb",
>   "dataDirectory": "C:\\Users\\USER\\AppData\\Roaming\\trilium-data",
>   "clipperProtocolVersion": "1.0"
> }
> 10:20:21.568 CPU model: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, logical cores: 4 freq: 2496 Mhz
> 10:20:21.616 Listening on port 37840
> 10:20:21.848 Triggering sync.
> 10:20:21.860 Slow 304 GET /setup took 14ms
> 10:20:22.117 Nothing to push
> 10:20:22.141 sync failed: Request to GET https://trilium.domain.tld/api/sync/changed?lastEntityChangeId=0 failed, error: 401 
> stack: Error: Request to GET https://trilium.domain.tld/api/sync/changed?lastEntityChangeId=0 failed, error: 401 
>     at generateError (C:\Program Files\trilium-windows-x64\resources\app.asar\src\services\request.js:191:12)
>     at ClientRequest.<anonymous> (C:\Program Files\trilium-windows-x64\resources\app.asar\src\services\request.js:62:28)
>     at ClientRequest.emit (events.js:315:20)
>     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
>     at SimpleURLLoaderWrapper.emit (events.js:315:20)
>     at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
> 10:20:22.144 ERROR: Failed to deserialize sync response: Logged in session not found
> 10:20:24.494 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:24.496 200 GET /api/sync/stats took 2ms
> 10:20:25.477 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:25.478 304 GET /api/sync/stats took 1ms
> 10:20:26.485 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:26.488 304 GET /api/sync/stats took 4ms
> 10:20:27.475 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:27.476 304 GET /api/sync/stats took 1ms
> 10:20:28.473 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:28.474 304 GET /api/sync/stats took 1ms
> 10:20:29.479 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:29.480 304 GET /api/sync/stats took 1ms
> 10:20:30.486 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:30.489 304 GET /api/sync/stats took 4ms
> 10:20:31.478 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
> 10:20:31.480 304 GET /api/sync/stats took 3ms
> 10:20:32.478 Returning sync stats: {"initialized":false,"outstandingPullCount":0}`

**Comment by zadam** [comment]
Hi, from log it's clear the authentication is failing. This is typically caused by some network proxy servers which are deleting/mangling the session cookie and thus preventing the authentication. I've seen also the case where server could not save session information due to lack of free space.

**Comment by seedrick** [comment]
Ok, thanks. I am indeed using a proxy redirect. What specifically should I be looking for in my nginx config? I run an LDAP so there's a gigantic stack of nginx wizardry going on with my server. Any help as to what fields to focus my search cone on would be a huge help.
