### ISSUE TITLE
in 0.47.3, calendar icon invisible for promoted date fields on black theme

### ISSUE THREAD

**Issue by elementc** [zadam/trilium#1959]
On 0.47.3, when using the black theme, I can't see the little calendar icon in a promoted date field.

Compare:
![Screenshot from 2021-05-17 23-27-15](https://user-images.githubusercontent.com/4315099/118603529-de5c3a00-b768-11eb-9c82-78d395d06ea8.png)
Versus: 
![Screenshot from 2021-05-17 23-24-46](https://user-images.githubusercontent.com/4315099/118603535-e025fd80-b768-11eb-863a-df0cc2b48fbd.png)

 _I originally thought the picker entirely had been disabled, original description follows:_

I can dig out the logs the template mentions if you like, but I think it's more of a frontend issue? Let me know if you need them, I didn't spot anything clear in there,

This might not be specific to 0.47.3, I skipped some point releases between late 0.46 and here.

Using the task tracker example as inspiration, I have a todo list item template with the following attribute:
```
#label:doneDate=promoted,single,date
```
On inherited instances of this template, I've historically been able to click or tap on a promoted single date defined like the above codeblock and a calendar chooser would pop up for me to click on a date. However, in this release, no such calendar is appearing. This forces me to type the date by hand, which is painful for me as sometimes I don't know a precise date off the top of my head and I'm searching for "last Thursday" which calendar views are great for.

If this feature was intentionally removed, please consider restoring it. If it's a bug, well, let me know if there's something I can do to help expedite a fix :)

**Comment by zadam** [comment]
Hi, do you use desktop or server version? Could you post a screenshot of the field?

Here's how it looks for me:

![image](https://user-images.githubusercontent.com/617641/118541680-46535600-b752-11eb-9b2e-4ddf092003ff.png)

**Comment by elementc** [comment]
My goodness, this got sillier than I would have anticipated.

I took screenshots to show that my server install (with the grey theme) behaves well in firefox on linux, but the desktop client behaves incorrectly.
![Screenshot from 2021-05-17 23-03-42](https://user-images.githubusercontent.com/4315099/118602248-4a3da300-b767-11eb-9542-a957edf49464.png)
![Screenshot from 2021-05-17 23-05-28](https://user-images.githubusercontent.com/4315099/118602254-4c076680-b767-11eb-80bc-e6bc87053e4a.png)

But then I noticed that I had the blue outline of your screenshot but not the little black calendar icon. I clicked where it should be, and:
![Screenshot from 2021-05-17 23-27-15](https://user-images.githubusercontent.com/4315099/118602431-87a23080-b767-11eb-820e-9fb182277a2c.png)
I flipped over to the white theme and sure enough, the icon re-emerged!
![Screenshot from 2021-05-17 23-24-46](https://user-images.githubusercontent.com/4315099/118602474-9983d380-b767-11eb-95c2-75a399cf3845.png)

Okay, so I guess this isn't a bug about broken functionality so much as the theme obscuring this super helpful icon which tells me where to click- I updated the bug title to reflect it. I could have sworn it wasn't hidden in a previous release, do you think this is fixable?

**Comment by zadam** [comment]
This icon is actually drawn by the electron (chromium) itself. Trilium 0.47 uses new electron version which probably causes this issue. I assume that such a bug should get fixed in chrome sooner rather than later.
