### ISSUE TITLE
Embedding Code Snippets in Text Notes.

### ISSUE THREAD

**Issue by JordyScript** [zadam/trilium#196]
A very useful feature to have implemented in Trilium would be the ability to embed code snippets with syntax highlighting into text notes. This would make annotating/documenting your code snippets much more convenient.

A visual example of what I mean is the following screenshot (this is a markdown note created in Boostnote)
____
![boostnote_2018-10-18_11-40-12](https://user-images.githubusercontent.com/35542866/47145682-99c74400-d2ca-11e8-9bdc-443c20ba93c2.png)
____
Note also how there is a copy button which allows you to copy the entire contents of the code snippet embedded in the text in a single click without selecting it first. This would also be really useful as an additional feature.

The way this is currently done in Boostnote, is by writing three back ticks followed by the programming language you want to write. Then the code, then on the last line three more back ticks. (This even works in githubs comments if I don't escape the back ticks.)

\``` python

[insert code here]

\```

**Comment by zadam** [comment]
Hi JordyScript, I'd love to have this feature as well, but this is actually a responsibility of CKEditor (which is our editing component). They have an issue for this, but I'm afraid there hasn't been much progress recently: https://github.com/ckeditor/ckeditor5/issues/436 As soon as that feature lands in, we'll have it as well. Even though it's not perfect for now I use code subnote for larger code snippets and if it's really piece of code small I use blockquote inside text document.

**Comment by zadam** [comment]
Unfortunately what you want is not possible now - there's always just single note displayed. Instead of doing that I rather want to wait for CKEditor to implement proper code block feature (which they plan to do, it's just a matter of time).

For now whenever I need code block inside text note I use either blockquote or single line code. It's far from perfect, but works for me in the meantime.

**Comment by Fenwick17** [comment]
Cheers @zadam I will stick with single line code, it'll do the job

**Comment by gpanders** [comment]
It looks like this may be added to CKEditor soon: https://twitter.com/ckeditor/status/1138803157700624385

**Comment by zadam** [comment]
Yes, I'm watching it closely and I'm ready to integrate as soon as it is available :-)

**Comment by zadam** [comment]
Code block support is in 0.38.0-beta

**Comment by dafmdev** [comment]
Hello, I have been testing the software, but I see that they do not apply color syntax in the code blocks.

**Comment by zadam** [comment]
Syntax highlighting is very difficult to apply in the code snippets in the text editor and I don't expect this to happen anytime soon. If you need highlighting then I recommend creating a "code note":

![image](https://user-images.githubusercontent.com/617641/121772465-c2846200-cb75-11eb-9f1f-fe1b13a2382f.png)
