### ISSUE TITLE
How can I export notes searched?

### ISSUE THREAD

**Issue by starsareintherose** [zadam/trilium#1963]
How can I export notes searched?
I find I can only export notes searched one by one? Can I export them all just by one button or other ways?

**Comment by zadam** [comment]
Hi, the way I would do this is through full search in the tree pane:

![image](https://user-images.githubusercontent.com/617641/118701531-1c626800-b814-11eb-82cc-8672a1285eee.png)

You can select the notes (using shift-click, shift-arrows or `CTRL-A` to select all) and copy to the clipboard. Then create a new note, paste using CTRL-V into it. You can then export the new note with all the new children. It's awkward but better than exporting one by one I guess.

**Comment by starsareintherose** [comment]
> Hi, the way I would do this is through full search in the tree pane:
> 
> ![image](https://user-images.githubusercontent.com/617641/118701531-1c626800-b814-11eb-82cc-8672a1285eee.png)
> 
> You can select the notes (using shift-click, shift-arrows or `CTRL-A` to select all) and copy to the clipboard. Then create a new note, paste using CTRL-V into it. You can then export the new note with all the new children. It's awkward but better than exporting one by one I guess.

Thanks for your quick and nice reply, it works for me.
