### ISSUE TITLE
Distraction-free width incorrect when window narrow

### ISSUE THREAD

**Issue by martinkoutecky** [zadam/trilium#1965]
I'm experiencing the following bug with Trillium 0.47.3. I resize the window to half screen width (roughly 960px), and hit Alt-M (distraction-free mode). Everything is good. Then I switch to a different tab, and the width of the note decreases to about 2/3, with a lot of empty space to the right of the note. See below. Leaving the distraction-free mode and entering it again fixes the issue.

![Peek 2021-05-18 13-39](https://user-images.githubusercontent.com/445269/118644955-9d9f0800-b7de-11eb-8f12-c61589feef27.gif)

The log only has stuff related to sync, so I'm not posting it for now.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, fixed.
