### ISSUE TITLE
Bug:  Trilium stops displaying notes after rearranging

### ISSUE THREAD

**Issue by JordyScript** [zadam/trilium#197]
I was just rearranging some notes in my Trilium installation, but suddenly the screen refreshed and now I cannot view any notes, nor reach them through the jump or search functions. I cannot create new notes, nor view recent changes, nor go the options menu. This behaviour persists after restarting the app.

Triliums CPU Usage hovers around 17,5% which is abnormal. Disk usage (read write) is also around 34%, which seems abnormal.

Inspecting the document.db file with DB Browser for SQLite shows that all my notes are still present. 

I now see this screen:
____

![trilium_2018-10-18_12-03-31](https://user-images.githubusercontent.com/35542866/47147430-7ef6ce80-d2ce-11e8-8548-898eb5285bfb.png)

____

Rearranging notes repeatedly gave me warnings of creating loops, even though I was not creating any loops, just reordering the notes in one folder. Before I did the reordering I had clicked the sync now button, but since I have a desktop installation on Windows, that did not work. I do not think that had anything to do with this bug, though.

I was using Trilium 0.22.1, but updating to Trilium 0.23.0 did not fix the issue.

My guess is that my rearranging of the notes caused Trilium to corrupt the document.db database (not the database file itself, as it can be read by other applications, but the content) in such a way that Trilium can no longer render its contents, which it then keeps retrying ad infinitum, leading to high CPU and Disk usage.

If my suspicion about the cause is indeed correct, then this would definitely need addressing, because it is unacceptable that a naive/non-technical user can just casually break the application, because the application allows the user to execute actions that are unsupported or "illegal" as far as the application is concerned.

I wonder if anyone can replicate this bug, or if I hit the trillion dollar jackpot.

**Comment by JordyScript** [comment]
Also, I have no backup, else I would have done a diff to see what changes were made.

**Comment by zadam** [comment]
This is very unfortunate. What you're saying is correct, my suspicion is that the rearranging the notes caused some unexpected state in the database (something like cycle in the tree). This is of course very serious issue and I'm very interested in finding and fixing it. As for your actual data, I don't think they are corrupted and I believe it should be possible to fix the database by one or few targeted SQL queries.

Could you please go to Options -> Advanced  and click on "Save anonymized database"? This will create file in trilium-data/anonymized-db. It's a copy of your database file with all its real content (text) erased but preserving the structure which will help me to find out what went wrong. You can attach it here or send it to me on email: adam.zivner@gmail.com

What would also help me are the logs - if you could zip contents of trilium-data/log and attach/send it to me as well.

Thanks!

**Comment by JordyScript** [comment]
> Could you please go to Options -> Advanced and click on "Save anonymized database"?

Impossible as the options menu is no longer working. When I click on it, nothing happens. Is there a way to anonymize the db from the command-line? Or would I have to manually erase the note contents.

> As for your actual data, I don't think they are corrupted and I believe it should be possible to fix the database by one or few targeted SQL queries.

The data are not corrupted. It can still be opened and read in a DB viewer application.

> if you could zip contents of trilium-data/log and attach/send it to me as well.

Will do.

**Comment by zadam** [comment]
@JordyScript Thank you for your help. I'm looking into the issue now. As you said, anonymization doesn't work now because the application is completely stuck after loading the document.

**Comment by zadam** [comment]
@JordyScript So it was a tree cycle after all. Although trilium has protection against forming tree cycles, it didn't work for one special case of root node - in your case root node had referred to itself as its parent. I'm fixing the anti-cycle protection and trying to test all the corner cases. I will release a patch version in coming days.

To fix your DB, you need to run following query and restart Trilium:
```
update branches set parentNoteId = 'none' where branchId = 'root'
```

**Comment by JordyScript** [comment]
Thanks for your time and effort and for helping me fix my document.db :) Glad I could be of help.
