### ISSUE TITLE
Could the docker image run on ARM?

### ISSUE THREAD

**Issue by starsareintherose** [zadam/trilium#1975]
Could the docker image run on ARM? Such as docker on Raspberry Pi？

**Comment by zadam** [comment]
No, docker images are only for x86-64 platform. There are some unofficial and outdated builds [here](https://hub.docker.com/r/hlince/trilium/tags?page=1&ordering=last_updated) but you those only at your own risk.

**Comment by ilikeorangutans** [comment]
Trilium runs great on arm, you just have to build your own image. Here's how I build it, from my Linux desktop to run on a Pi.

1. you'll need docker and [buildx](https://docs.docker.com/buildx/working-with-buildx/) 
2. check out the trilium (this) repo, check out the version tag, e.g. `git co v0.47.3`.
3. build your image: `docker buildx build  -t your.registry.com/trilium:v0.47.3  --platform linux/arm/v7 -f Dockerfile .  --load`
4. once the build is done you can push the image to your registry and use it on your pi.

**Comment by jmu** [comment]
Or use my image built on  Pi 4b.  https://hub.docker.com/repository/docker/jmujmu/trilium

**Comment by Drudoo** [comment]
> 
> 
> Or use my image built on Pi 4b. https://hub.docker.com/repository/docker/jmujmu/trilium

that image gives me an exec format error on armv7 (using a pi 4), which happens when it is build for the wrong architecture. Building my own image works.

**Comment by jmu** [comment]
> > Or use my image built on Pi 4b. https://hub.docker.com/repository/docker/jmujmu/trilium
> 
> that image gives me an exec format error on armv7 (using a pi 4), which happens when it is build for the wrong architecture. Building my own image works.

I built on ubuntu server 64bit，the architecture is linux/arm64.

**Comment by Kamuno** [comment]
> Trilium runs great on arm, you just have to build your own image. Here's how I build it, from my Linux desktop to run on a Pi.
> 
> 1. you'll need docker and [buildx](https://docs.docker.com/buildx/working-with-buildx/)
> 2. check out the trilium (this) repo, check out the version tag, e.g. `git co v0.47.3`.
> 3. build your image: `docker buildx build  -t your.registry.com/trilium:v0.47.3  --platform linux/arm/v7 -f Dockerfile .  --load`
> 4. once the build is done you can push the image to your registry and use it on your pi.

This indeed worked. The only thing I had to change was the COPY instruction in the Dockerfile because there is no `server-package.json`. I changed it to `package.json` and compiled it directly on the Pi, this worked perfectly.
