### ISSUE TITLE
import exported zip with internal links breaks trilium (47.3)

### ISSUE THREAD

**Issue by ivosm** [zadam/trilium#1979]
I have 2 users running desktop app. on their PCs (both Kubuntu 20.04) and both sync. with their own instance on sever. I have tested export note with descendants from one user and import them to other user. The same result was achieved by all combination of import/export from/to desktop/server(FF browser). 
Procedure:
1. On PC A was created note test-export-root with child note test-1 and test-2 with sec. level child test-2-1 and put some text into them.
2. On PC A was exported note test-export-root with descendants using zip.
3. On PC B was imported test-export-root.zip
4. All imported notes were opened one by one and checked error message using console in dev. tools. 
5. The same was done on server using browser
6. Everything worked as expected
7. Steps 1-4 were repeated after adding internal link to 'test-1' inside note test-2-1, i.e. everything is inside the exported tree.
8. Now everything works until note test-2-1 is opened. The link was checked from sub-view in note test-2 and worked.
9. After opening test-2-1 there are error messages and no content of the note is displayed on both desktop and server. 
10. Both behaved unpredictable until reload. In case of import real case of cca 20 notes and many internal links is the app completely broken (displays content of different notes etc.) The browser is more sensitive.

What was not tested but where additional problems are expected, are internal links and relations outside the exported tree. In any case, it should be described in docs. Consider e.g. a situation, where user exports and imports 2 trees with link from note-1 in tree-1 to note-2 in tree-2. Then the behavior could be generally: 
- All links outside will be deleted, so there is no way, how to transfer a content unless you transfer all notes up to some common root. Yes and even update of a small tree is not possible in that case.
- Only links pointing to existing IDs will be kept, so importing tree-2 first and tree-1 keeps the link.
- Links to non-existing IDs will be kept for future use but only ignored. ??? Dummy notes could be created ... 
- User could decide at export and/or import and maybe even (dreaming) having the possibility to list all the integrity problems and decide one by one. :-D

[test-export-root-internal-link-imported-view-on-desktop.log](https://github.com/zadam/trilium/files/6540559/test-export-root-internal-link-imported-view-on-desktop.log)
 [test-export-root-internal-link-imported-view-on-server.log](https://github.com/zadam/trilium/files/6540268/test-export-root-internal-link-imported-view-on-server.log)
[test-export-root-internal-link-imported.log](https://github.com/zadam/trilium/files/6540270/test-export-root-internal-link-imported.log)
[test-export-root-internal-link.zip](https://github.com/zadam/trilium/files/6540271/test-export-root-internal-link.zip)

**Comment by zadam** [comment]
Hi, thanks for the detailed bug report, I was able to reproduce the issue and fix it. I will be release 0.47.4 soon.

To answer your other question:

* relations pointing out of the exported subtree are dropped
* hyperlinks point out of the exported subtree are kept as they are - they can't be removed since they are part of the text content but they are broken in the sense that the target note does not exist.
