### ISSUE TITLE
sync problem :sync failed: Request to POST, linux noob stuck

### ISSUE THREAD

**Issue by bert010** [zadam/trilium#1981]
2 weeks ago I discovered trilium , started using the desktop version and happy since. ditched my notion/milanote etc.
But since I wanted to have remote acces too I installed the server version as wel. took me a few days since i'm not so familiar with linux but finally succeeded in having it run on my OpenMediaVault server.
Biggest problem was to get TLS working but luckily I found an OMV let's encrypt extension.

made a dynamic dns wit no-ip and can acces trilium at https://####.hopto.org:8080  

so now i'm trying th sync it with my desktop but no luck sofar,  desktop trilium accepts the server adress but the sync screen never completes and ther's an error in my log:
any suggestions? thnkz in advance

11:33:34.928 DB not initialized, please visit setup page
11:33:34.929 DB size: 4 KB
11:33:35.109 Generated session secret
11:33:36.406 App HTTP server starting up at port 37840
11:33:36.406 {
  "appVersion": "0.47.3",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-05-15T23:05:20+02:00",
  "buildRevision": "f6dd1110e842a8b84f2bbdaadad315763045c152",
  "dataDirectory": "C:\\Users\\gerard\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0"
}
11:33:36.407 CPU model: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz, logical cores: 4 freq: 2295 Mhz
11:33:36.448 Listening on port 37840
11:33:36.660 304 GET /setup took 7ms
11:34:00.777 Getting document options FROM sync server.
11:34:00.780 200 POST /api/setup/sync-from-server took 3ms
11:34:00.986 Creating database for sync
11:34:01.001 Schema and not synced options generated.
11:34:01.001 Triggering sync.
11:34:01.027 sync failed: Request to POST https://#####.hopto.org:8080/api/login/sync failed, error: 401 Unauthorized
stack: Error: Request to POST https://#####.hopto.org:8080/api/login/sync failed, error: 401 Unauthorized
    at generateError (C:\Users\gerard\Desktop\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\request.js:191:12)
    at ClientRequest.<anonymous> (C:\Users\gerard\Desktop\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\request.js:62:28)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
11:34:02.032 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
11:34:02.034 304 GET /api/sync/stats took 3ms
11:34:03.016 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
11:34:03.018 304 GET /api/sync/stats took 2ms
11:34:04.010 Returning sync stats: {"initialized":f
* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
Hi, could you also post here the server log? It should provide more details on why the authentication has been rejected.

**Comment by bert010** [comment]
thank you so much!!!  The server log showed that there was a time difference between server and computer.. after issuing ntpdate -u pool.ntp.org the sync did work!!!  Thnkz again!!!! so happy now!
