### ISSUE TITLE
NieR: Automata Theme

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#1990]
I made a  [NieR: Automata Trilium Theme](https://github.com/Nriver/NieR-Automata-Trilium-Theme)

![screenshot](https://user-images.githubusercontent.com/6752679/120321776-46d51a80-c316-11eb-8ed4-f1a32c9177d1.png)

Hope you guys like it.

**Comment by chee** [comment]
that's amazing :)

**Comment by Mirwaisse** [comment]
Really nice, thanks for sharing!

By the way, did you translate the UI in Chinese by yourself? I've seen quite a few people interested in a Chinese localization (@shijunjie007, @bug0306, @BingChunMoLi, @derbich @dejavudwh, @starsareintherose, @vvring).

**Comment by Nriver** [comment]
> Really nice, thanks for sharing!
> 
> By the way, did you translate the UI in Chinese by yourself? I've seen quite a few people interested in a Chinese localization (@shijunjie007, @bug0306, @BingChunMoLi, @derbirch @dejavudwh, @starsareintherose, @vvring).

Yes, I have translated almost all of the frontend text into Chinese, including UI and popup messages. I will release it this weekend.

**Comment by zadam** [comment]
If you wish to continue discussing this then please open a discussion topic.
