### ISSUE TITLE
Windows app crashes since v0.47

### ISSUE THREAD

**Issue by ZiriaRMD** [zadam/trilium#1994]
Since v0.47.2 the Windows app crashes after a few minutes and the window closes. This only happens when sync to server is configured, if I use local only there is no problem. I'm currently using v0.46.9 which works fine, Windows eventviewer shows an application error but this a very generic eventID

_Faulting application name: trilium.exe, version: 0.47.4.0, time stamp: 0x60ad3875
Faulting module name: trilium.exe, version: 0.47.4.0, time stamp: 0x60ad3875
Exception code: 0xc0000409
Fault offset: 0x0000000002edabb8
Faulting process id: 0x4320
Faulting application start time: 0x01d75852ddbee721
Faulting application path: C:\test\trilium-windows-x64\trilium.exe
Faulting module path: C:\test\trilium-windows-x64\trilium.exe
Report Id: 11bce717-4940-414e-a3b4-eb736f4eebed
Faulting package full name: 
Faulting package-relative application ID:__ 

Log file: [trilium-2021-06-03.log](https://github.com/zadam/trilium/files/6590941/trilium-2021-06-03.log)

**Comment by zadam** [comment]
Hi, thanks for reporting this.

v0.47 has upgraded electron (v9 => v13) and it seems to have bunch of issues (especially on windows). I expect the will get fixed in the patch versions to which I will of course update. In the meantime you can keep using 0.46.

**Comment by ZiriaRMD** [comment]
Hi, 

OK, thank you for the feedback. I'll keep using 0.46 for now.

**Comment by ZiriaRMD** [comment]
Issue is resolved in v0.47.5
