### ISSUE TITLE
Trilium Notes (unofficial) translation release. (非官方) 中文版发布.

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2000]
Trilium Notes (非官方) 中文版发布.
https://github.com/Nriver/trilium-translation/releases

![20210606135851579_1868988429](https://user-images.githubusercontent.com/6752679/120914251-65009900-c6cf-11eb-9b38-dd9554657372.png)

If you'd like to check the code or translate to other language, check [README.md](
https://github.com/Nriver/trilium-translation)

**Comment by Nriver** [comment]
Trilium Notes' 2000th issue, what a coincidence :)

**Comment by vvring** [comment]
终于看到国人汉化了，开发者不拿中国几亿用户当回事
![china](https://user-images.githubusercontent.com/47848167/121630537-eaa98d80-caaf-11eb-80eb-98ebc401c3e9.PNG)

**Comment by Nriver** [comment]
> 终于看到国人汉化了，开发者不拿中国几亿用户当回事

软件一开始设计没有考虑到国际化, 开发到一定程度再加就挺麻烦的, 发展到一定程度就几乎无解了, 这个我能理解. 不过我还是喜欢看自己熟悉的母语, 而且想让更多人来用这个牛逼的软件, 所以就自己动手啦.

It takes a lot of effort to make i18n if not considered in the first place. It would be almost impossible if it is already developed at a certain stage. However, I prefer to see the software I use is filled up with my mother language which I can understand without any effort. Besides, I want more people to use this awesome tool, that's why I did this.

**Comment by cnlzxin** [comment]
感谢作者开发出这么棒的软件，也感谢 @Nriver 为汉化付出的努力

**Comment by netesheng** [comment]
👍支持

**Comment by uliuyt** [comment]
可以可以👍 后续会保持更新吗？

**Comment by Nriver** [comment]
> 可以可以 后续会保持更新吗？

咕咕咕， 咕咕咕

**Comment by Nriver** [comment]
> 可以可以 后续会保持更新吗？
我刚刚更新了内置的文档汉化  ；）

**Comment by zadam** [comment]
If you wish to continue discussing this then please open a discussion topic.
