### ISSUE TITLE
Suppress network errors?

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2001]
![image](https://user-images.githubusercontent.com/69441971/120925700-44354500-c6c9-11eb-87e4-8f74ddcb9b6b.png)

I was able to emulate (I think?) an online, uneditable version unless I manually sync with desktop, by simply dropping `PUT` and `DELETE` requests through Apache2. but the above errors display whenever opening the tree or editing a note. 

https://wiki.linuxquestions.org/wiki/Securing_Apache#Disabling_PUT_and_DELETE
Essentially use the Limit directive in Apache: ![image](https://user-images.githubusercontent.com/69441971/120926043-c07c5800-c6ca-11eb-8137-c4a9df9686ca.png)

I could of course add #readOnly to all of the notes so if someone manually clicks edit, that's on them. But, the tree `PUT`'s still get error'd. I tried redirecting /app/services/toast.js to a toast.js on my main domain that removes the notification but for some reason it began requesting ws.js and utils.js from the main directory as well. Moving those over caused it to start requesting even more js's from the main directory, despite the fact that I only RewriteRule'd the app/services/toast.js 
![image](https://user-images.githubusercontent.com/69441971/120928174-12c17700-c6d3-11eb-9f27-abfb3df0e9f1.png)

So, is there another way to limit error notifications, so changing the tree state doesn't throw these errors? Thanks!

**Comment by zadam** [comment]
I don't have a solution for you, but forbidding PUT and DELETE is not safe enough. POST also modifies data but can't be easily disabled since POST is also used for read only operations which accept input in request body (typical workaround for POST not supporting request body).

**Comment by sigaloid** [comment]
Gotcha, thanks! closing since this seems like an [xy problem](https://xyproblem.info/)
