### ISSUE TITLE
markdown table could not display when imported

### ISSUE THREAD

**Issue by kkonghao** [zadam/trilium#2026]
import result is:
![image](https://user-images.githubusercontent.com/57028687/122653577-0f6cc780-d178-11eb-9bdd-778a2ec47c24.png)

**Comment by zadam** [comment]
Hi, Trilium uses CommonMark parser. Tables in Markdown are not standardized and (I assume) therefore not supported.

**Comment by b3taman** [comment]
Is it possible to add the ckeditor5-markdown-gfm plugin? Their example at https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html includes a table. Since it is GitHub Flavoured Markdown, lots of people will be very happy.

**Comment by zadam** [comment]
That's a different thing. Import (and conversion) happens on the backend, CKEditor is not involved in the import process.

**Comment by olunju** [comment]
> Hi, Trilium uses CommonMark parser. Tables in Markdown are not standardized and (I assume) therefore not supported by this library.

I was looking for someone with a similar problem and I saw this, When exporting as markdown file, the code block is not wrapped with ' ``` ', is this normal?

**Comment by zadam** [comment]
According to [common mark](https://commonmark.org/help/tutorial/09-code.html) it is possible to either use ``` or four spaces. The converter uses four spaces.

**Comment by olunju** [comment]
> According to [common mark](https://commonmark.org/help/tutorial/09-code.html) it is possible to either use ``` or four spaces. The converter uses four spaces.

sorry, I always thought only use ```

**Comment by antoniotejada** [comment]
[I added a note to the wiki https://github.com/zadam/trilium/wiki/Markdown/](https://github.com/zadam/trilium/wiki/Markdown)

For reference this is Commonmark's position regarding tables
- https://github.com/commonmark/commonmark.js/issues/128
- https://talk.commonmark.org/t/tables-in-pure-markdown/81

**Comment by samchugit** [comment]
> > According to [common mark](https://commonmark.org/help/tutorial/09-code.html) it is possible to either use ``` or four spaces. The converter uses four spaces.
> 
> sorry, I always thought only use ```

It's not a trilium problem, but I got a workaround by modifying some source code and needs to recompile. See #2963.

**Comment by olunju** [comment]
> > > According to [common mark](https://commonmark.org/help/tutorial/09-code.html) it is possible to either use ``` or four spaces. The converter uses four spaces.

Thank you for your reply. Maybe I will try it

**Comment by olunju** [comment]
> It's not a trilium problem, but I got a workaround by modifying some source code and needs to recompile. See #2963.

Thank you for your reply. Maybe I will try it

**Comment by livingfree2023** [comment]
still hoping to have table markdown to take notes from ChatGPT

**Comment by zadam** [comment]
support for tables will be in 0.61

**Comment by BigDataHunter** [comment]
<img width="1057" height="695" alt="Image" src="https://github.com/user-attachments/assets/77a5b585-5530-4280-9e1c-c3e822e4c8c5" /> can we support copy markdown table  to trilium
