### ISSUE TITLE
Will you consider internationalized language packs

### ISSUE THREAD

**Issue by omaidb** [zadam/trilium#2030]
I don't use English, but I find trilium is very easy to use.The only obstacle at the moment is that I don't understand English.
I hope to launch a Chinese language package project so that such good software can be enjoyed by users in other countries and regions.

**Comment by Mirwaisse** [comment]
Have a look at this:

https://github.com/zadam/trilium/issues/2000
https://github.com/Nriver/trilium-translation/releases

**Comment by zadam** [comment]
Hi, see #1852

**Comment by omaidb** [comment]
太感谢了
生命狂想


zadam ***@***.***> 于2021年6月22日周二 上午3:45写道：
