### ISSUE TITLE
trilium-data path changed?

### ISSUE THREAD

**Issue by TadasSu** [zadam/trilium#2035]
in image bded9d7970a5 trilium-data was in /root/trilium-data
now [image 33d7d834a143] it is in /home/node/trilium-data

So trilium-data path has been changed and docker volumes [for external trilium-data] stopped working.

(latest working version 0.45-latest)

**Comment by Nriver** [comment]
Maybe setting the TRILIUM_DATA_DIR environment variable like the [docker-compose.yml](https://github.com/zadam/trilium/blob/master/docker-compose.yml) will work?

**Comment by TadasSu** [comment]
Thank you for your suggestion. I will try this.
User has been changed also. trilium was running with root user in older releases. Now it runs on user node.
Line 14:
old: https://hub.docker.com/layers/zadam/trilium/0.45-latest/images/sha256-4e960283d7d506f61944f71fe9e5bcda0d6b6827896c4252d3156bb66ea692f8?context=explore
vs new:
https://hub.docker.com/layers/zadam/trilium/0.46-latest/images/sha256-7710463f600ecd986e58d947e85d9231f00629e21b74647a1830a62c8d07c59d?context=explore

**Comment by zadam** [comment]
Hi, yes, this was changed in #1422. At the time I didn't realize it will cause troubles for users who upgrade. Some other discussion is e.g. here #1747

**Comment by TadasSu** [comment]
My workaround (docker-compose.yml):
`version: "3.9"
services:
  trilium:
    image: zadam/trilium:latest
    user: root
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./trilium-data:/root/trilium-data"
    environment:
      - TRILIUM_DATA_DIR=/root/trilium-data
    restart: always`
