### ISSUE TITLE
FR: Remember the edit state

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#2036]
Hi

It would be very helpful if Trilium remembers the edit state of locked notes. Trilium seems to lock files with alot ofimages for viewing only which is fine, but this is not helpful in many situations because the unlock button is at the top and in a long file one looses the current line between unlocking and trying to find the line to edit.

Also a shortcut for the edit toggle  would be very helpful.

thanks

**Comment by Mirwaisse** [comment]
You can use the `#autoReadOnlyDisabled` label to solve your problem, if I understood it correctly.

**Comment by gerroon** [comment]
> You can use the `#autoReadOnlyDisabled` label to solve your problem, if I understood it correctly.

Thanks, that seems to be a partial solution since I still would like the lock feature enabled, just that it should remember the situation.

**Comment by zadam** [comment]
Hi, the edit button position will be (is) fixed in the next version. I also added possibility to define the shortcut.

The problem with scrolling to the beginning after editing is not simple unfortunately.
