### ISSUE TITLE
Encrypted note title and child title was shown during unprotected session, without entering password

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2038]
![image](https://user-images.githubusercontent.com/69441971/123484220-86321680-d5f7-11eb-8516-ac37e12a29e3.png)
Notice the "enter protected session" prompt and button.

I then unlocked it, file unlocked, everything worked. Exiting the protected session again resulted in correct behavior: 
![image](https://user-images.githubusercontent.com/69441971/123484287-9ea23100-d5f7-11eb-968a-7dacaf15030f.png)

**Comment by zadam** [comment]
Hi, what version are you using? This was fixed relatively recently, in 0.47.3 or so.

This used to happen when you entered the protected session, then e.g. frontend reloaded and did not notice that the protected session is still active and displayed wrong buttons ...

**Comment by sigaloid** [comment]
Oops, yes, 0.47.2. I restarted the wrong docker by accident, after updating to the recent one :sweat:
