### ISSUE TITLE
pdf file doesn't render properly in Windows client

### ISSUE THREAD

**Issue by grissiom** [zadam/trilium#2046]
The version of my Trilium: 0.47.4

Windows client could not display the pdf content properly. Here is the screenshot:
![image](https://user-images.githubusercontent.com/36101/123594721-a5f95280-d822-11eb-867d-6b20a097e3b9.png)

But the web interface is fine:
![image](https://user-images.githubusercontent.com/36101/123595159-2455f480-d823-11eb-9082-40e7b19f6944.png)

here is the relevant content in the log:
```
15:04:21.073 200 GET /api/tree?subTreeNoteId=TUVIBzWynUjh took 0ms
15:04:21.288 204 PUT /api/branches/nK2mFRUAxZBH/expanded/1 took 0ms
15:04:26.806 200 GET /api/notes/9iEP4jsdoa35 took 1ms
15:04:26.828 204 PUT /api/options took 0ms
15:04:27.762 200 GET /api/similar-notes/9iEP4jsdoa35 took 5ms
15:04:27.763 200 GET /api/notes/9iEP4jsdoa35/revisions took 0ms
15:04:27.765 200 POST /api/tree/load took 1ms
15:04:27.782 200 POST /api/notes/9iEP4jsdoa35/link-map took 0ms
15:04:32.690 204 POST /api/recent-notes took 0ms
```

Is there any hints? How could I solved the problem?

**Comment by FliegendeWurst** [comment]
Try updating to 0.47.5 (https://github.com/zadam/trilium/issues/1976#issuecomment-868785977)

**Comment by grissiom** [comment]
Thanks @FliegendeWurst , upgrading to 0.47.5 fixed the issue.
