### ISSUE TITLE
Recovered notes get the "recovered - " prefix in the sidebar all the time

### ISSUE THREAD

**Issue by grissiom** [zadam/trilium#2052]
Trilium version: 0.47.5

If a note is recovered, the title displayed in the sidebar always has the "recovered - " prefix. Even if I changed the title of the note. This is really annoying. How could I fix it?

The attachment is the anonymized DB, if it helps.

[anonymized-2021-07-02T004649.zip](https://github.com/zadam/trilium/files/6751430/anonymized-2021-07-02T004649.zip)

**Comment by zadam** [comment]
Hi, it's actually a specific "prefix" field - you can read about it here: https://github.com/zadam/trilium/wiki/Tree-concepts#prefix

You can change (remove) it in the context menu:

![image](https://user-images.githubusercontent.com/617641/124318603-2bf60000-db79-11eb-9044-1104bb57b48e.png)

**Comment by grissiom** [comment]
Thanks! That fixed my problem.
