### ISSUE TITLE
the code block is too long

### ISSUE THREAD

**Issue by ShadowDrifterII** [zadam/trilium#2063]
The code block is too long, it is unusable! Any solution!?
![code](https://user-images.githubusercontent.com/18482745/125182032-49e9e300-e1bf-11eb-880a-8cf8d06e5746.png)

**Comment by Oshino29** [comment]
` `code` ` for inline code
` ```code``` ``` for multiple-lines code

**Comment by ShadowDrifterII** [comment]
> 
> 
> ```
> for inline `code` type `back-ticks around` it
> ```
> 
> for inline `code` type `back-ticks around` it

Already do this :)

**Comment by zadam** [comment]
it's called "block", that's why it takes a whole line. If you use single backtick then it's inline ...
