### ISSUE TITLE
The tabs and window buttons are not clickable on the first few pixel rows

### ISSUE THREAD

**Issue by Mirwaisse** [zadam/trilium#2068]
![trilium_buttons](https://user-images.githubusercontent.com/25323123/126049439-36b8fdec-d8d1-412f-b9ab-97f976200908.gif)

It would be nice if we could click the buttons when the mouse is on the first pixel row, instead of having to "aim" down a little!

**Comment by bert010** [comment]
Mirwaisse, you could try another theme and check if it still happens, I've had this also once and it was theme related.

**Comment by abitofevrything** [comment]
It's a pretty easy [fix](https://github.com/abitofevrything/trilium/tree/control-button-fix) but it looks like this was done intentionally (the issue is caused by tabs & window control buttons having a `margin-top` set)... not sure why though.

**Comment by Mirwaisse** [comment]
> Mirwaisse, you could try another theme and check if it still happens, I've had this also once and it was theme related.

I don't think it's theme-related, the same thing happens with the default themes...
Could you share your theme to see if it indeed fixes the problem, please?

> It's a pretty easy [fix](https://github.com/abitofevrything/trilium/tree/control-button-fix) but it looks like this was done intentionally (the issue is caused by tabs & window control buttons having a `margin-top` set)... not sure why though.

Thank you for looking into it, I hope your commit can get merged!
