### ISSUE TITLE
How I can auto start Trilium server when booting

### ISSUE THREAD

**Issue by starsareintherose** [zadam/trilium#2080]
I have tried `systemctl enable trilium` or `systemctl enable trilium-server`, but all shows that 
```
Failed to enable unit: Unit file xxxx.service does not exist.
```
So, I can I make it auto start?

**Comment by gerroon** [comment]
I use Supervisor for this stuff, much easier

**Comment by starsareintherose** [comment]
Could you use command to explain it?

**Comment by Stitch10925** [comment]
A cronjob seems to work for me:

Create a script that starts Trilium

```
touch /boot/startTrilium.sh
nano /boot/startTrilium.sh
```

Place the following code in the script file

```
#!/bin/bash
cd trilium
nohup node src/www &
```

Create a cronjob to start the script

`crontab -e`

Add the following line to the cronjob file

`@reboot sh /boot/startTrilium.sh`

Save and exit the cronjob file

**Comment by starsareintherose** [comment]
I try to make a service file.
```
[root@archlinux systemd]# cd /usr/lib/systemd/system/
[root@archlinux system]# cat trilium.service
[Unit]
Description=Trilium

[Service]
ExecStart=/usr/bin/trilium-server

[Install]
WantedBy=multi-user.target
```
Then, I use `systemctl enable trilium` and `systemctl start trilium`

**Comment by SomwareHR** [comment]
> ExecStart=/usr/bin/trilium-server

What lives here?

**Comment by starsareintherose** [comment]
> > ExecStart=/usr/bin/trilium-server
> 
> What lives here?

systemd

**Comment by SomwareHR** [comment]
Hm, it's quite the opposite - "/usr/bin/" contains files that are NOT needed during boot-time.
Also, there is no "trilium-server" in "/usr/bin" - it probably depends on method of installation, and .tar file does not create a script there.

**Comment by starsareintherose** [comment]
> Hm, it's quite the opposite - "/usr/bin/" contains files that are NOT needed during boot-time. Also, there is no "trilium-server" in "/usr/bin" - it probably depends on method of installation, and .tar file does not create a script there.

If you want to know, I just tell you, just so.

**Comment by starsareintherose** [comment]
This issue has been closed, I shouldn't reply to anyone.
