### ISSUE TITLE
Close all resolved issues

### ISSUE THREAD

**Issue by abitofevrything** [zadam/trilium#2086]
Currently a lot of the open issues are either resolved and / or outdated but are not closed.
Closing these issues would allow us to see what actually needs to be fixed.

A few examples, found by clicking around in the issues tab:
- https://github.com/zadam/trilium/issues/1777
- https://github.com/zadam/trilium/issues/1733
- https://github.com/zadam/trilium/issues/1700

**Comment by zadam** [comment]
It's a non-trivial amount of work to do that and there's always something with higher priority. Help is welcome of course :)

**Comment by abitofevrything** [comment]
I will go through the issues and post ones I think would be closeable here.

**Comment by abitofevrything** [comment]
Hi, here are some of the issues I think should be closed that I have found so far:
- https://github.com/zadam/trilium/issues/632
- https://github.com/zadam/trilium/issues/612
- https://github.com/zadam/trilium/issues/594
- https://github.com/zadam/trilium/issues/583
- https://github.com/zadam/trilium/issues/567
- https://github.com/zadam/trilium/issues/566
- https://github.com/zadam/trilium/issues/669
- https://github.com/zadam/trilium/issues/750
- https://github.com/zadam/trilium/issues/739
- https://github.com/zadam/trilium/issues/732
- https://github.com/zadam/trilium/issues/730
- https://github.com/zadam/trilium/issues/718
- https://github.com/zadam/trilium/issues/714
- https://github.com/zadam/trilium/issues/712
- https://github.com/zadam/trilium/issues/697
- https://github.com/zadam/trilium/issues/687
- https://github.com/zadam/trilium/issues/782
- https://github.com/zadam/trilium/issues/781
- https://github.com/zadam/trilium/issues/767
- https://github.com/zadam/trilium/issues/866
- https://github.com/zadam/trilium/issues/835
- https://github.com/zadam/trilium/issues/1020
- https://github.com/zadam/trilium/issues/1017
- https://github.com/zadam/trilium/issues/1013
- https://github.com/zadam/trilium/issues/1100
- https://github.com/zadam/trilium/issues/1098
- https://github.com/zadam/trilium/issues/1083
- https://github.com/zadam/trilium/issues/1055
- https://github.com/zadam/trilium/issues/1050
- https://github.com/zadam/trilium/issues/1043
- https://github.com/zadam/trilium/issues/1040
- https://github.com/zadam/trilium/issues/1037
- https://github.com/zadam/trilium/issues/1032
- https://github.com/zadam/trilium/issues/1031
- https://github.com/zadam/trilium/issues/1028
- https://github.com/zadam/trilium/issues/1027
- https://github.com/zadam/trilium/issues/1165
- https://github.com/zadam/trilium/issues/1151
- https://github.com/zadam/trilium/issues/1139
- https://github.com/zadam/trilium/issues/1138
- https://github.com/zadam/trilium/issues/1241
- https://github.com/zadam/trilium/issues/1232
- https://github.com/zadam/trilium/issues/1177
- https://github.com/zadam/trilium/issues/1175
- https://github.com/zadam/trilium/issues/1173

These are issues that I think should be closed, but that is my personal opinion.

Here are some issues I found which could be closed, but I am not sure:

- https://github.com/zadam/trilium/issues/790
- https://github.com/zadam/trilium/issues/1081
- https://github.com/zadam/trilium/issues/1080 - Unable to reproduce

I will go through more issues tomorrow. I have also skipped most issues with tags on them, as I assume they have been reviewed already.

**Comment by abitofevrything** [comment]
More issues I have found that could be closed:
- https://github.com/zadam/trilium/issues/1319
- https://github.com/zadam/trilium/issues/1318
- https://github.com/zadam/trilium/issues/1316
- https://github.com/zadam/trilium/issues/1314
- https://github.com/zadam/trilium/issues/1305
- https://github.com/zadam/trilium/issues/1303
- https://github.com/zadam/trilium/issues/1302
- https://github.com/zadam/trilium/issues/1299
- https://github.com/zadam/trilium/issues/1299
- https://github.com/zadam/trilium/issues/1296
- https://github.com/zadam/trilium/issues/1295
- https://github.com/zadam/trilium/issues/1293
- https://github.com/zadam/trilium/issues/1291
- https://github.com/zadam/trilium/issues/1281
- https://github.com/zadam/trilium/issues/1276
- https://github.com/zadam/trilium/issues/1270
- https://github.com/zadam/trilium/issues/1268
- https://github.com/zadam/trilium/issues/1247
- https://github.com/zadam/trilium/issues/1245
- https://github.com/zadam/trilium/issues/1417
- https://github.com/zadam/trilium/issues/1414
- https://github.com/zadam/trilium/issues/1385
- https://github.com/zadam/trilium/issues/1377
- https://github.com/zadam/trilium/issues/1362
- https://github.com/zadam/trilium/issues/1346
- https://github.com/zadam/trilium/issues/1336
- https://github.com/zadam/trilium/issues/1330
- https://github.com/zadam/trilium/issues/1323
- https://github.com/zadam/trilium/issues/1472
- https://github.com/zadam/trilium/issues/1464
- https://github.com/zadam/trilium/issues/1451
- https://github.com/zadam/trilium/issues/1436
- https://github.com/zadam/trilium/issues/1435
- https://github.com/zadam/trilium/issues/1432
- https://github.com/zadam/trilium/issues/1555
- https://github.com/zadam/trilium/issues/1542
- https://github.com/zadam/trilium/issues/1536
- https://github.com/zadam/trilium/issues/1532
- https://github.com/zadam/trilium/issues/1523
- https://github.com/zadam/trilium/issues/1520
- https://github.com/zadam/trilium/issues/1501
- https://github.com/zadam/trilium/issues/1500
- https://github.com/zadam/trilium/issues/1493
- https://github.com/zadam/trilium/issues/1486
- https://github.com/zadam/trilium/issues/1482
- https://github.com/zadam/trilium/issues/1573
- https://github.com/zadam/trilium/issues/1570
- https://github.com/zadam/trilium/issues/1569
- https://github.com/zadam/trilium/issues/1560
- https://github.com/zadam/trilium/issues/1558
- https://github.com/zadam/trilium/issues/1671
- https://github.com/zadam/trilium/issues/1670
- https://github.com/zadam/trilium/issues/1667
- https://github.com/zadam/trilium/issues/1741
- https://github.com/zadam/trilium/issues/1735
- https://github.com/zadam/trilium/issues/1732
- https://github.com/zadam/trilium/issues/1728
- https://github.com/zadam/trilium/issues/1714
- https://github.com/zadam/trilium/issues/1713
- https://github.com/zadam/trilium/issues/1711
- https://github.com/zadam/trilium/issues/1814
- https://github.com/zadam/trilium/issues/1812
- https://github.com/zadam/trilium/issues/1811
- https://github.com/zadam/trilium/issues/1795
- https://github.com/zadam/trilium/issues/1776
- https://github.com/zadam/trilium/issues/1773
- https://github.com/zadam/trilium/issues/1858
- https://github.com/zadam/trilium/issues/1852
- https://github.com/zadam/trilium/issues/1837
- https://github.com/zadam/trilium/issues/1821
- https://github.com/zadam/trilium/issues/1943
- https://github.com/zadam/trilium/issues/1918
- https://github.com/zadam/trilium/issues/1993
- https://github.com/zadam/trilium/issues/1981
- https://github.com/zadam/trilium/issues/1957
- https://github.com/zadam/trilium/issues/2063
- https://github.com/zadam/trilium/issues/2037
- https://github.com/zadam/trilium/issues/2036
- https://github.com/zadam/trilium/issues/2030

Issues that might be closeable:
- https://github.com/zadam/trilium/issues/1727
- https://github.com/zadam/trilium/issues/1798
- https://github.com/zadam/trilium/issues/1782 - Unable to reproduce
- https://github.com/zadam/trilium/issues/1781
- https://github.com/zadam/trilium/issues/1880
- https://github.com/zadam/trilium/issues/1861
- https://github.com/zadam/trilium/issues/1854
- https://github.com/zadam/trilium/issues/1922
- https://github.com/zadam/trilium/issues/1915
- https://github.com/zadam/trilium/issues/1902
- https://github.com/zadam/trilium/issues/2000 - Maybe move to discussion
- https://github.com/zadam/trilium/issues/1990 - Maybe move to discussion
- https://github.com/zadam/trilium/issues/1975
- https://github.com/zadam/trilium/issues/2045
- https://github.com/zadam/trilium/issues/2035
- https://github.com/zadam/trilium/issues/2029
- https://github.com/zadam/trilium/issues/2026

And finally:
- https://github.com/zadam/trilium/issues/2086

**Comment by meichthys** [comment]
@abitofevrything Wow, Great work!

**Comment by zadam** [comment]
I closed all the recommended ones and I will look at the "might be closeable" soon ...
