### ISSUE TITLE
[Improvement] Multiline maths support and better editing interface (KaTeX)

### ISSUE THREAD

**Issue by aaronshenhao** [zadam/trilium#2088]
Please refer to main issue thread in the ckeditor5-math repository: [Edit window too small #10](https://github.com/isaul32/ckeditor5-math/issues/10)

***

The current math input box is too small and does not allow multiline equations like in Joplin. I haven't been successful in writing a multiline aligned equation (is `begin{align}` not supported?).

I think the best interface for writing TeX equations is the traditional vertically split interface with the code on the left and the output on the right, perhaps with the whole thing stacked under the bottom quarter to half of the screen (resizable, with possibility of being maximized).

Sidenote: Mathquill integration would be cool, perhaps as a shortcut for writing complex expressions.

**Comment by abitofevrything** [comment]
Hi,
This is an issue with the math plugin used in Trilium and there is already [an issue](https://github.com/isaul32/ckeditor5-math/issues/10) open over there. If you want to change the layout, you would have to submit an issue or PR over there.

**Comment by aaronshenhao** [comment]
Thanks for the link. Glad to know it's been brought up already. I searched for `math`, `katex`, `latex`, `tex` but it didn't show up.

**Comment by Mirwaisse** [comment]
To write multiline aligned equation, my workaround is to use on a second line `\panthom{left part of the equation}`.

For example, to get:
![image](https://user-images.githubusercontent.com/25323123/127392172-fc3cbe38-38e9-4927-b341-b5c4259b26a6.png)

I would write:
`\frac{dE}{dw_0} = -\frac 1 m \sum_{i=0}^m (y_i  - \operatorname{sigmoid}(w_0+w_1x_{1,i}+w_2x_{2,i}))`

and then in a second equation box:
`\phantom{\frac{dE}{dw_0}} = -\frac 1 m \sum_{i=0}^m (y_i  - \hat y_i)`

**Comment by abitofevrything** [comment]
@aaronshenhao you could close this issue since it is already present upstream, but then it technically isn't resolved so you might want to keep it open. Up to you.

**Comment by aaronshenhao** [comment]
@abitofevrything Thanks, I'll keep it open since I think the other issue is hard to find. I'll link it at the top of the thread.

**Comment by aaronshenhao** [comment]
Oddly enough, someone seems to have successfully used multiline align in that thread. Different version?

**Comment by abitofevrything** [comment]
They achieved this by using a phantom block, which isn't the cleanest way of doing it (a phantom block simply doesn't render it's content, but applies spacing).

As for `begin{align}`, I haven't tested so I am not sure if it is supported.

**Comment by Mirwaisse** [comment]
Wait, actually I have used multiline equation in the past like that:
![image](https://user-images.githubusercontent.com/25323123/127417774-20c39add-1a0a-4f0c-b86a-f4528c0bc4d8.png)
`f'(x) = \begin{Bmatrix} 1 & x>0 \\ 0 & x<0 \end{Bmatrix}`

**Comment by aaronshenhao** [comment]
> They used `\begin{aligned}` in that thread and not `\begin{align}`

Oh, that makes sense since its in math mode. I must have used the wrong one.

**Comment by gp-fault** [comment]
Any further ideas how to integrate MathQuill? That would be super cool!

**Comment by Nyxiad** [comment]
I'm going to make a separate issue regarding MathQuill

**Comment by eliandoran** [comment]
Done in https://github.com/TriliumNext/Notes/pull/2003.
