### ISSUE TITLE
Table dissapears when I drag and drop into another note

### ISSUE THREAD

**Issue by nielsnw** [zadam/trilium#2093]
Hi there,

When I drag and drop a table from one note to another, the table vanishes completely. It is gone in the original note and cannot be found in the note I dropped it in. When I copy/paste the table it does work.

Is this a known issue?

Looking forward, kind regards.

**Comment by zadam** [comment]
Hi, I just tested this and it seems to work for me ... could you record a show video/gif showing the issue?

**Comment by nielsnw** [comment]
Hi, thanks for looking into it. See attached.

https://user-images.githubusercontent.com/87858934/127729301-3cbe497d-b240-4267-bde1-7c861c392d08.mp4

**Comment by zadam** [comment]
Hi, I see, this is not supported. Although (drag & drop gives wrong indication).

What works is if you have 2 notes opened side by side (e.g. in separate windows) then you can drag between them.

**Comment by nielsnw** [comment]
Cool, thanks!
