### ISSUE TITLE
Syncing taking an absurd amount of time

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2100]
![image](https://user-images.githubusercontent.com/69441971/127882854-e8f5fe7a-4c8a-4d3e-90ce-f6ee511c76bd.png)
The syncing process is just displaying this over and over again. My document.db is ~150MB, and I only have ~1600 notes, but the pull count is in the 20,000's and it doesn't even seem to be moving at all at this point. 

Somehow I don't remember this occurring on my last fresh OS install when I synced it, but it could be that my db was a lot smaller then. Anyway, it's been stuck at the same outstanding pull count for ~15 minutes now. I was thinking of just `scp`ing the trilium-data folder to be honest, then any future syncs would be a lot faster once I have the whole db locally.

**Comment by sigaloid** [comment]
It stalled at a note that does not exist. Vacuum'd and consistency checked and then resynced, and the whole thing synced in a few seconds. I guess that a note not existing in the database stalls a sync? I know I didn't manually delete any notes from the file so it must be a bug of some kind. 

I assume it requested a note to sync because it thought it existed, meaning it was in some sort of index that the server gave to the client. But when requesting that note ID from the server, it fails. Oddly it blocked "https://(___)/api/sync/changed?lastEntityChangeId=30997", perhaps because requesting changes means the server looks at all notes including a possibly broken one. 

Perhaps when a client attempts to sync, a consistency check can be made beforehand? Leaving this open if this is something you might want to change the behavior for. If not, free to close

**Comment by zadam** [comment]
Hi, it's true that database inconsistency can cause some bugs, including stalled sync. As you mention, it would be ideal to run consistency checks before every sync attempt (normally once a minute) but it is not done so because consistency checks are relatively expensive (on large databases).

Database inconsistencies are usually caused by bugs but there are also complex sync situations which can cause them ...

**Comment by sigaloid** [comment]
Hm, good point, I was thinking of only when syncing a new device because my existing install seemed to sync just fine... not sure why though?... Perhaps my memory serves me wrong. But I agree that every minute would indeed be very taxing.

**Comment by sigaloid** [comment]
Closing, because this seems to be a bog-standard DB issue. Perhaps add a message about a stalled sync and what to do (consistency check) but besides that I can't reproduce it.
