### ISSUE TITLE
[Feature Request?] Stop creating date-tree when clicking Search or New Note

### ISSUE THREAD

**Issue by Stitch10925** [zadam/trilium#2101]
Every time I click "Search" to find one of my notes, or when I click the "New Note" it always creates a date-tree:

![afbeelding](https://user-images.githubusercontent.com/69055295/127939205-faec179c-f279-4f49-bf94-736261da3ce1.png)

Is there a way to disable this? I am very particular about my structure and I don't need the program to randomly start dumping date-trees inside my structure because I want to search something.

It's great that the possibility to store searches and quickly create new notes is there, but I should be able to choose if, when the button is pressed, the note is created as sub-node under my current selected node, or if it should create the date-tree.

**Comment by abitofevrything** [comment]
I also find this to be an issue...
If you know what you are doing you can override the `Entrypoints` prototype with the script API and define a custom `createNoteIntoInboxCommand()` function to create a note where you want, but this is a bit messy.

**Comment by ShadowDrifterII** [comment]
same here

**Comment by blumpcus** [comment]
I also do not like this behavior as a default, it feels like it should be an toggle or invoked by request, not as a default.

**Comment by zadam** [comment]
In v0.48 clicking on "search" does not create a search note automatically.

For "new note", you can override the default behavior by giving some note `#inbox` label, "new note" will then create children there instead of in the calendar structure.
