### ISSUE TITLE
API error "value.startsWith is not a function" when calling note.setLabel() with wrong type

### ISSUE THREAD

**Issue by QuentinLeCaignec** [zadam/trilium#2104]
Trilium version 0.47.5.

I have a script where I make a new note (api.createTextNote) and return that note reference, I then call api.openTabWithNote(note.noteId, true);

It works, but it also throws the following logs and errors :

At tree.js:75
```
14:52:07 Did not find parent root (root) for child IgFOUC0PuWaN (TEST NOTE), available parents: g5DKQSM1pifu (NEW NOTES)
```
At toast.js:75 
```
14:52:08 error:  Error when calling GET /api/similar-notes/IgFOUC0PuWaN: 500 - value.startsWith is not a function
```

At ws.js:21
```
14:52:08 Error when calling GET /api/similar-notes/IgFOUC0PuWaN: 500 - value.startsWith is not a function
v @ ws.js:21
throwError @ toast.js:87
c @ server.js:106
async function (async)
c @ server.js:104
(anonymous) @ server.js:165
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
```

At toast.js:89
```
Uncaught (in promise) Error: Error when calling GET /api/similar-notes/IgFOUC0PuWaN: 500 - value.startsWith is not a function
    at Object.throwError (toast.js:89)
    at c (server.js:106)
    at async EventEmitter.<anonymous> (server.js:161)
throwError @ toast.js:89
c @ server.js:106
async function (async)
(anonymous) @ server.js:165
emit @ events.js:315
onMessage @ electron/js2c/renderer_init.js:93
```

It seems like the "NoteId" I provide doesn't work itself and it has to search for available parents, and a searching/filtering parameter used (startsWith) isn't available. It still opens the new note in a new tab but throws these messages and errors every time.

**Comment by QuentinLeCaignec** [comment]
Oh, I think there might be still be an underlying error/bad type checking but for now I managed to fix the error by adding .toString()  to the value I pass into the note.setLabel() API function.

**Comment by zadam** [comment]
Hi, thanks for reporting this problem. I added coercing the attribute value into a string, that should prevent such issues. (only on master branch though).
