### ISSUE TITLE
When mac run sync with server on docker,the docker will stop.

### ISSUE THREAD

**Issue by hideonbeach** [zadam/trilium#2107]
But I  use windows10 run sync,it will be OK.Please fix it.I think it's my vps is sth. wrong,but i rebuild it the same either.

**Comment by zadam** [comment]
Looks like I missed this issue. If this problem still occurs could you fill in more details? What "docker will stop" means? Does the app crash? You're building it from source?

**Comment by zDEFz** [comment]
> But I use windows10 run sync,it will be OK.Please fix it.I think it's my vps is sth. wrong,but i rebuild it the same either.

I think your VPS or your Docker is out of RAM and runs into "Segmentation Fault"
