### ISSUE TITLE
Using single back ticks in the editor to create an inline code block doesn't consume the back tick

### ISSUE THREAD

**Issue by Geosearchef** [zadam/trilium#2108]
Using single back ticks " \` " in the editor to create an inline code block causes the first back tick to be consumed instantly once the second one is typed and an inline code block `like this one` is created.

Continuing to type then will create a back tick on space ` or an àccent for a character.

**Comment by zadam** [comment]
Hi, could you record this behavior? Either I'm not able to reproduce it or I don't understand the issue ....

**Comment by Geosearchef** [comment]
https://geosearchef.de/triliumInlineCodeBlock.mp4

I'm typing a space after the code block, the first backtick gets removed, but the \` get's inserted instead of that. Some case for typing a character like "a", would turn into "à".

This issue occurs using the electron app on Fedora or the web app in chromium. I cannot reproduce it using Firefox.

**Comment by zadam** [comment]
Hmm, interesting. It works correctly for me - electron app on ubuntu/windows.
![Peek 2021-08-14 11-49](https://user-images.githubusercontent.com/617641/129442089-ce4081ae-49de-4ec7-881d-337668b5d76e.gif)

**Comment by abitofevrything** [comment]
It may be to do with keyboard localisation, in some languages (like french for example) typing a backtick then a character can have special effects in some cases.
