### ISSUE TITLE
[Feature Request] Read-only secondary user

### ISSUE THREAD

**Issue by MalakanC** [zadam/trilium#2109]
I achnowledge the reasoning behind not currently supporting multiple users, as stated in the FAQ. However, a read-only user may be more easily implemented and could allow the user to share notes taken for various projects for peer-review or just sharing ideas in general.

**Comment by zadam** [comment]
Hi, there is a plan to allow publishing notes in a read-only website. That should cover similar use cases.

**Comment by MalakanC** [comment]
Would/could this read-only website be setup much the same way as Trilium, i.e. self-hosted?

Allow for pushing notes from trilium to the website would be nice. Is there any documentation on this plan before I spurt ideas/suggestions that have already been covered?

**Comment by zadam** [comment]
There isn't any docs, just ideas in my head. Feel free to share yours.

The read only website will be part of Trilium "server edition" - so yes, self-hosted. You will be able to mark certain notes (or subtrees) as "public" and they will be made accessible from some specific address.

**Comment by MalakanC** [comment]
If a note is marked public and edited, would that be auto-update on the website side or would I have to re-publish to the website? 

Maybe these could be an option for the user: auto-update with optional time delays so that it doesn't try and update too frequently during an edit, in case that is taxing on the servers.


Password protected, so that not just anyone can access the port and see the notes. I'd like to share to specific people but don't want the whole world to see it.


That's all I've got for right now. May add more as they come to mind.

**Comment by sigaloid** [comment]
This has been implemented in v0.49.0-beta release: https://github.com/zadam/trilium/wiki/Sharing

**Comment by MalakanC** [comment]
Works great, thank you!
