### ISSUE TITLE
Mobile frontend crashes the Trilium?

### ISSUE THREAD

**Issue by WantToLearnJapanese** [zadam/trilium#2111]
I reset the system by deleting all the docker volumes for Trillium but same thing happens even I did not execute  mobile version.

---

Trilium Version: the latest commit "fixes in frontend sync".

With, v0.47.5, I had issues with view synchronization on Desktop web front-end. (The deletion on windows desktop version were not reflected on web frontend. Though on recent change, it says the page is deleted, but still the page is listed on web version)
And it seems the issue I described above fixed with the latest commit "fixes in frontend sync".

But I think, similar issue happen on mobile web (iOS Safari). If I delete some note on mobile web, it crashes the web front end on both of mobile web  and desktop web. After the deletion, if I click "create child note", the desktop version says following
```
Error when calling POST notes/MgTVhq6QAvKV/children?target=into&targetBranchId=undefined: error -
```

**Comment by zadam** [comment]
Hi, since you're referencing a particular commit, are you running a master branch? If you build server version yourself, you need to use `stable` branch, `master` is development and unstable.

**Comment by WantToLearnJapanese** [comment]
> Hi, since you're referencing a particular commit, are you running a master branch? If you build server version yourself, you need to use `stable` branch, `master` is development and unstable.

Yes I am using master branch. Sorry to make you confused.

Since I had issue on latest stable version, I thought the issue is resolved with master branch. (As the commit message, front end issue sync issue solved)

Can you recommend which version I should use? 

Thank you

**Comment by zadam** [comment]
`master` should not be used in general. ARM64 builds are probably (very) outdated.
