### ISSUE TITLE
Question: Is there a difference between Desktop web and Electron version?

### ISSUE THREAD

**Issue by WantToLearnJapanese** [zadam/trilium#2112]
I guess the only difference is that data are synced locally for the Electron version?

**Comment by abitofevrything** [comment]
Considering you can run the electron version and still connect via a browser to the backend server it creates, not on the functionality side of things.
Some UI features (UI scale for example) are only available on electron though.

**Comment by zadam** [comment]
There are few feature differences, usually because something is available in electron but not in the browser - e.g. PDF viewer. But otherwise both version are largely equal.
