### ISSUE TITLE
Bug: Image caption not imported correctly

### ISSUE THREAD

**Issue by pssandhu** [zadam/trilium#2113]
**Describe the bug**
When a note is exported as HTML the image caption is placed in a `<figcaption>`. However, when the HTML file is imported back into trilium the image caption is empty. Opening the note externally or exporting it again shows that the caption is now just text next to the `<img>` tag with the `<figcaption>` missing.

**To Reproduce**
1. Create a note with an image and give it a caption
2. Export the note as HTML
3. Import the note
4. Observe the missing caption

Version: 0.47.5

**Comment by zadam** [comment]
Hi, thanks for reporting, this was fixed in master and will be released in 0.48
