### ISSUE TITLE
【Bug】Insert PDF file in the Note with full size but still show with small size

### ISSUE THREAD

**Issue by Tlonglan** [zadam/trilium#2116]
**My appversion: 0.47.5**

I insert PDF file in the Note **with full-size**, but it still show with **small-size**

In addition, when I insert the image, no matter what size I choose, it seems to always show with full-size,and I can change the image size 

![image](https://user-images.githubusercontent.com/38731172/129835378-df338432-e5bf-4e2f-944d-7a6b3466e9a4.png)

[trilium-2021-08-18.log](https://github.com/zadam/trilium/files/7004412/trilium-2021-08-18.log)

**Comment by zadam** [comment]
Hi, thanks for the bug report, fixed. Will be released in next stable version.
