### ISSUE TITLE
Version 0.47.6 mobile front-end issue: 1)Width of pane 2)Theme

### ISSUE THREAD

**Issue by WantToLearnJapanese** [zadam/trilium#2120]
1) Width overflows over actual display size. (A bit misaligned)

2) Theme is not applied correctly. It seems that every theme (including Nier-Automata) is broken now. If you select some theme, the appearance of Trillium is changed but not as intended.

**Comment by zadam** [comment]
1. could you post screenshot? Looks OK on my side:

![image](https://user-images.githubusercontent.com/617641/130352031-61e10b96-1357-4449-b3ce-a5a5cb9092c0.png)


2. Did these themes work correctly in the past on mobile? There hasn't been any significant change in this regard recently.

3rd party themes could also not be made with mobile frontend in mind and that could cause the breakage. The "official" themes seem to work OK.

**Comment by WantToLearnJapanese** [comment]
1. The right edge of the selected image is invisible.
![image](https://user-images.githubusercontent.com/88884927/130352362-6c21d47d-4a38-4c6a-8047-f0d9e96d2c36.png)

And on the navigation view, it seems misaligned to the right size. I will upload the screenshot for the navigation view in the following reply.

2. It happens for the "Black" theme also.
![image](https://user-images.githubusercontent.com/88884927/130352312-02ed95ee-596e-4618-b16a-2565520178c0.png)

**Comment by WantToLearnJapanese** [comment]
![image](https://user-images.githubusercontent.com/88884927/130352432-a886064b-4705-4469-80c6-8f895fc6402e.png)

**Comment by WantToLearnJapanese** [comment]
Jeez... 

You are right. Although I didn't select the theme. Some theme(allure-clear, in this case) were interfering.

The problem is solved after I remove the note containing allure-clear theme 

Thank you.
