### ISSUE TITLE
Question about a code note.

### ISSUE THREAD

**Issue by WantToLearnJapanese** [zadam/trilium#2122]
Question about a syntax highlight feature on code notes.

- I want to have a syntax highlight for the bash script. Is this also related to CKEditor?
- Which version of CKEditor is being used for Trilium?
  -  While there is no CKEditor-related line on the package.json, are files in /libraries/ckeditor only things for CKEditor?

**Comment by zadam** [comment]
Code notes are using CodeMirror v5. Bash is supported as "shell".

**Comment by WantToLearnJapanese** [comment]
> Code notes are using CodeMirror v5. Bash is supported as a "shell."

I can't find "shell" on the drop-down menu. 

Am I missing something?
