### ISSUE TITLE
[Feature Request?] Could we get a context menu for the "hovered" note, instead of the "selected" note?

### ISSUE THREAD

**Issue by WantToLearnJapanese** [zadam/trilium#2124]
It seems the behavior is specific to the "hoist menu".

Currently, the context menu(right-click) works for selected notes wherever the mouse is hovered on.

And I think this is not general behavior.

Could we get a context menu for the "hovered" note instead of the "selected" note?

**Comment by tpwrules** [comment]
@zadam I think this would be a good feature too. IMO this behavior is a bug.
