### ISSUE TITLE
Fail to render imported markdown file's LaTeX equations  [Trilium Version 0.47.5]

### ISSUE THREAD

**Issue by Zander-M** [zadam/trilium#2127]
When opening imported markdown files, the LaTeX equations are not rendered correctly. This happens when the file doesn't contain a LaTeX equation created in Trilium Notes. However, if I open another file created in Trilium with LaTeX equations in it, and then go back to the file, the LaTeX equations are rendered correctly.  I assume that it's related to how the KaTeX plugin is loaded?

**Comment by Zander-M** [comment]
Is there any plan to update this feature? I really like that I can import markdown files with LaTeX equations into Trilium. It would be nice if they can be displayed correctly when I open Trilium.

**Comment by zadam** [comment]
Not from my side. It's not an easy problem and the benefit isn't that big (IMHO). PRs are welcome though.

**Comment by Zander-M** [comment]
Thanks for the answer : )
