### ISSUE TITLE
[Feature Request] let Trilium tree structure mimic a filesystem folder structure

### ISSUE THREAD

**Issue by PDiracDelta** [zadam/trilium#2130]
Trilium is excellent for note-taking.
Note-taking is usually just one aspect of a possibly co;plex and hierarchical project.
It would be great to sync (or perhaps only generate) a tree of (empty) notes based on a folder structure in the filesystem.
Basically, this eliminates the need for making README.txt files everywhere.

**Comment by zadam** [comment]
You can generate a tree structure by ZIPping a directory structure and importing it.

In general, syncing with filesystem is a can of worms which I'd rather avoid.

**Comment by PDiracDelta** [comment]
OK, that makes sense. Any chance you could make it an option to import only the directory structure (and skip any files)? 
I'm only interested in the tree structure itself [for taking notes], not the dozens of files and images I have inside my folders.

**Comment by zadam** [comment]
Hi, I'm not sure if you use case is general enough to deserve an option. It's not only the initial implementation cost, each feature/option bring additional effort in maintenance / testing in the future.

I would recommend to create a simple script which will copy the directory structure to some temp directory, then delete only the files and keep the directories (with shell you can do it like [this](https://askubuntu.com/a/851369)) and then ZIP, import ...

**Comment by PDiracDelta** [comment]
Excellent suggestion, thanks.
I know this is not StackOverflow, but for others who need this solution and are working with files, you could also immeditaly create a copy of your directory structure without copying any files like so (and then import in Trilium after ZIPping):
`rsync -av -f"+ */" -f"- *"`
([source](https://www.cyberciti.biz/faq/unix-linux-bsdosx-copying-directory-structures-trees-rsync/))
