### ISSUE TITLE
XSS In Trilium search bar

### ISSUE THREAD

**Issue by ShadowDrifterII** [zadam/trilium#2145]
version of Trilium 0.47.7

![12](https://user-images.githubusercontent.com/18482745/131953016-a024c01b-b1e3-475a-9149-548c9d905912.PNG)

**Comment by zadam** [comment]
fixed.

This is not a true "XSS" though since this allows a user to "attack" themselves only.

**Comment by abitofevrything** [comment]
Self-XSS can be dangerous too...
