### ISSUE TITLE
"401 Unauthorized" after trying to sync with a new server instance (v0.47.5 and 0.47.7)

### ISSUE THREAD

**Issue by XrenynTheMage** [zadam/trilium#2157]
About a month ago I bought a Raspberry Pi 4B and set up a private Trilium Notes server according to [your tutorial using Docker](https://github.com/zadam/trilium/wiki/Docker-server-installation). The only thing I did differently was that I used [the unofficial ARM Docker Image from jcoin](https://hub.docker.com/r/jcoin/trilium-server) because hlince had apparently stopped releasing ARM builds for Trilium, and everything worked quite nicely regarding Trilium. Only thing was that Raspberry Pi OS started to crash every 1-2 days and not write logs to the SD card anymore, which is why I decided to simply reinstall the OS (without taking a backup, of course 🤦‍♀️️) and set up a new Trilium Notes server using [the exact same Docker Image](https://hub.docker.com/layers/jcoin/trilium-server/v0.47.5/images/sha256-b85601066cdf6315d281dc681291135148757bf0ec590fb9ee225f1bba25b23a?context=explore) as before. 
During the setup process of the new Trilium Notes Server, I get prompted to configure one of my Trilium clients to initiate synchronization, but when I do so the client responds with the following message and does not synchronize:

`Sync failed: Request to POST http://192.168.0.214:8080/api/login/sync failed, error: 401 Unauthorized`

This happens with the old (now gone) server, the new server, and the clients running Trilium version 0.47.5 and the issue persists if I  upgrade one of my clients to the most recent Trilium version (0.47.7) and try to sync it with a new v0.47.7 server. I should also mention that I use 2 computers times 2 OSes (Windows 10 and Ubuntu 20.04LTS) = 4 Trilium Clients.

 
logs from my upgraded Trilium 0.47.7 client below:
[trilium-2021-08-18.log](https://github.com/zadam/trilium/files/7138062/trilium-2021-08-18.log)
[trilium-2021-09-06.log](https://github.com/zadam/trilium/files/7138063/trilium-2021-09-06.log)
[trilium-2021-09-07.log](https://github.com/zadam/trilium/files/7138064/trilium-2021-09-07.log)
[trilium-2021-09-08.log](https://github.com/zadam/trilium/files/7138065/trilium-2021-09-08.log)
[trilium-2021-09-09.log](https://github.com/zadam/trilium/files/7138066/trilium-2021-09-09.log)
[trilium-2021-07-30.log](https://github.com/zadam/trilium/files/7138052/trilium-2021-07-30.log)
[trilium-2021-08-01.log](https://github.com/zadam/trilium/files/7138053/trilium-2021-08-01.log)
[trilium-2021-08-02.log](https://github.com/zadam/trilium/files/7138054/trilium-2021-08-02.log)
[trilium-2021-08-07.log](https://github.com/zadam/trilium/files/7138056/trilium-2021-08-07.log)
[trilium-2021-08-08.log](https://github.com/zadam/trilium/files/7138057/trilium-2021-08-08.log)
[trilium-2021-08-10.log](https://github.com/zadam/trilium/files/7138058/trilium-2021-08-10.log)
[trilium-2021-08-11.log](https://github.com/zadam/trilium/files/7138059/trilium-2021-08-11.log)
[trilium-2021-08-12.log](https://github.com/zadam/trilium/files/7138060/trilium-2021-08-12.log)
[trilium-2021-08-17.log](https://github.com/zadam/trilium/files/7138061/trilium-2021-08-17.log)

P.S I absolutely love Trilium and can't imagine living without it, you have my deepest respect for developing this amazing piece of software. I don't have a lot of money to spare for funding its development (unfortunately), as I still attend university full-time, but I think I could completely or at least partially compensate you for solving or helping me solve this issue, depending on how much work it'll be.

**Comment by XrenynTheMage** [comment]
In case anyone encounters the same bug, there is a workaround: One can export all notes (by right-clicking the `root `note) from one of the old, malfunctioning clients as HTML and import them into a new server instance

**Comment by zadam** [comment]
Yeah, that makes sense. Time has to correspond between sync client and server to mitigate potential replay attacks.

To be clear, the timezones can be different, it's just important that it's set correctly so that "unix timestamp" come out within 300 second difference.
