### ISSUE TITLE
Feature request - WEB UI log-in to sync

### ISSUE THREAD

**Issue by kxdyz** [zadam/trilium#2158]
Hello, 
would be possible to add "login function" through web for sync? I use authelia and traefik and don't want to expose the service to the internet directly.. If I could log-in through authelia with some permanent coockie, that would be really great.. So why I don't use web environment directly you ask? I would prefer desktop trilium for primary note taking. I probably could sync on local network only, but that does not seem as right solution.. I am newbie so if there is some obvious solution I don't see.. please will be happy for any advice.. Thank you

**Comment by zadam** [comment]
Hi, perhaps you could expose/whitelist the sync endpoints only? Sync process is using authentication so it doesn't leak any data ...

**Comment by kxdyz** [comment]
Thank you for the fast answer.. sorry could you elaborate more? I know how to expose whole trilium.. and if sync is through specific URL I can whitelist that..? and not the frontend? thank you

**Comment by kxdyz** [comment]
Hi, I found solution in authelia settings, created bypass rule only for api calls.. Thanks for the tip. Keep the good work.
