### ISSUE TITLE
runOnNoteCreation and runOnAttributeCreation seem not to work

### ISSUE THREAD

**Issue by r-nd-m** [zadam/trilium#2166]
Trilium version 0.47.7
[trilium-2021-09-13.log](https://github.com/zadam/trilium/files/7154232/trilium-2021-09-13.log)

Events ~runOnNoteCreation and ~runOnAttributeCreation seem not to work.

I've created a following setup:
I have modified a standard Journal example so it doesn't create a daily entry, but stops at the month's level.
I have also modified a demo note template in such way that it has an attribute "~runOnNoteCreation=New Note", where "New Note" is a backend script to create a date label in the new note and modify the default title to also show the same date value.
When I create a new note with the template above, the script doesn't run (or at least doesn't work properly) - neither the label is created nor the tile modified. When I change the event to ~runOnNoteChange, the script does run but obviously that's not a good solution as it runs basically on every note modification (which in turn seems to reset the cursor position to the beginning of the note). 
The script does run partially (date label is created but the title is not changed) when I change the attribute "~runOnNoteCreation=New Note" as inheritable and create an inner note to the new note with inherited attribute:
```
Year
-> Month
     ->  Note 1         <- created using a template, with inheritable attribute "~runOnNoteCreation=New Note"
           -> Note 2    <- note in which label is created as required
```
 
I've tried a similar setup with ~runOnAttributeCreation to get the same result.

Backend script looks like that (simplified for testing purposes):
```
api.log('date test');

const note = api.originEntity;

note.setAttribute('label', 'date', '2021-09-13');
note.title = '2021-09-13 new note';
```

**Comment by zadam** [comment]
You need to call `.save()` method:

```
note.title = '2021-09-13 new note';
note.save();
```

`runOnNoteCreation` is not triggered because the `template` relation is assigned after note is created, so the template can't receive this event. Alternative option would be to use `runOnChildNoteCreation` on a parent note.

**Comment by r-nd-m** [comment]
Thank you - fixed based on your suggestions.
