### ISSUE TITLE
The "WEEK" syntax can not work in search. But "TODAY" , " MONTH" is work fine.

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#2169]
The "WEEK" syntax can not work in search. But "TODAY" , " MONTH" is work fine.

can not work, and return "No notes have been found for given search parameters."
```
note.dateCreated > WEEK-1
```

work fine
```
note.dateCreated > TODAY-1
note.dateCreated > MONTH-1
```

**Comment by zadam** [comment]
Hi, yes, it looks like WEEK was not implemented in the end (it is more complicated than the other ones). I removed it from the documentation. Thanks.
