### ISSUE TITLE
Search should ignore accents

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2182]
I'm on Trilium 0.47.5. I'd like search (at least in Jump to note - Ctrl+J - and in linking dialog - Ctrl+L) to ignore accents when searching. I have pages for people I know from non-English speaking countries, and their names include accents. But my default keyboard is English. If I want to jump or link to someone whose name has an accent, since search does not ignore accents, I have to switch keyboards, which is more work than it could be otherwise.

**Comment by zadam** [comment]
Hi, yes, that makes sense. Now the strings are "normalized" before search.

**Comment by agentydragon** [comment]
Thanks a lot for swift resolution <3
