### ISSUE TITLE
Yet another question about  certificate.. trilium-desktop, windows

### ISSUE THREAD

**Issue by thehotery** [zadam/trilium#2194]
Is there's any way to disable certificate check then using batch file? Some command-line options or something?

The problem is I want to pin trilium desktop app onto windows taskbar. but with batch file its not possible - windows for some reason dont allow to pin more then one shortcut to the .exe and I already have cmd.exe pinned, so .batch file became 2nd. 
Any workarounds?

For what crazy reason I want to disable certificate check? Its about antivirus software that, to perform https check, insert its CA cert into system/firefox and decrypt all traffic [like mitm, but with good intensions]. And its works well with chrome and anything that using system certificate store + firefox. Another way can be to "allow" its CA, but dontknow how..

**Comment by abitofevrything** [comment]
Looking in the `trilium-no-cert-check.bat` (or `.sh`) file, you can see that the environment variable that dictates whether  trilium should check certificates is `NODE_TLS_REJECT_UNAUTHORIZED`. Setting this to `0` will disable certificate checking (`set NODE_TLS_REJECT_UNAUTHORIZE=0`).

As for your problem with the task bar, you can follow the instructions [here](https://winaero.com/pin-file-taskbar-windows-10/), or you can add a shortcut to the file in this directory: `%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar` (this is where programs and files pinned to the task bar are saved). The `User Pinned` folder is hidden, so you will have to either enter the path manually or select the "show hidden items" option.
