### ISSUE TITLE
Add "code" basic style to CKEditor

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#220]
See https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html#demo

**Comment by CrashLaker** [comment]
Hi @zadam 

Is it possible to add block code structure in CKEditor?

Or at least add a <pre> tag.

Regards!

**Comment by zadam** [comment]
I would wish to do that, but unfortunately this functionality is not available in CKEditor right now. It's highly requested so I hope it will appear soon so I can integrate it.

**Comment by zadam** [comment]
Code block support is in 0.38.0-beta
