### ISSUE TITLE
Segmentation fault (SIGSEGV) when trying to save edited PDF

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2205]
When I edit a PDF and click the Download button and save with changes, trilium gives me this error: 
`fish: “trilium” terminated by signal SIGSEGV (Address boundary error)`
I was going to save it to `/tmp/` then click upload new revision. This seems like an internal error with Chromium's PDF handler, though, but if there is something I can do to debug this or get more helpful logs I'm glad to.

Standard 64-bit CPU, 4GB ram, running Lubuntu (LXDE). Can't imagine anything particular about my setup; will try on my desktop when I get home.

**Comment by abitofevrything** [comment]
I'm able to get the following logs out of electron with `--enable-logging`, meaning this is almost certainly a chromium error.
```Received signal 11 SEGV_MAPERR 000000000000
#0 0x55f2b9aeecf9 (/usr/lib/electron13/electron+0x4703cf8)
  r8: 0000000000000004  r9: 0000000000000000 r10: 0000000000000001 r11: 00007ffeef022fa8
 r12: 00007ffeef023190 r13: 00002566ba6a6000 r14: 0000000000000004 r15: 00007ffeef0230a0
  di: 00002566ba9c8cc0  si: 00007ffeef0231f0  bp: 00007ffeef023090  bx: 00007ffeef023050
  dx: 00007ffeef023190  ax: 0000000000000000  cx: aaaaaaaaaaaaaaaa  sp: 00007ffeef023030
  ip: 000055f2b994ce01 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by sigaloid** [comment]
If it's just Trilium that this happens with, then this might be in-scope for this issue (rather than being an upstream issue). I can't find any other applications it crashes with, shall I try reporting it in the Electron repo? I'm not familiar with the particulars with how Trilium handles PDF's, maybe there's a library it uses to open it? 

https://github.com/zadam/trilium/blob/f6776df645ae2cb87b588274e88eb9db56193e11/src/public/app/services/note_content_renderer.js#L82-LL84 seems to say it's just an iframe. I wonder if we could get a Windows user to test this, maybe it's handled differently? 

In the browser, it handles it just fine in Firefox and Chromium. It's only the desktop version implying it's an Electron issue. 

I'll see if I can get some sort of debugging running.

**Comment by sigaloid** [comment]
Alas, it's true. 

https://user-images.githubusercontent.com/69441971/136713578-13a83c57-5e7b-495c-82fc-2cdf81ffaeb0.mp4

Time to report upstream! Closing for now.

**Comment by sigaloid** [comment]
>This might be fixed in electron 15+ but Trilium still uses electron 13 and I'm not sure how to migrate (electron-rebuild nightmares).

It seems to occur in 15 as well: https://github.com/sigaloid/electron-pdf-crash/blob/main/package.json#L20
