### ISSUE TITLE
(Bug report) 0.48 beta: errors with backend API "get" methods

### ISSUE THREAD

**Issue by mabeyj** [zadam/trilium#2230]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.1-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 21H1

### Expected Behavior

The backend `api.getNote`, `api.getBranch`, and `api.getAttribute` methods shouldn't cause an error.

### Actual Behavior

Create a JS frontend code note:

```js
(async () => {
    const result = await api.runOnBackend(noteId => {
        return api.getNote(noteId);
    }, [api.currentNote.noteId]);
    console.log(result);
})();
```

Open the dev console, execute the script, and an error occurs: `Error: server error: Load of script note "<note title>" (<note id>) failed with: Cannot read property '<note id>' of undefined"`

Similarly, `api.getBranch` and `api.getAttribute` also cause errors.

### Additional Information

Replacing `api.getNote` with `becca.getNote` works (as well as `becca.getBranch` and `becca.getAttribute`).

The issue seems to be these three methods on `BackendScriptApi` are assigned their respective `becca` methods, and the `becca` methods use `this` which is undefined when the backend methods are called: https://github.com/zadam/trilium/blob/21d2ca3c54557a04c5fa4a648e36bdfc96709c51/src/services/backend_script_api.js#L61-L75

**Comment by zadam** [comment]
Hi, thanks for report, fixed.
