### ISSUE TITLE
(Bug report) The input box of the local search cannot get the focus again after losing the focus. 

### ISSUE THREAD

**Issue by olapEin** [zadam/trilium#2254]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows10 21H2

### Expected Behavior

The input box for local search can gain focus again after losing focus.

### Actual Behavior

![XLEgxC0lI8](https://user-images.githubusercontent.com/73106094/138284297-8f82fc34-316d-492d-b42b-1fecf0ad48a1.gif)

### Additional Information

* The local search button can still be used after losing focus.
* A new local search box is created without any operation on the previous local search box by <kbd>ctrl</kbd>+<kbd>F</kbd>. I hope that when there is already a local search, <kbd>ctrl</kbd>+<kbd>F</kbd> will no longer perform any operation.

**Comment by LorenAmelang** [comment]
`"I plan to replace this with native CKEditor one (it is already available through menu, but not through shortcut)."`

```
https://github.com/zadam/trilium/wiki/Search
You can activate note search by clicking on magnifier icon on the left or pressing CTRL-S keyboard shortcut.
```

Seems Ctrl+S now gets "Quick Search" of notes, at top left of window. The Magnifier Icon gets something different: 
![SearchIcon](https://user-images.githubusercontent.com/1297090/141015567-351dfe6b-a2b6-46f8-98fe-b4a5b5f8eebc.png)

I guess that "Change note icon" button is the one to perform a search? 
But no matter what I try to input, my results are a page full of hundreds of B&W emoji...  
I suspect it is searching _for_ notes, not within the current one? Is it documented somewhere? 

So I guess that isn't the "native CKEditor one, already available through menu"? 

I can't find anything else related to the Menu - what am I missing? 

Actually, I'm fine with the old Ctrl+F search, except there now seems to be no way to "find next" except clicking the tiny '>' icon right next to the Close 'X'. I'd be happy with repeating Ctrl+F, pressing Enter, an arrow key, anything that can reliably be done by feel while I'm focused on the highlighted text and not on the tiny '>' icon! 

Maybe this new CKEditor search would work for me?

**Comment by abitofevrything** [comment]
Open the balloon editor block (click on the paragraph symbol to the left of the line you are currently typing on), that is where the CKEditor search is. That only searches the current note.

**Comment by LorenAmelang** [comment]
@abitofevrything - Thank You! I'd never have found that...  I guess there are supposed to be tooltips on those icons, but I've never seen them and have no idea what most of them do. 

So you have to be editing a note to search it...  But at least once you have the search you can confidently move next/previous! Now if it would just center the found text, for maximum context, instead of keeping "next" at the very bottom lime of the window...  I suspect there is a way to configure that somewhere in CKEditor - any ideas where? 

Oh, and the white stripe above the search text in my black theme is odd:

![Black](https://user-images.githubusercontent.com/1297090/141360971-be35ff2b-e281-4458-a2cb-d0bd2ae3075d.png)

Apparently it somehow gets a different CSS background from everything else:

![Light](https://user-images.githubusercontent.com/1297090/141361135-1f0cbf00-78c5-41c8-979a-c805b7957a4c.png)

**Comment by cwilliams5** [comment]
> Oh, and the white stripe above the search text in my black theme is odd:
> 
> ![Black](https://user-images.githubusercontent.com/1297090/141360971-be35ff2b-e281-4458-a2cb-d0bd2ae3075d.png)
> 
> Apparently it somehow gets a different CSS background from everything else:
> 
> ![Light](https://user-images.githubusercontent.com/1297090/141361135-1f0cbf00-78c5-41c8-979a-c805b7957a4c.png)

Sigh, your right. Thanks for pointing out. Affecting my [dark theme](https://github.com/cwilliams5/Midnight-Trilium-Dark-Mode) as well. If I could develop a CSS selector I could override it but the box is disappearing on any attempt to use developer tools to inspect it. It's been a long time since I've done this type of thing I think I have to use a subtree modification break or otherwise capture the generated DOM or something, I'll tackle it another day. I'll drop the selector here if I find it.

**Comment by LorenAmelang** [comment]
Just checked through this again. The magnifier icon in the far left column of icons under the colorful (when it isn't showing an update...) Trilium menu now works:
![Trilium left icon search](https://user-images.githubusercontent.com/1297090/152864683-8cbe4342-681b-4f53-a209-a1a9d3aadfb7.PNG)
Searches all notes nicely! 

The CKEditor search
![2022-02-07](https://user-images.githubusercontent.com/1297090/152865737-914388e2-2007-4d6d-b97f-5252fdc8ffa9.jpg)
works nicely for searching within a note. But it hides a good portion of the note you are trying to search, and I can't find a way to move it...  

The original Ctrl+F search still works like this issue originally reported. If it loses focus, you can't get back to it. It seems like it is no longer receiving input, even though it is still visible. I'm way too often clicking the "previous" arrow, and it falls through to the "maximize window" icon hidden below the still visible search box!

**Comment by cwilliams5** [comment]
> > Oh, and the white stripe above the search text in my black theme is odd:
> > ![Black](https://user-images.githubusercontent.com/1297090/141360971-be35ff2b-e281-4458-a2cb-d0bd2ae3075d.png)
> > Apparently it somehow gets a different CSS background from everything else:
> > ![Light](https://user-images.githubusercontent.com/1297090/141361135-1f0cbf00-78c5-41c8-979a-c805b7957a4c.png)
> 
> Sigh, your right. Thanks for pointing out. Affecting my [dark theme](https://github.com/cwilliams5/Midnight-Trilium-Dark-Mode) as well. If I could develop a CSS selector I could override it but the box is disappearing on any attempt to use developer tools to inspect it. It's been a long time since I've done this type of thing I think I have to use a subtree modification break or otherwise capture the generated DOM or something, I'll tackle it another day. I'll drop the selector here if I find it.

OK I have OCD so couldn't let it go. This selector will let you fix the label in this pop up, here it is currently in my theme [Trilium Midnight](https://github.com/cwilliams5/Midnight-Trilium-Dark-Mode):

/* text label in find and replace dialog */
.ck-find-and-replace-form__find .ck-labeled-field-view .ck-labeled-field-view__input-wrapper label.ck-label {
    background-color: #033c53 !important;
    color: #dedede !important;  
}

Style it however you please:

![image](https://user-images.githubusercontent.com/10100743/152868863-677d5ca5-e73e-4c33-80d5-922b48b1b752.png)

**Comment by zadam** [comment]
@cwilliams5 thanks, fixed.

**Comment by antoniotejada** [comment]
This widget #2806 is a simple replacement for all the ctrl+f blues.

**Comment by zadam** [comment]
There's a new widget integrated into Trilium based on @antoniotejada's work.
