### ISSUE TITLE
Latest update broke themes

### ISSUE THREAD

**Issue by legion1978** [zadam/trilium#2256]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

v0.48.2

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Manjaro 21.1.6

### Expected Behavior

Custom themes are not being applied.

### Actual Behavior

Trilium reverts to default theme (dark or light)

### Additional Information

Maybe there is a new format or steps to get old themes working?

**Comment by zadam** [comment]
Hi, yes, custom themes need to be migrated as described in: https://github.com/zadam/trilium/wiki/Release-notes-v0.48#migrate-custom-themes

But the app UI changed so much that many (especially more advanced themes) will be broken anyway.
