### ISSUE TITLE
(Feature request) Search and move to

### ISSUE THREAD

**Issue by anno189** [zadam/trilium#2264]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

search and  "move to ..." action。

I usually collect articles in the journal node used Web Clipper and then process them. 
So I want to add a “move to ...” action in the search function。

Please evaluate the practicability, thank you.

Similar functions, search and replace, batch add internal links。

**Comment by sigaloid** [comment]
I would love this but for now you can use this: https://github.com/zadam/trilium/wiki/Web-clipper#functionality

Set a note with the `#clipperInbox` attribute and it will receive all clipped notes.

**Comment by zadam** [comment]
"Move to" search action was added in https://github.com/zadam/trilium/commit/91e3dd022a843e1e700d6c739be325d775087acb
