### ISSUE TITLE
(Feature request) Restore the navigational (previous/next in the history) buttons, or add an option

### ISSUE THREAD

**Issue by QuentinLeCaignec** [zadam/trilium#2267]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I am very happy with the 0.48.x UI changes, however I sorely miss the navigational buttons.

I navigate a very large note tree and I often need to go back and forth quickly when searching/reading information, but before I was able to do so very efficiently just with the mouse.

I'm aware of the shortcuts, but an option to restore those buttons or some other way of clicking back in the history would be very nice, and it would be useful to users using mostly the mouse when navigating. 

Considering the shortcut requires both my hands or (if using ALT GR) at least to move my right hand over (since the arrow keys are required), and navigation is typically down by clicking on notes/links with the mouse, navigating back and forth will require most Users to stop and switch between using the mouse and the keyboard with the right hand, which is not as convenient and much slower.

**Comment by SiriusXT** [comment]
`
api.addButtonToToolbar({
    title: 'Back',
    icon: 'left-arrow-circle',
    action: async () => {
       history.go(-1);
    }
});
api.addButtonToToolbar({
    title: 'Forward',
    icon: 'right-arrow-circle',
    action: async () => {
       history.go(1);
    }
});
`
#run=frontendStartup

**Comment by zadam** [comment]
Sidebar is configurable in the (not yet release) 0.58 and it will be possible to add back/forward buttons.
