### ISSUE TITLE
(Bug report) Trilium 0.48 stopped returning isDeleted in api.originEntity for attribute changes

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2268]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.3

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop!_OS 20.04

### Expected Behavior

I have this backend script linked to `~runOnAttributeChange` in my Trilium issue tracking system:

```js
const note = api.originEntity.getNote();

api.log(`origin entity ${api.originEntity} ${JSON.stringify(api.originEntity)}`);
api.log(`issue attribute changed ${note.noteId}, ${api.originEntity.name}, ${api.originEntity.value}`);

if (api.originEntity.name == "state" && !api.originEntity.isDeleted) {
    const stateNote = api.getNote(api.originEntity.value);
    api.log(`state in api.originEntity ${api.originEntity.value} ${stateNote.title}`);
    // If state sets an icon, set it on the issue.
    if (stateNote.hasLabel("issueIcon")) {
        note.setLabel("iconClass", stateNote.getLabel("issueIcon").value);
    }
}
```

When I change the `~state` of an issue, I want to update the issue's `~iconClass` to the state's `~issueIcon`.

This worked for me until I just tried upgrading to Trilium 0.48. At the same time, I also switched from local-only to server sync.

On each attribute change, IIRC, Trilium fires the script twice - once for the old attribute's value getting deleted, once for the new attribute getting added.

Expected behavior: when attribute changes, the script should be called twice:

1. once with `.isDeleted = true`, with `api.originEntity.value` pointing to the old value,
2. once with `.isDeleted` falsey, with `api.originEntity.value` pointing to the new value.

### Actual Behavior

These are my logs from Trilium 0.48, when changing state from "done" (with icon `mx-check`) to "open" (with icon `mx-bug`):

```
Script "issue attribute changed" (1wu3AHCG03pi): origin entity [object Object] {"attributeId":"JzrL3ZGMZLJI","noteId":"5EjMmafufn2l","type":"relation","name":"state","position":42,"value":"SittoKTBsvYX","isInheritable":false,"utcDateModified":"2021-10-24 20:12:55.593Z"}
Script "issue attribute changed" (1wu3AHCG03pi): issue attribute changed 5EjMmafufn2l, state, SittoKTBsvYX
Script "issue attribute changed" (1wu3AHCG03pi): state in api.originEntity SittoKTBsvYX Open
Script "issue attribute changed" (1wu3AHCG03pi): origin entity [object Object] {"attributeId":"z7yp5ANm9XM1","noteId":"5EjMmafufn2l","type":"label","name":"iconClass","position":43,"value":"bx bx-bug","isInheritable":false,"utcDateModified":"2021-10-24 20:12:55.594Z"}
Script "issue attribute changed" (1wu3AHCG03pi): issue attribute changed 5EjMmafufn2l, iconClass, bx bx-bug
Script "issue attribute changed" (1wu3AHCG03pi): origin entity [object Object] {"attributeId":"Ke0exfTaSuzz","noteId":"5EjMmafufn2l","type":"relation","name":"state","position":42,"value":"2CpyDq8DmG3E","isInheritable":false,"utcDateModified":"2021-10-24 20:12:50.913Z"}
Script "issue attribute changed" (1wu3AHCG03pi): issue attribute changed 5EjMmafufn2l, state, 2CpyDq8DmG3E
Script "issue attribute changed" (1wu3AHCG03pi): state in api.originEntity 2CpyDq8DmG3E Done
Script "issue attribute changed" (1wu3AHCG03pi): origin entity [object Object] {"attributeId":"z7yp5ANm9XM1","noteId":"5EjMmafufn2l","type":"label","name":"iconClass","position":43,"value":"bx bx-check","isInheritable":false,"utcDateModified":"2021-10-24 20:12:55.597Z"}
Script "issue attribute changed" (1wu3AHCG03pi): issue attribute changed 5EjMmafufn2l, iconClass, bx bx-check
```

As expected, I get 2 events - one with the new value, one with the old one. However, it looks like `api.originEntity.isDeleted` is no longer being set. So my script interprets both as the new value, and in effect the icon no longer gets updated.

Is this intended? If it is, how can a backend script distinguish between the old and new value of an attribute?

**Comment by zadam** [comment]
Hi, sorry for late response - there were a couple of user facing bugs which I wanted to solve first.

0.48 had quite a big refactoring of persistence/entity system and with that some conceptual changes as well. One of them is that deleted entities are not kept in the cache and thus in theory not accessible to scripts, thus not needing the `.isDeleted` since all accessible entities are not deleted. However these event hooks are the only exception where you have access to deleted entities and thus need to know their state.

I added a `.isDeleted` to Note, Branch and Attribute classes, hopefully this should unbreak the existing scripts.
