### ISSUE TITLE
Drag & drop from tree to text editor should create link

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#227]

**Comment by mbafford** [comment]
This would be a great feature. It took a few days of using Trilium to fully learn that this isn't possible. As an intuitive feature, I think it makes perfect sense.

**Comment by mbafford** [comment]
I just noticed this does work when dragging from the tree into a note with the type "Relation Map". So part of this functionality (dragging from the tree into a note) does look to be partially implemented. Of course the differences in an editable note and the relation map note may be so fundamental this is still a hard task.

**Comment by nil0x42** [comment]
I loved this ! Would be an awesome feature !

**Comment by wwwald** [comment]
I've been running into this regularly over the past months - don't know where I acquired the habit, but I keep on dragging tree notes into the editing pane, only to be disappointed :-)

Any progress on this?

**Comment by wwwald** [comment]
*BUMP* ;-)
Any update on this?

**Comment by zadam** [comment]
Added to the backlog. We could also ask user if they want to add a link or "include" the note.
