### ISSUE TITLE
v0.48 the note map missed links.

### ISSUE THREAD

**Issue by leeyaunlong** [zadam/trilium#2270]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

WIN10

### Expected Behavior

the note map missed links.

### Actual Behavior

- link map
in v4.7 or old , the link map include link out and link back links.
but in 4.8 link map has no link back links.

- org link
for org link, why just show children? we also want to know come from where ( maybe the node has many parents).

**Comment by jhgehrs** [comment]
> 
> 
> me too. And another question, in 0.48, I cant find "what links here" button, which used to show all the backlinks and very useful, can we have it back?

where can I stay tune about this issue?

**Comment by anno189** [comment]
> Hi, the back links are currently not shown in the map and that's something which needs to be changed.
> 
> What links here is missing as well. I need to find a way to put it somewhere in the UI.
> 
> Stay tuned.

me too。

The right side panel may be required。
or the left panel is divided into upper and lower parts.

**Comment by snipersteve** [comment]
> Hi, the back links are currently not shown in the map and that's something which needs to be changed.
> 
> What links here is missing as well. I need to find a way to put it somewhere in the UI.
> 
> Stay tuned.

what about showing the back link in the note after the content? like this
![image](https://user-images.githubusercontent.com/834498/141880838-1fae98b9-8242-4d08-80c9-c8b9685b70dd.png)
or this
![image](https://user-images.githubusercontent.com/834498/141880947-51fda606-bc0d-40bd-8f15-92689de8913c.png)
