### ISSUE TITLE
(Bug report) 0.48.3 deb is broken

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#2272]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Debian Testig x64

### Expected Behavior

Proper installation

### Actual Behavior

The .deb file does not install properly. This is the first time I getting with the provided .deb file. Please see the log

```
dpkg -i trilium_0.48.3_amd64.deb 
dpkg-deb: error: archive 'trilium_0.48.3_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive trilium_0.48.3_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 trilium_0.48.3_amd64.deb


```

**Comment by Zocker1999NET** [comment]
Or if someone like me really requires using the deb package, you can convert it manually for now (requires `binutils` (for `ar`) and `zstd` to be installed):
```bash
# configure version
export trilium_version=0.48.4
# jump into own directory
mkdir -p trilium-deb-fix
cd trilium-deb-fix
# download trilium
wget https://github.com/zadam/trilium/releases/download/v${trilium_version}/trilium_${trilium_version}_amd64.deb
ar x trilium_${trilium_version}_amd64.deb
# recompress
< control.tar.zst zstd -d | xz > control.tar.xz
< data.tar.zst zstd -d | xz > data.tar.xz
# create deb archive (I really do not know, what argument "sdsd" is for but something is required for ar to create the archive as desired)
ar -m -c -a sdsd trilium_${trilium_version}_amd64_xz.deb debian-binary control.tar.xz data.tar.xz
## uncomment if you want to install it directly afterwards
# sudo dpkg -i trilium_${trilium_version}_amd64_xz.deb
```

**Comment by zadam** [comment]
@Zocker1999NET thanks, I added your workaround to the build process as a temporary solution so 0.48.5 and later should be again compatible with debian.
