### ISSUE TITLE
(Bug report) The attribute editor cannot complete the attributes correctly for the first time after gaining the focus.

### ISSUE THREAD

**Issue by linger98** [zadam/trilium#2295]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 21H2

### Expected Behavior

Normal completion attributes

### Actual Behavior

![QApaYBFRPb](https://user-images.githubusercontent.com/73106094/139522774-aa0938e0-4b09-471d-b0f7-467cd02b0697.gif)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, fixed.
