### ISSUE TITLE
(Bug report)  --monospace-font-size css variable doesn't change font size in code editor

### ISSUE THREAD

**Issue by Lightirius** [zadam/trilium#2296]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11 Pro 21H2

### Expected Behavior

--monospace-font-size should apply to the font size of code notes

### Actual Behavior

--monospace-font-size doesn't apply to code notes

### Additional Information

I am not shure this is a bug or expected behaviour, but it doesn't look logical for me

Can be fixed in custom theme with this css:
```
body .CodeMirror {
    font-size: var(--monospace-font-size)
}
```

**Comment by zadam** [comment]
Hi, thanks for reporting this bug, fixed.
