### ISSUE TITLE
Revert back to Old UI

### ISSUE THREAD

**Issue by Aksheet10** [zadam/trilium#2297]
How do you revert back to the old UI? seems like once u open the new UI u cannot open the old trilium.exe :(

**Comment by zadam** [comment]
The new UI comes with v0.48 which also does some migration steps compared to the old one which are not forward compatible with 0.47 and older.

During this migration Trilium creates a backup of the old database in your `trilium-data/backup/backup-before-migration.db`. You can [restore this backup](https://github.com/zadam/trilium/wiki/Backup#restoring-backup) and continue using 0.47 if you wish.

**Comment by Aksheet10** [comment]
hey, there thanks for the reply, but sadly that didnt work.. i get the same ui even after that :(

**Comment by zadam** [comment]
If you get the same UI, that means you're still starting in 0.48. To get the old UI you need to use v0.47.X

**Comment by Aksheet10** [comment]
i deleted the .48 files and folder :p ... i tried to open the app using the .47.5 trilium.exe

**Comment by zadam** [comment]
If you see new UI then you're definitely still on 0.48. Older version don't contain the new UI at all.

**Comment by Aksheet10** [comment]
![image](https://user-images.githubusercontent.com/71016915/139619251-f004b56f-9856-4ab5-9ab9-f04e8bf0e3c6.png)

This is the trilum.exe i am opening.. 0.47 

Now when you click on it *trilium.exe*  it doesnt wanna open..i tried downloading another .47.x but still it didnt open

**Comment by abitofevrything** [comment]
You'll need to restore the backup before you try to open the older version, else the app will try and fail to load the newer DB.

**Comment by Aksheet10** [comment]
i copied the backup/backup-before-migration.db to trilum-data/database.db
and then loaded the file....i have the old files saved /stored i even tried
that but didnt work

**Comment by Aksheet10** [comment]
i copied the backup/backup-before-migration.db to trilum-data/database.db
and then loaded the file....i have the old files saved /stored i even tried
that but didnt work

**Comment by abitofevrything** [comment]
If this is resolved, maybe consider closing the issue to reduce the amount of open issues we have to consider.
