### ISSUE TITLE
(Bug report) maxContentWidth is not defined after upgrading to v0.48.5

### ISSUE THREAD

**Issue by shotcollin** [zadam/trilium#2300]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

v0.48.5

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu Server 16.04

### Expected Behavior

Install newest version (which I did by copying the files contained in `trilium-linux-x64-server-0.48.5.tar.xz` to the existing installation directory, though not sure that's a supported method). Access the UI remotely as usual and enjoy the new features.

### Actual Behavior

After installation of new version, all pages other than login page return
```{"message":"/opt/trilium/src/views/desktop.ejs:63\n    61| <style>\n    62|     .note-split {\n >> 63|         max-width: <%= maxContentWidth %>px;\n    64|     }\n    65| </style>\n    66| \n\nmaxContentWidth is not defined"}```.

I assume this is obviously related to the new "max content width" feature, but I didn't find anything in release notes, etc., indicating how to go about defining that value for content that was created before the feature was implemented.

**Comment by zadam** [comment]
Hi, did you stop the process before copying the files and starting it again after?

**Comment by shotcollin** [comment]
Yes...at least, I stopped the service that runs the process, but now that I think about it I'm not sure that actually stopped the process itself. I'll try again and confirm.

**Comment by shotcollin** [comment]
Hi, that was it. I'd forgotten that I'd set up a service to run the process and didn't think to check on the underlying process after stopping the service.  Seems like I haven't updated in quite a while...all the new stuff looks great. Thanks!
