### ISSUE TITLE
Cannot login after server installation

### ISSUE THREAD

**Issue by javisomoza** [zadam/trilium#2302]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Debian 10

### Expected Behavior

After installation I expected a first time setup to establish credentials or having default credentials to be able to login.
But it only shows a login form and i dont have any credentials

### Actual Behavior

After installation it only shows a login form and i don't have any credentials

### Additional Information

I installed this way:

wget https://github.com/zadam/trilium/releases/download/v0.48.5/trilium-linux-x64-server-0.48.5.tar.xz
xz -d trilium-linux-x64-server-0.48.5.tar.xz
tar xf trilium-linux-x64-server-0.48.5.tar
cd trilium-linux-x64-server/
./trilium.sh

I have checked this issue (https://github.com/zadam/trilium/issues/2241) but it does not solve my problem.

**Comment by anno189** [comment]
Are there other versions ？

**Comment by javisomoza** [comment]
Solved after removing trilium-data folder to regenerate db
