### ISSUE TITLE
(Feature request) Bash Highlights

### ISSUE THREAD

**Issue by dawidmachon** [zadam/trilium#2304]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Hi, there is option to add more code blocks language highlights? Bash/Unix or Json ?

It is possible on my own or by PR, or it is totally dependent on Ck Editor.

**Comment by dawidmachon** [comment]
My bad, sorry. Duplicated and also I found already in options. 

But in general - it is possible to add more by my own or by PR?

**Comment by zadam** [comment]
Adding support for new languages is not supported.

Closing since the original problem was solved.

**Comment by BoKKeR** [comment]
Where is the Bash code block option? I cant find it
