### ISSUE TITLE
(Bug report) Creating day note via Calendar with YYYY-MM-DD format creates note with wrong title

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2306]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop!_OS 20.04

### Expected Behavior

1. Set journal's `#datePattern="{isoDate} - {weekDay}"`
1. Use Calendar, navigate and click on March 09. No note exists for that day yet.
1. Expected: jump to new note titled `2021-03-09 - Wednesday`, with attribute `#dateNote=2022-03-09`

### Actual Behavior

The title of the newly created note is wrong - instead of referring to the clicked date in calendar, its title corresponds to *today*'s date. The attribute is correct, though:
![image](https://user-images.githubusercontent.com/714892/140305005-f4138a8c-c4a0-4e8b-aca2-a4c10b9c53cf.png)

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
