### ISSUE TITLE
(Bug report) Error: Option "username" doesn't exist

### ISSUE THREAD

**Issue by ttlequals0** [zadam/trilium#2311]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

macOS 12.0.1

### Expected Behavior

Log in and see my notes. This fails using WebUI and macOS desktop app.

### Actual Behavior

Unable to log in and I receive this error.
`Error: Option "username" doesn't exist`

### Additional Information

Nov 05 14:36:00 ip-172-31-16-231 docker[696]: Error: Option "username" doesn't exist
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at Object.getOption (/usr/src/app/src/services/options.js:7:15)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at checkCredentials (/usr/src/app/src/services/auth.js:86:38)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
Nov 05 14:36:00 ip-172-31-16-231 docker[696]:     at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)

**Comment by zadam** [comment]
Hi, can you explain what exactly are you doing?

Based on the stacktrace it seems that you're trying to setup sync against a new server instance which hasn't been set up yet.

**Comment by ttlequals0** [comment]
You are correct, I have found the issue. turns out i ran out of disk space on server.
