### ISSUE TITLE
(Bug report) Javascript error on sync

### ISSUE THREAD

**Issue by ttlequals0** [zadam/trilium#2314]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

macOS

### What is your setup?

Server access only

### Operating System Version

MacOS 12.0.1

### Expected Behavior

I am trying to do the initial sync from the server on the newly installed desktop client.

### Actual Behavior

When trying to do the initial sync on a desktop client a javascript error gets thrown during the sync

A JavaScript error occurred in the main process
Uncaught Exception:
Error: net::ERR_CONTENT_LENGTH_MISMATCH
at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
at SimpleURLLoaderWrapper.emit (events.js:315:20)
at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)

**Comment by anno189** [comment]
Maybe it's a network problem。
Maybe there are missing attachments or wrong attachment paths on your server。
In earlier versions, there may be attachment path errors, resulting in what you said。

you can installed server， i think you can find this error message in the log file at the server。

**Comment by ttlequals0** [comment]
This is working now, I think you were correct about it being network-related.
