### ISSUE TITLE
(Bug report) delete notes, sync error

### ISSUE THREAD

**Issue by anno189** [zadam/trilium#2316]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS Big Sur， Ubuntu 18.04

### Expected Behavior

if choose "erase nots permanently" options, the operation can't sync to another。 
<img width="861" alt="截屏2021-11-09 下午8 07 21" src="https://user-images.githubusercontent.com/3339262/140922080-28b26d70-ca1f-4be2-a807-375ffa5bad28.png">

### Actual Behavior

the operation sync to another。

**Comment by zadam** [comment]
Hi, can you post some logs? Why do you believe it doesn't sync?

**Comment by anno189** [comment]
delete notes using "erase nots permanently" options on the server。

08:46:03.835 Slow 200 POST /api/delete-notes-preview with 60 bytes took 11ms
08:46:06.021 200 POST /api/delete-notes-preview with 60 bytes took 3ms
08:46:08.482 Sending message to all clients: {"type":"taskProgressCount","taskId":"qIkxwoHvvN","taskType":"delete-notes","progressCount":0}
08:46:08.484 Deleting note eeEjxdZmtn3r
08:46:08.508 Erased notes: ["eeEjxdZmtn3r"]
08:46:08.511 Sending message to all clients: {"type":"taskSucceeded","taskId":"qIkxwoHvvN","taskType":"delete-notes"}
08:46:08.522 Slow 204 DELETE /api/notes/eeEjxdZmtn3r?taskId=qIkxwoHvvN&eraseNotes=true&last=true with 0 bytes took 40ms
08:46:08.584 JS Info: Frontend app reload: notes eeEjxdZmtn3r is erased, need to do complete reload.
08:46:08.587 JS Info: Frontend app reload: branches LSZZycvz5F4D is erased, need to do complete reload.
08:46:08.625 JS Info: Frontend app reload: erasing notes requires reload
08:46:08.631 GET /api/notes/eeEjxdZmtn3r returned 404 with response "Note eeEjxdZmtn3r has not been found."
08:46:08.631 404 GET /api/notes/eeEjxdZmtn3r with 37 bytes took 1ms
08:46:08.635 Generated CSRF token xtk0aYM2-y0-JxkgTpwHktHk2I2a7dzgG89A with secret undefined
08:46:08.657 Generated CSRF token UgY5Tf8s-rz9oys4Q3N7fYg3FtRAah9fjg8U with secret undefined
08:46:08.735 JS Error: Error when calling GET notes/eeEjxdZmtn3r: error - Not Found
Stack: Error
    at Object.logError (http://XXXX/app/services/ws.js:23:20)
    at Object.throwError (http://XXXX/app/services/toast.js:87:8)
    at reportError (http://XXXX/app/services/server.js:106:18)
    at async Object.error (http://XXXX/app/services/server.js:131:17)
08:46:10.750 304 GET /api/setup/status with 59 bytes took 1ms
08:46:10.825 200 POST /api/login/sync with 53 bytes took 1ms
08:46:10.924 Returning 2 entity changes in 0ms
08:46:10.925 200 GET /api/sync/changed?lastEntityChangeId=43970 with 434 bytes took 1ms
08:46:10.929 304 GET /api/options with 5379 bytes took 1ms
08:46:10.932 200 GET /api/tree with 14475 bytes took 1ms
08:46:10.942 304 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 0ms

**Comment by anno189** [comment]
local log。 

i try ”sync server“ button。


08:45:11.050 Content hash computation took 59ms
08:45:11.050 Content hash checks PASSED
08:45:11.051 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":43970}
08:45:24.408 304 GET /api/clipper/handshake with 45 bytes took 0ms
08:46:10.721 Nothing to push
08:46:10.819 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":43970}
08:46:10.833 Pulled 2 changes in 0 KB, starting at entityChangeId=43970 in 98ms and applied them in 14ms, 0 outstanding pulls
08:46:10.862 JS Info: Frontend app reload: notes eeEjxdZmtn3r is erased, need to do complete reload.
08:46:10.926 JS Info: Frontend app reload: branches LSZZycvz5F4D is erased, need to do complete reload.
08:46:10.929 Finished pull
08:46:10.989 204 PUT /api/branches/wyPuvHHumc8U/expanded/1 with 0 bytes took 2ms
08:46:10.991 204 PUT /api/branches/dA3m2qWVbk0B/expanded/1 with 0 bytes took 0ms
08:46:11.013 Generated CSRF token hVwEmt88-ex5o49uS_bxXTPlJzINmfkOi0ac with secret undefined
08:46:11.054 Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":43970}
08:46:11.054 Pushing 2 sync changes in 125ms
08:46:11.055 Nothing to push
08:46:11.329 Slow query took 57ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
08:46:11.352 Content hash computation took 80ms
08:46:11.352 Content hash checks PASSED
08:46:11.352 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":43973}
08:46:12.078 200 GET /api/options with 5570 bytes took 0ms
08:46:12.083 200 GET /api/tree with 23679 bytes took 2ms
08:46:12.088 200 GET /api/keyboard-actions with 11948 bytes took 4ms
08:46:12.089 200 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 1ms
08:46:12.090 200 GET /api/script/widgets with 2 bytes took 1ms
08:46:12.365 200 POST /api/tree/load with 2460 bytes took 0ms
08:46:12.369 200 GET /api/search/%23bookmarked%20or%20%23bookmarkFolder with 31 bytes took 1ms
08:46:12.473 200 POST /api/tree/load with 8088 bytes took 1ms
08:46:13.179 200 GET /api/notes/3RZdU4mYNNwq with 3313 bytes took 0ms
08:46:15.144 200 GET /api/script/startup with 861 bytes took 2ms
08:46:15.146 200 POST /api/tree/load with 6513 bytes took 0ms
08:46:24.418 304 GET /api/clipper/handshake with 45 bytes took 1ms
08:47:16.268 204 PUT /api/branches/wyPuvHHumc8U/expanded/0 with 0 bytes took 8ms
08:47:21.962 Received request to trigger sync now.
08:47:21.963 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":43973}
08:47:24.437 304 GET /api/clipper/handshake with 45 bytes took 2ms
08:47:26.750 Nothing to push
08:47:26.835 Finished pull
08:47:26.835 Nothing to push
08:47:27.189 Slow query took 73ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
08:47:27.269 Content hash computation took 153ms
08:47:27.269 Content hash checks PASSED
08:47:27.269 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":43973}
08:47:27.432 Nothing to push
08:47:27.516 Finished pull
08:47:27.516 Nothing to push
08:47:27.805 Slow query took 40ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
08:47:27.829 Content hash computation took 64ms
08:47:27.829 Content hash checks PASSED
08:47:27.829 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":43973}
08:47:27.831 Slow 200 POST /api/sync/now with 16 bytes took 5869ms
08:48:10.803 Nothing to push
08:48:10.884 Finished pull
08:48:10.884 Nothing to push
08:48:11.133 Slow query took 30ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
08:48:11.158 Content hash computation took 56ms
08:48:11.159 Content hash checks PASSED
08:48:11.159 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":43973}
08:48:24.428 304 GET /api/clipper/handshake with 45 bytes took 2ms
08:49:10.806 Nothing to push
08:49:10.889 Finished pull
08:49:10.889 Nothing to push

**Comment by anno189** [comment]
SQL Console， note id = "eeEjxdZmtn3
<img width="910" alt="截屏2021-11-10 上午8 55 15" src="https://user-images.githubusercontent.com/3339262/141029948-ee3db82d-d117-4a28-9cfa-d1db6330de6b.png">
r"

**Comment by anno189** [comment]
I tried many times, and reset the system and import the records.
I think this problem can be reproduced.

**Comment by anno189** [comment]
Server 
<img width="1007" alt="截屏2021-11-10 上午9 51 02" src="https://user-images.githubusercontent.com/3339262/141034965-29f3da95-5b36-4b73-be5d-01ce58feffe4.png">

**Comment by zadam** [comment]
Hi, thanks for the info. I can reproduce the problem and see where it probably comes from. I will try to fix this ASAP.
