### ISSUE TITLE
(Feature request) Add a "Update available" box

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#2319]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I would like to be alerted whenever there's a new version available.

### Additional Information

We could use a simple `alert` in the web version, send a notification in the electron version and it any of them fails show a dialog box (that gray box at the top) otherwise.

I can implement this feature if you'd like :)

**Comment by zadam** [comment]
Having some kind of indication of new version would be nice, but IMHO not in the form of pestering notifications. Something like chrome has with only icon change ...

**Comment by Myzel394** [comment]
What about this?

![image](https://user-images.githubusercontent.com/50424412/141152842-53645dbb-eb20-4cb1-b0cc-e87a0c6767fe.png)

**Comment by Myzel394** [comment]
But I would still show a notification for the electron version or in the mobile view

**Comment by zadam** [comment]
I was thinking something like this - non intrusive:

![image](https://user-images.githubusercontent.com/617641/141190288-bb4a862d-01a4-4b04-93d0-5a1caa31b55c.png)

But you can submit also your variant, that's OK for a start.

Notifications I would avoid, no need to push/force such information on users who often don't care about updates.

**Comment by Myzel394** [comment]
That's a good idea. How about we change the color of the sync icon depending whether it's a minor/major release?

Something like:
Minor release: gray
Semi-major release: green (like in Chrome)
Major release: red


And I would also pledge for an option to disable this icon for minor releases

**Comment by Nriver** [comment]
If you are going to make this, please make the update check and notification icon/message optional, I am the one of those who do not like update notifications.

**Comment by Myzel394** [comment]
What do you think about this?

minor
![image](https://user-images.githubusercontent.com/50424412/141322387-9b265935-60fc-4a6d-b06a-ff10777f1408.png)

semi-major
![image](https://user-images.githubusercontent.com/50424412/141322452-7a5144ce-bbc8-4ae8-91b3-c33f5498a0a2.png)

major
![image](https://user-images.githubusercontent.com/50424412/141322503-7f9ba94e-5331-4050-8edf-8a260e82a167.png)

**Comment by Myzel394** [comment]
Btw @zadam maybe you could tell me how to add default options for `options`? I'm currently adding the options but don't know how to assign default values to them (link to new options: https://github.com/Myzel394/trilium/blob/add-update-available/src/public/app/dialogs/options/appearance.js#L284-L304)
