### ISSUE TITLE
(Feature request) Add a "Shape Toolbox"

### ISSUE THREAD

**Issue by ViKi-R** [zadam/trilium#2320]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I've been using Trilium for a few days now, and it's fantastic. I'm also using OneNote, and I'd like to have a shapes toolbox like in OneNote, which would be really useful for taking notes (Like flowchart, arrows, circles etc..). For example, in the image, the arrows utilised for classification.

![Screenshot (11)](https://user-images.githubusercontent.com/73846668/140974523-2a63f591-ceb5-4fbf-babe-93ac6fd051df.png)

### Additional Information

Thanks to @zadam and others for providing us with this beautiful, awesome, fantastic tool for taking notes, particularly for technologists. This tool is highly recommended even for day-to-day tasks. I'm delighted I found these resources, and I appreciate the work of those who created it.

**Comment by abitofevrything** [comment]
If you want to make flowcharts, check out the mermaid diagram note type.
