### ISSUE TITLE
(Bug report) Can't change TRILIUM_DATA_DIR with the OneDrive directory location

### ISSUE THREAD

**Issue by skitou** [zadam/trilium#2327]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

v0.48.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11 / Windows 10

### Expected Behavior

I got a computer for my studies in highschool/college, the computer is set up in organisation mode with a OneDrive storage for each student with 1TB.

I tried using the portable version of Trillium by modifying the TRILIUM_DATA_DIR variable in the .bat file:
```
SET DIR=%~dp0
SET TRILIUM_DATA_DIR=D:\Users\gally\OneDrive\OneDrive - Conseil Régional des Pays de La Loire - Direction des Lycées\Lycee\trilium-data
cd %DIR%
start trilium.exe
```

### Actual Behavior

When launching the .bat I got that error message:
![image](https://user-images.githubusercontent.com/38993289/141333246-0d3ef185-b825-4c93-beab-242526eff845.png)

### Additional Information

- I have already done that with Google Drive and got no error, Trillium launched like a charm.
- The computer is offered by the regional academic of my country -> I have no administration permissions on it and I can't change the OneDrive directory name.
- The computer I use at home is on Windows 11 and the other computer is on Windows 10.

**Comment by zadam** [comment]
Might be some problem with spaces and/or accents. Not sure.

It's not recommended to sync the database file with tools like OneDrive or Google Drive - they are known to corrupt the DB file. See e.g. #995 or #913.

**Comment by abitofevrything** [comment]
Note that all of the folders in the path must already exist (excluding `trilium-data` which is auto-generated). So the folder `D:\Users\gally\...\Lycee` must already exist.

Did you make a typo? I'm surprised the last `Lycee` is spelt without an accent (`Lycée`)

**Comment by skitou** [comment]
> Note that all of the folders in the path must already exist (excluding `trilium-data` which is auto-generated). So the folder `D:\Users\gally\...\Lycee` must already exist.

All the folders already exists.

> Did you make a typo? I'm surprised the last `Lycee` is spelt without an accent (`Lycée`)

I named it without the accent to avoir any problems with the path.

**Comment by skitou** [comment]
> Might be some problem with spaces and/or accents. Not sure.

I think it is a problem with path with accents.

I will test later to see if this is the probleme.

> It's not recommended to sync the database file with tools like OneDrive or Google Drive - they are known to corrupt the DB file. See e.g. #995 or #913.

I know, but I can't buy a vps for the moment and this is the most convenient way for me.

**Comment by U-Bren** [comment]
**I've managed to make this work (tested on win10 20H2 )using PowerShell:**
```powershell
Set-Item -Path Env:TRILIUM_DATA_DIR -Value (Get-Item -Path './éèà')
./trilium.exe
```
I will find a way to pass args to trilium and make a PR to add those scripts in replacement of the .bat ones.

Please note that this dosen't work (same bug as with the .bat):
```powershell
$Env:TRILIUM_DATA_DIR = './éèà'
./trilium.exe
```


One could probably also use a symlink and put it in a path that have only ASCII, but it unfortunately requires Administrator permission (or ``SeCreateSymbolicLink``), which doesn't fit the described issue.

I agree with @xyqyear, using syncthing might be the next best thing to having a server instance, though the fact that (to my knowledge) trilium can't merge two documents which have diverged is a huge issue for that use case.
(Perhaps out of topic for this issue, but) would it be feasible to add an (command-line) option to merge two documents (with the same origin), like for example keepass can do?

**Comment by U-Bren** [comment]
I have reproduced the ENOENT error described by @skitou using the following .bat.
```batch
SET DIR=%~dp0
SET TRILIUM_DATA_DIR=%DIR%\OneDrive - Conseil Régional des Pays de La Loire - Direction des Lycées\trilium
cd %DIR%
start trilium.exe
```

Using Powershell  to set the TRILIUM_DATA_DIR env variable instead makes trilium work as expected:
```powershell
Set-Item -Path Env:TRILIUM_DATA_DIR -Value (Get-Item -Path './OneDrive - Conseil Régional des Pays de La Loire - Direction des Lycées\trilium')
Set-Location (Split-Path -Parent $MyInvocation.MyCommand.Path)
./trilium.exe
```

However this is apparently only the first issue. I sent the above script to @skitou for testing, and while it fixed the crash (ENOENT), they still cannot find the folder that is supposed to be created at the specified path.
