### ISSUE TITLE
(Feature request) can you add modify notes function in backend API

### ISSUE THREAD

**Issue by anno189** [zadam/trilium#2331]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I wrote some functions with the "custom request handler", because some requirements need to update the existing notes. Can you add a function to modify note in the backend API?

Now I use SQL to update, which affects the sync.

thank you。

**Comment by zadam** [comment]
I guess you already figured it out, but for future reference updating a note is done with `.save()` method call:

```javascript
const note = api.getNote('root'); // or however you get the Note instance
note.title = "new changed note title"; 
note.save();
```

**Comment by ventureg** [comment]
Hi, @zadam 

I am trying to create the note with title only first, then update the content of the node.

I don't know much about javascript, could you please show us how to update the content through backend API ?

Thanks.

**Comment by zadam** [comment]
```javascript
note.setContent("bla bla");
```
