### ISSUE TITLE
(Feature request) Change browser tab title

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#2333]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Please change the window tab title format to "[Note Title] - Trilium Notes"

### Additional Information

Currently we have the format "Trilium Notes - [Note Title]". However, most websites use their names as a suffix instead as a prefix. This is useful because some people have many tabs open and if you only see a part of the title, you always just see "Trilium No". If we change the format, this issue would be solved :D

**Comment by zadam** [comment]
I actually think this used to be that way at certain point in time but was changed later to current format. But I can't recall what was the reason for this change.

**Comment by sigaloid** [comment]
#1551

**Comment by Myzel394** [comment]
duplicate, closing it
