### ISSUE TITLE
(Feature request) Flatpak

### ISSUE THREAD

**Issue by jergao** [zadam/trilium#2335]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Have a flatpak to support most Linux distros concurrently.

**Comment by zadam** [comment]
Help for this issue would be appreciated!

**Comment by pssandhu** [comment]
I've managed to make a working flatpak based on the [documentation](https://docs.flatpak.org/en/latest/). Just a couple things left:
- Include a .desktop file and a metadata file in the trilium repo (I can open a PR)
- [Submit to flathub](https://github.com/flathub/flathub/wiki/App-Submission). I can do this but I may need some help if the reviewers have some questions as I'm not familiar with trilium's code

Note: This is the first time I've made a flatpak and I'm not very familiar with building electron apps but it seems to work

**Comment by zadam** [comment]
Hi, do you have scripts (or whatever is needed) to build flatpak in some github repo?

**Comment by pssandhu** [comment]
You can find all the [files here](https://github.com/pssandhu/flathub/tree/com.github.zadam.trilium). The build commands are in the yml file. They are adapted from the trilium build scripts. Please take a look and see if anything is missing or unnecessary.

It's also worth looking at the metainfo and .desktop as they're what users will see on flathub and in software managers.

**Comment by sigaloid** [comment]
Hi, awesome work! I'm not sure if you are offering to maintain the Flathub releases in the future but I would be willing to do it for each release if not (and if it's a lot for @zadam to do on each release). I already have to keep an eye out for new releases so it wouldn't be much of a burden :p 

In any case, glad to see this! Finally can use this on Fedora without converting the .deb file. :D

**Comment by pssandhu** [comment]
Thanks for the offer. I assumed that if no one else was going to maintain it that I would do it. I don't mind if someone else wants to or we could do it together. An extra pair of hands is always good.

Updating the flathub release shouldn't be too much work (although I appreciate that it's still _extra_ work on top of the current releases). Basically just have to update those files I linked to. I think the exact steps will be more clear once we have the first version on there.

**Comment by sigaloid** [comment]
That works as well! I'm fine with whichever. I can also test the flatpak before an update is pushed if necessary. It's going to be my daily driver from now on as there is no package currently available on Fedora, so it wouldnt be a hassle to me. You did of course make the Flatpak build files so let me know what you decide. :)

**Comment by zadam** [comment]
Just FYI I plan to take a look at this in the near future and if this can be fully automated, flatpak could be a part of the standard release process.

**Comment by sigaloid** [comment]
Any updates?

**Comment by zadam** [comment]
No, I got stuck. Flatpak was crashing on me and I didn't get beyond that point.

**Comment by sigaloid** [comment]
I successfully got it working, is there a particular error message it printed or was it just crashing outright? Once you install `org.freedesktop.Sdk.Extension.node16`, `org.electronjs.Electron2.BaseApp`, and `org.freedesktop.Platform`, it should be as easy as the four files in @pssandhu 's repo. Here's what I had to do:

1. Run `flatpak-node-generator npm package-lock.json` from https://github.com/flatpak/flatpak-builder-tools/tree/master/node
2. Copy the generated-sources.json into the flathub directory, replacing the existing one
3. Update `com.github.zadam.trilium.yml` in the Sources section to update the tag and the commit
4. Run `flatpak-builder build-dir com.github.zadam.trilium.yml --force-clean`
5. Run `flatpak-builder --user --install --force-clean build-dir com.github.zadam.trilium.yml` 
6. Start it with `flatpak run com.github.zadam.trilium` and ensure it's working

However, the flathub service takes care of building it. All you really need to do on each release is steps 1-3 and push to a repo.

If you're okay with it, I can submit the app on your behalf

**Comment by zadam** [comment]
TBH, I don't remember the details.

But now, I followed your guide and got it working on the first try. Not sure what's different. I will give it a second try then, thanks!

**Comment by sigaloid** [comment]
Awesome, can't wait to see it! No more [Fedora/alien](https://help.ubuntu.com/community/RPM/AlienHowto) problems :smile:

**Comment by zadam** [comment]
FYI, flathub PR has been sumitted here: https://github.com/flathub/flathub/pull/3353

**Comment by pssandhu** [comment]
Good work everyone, I'm glad this was able to be finished. I'll be moving over to the flatpak version as well.

**Comment by Myzel394** [comment]
Will FlatHub also contain future versions of Trilium Notes or only v0.57.5?

**Comment by zadam** [comment]
The releases are [getting published](https://github.com/flathub/com.github.zadam.trilium/commits/master) to repo, but it's not getting through to the website. This happened before and the problem was on the flatpack infra side which got resolved eventually.
