### ISSUE TITLE
(Feature request) Embed mermaid diagram in existing note

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2339]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I think it would be cool to be able to link an existing mermaid note into within another note so I can see it (instead of a regular link). 

### Additional Information

It sort of exists, as hovering over a linked mermaid note shows a preview of the HTML.

**Comment by zadam** [comment]
Use "include note" functionality in the ckeditor toolbar:

![image](https://user-images.githubusercontent.com/617641/141843564-c447afb7-a664-4660-ab97-7db0dbb7f4ba.png)


![image](https://user-images.githubusercontent.com/617641/141843508-c3a1e6cf-c99d-410f-b162-ffe9ad22ffa8.png)

**Comment by sigaloid** [comment]
:0 every day I learn something new about this software. Thanks!!
