### ISSUE TITLE
How to customize editor CSS

### ISSUE THREAD

**Issue by olunju** [zadam/trilium#2341]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I want to customize the style of the text in the editor, but I can't find the place.

Does Trilium support custom CSS? If not, could you please tell me which CSS files I should modify? Thank you

**Comment by olunju** [comment]
I found the corresponding file

**Comment by zadam** [comment]
Some docs is here: https://github.com/zadam/trilium/wiki/Themes
