### ISSUE TITLE
(Feature request) Make shortcuts optional

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#2342]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Make shortcuts completely optional.

### Additional Information

I'm that kind of person who doesn't use any shortcuts at all. With my internatianal keyboard enabled, I can't type some characters (reference: https://www.starr.net/is/type/imgt/IEKeyboard.GIF) because they are reversed for shortcuts. If we could make this feature optional, we can type them again

**Comment by zadam** [comment]
Which shortcuts do you have in mind? Most can be turned off in the Options dialog, but some are hardcoded in e.g. CKEditor.

**Comment by Myzel394** [comment]
I mean generally all shortcuts for Trilium Notes. I know that I can manually remove each one, but I don't want to remove them generally. I want to disable them on my laptop because it doesn't have the right keyboard layout, but my main computer should have them still enabled.

**Comment by zadam** [comment]
Keyboard shortcuts are not synchronized so you can remove them on laptop and keep on the main computer.
