### ISSUE TITLE
(Feature request) Attribute to keep note on the top by sorting

### ISSUE THREAD

**Issue by ivosm** [zadam/trilium#2343]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

In case a note has many children, then sorting them alphabetically (manually or through 'sorted' attribute) is mostly better approach then editing their position manually. But there are often 1 or few notes, which we like to keep on the top. 
I hope, adding some attribute used with highest priority by sorting would be easy and helpful solution. This attribute could be e.g. as easy as 'top' and work similarly to generally used stars or could be integer for techies.

**Comment by agentydragon** [comment]
I'd suggest an option to sort children by, say, "1. arbitrary user-selected attribute, 2. name".

(i.e.: 1. add option to sort by custom user attribute, 2. add option to specify how to break ties)

**Comment by Myzel394** [comment]
I would suggest showing first a simple form, with the ability to access advanced settings to make Trilium Notes easier for non tech-savvy people.

> 1. add option to sort by custom user attribute, 2. add option to specify how to break ties

Could you explain this further and give an example @agentydragon ?

**Comment by agentydragon** [comment]
Let's say you wanna have note Foobar first, then note Barfoo, then all remaining notes in alphabetical order. Then you'd set:

* Foobar page: custom attribute, say `#mySortOrder=1`
* Barfoo: `#mySortOrder=2`
* All other subpages: no change

And the sort order for the containing page would be: "sort my `#mySortOrder`, then alphabetically". Because the other subpages would have `#mySortOrder` not set, that would count as a tie, and they'd be sorted alphabetically.

This is better than just adding the option to "keep this note on top", because if you just add a "keep this note on top" checkbox, that leaves the question of "what happens if multiple notes are set to stay on top" open.

**Comment by ivosm** [comment]
> This is better than just adding the option to "keep this note on top", because if you just add a "keep this note on top" checkbox, that leaves the question of "what happens if multiple notes are set to stay on top" open.

It is not completely true. The only difference is, that technically, in my "easy" variant, which thinks more on non-techie users, the attribute is boolean and in your case the attribute is integer. Sorting is then set as 2 level. First according attribute and second is the user  choice, e.g. alphabetically, date or whatsoever. 
Q.: And what happen in your case of 2 notes with same value of `#mySortOrder`? I guess, you will not display error message but use the chosen sorting inside. ;-)
What I really love on trillium is, that it could be used by my mom as well as by me. It's very conceptional and I would try to keep it.

**Comment by zadam** [comment]
See https://github.com/zadam/trilium/wiki/Sorting which should cover both cases.

There's a `top` label which is an implicit highest priority sorting label. It can be either empty (meaning "" value which coincidentally sorts before any other string) or whatever value.

Then it's possible to define a custom sorting label by giving a `sorted` attr a value with the name of a label which should be used for sorting.

Suggestions are welcome.

**Comment by agentydragon** [comment]
In that case looks to me like this can just be closed since the `top` label function already exists.

**Comment by ivosm** [comment]
I think, it could not be better. (acc docs - I'll check it in 0.49 when it comes)

**Comment by cwilliams5** [comment]
I wanted the same and found this issue and: https://github.com/zadam/trilium/wiki/Sorting

Works great for me. Can't this issue be closed in light of this? Or is there something else not covered?

**Comment by zadam** [comment]
Yep, those improvements came from this ticket and thus can be closed.
