### ISSUE TITLE
Release docker image for 0.48.6

### ISSUE THREAD

**Issue by wreiner** [zadam/trilium#2344]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I just wanted to update to 0.48.6 with my Ansible role but the new version is not yet available on Docker hub. Would it be possible to release the new version as an official Docker image? Thank you!

**Comment by Myzel394** [comment]
@zadam I think it would be useful if this is done automatically (probably using ci:cd)

**Comment by zadam** [comment]
It's done automatically from Github Actions, but it broke because of (probably removed) dependency. 

Pushed now with special tag: 0.48.6-docker

**Comment by wreiner** [comment]
Thank you, it worked for me.
