### ISSUE TITLE
(Bug report) Cannot export root note ("Cannot export branch root since it does not exist")

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2346]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.6

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

xubuntu

### Expected Behavior

I should be able to export the root note. 

### Actual Behavior

When choosing export zip on any other note, the filename in the export dialog is a .zip, but on the root note, it's an HTML file. And even if I export the root note as a HTML file, it doesn't actually create the file.

Export file dialog on root note:
![image](https://user-images.githubusercontent.com/69441971/141819191-edac595f-8a0f-43d8-bc0b-07016d75fc25.png)

Export file dialog on any other note:
![image](https://user-images.githubusercontent.com/69441971/141819291-f847baab-c690-4e64-bd47-659afbff3ccb.png)

It never saves the file if I export the root note 

As well, the web version says this: "Cannot export branch root since it does not exist."

**Comment by zadam** [comment]
Fixed, thanks for reporting!

**Comment by decentropy** [comment]
I don't think this is fixed?

I am on 0.58.2-beta ... and when I try to export root, it gives error page "Cannot export branch root since it does not exist."

**Comment by decentropy** [comment]
> Fixed, thanks for reporting!

@zadam I don't think this is fixed?

I am on 0.58.2-beta ... and when I try to export root, it gives error page "Cannot export branch root since it does not exist."

**Comment by sigaloid** [comment]
That issue might also be caused by a corrupted database, have you tried running the various database fixes in settings ->  advanced? 
![image](https://user-images.githubusercontent.com/69441971/210420657-ab7233d0-d718-4871-82fa-625e5273f66d.png)

**Comment by decentropy** [comment]
I just ran 'check' and 'find & fix'... it said no issues found, and still gives same error.
I then also tried 'vacuum', then 'fix'... still same error.

**Comment by zadam** [comment]
@decentropy it's a bug in the 0.58 betas, fixed now. Thanks for reporting!

**Comment by decentropy** [comment]
Thanks @zadam .. Trilium is awesome.

A question (perhaps unrelated), but is there way to have the export respect sorting/order of the notes?
I notice that exporting is not alphabetical, but also not in my custom sorted order. I was wondering if there's way to control the left-menu order on export.

**Comment by zadam** [comment]
@decentropy the backend data model did not keep the notes sorted, I guess I assumed it's not needed on the backend. But for export it is, it should keep the order as it is defined in the application. I fixed this in the 0.59 branch.
