### ISSUE TITLE
(Feature request) Show page references with some context

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2349]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

This is a feature that Roam Research-like software (e.g. Athens Research, logseq) has.

On any page, you can see blocks from other pages that reference it (i.e., link to it). That's a useful feature for seeing the connections between ideas and such. Here's a screenshot:

![image](https://user-images.githubusercontent.com/714892/142064832-bb1d4645-2651-475e-b3e9-30724b3b1de3.png)

It would be nice to have a feature like this in Athens, where on a page, you could see not just the pages that reference it with a link, but also some context of how they link it. It's also useful to have it on the default view of a page in Roam-like software.

### Additional Information

I know this would be made more complicated by Trilium not being block-based. Maybe you could heuristically snip, say, +/- 1 sentence around the mention.

I expect this would be hard, and don't expect this will be implemented any time soon. Just wanted to say this would make Trilium better.

**Comment by zadam** [comment]
Work in progress:

![image](https://user-images.githubusercontent.com/617641/144322487-3c201716-7789-4899-9805-6df849709160.png)

**Comment by agentydragon** [comment]
Awesome! <3
Some thoughts seeing this prototype:

* Will it be ergonomic if there's a lot of backlinks? Maybe there could be some switch like "low context / high context".
* Not sure whether it would be useful to include relations.
* What's the right sort order for mentions? Maybe might be useful to have a switch for that.

**Comment by zadam** [comment]
Implemented, released, closing.
