### ISSUE TITLE
(Bug report) templated note does not get focus

### ISSUE THREAD

**Issue by adamcodemaker** [zadam/trilium#2353]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.6

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

Ubuntu 20.04

### Expected Behavior

New templated note should get focus when it is created

### Actual Behavior

Templated note does not get focus when it is created
There is message in console
`Waiting for entityChangeId 1349 while last processed is 1348 (last accepted 1349) for 0s`
and when I click anywhere else in notes tree then new note gets focus

### Additional Information

to replicate the problem
1. create note "test focus"
2. in this note create note "issuetemplate" and add #issue to its owned attributes
3. create note "start" and add "~child:template=issuetemplate" to its owned attributes
4. click on + start note to create templated child
5. observe that "new note" does not get focus

It have this issue on 0.48.6.
On 0.47.8 it works ok

**Comment by zadam** [comment]
Hello, I think I already fixed the bug and it will be in the 0.48.7 which should be released soon.

**Comment by adamcodemaker** [comment]
issue is fixed in 0.48.7
good job
thank you :)

**Comment by zadam** [comment]
Great, thanks for info.
