### ISSUE TITLE
(Bug report) Setup Page is white 

### ISSUE THREAD

**Issue by Jonas-stack3009** [zadam/trilium#2357]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

13.6.1

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Expected Behavior

see what is happening on the setup screen, e.g. what step the program is taking, if there is an error or progress

### Actual Behavior

When I try to start Trilium, the setup page is displayed and nothing is visible. After waiting for several minutes, nothing happened.

**Comment by zadam** [comment]
Hi, could you please post the log from the [data directory](https://github.com/zadam/trilium/wiki/Data-directory)?

Also could you press `CTRL+SHIFT+I` on the blank setup screen and make a screenshow? This opens the developer console which might contain more details.

**Comment by Jonas-stack3009** [comment]
Thanks for your quick reply:

![image](https://user-images.githubusercontent.com/82601197/142624874-a532d02b-3efc-4f25-af33-4a6011bf4d67.png)
There are also no warnings, error messages or notifications in the console. 

Log file has only one entry: 10:15:04.568 DB not initialized, please visit setup page

maybe I am just too incompetent to install your software

**Comment by Myzel394** [comment]
A friend of mine is also facing this issue. I know that his network is limited by his parent, however, I don't think this has to do something with it. I will take a look with him in the near future.

**Comment by zadam** [comment]
@Jonas-stack3009 to be honest I have no idea what's going on. It doesn't look like any user error.

**Comment by Jonas-stack3009** [comment]
Thank you for your help.  I will try again on another PC and I hope that I will be successful.

**Comment by zadam** [comment]
I recalled similarity with #2071 

You can try running (from command line) trilium like this:

```
trilium --disable-gpu
```

**Comment by Jonas-stack3009** [comment]
This tipp worked fine for me. Now i can follow the Setup Steps

**Comment by zadam** [comment]
I'm glad it worked for you.

**Comment by komali2** [comment]
This didn't resolve this same issue I had.

Logs before disable gpu:

https://pastebin.com/VXaMrZuj

Logs after disable gpu:

https://pastebin.com/0us2eRSg

System info: 

```
**System Information:**

**Operating System:**
- Distribution: Manjaro Linux 25.0.3 (Zetar)
- Kernel: 6.14.6-2-MANJARO #1 SMP PREEMPT_DYNAMIC
- Architecture: x86_64

**Display Server:**
- Session Type: Wayland
- Window Manager: Sway 1.10.1

**GPU Information:**
- GPU: AMD Radeon 890M (Strix)
- Driver: Mesa 25.0.5-arch1.1 (radeonsi, gfx1150, LLVM 19.1.7, DRM 3.61)
- Mesa Package: mesa 1:25.0.5-1
- Linux Firmware: linux-firmware 20250508.788aadc8-1

**Hardware:**
- CPU: AMD Ryzen AI 9 HX 370 w/ Radeon 890M
- Cores: 12 cores, 24 threads
- Memory: 30GB RAM (16GB available)
- Swap: 33GB

**Trilium**

- triliumnext-bin                       0.94.0-1                         AUR         108.5 MB
```

I have triliumnext-bin working successfully on another manjaro system, however that's i3 xorg with an nvidia gpu.
