### ISSUE TITLE
(Bug report) Search results should not contain temporary search pages 

### ISSUE THREAD

**Issue by jasongwq** [zadam/trilium#2361]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 11

### Expected Behavior

Default Search results should not contain temporary search pages （not use Save to note）

### Actual Behavior

![image](https://user-images.githubusercontent.com/7529184/142736336-3b8e896a-bb14-4172-9942-52bc7a82ba81.png)

**Comment by zadam** [comment]
Hi, that's right, fixed.
