### ISSUE TITLE
(Feature request) Limit Note Map to Hoisted Notes

### ISSUE THREAD

**Issue by Zocker1999NET** [zadam/trilium#2365]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

- currently, a note map contains (nearly) all notes linked to the current one, also including notes outside of the current hoisted note tree
- please limit that to the current "hoist"

### Additional Information

Really, zadam, you do a great job on this app, thank you for your work

**Comment by zadam** [comment]
Hi, this has been fixed a while ago, but forgot to mark the issue as closed. Thanks for reporting.
