### ISSUE TITLE
(Bug?)  Not all note tree are seen on mobile browsers

### ISSUE THREAD

**Issue by thehotery** [zadam/trilium#2367]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.6

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Windows & ipados / android

### Expected Behavior

Web interface of trilium looks in mobile browsers looks correctly

### Actual Behavior

Its not...
Its strange issue, and it was before 0.48 version redisign
Screenshot from computer's browser
![image](https://user-images.githubusercontent.com/62539068/142757145-476f40ac-bb79-4738-9e71-fa1ffc51bbcd.png)

Screenshot from Safari on IpadOS 15 (but all the same in ipados 14 or on android tablet)

![image](https://user-images.githubusercontent.com/62539068/142757171-0456d648-3cdb-40a0-88e7-224b7ff1e5b8.png)

the lower part of the web page disappeared. In the "example" thread the notes are named from 1 to 23 (screenshot on the desktop), in the screenshot of the iPad - 22, and it is difficult to press the lower part (in the tablet on android - 20).

The screenshot shows a mobile view, but if it switches to desktop mode, it's the same. Same problem on android 11 phone, with chrome and brave.

It's a strange thing, I usually don't use **firefox on android**, and it turned out that there is **no such problem** (it's not about the chrome cache or brave, no). So, problem are "only" on chrome/chromium based browsers on android and Safari on ipad

Is this reproducible or is there a problem with my installation? (

**Comment by zadam** [comment]
I think I can reproduce it now. Seems like a mobile only problem, even mobile mode on desktop chrome can't reproduce it (which will make debugging difficult :-/)

**Comment by zadam** [comment]
Found and fixed the issue. Some details are here: https://stackoverflow.com/questions/52848856/100vh-height-when-address-bar-is-shown-chrome-mobile
