### ISSUE TITLE
(Bug report) Setup not working

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#2368]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

latest main branch, 0.48.6.1, 0.48.6

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Debian

### Expected Behavior

Setup should work as always.

### Actual Behavior

I'm trying to create a fresh installation but setup won't work after I click "Finish setup".

Here are the logs:

```bash
DB size: 4 KB
DB not initialized, please visit setup page - http://[your-server-host]:8080 to see instructions on how to initialize Trilium.
App HTTP server starting up at port 8080
{
  "appVersion": "0.48.6",
  "dbVersion": 187,
  "syncVersion": 21,
  "buildDate": "2021-11-13T22:49:58+01:00",
  "buildRevision": "c94603010630cfafe64575ab378c482bb39fb083",
  "dataDirectory": "/home/myzel394/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
CPU model: AMD Ryzen 7 3700X 8-Core Processor, logical cores: 16 freq: 2139 Mhz
Listening on port 8080
Creating database schema ...
Creating root note ...
ERROR: post /api/setup/new-document threw exception: SqliteError: near "(": syntax error

```

### Additional Information

Tried to delete data dir and changed permission on it to `777`. Rebuilt `better-sqlite3` using `electron-rebuild` and also deleted `node_modules` and reinstalled dependencies. Do you have any idea how to get this up running?

**Comment by zadam** [comment]
Fixed, this regression was present only in (unreleased) master.
