### ISSUE TITLE
(Feature request) Make setup more user-friendly for non-tech-savvy people

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#2370]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

To make Trilium Notes easier to use for non-tech-savvy people I suggest making it's setup easier and more appealing to use.

### Additional Information

I would declutter the setup a little bit and shift the focus on the initial setup (no server instance available, just local setup), because most people (who are not tech-savvy) won't have a self-hosted server they can connect to. And if they have, they have at least some knowledge.

Here's how I would go with the design:

Initial setup page when you open the program for the first time:
![First](https://user-images.githubusercontent.com/50424412/142767920-c4272371-be5c-4201-89bf-5a3fab0c33ea.png)

Second page (after you press "Start Setup"):

![MacBook Pro - 4second](https://user-images.githubusercontent.com/50424412/142768195-3908ec95-c0da-4a58-8840-59258f120c50.jpg)

I haven't created the other pages yet, because I first wanted to know what you think so far. So, what do you think @zadam ?

**Comment by zadam** [comment]
I plan to radically the setup experience but somewhat differently:

* the initial choice of "new document", "setup sync" needs to stay since when you already have a sync server then you need to setup the sync on the client right away - it's not possible to sync two different "documents". However better guidance and clear default "new document" can improve the clarity.
* on the other hand I would like to leave out username & password from the setup - for people not using web version or protected notes it's not needed and if need be it can be set up later.
  * username might be left out completely since it doesn't really serve any purpose

So the typical setup (desktop) would be - the initial choice screen - "create new document", click on "finish" and that's it.

**Comment by Myzel394** [comment]
1) Why does it need to stay? If you have a server, you can click on "I have a server I can connect to" and then your setup will change. If we don't require a password at the start, we can ask the user and optionally activate the fields (otherwise they will be grayed out) - that's how I would do it
2) That's per se a good idea. However, how will the read-only user work? Or how will multi-user support work? If we plan to do that, we shouldn't remove the username

**Comment by zadam** [comment]
1. Trilium sync works on the principle that there's one document synchronized across the network. So when you want to sync from the remote server, you need to do it before you create a second document locally. If you allow to change this after, what do you do with the second local document?

2. Not sure what you mean by "read only" user - there's a feature (currently being worked on) which allows you to publish notes online. For that no user is necessary, it's publicly accessible. Multi-user is not going to happen (see [FAQ](https://github.com/zadam/trilium/wiki/FAQ#multi-user-support)).

**Comment by Myzel394** [comment]
1. I think you misunderstood me. If you click on "Start Setup", you will be taken to the second page (the second screenshot). If you enter the inputs and click on "Finish Setup", you will have a local setup created. If you click on the bottom right on "I have a server I can connect to", you will be redirected to another page, where you can connect to your server and you will have a server setup.
2. I didn't know that, in that case, the username is indeed unnecessary :D

**Comment by zadam** [comment]
I see, that's sort of difficult to notice and I did not see it. If the username/password will get removed then this choice will be essentially the only thing for the user to decide on during the setup. (theme choice is IMHO secondary and can be removed from the setup.

**Comment by Myzel394** [comment]
I know that the theme selection isn't so important, but it gives the user the ability to personalize it's Trilium instance. And it's also something very easy to understand, I think it would be good to show this easy selection after asking them this "strange" question whether they want a local or a server setup

**Comment by Myzel394** [comment]
So, will username be removed or not?

**Comment by zadam** [comment]
My current thinking is that it should be removed, but I'm open to hear arguments against it.

As for the theme selection, I'm not sure. Especially if all the other settings fall out, will configuring theme justify having an extra step/screen in the setup process?

**Comment by zadam** [comment]
username has been removed, password is now settable in the options. Even though it remains ugly, I think the point of simplifying the process has been achieved.
