### ISSUE TITLE
可以增加常驻托盘区域么？（Can add the permanent tray?）

### ISSUE THREAD

**Issue by QingShui23** [zadam/trilium#2371]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

常驻托盘区可以方便随时打开软件进行记录，我试过其他Electron打包的note程序具备这个功能。
The resident tray area can easily open the software to record at any time. I have tried other Electron packaged note programs that have this function.

**Comment by Nriver** [comment]
#2325

**Comment by zadam** [comment]
Will be in the next version (0.49)

**Comment by QingShui23** [comment]
thks！！
