### ISSUE TITLE
When inputting Chinese, it will automatically leave English letters in front.

### ISSUE THREAD

**Issue by QingShui23** [zadam/trilium#2372]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 功能体验包 1000.22000.348.0

### Expected Behavior

在输入中文的时候前面会自动留下一个字母，出现的情况在80%左右。
[](url)
![企业微信截图_163755530072](https://user-images.githubusercontent.com/7929884/142801320-11c7b6a7-d2db-4109-9950-2c6ecdf5cfcd.png)

### Actual Behavior

？？

**Comment by Myzel394** [comment]
From what I understand, it seems like that an extra character is inserted when typing chinese characters. However, I can't reproduce this issue, maybe this issue only occurs with this given "F" shaped like chinese character. @QingShui23 could you copy-paste your text here so I can reproduce this issue? :smile:

**Comment by Nriver** [comment]
It may be a browser related issue. On iOS, with the system built-in Chinese IME, the default browser Safari has no problem. However, if I use some 3rd party browser, like Alook browser, this "bug" can be reproduced.

By the way, in my experience, the extra character only occurs at the beginning of the line.

**Comment by linger98** [comment]
On Windows OS, using inline encoded Chinese IMEs, such as Microsoft IME and RIME, has this problem and some other problems. We can choose to use non-embeddable Chinese IMEs, such as Sogou IME, to avoid these problems.

**Comment by Myzel394** [comment]
@Nriver could you paste some text where this bug occurs? (so I can reproduce it)

**Comment by Nriver** [comment]
@Myzel394 try type nihao (你好, which means hello in Chinese) in a note content in Alook browser

type 'nihao' will get 'nnihao'
![photo_2021-11-23_16-28-34](https://user-images.githubusercontent.com/6752679/142991360-b46ebff4-d7a5-4327-9ca2-cf3ca52fd690.jpg)

after select the word 你好, the extra 'n' is still there
![photo_2021-11-23_16-28-39](https://user-images.githubusercontent.com/6752679/142991471-f16e38d1-6db4-42f1-b1a5-c36a076b7107.jpg)

**Comment by Myzel394** [comment]
I can't reproduce this issue at the moment. Tried Firefox and Chrome (I don't have any Apple products). However, after a quick search, I found out that the Alook Browser is only available for iOS. I think it's (as you already said) an issue with Apple's notoriously underdeveloped Safari browser. I'm sorry, but if this issue doesn't occur in other engines than WebKit (the browser engine from Safari), I'm not gonna fix it. Others can do it of course, but Apple gives a sh1t about their browser support and I don't want to support this.

**Comment by QingShui23** [comment]
> 
我使用的windows11，22000，348这个版本的系统。
浏览器使用的是Vivaldi
Vivaldi | 4.3.2439.65 (Stable channel) （64 位）
修订版本 | 422e3f53c5055d214398129edf198ce15d0fcdd7
操作系统 | Windows 11 Version 21H2 (Build 22000.348)
JavaScript | V8 9.4.146.24
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36

**Comment by QingShui23** [comment]
> I can't reproduce this issue at the moment. Tried Firefox and Chrome (I don't have any Apple products). However, after a quick search, I found out that the Alook Browser is only available for iOS. I think it's (as you already said) an issue with Apple's notoriously underdeveloped Safari browser. I'm sorry, but if this issue doesn't occur in other engines than WebKit (the browser engine from Safari), I'm not gonna fix it. Others can do it of course, but Apple gives a sh1t about their browser support and I don't want to support this.

我使用的windows11，22000，348这个版本的系统。
浏览器使用的是Vivaldi
Vivaldi | 4.3.2439.65 (Stable channel) （64 位）
修订版本 | 422e3f53c5055d214398129edf198ce15d0fcdd7
操作系统 | Windows 11 Version 21H2 (Build 22000.348)
JavaScript | V8 9.4.146.24
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36

**Comment by olunju** [comment]
hi, I encountered this problem too, but only when changing hyperlink text using Microsoft input methods that leave multiple spellings before typing Chinese. 
On the Win10 Edge browser

**Comment by anno189** [comment]
Many software have this problem. I think it is due to the interruption of the input method when building redraws
