### ISSUE TITLE
(Bug report) Image not immediately updated after uploading a new revision of the image

### ISSUE THREAD

**Issue by xyqyear** [zadam/trilium#2378]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 21H1

### Expected Behavior

After uploading a new revision of the Image, I expect the image to be immediately updated in the note.

### Actual Behavior

How to reproduce:

1. Create a new note
2. Insert an image into the note
3. double click the image to reveal file details
4. click the "upload new revision" button to update the image
5. go back to the note

You will find the image is not updated. It will only be updated when you reload the frontend or restart the application.

**Comment by zadam** [comment]
Hi, thanks for the report. I've added a HTTP header instructing the browser to not cache the image which fixes this issue.
