### ISSUE TITLE
Global style chaos after opening special notes

### ISSUE THREAD

**Issue by olunju** [zadam/trilium#2379]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

CentOS 7

### Expected Behavior

![image](https://user-images.githubusercontent.com/67050602/143434897-1b95ead8-833d-45d9-86b9-f12c64c9bbbe.png)
![image](https://user-images.githubusercontent.com/67050602/143434952-2adfe380-306b-4f0d-92ea-1a971dbe0422.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/67050602/143435003-e4983643-2cfb-485d-9471-b238893e7281.png)
![image](https://user-images.githubusercontent.com/67050602/143435036-92ca3682-508f-4202-adac-0293b274e266.png)

### Additional Information

This problem occurs when I click on the parent page of a render HTML note. 

![image](https://user-images.githubusercontent.com/67050602/143435311-e231bed6-9adb-42c3-810d-763b5d9f2b2c.png)

The rest of the time it was normal

**Comment by olunju** [comment]
It's possible that the CSS in the notes affects the overall situation, but I don't think that should happen

**Comment by olunju** [comment]
Could you please give me an answer?I can make adjustments as soon as possible.Rendering notes is a nice feature

**Comment by zadam** [comment]
This is possible with type "render note". CSS does not allow encapsulation so if it's loaded it can affect the whole element tree. The fix is in writing the CSS in your render notes so that it allows only elements within it.

**Comment by olunju** [comment]
> This is possible with type "render note". CSS does not allow encapsulation so if it's loaded it can affect the whole element tree. The fix is in writing the CSS in your render notes so that it allows only elements within it.
Yes, I noticed that "render note" should not be a complete HTML page, it should be an HTML fragment. It's working fine now
