### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by QingShui23** [zadam/trilium#2383]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 功能体验包 1000.22000.348.0

### Expected Behavior

我有一个桌面版本的trilium，现在想搭建一个服务端版本来同步数据。
我使用的是 @Nriver 制作的中文版本
使用的docker镜像来安装的服务端。
---
I have a desktop version trilium, now want to build a server version to synchronize data. I use is made of @ Nriver docker mirror to install the Chinese version of the use of the service side.
```
docker run -d -p 127.0.0.1:8080:8080 --name tmserver -v /data/trilium-data:/home/node/trilium-data -e TRILIUM_DATA_DIR='/home/node/trilium-data' nriver/trilium-cn
```
我使用了nginx，配置如下
---
I use the nginx, configuration is as follows
```
server {
    listen              443 ssl;  
    server_name         mysite;
    ssl_certificate     /data/crt.crt;  
    ssl_certificate_key /data/key.key;
    ssl_session_cache   shared:SSL:1m;  
    ssl_session_timeout 5m;  
    ssl_ciphers         HIGH:!aNULL:!MD5;         
    ssl_prefer_server_ciphers  on;
   
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8080;
        
    }

    location ~ /.well-known {
        allow all;
    }

    client_max_body_size 50m;
}
```
现在不能正常同步，错误日志如下：
---
Now can't normal synchronization, error log is as follows:
[trilium-2021-11-26.log](https://github.com/zadam/trilium/files/7606003/trilium-2021-11-26.log)

### Actual Behavior

同上

**Comment by zadam** [comment]
Hi, thanks for the report, could you please include also the log of the sync client (the other side of the sync exchange).

It looks like the sync client keeps repeating the same request in quick succession and the log might shed more light on why.

Thanks.

**Comment by QingShui23** [comment]
> Hi, thanks for the report, could you please include also the log of the sync client (the other side of the sync exchange).
> 
> It looks like the sync client keeps repeating the same request in quick succession and the log might shed more light on why.
> 
> Thanks.
好的，你可以看看这个。
[trilium-2021-11-26.log](https://github.com/zadam/trilium/files/7611039/trilium-2021-11-26.log)
[trilium-2021-11-25.log](https://github.com/zadam/trilium/files/7611040/trilium-2021-11-25.log)

**Comment by QingShui23** [comment]
Today I test it again
A new error log here
```
11:25:55.435 ERROR: Failed to deserialize sync response: Logged in session not found
11:26:11.289 304 GET /api/clipper/handshake with 45 bytes took 1ms
11:26:55.436 sync failed: Request to PUT https://tmserver.1900.live//api/sync/update failed, error: 401 Unauthorized
stack: Error: Request to PUT https://tmserver.1900.live//api/sync/update failed, error: 401 Unauthorized
    at generateError (D:\Program Files (x86)\trilium-windows-x64\resources\app.asar\src\services\request.js:191:12)
    at ClientRequest.<anonymous> (D:\Program Files (x86)\trilium-windows-x64\resources\app.asar\src\services\request.js:62:28)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
11:26:55.437 ERROR: Failed to deserialize sync response: Logged in session not found
11:27:11.293 304 GET /api/clipper/handshake with 45 bytes took 1ms
11:27:55.427 sync failed: Request to PUT https://tmserver.1900.live//api/sync/update failed, error: 401 Unauthorized
stack: Error: Request to PUT https://tmserver.1900.live//api/sync/update failed, error: 401 Unauthorized
    at generateError (D:\Program Files (x86)\trilium-windows-x64\resources\app.asar\src\services\request.js:191:12)
    at ClientRequest.<anonymous> (D:\Program Files (x86)\trilium-windows-x64\resources\app.asar\src\services\request.js:62:28)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
11:27:55.428 ERROR: Failed to deserialize sync response: Logged in session not found
11:28:11.279 304 GET /api/clipper/handshake with 45 bytes took 0ms
11:28:55.449 sync failed: Request to PUT https://tmserver.1900.live//api/sync/update failed, error: 401 Unauthorized
stack: Error: Request to PUT https://tmserver.1900.live//api/sync/update failed, error: 401 Unauthorized
    at generateError (D:\Program Files (x86)\trilium-windows-x64\resources\app.asar\src\services\request.js:191:12)
    at ClientRequest.<anonymous> (D:\Program Files (x86)\trilium-windows-x64\resources\app.asar\src\services\request.js:62:28)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
11:28:55.449 ERROR: Failed to deserialize sync response: Logged in session not found
11:29:11.289 304 GET /api/clipper/handshake with 45 bytes took 0ms

```

**Comment by zadam** [comment]
> SqliteError: database disk image is malformed

Your database is corrupted. Your best bet is to set up the sync anew.

The reason for corruption is OneDrive. All of these sync applications corrupt (database) files. See https://github.com/zadam/trilium/wiki/FAQ#can-i-use-dropbox--google-drive--onedrive-to-sync-data-across-multiple-computers

**Comment by QingShui23** [comment]
> > SqliteError: database disk image is malformed
> 
> Your database is corrupted. Your best bet is to set up the sync anew.
> 
> The reason for corruption is OneDrive. All of these sync applications corrupt (database) files. See https://github.com/zadam/trilium/wiki/FAQ#can-i-use-dropbox--google-drive--onedrive-to-sync-data-across-multiple-computers

谢谢，已经解决了。
我把文件从“损坏”的数据库里导出了，然后重新建立数据库导入。
