### ISSUE TITLE
(Bug report) Importing ZIP backup works selectively

### ISSUE THREAD

**Issue by surajsharma** [zadam/trilium#2384]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOs 11.6 

### Expected Behavior
All of the notes should be imported.

### Actual Behavior

While importing a rather sizeable ZIP file into a fresh installation, I can see (with all the default options on the import dialog) that not all the notes are imported. The zip file in question has upwards of 1300 notes and only roughly about 1000 arbitrary notes are imported. Even after several tries, the same notes are excluded from the import.

**Comment by zadam** [comment]
Hi, how do you know that the notes are missing? Did you explore the ZIP archive? Are the notes/files in there?
