### ISSUE TITLE
(Bug report) Deleting last copy of repeated attribute should leave behind an empty attribute box

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2388]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.6

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop!_OS 20.04

### Expected Behavior

Create a note with a repeated relation attribute, like ` #relation:hotlist="promoted,multi,inverse=issues"`

When you open the note's promoted attributes, and one of these defined relations does not have any value, it's displayed as an empty combobox:
![image](https://user-images.githubusercontent.com/714892/143606356-eb03d0fb-0ec5-40b9-b728-01f18e6be220.png)

That empty combobox lets you enter the first value for the relation.

When you delete the only relation of a type the note has, the same thing should appear - an empty combobox to let you enter a value for the repeated relation.

### Actual Behavior

Instead of the one copy of the combobox staying behind (and being empty) after you delete the relation, the combobox disappears and you can't set the relation for Promoted attributes view anymore.

But when you force a re-render (like by going to Note info view, then back to Promoted attributes), the empty combobox correctly appears.

### Additional Information

Video:

https://user-images.githubusercontent.com/714892/143606798-80dcdb70-e665-4c29-82f9-2af3ba7c1b6d.mp4

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, fixed.
