### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by Lolabird** [zadam/trilium#2392]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint (Desktop), Linux Ubuntu

### Expected Behavior

ctrl+z undoes the automatic formatting of ==. ===. !=. !==. . and other similar coding syntax. 

### Actual Behavior

Undoing does not revert to regular syntax in coding blocks.

**Comment by abitofevrything** [comment]
This is a CKEditor bug, and cannot be fixed from Trilium.
