### ISSUE TITLE
#apptheme works on the server but is inconsistent on desktop version

### ISSUE THREAD

**Issue by Lolabird** [zadam/trilium#2393]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint (Desktop), Ubuntu (Server)

### Expected Behavior

Using a theme with the tag apptheme should stay applied without having to change the theme or reloading front end. 

### Actual Behavior

On the desktop version, when app times out the app theme reverts to the light theme. It also reverts to the light theme when the app is closed and then reopened. This doesn't happen on the server version. The theme is consistent there. I tried adding the tag appCSS, but that does not fix the consistency issue. 

### Additional Information

I haven't inspected the code too closely, so I'm not sure if the answer to #1941 applies, but I assumed it didn't since themes seem to work fine on the server version. I did look to see if having the !important selector as suggested in #2355 was an issue here, but the lines that were marked !important didn't seem to be applied upon signing back in or reopening the program on the desktop. I'm new to the themes thing, so maybe I'm missing something. I tested this with Neon Dark, Coder Dark, and Rainbow in the Dark.

**Comment by Lolabird** [comment]
I figured out what the issue is for desktop. If the note is protected, the theme won't load when you're signed out of protected note mode. This same issue doesn't apply on the server version, though. Whether in protected mode or not, the theme will still stick.

**Comment by zadam** [comment]
Hi, thanks for this report.

I can reproduce this. It looks like browser will use cached version of CSS even though the server responds with 401. Not sure why electron differs here and how to fix this ...

**Comment by Lolabird** [comment]
I noticed that something similar happens with bookmarks where, if they are protected, you have to refresh the front end after signing in for the actual note titles to show. Unprotected notes don't have that problem.

**Comment by zadam** [comment]
Hi, thanks for the report, fixed.

**Comment by Lolabird** [comment]
Thanks for working on it!
