### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by laughstorms** [zadam/trilium#2400]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Linux ab30f5df76a3 4.13.16 #446 SMP Thu Nov 19 16:35:43 CST 2020 x86_64 Linux

### Expected Behavior

const notes = api.searchForNotes(search + " #code"); 

### Actual Behavior

Load of script note "getcode" (0D2UkR8WGF12) failed with: Cannot read property 'includes' of null

**Comment by zadam** [comment]
What's the value of "search"?
