### ISSUE TITLE
(Feature request) copy reference-link in note tree

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2401]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

I know there is a "In-place linking" which can be triggerd by typing @. I find it sometimes tedious to type in the long name of notes.

It would be nice to have a "copy reference link" in the note tree context menu while browsing through the note tree and get the reference link of certain note by a simple click.

**Comment by zadam** [comment]
Hi, good idea. Now right click -> copy or ctrl+c will also insert HTML links into the clipboard. Works also for multiple notes.

Will be in the next minor release (0.49)

**Comment by thfrei** [comment]
As an afternote: It should be possible to use without electron: https://stackoverflow.com/questions/23211018/copy-to-clipboard-with-jquery-js-in-chrome

```javascript
async function copy(branchIds) {
    clipboardBranchIds = branchIds;
    clipboardMode = 'copy';

    if (utils.isElectron()) {
        // https://github.com/zadam/trilium/issues/2401
        const {clipboard} = require('electron');
        const links = [];

        for (const branch of froca.getBranches(clipboardBranchIds)) {
            const $link = await linkService.createNoteLink(branch.parentNoteId + '/' + branch.noteId, { referenceLink: true });
            links.push($link[0].outerHTML);
        }

        clipboard.writeHTML(links.join(', '));
    }

    toastService.showMessage("Note(s) have been copied into clipboard.");
}
```

Also, showing a note, that says "copied into clipboard" when actually nothing happens, might be misleading. Suggestion:

```javascript
async function copy(branchIds) {
    clipboardBranchIds = branchIds;
    clipboardMode = 'copy';

    if (utils.isElectron()) {
        // https://github.com/zadam/trilium/issues/2401
        const {clipboard} = require('electron');
        const links = [];

        for (const branch of froca.getBranches(clipboardBranchIds)) {
            const $link = await linkService.createNoteLink(branch.parentNoteId + '/' + branch.noteId, { referenceLink: true });
            links.push($link[0].outerHTML);
        }

        clipboard.writeHTML(links.join(', '));
        toastService.showMessage("Note(s) have been copied into clipboard.");
    } else {
         toastService.showMessage("Only available in Electron/Desktop as of now"); // or something like it.
    }

}
```

**Comment by zadam** [comment]
HTML needs to be put into the clipboard so the `clipboard.write()` API would have to be used. 

> Also, showing a note, that says "copied into clipboard" when actually nothing happens, might be misleading.

That's not exactly true - the note is still copied into the clipboard for pasting in the tree (for cloning / cutting).
