### ISSUE TITLE
Bug about exporting to markdown file

### ISSUE THREAD

**Issue by djw-easy** [zadam/trilium#2402]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 21H2

### Expected Behavior

~~~
what i write


what i write
~~~

### Actual Behavior

~~~
what i write
~~~

~~~
what i write
~~~

### Additional Information

One more empty line can not be exported to markdown file successfully

**Comment by zadam** [comment]
Markdown export is handled by `turndown` and `joplin-turndown-plugin-gfm` so if there's some problem it will have to be handled there.
