### ISSUE TITLE
Searching problem

### ISSUE THREAD

**Issue by iridiumR** [zadam/trilium#2403]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 21H2

### Expected Behavior

I don't know how to solve it.

### Actual Behavior

Every time I do a searching, there would leave a hidden page and can not be deleted, which is very annoying. They are hidden is the left bar, but show up in global note map. How can I solve it? It would be nice if you help me.

![image](https://user-images.githubusercontent.com/88495501/144700259-db90d2d5-4b1a-4432-a423-fc388a189ee1.png)

![image](https://user-images.githubusercontent.com/88495501/144700277-ac1e46b7-1100-44b7-8d0d-d38de7221eec.png)

**Comment by zadam** [comment]
Hi, search creates a hidden note, but they should be really hidden and not bother users so them appearing in note map is a bug which has been now fixed.

Thanks for reporting this.

**Comment by ArthasLich** [comment]
I think users should be able to delete the search note instead of hiding the search note.
