### ISSUE TITLE
(Bug report) Something went wrong with html

### ISSUE THREAD

**Issue by thehotery** [zadam/trilium#2405]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Server on ubuntu + web app on windows 11 in chrome browser

### Expected Behavior

html code is broken -> not usable markdown export, web app sometimes hangs

### Actual Behavior

To be clear, its not an issue until i'm tryied to export the note into markdown and produced unexpected result, so then i'm looked into note source and...

![image](https://user-images.githubusercontent.com/62539068/144739815-de5454a6-328a-4a71-9ddf-18147e425a1d.png)
(code of  problem part of the note here https://rentry.co/p7kpv )

but in interface its looks as usual

![image](https://user-images.githubusercontent.com/62539068/144739898-ee0a7b2b-7da4-4876-b5ea-cf1f05da357e.png)

Or maybe its not completely trilium issue and it is more correct to ask the developers of ckeditor?

**Comment by zadam** [comment]
What exactly is wrong with that HTML? Seems fine to me.

**Comment by thehotery** [comment]
I may be wrong, but it looks like the <a> tag is not closed where is should be, many items of list ( <li> ) are inside of that large <a> </a> tag. dont know that i can do wrong becaus user dont have access to html... maybe because of [ ] signs for whatever reason...
 please take a look at source [https://rentry.co/p7kpv](https://rentry.co/p7kpv)

**Comment by zadam** [comment]
I took a look on the source before and it looks fine. Please point out where exactly the problem is, otherwise there's nothing to do for me.
