### ISSUE TITLE
(Feature request) Favorite function

### ISSUE THREAD

**Issue by sheep94lion** [zadam/trilium#2411]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Is there some function like Favorite in trilium notes?
You can star a note into Favorite or remote it from Favorite.
Is there any CSS/JS plugin that implements this?

**Comment by thehotery** [comment]
Favorite - do you mean bookmark? (note - basic properties - bookmark)
![image](https://user-images.githubusercontent.com/62539068/144830176-983439fa-3437-4902-9d76-90308e9af714.png)

**Comment by sheep94lion** [comment]
Yes, exactly!

> Favorite - do you mean bookmark? (note - basic properties - bookmark) ![image](https://user-images.githubusercontent.com/62539068/144830176-983439fa-3437-4902-9d76-90308e9af714.png)

**Comment by zadam** [comment]
Just to complete the info, bookmarked notes will appear on the sidebar:

![image](https://user-images.githubusercontent.com/617641/144909157-06fce7c9-72ae-4d11-8540-1b263b6c8562.png)

Closing.
