### ISSUE TITLE
(Bug report) Even the Full search does not search inside links

### ISSUE THREAD

**Issue by cidious** [zadam/trilium#2412]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Microsoft Windows [Version 10.0.17763.2183]

### Expected Behavior

Make a hyperlink, start a Quick Search or Full Search, type some part of the URL, find it in the Search Results.

### Actual Behavior

No results

### Additional Information

![image](https://user-images.githubusercontent.com/631488/144840403-49667209-3a7b-415e-bf3a-9f8fe8e125ae.png)

![image](https://user-images.githubusercontent.com/631488/144840481-899f6be0-b816-4236-a05c-145cbcee3fbd.png)

**Comment by zadam** [comment]
Hi, so the issue, is that link's URL is in the A element's attribute and full text generally searches only through visible text.

However I agree that this is probably not expected, I added an exception to tag stripping so that A element is preserved so that URL matches will be found as well.
