### ISSUE TITLE
(Bug report) There is a bug when the query condition is ”and”

### ISSUE THREAD

**Issue by microver** [zadam/trilium#2427]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

v0.48.7 release

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

linux redhat 7.6

### Expected Behavior

Define labels in multiple pieces of information, for example:
info 1： #nameinclude=zhang #nameinclude=wang
info 2: #nameinclude=zhang #nameinclude=li

 When searching with the following criteria: 
#nameinclude=wang and (#nameinclude=zhang or #nameinclude=li)
 Correct results can be obtained ： info 1
When searching with the following criteria: 
(#nameinclude=zhang or #nameinclude=li) and #nameinclude=wang 
The query conditions are the same, and the results are the same that can be obtained: info 1

### Actual Behavior

 When searching with the following criteria: 
#nameinclude=wang and (#nameinclude=zhang or #nameinclude=li)
 Correct results can be obtained ： info 1 , It's right；
But When searching with the following criteria: 
(#nameinclude=zhang or #nameinclude=li) and #nameinclude=wang 
The query conditions are the same, but the order is change，It's unexpected results: info1 and info2，Results contained two message，It's wrong.

**Comment by zadam** [comment]
Hi, I think you stumbled upon the corner case described in [wiki](https://github.com/zadam/trilium/wiki/Search#separating-fulltext-and-attribute-parts)

Parser needs to separate between fulltext and attribute search and it uses some tokens to detect them. `(` is not one of them so this is still considered to be part of fulltext which leads to wrong results.

To fix it, you need to add the separator manually like this:

```
# (#nameinclude=zhang or #nameinclude=li) and #nameinclude=wang
```

`#` gives signal to the parser that the following content is attribute search.

**Comment by microver** [comment]
> Hi, I think you stumbled upon the corner case described in [wiki](https://github.com/zadam/trilium/wiki/Search#separating-fulltext-and-attribute-parts)
> 
> Parser needs to separate between fulltext and attribute search and it uses some tokens to detect them. `(` is not one of them so this is still considered to be part of fulltext which leads to wrong results.
> 
> To fix it, you need to add the separator manually like this:
> 
> ```
> # (#nameinclude=zhang or #nameinclude=li) and #nameinclude=wang
> ```
> 
> `#` gives signal to the parser that the following content is attribute search.



The problem has been solved, thank you very much!
