### ISSUE TITLE
(Bug report) Hard to find the attribute bar when the width of table is too big.

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2429]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

macOS

### What is your setup?

Local + server sync; and web client

### Operating System Version

macOS 12.0.1

### Expected Behavior

Easily find the attribute bar.

### Actual Behavior

Because the width of table must be set manually with a number, sometimes I accidentally type a very big number like 10000, so that it is hard to find the attribute bar when I want to correct it. (It falls at the center of the table.)

### Additional Information

Is there a good way to solve this? 

Really thank you!

**Comment by zadam** [comment]
Sorry, I don't really get your problem. Can you make some screenshot(s) illustrating your problem?

**Comment by Mirwaisse** [comment]
You can just Ctrl+Z.
If it's too late for that, you can change the note type to e.g. "Plain text" then modify the width in the raw text, then change note type back to "Text".

**Comment by gdbb** [comment]
> If it's too late for that, you can change the note type to e.g. "Plain text" then modify the width in the raw text, then change note type back to "Text".

This works! Thank you! Editing plain text can solve many weird problem.
