### ISSUE TITLE
(Question) Mismatch between the size of local database and sync server database. 

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2430]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Hi!

I have set up a sync server and successfully sync the data.
But I notice that the size of the document.db in local computer (macOS), is different from the one in sync server (Linux). 

Local: 64MB
Sync Server: 7.1MB

Because I'd like to use the sync server as a kind of "remote backup", I'm not sure what causes this and can I just use the document.db in sync server to restore my data?

Really thank you!

**Comment by zadam** [comment]
As long as you see this icon on the client, you're good and everything is synced: 
![image](https://user-images.githubusercontent.com/617641/145476278-5e8af1ea-d6aa-4aa0-a002-83a9a5c14492.png)

The difference in size can be explained in the way the databases work - when e.g. something is deleted, the database file does not shrink on its own, unless you issue `VACUUM` command they usually only grow in size.

> I'm not sure what causes this and can I just use the document.db in sync server to restore my data?

Yes, more exact guide on this is here: https://github.com/zadam/trilium/wiki/Backup#restoring-backup

**Comment by gdbb** [comment]
> As long as you see this icon on the client, you're good and everything is synced: ![image](https://user-images.githubusercontent.com/617641/145476278-5e8af1ea-d6aa-4aa0-a002-83a9a5c14492.png)
> 
> The difference in size can be explained in the way the databases work - when e.g. something is deleted, the database file does not shrink on its own, unless you issue `VACUUM` command they usually only grow in size.
> 
> > I'm not sure what causes this and can I just use the document.db in sync server to restore my data?
> 
> Yes, more exact guide on this is here: https://github.com/zadam/trilium/wiki/Backup#restoring-backup

Amazing! Sorry I just start to use trilium and forgot about the VACUUM command. VACUUM really works.
