### ISSUE TITLE
(Feature request) fulltext search with and

### ISSUE THREAD

**Issue by microver** [zadam/trilium#2431]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a feature request that matches the one I want to file, without success.

### Describe feature

Simple note search examples:
rings tolkien - fulltext search, this will try to find notes which have anywhere words "rings" and "tolkien"
info 1 : include "rings"
info 2：include "tolkien"

I want search rings or tolkien , I do that:
Search string :   rings or tolkien 
 Expected Behavior  : info1 and info2
but it results nothing.

How can I do it ?

**Comment by zadam** [comment]
For `OR` operator you need to use expression search:

```
note.content *=* rings OR note.content *=* tolkien
```

**Comment by microver** [comment]
Thank you very much!The problem has been solved !
If possible, please update this example to the wiki so that more people can understand it. Thank you!

**Comment by zadam** [comment]
Yes, I added it to the wiki: https://github.com/zadam/trilium/wiki/Search
