### ISSUE TITLE
(Bug report) Accidental Content Loss 

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2444]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS 12.0.1

### Expected Behavior

The title and contents are saved as normal.

### Actual Behavior

I just met title and content loss. 

The general situation is that I create a new note, insert a big image (about 10MB), add a paragraph and edit the title. 

When I revisit this note, the title has returned into the original "new note", and the paragraph has gone. Only the image is left.

I'm not sure whether I did some unconscious operation like "ctrl+z". 

Because the data safety is the most important thing, so I just want to confirm that if anyone ever notice things like this.

Or maybe it was my misoperation.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue.

I agree with you that data loss is a serious problem.

Is this bug reproducible? Meaning, if you try to do the same thing, does the data loss happen the same way?

Also, could you share log file (in [data directory](https://github.com/zadam/trilium/wiki/Data-directory)) from this day? Either here or to my email: zadam.apps@gmail.com

Thanks!

**Comment by gdbb** [comment]
Thanks for your reply!

> Is this bug reproducible? Meaning, if you try to do the same thing, does the data loss happen the same way?
I have tried several times and everything works well.

I have sent you the log file with email, because there are too many records.

Thank you!

**Comment by gdbb** [comment]
I met title loss again, namely title returning to "new note" automatically. (no content loss this time)

I cannot precisely reproduce this because there are too many factors to be considered. But these two situations are similar: copy the whole content of a page in OneNote, and paste them into a new Trilium note. After pasting, the laptop (and Trilium) gets stuck for a little while. At the same time, Trilium is still synchronizing.

If it was not my misoperation, maybe it has something to do with the sync?
