### ISSUE TITLE
(Bug report) The synchronization service running the latest mirror failed to start (Pi4B)

### ISSUE THREAD

**Issue by rundon** [zadam/trilium#2449]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.8

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

### Expected Behavior

同步服务启动失败。
命令：docker run -p 8080:8080 --name trilium -d zadam/trilium，镜像最新的 IMAGE ID：d785cc2323af
docker 版本：
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:14 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

### Actual Behavior

查询日志：
![image](https://user-images.githubusercontent.com/9165226/146497329-d435ef56-9e52-4d80-8b1c-ad75e298459d.png)

**Comment by WKSu** [comment]
Hi, I believe I am running into the same problem whenever I want to update Trilium on my raspberry Pi using Docker. The latest version I am able to run is 0.48.5. Any suggestions on how to fix it?

![image](https://user-images.githubusercontent.com/49348667/148556206-a3b57f95-d5a3-4766-91e3-4cec775b8779.png)

**Comment by zadam** [comment]
That's unfortunate, ARM build is user contributed and I don't have an ARM machine to test this ... :-/

**Comment by zadam** [comment]
There's a new "official" docker arm build now.
