### ISSUE TITLE
Decimal support in Number

### ISSUE THREAD

**Issue by breadcat** [zadam/trilium#245]
Hello,

I've been experimenting with the software and I'm liking it so far.

One thing I've noticed though is that in the weight tracker example, the weight attribute only supports whole numbers and no decimals. I was wondering if it were possible to extend this so decimal values could be supported.

Thanks!

**Comment by zadam** [comment]
Hello, yes, allowing floating point numbers should pretty easy change ... I'll keep it in mind.

**Comment by zadam** [comment]
Support for defining number precision has been committed to master and will be in the next release.
