### ISSUE TITLE
(Bug report) Must search with quotation mark

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2456]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.7

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS 12.0.1

### Expected Behavior

search attribute directly.

### Actual Behavior

Hi, zadam,

when I search #genre=sci-fi, there is no result, and I have to use #genre='sci-fi'.

Similarly, #x=y+y, I must search it with #x='y+y'

I'm not sure which symbol should be avoided for search convenience.

Maybe a better solution is to use quotation mark every single time?

Thank you!

**Comment by zadam** [comment]
Hi,

Only alphanumerical character and underscore can be used without quotes. Any other character needs to be quoted.

If you want, you can use quotes for every search.
