### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by sunflowerno0b** [zadam/trilium#2458]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

Version 0.48.6 (0.48.6)

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

MacOS Monterray 12.0.1

### Expected Behavior

Not applicable.

### Actual Behavior

Not applicable.

### Additional Information

Hello,

I understand Trilium for Mac OS is not supported. I started on MacOS but I would like to move the contents I have to Linux. By chance, does anyone know where those files lives so that I can copy them over to a USB and load into my linux local version of Trilium? 

Or do I have to start everything over fresh?

**Comment by Mirwaisse** [comment]
https://github.com/zadam/trilium/wiki/Data-directory
