### ISSUE TITLE
(Bug report) Cannot share root note

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2465]
### Trilium Version

0.49.0-beta

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora

### Description

Attempting to share the root note results in an error that the root note cannot be moved. Trying to move the root note to the shared note folder is recursive. I think just adding a folder for everything under root then sharing that one works as well, but maybe there's a better way to handle this.

**Comment by zadam** [comment]
Hi, I didn't really think of this, but yes, sharing root (and thus all notes) is not possible.

**Comment by sigaloid** [comment]
Thanks, closing!
