### ISSUE TITLE
Optional activation of the codemirror vim keymappings

### ISSUE THREAD

**Issue by DHMike57** [zadam/trilium#2476]
### Describe feature

Codemirror provides a vim compatibility keymap.  I find it a nice option especially for working on themes and js scripts where it is natural do do some editing in trilium itself.  See PR #

**Comment by zadam** [comment]
Merged.

**Comment by mlthlschr** [comment]
Would it be possible to enable VIM in non-Code notes as well? If it is not too complex, i could try it myself.

**Comment by zadam** [comment]
No, text editor is a different library (CKeditor) with no support for VIM mode.
