### ISSUE TITLE
Can't execute old code note; 500 error

### ISSUE THREAD

**Issue by PAK90** [zadam/trilium#2490]
### Trilium Version

0.47.5

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win10 21H1

### Description

I have an old code note (type JS-backend) that I want to use to search for Trilium notes from another program I'm writing. This code note used to work back when I first created it, but now when I make modifications to it and execute (Ctrl+Enter), it gives me the following error:

Error when calling POST /api/script/run/fI4QhrU16Vef: 500 - Load of script note "api:search-notes" (fI4QhrU16Vef) failed with: Cannot read property 'body' of undefined

For reference, this is the code in the note:

```
const {req, res} = api;
const {secret, queryString} = req.body;

if (req.method == 'GET') {
    const foundNotes = await api.searchForNotes(queryString);

    res.status(201).json(foundNotes.slice(0, 10));
}
else {
    console.log('---returning 400 status');
    res.send(400);
}
```

**Comment by zadam** [comment]
Hi, this is not an ordinary script note, it's a [custom request handler](https://github.com/zadam/trilium/wiki/Custom-request-handler). It's processing HTTP request and can't be executed without a HTTP request.
