### ISSUE TITLE
Let user be prompted before changing DB version

### ISSUE THREAD

**Issue by aktaboot** [zadam/trilium#2494]
### Describe feature

I installed Server version and DB was automatically updated to a new version, which led to me installing a beta version to access the DB with the Desktop version. 

User can be prompted so he knows the DB version will get updated, and that this could cause potential problems with other app versions (Desktop/Server).

**Comment by zadam** [comment]
Hi, can you clarify from which version to which version you updated?

In general, there are DB version changes only across minor version changes (0.48 → 0.49). 

So I guess you updated to beta on the server? And because of your sync you had to update to the same beta on desktop, right?

**Comment by aktaboot** [comment]
0.48.9-1 for the Desktop version, then I just cloned the repo to try and tinker a little with the code.
It automatically synced with my DB and updated it.

So yes the server is on latest/beta,  and Desktop on 0.48.9-1

**Comment by zadam** [comment]
It's not recommended running `master` branch on "production environment" since it can contain unstable code.

To the original request - originally Trilium had this notification, but users found it confusing and seemed to prefer "seamless" upgrades which is I think common in other apps as well.
