### ISSUE TITLE
OPML v2 import issue

### ISSUE THREAD

**Issue by jobidon** [zadam/trilium#2495]
I am trying to import an opml file from workflowy into Trilium and get an error (see below).
The sample file is attached [simple.zip](https://github.com/zadam/trilium/files/7794009/simple.zip)
My understanding was that opml v2 was now supported, but perhaps I need to add attributes to the xml first? Please advise.
Thanks!

`  "appVersion": "0.48.9",
  "dbVersion": 185,
  "syncVersion": 22,
  "buildDate": "2021-12-22T22:39:24+01:00",
  "buildRevision": "10a5773c66e678c6d2bd3bd9dc9952d5cd76b795"
`

logs:
`
12:22:01.049 Sending message to all clients: {"type":"taskProgressCount","taskId":"s4SzxVPvlm","taskType":"import","data":{"safeImport":false,"shrinkImages":true,"textImportedAsText":true,"codeImportedAsCode":true,"explodeArchives":true,"replaceUnderscoresWithSpaces":true},"progressCount":0}

12:22:01.051 Sending message to all clients: {"type":"taskError","taskId":"s4SzxVPvlm","taskType":"import","data":{"safeImport":false,"shrinkImages":true,"textImportedAsText":true," codeImportedAsCode":true,"explodeArchives":true,"replaceUnderscoresWithSpaces":true},"message":"Import failed with following error: 'Cannot read property 'toLowerCase' of undefined'. More details might be in the logs."}

12:22:01.051 ERROR: Import failed with following error: 'Cannot read property 'toLowerCase' of undefined'. More details might be in the logs.TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.sanitize (/opt/trilium-bin/resources/app.asar/src/services/html_sanitizer.js:9:38)
    at importOutline (/opt/trilium-bin/resources/app.asar/src/services/import/opml.js:54:33)
    at Object.importOpml (/opt/trilium-bin/resources/app.asar/src/services/import/opml.js:77:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async importToBranch (/opt/trilium-bin/resources/app.asar/src/routes/api/import.js:56:20)

12:22:01.051 POST /api/notes/kMrz7p4PQoVB/import returned 500 with response "Import failed with following error: 'Cannot read property 'toLowerCase' of undefined'. More details might be in the logs."

12:22:01.051 500 POST /api/notes/kMrz7p4PQoVB/import with 121 bytes took 2ms
`

**Comment by zadam** [comment]
Hi, thanks for your report, this is now fixed.

OPML is stored a bit differently in different applications which causes sometimes issues like this.

**Comment by jobidon** [comment]
Thanks for super fast response!
For reference, the workflowy implementation of OPML v2 uses a single "text" attribute for each outline, and Trilium requires a "title" attribute. A quick fix was to find and replace "text=" by "title=" in the source opml file
