### ISSUE TITLE
ctrl+shift+left not sure good UX

### ISSUE THREAD

**Issue by mahdi1234** [zadam/trilium#25]
Trillium 0.5.4 beta

- ctrl+shitf+down in tree to get detail of some note
- type text like "lorem ipsum"
- use ctrl+shift+left arrow

Expected:
Word "ipsum" is selected (this is kind of standard shortcut).

Observed:
Moved in the tree node up.

**Comment by zadam** [comment]
You're right, I didn't realize this is kind of standard shortcut. There's not enough free shortcuts/modifiers :-/

I'll remove ctrl+shift+left and right, they are kind of less important than ctrl+shift+up, ctrl+shift+down (which should be fine) anyway.
