### ISSUE TITLE
configure starting directory

### ISSUE THREAD

**Issue by alexisargyris** [zadam/trilium#250]
Hello,

First, thanks a lot for this great app!

And now for my question. Is the default location of the trilium-data directory configurable? Can it be changed? In the case of an already initialised installation, is it possible to move the trilium-data directory elsewhere and re-configure the app to look at the new location for its data?

**Comment by zadam** [comment]
Hello, yes, it is possible - just set TRILIUM_DATA_DIR environment variable to trilium-data path in the new location and run trilium. So something like this:

```bash
export TRILIUM_DATA_DIR=/home/user/data/whatever/trilium-data

./trilium
```

**Comment by alexisargyris** [comment]
I forgot to mention that I'm interested in the Windows desktop version of the app. Is the above suggestion still valid? If so, where should I enter that setting?

**Comment by alexisargyris** [comment]
Works exactly as advertised (e.g. set a TRILIUM_DATA_DIR environment variable in the Windows system control panel). This way one can, for example, share data between multiple installations of Trilium as long as all installations share the trilium-data directory and files are not accessed concurrently.

**Comment by mariostrd** [comment]
For non-technical people: you can set up the environment variable via Windows PowerShell by writing this command (put your own trilium-data directory):

[System.Environment]::SetEnvironmentVariable('TRILIUM_DATA_DIR','D:\path\to\trilium-data', System.EnvironmentVariableTarget]::User)
