### ISSUE TITLE
(Bug report) Search doesn't evaluate AND correctly

### ISSUE THREAD

**Issue by JaCoB1123** [zadam/trilium#2503]
### Trilium Version

0.48.9

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 21H1, Firefox 95.0.2

### Description

I'm currently in the process of migrating my TODOs to Trilium and the following query would be really helpful for me.

```
 ( note.parents.title='TODO' OR #todo ) AND ( #!state OR #state!=completed )
```

Quick explanation:
I'm trying to find all Notes, that are either children of my "TODO"-note OR are located anywhere and have the #todo-attribute. Any completed TODOs are irrelevant though.

Problem:
Trilium shows far too many search results (seemingly every note?)

What I noticed:
- Removing the space after the first open parenthesis results in no results at all. 
- ` ( #todo ) AND ( #!state OR #state!=completed )`  
  Yields the correct results, but obviously misses all notes below my  TODO note without the #todo-attribute.
- `note.parents.title = "TODO" OR #todo`  
  seems to work as expected.
- `( note.parents.title = "TODO" OR #todo )`  
  seems to be return a mixture of `#todo` and `note.parents.title = "TODO"`, but doesn't include any of the searches fully.

**Comment by zadam** [comment]
Hi, the problem is actually in the parenthesis. Search engine considers everything as a fulltext search until an "expression separator sign" is found - `#` or `~`, but not `(` (since that's quite common in fulltext searches).

So the following should work:

```
# ( note.parents.title='TODO' OR #todo ) AND ( #!state OR #state!=completed )
```

**Comment by JaCoB1123** [comment]
Awesome, that fixed it.

I see you already updated the wiki, thanks for that as well. 👍 

I'm closing this issue.
