### ISSUE TITLE
我在插入图片时报了一个错误 |  I in the insert images | times is a mistake

### ISSUE THREAD

**Issue by QingShui23** [zadam/trilium#2506]
### Trilium Version

0.48.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 功能体验包 1000.22000.348.0

### Description

我使用了trilium-collection-views创建了一个视图，并获取子类下的文章
_I use the trilium - collection - views created a view, and obtain a subclass of the article_

![image](https://user-images.githubusercontent.com/7929884/147914542-54528ef7-7b7b-4aed-bf3b-b3e070e360b4.png)

![image](https://user-images.githubusercontent.com/7929884/147914643-9e3a9cb4-8f07-4934-9740-c502b2d2bd44.png)

**Comment by zadam** [comment]
Hi, this was fixed already and waits for a release. (it's not a serious error in any case).

**Comment by QingShui23** [comment]
@zadam thanks!
