### ISSUE TITLE
(Bug report) Typo in `executeNote` error message

### ISSUE THREAD

**Issue by wunter8** [zadam/trilium#2513]
### Trilium Version

0.48.9

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu 18.04.6 LTS

### Description

The error message on line 8 says the type of the code block needs to be `Code: JS frontend`, but the type of the code block actually needs to be `Code: JS backend` based on the `if` statement on line 7.

https://github.com/zadam/trilium/blob/2b100230552bae4014398ea4ed251a294ebbb396/src/services/script.js#L6-L16

**Comment by zadam** [comment]
Good catch! Fixed.
