### ISSUE TITLE
RFC: Default theme - light or dark?

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#2516]
Hi, in the next version (0.50), setup will be one step shorter - user won't have to enter username & password (maybe they will never need it) and there won't be a choice of a theme (IMHO it doesn't make sense to have a step only for theme selection).

So I would like to ask you, what do you think would be better as a default theme?

Please vote with emoji:
 
* dark theme is better - click on :heart:
* light theme is better - click on :rocket:

**Comment by QingShui23** [comment]
I think the trilium needs a more modern UI design

**Comment by Nriver** [comment]
Even though I prefer dark theme. I think maybe it would be better if trilium can read dark/light mode status from OS settings on the first boot.

**Comment by zadam** [comment]
@Nriver good idea, electron does have access to [this information](https://www.electronjs.org/docs/latest/api/native-theme).

**Comment by agentydragon** [comment]
Yeah, do read the default theme from OS settings. I've been able to make my theme automatically adjust to my OS theme using CSS media queries: https://github.com/agentydragon/trilium-solarized-theme/blob/fa6b2598511b8d78cb0469edb124bdd02c6b0ac0/solarized.scss#L312

Unfortunately, on Pop!_OS, if the system switches theme while Trilium is running, it won't notice the theme change until I restart it. A small price to pay.

**Comment by zadam** [comment]
The theme is chosen **during the initial setup** based on OS settings. Impemented in 0.50
