### ISSUE TITLE
[macOS] Tree Manipulation - Drag and drop - Not Working

### ISSUE THREAD

**Issue by cadorn** [zadam/trilium#252]
Build: https://github.com/zadam/trilium/releases/tag/v0.25.0-beta

Expected: https://github.com/zadam/trilium/wiki/Tree-manipulation#drag-and-drop

Actual:

  * When trying to drop, the location indicator arrow appears in top left of screen
  * Drop is not working (node does not move)

This app looks very promising. Very much looking forward to trying it to organize many years of notes!

**Comment by zadam** [comment]
Thanks for bug report, I'll take a look.

**Comment by alexisargyris** [comment]
I am on Windows v0.24.5 and "drag-and-drop" doesn't seem to work either: the cursor icon changes from a pointer to a "do-not-enter" sign as soon as I start moving. However "cut-and-paste into" works normally.

**Comment by zadam** [comment]
@alexisargyris is right that this bug was not specific to mac - it affected all platforms. Should be fixed in 0.25.1-beta

**Comment by cadorn** [comment]
Confirmed that it is fixed in 0.25.1-beta. Thanks!

**Comment by alexisargyris** [comment]
Works fine now! Looks nice too!
