### ISSUE TITLE
(Feature request) Monaco instead of CodeMirror?

### ISSUE THREAD

**Issue by mnpenner** [zadam/trilium#2521]
### Describe feature

Would it be possible to use [Monaco](https://microsoft.github.io/monaco-editor/) instead of CodeMirror? This is basically what VSCode uses and its quite nice.

**Comment by zadam** [comment]
Hi, Monaco is more geared towards IDE-like experience and is correnspondingly heavier than CodeMirror.

Since Trilium has no ambition to be an IDE, CodeMirror fulfills our need quite well.

**Comment by mnpenner** [comment]
That's fair. I mostly intent to use it for pasting in code snippets, not coding directly in there. Thanks for the response!

**Comment by Wingysam** [comment]
Would it be possible to implement this with a user-made code note? It could possibly watch for CodeMirror and replace it with Monaco.

It would be complex but I use Trilium as an IDE for my blogging backend.

**Comment by zadam** [comment]
It would be probably technically possible but I wouldn't recommend it.

**Comment by Wingysam** [comment]
I see, CodeMirror handles indentation slightly differently than Monaco, but I think a simple auto-format-on-edit script would do the trick.
