### ISSUE TITLE
(Feature request) Extend code editor to bottom of page?

### ISSUE THREAD

**Issue by mnpenner** [zadam/trilium#2522]
### Describe feature

Just trying out Trilium for the first time. I'm finding it a bit unintuitive that the code editor box is so tiny, and there's no border around it either so I can't tell where I'm allowed to click.

![image](https://user-images.githubusercontent.com/1112998/148325400-4bb52aba-c83c-4b47-a9d1-172e2b2c8475.png)

Can the editor be expanded all the way down to the bottom of the page so there's a bigger click target, and add borders around click-targets? I think this would really improve accessibility.

**Comment by zadam** [comment]
Hi, thanks for bringing my attention to this - I agree that it's not ideal.

I have fixed the height issue so you can click on the whole height and the editor/cursor will get focus. I also added placeholder for code notes which should help a little bit as well:

![image](https://user-images.githubusercontent.com/617641/148597205-83cebec3-31f6-4ded-9c75-ad4c3281ac57.png)

These changes are in the 0.50 branch.

**Comment by thfrei** [comment]
FYI: I used thise feature to make canvas-note fullscreen. https://github.com/thfrei/trilium/commit/5da6dec4b1a595990e1095180e054895a4c4660b
