### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#2523]
### Trilium Version

0.49.2-beta

### What operating system are you using?

Other (specify below)

### What is your setup?

Local + server sync

### Operating System Version

win11 client ubuntu 21.04 server

### Description

New install.  I have 49.2-beta on client and just downloaded the 49.2-beta on the server.  Start with trilium.sh.  When I set client sync and test I get:

![image](https://user-images.githubusercontent.com/1071479/148395830-74c151aa-251f-408d-8ea6-bcbecf8e9d2d.png)

the output on startup says:

```
App HTTP server starting up at port 8080
{
	appVersion": "0.49.2-beta",
	"dbVersion": 188,
	"syncVersion": 23,
	"buildDate": "2022-01-02T22:43:30+01:00",
	"buildRevision": "feffd57f240438d107c1ed1c1772545611a97dee",
	"dataDirectory": "/home/user/.local/share/trilium-data",
	"clipperProtocolVersion": "1.0"
}

```

on the client about trilium says:

![image](https://user-images.githubusercontent.com/1071479/148396605-844d95e9-9c53-49ba-8192-f7d11b20af9a.png)

I have a port forward from 999 on client machine to 8080 on server.  Works fine from browser.

**Comment by zadam** [comment]
Hi, I think you have some problem with the upgrade/routing.

Sync version 22 is 0.48.X.
