### ISSUE TITLE
(Feature request) Add order number for toolbar buttons.

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2525]
### Describe feature

I created some buttons with `api.addButtonToToolbar`, and want to make a certain button to the last one in the bottom. However, I did not find any way to reorder the buttons.
I am wondering if it's possible to add a order number for the buttons so that I can control their position.

**Comment by zadam** [comment]
I agree this is missing currently, but I'm also not sure what approach would be the best here. I have to think about this.

**Comment by zadam** [comment]
Configuration / reordering is part of (unreleased) v0.58.
