### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by cleverestx** [zadam/trilium#2527]
### Trilium Version

0.49.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 version 21H1 (Trilium is running on a Synology NAS w/ DSM 7)

### Description

Upon the first launch after building Trilium with Docker-Compose on my Synology NAS, I set the username and password through the wizard after choosing the top option, and then it fails to log me in on the very next screen, telling me in the logs that it is the wrong username/password. If I disable auth from the config file, then it loads fine. If I try to enable/change the password in the IT after that, it tells me I am using the wrong current password, no matter what I try (empty or the old one I tried before I disabled auth).

**Comment by zadam** [comment]
Hi, is it possible you had caps lock or something?

If your setup is completely new, could you remove the `trilium-data` and simply try from scratch again?
