### ISSUE TITLE
(Bug report) Icons broken

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#2529]
### Trilium Version

0.49.3

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Linux myzel394-computer 5.15.0-2-amd64 #1 SMP Debian 5.15.5-2 (2021-12-18) x86_64 GNU/Linux

### Description

While upgrading from `0.48.9` to `0.49.3` all icons are now shuffled. Here's a screenshot of the sidebar:

![image](https://user-images.githubusercontent.com/50424412/148654141-00c54a7a-cc71-49ac-a64f-e111151b69c7.png)

**Comment by zadam** [comment]
You might want to clear the cache (CTRL-F5).

boxicons have been upgraded and the font character IDs have changed (class names stay the same).

**Comment by Myzel394** [comment]
Thank you, that worked! If anyone is also facing this issue on **Firefox**, you can use this guide: https://superuser.com/a/733154
