### ISSUE TITLE
(Bug report) (node:34706) UnhandledPromiseRejectionWarning: Error: Note title must not be empty

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2530]
### Trilium Version

0.49.3

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Fedora

### Description

```
(node:34706) UnhandledPromiseRejectionWarning: Error: Note title must not be empty
    at Object.createNewNote (/var/home/matt/Downloads/trilium-linux-x64-0.49.3/trilium-linux-x64/resources/app.asar/src/services/notes.js:106:15)
    at saveNote (/var/home/matt/Downloads/trilium-linux-x64-0.49.3/trilium-linux-x64/resources/app.asar/src/services/import/zip.js:382:35)
    at /var/home/matt/Downloads/trilium-linux-x64-0.49.3/trilium-linux-x64/resources/app.asar/src/services/import/zip.js:486:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
When importing, blank named notes fail. However, these can easily be created from within Trilium without issue, it's only when importing do I encounter a problem

**Comment by sigaloid** [comment]
Manually editing meta.json (replacing `"title": ""` with `"title": "something"`) and re-zipping did the trick for me, but it doesn't seem to have fully imported right after I re-zipped it back up. 
![Screenshot from 2022-01-08 13-10-09](https://user-images.githubusercontent.com/69441971/148654953-df5d3e69-f7b1-454d-a3f8-247c6b71056e.png)
I remember seeing something about this on the tracker before.

**Comment by zadam** [comment]
Hi, you're right, import should be consistent with the UI, fixed.

**Comment by sigaloid** [comment]
Thanks :heart:
