### ISSUE TITLE
(Bug report) In shared note, parent link doesn't link with shared alias link

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2535]
### Trilium Version

0.49.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora

### Description

When clicking a note in the tree, the URL (with the shareAlias'd custom URL) is returned. However, when in a child note, the parent note button returns the note ID. 

It looks like a discrepancy in share.ejs and tree_note.ejs where in the former, the note ID is used to form the URL, whereas in the latter, it uses the correct share alias.

**Comment by zadam** [comment]
Hi, thanks for report, fixed.
