### ISSUE TITLE
(Feature request) Automatically sync after sharing/unsharing note

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#2539]
### Describe feature

Currently we need to manually sync or wait for the next sync in order for the 'shared' public url to work. It would be nice if a sync was automatically triggered on the note when it is shared/unshared.

Steps to reproduce:

- Create a shared note
- Click public link
- "Not Found" will be displayed when opening the link.
- Trigger manual sync
- Try to re-open the public link
- Note will be be visible as expected

**Comment by Nriver** [comment]
Had to manually sync before open the link! No wonder I couldn't get my test note shared, I thought it was my network issue.

**Comment by zadam** [comment]
Hi, yes, that makes sense. Fixed.
