### ISSUE TITLE
[macOS] ctrl vs command in shortcuts

### ISSUE THREAD

**Issue by Vykook** [zadam/trilium#254]
On macOS it's common to use command key(for example cmd+v for paste), but in Trilium it's control as on another platforms.

**Comment by zadam** [comment]
I see, I'm not familiar with Mac. Is it then expected that these common shortcuts (C, X, V, Z, Y, A) work with both CTRL and command key?

**Comment by zadam** [comment]
Both CMD and CTRL keys work now.
