### ISSUE TITLE
widget (word count) doesn't work

### ISSUE THREAD

**Issue by NiuXZi** [zadam/trilium#2541]
### Trilium Version

0.49.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 21H2 22000.376

### Description

I cannot see the widget (word count) in my note. I use trilium before and upgrate to latest version.
![image](https://user-images.githubusercontent.com/61132813/148900807-d282046e-ee4b-48f5-91ff-40d5626df83c.png)

**Comment by Nriver** [comment]
Did you add `#wordCount` label to your note? It works for me.

**Comment by rebron1900** [comment]
You need add tag `word count` to your note lable

**Comment by NiuXZi** [comment]
> Did you add `#wordCount` label to your note? It works for me.
I do. I also cannot see it.
![image](https://user-images.githubusercontent.com/61132813/148922205-1b77e37b-66ec-40e9-a24a-93c1354b8cac.png)

**Comment by rebron1900** [comment]
@NiuXZi Did you use a custom theme? Try switching back to the default theme

**Comment by NiuXZi** [comment]
> @NiuXZi Did you use a custom theme? Try switching back to the default theme

The theme I use is the default
![image](https://user-images.githubusercontent.com/61132813/148946980-fc87a91e-d82a-4636-9e73-6410b1fd11b3.png)

**Comment by zadam** [comment]
Hi, thanks for reporting this.

I think you used the widget from [wiki](https://github.com/zadam/trilium/wiki/Custom-widget) and it looks like it was slightly broken.

I've updated it, so just copy it from wiki again (and don't forget to reload).
