### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by Rigel772** [zadam/trilium#2548]
### Trilium Version

0.48.9

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Linux Manjaro KDE

### Description

Hello there,
I am not sure if it is actually a Trilium bug, but on my Manjaro KDE system Trilium window has no border.
The app window blends with window beneath, please see the picture:
https://i.imgur.com/GpwQ48v.png
There are 3 windows: Thunderbird at the bottom, Dolphin in the middle and Trillium on top...
The Trilium window is the active on and completely blends in...
Is it possible to make it behave like other windows

**Comment by zadam** [comment]
Hi, by default sind DE decorations disabled, you can enable them here:

![image](https://user-images.githubusercontent.com/617641/149570583-9cbab0f5-b572-4bd2-82fc-48867c9aa01f.png)

Then Trilium has a title bar, drop shadows (depends on the DE):

![image](https://user-images.githubusercontent.com/617641/149570695-c61f950f-6bfe-4ebd-9e2a-3d80bd82f0ec.png)

**Comment by Rigel772** [comment]
Strange, I had the native title bar setting set to "enabled" but the app looked like in the screens I posted. It took to set it to disabled, close app, set to enabled, close app and then I do have the bar and drop shadow.
Thanks
