### ISSUE TITLE
(Bug report) Export & Print Note, dose not export/print promoted fields

### ISSUE THREAD

**Issue by TMS-Namespace** [zadam/trilium#2550]
### Trilium Version

0.49.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Win10, 21H1, 19043.1415

### Description

(I did a quick search, it seems no one reported this before)
Printing, or exporting the note, prints\export only the main section of the note, and totally ignores the prompted fields, that actually could be a key thing in this note.

**Comment by zadam** [comment]
Hi, that's true. I think it's an omission from the big frontend refactoring in 0.48.

I added a simple overview of promoted attributes to the printed page, but it looks different from the editing page.
