### ISSUE TITLE
HTML Export - Render Issue

### ISSUE THREAD

**Issue by Epod** [zadam/trilium#2555]
### Trilium Version

latest

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

WSL2 (Ubuntu) - Docker

### Description

When exporting notes using HTTP - the .zip file it generates contains a "Global Note Map.bin" file with 0 KBs. 

When you open "index.html", every time it just downloads this blank "Global Note Map.bin" file

![image](https://user-images.githubusercontent.com/49006/149599740-cfd1def3-aa56-467a-ac15-bee06d0e7bce.png)

**Comment by zadam** [comment]
Hi, thanks for report. These notes should not be in the export at all. Fixed.
