### ISSUE TITLE
Upgrading from an old version (0.47.7 -> 0.49.5)

### ISSUE THREAD

**Issue by Mirwaisse** [zadam/trilium#2558]
My Trilium installation is still on version 0.47.7 (DB version: 183).

Can I upgrade directly to version 0.49.5 (DB version: 189)? Or is there a specific "upgrade path"?

I'm asking since I saw that to upgrade to 0.48.X, you first have to be on version 0.47.X. I was wondering if there were any other rules like that.

Thank you!

**Comment by zadam** [comment]
Hi, no, you should be able to upgrade directly. Please report back if you have any problems.

> I'm asking since I saw that to upgrade to 0.48.X, you first have to be on version 0.47.X.

This was an exception, because of the large scale changes in 0.48. But otherwise you should be able to upgrade from older versions.

**Comment by Mirwaisse** [comment]
I upgraded and I haven't noticed any problems as of now, so I'm closing this issue.

**Comment by ashleysommer** [comment]
I did the same upgrade yesterday, but I didn't read this, I did an intermediate version.
I did 0.47.7 -> 0.48.9 then -> 0.49.5
That worked as expected without issue too.

**Comment by Mirwaisse** [comment]
If you don't mind me asking, why did you also wait so long before upgrading? In my case, it's because I still prefer by far the old design, but we have to upgrade anyway at one point or another to benefit from update/bug fixes, so I finally decided to do it...

**Comment by ashleysommer** [comment]
Oh, it's because I am just coming back to trilium now, after trying some alternatives for 6 months. I started trilium, and thought "this is a pretty old installation, I should check if there has been any updates". And yes, there had been a _lot_ of updates.
