### ISSUE TITLE
App-level password

### ISSUE THREAD

**Issue by ghost** [zadam/trilium#256]

**Comment by zadam** [comment]
Username and password are used to encrypt/decrypt "protected notes" and it's also used for logging into the web application.

What you want to achieve is not supported use case but there is a workaround - if you protect root note, then all its children will be protected by default as well, thus in effect having everything protected (encrypted). Opening the (desktop) app itself is not guarded by password, but then if all the notes are protected (and unreadable), then the effect is more or less the same.
