### ISSUE TITLE
DB Not Initilized - Local Set up

### ISSUE THREAD

**Issue by sunflowerno0b** [zadam/trilium#2563]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

hi,

attempting to load the trilium data log, but its not working. the log files are empty. I pulled up the latest release found [here](https://github.com/zadam/trilium/releases/tag/v0.49.5), 0.49.5. I keep getting DB not initilized. I am including a screenshot of my output. I tried to search the other issues that might match but they all seem to be on the server.
![Uploading Screenshot from 2022-01-15 13-26-24.png…]()

**Comment by zadam** [comment]
Hi, the screenshot is not available.

Also, what's the context? Is it a new installation? If yes, then the message is OK and you need to go through the setup process. Is it desktop or server?

**Comment by sunflowerno0b** [comment]
hi,

sorry about that- attaching again. this is a fresh install on my local computer, not the machine. I was having issues so I attempted to follow this guy: [here](https://www.youtube.com/watch?v=J8RAihtij0s) but once i managed to get past the no sand box i got the DB issue.
![Screenshot from 2022-01-15 13-26-24](https://user-images.githubusercontent.com/68705196/149683703-bf9027ce-e478-49bc-b1dc-8a621aa5c9df.png)

**Comment by zadam** [comment]
Okay, so the problem is that the setup window is not coming up. I'm not sure why, but it could be connected to the fact you're running it as root. I would recommend to run Trilium under a normal user, as is standard practice.

**Comment by sunflowerno0b** [comment]
I've run it as user several times, as standard practice and then went to root to attempt as a final resort. I'm attaching screenshots here - you can see that root is the owner as the output says and still the same error.
![Screenshot from 2022-01-17 15-38-31](https://user-images.githubusercontent.com/68705196/149835124-5a5d180e-1d8c-4ee6-bc5f-26fa0a2a2805.png)
![Screenshot from 2022-01-17 15-38-06](https://user-images.githubusercontent.com/68705196/149835134-6a29519f-2177-4308-973d-e9092570ff7e.png)

**Comment by zadam** [comment]
What you're showing is that the directory is owned by the root, but the error message complains about `chrome-sandbox`.

**Comment by sunflowerno0b** [comment]
Correct but by root owning the directory - recursively all files inside are owned by root - not at my computer now but I checked and root does in fact own chrome sandbox. 

--
-A.

**Comment by sunflowerno0b** [comment]
anyone have tips, i'd like to get this running to move out of my mac - since its unsupported.
