### ISSUE TITLE
(Bug report) Keystrokes lost when tabbing out of title quickly

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2566]
### Trilium Version

0.48.9

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop!_OS 21.10

### Description

Create a new page, start typing the title, then quickly Tab out of it and start writing the body.

If you do this too quickly, some of the last keystrokes in the title will be lost.

See video: https://www.youtube.com/watch?v=blJP_wUO2Do

**Comment by zadam** [comment]
Hi, thanks for reporting, unfortunately I can't reproduce it in 0.48.9 or later. But there has been already such bugs in the past.

I'm wondering if it's also reproducible without the Tab.

Is this the desktop or server?

Also, just to make sure, you don't have any scripts listening on note's changes, right?

**Comment by agentydragon** [comment]
This is the desktop client. I will later check if this also happens in the
server when opened as a webpage.

I do have some custom JS that might be interfering - a custom component
that should not be rendering in this note. I'll try turning it off and
report back. Thanks :)

**Comment by agentydragon** [comment]
This also happens when I access the server as a webpage in my browser. Turning off my custom `#widget`s did not fix this. I do have some scripts listening on attribute changes on some notes, but those notes I'm trying it on don't have that script attached - I create them anew with `Ctrl+Alt+P` with no scripts attached by relations.

**Comment by zadam** [comment]
Thanks, I was able to reproduce this and fix it. The missing part for me was that to reproduce it you need to switch to content and write (quickly after switching). Before I was doing just the Tab which alone does not suffice.

**Comment by agentydragon** [comment]
Thanks for solving this so quickly <3
Looking forward for a release with the fix
