### ISSUE TITLE
Support for custom fonts

### ISSUE THREAD

**Issue by vballworld** [zadam/trilium#257]
It'd be great if users can choose the font of choice.

P.S. This is so great. Really would love to see this become the "VS Code" of note taking! Keep going!

**Comment by vballworld** [comment]
@zadam btw, just realized the css customization which is super awesome for us tech folks! However, for mass adoption, I still think it'd be necessary for a more non-techie friendly way to customize the fonts.

**Comment by zadam** [comment]
Hi, I plan to work a bit on the design in the next iteration and I can think about letting users choose fonts as well.

**Comment by vballworld** [comment]
@zadam btw, what's the css tag for the note titles on the left side nav panel? Everything under >> root? I'd like to make just those fonts a bit bigger & couldn't find it in the source code. Thanks!

**Comment by zadam** [comment]
You can use following code to use the same font size as the rest of the app which is a bit larger:
```
ul.fancytree-container {
    /* override specific size from fancytree.css */
    font-family: inherit !important;
    font-size: inherit !important;
}
```

You can also press CTRL-SHIFT-I to open dev tools and look into the HTML structure.

**Comment by vballworld** [comment]
Ah, the CTRL SHIFT I is perfect. Thanks!

**Comment by zadam** [comment]
First thing is that code block isn't actually in element "code", but in div with class .CodeMirror. Also it would make sense to use !important directive. Something like this:

```css
.CodeMirror {
    -webkit-font-feature-settings: "liga" on, "calt" on !important;
    -webkit-font-smoothing: antialiased !important;
    text-rendering: optimizeLegibility !important;
    font-family: 'Fira Code' !important;
}```

**Comment by linonetwo** [comment]
Oh, by using `.CodeMirror` I can change the color of text, so it's working.

But I still can't get that font working, though it is installed on my Mac and works in VSCode.

Can you enable developer tool in the production, just like what VSCode does? It will make this kind of style tweaking easier.
<img width="603" alt="2019-01-14 12 18 44" src="https://user-images.githubusercontent.com/3746270/51087730-fdf68880-1791-11e9-9274-0c5e5f291716.png">

**Comment by zadam** [comment]
Dev tools are enabled, just press CTRL+SHIFT+I to open them.

**Comment by zadam** [comment]
It is possible to define custom fonts in the theme - example is in "Steel Blue" theme provided in the demo document.
