### ISSUE TITLE
Note lost when converting from "text" to another Type

### ISSUE THREAD

**Issue by vballworld** [zadam/trilium#258]
When an existing note is converted from "text" to another Type, the existing note contents are completely lost/unrecoverable.
Note contents should persist through type changes unless user explicitly deletes it. Could lead to bad situations where user loses all note contents through an inadvertent type change.

**Comment by zadam** [comment]
Hi, I'm aware that the workflow here is a bit awkward. The assumption is that note type change happens mostly right after creating the note or later only when the note is empty. It doesn't really make much sense to change the type of a note which already has some content. But as you say this might happen accidentally or just as part of exploring the application.

But this problem should be mitigated by the fact that changing the note type doesn't actually change the content at all. It is then possible to change the note type from text to code and then back and there's nothing lost (there's no conversion of content or any other change to content) as long as you don't change the note (by e.g. editing the code). Even if you manage to destroy content this way, it might still be partially recoverable from note revision (depends on some factors though).

Having said that I did actually try what I describe above and there is one bug - changing the type to relation map will immediatelly change the content to expected format which will destroy previous content - I'll fix that.

**Comment by zadam** [comment]
No change planned for this, but there is a warning if the note type is changed while not being empty.
