### ISSUE TITLE
(Bug report) Can I use multiple clients?

### ISSUE THREAD

**Issue by theryecatcher** [zadam/trilium#2587]
### Trilium Version

0.49.5

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Server on Ubuntu, local installation on Debian, desktop client on Arch Linux

### Description

Hello,

First of all thanks for this piece of brilliant software. I have been using it for quite some time now with a local network instance hosted on Debian accessed using web frontend and a sync instance on a public server behind a reverse proxy. Everything is working great in this setup.

 I recently wanted to setup a desktop client too and tried to init the client with the sync data from the server with correct username and password but it keeps on failing with the below error. Could you kindly help in clarifying if I can have multiple clients and one server instance and if so what could possibly be going wrong in this case. A snapshot of the error.

```
Getting document options FROM sync server.
ERROR: Sync failed: Request to get https://blah/api/setup/sync-seed failed, error: 401 
Slow 200 POST /api/setup/sync-from-server with xxx bytes took xxms
ERROR: Failed to deserialize sync response: Incorrect username and/or password
```
And this keeps on repeating. I have tried even changing the password with no avail.

**Comment by zadam** [comment]
> Could you kindly help in clarifying if I can have multiple clients and one server instance...

Hi, sure, that's actually the typical case.

> ... what could possibly be going wrong in this case

It is what the error says - either username or password is wrong. If you managed to change your password, then you did not forget it, and it has to be the wrong username. 

But in any case, there's a simple workaround - just copy the [`trilium-data` directory](https://github.com/zadam/trilium/wiki/Data-directory) from your first client to a different client (again consult the wiki page where the app will expect the directory), and the app on the second client will just work including the sync.

**Comment by rebron1900** [comment]
也许你还需要更改监听端口
You may also need to change the listening port

**Comment by theryecatcher** [comment]
![image](https://user-images.githubusercontent.com/16442416/154814229-9854741a-889a-404a-b4ba-f21da0b63fb1.png)

Still not sure what I am doing wrong. 

I tried the suggested copy the data directory too but the app still starts up and asks for the server instance (x3) options. Now I do not even see the username field. Could you kindly help as you find some time. One thing of note the server sits behind a reverse proxy but I do not if it's affecting as the db seems to be downloaded to the desktop machine and fails at the decryption. I can login with the same username and password on both the server instance and also the local web hosted instance.

**Comment by theryecatcher** [comment]
Ahh kindly ignore the issue I have been naive and using different (very old version for the server) reinstalling the latest release on all the clients and the server resolved this issue. Thanks again for all the work and efforts to help me out.
