### ISSUE TITLE
Ability to store notes as plain text (folder structure), instead of inside DB

### ISSUE THREAD

**Issue by rogierlommers** [zadam/trilium#2590]
### Describe feature

What do you think about the ability to store the notes in plain text (markdown files) instead of inside a database? For portability reasons it's way better, right? Also the notes could be index by tools like Alfred and spotlight.

**Comment by Mirwaisse** [comment]
https://github.com/zadam/trilium/wiki/FAQ#why-database-instead-of-flat-files

**Comment by rogierlommers** [comment]
Ah sorry :).
