### ISSUE TITLE
(Bug report) Data Loss, Synchronization Failure, Server/Client Mismatch, Crashes

### ISSUE THREAD

**Issue by cwilliams5** [zadam/trilium#2591]
### Trilium Version

0.49.5

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Multiple

### Description

Just found Trilium, was super impressed, spent the last week migrating everything over - and now its blown up. Worked on layout, importing, building data for >6 hours yesterday. Client was open and synched, woke up to client failing to sync, "recovered" files, data loss, and server/client data mismatch.

Server: Latest Official Docker
Clients: Win 10 PC, Win 11 Laptop, Android via Browser

Screenshot:
This screenshot will show multiple issues discussed below. Windows client on right, server on left. 
![trilium_failure](https://user-images.githubusercontent.com/10100743/150897333-ba6eaf7d-0ce7-45b2-a849-6a03e85cb720.jpg)

Events:

1. Busy day of lots of Trilium work - importing hundreds of documents, copy and pasting, building relationship graphics, deep hierarchies, etc. Lots of syncs throughout the day. Lots of client restarts while developing a theme. Notice at end of day Windows client is fully synced. Left client/computer open, went to sleep.
2. Next morning, client appears as above on the right. The top set of blurred notes are people that were placed in the people tree( created as child notes even), not sure why they are not in the proper tree anymore. The "image" belongs to a now unknown onenote record that was pasted in deep in some subtree. The bottom blurred box is all Recovered -- XXXX documents. Most of these are * and clones of existing documents, but some are not, representing notes that are no longer in their original spot.   (No picture of this) but sync button would spin forever, error out and say something like sync status would be available on next sync click to sync. Clicking recreated wait, timeout, error loop.
3. In a panic, right click on root node "Life" and select export, this note and all descendants, HTML - application crashes. 
4. Navigate to %appdata%\Roaming and immediately backup "trillium-data" and Trillium Notes.
5. Restart Windows application, attempt to sync. Syncing still fails as above.
6. Exit application and delete trillium-data and Trillium Notes from %appdata%\Roaming. 
7. Launch Trillium and set up "as new" to sync from server- it syncs and comes up as in picture on the right. So still messed up, but the syncing error is gone, and it appears to sync fine.
8. Repeat steps 5-7 on laptop. Same broken sync, same messed up display, only deleting data and resetting up restores sync to work but data still messed up.
9. Checked the non client server directly via https, surprised to see something totally different. The above screenshot shows how the server looks, and a freshly synced client from scratch looks. Note that while the server has all the "recovered" nodes, the extra nodes above are gone. More worringly, the "People" tree is completely gone. Yet if I install a new client on a PC and sync to this server, the "People" tree comes in the sync....so its in the server, but not in the webview? How is that?
10. Lastly, I can still freeze the client on demand by selecting right click on root node "Life" and select export, this note and all descendants, HTML. UI will freeze, process manager shows pegged to 25% cpu (so 1 full core) and memory use jumping wildly between 400-800 megs. I left if like this for 5 hours today and it never recovers or changes form this state. 
11. Just found another broken thing - the mobile interface does not load. Tested in Chrome and Firefox across multiple devices and networks. Just a blank dark screen. If I use a new device or force a new session, I am challenged for a working login screen, after that, back to the blank page. It was working perfectly before things got so messed up. 

So, yeah, borked. Why did any of this happen? Under what circumstances is a "recovered" note created? Why do the server and client no longer match? How can I fix these many errors? How do I know I don't have additional data loss not covered by "recovered" files? How do I prevent this from happening again? 

I don't know what further I could give you for logs or dbs or whatever to troubleshoot, just ask and I'll gather it. 

** EDITED to add issue 11 to above list **

**Comment by zadam** [comment]
Hi, I'm sorry you had such a bad experience.

I see you mentioning logs, but there are none attached.

I would appreciate if you would ZIP all logs from both client and server and send them to me to zadam.apps@gmail.com

Additionally, it would really help me if you could create an [anonymized database](https://github.com/zadam/trilium/wiki/Troubleshooting#anonymized-database) on both client and server (as seen on the left and right screenshot) so that I can compare these 2 DBs and logs.

With that I should be able to reconstruct what went wrong and hopefully fix the issues.

Thanks!

**Comment by cwilliams5** [comment]
> Hi, I'm sorry you had such a bad experience.
You are too kind. I know of course as open source it has no warranty or guarantee. It was very frustrating, but I can tell you have pride in this product so wanted to give you everything you need to improve it by resolving these issues. 

> I see you mentioning logs, but there are none attached.
I wasn't sure what exactly you needed so was prompting for your needs. 

> I would appreciate if you would ZIP all logs from both client and server and send them to me to [zadam.apps@gmail.com](mailto:zadam.apps@gmail.com)
Logs from client and server delivered as requested.

> Additionally, it would really help me if you could create an [anonymized database](https://github.com/zadam/trilium/wiki/Troubleshooting#anonymized-database) on both client and server (as seen on the left and right screenshot) so that I can compare these 2 DBs and logs.
Server anonymized DB delivered (had to learn some docker and linux to extract them, a few lessons there for me xD)

Client DB refuses to create anonymized giving below error.
![image](https://user-images.githubusercontent.com/10100743/151302425-ab9ada0f-bab2-4e77-b12b-24beadb469d2.png)

> With that I should be able to reconstruct what went wrong and hopefully fix the issues.
I appreciate your time. 

As listed above I cannot make a client anonymized database due to another new error. If you need the full, I'd be willing to share if it helps you here. I also have a daily backup that the client appeared to generate the night before, AFTER my multi-hour edit session but BEFORE the synchronization failure/disaster. I also have a backup I created as soon as the failures were experienced. If any of these, or anything else I can provide, would be of help just let me know. You have my email now as well. 
 
> Thanks!
Thank you. I was very impressed with Trilium. It's hierarchical design, cloning, server/client, clipper, etc, all really matched me and what I needed. Hopefully these bugs can be fixed and I can restore confidence in it. Either way its an impressive product, well done. I have a list of feedback being built xD

**Comment by zadam** [comment]
Hi, thank you, I have received your email with the attachments.

I will first try to analyze the logs and one anonymized DB. It is possible that the original DB would be needed, in that case I will write you an email.

**Comment by cwilliams5** [comment]
I'm closing this as its really not a specific issue. For the record everyone, zadam and I have been in contact over email (due to the private nature of my database). He has been debugging my databases and discussing things with me. At least one of these issues has been fixed in a new version, others are under investigation, and some may never be explainable. His response and commitment to improve Trilium couldn't be better.
