### ISSUE TITLE
(Bug report) cannot access etapi in server

### ISSUE THREAD

**Issue by N4v41** [zadam/trilium#2600]
### Trilium Version

0.49.5 docker latest

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

linux ubuntu 20.04 docker container ARM64

### Description

hi, i can't figure out how to access the etapi in trilium notes server, trying to autenticate i got the error:
```
{
    "message": "Router not found for request /etapi/auth/login"
}
```

**Comment by zadam** [comment]
Hi, ETAPI is available only since 0.50 (currently in beta).
