### ISSUE TITLE
Question: Two different local instances sync

### ISSUE THREAD

**Issue by ArisKallergis** [zadam/trilium#2602]
Hello! 
I recently managed to setup a cloud installation of Trilium. 
Before that, I had one local instance for work, and one at home. 

I used sync from my home installation, and everything worked as (intuitively) expected.
What will happen now if I try to sync from my work machine? 
Will it overwrite everything on the remote server? Will it overwrite everything on the local machine? 
Will it merge (which I find unlikely) ?

**Comment by zadam** [comment]
Hi, directly trying to sync your work instance with the server (which contains the home data) won't work, it will get rejected. You will need to merge the data manually:

1) export data from your work instance into ZIP
2) run a clean (empty) instance on your work machine and setup sync with the server, this will sync your home content into the work instance. To make an instance empty, move `trilium-data` folder into some backup, Trilium then won't find it and consider it as initial setup.
3) you can import the ZIP with your work data.

![image](https://user-images.githubusercontent.com/617641/151713753-ea8d6d81-98af-4011-8019-6235e4201e5d.png)

**Comment by ArisKallergis** [comment]
Nice! Many thanks!
