### ISSUE TITLE
(Feature request) Make "open attribute list" shortcut put focus into the attribute list

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2606]
### Describe feature

Idea for a slight improvement of ergonomics. When I use the "open owned attributes" shortcut (`Alt+A` for me right now, not sure whether that's the default), I usually want to type in something. My workflow is often:

* Create a page
* Eventually want to give it a template (e.g., issue, paper)

It would save me a tab or two if I could just use `Alt+A` to open the attribute list and then I could immediately start typing `~tem<Tab>=@` etc.

### Additional Information

I think there could be a similar improvement to the "promoted attributes" shortcut.

**Comment by zadam** [comment]
Hi, yeah, that makes sense, implemented.
