### ISSUE TITLE
(Feature request) ETAPI: Change /create-note to POST /notes

### ISSUE THREAD

**Issue by mikkel1156** [zadam/trilium#2611]
### Describe feature

For most REST like APIs it's standard to have a endpoint accepting a POST request for creating new resources, that is the same for all other CRUD oeprations. All other note related functions are already using `/notes` so adding a POST one to this makes sense and more in-line with most other APIs.

**Comment by zadam** [comment]
This was intentional - neither input nor output of this service is a `Note` entity. This endpoint is RPC style method, that's why it has RPC style naming.

**Comment by mikkel1156** [comment]
Any reasoning for that then? Just seemed unintuitive for it to be a different style endpoint. Even more so when the output is _almost_ the same as with `GET /notes/{noteId}`.

Feel free to close this issue.

**Comment by zadam** [comment]
It's because creating a note creates two entities - Note and Branch, both of these need to be configured by the client and returned to the client.

REST is primarily a data oriented service modelling style and more complex operations do not map well into it.
