### ISSUE TITLE
(Bug report) JS script crashes Trilium

### ISSUE THREAD

**Issue by zvelasquezb** [zadam/trilium#2614]
### Trilium Version

0.50.1

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Linux lite

### Description

Hy, i just added a few lines of html and js with a "hello world" and then trillium keeps displaying this hello world without giving me any other option
![Captura de pantalla_2022-02-05_22-03-31](https://user-images.githubusercontent.com/37085970/152666225-94670fe3-1281-4677-b229-2762f8a3ed60.png)

**Comment by zadam** [comment]
Hi, can you post the example JS script? It looks like it replaces the whole DOM which messes up the application.

You can fix that by running Trilium in "safe mode" by running application with `trilium-safe-mode`.

See https://github.com/zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup for details.

**Comment by zvelasquezb** [comment]
Code :
<script>
  document.write("Hola Mundo");
</script>

**Comment by zadam** [comment]
Yeah, this API is ancient and not used anymore because it overwrites the whole DOM, thus crashing the application. JavaScript has no sandboxing, so you must be careful when playing with scripts.
