### ISSUE TITLE
(Bug report) ETAPI token add and delete issue

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2616]
### Trilium Version

0.50.1

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Manjaro

### Description

I tried to create a ETAPI token with a fresh Trilium data in portable mode with only desktop client, no sync. Several issues happend.

1. When creating an api key, the second step(copy to clipboard stuff) is somehow get skipped. One click on ok in the first setp will cause Trilium to reload.
 
2. After reload, there will be two duplicated items in ETAPI token page. They seem to be the same data, as they have the same time. And if I change one name, the other will also change.
![image](https://user-images.githubusercontent.com/6752679/152734295-fad75f00-f8eb-4e3a-a277-fd3e551634a2.png)

3. Delete button will make a prompt but no token can be deleted.

**Comment by zadam** [comment]
Hi, thanks you for reporting. The UI was pretty buggy, yeah :-(
