### ISSUE TITLE
(Bug report) Cannot find "Upload file" options

### ISSUE THREAD

**Issue by ibnishak** [zadam/trilium#2619]
### Trilium Version

0.50.1

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Arch Linux Rolling Update

### Description

Cannot find the `upload file` option mentioned here

https://github.com/zadam/trilium/wiki/Images#compression

> If you want to save images in their original resolution, it is recommended to save them as attachment to note (top-right "Note actions -> Upload file").

**Comment by zadam** [comment]
The item is now called "Import files":

![image](https://user-images.githubusercontent.com/617641/152878625-a41f9e6c-7315-4aa6-943d-d48960e4a31f.png)
