### ISSUE TITLE
(Bug report) DWG files get lost after uploading

### ISSUE THREAD

**Issue by bbappyuanyuan** [zadam/trilium#2628]
### Trilium Version

0.50.1

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 20.04

### Description

Uploaded *.dwg files recognized as image and zero file size. When I download it, I get file with 0 size, i.e., the file get lost. Testing object: http://www.manufacturinget.org/wp-content/uploads/2011/07/mpgbylayers.dwg

**Comment by zadam** [comment]
Hi, thanks for reporting this bug. Trilium recognizes this file as image and tries to process it, but fails at that. Fixed.
