### ISSUE TITLE
(Feature request) Mermaid diagrams need Zoom and Pan.

### ISSUE THREAD

**Issue by cwilliams5** [zadam/trilium#2635]
### Describe feature

It's hard to make anything but a small diagram. The zoom, pan, and reset controls (and the way the note remembers previous view) from relationship maps are probably a great fit here.

**Comment by zadam** [comment]
Implemented in master, will be in 0.51

**Comment by jbertagn** [comment]
> Implemented in master, will be in 0.51

I'm seeing that this pan and zoom has been implemented, but I'm having trouble finding any documentation on it (?). Could someone please point me in the right direction to enable pan and zoom for graph?
