### ISSUE TITLE
(Feature request) Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [zadam/trilium#2638]
### Describe feature

I am not sure whether this can be considered a feature request or not. This project is currently missing the **Code of Conduct** which defines the standards for how to engage in a community. If you are interested in adding that, then I can add a PR with that.

Please let me know what do you think about this.

### Additional Information

Nothing

**Comment by zadam** [comment]
Hi, I just created one, see https://github.com/zadam/trilium/commit/4da2d2f516d407eeae8814a02b9349dd7580964b
