### ISSUE TITLE
(Bug report) Wiki Relationship Map Page broken (by me 😱)

### ISSUE THREAD

**Issue by cwilliams5** [zadam/trilium#2643]
### Trilium Version

n/a

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

n/a

### Description

OK this is my fault. I broke the following page in the wiki:

https://github.com/zadam/trilium/wiki/Relation-map

I was trying to compare changes across two revisions, I have no idea what I actually clicked to do this....but its blanked out now.

I can see no way to get at its history to revert. Checking around supposedly there is a repo for every wiki and you can check out the file for its history. But I'm trying to clone zadam/trilium.wiki.git but cant get it working.

Otherwise it looks like wayback machine has a copy (but not the latest, this is 1 version old):
https://web.archive.org/web/20220203112030/https://github.com/zadam/trilium/wiki/Relation-map

I'd copy this content over - but I don't want to mess things up further or ruin revert chances by doing this. So:

1. I'm sorry for creating extra work on this. My bad!
2. If recreating it from the wayback machine is best step, I'll go ahead and do so.

Sorry!

**Comment by zadam** [comment]
Restored. Github Wiki is actually a git repository so all the history is preserved but not all options are available through UI.
