### ISSUE TITLE
(Bug Report) Deleting all clones of a task in task manager, causes white screen, needing restart.

### ISSUE THREAD

**Issue by ArisKallergis** [zadam/trilium#2645]
Hello, I'm using Trilium 0.50.2, on a Linux server that I have set up on the cloud, with the docker image.

I was trying out the Task Manager and noticed this behaviour, which should be reproducible by following these steps:
* Create a task with the button on the left sidebar
* Give it one or two tags
* Delete it, while also checking to delete all of its clones

When doing that, this is shown in DevTools console:
![image](https://user-images.githubusercontent.com/15965631/153759342-6b100c63-7681-4fb8-8a39-337de15d522a.png)

Then after some 10-15 seconds, the app reloads, displays a white screen only, and shows this error:
![image](https://user-images.githubusercontent.com/15965631/153759440-9075cc58-ca1b-4b95-9d30-4ea57555bdc8.png)

The only way to make Trilium work again after this, is docker stop and start again.

This is the log: [trilium-2022-02-13.log](https://github.com/zadam/trilium/files/8055747/trilium-2022-02-13.log)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. It is indeed reproducible, it comes from the interaction between TODO script and Trilium itself. The fix is a bit involved and will come probably in the next minor version ...
