### ISSUE TITLE
(Feature request) SSO integration (Authelia)

### ISSUE THREAD

**Issue by adamcodemaker** [zadam/trilium#2646]
### Describe feature

I started to use Authelia in my homelab. It would be very nice to have trilium notes integration. 
Now I have 403 message when I try to auth by Authelia. I am not sure why.

**Comment by zadam** [comment]
If auth is managed externally then it's possible to disable authentication: https://github.com/zadam/trilium/wiki/Server-installation#disable-authentication

**Comment by adamcodemaker** [comment]
thx for very fast response :)

403 was my fault 
I havent added proper domain to authelia access_control rules.

Now I disabled authentication in trilium and and it works as expected.
But now trilium is unprotected in my local netwowk. However this is not trilium problem. This is my architecture problem.

**Comment by adamcodemaker** [comment]
on the other hand I have grafana with config 
`
[auth.proxy]
enabled = true
header_name = Remote-User
header_property = username
auto_sign_up = true
headers = Groups:Remote-Group
enable_login_token = false
`

and when I try to access it via reverse proxy it requires authelia credentials and then grafana login is skipped.
When I try to access it from local network by entering ip address in browser the grafana login screen appears .

I am wondering If such feature can me implemented in trilium 🤔

**Comment by kaaass** [comment]
I recently started to use Authelia and managed to configure Trilium with Authelia. I setup two endpoints for Trilium:

1. `trilium.com` for Browser use. Protected by Authelia's forward auth mode
2. `trilium.com/sync` for Synchronization. Force URL prefix "/sync/api" and will remove "/sync" prefix. Thus the synchronization URL will be `trilium.com/sync`.

The traefik configuration to achieve this:

```yaml
labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.trilium-https.rule=Host(`trilium.com`)'
      # ...
      - 'traefik.http.routers.trilium-https.middlewares=authelia@docker'
      # Sync Service
      - 'traefik.http.routers.trilium-api.rule=Host(`trilium.com`) && PathPrefix(`/sync/api`)'
      - 'traefik.http.routers.trilium-api.middlewares=trilium-api-path'
      - 'traefik.http.middlewares.trilium-api-path.stripprefix.prefixes=/sync'
      # ...
```

The theory is that I found Trilium will ask password before synchronization, even `noAuthentication=true`. So I guess exposing the `/api` with another unprotected endpoint is safe.
