### ISSUE TITLE
(Feature request) Select Tree Items in Between (Normally Shift)

### ISSUE THREAD

**Issue by cwilliams5** [zadam/trilium#2647]
### Describe feature

Expected behavior:

Decades of computer software have trained me to click on an item, shift click on another, and all other items in between are selected. But it doesn't work in Trilium, where instead shift works as ADDING items to the selection, the way the control key does in most software:

![trilium_2022-02-13_13-09-29](https://user-images.githubusercontent.com/10100743/153775214-5c0bf143-8245-40f1-86e7-192734886ac2.gif)

The control button works the way it normally works when clicking a link in a browser - it opens the note in a new tab. This is both expected (as the normal behavior of links) and unexpected (as not the normal behavior or selecting items in a list). 

I'm not _entirely sure_ how to solve this. I personally don't use the control button to open in new tabs (I use middle click). But I'm sure many people do. 

I see two possible solutions (assuming electron/chrome allow remapping the relevant keys):

Scenario 1: Put the select addition behavior (currently on SHIFT) back on CONTROL, then add a select between functionality to SHIFT. The open in new tab function could be put on ALT.
Result: Multiselect behaviors (CTRL and SHIFT) work as expected in most software, however opening link in new tab, while possible, is not on the expected key.

Scenario 2: Leave current CTRL and SHIFT. Add a select between functionality to ALT. 
Result: Multiselect behaviors are possible, but not on the expected key. Opening link in a new tab is on the expected key. 

Probably Scenario 2 is the most widely acceptable?

**Comment by cwilliams5** [comment]
Hi, this is partly a conflict in the fact that Trilium is both a web and desktop application and there are different expectations on both (but still in-app consistency is desired).

That's actually a great way of putting the dilemma!

> Workaround is to use keyboard to select - shift + cursor keys make it quite fast.

Any interest in the proposal of using ALT as a stand in for the normal desktop app SHIFT behavior? Alt click is currently unused in the tree in Trilium. I guess this supposes your upstream dependencies support using ALT or selecting between items.

**Comment by zadam** [comment]
> Any interest in the proposal of using ALT as a stand in for the normal desktop app SHIFT behavior?

I'm not against this, I'll put it to backlog. No promises though ...

**Comment by cwilliams5** [comment]
> > Any interest in the proposal of using ALT as a stand in for the normal desktop app SHIFT behavior?
> 
> I'm not against this, I'll put it to backlog. No promises though ...

I know I thew a lot of FRs/bugs in. I of course expect no promise or anything else. If you like them for your software, hey great, if you don't then they can be closed wontfix and serve as documentation to any others who might request. Please don't take it as anything other then my enthusiasm for Trilium and my desire to add value as a tester/feedback giver.
