### ISSUE TITLE
(Feature request) New Sort Criteria Parents First

### ISSUE THREAD

**Issue by cwilliams5** [zadam/trilium#2649]
### Describe feature

_Sometimes_, I want to be able to sort like files in a file explorer. By this I mean, if I sort a folders contents in Windows, it looks like this: Folders(A-Z) then Files(A-Z). There are some times in Trilium that I would want to sort an entire subtree in a similar way: NotesWithChildren(A-Z) then NotesWithoutChildren(A-Z). 

This could be another option along title, date created, and date modified in sorting critera. This should also be an option for the #sorted label.

Even the "folder" icon for notes with children brings to mind this type of sorting:

![trilium_2022-02-13_15-57-57](https://user-images.githubusercontent.com/10100743/153781147-efaca045-fc60-44ec-9018-91957ddfc2f7.gif)

**Comment by zadam** [comment]
Interestingly, the sorting algorithm already supports this as it's used for importing ZIPs without ordering metadata, but it's not exposed to the end user in any way.
