### ISSUE TITLE
(Bug report) Highlight Text looks bad when Application/Tab Loses focus

### ISSUE THREAD

**Issue by cwilliams5** [zadam/trilium#2652]
### Trilium Version

.50.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win 10 19043.1466

### Description

Highlighted text changes very negatively when application is out of focus. Effects built in Dark theme as well. Light theme to a much lower extent. I can't figure out how to target this with a CSS selector. 

It's not just on application focus either - its when the tab itself loses focus, IE it flashes when switch to another note (too fast for my gif recorder to catch, but visible and annoying). 

![trilium_2022-02-13_17-20-37](https://user-images.githubusercontent.com/10100743/153785048-506f39eb-51d7-461e-9530-e74cf10016e1.gif)

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
