### ISSUE TITLE
(Feature request) Scheduled Full HTML Backup

### ISSUE THREAD

**Issue by cwilliams5** [zadam/trilium#2653]
### Describe feature

The ability to export my root note as a full HTML export is **excellent**. It is a great "insurance policy" backup to the sqlite database. That said, it's a manual process....

Would be nice to be able to have the server (for me, I guess desktop for desktop only people) export at a configurable interval to a configurable destination. Like every 6 hours export to /home/user/trilium-html. 

The user could then do what they want with this - store in a git tree to retain changes over time, back it up to a dropbox, whatever.

**Comment by zadam** [comment]
https://github.com/zadam/trilium/wiki/ETAPI provides a method to export ZIP. With a little bit of scripting it's possible to automate this.

**Comment by zadam** [comment]
Closing, since I don't plan to provide a built-in solution. As mentioned above, it's possible to schedule an ETAPI call with e.g. CRON.
