### ISSUE TITLE
Document location for mac is incorrect on wiki

### ISSUE THREAD

**Issue by ctlevi** [zadam/trilium#266]
Amazing project! I'm trying it out on mac, and was confused when I started trying to find the backup Sqlite DB. Per this page of the wiki https://github.com/zadam/trilium/wiki/Document, it should be in

> `/Users/[user]/Library/Preferences` for Mac OS

But the file is actually in `/Users/[user]/Library/Application Support` per https://github.com/zadam/trilium/blob/d72efd24500bbacee85a6aaf6302490d644cb5a8/src/services/data_dir.js#L24

**Comment by ctlevi** [comment]
The docker run image command at the bottom of this page https://github.com/zadam/trilium/wiki/Docker-server-installation Also appears to be out of date. The data seems to be stored in the docker container at `/root/trilium-data`

**Comment by zadam** [comment]
Hello, thanks for the report! Just to be clear, is the /Users/[user]/Library/Application Support correct or the /Users/[user]/Library/Preferences? (I do not have a lot of experience with Mac platform).

**Comment by tmerse** [comment]
> The docker run image command at the bottom of this page https://github.com/zadam/trilium/wiki/Docker-server-installation Also appears to be out of date. The data seems to be stored in the docker container at `/root/trilium-data`

I can confirm this.

`sudo docker run -t -i -p 8080:8080 -v ~/trilium-data:/home/[myuser]/trilium-data zadam/trilium:latest`
should be `sudo docker run -t -i -p 8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:latest`
if you want your data to be linked to the host os.

Apart from that really nice app (This looks promising for some of my usecases, and I am speaking as a VIM user :smiley:  ).

**Comment by ctlevi** [comment]
Sorry! The /Users/[user]/Library/Application Support is correct. If you were asking whether that is the correct place to actually store that data, I have no clue!
