### ISSUE TITLE
Original cloned note loses (*) icon when sharing.

### ISSUE THREAD

**Issue by netnem** [zadam/trilium#2661]
Using latest 50.2

Normally an icon is present indicating a cloned note:
![image](https://user-images.githubusercontent.com/32517635/154157577-90f7d0b6-1b0f-4715-a943-633d23ada834.png)

When sharing the subtree the icon disappears in favor of the share icon:

![image](https://user-images.githubusercontent.com/32517635/154157701-f85d693c-ff66-4fd4-a3e1-fe9dea97cde9.png)

The new cloned note does have the star(*) so I'm not sure if this is intended behavior or not.  My expectation was that I would have two icons: the * and the share icon.

**Comment by zadam** [comment]
Hi, shared note is also a cloned note, so you could understand the share icon as more specific version of the star icon.

(there's a corner case where the note only exists in the share subtree, so it doesn't have other clones)

**Comment by netnem** [comment]
Closing as it's intended behavior.
