### ISSUE TITLE
(Feature request) File import for ETAPI.

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2667]
### Describe feature

I tried to upload a image by updating the content of a note without success. Hope there is a way to import files with ETAPI.

**Comment by Nriver** [comment]
My image seems to be force converted to UTF-8 if I send set it as the note content.

Left is the broken one, right is the original image. All those `EF BF BD` were UTF-8 replacement character.

![ksnip_20220218-152644](https://user-images.githubusercontent.com/6752679/154637287-971c8eb0-ce03-48f2-9ab0-cce2c5555d7b.png)

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
