### ISSUE TITLE
Cannot paste password from password manager

### ISSUE THREAD

**Issue by francois** [zadam/trilium#267]
Downloaded [0.27.3](https://github.com/zadam/trilium/releases/download/v0.27.3/trilium-mac-x64-0.27.3.7z) on Mac OS X High Sierra 10.13.6 (17G4015) and was presented with a sign up form. Entered a username, and used a password manager to generate a password. When I attempted to paste the password, the form did not react: the password was not pasted as I expected. I tried CMD+V and right-clicking the field to find a paste menu, but failed. I also noticed that the Edit menu is absent. I expected to be able to paste a password, in order to manage a secure password in my password manager.

**Comment by zadam** [comment]
Hello, you're right! Mac has a particular way to handle clipboard and essentially I need to handle it manually which is done in the main app, but not in the login/setup. I'll correct it in the next release.

**Comment by josselinauguste** [comment]
the bug is still here in the current version
