### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by AlexanderRyb** [zadam/trilium#2672]
### Trilium Version

.50.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Pro version 21H2

### Description

When I open "largest notes" in statistics this error shows up : 
`Execution of JS note "template" with ID T43jQO3esH4x failed with error: Load of script note "js" (av5julTvdLp8) failed with: server error: no such column: note_revisions.isErased`
And similar error with "most edited": 
`Execution of JS note "template" with ID zMo3hklbgCIt failed with error: Load of script note "js" (SxXStLSJblfF) failed with: server error: Load of script note "js" (SxXStLSJblfF) failed with: no such column: note_revisions.isErased`

**Comment by zadam** [comment]
Hi, I assume this is not a clean installation. These statistics scripts are probably from an older version of Trilium (probably when you first installed it) and are not anymore compatible with the newer versions of Trilium. Example scripts are notes/data, not part of the Trilium application and thus are not automatically upgraded.

You can import the following ZIP with up to date scripts:
[Statistics.zip](https://github.com/zadam/trilium/files/8103071/Statistics.zip)

(You need to uncheck "Safe import")
