### ISSUE TITLE
Authelia and blank page (Not sure if this is a bug)

### ISSUE THREAD

**Issue by Oldjuju** [zadam/trilium#2677]
### Trilium Version

0.50.2

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Docker on QNAP

### Description

Hey,

I've hit a strange issue.
I'm running Trilium on my QNAP via docker. Everything works fine when I access it via IP address internally.
I'm trying to expose it via Traefik with Authelia as middleware. I have a number of other services working fine. Traefik and Authelia are on another server.

I have "noAuthentication=true" in the config.ini.

Without Authelia enabled, everything works fine from externally.
However, when Authelia is enabled, I land at a blank page. 
I can see in the Dev Console of Chrome a bunch of net::ERR_ABORTED 429 errors when the page is loading anything under the /app path.
This error is due to too many requests.

From my Android phone I am able to access Trilium from external to my network with Authelia enabled.
From the Dev Console, I tried mimicking the User Agent of the Android browser, but that did not work.
But, if I change the Network throttling to Fast 3G, then the page will load. Very slowly.

Has anyone come across this before?
I assume that this is an issue with Authelia, but unsure how to narrow it down any further.

I've put a bypass into the Authelia but I still get the errors and a blank page.
access_control:
  default_policy: deny
  rules:
    - domain: "trilium.example.com"
      resources:
        - '^/app([/?].*)?$'
      policy: bypass
    - domain: auth.example.com
      policy: bypass
    - domain:
        - "*.example.com"
        - "example.com"
      policy: two_factor

This is a screen shot of the 429 errors.
![Lzfsw4fpKv](https://user-images.githubusercontent.com/29051037/154890719-7666252b-75b5-492a-b0f5-a00862568e95.png)

thanks,

Cam

**Comment by Keridos** [comment]
Bit late, but if you have a middleware for rate limiting in traefik, you need to disable that for the trilium service. I had the exact same issue just with traefik and removing that fixed that. http error 429 is given back by traefik when the rate limiting middleware gets triggered by your browser requesting all the files.
