### ISSUE TITLE
(Bug report) What happened to the "username" field in the desktop login?

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#2679]
### Trilium Version

50.2

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu 20.04

### Description

I just installed Trilium on a new computer, and I am being rejected with a 401 error when I try to sync from the desktop. However, my user/password works when I sign in via the web. I thought this might be because I had not supplied a username (there was no field for it).I tried to supply a user name by making the url https://username@mydomain.com:443. Is the username field supposed to be gone now?

![image](https://user-images.githubusercontent.com/12942318/155226483-793f3c7a-d35f-4a16-8839-ca9e3120cf51.png)

**Comment by zadam** [comment]
Yes, username is gone. Trilium is never going to support multiple users, username does not provide extra security and it was confusing in some scenarios, so it was removed.

401 error is caused by something else, you can post here the logs to figure out what's the real reason ...
