### ISSUE TITLE
(Feature request) Multiple-line formula (TeX) input box

### ISSUE THREAD

**Issue by outloudvi** [zadam/trilium#2684]
### Describe feature

Currently the formula input box only gives one line for the user to type in TeX code. Long and single-line formulas would easily exceed the limit of the visible `<input>` box, making it tiring to use and check for TeX syntax errors. Therefore, I would hope if the following feature can be added:

* Allow users to type multiple-line formula (TeX code)

**Comment by zadam** [comment]
Hi, this was already reported and discussed in #2088, also links to the issue in the upstream repo.
