### ISSUE TITLE
(Bug report) A notes belong of root is disappeared

### ISSUE THREAD

**Issue by agent-kimbley** [zadam/trilium#2686]
### Trilium Version

0.48.9

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

 Linux DC9 5.16.4-arch1-1 #1 SMP PREEMPT Sat, 29 Jan 2022 19:08:13 +0000 x86_64 GNU/Linux

### Description

And I find in 'show recent changes' has no any record about the disappeared notes.
I mean how to recover it.

**Comment by agent-kimbley** [comment]
And it possible not I deleted.

**Comment by agent-kimbley** [comment]
The clone notes is existing that I was clone it into the place .

**Comment by zadam** [comment]
Hi, I'm not sure if I understand you correctly - you say that the note doesn't exist under the root, but the cloned note somewhere else still exists?

**Comment by agent-kimbley** [comment]
> Hi, I'm not sure if I understand you correctly - you say that the note doesn't exist under the root, but the cloned note somewhere else still exists?

Yes,’but the cloned note somewhere else still exists?‘I not sure about it,May be lost at all.
I tired again find it in  'show recent changes' and Undeleted notes,But unavliable.

**Comment by agent-kimbley** [comment]
> Hi, I'm not sure if I understand you correctly - you say that the note doesn't exist under the root, but the cloned note somewhere else still exists?

Yes,’but the cloned note somewhere else still exists?‘I not sure about it,May be lost at all.
I tired again find it in  'show recent changes' and Undeleted notes,But unavliable.

**Comment by agent-kimbley** [comment]
And I tried search some sub-notes of the disappeared note nothing found.

**Comment by agent-kimbley** [comment]
It seems disappeared by itself without any trace that I can discover.
That is creep!

**Comment by agent-kimbley** [comment]
I recover it with backup-weekly.db
