### ISSUE TITLE
(Bug report) Sync failed: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2688]
### Trilium Version

0.52.0

### What operating system are you using?

Other (specify below)

### What is your setup?

Local + server sync

### Operating System Version

Linux

### Description

"Sync failed: Cannot create a string longer than 0x1fffffe8 characters"

It looks to be either here: https://github.com/zadam/trilium/blob/1b7bcc5cc12361a4e768cb8cbe22ecb00b5ea077/src/services/setup.js#L96

Or here: https://github.com/zadam/trilium/blob/1b7bcc5cc12361a4e768cb8cbe22ecb00b5ea077/src/public/app/services/sync.js#L16

This is on the client-side when setting up a new sync server

**Comment by sigaloid** [comment]
This [sounds like a problem with handling extremely large files](https://stackoverflow.com/questions/68230031/cannot-create-a-string-longer-than-0x1fffffe8-characters-in-json-parse) (specifically, 512MB+ files) being read into a string. Perhaps there's a streaming JSON parsing library that can be used, or files can be split up into chunks? Or maybe just excluding files that are 512MB+ from being synced, with a toast message to the user.

**Comment by zadam** [comment]
Hmm, Trilium is not really designed for & tested with such huge files. Not sure if it's a good idea to put some hard limits on the upload size or what ...

**Comment by sigaloid** [comment]
I think for syncing to the server it should be hard limited as it's not just bug-worthy to store the data, it's flat-out not supported by the sync protocol.
