### ISSUE TITLE
(Feature request) How about put trilium-data in ‘/dev/shm’ for enhance accessing speed?

### ISSUE THREAD

**Issue by agent-kimbley** [zadam/trilium#2690]
### Describe feature

I notice in there has a database file calld document.db-shm in trilium-data dir.
So,Is necessary put trilium-data in ‘/dev/shm’ for enhance accessing speed?
That action is surplus or not?

**Comment by sigaloid** [comment]
This would make Trilium susceptible to data loss from power outage or hardware failure, cancelling out the benefits from using an [ACID-compliant database](https://en.wikipedia.org/wiki/ACID) like SQLite.
