### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by niklasbautz** [zadam/trilium#2693]
### Trilium Version

0.50.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Win 11 Build 22000

### Description

I was playing around with the demo. In Mermaid Diagrams/Git I changed the name of the branch. After I changed it the program freezes. When I try to start the program again It´s still frozen since the git no is still open. 
![grafik](https://user-images.githubusercontent.com/58566859/155879561-d2843dbe-96b5-483d-9e4b-9dd756ecd41c.png)

**Comment by zadam** [comment]
Hi, sorry for late response - see https://github.com/zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup 

Start the trilium in "safe mode" which will reset the page to the root page.

This is probably a bug in Mermaid which freezes the application. Something similar has been reported before :-/
