### ISSUE TITLE
"To switch to dark theme, you just need to go to Options (top-right) " - where?!

### ISSUE THREAD

**Issue by timdonovanuk** [zadam/trilium#2702]
### Trilium Version

latest

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Win 10

### Description

Simple one, but the Theme page says:

"To switch to dark theme, you just need to go to Options (top-right) "

None of the icons top right are Options for me:

![image](https://user-images.githubusercontent.com/8156439/156400226-70abdaf9-6492-4b4e-955f-1e2e8b56a082.png)

In fact, I have spent 5 mins hunting for options screen anywhere and it's nowhere to be found. It's not on the left hand side either:

![image](https://user-images.githubusercontent.com/8156439/156400426-e747fa74-fa9d-4112-a1d3-d545b1f2081e.png)

Am I overlooking it?

**Comment by sigaloid** [comment]
Top left! It's here: 
![image](https://user-images.githubusercontent.com/69441971/156402137-144dbb6e-e35b-477e-9f6c-65f1787607bf.png)

**Comment by timdonovanuk** [comment]
Ah! Damnit :) I swear I hovered over that and it didn't do anything. Might be worth updating the wiki with this. Thank you!

I <3 trilium!

**Comment by sigaloid** [comment]
Done! Glad to help :)
