### ISSUE TITLE
Question about feature

### ISSUE THREAD

**Issue by ANOLASC** [zadam/trilium#2705]
For bug reports, **PLEASE mention version of Trilium you're using** and also include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

I'm wondering if i can create new isolated tree, rather than subtree under the root. If it can, how can i accomplish it?

**Comment by XXXJetfireXXX** [comment]
Well, 'root' is called like that for a reason - it is a starting point of your note tree. I don't think there's a way to make a note outside of it.
Why would you need to do that anyway? Just curious ¯\_(ツ)_/¯

**Comment by ANOLASC** [comment]
> 

hmmm, is there any way to create subtree under the root? I find no place to do it.

**Comment by sigaloid** [comment]
Do you mean as a child to the root? Just add a new note. 
Do you mean separate from the root note, not connected? That's not possible, every note has to have a valid parent and creating it outside the root note would be invalid AFAIK.

**Comment by zadam** [comment]
People above me are correct, root note is the only one without a parent. 

You can create a sub-root just by creating a note under a root, e.g. like this:

![image](https://user-images.githubusercontent.com/617641/157125769-b5778cb3-9f20-4e95-800b-2dbc0e2ea929.png)
