### ISSUE TITLE
(Feature request) Shared notes - Can it render markdown?

### ISSUE THREAD

**Issue by letshin** [zadam/trilium#2708]
### Describe feature

Not sure if this is already possible - can shared notes render markdown to RTF?

**Comment by letshin** [comment]
Sorry. I was/am confused between the note types. When its note type: text from what I understand Trilium uses CKEditor for some Markdown autoformatting. Whilst using note type: markdown, the markdown code is highlighted, but while sharing the markdown-type code only the code is shown, and it is not converted into any formatting. Is there any way to have the markdown rendered whilst being shared?

The alternative is of course, to type it in the text format but it does feel somewhat easier to be able to type in pure markdown without CKEditor converting it on the fly.

**Comment by zadam** [comment]
Sorry for late response. What you want is not possible, Trilium simply doesn't support Markdown formatting. Markdown will be displayed as plain text.

**Comment by sigaloid** [comment]
Pardon me if I don't understand, but sharing notes that contain formatting with the built-in Trilium interface already render with shared notes.

Type \`code test\` in a note and share it, the code block will be rendered. Same as typing '#' and adding a header and such.

**Comment by wunter8** [comment]
This is changing markdown text in the code block in Trilium into rendered, stylized HTML in the shared note. For example, converting

```
# Introduction

## Download tarball

* bullet one
* bullet two
* bullet three
```
to
```
<h1>Introduction</h1>

<h2>Download tarball</h2>

<ul>
    <li>bullet one</li>
    <li>bullet two</li>
    <li>bullet three</li>
</ul>
```
which gets rendered as
# Introduction
## Download tarball

- bullet one
- bullet two
- bullet three


This allows you to write markdown in Trilium and convert it to HTML when it is shared.

**Comment by sigaloid** [comment]
Yes, but you can also just type in those things into Trilium and they get rendered. 
![image](https://user-images.githubusercontent.com/69441971/160474145-4c8d93c3-a99c-43ef-8066-ebbe337410ac.png)
Using any of these buttons is de-facto Markdown (Ctrl-B to bold, Ctrl-I to italicize, etc). These do get rendered as HTML normally when shared.

**Comment by wunter8** [comment]
Correct. I agree that if you want rendered HTML in a shared note, it's easier just to type it with the headers and everything else in the Trilium note itself. But the question was asking about converting markdown in a note into HTML in a shared note, so that's the problem I was trying to solve.

I know some people prefer taking notes in markdown instead of worrying about clicking around to add headers and bullet points and things. Also, some people might be transferring markdown notes from other tools. This is to help in those cases.

**Comment by sigaloid** [comment]
Ah, I understand now, thanks!
