### ISSUE TITLE
(Bug report) Redundancy Search Pages

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2711]
### Trilium Version

0.50.2

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

mscOS 12.2.1

### Description

Hi, Zadam,

I have been noticing that every single time I click the "show in full search" button in "quick search", there is a new full search page generated. So When I search with the same query, there will be many same full search pages in the result list.

The path of these pages seem to be "hidden/search", but I cannot find and delete them.

<img width="227" alt="图片" src="https://user-images.githubusercontent.com/7486825/157619057-70bfa251-cabe-43fd-b263-85fa318e38c9.png">

I wonder whether there is a solution for this, and I don't know whether this is a bug.

Thank you!

**Comment by gdbb** [comment]
I find a solution that I can manually delete all search notes in full search pages with the button "action" -> "Delete note".

query: "Search:" or "Search: ~ancestor=Root"

<img width="856" alt="图片" src="https://user-images.githubusercontent.com/7486825/157637047-8bcc804f-bdba-4319-9494-e643c1ac6725.png">

**Comment by sigaloid** [comment]
A better option would be to use "#searchString" as the search query, that's the attribute that gets applied to searches.
