### ISSUE TITLE
(Bug report) Incomplete searching results

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2712]
### Trilium Version

0.50.2

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS 12.2.1

### Description

Hi, Zadam,

These days I am trying various searching skills and I found another bug.

I reproduced this bug many times and found the logic.

<img width="308" alt="截屏2022-03-10 19 48 13" src="https://user-images.githubusercontent.com/7486825/157656499-9df717c8-a915-4d4b-9ba8-a4cc3a0d55db.png">

1. Unlock protected session, search contents of protected notes, and search results are normal.
<img width="356" alt="截屏2022-03-10 19 48 59" src="https://user-images.githubusercontent.com/7486825/157656509-bbd5a44f-71d5-41de-a9b6-053c81eb7000.png">
2. Lock protected session, search in "quick search", nothing shows because the protected notes are locked.

<img width="328" alt="截屏2022-03-10 19 48 34" src="https://user-images.githubusercontent.com/7486825/157656513-779e8852-5dbd-47e7-b915-716bdb1f7c7a.png">
3. After 2, if I unlock protected session, and then search contents of protected notes, nothing shows in searching results. (it is abnormal compared with 1)
<img width="328" alt="截屏2022-03-10 19 48 34" src="https://user-images.githubusercontent.com/7486825/157656513-779e8852-5dbd-47e7-b915-716bdb1f7c7a.png">

4. After 3, if I manually click the button "option -> advanced -> fill entity changes records", everything works well again.
<img width="356" alt="截屏2022-03-10 19 48 59" src="https://user-images.githubusercontent.com/7486825/157656509-bbd5a44f-71d5-41de-a9b6-053c81eb7000.png">

In one word, quick search before unlocking the session will cause failure for searching protected contents, even the session is unlocked then. (but everything is OK if we do **not** search before unlocking the protected session)

This happens because sometimes I forget to unlock the protected session before searching, so I have to manually use the "fill entity changes records".

It would be great if the function "fill entity changes records" could execute after every unlocking.

Thank you!

**Comment by zadam** [comment]
Hello, sorry for late response.

Thanks to your detailed instructions, I was able to reproduce and fix the problem. It will be in the next patch release.
