### ISSUE TITLE
(Feature request) Support Chinese language

### ISSUE THREAD

**Issue by oreak** [zadam/trilium#2718]
### Describe feature

Support Chinese language

### Additional Information

Support Chinese language

**Comment by Nriver** [comment]
You can try my Chinese version here https://github.com/Nriver/trilium-translation/blob/main/README_CN.md

**Comment by oreak** [comment]
> You can try my Chinese version here https://github.com/Nriver/trilium-translation/blob/main/README_CN.md

正是我需要的，简直太棒了
