### ISSUE TITLE
Bug: recent-docs dropdown doesn't disappear when attributes dialog closes

### ISSUE THREAD

**Issue by yozlet** [zadam/trilium#272]
To reproduce:

1. On a note, open `Attributes` view
2. Change a row's `Type` to `relation`
3. In the note search box that appears (in the `Value` column), click the "recent documents" (clock) button: a dropdown of recent documents appears
4. instead of choosing a document, close the dialog (either corner `X` button, or hit `Esc` key)

Result: the attributes dialog disappears, but the list of recent documents stays above the note. Clicking around (e.g. navigating to other notes) doesn't remove the list. However, clicking an item _in_ the list removes it.

**Comment by zadam** [comment]
Hello, thank you for the report, bug has been fixed and will be released soon.
