### ISSUE TITLE
(Bug report) “Search in note”

### ISSUE THREAD

**Issue by gdbb** [zadam/trilium#2730]
### Trilium Version

0.50.2

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS 12.2.1

### Description

Hi,

There is a bug in "Search in note".

**Sometimes**, when I click the right arrow button or press return button to find the next result, the total number of results changes.

In this case, it should be "1/4" and it changes from 1/4 to 2/4 to 3/4 to 4/4, but it becomes like:

the left number is in the loop of "1, 2, 3, 4, 1, 2, 3, 4...", but the right number (the number of total results) keeps increasing by a specific step, for example, "1/4, 2/5, 3/6, 4/7, 1/8, 2/9, 3/10, 4/11, 1/12 ..."

https://user-images.githubusercontent.com/7486825/158363357-a090a90d-0d51-4d84-a2c7-16be9a7e170b.mov

https://user-images.githubusercontent.com/7486825/158363363-f8ffe817-6788-469c-9138-a962031eeb9b.mov

**Comment by antoniotejada** [comment]
You can give #2806 a try, it's simple but works.

**Comment by gdbb** [comment]
> You can give #2806 a try, it's simple but works.

Wow, incredible!

**Comment by zadam** [comment]
There's a new find dialog, closing.
