### ISSUE TITLE
(Bug report) app/share.js missing

### ISSUE THREAD

**Issue by wunter8** [zadam/trilium#2738]
### Trilium Version

0.50.2

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu

### Description

Shared notes try loading `../app/share.js` which doesn't exist in the latest server release tar.xz file

https://github.com/zadam/trilium/blob/77ce56ba840300fd79b4573dbbee339175944096/src/views/share/page.ejs#L10

**Comment by sigaloid** [comment]
It loads alright for me. https://github.com/zadam/trilium/blob/master/src/public/app/share.js

That file is loaded from the Trilium server, which has to be running, but I am running it and I can access it: 
![image](https://user-images.githubusercontent.com/69441971/159353295-158dd48e-dcd3-4bc0-8957-2397774160fa.png)

I am also on 0.50.2.

**Comment by wunter8** [comment]
If you look inside the latest release ([https://github.com/zadam/trilium/releases/download/v0.50.2/trilium-linux-x64-server-0.50.2.tar.xz](https://github.com/zadam/trilium/releases/download/v0.50.2/trilium-linux-x64-server-0.50.2.tar.xz)) there is no `app` folder in `src/public/` (and thus no `app/share.js`)

**Comment by sigaloid** [comment]
Ah, I see. I'm using the Docker container so it might be packaged differently.

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed. Note that this file is not critical for most use cases.
