### ISSUE TITLE
(Bug report) I need to refresh the page to see the changes

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#2746]
### Trilium Version

0.50.3

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Debian Testing

### Description

Hi

I am running Docker setup behind Apache proxy on Debian Testing. I can login to my site and see my notes however I can't see my changes as I make them, I need to reload the page to see the changes.

Here is my proxy which I copied from the Wiki

```
 #Trillium
      RewriteCond %{HTTP:Connection} Upgrade [NC]
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteRule /trilium/(.*) ws://localhost:8083/$1 [P,L]
        AllowEncodedSlashes NoDecode
        ProxyPass /trilium/ http://127.0.0.1:8083/
        ProxyPassReverse /trilium/ http://127.0.0.1:8083/


```

I see that in the console I get this error 

```
WebSocket connection to 'wss://DOMAIN/trilium/' failed: 
connectWebSocket @ ws.js:198
sendPing @ ws.js:220


```
Bear in mind that v4 used to work great with exact same setup, so I do not understand why this is failing for me.

Has there been any change to the websocket requirements? I have the wss modules enabled for Apache already

**Comment by zadam** [comment]
Hi, this is a problem with websocket configuration on the apache. 

There hasn't been any changed in this behavior in years.

**Comment by zadam** [comment]
> Is it possible that v5 has an issue with subpath (something v4 did not have issue with)? Because I am not running it with its own domain, rather runing with under a path like `https://domain/trilium'

I don't think so. I actually have the same setup (having trilium on a subpath) and it works fine.
