### ISSUE TITLE
Error when calling DELETE

### ISSUE THREAD

**Issue by longzekai** [zadam/trilium#2750]
### Trilium Version

0.50.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

win 10

### Description

Error when calling DELETE /api/branches/jXOj0DCc3xyw?taskId=Wn8ajco9PN&eraseNotes=false&last=true: 500 - database disk image is malformed

**Comment by zadam** [comment]
Hi, unfortunately it looks like your database is corrupted. You might try to restore a backup: https://github.com/zadam/trilium/wiki/Backup#restoring-backup

Do you by chance use something like Dropbox or Google Drive to sync data?
