### ISSUE TITLE
Header bar does not fully extend when advanced sample button removed

### ISSUE THREAD

**Issue by s-schumann** [zadam/trilium#276]
Congrats on the project first of all.

I removed the "Weight Tracker" from the demo and after a restart the "Weight Tracker" icon in the toolbar also disappeared (as I expected, was wondering why I needed to restart, but maybe there is a way to refresh).

What I see now though - and I think it is related - is that the header bar does no longer span over the full screen.

I attached a screenshot and video to make it clear, not sure how to explain it better. I strongly assume it correlates to the button being removed, it looked ok before:

<img width="1011" alt="toolbar-enlarge" src="https://user-images.githubusercontent.com/428710/50795883-fdf91300-12cf-11e9-8aa5-c6bc372362ec.png">

![toolbar-enlarge-screen](https://user-images.githubusercontent.com/428710/50796254-42d17980-12d1-11e9-8dc6-bce8585f286b.gif)

Thanks for checking.

Best regards
Sebastian

**Comment by zadam** [comment]
Hello, thank you for the bug report! It turns out it's not related to the removal of weight tracker and it happens everytime you stretch the window beyond a certain width (in my case more than 1956 pixels). I've never noticed because I don't have a screen with such resolution. Fix was very simple.
