### ISSUE TITLE
(Bug report) Multiple scroll bars in long js backend/js frontend notes

### ISSUE THREAD

**Issue by Lightirius** [zadam/trilium#2760]
### Trilium Version

0.50.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 Pro 21H2

### Description

Long code notes with type "js backend" or "js frontend" have multile scroll bars. I think that's because of the additional buttons below text editor. There was no such problem in 0.49.5.
![image](https://user-images.githubusercontent.com/11685338/160666199-663ed2f4-b670-4437-9edd-d4f472cc1e27.png)

**Comment by zadam** [comment]
Yeah, the buttons are causing this. Not a big problem but would be nice to fix this ...

**Comment by Lightirius** [comment]
Works fine on Trilium 0.57.5
