### ISSUE TITLE
Wiki: Gif for saved search missing

### ISSUE THREAD

**Issue by jniggemann** [zadam/trilium#2761]
### Trilium Version

latest

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Windwos 10, Debian 11

### Description

Not directly program-related, but the gif on https://github.com/zadam/trilium/wiki/Saved-search is missing.
I'd have taken the one from an earlier revision, but I'm not sure if it's current.

**Comment by KhadishaKudys** [comment]
I added a gif on this page. 
<img width="697" alt="image" src="https://user-images.githubusercontent.com/51974069/160965233-4554ed9f-9e82-4227-be71-6105b788d841.png">

Please let me know if it needs correction.

**Comment by jniggemann** [comment]
Nice, TY
