### ISSUE TITLE
(Feature request) "Bookmarks" section

### ISSUE THREAD

**Issue by KhadishaKudys** [zadam/trilium#2766]
### Describe feature

Bookmarking notes cause overflow in the launch panel. I think it will be better to place them in the left panel, right above all other notes, by creating the "Bookmarks" section. It will be more convenient to navigate through them (since the title will be visible without hovering it). Also, it will not cause overflow and alignment problems. 

Actual:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/51974069/160978086-05c33a2d-fafc-47d0-8c28-647b81cd9b58.png">

**Comment by zadam** [comment]
Hi, I think something like that is already available as "bookmark folder", see here: https://github.com/zadam/trilium/wiki/Bookmarks#bookmark-folder

**Comment by KhadishaKudys** [comment]
> Hi, I think something like that is already available as "bookmark folder", see here: https://github.com/zadam/trilium/wiki/Bookmarks#bookmark-folder

I think that I am doing something wrong since I don't have this folder, but all the bookmarks are located in the launch panel as in the screenshot above.
