### ISSUE TITLE
Cant log in with Mac desktop app - Auth request time is out of sync

### ISSUE THREAD

**Issue by dabeeeenster** [zadam/trilium#277]
Self hosting the server on Dokku with docker. 

On one of my laptops (running Mojave) I am unable to login. Seeing this in the logs:

```
2019-01-07T22:10:52.805560869Z app[web.1]: POST /api/login/sync returned 400 with response {"message":"Auth request time is out of sync"}
```

Checked the times on the server and laptop and they are both correct (am in London/UTC).

**Comment by dabeeeenster** [comment]
Understood. Some feedback to the user here would be great.

**Comment by gm-github** [comment]
Hi, does this time sync handle time zones?  I have a server in UTC, and a client in AEST which gives the same error on sync.

**Comment by gm-github** [comment]
I just increased the validity time to 60000 and it's working fine now, so time zones are good, my clocks would be more than 5000ms out.
