### ISSUE TITLE
Attributes change from #x=1 to #x_1 over time?

### ISSUE THREAD

**Issue by PAK90** [zadam/trilium#2771]
### Trilium Version

0.50.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win10 21H1

### Description

I create notes via an api note from a 3rd party application, and one of the most important things I add are attributes with either numeric or string values. For example, I might create a new note with attributes like this: `#rating=3 #event=workout`. I've confirmed this seems to work fine whenever I create the note (i.e. I created some new notes with my app right now and the attributes have `=` in them as intended).

However, I was going through old notes from a few days ago and something weird has happened; all the attributes have been 'corrupted' to be this: `rating_3 #event_workout`. Is there some auto-cleanup thing running that's accidentally corrupting these? This is NOT happening via the normal method of creating attributes within the Trilium app itself, thankfully.

For reference, here's the API note that's creating these attributes:

```
const {req, res} = api;
const dayjs = require('dayjs');
const {secret, title, content, attributes} = req.body;

console.log('req and secret: ', req.method, secret);
if (req.method == 'POST' && secret === 'password') {
    // notes must be saved somewhere in the tree hierarchy specified by a parent note. 
    // This is defined by a relation from this code note to the "target" parent note
    // alternetively you can just use constant noteId for simplicity (get that from "Note Info" dialog of the desired parent note)
    const todayNote = api.getTodayNote();
    
    const {note} = api.createTextNote(todayNote.noteId, `${dayjs().format('HH:mm:ss')} - ${title}`, content);
    
    attributes.split('|').forEach(async attr => {
        let fixedAttr = attr;
        const [attrName, attrValue] = attr.split('=');
        // if the attrValue is a number, cast it as such
        if (!isNaN(attrValue.replace(/'/g, ''))) {
            const numAttr = Number(attrValue.replace(/'/g, ''));
            fixedAttr = attrName + '=' + numAttr;
            console.log('fixed: ', fixedAttr, numAttr);
        } else {
            // not a number, but still wanna remove quotes
            fixedAttr = attrName + '=' + attrValue.replace(/'/g, '');
        }
        
        note.addAttribute('label', fixedAttr);
    })

    res.status(201).json(note.getPojo());
}
else {
    console.log('---returning 400 status');
    res.send(400);
}
```

**Comment by sigaloid** [comment]
Looks like this code here. https://github.com/zadam/trilium/blob/df1d94ec61b04f73ff4bcc9681bb806af2ee09ca/src/services/attributes.js#L131-L143

It sounds like your code possibly sets the input ("rating=3") as the _name_ when it should be handling it as a split of name and value (name = "rating", value = "3").

Is there a way to call note.addAttribute with a value?

https://regex101.com/r/oFok5J/1

**Comment by PAK90** [comment]
It seems to be adding them as values? If I click on the attributes I see this:

![image](https://user-images.githubusercontent.com/1844422/161466234-c75bba6f-d3c6-43d7-a31a-a179e30eafd8.png)

**Comment by sigaloid** [comment]
That seems like GUI quirk because replacing the "=" with a "_" from an attribute name matches the behavior of the code I linked. 

If you modify your code to instead call `note.addAttribute('label', attrName, attrValue.replace(/'/g, ''))`, that should correctly set the value. Can you try that?

**Comment by PAK90** [comment]
Ohh that's interesting... I tried that, and it seems to be working rather well (I didn't even have to do all that number parsing/casting I have in my code previously). If this 'switches' back to having `_` instead of `=` I'll post again in this issue, but I'm hopeful you've given me the fix here. Thanks!

**Comment by sigaloid** [comment]
Glad to hear! By the way, you can manually check to see if it will revert, by running a consistency check in the settings menu; that will call the sanitizeAttributeName function on attributes.

**Comment by PAK90** [comment]
Oh, _that's_ what it is... ok yeah, double-confirmed now, this absolutely fixed the issue I was having. Thank you again! I guess I should've read the API docs better and realised that method had two params; one for value and one for label.

**Comment by sigaloid** [comment]
Awesome! Glad to help.

**Comment by zadam** [comment]
Looks like the issue has been resolved, so I'll close this issue.
