### ISSUE TITLE
Code highlighting in markdown

### ISSUE THREAD

**Issue by ALittleFishes** [zadam/trilium#2780]
### Describe feature

Add code highlighting features

**Comment by zadam** [comment]
Trilium isn't really a markdown editor. Highlighting within markdown's code blocks is not planned.

If you actually mean highlighting in the rich text's code blocks, then this is not supported either, but has a better chance of being implemented in the future.

**Comment by ScarletDor** [comment]
> Trilium isn't really a markdown editor. Highlighting within markdown's code blocks is not planned.
> 
> If you actually mean highlighting in the rich text's code blocks, then this is not supported either, but has a better chance of being implemented in the future.

sad
