### ISSUE TITLE
(Feature request) Sharing - Can we password protect public pages

### ISSUE THREAD

**Issue by letshin** [zadam/trilium#2781]
### Describe feature

Would like the public shared page to be password protected before it is accessed, so it isn't accessible that easily. Is this possible to be implemented please? Same password as the trillium notes would be acceptable as a next-best!

Thanks

**Comment by zadam** [comment]
Basic docs here: https://github.com/zadam/trilium/wiki/Sharing#protecting-shared-notes-with-a-password
