### ISSUE TITLE
(Feature request) Custom font support

### ISSUE THREAD

**Issue by ScarletDor** [zadam/trilium#2789]
### Describe feature

For other languages, the default font is not suitable, I hope to add an address bar to replace the default font address in the options, and fill in the cdn link of the font to replace the default font

### Additional Information

thanks

**Comment by zadam** [comment]
Hi, it's possible to define a custom font in a custom theme, it is documented here: https://github.com/zadam/trilium/wiki/themes

It's a bit advanced though.

**Comment by ScarletDor** [comment]
感谢，但是随着版本的更新自定义主题会不适用，我还是期待能在软件本身集成这种功能，或者是更换成更好看的字体

**Comment by ScarletDor** [comment]
可以了，我有办法了，感谢
