### ISSUE TITLE
(Feature request)  I hope that the shared page can be mobile friendly.

### ISSUE THREAD

**Issue by flysaber** [zadam/trilium#2790]
### Describe feature

This note is a great work. I hope that the shared page can be mobile friendly. The current shared page is too small to watch on the mobile phone. In addition, I hope that the shared page can highlight the code syntax, preferably dynamic.

**Comment by zadam** [comment]
Hi, thanks for reporting this problem. Shared notes are actually supposed to be responsive, but there was a bug preventing it from working. Now it's fixed and should be in the next stable version.

**Comment by Rsose** [comment]
Hi Zadam
The exported HTML format file(INDEX.html) is very distorted on the mobile phone
<img src="https://user-images.githubusercontent.com/51273534/171799187-0fa65f33-fe53-44a9-8000-b6c5928a74d0.png" width=30% height=30%>
Titles can only be displayed by scrolling,is there any good solution for this?


I found some good responsive websites it may gives you some inspiration
**2 examples** from Help and Manual software

1. https://www.helpandmanual.com/help/hm_working_project_importsandcastle.html
2. https://www.it-authoring.com/info/pp4help/sp03_toolboxconfig.html
<img src="https://user-images.githubusercontent.com/51273534/171800737-57dcfcb3-6c45-4328-b353-441a5d9ed950.png" width=30% height=30%><img src="https://user-images.githubusercontent.com/51273534/171801024-43384510-6a60-45fa-9632-3b083707fb84.png" width=30% height=30%>
<img src="https://user-images.githubusercontent.com/51273534/171800832-21922a85-fcbb-43eb-ab8d-09774df70e92.png" width=30% height=30%><img src="https://user-images.githubusercontent.com/51273534/171800855-a7f545ea-0bec-40b4-af30-8a96cca7dd38.png" width=30% height=30%>
Their file directories can be freely hidden and shown on the mobile

Another request will a **SEARCH** function be added to index.html in coming days?It's like as shown in the links above
Waiting for your reply
Thanks

**TRILIUM WINDOWS VERSION 0.51.2 **

**Comment by zadam** [comment]
Responded in #2893
