### ISSUE TITLE
(Bug report) Hover popup on internal link breaks when displaying image

### ISSUE THREAD

**Issue by QuentinLeCaignec** [zadam/trilium#2794]
### Trilium Version

0.50.2

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Kernel 5.13.13, KDE 5.22.5

### Description

There is a specific case that breaks the popup preview of an internal link when hovering said link.
If the preview contains an image at the start of the note (or close enough to the start), and if the popup appears to the top of the link (rather than below, left or right), the preview popup glitches and rapidly becomes visible/invisible. 
Its position is probably wrong, so it shortly displays on top of the link, making the mouse not hovering the link anymore whichs stop the displays, making the mouse hover again which displays the popup, on loop.

Here's a webm of the problem, to the right is a note with text, to the left is a note with an image at the top. You can see the left popup briefly appear, in reality it is very rapidly blinking.

![output](https://user-images.githubusercontent.com/12102823/163673541-58f4fd55-9df3-4e7a-b77f-666d1465ba32.gif)

Here's another example in a new note, you can see that it's the popup position that matters, since just scrolling a bit makes it display or glitch based on where it tries to appear.

![output](https://user-images.githubusercontent.com/12102823/163673742-683a8c1e-2c17-4f29-a01e-012e5fb20aae.gif)

**Comment by zadam** [comment]
Hi, unfortunately I'm not able to reproduce this:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/617641/163675094-0e39e5c9-f90b-499d-851f-1bdeb47bf200.png">

Would it be possible to make a minimal reproducible example (one note with the image, one note linking to it) and export the subtree as ZIP?

<img width="622" alt="image" src="https://user-images.githubusercontent.com/617641/163675149-28558224-2114-49e5-b287-1b473ac953c5.png">

**Comment by QuentinLeCaignec** [comment]
[test note.zip](https://github.com/zadam/trilium/files/8499942/test.note.zip)

Interesting. Here's an export with new notes I made. Do you think it might have to do with appearance settings ? Here's mine :

Heading Style : Markdown Style
Zoom factor: 1,0
Native title bar: disabled
Theme: dark
Override theme fonts: yes
Main font: theme defined, size 100%
Note tree font: theme defined, side 100%
Note detail font: sans serif, 120%
Monospace font: theme defined, 100%
Content width: 1600

**Comment by zadam** [comment]
Hi, your analysis was correct, there seems to be some problem in bootstrap's placement algorithm. I fixed it by workaround by offsetting the placement a little.
