### ISSUE TITLE
Attributes visible without going to dialog

### ISSUE THREAD

**Issue by mahdi1234** [zadam/trilium#28]
It might be good idea to show attributes/values for selected note in status bar (either below actual note or at the bottom of the app, which may be more consistent as it would be always the same position).

**Comment by zadam** [comment]
See example:

![image](https://user-images.githubusercontent.com/617641/35784780-57607dfc-09e9-11e8-8d93-a175c5ca520d.png)

Button "Attributes:" takes you to the attribute edit dialog. Attributes are formatted in a way that allows you to just copy & paste to search input to look for notes with same attribute / value.

**Comment by mahdi1234** [comment]
Perfect :)
