### ISSUE TITLE
(Bug report) WITH clause does not work in SQL Console

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#2800]
### Trilium Version

0.50.2

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop!_OS 21.10

### Description

Running `sqlite3` manually on Trilium's SQLite database, this works just fine:

```
sqlite> WITH
  Test AS (
    SELECT title, isDeleted, isProtected FROM notes LIMIT 100
  )
SELECT * FROM Test


   ...> ;
chart.js|0|0
Statistics|0|0
Attribute count|0|0
template|0|0
js|0|0
...
```

Trying the same in SQL Console in Trilium (opened with Alt+O):

![image](https://user-images.githubusercontent.com/714892/164061160-5e4a93a0-e544-4aa1-b87b-2bb3cae6136a.png)

The results don't get shown:

![image](https://user-images.githubusercontent.com/714892/164061087-edbf88f7-aeb6-4fd2-b7bf-188f5b086038.png)

**Comment by mechanarchy** [comment]
The server code currently handles queries differently; anything that doesn't start with `select` is executed but the rows aren't fetched.

https://github.com/zadam/trilium/blob/c177aaa901a9388bbce5341b3e6fdb41195dcbe2/src/routes/api/sql.js#L40-L45

**Comment by zadam** [comment]
Indeed, the fix is actually trivial, thanks for bringing attention to this.
