### ISSUE TITLE
Option "passwordVerificationHash" doesn't exist(Bug report) 

### ISSUE THREAD

**Issue by surajsharma** [zadam/trilium#2803]
### Trilium Version

0.50.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

macOs 12.13 / Linux

### Description

Instance hosted on a linux box in Azure app service using docker (latest) won't let me log in, saying 

`Option "passwordVerificationHash" doesn't exist`

when I click login.

logs on the locally hosted instance reporting no error  and even the sync is working fine otherwise.

**Comment by surajsharma** [comment]
thanks for your answer. i am able to run the query locally and it returns a value, so should i just create a new remote instance?

**Comment by sigaloid** [comment]
That would likely solve the issue, if you can reinstall it and set up a synchronization again. That's an odd bug so hopefully it doesn't happen again.

**Comment by surajsharma** [comment]
> That would likely solve the issue, if you can reinstall it and set up a synchronization again. That's an odd bug so hopefully it doesn't happen again.

yeah i reinstalled and it works, thanks.
