### ISSUE TITLE
(Feature request) Relationships-Symlinks mode

### ISSUE THREAD

**Issue by AKmatiAK** [zadam/trilium#2809]
### Describe feature

Hi. I have idea to make advantageous "filesystem". Instead of just hierarchizing notes in folders:
1. Save all notes in root directory.
2. Build hierarchies using symlinks to notes. That would allow to include single note in multiple hierarchies, and make hierarchies with other hierarchies inside etc. freely. I found thread mentioning clones (marked with *) that look somehow similar to symlinks. Then 

This approach overcomes simple hierarchy limitations - that every element has only one child and only one parent. Combining it with well-described relations between notes/hierarchies you can create probably any logical construct. It's basically improved zettelkasten in my opinion, something similat to what you can do in Logseq, but with hierarchies and relationships (which are already implemented in trilium) added. The most important part for me is ability to create net based on relations, whose I think are very important in organizing knowledge.

Or, if clones work like symlinked notes, just add option to disable showing *
Damn... I'm new to trillium and the more I dig in how it works the more I think I'm reinventing already introduced concepts 😮

**Comment by AKmatiAK** [comment]
Ok, what I was talking about is clones not symlinks. So the only change will be option to disable showing *

**Comment by zadam** [comment]
Yes, what you're describing is called clones. The "relation" concept you describe also exists and is in fact called "[relation](https://github.com/zadam/trilium/wiki/Attributes)".

If the * bothers you a lot, you can disable it with [custom CSS](https://github.com/zadam/trilium/wiki/Themes#custom-css).
