### ISSUE TITLE
Add wikilinks

### ISSUE THREAD

**Issue by crispinb** [zadam/trilium#281]
ie. automatically make dummy links from words written in camel case (or perhaps upper-camel/title-case) which, when clicked on, automatically create a new note, and replace the dummy link with a real link to the new note.

The aim would be to make a common use-case (writing hierarchical content) a bit more fluent. Currently a user needs to make a new note, go back to the original note & add a link.

An equally useful alternative could be: if/when the 'Cut selection to sub-note' feature is re-enabled,  add an option to replace the extracted selection with a link to the new note.

**Comment by zadam** [comment]
> ie. automatically make dummy links from words written in camel case (or perhaps upper-camel/title-case) which, when clicked on, automatically create a new note, and replace the dummy link with a real link to the new note.

I'm skeptical towards this - I used to use Wikidpad years ago which worked the same way and it was pretty annoying because there's many cases of CamelCase which shouldn't be links. 

> An equally useful alternative could be: if/when the 'Cut selection to sub-note' feature is re-enabled, add an option to replace the extracted selection with a link to the new note.

Yeah, inserting the link would be possible. Unfortunately it's blocked by a kind of architectural limitation of CKEditor which might be resolved in the future - see details here: https://github.com/ckeditor/ckeditor5/issues/1384

CKEditor team is also working on an inline mention/autocomplete system which would allow easier inplace linking and I can imagine it could be possible to also use it to create new subnote inplace - see https://github.com/ckeditor/ckeditor5/issues/998

**Comment by crispinb** [comment]
> I'm skeptical towards this - I used to use Wikidpad years ago which worked the same way and it was pretty annoying because there's many cases of CamelCase which shouldn't be links.

Fair enough - it's a bit of a love-or-hate-it feature. Wikilinking did in any case arise from early web apps which lacked the dynamic capabilities to offer interactive UIs for things like linking.

I still think the idea of being able to create a link and a new note simultaneously is worth considering: how about an option to create a new note in the 'Add Note Link' (ctrl-l) dialogue? A new button there could create a new child note in the background, initially titled using the link text. Just a thought.

(Separately, I also hope one way or another you can get cut selection to sub-note working with CKEditor - it's a great feature and AFAIK unique to Trilium)

**Comment by jsaaby** [comment]
> > ie. automatically make dummy links from words written in camel case (or perhaps upper-camel/title-case) which, when clicked on, automatically create a new note, and replace the dummy link with a real link to the new note.
> 
> I'm skeptical towards this - I used to use Wikidpad years ago which worked the same way and it was pretty annoying because there's many cases of CamelCase which shouldn't be links.

It works beautifully in Confluence! Not from CamelCase though, but by just adding square brackets around the text.

A link to a non-existing page is then created. If you click the link, a page is created with the title from the link text. Simply include a function to see which links to non-existing pages exist, and you've basically created a todo for page creation.

**Comment by zadam** [comment]
Yeah, confluence-style creation would be probably preferable. I think it should be possible once CKEditor has this: ckeditor/ckeditor5#998

**Comment by technovangelist** [comment]
having something like this would be wonderful.

**Comment by nil0x42** [comment]
I seems that ckeditor5 merged the mentions feature in march, should make it possible to do now :)

**Comment by zadam** [comment]
Implemented in master, coming in 0.37:

![image](https://user-images.githubusercontent.com/617641/68500703-a1061a80-025c-11ea-8202-16aba04918e4.png)
