### ISSUE TITLE
(Bug report) Button tooltips duplicating each other.

### ISSUE THREAD

**Issue by XXXJetfireXXX** [zadam/trilium#2811]
### Trilium Version

0.50.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

I'd say it's not really a bug, just a strange behaviour.
When you hover your mouse over some of the buttons, two tooltips that are exactly the same will show up, sometimes overlapping each other. and I'm not sure if that is intended.
![image](https://user-images.githubusercontent.com/43646178/164949916-cfe8ca87-4014-4a6d-88f4-00be8b2a4e53.png)
![image](https://user-images.githubusercontent.com/43646178/164949918-9b41da05-921d-4b31-83fe-04175a0ab18e.png)
![image](https://user-images.githubusercontent.com/43646178/164949966-99ea6d50-f6fa-420f-8c94-2766227acb65.png)

**Comment by sigaloid** [comment]
Is this in a browser or a local app?

**Comment by XXXJetfireXXX** [comment]
A local app, no sync setup.

**Comment by sigaloid** [comment]
Ah, I was going to say, this occurs on my browser as well. Perhaps the tooltips can be disabled on the web view, not sure..

![image](https://user-images.githubusercontent.com/69441971/164950556-0b530242-66d8-41b7-ad7f-bf86c1c74f65.png)

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
