### ISSUE TITLE
(Feature request) Bulk-adding attributes

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#2812]
### Describe feature

When the user uses Shift+Click to select a bunch of pages in the tree bar, add a right-click option (and maybe keyboard shortcut) that open a dialog for adding owned attributes to all selected pages.

This way I could add the ~template=@Paper template attribute en masse.

**Comment by zadam** [comment]
implemented in master

**Comment by agentydragon** [comment]
awesome, thanks so much!
