### ISSUE TITLE
docker code is not sync with persistence volume 

### ISSUE THREAD

**Issue by kush99993s** [zadam/trilium#282]
Hello everyone,

When I run following command 

```sudo docker run -t -i -d -p 8080:8080 -v ~/trilium-data:/home/my_user/trilium-data zadam/trilium:0.26.1```

I set up account, and save couple of files.

Then I kill that docker instance, and restart it. I am not able to see old records. Nor do I was able to see files in /home/my_user/trilium-data  folder.

Any help is appreciated

**Comment by tmerse** [comment]
Let me refer to my answer: https://github.com/zadam/trilium/issues/266#issuecomment-451940722

**Comment by zadam** [comment]
@tmerse thank you for your help! I'll fix in the wiki ASAP.

**Comment by kush99993s** [comment]
@tmerse , thank you. It worked. Thank you @zadam for great applicaitons
