### ISSUE TITLE
(Bug report) can not search keywords across/merging title, attributes, and the main body content

### ISSUE THREAD

**Issue by mo-han** [zadam/trilium#2820]
### Trilium Version

0.50.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows 10 LTSB 2016

### Description

a note, with `kw_a` ONLY in title, `kw_b` ONLY in attributes, `kw_c` ONLY in the body/content
- search for `kw_a kw_b` or `kw_c`: can find this note
- search for `kw_a kw_b kw_c` or `kw_a kw_c` or `kw_b kw_c`: not found

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
