### ISSUE TITLE
(Bug report) Searching text from mermaid does not work

### ISSUE THREAD

**Issue by gao-feng** [zadam/trilium#2821]
### Trilium Version

0.50.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Win 10 19043.1645

### Description

For example 
```
flowchart LR
    Test_Start --> Test_Stop
```

I expect to find out this mermaid note by searching "Test_Start"  in "Quick search".

**Comment by zadam** [comment]
Hi, fixed, thanks for reporting.
