### ISSUE TITLE
Missing div tag closing angle in initial database word count widget

### ISSUE THREAD

**Issue by antoniotejada** [zadam/trilium#2829]
### Trilium Version

0.50.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

The HTML template variable TPL for the word count widget in the initial database is missing a closing angle at the very end, in the closing div tag:

```
const TPL = `<div style="padding: 10px; border-top: 1px solid var(--main-border-color); contain: none;">
    <strong>Word count: </strong>
    <span class="word-count"></span>

    &nbsp;

    <strong>Character count: </strong>
    <span class="character-count"></span>
**</div`;**
```

This was fixed in the wiki by

https://github.com/zadam/trilium/wiki/Custom-widget/_compare/fb4396ac6e21cffc1583b13f5f3a5c3ee9a5c50f

but the example shipped in the initial database is still broken as of 0.50.3

**Comment by zadam** [comment]
Thanks for the heads up, fixed.
