### ISSUE TITLE
Use platform specific compression format for desktop releases

### ISSUE THREAD

**Issue by jvgrootveld** [zadam/trilium#283]
Packaging executables is good but I think it is unnecessary to require a 3rd party unarchiver like 7z for a platform specific release.

I would recommend the following formats:
- Mac: .dmg or .zip
- Windows: zip
- Linux: .zip or .tar.gz

**Comment by zadam** [comment]
DMG on Mac is not possible unfortunately since it's not possible to build it on linux host.

But I will probably unify formats. Closing in favor of #316
