### ISSUE TITLE
Advice Request - Data Recovery

### ISSUE THREAD

**Issue by Typhonragewind** [zadam/trilium#2832]
Hello!

I've been using Trilium for ages now without a hitch, truly amazing software and I can't thank you enough for it.

I write this in the hope that  you can help me in a last chance attempt at recovering some lost data after a major mistake on my part.

2 Months ago I overhauled pretty much my entire system while doing a domain name change, and it seems that during all that I misconfigured my trillium docker container so that the data path i persisted in the system was not the path where the data was actually saved to. This is what I found out today after I updated to the latest version.

I only use trilium in the browser, so my only chance to recover the data is from the browser local cache on my desktop, which hasn't been online since the update - so my question is, where and how would this data be stored locally in the browser cache (Firefox) and how recoverable is it?

**Comment by Typhonragewind** [comment]
> Do you have the command in your bash command history? If so, you can go back to see what directory you bound. If you didn't bind a directory, it should be contained within the docker container still (just shut down) unless you deleted it.

The data was wrongly stored in the container itself, not in an unknown folder in the host. And unfortunately I updated it by using the Recreate function in portainer, so the container is gone as well. I appreciate the tip though!

**Comment by zadam** [comment]
Hi, unfortunately, I don't think there will be anything of value stored in the browser caches. Browsers cache static data like library assets, but not dynamic data like REST calls ...

**Comment by Typhonragewind** [comment]
> 



> Hi, unfortunately, I don't think there will be anything of value stored in the browser caches. Browsers cache static data like library assets, but not dynamic data like REST calls ...

Ah, there goes my last hope. My last good backup is 2 months, but I'll manage to rebuild (this is what I get from thinking i shouldn't be so paranoid).
But thanks for trying to help :)
