### ISSUE TITLE
(Feature request) Internal links in markdown notes

### ISSUE THREAD

**Issue by surajsharma** [zadam/trilium#2834]
### Describe feature

It may be a copy of [2121](https://github.com/zadam/trilium/issues/2121), but AFAIK there is no way to create internal links in a markdown note. the ability to refer to other notes in markdown is a sorely missed feature to the point i would be happy to make a PR, but i'm not that familiar with the codebase.

ckEditor allows for traditional markdown links like: 

```

 [John Gruber](https://daringfireball.net/projects/markdown/)

```

and so theoretically creating a local internal look would look like:

```
[note title](http://localhost:8080/#root/<note_location>)

```

which will result in a non-clickable, ugly looking piece of markup in the text 

what is needed is :
1. the ability to render clickable internal links that show up as `[note title]` inside a markdown note

i'm not sure if its too tall an order, but certainly not too much to ask. if its possible, could @zadam or anyone describe how to go about such a thing?

**Comment by zadam** [comment]
Hi, in Trilium markdown is just a "code" with syntax highlighting. Markdown is not supposed to be an alternative for text notes, so such features are not planned.
