### ISSUE TITLE
Can't start after Ubuntu upgrade to 22.04

### ISSUE THREAD

**Issue by ktenney** [zadam/trilium#2837]
V 0.50.2, no log file

starting Trilium fails

docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.

ktenney@albert:~$ mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)

On 20.04 there are a bunch of cgroup mounts
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755,inode64)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
...

Thanks,
Kent

**Comment by zadam** [comment]
Hi, I just tested the latest version (0.51.2) on Ubuntu 22.04 and it starts just fine. Both desktop and docker builds. Maybe it's something with your cgroups configuration?

**Comment by ktenney** [comment]
ok, the 2 commands here
https://bigdata-etl.com/docker-cgroup-mountpoint-does-not-exist-unknown
fixed it

Thanks,
Kent
