### ISSUE TITLE
Compatibility issue of data directory or DB file across different versions of trilium notes.(Bug report) 

### ISSUE THREAD

**Issue by jsundhar1985** [zadam/trilium#2843]
### Trilium Version

0.45.9

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 21H1

### Description

Thank you for providing this application. It is very useful and has good features to use.

I am trying to find a solution for custom saving location for the entire DB file. I have tried few different things to make it work but somehow it didn't work.
Initially I had set up the Trilium notes linux server edition (Version 0.45.9) and made some notes in it. I was able to successfully sync it with Trilium notes in my 
windows 10 desktop running the same trilium version 0.45.9 extracted from the Zip bundle. This has been working fine for a long time. 

Today, in my windows 10 laptop, I downloaded the latest version 0.51.2 for windows 64bit and extracted in one of my personal folders and launched the .exe from there.
I understand that this creates couple of folders namely Trilium Notes and trilium-data in C:\Users\MyAccount\AppData\Roaming. 
In one of your wiki posts, you mentioned to backup the data directory as it contains everything you need and a variable confiugration to change the data directory location.
As I wasn't running the linux server at this moment, i thought i will copy the data directory folder "trilium-data" from my windows 10 desktop to my windows 10 laptop.
I used syncthing to do it and synced the trilium-data folder in the desktop to a newly created folder in my laptop.
Desktop folder: C:\Users\MyAccount\AppData\Roaming\trilium-data
Laptop folder: J:\JP\Pers\SNOTE\Notes Tool\trilium-windows-x64-0.51.2\trilium-windows-x64\Tril_DB

I didn't use the directory location which is created by default by the application which is always in the Appdata\Roaming.

Now, whenever i used to launch the application in my laptop, I didn't see my notes and data which was there in the desktop version.
I checked the logs and saw that it is setting the dataDirectory to C:\Users\MyAccount\AppData\Roaming\trilium-data and not the one i copied it.
I tried to understand how to Change the location of data directory but somehow couldn't get a hold as even the wiki didn't had any notes for windows.
I found a guide in the internet to add environment variable via windows Control Panel and added the variable TRILIUM_DATA_DIR and provided the location as J:\JP\Pers\SNOTE\Notes Tool\trilium-windows-x64-0.51.2\trilium-windows-x64\Tril_DB in the laptop. I launched the application again but there were some errors and it was mostly the db version mismatch as far as i could understand.
This time, the application was able to find the location of the "dataDirectory", however it threw the db version mismatch error.
When the application is launched in laptop, i think the application creates a db version 194 and when it tries to read the actual db, it sees the db version as 176 and 
due to this mismatch it doesn't open the application at all. 
This shows that document.db or the entire directory of an older version of trilium notes won't be able to work with a newer version of the trilium notes i.e. compatibility isn't right.

I finally thought to give a try to sync the laptop's trilium notes with the linux trilium notes server. So, I tried to sync the laptop with my linux notes server and it failed.
Error: Could not setup sync since local sync protocol version is 25 while remote is 16. This tells to use same trilium versions on all instances.

What I am trying to understand here is that the Database which is created in an earlier version should be compatible and should be easy enough to use it in the new versions.

If I have to upgrade the Windows Desktop version from 0.45.9 to the latest 0.51.2 - Do we have a simple and straight forward procedure without breaking the application 
performance especially with regards to the database which will be used. As i have already checked, data directory or the document.db of older version cannot be used with 
a newer version of trilium notes in the same platfrom i.e. windows OS. Similar question will be for linux server notes edition as to what is the process for updating the
application to the latest one but not breaking the DB as the DB in linux is also created from an older version of trilium notes.

I was almost about to lose entire data while using the new version as the newer version in my windows 10 desktop didn't understand the data directory structure and it 
didn't even load the notes which were created in the previous version.

Why I am asking this question is because my 3 systems have different trilium versions and the DB or document directory of older version doesn't go with newer
version and this will limit the user's experience of using a new version because the older version DB isn't compatible.

Solution will be helpful. 
Help is appreciated.
Regards,
R J

**Comment by zadam** [comment]
Hi, when starting a new version of the application, it will check the DB version and will upgrade the database if necessary.

> I launched the application again but there were some errors and it was mostly the db version mismatch as far as i could understand.

If you provide the errors (or even better the log file) then maybe I will be able to help ...

> Error: Could not setup sync since local sync protocol version is 25 while remote is 16. This tells to use same trilium versions on all instances.

This means that you have a (very) different version of Trilium on the client and server, they don't know how to talk together. You need to have same version of Trilium on both server and client, then they will sync together.

**Comment by jsundhar1985** [comment]
Hello Zadam,

Thank you for the reply.
I was reading the logs myself to get some understand as to find out at which point the application isn't opening.
As you said, the application will check the DB version and will upgrade if required. This is correct as I tried the newer version in my windows 10 laptop and it did upgrade the DB and launched the application with the updated notes.

As far as the Client-Server communication, both need to have the same version of trilium notes.

I am wondering if you could guide me a little bit to save the data directory folder to a different location (different partition drive, Eg: D; Drive instead of the regular C; Drive)in windows environment because last time when i tried to change it or even to use the variable TRILIUM_DATA_DIR, i couldn't get it to work. 
If there is a method or a way to tell the application to look in for the Directory folder in a different partition drive, will be helpful.
Appreciate the work.

Thank you,
Regards,
R J
