### ISSUE TITLE
(Bug report) Mermaid diagrams are not exported correctly

### ISSUE THREAD

**Issue by abbasc52** [zadam/trilium#2844]
### Trilium Version

0.51.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11 21H2

### Description

When using Mermaid diagrams, when you click on export -> as html , the export only generates text version of mermaid in exported html

Expected behavior
Mermaid diagrams should be exportable as html or svg or png.

**Comment by marcarneg** [comment]
I'd like to second this very much! I'm using trilium successfully to organize a lot of literature and notes, and really appreciate the integrated mermaid plugin. But without a functioning print/export function, it is extremely limited. I'd also argue, that "embedding" a mermaid-graph into another note (like an embedded picture) would be extremely useful!

**Comment by zadam** [comment]
Hi, export is planned.

Embedding diagrams into notes is already supported via "include note" feature:

![image](https://user-images.githubusercontent.com/617641/176544489-2948c27c-3098-4d52-80b8-0aacbac46d92.png)

**Comment by zadam** [comment]
0.54 has an export button:

![image](https://user-images.githubusercontent.com/617641/182682083-c3188342-98af-49c2-b464-12566357dd17.png)
