### ISSUE TITLE
(Bug report)upload a mp4, then no respond,faild.

### ISSUE THREAD

**Issue by zomboo** [zadam/trilium#2857]
### Trilium Version

0.51.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windows11 21H2

### Description

when import some big file , like a zip file,size is 1G, or a mp4 file,size 2G, when click the upload button, no progress, no respond, and failed ,no file import.
and when the file'name with unicode character,like japanese,chinese ,it also show above phenomenon.
hope solve big file (with over *G size ) upload, and speed , best with a progress bar.

**Comment by zadam** [comment]
Hi, Trilium is not designed to be a big file storage, it can't really handle such big files. It's recommended to upload files <= 100 MB.

There are other softwares which are dedicated for this purpose.

> and when the file'name with unicode character,like japanese,chinese ,it also show above phenomenon.

Can you post an example of such filename? I just tried with random japanese name and it worked fine. Or was this file also big?

**Comment by zomboo** [comment]
> Hi, Trilium is not designed to be a big file storage, it can't really handle such big files. It's recommended to upload files <= 100 MB.
Trilium  really good, when I upload the font source-han-serif-1.001R.zip(1.9G), it works a bit slow ,but success insert into the note. very good.
I hope use Trilium erverwhere, so I really also hope it could be my files manager :)
but when insert a mp4 , failed. file name is 龙猫.720p.国粤日三语.BD中字.mp4
here is the screen image.
![image](https://user-images.githubusercontent.com/3627672/169180981-fa8104d7-76ea-48ba-91ec-0e6bf5aa17ff.png)

**Comment by zadam** [comment]
It's not about the filename most probably, I managed to upload a file with this name just fine:

![image](https://user-images.githubusercontent.com/617641/169398940-225e0b6f-a809-4bc5-8bf5-828a68dd5f32.png)

But I can see that the file is 1.6 GB and that's the problem probably. Handling such large files needs special consideration which Trilium doesn't make (e.g. generally streaming content while Trilium just loads the whole thing into memory).

**Comment by zomboo** [comment]
Thanks for reply , I think so. And I also find Trilium can't support play some video files in note, like .flv files.
But , Trilium really a  good tools, thank  you very much for developing Trilium.
