### ISSUE TITLE
(Feature request) Inserting external image (URL) feature

### ISSUE THREAD

**Issue by Rayme** [zadam/trilium#2859]
### Describe feature

Trilium is brilliant. I use it everyday, on my 3 PCs and mobile phone.

I know that trilium stores everything in a SQLite database, but sometimes I would like to insert an image which might be large or not that important. In this case, it would be great if I can insert it in a way like ![img](the URL link) in markdown or something like that. I doesn't matter if I can't load that image offline (because it is not important, I store important or frequently used image locally).

Thank you for building such an amazing FOSS!

**Comment by zadam** [comment]
I guess your best bet is to just make a link to it.

Whenever Trilium sees an image, it tries to make a local copy. But it recompresses it and makes it smaller, so size might not be an issue.

**Comment by Rayme** [comment]
> 

It seems the best way. Is it able to add this function (shows an external linked image) to trilium?

**Comment by zadam** [comment]
Hi, I have added an option to disable the auto-download of referenced images, I think that should fix your problem.

![image](https://user-images.githubusercontent.com/617641/169650696-ebd7460b-cadf-495a-a54f-92fa124d33c2.png)

This is going to be in 0.52

**Comment by Rayme** [comment]
> Hi, I have added an option to disable the auto-download of referenced images, I think that should fix your problem.
> 
> ![image](https://user-images.githubusercontent.com/617641/169650696-ebd7460b-cadf-495a-a54f-92fa124d33c2.png)
> 
> This is going to be in 0.52

Thank you for your great work!
