### ISSUE TITLE
Support OPML 2.0

### ISSUE THREAD

**Issue by dabeeeenster** [zadam/trilium#286]
Im trying to migrate data from Workflowy - it exports as OPML 2.0 which can't be imported into Trilium. The import fails silently.

**Comment by zadam** [comment]
Would it be possible to attach an example OPML v2 export?

**Comment by dabeeeenster** [comment]
```
<?xml version="1.0"?>
<opml version="2.0">
  <head>
    <ownerEmail>
      ben+workflowy@solidstategroup.com
    </ownerEmail>
  </head>
  <body>
    <outline text="23r23r23r">
      <outline text="weoufgwiufgweiuogf" />
    </outline>
    <outline text="erghoiergiophergpiherg">
      <outline text="warogjerwegw" />
      <outline text="egp" />
    </outline>
    <outline text="er[go" />
  </body>
</opml>
```

**Comment by zadam** [comment]
Hmm, this looks exactly like OPML v1 except for the version field. 

What I heard some time ago is that OMPL 2.0 implementations differ greatly from the standard and that's a reason I'm trying to get some real world samples ...

**Comment by washere** [comment]
importing small files from Notecase Pro works but big files from Notecase Pro often fail.

**Comment by zadam** [comment]
Hmm, when I changed it to 1.0 it didn't import correctly because of missing "title" attribute in the outline nodes. But after filling that attribute in, it imported correctly ...

**Comment by zadam** [comment]
fixed in master
