### ISSUE TITLE
(Bug report)./node/bin/node:bad option: --harmony_top_level_await 

### ISSUE THREAD

**Issue by agent-kimbley** [zadam/trilium#2860]
### Trilium Version

0.48.9

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

arch

### Description

today when run trilium like before suddenly echo` ./node/bin/node:bad option: --harmony_top_level_await `

**Comment by zadam** [comment]
I assume you're running the server version?

I don't know what this is about to be honest, trilium doesn't set `--harmony_top_level_await` flag, but even if it did, the supplied node.js version does support it. 

Can you try `./node/bin/node --version`?

**Comment by agent-kimbley** [comment]
v14.18.1

**Comment by agent-kimbley** [comment]
> I assume you're running the server version?
> 
> I don't know what this is about to be honest, trilium doesn't set `--harmony_top_level_await` flag, but even if it did, the supplied node.js version does support it.
> 
> Can you try `./node/bin/node --version`?

> v14.18.1

v14.18.1

**Comment by agent-kimbley** [comment]
It semms working again, After reboot and check node‘s version.
