### ISSUE TITLE
(Feature request) 

### ISSUE THREAD

**Issue by ArthasLich** [zadam/trilium#2863]
### Describe feature

When I copy the output of the linux terminal to trillium, the originally aligned text is displayed unaligned in trillium. I think this is caused by the difference between the width of the null character displayed by trilium and the width of the displayed other characters. I hope this situation can be improved. Thanks!

**Comment by zadam** [comment]
Hi, it's a font issue - for text you typically use fonts which don't have fixed width, for code monospace.

You can "fix" that by pasting into the "code block" or into code notes:

![image](https://user-images.githubusercontent.com/617641/169649876-e5e50395-ed5b-4caf-8d6e-e84410e40f00.png)
