### ISSUE TITLE
(Bug report)When delete several notes, the delete list in confirm dialog lost some selected note

### ISSUE THREAD

**Issue by zomboo** [zadam/trilium#2865]
### Trilium Version

0.51.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windows11 21H2

### Description

Today I want to delete several notes, but when I press 'shift' key  and click mouse to select notes , then right click to delete, I find the delete list in open dialog is not All notes that I had select.
show in  gif like this:
![trilium_bug](https://user-images.githubusercontent.com/3627672/169673688-526a684f-ef7a-47bb-95c3-447d358e0574.gif)

**Comment by sigaloid** [comment]
I think this is intended behavior. If a note is not italicized it's not selected for deletion. Just having a note open when you begin selecting doesn't automatically include it for deletion. (Assuming you're referring to the one you have open not being included)

**Comment by SiriusXT** [comment]
It is recommended to add the following CSS styles to the theme file so that the selected items will be both italicized and underlined,
`span.fancytree-selected span.fancytree-title{
    text-decoration:underline;
}`
![图片](https://user-images.githubusercontent.com/37627919/169677854-1db8866c-6dac-4a79-bd0d-eaae8d274548.png)

**Comment by zadam** [comment]
@sigaloid is right, there's a difference between active note and selected note, active is not automatically part of multi-selection.

@SiriusXT I added the underline to add some more visual difference as suggested.
