### ISSUE TITLE
Support Latex

### ISSUE THREAD

**Issue by heytitle** [zadam/trilium#287]
Is it possible to render latex inside notes?

**Comment by trishmapow** [comment]
+1 this is very important for me. A similar note taking app, Noteable does this through KaTex.

**Comment by zadam** [comment]
The trouble as I see it is that CKEditor doesn't support such mixed content inside one note yet. Until they get it I might implement it purely as a renderer of code note (so it would be all latex or all text) but that's not an ideal solution ...

**Comment by artifacter** [comment]
May be KaTeX?

**Comment by wesrer** [comment]
@zadam Any updates on this? It would be very helpful even if you could implement your solution of rendering latex code notes

**Comment by davidenitti** [comment]
any update on this?

**Comment by zadam** [comment]
Unfortunately no, still planned at some point, but still not a priority. I'm trying to get basic things right first before expanding into other things like math support.

**Comment by sprajagopal** [comment]
Was hoping to move away from Roam to Trillium (because this is local). But without latex, a large number of use cases cannot be handled in this. Hope to see this soon!

**Comment by Engr-AllanG** [comment]
bumping thread to show support for the idea

**Comment by zadam** [comment]
I did some quick experiments with [ckeditor5-math](https://github.com/isaul32/ckeditor5-math) in [math](https://github.com/zadam/trilium/tree/math) branch and the basics seem to work, but there are couple rough edges - so far lazy loading of renderer is not supported, not clear how we'll support latex in read only notes etc.

**Comment by zadam** [comment]
The experiment has been coming along nicely - you can expect first beta of 0.45 soon.

**Comment by millernb** [comment]
Can this issue be closed now? https://github.com/zadam/trilium/wiki/Text-notes#math-support

**Comment by zadam** [comment]
Yes.

**Comment by BrettBass** [comment]
There is no compiling laTex code tho right?
