### ISSUE TITLE
(Bug report) file insert to  note, the note info show  a blank square.

### ISSUE THREAD

**Issue by zomboo** [zadam/trilium#2872]
### Trilium Version

0.51.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windows11 21H2

### Description

when insert some type  file, like .docx or .xlsx into note, the note info will show a  blank square.
like this.
![image](https://user-images.githubusercontent.com/3627672/170026598-9ef651f3-5d28-4167-9bd0-82f5aeee50d8.png)

**Comment by zadam** [comment]
I'm not sure what you expect, but there's no office document preview or anything like that ...

**Comment by zomboo** [comment]
normal is this:
![image](https://user-images.githubusercontent.com/3627672/170212205-4198f4a6-11e1-485e-ab03-b3fda46aa3d9.png)
and the hollow rectangle position with red arrow :
![image](https://user-images.githubusercontent.com/3627672/170212474-6c8add4e-1c2e-4f51-8805-119ece044bd4.png)
as the normal note info,  there is no the hollow rectangle, why hava a the hollow rectangle.

**Comment by zadam** [comment]
Oh, I see, I misunderstood.

It's a horizontal scrollbar because the line is too long (caused by long mime type)

**Comment by zomboo** [comment]
I misunderstood :)
thanks.
