### ISSUE TITLE
(Feature request) The database file is too big than mybase desktop

### ISSUE THREAD

**Issue by zomboo** [zadam/trilium#2873]
### Describe feature

Today, I have move data from mybase desktop to trilium, but when I backup the database, I found the same content, mybase desktop is 203.6MB,
![image](https://user-images.githubusercontent.com/3627672/170027465-5f61c441-63a4-48f4-bbce-d8895269fc3d.png)
and the database of trilium is 703.4MB
![image](https://user-images.githubusercontent.com/3627672/170027971-978952a6-b4e9-416e-809c-47745085bfd0.png)
I had try the vacuum database, but it decrease a bit, remain 689M.
hope the database size could samller.

**Comment by zomboo** [comment]
Thanks ,it help I decrease the database size to 187M.
thank you.

**Comment by Ivy-End** [comment]
What's your explorer software, that's so cool.

**Comment by jinxiaoman** [comment]
> Thanks ,it help I decrease the database size to 187M. thank you.

Hello, how do you migrate mybase desktop data to trilium? I am also an old user of mybase desktop. I want to migrate some notes but I don’t know how to do it.

**Comment by simonfoobar** [comment]
Hello, all my notes size is  (subtree size: 35.7 MiB in 218 notes) 
but the document.db file took ~400MB, I have cleandup all mentioned things. Is anything more i can do?
Thx

**Comment by zadam** [comment]
VACUUM in Options -> Advanced would be the best bet:

![](https://github.com/zadam/trilium/assets/617641/421f91c0-f28b-4300-a3fd-5c2d44cc19ac)
