### ISSUE TITLE
(Bug report) Failed to get the backlinks of a note

### ISSUE THREAD

**Issue by Qining** [zadam/trilium#2877]
### Trilium Version

0.51.2

### What operating system are you using?

macOS

### What is your setup?

Server access only

### Operating System Version

macOS 12.4 Monterey

### Description

Usually I use Safari browser to access my self hosted server. I do use Windows app some time. But I don't think the issue is related to the app or the frontend.

For one note, my server always fails to get the backlinks of it. I've tried multiple browsers (safari and chrome) and windows app, neither of them works. Following screenshots show the problem.

<img width="165" alt="Screen Shot 2022-05-27 at 9 17 31 AM" src="https://user-images.githubusercontent.com/2983685/170707820-115ca6fb-dd32-4c9e-840d-b0bb1a225c67.png">

<img width="352" alt="Screen Shot 2022-05-27 at 9 17 40 AM" src="https://user-images.githubusercontent.com/2983685/170707865-bf86cd62-744d-4f12-bb10-747e93d69004.png">

<img width="1012" alt="Screen Shot 2022-05-27 at 9 17 57 AM" src="https://user-images.githubusercontent.com/2983685/170707930-e35e9f54-d124-41ff-9ec1-3b7f7d077db9.png">

The error log from the server side says there is a type mismatch exception:

<img width="1241" alt="Screen Shot 2022-05-27 at 9 22 40 AM" src="https://user-images.githubusercontent.com/2983685/170708060-deca037d-c8b5-4b6c-afa1-f604e21f1c33.png">

This issue is only found on one note. The backlinks on my other notes are working properly.

At the end, I want to say thank you to the author and all the contributors for building such an amazing tool!

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, I'm not sure when exactly this happens, but I made the code a bit safer handling this.
