### ISSUE TITLE
(Privacy Question) 

### ISSUE THREAD

**Issue by matty0blake** [zadam/trilium#2884]
### Describe feature

i am a little concern about the privacy. i love the software it exactly what i have been looking for in the past 2 year. and it really help me. and i have searched the code and monitor the builded  one. 
i couldn't find a privacy for data collection document.
so i wonder what type of data do you collect or the software send at any point.

thank you for you hard working <3

**Comment by zadam** [comment]
Hi, there's no data collection at all. No telemetry, no analytics etc.
