### ISSUE TITLE
(Feature request)  how to custom font style in note

### ISSUE THREAD

**Issue by zomboo** [zadam/trilium#2885]
### Describe feature

I'd like to use some font style like art font.
but there is no choice to select font style like other(eg. evernote) app's  editor.
How to change the font style in note .except to edit html note.

**Comment by XXXJetfireXXX** [comment]
Though, if you really want to change the font - custom CSS themes are all about it.
https://github.com/zadam/trilium/wiki/Themes
In `root` you can change the following variables to change the font to your liking:
![image](https://user-images.githubusercontent.com/43646178/171232549-699d251c-905a-4e7a-bf5a-18c240a12333.png)

**Comment by XXXJetfireXXX** [comment]
Though, like @zadam said, the most important aspect of font selection for the notes is readability. If a certain font looks nice, but is painful to read, your eyes are gonna get tired pretty quickly.

**Comment by zomboo** [comment]
Thanks for reply. I get it.
