### ISSUE TITLE
(Bug report) Error on search `note.` as keyword

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#2889]
### Trilium Version

0.51.2

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Manjaro

### Description

Open desktop client and just search for `note.` in quick search.

Got error message.
```
Error when calling GET /api/quick-search/note.: 500 - Cannot read properties of undefined (reading 'token')
```
Also happens in browser.

I was writing some backend js and try to find some example to manipulate the note object and got this. (BTW search `note\.` works).

**Comment by zadam** [comment]
`note.` is a "special" prefix since it provides access to e.g. `note.dateCreated` properties for comparison etc. But the error should surely be more explanatory ...
