### ISSUE TITLE
[bug] "Cut & paste selection to subnote" not working after opening a new tab / split

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#2895]
### Trilium Version

0.51.2

### What operating system are you using?

Windows

### What is your setup?

Server access only
Browser: Firefox 101.0

### Operating System Version

Windows 10 version 2004

### Description

Reproduction steps:
1. Open a note (A)
2. Open another note in a new tab / split (B)
3. "Cut & paste selection to subnote" does not work anymore in pane A

You will get an empty note after clicking "Cut & paste selection to subnote".

**Comment by WPum** [comment]
Related #1182

**Comment by zadam** [comment]
Hi, thanks for the reproduction steps, I think I was able to fix this.
