### ISSUE TITLE
(Feature request) Please add more information to the Wiki

### ISSUE THREAD

**Issue by ThetaEdra** [zadam/trilium#2896]
### Describe feature

Please add information about various topics to the Wiki

### Additional Information

Currently i try to decide if i want to use Trillium because i really like the features so far. But before i really go through the effort of setting up my server for sync and everything i have some more questions that the wiki did not answer so far. Here is the list of information i also wish to be added to the wiki:

1.  Can you share encrypted notes? If so how is ist handled that the notes stay E2E and will you need to enter a Password or does it work through URL? If not please also add this to the Wiki. I used CodiMD before and id like to share notes with specific groups only. I could not find any information about sharing encrypted notes on the encryption or sharing page. 
2. Is there or will there be a Web Editor? There is a Server Installation but so far it seems to be only for syncing and sharing notes which seems kinda disappointing. Will there be a Web Editor like CodiMD has or am i overlooking anything and there is one already? Please add a hint as the mobile and Desktop Client provide a Frontend it would be nice knowing more about (planned) Server Frontends.
3. I like to see the Source Code of notes like i can in Jooplin but i could not find information on how to dispaly Notes in Source Code view/Markdown View without them rendering it instead or having to export them first. When writing notes i like to the see Source and when headings are displayed automatically i have to figure out which one i used before first which is rather annoying.
4. It would be awesome if you could add a correctly tested docker compose file to the deployment pages. I like that you already have the nginx and apache reverse Proxy configuration but using docker compose for the image makes the system service obsolete (restart unless stopped could also be used) and makes it possible to really quickly test everything (either with webserver included or without).
5. For Apache and TLS there could be a hint to use Certbot which makes a lot of Lets Encrypt configuration easier.

Also it would be nice if the amount of open Github issues could be reduced. Its hard to search for duplicates with this many issues especially as many of them could be closed already.

**Comment by zadam** [comment]
Hi,

> Can you share encrypted notes?

No and it's not really planned ATM.

> Is there or will there be a Web Editor?

Server installation is actually a fully functioning instance - i.e. "web editor".

> I like to see the Source Code of notes like i can in Jooplin

It's possible to check the source code (HTML): 
![image](https://user-images.githubusercontent.com/617641/171996237-a7fd8110-08ce-4390-a89a-4188a1293258.png)

But this is view only. Editing can be done only through rich text editor.

> For Apache and TLS there could be a hint to use Certbot which makes a lot of Lets Encrypt configuration easier.

I don't have much experience with certbot, you're welcome to add useful information to the wiki (it is publicly editable). Thanks.

**Comment by ThetaEdra** [comment]
If there should be a ever a planned implementation to allow password protected note sharing id probably suggest to either make it password protected or probably better use the URL to decrypt it ClientSided like Mega did with files. This way i can just share the link to a note. It would be important to have some kind of feedback that a note is published and a possibility to renew the password/url. Just some ideas.

Could you share some more Screenshots from the Web Editor and maybe add them to the Wiki? It would be nice to see how the Web Editor looks like (Landing Page / Not edit). Also how do you authenticate in the Web Instance?

Is it planned to allow editing nodes in source mode? I really dont like that the markdown is rendered automatically. An option to turn it off would already be good enough. 

I can add some information about certbot, probably a reference is enough. One can just use it and run it to add a Lets Encrypt Certificate to Apache2 - its installed automatically given that the http virtual hosts config is valid as well as the users inputs.

**Comment by zadam** [comment]
> probably better use the URL to decrypt it ClientSided like Mega did with files

Trilium supports encryption, but this is fundamentally incompatible concept with sharing. Encrypted notes are for the owner only. Shared notes can be only unencrypted and that probably won't change even if they will be password protected.

> Could you share some more Screenshots from the Web Editor and maybe add them to the Wiki?

Web app is essentially identical to the desktop app. All the screenshots apply to both web and desktop editions.

> Is it planned to allow editing nodes in source mode? I really dont like that the markdown is rendered automatically.

No, Trilium actually doesn't use markdown. It uses a WYSIWYG HTML editor and Markdown doesn't come into play there.

**Comment by ThetaEdra** [comment]
I added the comments to the Wiki.

Would be awesome if youd add support to toggle off CKEditors automatic rendering or some options to work with the "markdown code" instead of having everything rendered instantly. It works in editors like word because it displays for example the text size and header size in the top menu bar. In this editor with no elements that display the attributes and no way to see the source its a guarantee that notes will become a mess. I think this is a huge disadvantage over other editors and maybe youll reconsider allowing code edits or displaying the underlaying structure to advanced users.
