### ISSUE TITLE
Strange behavior saving empty attributes

### ISSUE THREAD

**Issue by mahdi1234** [zadam/trilium#29]
- have a node which already has some attribute
- Alt+A
- click twice "Add new attribute" and click "Save" without actually filling anything

"Note attributes" dialog appears again this time with single empty attribute.

**Comment by zadam** [comment]
Yep, can reproduce - incorrect handling of empty attribute causes whole knockout binding to fail. Will fix.

**Comment by zadam** [comment]
Fixed in 873ea67e9ce1ed780a7b0b1104ecae9e7cd2e555
