### ISSUE TITLE
(Bug report) Too many redirects, client cant sync but api status page looks correct

### ISSUE THREAD

**Issue by fusrohdan** [zadam/trilium#2902]
### Trilium Version

0.51.2

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 21H1 client, with server running behind docker in Ubuntu server 20.04

### Description

The trilium notes app refuses to sync. From the same PC, if I browse to the web portal trilium loads fine and all my notes are there.  Same from my mobile over 4G. Full client on my home pc works, but not my work PC.  No policies are blocking it at work (I am an IT sysadmin and have checked fw logs)

When I sync I get the following error:
`Sync failed: Request to GET https://trilium.REDACTEDDOMAIN/api/setup/status failed, error: Error: net::ERR_TOO_MANY_REDIRECTS
`
If I browse to `https://trilium.REDACTEDDOMAIN/api/setup/status` I see the following
`{"isInitialized":true,"schemaExists":true,"syncVersion":25}`

The backend log presents me with the following:

`08:23:14.145 sync failed: Request to GET https://trilium.REDACTEDDOMAIN/api/setup/status failed, error: Error: net::ERR_TOO_MANY_REDIRECTS
stack: Error: Request to GET https://trilium.REDACTEDDOMAIN/api/setup/status failed, error: Error: net::ERR_TOO_MANY_REDIRECTS
    at generateError (C:\Program Files\trilium-windows-x64\resources\app.asar\src\services\request.js:191:12)
    at ClientRequest.<anonymous> (C:\Program Files\trilium-windows-x64\resources\app.asar\src\services\request.js:58:47)
    at ClientRequest.emit (node:events:394:28)
    at ClientRequest._die (node:electron/js2c/browser_init:101:8391)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7128)
    at SimpleURLLoaderWrapper.emit (node:events:394:28)
    at SimpleURLLoaderWrapper.callbackTrampoline (node:internal/async_hooks:130:17)`

Happy to provide more info if needed.

Thanks for the awesome product!

**Comment by fusrohdan** [comment]
> Hi, there must be some network proxy between the client and server which is doing the redirects.
> 
> 
> 
> `api/setup/status` is a public endpoint (no auth) and Trilium never issues redirects on its own for this endpoint.

Hey,

Thanks for replying.

There's no proxy no.  Is there anything else that could cause this?

**Comment by zadam** [comment]
Is trilium exposed directly or through some reverse proxy?

It's difficult to guess, but some network element between the client and server is causing the redirects.

**Comment by fusrohdan** [comment]
This is now resolved.  I made no changes and it just started working again.
