### ISSUE TITLE
(Feature request) Environment variables USER_UID & USER_GID

### ISSUE THREAD

**Issue by bill88t** [zadam/trilium#2913]
### Describe feature

This feature request arises as a result of #2907.

Well, if you are planning on keeping the containers running always as root, could you at least make it accept env variables USER_UID & USER_GID for the data?
These env variables are commonly used for containers to specify the uid & gid in which they run their actual app and save their data.

Having root-owned data in your files is not fun, especially when you want them accessible by other software that run under your uid & gid.

Having no way to make the data correctly save under the proper uid & gid is a breaking change, forcing at least me to permenantly stick to :0.51-latest

**Comment by zadam** [comment]
Hi, most of the changes to Dockerfile are user contributed, I'm myself am not an expert on all the different deployment options of Docker.

Is it possible to combine current su-exec approach with allowing to configure UID/GID or would this need a second image being built?

In any case help on this would be appreciated.

**Comment by bill88t** [comment]
Took a quick look into the Dockerfile and start-docker.sh
it should be as simple as reading the variables and setting 'node' user's id's to be those once start-docker.sh is started.
I'll try doing it myself in the following days

**Comment by bill88t** [comment]
#2917 is provided to solve this

**Comment by bill88t** [comment]
Closing the issue, as the pr has been merged.
It's 12 am, imma update the wiki tomorrow.
