### ISSUE TITLE
render pdf attachments

### ISSUE THREAD

**Issue by ewingrj** [zadam/trilium#292]
It would be great if pdf attachments were rendered directly in trilium. I'm fairly certain that electron supports this.

**Comment by ctlevi** [comment]
I looked into seeing if this was an easy addition (because I really want it). Apparently, the native PDF viewer hasn't worked since version 2 of electron per https://github.com/electron/electron/issues/12337. There looks like there might be some workarounds to use [electron-pdf-window library](https://github.com/gerhardberger/electron-pdf-window), but I haven't investigated much further yet.

**Comment by zadam** [comment]
Oh, that's a bad news. I was pretty excited for this as well. I'm not sure if that electron-pdf-window is the same thing as it seems to me to open a new window and render PDF there. What I had in mind was rendering the PDF inside Trilium's detail pane, but if this needs to open a new window then it is pretty similar to just opening system PDF reader ...

**Comment by cculbreath** [comment]
Looks like a fix is imminent:
https://github.com/electron/electron/pull/17163

**Comment by StoltHD** [comment]
can't you implement pdf.js instead? It also read the annotations in a pdf...

https://github.com/mozilla/pdf.js/issues/7135

**Comment by Sytten** [comment]
The electron fix is merged

**Comment by zadam** [comment]
Implemented in https://github.com/zadam/trilium/commit/e7aa84435bcffaf8ac9ce4e8798fcdab202c5cce (electron 9 supports PDF previews again).

**Comment by dereitz** [comment]
> Implemented in [e7aa844](https://github.com/zadam/trilium/commit/e7aa84435bcffaf8ac9ce4e8798fcdab202c5cce) (electron 9 supports PDF previews again).

Should this work in the latest Mac release?  I'm using 0.40.6 with a note exported from Evernote as a test that I imported into Trillium.  When I open that note, it shows a PDF attachment with a "Download" and "Open" button.  Is there a setting/preference I need to enable or perhaps something else I'm missing?  I appreciate your efforts on supporting this feature in Trillium!!

**Comment by zadam** [comment]
No, this will be in 0.41 release (not yet stable)
