### ISSUE TITLE
Link dialog should not prefer child notes

### ISSUE THREAD

**Issue by Allzi** [zadam/trilium#2927]
### Describe feature

Currently the note seach in linking dialog prefers heavily child notes, burying the note I want to the end of the list.
This is bad for workflow when the hierarhcy gets deep, and linking the correct note gets hard.
The ordering should be changed so that when I type a note's name it should be the first option in the list.

![image](https://user-images.githubusercontent.com/8063936/174434053-4e96f12b-9ef2-4587-8baa-0a1c5f1fd3a4.png)

**Comment by zadam** [comment]
Hi, the problem is that the child note (with its complete path) has more word matches on the search string and therefore receives higher score than the parent.

I have added some extra weight on matches on the note's title as opposed to whole note path's matches, which should help.

**Comment by Allzi** [comment]
Thanks, it should at least help a bit.
