### ISSUE TITLE
Imported a directory of markdown and items not showing in links

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#293]
New user.  I started trilium and after playing a while I imported a directory of markdown.  The directory had folder and documents within folders.  I can see all of the items are imported and the structure preserved.  However, when I go to the demo items and try to link to one of the imported notes, I don't see the notes listed in the search list.

**Comment by zadam** [comment]
That looks like a bug in caching the autocomplete results. Thank you for reporting it!

In the meantime I think restarting the app will fix the issue by clearing the cache.

**Comment by pcause** [comment]
that seems to work as a work around
