### ISSUE TITLE
(Bug report) followLinkUnderCursor shortcut not working for "link title mirrors the note's current title"

### ISSUE THREAD

**Issue by capi** [zadam/trilium#2932]
### Trilium Version

0.52.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 Pro, 21H2, 22000.739

### Description

Following the link under cursor, by default bound to `Ctrl-Enter`, works for external links and for links to internal pages, unless the link type is "link title mirrors the note's current title".

Can also reproduce this with the desktop edition on Windows 11, and the browser edition on Firefox.

Here is a short screen recording to demonstrate the issue:

https://user-images.githubusercontent.com/254852/174671913-b515508c-3bb1-4269-bb75-d17e57ef98d2.mp4

**Comment by zadam** [comment]
Hello, thanks for reporting, fixed.
