### ISSUE TITLE
(Bug report) The template does not appear in the bar when I create a child

### ISSUE THREAD

**Issue by dafmdev** [zadam/trilium#2941]
### Trilium Version

0.52.3

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Heroku 20 with docker

### Description

I am reading this [documentation](https://github.com/zadam/trilium/wiki/Template)

I already put #template in the note attributes

But when I go to insert a daughter note, my template does not appear as in the second photo

**Comment by zadam** [comment]
Hi, sorry for confusion, the feature is available only in the latest [v0.53.0-beta](https://github.com/zadam/trilium/releases/tag/v0.53.0-beta) which the documentation does not mention.

**Comment by dafmdev** [comment]
Thanks
