### ISSUE TITLE
(Feature request) Add password access to shared links

### ISSUE THREAD

**Issue by akatong** [zadam/trilium#2942]
### Describe feature

When a node is given a public link, it is recommended to add a password access feature in order to allow only a few people to have access to the node content.
Further, we can set any node to have a separate access password, and, each node can have a different password.
Hope this suggestion can be adopted :)

**Comment by r3cgm** [comment]
Thanks for submitting this feature request.  I too wish we could have more granular permissions control, including this specific use case of being able to provide a distinct password to specific people to access a particular node. +1!

**Comment by zadam** [comment]
Hi, this is planned, already reported in https://github.com/zadam/trilium/issues/2781 so I will close this one as a duplicate.
