### ISSUE TITLE
(Bug report) Dragging an open workspace tab out opens hundreds of new windows

### ISSUE THREAD

**Issue by asoftbird** [zadam/trilium#2944]
### Trilium Version

0.51.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 Home Version 21H2 19044.1766 Windows Feature Experience Pack 120.2212.4180.0

### Description

Upon hoisting a file as a workspace tab (top of the screen) and dragging it out of the main screen to open a new window, there's no debounce- it keeps opening new windows in the same place until the mouse is released. Expected behavior is obviously opening _one_ extra window. Holding it for long can open _hundreds_ of windows. See attached video for reference. Video includes a few blurred sections to hide personal informations. https://www.youtube.com/watch?v=1ZvNrI3VnkY

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, it's been fixed.
