### ISSUE TITLE
(Bug report) Render Note also rendering parent and sibling notes?

### ISSUE THREAD

**Issue by ferrlen** [zadam/trilium#2949]
### Trilium Version

0.52.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Home 21H2, 10.0.19044 Build 19044

### Scenario:

Say I have these notes, parent note being a direct child of root:

> Text Note parent
    > Text Note child 1
    > Text Note child 2
    > Render Note
    > HTML code note

I'm rendering in Render Note the HTML from "HTML code note" (`Note type: Code/HTML`).

Code from HTML code note:
```html
<style>
  p {
    color: red;
  }
</style>
```

Render Note has no content, only this Owned Attribute: `~renderNote=HTML code note`.

### Bug:

If I reload the frontend, Text Note child 1 and 2 are normal. However, if I go to Text Note parent, everything appears red, and if I now go back to child 1 or 2, their text is red as well. If I reload the frontend, their text color goes back to normal.

My expectation was that Render Note would only render the html code and not affect any other notes. Am I misunderstanding it?

Thanks

**Comment by zadam** [comment]
Hi, your style declaration is global and once rendered, it will affect all paragraphs in the whole DOM tree. 

That's just how CSS works, there's no implicit scoping - the person writing HTML/CSS is responsible for proper scoping using e.g. classes.
