### ISSUE TITLE
Text Size Options

### ISSUE THREAD

**Issue by washere** [zadam/trilium#295]
Any serious outliner needs to have Text Size options.

The master zoom level for the app is not ideal. And not the standard by any means.

Other aspects such as font types are also standard.

But font size is a must and a much needed start.

**Comment by zadam** [comment]
This was actually planned for 0.28, but recent storm of issues will probably push it a bit later.

So far I plan to have separate setting for text pane, tree pane and then probably UI font (for things like Options etc.)

**Comment by washere** [comment]
Sounds even better.

**Comment by zadam** [comment]
fixed in master and will be release in 0.28
