### ISSUE TITLE
(Feature request) 

### ISSUE THREAD

**Issue by john3588** [zadam/trilium#2955]
### Describe feature

Internal link to another node

### Additional Information

Can Trilium do internal links from one topic to a node in another topic? If so what is the format? Thanks

**Comment by sigaloid** [comment]
https://github.com/zadam/trilium/wiki/Links#internal-links-to-notes

**Comment by john3588** [comment]
Can you point me towards information about installing on a usb drive.

~~_/) ~~ John Frost ~~_/) ~~

AK2T
Custom Data, LLC
2417 Healy Lane
Lexington, KY 40909
PO Box 55686
Lexington, KY 40555
Cell 859-421-0707<tel:859-421-0707>
***@***.******@***.***>

**Comment by Nriver** [comment]
run trilium-portable.bat

**Comment by john3588** [comment]
Run it to install? Or after install, run it to start?



John Frost
AK2T
2417 Healy Lane
Lexington, KY 40509
859-421-0707



-------- Original message --------
From: Nriver ***@***.***>
Date: 7/6/22 9:19 PM (GMT-05:00)
To: zadam/trilium ***@***.***>
Cc: "John B. Frost" ***@***.***>, Author ***@***.***>
Subject: Re: [zadam/trilium] (Feature request) (Issue #2955)


run trilium-portable.bat
