### ISSUE TITLE
Make Tree Pane Divider Resizable by Dragging with Mouse

### ISSUE THREAD

**Issue by washere** [zadam/trilium#296]
The size of the tree pane was discussed below as in below links.

HOWEVER, the standard in 2 pane outliner apps is usually to be able to drag the vertical divider line between the 2 panes by the mouse.

please do not close this issue until dragging the divider horizontally by the mouse is implemented.

Thank you.

Size of the tree discussions, not dragging by mouse as in this issue:
https://github.com/zadam/trilium/issues/89
https://github.com/zadam/trilium/issues/176

**Comment by zadam** [comment]
implemented in master
