### ISSUE TITLE
(Bug report) toc widget sometimes dont work

### ISSUE THREAD

**Issue by phyxnj** [zadam/trilium#2962]
### Trilium Version

0.53.1-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windos 10

### Description

In read-only mode, the toc widget cannot jump when click heading. It appear on crawled pages which the entire page is wrapped in a div tag. So the widget can't match h tag by traverse it's children.

**Comment by phyxnj** [comment]
> 

https://segmentfault.com/a/1190000041463008?utm_source=sf-similar-article

**Comment by zadam** [comment]
Thanks, but when I scrape it using "save whole page", the TOC does work for me, including the jumping. 

Could you please export the problematic note and attach it here to make sure I have the exact same note as you? Thanks.

![image](https://user-images.githubusercontent.com/617641/177629314-1041197c-2003-4204-a082-3e1aa2fb605a.png)

**Comment by phyxnj** [comment]
[WSL2连接到宿主Windows程序的网络代理设置.txt](https://github.com/zadam/trilium/files/9059819/WSL2.Windows.txt)
I uploaded the file and modified the suffix to txt.
In my case it doesn't work in read only mode but in write mode it works well.

**Comment by zadam** [comment]
Hi, thank you, I was able to reproduce the problem and fix it.
