### ISSUE TITLE
Markdown export options (Feature request) 

### ISSUE THREAD

**Issue by samchugit** [zadam/trilium#2963]
### Describe feature

When I export a note with code blocks into markdown, the code blocks are indented rather than fenced with ```, along with the header style using setext than the atx style, which will be rendered normally in most markdown renderers. However, I still want the atx headers and fenced code blocks as my writing favor. 

After inspecting the source code, I figure out that the markdown exporter utilizes [turndown](https://github.com/mixmark-io/turndown), and the export behavior can be tweaked by some [options](https://github.com/mixmark-io/turndown#Options). So I made some changes to the `src/services/export/md.js` as followed.

```diff
--- a/src/services/export/md.js
+++ b/src/services/export/md.js
@@ -7,7 +7,7 @@ let instance = null;

 function toMarkdown(content) {
     if (instance === null) {
-        instance = new TurndownService();
+        instance = new TurndownService({ codeBlockStyle: 'fenced', headingStyle: 'atx' });
         instance.use(turndownPluginGfm.gfm);
     }
```

After recompiling the docker image, I can totally export notes into markdown files with fenced code blocks and atx style headers. Therefore, I wonder if it's possible to add some option entries to adjust exporting style.

P.S. thanks for your great job!

**Comment by zadam** [comment]
Hi, I changed codeblock style to fenced, it seems to be more popular.
