### ISSUE TITLE
(Bug report) The node size of the note map is incorrect

### ISSUE THREAD

**Issue by a15355447898a** [zadam/trilium#2965]
### Trilium Version

0.52.4 

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

openSUSE 15.4

### Description

The node size of the note map is incorrect
![image](https://user-images.githubusercontent.com/62456287/177719343-79863375-59c2-4750-9f74-074b5339d19b.png)
![image](https://user-images.githubusercontent.com/62456287/177719558-9ff3ba36-019a-4ecd-9cd5-42ff576d7ecb.png)

**Comment by zadam** [comment]
Hello, thank you for the bug report. It does seem like a bug, but I can't reproduce it.

Would you be so kind and create an anonymized database in Optons -> Advanced:

![image](https://user-images.githubusercontent.com/617641/178065644-2f46a6f3-7a4b-45e5-950a-11fa7bdbcf8b.png)

This will create a copy of the database in `~/trilium-data/anonymized/...` which keeps the structure, but removes all the note contents and titles. Please send this *.db file to zadam.apps@gmail.com

Thanks!

**Comment by zadam** [comment]
Hi, thanks for the anonymized database. The problem was that the note had hidden images as children, which is quite confusing leading to this behavior. Fixed.
