### ISSUE TITLE
(Bug report) Alt Gr + P  shortcut is a little overzealous

### ISSUE THREAD

**Issue by NicolaBagala** [zadam/trilium#2966]
### Trilium Version

0.52.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Pro 21H2 build 19044.1766

### Description

Pressing Alt Gr (right Alt) + P will create a new note in the calendar root, **no matter what.** If there's no note tagged as #calendarRoot, it will create one and place the note there, under the current date. If I press this shortcut when I'm in another app, and even if Trilium is minimised, Trilium will spring up front and create the new note. This is in spite of the fact that the Alt Gr + P shortcut isn't defined anywhere in the options.

This means that when I'm trying to type a [, I get this problem *all the time*, because [ is Alt Gr + è on my keyboard, and P is right next to è. 

Is there any way to disable this shortcut that I'm not seeing, or is this a bug to fix?

**Comment by zadam** [comment]
Hi, you can remove this in the options:

![image](https://user-images.githubusercontent.com/617641/178066139-2874f076-b9d8-4015-8164-b42b0859fb12.png)

However, because it's a global shortcut, it needs an app restart for the change to take effect.

**Comment by NicolaBagala** [comment]
Hi, thanks! I somehow had missed that, despite looking through the options several times.
