### ISSUE TITLE
Question: What username to enter in Web Clipper?

### ISSUE THREAD

**Issue by ArisKallergis** [zadam/trilium#2973]
Hello, I'm trying to setup the chrome web clipper extension but I forgot what username I'd been using the last time.
Where am I supposed to find it? Any defaults?

**Comment by Nriver** [comment]
Username was removed. You can enter anything you like. Only the password matters.

**Comment by ArisKallergis** [comment]
I was trying to do that, but was getting a validation message saying that required field needs to be filled or something like that.

But right now that I'm looking at it, it works somehow!

Anyway, thank you very much!

**Comment by zadam** [comment]
It's as @Nriver described. The username will be removed from web clipper UI in the future to make it less confusing.
