### ISSUE TITLE
(Bug report) ETAPI POST /branches is broken

### ISSUE THREAD

**Issue by st3iny** [zadam/trilium#2978]
### Trilium Version

0.53.2

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Docker Image

### Description

I'm not able to create branches via the ETAPI. Posting a body with and without `parentNodeId` fails. The branch I'm trying to create does not exist yet.

### Posting with `parentNodeId`
```sh
curl --request POST \
  --url https://[REDACTED]/etapi/branches \
  --header 'Authorization: [REDACTED]' \
  --header 'Content-Type: application/json' \
  --data '{
	"noteId": "YH9DW9VNzeDt",
	"parentNodeId": "w7XEQyNMjzJi"
}'
```
```json
{
	"status": 400,
	"code": "PROPERTY_NOT_ALLOWED",
	"message": "Property 'parentNodeId' is not allowed for PATCH."
}
```

### Posting without `parentNodeId`
```sh
curl --request POST \
  --url https://[REDACTED]/etapi/branches \
  --header 'Authorization: [REDACTED]' \
  --header 'Content-Type: application/json' \
  --data '{
	"noteId": "YH9DW9VNzeDt"
}'
```
```json
{
	"status": 500,
	"code": "GENERIC",
	"message": "NOT NULL constraint failed: branches.parentNoteId"
}
```

**Comment by zadam** [comment]
Hi, you have a typo in the attribute name, it's parent**Note**Id, note parent**Node**Id.

**Comment by st3iny** [comment]
Wow, thanks. Sometimes a second pair of eyes really helps ...
