### ISSUE TITLE
Scripting: "getTargetNote" is not a function

### ISSUE THREAD

**Issue by marcarneg** [zadam/trilium#2981]
### Trilium Version

0.53.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 x64

### Description

Hi! I'm working with the word-counter code example to start my plugin development. 

I'm getting an array of Notes via my own method "this.getAllChildren()"- this works as expected. Via "getRelations('internalLink')" I am scanning each note for internal links. So far this works fine. But when I want to evaluate the target notes of the internal links, it fails, because the attributes I got from "getRelations('internalLink')" dont contain the function "getTargetNote()".

TLDR:
a) a Note object can return all the internal links as "Attribute" via "getRelations('internalLink')" (works as expected)
b) each attribute-as long as it's an relation- can retrieve the it's target Note, via "getTargetNote()". This throws an error (Uncaught (in promise) TypeError: relations[j].getTargetNote is not a function)

Code example
`async refreshWithNote(note) {

	var all_children = await this.getAllChildren(note) //works
	if(all_children === false || all_children === null){ return;}
    
	for (var i = 0; i < all_children.length; i++) { 
			var relations = all_children[i].getRelations('internalLink') //debug via console.log seems valid and sane
			if(relations === null) {continue}

			for (var j = 0; j < relations.length; j++) { 
				console.log(relations[j]) //has content
				var targetNote = await relations[j].getTargetNote() //Uncaught (in promise) TypeError: relations[j].getTargetNote is not a function
			}
		}
}`

What am I doing wrong? Is this a bug, or did I misread the docs? Thanks in advance!

**Comment by zadam** [comment]
Hello, it turns out that `Attribute.getTargetNote()` did not exist in the frontend API. You probably saw it in the backend API, unfortunately the two APIs are not completely in sync and there are inconsistencies.

I added this API, in the meantime you can work around it by something like:

```javascript
const note = await api.getNote(attr.targetNoteId);
```
