### ISSUE TITLE
(Feature request) Add ways to hide the TOC sidebar

### ISSUE THREAD

**Issue by abstractionmage** [zadam/trilium#2985]
### Describe feature

The TOC sidebar for text notes added in [v0.53.2](https://github.com/zadam/trilium/releases/tag/v0.53.2) is always visible and taking up screen space. I wish there was a way to hide the TOC sidebar if it's not needed to make more efficient use of screen space, especially on small displays and/or when tiling the trilium window to the left or right half of the screen.

**Comment by zadam** [comment]
Hi, that's true. I'm thinking there should be probably global on/off and then the ability to enable it per note I guess.

An alternative approach could be heuristic based on number of headings. If the number of headings is less than X, don't display TOC as it's not really needed. If there's more than X headings, display it.

WDYT?

**Comment by zadam** [comment]
It's possible now (in master, future 0.54) to configure TOC globally:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/617641/181914997-f39a9900-b35e-4e17-8860-5db0b5e38e05.png">

It's also possible to force showing/hiding on invidual notes using `#toc=show` and `#toc=hide`.
