### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Rigel772** [zadam/trilium#2986]
### Trilium Version

0.50.3

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Manjaro KDE

### Description

![image](https://user-images.githubusercontent.com/1696243/178928228-8f32ebca-a3dd-4fc7-91d0-4227c377bd56.png)

- Opened Trilium
- created new node
- tried to close the window
- after clicking OK window closes and after re-openning the node looks ok

**Comment by zadam** [comment]
I believe some process got stuck / was late and didn't notice that the Trilium is already shutting down. It should be harmless probably and shouldn't be happening often ...

**Comment by Rigel772** [comment]
Indeed seems to be harmless, thanks
