### ISSUE TITLE
(Bug report) Opening notes in new tab via middle-click also pastes clipboard content

### ISSUE THREAD

**Issue by abstractionmage** [zadam/trilium#2995]
### Trilium Version

0.53.2

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Manjaro KDE (stable branch)

### Description

When I open notes in new tabs by middle-ckicking them in the tree view while editing a text note, my current clipboard content is pasted into the text note, even though that is not my intention.
![Peek 2022-07-17 20-13](https://user-images.githubusercontent.com/37195767/179419500-0a909521-8efb-455d-a2b9-38e18f545cc0.gif)

**Comment by zadam** [comment]
Hi, can you try if the middle click does the same thing in e.g. text editor like Kate? Middle click as paste is quite common config in Linux.

**Comment by abstractionmage** [comment]
Yeah, pasting via middle-click is an inherent feature of Manjaro KDE and works in pretty much all applications. This isn't problematic in most applications because opening and closing tabs via middle-click usually doesn't trigger a paste (for example in Kate and VSCode).
