### ISSUE TITLE
(Bug report) Table captions do not respect dark theme

### ISSUE THREAD

**Issue by abstractionmage** [zadam/trilium#2998]
### Trilium Version

0.53.2

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Manjaro KDE

### Description

![welp](https://user-images.githubusercontent.com/37195767/179695584-773dc4d0-946a-435e-af4d-8520ebd5931e.gif)

Would be cool if I could actually see what I'm typing into table captions without having to switch to a light theme 😅

**Comment by zadam** [comment]
It does actually respect the dark theme:

![image](https://user-images.githubusercontent.com/617641/179855858-f7be2915-4efe-4d10-abf0-6dc538673921.png)

Typical problem is that the table cells have an explicit assigned color which you should be able to clear via cell properties:

![image](https://user-images.githubusercontent.com/617641/179856004-b6cfe575-5095-41b7-a804-9358e99896f6.png)

**Comment by abstractionmage** [comment]
Hi, thanks for taking the time. You may have misunderstood me: I'm not talking about the *header bar* of tables, but their *captions* (enabled by selecting any cell and clicking the *"Toogle caption on"* button). Those always have dark grey text and a white background regardless of theme. Unless you edit them, then their background seems to become fully transparent and you can't see what you're typing on dark themes.
 
![caption](https://user-images.githubusercontent.com/37195767/179911686-a8bd96f1-5341-48ef-9895-385c1e8bb5f2.gif)

**Comment by zadam** [comment]
Hi, you're right, I misunderstood. Table captions are quite new in CKEditor and I didn't add CSS variables for them yet. That should be now fixed.
