### ISSUE TITLE
Attribute name can be empty

### ISSUE THREAD

**Issue by mahdi1234** [zadam/trilium#30]
- Alt+A on any node
- "Add new attribute" button
- Do not specify "Name" only fill in "Value" and "Save"

It's saved as empty attribute name, not sure this is correct.

**Comment by zadam** [comment]
Yeah, I guess this shouldn't be allowed. Will fix.

**Comment by zadam** [comment]
Fixed in 873ea67e9ce1ed780a7b0b1104ecae9e7cd2e555
