### ISSUE TITLE
Web interface gray screen

### ISSUE THREAD

**Issue by Dmitrykrz** [zadam/trilium#3003]
### Trilium Version

0.53.2

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Windows7 + Ubuntu 22.04

### Description

I have Trillium 0.53.2 on my Windows machine.
I set up Trilium 0.53.2 using Docker on Ubuntu machine.
I go to Ubuntu machine web interface and see 3 radio buttons: I am new user, I have desktop, Connect to server.
I choose second radio button, The web interface instructs me to to go desktop version in plug in the address.
The desktop veriosn connects to the server and says "Sync ok"
I open the web interface of the server and it shows just gray screen with nothing on it.
How do I enable the web interface on the ubuntu machine?

**Comment by sigaloid** [comment]
Can you press F12, choose console, and then reload the web interface? It may display an error that is more specific.

**Comment by zadam** [comment]
Hi, as @sigaloid mentioned, more info - screenshot (not sure what is grey screen), web developer console log, maybe even backend log from the server would help.

**Comment by Dmitrykrz** [comment]
> Hi, as @sigaloid mentioned, more info - screenshot (not sure what is grey screen), web developer console log, maybe even backend log from the server would help.

:8080/:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
:8080/:1 The page requested an origin-keyed agent cluster using the Origin-Agent-Cluster header, but could not be origin-keyed since the origin 'http://*my ip*:8080' had previously been placed in a site-keyed agent cluster. Update your headers to uniformly request origin-keying for all pages on the origin.
DevTools failed to load source map: Could not load content for http://*my ip*:8080/libraries/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
desktop_layout.js:49          GET http://*my ip*:8080/app/widgets/backlinks.js net::ERR_BLOCKED_BY_CLIENT

**Comment by Dmitrykrz** [comment]
Here is the screenshot 
![207 180 203 248_8080_ (1)](https://user-images.githubusercontent.com/25010053/180141389-d9a0bdec-3696-421a-a074-e16cb1548755.png)

**Comment by Dmitrykrz** [comment]
here is the data from trilium Log file

```
12:44:08.825 200 GET /api/health-check with 15 bytes took 1ms
12:44:39.028 200 GET /api/health-check with 15 bytes took 1ms
12:45:09.148 200 GET /api/health-check with 15 bytes took 1ms
12:45:39.333 200 GET /api/health-check with 15 bytes took 1ms
12:46:09.553 200 GET /api/health-check with 15 bytes took 1ms
12:46:28.885 Generated CSRF token iFAySJ6j-4HXCs0Z2i11xiE39h_nEQCs with secret undefined
12:46:35.277 Generated CSRF token h9TTiGhO-fr7a3le91R7NMv-ytDajZY4 with secret undefined
12:46:39.721 Generated CSRF token LVCV5Apn-TdsuVU0sNAdONHrhVNI4k with secret undefined
12:46:39.860 200 GET /api/health-check with 15 bytes took 1ms
12:46:41.795 Generated CSRF token obUm5JjD-3ob_-45OX6HD8J6pwqtgtA with secret undefined
12:46:57.272 Generated CSRF token zxCbsUVx-69f2a7GMiKJGDv0cb_MU with secret undefined
12:46:58.705 Generated CSRF token wooxBw7h-Lx1Ilxa2th3q_3ipKgWypY with secret undefined
12:47:10.210 200 GET /api/health-check with 15 bytes took 3ms
12:47:13.783 Table counts: notes: 244, note_revisions: 385, branches: 261, attributes: 296, etapi_tokens: 0
12:47:13.801 All consistency checks passed with no errors detected (took 18ms)
```

**Comment by zadam** [comment]
Looks like you have an adblocker which doesn't like the file `backlinks.js`. Disabling the adblocker for localhost should fix the problem.

**Comment by Dmitrykrz** [comment]
> Looks like you have an adblocker which doesn't like the file `backlinks.js`. Disabling the adblocker for localhost should fix the problem.

Thank you. Problem solved. This really was adblocker's fault. I disabled it for my server.
