### ISSUE TITLE
Documentation: glitch.com server setup

### ISSUE THREAD

**Issue by yozlet** [zadam/trilium#301]
I set up the server on [Glitch](https://glitch.com/) and it literally just worked out of the box - no configuration needed.

Here's the button to click that'll do it (created using https://github-import.glitch.me/ ) : [![Remix on Glitch](https://cdn.glitch.com/2703baf2-b643-4da7-ab91-7ee2a2d00b5b%2Fremix-button.svg)](https://glitch.com/edit/#!/import/github/zadam/trilium)

It'd be good to:

1. Add this button to the README, with a one-line explanation
2. Add cloud-hosting options to the wiki with deeper explanations of pros and cons

(I'm happy to take this on, I just don't have time this morning)

**Comment by zadam** [comment]
Is it something like (already merged) gitpod? If so, we can add it next to it on the README. PRs are welcome.

**Comment by dixonge** [comment]
Glitch is an app testing environment. @yozlet is right - click the 'Live' button and the app kicks right off.
