### ISSUE TITLE
(Feature request) Mouse-over a hyperlinked text shows the link

### ISSUE THREAD

**Issue by CsatiZoltan** [zadam/trilium#3010]
### Describe feature

Could you please add the (optional) feature of showing the external link in a pop-up box when hovering the mouse over a text, which points to a webpage ?
Currently, checking the link is quite cumbersome: one has to i) click on the text, then ii) click on the edit text button and finally iii) browse the link URL in the containing box (the width of which is usually shorter than the URL, so you need to use the mouse or the arrow keys).
What I have in mind is that when the user hovers the mouse over the text, and waits for some time (to avoid too many links popping up), a tooltip pops up displaying the link.

### Additional Information

The [hover](https://github.com/zadam/trilium/issues?q=hover) keyword did not give me relevant results, that is why I open this issue.

**Comment by zadam** [comment]
Hi, this is a CKEditor way of doing things and we're just taking it as it is. There's no plan to implement custom handling for this, sorry.

**Comment by CsatiZoltan** [comment]
Yes, I noticed that you made some modifications with respect to the default CKEditor (e.g. including the maths button on the editor panel). It would have been nice to include this pop-up solution, but I can live without it.
