### ISSUE TITLE
(Bug report) Import file with Chinese char in file name cause random char in file name after import

### ISSUE THREAD

**Issue by shutaozhenzhen** [zadam/trilium#3013]
### Trilium Version

0.53.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windows 10 1809

### Description

Import file with Chinese char in file name cause random char in file name after import.

**Comment by zadam** [comment]
Hi, sorry for late response, are you importing notes in ZIP or directly from filesystem? ZIP has the issue that it assumes UTF-8 encoding, but as I learned most chinese software pack with a different encoding.

**Comment by shutaozhenzhen** [comment]
> 

directly from filesystem

**Comment by zadam** [comment]
could you post some screenshot of the original filename and imported? To have an idea how the characters get mangled ...

**Comment by shutaozhenzhen** [comment]
![image](https://user-images.githubusercontent.com/24778590/181793496-064b1233-e08d-4f06-8ae2-4628b0a00fcd.png)
![image](https://user-images.githubusercontent.com/24778590/181793555-d3a818b3-ffbe-4d6d-a1b4-f9b582134a06.png)
![image](https://user-images.githubusercontent.com/24778590/181793572-60dcc1f0-913f-4b32-b3cb-cec1925939f4.png)
![image](https://user-images.githubusercontent.com/24778590/181794003-35a7681f-8e00-42d4-833a-b0a256cf4675.png)
![image](https://user-images.githubusercontent.com/24778590/181794081-4c7f7689-2979-4488-a958-43df1fc93e88.png)
![image](https://user-images.githubusercontent.com/24778590/181794149-0212e9dc-c005-4939-a07e-c99da210298f.png)
`测试.txt` is a empty file with Chinese char filename
And my systerm charset is non-unicode(gbk)
![image](https://user-images.githubusercontent.com/24778590/181795015-2a978cb8-0e15-4aa2-af11-25e8d8ae18b9.png)

**Comment by zadam** [comment]
I see, my guess is that you're using non-unicode system encoding. Trilium is tested (and thus supported) only on unicode encoding.

Of course, if the fix is simple enough then PR is welcome.

**Comment by xiecang** [comment]
This issue is still not fixed in the latest version.

**Comment by eliandoran** [comment]
@xiecang , can you provide a sample ZIP so that I could look at it?

**Comment by xiecang** [comment]
> [@xiecang](https://github.com/xiecang) , can you provide a sample ZIP so that I could look at it?

[测试.zip](https://github.com/user-attachments/files/26539784/default.zip)

<img width="836" height="838" alt="Image" src="https://github.com/user-attachments/assets/e5852e52-4e11-4336-82a2-27cf1ebd1dd1" />

**Comment by eliandoran** [comment]
@xiecang , thank you for the sample, I can reproduce the issue and I will be looking for a fix.

**Comment by eliandoran** [comment]
@xiecang , a fix will be available in the next release.

**Comment by xiecang** [comment]
@eliandoran Thank you for looking into this and for the quick response. I’ll keep an eye out for the next release.
