### ISSUE TITLE
How can i get the notelabel in js ?

### ISSUE THREAD

**Issue by Cai-Tang** [zadam/trilium#3016]
### Describe feature

I'm trying to use shareJS to add new functionality to my share page, as you know, shareJS does the same thing on all pages, I want to change this behavior through the owned attributes of the note. How do I get the note label value  in ShareJS to make it behave according to the note tag? Or just  can only use etapi?  Give me an example Please.

**Comment by zadam** [comment]
Hi, share pages have a builtin JS function to load a note:

```
const note = await fetchNote(noteId);

console.log(note);
```

The object also contains attributes. To get the currently displayed noteId, you can get it from `body` element's attribute `data-note-id`.

**Comment by Cai-Tang** [comment]
Thanks, I'll give it a try
