### ISSUE TITLE
(Feature request) Backend API: run system command

### ISSUE THREAD

**Issue by cidious** [zadam/trilium#3019]
### Describe feature

Hi, thanks for excellent project.

I want to make an IT infrastructure diagram and it would be cool if every node could be a Code Note running external scripts like `ping a host` or `traceroute a server` -- collecting output.

It would be nice to have some `Exec system command` function in the Backend API to make those pings.

Thanks.

**Comment by marcarneg** [comment]
I think trilium uses node.js - so you could use a (backend)-code note and call "exec" like described [here ](https://stackoverflow.com/questions/1880198/how-to-execute-shell-command-in-javascript) .

This worked for me (on windows) and gave back the result on the backend-log:
`var exec = require('child_process').exec;

exec('dir "C:/Users"',
    function (error, stdout, stderr) {
        api.log('stdout: ' + stdout);
        api.log('stderr: ' + stderr);
        if (error !== null) {
             api.log('exec error: ' + error);
        }
    });`

**Comment by zadam** [comment]
as @marcarneg mentioned, you can use standard node.js APIs.
