### ISSUE TITLE
(Bug report) no shortcut keys to `Decrease indent`

### ISSUE THREAD

**Issue by jan-bar** [zadam/trilium#3022]
### Trilium Version

0.53.2

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

win10 ltsc 1809 chrome 103.0.5060.114

### Description

I can use tab to quickly `Increase indent`，But I don't know what shortcut keys to use to quickly `Decrease indent`

If I press multiple tab keys, I am currently only able to click multiple times with the mouse click `Decrease indent`

In other editors, you can usually use the Backspqce key to quickly achieve this function

![搜狗截图20220729174559](https://user-images.githubusercontent.com/14202095/181733456-243dbe55-dd66-46bd-8401-91a7dca5ae80.png)

**Comment by Nriver** [comment]
It's `Shift + Tab`.

**Comment by jan-bar** [comment]
> It's `Shift + Tab`.

Thank you very much. I'm not used to it.

**Comment by jan-bar** [comment]
> It's `Shift + Tab`.

Thank you very much. I'm not used to it.

**Comment by jan-bar** [comment]
> It's `Shift + Tab`.

Thank you very much. I'm not used to it.
