### ISSUE TITLE
(Bug report) Cancelling the search action will report an error "Error when calling POST bulk-action/affected-notes: error - Internal Server Error"

### ISSUE THREAD

**Issue by jan-bar** [zadam/trilium#3027]
### Trilium Version

0.53.2

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

win10 ltsc 1809 chrome 103.0.5060.114

### Description

Since I just came into contact with trilium, I found this problem when testing various functions, and this error also exists on the window desktop.

![GIF 2022-07-30-星期六 18-22-35](https://user-images.githubusercontent.com/14202095/181906134-842a64ae-7209-41e8-b402-8c785e11655d.gif)

![搜狗截图20220730182602](https://user-images.githubusercontent.com/14202095/181906232-4cb17fdf-a4f2-463d-b954-cc327cc5c4e0.png)

**Comment by zadam** [comment]
Hi, thanks for reporting this problem, it has been fixed. Note that this wasn't a functional bug, just extra error message.
