### ISSUE TITLE
(Feature request) Script execution should capture api.log() and show in a panel

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#3028]
### Describe feature

-

**Comment by shutaozhenzhen** [comment]
I think in frontend you can just use console.log
with `ctrl+shift+i` or `open dev tool` you can open dev tool, and you log will present here
I don't know how to show log in backend

**Comment by zadam** [comment]
Yes, but those options are quite awkward, especially the backend log.

**Comment by mzrimsek** [comment]
> 

FWIW this is super hit or miss with my installation. Logging rarely actually does anything as far as I can tell.

**Comment by zadam** [comment]
implemented in master
