### ISSUE TITLE
(Feature request) Starting Electron App again with same TRILIUM_DATA_DIR should activate already running instance

### ISSUE THREAD

**Issue by capi** [zadam/trilium#3036]
### Describe feature

At the moment, when I (accidentally) start Trilium a second time, it will show an EADDRINUSE because it wants to listen on the same port. 

![image](https://user-images.githubusercontent.com/254852/182457747-fe72b726-9703-4fd5-a30c-7de6f38221ee.png)
(0.53.2 on Windows 11) (To be honest, reading https://github.com/zadam/trilium/blob/master/src/services/port.js I don't really understand why, I'd expect it to just listen on another port and start a second instance. But to be fair, that would likely lead to problems with the database?).

Starting the second instance should cause the already running instance to come to foreground and receive the focus, in my opinion.

**Comment by zadam** [comment]
Hi, implemented. 

> I don't really understand why, I'd expect it to just listen on another port and start a second instance.

The reason Trilium has a standard port is that Web Clipper expects it to be there when establishing the communication.

**Comment by capi** [comment]
Wow, your speed in reacting to suggestions always amazes me! Thanks a lot! ❤️ 🎉 

> The reason Trilium has a standard port is that Web Clipper expects it to be there when establishing the communication.

Makes sense, but shouldn't
```
portscanner.findAPortNotInUse(startingPort, startingPort + 10, '127.0.0.1', function(error, port) {
  // ...
}
```
attempt to open another port in the 37840-37850 range? Why doesn't that happen? (This is me just trying to understand the code. I'm aware that weird things would happen if two separate instances connect to the same DB.)

**Comment by zadam** [comment]
Yes, that was the initial intention, but I don't actually know why does it not work.

But now, this is not desirable anymore anyway, so I removed the code - there was an issue on some Windows (IIRC) machines that web clipper scanning even just 10 ports took too much time, so it was changed to check just one exact port.
