### ISSUE TITLE
[Security] Maximum number of login retries and adding option for OTP 

### ISSUE THREAD

**Issue by Neko-Box-Coder** [zadam/trilium#3044]
Hi,

First of all, I want to thank you for bringing this project alive. I have been using it recently and really like it.

This is mainly for self-hosting where this is exposed to the internet. Apologize if this already exists or if someone has already mentioned this because I couldn't find it anywhere.

The first thing is being able to have a **`maximum number of login retries (per IP address)`**.
Ideally, the user should have a strong password and brute-forcing it is infeasible. 
But this is not great because this relies on the user to be aware of it.

The second thing is **`the ability to use OTP such as google authenticator`** as a second line of defense for logging in.
This doesn't require an internet connection (afaik) but just requires the time for both machines to be the same.
The reason for this is that for machines that are key-logged (company machines or public machines), password becomes useless and anyone can easily log in to the self-hosted Trilium and do any damage or worse, get hold of any sensitive personal information.

The final thing is at the moment, the sample config file is only mentioned [here](https://github.com/zadam/trilium/wiki/Backup). I know it is in the root directory but it wasn't too obvious and nowhere else mentions it, it will be nice if there's a dedicated page that mentions this (Server installation maybe?).

**Comment by zadam** [comment]
Hi, Trilium has already rate limiting with 10 login attempts in 15 minutes per IP, so brute forcing should not be possible.

As for the OTP, at the moment I consider it out of scope for the project. It is possible to add this functionality via authentication proxy like e.g. authelia.

**Comment by Neko-Box-Coder** [comment]
Thanks for the reply. 

I didn't know there's a limit for login attempts, good to know it is already there. It will be nice though if it is configurable.
Also thanks for informing me for authentication proxy, I didn't know it is a thing. I definitely need to try it out.
