### ISSUE TITLE
Sorted attribute - a way to set the ascending/descending order

### ISSUE THREAD

**Issue by mid1221213** [zadam/trilium#3046]
I have searched for a while and I don't think it is currently possible to make a permanent sorting in descending order. So I suggest this enhancement.

### Discussed in https://github.com/zadam/trilium/discussions/2599

<div type='discussions-op-text'>

<sup>Originally posted by **mondayrobot** January 28, 2022</sup>
Hello,

I'm trying to have all the new notes in my Inbox to appear at the top of my Inbox, not at the bottom. I'm using the attribute `#sorted=DateCreated`, but is there a way to set a descending order? I have tried `#sorted=descending` but it does not work.

Thanks!</div>

**Comment by zadam** [comment]
Hi, you're right, this was missing. Add `#sortDirection` label (value `desc`). This will be in 0.55 (beta soon-ish)
