### ISSUE TITLE
How do I create a folder?

### ISSUE THREAD

**Issue by damianesteban** [zadam/trilium#305]
Maybe I'm missing something, but how do I create a folder?

**Comment by zadam** [comment]
All notes are folders at the same time. You just create subnote under it using context menu in the tree pane or using CTRL-O/CTRL-P keyboard shortcuts.

**Comment by zadam** [comment]
Hmm, folder icon just means the note is not a leaf and has some child notes (i.e. it acts as a folder for its child notes).

**Comment by damianesteban** [comment]
Ok great. Thank you.
