### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#3051]
### Trilium Version

0.54.2，0.54.1

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows10

### Description

It doesn't show recent history by default. This button is also not clickable, but I remember it was clickable before.
![图片](https://user-images.githubusercontent.com/37627919/183653348-8abd240b-380f-422d-9177-22478532a3aa.png)

**Comment by zadam** [comment]
Hi, you're right, this was broken. Fixed.
