### ISSUE TITLE
(Bug report) Widget position prevents desktop app loading

### ISSUE THREAD

**Issue by Lewiscowles1986** [zadam/trilium#3060]
### Trilium Version

0.54.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Home 

### Description

Hi, 

Great app! I've been playing with it for the past 2 weeks after noticing a friend talking about it.

if I change the WordCountWidget, to have 

`get position() { return 0; }` then reload; the app doesn't work. 😂 

I fixed it by using DBeaver and modifying back to 100.

I Was just spelunking around the system as I'm in my second week of learning Trilium. It's an amazing project. I wonder if NoteContextAwareWidget should have some min / max limiting where it is called internally to protect users.

**Comment by zadam** [comment]
Hi, in case this happens, there's an option to prevent custom widgets loading: https://github.com/zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup

**Comment by Lewiscowles1986** [comment]
Left a note on #3060 just to say I am not sure that edit is the fix.
https://github.com/zadam/trilium/blob/aebdbdf8befcde535cbeca454d83e1bbb4f5a8ff/src/public/app/widgets/containers/container.js#L26 is what I think the culprit may be, although I'm not 100% sure why it would lead to crash of frontend.

**Comment by Lewiscowles1986** [comment]
Fixed. I was wrong about the other edit. this works great, and puts the book wordCount at the top of the screen! 🙌
