### ISSUE TITLE
(Feature request) Update demo.zip

### ISSUE THREAD

**Issue by Lewiscowles1986** [zadam/trilium#3061]
### Describe feature

As a new user of Trilium, I should be able to click add note in the `My Family Tree`, and have it automatically add a person. So that I am not prematurely confused about changing note types. So that I might experiment with that feature.

### Additional Information

I hacked around in the demo.zip `!!!meta.json` file and found the following edit:

```json
						{
							"type": "relation",
							"name": "child:template",
							"value": "PLytAmCp7kGE",
							"isInheritable": false,
							"position": 0
						}
```

I'm sure you know what this does, but basically it links the `child:template` to the demo.zip reference for the `Person Template` note.

To explore this concept I went through the "fun" of getting Trilium server running on a raspberry pi, building, checking it worked and then editing the file in the demo.zip, noting that the ID's were different post-zip-seed. I Have struggled with reproducing as I don't know how to wipe the database (deleting document.db certainly wasn't it).

I've raised as a feature request, as I wasn't sure if there was nuance preventing this, which could be why this is not shipped in the demo zip file.

**Comment by zadam** [comment]
I added `~child:template` relation as you suggested.

**Comment by Lewiscowles1986** [comment]
Thank you, but I really wanted to know how I could also contribute things like this. I Have more edits for books, a photo-type, reviews. It would be wonderful to understand how to put things in that demo.zip the correct way.

**Comment by zadam** [comment]
demo.zip is just exported ZIP (right click on "Trilium Demo", export as HTML ZIP).
