### ISSUE TITLE
(Feature request) Documentation: reset DB / Clean instance

### ISSUE THREAD

**Issue by Lewiscowles1986** [zadam/trilium#3062]
### Describe feature

As a user, looking to contribute to the community, I would like to know how to reset the trilium database and start the app as a new user, so that I might verify that my efforts work in greenfield scenarios, as well as existing installations, and so that I might reduce bugs as a result.

### Additional Information

I tried deleting `document.db`. I'm unsure what ini file edits would be needed to bring a Trilium install back to default state, as-if it were a fresh download and install.

**Comment by Lewiscowles1986** [comment]
Note: I Am presently able to work around this by installing multiple docker containers, with separate port bindings.

**Comment by zadam** [comment]
Hi, deleting the `document.db*` files should do the trick, I added some words on it here: https://github.com/zadam/trilium/wiki/Document#how-to-reset-the-document

**Comment by Lewiscowles1986** [comment]
Ah, that is a little frustrating 😄 deleting the data dir seems to work now, as does deleting document.db.

Perhaps the issue was that I had another program open document.db, then deleted, while it was open in that program. I Thought this was a problem with trilium, but it might have been some weird locking file-handle issue 😊 the software I was using was DB Browser for SQLLite 3.10.1. Maybe was something else. In any case, happy to say solved 🙌 apologies for the noise.
