### ISSUE TITLE
(Feature request) Add HTML minifier middleware to express

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#3071]
### Describe feature

Much of the HTML generated is filled with errant new lines, tabs, etc. 
![image](https://user-images.githubusercontent.com/69441971/185227672-172d8689-d076-49cf-9c33-bbedf7f5dcb5.png)

This inflates the size of webpages by 40-60% unnecessarily - especially in HTML-heavy pages, like shared notes. A package like [express-minify-html](https://www.npmjs.com/package/express-minify-html) would improve delivery size by a lot. 

Unfortunately that package seems to only minify `res.render()` responses so the main app page, shared notes, etc will be minified but it looks like much of the javascript and CSS files are excluded from this. 

If page weight is a priority, perhaps this could be considered as an option. I have a PR ready if desired.

**Comment by zadam** [comment]
Hi, I think a preferred solution would be a transparent [HTTP GZip compression](http://expressjs.com/en/resources/middleware/compression.html). That way the source code is still halfway readable/formatted. There's usually only a small difference between gzipped minified and gzipped non-minified.

**Comment by sigaloid** [comment]
Good point, open to a PR adding this [middleware](https://github.com/expressjs/compression)?

**Comment by zadam** [comment]
Yes, that would be welcome. I think it should be enabled for "server" setup only.
