### ISSUE TITLE
(Feature request) WordPress / Automattic Gutenberg

### ISSUE THREAD

**Issue by Lewiscowles1986** [zadam/trilium#3073]
### Describe feature

I've technically got this built, although it is maybe buggy, pre-alpha / alpha software.

Basically, I really don't like the built-in editor. I Like the idea of having `/slash` commands, which confluence and Gutenberg support; and the ability to author and edit content blocks.

The storage should be compatible with `text/html` storage.
![2022-08-18_20-46](https://user-images.githubusercontent.com/2605791/185481647-050aaa40-6dd7-4928-9740-c4757c8f17a7.png)

![2022-08-18_20-47](https://user-images.githubusercontent.com/2605791/185481885-91d62594-3ac7-4f36-b2f3-b7b786448632.png)
![2022-08-18_20-47_1](https://user-images.githubusercontent.com/2605791/185481893-ebef29f4-a933-44fc-8604-cef1fa84aa92.png)
![2022-08-18_20-48](https://user-images.githubusercontent.com/2605791/185482057-e3a9c61f-f3f0-4e06-8ee2-c6098b22589f.png)

### Additional Information

I'd be happy to contribute and attempt to maintain this. It relys on other OpenSource software.

It uses https://github.com/Automattic/gutenberg-everywhere which may not be license compatible with AGPL 🤷 

It is a custom build, although I am willing to share the code and am still attempting to tweak things.

I'll need support to learn how you test features you include. Maybe there are ways of painlessly protecting against regression. In any case, the integration path confuses this I feel, and with the already large scope of Trilium, I do worry a little about compromising the security if this isn't up to scratch.

**Comment by zadam** [comment]
Hi, I don't plan to support multiple editors, so I don't really expect myself to merge your work. You can of course keep maintaining it in a fork, if you wish.

In general maintaining two different ways of doing the same thing is usually double the maintenance work + many interoperability issues for a small benefit, so I try to avoid this.

**Comment by Lewiscowles1986** [comment]
I'll keep my fork, but thought I'd leave this here. It is made more difficult by all the central files where `types` are stored, but you are probably right and I will come to that realisation in time 😄 .
