### ISSUE TITLE
(Feature request) Electron 16 reached EOL

### ISSUE THREAD

**Issue by DynamoFox** [zadam/trilium#3081]
### Describe feature

Update from Electron 16.x to Electron 19.x.

### Additional Information

Hello, on 24 May 2022 [Electron 16 went end-of-life](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) and won't receive any new updates.
I guess it would be better to move to a new major release which uses newer tool-chain and likely comes with specific platform improvements (i.e. Electron on Wayland).

I was able to test Trilium on Electron 19.0.13 **on Linux** without any code related change, monitoring warnings/errors in devtools didn't reveal anything new. I also checked whether there were [breaking changes between Electron's major versions](https://github.com/electron/electron/blob/main/docs/breaking-changes.md) needing attention but they don't seem to affect Trilium.

Unfortunately the latest Electron series, v20, doesn't seem to be compatible with better-sqlite3 as I can't get it to compile ([same issue as other people](https://github.com/WiseLibs/better-sqlite3/issues/126#issuecomment-1204957779)) which means we can't target that version yet.

**Comment by zadam** [comment]
Hi, electron upgrades are often painful, mainly because of having to compile the binaries for better-sqlite3 for all platforms. I planned to do this once Electron with node.js 18 so that the whole platform is updated at once.
