### ISSUE TITLE
(Feature request) Focus search bar always on new tab

### ISSUE THREAD

**Issue by Zocker1999NET** [zadam/trilium#3083]
### Describe feature

In 26602e8 Trilium was set to focus the "search for a note by its name" bar only if no workspaces exist. However, I do not understand why it shouldn't focus the search bar always. The current default focus does not allow users to select the workspaces faster by using the keyboard (it isn't even possible to select a workspace using TAB) and it seems to make no disadvantage to focus the bar automatically as the auto-completion does only appear after starting to type. So I propose to make the focus change always happen.

If there is a reason for not focusing the search bar by default, I propose adding a comment to the code and here so others can comprehend the reasoning as well.

### Additional Information

The commit 26602e8 was created for #2455.

**Comment by zadam** [comment]
Hi, IIRC the reason for that was that focusing autocomplete also triggered it (showed recent notes) which obscured the list of available workspaces.

But recently, autocomplete was changed, and it is possible to separately focus and activate it. Here we just focus it, so the problem with obscuring workspaces does not happen and the autocomplete can be focus always.
