### ISSUE TITLE
(Bug report) No keyboard input after unsuccesfully copying a note

### ISSUE THREAD

**Issue by EMKAH** [zadam/trilium#3086]
### Trilium Version

0.54.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11 Home 21H2

### Description

Steps to recreate the problem:

Create a new note and add a subnote. Copy the subnote and try to paste it into the same top note/folder. Or try to clone it into the same top note/folder. A message that the "Note $Your_note_name_here note exists already in the $Your_parent_node_here" appears. Afterwards, try to edit your note titles or enter text in any of your notes. It doesn't work (although the ESC key is recognized). Alt-Tabbing out and into Trilium solves the problem.

**Comment by zadam** [comment]
Hi, thanks for the report. It seems like this is an electron problem: https://github.com/electron/electron/issues/19977

I replaced all alerts with toast messages, which should fix the problem.
