### ISSUE TITLE
(Bug report) Note attributes replace template attributes

### ISSUE THREAD

**Issue by EkoeNi** [zadam/trilium#3090]
### Trilium Version

0.54.2

### What operating system are you using?

Other (specify below)

### What is your setup?

Local + server sync

### Operating System Version

Windows 11, Web client

### Description

Hi,
It's seems to be an issue with templates. if you are on a note who have a template and click on the ~template link, the note's attributes replace the template's attributes in the template note. I just update to 0.54.2 and can replicate this bug on Windows Desktop app and WebClient.
Thanks.

![trilium_ld0KcrTF4Z](https://user-images.githubusercontent.com/38835243/186704531-ddf58f3a-6bcc-458e-82d7-2aeacc1fa979.gif)

**Comment by zadam** [comment]
Hi, thanks for the report, I can reproduce it. This is a pretty nasty bug, I will prepare a patch release tomorrow.

**Comment by zadam** [comment]
fix released in 0.54.3
