### ISSUE TITLE
(Bug report)  Bold font is barely visible

### ISSUE THREAD

**Issue by sruebner** [zadam/trilium#3094]
### Trilium Version

0.54.3

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

macOS Monterey (12.5.1)

### Description

When formatting text bold, it is barely visible that the text is bold. There difference between bold and non-bold text is so minute, it is basically useless to bolden text.

I tried this with all three themes and multiple fonts, it is always the same.

For reference, I attached a screenshot:
![Bildschirmfoto 2022-08-27 um 17 58 59](https://user-images.githubusercontent.com/3474352/187038065-5c9bcedd-cf83-41b7-bb23-e3f87529320a.png)

**Comment by zadam** [comment]
Hi, thanks for reporting the problem, the bold font was missing, this will be fixed in the next version:

<img width="148" alt="image" src="https://user-images.githubusercontent.com/617641/188319689-59d59a4f-2c7b-4d3d-868c-469b016b129a.png">
