### ISSUE TITLE
Sync failed: Cannot create a string longer than 0x1fffffe8 characters(Bug report) 

### ISSUE THREAD

**Issue by e-p-s** [zadam/trilium#3108]
### Trilium Version

windows-x64-0.54.3 + windows-x64-0.54.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

10Pro 21H1

### Description

cant sync anymore.... 

i sadly didnt know what i can add to help support.

**Comment by zadam** [comment]
Hello, there was already an occurence of this in #2688

Did you upload a very large file before this started to happen?

**Comment by zadam** [comment]
To unblock the sync you can execute the following:

```sql
UPDATE note_contents SET content = '' WHERE LENGTH(content) > 250000000;
```

and then:
```sql
UPDATE note_revision_contents SET content = '' WHERE LENGTH(content) > 250000000;
```

This can be executed in the SQL console:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/617641/188272124-f3fc458c-8b5f-4a32-abf1-54d2aba75312.png">

Note that this will delete the contents of notes larger than 250 000 000 bytes. Trilium isn't built to handle such large files and they will fail to sync.

**Comment by e-p-s** [comment]
Last thing i remeber was, take a web clipper "shot" from this side:

https://github.com/awesome-selfhosted/awesome-selfhosted

sql1:
UPDATE note_contents SET content = '' WHERE LENGTH(content) > 250000000;
{
	"changes": 13,
	"lastInsertRowid": 56340
}


sql2:
UPDATE note_revision_contents SET content = '' WHERE LENGTH(content) > 250000000;
{
	"changes": 0,
	"lastInsertRowid": 56342
}


yes. the sync is working again. thanks for your quick reply.
