### ISSUE TITLE
Easier way to remove URL links

### ISSUE THREAD

**Issue by Sod-Almighty** [zadam/trilium#3114]
### Describe feature

When copying and pasting text from webpages into notes, I often end up with inline links:

![Metaprogramming - Trilium Notes trilium, Today at 1 04 41 pm](https://user-images.githubusercontent.com/4511095/188445217-48f0942b-658d-428a-a4ea-96282b0567c5.png)

To remove these links, I have to highlight the link text (awkwardly, using the mouse!) and click the "remove link" button on the floating toolbar. There is no way to do this with the keyboard; or without highlighting the link text (and _only_ the link text).

I would like to be able to right-click a link and remove it right there and then, from the menu.

**Comment by sigaloid** [comment]
You can try pasting with Ctrl Shift V which should remove formatting. But this will also remove other formatting.

**Comment by Sod-Almighty** [comment]
I actually figured out today that you can just single-click the link and then click remove. So I closed the ticket.
