### ISSUE TITLE
Ghost split when "open in new tab" (Bug report) 

### ISSUE THREAD

**Issue by Potjoe-97** [zadam/trilium#3115]
### Trilium Version

0.54.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Pop_Os! 22.04

### Description

If there is an active split, opening a link to a trilium note in a new tab creates a ghost split. 

Steps to reproduce : 
1. Create a split
2. Right click on a link, and select "open in a new tab"
3. A ghost split, empty, appears. 

Screen capture : 
[New split when open in new tab.webm](https://user-images.githubusercontent.com/42873357/188604639-2fec5477-a05a-494a-9e42-d2e639548d4f.webm)

**Comment by XXXJetfireXXX** [comment]
Also when several tabs are opened, a ghost split will appear for each inactive tab when reloading frontend.

**Comment by zadam** [comment]
Thanks for the report, fixed.
