### ISSUE TITLE
Option to minimize the application to system tray (run in background in Windows)

### ISSUE THREAD

**Issue by madhusudhanarya** [zadam/trilium#3119]
### Describe feature

Is it possible to add "minimize to system tray" kind of option for windows OS? i want to run Trilium in the background and webclipper can connect to running instance without me opening/re-opening the application.

**Comment by XXXJetfireXXX** [comment]
This feature already exists: if you click the tray icon the window should become hidden.
![image](https://user-images.githubusercontent.com/43646178/188886773-2301cd9b-a956-488d-bdef-f7f07dc24523.png)

**Comment by madhusudhanarya** [comment]
Thank you. Just realized it.
