### ISSUE TITLE
Defining custom backup directory path

### ISSUE THREAD

**Issue by madhusudhanarya** [zadam/trilium#3120]
### Describe feature

In Windows, Trilium backup gets stored in one of the roaming directories. Since the application is shipped as a standalone/portable app, can we have an option to set a custom directory to be used for the backup? This way, i can set the backup paths to the current directory and have both application and backup in the same directory. This allows me to copy the entire directory (with backups) to another windows system, restore the data and start using it.

**Comment by XXXJetfireXXX** [comment]
As a solution, you could make a symbolic link that leads to the path you want.

**Comment by madhusudhanarya** [comment]
Thank you. Was able to get it configured as you have mentioned.
