### ISSUE TITLE
Ghost splits appearing for each inactive tab after reloading frontend.

### ISSUE THREAD

**Issue by XXXJetfireXXX** [zadam/trilium#3122]
### Trilium Version

0.54.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

When reloading frontend/launching Trillium, a ghost split would appear for each inactive tab.
![image](https://user-images.githubusercontent.com/43646178/188887985-0ea2e592-bc63-4267-9c8d-ec7d45660485.png)

**Comment by sigaloid** [comment]
Looks very similar to #3115, and +1: I experience this occasionally.

**Comment by XXXJetfireXXX** [comment]
Yeah, these two indeed might be connected in some way.

**Comment by zadam** [comment]
Fixed in #3115, thanks for report.
