### ISSUE TITLE
(Feature request) Add Apple Silicon release too to the releases section in next build

### ISSUE THREAD

**Issue by coolerspeex** [zadam/trilium#3125]
### Describe feature

Add Apple Silicon release too to the releases section in next build

**Comment by zadam** [comment]
This is probably not going to happen soon. AFAIK building for M1 essentially needs to be done on Mac which would complicate release process dramatically. There are some more difficulties like mandatory notarization.

 In my experience, the emulation works quite well, so this does not seem pressing.
