### ISSUE TITLE
I've got the password, username and database backup but the machine is gone.

### ISSUE THREAD

**Issue by theniceguy8731** [zadam/trilium#3126]
Ok so I don't there is anything that need explanation here, I have the backup of database and password and username but my brother randomly changed the operating system of the machine trillium(desktop version) was running on. How do I retrieve all the files and data that is stored in the database.  
Right now the machine is running pop_os. I'm fairly new to linux and don't know a lot but I can still manage my way around the machine please do help out cause i had stored a lot of data on Trilium and also some important things.

**Comment by XXXJetfireXXX** [comment]
You can make a copy of your backup file, change it's name to "document", leaving the extension unchanged and it effectively becomes a database you can load inside Trillium, iirc.

**Comment by theniceguy8731** [comment]
I tried to do the same before but it didnt work.
When i installed trilium on pop_os it didn't ask me for any signin which was surprising.
I tried other ways but still it didnt work. There was no login.and as long as i do not login with the same username and password i won't be able to decrypt the documents in backup file.

**Comment by zadam** [comment]
When you start Trilium, check "About Trilium Notes" in the top-left menu:

![image](https://user-images.githubusercontent.com/617641/189974895-ec2ff08c-6853-4b3d-b928-9c98d7310936.png)

It should display the folder with the data Trilium uses. Copy the backup file into that directory and make sure it's named `document.db`. Start Trilium again.

Desktop app doesn't ask you to login during app startup, only when you try to access a protected note.

**Comment by theniceguy8731** [comment]
ok so i tried it and it's still not working. i renamed the backup file and started trilium. it's doesn't start in that case. and when i use the original sample database setup by default in a new trilium instance it would only ask me for a to setup a password and not a username when i try to enter protected session.

**Comment by theniceguy8731** [comment]
ok so once again i have downloaded a new instance of trilium this time someone pls guide me about the exact steps.
![image](https://user-images.githubusercontent.com/112561157/190080137-fd536914-5575-4ec8-ab5e-ef0c314ff2af.png)
what should i select?

**Comment by zadam** [comment]
You're probably putting the `document.db` into a wrong directory since trilium thinks it's an empty installation and wants to guide you through initial setup steps.

**Comment by theniceguy8731** [comment]
When i put the backup file in plce of document.db and rename the backup file and then remove the default document.db the app doesn't even run.

**Comment by XXXJetfireXXX** [comment]
Have you tried deleting `.db-shm` and `.db-wal` files before running Trillium? These two might interfere.
Here are the instructions from https://github.com/zadam/trilium/wiki/Backup:
![image](https://user-images.githubusercontent.com/43646178/190405421-ee7b8f32-3fec-46b6-842d-49e8f48230a5.png)

**Comment by theniceguy8731** [comment]
i tried again and made sure of every little detail mentioned here. still doesn't work. the application crashes immediately after i run it with backup file. but when i use the demo file it runs normally. i even tried to rename the file after the application was running and then tried sync but it still didn't work.

**Comment by sigaloid** [comment]
Your notes are still available in the document.db file. It sounds like there's a broken note or script. Try one of these troubleshooting steps from the wiki:
* https://github.com/zadam/trilium/wiki/Troubleshooting#broken-note-crashes-trilium
* https://github.com/zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup

**Comment by theniceguy8731** [comment]
![image](https://user-images.githubusercontent.com/112561157/191325694-5754b8e5-0b4a-4f71-8439-d66bebb2ed64.png)
could someone make-out the reason for crash from this
i tried the troubleshooting methods, didn't work.

**Comment by sigaloid** [comment]
Okay, I see. The problem is that your document.db is corrupted. This may happen because of a disk error, it generally doesn't happen in normal usage or even power loss because SQLite is generally resistant to events like that. 

If even the backup documents are corrupted (that's really rare), then there's not a whole lot you can do besides manually doing recovery with the file, and I'm not totally sure how you would do that or if SQLite would even let you. 

Are you sure the backup document.db's are corrupted too? Open the data directory, rename the current document.db to current-document.db, and move a backup from `backup/backup-daily.db` (or weekly or monthly) up to the main folder with the current-document.db, then rename that backup file to document.db.

**Comment by theniceguy8731** [comment]
so it there absolutely any way for me to retrieve my files from that database? i only need the pdf files that i had stored in it cause they are important.how can i manually get them. also they were saved in protected session so they are probably encrypted. would that serve as a hindrance in retrieval too?

**Comment by sigaloid** [comment]
Were the PDF files added recently enough that they wouldn't be in the backup?

I'm guessing yes, because it should be hard to upload a PDF if the app doesn't open.

If so, you should recover from the backup - that would let you enter in the password easily instead of complicated data recovery. It may be possible, but it would require technical knowledge and probably manually decrypting it along with the key stored in the database. TLDR, recover from backup if possible - it'll definitely be easier than manual recovery.

**Comment by theniceguy8731** [comment]
> Were the PDF files added recently enough that they wouldn't be in the backup?
> 
> I'm guessing yes, because it should be hard to upload a PDF if the app doesn't open.
> 
> If so, you should recover from the backup - that would let you enter in the password easily instead of complicated data recovery. It may be possible, but it would require technical knowledge and probably manually decrypting it along with the key stored in the database. TLDR, recover from backup if possible - it'll definitely be easier than manual recovery.
> 
> Here's some instructions that should make it clear: https://github.com/zadam/trilium/wiki/Backup#restoring-backup

ok i think your missing the issue here. i don't have any backup. it is the backup that is corrupted. i took the backup with me on a pendrive and the machine os was changed. now i need to get back the data from the backup by loading it on trilium which is not working out because as it turns out the backup is corrupted.
so now my question is...
it there any way for me to recover the data manually from the corrupted backup database? even if i can retrieve the pdf files stored in it that would be enough.

**Comment by sigaloid** [comment]
Ah, I see. You may have some luck with using [SQLiteBrowser](https://sqlitebrowser.org/) to open the database. If you can open the database, you can locate the file ID based off metadata. You'd then have a binary blob that is encrypted with a key: that key (`encryptedDataKey`) is stored encrypted elsewhere in the database with your actual password. So, you'd need to locate the encryption key, and the PDF data. Then you'd decrypt the key manually with your password, then use that key to decrypt the file. 

As you can see, it's a bit of an involved process, and that's assuming you are able to retrieve this information from the database. It sounds like you unplugged the flash drive before ejecting/flushing the cache so it's possible that no data is recoverable. If you try opening it with SQLiteBrowser and it shows some records, you may have luck. If it fails to even load, then you may be out of luck...

**Comment by zadam** [comment]
The "malformed" error is typically caused by either of these things:

* document.db was synchronized using e.g. Dropbox, Google Drive etc. which corrupted it
* during the restore process, you forgot to delete ~/trilium-data/document.db-wal and ~/trilium-data/document.db-shm. If they stay and don't correspond to the document.db, then SQLite thinks the database is corrupted.

**Comment by theniceguy8731** [comment]
Ok i think it'll be fair to infer that my backup file is corrupted and i'd have to spend some years trying to figure out how to extract the those files from the database manually. Thanks for helping me figure out the issue @zadam @sigaloid @XXXJetfireXXX .
