### ISSUE TITLE
The `#excludeFromNoteMap` label does not exclude from Global Note Map

### ISSUE THREAD

**Issue by anantone** [zadam/trilium#3128]
This was added few months ago in the form of `#excludeFromNoteMap` label.

_Originally posted by @zadam in https://github.com/zadam/trilium/issues/885#issuecomment-1030644611_

I was following up on this old issue, looking to exclude "admin" part of my tree (themes, scripts) from global note map, and this label worked for the note map from individul note menu, but not from the Global Note Map button in side bar. Instead, the Note Map is divided into remote parts (see screenshot below)

**Comment by anantone** [comment]
Hm, yet I see that adding #archived label achieves the desired result...

**Comment by zadam** [comment]
I think this might happen if you don't  have the `#excludeFromNoteMap` as inheritable, then the child notes are still displayed, but disconnected.

**Comment by anantone** [comment]
Yes, that's exactly the case, thank you! `#excludeFromNoteMap(inheritable)` works perfectly.
