### ISSUE TITLE
Numbers in Table of Contents loop to 0

### ISSUE THREAD

**Issue by anantone** [zadam/trilium#3129]
When using more than 9 headers, table of contents number loop back to 0, 1, 2... instead of 10, 11, 12... (see attached screenshot)

Sure, I would usually use individual notes and list them in parent, but here each header content is very short, so this would make more sense (just need ToC to navigate easily within the list). 

Is there a straightforward fix for this?

![Screenshot_2022-09-14_09-32-21](https://user-images.githubusercontent.com/106339342/190090686-c459e638-2088-44e7-ac72-dccec618193e.png)

**Comment by charlesdagenais** [comment]
Weird as I have a similar note and numberins is normal (9...10..11)
is it possible the 1 is hidden behind the parent div ?

How does it look if you set higher padding for .toc-widget (20 instead of 10):
```
.toc-widget {
    padding: 20px;
```

**Comment by anantone** [comment]
Thanks for the answer, it is definitely a good hypothesis, as in the desktop app I can get a glimpse of the missing 1s. But not at all in my browser (see attached images, browser is first, desktop second).

But I created a CSS note, added the #appCss label and copy/pasted your suggestion for extra padding, reloaded the frontend, and that didn't change anything (neither in desktop nor browser).

I'm using a custom theme in both instances, [melon-4](https://github.com/raphwriter/trilium-theme-melon), in whose CSS I couldn't find an existing .toc-widget entry. But I thought that my CSS note should override other sources??

Don't know what more to try...

![Screenshot_2022-09-14_22-10-25](https://user-images.githubusercontent.com/106339342/190252884-267dc98c-acba-4f35-b0ca-37549b6276dc.png)
![Screenshot_2022-09-14_22-10-39](https://user-images.githubusercontent.com/106339342/190252887-83d59cbe-3472-4c75-b30c-2d6818951350.png)

**Comment by zadam** [comment]
Hi, looks to be similar to #3025.

**Comment by anantone** [comment]
It does indeed. I don't have the same experience when activating/deactivating custom theme, but the clue seems to be "font size". I'm struggling a bit with the CSS though, finding what to adjust where (newbie problems). I'll investigate and report the precise method.

**Comment by anantone** [comment]
I'm happy to report that this is solved, thanks to the author of the theme. Here is his solution, if that can help similar problems in other themes:

https://github.com/raphwriter/trilium-theme-melon/issues/12#issuecomment-1248235329

`/* ----------- RIGHT PANE ------------ */ 
  
 div#right-pane.component { 
     margin-left: 10px; 
 } 
  
 div#right-pane.component div.card-header { 
     border-radius: 0; 
     font-family: var(--font-headers); 
     font-weight: normal; 
 } 
  
 div#right-pane.component div.card-header .toc > ol { 
     padding-left: 15px; 
 } 
  
 div#right-pane.component div.card-body .toc > ol > ol li { 
     list-style: lower-latin; 
 } 
  
 div#right-pane.component div.card-body div.toc-widget { 
 padding: 0 1rem; 
 contain: none; 
 overflow: auto; 
     } 
  `
