### ISSUE TITLE
(Feature request) Delete option for touch-based devices

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#3131]
### Describe feature

I've been using Trilium since the early days and have not looked back, but one thing that has become an annoyance is the inability to delete a note when using trilium on a touch screen like an ipad or tablet. The mobile view provides a delete option but is severely limited in features. The desktop view works great on an ipad but lacks a context menu. 

It would be nice if there was a menu option to delete a note.

**Comment by zadam** [comment]
Added this to here:

![image](https://user-images.githubusercontent.com/617641/190509257-e6743ee6-91f9-4f27-b80d-c4198d8d89fb.png)

**Comment by meichthys** [comment]
Perfect! Exactly where I would expect it 👍
