### ISSUE TITLE
(Feature request) Scroll or extend "Insert Note" menu

### ISSUE THREAD

**Issue by AustinCurrie** [zadam/trilium#3136]
### Describe feature

I make heavy use of the [template](https://github.com/zadam/trilium/wiki/Template) feature within Trilium. An issue I have is when I have a lot of template (inside of a workspace) and when I go to create a new note from one of my templates, the "Insert Note" menu will get cut off and not display all of the template options available. This is because I have too many templates than can be displayed within the drop-down menu.

![image](https://user-images.githubusercontent.com/40914121/190699289-da4dfd0d-4fb1-4620-a7f5-b58efc71ac88.png)
In the image above, not all of my templates are featured on the list because they're getting cut off at the bottom.

I'd like to have some way to be able to view all of the templates I have available to use. I can think of two solutions for this:
1. Any menu options cut off by the bottom of the screen will be "rolled over" or extended to the right in another menu drop-down. Something akin to what you see below:
![image](https://user-images.githubusercontent.com/40914121/190700110-9aa1e195-4840-4390-9013-56f41a23404b.png)
2. A scroll feature that lets you scroll up and down the drop-down menu so that templates cut off at the bottom can be "scrolled up" to be visible.
Something akin to this:
![image](https://user-images.githubusercontent.com/40914121/190700467-d567a4e0-9d73-4b22-911e-8217c65d850a.png)

Personally, I prefer the scroll solution, but either would solve my problem.

Thanks!

**Comment by zadam** [comment]
Hi, the submenu will be scrollable.
