### ISSUE TITLE
(Bug report) Trilium Crashes after deleting a TODO note

### ISSUE THREAD

**Issue by YJDoc2** [zadam/trilium#3146]
### Trilium Version

0.54.3

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Linux pop-os 5.19.0

### Description

Trilium crashes after attempting to delete a todo note on a fresh install

### Steps to reproduce
- open brand-new install of trilium 
- click on the new task widget icon on side bar
- close the (newly opened) tab/note of todo without making any changes
- right-click on the (newly crated) task note from the tree and select delete
- select `erase note permanently...` checkbox, (delete all clones left unticked)
- click ok

### Result 
After a pop-up/modal showing up at the top saying deleted (or note deleted, not completely sure of the exact wording) the window goes blank. There are no icons/widgets or anything that shows up, except the blank gray-ish (default color) window.
Attempting to open dev console opens it, but I am not able to switch to console tab from elements. Attempting to resize or grab and move the window in this state make it completely blank again (but it does get resized) and now ctrl+shit+i does nothing, dev console is not visible anymore. Even the close buttons are not visible, so have to close with ctrl+q

Trilium works normally after quitting and relaunching.

### Expected output
Note deletion should delete the note and reload the Trilium in a usable state.

I know this is a showcase thing, so the bug might not get fixed, but wanted to just report it, in case it has a deeper cause.

**Comment by zadam** [comment]
Hi, thank you for reporting this, it is indeed a bug in the application, in fact no even related to the TODO. Fixed, will be in the next release.
