### ISSUE TITLE
(Feature request) Add css class to component

### ISSUE THREAD

**Issue by raphwriter** [zadam/trilium#3147]
Would it be possible to add a css class (or id) to the parent div of `note-detail` and `note-list-widget`? At the moment it just has the "component" class which makes it difficult to style without affecting too many other elements.
![grafik](https://user-images.githubusercontent.com/28687075/191073669-8be3ca8d-ce04-4b9c-9ff5-00bb76f03721.png)

I tried to find the appropriate line(s) in the source code but am too unfamiliar with the framework.

Thank you for your dedication and continuous work, it is much appreciated.

**Comment by zadam** [comment]
Hi, I added "scrolling-container" class name. Note that these class names are not guaranteed to stay the same, although in practice they don't change often.
