### ISSUE TITLE
(Bug report) One canvas for all notes?

### ISSUE THREAD

**Issue by darmar** [zadam/trilium#3154]
### Trilium Version

0.55.1

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

Hi,
maybe I'm missing something regarding the Canvas note type...

No matter how many Canvas notes I create, they all share the same content?

Thank you,
regards

**Comment by darmar** [comment]
I just installed a server version (0.55.1) with Docker on Win10.
This canvas "bug" doesn't exist here, only on desktop as I see.

**Comment by darmar** [comment]
Further testing...
When having desktop client which syncs with Trilium server - the issue with canvas does not exist.

**Comment by zadam** [comment]
Hello, that is certainly strange. Do you have a way to reproduce this?

**Comment by darmar** [comment]
Well, it's quite simple.
I'm a first time user of Trilium - downloaded desktop version, unpacked ZIP file, started the EXE file, when asked - I've picked first option (standalone desktop instance without sync). Then, I was playing with the app, creating various notes, and one of those notes was Canvas type. Everything seems fine until I created a second Canvas type note - it already had the content of previous canvas note. But also, when I changed that note, the canvas changes reflected to the other canvas notes as well...

Also, when I started from fresh and tried with the option to connect to Docker server, the Canvas type notes worked fine without this issue.

**Comment by XXXJetfireXXX** [comment]
Sounds kinda like if you made a clone somehow... Did these notes have the same adress?

**Comment by darmar** [comment]
I've checked that, and no - not a clone, different address.
What I did was that I removed the app and run it again, and it doesn't seems to have the issue anymore with canvas type.
Will keep an eye on this and let you know if I can reproduce the issue.
