### ISSUE TITLE
(Bug report) Context menu should not be offset from where the cursor clicked

### ISSUE THREAD

**Issue by martinml** [zadam/trilium#3157]
### Trilium Version

0.55.1

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Server: Ubuntu 20.04.5. Local: Xubuntu 20.04.5.

### Description

My mouse has a fiddly right click button: it sometimes fires twice 😞 

It's totally my fault but it's only in Trilium where I have the problem where I **right click once and some option gets immediately selected**. This happens because all the context menus in my system open **next** to where the cursor clicked, but Trilium has [an offset](https://github.com/zadam/trilium/blob/8e23c1576314aef4d210cd0e502cbd10f17c51d2/src/public/app/services/context_menu.js#L30) so the cursor ends **inside** of the menu!

Let me illustrate what happens in my system when I right-click _and not move the mouse_:
![image](https://user-images.githubusercontent.com/217925/191811999-7dc310b4-12aa-4511-b968-ca7172708a2f.png)
![image](https://user-images.githubusercontent.com/217925/191812039-64aab3a4-9a21-4efe-baee-dddc4d7f8b38.png)
![image](https://user-images.githubusercontent.com/217925/191812195-2f560d78-9dfd-45c1-8298-4853810dd2a3.png)
See? Nothing is selected until you move the mouse 🕵🏼 

Now this is Trilium:
![image](https://user-images.githubusercontent.com/217925/191812352-c15a5523-2191-4120-982d-cb81cca429a6.png)
As you can see, the cursor ends inside the context menu, and if you accidentally right-click again (which for my stupid mouse is often) **you end selecting whatever option falls there**.

I've fiddled with the Chrome inspector changing that offset to several values but **zero** is the only one that never selected any option in the context menu in all the different conditions I came up with. Which I guess would warrant removing that value from the calculations altogether.

I can submit a PR if you want!

**Comment by zadam** [comment]
Hi, I've set the value to 0, it's better to be consistent with other UIs.
