### ISSUE TITLE
note.ancestors does not include search note

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3162]
Trilium version: 0.55.1

Running on Firefox 104.0.2

Reproduction Steps:

1. Create a note titled 'testNote'
2. Do a search 'note.title=testNote', and save the result into note
3. Attach a label '#testLabel' to the search note created in step 2
4. Do another search 'note.ancestors.labels.testLabel'

Result:

testNote should appear in the search result in Step 4, but in fact it doesn't.

**Comment by zadam** [comment]
Hi, this is intentional. Search notes are not considered to be true ancestors.
