### ISSUE TITLE
(Bug report) Bookmarking a template note will make related notes also bookmarked

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3173]
### Trilium Version

0.55.1

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows

### Description

Create a test note. Then create another note and set template to the test note with `~template=test`.

Bookmark the first note. There will be two notes showup in the bookmark area.

**Comment by zadam** [comment]
Well, yeah, notes with template relation inherit all the attributes from the template, including the bookmark label.

Might be surprising, but it does not look like a bug to me.

**Comment by Nriver** [comment]
I see the logic here now. Anyway, it's just a corner case. I believe most user will not bookmark a template note. I will close this.
