### ISSUE TITLE
Book or subtree global wordcount

### ISSUE THREAD

**Issue by anantone** [zadam/trilium#3178]
### Describe feature

Would it be possible, when #wordcount is set as inheritable for a whole book or subtree, to have the total wordcount (of all the children/parts) shown in the parent/root note?

**Comment by zadam** [comment]
That's not really how the inheritance works - inheritance just means that the attributes are automatically present on the descendant notes.

The script can be adjusted to also count words in the children, if you have some JS knowledge. Although for large subtrees this might become a performance issue.

**Comment by anantone** [comment]
I thought that the inherited attribute would tell the script which notes to include in the count? If not just the whole subtree.

Yes, I guess the script woud need to be extended. I don't know how to do that.

**Comment by XXXJetfireXXX** [comment]
Attribute just tells Trillium in which notes the widget should be active. Making it inheritable just tells it that "This widget will show up and do its thing in each note of the subtree". For counting words in all notes of a subtree you'd have to do some tweaking in code, indeed. Unfortunately I also don't know how to do that, didn't have time to practice xd

**Comment by anantone** [comment]
Thanks! Yes, I guess it could be used similarly to include notes in a subtree count (if it wasn't the whole subtree). But that is kind of moot without the ability to set up that feature...

**Comment by anantone** [comment]
Right
