### ISSUE TITLE
BasicAuth etc. for ETAPI

### ISSUE THREAD

**Issue by captain-joni** [zadam/trilium#3181]
### Describe feature

For better Integration Possibilitys it would be nice to have basicauth and other authenticationsystems for the ETAPI.
A Feature in the Options Section so that one could set AuthCredentials for the ETAPI. 

### Additional Information

The Problem i am having is the Integration between Trilium and n8n. I want an http Request so that i could retrieve data out of my Notes. And with the N8n http reqest only Basicauth options are given.

**Comment by zadam** [comment]
Hi, I added a Basic Auth support, some details are in https://github.com/zadam/trilium/wiki/ETAPI

Will be released in 0.56
