### ISSUE TITLE
Links within text notes

### ISSUE THREAD

**Issue by anantone** [zadam/trilium#3183]
### Describe feature

MAIN: I'd like to be able to create links within text notes, like from a word to another word, or from a word to a heading. ("Anchor links", I think.)

SECONDARY: if these links could have a label, that would be awesome.

**Comment by XXXJetfireXXX** [comment]
As @zadam said in #1021,
> while this is a valid feature request, it's quite a bit more complex than one could guess from outside. So don't get your hopes up, it's probably not coming in near or medium term future.
Trillium works best with smaller notes instead of smaller amount of large ones.

As a workaround, you could do this:

> As of now, you can split the large note into smaller parts and reference the needed one, or you can use "Cut and paste selection to subnote" and include it in the parent note to keep your text more consistent. ![image](https://user-images.githubusercontent.com/43646178/158110928-b5e2f13d-3dee-4ac4-ba55-7233515be3b8.png) ![image](https://user-images.githubusercontent.com/43646178/158110950-78fc089f-df7c-411c-9741-e332475260ec.png)
> 
> After that you can reference it with a link as well. ![image](https://user-images.githubusercontent.com/43646178/158111385-2b0e7fdc-c35a-4ed8-86de-003146a83572.png)

**Comment by anantone** [comment]
Thank you, yes I've been trying such workarounds. While I love Trilium Notes and have moved a lot of my work to it as it's so efficient and convenient (especially for people who need everything well organized and structured), I'm still running into that problem of managing longer evolving documents within it. I guess every great tool has its limitations, maybe I need to use something else and link to it within Trilium to connect the dots.

**Comment by XXXJetfireXXX** [comment]
Oh, I see. Well, another idea that comes to my head is using many subheaders and navigating through them using Table Of Contents.
![image](https://user-images.githubusercontent.com/43646178/194641524-2f828245-672c-4bf5-9747-6af664cca8ab.png)

**Comment by anantone** [comment]
That seems interesting, but I'm not able to reproduce it. Which header style are you using? Any other settings that could be needed to make it work?

**Comment by XXXJetfireXXX** [comment]
By default TOC widget turns on when your note has >5 headers. You can override that by adding \#toc attribute to the note or by changing it in options:
![image](https://user-images.githubusercontent.com/43646178/194644383-c394ac7d-5f34-44d5-94f5-566221592bfe.png)

**Comment by anantone** [comment]
Oh, I see. I thought that using the #subheader_name you were able to create an entry in ToC that's actually within a paragraph. That would have been a big step. Otherwise, I guess that means referring to the header by name, in order to go click in the ToC, but that still only refers to the header's content as a whole. 

Thank you for thinking about this anyway. In the meantime, I've been trying wiki.js for long documents with internal structuring, which I then link to their project part in my Trilium subtree. Seems okay, just a bit slower.

**Comment by anantone** [comment]
That and Markdown footnotes would be great.

**Comment by DuckersMcQuack** [comment]
> As [@zadam](https://github.com/zadam) said in [#1021](https://github.com/TriliumNext/Trilium/issues/1021),
> 
> > while this is a valid feature request, it's quite a bit more complex than one could guess from outside. So don't get your hopes up, it's probably not coming in near or medium term future.
> 
> Trillium works best with many smaller notes instead of smaller amount of large ones.
> 
> As a workaround, you could do this:
> 
> > As of now, you can split the large note into smaller parts and reference the needed one, or you can use "Cut and paste selection to subnote" and include it in the parent note to keep your text more consistent. ![image](https://user-images.githubusercontent.com/43646178/158110928-b5e2f13d-3dee-4ac4-ba55-7233515be3b8.png) ![image](https://user-images.githubusercontent.com/43646178/158110950-78fc089f-df7c-411c-9741-e332475260ec.png)
> > After that you can reference it with a link as well. ![image](https://user-images.githubusercontent.com/43646178/158111385-2b0e7fdc-c35a-4ed8-86de-003146a83572.png)

How did you make the note itself blue? I made a note into a hyperlink for a note, but the title didn't turn blue.

Oh, just realized it was the text in question the hyperlink directs from that goes blue.

**Comment by eliandoran** [comment]
@DuckersMcQuack , you can change the color of the notes as displayed in reference links and in the note tree by adding a #color label and assigning it your desired color in HEX format (eg. #ff0000 to get a full red color).
