### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by behold-research** [zadam/trilium#3190]
### Trilium Version

0.55.1

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

Ubuntu Desktop 20.04

### Description

Backlinks are not displaying properly.

Note backlinks are often not displaying at all. The only way to get them to show reliably is to force the reloading of the front end.

**Comment by XXXJetfireXXX** [comment]
Yeah, this is a known issue (#3158) and is getting fixed in the next release.

**Comment by behold-research** [comment]
Thanks!

**Comment by zadam** [comment]
Closing as fixed.
