### ISSUE TITLE
Add Any Existing Note to Relation Map (Feature request) 

### ISSUE THREAD

**Issue by egutierrez-ar** [zadam/trilium#3192]
### Describe feature

I would like to be able to add any kind of note to a relation map, not just being constrained to adding child notes to a map.

My goal is to be able to document structures in a heirarchical tree, and use relation maps outside of those heirarchies to document their interactions.

For example, this note structure:
```
- company1
  - team1
    - person1
    - person2
  - team2
    - person3
    - person4
- resources
  - object1
  - object2
- products
  - sku1
```

I would like to make separate relation maps that connect the interactions between the notes that I don't necessarily want them all to be child notes.

```
relation_map1:
[person1] -> writeSpec -> [object1]
[person2] -> readSpec -> [object1]
```

```
relation_map2:
[object1] -> isRequired -> [sku1]
[object2] -> isRequired -> [sku1]
```

**Comment by zadam** [comment]
Hi, you can add any note just by dragging it from the tree on the left to the relation map.

**Comment by egutierrez-ar** [comment]
Wow, I feel quite dumb now.
Thank you for the quick reply 😅
