### ISSUE TITLE
Attribute editable only for notes with existing attribute

### ISSUE THREAD

**Issue by mahdi1234** [zadam/trilium#32]
with 0.5.5

- select any node which had attribute from 0.5.4 and click button from menu, status bar or ALT+A

Attributes dialog invoked

- select any node which doesn't have any attribute yet or create new node and click button from menu, status bar or ALT+A

Nothing happens.

Repro with entirely fresh DB created in 0.5.5 as well.

**Comment by zadam** [comment]
I can reproduce this ... I just never tested new attribute dialog with note without attributes.
