### ISSUE TITLE
(Bug report) Unable to assign Ctrl+B as pasteMarkdownIntoText ?

### ISSUE THREAD

**Issue by u1735067** [zadam/trilium#3200]
### Trilium Version

0.55.1

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win 10 21H2

### Description

Maybe it's not possible, but I'm unable to associate `Ctrl+B` (nor `Ctrl+Y/U/I`) as a shortcut to `pasteMarkdownIntoText`, it there something wrong with this shortcut (like reserved for something) / is that expected?

If I set Ctrl+J, it works but I lose the Quick Jump, if I set `Alt+V` it seems to be ok.

Best

**Comment by zadam** [comment]
ctrl+b does not work within text editor since it's used to make the text bold

**Comment by u1735067** [comment]
I knew I was missing something obvious but I couldn't find what ^^'

And the same for Ctrl+Y (redo), U (underline), I (italic) ; thank you, sorry for the noise!

Maybe editor shortcut (https://ckeditor.com/docs/ckeditor5/latest/features/keyboard-support.html ; missing underline though) could be documented too for dummies like me?
