### ISSUE TITLE
(Bug report) Ubuntu installation from Flatpak creates multiple desktop entries 

### ISSUE THREAD

**Issue by vtlkzmn** [zadam/trilium#3201]
### Trilium Version

0.55.1

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu 22.0.4

### Description

Installed from Flatpak. Shows 2-3 entries in menu. One is automatically creating in ~/.local/share/applications, another, I think that comes from /usr/bin. Even if I remove entry from ~/.local/share/applications still shown 2 icons.

**Comment by zadam** [comment]
Hi, trilium itself generated an app shortcut, but this is not necessary for flatpak (and debian). I improved the detection. I'm not sure where does the 3rd shortcut come from, though.
