### ISSUE TITLE
(Bug report) Printing - text is gray instead of black

### ISSUE THREAD

**Issue by AKmatiAK** [zadam/trilium#3202]
### Trilium Version

0.56.0-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Win10 21H1 64

### Description

Hi. When I print documents text is gray instead of black. I have mono printer. It's not printer issue of course.

**Comment by zadam** [comment]
Hello, could you post an example printed PDF (print into a file instead of a real printer)?

When I try, the text is black.

**Comment by AKmatiAK** [comment]
[test.pdf](https://github.com/zadam/trilium/files/9795718/test.pdf)

**Comment by zadam** [comment]
Thanks. I didn't notice it at first since the text appears black to my eyes, but it is in fact slightly gray. I fixed the print color to black.
