### ISSUE TITLE
(Bug report) Edit block crash when I want to insert code block with cmake or nginx.

### ISSUE THREAD

**Issue by zhang-stephen** [zadam/trilium#3222]
### Trilium Version

0.55.1

### What operating system are you using?

macOS

### What is your setup?

Server access only

### Operating System Version

MacOS 13 Public Beta

### Description

When I want to insert some cmake snippet or nginx configuration snippet, I got this:

<img width="556" alt="截屏2022-10-23 03 34 54" src="https://user-images.githubusercontent.com/17326718/197359228-05a756c0-a68e-4429-8af9-5f4b3dd62b9c.png">

and the UI of Editing Block works but no effect when I click anyone of them. I think trilium should do something to restore the working if exception raised by CKEditor. And why invalid language of the code block could be enabled in the options > code notes?

**Comment by zadam** [comment]
Hi, it looks like you're using some plugin/extension for highlighting code blocks, something not supported in Trilium. So I guess you need to turn to the author of this extension.

**Comment by zhang-stephen** [comment]
Hi, thank you for the reply, this crash is caused by [Discussion #2822](https://github.com/zadam/trilium/discussions/2822), the cmake/nginx is not supported by highlight.min.js in the default. I tried to use customized highlight.min.js to solve it and it works well.

But I still think a more stronger exception handler is neccessary, e.g. restart CKEditor if exception were raised. What's your opinion about it?

**Comment by zadam** [comment]
> But I still think a more stronger exception handler is neccessary, e.g. restart CKEditor if exception were raised. What's your opinion about it?

I agree, but TBH I don't know how to do this ATM. These exceptions arise asynchronously and there isn't really a good place to catch them.

**Comment by zhang-stephen** [comment]
There should be a notification at least to inform user that CKEditor or other module crashed... This is my original idea. 😄 

I will close this issue after this comment. And look forwarding the better exception handler in the future.
