### ISSUE TITLE
(Bug report) the display effect of include note between view mode and editing mode is different

### ISSUE THREAD

**Issue by fooyoo** [zadam/trilium#3225]
### Trilium Version

0.56.1

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 19044.2130

### Description

The include note in "Read-only" mode displays different from it in "Edit" mode, especially when the title is long, the difference is obvious(see attached GIF).looks it displays by row in "Edit" mode while displays by column in view(Read-only) mode. 

I compared the html in devtool, found it seems include-note-wrapper is missed in "Read-only" mode, which seems also match code in includenote.js (https://github.com/zadam/trilium-ckeditor5/blob/stable/packages/ckeditor5-build-balloon-block/src/includenote.js)(in editingDownCast, there add include-note-wrapper while above no such wrapper.
```
		conversion.for( 'dataDowncast' ).elementToElement( {
			model: 'includeNote',
			view: ( modelElement, { writer: viewWriter } ) => {
				// it would make sense here to downcast to <iframe>, with this even HTML export can support note inclusion
				return viewWriter.createContainerElement( 'section', {
					class: 'include-note',
					'data-note-id': modelElement.getAttribute( 'noteId' ),
					'data-box-size': modelElement.getAttribute( 'boxSize' ),
				} );
			}
		} );
		conversion.for( 'editingDowncast' ).elementToElement( {
			model: 'includeNote',
			view: ( modelElement, { writer: viewWriter } ) => {

				const noteId = modelElement.getAttribute( 'noteId' );
				const boxSize = modelElement.getAttribute( 'boxSize' );

				const section = viewWriter.createContainerElement( 'section', {
					class: 'include-note box-size-' + boxSize,
					'data-note-id': noteId,
					'data-box-size': boxSize
				} );

				const includedNoteWrapper = viewWriter.createUIElement( 'div', {
					class: 'include-note-wrapper'
				}, function( domDocument ) {
					const domElement = this.toDomElement( domDocument );

					const editorEl = editor.editing.view.getDomRoot();
					const component = glob.getComponentByEl( editorEl );

					component.loadIncludedNote( noteId, $( domElement ) );

					preventCKEditorHandling( domElement, editor );

					return domElement;
				} );
```
I am not sure if this is the cause(maybe understand incorrectly), if not please ignore above code checking.  

![trilium-include-note-display](https://user-images.githubusercontent.com/36770100/197385723-a0f5fc8a-ab07-4438-96b4-d00eba773ef2.gif)

Thanks

**Comment by zadam** [comment]
Hi, you're correct, fixed.
