### ISSUE TITLE
Router not found for request /api/notes/nHhnKwklSU5Q/backlink-count

### ISSUE THREAD

**Issue by FlashYDirOX** [zadam/trilium#3230]
### Trilium Version

0.56.1

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Arch Linux 5.16.10.3

### Description

After I pull the latest docker image and update server client from 0.55 to 0.56.1, I get this error message pronpted whenever I try to switch a note tab. 

Error when calling GET notes/LEqpllgXaPIi/backlink-count: error - {"message":"Router not found for request /api/notes/LEqpllgXaPIi/backlink-count"}

And the path after /api/notes/ varies from time to time when I selected differenct notes. For example:
Error when calling GET notes/nHhnKwklSU5Q/backlink-count: error - {"message":"Router not found for request /api/notes/nHhnKwklSU5Q/backlink-count"}

I m not sure if it is a client side error since I've cleared the cache of my browser and still get this error. 
Sorry for my poor English, I am not a native speaker though. I would be appreciate if you solve this.

**Comment by FlashYDirOX** [comment]
Anyway I m using a custom theme melon-theme-4 if that helps.
And in this case I can still save my notes correctly, however, the error messages are really bothering so I need to fix it. :)

**Comment by zadam** [comment]
Hello, I'm quite sure that this is a browser cache issue. Try again to reset the cache.

**Comment by FlashYDirOX** [comment]
> Hello, I'm quite sure that this is a browser cache issue. Try again to reset the cache.

That helps, thanks. This time I cleared the cache of the browser and simply restarted the computer and it was fixed.
