### ISSUE TITLE
(Feature request) configurable math delimiter when import/export from/to markdown

### ISSUE THREAD

**Issue by zhang-stephen** [zadam/trilium#3231]
### Describe feature

The default inline math delimiter is `\(` and `\)` when exports note as markdown, I hope this is configurable. the `$` is preferred in some markdown editor/renderer, e.g. Typora or Hexo.

And `$$` is preferred, as the block math delimiter. 

And inline math with `$` or math block with `$$` won't be recognized when import markdown. I have many complexed math equations and I do not want re-type them in after importing... 😫 

### Additional Information

I remember the math support is provided by KaTeX? There is an example to render use different delimiters: [KaTeX - usage](https://katex.org/docs/autorender.html#usage), FYI.

**Comment by zadam** [comment]
Hi,

Trilium uses commonmark parser to convert Markdown into HTML. I'm not very knowledgeable in Markdown, but my impression is that math is not part of commonmark spec and thus might not be recognized during import at all.

**Comment by zhang-stephen** [comment]
Yes, LaTeX is not a part of CommonMark, but I think the CommonMark is a bit of obsolete... As a web application, integrate the [markdown-it](https://github.com/markdown-it/markdown-it), a flexible and easy-to-extend markdown parser, and its ecosystem as an optional markdown parser is a better choice in my opinion.

**Comment by Liu-Wenzheng** [comment]
I have the same issue here. The maths block is ill-formatted when I export the note as markdown (opened by Typora) or HTML (opened in Safari). I hope Trillium can provide us an option to use the LaTeX format in Maths-related writing.

**Comment by Liu-Wenzheng** [comment]
Btw, MathJax is an excellent approach to dealing with Math blocks in Trillium.

**Comment by Aziily** [comment]
> 

I have the same problem, however I don't know how to use a customed render to solve it, can you give me some suggestion? Some blogs or other

**Comment by eliandoran** [comment]
Added support for Markdown $ and $$ equations for import/export in [TriliumNext}(https://github.com/TriliumNext/Notes). Will be available in the upcoming version.
