### ISSUE TITLE
(Feature request) More icon from boxicon?

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3233]
### Describe feature

The new icon in the reference link looks so great, it motivates me to use more icons.
I was trying to find an icon for tea, but couldn't find a 'leaf' or the 'java' cup icon which should be included in boxicon.

**Comment by zhang-stephen** [comment]
or support font-awesome(free icons)?

**Comment by Nriver** [comment]
Ok, I figured out that I can get my leaf by changing the label to `#iconClass="bx bx-leaf"`, but it would be more convenient if I can search and find it in the icon list.

**Comment by Nriver** [comment]
Ok, I figured out that I can get my leaf by changing the label to `#iconClass="bx bx-leaf"`, but it would be more convenient if I can search and find it in the icon list.

**Comment by zhang-stephen** [comment]
> Ok, I figured out that I can get my leaf by changing the label to `#iconClass="bx bx-leaf"`, but it would be more convenient if I can search and find it in the icon list.

more convenient... the icon is clickable, and you can select icons from the UI popped up. I think this is what you want 😂

**Comment by Nriver** [comment]
> > Ok, I figured out that I can get my leaf by changing the label to `#iconClass="bx bx-leaf"`, but it would be more convenient if I can search and find it in the icon list.
> 
> more convenient... the icon is clickable, and you can select icons from the UI popped up. I think this is what you want joy

Unfortunately, `leaf` is not in the pop up list. For now, the only way to get it is to manually change the label value.

**Comment by zadam** [comment]
@Nriver "leaf" was not searchable because the icon index was out of date and the leaf icon was one of the newly added icons.

This should be fixed now.
