### ISSUE TITLE
(Bug report) Workspace not working ?

### ISSUE THREAD

**Issue by davidszerman** [zadam/trilium#3234]
### Trilium Version

0.55.1

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Debian 

### Description

Hello,

I have added the #workspace label to a subtree, reloaded the frontend but it does not change anything, no workspace icon in order to enter into it...  
The workspace icon (not in the screenshot with boxicons work)

Screenshot below

Whant did I do wrong ?

Thanks

![image](https://user-images.githubusercontent.com/27421517/197473675-20be6995-3fd3-45f3-a275-8a146cca10d8.png)

**Comment by zadam** [comment]
Hi, the icon appears upon hovering:

![image](https://user-images.githubusercontent.com/617641/197877287-5d5e4fb6-4d11-49fd-959b-ea47fd341c84.png)

BTW, reloading frontend is not necessary.

**Comment by davidszerman** [comment]
Hi @zadam 

thank you for your answer but it does not work ; in the screenshot below, I have selected the root note and have got the mouse on the note title but nothing appears...

![image](https://user-images.githubusercontent.com/27421517/197983750-1f5211ec-9ea3-43a3-8054-e8a0380b2ed0.png)

**Comment by davidszerman** [comment]
Oups, it seems it is related to the theme I was using... 
I was trying other themes and... it works with another one... !
