### ISSUE TITLE
Can't create new internal links (Bug report) 

### ISSUE THREAD

**Issue by Lolabird** [zadam/trilium#3236]
### Trilium Version

0.56.1

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint 20.3 Cinnamon

### Description

New internal links are not being created when I try to create them.

**Comment by Nriver** [comment]
The console complains about `Uncaught TypeError: Cannot read properties of undefined (reading 'editing')` when creating the link by clicking the button in the popup menu.

I find something interesting. As a temporary solution, you can use Ctrl+L to create link. Yeah, the shortcut still works. (The shortcut and the button seems to trigger different popup UI.)

You can also use @ command or copy&paste from the note tree.

**Comment by sigaloid** [comment]
I can confirm I've had reports of this happening to my users as well. For now I've downgraded them to 0.55.1 as there is no database schema change.

PS: 0.56.1 is a beta release, even though it wasn't labeled as one in the name (it was in the GitHub description).

**Comment by seryeb** [comment]
I have the same problem here. Thanks for the shortcut solution! @Nriver

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
