### ISSUE TITLE
Trying to run trilium Server on userland [UBUNTU]

### ISSUE THREAD

**Issue by BHARATHCK** [zadam/trilium#325]
Output after running ./trilium.sh in the terminal :
" ./trilium.sh: line 2: ./node/bin/node: No such file or directory"
--------------------------------------------------------------------------------------------------------
Even tried with manual command "./node/bin/node src/www" and also tried using chmod to mark node as executable .
But , no luck!

Any packages needed to be installed or it doesn't work in such environment?

**Comment by zadam** [comment]
Hello. I'm running the server on ubuntu as well and don't have such problems.

Was the unpacking finished correctly? Can you check if the "node/bin/node" exists?

**Comment by BHARATHCK** [comment]
Yes , unpacking finished correctly and every directory exists.

But , yeah as it is running perfectly fine on Ubuntu amd64 .

But I was trying to use it in Ubuntu arm64 environment using userland app. But I do have amd64 dependencies installed.

**Comment by zadam** [comment]
Oh I see, I'm afraid that won't work, the "server" package has binaries built for AMD64.

You could try to build the trilium yourself: https://github.com/zadam/trilium/wiki/Manual-server-installation
