### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by behold-research** [zadam/trilium#3251]
### Trilium Version

0.56.1

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu Desktop 20.04

### Description

I can no longer add internal trilium links to other notes. The dialog to add a link to another note comes up but after clicking the button or pressing enter nothing happens

**Comment by sigaloid** [comment]
Fixed in #3236 - you can revert to 0.55.1 to fix it or wait for the next beta release

**Comment by behold-research** [comment]
Thanks

**Comment by behold-research** [comment]
Useful info about the shortcut in the other thread
