### ISSUE TITLE
(Bug report) Ctrl + F after a search window is open does not autofocus

### ISSUE THREAD

**Issue by thansk** [zadam/trilium#3252]
### Trilium Version

0.55.1

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

N/A

### Description

When inside a note, Ctrl + F opens a search bar, then I focus on the note and when I decide to search again Ctrl + F does not autofocus the search dialog.

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.

**Comment by thansk** [comment]
Hi, @zadam 

I've updated to 0.56.2 and this doesn't seem to be fixed for me.

Here is a video that might help illustrate it, you can see the key presses on the bottom right corner and how Ctrl+F when a find widget is open does not refocus it:

[ctrlf](https://user-images.githubusercontent.com/53181514/201550440-78ec7019-bbc0-4fb0-8322-ccbe5131b7f5.mp4)

**Comment by zadam** [comment]
Hi, this was released only in 0.57.0-beta yet:

![image](https://user-images.githubusercontent.com/617641/201753802-bf163577-103e-4be6-b71b-7a20a5c60ea5.png)

**Comment by thansk** [comment]
Sorry, didn't see that.
