### ISSUE TITLE
Table of Content shortcut

### ISSUE THREAD

**Issue by edalcin** [zadam/trilium#3259]
Hi there,

I was editing a note and, suddenly, I pressed something that shown a beautiful "Table of Content" on the right side of the note. Please, what shortcut toggle this feature?

Thanks in advance!

Eduardo

**Comment by Nriver** [comment]
By default, the toc will show up automatically if there are more than 5 headings. You can change the number in settings.

**Comment by edalcin** [comment]
Thanks!
