### ISSUE TITLE
how to change the text size

### ISSUE THREAD

**Issue by maniasso** [zadam/trilium#326]
I just running the app and loved it, however I see there's no way to adjust the text size, I see other people commenting about and new release probably will have this feature... in meantime is there a way to change the text size even changing at code? I 'm at configuration files from trilium?

**Comment by zadam** [comment]
Hello, yes, it's a planned feature.

Currently you can scale the whole app with pressing CTRL and plus/minus (or in Options tab). If you really need to change just font size, you can create new CSS code note, add label @appCss and save your custom styles in there. For example:

```
body {
    font-size: larger;
}
```

For more specific settings you can open dev tools with CTRL-SHIFT-I and find appropriate selectors.

**Comment by maniasso** [comment]
Sorry for my ignorance, when you say open dev tools using CTRL-SHIFT-I , are you refering this to run this command into firefox for ex?
also this code you mentioned should be add at some place when open the dev tools?

**Comment by maniasso** [comment]
Ok, I got it how to do, but in case I do that I need to load the css file every time, is there a place in a filesystem where I can save it to load automatically or a css file that I can edit and add the code for load automatically everytime?

**Comment by maniasso** [comment]
I see there's update in the code which contains some fields to adjust the text size, I used it to create a new docker image and worked as charm, thanks a lot.
