### ISSUE TITLE
(Bug report) /share vs /share/ - relative URLs don't work in /share

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#3264]
### Trilium Version

0.55.1

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Pop!_OS 22.04 LTS

### Description

You can see the actual issue in the included links.

If you open https://trilium.agentydragon.com/share, the CSS on the share root page does not work, and the links lead to URLs like `https://trilium.agentydragon.com/7fpyxNxJPVSH`, which give an error like `{"message":"Router not found for request /7fpyxNxJPVSH"}`.

If you open https://trilium.agentydragon.com/share/ with a slash at the end, the CSS and links both work. Looks to me like this is an issue with relative links.

I think it would work to just redirect `/share` -> `/share/`.

**Comment by sigaloid** [comment]
[This](https://github.com/zadam/trilium/blob/master/src/share/routes.js#L114) looks like the problem, it should redirect in the first case

**Comment by zadam** [comment]
Fixed, thanks.
