### ISSUE TITLE
(Feature request) Index of shared notes

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#3265]
### Describe feature

I have a lot of shared notes, and I'd like my `/share/` page to have a list of them all somewhere. Right now, `#shareRoot` page's sidebar only shows pages directly under it. If I wanted to use the sidebar, I'd have to move all my shared pages under a common root, which takes work.

I'd prefer to have an option to expose the whole list of my shared pages somewhere on a shared page.

(Or maybe even more generally, expose the result of a search query?)

**Comment by agentydragon** [comment]
I just tried adding a search note and sharing it. Unfortunately, doesn't work as a workaround.

![image](https://user-images.githubusercontent.com/714892/198854463-c4877163-b0bf-4ca4-bdc2-0ba1bcdd461e.png)

**Comment by zadam** [comment]
I added a `#shareIndex` which you can add to a note - this note will then append a list of all shared note roots to the content. You can combine it with a `#shareRoot`.

**Comment by agentydragon** [comment]
sweet! looking forward to the new version cut :)

**Comment by uhdotie** [comment]
Hi, this only seems to work on a shared note. I'd like a private index of shared notes for my own reference, is that possible?

**Comment by eliandoran** [comment]
@dahamsta , there already is one. Go to the Trilium menu -> Show Shared Notes Subtree.

**Comment by uhdotie** [comment]
Brilliant, thank you.
