### ISSUE TITLE
[BUG] Emptying Attribute doesn't trigger 'runOnAttributeChange'

### ISSUE THREAD

**Issue by Belphemur** [zadam/trilium#327]
Hello,

When I set to null some attribute, I don't get the relation `runOnAttributeChange` called.

Is it a bug or is it on purpose ?
It would be nice to be able to act (in my case remove branches) when I null an attribute.

**Comment by zadam** [comment]
I assume that by emptying/setting to null you mean deleting the attribute, right?

In general I don't have these events fully thought through, but in this case I agree it makes sense that this it should be called for attribute deletions as well.

**Comment by zadam** [comment]
fixed in 581b1fdaa5f1c89956aa38a328df4ac5179a3ba8

**Comment by Belphemur** [comment]
Yes this is exactly what I meant :) 

It's useful to cleanup after having created prefix branches that aren't used anymore. 

________________________________
