### ISSUE TITLE
Bad (possibly malicious) link in manual installation wiki

### ISSUE THREAD

**Issue by michaelasp** [zadam/trilium#3271]
Just was browsing the wiki to get setup, looks like there was a change last May in https://github.com/zadam/trilium/wiki/Manual-server-installation where someone changed the link for node.js installation. PTAL and see if that's intentional. Thanks!

**Comment by Nriver** [comment]
The bad link is `https://www.ps3 cfw.com/cool.php?item=12150944`(I put a space in url, just don't click it). Similiar to this one https://github.com/OpenSC/OpenSC/issues/2554.

The website seems to be an ip logger and recorded in multiple blockers https://github.com/search?q=ps3cfw&type=code I'd say it's guilty.

**Comment by zadam** [comment]
Thanks for the heads up, I fixed the page.

The wiki was until recently publicly editable, until a few months ago somebody started to insert these links.
