### ISSUE TITLE
Theme and Icon support

### ISSUE THREAD

**Issue by ZMonk91** [zadam/trilium#328]
Hi there. I would like to request 3 things, all related to theme support:

1. Create a folder/supported directory/location option in the menu to store CSS files for themes.
2. Change the current CSS values to all point to CSS Variables. i.e. OLD: ` color: #1234` NEW: `color: var(--red)`
3. (Perhaps this is just my lack of skill and is already available), provide a way to classify notes under more specific Classes. For instance, changing the type to Javascript or C++ will render different classes. 

Reasoning:
1. This would allow theme and/or script files to be hidden from the main knowledge path. In turn, making for a more cleaner approach. 
2. This would streamline the process of others creating themes by making it more readable and easier to locate specific elements. This could also enable a future option in the menu for users to specify accent options.
3.  This would enable the option to change the icons depending on language and provide a much more customizable experience. 

As it stands, I have been working on my own custom theme for Trilium. [Found Here](https://github.com/ZMonk91/Material-Dark-Trilium)
Due to different circumstances, I've had difficulty getting the uncompiled program to run, while Gitpod continually crashes. This causes my theme development to be a sort of guesswork going off the old CSS files. I still have a lot of things to change, but there's little to no documentation on them. With these options available, future theme development could become more successful. Notice I'm not asking for themes, only features that would make theme development better for others. I believe having a more visible and accessible approach will allow the theming community to build itself.

**Comment by zadam** [comment]
Wow, your theme looks pretty nice!

1. I assume you still mean folder inside Trilium's document. I'm not sure if this requires some special handling and I think it's best to leave it to the users to organize their data. To have this "out of the way", you can e.g. store all such things in one top level note called "system" or something which you would keep collapsed unless specifically needed.

2. I need to research this. So far I wasn't even aware of CSS variables, but they look good! I thought you need to use some CSS preprocessor (which I'd like to avoid) to have this. Seems like a way to go.

3. Yep, currently we have CSS classes only per basic note type (text/code/file/image etc.), what you're suggesting might be possible based on note's mime type.

**Comment by zadam** [comment]
I create a set of CSS variables which should allow you to create basic color themes in pretty simple way:

```css
    --main-background-color: white;
    --main-text-color: black;
    --accented-background-color: #eee;
    --more-accented-background-color: #ccc;
    --header-background-color: #f8f8f8;
    --button-background-color: #eee;
    --button-border-color: #ddd;
    --button-text-color: black;
    --button-border-radius: 3px;
    --muted-text-color: #444;
    --input-text-color: black;
    --input-background-color: white;
    --modal-background-color: white;
    --hover-item-text-color: black;
    --hover-item-background-color: #eee;
    --active-item-text-color: black;
    --active-item-background-color: #ccc;
    --menu-text-color: black;
    --menu-background-color: white;
```

There will be probably some more added along the way. Of course more advanced theming will have to be done through classic CSS selectors.

I also addressed your third point - tree nodes now have CSS class generated from note's mime type - e.g. JavaScript note has class mime-application-javascript (JS mime is "application/javascript").

This should be released as beta sometimes this week.
