### ISSUE TITLE
How to set multiple property values at once using ETAPI

### ISSUE THREAD

**Issue by yingjialong** [zadam/trilium#3284]
### Describe feature

How to set multiple property values at once with ETAPI

**Comment by zadam** [comment]
Hi, could you please specify in more detail what you want to do?

when you e.g. want to update a note, just send PATCH to the `/etapi/notes/[noteId]` with:

```json
{
   "title": "new title",
   "type": "text"
}
```

**Comment by yingjialong** [comment]
I have created a note，and sent POST to the /etapi/attributes. but i had five attributes to need to set,i had to use the api 5 times.

**Comment by zadam** [comment]
I see, at this point there isn't a bulk endpoint to add/update multiple attributes at once.
