### ISSUE TITLE
(Type: Question) enter text in the PC web browser, the smartphone will update the content in real time

### ISSUE THREAD

**Issue by dahe5ma1** [zadam/trilium#3292]
0.55.1 server version, the PC web browser and the smartphone web browser open the same notes, enter text in the PC web browser, the smartphone will update the content in real time. Enter text into the phone, and the PC will refresh the content in real time. But the version after 0.55.1 does not have this function.
Is this feature canceled or a bug?

**Comment by zadam** [comment]
Hi, thanks for reporting, this is indeed a bug/regression. Fixed, will be in 0.56.3
