### ISSUE TITLE
(Feature request) Setting CSS on all shared pages

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#3294]
### Describe feature

I have a CSS file I want to apply to all my publicly shared pages. The `~shareCss` relation works for putting it on my `#shareRoot` page, and on every other page that I explicitly put the relation on.

I'd like to ideally just open up large parts of my Trilium database, though, and adding the `~shareCss` attribute to the notes one by one when I turn on sharing for the notes is tedious.

I've tried setting `~shareCss` on the "Shared notes" note under which shared notes all automatically go, and setting it as inheritable, but it didn't work. I guess probably because those notes are only actually cloned under there, not really present.

One possible implementation would be: `#shareDefaultCss` on a stylesheet note to make that the default. Another would be to make the inheritance I tried work.

**Comment by zadam** [comment]
Hi,

> I've tried setting ~shareCss on the "Shared notes" note under which shared notes all automatically go, and setting it as inheritable, but it didn't work. 

That does actually work. Depending on the method you did this (e.g. SQL insert), you might need to restart the app to invalidate the caches. Also it needs to be inheritable.

> I guess probably because those notes are only actually cloned under there, not really present.

"clones" are actually all equal, there's no differentiation or special status of e.g. the original clone.

I'm working on the support for exposing hidden subtrees which will make this possible from the UI.

**Comment by agentydragon** [comment]
I've had this relation, with it set as inheritable, in my database for a while on the `share` note:
![image](https://user-images.githubusercontent.com/714892/200222055-28fca2ed-07e0-4729-8ee9-eb36c608690f.png)

The stylesheet gets properly shown on the note I have at https://trilium.agentydragon.com/share/, which looks like this:
![image](https://user-images.githubusercontent.com/714892/200222328-9a64dda8-a5f9-4855-a7d0-0c4f9953f37f.png)
I've added the `~shareCss` relation to this note explicitlly.

Here's an example note which doesn't seem to have the CSS applied: https://trilium.agentydragon.com/share/GuGRYgzXvhzm
It is in the Trilium tree under the `share` note ("Shared notes" root), so I'd expect it to inherit the `~shareCss` relation which I have defined there. This is what I see in Trilium:
![image](https://user-images.githubusercontent.com/714892/200222688-56d2658f-76c4-4dfc-87eb-266148d9ca85.png)

It looks like it does inherit the relation definition from the shared notes root, but not the value.

I'll go try and restart the server, but I expect it won't help, I've had this setup for a couple of server restarts already.

**Comment by agentydragon** [comment]
Server upgrade + restart didn't help.

**Comment by agentydragon** [comment]
I've made a test page with 3 levels of nesting in my shared notes:
![image](https://user-images.githubusercontent.com/714892/200289707-c2139a89-d374-4740-9ad2-9e3bab088da4.png)
https://trilium.agentydragon.com/share/kuk4BhZzpsGM

the top one has owned attributes: `#relation:shareCss(inheritable)=single ~shareCss=[the CSS note]`

the CSS is correctly inserted into the top note:
![image](https://user-images.githubusercontent.com/714892/200289963-a077f1d6-f42c-4631-95fe-4a988242c55b.png)

but it's not applied in the nested notes, like https://trilium.agentydragon.com/share/X3Iv8Gyc03J4
![image](https://user-images.githubusercontent.com/714892/200290109-c969d4b5-448b-4d5d-b28f-7a6087e6eb62.png)
![image](https://user-images.githubusercontent.com/714892/200290160-a8bcb5e8-f224-41c6-95d4-4abeadfe0d2d.png)

**Comment by agentydragon** [comment]
oh, I think I figured it out. I had these attributes set:
`#relation:shareCss(inheritable)=single ~shareCss=[...]`
whereas the correct setting is:
`~shareCss(inheritable)=[...]`

I was confused between "inheritable relation definition" and "inheritable relation".
