### ISSUE TITLE
Fail to open in mac

### ISSUE THREAD

**Issue by yesvods** [zadam/trilium#330]
When I open the release of v0.27.4.7, then it will be crashed in my OSX 10.14.2.

![image](https://user-images.githubusercontent.com/4458848/51073995-e5b03c00-16b3-11e9-9703-095b4ced4957.png)

**Comment by lorza** [comment]
Also having this issue. Have you managed to fix this?

**Comment by yesvods** [comment]
I have no error log about that crash.

**Comment by yesvods** [comment]
Closed due to no more progress.
