### ISSUE TITLE
Remove "Content of this note cannot be displayed in the book format" (Feature request) 

### ISSUE THREAD

**Issue by anantone** [zadam/trilium#3301]
### Describe feature

Would it be possible to remove the mention of "Content of this note cannot be displayed in the book format" which appears in book notes? Just to make things prettier...

![image](https://user-images.githubusercontent.com/106339342/200666943-00be4606-f3a3-4e61-8834-e9757e4034f3.png)

**Comment by zadam** [comment]
Hi, fixed, yeah, it doesn't make much sense for the book note.

**Comment by anantone** [comment]
Wonderful, thanks!
