### ISSUE TITLE
List start index

### ISSUE THREAD

**Issue by sindzicat** [zadam/trilium#3308]
### Describe feature

Hello!

I need the possibility to set ordered list start index. Like in example below:

![image](https://user-images.githubusercontent.com/33900895/201009131-0aa6c4fe-87a4-428e-a021-2d396e14d320.png)

As we can see on screenshot above, second list starts with number 5.

This feature is already available in ckeditor-5: https://ckeditor.com/docs/ckeditor5/latest/features/lists/lists.html#list-start-index

I got example from this doc.

**Comment by sindzicat** [comment]
@zadam, thank you very much! Surprisingly fast!
I just downloaded zip archive of this repo, `npm install`, `npm run start-server`. All works file 👍 
Is there instruction how to build electron portable app for Windows 10?

**Comment by ferrlen** [comment]
@sindzicat I'm not sure I understand your question, one can already download a portable x64 version for Win 10 https://github.com/zadam/trilium/releases/tag/v0.57.5

**Comment by sindzicat** [comment]
> @sindzicat I'm not sure I understand your question, one can already download a portable x64 version for Win 10 https://github.com/zadam/trilium/releases/tag/v0.57.5

I am aware of this and use trilium as a portable application on Windows. I asked how I could build the application myself from source code on Github.

**Comment by zadam** [comment]
@sindzicat - you can follow the ~/bin/build-win-x64.sh - I'm doing all the building on a linux box, but it should be possible to do that on windows as well (maybe with some tweaks)
