### ISSUE TITLE
(Bug report) backlink ungenerated in drag

### ISSUE THREAD

**Issue by xuxanwan** [zadam/trilium#3314]
### Trilium Version

0.57.0-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows10 21H1 19043.2251

### Description

When I drag a note from the left tree to another note, the backlink is not generated.

https://user-images.githubusercontent.com/5035496/201526458-9ef88974-3474-4205-8408-84ed0c5935fb.mp4

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.
