### ISSUE TITLE
I hope that the software can add an alias attribute, and when @ referenced, the alias can be referenced directly.

### ISSUE THREAD

**Issue by sc8cn** [zadam/trilium#3316]
I hope that the software can add an alias attribute, and when @ referenced, the alias can be referenced directly. This feature I used in obsidian, very useful feature.

**Comment by Nriver** [comment]
You can create a promoted attribute called 'alias' to note template. Just like the 'weight' attribute in the built-in Journal demo.

**Comment by sc8cn** [comment]
您好，来信已到达目的地，我的主人将择日阅读，谢谢！

**Comment by sc8cn** [comment]
> You can create a promoted attribute called 'alias' to note template. Just like the 'weight' attribute in the built-in Journal demo.

I don't know if I didn't express it clearly or I didn't understand what you said. I hope that when writing articles, it can be more flexible to quote other article titles, which helps to write articles and keep sentences flowing. As shown in the picture, I want to quote the alias test1 in the Original title article in the new note, but the result shows "Original title".
![1](https://user-images.githubusercontent.com/26480118/201906562-4d63d4de-4f28-4a24-810d-a780785280ef.jpg)
![2](https://user-images.githubusercontent.com/26480118/201906570-3592b0b2-5660-4bc9-a0bd-492392a4c922.jpg)

**Comment by Nriver** [comment]
You can use `ctrl+l` to create link with arbitrary words.

**Comment by sc8cn** [comment]
> You can use `ctrl+l` to create link with arbitrary words.
Thanks a million。
