### ISSUE TITLE
(Feature request) JS + CSS compress

### ISSUE THREAD

**Issue by yanickxia** [zadam/trilium#3322]
### Describe feature

selfhosted trilium open too slow, looks too many requests for js/css

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/6848593/202600842-fe71ddb3-5fec-484d-8612-e76a2232321d.png">

Response Header also not cache
```html
Cache-Control: public, max-age=0
```

**Comment by Nriver** [comment]
I think that's the job for Nginx, you can easily achieve compression by enabling gzip. For further optimization, you
 can enable http/2 to reduce response request count.

**Comment by yanickxia** [comment]
@Nriver sound nice. i try it, but nginx seem only support ssl http2.  
nginx reverse proxy access trilium node api, seem also by http 1.1,  [Nginx-proxy-setup](https://github.com/zadam/trilium/wiki/Nginx-proxy-setup), speed also not fast……

maybe , i should force add cache-control in nginx configration

**Comment by bbsweb** [comment]
I think you should use webpack to build these js files or use the release package directly

![image](https://user-images.githubusercontent.com/20337958/202650742-4136d0fe-77b8-48d4-8bd4-fa23fb44a4db.png)

as the image shows, after building, you can get fewer js request

**Comment by zadam** [comment]
Hi, Trilium uses webpack and you shouldn't see these files being loaded individually. It looks like you're using a non-official build / use cloned branch and running it directly or something like this.

What's the Trilium version you're running and how did you get it?

**Comment by yanickxia** [comment]
@zadam  screenshot that use [Docker installation](https://github.com/zadam/trilium/wiki/Docker-server-installation) for chrome. but i'm  try desktop version, it's fever js request.

seem something different...

**Comment by zadam** [comment]
@yanickxia thanks, docker images indeed did not use webpack files. Fixed.
