### ISSUE TITLE
(Bug report) Displays top of the note after a link is added from "add link" window

### ISSUE THREAD

**Issue by Potjoe-97** [zadam/trilium#3325]
### Trilium Version

0.56.2 flatpak build

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Pop os 22.04

### Description

Since the last version, I noticed that after a link to a note is added from the "add link" window, editor now displays the top of the note, whereas it should still display the location of the newly added link. This behaviour does not occur when a link is added with "@". 
To replicate :  
1) Go at the bottom of a note where the text is longer than what your screen can display (thus you need to scroll to see the last lines)
2) Add a link from the "add link" window
3) You're sent back at the top of the current note, instead of still being at the bottom, where the link was added. 

Video capture : 

https://user-images.githubusercontent.com/42873357/202669488-53e6761f-b7e9-4e01-b216-0a38ff02a276.mp4

**Comment by zadam** [comment]
Hmm, unfortunately I can't reproduce this. I could not test the flatpak build, I will do that once I get to my linux box.

**Comment by Nriver** [comment]
I can reproduce it with github release file on windows and linux.
Just point to any position in the note. Press `ctrl+shift+c` followed by `esc`, the cursor will jump to the beginning of the note.

**Comment by zadam** [comment]
Thanks, managed to reproduce and fix it now.
