### ISSUE TITLE
(Bug report) paste-after does not work - moving notes within the tree

### ISSUE THREAD

**Issue by LiamFry** [zadam/trilium#3328]
### Trilium Version

0.56.2

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Debian 11

### Description

When you cut a note - either via context menu or CTRL-X - the "Paste after" (via context menu) does nothing.

This situation is exacerbated by the fact that you cannot drag/drop a note (to set its place in the tree) when the drop destination would require scrolling. For example, the current sizing of my Trilium window shows 20 items in the tree . If I click/drag a note, I can only drop it somewhere within those 20 items; the tree does not scroll as I drag.

All this means that, in order to move a note any appreciable distance, my only choice is repeated use of CTRL-UP or CTRL-DOWN.

**Comment by zadam** [comment]
Hi, paste after has been already fixed in https://github.com/zadam/trilium/issues/3276 but released only in 0.57.0-beta

> This situation is exacerbated by the fact that you cannot drag/drop a note (to set its place in the tree) when the drop destination would require scrolling

Actually it does, but it sometimes require a little bit of playing with the cursor before it catches on ...
