### ISSUE TITLE
(Feature request) Ability to disable/change interval of auto-save

### ISSUE THREAD

**Issue by kingcobra2468** [zadam/trilium#3334]
### Describe feature

On some devices types (particularly those with lower-end hardware) the `SpacedUpdate` interval of every 1 second causes significant lag in Trilium's web interface (especially when editing large notes). Idea is to add support to disable the SpacedUpdate sync (could be something localized in order to allow more powerful devices to continue doing the auto-sync) and instead add an option to manually save each time the user feels that its time to sync. Another option (or perhaps in addition to the other idea) could be to add support for a setting such that a user can modify the SpacedUpdate interval from 1 second to any value they choose. I've looked into the codebase and might be able to implement this functionality and create a PR if you are interested in adding this feature into Trilium.

**Comment by zadam** [comment]
Hi, the reason why I kinda want to keep it fixed at 1 second is that it's immediate and Trilium therefore doesn't really need to show the user the saved status.

If we allow this to change, there's now several new things to consider - how to show the saved status, what to do in various situation which could lead to data loss etc.

For me it would make sense in a case where this problem affects a significant amount of users. But this is the first complaint for this I've seen ...

BTW, what specs / hardware do you have with these issues?

**Comment by kingcobra2468** [comment]
Hey,
Thanks for responding. Makes sense based on the potential issues you mentioned and given the fact that it seems to work fine for most users. 

For hardware, these issues generally appear on two laptops one with a Celeron 3205U cpu and 4gb ram and other with another with a i5-3320qm cpu and 8gb ram.

**Comment by XXXJetfireXXX** [comment]
I'd also add that Trilluim is meant to be used with lots of small/medium sized notes instead of a few huge ones...
Though, I've been using it for a year now and haven't encountered such problem even with notes that are pretty large (if 227KiB is large that is).
