### ISSUE TITLE
404 for /api/notes/XXX/backlink-count

### ISSUE THREAD

**Issue by adamcodemaker** [zadam/trilium#3339]
### Trilium Version

0.56.2

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

ubuntu

### Description

![image](https://user-images.githubusercontent.com/25587877/203164588-566f65c2-b23a-4e9f-9cd1-b1cf97efe615.png)

![image](https://user-images.githubusercontent.com/25587877/203165073-ff77f3bf-b7cd-41c9-8e09-c57149133b12.png)

When I downgraded to 0.55.1 there is no problem.

![image](https://user-images.githubusercontent.com/25587877/203165494-42301f96-1ec6-4c8f-b275-750034dd2de0.png)

**Comment by zadam** [comment]
Hello, this is a cache problem, try to force cache refresh with ctrl-f5 or similar.

**Comment by adamcodemaker** [comment]
I cleared the cache
Problem solved
