### ISSUE TITLE
(Bug report) Graphic error

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#3354]
### Trilium Version

0.56.2

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

[Fedora 37] - Linux computer 6.0.9-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 16 17:36:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Description

When starting the Trilium application (via FlatHub; Browser version is running fine), it looks like this:

![image](https://user-images.githubusercontent.com/50424412/204145349-5e7b4d6c-4abb-4741-afc2-0de562da9033.png)

(top was cropped because a share url can be seen, but it looks pretty much the same way)

**Comment by zadam** [comment]
Looks like GPU driver issue? There's a way to disable GPU acceleration with `--disable-gpu` flag, but I don't know if this is passed/supported by flatpak.

**Comment by Myzel394** [comment]
@zadam Yes that worked! I'll probably have to reinstall the GPU drivers, don't I?

This is the command I used:
```
flatpak run com.github.zadam.trilium --disable-gpu
```
