### ISSUE TITLE
(Feature request) Dark mode preservation for shared notes

### ISSUE THREAD

**Issue by dasrocky** [zadam/trilium#3360]
### Describe feature

Hello,
I recently started using shared web notes option from trilium notes and noticed that it doesn't preserve the theme from notes or have an option to show the shared notes in dark mode, which in my opinion looks much better. The web shared notes actually looks ugly when view with white background and I believe just by changing the background to material dark might look better.

Thanks for creating trilium notes, till now one of the best I have tried out there.

### Additional Information

By default, the web shared notes are white background.
![image](https://user-images.githubusercontent.com/61043834/204488307-43f060a7-de9e-4e10-b2e6-ff5101bc90e8.png)
Now this with black color(not actually dark mode)(not a web developer 😅)(changed body bgcolor, font color and url link color)
![image](https://user-images.githubusercontent.com/61043834/204488540-634fca61-7209-447e-bba2-51fc59dd2b74.png)

It can be improved further with better dark mode implementation. Another possibilities could be if the person sharing the note has dark mode theme selected it stay as it is when shared and on top of that shared notes can have button on top left to switch themes. 

Importance of the feature: 
- Consistency of user experience between Trilium notes app and shared notes(the notes was created in dark theme and user might add pics or other visual materials that fits the theme while sharing, and if the theme changes it completely looks bad)
- Dark theme in the above pic looks much better than white background theme when shared.(personal opinion)

I hope I was able to convey the message in understandable form.

**Comment by zadam** [comment]
Hi, it's possible to attach your custom CSS to the shared notes: https://github.com/zadam/trilium/wiki/Sharing#styling-the-shared-notes

My initial goal was to have the shared notes very minimalistic. But I agree that the default could look nicer and have some vague plans to improve that.
