### ISSUE TITLE
(Bug report) cursor jump to head of note when 2 same notes opened

### ISSUE THREAD

**Issue by fooyoo** [zadam/trilium#3365]
### Trilium Version

0.57-beta1

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 19044.2130

### Description

When 2 same note opened in tab, cursor will jump to the head during edit one of them.

![cursor_jump_to_top_when_same_note_open](https://user-images.githubusercontent.com/36770100/205009999-f5e12b40-2357-426f-a410-3f36daded438.gif)

**Comment by zadam** [comment]
Thanks for reporting, fixed.
