### ISSUE TITLE
[Question] Is it possible to order promoted attributes?

### ISSUE THREAD

**Issue by wunter8** [zadam/trilium#3368]
I have two attributes: clientNumber and matterNumber.

clientNumber is an "inherited attribute/label".
matterNumber is an "owned attribute".

I would like clientNumber to appear first in the "Promoted attributes" tab.
Is it possible to specify an ordering of the promoted attributes?

![image](https://user-images.githubusercontent.com/8421688/205174307-8709ed36-f3e3-4594-a61b-d7aaf92b176b.png)

**Comment by zadam** [comment]
Hi, promoted attributes keep the order in which they are specified in the "owned attributes". But it's not possible to specify the relative order between owned and inherited attributes.

**Comment by wunter8** [comment]
Bummer. Alright, thanks for the quick response!
