### ISSUE TITLE
(Bug report) /assets/v0.57.2/app-dist/desktop.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by wangxinpier** [zadam/trilium#3369]
### Trilium Version

0.57.2

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

synology nas

### Description

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/1505835/205194211-b2fe0765-ca82-4a91-bf47-72ff6d99ab6d.png">
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1505835/205194281-2a1db031-3939-4686-9982-8e593fd65b9e.png">
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/1505835/205194316-0ca5175d-fe44-46f7-8719-d5de13b3dec8.png">

**Comment by yanickxia** [comment]
the same problem ……

**Comment by derbirch** [comment]
same here, the macOS client works and can trigger a sync, but can not access it from the browsers
<img width="1159" alt="Screenshot 2022-12-02 at 11 35 17" src="https://user-images.githubusercontent.com/33411000/205209484-abe37b52-9433-479d-8002-b2ffb1379794.png">

**Comment by zhang-stephen** [comment]
same here... could it be resolved with rolling back to 0.56.2?

**Comment by yanickxia** [comment]
@zhang-stephen  rollback to 0.56.2, everything is OK

**Comment by derbirch** [comment]
> @zhang-stephen rollback to 0.56.2, everything is OK

Rolled back too and it worked like a charm XD

**Comment by st3iny** [comment]
It seems that bundled app code is missing entirely from the container:

```sh
11:04:19 [~/Code/trilium] git:(v0.57.2):dirty
richard@arch 130 $ docker run --rm -ti --entrypoint=sh zadam/trilium:0.57.2
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
/usr/src/app # ls -l src
total 20
-rw-r--r--    1 root     root           616 Dec  1 21:56 anonymize.js
-rw-r--r--    1 root     root          5007 Dec  1 21:56 app.js
drwxr-xr-x    1 root     root           162 Dec  1 21:57 becca
drwxr-xr-x    1 root     root           256 Dec  1 21:57 etapi
drwxr-xr-x    1 root     root            98 Dec  1 21:57 public
drwxr-xr-x    1 root     root           112 Dec  1 21:57 routes
drwxr-xr-x    1 root     root          1724 Dec  1 21:57 services
drwxr-xr-x    1 root     root           134 Dec  1 21:57 share
drwxr-xr-x    1 root     root            40 Dec  1 21:57 tools
drwxr-xr-x    1 root     root           120 Dec  1 21:57 views
-rw-r--r--    1 root     root          4976 Dec  1 21:56 www
/usr/src/app #
```
