### ISSUE TITLE
"Today" button produces an invalid date

### ISSUE THREAD

**Issue by d5ve** [zadam/trilium#337]
I added a note called "Diary", and and gave it a "Label" attribute named "calendarRoot".

When I clicked on the "Today" button in the top of the Trilium window, three descendant notes were created: "2019" / "01 - January" / "14 - Tuesday"

2019-01-14 is a Monday, not a Tuesday.

My client machine is running Ubuntu 10.10, with v0.27.4 of Trilium. 
My sync server machine is running Ubuntu 16.04 with docker version zadam/trilium:0.27.3

Both machines have the correct date set, and both are using New Zealand Daylight Savings time (NZDT)

I'm not sure how to debug this further.

**Comment by zadam** [comment]
> 2019-01-14 is a Monday, not a Tuesday.

Wow, that's pretty funny error. I'll look into that. It might have something to do with timezones.

**Comment by d5ve** [comment]
Many thanks @zadam !
