### ISSUE TITLE
(Bug Report) Router not found for request /assets/v0.57.2/app-dist/setup.js

### ISSUE THREAD

**Issue by sp00ky** [zadam/trilium#3370]
### Trilium Version

Latest Docker Image

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Docker on Fedora 37 Server

### Description

Using docker and the latest docker-compose.yml.  Navigating to the app for the first time a blank screen loads.  The dev tools console gives a 404 for setup.js and navigating to setup.js gives me the following:

{"message":"Router not found for request /assets/v0.57.2/app-dist/setup.js"}

**Comment by cyrsis** [comment]
+1 in here

**Comment by aashish108** [comment]
Yeah me too, blank screen. Should not have upgraded lol.

**Comment by st3iny** [comment]
Seems to be a duplicate of https://github.com/zadam/trilium/issues/3369.

**Comment by sp00ky** [comment]
> Seems to be a duplicate of #3369.

Probably related.  However, I don't get the error referenced there.

**Comment by 5AMsan** [comment]
Same here

**Comment by yllekz** [comment]
Same. Phew thought I screwed something up
