### ISSUE TITLE
(Bug report) 0.57.2 Handhsake failed 

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#3372]
### Trilium Version

0.57.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11, Linux

### Description

Hi

I have been using trilium with my server for couple years, I did many updates and uprgades without any issues. Today I upgraded my windows client and the linux trilium server and now I cant sync. 

I am getting etting the error below. I cant imagine this being a setup issue with mine since it was working well until this point.

I can also login to the server ui usig a browser, so definetely the server and the server url works. My passwork works in the browser

![Be2QPdlI7r](https://user-images.githubusercontent.com/8519469/205209803-3fcc9869-150c-4d1d-a2cd-b296336b581a.png)

**Comment by gerroon** [comment]
Putting the direct Ip:Port in the client does not work either, so like I said I doubt that this is an issue with my setup.

**Comment by ztankoz** [comment]
Same with docker.
Fresh install -> blank page on browser but no errors in logs
Downgrade to 56.2 works fine

**Comment by DaveDavenport** [comment]
I get the following after updating:
```
Error: Router not found for request /assets/v0.57.2/app-dist/desktop.js

    at /usr/src/app/src/app.js:92:17

    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)

    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)

    at /usr/src/app/node_modules/express/lib/router/index.js:286:9

    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)

    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)

    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:91:12)

    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)

    at /usr/src/app/node_modules/express/lib/router/index.js:286:9

    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12) {

  status: 404

}
```

**Comment by IPPrem** [comment]
Indeed, for me as well, all 0.57 versions seem to fail (docker install), both while upgrading from 0.56-latest (or earlier) and on a completely fresh install. The symptom is always a blank (maybe hidden) webpage. The only error I've seen so far is in the web-developer log/console something about app-dist/desktop.js not being loaded due to a missing/wrong mime-type. 
This looks to be the source of many of the issues with 0.57
Since 0.56 works for me, I won't search any deeper than this.

**Comment by zandhaas** [comment]
> I get the following after updating:
> 
> ```
> Error: Router not found for request /assets/v0.57.2/app-dist/desktop.js
> 
>     at /usr/src/app/src/app.js:92:17
> 
>     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
> 
>     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
> 
>     at /usr/src/app/node_modules/express/lib/router/index.js:286:9
> 
>     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
> 
>     at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
> 
>     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:91:12)
> 
>     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
> 
>     at /usr/src/app/node_modules/express/lib/router/index.js:286:9
> 
>     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12) {
> 
>   status: 404
> 
> }
> ```

I get the same after the upgrade to 57.2
After reinstallation of 56.2 everything is OK again.

I'm running Trillium on Docker

**Comment by yllekz** [comment]
Getting this too. Can't load the Trilium web UI. Rest of the container seems to work

**Comment by zadam** [comment]
Hi, this is strange. There was no change in sync / authentication in 0.57.X. Is there perhaps some error in the backend log?

(I've hidden a couple of comments since they relate to a different problem.)

**Comment by gerroon** [comment]
Maybe this?

```
POST /api/login/sync returned 401 with response {"message":"Auth request time is out of sync, please check that both client and server have correct time."}
401 POST /api/login/sync with 107 bytes took 1ms
```

**Comment by zadam** [comment]
> Both the client and the server are on the same time zone and date tiem with 5 mins difference.

Well, the leeway is exactly 5 minutes. So 5min 1sec will produce this error. I would recommend trying to sync them.

**Comment by gerroon** [comment]
Thanks, that works
