### ISSUE TITLE
Local variables are preserved through different runs of a backend script

### ISSUE THREAD

**Issue by ifsmirnov** [zadam/trilium#3379]
### Trilium Version

0.57.3

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu 20.04

### Description

TL;DR: consequent runs of backend scripts inherit local variables defined in previous backend runs. This can lead to different outcomes of script execution at local and server backends.

---

I create a backend script at the local installation. Let it be triggered by, e.g., runOnChildNoteCreationEvent.

```
foo = 12345
...
api.log(foo)
...
```

I run a script a few times and remove `foo` declaration, forgetting to remove logging:

```
...
api.log(foo)
...
```

Surprisingly, the line `api.log(foo)` still executes correctly and prints the old value of `foo`. Perhaps that is because I didn't use `let` or `var`, but I'm not very fluent in JS to tell.

However, if I run the same script on a different backend (e.g. via a server web interface), it predictably fails since `foo` is not defined. It is especially annoying since a script triggered by an event has no visible indication of failure.

It seems to me that each backend script execution should be done in its own sandbox and have no side-effects on future runs.

**Comment by zadam** [comment]
Hi,

> Surprisingly, the line api.log(foo) still executes correctly and prints the old value of foo. Perhaps that is because I didn't use let or var, but I'm not very fluent in JS to tell.

Yes, that's my assumption as well - in legacy JavaScript, you can assign an undeclared variable, in that case it's defined in a global scope. In modern JS, one should always use let/const.

> It seems to me that each backend script execution should be done in its own sandbox

JavaScript has no sandbox. The code runs in the "mother" process in backend/frontend. Which means it can crash the main process etc., but that's just the nature of the game.

**Comment by ifsmirnov** [comment]
After a bit of research I found that a variable declared without `var` or `let` belongs to the global scope indeed. Looks like a pitfall every JS developer should meet at least once. "use strict" at the global scope fixes the problem, but it will likely be a truly breaking change.

I believe the issue may be closed.
