### ISSUE TITLE
Keyboard shortcut to move line or list item up / down

### ISSUE THREAD

**Issue by DanMundy** [zadam/trilium#3396]
### Describe feature

For example in Sublime Text (and other text editors and outliner apps), it's really handy that I can press ⌘⌃↑ to move a line of text up, and ⌘⌃↓ to move it down. 

When I have a huge checklist of todos, for example, it makes the process of re-ordering everything really smooth - makes it function more like an outliner.

Hoping you can implement this in Trilium?

Thanks :)

--Dan

**Comment by zadam** [comment]
It would be a nice feature, but this would have to be implemented in CKEditor...

**Comment by DanMundy** [comment]
Ah I see, thanks for the super quick reply, and for making such an awesome thing as Trilium :) 

I really hope they do implement this feature, it's so handy in the other apps I use.
I've logged the request their GitHub;
https://github.com/ckeditor/ckeditor4/issues/5391
