### ISSUE TITLE
(Bug report) Reopen last tab doesn't work

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3397]
### Trilium Version

0.57.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Manjaro

### Description

`reopenLastTab` does not work.
Press `Ctrl+Shift+T`, the console shows error message:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ntxId')
    at C.reopenLastTabCommand (tab_manager.js:497)
    at C.callMethod (component.js:97)
    at A.triggerCommand (app_context.js:92)
    at keyboard_actions.js:42
    at HTMLDocument.<anonymous> (utils.js:144)
    at HTMLDocument.handleObj.handler (jquery.hotkeys.js:183)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.v.handle (jquery.min.js:2)
```

**Comment by zadam** [comment]
Hi, thanks for the report. Is it reproducible? Unfortunately all my attempts work.

**Comment by Nriver** [comment]
Yes, it's reproducible. I tested it with a fresh database.

![demo](https://user-images.githubusercontent.com/6752679/206602055-34cf0a32-943e-46a3-8909-942cf4a245b5.gif)

**Comment by zadam** [comment]
Thanks, can reproduce now - this happends when you close the last existing tab which has a special behavior. This isn't completely trivial to tackle, so will probably happen in the next feature release.

**Comment by zadam** [comment]
fix in next58 branch
