### ISSUE TITLE
(Bug report) Why does the BAT version need powershell

### ISSUE THREAD

**Issue by deajan** [zadam/trilium#3398]
### Trilium Version

0.57.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 21H2 x64

### Description

Hello,

Using trilium for a while now.
But on every release, I need to change `trilium-portable.bat` file since it will launch powershell which will fail with the following message:
```
C:\Users\User\Desktop\TRILIUM\trilium-windows-x64>trilium-portable.bat

C:\Users\User\Desktop\TRILIUM\trilium-windows-x64>SET DIR=C:\Users\User\Desktop\TRILIUM\trilium-windows-x64\

C:\Users\User\Desktop\TRILIUM\trilium-windows-x64>SET TRILIUM_DATA_DIR=C:\Users\User\Desktop\TRILIUM\trilium-windows-x64\\trilium-data

C:\Users\User\Desktop\TRILIUM\trilium-windows-x64>cd C:\Users\User\Desktop\TRILIUM\trilium-windows-x64\

C:\Users\User\Desktop\TRILIUM\trilium-windows-x64>WHERE powershell.exe
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

C:\Users\User\Desktop\TRILIUM\trilium-windows-x64>IF 0 NEQ 0 (start trilium.exe )  ELSE (powershell.exe ./trilium-portable.ps1 )
./trilium-portable.ps1 : Impossible de charger le fichier
C:\Users\User\Desktop\TRILIUM\trilium-windows-x64\trilium-portable.ps1, car l’exécution de scripts est désactivée
sur ce système. Pour plus d’informations, consultez about_Execution_Policies à l’adresse
https://go.microsoft.com/fwlink/?LinkID=135170.
Au caractère Ligne:1 : 1
+ ./trilium-portable.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Erreur de sécurité : (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

C:\Users\User\Desktop\TRILIUM\trilium-windows-x64>
```

My system configuration is vanilla for Powershell.
Indeed I could change execution policy, but why do we actually need powershell for launching Trilium if it will fail on all vanilla setups ?
Why not keep it simple and let the .bat file use batch, and the .ps1 file use powershell ?

**Comment by zadam** [comment]
the reasoning is in the PR: https://github.com/zadam/trilium/pull/2561

Something with .bat not supporting non-ASCII paths. But I'm open to reverting back to pure .bats, PRs are welcome ;-)

**Comment by deajan** [comment]
@zadam Thanks for the insight.
I've made a PR with a hopefully elegant solution.
