### ISSUE TITLE
(Feature request) Add a default page of shared notes in https://<my-trilium-deployment>/share

### ISSUE THREAD

**Issue by zhang-stephen** [zadam/trilium#3401]
### Describe feature

As title said, there is nothing except a 404 when try to access https://<my-trilium-deployment>/share. Is it possible that add a default page, e.g. lists of shared notes?
I think it's more convenient if shared some documents to others.

**Comment by sigaloid** [comment]
You can do this with the `share-root` attribute: https://github.com/zadam/trilium/wiki/Sharing#sharing-a-note-as-the-root

**Comment by zhang-stephen** [comment]
> You can do this with the `shareRoot` attribute: https://github.com/zadam/trilium/wiki/Sharing#sharing-a-note-as-the-root

I will have a try. Thank you.
