### ISSUE TITLE
(Bug report) Router not found for request /assets/v0.57.4/app-dist/share.js

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#3409]
### Trilium Version

0.57.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora 37

### Description

Sharing notes (specifically in this example, an excalidraw canvas note) does not work on v0.57.4 because of this 404.

**Comment by DynamoFox** [comment]
Mhm, I think I understand the issue... But I have no idea why it worked in the first place with v0.57.3.
Also note that this should only affect only the Docker build.
