### ISSUE TITLE
(Bug report) Context next to tile is limited length leading to longer vertical titles

### ISSUE THREAD

**Issue by CallumBaston** [zadam/trilium#3412]
### Trilium Version

0.57.4

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Arch - Latest

### Description

When adding headings into a note, any note. The bar to the left of the heading seems to be of a limited width, leading to the hash taking up more lines than is expected causing the title to take up more vertical space (image below). This is the case on a 1080p screen, it does not seem to be effected by zoom or scaling, or which theme I select. Reloading doesn't change anything it seems my instance is stuck like this.

![latest-screenshot](https://user-images.githubusercontent.com/45321070/207285932-ddd8f568-db10-410e-b235-be602f4810b9.png)

**Comment by zadam** [comment]
Hello, do you have some custom theme or styling? Headings look quite different for me:

![image](https://user-images.githubusercontent.com/617641/207451438-d748e06d-1240-4f72-805d-d57269b9a603.png)

**Comment by CallumBaston** [comment]
> Hello, do you have some custom theme or styling? Headings look quite different for me:
Hello, sorry for such a late reply. If I set my theme to the defaults the issue still persists. My usual theme is a slightly modified version of dark-plus https://pastebin.com/ipMX2LPB

**Comment by zadam** [comment]
That is strange. It must be some custom CSS applied since I haven't seen anything like that before ...

**Comment by CallumBaston** [comment]
I've tested something I should have at the start. Deleting my version of dark-plus solves the issue. I'll go through the CSS and try to identify what the issue is.
