### ISSUE TITLE
Ability to hide notes as soon as they are labeled as archived

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3422]
### Trilium Version

0.56.2

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 version 2004 with Firefox 107.0

### Description

When you attach the `#archived` label to a note, the note doesn't disappear from the note tree until you do a F5 refresh (and vice versa). This is important as the api function `refreshTree()` is deprecated and there seems to be no way to let these archived notes disappear from the note tree immediately.

**Comment by zadam** [comment]
Fixed in master, notes should now disappear automatically.
