### ISSUE TITLE
(Bug report) Broken image in .enex file import

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3424]
### Trilium Version

0.57.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Manjaro

### Description

I have a .enex file exported from evernote. The image inside the note can not be imported into Trilium properly. The .enex file is valid as it can be imported into evernote and the image is shown correctly.

I've send you the .enex file through E-mail. Please have a look.

**Comment by zadam** [comment]
Hi, thanks for the bug report. The image was mangled because the SAX library was splitting it into multiple "chunks" during parsing (why is actually undocumented behavior I haven't seen before).
