### ISSUE TITLE
(Feature request) Display Name for promoted attributes

### ISSUE THREAD

**Issue by TheOneValen** [zadam/trilium#3438]
### Describe feature

Hi!

Thanks for this really great tool!

I have a suggestion which might further increase the usabillity.

I would like to be able to be able to make "nice" display names for promoted attributes. Meaning that instead of the variable name (mostly camelCase and without spaces for example) an optional displayname (nice name, maybe with spaces) can be shown.

e.g.

`#label:computerRam="promoted,single,number,displayName=RAM Speicher,precision=0" `

**Comment by zadam** [comment]
Hi, I will close this in favor of already existing #3329
