### ISSUE TITLE
Can't import Evernote

### ISSUE THREAD

**Issue by jsaaby** [zadam/trilium#344]
Hi.

Tried to import an ENEX file. Seemed like nothing happened at first. Then I just got an error message saying it couldn't import.

When I tried to recreate that just now, Trilium just didn't do anything. But I couldn't go into Options. I exited without problems. But nothing was imported.

Relatively small ENEX file. Just a couple of folders I use for test importing.

**Comment by zadam** [comment]
Hello, thank you for the report! Could you please submit the content of trilium-data/log/*.log files here? Where this trilium-data directory is depends on the platform:

* /home/[user]/.local/share for Linux
* C:\Users\[user]\AppData\Roaming for Windows Vista and up
* /Users/[user]/Library/Application Support for Mac OS

Also I'm not sure I understand - you say the app doesn't work at all now after the failed import? Is that correct?

**Comment by jsaaby** [comment]
Sure. Here you go. This was done using one folder, containing 32 notes which are clips from various sites. A bit much with a 32Mb logfile for that ;)

[trilium-2019-01-15.zip](https://github.com/zadam/trilium/files/2759694/trilium-2019-01-15.zip)

I can use the app. It takes a little while for it to start (like 15-20 seconds, and I'm not on a particularly slow pc, it's a 1 year old Lenovo X1 Carbon).

But, when I try to import, if I click the options button afterwards, Trilium just freezes. The Option button has a blue box around it, and then nothing more happens. I have to close it, then open it.

**Comment by zadam** [comment]
@jsaaby thank you! I deleted the link since the log actually leaked some of your document data (that's why it was so large). I will fix that issue.

Otherwise it looks like something is wrong from the performance perspective because all the DB queries are taking very long (they are at least ten times slower than they should be). And they aren't even complex queries. I'll investigate further.

**Comment by jsaaby** [comment]
It's ok regarding the document data, but thanks anyway :) I specifically exported that folder because the contents were not sensistive in any way ;)

**Comment by jsaaby** [comment]
Tried starting Trilium just now. Just over 6 seconds. I find that fine. That was just after startup, so nothing else was really running by then.

There may have been something impacting performance yesterday, I think, without me having been aware of it.

Let's park that part here, and I'll write again if things get slow :)
