### ISSUE TITLE
(Feature request) Add Shortcuts to New Tab page

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#3444]
### Describe feature

Currently a new tab has a lot of unused screen real-estate. It seems like there might be some opportunity to use that space to improve user productivity. The searchbar really does most of the suggestions below, but having a visual button to click may help new users.
![image](https://user-images.githubusercontent.com/10717998/208719759-46d04b58-17e9-4585-bec6-e96ea2c838fe.png)

I think it would be nice to add some "Cards" or shortcuts to the blank area. Some might be to show:
- Recently edited notes
- Note Notes (Blank note, calendar note, template note, protected note)
- Trilium tip for new users

![image](https://user-images.githubusercontent.com/10717998/208723685-b684dec4-0383-4c96-8193-2c0674f8e711.png)

**Comment by zadam** [comment]
Actually, that space is used for the shortcut list of [workspaces](https://github.com/zadam/trilium/wiki/Workspace).

**Comment by meichthys** [comment]
Ok, Nice! I'll have to start using workspaces!
