### ISSUE TITLE
(Bug report) Note order is not updated after cutting & pasting

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3453]
### Trilium Version

0.57.2

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 version 2004 with Firefox 107.0

### Description

Steps:

1. Create a note A and attach a label `#sorted` to it.
2. Create a note B with title "new note 1"
3. Create a note C with title "new note 2"
4. Cut & paste note C into A
5. Cut & paste note B into A

Expected: note B is listed before note C since B's title is smaller than C's by string comparison

Actual: note C is listed before note B

**Comment by WPum** [comment]
Update:

`api.toggleNoteInParent()` seems not to trigger subnote reorder as well.

**Comment by zadam** [comment]
Hi, thanks for reporting. The intention is that this should work automatically (which it didn't) and one should not have to trigger some resorting manually.
