### ISSUE TITLE
(Bug report) Right click launchbar does not suppress browser context menu

### ISSUE THREAD

**Issue by hulmgulm** [zadam/trilium#3454]
### Trilium Version

0.58.0-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit), Windows 11 22H2

### Description

Right click launchbar does not suppress browser context menu. First the "Configure Launchbar" context menu is opened, but then the browser context menu hides it completely. Clicking somewhere else will close both which the exception of clicking on a scroll bar, which will only close the browser context menu.

**Comment by zadam** [comment]
Thanks for the bug report, fixed.
