### ISSUE TITLE
(Bug report) Resources missing in 0.58.0-beta docker image

### ISSUE THREAD

**Issue by hulmgulm** [zadam/trilium#3455]
### Trilium Version

0.58.0-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit), Windows 11 22H2

### Description

The following resources are not found by the server:
![image](https://user-images.githubusercontent.com/12165268/209461270-0a0d4f65-4695-498f-99cb-26d5ea809a7a.png)
![image](https://user-images.githubusercontent.com/12165268/209461280-267be43b-c41d-4d47-ad21-839f6a85fe30.png)

Opening the URLs directly in the browser result in:
{"message":"Router not found for request /assets/v0.58.0-beta/app/doc_notes/launchbar_note_launcher.html"}

**Comment by zadam** [comment]
Thanks for reporting, fixed.
