### ISSUE TITLE
(Feature request) Customize Calendar Tree

### ISSUE THREAD

**Issue by AllanZyne** [zadam/trilium#3461]
### Describe feature

Can Trilium provide a way to customize the note tree of calendar notes?

For example, when I set `calendarTreeTemplate="WW{weekNumber}/{isoDate}"` at `#calendarRoot`, and assume today is 2022-12-27, then my daily note will be created at "#calendarRoot/WW53/2022-12-27".

**Comment by zadam** [comment]
Hello, there is some limited customization of the leaf date notes: https://github.com/zadam/trilium/wiki/Day-notes#date-pattern

**Comment by AllanZyne** [comment]
Hi, zadam.
I'd like to implement this feature by myself. 
After investigation, I find Trilium has provided getYearNote/getMonthNote/getWeekNote apis, if I add `#calendarTreeTemplate` attribute, these apis will fallback to call getDayNote. 
But this is not an ideal solution.
For example, if I use "WW{weekNumber}/{isoDate}" pattern, I prefer that getWeekNote will return "WW{weekNumber}" note.
Maybe `calendarTreeTemplate` should also provide a label, like "WW{weekNumber}:week/{isoDate}:day"?

Would you like to give some suggestions on this feature?
Thank you very much!
