### ISSUE TITLE
The picture is incorrect sequence in the notes

### ISSUE THREAD

**Issue by FordringWang** [zadam/trilium#3468]
### Trilium Version

0.57.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

win10 1909

### Description

Dear Team,
Trilium Notes is so great, I'm going to migrate all of my evernote to Trilium Notes.
When I import Evernote file, I found picture is not in correct sequence in the notes.
For example, my evernote's picture is on the first line, but when I import to Trilium Notes I found picture In the last line, could you help me? Wish you happy New Year~

Kind Regards,
Fordring

**Comment by zadam** [comment]
Hello, would you be willing to provide a (minimal) ENEX import which demonstrates this issue? If yes, please send it to zadam.apps@gmail.com

**Comment by Nriver** [comment]
@zadam It‘s may be realated that the sample I sent to you in https://github.com/zadam/trilium/issues/3424 have a similar issue. The image is in the middle of the note in Evernote. After the import to Trilium, the image is placed at the end of the note.

**Comment by zadam** [comment]
@Nriver thanks, I was able to reproduce the issue with your file. Fixed.
