### ISSUE TITLE
Add multi-user collaboration

### ISSUE THREAD

**Issue by elimisteve** [zadam/trilium#347]
I think Trilium could be pretty revolutionary for many use cases if multiple people could edit notes at once.

It sounds like @zadam is probably not interested in adding this, but: how hard would this be for someone else to add?

**Comment by blyamur** [comment]
Great idea. I would even be satisfied with just a portable version or a variant with the placement of data in a shared folder with the possibility of simultaneous operation of the program from different places.

**Comment by zadam** [comment]
Making Trilium portable is quite easy - you just need to run it with `TRILIUM_DATA_DIR` environment variable set to the portable location (e.g. in your flash drive), e.g.:

```shell
export TRILIUM_DATA_DIR=/media/usb-drive/trilium-data

./trilium
```

**Comment by blyamur** [comment]
> Сделать trilium portable довольно просто-вам просто нужно запустить его с `TRILIUM_DATA_DIR`переменной окружающей среды, установленной в портативном месте (например, в вашем флэш-накопителе), например:
> 
> ```shell
> экспорт TRILIUM_DATA_DIR= / media / usb-drive / trilium-data
> 
> ./ trilium
> ```
Is it in the properties of the label or in the config is written?
For example, ideally store data in the same folder as the application itself. Then taking notes I can just transfer them one time.

**Comment by zadam** [comment]
> Is it in the properties of the label or in the config is written?

This is not in any config - it's the command you would use to set the environment variable (in unix os) and then running the Trilium itself. You could put it in a shell script for example.

> For example, ideally store data in the same folder as the application itself. Then taking notes I can just transfer them one time.

By default we use platform specific conventions where the data files should be. But you can override this with the env. variable mentioned above to be stored in the trilium application directory if you want.

**Comment by zadam** [comment]
Closing as this is not considered in-scope for Trilium. Some explanation here: https://github.com/zadam/trilium/wiki/FAQ#multi-user-support
