### ISSUE TITLE
(Feature request) Marking Code Language with Icons

### ISSUE THREAD

**Issue by renaldo-chen** [zadam/trilium#3475]
### Describe feature

I'm trying to mark my code language with icons.
I found that though there are icons marking code in [https://boxicons.com/](url), I can't simply use them by adding attributes like. `#iconClass="bx bx-python"` 
I'm wondering if I've got something wrong, or some enhancement can be made in this place.
By the way, trilium notes is quite great, thank you for your efforts.

**Comment by renaldo-chen** [comment]
I realize that I don't need to add attributes to change icon, all it takes is a simple click.

**Comment by zadam** [comment]
I was curious why the adding attribute didn't work (since it should), the problem was that the icon is `#iconClass="bx bxl-python"`.

**Comment by renaldo-chen** [comment]
Yes, after I replaced the code icon by clicking on it, I went back and checked the attribute and found out that it should be `#iconClass="bx bxl-python"`.
Then I checked your source code and found the paragraph about logo handling, and it all makes sense.
