### ISSUE TITLE
Mac version copies and pastes everything in clipboard (0.28.0)

### ISSUE THREAD

**Issue by HDLOfficial** [zadam/trilium#348]
Hello there! I am having an issue with the 0.28.0 version for Mac users.
I have installed this looking to log onto my server on my Windows computer (which works fine) but then every time I type any key on my Mac when in a text box (on the login screen), it just pastes everything in my keyboard. This applies to every key, Caps Locks, Cmd, etc.
Is there a way to easily fix this or would it just be best to go to the last stable version?
Thank you so much!

**Comment by zadam** [comment]
Thank you for the report. Fix will be released in the next beta soon.
