### ISSUE TITLE
(Bug report) Notes not editable after script execution

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3483]
### Trilium Version

v0.58.2-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Window 10

### Description

1. Create a JS frontend note with the following content.
```
alert("111");
```

execute it, and close the popup window.

2. None of the notes is editable now.

It may have something todo with the focus. As I hit `alt+tab` twice, the note will go back to normal.

The issue only occurs in client, the browser is fine.

**Comment by zadam** [comment]
Hi, IIRC this is an electron bug, e.g. described here: https://github.com/electron/electron/issues/19977

The workaround is to not use alert(), confirm(), prompt().

**Comment by Nriver** [comment]
In that case, we should change the code example for script launcher.

**Comment by zadam** [comment]
True, fixed.

**Comment by Nriver** [comment]
Close as fixed.
