### ISSUE TITLE
(Bug report) Evernote import mangles creation date

### ISSUE THREAD

**Issue by avidrissman** [zadam/trilium#3496]
### Trilium Version

0.57.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

macOS Ventura 13.1 (22C65)

### Description

Evernote import of .enex files written by the Mac version of Evernote Legacy mangles the creation date.

[sample2.enex.zip](https://github.com/zadam/trilium/files/10367633/sample2.enex.zip)

^ this sample was created, as noted in the `enex`:

```
<created>2013-04-14T16:19:00.000Z</created>
```

Upon import, Trilium says:

> Created:	2013--0-4- 4T:16

It seems like Trilium is pattern matching against a pattern that is not used by the Mac version of Evernote Legacy.

**Comment by avidrissman** [comment]
https://github.com/zadam/trilium/blob/4f771cfa7afcec2bae560eba8f4fa5f5492dcfa6/src/services/import/enex.js#L14

The easiest fix would probably be to have `parseDate` do a quick check to see if the date is already in ISO format before inserting the characters. (A quick `if (text.includes("-")) return text;` might honestly be good enough.)

**Comment by zadam** [comment]
Thanks for the report, fixed. I've added the ENEX import to my test files.
