### ISSUE TITLE
(Bug report) link title is not updated in note previews

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3499]
### Trilium Version

0.57.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 version 2004

### Description

Create three notes A, B and C.

In note A, insert an internal link `@B`.

In note B, insert an internal link `@C`.

Rename note C to D. In note A, hover the mouse on the internal link `@B`, the preview of note B displays 'C' instead of 'D'.

**Comment by zadam** [comment]
Thanks for reporting, fixed.
