### ISSUE TITLE
Attribute search broken for certain chars

### ISSUE THREAD

**Issue by mahdi1234** [zadam/trilium#35]
Attribute search probably doesn't escape well - none of below works when used in search

@attrib=999,1
@attrib=-999.1
@ghi=fdsf.,dsfsd
@def=r3,.gds
@sde=#$%##$%
@sde=abc\n

v 0.5.5

**Comment by zadam** [comment]
Unquoted attribute search works only for alphanumeric characters plus underscore and minus (this might be relaxed in the future).

Following should work: @attrib="999,1"

**Comment by mahdi1234** [comment]
Ok, please also note trying @sde="abc\n" makes app complete freeze.

**Comment by zadam** [comment]
Fixed the freezing for @sde="abc\n"
