### ISSUE TITLE
(Bug report) Evernote import places images and attachments at end

### ISSUE THREAD

**Issue by avidrissman** [zadam/trilium#3503]
### Trilium Version

0.57.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Docker, on a Synology

### Description

[Note Export.1.enex.zip](https://github.com/zadam/trilium/files/10369215/Note.Export.1.enex.zip)
^ was generated by Evernote Legacy

When imported, this does not place the images in their correct location.

I have my suspicions as to why. In `enex.js`:

https://github.com/zadam/trilium/blob/43c5163f6662e862c7b19b016869963b732dd207/src/services/import/enex.js#L272

the regex matches `en-media` elements in which the `hash` attribute comes first. However, in this `enex` file, there is:

```
<en-media type="image/png" hash="bebf29eaebe00ea01693b4763c3484f1"/>
```

In other `enex`es (that are private and that I can’t share) I see:

```
<en-media style="--en-naturalWidth:1125; --en-naturalHeight:501;" hash="60ff10477080d28c820209a3f681c045" type="image/png" />
<en-media style="width: 160px; height: 120px;" hash="e4581e956a062139aed4788cc4b90009" type="audio/x-m4a" title="Attachment"/>
```

You may need to expand the regex you use.

Thanks for being so responsive!

**Comment by zadam** [comment]
Thanks, fixed based on the sample import you provided.

**Comment by contributor** [comment]
All images are still at the bottom of the note.
Evernote:
![image](https://user-images.githubusercontent.com/598873/211343383-b00cdff8-79c4-4908-a22a-edee1c59dfde.png)
Trilium:
![image](https://user-images.githubusercontent.com/598873/211343546-9dca1b38-6c4d-4dc1-956f-e2d7287bf2a6.png)

In my case source of trilium note is the same either before and after https://github.com/zadam/trilium/commit/f7387872020a6e56a80152b0cd93e6e2ee3c1755

```
<div>First line, first image follows</div>
<div></div>
<div>Second line, first image follows</div>
<div>
  <br>
</div>
<div></div>
<div>
  <br>
</div>
<img src="api/images/zQI3GBFdTIzx/Image.png">
<img src="api/images/WMRVotHpWxwY/image.png">
```

**Comment by contributor** [comment]
Test enex file with the note above: 
[EnexImages.enex.zip](https://github.com/zadam/trilium/files/10374400/EnexImages.enex.zip)

**Comment by zadam** [comment]
There was another fix for this a couple of days ago. You need to use master branch.

```html
<div>First line, first image follows</div>
<div>
  <img src="api/images/81sqKw2DqxyT/Image.png">
</div>
<div>Second line, first image follows</div>
<div>
  <br>
</div>
<div>
  <img src="api/images/PQePFzr2Wevb/image.png">
</div>
<div>
  <br>
</div>
```

**Comment by contributor** [comment]
Included https://github.com/zadam/trilium/commit/e40f1fd11adc016fe598f518e7e44a6f4d75e43f and now it works!

Thank you!
