### ISSUE TITLE
Table of Contents is stuck at months ago content, can't update?

### ISSUE THREAD

**Issue by LorenAmelang** [zadam/trilium#3505]
### Trilium Version

0.57.5

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 Pro 21H2

### Description

I have a note that began showing a table of contents many months and versions ago. Since then I have added content and headings within the text originally used for the TOC. The headings above the additions still show properly. The first heading in the added section, even if I add several, is now the target for the last TOC item, which still shows its old label. The heading that should be the target of that last TOC item is ignored, as are several after it. I can't seem to make it add new TOC items on any level. 

I've tried many changes of font, style, adding, deleting, previous or following text, and none of it matters. Seems I need a way to tell the TOC function to delete its memory of the old situation and start fresh...  

### Error logs

This is where today's effort to add content begins: 

(I don't see any clues, but...)

13:27:25.352 Slow query took 78ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:27:25.414 Content hash computation took 140ms
13:27:25.414 Content hash checks PASSED
13:27:25.414 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173227}
13:27:26.134 200 GET /api/tree?subTreeNoteId=6fucuZvdxO3K with 27962 bytes took 1ms
13:27:26.360 204 PUT /api/branches/K2C7KeW8cA9P/expanded/1 with 0 bytes took 2ms
13:27:29.396 200 GET /api/tree?subTreeNoteId=s6Yz4mV2UYYi with 11507 bytes took 1ms
13:27:29.611 204 PUT /api/branches/KB8Xro46M5sw/expanded/1 with 0 bytes took 3ms
13:27:39.677 200 GET /api/notes/Pa3rDXUaw35O with 86960 bytes took 5ms
13:27:39.678 200 GET /api/note-map/Pa3rDXUaw35O/backlink-count with 11 bytes took 1ms
13:27:39.721 204 PUT /api/options with 0 bytes took 2ms
13:27:39.731 200 POST /api/tree/load with 7220 bytes took 0ms
13:28:21.289 304 GET /api/clipper/handshake with 45 bytes took 1ms
13:28:24.484 Nothing to push
13:28:24.662 Finished pull
13:28:24.662 Nothing to push
13:28:25.434 Slow query took 70ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:28:25.477 Content hash computation took 113ms
13:28:25.477 Content hash checks PASSED
13:28:25.477 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173227}
13:29:21.293 304 GET /api/clipper/handshake with 45 bytes took 2ms
13:29:24.517 Nothing to push
13:29:24.702 Finished pull
13:29:24.702 Nothing to push
13:29:25.663 Slow query took 82ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:29:25.713 Content hash computation took 132ms
13:29:25.713 Content hash checks PASSED
13:29:25.713 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173227}
13:29:43.271 200 GET /api/notes/Pa3rDXUaw35O with 86960 bytes took 2ms
13:30:08.679 Slow 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 20ms
13:30:08.686 200 GET /api/notes/Pa3rDXUaw35O with 86973 bytes took 2ms
13:30:09.856 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 7ms
13:30:09.862 200 GET /api/notes/Pa3rDXUaw35O with 86986 bytes took 3ms
13:30:12.037 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 7ms
13:30:12.041 200 GET /api/notes/Pa3rDXUaw35O with 87019 bytes took 2ms
13:30:15.021 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 6ms
13:30:15.028 200 GET /api/notes/Pa3rDXUaw35O with 87088 bytes took 3ms
13:30:21.292 304 GET /api/clipper/handshake with 45 bytes took 1ms
13:30:25.329 Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":173227}
13:30:25.329 Sync kV2fkWcSjo: Pushing 3 sync changes in 826ms
13:30:25.330 Nothing to push
13:30:25.520 Finished pull
13:30:25.520 Nothing to push
13:30:26.473 Slow query took 217ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:30:26.522 Content hash computation took 266ms
13:30:26.522 Content hash checks PASSED
13:30:26.522 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173234}
13:31:04.806 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 5ms
13:31:04.814 200 GET /api/notes/Pa3rDXUaw35O with 88402 bytes took 2ms
13:31:17.003 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 6ms
13:31:17.009 200 GET /api/notes/Pa3rDXUaw35O with 87088 bytes took 1ms
13:31:21.279 304 GET /api/clipper/handshake with 45 bytes took 1ms
13:31:22.889 Slow query took 25ms: INSERT OR REPLACE INTO entity_changes(entityName, entityId, hash, isErased, utcDateChanged, isSynced, changeId, componentId, instanceId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
13:31:22.891 Slow 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 29ms
13:31:22.897 200 GET /api/notes/Pa3rDXUaw35O with 88124 bytes took 2ms
13:31:24.876 Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":173234}
13:31:24.876 Sync xMWK4QfY9x: Pushing 1 sync changes in 361ms
13:31:24.877 Nothing to push
13:31:25.059 Finished pull
13:31:25.060 Nothing to push
13:31:25.979 Slow query took 100ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:31:26.034 Content hash computation took 155ms
13:31:26.034 Content hash checks PASSED
13:31:26.034 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173237}
13:31:29.937 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 7ms
13:31:29.945 200 GET /api/notes/Pa3rDXUaw35O with 88125 bytes took 2ms
13:31:33.037 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 5ms
13:31:33.044 200 GET /api/notes/Pa3rDXUaw35O with 88131 bytes took 2ms
13:31:35.476 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 5ms
13:31:35.608 200 GET /api/notes/Pa3rDXUaw35O with 88127 bytes took 2ms
13:31:36.609 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 5ms
13:31:36.615 200 GET /api/notes/Pa3rDXUaw35O with 88130 bytes took 4ms
13:31:52.468 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 3ms
13:31:52.477 200 GET /api/notes/Pa3rDXUaw35O with 88137 bytes took 3ms
13:31:56.006 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 3ms
13:31:56.011 200 GET /api/notes/Pa3rDXUaw35O with 88130 bytes took 2ms
13:32:00.077 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 3ms
13:32:00.099 200 GET /api/notes/Pa3rDXUaw35O with 88134 bytes took 3ms
13:32:07.539 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 4ms
13:32:07.546 200 GET /api/notes/Pa3rDXUaw35O with 88162 bytes took 2ms
13:32:16.199 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 5ms
13:32:16.206 200 GET /api/notes/Pa3rDXUaw35O with 88158 bytes took 2ms
13:32:17.374 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 4ms
13:32:17.387 200 GET /api/notes/Pa3rDXUaw35O with 88154 bytes took 3ms
13:32:21.309 304 GET /api/clipper/handshake with 45 bytes took 5ms
13:32:23.556 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 3ms
13:32:23.564 200 GET /api/notes/Pa3rDXUaw35O with 88162 bytes took 4ms
13:32:24.862 Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":173237}
13:32:24.863 Sync 9JgH2QLn5s: Pushing 1 sync changes in 343ms
13:32:24.863 Nothing to push
13:32:25.039 Finished pull
13:32:25.039 Nothing to push
13:32:25.764 Slow query took 93ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:32:25.811 Content hash computation took 140ms
13:32:25.811 Content hash checks PASSED
13:32:25.811 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173248}
13:32:36.582 Slow 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 31ms
13:32:36.592 200 GET /api/notes/Pa3rDXUaw35O with 88127 bytes took 2ms
13:32:39.391 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 9ms
13:32:39.419 200 GET /api/notes/Pa3rDXUaw35O with 88134 bytes took 2ms
13:32:45.895 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 3ms
13:32:45.902 200 GET /api/notes/Pa3rDXUaw35O with 88138 bytes took 2ms
13:32:54.255 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 2ms
13:32:54.264 200 GET /api/notes/Pa3rDXUaw35O with 88139 bytes took 4ms
13:32:55.412 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 2ms
13:32:55.417 200 GET /api/notes/Pa3rDXUaw35O with 88140 bytes took 3ms
13:33:14.585 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 4ms
13:33:14.594 200 GET /api/notes/Pa3rDXUaw35O with 88141 bytes took 3ms
13:33:15.986 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 4ms
13:33:16.002 200 GET /api/notes/Pa3rDXUaw35O with 88142 bytes took 6ms
13:33:21.280 304 GET /api/clipper/handshake with 45 bytes took 0ms
13:33:24.874 Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":173248}
13:33:24.874 Sync PBSJASVdw8: Pushing 1 sync changes in 344ms
13:33:24.874 Nothing to push
13:33:25.087 Finished pull
13:33:25.087 Nothing to push
13:33:26.002 Slow query took 103ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:33:26.052 Content hash computation took 153ms
13:33:26.052 Content hash checks PASSED
13:33:26.052 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173255}
13:33:30.907 204 PUT /api/notes/Pa3rDXUaw35O/content with 0 bytes took 3ms
13:33:30.916 200 GET /api/notes/Pa3rDXUaw35O with 88146 bytes took 2ms
13:34:21.289 304 GET /api/clipper/handshake with 45 bytes took 1ms
13:34:24.863 Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":173255}
13:34:24.864 Sync gWNoyF4ifK: Pushing 1 sync changes in 343ms
13:34:24.864 Nothing to push
13:34:25.043 Finished pull
13:34:25.043 Nothing to push
13:34:25.834 Slow query took 73ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
13:34:25.880 Content hash computation took 119ms
13:34:25.880 Content hash checks PASSED
13:34:25.880 Sending message to all clients: {"type":"sync-finished","lastSyncedPush":173256}
13:35:21.284 304 GET /api/clipper/handshake with 45 bytes took 1ms
13:35:24.526 Nothing to push
13:35:24.703 Finished pull
13:35:24.703 Nothing to push

**Comment by zadam** [comment]
Hi,

>  Seems I need a way to tell the TOC function to delete its memory of the old situation and start fresh...

TOC has no memory and as such can't be reset. It just takes the note, parses it and produces TOC.

Unfortunately the parsing is done using regex which is not very suitable for HTML and in your case the HTML probably contains something (possibly got there via copy and paste) at which the parser gets stuck.

If your note is not too sensitive, you could send its export to zadam.apps@gmail.com and I think I should be able to debug this issue.

**Comment by LorenAmelang** [comment]
Note sent with eMail reply: 

Zadam,

Thanks for the quick reply! 

I peeked at the HTML for this exported note, and it looks like the sections copied from Wikipedia get indented deeper with each new quoted link. When the indent gets deep enough, TOC stops seeing the ##Headers. I totally don't understand why the indents grow...  

Attaching my DevTools view of one of the Wikipedia clippings, where there is no indent problem apparent. 

Guess I could use my PureText tool to strip the link content from things I copy and paste, but the links are handy! And this complex mess would be a hassle to undo now...  

(Sparing GitHub the messy details... )

**Comment by zadam** [comment]
should be fixed in 0.58.4, closing.
