### ISSUE TITLE
(Bug report) Wrong branch is selected after exiting hoist mode

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3506]
### Trilium Version

0.57.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 version 2004

### Description

Create a note structure like this:

```
A1
|-- B *
    |-- C
A2
|-- B * (clone of B)
    |-- C
```

1. select note B on the A2 branch
2. reload the application
3. hoist note B
4. select note C
5. unhoist note B

Expected: note C on the A2 branch should be selected

Actual: note C on the A1 branch is selected

https://user-images.githubusercontent.com/27683756/211455214-8866afd9-b99b-4691-b8a4-40eec5c7a6d1.mp4

**Comment by zadam** [comment]
Yes, that's because "note" is hoisted, not "note path". It's not perfect and produces this minor defect, but I'm not sure if it's worth addressing to be honest.
