### ISSUE TITLE
(Bug report) Bookmarks not working on 0.58.4

### ISSUE THREAD

**Issue by Lightirius** [zadam/trilium#3514]
### Trilium Version

0.58.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 Pro 21H2

### Description

After update to 0.58.4 from 0.57.5 notes with **BookmarkFolder** and **bookmarked** attributes are no longer displayed in the launchbar
I have **Bookmarks** launcher in the visible launchers sub-tree in new launchbar configuration

**Comment by zadam** [comment]
Hello, in 0.58 the bookmark implementation changed and it doesn't use `#bookmarked` label anymore. However, all such labels/bookmarks should have been migrated to the new (clone based) implementation.

Did this migration not work for you? Or do you perhaps assign the `#bookmarked` label manually or via script_

**Comment by Lightirius** [comment]
Migrations didn't work. I had a few notes with manually added `#BookmarkFolder` labels, but they are missing frome the launchbar after update.
Tested it again with portable Trilium and demo database - `#bookmarked` migrates fine, but `#BookmarkFolder` folders disappears from the launchbar after update.

Also, what is the new way to create bookmarks? New launcher is empty and wiki page about them is outdated
![image](https://user-images.githubusercontent.com/11685338/212121974-105f9453-9dfc-4e2d-b221-5784b50a892f.png)

**Comment by Lightirius** [comment]
Found the new `Bookmark` toggle on the basic properties

**Comment by Lightirius** [comment]
Found the problem - on the 0.57.5 `#bookmarkFolder` label was working fine without `#bookmarked` label.
It looks like migrations don't check that case

**Comment by zadam** [comment]
> Found the problem - on the 0.57.5 #bookmarkFolder label was working fine without #bookmarked label.

That's right - I did not realize it was possible to have a folder without the #bookmarked label. Migration has been fixed now. Sorry for the trouble.
