### ISSUE TITLE
(Bug report) Search (searchInSubtree) keyboard shortcut doesn't work from a note

### ISSUE THREAD

**Issue by contributor** [zadam/trilium#3515]
### Trilium Version

0.58.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Pro 19044.2364

### Description

Keyboard shortcut Ctrl+Shift+S only works when tree is focused. You cannot trigger searchInSubtree action when a note is focused. All other shortcuts (including simple search Ctrl+S) can be triggered from a note.

At least three last releases have this bug.

**Comment by zadam** [comment]
This is intentional - some shortcuts work only in some contexts. Search in subtree is note tree specific, it doesn't make much sense elsewhere. "Search" is on the othe hand a global action since it does not depend on the position on the tree state.

**Comment by contributor** [comment]
Shortcut to search quickly across notes content is a must for note taking app. It's is too much of hassle to press Ctrl+Shift+S, understand that nothing happens, than use mouse to focus tree and press shortcut again. Main usage scenario: I know that I have notes on topic X, but I don't remember (or don't want to waste time) for locating nodes in the tree. Most of the time I search from root.

Moreover, I would even vote for GLOBAL shortcut, so I can quickly search from ANY app (from the root)

**Comment by zadam** [comment]
> Shortcut to search quickly across notes content is a must for note taking app. It's is too much of hassle to press Ctrl+Shift+S, understand that nothing happens (you alt tabbed to trilium and not necessary know where the focus is), then use mouse to focus tree and press shortcut again.

But there's `CTRL+S` which works in the whole app and seems to do what you want.

> Moreover, I would even vote for GLOBAL shortcut, so I can quickly start search from ANY app (from the root node)

This is possible by adding a `global:` prefix, there's one in default config:

![image](https://user-images.githubusercontent.com/617641/212409413-1fe3b39b-65e4-410d-a5ef-e347469bdd31.png)

Global shortcuts need app restart to take effect.

**Comment by contributor** [comment]
Awesome, thank you! global: prefix did the trick! I assigned additional shortcut `global:Ctrl+Shift+F` for searchInSubtree, and it works the way I want both in Trilium and in other apps

As for `Ctrl+S` search - I didn't find any benefits comparing to `Ctrl+Shitf+S` (in root) in my 1.5 months Trilium evaluation:
- no highlight of found terms
- serch result dissapears when you open one of the found note

And `Ctrl+Shitf+S` now is perfect for me. The only thing I still miss is ability to expand all found notes - something like in Book Note in list mode.

**Comment by contributor** [comment]
Since it searchInSubtree works only from tree intentionally (and there is workarround to amend this) the issue can be closed.

Question: keyboard shortcuts are not synchronized across my cluster (web + 2 windows apps). Are there some tricks to make them sync?

**Comment by zadam** [comment]
> Question: keyboard shortcuts are not synchronized across my cluster (web + 2 windows apps). Are there some tricks to make them sync?

No, shortcuts are intentionally not synced, because they often have to differ between platforms (mac, windows ...)

**Comment by contributor** [comment]
Any unofficial ways? Should I setup SQL sync myself for `options WHERE name like 'keyboardShortcuts%'? What is the role of column 'isSynced'?

**Comment by contributor** [comment]
Will the following idea work? I maintain an (external) file with SQL update statements with all my options shortcuts, then I setup each instance of trilium with `backendStartup` that executes this file?

**Comment by zadam** [comment]
> Should I setup SQL sync myself for `options WHERE name like 'keyboardShortcuts%'? What is the role of column 'isSynced'?

That marks options which are synced as opposed to which aren't. You could try to set those keyboardShorcut ones to 1, it might work. But changes would be applied on the next restart.

> I maintain an (external) file with SQL update

Not sure why external file. Just SQL code note which is automatically synced seems easier.

> I setup backendStartup note on each instance of trilium with that executes this file?

That would work, yes. Although kinda annoying is the fact that the script will be executed after applying the shortcuts, so you'll need another reload/restart to see the changes.

**Comment by contributor** [comment]
Thanks, I will try all options. External file - to apply it in different instances too (different data dirs/dbs) on the same computer. Extra restart is acceptable, it is so much better than changing shortcuts manually and restarting anyway.
