### ISSUE TITLE
(Bug report) Cannot protect subtree if subtree has zero-byte note from web clipper

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#3523]
### Trilium Version

0.58.4

### What operating system are you using?

Other (specify below)

### What is your setup?

Local + server sync

### Operating System Version

Fedora 37

### Description

Occasionally the web clipper will clip a zero-byte image and I am unable to protect it, and since protection is recursive, I find myself unable to protect any subtree that contains one of these images. Not just a zero byte file will trigger it, it seems specific to ones the web clipper brings in. Maybe there's something particular about how it imports a zero byte file, not sure.	

### Error logs

`Error when calling PUT notes/[id]]/protect/1?subtree=1: error - Cannot set null content to note '[id2]'`

**Comment by zadam** [comment]
Thanks for reporting, fixed.
