### ISSUE TITLE
Custom Themes are gone?

### ISSUE THREAD

**Issue by memo-567** [zadam/trilium#3528]
### Trilium Version

v0.58.5 release

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint, Win 11 and Server version.

### Description

Custom themes that worked before the update no longer appear in the selection list. 

Neither on the server nor in the desktop version.

`Options -> Appearance`

Only Dark and Light are available.

**Comment by XXXJetfireXXX** [comment]
Hmm, custom themes shouldn't be gone, that's definitely a bug.
My custom theme works fine by itself, but it doesn't appear at the selection list. (Win10)
![image](https://user-images.githubusercontent.com/43646178/212528736-1781e062-3050-4d92-981c-ed92c57611bf.png)

**Comment by memo-567** [comment]
@XXXJetfireXXX 

Same behavior here.

**Comment by zadam** [comment]
Thanks for reporting, fixed.

**Comment by memo-567** [comment]
Fixed for the docker image too?

**Comment by zadam** [comment]
Yes, but it's not released yet, will be in 0.58.6.

**Comment by memo-567** [comment]
OK. Thank you for the hint.
