### ISSUE TITLE
(Bug report) Attribute bug

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#3529]
### Trilium Version

0.58.5

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

win11

### Description

I like this note software very much!
There are two issues after a recent update:
1. The attribute #appTheme doesn't work anymore, I can't see the theme I added in settings.
2. The attributes #inbox #clipperInbox #hoistedInbox in the old version will be automatically deleted when upgrading.

**Comment by zadam** [comment]
Hi, the first issue has just been fixed: https://github.com/zadam/trilium/issues/3528

Regarding the `hoistedInbox`, it was renamed to `workspaceInbox` and the migration should take care of it. There should be no change to `clipperInbox` AFAIK.
