### ISSUE TITLE
Custom Themes are not showing up in  0.58.5 Server

### ISSUE THREAD

**Issue by greengeek** [zadam/trilium#3530]
### Trilium Version

0.58.5

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Windows 10

### Description

I set up a 0.58.5 Trilium Server as a new install on Debian, not using docker.  I followed the official guide here, https://github.com/zadam/trilium/wiki/Packaged-server-installation, and used the second option, "Configure Trilium to auto-run on boot with systems"  I added my themes, yet they are not showing up in the Options menu.  I am only able to choose from the two default themes.  I have a previous 0.58.4 Trillium Server installed in docker on Debian and they are working there.

These are the steps that I have taken on both servers to install the themes:

- Create a new note in Trilium notes.
- Under the Basic Properties tab, set Note type to Code and choose the CSS option
- Under the next tab over, called Owned attributes, paste in the following: #appTheme=Obsidian
- In the body of the notes paste the contents of Obsidian.css
- Click on the Trilium icon at the top left of the page and choose Options
- Select Appearance and choose Obsidian in the drop down under Theme

I am trying to install the themes I build that are working on 0.58.4 that are found here https://github.com/greengeek 

I haven't been able to verify if this is an issue with switching to the newest version which appears to have changed how the options menu is displayed (now as its own page) or if this is an issue with installing Trilium directly on the server.

**Comment by greengeek** [comment]
I also noticed that the Steel Blue theme is not showing up as an option under Themes with the default install and demo content.

**Comment by SiriusXT** [comment]
it has just been fixed: #3528

**Comment by greengeek** [comment]
Awesome!  Closing this out as duplicate
