### ISSUE TITLE
(Bug report) content of included note of its child note cannot be seen properly

### ISSUE THREAD

**Issue by gingerkitti** [zadam/trilium#3533]
### Trilium Version

0.58.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 22H2

### Description

In the view of parent note, the content of  included note  of its child note cannot be seen properly
![image](https://user-images.githubusercontent.com/89347119/212734153-7731f6f9-a576-4cfe-96be-e87a43db2550.png)
![image](https://user-images.githubusercontent.com/89347119/212734250-c800d371-a88d-4f74-9dfe-58ba950e3b39.png)

### Error logs

Sorry that I am not an programmer and do not understand which logs you are needed, so I just copy the whole logs and printscreen. Hope it could provide any help

### Frontend logs
```
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.58.5/libraries/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.58.5/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.58.5/libraries/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/ckeditor/ckeditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.58.5/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

![image](https://user-images.githubusercontent.com/89347119/212595794-a12e66e1-a585-498a-9c29-edcd7821beb2.png)

**Comment by zadam** [comment]
Hi, this is not loaded intentionally. Included notes cause extra HTTP/DB requests and could be too much for the listing (imagine many notes each containing many included notes).

**Comment by XXXJetfireXXX** [comment]
> Hi, this is not loaded intentionally. Included notes cause extra HTTP/DB requests and could be too much for the listing (imagine many notes each containing many included notes).

Let alone resursion cases when two notes include each other x)

**Comment by gingerkitti** [comment]
OK, I get it. Thank you very much
