### ISSUE TITLE
(Bug report) Cannot change order of sidebar launchers if root has inheritable attribute "sorted"

### ISSUE THREAD

**Issue by SalvyTek** [zadam/trilium#3537]
### Trilium Version

0.58.6

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Linux *** 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Description

If root has the inheritable "sorted" attribute, it is not possible to change the order of sidebar launchers. By disabling attribute inheritance, it becomes possible to reorder the launchers at will.

Would it be possible to make the settings sub-tree ignore attributes inherited from the root?

P.S. Sorry for my English...

**Comment by zadam** [comment]
Hi, that's true, inheritance makes little sense here. I fixed this, it will be in 0.59.

**Comment by SalvyTek** [comment]
Thank you so much for fixing this problem so quickly and thank you for all the work you do to make Trilium an ever better tool!
