### ISSUE TITLE
Lazyman's Sync?

### ISSUE THREAD

**Issue by Abourass** [zadam/trilium#354]
Is there any reason I should **not** make a private repo for my trilium data folder as a lazyman's sync without having to set up a server? Since private repo are free now, I set this up to sync between work and home, seems to be working great; Am I going to cause issues in the long run?

**Comment by zadam** [comment]
This can work as long as you make sure you don't have any write conflicts. If you edit on both sides you won't be able to merge changes.

**Comment by Abourass** [comment]
Makes sense. Thank you!
