### ISSUE TITLE
The gray logo image in the upper left corner of the software is missing

### ISSUE THREAD

**Issue by sc8cn** [zadam/trilium#3545]
### Trilium Version

0.58.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

win10

### Description

The gray logo image in the upper left corner of the software is missing.
![trilium-logo](https://user-images.githubusercontent.com/26480118/213631133-657bf094-1218-4c41-be17-e8a429868d34.jpg)
![trilium-logo2](https://user-images.githubusercontent.com/26480118/213631147-31848608-096c-4a62-871d-daae8d8f95e0.jpg)

**Comment by sc8cn** [comment]
It is normal to completely reinstall the docker, if the original database is used to display the logo, there is a problem

**Comment by zadam** [comment]
You probably use a custom theme which needs to be updated to use a correct image path: https://github.com/zadam/trilium/wiki/Themes#asset-path

**Comment by sc8cn** [comment]
您好，来信已到达目的地，我的主人将择日阅读，谢谢！

**Comment by sc8cn** [comment]
> You probably use a custom theme which needs to be updated to use a correct image path: https://github.com/zadam/trilium/wiki/Themes#asset-path

Thank you! I tried to test it with version 0.56.2 of the database, and it is true that, as you said, it was caused by the wrong location of the image referenced by the chosen theme.
