### ISSUE TITLE
Impossible to remove clones?

### ISSUE THREAD

**Issue by Dwindle2234** [zadam/trilium#3548]
I have cloned a note (actually I just wanted to duplicate it but couldn't find this feature) - and now want to remove the clone. The delete note dialogue does have the option but I cannot remove the top tick (firefox nor chrome), hence both items are deleted....How can I deselected the top option?

In the attached I just want to remove the "Dec" note from the 2023 sub tree.

Thanks

![image](https://user-images.githubusercontent.com/120342689/213860810-e28a5076-027e-4492-a651-901f04b4ede1.png)
![image](https://user-images.githubusercontent.com/120342689/213860830-607a6b1c-cd19-4afc-b74b-d56f6ad923df.png)
![image](https://user-images.githubusercontent.com/120342689/213860839-8c257d90-4677-4bb8-9b55-4c77723a7fb4.png)

**Comment by zadam** [comment]
Hello, I assume you did this:

![image](https://user-images.githubusercontent.com/617641/213862481-37f2d6ff-a7d1-4210-a84a-89dde9daa678.png)

But this component doesn't "know" about the tree position - it doesn't know which clone to delete so allows deleting only the whole note.

To delete a particular clone, you need to delete it from the tree component - e.g. from the context menu:

![image](https://user-images.githubusercontent.com/617641/213862555-3f19e784-035f-45cf-958f-c55b2728ed0e.png)

(There you can also find the "Duplicate" action)

**Comment by Dwindle2234** [comment]
F.A.B.

Thank you
