### ISSUE TITLE
Won't sync with error 500

### ISSUE THREAD

**Issue by renyuneyun** [zadam/trilium#3550]
### Trilium Version

0.58.7

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Archlinux x86_64; Linux 6.0.18-1

### Description

I have the local + remote set up, with both 0.58.7 (updated recently).

It used to sync without issues, but now it raises error while syncthing:

```
Sync failed: Request to PUT https://MY_SERVER/api/sync/update?logMarkerId=XXX failed, error: 500
```

Actual ID masked with `XXX`; server is masked with `MY_SERVER`.

The sync test says success. I can also log-in to my remote server's trilium without issues.

I assume it is the backend log that should be provided? Please let me know if the `logMarkerId` is not sensitive so I can attach the full log which contains lots of them...

**Comment by zadam** [comment]
> I assume it is the backend log that should be provided? Please let me know if the logMarkerId is not sensitive so I can attach the full log which contains lots of them...

Yes please, ideally send the whole backend log to zadam.apps@gmail.com.

**Comment by renyuneyun** [comment]
Thanks. I have sent the email. Happy to continue the conversation anywhere

**Comment by renyuneyun** [comment]
I'm closing this issue for now because it seems to be fixed after a third restart of my Nginx deployment. No idea why that happened, nor why it is fixed.
