### ISSUE TITLE
(Feature request) Toggle switch for ToC?

### ISSUE THREAD

**Issue by leohougmail** [zadam/trilium#3555]
### Describe feature

I like the idea of auto ToC and the tag to disable it but I found myself removing and adding the tag very often since my screen/browser width is limited and I really need the ToC panel. Is it possible to add a toggle switch somewhere so I can turn it on/off easily? 

I knew there was a widget to have a small ToC below note tree, but for the same width  reason, I normally hides the tree. And that widget doesn't work well with some of my notes.

Thank you in advance

**Comment by zadam** [comment]
Hi, I added a button to temporarily hide the TOC. Will be in 0.59
