### ISSUE TITLE
Webhook to submit notes

### ISSUE THREAD

**Issue by christophersw** [zadam/trilium#356]
It would be awesome if the Trilium Server supported a simple Webhook mechanism for note submission. 

I would immediately leverage this to send notes to Trilium from Slack, from IFTTT, from JIRA, etc.

**Comment by zadam** [comment]
Hmm, Trilium actually does have API to do this, but it's currently not documented. It is used in [trilium-sender](https://github.com/zadam/trilium-sender) which is a simple Android app from which you can create notes and send pictures to Trilium.

**Comment by christophersw** [comment]
Looking at that code - I think the main change here is support for an "api key" or other token that would allow a robot to login.  (Otherwise Slack/IFTT/Other isn't going to be able to authenticate).

**Comment by zadam** [comment]
Yes - the flow in the android app is that first user needs to login using credentials using which the android app gets long lived token which is then used for authentication against the server installation.

But I guess for e.g. Slack it would make more sense to generate the token in Trilium and then manually set it in the slack plugin, right?

**Comment by christophersw** [comment]
I dug a little deeper into Slack and IFTTT - just as the two services that I can personally imagine using the most.... There are probably myriad other apps and integrations that could be imagined. 

Slack's integration is not as easy as I had hoped. Slack allows you to easily create "slash commands" that call a specific URL, but the format and content of the POST is fixed by Slack. [See this...](https://api.slack.com/slash-commands#app_command_handling). So it looks like for Slack we would need a dedicated endpoint. 

It looks from first glace like that's more or less how github handles their webhooks as well - [See this](https://developer.github.com/webhooks/configuring/#writing-the-server)

IFTTT allows you to "make a web request" after a trigger, and it is a bit easier to take advantage of than Slack. IFTTT allow you to set the URL, the HTTP call type (GET, POST), as well as edit the message body to fit your needs. Unfortunately, they don't allow you to set headers, only the response body. So I guess the only real limitation here would be the API Token would need to be in the body text... Not really ideal, but maybe workable.

**Comment by christophersw** [comment]
Completely agree on implementing a per-service API... That's just whack-a-mole thinking that could lead to terrible bloat-ware. 

**I love the idea of the catch-all + scripting.** That really leverages the awesome capabilities of the Trilium's scripting! It's also really flexible, so you could implement all kinds of interactivity and interaction beyond simply posting new notes. You leave it entirely up to the user how to deal with the specific response bodies and content - so the main repo remains clear of all that integration-specific code.

**Comment by zadam** [comment]
released in 0.29.

Documentation here: https://github.com/zadam/trilium/wiki/Custom-request-handler

**Comment by christophersw** [comment]
This is phenomenal, and works perfectly! Thanks for the hard work!
