### ISSUE TITLE
(Bug report) Task manager: new task template doesn't auto update if attribute changed

### ISSUE THREAD

**Issue by Seiryu-K9** [zadam/trilium#3564]
### Trilium Version

0.58.7

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

opensuse tumbleweed 

### Description

Environment:

- fresh installation, used template 

Steps:

- First I create new task from template source, then change attribute 'tag'. 

Expected Behavior

- new template task should be automatically move to correct '**health**' tag

![image](https://user-images.githubusercontent.com/103570859/214565579-9baea332-67a6-4744-bd48-e3862e60039a.png)
![image](https://user-images.githubusercontent.com/103570859/215035539-a90e32c8-2a39-44e7-84b4-38f898f16625.png)

### Error logs

[trilium-2023-01-27.log](https://github.com/zadam/trilium/files/10516765/trilium-2023-01-27.log)

**Comment by zadam** [comment]
Thanks for reporting, there was a slight problem in this example script. You can import the fixed version (uncheck "safe import"):

[Task manager.zip](https://github.com/zadam/trilium/files/10553880/Task.manager.zip)
