### ISSUE TITLE
(Feature request) Inline icons

### ISSUE THREAD

**Issue by brecht-derooms** [zadam/trilium#3567]
### Describe feature

Inline (markup) icons inside a text note.

### Additional Information

Some note taking allow you to use inline markup icons in this format: https://gist.github.com/rxaviers/7360908 
I typically use inline icons to highlight things in notes. Is there any way to do that in Trilium? 
If not, consider it a feature request :+1:

**Comment by hulmgulm** [comment]
You can always enter the corresponding Unicode character yourself. If you work on Windows, just press <win>+. which opens a emoji picker.

**Comment by brecht-derooms** [comment]
Of course, I didn't think of that.
That works for me.

**Comment by thanayut1750** [comment]
Press " Win key +  [dot] " which opens a emoji picker.

> You can always enter the corresponding Unicode character yourself. If you work on Windows, just press +. which opens a emoji picker.
