### ISSUE TITLE
Extending trilium

### ISSUE THREAD

**Issue by dixonge** [zadam/trilium#357]
Trilium is inspiring, but frustrating. I love the book review and weight tracker ideas. I want to extend those, perhaps to add movie reviews, or track walking or other things. Normally I'd just copy them out of the demo and alter a few things, but so far all I can do is clone, which I want to *not* do in this case.

The only other alternative seems to be crafting some new module by hand. Unfortunately I'm a hack, not a javascript programmer.

Am I missing an easy way to do this?

**Comment by zadam** [comment]
There's no in-app way to really duplicate a note sub tree, but if I wanted to do that I would export that subtree to .tar file and then import it where I want the duplicate ...

Having said that - if you just want to experiment and play with the demo - you can. The demo are just notes and you can do whatever you want with them - you can pull them out of "Trilium Demo" subtree by drag & drop etc.

**Comment by dixonge** [comment]
I was more interested in creating my own templates, but I don't even see how to edit an existing one.

**Comment by octoshrimpy** [comment]
@zadam if we had a way to view the tree as json (maybe a local window variable on startup, pulled from fancytree), that would be amazing for something like this. 

@dixonge lucky for you I'm a JS dev who is currently working on plugins for Trilium. :) I'll see what I can do. When you say track walking, do you mean how much? The weight tracker uses [chartjs](https://www.chartjs.org/) which has pretty good docs if you want to try your hand at modifying a copy of weight tracker. 

----
----

For now, I'll make my own tree2json with some js and DOM parsing, so that something like this can be done.

**Comment by zadam** [comment]
The whole tree is usually not even loaded (mainly for scalability reasons) so JSON representation is not possible.

But have you seen the [frontend](https://zadam.github.io/trilium/frontend_api/FrontendScriptApi.html) and [backend](https://zadam.github.io/trilium/backend_api/BackendScriptApi.html) APIs? The entities you get from them provide easy access to the whole tree so you can do stuff like:

```javascript
const rootNote = await api.getNote('root');

for (const childNote of await rootNote.getChildNotes()) {
    await childNote.getChildNotes() ....
}
```

This way you can "walk" the tree as you wish ...

**Comment by octoshrimpy** [comment]
sweeet! I'll play with it today.

**Comment by dixonge** [comment]
> @dixonge lucky for you I'm a JS dev who is currently working on plugins for Trilium. :) I'll see what I can do. When you say track walking, do you mean how much? The weight tracker uses [chartjs](https://www.chartjs.org/) which has pretty good docs if you want to try your hand at modifying a copy of weight tracker.
> 
> For now, I'll make my own tree2json with some js and DOM parsing, so that something like this can be attempted

Yes, track walking (or any similar thing). I already tried copying/modifying the weight tracker, but quickly hit a roadblock. I've decided to use something besides trilium for tracking. I have no desire to learn javascript.

**Comment by Marenz** [comment]
I am a bit confused about the APIs.. what exactly is the conceptual difference between the backend and frontend APIs? And how do I authenticated against them from my client?

**Comment by zadam** [comment]
Trilium is a web application (which can be wrapped in the electron build) so there is a frontend running in the browser (or electron renderer process) and backend running on the server (or node process in electron). When you call backend script from frontend script then the authentication is transparent.

I'm not sure what your client is, if it's external component then you might want to use [custom request](https://github.com/zadam/trilium/wiki/Custom-request-handler) which also briefly discusses authentication.

**Comment by Marenz** [comment]
Custom Requests look much more like what I was looking for. I want to create an xbrowsersync compatible REST API (it looks like this: https://api.xbrowsersync.org) so I can have my bookmark syncs in trilium.

Is there some collections of custom requests other users created and shared? I can imagine more usecases than mine..

I do wonder how easy it would be to make a caldav/webdav integration as well...

**Comment by zadam** [comment]
Yeah, I think custom requests is a way to go for your bookmark sync.

So far there isn't any collection, I don't think many users use this feature anyway ...

Not sure about the webdav/caldav since those are HTTP extensions and custom requests currently work with standard HTTP only.

**Comment by Marenz** [comment]
Well, I'll happily share my result if there is any interest.
My dream is that all the Apps I use pipe back into one common backend that has all the data..
eg:

* Email
* task list / todo list app (using webdav currently)
* calendar app
* bookmarks

Email will probably be the hardest

**Comment by zadam** [comment]
I'm definitely interested in your efforts. Your goals are ambitious so they will probably push the limits ...

BTW, this is an old issue so I'll close it. Please open a new issue in case you have more questions/comments.
