### ISSUE TITLE
(Bug report) Instances open in separate browser tabs/windows no longer distinct

### ISSUE THREAD

**Issue by danielbrown96** [zadam/trilium#3571]
### Trilium Version

0.58.7

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

docker rasberry pi

### Description

Trilium is open in two browser tabs to the same note. On tab A, navigate to a different note. Refresh tab B. It will have moved to the new note whereas I believe previously they would have split into multiple tabs automatically. 

This quite annoying for me as I frequently have trilium open to different locations in different contexts across my computers, but I don't like the aesthetics of the tabs, so I hide them with css. (My ideal solution would be the ability to disable tabbing and have multiple instances operate completely separately.

**Comment by zadam** [comment]
Hi, thanks for reporting, this is a recently introduced bug.
