### ISSUE TITLE
Issue with not-equals sign

### ISSUE THREAD

**Issue by mspeculatrix** [zadam/trilium#3580]
### Discussed in https://github.com/zadam/trilium/discussions/3579

<div type='discussions-op-text'>

<sup>Originally posted by **mspeculatrix** January 31, 2023</sup>
Whenever I enter the 'not equals' operator (!=) Trilium changes it to a not-equal symbol (an equals sign with a slash through it). This is irritating when making codes notes. Is there any way of switching off this behaviour? Or a workaround? </div>

**Comment by zadam** [comment]
Resolved in https://github.com/zadam/trilium/discussions/3579
