### ISSUE TITLE
(Bug report) Cannot save relation 'imageLink' of note

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3583]
### Trilium Version

0.58.7

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10

### Description

This error occurred when undeleting a note with an internal link to its subnote.

**Comment by zadam** [comment]
Thanks for reporting. This bug has been fixed last week in dev branch, but this reminded me to backport to master.
