### ISSUE TITLE
(Bug report) Note content get "locked" and not editable sometimes

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3584]
### Trilium Version

0.58.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows10

### Description

After upgrade from 0.58.4 to 0.58.7, the note content occationally seems to be "locked" and not editable anymore.

![GIF 2023-2-2 11-02-10](https://user-images.githubusercontent.com/6752679/216221740-0aef545c-5856-4ea7-a8fa-779c55d4c6f2.gif)

A restart will make Trilium back to normal. But after some time, it will become not editable again. Not sure what caused this yet.

### Error logs

There are some error logs in the console.

![snipaste20230202_112013](https://user-images.githubusercontent.com/6752679/216223745-a9cbcd27-0c3f-4bac-ba60-51f152747daf.png)

**Comment by zadam** [comment]
These are generally caused by some bugs in CKEditor, usually triggered by some specific content/structure/action.

**Comment by Nriver** [comment]
After lots of tests, I find a quick way to trigger this error. Just click the internal links quickly, the editor will get crash. Thus the notes are not editable.

![peek](https://user-images.githubusercontent.com/6752679/216508146-51ddc4e5-e29c-4c92-b503-07396bd65f4f.gif)

Here is my test note.

[test.zip](https://github.com/zadam/trilium/files/10575374/test.zip)

Of course the above step is crazy. But the crash does happen from time to time in my normal note taking process as I jump between note through the internal links. It's getting really annoying now that I do not know when my note content can be lost.

**Comment by Nriver** [comment]
It's still happening in 0.58.8. Would you make Trilium reload or re-initialize the CKEditor if CKEditor crashed? The silent crash is horrible.

**Comment by zadam** [comment]
Ok, I think I managed to fix it. CKEditor has "watchdog" which reinitializes itself after a crash. That was happening, but the problem was that the event listener for the content change was still registered to the old crashed instance and not to the reinitialized one. So the editor component worked, just did not update the notes anymore.
