### ISSUE TITLE
(Bug report) note.dateModified is not updated in scripts

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#3588]
### Trilium Version

0.58.7

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10

### Description

Create a note and then modify it. It is expected that `note.dateModified` will be the modification time, but in fact it will remain the creation time.

**Comment by zadam** [comment]
Hi, how do you modify the note? Is it SQL or the entities?

Through entities the dateModified should be updated: https://github.com/zadam/trilium/blob/master/src/becca/entities/note.js#L1414

Note also that content's dateModified is tracked separately (in note_contents.dateModified).

**Comment by WPum** [comment]
Thanks for responding, I don't realize that the content's modification time is tracked separately.

I created a note and directly modified it in the editor, and then I tried to get this note using `const note = api.getNote(noteId)`. I want to fetch the last modification time of this note's content (or the larger one between the content and all other data). What should I do to achieve this goal?

**Comment by zadam** [comment]
There's a similar logic in the code, I think you can adapt it for your needs:

```javascript
    const contentMetadata = note.getContentMetadata();

    pojo.contentLength = contentMetadata.contentLength;

    pojo.combinedUtcDateModified = note.utcDateModified > contentMetadata.utcDateModified ? note.utcDateModified : contentMetadata.utcDateModified;
    pojo.combinedDateModified = note.utcDateModified > contentMetadata.utcDateModified ? note.dateModified : contentMetadata.dateModified;

```
