### ISSUE TITLE
Setting meta+ctrl+alt+shift+n shortcut not working

### ISSUE THREAD

**Issue by technovangelist** [zadam/trilium#359]
I have remapped my caps lock to command-option-control-shift to give me a new set of keyboard shortcuts. So I want to use them in Trilium. If I use 3 of the keys, it seems to work fine, but as soon as my shortcut has four keys, it won't. I have tried it with that special caps lock key as well as simply mashing down all those keys at once.

**Comment by zadam** [comment]
When you say "use them in Trilium" - how do you bind the keyboard shortcut to something? AFAIK this is not exposed now in script API ...

**Comment by technovangelist** [comment]
here is the beginning of one of your examples:

```javascript
api.addButtonToToolbar({
    title: 'New task',
    icon: 'check',
    shortcut: 'alt+n',
    action: async () => {
        // creating notes is backend (server) responsibility so we need to pass
        // the control there
        const taskNoteId = await api.runOnServer(async () => {
            const todoRootNote = await 
```
shortcut is alt+n. I want to have command-option-control-shift-n. Have tried cmd+shift+ctrl+alt+n and replaced cmd with meta just in case. nothing works.

**Comment by technovangelist** [comment]
i can do meta+n, and i can do ctrl+n, but i cannot do meta+ctrl+n

**Comment by zadam** [comment]
Try `ctrl+meta+n`- I'm using [this library](https://github.com/jeresig/jquery.hotkeys) for keyboard shortcuts and they say if you use multiple modifiers they should be in alphabetical order.

**Comment by technovangelist** [comment]
so shift+meta+n works but ctrl+meta+n does not
