### ISSUE TITLE
(Bug report) A backslash in the name of an image makes it not display when viewed directly

### ISSUE THREAD

**Issue by Mach565** [zadam/trilium#3591]
### Trilium Version

0.58.7

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Home

### Description

If the title of an image notes contains a backslash, the image breaks when viewing that note, as seen below.
![image](https://user-images.githubusercontent.com/97276027/216804147-54c3c8b1-6553-4dc3-a456-8cd777b750eb.png)
The image is still there, and works fine if embedded in another note or renamed back to normal (the image is just a blank square, there's nothing going wrong here.)
![image](https://user-images.githubusercontent.com/97276027/216804348-7d2839a2-a733-42c1-9473-1f829bbcd87a.png)

### Error logs

a:1 GET http://127.0.0.1:37840/api/images/4XIclsQGFRe8/image/a 404 (Not Found)

**Comment by zadam** [comment]
Hello, thank you for reporting this bug, fixed.
