### ISSUE TITLE
[BUG] runOnAttributeChanged complains about isDeleted on null

### ISSUE THREAD

**Issue by Belphemur** [zadam/trilium#360]
Hello,

With the beta 0.28.1

I'm getting a complaint about isDeleted on a null object every time I change an attribute, even if the isDeleted is nowhere to be found in the code.

`Jan 19 11:06:02 dolma trilium[942]: Trace: ERROR: Execution of script "attribute changed" (PX7S8HJwf8Cr) failed with error: Load of script note "attribute changed" (PX7S8HJwf8Cr) failed with: Cannot read property 'isDeleted' of null
Jan 19 11:06:02 dolma trilium[942]:     at Object.error (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/log.js:33:13)
Jan 19 11:06:02 dolma trilium[942]:     at executeBundle (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/script.js:38:13)
`

You can reproduce it with the Task Manager from the demo. Create a task, edit the attribute, nothing happens and check the log of Trilium.

**Comment by zadam** [comment]
Thank you for the bug report. It was a bug in the setNoteToParent API method which caused this error being thrown ...
