### ISSUE TITLE
The display speed of tooltip is slow.

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#3605]
When the title of the note on the left panel is not fully displayed, a tooltip will be displayed, but the display of the tooltip is delayed. How to display the tooltip immediately when the mouse moves over the title.
![图片](https://user-images.githubusercontent.com/37627919/218354255-1b7bfea8-7402-44ee-b85a-b2f94c8a3791.png)

**Comment by zadam** [comment]
This is actually a native tooltip and can't be configured.

It would be quite disruptive anyway to appear immediately.
