### ISSUE TITLE
How do I compile the binary file on the WOA device?

### ISSUE THREAD

**Issue by ShiinaMono** [zadam/trilium#3608]
### Describe feature

The released binaries don't seem to have binaries for the Windows 11 on ARM64 version, is there any intention to release that version? Or what should I do to compile such binaries?

**Comment by zadam** [comment]
No, we don't have such a build. You could try to build from source yourself - https://github.com/zadam/trilium/wiki/Manual-server-installation but it's basically not really tested/supported.
