### ISSUE TITLE
Changing Trilium language

### ISSUE THREAD

**Issue by collector-ynh** [zadam/trilium#3612]
### Trilium Version

0.58.8

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Linux-Mint 21.1

### Description

I would like to change the language of Trilium, but it does not offer any other language than English. Is it possible to change the language of Trilium?

**Comment by sigaloid** [comment]
Unfortunately Trilium doesn't support internationalization currently - https://github.com/zadam/trilium/wiki/FAQ#translation--localization-support and #3603

**Comment by punkyard** [comment]
hi
are we going to be able to access files to translate to our languages?
👍
