### ISSUE TITLE
Not able to access web interface on server side after password change

### ISSUE THREAD

**Issue by Dmitrykrz** [zadam/trilium#3623]
### Trilium Version

0.53.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows 11 + ubuntu (docker)

### Description

I have desktop version of Trilium. I have server version running on remote ubuntu server.
I have no protected notes. I forgot my password. I reset my password via menu in desktop app. Everything is still works fine. Synchronization with ubuntu server works. 
But now when I try to access the web interface of the trilium from my remote server it says "incorrect password".
It is counter intuitive. I just changed the password but server is still talking to windows app no problem. How does the server app knows the password change? How to I access the web interface on the the server app?  I want to acess the trilium from desktop app and also from android phone via web interface on my remote server but now it is impossible to access.

**Comment by zadam** [comment]
Hi,

password is synced (hashed) between desktop app and server - a password change will not break the sync. Sync is aunthenticated using a shared secret embedded in the document (and independent of the password).

You should be able to login to the server app using the new password.

**Comment by Dmitrykrz** [comment]
Thank you for clarification. Now I understand how passwords work. But I still cannot login into web interface with new password that I just changed. It says "Password is incorrect. Please try again" . Desktop app and sync still works fine.

**Comment by zadam** [comment]
@Dmitrykrz have you tried changing password again to rule out the possibility of accidentally changing it to a different password than you expected (e.g. capslock on or similar)

**Comment by Dmitrykrz** [comment]
> @Dmitrykrz have you tried changing password again to rule out the possibility of accidentally changing it to a different password than you expected (e.g. capslock on or similar)

Yes, I have tried that. I am using Keepass and I am copy pasting passwords so it is impossible to make a mistake like capslock on/off. I have tried restarting trillium and changing password again. still, everything works fine but web interface is "invalid password"

**Comment by zadam** [comment]
Hello, I think I managed to reproduce that issue. It seems that the old password on the server instance remains in cache and is not reloaded from the synced database. Restarting the server should help.

**Comment by Dmitrykrz** [comment]
It's all good now. Restarting helped.
