### ISSUE TITLE
(Bug report) Duplicated tabs opened when Control+Click a link

### ISSUE THREAD

**Issue by gingerkitti** [zadam/trilium#3630]
### Trilium Version

0.58.8

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Education 22H2 19045.2604

### Description

when I "control click" a link to website, trilium opens duplicated tabs
![Animation](https://user-images.githubusercontent.com/89347119/220561156-eed48e02-f6b4-406f-b072-d277ab72bfc7.gif)

**Comment by Nriver** [comment]
ctrl + click on an internal link will also open two pages - one in trilium, one in browser.

For now, I would suggest using the middle mouse key to click the links. It works fine.

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed. CKEditor added its own handling of ctrl+click which conflicted with the Trilium's.
