### ISSUE TITLE
Web clipper clips only part of the page on "Save whole page"

### ISSUE THREAD

**Issue by 4asifm** [zadam/trilium#3635]
### Trilium Version

0.47.7

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

I have the latest web-clipper on Mozilla Firefox - v110.

When I clip a page - for most websites the web clipping and storing in Trilium works fine and I get the whole page.

Only, recently I noticed that the clipping is not working fine on StackOverflow. The clipper behaves erratically - sometimes the marked answer is copied, sometime other sections are copied. The question part from the original poster is rarely copied.
(this is not copied properly https://stackoverflow.com/questions/16086162/handle-file-download-from-ajax-post)

Some pages from StackOverflow work fine though.
(e.g. https://stackoverflow.com/questions/1903838/how-do-i-kill-all-the-processes-in-mysql-show-processlist)

The clipping used to work fine before - but recently this snag developed - specifically for stackoverflow.

Any idea?

**Comment by zadam** [comment]
Trilium uses "readability" library for parsing the output. StackOverflow probably changed HTML page structure and it doesn't work anymore, but there's not much I can do about it ... :-(

**Comment by 4asifm** [comment]
So I guess if I want to develop a (local) mod to improve this feature, I should get Readability source and modify it?
Ideas? Suggestions?

**Comment by zadam** [comment]
Yes, probably.

**Comment by 4asifm** [comment]
Thanks a lot for your feedback.
