### ISSUE TITLE
(Bug report) Toggle Line Wrapping not working

### ISSUE THREAD

**Issue by ygbillet** [zadam/trilium#3639]
### Trilium Version

0.58.8 / 0.59.0

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10

### Description

Hi,

It seems enabling or disabling line wrapping for code notes (#3299 ) doesn't work as expected in 0.58.8 and 0.59.0
I found a checkbox in Options / Code Notes / Wrap lines in code notes.

Checked or unchecked i got the same behavior : lines are wrapped in code notes.

**Comment by zadam** [comment]
Hi, did you restart the app after changing the settings?

**Comment by zadam** [comment]
Strange. Unfortunately I can't reproduce this - after restart I can see that the line wrap changed.

**Comment by ygbillet** [comment]
I'm really sorry, i misunderstood code notes and code block.

I just realized my mystake launching a blank instance of trilium !
