### ISSUE TITLE
(Documentation) Markdown URL broken for Weight Tracker.

### ISSUE THREAD

**Issue by syberslxt** [zadam/trilium#3648]
### Trilium Version

0.59-latest

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

Hello,

This is a minor change, but i noticed with the URL on the wiki for `weight tracker`, it removed the space between `Weight` and `tracker` in the url since there is no `%20`. It also results in the markdown not working for hyperlinks.

[Link to the part.](https://github.com/zadam/trilium/wiki/Patterns-of-personal-knowledge-base#day-note)

Instead of:
```
(see a [Weight Tracker](https://github.com/zadam/trilium/wiki/Weight tracker) 
```

It should be: 
```
(see a [Weight Tracker](https://github.com/zadam/trilium/wiki/Weight%20tracker) 
```

**Comment by eliandoran** [comment]
Hello, @syberslxt .

Thank you for reporting.

I have fixed the broken link and It should be OK now.

Feel free to report any other mistakes you might see in the documentation.
