### ISSUE TITLE
Broken images in Markdown import

### ISSUE THREAD

**Issue by SnowDrifterr** [zadam/trilium#3649]
### Trilium Version

0.58.8

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 22623.1250

### Description

When I import a .zip containing markdown files and linked images, the links to said images display as a broken/empty link

![image](https://user-images.githubusercontent.com/57574629/221430969-5f21df9c-35be-4063-b4c1-1614a2934e1f.png)

**Comment by zadam** [comment]
Hello, can you provide a sample of the Markdown file which causes this? Either here or to zadam.apps@gmail.com.

Thanks.

**Comment by hxchtiewei** [comment]
> 




> Hello, can you provide a sample of the Markdown file which causes this? Either here or to [zadam.apps@gmail.com](mailto:zadam.apps@gmail.com).
> 
> Thanks.

[import-test.zip](https://github.com/zadam/trilium/files/10862974/import-test.zip)

**Comment by SnowDrifterr** [comment]
Original page:

![image](https://user-images.githubusercontent.com/57574629/222299437-6057f68b-db40-4fce-b792-3f8b0ba06ab2.png)
[Draw-Test.zip](https://github.com/zadam/trilium/files/10866569/Draw-Test.zip)

**Comment by Nriver** [comment]
![import](https://user-images.githubusercontent.com/6752679/222307360-e937ace9-3ef7-437a-b75c-177b1de0f574.png)

You can try to import your markdowns with my [trilium-py](https://github.com/Nriver/trilium-py#advanced-usage-upload-markdown-files). It will handle the images for you.

**Comment by zadam** [comment]
Hello, thank you for the samples. URL rewriting for the images was broken if there was no meta-file. This is now fixed.

There will still be some extra tokens like `{width="4.375in"` since those are non-standard Markdown extensions.
