### ISSUE TITLE
Smart Tags

### ISSUE THREAD

**Issue by dpffxhad** [zadam/trilium#365]
Standard Notes have this feature called [Smart Tags](https://github.com/standardnotes/desktop/releases/tag/v2.3.0) which makes it possible to view notes edited in past x days, contains certain words.
Is it possible to have something like that?

**Comment by zadam** [comment]
Hello, I think conceptually similar feature in Trilium is called [saved search](https://github.com/zadam/trilium/wiki/Search). It doesn't support "notes edited in past X days" even though it should be possible once #38 is implemented.
