### ISSUE TITLE
(Bug report) Jump to note opens notes within Hidden Notes

### ISSUE THREAD

**Issue by JaCoB1123** [zadam/trilium#3654]
### Trilium Version

0.58.8

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 22H2 19045

### Description

When I use "Jump to note" to open a note, Trliium regularly switches the sidebar to the "Hidden Notes" view. It looks like this afterwards:
![grafik](https://user-images.githubusercontent.com/642504/221662205-072da891-18ab-414e-a2a1-ec3881f3bf84.png)

The note is found by Jump to note within "Hidden Notes" although it appears directly in my "root / INBOX". 
![grafik](https://user-images.githubusercontent.com/642504/221662543-a6d1b133-c0c8-462a-889d-e1b27c5788a3.png)

I can reproduce the issue on directly the server as well.

**Comment by zadam** [comment]
Hello, thank you for reporting this bug. It has been fixed and will be released in 0.59.1.
