### ISSUE TITLE
No new theme selection and login after restart

### ISSUE THREAD

**Issue by memo-567** [zadam/trilium#3662]
### Describe feature

It would be nice if there's no need to login again and not to select the favorite theme again after server / Trilium restart or update of Trilium.

**Comment by zadam** [comment]
Hello, app restart should require neither login nor theme selection. Something seems to be wrong.

Can you clarify closer what happens? Do you get this screen after restart?

<img width="563" alt="image" src="https://user-images.githubusercontent.com/617641/222354140-616f13d2-9e39-4410-8f04-3cb603ead4db.png">

**Comment by memo-567** [comment]
Just in the beginning.  After the desktop app syncs, I get this one:

![trilium hw2k com -  2023 - 03 - 02  08 - 01](https://user-images.githubusercontent.com/58190287/222355258-f7e2383a-41b5-4bd3-a64d-692d44bf4b11.jpg)

**Comment by memo-567** [comment]
#### Notice

I selected:

`I have desktop instance already, and I want to set up sync with it`

in the beginning, if this is relevant.

**Comment by zadam** [comment]
Okay. So once you login, you end up with a default theme, even though you previously selected another theme?

**Comment by memo-567** [comment]
Unfortunately yes `¯\_(ツ)_/¯`

**Comment by memo-567** [comment]
I found the issue. The reason was a misconfiguration on my site. Sorry for this.
