### ISSUE TITLE
(Feature request) #run=... to be executed on inherited notes

### ISSUE THREAD

**Issue by Fackelmann** [zadam/trilium#3669]
### Describe feature

I want to have a parent note (type text) with the inheritable attribute "#run=frontendStartup". Under this note I have several child notes with small JS frontend scripts (mostl shortcuts).

My expectation is that the "run" attribute will be inherited by the child notes (it is), and thus the notes will be executed automatically on startup (they are not). I have to set this attribute manually as an owned attribute for each of them if I want them to execute on startup.

Is this a known limitation? It would be useful to be able to set an "executable" parent note.

**Comment by zadam** [comment]
Hi, you're right, this wasn't respecting inheritance. On frontend this was apparently done intentionally as a (small) optimization, but reflecting on it, this trade-off was probably not worth it.
