### ISSUE TITLE
Search bar overflow in resized side pane

### ISSUE THREAD

**Issue by dbranham20** [zadam/trilium#367]
Hi, 

Using the search bar in the side panel after shrinking the size of the side panel causes it to overflow and be unusable in the notes area. Attached is a screenshot and the [logs](https://github.com/zadam/trilium/files/2780095/trilium-2019-01-21.log) from today when I noticed it.

_____________________________________________________________________________________
![screenshot from 2019-01-21 13-17-55](https://user-images.githubusercontent.com/29207819/51492452-e7e35c00-1d7f-11e9-91d8-a12365235ac8.png)

**Comment by zadam** [comment]
Thank you for report, this will be fixed in next patch release.
