### ISSUE TITLE
ApplyLayer (...) invalid argument when pulling docker image

### ISSUE THREAD

**Issue by whatthesamuel** [zadam/trilium#3674]
### Trilium Version

0.59-latest

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Debian GNU/Linux 11

### Description

![image](https://user-images.githubusercontent.com/31382049/223033612-b662924a-093d-44b7-9bb5-b8bb6daf9641.png)

I've been sleeping on updates and now when I decided to update to the latest version I got these errors on the server. I traced it back down and found out that it starts from 0.75.5 but the unlink happens at different places depending on versions. I've updated docker to the latest version, but it didn't help. I'm not a dockerfile expert, but I think there might be an invalid argument somewhere?

**Comment by zadam** [comment]
Hi, TBH it seems like a docker bug to me. I haven't seen this yet.

**Comment by whatthesamuel** [comment]
@zadam It's been a while, I've waited to see if docker made any significant changes/fixes, and just did the test again, but the problem persists. I created a clean new system to test it out, but the latest version I can use is still 0.75.4, because of this issue.

**Comment by rauenzi** [comment]
This (https://github.com/zadam/trilium/pull/3410) seems to be the only change going from 0.57.4 to 0.57.5. So I think you would need to take down any running instances, remove all previous trilium images (and cache), then try to pull a new one.

**Comment by whatthesamuel** [comment]
> This (#3410) seems to be the only change going from 0.57.4 to 0.57.5. So I think you would need to take down any running instances, remove all previous trilium images (and cache), then try to pull a new one.

I actually created a new, clean vm, or rather a new proxmox container to test it, but I just couldn't pull any images after 0.57.4. Not just 0.57.5. It is on debian 11

**Comment by rauenzi** [comment]
> new proxmox container

Ah that makes a lot of sense now. Try changing your docker storage driver from OverlayFS to VFS.

**Comment by whatthesamuel** [comment]
> Ah that makes a lot of sense now. Try changing your docker storage driver from OverlayFS to VFS.

that worked, thanks!
