### ISSUE TITLE
(Feature request) Natural sort in sorted notes.

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3690]
### Describe feature

Currently the sorting order is alpabetical. Wish there is a natural sort.

Current the ordering will make this.
![ksnip_20230309-091155](https://user-images.githubusercontent.com/6752679/223889420-1b174224-45ac-4afd-ac6b-7a72ac658479.png)

Natural sort would be like this.
![ksnip_20230309-091212](https://user-images.githubusercontent.com/6752679/223889455-dcc0c85c-5c8e-421f-a733-9c6486f34566.png)

**Comment by zadam** [comment]
Well, you need to add a zero in front of the single digit, and it works like magic :D

Titles are strings, there could be added some magic trying to guess the type, but I think it would have the potential of being even more confusing.

**Comment by Nriver** [comment]
I found `localeCompare` from https://stackoverflow.com/questions/2802341/natural-sort-of-alphanumerical-strings-in-javascript. It's a built-in feature in feature in modern js.

I tweaked the code a little bit and made it work.
![Peek 2023-03-10 14-24](https://user-images.githubusercontent.com/6752679/224242050-a89301d4-fe65-4727-950d-c3fda7eff10a.gif)

Also added a new label `#sortNatural` to trigger this.
![Peek 2023-03-10 14-25](https://user-images.githubusercontent.com/6752679/224242169-2281b65f-6d70-454c-8230-a921fd33343d.gif)

I will make a PR, please have a look.

**Comment by Nriver** [comment]
PR is here https://github.com/zadam/trilium/pull/3695

**Comment by Nriver** [comment]
I find another benefit for natural sort.

The original sort for Chinese characters results in a strange order for Chinese Pinyin (how we pronounce Chinese characters).
![ksnip_20230329-144721](https://user-images.githubusercontent.com/6752679/228449317-dd1cc17f-9b6b-484a-80b0-69b4cb0cfac9.png)

The pinyin for the first character of above notes are:
```
yi
ji
an
kai
shu
ce
you
dian
bian
yu
```
The order looks chaotic.

Natural sort will result like this:
![ksnip_20230329-144738](https://user-images.githubusercontent.com/6752679/228449505-9ee878a2-f40e-4083-a79f-ecec4be5f73a.png)
Which is:
```
an
bian
ce
dian
ji
kai
shu
yi
you
yu
```
The order looks much better in this way as it follows the a-z order like the OS would place them in.
![snipaste20230329_150459](https://user-images.githubusercontent.com/6752679/228453507-abe42dcc-0502-4db1-865e-f7bc43e63dae.png)


Here is a little sample note with those characters.
[Chinese character.zip](https://github.com/zadam/trilium/files/11097453/Chinese.character.zip)

**Comment by Nriver** [comment]
Close as merged.
