### ISSUE TITLE
(Bug report) Some links lost when importing from .enex

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#3692]
### Trilium Version

0.59.1

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10

### Description

When importing notes from an .enex archive, some links are lost. It would be preferable if the links were preserved in some way - even if they are broken links in Trilium. Broken links can be fixed, but missing links can't.

After importing, i can see that the `<a>` tag is preserved, but the `href` attribute isn't:

### Evernote:
![image](https://user-images.githubusercontent.com/10717998/224069012-1d25005b-562b-4d06-8511-b07b6cdec79c.png)

### Evernote (enex) source:
`<en-note><div><font face="Arial" style="font-size: 10pt;">File Link:&nbsp;<a href="file:///C:/file.txt"><font>C:/file.txt</font></a></font></div><div style="margin: 0in;"><font style="font-family: Arial; font-size: 10pt;">OneNote Link:&nbsp;<a href="onenote:Notebook.one#note_name&amp;section-id=%7BB586B89B-DBB4-4083-A09B-AD2C17100F40%7D&amp;page-id=%7B127D4582-5263-4E3D-8BB6-48F5D92C691C%7D&amp;object-id=%7B8EDA20EB-AA0D-4EF2-B102-8DD244309BC0%7D&amp;2A&amp;base-path=C:%5Cpath_to_notebook">OneNoteLink</a></font></div></en-note>]]></content><created>20230309T145905Z</created><updated>20230309T150302Z</updated><note-attributes><author>evernote.com@gieger.org</author><source>desktop.win</source><source-application>evernote.win32</source-application></note-attributes></note></en-export>`

### Trilium:
![image](https://user-images.githubusercontent.com/10717998/224069064-81d68ac0-ccb8-4c43-911f-86612ce5a2fa.png)

### Trilium Source:
`<div>File Link: <a>C:/file.txt</a></div><div>OneNote Link: <a>OneNoteLink</a></div>`

I'm pretty sure this is related to https://github.com/zadam/trilium/issues/965

I've attached a sample note in .exex format.
[LostLinks.zip](https://github.com/zadam/trilium/files/10933053/LostLinks.zip)

### Error logs

The only thing i've seen in the debug console is this after importing the test enex:
![image](https://user-images.githubusercontent.com/10717998/224071045-6e8233f6-6a65-4dac-8c9e-34278f815e50.png)

**Comment by zadam** [comment]
Hi, the URI scheme 'file' was not white listed, I've added it together with some other common ones.
