### ISSUE TITLE
PLEASE STOP SUPPORTING UKRAINE WAR

### ISSUE THREAD

**Issue by anthonyrussano** [zadam/trilium#3694]
I'm honestly asking you to please remove your public support for this Ukrainian war from your software project.

**Comment by anthonyrussano** [comment]
Since you have openly demonstrated your allegiance to this ukraine war, I can no longer trust or support this project.

**Comment by atomGit** [comment]
to the dev(s): research what's _really_ going on in Ukraine from **independent** journalists and those who actually live there and have witnessed the numerous atrocities committed by the U.S. sponsored you're supporting
