### ISSUE TITLE
(Feature request) Is it possible to add an option to disable the editor's autocorrect feature

### ISSUE THREAD

**Issue by gingerkitti** [zadam/trilium#3696]
### Describe feature

Autocorrect feature may be useful, but sometimes it can cause trouble.

### Additional Information
The following is one of examples which demonstrates how autocorrect can cause trouble
![Animation](https://user-images.githubusercontent.com/89347119/224247685-e4b0dc7f-4bf1-42a2-aeb2-c4e8a6319276.gif)

**Comment by XXXJetfireXXX** [comment]
It is not the autocorrection but the font ligature (the visual change is purely cosmetic). I don't remember how do you exactly turn this off, probably by overriding theme fonts or somethin...

**Comment by gingerkitti** [comment]
Thank you very much. I have fixed it.

**Comment by zadam** [comment]
Yes, it's a font ligature thing. For future reference, the Monospace font needs to be overriden:

![image](https://user-images.githubusercontent.com/617641/224572228-db9eb9f5-7c1a-4c11-8585-f8075570333d.png)
