### ISSUE TITLE
(Feature request) The current directory is partially bolded

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#3700]
### Describe feature

For example, I am now in this part, but the directory has not changed. Can you add a bold effect to the part of the directory where you are located? Let me know which directory I am in now, and he hasn't changed in that part of me now. I don't know where I am.
![image](https://user-images.githubusercontent.com/45162558/224592921-c70b75b8-a0e6-4d03-9a60-52982d623ea8.png)

**Comment by zadam** [comment]
Do you mean a cursor? TBH I probably don't understand.

**Comment by Joackk** [comment]
> Do you mean a cursor? TBH I probably don't understand.

For example, in case the title is 1, 2, 3 respectively, can I have an operation to bold the outline of 2 when browsing the content of 2? Let me know that I am browsing this part of 2.

**Comment by Joackk** [comment]
> Do you mean a cursor? TBH I probably don't understand.

It's been solved。
https://github.com/SiriusXT/trilium-show-position-in-toc  
This script solved my problem.
