### ISSUE TITLE
(Bug report) notes cannot be opened on desktop version

### ISSUE THREAD

**Issue by Lizlone** [zadam/trilium#3725]
### Trilium Version

v0.59.2 release

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 20.04 LTS x86_64

### Description

I just updated from v0.58.8 release to the newest version v0.59.2 release.
When I open site on chrome browser(windows), notes that are being clicked cannot be opened. It stays on root note, so does the option page. I can open the option page but the setting on this page cannot be opened.
After switching to mobile version, it worked. Only the desktop version has this trouble.

### Error logs

# Frontend logs
:8080/#root-yiWJ:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
:8080/#root-yiWJ:1 The page requested an origin-keyed agent cluster using the Origin-Agent-Cluster header, but could not be origin-keyed since the origin 'http://mydomain' had previously been placed in a site-keyed agent cluster. Update your headers to uniformly request origin-keying for all pages on the origin.
split.min.js:2 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://mydomain/assets/v0.59.2/libraries/boxicons/fonts/boxicons.woff2
split.min.js:2 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://mydomain/custom/fonts/raleway.woff2
icon-grey.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
raleway.woff2:1          Failed to load resource: the server responded with a status of 404 (Not Found)
frontend_script_api.js:125 api.addButtonToToolbar() has been deprecated since v0.58 and may be removed in the future. Use  Menu -> Configure Launchbar to create/update launchers instead.
addButtonToToolbar @ frontend_script_api.js:125
VM123:16 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dataset')
    at hide (eval at <anonymous> (bundle.js:18:20), <anonymous>:16:19)
    at updateHiddenClass (eval at <anonymous> (bundle.js:18:20), <anonymous>:146:9)
    at noteTreeProto.reloadTreeFromCache (eval at <anonymous> (bundle.js:18:20), <anonymous>:103:5)
jquery.fancytree-all-deps.min.js:1 FancytreeNode@BRMzLRa8sgzK[title='Options'] nodeSetExpanded: UL.style.display already set
d @ jquery.fancytree-all-deps.min.js:1
ws.js:211 22:23:47 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.
ws.js:221 22:23:47 WS closed or closing, trying to reconnect
ws.js:211 22:24:47 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.
ws.js:211 22:25:47 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.
ws.js:221 22:25:47 WS closed or closing, trying to reconnect
:8080/#root/_hidden/_options-CTez:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'isM3U8Video')
    at chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js:1:17996
:8080/#root/_hidden/_options-CTez:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
ws.js:211 22:26:47 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.
note_context.js:41 Uncaught (in promise) TypeError: Cannot create property 'triggerSwitchEvent' on boolean 'true'
    at x.setNote (note_context.js:41:14)
    at tabContextProto.setNote (eval at <anonymous> (bundle.js:18:20), <anonymous>:86:35)
    at async HTMLDivElement.activate (note_tree.js:392:43)
9note_context.js:41 Uncaught (in promise) TypeError: Cannot create property 'triggerSwitchEvent' on boolean 'true'
    at x.setNote (note_context.js:41:14)
    at tabContextProto.setNote (eval at <anonymous> (bundle.js:18:20), <anonymous>:86:35)
2note_context.js:41 Uncaught (in promise) TypeError: Cannot create property 'triggerSwitchEvent' on boolean 'true'
    at x.setNote (note_context.js:41:14)
    at tabContextProto.setNote (eval at <anonymous> (bundle.js:18:20), <anonymous>:86:35)
    at async HTMLDivElement.activate (note_tree.js:392:43)
:8080/#root-ak52:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
:8080/#root-ak52:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
ws.js:211 22:30:35 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.
9note_context.js:41 Uncaught (in promise) TypeError: Cannot create property 'triggerSwitchEvent' on boolean 'true'
    at x.setNote (note_context.js:41:14)
    at tabContextProto.setNote (eval at <anonymous> (bundle.js:18:20), <anonymous>:86:35)
7Unchecked runtime.lastError: The message port closed before a response was received.
:8080/#root/_hidden/_options-3J98:1 Unchecked runtime.lastError: The message port closed before a response was received.
:8080/#root/_hidden/_options-3J98:1 Unchecked runtime.lastError: The message port closed before a response was received.
:8080/#root/_hidden/_backendLog-7uwV:1 Unchecked runtime.lastError: The message port closed before a response was received.
:8080/#root/_hidden/_backendLog-7uwV:1 Unchecked runtime.lastError: The message port closed before a response was received.
:8080/#root/_hidden/_backendLog-7uwV:1 Unchecked runtime.lastError: The message port closed before a response was received.
:8080/#root/_hidden/_backendLog-7uwV:1 Unchecked runtime.lastError: The message port closed before a response was received.
:8080/#root/_hidden/_backendLog-7uwV:1 Unchecked runtime.lastError: The message port closed before a response was received.
DevTools failed to load source map: Could not load content for http://mydomain/assets/v0.59.2/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://mydomain/assets/v0.59.2/libraries/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://mydomain/assets/v0.59.2/libraries/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://mydomain/libraries/ckeditor/ckeditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://mydomain/assets/v0.59.2/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by zadam** [comment]
Hi, it looks like you have some custom code which is crashing this. There's no `updateHiddenClass` function in Trilium codebase.

Try starting Trilium in [safe mode](https://github.com/zadam/trilium/wiki/Troubleshooting#broken-script-prevents-application-startup) and identify the offending script.

**Comment by XXXJetfireXXX** [comment]
`updateHiddenClass` is from Hidden Notes plugin: #2072

**Comment by Lizlone** [comment]
Thanks, it worked after I delete the Hidden Notes plugin which I rarely used.
