### ISSUE TITLE
parse error in  attribute changed code for tasks

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#373]
I am running 28.2 and when I open the _attribute changed note, under Implementation of TODO, the line:

const note = await api.originEntity.getNote();

has a small red x next to it and when I mouse over says "Parsing error: Unexpected token API"

**Comment by zadam** [comment]
Hello, I'm aware of this issue. This is ESLint error report which complains of using await outside of a function. This is not allowed in JS, but what ESLint doesn't know is that during runtime code is surrounded by function provided by Trilium. Unfortunately I'm not aware of a way to fix this. This is already tracked in #81
