### ISSUE TITLE
(Bug report)  How to add a label through the front js and test setlabel for errors :

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#3731]
### Trilium Version

0.59.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

win10

### Description

 How to add a label through the front js and test setlabel for errors :
`note.setLabel("xx").value=0.5;`

### Error logs

 failed with: note.setLabel is not a function

**Comment by zadam** [comment]
In general, you can't make changes to data directly from frontend, but there's a trick/function to do this:

This is a frontend script note:

```javascript
const noteId = // you get this from somewhere

await api.runOnBackend(async noteId => { // transition into the backend process
       const note = api.getNote(noteId);
       note.setLabel('xx', 'your value');
}, [noteId]); // notice the noteId, this is the argument list for the backend function. Can be primitive values only.
```
