### ISSUE TITLE
Create New Note at the Top

### ISSUE THREAD

**Issue by pfirsich** [zadam/trilium#3734]
### Describe feature

It would be nice if clicking on the "+" button next to a folder would create a note at the top of the child note list, since currently the first thing I do after creating a new note is moving to the top every time.

Of course I am not asking to change the default behavior. Ideally there would be a setting in the options to change the behavior.

**Comment by zadam** [comment]
Hi, this is not supported directly, but something close by is:

![image](https://user-images.githubusercontent.com/617641/226058161-958adbe4-e229-442d-ae70-d62492b6cec4.png)

These labels define that notes are sorted by their creation date in descending order. Putting these labels on the root and making them inheritable means that it applies everywhere. The downside is that with this setup, you can't change the note order at all.

**Comment by pfirsich** [comment]
Hey, though that is interesting, not changing the note order would make this not very useful to me. 
I fully understand if this is not worth the trouble and clutter if few people are interested in it.
If you can see it being added in principle, but don't find the time or don't want to prioritize it, would you be willing to accept contributions that add this feature?

**Comment by zadam** [comment]
Ok, I added the `#newNotesOnTop` label, you can again put it to root and make it inheritable to have effect everywhere. Will be in the 0.60

**Comment by pfirsich** [comment]
That sounds great! I'm excited to try it out. Thank you so much!

**Comment by pfirsich** [comment]
I got a chance to try it out now and it's perfect. Thanks a lot again!
