### ISSUE TITLE
Rofi like Tab Switching for Open Notes

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#3735]
### Discussed in https://github.com/zadam/trilium/discussions/3730

<div type='discussions-op-text'>

<sup>Originally posted by **adityaverma415** March 17, 2023</sup>
Hello,

Sometimes, I find myself having multiple files open simultaneously. To navigate to the desired file, I have to use my cursor or to keep pressing `Ctrl + Tab` till I arrive at the desired file. While this is alright, I think it would be great if we could pull up a menu of open files with the press of a button combination and then just select and open a desired file. This functionality has been implemented for open windows in [`rofi`](https://github.com/davatorium/rofi).

If this is a plausible idea, would you implement it? If yes, how long would it take?

Thanks for your time.</div>

**Comment by adityaverma415** [comment]
I had another idea. Perhaps it would be useful to be able to jump to an open file like we jump to tabs in certain browsers. In Vivaldi, this can be done by pressing `Ctrl+[NUMBER]`, where [NUMBER] is the ordinal value of the open tab in the tabs open. If there are more than 9 tabs, pressing `Ctrl+0` opens the last tab in the list of open tabs.

**Comment by zadam** [comment]
Sounds pretty good.
