### ISSUE TITLE
Spellcheck?

### ISSUE THREAD

**Issue by logan-lieou** [zadam/trilium#374]
Love the application so far and very impressed overall but I couldn't help but notice the absence of a spellcheck, which is pretty standard and pretty easy to implement. but besides that keep up the good work!

**Comment by bwat47** [comment]
#182 
#181

**Comment by gerroon** [comment]
Offline spellcheck would be so nice :(

**Comment by zadam** [comment]
Spellcheck is provided in 0.36 (beta for now).
