### ISSUE TITLE
(Feature request) How to keep him at the top when creating notes？

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#3742]
### Describe feature

When creating a note, by default he will add it at the bottom, how do I set it so that the note starts at the top when it is created?

**Comment by zadam** [comment]
Coincidentally I just implemented this feature in https://github.com/zadam/trilium/issues/3734

It will be in the next 0.59.X release.

**Comment by Joackk** [comment]
> 巧合的是，我刚刚在#3734中实现了此功能
> 
> 它将在下一个 0.59.X 版本中。

Thanks, I'm looking forward to it.
