### ISSUE TITLE
(Bug report) Notebook card headers are smaller than text inside the note

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#3747]
### Trilium Version

0.59.2

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10

### Description

Currently the header on the note cards are smaller than all the headings in the note itself:
![image](https://user-images.githubusercontent.com/10717998/226457442-41026425-ce60-4861-b805-233eb75d9d74.png)

Ideally the note header should be larger than the content of the note. This may take up more screen real-estate than desired and doesn't leave a lot of room for note text to show - especially with the large padding around the headers.
![image](https://user-images.githubusercontent.com/10717998/226458979-e1741763-be8e-442d-8a19-2e3ece330172.png)

Alternatively, we could color the header slightly different to differentiate it?
![image](https://user-images.githubusercontent.com/10717998/226458543-f362a955-e815-4377-a2f9-4f2da563d240.png)

Or maybe an underline after the header?
![image](https://user-images.githubusercontent.com/10717998/226458187-30c08890-022f-49b7-8b3c-98e03ab48cb7.png)

**Comment by XXXJetfireXXX** [comment]
I like the underline solution, looks neat :)

**Comment by zadam** [comment]
I agree with @XXXJetfireXXX.

H1 semantically does not match card titles, it's also just too large ...
