### ISSUE TITLE
(Feature request) Align the note-content to the left

### ISSUE THREAD

**Issue by oyundev** [zadam/trilium#3749]
### Describe feature

Is it possible to aling the contents to the left side instead of centering them?

![align-left](https://user-images.githubusercontent.com/44315345/226474467-c6ad4efb-59ac-4bf6-b7cb-9421bc2df832.png)

**Comment by zadam** [comment]
Hi, this is caused by the reduced max content width: 
![image](https://user-images.githubusercontent.com/617641/226477077-9b90a11a-f1e0-4e8b-b8ed-b6787ee07a90.png)

Increasing it might help.

**Comment by oyundev** [comment]
Thanks for your prompt reply. :) As you've suggested, after increasing the setting value: 'Max content width in pixels' from 1200 to 12000 (and after reloading), the annoying(at least to me) gap is gone, now the note contents fills the page as I expect them to be.
