### ISSUE TITLE
Alt-Left and Alt-Right Key Bindings

### ISSUE THREAD

**Issue by iwoloschin** [zadam/trilium#376]
I think this is probably related to #86, and possibly just asking for it to be reverted, but is it possible to revert behavior for Alt-Left and Alt-Right to jump backwards/forwards by one word?  The jumping through note history is great, but I'd prefer that to be a different keybinding if possible.  This trips me up a couple of times a day, and while I might eventually retrain my fingers, I think this is still a useful keybinding for a text editor to have.

**Comment by zadam** [comment]
Browser behavior with these shortcuts is the navigation in the history and I'm trying to keep reasonable parity between desktop and web versions.

Also for jumping between words there's (standard) CTRL-LEFT, CTRL-RIGHT. What editor uses ALT-Left and ALT-Right for these?

**Comment by iwoloschin** [comment]
Ah, this might be a macOS thing then.  On macOS the Ctrl-Left/Right keypress is typically used as a global Space Switch (think virtual desktops).  Alt-Left/Right is used instead for jumping backward/forward by one word.  Web navigation, for backward/forward one page is typically Cmd-Left/Right.

**Comment by zadam** [comment]
I see - so I changed the bindings to CMD-left/right for Mac so Alt-left/right should have original mac behavior.
