### ISSUE TITLE
Nginx-proxy-setup example

### ISSUE THREAD

**Issue by Vertux** [zadam/trilium#3763]
### Trilium Version

0.59.2

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Debian 11

### Description

Not a bug, but a little remark.
I have found by chance your nginx proxy configuration example: https://github.com/zadam/trilium/wiki/Nginx-proxy-setup

IMHO it would make sense to replace the placeholder "IP" with  "127.0.0.1", because it is not really a variable option.

**Comment by zadam** [comment]
Updated, also added the default port.
