### ISSUE TITLE
Freeze when typing at sign followed by two double-quotes (@"")

### ISSUE THREAD

**Issue by bhank** [zadam/trilium#3772]
### Trilium Version

0.59.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 version 22H2

### Description

Type `@""` in a note. After typing `@` it pops up the list of notes to autocomplete; after typing the first `"` it updates the list; after typing the second `"` the cursor still blinks, but the app seems to be frozen. Additional typing or pressing Escape does nothing; clicking does nothing; the "Trilium Notes is not responding" dialog comes up.

### Error logs

[trilium-log.txt](https://github.com/zadam/trilium/files/11072702/trilium-log.txt)

Nothing is shown in the dev tools console.

**Comment by zadam** [comment]
Hello, thanks for the report, this was actually already fixed in https://github.com/zadam/trilium/commit/4c3fcc3ea6f37debcb87ac1a7f5698c27be0e67b but not released yet. I'll make another release soon.

**Comment by zadam** [comment]
Fixed, it was different, although related, bug.
