### ISSUE TITLE
(Bug report) - Shared Note gives a different link for Windows 10 vs Windows 11

### ISSUE THREAD

**Issue by PlatFormPlayZ** [zadam/trilium#3782]
### Trilium Version

v0.58.7 release

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 and Windows 10 w/ the server instance running on Unbuntu (tbh idk which version exactly)

### Description

On my windows 10 machine, when I share a folder, the share link is along the lines of `https://[myDOMAIN]/share/[noteId]`
whereas when I share a file on the windows 11 machine, the link that is generated adds a second slash before the share in the url to look like so `https://[myDOMAIN]//share/[noteId]` the difference that makes means that the css for the page doesnt get loaded in for some reason?

**Comment by sigaloid** [comment]
This might be because you entered in the URL with a trailing slash on one device - check client options, sync, server instance address

**Comment by zadam** [comment]
Hello, it looks like IE is adding a trailing slash to the hostname which is causing this problem. Should be fixed in the next version.
