### ISSUE TITLE
Allow querying by virtual attributes

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#38]
Allow e.g. @dateModified, @dateCreated, @isProtected to be used for filtering in similar way to the "real" attributes.

**Comment by jkurei** [comment]
Is anyone working on this? With a little bit of guidance I'd love to try.

**Comment by zadam** [comment]
This functionality is in parse_filters.js and build_search_query.js

Adding support for filtering by e.g. "@dateModified>=2018-01-01" should not be too difficult since date in DB is actually string so you just need to recognize that this is not an attribute search and compare with column dateModified in notes table. Since date ordering (in ISO format) is same as string ordering you don't need to parse the value or anything ...

The part with `@dateModified >= NOW - 5 days` is more difficult. Our custom parser doesn't support this and it also means you need to understand the data types to be able to calculate `NOW - 5 days`.

**Comment by jkurei** [comment]
I haven't forgotten about this, I've started working on it and gotten some, or may be most normal cases, to work. 

If I'm taking too long please let me know. My "real" work has gotten in the way these days, but I'll have more free time this week. Also I haven't worked on an unknown codebase for a couple of years, and my code-exploring skills are rusty haha.

I've noticed that there is no way in the UI to check the creation or modification dates of a note, am I right? Unless there are revisions, those don't appear anywhere. Shouldn't they? May be show up as non-virtual attributes do?

> The part with @dateModified >= NOW - 5 days is more difficult. Our custom parser doesn't support this and it also means you need to understand the data types to be able to calculate NOW - 5 days.

I don't think I'll have a problem with calculating `NOW - 5 days`. Doing it without momentjs will be a change for me haha, but it's more tedious than actually complicated.

The parsing might be a bit trickier, but I think I'll enjoy exploring that area of your code. 

> Adding support for filtering by e.g. "@dateModified>=2018-01-01" should not be too difficult

I've done this and it wasn't hard. Had to fumble a bit with substr, for the "=" part of ">=" (we want `2017-01-01 = 2017-01-01T12:14:56.301Z`). So now for virtual attributes I produce queries such as:

```sql
SELECT DISTINCT notes.noteId FROM notes
WHERE\n                notes.isDeleted = 0
AND (1 and substr(notes.dateModified, 0, 11) > ?)
```

**Comment by jkurei** [comment]
> Doing it without momentjs will be a change for me

Actually, I just saw moment is in Trilium's dependencies, but I don't think it's being used anywhere. What's that about?

**Comment by zadam** [comment]
You're right that dateCreated and dateModified are not displayed anywhere in the app. There are revisions (Note Actions in top right), but they don't necessarily display this either.

> I don't think I'll have a problem with calculating `NOW - 5 days`. Doing it without momentjs will be a change for me haha, but it's more tedious than actually complicated.
> The parsing might be a bit trickier, but I think I'll enjoy exploring that area of your code.

The tricky thing here is that `@dateModified>="NOW - 5 days"` is currently valid syntax even though it does something different - it's trying to find an attribute with value larger than "NOW - 5 days" (string-wise comparison). `@dateModified>=NOW - 5 days` (without quotes) is also valid and looks for attribute with value larger than "NOW" and then the rest (`- 5 days`) is full text search. So how do we differentiate where we want parts of the string `NOW - 5 days` have special meaning instead of being literal value?

Also does `NOW - 5 days` resolve to date or a timestamp? Meaning does `@dateModified="NOW - 1 days"` look for notes last edited yesterday or only the ones edited add that particular timestamp? If it's the former then it's more complicated since the dates in the DB are in UTC and now we would have to convert to local time so the query would then depending on the timezone look like `... AND notes.dateModified >= '2019-02-03T23:00:00' AND notes.dateModified < '2019-02-04T23:00:00'` (days in UTC don't correspond to days in other timezones).

**Comment by jkurei** [comment]
> So how do we differentiate where we want parts of the string `NOW - 5 days` have special meaning instead of being literal value?

We could use a Regex, and since there is a label type for dates may be it makes more sense to do it only for labels of such type, dateCreated and dateModified. Sounds right to you?

Parse filter could replace the "smart" value `NOW - 5 days` with the result of its calculation if the regex matches and/or the target label fits.

> Also does `NOW - 5 days` resolve to date or a timestamp?

The least surprising thing would be to add a TODAY and do "TODAY - 1 day" for dates. Adding a few "YESTERDAY" and "LAST MONTH" and such sounds great to me too since we're at it. 

Suggestion:

- `NOW - 1 hour` => 2019-02-05 10:00
- `NOW - 1 day` => 2019-02-04 11:00
- `TODAY - 1 day` => 2019-02-04
- `TODAY - 1` => 2019-02-04

Some "smart words" I'd consider: NOW, TODAY, YESTERDAY, LAST MONTH, LAST YEAR, THIS MONTH, THIS YEAR. Do you think this is worth it? May be just "NOW" and "TODAY" are enough?

If you don't want to add any more words, I guess I'd expect "NOW - 1 days" to refer to 2019-02-04 and "NOW - 24 hours" to 2019-02-04 11:00:

- `NOW - 1 hour` => 2019-02-05 10:00
- `NOW - 24 hours` => 2019-02-04 11:00
- `NOW - 1 day` => 2019-02-04

**Comment by zadam** [comment]
> We could use a Regex, and since there is a label type for dates may be it makes more sense to do it only for labels of such type, dateCreated and dateModified. Sounds right to you?

I think this might cause problems in the future when we add more things. But it might be a problem even now - let's say you have a query `@dateModified="TODAY"` - it's not obvious you want a smart today value or literal TODAY string - both of them are valid. You might argue that this value is not possible for @dateModified, but I'd rather have something generic which works on custom attributes as well (custom date attributes are pretty useful).

Instead I'd rather have clear separation on when user wants smart tag and when it's a literal value. Just of the top of my head - possibly using e.g. backtick instead of quotes for smart evaluation and standard quotes for literal one?

**Comment by jkurei** [comment]
That sounds very natural for programmers, IDK how well it would work for the rest of the world... But I can't think of anything much better. 

Using something like $(NOW - 5) or `NOW - 5` would also open the door for more of these "smart" queries, kinda like functions in Excel. You could filter notes such that $(doneDate - todoDate >= 2 days) to search for tasks that went past its due date for instance... This might be going too deep though.

**Comment by jkurei** [comment]
I've implemented two keywords, NOW and TODAY. TODAY is used for dates, NOW is used for times. The code is awful yet, I did the parsing in the most naive way, but I like the functionality. 

```
smart expression => value for the query

today    => 2019-02-11
today+1  => 2019-02-11
today+1d         => 2019-02-11
today+2m         => 2019-04-10
today-3y         => 2016-02-10
now      => 2019-02-10T21:59
now+5    => 2019-02-10T22:03
now-3h   => 2019-02-10T18:58
```

The unit is optional, and the default is days for TODAY expressions and minutes for NOW expressions. I added [iamkun/dayjs](https://github.com/iamkun/dayjs) for this calculation, which is a much lighter equivalent to momentjs, what do you think?

So a query like `@dateCreated=TODAY-6` will lead to a query such as: 

```
SELECT DISTINCT notes.noteId FROM notes
              WHERE
                notes.isDeleted = 0
                AND (1 and substr(notes.dateCreated, 0, 11) = 2019-02-04)
```

I'll look into using backticks for smart queries; right now I do smart queries when user queries a virtual attribute and the query matches a regex, and that's not great.

@zadam What do you think should be the behaviour when a user enters an invalid expression? Like `TODEY+5` or `TODAY+`?

**Comment by zadam** [comment]
@jkurei overall I like it, maybe I would omit default unit since it's not really obvious. I'd just keep unit always mandatory.

Feel free to make PR, it's OK for the code to be ugly for testing & experimentation. We can iteratively improve it later.

> What do you think should be the behaviour when a user enters an invalid expression? Like `TODEY+5` or `TODAY+`?

Good question, I don't know at this point.

Backticks are not mandatory now - it's just one of the possibilities. There's a lot of constraints and trade offs possible.

**Comment by jkurei** [comment]
OK, I'll throw you a PR before the weekend. I have some improvements in mind but they should be quick.

**Comment by zadam** [comment]
Closing as this has been long implemented.
