### ISSUE TITLE
(Bug report) Will not be updated in real-time

### ISSUE THREAD

**Issue by infanx** [zadam/trilium#3803]
### Trilium Version

0.59.3

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 21H2

### Description

After clicking on the new note, you need to refresh the browser to display it
Other operations also require refreshing the browser to update

**Comment by zadam** [comment]
This happens when your reverse proxy blocks WebSocket traffic. Check your nginx/apache/caddy config.

**Comment by infanx** [comment]
> This happens when your reverse proxy blocks WebSocket traffic. Check your nginx/apache/caddy config.

Thank you very much. I have added
```
proxy_set_header Upgrade $http_upgrade;
proxy_ set_ header Connection "upgrade"; 
```
After that, it was resolved
