### ISSUE TITLE
(Feature request) Add a way to configure the default displayed tab of note properties.

### ISSUE THREAD

**Issue by papundekel** [zadam/trilium#3806]
#### Introduction

When opening a note, the behavior seems to be to open the _Promoted attributes_ tab, if it exists. If not, the app opens the _Basic Properties_ (unrelated, but notice the naming inconsistency on _Promoted attributes_). There is one exception to this I found (may be more) which is when the note type is _Book_ it always opens the _Book Properties_ tab.

#### Use case
I often use templated notes with promoted attributes which I set right after creating the note. The type of these notes set in the template is mostly _book_, because the content of the note is better structured in it's child notes than in it's content. With the current behavior I have to change the property tab every time I create such a note.

#### Request
Add an option to configure the default displayed note property tab. Either by having a new enum label with values such as "basic", "book", "promoted", or change the default behavior to always open promoted attributes tab if any exist, as this seems to be the most logical and *almost* current behavior. Book properties are changed rarely and are most often set by the template (at least in my case).

**Comment by zadam** [comment]
Hi, Promoted attributes are indeed meant to be activated when available, beating Book properties. Fixed.
