### ISSUE TITLE
(Bug report) Cannot Duplicate Subtree

### ISSUE THREAD

**Issue by FoodFighters** [zadam/trilium#3813]
### Trilium Version

0.59.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 

### Description

I cannot duplicate subtrees with cloned notes that are internally linked to other notes. 

### Error logs

JS Error: 500 POST /api/notes/gd5kP3uXzIPe/duplicate/jhbEfGuvEA08 - Cannot save relation 'internalLink' of note 'jwavjm5kOKGX' since it target not existing note 'oEYkdwfjLBtJ'.

**Comment by zadam** [comment]
Hi, thanks for reporting this bug, fixed.
