### ISSUE TITLE
Character code specification in HTML header

### ISSUE THREAD

**Issue by ECOWOOD** [zadam/trilium#384]
Print using the export function.

The HTML file outputted in the HTML format by the note export function is displayed on the IE 11 before printing.However, since character strings in Japanese are garbled, it is necessary to change the character encoding of IE 11 to UTF - 8 every time.

Is it possible to specify the character code in the HTML header?

**Comment by zadam** [comment]
You're right, the exported HTMLs didn't have any header, they were more like HTML fragments. Will be in the next stable release.

**Comment by ECOWOOD** [comment]
Thank you. I'll be waiting for Release.
