### ISSUE TITLE
(Bug report) Mermaid diagram not displaying errors.

### ISSUE THREAD

**Issue by perfectra1n** [zadam/trilium#3841]
### Trilium Version

0.59.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 19045.2728

### Description

It looks like the "Mermaid diagram not showing errors" bug has reared its ugly head again, it's the same error as as #3610 (which was fixed in commit 896a4fe), but here are some included pictures

Example of online service that shows error:
![image](https://user-images.githubusercontent.com/2390633/231881362-4e659797-258b-47e1-a414-54fe2b032069.png)

Inside of Trilium:
![image](https://user-images.githubusercontent.com/2390633/231881475-3aa7c389-b2e9-45ad-a1b1-9b177b1d07c9.png)

### Error logs

It doesn't appear that there are any issues inside the log:
![image](https://user-images.githubusercontent.com/2390633/231881896-a963d7a7-24fe-4629-a0d0-e2693e83c1e1.png)

**Comment by zadam** [comment]
Hmm, strange, somehow it does seem to work for me:

![image](https://user-images.githubusercontent.com/617641/232341338-0468a330-87bb-4396-a5c6-f1945bfbaf67.png)

**Comment by perfectra1n** [comment]
That's really interesting, I downloaded the latest version and ran it in portable mode, fresh install, still couldn't see that error populate...
![image](https://user-images.githubusercontent.com/2390633/232342146-96ea21a7-99a3-45e7-8fdb-2d51c1661248.png)

**Comment by perfectra1n** [comment]
Same thing on Linux
![image](https://user-images.githubusercontent.com/2390633/232343048-66934b6a-8191-42c9-9549-185008b726da.png)

No error shown:
![image](https://user-images.githubusercontent.com/2390633/232343054-41e609a7-534b-413f-970d-d2effc7fca81.png)

But what's interesting, if you create a new note, mark it as "Mermaid Diagram" and don't include anything inside the graph, you get the initial "empty graph" error:
![image](https://user-images.githubusercontent.com/2390633/232343160-69546873-886b-41fe-b655-43147a318aa3.png)

But then adding an entry to the graph, the error disappears:
![image](https://user-images.githubusercontent.com/2390633/232343171-4c7bf813-7533-47dc-86b2-dd2476574f99.png)

This is when using the latest Trilium in portable mode on Linux Mint.

**Comment by XXXJetfireXXX** [comment]
Can confirm, the error message is not visible to me as well.
![image](https://user-images.githubusercontent.com/43646178/232343030-8ca22e66-bc44-44d2-a1ab-1afdee78a5a9.png)
Running local setup on Win 10 19045.2728, latest version.

**Comment by perfectra1n** [comment]
It looks like the `mermaid-error alert alert-warning` class has `display: none;` associated to it when adding an entry to the graph
![image](https://user-images.githubusercontent.com/2390633/232343341-034b1b33-bbf8-4383-bcbf-30ff40f54f62.png)

But after deleting that style, the error successfully displayed:
![image](https://user-images.githubusercontent.com/2390633/232343370-481f4268-5ea1-434e-8153-5b02f483f750.png)

**Comment by zadam** [comment]
Ok, I think I got it, there was a race condition which explains that it behaves differently for me and for you.

It's just that mermaid's API is very weird. It boths throws an exception and calls a callback in case of an error, both of which need to be handled, but the order is not defined. There should be new API in v10, I hope it will be better.

**Comment by perfectra1n** [comment]
Awesome, thank you so much for reviewing it and resolving it, I love Trilium :)
