### ISSUE TITLE
copy and paste from libreoffice writer

### ISSUE THREAD

**Issue by iclementine** [zadam/trilium#3842]
### Describe feature

Expected: Select a block of content (text with images) and paste into trilium text note, and the images will be copied into trilium note.

Current: Images are lost. It seems that web pages and office docuemnts are handled differently. BTW, copying a single image from libreoffice writer and paste it into trilium note works. It only failes when selecting and copying text with images.

It would be nice to handle libreoffice writer document is the expected way.

**Comment by zadam** [comment]
Hello, it looks like LibreOffice puts only `file://...` references into clipboard which then renderer process can't access so they appear broke.

However, I fixed the background offline image downloader to understand these local file paths.

Unfortunately, initially the copied content will appear broken until asynchronously the backend job will copy all the images.
