### ISSUE TITLE
URL to create a search

### ISSUE THREAD

**Issue by dabeeeenster** [zadam/trilium#385]
I'd like to integrate Trilium with [Alfred](https://www.alfredapp.com/). Is there a URL that you can open that will create a search when the page loads/opens? I could then use an alfred shortcut to immediately see search results in a new Trilium browser tab?

**Comment by zadam** [comment]
Hello, you will (in the next release) be able to do this with following.

```
http://localhost:8080/#search=abc
```

It's briefly documented here: https://github.com/zadam/trilium/wiki/Search

**Comment by SomwareHR** [comment]
Hi, thanks for that great software! :)

Seems that `http://localhost:8080/#search=abc` is not working.

```text
Homepage: 	https://github.com/zadam/trilium
App version: 	0.59.4
DB version: 	213
Sync version: 	29
Build date: 	2023-04-17T21:40:35+02:00
Build revision: 	1d3272e9f8c27106a66227fbb580677ae5d70427
Data directory: 	/root/.local/share/trilium-data
Host: Linux server 20.04 LTS
```
 
Sometimes Trilium doesn't react at all (stays on whatever URL is active). Sometimes it only displays input field:

+ `Open a note by typing the note's title into the input below or choose a note in the tree`
+ `Search for a note by its name`

![image](https://github.com/zadam/trilium/assets/45540611/7fe887ef-ab3b-4cd9-a883-266c14e4f898)

Result is the same no matter if string is existing in Trilium or not.

Thanks!

**Comment by zadam** [comment]
Hello, this got lost a long time ago in some refactoring. It seems like a useful feature, so I reimplemented this and will appear in 0.61, this time in a slightly different format:

```
http://localhost:8080/#?searchString=abc
```
