### ISSUE TITLE
FR: Disable angle brackets if there is no child note

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#387]
Hi

It will be very useful if the note does not show an angle brackets if there is no child node under neath. At the moment it is a bit confusing when looking at the tree all seem to have the same brackets whether they have child nodes or not.

See the picture please, this node has no child node and still looks like it is a tree node

![screenshot_2019-01-27_12-31-52](https://user-images.githubusercontent.com/8519469/51805175-24242a00-2262-11e9-9fc9-ccb114e150ce.png)

**Comment by zadam** [comment]
So in the picture there are two angle bracket - one signals a folder note, the other is an icon for folder note. If this is really a note without any children, then this is a bug because the first angle bracket is not supposed to be there. This is managed by FancyTree component and it has been very reliable so far.

**Comment by gerroon** [comment]
To make it clear here is a second picture

Both looks same except that "_test" has achild node and "".customize" has no child nodes.

![screenshot_2019-01-27_12-47-29](https://user-images.githubusercontent.com/8519469/51805357-25565680-2264-11e9-8e9f-30f0883dfa6e.png)

**Comment by zadam** [comment]
Hmm, that's weird. This is how it's supposed to look like:

![image](https://user-images.githubusercontent.com/617641/51805422-44a5b180-226d-11e9-8699-0afda4b87e09.png)

What browser do you use?

**Comment by gerroon** [comment]
I am using the linux package from the releases, and running the docker server

**Comment by zadam** [comment]
Oh I see - I didn't see it because of me using a white theme and this shows in dark/black theme only. I'll fix it then! Thanks for help.

**Comment by gerroon** [comment]
Cool, thanks for fixing it. Please release it for the docker too if you can.

thanks
