### ISSUE TITLE
(Bug report) Notes created by custom handlers not displaying local time

### ISSUE THREAD

**Issue by soulsands** [zadam/trilium#3876]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 Pro version 22H2

### Description

![image](https://user-images.githubusercontent.com/32272399/234324173-da0800b7-3f13-4bbe-8cc0-5c46bbb73e08.png)

Hi, I just found notes created through a custom handler do not use local time, but instead use UTC time. Its display can be handled on frontend, but I feel like it's more complicated than that.

**Comment by zadam** [comment]
I assume the custom handlers are executed on your server instance for which UTC is the local timezone.

When you use trilium server edition with a browser, then the local timezone information is taken from the browser, but that info is missing from the custom handlers.

If you are able to control the custom handler invocation, you can add a header `trilium-local-now-datetime` with value like `2023-04-25 00:00:28.504+0200` which will then be used when creating the note.

**Comment by soulsands** [comment]
Thanks! I changed the timezone and it's fixed.
Regarding custom handler, I think it may be necessary to add a tip on [the wiki page](https://github.com/zadam/trilium/wiki/Custom-request-handler), otherwise it looks like kind of a bug. but still, IMHO it's probably no suitable requiring a header to make things work.
I noticed that every entity has both local date and utc date, may I ask what's the different infuences of them? and is it possible to use only utc date in backend and frontend handles the conversion?

**Comment by zadam** [comment]
> but still, IMHO it's probably no suitable requiring a header to make things work.

How it should work? The server won't know the client's timezone unless the client tells the server.

> and is it possible to use only utc date in backend and frontend handles the conversion?

That doesn't work well if you travel between timezones - UTC would stay the same, but when you fly between Tokyo to New York, suddenly the "date created" you see changes from e.g. 6th of May to 5th of May (or vice versa) which is at minimum misleading. That's why we also record the local time with the timezone at the point of time of creation.

**Comment by soulsands** [comment]
thanks for your clarification!
