### ISSUE TITLE
(Feature request) customize search engine

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3882]
### Describe feature

Today, a user complained to me that the default search engine in Trilium is duckduckgo, which is blocked in China. It would be beneficial if we could customize the search engine to use alternatives such as bing or baidu for searching messages.

Also, I believe it would be intriguing to send the message to my personal ChatGPT bot. Given its impressive capabilities, connecting Trilium and ChatGPT in some manner would be a fascinating prospect.

**Comment by zadam** [comment]
A configurable search engine is possible, but perhaps not the highest priority. Should be relatively easy as a contribution, though.

Basically there would be a new "options" row and UI in Options where you can define a template like `https://duckduckgo.com/?q={keywords}` with perhaps few predefined options.

Regarding ChatGPT, such integration seems very vendor specific. It looks more like a use case for custom widgets / scripting.

**Comment by sigaloid** [comment]
> I'm confused. We can search the internet from within Trilium? How do we do that?

In the desktop app, you can select text and it suggests to search in a search engine. 

![image](https://user-images.githubusercontent.com/69441971/235509279-b29a8e9f-bc3e-48ce-aa0a-6f9c58e8cf28.png)

**Comment by Nriver** [comment]
@meichthys The search engine url is currently hard-coded to duckduckgo.

The user I said is just one of the Chinese users who is using the Chinese version of Trillium that I made with the trilium-translation project.

**Comment by Nriver** [comment]
Closing for https://github.com/zadam/trilium/pull/3901
