### ISSUE TITLE
Attached PDF Files will evertime download if open the note

### ISSUE THREAD

**Issue by zutewas** [zadam/trilium#3889]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 with Firefox as Client 

### Description

I installed Trilium in my docker environment and work with Firefox (112.0.2 (64-Bit)) und Windows 10.

Steps to reproduce:
1. Create a Note
2. Drag and Drop a PDF to note for start the import. The pdf is import as note in subtree
3. Drag and Drop the PDF from subtree to main note for link in text

Everytime if I reopen the note from 1. all PDF file will be downloaded. If I open a another note and come back, this issue occurs again.

![pic01](https://user-images.githubusercontent.com/16150873/235325977-8efd41fe-e289-4fb4-813f-5fe27160f406.jpg)

**Comment by Dwindle2234** [comment]
Change Firefox's default behaviour for PDF files to 'open in Firefox'

Settings/General/Applications

![image](https://user-images.githubusercontent.com/120342689/235345518-5ae83eab-6702-44a1-a263-1bc420172fa3.png)

**Comment by zutewas** [comment]
Thanks. This ist very helpful. 

What is a good thing to manage attachments? Should I save all attachments collect in a separate note and link the file in a note where I need it or it is better to save the attachment as child on the parent note which contain my notes (text)?

**Comment by Dwindle2234** [comment]
I prefer the latter: Child on the parent.  Then when you click on the parent you get a nice digest of the children.  Everything in the right place 😁
