### ISSUE TITLE
(Bug report) #sorted should respect branch prefix

### ISSUE THREAD

**Issue by BeatLink** [zadam/trilium#3896]
### Trilium Version

0.59.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linuxt Mint Cinnamon

### Description

When sorting child notes using the #sorted label on parent notes, if the child notes have branch prefixes, the child notes are sorted on their original titles instead of the branch prefixes. In other words, the branch prefix has no effect on note sorting while it should.

**Comment by zadam** [comment]
Hi, thanks for the report. This will be fixed in 0.60.

**Comment by BeatLink** [comment]
Unfortunately this issue is still persistent in 0.60.4

**Comment by zadam** [comment]
It's actually in 0.61 since there was one more unplanned intermediate release.
