### ISSUE TITLE
Placeholder still showing after first Markdown command

### ISSUE THREAD

**Issue by SebastianOner** [zadam/trilium#390]
**0.28.3**

The new-note-placeholder is still showing when you want to open a new note start of with a md-Command. The text disappears after you start typing anything.

[Examples here](https://imgur.com/gallery/yZ73nvA)
[trilium-2019-01-28.log](https://github.com/zadam/trilium/files/2803677/trilium-2019-01-28.log)

**Comment by zadam** [comment]
This has been reported in #358. Currently we're using a CKEditor plugin for the placeholder, but it looks like CKEditor might support this natively in the near future and hopefully without this bug ...
