### ISSUE TITLE
(Feature request) Notes scroll smoothly when toc is clicked

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#3911]
### Describe feature

I hope that the notes can scroll smoothly when the toc is clicked.
After checking the code, I think modifying toc.js can be solved:
`headingElement.scrollIntoView(); -> headingElement.scrollIntoView({behavior: "smooth"});`

**Comment by zadam** [comment]
Hi, I applied your suggestion, but it works only on readonly notes. For editable notes, we would have to use the CKEditor scrolling API (scrollToTheSelection()), but it seems like it doesn't support the smooth scrolling.
