### ISSUE TITLE
Weired behavior: Jump from note to included note(Bug report) 

### ISSUE THREAD

**Issue by ElHado** [zadam/trilium#3914]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 10.0.19045.2846 / Firefox 112.0.2 (64-Bit)

### Description

If you jump into the note and write some text there is weired behavior. If you jump into the note by the tree it is no problem. I made a small vid for this.

It don't matter if I try it with the windows application or with the server/web version. Also in Firefox or Edge/Chrome: Same bahavior.

https://user-images.githubusercontent.com/92795993/236913034-05d3b527-60aa-4a7a-977b-c654b7e6a505.mp4

**Comment by zadam** [comment]
Hi, that looks like the CKEditor crashed. Could you open the devconsole to see if there are errors?

**Comment by ElHado** [comment]
Hi, 
you mean the devconsole from the browser? There are some errors:

```
vTools failed to load source map: Could not load content for chrome-extension://dfhgmnfclbebfobmblelddiejjcijbjm/lib/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://wegele.org/trilium/assets/v0.59.4/libraries/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wegele.org/trilium/libraries/ckeditor/ckeditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wegele.org/trilium/assets/v0.59.4/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wegele.org/trilium/assets/v0.59.4/libraries/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wegele.org/trilium/assets/v0.59.4/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by zadam** [comment]
This has to be reverted, because it broke keyboard navigation in the note tree, see #4036
