### ISSUE TITLE
(Feature request) Is there a way to preserve languages similar to HTML markup

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#3922]
### Describe feature

I want to be able to include inside an html Handlebars templates like so:
`<iframe width="560" height="315" src="https://www.youtube.com/embed/***" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`
I inquired that ckeditor5 has corresponding plug-in or extension support:
https://ckeditor.com/docs/ckeditor5/27.1.0/api/module_html-embed_htmlembed-HtmlEmbed.html
https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html#using-external-services-for-preview

**Comment by zadam** [comment]
Last time I was testing the embed plugin it didn't really work for trilium's usecase. The embedded (e.g. video) could not be interacted with (e.g. play) from within CKEditor. The supported use case was to author e.g. article with embedded video, which will be then playable on static page generated from that content.
