### ISSUE TITLE
(Bug report) `Ctrl-F` doesn't work when viewing note source on Desktop Version

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#3929]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

Ctrl-F does not search note source on the Desktop version (it works fine in the browser since ctrl-f uses the native browser search.

**Comment by zadam** [comment]
Thanks for report. The note source was only recently reworked from a dialog (where search wasn't available) to the current form, but I didn't think of being able to use search now. Will be fixed in 0.59.5.
