### ISSUE TITLE
(Bug report) Cyrillic letters rendered with fallback font

### ISSUE THREAD

**Issue by Lobstarr** [zadam/trilium#3933]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win10 and Win11

### Description

All bold cyrillic characters are rendered with times new roman in notes and note headers.

![trilium](https://github.com/zadam/trilium/assets/6901136/9b713d02-0207-49e0-a7c8-084cbaf801b4)

**Comment by zadam** [comment]
Hi, I updated the font which now seems to have a better support for cyrillic:

![image](https://github.com/zadam/trilium/assets/617641/57473cd9-35ed-4f38-91c0-314c75df56e4)


Will be in 0.60.
