### ISSUE TITLE
Scenario where you can unintentially drag multiple notes

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#394]
Steps to Re-create:
- Create Note A and Note B
- Click on Note A to select it
- Place your mouse cursor over Note B, then click (and hold down the left mouse button, to re-create this you cannot release left mouse yet)
- while holding down the left mouse drag and drop Note B to somewhere else in the tree

Expected: Only note B should be dragged/dropped

Actual: Both Note A and Note B are dragged dropped, as if you had used ctrl + click to select them both

This has left me confused quite a few times as to why some of my notes where unexpectedly appearing elsewhere when I was quite sure I hadn't dragged them!

With these steps, if you make sure to release the left mouse before clicking and dragging note B, it works as expected and only drags note B

**Comment by zadam** [comment]
Hello, I think what you describe matches #375. I agree it's confusing and it has been fixed in master (not yet released though).

**Comment by bwat47** [comment]
yep, that does sound like the same issue, good to hear it's already fixed :)

**Comment by zadam** [comment]
released in 0.29.0
