### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by ryansyah** [zadam/trilium#395]
Hello,

I've been testing Trilium Notes for a few weeks now and love it so far. After importing Evernote documents, I currently have a little over 57,000 notes residing on my client system (macOS 10.14.3, fully patched).

I have tried to setup a sync server, but am running into issues that could use some additional insights.

I have a setup CentOS 7 server with Trilium Notes `0.28.3` in a docker container. I also have nginx running a reverse proxy (per the instructions provided on this wiki) with a certificate provided by certbot/Let's Encrypt. 

When I configure sync and hit the 'Test' button, I get a green status indicator:
```
 Sync server handshake has been successful, sync has been started.
```

Furthermore, the webpage, `https://domain.com/setup` provides the message:
```
Trilium Notes setup
Sync in progress
Sync has been correctly set up. It will take some time for the initial sync to finish. Once it's done, you'll be redirected to the login page.
```
I waited overnight, sync never finishes. When I look closer, it appears to have never started. 

In Trilium Notes on the client system, I have a 'Sync' button with a count of 57,276 in the top bar. When I hit that button, I receive the following error message:

```
Sync failed: Request to PUT 
https://domain.com/api/sync
```
On the server, my `/root/trilium-data/log/*.log` files record GET and POST requests, but only one PUT:
[trilium-2019-01-29.log](https://github.com/zadam/trilium/files/2808690/trilium-2019-01-29.log)

The client system is running Trilium Notes version 0.28.3 on macOS, and it's log file (`~/Library/Application\ Support/trilium-data/log/trilium-2019-01-29.log`) contains this repeating error:
```
10:53:02.909 INFO  ERROR: Failed to deserialize sync response: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

10:53:02.910 INFO  sync failed: Request to PUT https://domain.com/api/sync/update failed, error: 413 Request Entity Too Large
```

**Comment by ryansyah** [comment]
Self-Solve!

source: https://www.keycdn.com/support/413-request-entity-too-large

add to nginx config in `server {}` block:
```
  # set to 0 for unlimited. Default is 1M.
  # client_max_body_size 100M;
  client_max_body_size 0;
```

**Comment by ryansyah** [comment]
Maybe want to include this information in the nginx reverse proxy section.

**Comment by ryansyah** [comment]
Seems after making the above changes, I still see some issues when viewing the docker container logs (`docker logs -t --follow trilium_notes`) :

```
2019-01-29T17:12:10.737065608Z { PayloadTooLargeError: request entity too large
2019-01-29T17:12:10.737111511Z     at readStream (/usr/src/app/node_modules/raw-body/index.js:155:17)
2019-01-29T17:12:10.737145341Z     at getRawBody (/usr/src/app/node_modules/raw-body/index.js:108:12)
2019-01-29T17:12:10.737157954Z     at read (/usr/src/app/node_modules/body-parser/lib/read.js:77:3)
2019-01-29T17:12:10.737169469Z     at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:135:5)
2019-01-29T17:12:10.737180866Z     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
2019-01-29T17:12:10.737192291Z     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
2019-01-29T17:12:10.737203607Z     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
2019-01-29T17:12:10.737214797Z     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
2019-01-29T17:12:10.737226195Z     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
2019-01-29T17:12:10.737237489Z     at cls.init (/usr/src/app/src/app.js:38:9)
2019-01-29T17:12:10.737248702Z   message: 'request entity too large',
2019-01-29T17:12:10.737260542Z   expected: 82509192,
2019-01-29T17:12:10.737271880Z   length: 82509192,
2019-01-29T17:12:10.737283152Z   limit: 52428800,
2019-01-29T17:12:10.737294541Z   type: 'entity.too.large' }
```

**Comment by zadam** [comment]
Hello, this is pretty interesting to hear that somebody use Trilium with such number of notes. I tested such large documents only with generated data.

Trilium has limit of 50 MB requests and it looks like one of your notes have 80 MBs. I just raised the limit to 500 MB in master but I'm not sure how will that perform. I guess better solution would be to change sync protocol to split large notes into chunks and send them part by part, but that's not trivial for few reasons.

Since you probably don't want to wait for the next release, there's another way - you can manually copy "document.db" from your client (which has all the notes) to the server using e.g. SCP. I do that quite often for testing since it's quite a bit faster than normal sync. One thing which should be done afterwards is to remove sync settings on the server (copied from client), otherwise server would try to sync with itself.

**Comment by ryansyah** [comment]
@zadam, thanks for the review and feedback. I can confirm that I was able to bootstrap the system by rsyncing document.db to the Trilium Notes server. I have also confirmed that note syncing for larger notes appears to be working as expected in the  0.29.0-beta release.
