### ISSUE TITLE
(Bug report) infinite loop calling 

### ISSUE THREAD

**Issue by soulsands** [zadam/trilium#3950]
### Trilium Version

0.60.0-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 Pro version 22H2

### Description

https://github.com/zadam/trilium/blob/0728f540abe86063603ba0f146bdd02e616e1e6c/src/public/app/entities/fnote.js#LL312C1-L331C6

This method causes an infinite loop resulting in the failure of many functions, e.g. search, options. It can be fixed by reverting it to the previous version.

### Error logs

![image](https://github.com/zadam/trilium/assets/32272399/63a9a0d2-20d7-4bca-af76-01905855c417)

**Comment by Nriver** [comment]
The Quick search feature is functioning properly. I will utilize it as a temporary solution until a fixed version is released.

**Comment by soulsands** [comment]
> The Quick search feature is functioning properly. I will utilize it as a temporary solution until a fixed version is released.

I have made modifications and built it on my own. If you want to build it too, please note that you need to modify the version, because the current resources have been cached persistently. If the version is the same as before, you need to force a refresh(shift+f5).
