### ISSUE TITLE
(Bug report) Single grid is stretched in book note and first image dosen't appear as cover

### ISSUE THREAD

**Issue by arromattic** [zadam/trilium#3965]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windoes 10 version 21H2

### Description

I am using the trilium webclipper to save website with screenshot as bookmarks 
1. when ever a row has two or one book item the image is streched like this
![trilium book note image a](https://github.com/zadam/trilium/assets/133383364/c13acf5a-ba5c-4fd7-9930-6b8ac030617b)

but the problem dosen't happen when you have three item like this 
![trilium book note image b](https://github.com/zadam/trilium/assets/133383364/e2add999-d844-4f48-909c-2db5aa6ca126)

2. The first image should appear shrinked instead of a corner of image appearing as cover of the grid card which is extremely useful for visually saving a websites screenshot .
3. image is drowned when there are text before the image so add the first image as cover

**Comment by arromattic** [comment]
the image in the clipperbox appears like this 
![trilium book note image b](https://github.com/zadam/trilium/assets/133383364/aedd9711-7cf4-40a2-91eb-7115c549e160)
this is how it appears in appears in tagspaces 
![tagspaces bookmark](https://github.com/zadam/trilium/assets/133383364/c26ffae0-49d2-42fa-8f03-e563155c45ba)
the whole image should shrink and appear like this

**Comment by zadam** [comment]
Hello, the images should now fit into the visible box.

> image is drowned when there are text before the image so add the first image as cover

The content is displayed as it is.

**Comment by arromattic** [comment]
Thanks.
