### ISSUE TITLE
(Bug report) Right clicking external link in `readOnly` mode opens link

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#3971]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

Currently when right-clicking on an external link while in `readOnly` mode, the link is opened in addition to the right-click context menu being opened. 

Ideally only the context menu would be opened since we can regular (left-click) the link to open it.

**Comment by zadam** [comment]
Thx for reporting, fixes.
