### ISSUE TITLE
(Feature request)  Quick jump of highlighted text in text notes

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#3973]
### Describe feature

 I found that Trillium lacks the bookmark function within the notes. For a long article, it may not be convenient to jump to the key points in the article. However, highlighted text can be used as a bookmark to facilitate quick jumps within the notes 
![图片](https://github.com/zadam/trilium/assets/37627919/5b8cd1e0-e24b-4c4f-b088-cc175fabb415)

**Comment by Nriver** [comment]
Sounds like a good idea.

**Comment by zadam** [comment]
That sounds neat and the way it's presented well too. The implementation might be similar to TOC as well.

It looks like you're already working on this?

**Comment by SiriusXT** [comment]
I currently have some simple experiments. Ok, I will continue to improve this feature
