### ISSUE TITLE
(Bug report) Tab row breaks when the main split is empty

### ISSUE THREAD

**Issue by dymani** [zadam/trilium#3985]
### Trilium Version

0.60.1-beta

### What operating system are you using?

Other (specify below)

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 version 22H2 with WSL2 Ubuntu 20.04

### Description

This bug can be reproduced as follows:

1. Open a new tab
2. Create a new split
3. Open any note on the new split, while keeping the main split as an empty pane
4. Refresh, and the tab row will break

![2023-05-31_02-15-36](https://github.com/zadam/trilium/assets/10493889/fd63a273-7a1a-4661-8d0a-712d65ebc2fd)

The error can be mitigated by switching to mobile version and back to desktop version.

### Possible cause
Upon refreshing, the program will not create a tab for any empty note, which is a main context in this case, resulting in orphan subcontexts.

**Comment by zadam** [comment]
Hello, thank you for reporting this bug, fixed.
