### ISSUE TITLE
(Bug report) Inherited attributes not populated for ETAPI when note is cloned

### ISSUE THREAD

**Issue by mm21** [zadam/trilium#3994]
### Trilium Version

v0.60.1-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 22.04 LTS

### Description

This is very similar to #3989, but only occurs when the child note is initially created under another note (say root) and then cloned to a parent note with an inheritable attribute.

Steps to reproduce:

1. Create a note under root (call it "parent note")
2. Create an inheritable attribute for parent note
3. Create another note under root (call it "child note")
4. Create an attribute for child note (optional)
5. Clone child note to parent note
6. Check attributes of child note
a. Doesn't contain parent note's attribute, but workaround from #3989 still applies - creating/deleting a dummy attribute for child causes parent's attribute to show

**Comment by zadam** [comment]
Hi, I appreciate you testing and reporting these bugs - it's important to get these ironed out.

Should be fixed now.
