### ISSUE TITLE
(Feature request) Better size format

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3996]
### Describe feature

There are three places shows the size of notes.

1. `Note size` under `Note Info` tab. It shows the size in `KiB` and `MiB`.
![1](https://github.com/zadam/trilium/assets/6752679/0d86f5d5-5589-48ef-82e7-ed9fa12a3288)

2. `File size` of `File` notes. It shows the size in `bytes`.
![2](https://github.com/zadam/trilium/assets/6752679/cdbe0546-3d81-47fe-ba7d-872e30904ced)

3. `Largest notes` in the demo `Statistics` note. It shows the size in `bytes`.
![3](https://github.com/zadam/trilium/assets/6752679/148888a1-6e7e-4d3b-8626-b2c5e0ec01b9)

There are two minor problem here. The units are not uniformed and the numbers in bytes is not quite user-friendly.

**Comment by Nriver** [comment]
I've made some change to the code. Here is the pr https://github.com/zadam/trilium/pull/3997

This is what it looks like after the code applied.
![4](https://github.com/zadam/trilium/assets/6752679/4946c4e0-2e93-4ffe-a390-21c6e578dd74)

![5](https://github.com/zadam/trilium/assets/6752679/5a826426-5e96-4da1-841d-4edb224e6d2a)

![6](https://github.com/zadam/trilium/assets/6752679/31307e90-bd2a-48c8-921c-cf077dfb135a)

The demo note is not in the source code, so I can not change it. You can take my code from [here](https://github.com/Nriver/trilium-translation/blob/main/demo-cn/%E7%A4%BA%E4%BE%8B%E7%AC%94%E8%AE%B0%20-%20%E8%AF%B7%E4%B8%8D%E8%A6%81%E5%88%A0%E9%99%A4/Trilium%20%E6%89%A9%E5%B1%95/%E7%BB%9F%E8%AE%A1/%E7%AC%94%E8%AE%B0%E5%A4%A7%E5%B0%8F/template/js.js).

**Comment by zadam** [comment]
added to file_properties: https://github.com/zadam/trilium/commit/7e71029d1ccde2a16a3ab9ed073c2e9872f73999

**Comment by Nriver** [comment]
Thanks!
