### ISSUE TITLE
Can no longer drag/drop multiple notes at once (v 0.29 beta)

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#400]
**Steps to Re-create (in version 29 beta):**
1. Create folders TEST1 and TEST2
2. Create notes A, B and C under folder TEST1
3. Hold the ctrl key and click notes B and C (so that they are both selected)
4. Then, left click and drag (either note B or C) and drop them under folder TEST2

**Expected:** Both notes B and C should get moved since they were multi-selected with ctrl + click

**Actual:** Only note B or C gets moved (depending on which one you left clicked on when dragging)

NOTE: There was previously a different issue where in this scenario, if you had previously selected Note A (e.g. if that was the note you were currently looking at) and then used ctrl + click to select notes B and C and move notes B and C, note A would end up getting inadvertently moved as well (#394, #375). This is now fixed in v29, but the fix seems to have caused this issue where you can no longer move multiple notes at all

**Comment by zadam** [comment]
Hello, since 0.29 it's necessary to hold CTRL during the multi-note dragging (not only for multi selection, but also during the actual drag & drop). 

This is the only solution I could come with to fix mentioned issues #394, #375. I know it's not ideal. I might take a second look at it.

**Comment by bwat47** [comment]
Ah, thanks I didn't think to try that. If I hold ctrl it does work as you mentioned :)
