### ISSUE TITLE
Font size - Cyrillic (Bug report) 

### ISSUE THREAD

**Issue by Doublemyst** [zadam/trilium#4003]
### Trilium Version

0.59.4

### What operating system are you using?

Other (specify below)

### What is your setup?

Local (no sync)

### Operating System Version

Docker

### Description

When using the bold text in cyrillic, the font size from "default sized bold" text is much smaller than the regular "default" text. 
![grafik](https://github.com/zadam/trilium/assets/40290451/044d8757-7c9f-4c26-8e62-e47a0dc668ba)

Left part is regular text, right part was in bold.

**Comment by zadam** [comment]
Hello, this was fixed recently in #3933 and was release in 0.60 (currently in beta).
