### ISSUE TITLE
Error: Router not found for request desktop.js

### ISSUE THREAD

**Issue by Fogest** [zadam/trilium#4006]
### Trilium Version

0.59.4

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 20.04.5 LTS

### Description

I have upgraded from an older Trilium version to the current stable git branch ("0.59.4"). I am now unable to access the notes from the web. Weirdly enough though, I have no problem syncing and accessing my notes via the Windows desktop client after the update. It's only via the web browser where I can no longer access Trilium. 

I am able to login on the browser, but as soon as I login I get a blank screen with an error in the logs stating the following:

```
Error: Router not found for request /assets/v0.59.4/app-dist/desktop.js
    at /opt/trilium/src/app.js:94:17
    at Layer.handle [as handle_request] (/opt/trilium/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/trilium/node_modules/express/lib/router/index.js:328:13)
    at /opt/trilium/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/trilium/node_modules/express/lib/router/index.js:346:12)
    at next (/opt/trilium/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/opt/trilium/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/opt/trilium/node_modules/express/lib/router/index.js:328:13)
    at /opt/trilium/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/opt/trilium/node_modules/express/lib/router/index.js:346:12) {
  status: 404
}
```

I had pulled a totally clean copy of Trilium and ran the `npm install` and `npm rebuild` commands as the installation guide indicated. Unsure what is the issue here. 

### Error logs

Chrome's console shows essentially the same thing as the server console error logs. Just that it got a 404 error. 

![image](https://github.com/zadam/trilium/assets/1163628/25a42690-183a-4a81-8552-6fde6375bac6)

**Comment by zadam** [comment]
Running trilium directly from git clone is not well supported and the instructions are out of date (which is also indicated). It's recommended to run one of the published builds.

Having said that, it looks like the webpack build is missing so you might try `npm run webpack`

**Comment by Fogest** [comment]
Thanks, that was the command needed to resolve the issue. I agree that I should at some point switch to the docker version. When I originally setup Trilium I believe I had some kind of issue with the docker setup but I am sure I could get that resolved now. Thanks for the help, closing this.
