### ISSUE TITLE
(Bug report) List of bugs

### ISSUE THREAD

**Issue by dimidir** [zadam/trilium#4024]
### Trilium Version

0.59.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Server: Ubuntu 18.04, Client: Kubuntu 22.04

### Description

I'm not quite sure If I put in the right format but here is a list of Bugs that I gathered couple of months of use. There were more that I didn't bother to note down though.

- Table of contents just appears after a note is large enough? (a toggle switch with auto/default settings)
- Sometimes drag&dropping folders in the left panel doesn't work (anymore), need to restart the app. (F5 doesn't work)
- On Copy&Paste plain text (Ctrl+shift+v) into preformatted empty text field (just bullet point without text yet) bullet point gets erased and text is inserted as blank paragraph (one has to type some characters into that bullet point first, then is able to paste it into the bullet point.)
- Can't bookmark to a note on mobile properly (doesn't open it directly) 
- When the cursor is at the beginning of a header and you press Enter to create rows(more space to content above), the new rows are keeping the heading format instead of just being neutral paragraph rows
- “Remove Formatting” does not remove bullet points listing
- Webclipper screenshots get cut and show not the chosen area + bad quality
- In Code block: SHIFT+TAB does not reverse indent (seems fixed)
- toc stops showing the last headings once a limit of headings is reached in the linux app. 
-- In browser one can see the whole toc tree but clicking on a heading does not navigate correctly to it. It navigates off several headings. 
- Cannot internal Link to a note (grabbed website) that is in Trillium/Journal/YYYY/DATE

Sorry and correct me if I got in a wrong format or so.

**Comment by dimidir** [comment]
Yea the min headings before appearance was one of the early ones indeed and quite trivial.
Just realised reloading lets the toc pane reappear anyways, as well. So this one is off the list. 
Thanks anyway!

**Comment by Nriver** [comment]
> Sometimes drag&dropping folders in the left panel doesn't work (anymore), need to restart the app. (F5 doesn't work)

Ctrl + shift + i , see if there is a console error message.

> On Copy&Paste plain text (Ctrl+shift+v) into preformatted empty text field (just bullet point without text yet) bullet point gets erased and text is inserted as blank paragraph (one has to type some characters into that bullet point first, then is able to paste it into the bullet point.)

Works fine for me.

![paste](https://github.com/zadam/trilium/assets/6752679/81881cda-513a-4cff-bc1d-3df003b56b60)

> Can't bookmark to a note on mobile properly (doesn't open it directly)

Works fine for me. You can try use another browser app and clean the cache.

> When the cursor is at the beginning of a header and you press Enter to create rows(more space to content above), the new rows are keeping the heading format instead of just being neutral paragraph rows

This one may be not related to Trilium, should be a behavior of CKEditor. May be you should ask them.

> “Remove Formatting” does not remove bullet points listing

It's not text format, it belongs to paragraph. You need to remove it in the paragraph symbol, ¶.

> Cannot internal Link to a note (grabbed website) that is in Trillium/Journal/YYYY/DATE

Right click the note in the note tree and hit `Copy/Clone`. You should be able to paste the link in note now.

**Comment by dimidir** [comment]
> > Sometimes drag&dropping folders in the left panel doesn't work (anymore), need to restart the app. (F5 doesn't work)
> 
> Ctrl + shift + i , see if there is a console error message.
Maybe fixed.


> > On Copy&Paste plain text (Ctrl+shift+v) into preformatted empty text field (just bullet point without text yet) bullet point gets erased and text is inserted as blank paragraph (one has to type some characters into that bullet point first, then is able to paste it into the bullet point.)
> 
> Works fine for me.
Works now better than expected too. Remains though with different formats in the cliboard being pasted. But I cannot help but mention that I have to do that work around with text already being written into the bullet point to accept plain text via ctrl+shift+v.

> > Can't bookmark to a note on mobile properly (doesn't open it directly)
> 
> Works fine for me. You can try use another browser app and clean the cache.
Didnt work out with Brave Browser indeed. Worked in chrome though..

> > “Remove Formatting” does not remove bullet points listing
> 
> It's not text format, it belongs to paragraph. You need to remove it in the paragraph symbol, ¶.
Makes sense. Perception was the feature does things differently then.

> > Cannot internal Link to a note (grabbed website) that is in Trillium/Journal/YYYY/DATE
> 
> Right click the note in the note tree and hit `Copy/Clone`. You should be able to paste the link in note now.
Sure is it possible to link directly to a paragrph or heading? Like in https://github.com/zadam/trilium/wiki/Links#external-links is pointing at #external-links heading.
