### ISSUE TITLE
Race condition in SQL console (save changes vs execute query)

### ISSUE THREAD

**Issue by mechanarchy** [zadam/trilium#4028]
### Trilium Version

0.59.4

### What operating system are you using?

macOS

### What is your setup?

Server access only

### Operating System Version

macOS Monterey 12.6.3

### Description

A race condition exists in the SQL console, between changes being pushed to the backend, and the request for a query to be executed.

This mostly happens when I am actively modifying the query and then quickly press Ctrl+Enter. In the screenshots below, I:
1. Enter the query `SELECT ''` and wait for the note to be saved
2. Quickly type `asd` into the single quotes, and then quickly press Ctrl+Enter
3. See that the result of the SQL query is `''` and not `'asd'` as expected.

Looking at the request timeline in developer tools, it is clear the race condition is present:
<img width="524" alt="image" src="https://github.com/zadam/trilium/assets/1166756/51e9b442-a0c8-4028-894e-27c2308f9093">
<img width="591" alt="image" src="https://github.com/zadam/trilium/assets/1166756/6a2b4227-e7dd-4ef0-b64d-2982b8c36472">
<img width="442" alt="image" src="https://github.com/zadam/trilium/assets/1166756/3d01f7f6-e446-44ca-80a1-d4882218ec8c">

**Comment by mechanarchy** [comment]
A quick look at the code suggests the `Entrypoints:runActiveNoteCommand` function is where a change should be made:
https://github.com/zadam/trilium/blob/6f16b4caeca3073de17527d3ebcf0283a1782464/src/public/app/components/entrypoints.js#L170-L173

By forcing another save using a command like this:
https://github.com/zadam/trilium/blob/6f16b4caeca3073de17527d3ebcf0283a1782464/src/public/app/widgets/note_detail.js#L86

But I'm not sure about the cleanest way of doing it.

**Comment by zadam** [comment]
fixed
