### ISSUE TITLE
Search for shared notes

### ISSUE THREAD

**Issue by mechanarchy** [zadam/trilium#4033]
Trilium 0.60.3 web

Is it possible to search for root-shared notes? ie not descendents of shared notes, just those that have the "Share" toggle turned on. Looking at the [Search wiki page](https://github.com/zadam/trilium/wiki/Search) and the project source, it seems like this syntax should work: `note.parents.noteId=_share` but nothing is returned. 

For the time being I've made this raw SQL query, but it's not as easy to work with in the backend API.
```sql
SELECT notes.*
FROM notes
INNER JOIN branches
ON notes.noteId = branches.noteId
WHERE branches.parentNoteId = '_root';
```

**Comment by zadam** [comment]
Hmm, searching for \`note.parents.noteId=\_share\` does work for me.

Also you can see all of them here: 

![](https://github.com/zadam/trilium/assets/617641/657fb63c-329a-41a0-8360-48f301ec3dcb)

**Comment by mechanarchy** [comment]
Yep, you're totally right, `note.parents.noteId=_share` does work.

Comparing a brand new search with the one in my search history, I had removed the 'ancestor' constraint and so I guess it defaulted to searching just the 'Search History' subtree, or the root tree but not hidden notes.
