### ISSUE TITLE
(Bug report) Arrow keys navigation not working in note tree

### ISSUE THREAD

**Issue by dymani** [zadam/trilium#4036]
### Trilium Version

0.60.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 22H2

### Description

In the older versions (v0.59.4 or before), when the note tree is in focus (e.g. after pressing Ctrl + period), pressing Up/Down keys can activate the previous or the next note, and pressing Left/Right keys can expand or collapse a parent note.

Starting from v0.60.0-beta onwards, we cannot use arrow keys to navigate the tree anymore. Instead, the whole tree will scroll when Up/Down keys are pressed.

**Comment by zadam** [comment]
Strange, this continues to work for me. There's one exception with Canvas note which keeps stealing focus on activation, but apart from this, it should work.

**Comment by zadam** [comment]
Found the problem, will be fixed in the next patch release.
