### ISSUE TITLE
(Bug report) Paste Into Note Keyboard Shortcut No longer Works

### ISSUE THREAD

**Issue by BeatLink** [zadam/trilium#4039]
### Trilium Version

0.60.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linuxt Mint Cinnamon

### Description

When attempting to use Ctrl+V to paste/clone a note into another note, nothing happens. One must use the context menu option to paste the note. The change seems to have occured recently. I will attempt a rollback to a previous version to see if that resolves the issue

**Comment by BeatLink** [comment]
The issue is solved once Trilium is rolled back to version 0.59.4 so there must have been a regression introduced between 0.60.3 and that one. For the meantime ill be staying on 0.59.4

**Comment by zadam** [comment]
Hi, it should be the same problem causing #4036, will be fixed in the next patch release.
