### ISSUE TITLE
More colors for the highlight option

### ISSUE THREAD

**Issue by RainSharky** [zadam/trilium#4045]
### Describe feature

I would love to have a bigger color palette for the highlight text option. Maybe also some that are less bright (Pastel for example)

### Additional Information

Currently:
<img width="116" alt="image" src="https://github.com/zadam/trilium/assets/125542081/8f6b9eff-3697-482a-8037-8e7f97009c33">

**Comment by SalvyTek** [comment]
@zadam I think this can be closed. Thanks for adding this feature!
