### ISSUE TITLE
(Bug report) Table of Contents Does Not Scroll to the Right Section When Other Notes are Included

### ISSUE THREAD

**Issue by Lolabird** [zadam/trilium#4046]
### Trilium Version

	0.60.4

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint 20.3 Una

### Description

TOC works fine when there are no included notes, but for texts notes that I've inserted other notes into, the anchoring does not seem to be working as well and gets more and more sections behind the further down the document I go. It seems like adding notes is messing with the anchoring. In one of my notes, I noticed that clicking on a link in the TOC actually scrolled to different sections within the inserted note. So the TOC may be anchoring to inserted notes.

**Comment by SiriusXT** [comment]
The bug was fixed in toc.js in pr: [4049](https://github.com/zadam/trilium/pull/4049)
