### ISSUE TITLE
Prevent default ribbon tab activation

### ISSUE THREAD

**Issue by mechanarchy** [zadam/trilium#4047]
### Describe feature

Hi, currently the 'promoted attributes' or 'edited notes' ribbon tabs default to auto-activating/showing themselves when opening a note.

I personally would prefer not to have any tabs open by default - is it possible for this feature to be added either in the base Trilium code, or do you know of a way I could hook into the events with a script note and take care of it myself?

Trilium 0.60.3 web.

**Comment by polaroidkidd** [comment]
glad to see I'm not the only one. I thought this was a bug at first.

**Comment by mechanarchy** [comment]
Fixed in #4151 / a9cdd93cb425fdea97ddef407ceae822e4fe60eb
