### ISSUE TITLE
(Bug report) Jump to note unexpectedly jumps to a parent note

### ISSUE THREAD

**Issue by eliandoran** [zadam/trilium#4054]
### Trilium Version

0.60.3, latest `master`

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

NixOS 23.05.20230616.a088f2e (Stoat)

### Issue description 

Looking for “nixos configuration” in "Jump to note" results in the following:

```
Knowledge Base / Information Technology / GNU/Linux / Distributions / NixOS / Configuration / Hardware configuration / Configuration / NixOS
```

But clicking on it actually goes to:

```
Knowledge Base / Information Technology / GNU/Linux / Distributions / NixOS
```

There is no "Configuration / NixOS" in "Hardware configuration".

### Partial analysis of the issue

Was able to reproduce the issue in a lightly anononymised database as well.

Looking in the branches table:

```
root
	czLehkFDdyxD
		h6LyfLo54AAT
			yRQeEQbsC6La
				EQ0IcMufRZwZ
					xUd8HpmufWbM
						IOnMuYPIGfBk
							pRROaDuQ0tlF						
		94Rb7FAdHlc1
			yRQeEQbsC6La
```

A diagram taking into consideration the hierarchy in the branches table (black arrows) and the path taken by the autocompletion (darker red).

![image](https://github.com/zadam/trilium/assets/21236836/9c1bff31-ff1f-4fd9-acec-1bec450c0403)

It seems that the search “jumps back” two notes in hierarchy for no apparent reason. There is no direct branch between pRROaDuQ0tlF and xUd8HpmufWbM.

The issue seems to be introduced in a1d4e062ed2e06800d93f5f2a2de90e16af41cc0 or 7aa26580ba8b0efb2687343f5ed00ab070fb6278.

Digging deeper, in `note_flat_text.js` there is a `searchDownThePath` method, the path is wrong from there:

```
rel  xUd8HpmufWbM -> [
  'root',
  'czLehkFDdyxD',
  'h6LyfLo54AAT',
  'yRQeEQbsC6La',
  'EQ0IcMufRZwZ',
  'xUd8HpmufWbM',
  'IOnMuYPIGfBk',
  'pRROaDuQ0tlF',
  'IOnMuYPIGfBk',
  'xUd8HpmufWbM'
]
```

The issue seems to stem from `note_flat_text.js` where the `closestNoteBestNotePath` and `path.slice(1)` are calculated:

```js
return [...closestNoteBestNotePath, ...path.slice(1) ];
```

This results in:

```
getNotePath EQ0IcMufRZwZ [ 'pRROaDuQ0tlF', 'IOnMuYPIGfBk', 'xUd8HpmufWbM' ]
getBestNotePath pRROaDuQ0tlF [
  'root',
  'czLehkFDdyxD',
  'h6LyfLo54AAT',
  'yRQeEQbsC6La',
  'EQ0IcMufRZwZ',
  'xUd8HpmufWbM',
  'IOnMuYPIGfBk',
  'pRROaDuQ0tlF'
]
         closestNoteBestNotePath= [
  'root',
  'czLehkFDdyxD',
  'h6LyfLo54AAT',
  'yRQeEQbsC6La',
  'EQ0IcMufRZwZ',
  'xUd8HpmufWbM',
  'IOnMuYPIGfBk',
  'pRROaDuQ0tlF'
]
         path= [ 'pRROaDuQ0tlF', 'IOnMuYPIGfBk', 'xUd8HpmufWbM' ]
         merged= [
  'root',
  'czLehkFDdyxD',
  'h6LyfLo54AAT',
  'yRQeEQbsC6La',
  'EQ0IcMufRZwZ',
  'xUd8HpmufWbM',
  'IOnMuYPIGfBk',
  'pRROaDuQ0tlF',
  'IOnMuYPIGfBk',
  'xUd8HpmufWbM'
]
```

Not exactly sure what the solution would be; either `closestNoteBestNotePath` is not calculated correctly or we shouldn't append the rest of the path if they are already contained.

**Comment by eliandoran** [comment]
I'll provide the lightly anonymized DB if needed, but it's slightly large at around 500mb.

**Comment by zadam** [comment]
Hi, thanks for the bug report. I wasn't able to reproduce the exact behavior, but reading the code I can see where things went wrong. I think I got it fixed.

**Comment by eliandoran** [comment]
@zadam , just tested the commit and works great! :)
