### ISSUE TITLE
customRequestHandler broken with 0.60.4

### ISSUE THREAD

**Issue by TheOneValen** [zadam/trilium#4067]
### Trilium Version

0.60.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

debian11

### Description

Before installing 0.60.4 (I was on antoher 0.59.x version, don't remember exactly but can check) this worked, now it does not anymore:

I defined a custom request handler `#customRequestHandler=xbs-lastUpdated `
I made a (GET) request do `trilium_url.../xbs-lastUpdated/<somepath>` and could extract `<somepath>` and run my logic.

Now I get an error, that there is no handler for `trilium_url.../xbs-lastUpdated/<somepath>`. 

I could not find any change to the request handler in the changelog.

Defining explicid e.g. `xbs-lastUpdated/path1` seems to work, but would need work to rewrite the structure of my implementation. Is this a planned change?

**Comment by soulsands** [comment]
Hi, you can use `#customRequestHandler=xbs-lastUpdated/.+` to match the path. 
The RegExp matching was changed in this pr https://github.com/zadam/trilium/pull/3866/files.

**Comment by TheOneValen** [comment]
That looks like a clean solution. Thanks!
