### ISSUE TITLE
(Bug report) Exporting Backend Log results in zero byte file

### ISSUE THREAD

**Issue by jwhonce** [zadam/trilium#4076]
### Trilium Version

0.60.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora 38

### Description

Select `Menu->Advanced->Show Backend Log` 
then note menu `Export note`, selecting  `this note and all its descendants.HTML in ZIP archive`
then `Export`

The file `Backend Log.zip`  was created but `Backend Log.dat` is zero bytes in length.

I am not sure if  this is a menu error, ie should export be grayed out? Or is should the missing contents be exported?

I was able to "export" the logs using copy & paste.

/jwh

**Comment by jwhonce** [comment]
[trilium-2023-07-02.log](https://github.com/zadam/trilium/files/11931602/trilium-2023-07-02.log)

**Comment by zadam** [comment]
Backend Log is not a normal note and there isn't a special handling just for this to be exported and I'm not sure if it's worth doing this when a CTRL-C is available as a workaround. ..

**Comment by jwhonce** [comment]
Maybe grey out the menu option? `Search in Note` and `Note source` are already greyed out.

**Comment by zadam** [comment]
Fixed specifically for backend log. I don't really want to handle all these special notes individually since it might get complex for a small benefit, but it's true that the export specifically for backend log note is a natural action, so I'm handling this one.
