### ISSUE TITLE
frontend is reset after note go protected mode

### ISSUE THREAD

**Issue by Archibaldium** [zadam/trilium#4079]
Hello,

So my little problem is that I have some css code in trilium but each time the note goes in protected mode because I didn't interact with it it reset. When i type back my password, the css style is not active anymore and I need to reload the frontend.

css before going protected:
![image](https://github.com/zadam/trilium/assets/63864082/f3ddc2b8-36b8-4ae7-abbe-8e3fe3810a10)

css before protected:
![image](https://github.com/zadam/trilium/assets/63864082/a7b1b4eb-ea26-45f1-877f-9785a00fc7a6)

I'm using trilium 0.60.4 as a web app thanks to trilium.cc.
Is this normal? idk if it was so I didn't tag this as bug.
Can anyone help me fix it if possible?
Thanks in advance.

**Comment by zadam** [comment]
Is the CSS itself protected? That would explain it - the protected session would have to be already active at the time the CSS (with trilium itself) is being loaded. The simplest way to fix it would be to unprotect the CSS note.

**Comment by Archibaldium** [comment]
Yes it is. I'll unprotect it to see.
Thank you.

**Comment by Archibaldium** [comment]
I did what you said and now it's good.
Thank you.
