### ISSUE TITLE
(Bug report) RenderNotes Refuse to Connect

### ISSUE THREAD

**Issue by Dwindle2234** [zadam/trilium#4088]
### Trilium Version

0.60.4

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Chromebook / Chrome

### Description

Is this a bug or my setup?  A basic render note does render briefly but then 'refuses to connect'.  This is on a Chromebook - not tried anywhere else....

Video demos it:
[Screen recording 2023-07-09 20.46.51.webm](https://github.com/zadam/trilium/assets/120342689/05903b27-e1da-4da9-8c3f-5a4fb7b0ede6)

Any advice appreciated.

**Comment by zadam** [comment]
It's quite normal that websites try to prevent their display within iframes, possibly this is a manifestation of that?

**Comment by Dwindle2234** [comment]
Thanks Zadam. I started with generated iframe code by Granfana (self hosted!) not working  so then tried the BBC site.  I have seen render pages nicely working (e.g. Home Assistant dashboard) so your theory of the source site blocking is solid.

Closing.

Cheers.
