### ISSUE TITLE
Table of contents not shown

### ISSUE THREAD

**Issue by NeiBaf79** [zadam/trilium#4089]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 22H2

### Description

The table of contents only appears when several lines are skipped, as shown in the screenshots below.

![image](https://github.com/zadam/trilium/assets/43474458/367cf161-527f-4a83-b177-18726a306ebc)

![image](https://github.com/zadam/trilium/assets/43474458/3abed7a6-6df9-4737-91e1-cfed72850e19)

**Comment by hewo** [comment]
You can set the minimal number of headings in your settings. Did you do that?

Options  Text Notes: 

![grafik](https://github.com/zadam/trilium/assets/602028/042f4b4e-5436-4324-9f5c-5e9877cfb978)


 So, this is probably not a bug.

**Comment by NeiBaf79** [comment]
Hi !

Thank you for your answer. You are right, it's not a bug, i'm just blind...

**Comment by mechanarchy** [comment]
Note that you can also use the `#toc` [attribute](https://github.com/zadam/trilium/wiki/Attributes) to force the table of contents on or off on a per-note basis.
