### ISSUE TITLE
(Feature Request) Use MathQuill for editing equations

### ISSUE THREAD

**Issue by Nyxiad** [zadam/trilium#4091]
### Describe feature

Website: [MathQuill](http://mathquill.com/)
GitHub: [Source Code](https://github.com/mathquill/mathquill)

MathQuill makes it more intuitive to create/edit LaTeX equations. To try it out, you can check out the demo on their website or go to [Desmos](https://www.desmos.com/calculator) since it uses MathQuill as well.

**Comment by zadam** [comment]
This would have to be supported by [https://github.com/isaul32/ckeditor5-math](https://github.com/isaul32/ckeditor5-math) or some other plugin.

Even in that case I plan to support only one way to enter math/LaTeX. If the community agrees on MathQuill and there's support for that in CKEditor, then it would be possible to switch.
