### ISSUE TITLE
(Feature request) Change the order of widgets

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4092]
### Describe feature

How can I adjust the order of custom widgets? Also, can I reorder the sidebar TOC widget?
![00AC3A40-10B9-47A5-AEF2-1E8FBF7FC604](https://github.com/zadam/trilium/assets/33273040/5f6e5619-0777-4a34-9d8e-6b7ae2869eda)

**Comment by zadam** [comment]
It's possible to order custom widgets by defining the position like this:

```javascript
class WordCountWidget extends api.NoteContextAwareWidget {
    get position() { return 100; } // higher value means position towards the bottom/right
    
    ...
}
```
