### ISSUE TITLE
(Bug report) / (Feature) - Shared Notes Include Branch Prefix

### ISSUE THREAD

**Issue by Dwindle2234** [zadam/trilium#4096]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Browser

### Description

When sharing out notes to URLs, the titles/links to notes (on the left hand side) don't include any branch prefix that may have been set in that subtree don't propagate.  It would be really nice if they did - and also be displayed as a title when you click on them.

**Comment by zadam** [comment]
Hi, you're right, it's an omission. Will be fixed in 0.61
