### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by Dwindle2234** [zadam/trilium#4097]
### Trilium Version

0.60.4

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Browser

### Description

When sharing out cloned notes I lose the "*" icon in favour of the network icon.
(
![image](https://github.com/zadam/trilium/assets/120342689/0df04e8c-6acd-4b56-9265-840d5f240879)
).

Unsharing brings back the "*".  Could we have both shown against titles to notes in the notes tree?

**Comment by zadam** [comment]
fixed, will be in 0.61
