### ISSUE TITLE
(Feature request) There's no "Insert paragraph after block" button under codeblock.

### ISSUE THREAD

**Issue by Anuranj-Krishnan** [zadam/trilium#4102]
### Describe feature

There's no 'Insert paragraph after block' button under the code block (with this symbol ->⏎). It seems to be available for images but not for code blocks. Please add it."

**Comment by zadam** [comment]
This is a builtin functionality of CKEditor, so there's not much I can do about it.

@meichthys is correct, expect now you have to hit the enter 3 times :D
