### ISSUE TITLE
(Bug report) Promoted relations not in correct order

### ISSUE THREAD

**Issue by mm21** [zadam/trilium#4105]
### Trilium Version

next61 (f8c9178)

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 22.04 LTS

### Description

The order of promoted relations: 

![image](https://github.com/zadam/trilium/assets/8033134/ba236113-22ef-4cc5-b094-6c1cb80137c2)

Doesn't follow the actual attribute order:

![image](https://github.com/zadam/trilium/assets/8033134/64ad1ac3-d1b9-4303-b5d1-3ba2478fef8f)

~~But promoted labels seem to be ordered fine.~~ This applies to labels too.

**Comment by mm21** [comment]
For some background, these relations are created via ETAPI and can be created out of order, which I think is what's causing this.

**Comment by mm21** [comment]
Did some digging and can confirm that values of promoted attributes are showing in the order in which they're created, not their position, even after restarting frontend and backend. It reproduces in the UI for me as well.

From looking at the code, I think FNote.getOwnedAttributes() is not taking position into account while FNote.getAttributes() is.

**Comment by zadam** [comment]
Actually not even getAttributes() has guaranteed sorting. The position order of attributes is mostly important for UI in a few places and thus the data model does not keep them sorted.

So this fixes it in the promoted attributes UI.

**Comment by mm21** [comment]
Makes sense. Thanks for the background and quick fix!
