### ISSUE TITLE
(Feature request) Add special characters support to trilium

### ISSUE THREAD

**Issue by Onionbai** [zadam/trilium#4119]
### Describe feature

Hi, Zadam, CKEditer now supports special characters, making emoji inserting much convenient. So you have any plan to introduce it into trilium notes?
![image](https://github.com/zadam/trilium/assets/76639100/c0f4716d-1067-4bb7-af78-1da2f6793bc1)

**Comment by Nriver** [comment]
Second to that. It looks great.

**Comment by thanayut1750** [comment]
Press " Win key + [dot] " which opens a emoji picker.

**Comment by Onionbai** [comment]
That's great.

**Comment by zadam** [comment]
I've also added the CKEditor special characters widget.

**Comment by Onionbai** [comment]
![image](https://github.com/zadam/trilium/assets/76639100/dbbf2011-d031-4dcc-8dff-f7b2192875c4)
That's really great, thank you😀
