### ISSUE TITLE
(Feature request) Preview all note content in the note tooltip.

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4120]
### Describe feature

Now, when the mouse hovers over a note link, only a part of the note can be previewed. It would be great if it could display a scrollbar to show all the content of the note. Like this:
![bandicam-2023-07-25-15-34-41-928](https://github.com/zadam/trilium/assets/33273040/0c10e794-42aa-4920-9d0a-ed1e90e960e6)

**Comment by zadam** [comment]
Hi, I reworked the tooltip and it now supports displaying the whole note. Will be in the next 0.61 beta.

**Comment by dvai** [comment]
That would be great，thanks!
