### ISSUE TITLE
(Bug report) Zoom only has two available states when viewing attachments.

### ISSUE THREAD

**Issue by XXXJetfireXXX** [zadam/trilium#4121]
### Trilium Version

0.61.0 beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

Since I can't test the beta right now, I'm not sure if it's fixed yet, but when I tried 0.61 beta several days ago, I discovered that trying to zoom in when viewing an image attachment will instantly go from 'full view' to 'fully zoomed' state, with no intermediate states whatsoever. May be the same for the image notes, can't remember.

**Comment by zadam** [comment]
The library has been updated and the parameter meaning apparently changed. Fixed.
