### ISSUE TITLE
(Bug report)  couldn't load  color picker

### ISSUE THREAD

**Issue by jccur** [zadam/trilium#4126]
### Trilium Version

zadam/trilium:0.60-latest

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

CentOS Linux release 7.5.1804

### Description

![image](https://github.com/zadam/trilium/assets/5088245/6ebd4449-3fa0-4558-9c6b-6da884998e1c)
[Table properties]->[Border] -> color picker cannot be popped up

**Comment by Nriver** [comment]
You need to choose a style first.

**Comment by jccur** [comment]
> You need to choose a style first.

thanks
