### ISSUE TITLE
Tab does not work in text docs

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#413]
Hi

I cant seem to be able to use tab to indent in text notes.  It works in markdown

Create a text note
Start typing
Go back to beginning of a line try to use tab to indent

```
App version:	0.29.1
DB version:	124
Sync version:	4
Build date:	2019-02-12T20:30:07+01:00
```

**Comment by zadam** [comment]
Tab indentation doesn't really exist in HTML (apart from `pre` element) and I don't know any good way to emulate it. Example you created looks like a table so you might want to use that instead.

**Comment by gerroon** [comment]
Ok I did not know that it was a limitation.

**Comment by Mustafa-C** [comment]
Is there any update to this? Could it be possible in any way?

**Comment by zadam** [comment]
I'm not aware of any way to do this ATM.

**Comment by popey456963** [comment]
For a different project we had the following flow (we also did not use `textarea`):

```
function onTabPress() {
    const lineLength = cursor.getCurrentColumn()
    cursor.insert(' ' * (4 - Math.floor(lineLength % 4)))
}
```

Which would align to the next multiple of four with spaces.

**Comment by jaimehrubiks** [comment]
I'm also very interested in this feature

**Comment by gerroon** [comment]
@popey456963

Thanks for the workaround, this seems to be a total improvement!

**Comment by gerroon** [comment]
@zadam, it seems liek the text notes are actually not simple txt files. I can see the issue in that way. Why not also add a purely barebones .txt type that does not employ html?

thanks

**Comment by zadam** [comment]
The code note without type (just click on "code" note type) is actually plain text (MIME text/plain) although it's not easily discoverable ...

**Comment by jetacpp** [comment]
Is it possible to add option to globally map TAB to 4 spaces ? Ability to indent when taking notes is so essential that I may give up TAB for other functionalities such as tabbing tables, etc ...

**Comment by zadam** [comment]
I think it's necessary to distinguish between a traditional TAB key which has quite special behavior and the need for indentation.

I don't think TAB key will ever be supported with it's table-like alignment feature, but there is a standard indent function:

![image](https://user-images.githubusercontent.com/617641/79543807-4fc14900-808e-11ea-9d7f-87b514756a0c.png)

**Comment by gerroon** [comment]
@zadam 

Is it possible to get shotcuts for those indenting functions?

**Comment by zadam** [comment]
@gerroon Yes, would you mind creating an issue for that specifically for better visibility?

**Comment by zadam** [comment]
tab and shift-tab for indent have been added in 0.43.2
