### ISSUE TITLE
(Bug report) Included notes display incorrectly in `readOnly` mode

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#4135]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

If a note is set to `#readOnly` and contains an included note, the included note will be completely expanded regardless of the chosen included note setting:
![image](https://github.com/zadam/trilium/assets/10717998/8b026b69-55aa-4f33-b996-524a94d7e0c1)

Once the edit button is clicked, the included note displays correctly, so it's only when the note is in `#readOnly` mode and is not editable.

**Comment by zadam** [comment]
Thanks for reporting, fixed.
