### ISSUE TITLE
add note android app issue

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#415]
I filed a issue with the android app, but I suspect this is an api issue with the main trilium.  When I use the add note I always get an error saying that "Sending note to Trilium failed" even though it hasn't fialed and the note is correctly added.  This message comes from SendNoteActivity.kt.  I assume this uses to work and send success but now it doesn't even though the activity is success.  Likely there was a change to the API handling in the main app and this could be fixed by fixing the return code sent to the Android app.

**Comment by zadam** [comment]
Hi, you're right API changed slightly. I fixed this and also the image upload should now (or rather with next release) work with existing Android app (no changes there).

**Comment by mayailkour** [comment]
About which Android app are we speaking?

**Comment by zadam** [comment]
https://play.google.com/store/apps/details?id=io.github.zadam.triliumsender
