### ISSUE TITLE
(Bug report) add pdf file note type

### ISSUE THREAD

**Issue by Darvyn** [zadam/trilium#4152]
### Trilium Version

0.61-latest

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

windows / macos chrome

### Description

Hi,

Just started with this project, set up with docker using 0.61-latest version. 
But when I want to add a PDF, I cannot choose the Note Type to file, checked other closed issue, pdf function is already integrated. 

Could you please help to check ? Thanks
![image](https://github.com/zadam/trilium/assets/26133254/7d2da107-5fcd-430f-962c-d6cc963305cf)

**Comment by Nriver** [comment]
just drag and drop pdf to note tree

**Comment by Darvyn** [comment]
@Nriver Thanks, it works ！

> just drag and drop pdf to note tree
