### ISSUE TITLE
(Feature request) Add sharing functionality for attachments.

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4156]
### Describe feature

In the new version(v0.61.3-beta), images exist in the form of attachments, it is a good idea, I really like this. But if I want to share the images in the notes, I have to convert the attachments into notes, which is not what I expected.
 It would be great if attachments could also be shared conveniently.

**Comment by zadam** [comment]
Hi, attachments can't be shared individually, but can be shared as part of the note. e.g. the image in this shared page is an attachment:

![](https://github.com/zadam/trilium/assets/617641/59dc2254-c2c2-4116-9ab5-9a74d3547b17)

**Comment by zadam** [comment]
Hi, attachments can't be shared individually, but can be shared as part of the note. e.g. the image in this shared page is an attachment:

![](https://github.com/zadam/trilium/assets/617641/59dc2254-c2c2-4116-9ab5-9a74d3547b17)
