### ISSUE TITLE
(Bug report) trilium.sh does not start

### ISSUE THREAD

**Issue by HyperCriSiS** [zadam/trilium#4162]
### Trilium Version

v0.60.4

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Raspbian

### Description

Hi,

I just tried installing the server on Raspbian OS.
When I start the sh I get:
./trilium.sh: 2: ./node/bin/node: Exec format error

Did I do something wrong?

Thanks
Hyper

**Comment by zadam** [comment]
The package you downloaded is for AMD64 platform. For ARM there's a docker image available.

**Comment by HyperCriSiS** [comment]
oh, haha, sorry :man_facepalming:
