### ISSUE TITLE
(Feature request) Import images as attachments from Evernote's ENEX file

### ISSUE THREAD

**Issue by coldwinds** [zadam/trilium#4163]
### Describe feature

Hi,

Looks like the [v0.61.1-beta release](https://github.com/zadam/trilium/releases/tag/v0.61.1-beta) has added support for attachments,  but I found that the imported images from ENEX file were created as standalone note like the old way, is it possible to add an option to import images as attachments? I think it would be very helpful for the user migrating from Evernote that they don't need to convert notes to attachments manually if they prefer to use image as attachment.

**Comment by zadam** [comment]
That was an omission, thanks for reporting this issue. Fixed.
