### ISSUE TITLE
(Feature request) Could trilium included full ckeditor features?

### ISSUE THREAD

**Issue by Ivy-End** [zadam/trilium#4166]
### Describe feature

Trilium currently just includes **Ballon block** type ckedior. However, could trilium includes **Classic** type ckeditor or any other types, because **Ballon block** cannot fulfill overall text editing requirement sometimes.

Thanks.

**Comment by YestermorrowONill** [comment]
The full-featured CKEditor requires payment.

**Comment by Ivy-End** [comment]
> The full-featured CKEditor requires payment.

haha, sigh...

**Comment by zadam** [comment]
The classic editor does not require commercial license ...

I'm not sure if it is technically possible to have a CKEditor build containing both Balloon and Classic. However, it is not a direction I want to go in either case.

**Comment by shutaozhenzhen** [comment]
> The full-featured CKEditor requires payment.

I think ckeditor is the worst part in trilium

**Comment by Ivy-End** [comment]
> 

Thanks

**Comment by Ivy-End** [comment]
Thanks very much!

> The classic editor does not require commercial license ...
> 
> I'm not sure if it is technically possible to have a CKEditor build containing both Balloon and Classic. However, it is not a direction I want to go in either case.

**Comment by eliandoran** [comment]
A fixed toolbar was added as part of TriliumNext, if the topic is still of interest. See https://github.com/TriliumNext/Notes/pull/571 for more information.
