### ISSUE TITLE
(Bug report) Code notes cannot create revisions.

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4176]
### Trilium Version

0.61.5beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows11

### Description

Code notes cannot create note revision history (whether automatic or shortcut).

**Comment by zadam** [comment]
Thank you for catching this regression. Fixed.

**Comment by dvai** [comment]
@zadam  Hi, This issue still exists in version 0.61.6beta.

**Comment by zadam** [comment]
Sorry about that, the last fix was mistakenly committed to master and not to the beta branch.
