### ISSUE TITLE
(Bug report) current 0.61-5-beta cannot save-as / load canvas properly

### ISSUE THREAD

**Issue by deajan** [zadam/trilium#4182]
### Trilium Version

0.61.5-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 22H2 x64

### Description

Here's my second excalidraw problem: no way to import previously exported canvas.

I've setup a fresh trilium instance for this one, and created a canvas.
Using the `save as` button, I've created an `.excalidraw` file which I attached to this issue.
When trying to reimport that file, I get `Couldn't load invalid file` as below:

![image](https://github.com/zadam/trilium/assets/4681318/a4d6658f-7250-4d4f-9a1f-b0bc88256cc9)

I've also tried to import that file into official exalidraw and get the same error, so I assume something doesn't work with the export function of Trilium.

[Untitled-2023-08-18-1256.zip](https://github.com/zadam/trilium/files/12378541/Untitled-2023-08-18-1256.zip)

### Error logs

<no relevant logs>

**Comment by zadam** [comment]
If you take a look at the exported file, it has 0 bytes. There's also some permission error in the console. IIRC excalidraw is using some new file API which is unimplemented / blocked in electron.

The way to save canvas files is through trilium's import/export dialog.

**Comment by zadam** [comment]
I've hidden non-working/misleading save buttons ...

**Comment by deajan** [comment]
Thanks, I could indeed export from 0.59-4 and import into 0.61-5-beta now.
