### ISSUE TITLE
(Bug report) TOC-Navigation doesn't work properly when using "include note"  

### ISSUE THREAD

**Issue by Luxing-PP** [zadam/trilium#4189]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows11 22621.2134

### Description

Original
![image](https://github.com/zadam/trilium/assets/56151286/aa2e11b0-afd9-4cfc-bd3d-b26046d299d0)

**After click "4.Title-D"**,jump to an unproper position 
![image](https://github.com/zadam/trilium/assets/56151286/f2a012ad-064c-4ba9-8a22-673a618cee1b)

Due to the scroll of the included note, i guess it navigate to the "Linux"Heading of the included note

### Error logs

No error in log
![image](https://github.com/zadam/trilium/assets/56151286/3cf29126-a29e-44a7-8134-a27492331907)

**Comment by zadam** [comment]
This was already reported in #4046 and fixed in #4049 , the fix is present in 0.61.X.
