### ISSUE TITLE
What if I forget my password?

### ISSUE THREAD

**Issue by callmexss** [zadam/trilium#419]
Hi there, 

Is there a way to recover my notes when I forget my password? Or is there any way to reset the password from the server end? Can I get a unencrypted archive(database file) used for backup?

**Comment by zadam** [comment]
Hello. I assume we're talking about protected/encrypted notes. If you forget your password, then the protected/encrypted notes are lost. That's the point of encryption that you can't read the data without knowing the password ...

**Comment by bwat47** [comment]
You can export all the notes to html files in a tar archive

**Comment by callmexss** [comment]
> Hello. I assume we're talking about protected/encrypted notes. If you forget your password, then the protected/encrypted notes are lost. That's the point of encryption that you can't read the data without knowing the password ...

Thanks for your explanation. I shall keep my password well managed, which is really a tough work QAQ

**Comment by callmexss** [comment]
> You can export all the notes to html files in a tar archive

Thanks for your advice. I find the operation.

**Comment by martinmurciego** [comment]
I am not clear how the password is reset to protect notes. I have the desktop version installed and never sync with the cloud version.

**Comment by zadam** [comment]
@martinmurciego can you clarify your question?

**Comment by dolt131943** [comment]
> You can export all the notes to html files in a tar archive

be carefully,  that would lost some data because I have try export all , and recreate new db and import it, but some data is lost. Version 0.45.10 (0.45.10)

**Comment by dolt131943** [comment]
How can I reset password and I have not encrypt doc , so just reset password . 
I tried export all and create new db and import it , but lost some data.

thanks.

**Comment by zadam** [comment]
There's somewhat complicated process to reset password in here: [https://github.com/zadam/trilium/wiki/Troubleshooting#forgotten-usernamepassword](https://github.com/zadam/trilium/wiki/Troubleshooting#forgotten-usernamepassword)

It's not built into the application since it leads to the loss of protected notes.

Otherwise export & import should not lead to loss of data. I would be interested to see the issues if you have some particular cases to report ...

**Comment by dolt131943** [comment]
> would

thanks, I will try it.

for the data lost in export & import, I will try to reproduced case later.

**Comment by dolt131943** [comment]
> There's somewhat complicated process to reset password in here: https://github.com/zadam/trilium/wiki/Troubleshooting#forgotten-usernamepassword
> 
> It's not built into the application since it leads to the loss of protected notes.
> 
> Otherwise export & import should not lead to loss of data. I would be interested to see the issues if you have some particular cases to report ...

thanks, I will try it.

for the data lost in export & import, I will try to reproduced case later.

**Comment by dolt131943** [comment]
> > There's somewhat complicated process to reset password in here: https://github.com/zadam/trilium/wiki/Troubleshooting#forgotten-usernamepassword
> > It's not built into the application since it leads to the loss of protected notes.
> > Otherwise export & import should not lead to loss of data. I would be interested to see the issues if you have some particular cases to report ...
> 
> thanks, I will try it.
> 
> for the data lost in export & import, I will try to reproduced case later.

hi @zadam ， I have reproduced that issue, and report it at : https://github.com/zadam/trilium/issues/1675

it look like data shown incorrect , I cannot confirm whether the data is lost.

Thanks again for your amazing app .
