### ISSUE TITLE
(Bug report) Automatic scroll while typing fails unless new paragraph created

### ISSUE THREAD

**Issue by copperheadclgp** [zadam/trilium#4195]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Pro 22H2 OS Build 19045.3324

### Description

While typing notes, I have discovered that unless I hit enter to create a new paragraph, the word wrap of the current paragraph will not trigger automatic scrolling to keep text visible. This occurs across multiple Windows 10 endpoints, and goes back at least two releases. The two images below show the behavior observed by the end user. 

![scroll failure](https://github.com/zadam/trilium/assets/51468137/1c2a07e9-f0e9-4ed1-a4ab-5eac8dc66506)
![scroll failure 2](https://github.com/zadam/trilium/assets/51468137/7e7b1470-d0f7-4c28-8aee-12a502ae7960)

**Comment by zadam** [comment]
I just tried with the latest 0.61 beta and the autoscroll seems to work even without new paragraph. It might be because of CKEditor upgrade.

**Comment by copperheadclgp** [comment]
Confirmed - the issue does not occur in 0.61.5-beta.
