### ISSUE TITLE
Will images that originally existed independently be cleaned up, and if so, how to avoid it?

### ISSUE THREAD

**Issue by chncho** [zadam/trilium#4208]
When I reading the wiki : https://github.com/zadam/trilium/wiki/Attachments  , here is some sentense

> Image attachments are expected to be linked in the owning text note. If it's not linked, it will get deleted in a configurable timeout.

So, Will images that originally existed independently be cleaned up, and if so, how to avoid it?

**Comment by rauenzi** [comment]
If you're referring to images that are acting as child notes or independent notes, no I don't believe those will be cleaned up. That text from the wiki is specifically referring to attachment images which are a new feature available only in the beta. Basically, if you attach an image to the note as an attachment, it's expected to be used in the note it was attached to. If you no longer use the image in the note it's assumed to be no longer needed and it'll eventually be cleaned up.

**Comment by zadam** [comment]
@rauenzi is correct. Independent images are not converted into attachments during a migation to 0.61 and only attachments can get cleaned up. In general there should be no data loss / cleanups as a consequence of upgrading to 0.61 alone.

**Comment by chncho** [comment]
thanks a lot
