### ISSUE TITLE
(Feature request) Is there no left-hand option for beta pictures?

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#4215]
### Describe feature

I want my picture to be on the left when I insert a picture in the beta version, but now there seems to be only text surround mode on the left. in the previous version, there was a separate picture on the left. has it been cancelled?
If so, is it possible to add it back in?

**Comment by SiriusXT** [comment]
![图片](https://github.com/zadam/trilium/assets/37627919/61ae2d82-9c45-4b3d-879b-2ff18b002f07)
Is that right?
My version is 61.5.

**Comment by Joackk** [comment]
> ![图片](https://user-images.githubusercontent.com/37627919/264329821-1fc6e9f0-f9ca-43d2-aeaa-33c807d24079.png) Is that right? My version is 61.5.

hi，me too 61.5，The left orientation of this mode will also include text, and the official version of 60 can have separate images placed to the left

**Comment by SiriusXT** [comment]
After testing, it is true that 61.5-beta lacks an option. The picture below is 60.4
![图片](https://github.com/zadam/trilium/assets/37627919/985697ce-0e79-4f0a-baec-959f7b093c1c)

**Comment by Joackk** [comment]
> After testing, it is true that 61.5-beta lacks an option. The picture below is 60.4 ![图片](https://user-images.githubusercontent.com/37627919/264340945-985697ce-0e79-4f0a-baec-959f7b093c1c.png)

That's right, is that why the new version has been removed? Can we add it back

**Comment by zadam** [comment]
Added those options back, there were some renames in recent CKEditor versions:

![](https://github.com/zadam/trilium/assets/617641/bba51d0d-adbe-4b14-a1a0-90cfccbfbbe2)
