### ISSUE TITLE
Web clipper's #clipperInbox tag is invalid

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#4219]
### Trilium Version

0.61.5-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

win11

### Description

Web clipper: v1.0.1
The note from web clipper was placed under the calendar. I remember that before the update, it was placed under the note with the #clipperInbox tag added.

**Comment by sottey** [comment]
I reported this over in the WebCipper repo as I believe this to be an issue over there:

https://github.com/zadam/trilium-web-clipper/issues/56

**Comment by zadam** [comment]
Hi, thanks for the report, will be fixed in the next release.
