### ISSUE TITLE
Please improve the readability in the dark theme

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#422]
Hi

it would be nice if the dark theme has a bit better contrast with some color choices. For instance please see the attached image, as you see the blue in the dark gray is not so much readable, it would be nice if we have better color light contrast with some of these colors choices.

thanks

![trilium_wgsn2rexnt](https://user-images.githubusercontent.com/8519469/53316309-4e97f000-38bf-11e9-9ebd-ae5cddb2372a.png)

**Comment by msbentley** [comment]
Also, when add an image caption in dark mode the text is white on a white background:

![image](https://user-images.githubusercontent.com/1671065/53332198-0266a300-38f3-11e9-8e40-3626f2305a0a.png)

Cheers, Mark

**Comment by gerroon** [comment]
The "blue" is especially looks bad in the settings window, I personally cant read any of the name of the settings tab in dark mode.

**Comment by zadam** [comment]
I changed the link color to lighter blue which should be more contrasty.

Also fixed an issue pointed out by @msbentley
