### ISSUE TITLE
Wrong results when ordered by 2 custom labels

### ISSUE THREAD

**Issue by markbj71** [zadam/trilium#4220]
### Trilium Version

0.61.5-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows j10 21H2

### Description

I just test with 4 notes, with 2 custom lables #year and #month:

- If just order by 1 single label, it works:
![image](https://github.com/zadam/trilium/assets/58618994/71bd60dd-0276-4707-a1d5-aebc7c000a27)

-  if order by 2 labels, the results are wrong:
![image](https://github.com/zadam/trilium/assets/58618994/a0c29ace-59eb-4754-96c6-5de46a8bf179)

Actually if I order by 1 lable and 1 note property like note.dateModified, it doesn't work either.

**Comment by markbj71** [comment]
OK, I found a way to make it working, in the search string, just add spaces both before and after the comma between the 2 labels, then the results are correct:
#year>0 orderby  #year asc , #month desc

I don't see this kind of grammer in the wiki search example, it doesn't have space before the comma:
#author=Tolkien orderBy #publicationDate desc, note.title limit 10

So this still is a small bug?


![image](https://github.com/zadam/trilium/assets/58618994/48c8f3b8-9091-47e2-8cea-98bb621d705a)

**Comment by zadam** [comment]
It is indeed a bug, thanks for reporting, fixed.
