### ISSUE TITLE
(Bug report) TOC problem

### ISSUE THREAD

**Issue by mffan0922** [zadam/trilium#4228]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11, 22H2

### Description

Hi, I start using trilium recently,  with docker server on Debian 12 and client on Windows11. And today I found when I create a TOC with sub-headings which has a quoted format, the last few items would not work properly. For example, as the following picture shows, the last two items would not do when I click on them, just remove `1.1 test` and `1.2 testtest`, all of the toc work fine, even just remove the quoted format will do.

Not sure if it's my setting problem

![image](https://github.com/zadam/trilium/assets/63949101/2dc40281-c157-49d9-897e-324cf2bdef37)

**Comment by zadam** [comment]
Thanks for the report, I can reproduce.

Seems to be caused by the fact we're searching only for headings immediately under root editor element (in the CKEditor data model): https://github.com/zadam/trilium/blob/72b2a6ecb63a4631729549eb8f524cd552170fe3/src/public/app/widgets/toc.js#L242
