### ISSUE TITLE
(Bug report) Router not found for request

### ISSUE THREAD

**Issue by Geekswordsman** [zadam/trilium#4229]
### Trilium Version

0.60.4

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Linux 5.15.0-1032-oracle #38~20.04.1-Ubuntu SMP Thu Mar 23 20:47:35 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Description

Problem occurs on a manual installation on ARM architecture after upgrading from 0.5x.

SSL configured, port 8090, behind nginx reverse proxy using recommended configuration.

Attempting to access the instance results in the following error; this error persists whether attempting to retrieve desktop.js or mobile.js:

```
0|trilium  | Error: Router not found for request /assets/v0.60.4/app-dist/mobile.js
0|trilium  |     at /home/trilium/trilium/src/app.js:105:17
0|trilium  |     at Layer.handle [as handle_request] (/home/trilium/trilium/node_modules/express/lib/router/layer.js:95:5)
0|trilium  |     at trim_prefix (/home/trilium/trilium/node_modules/express/lib/router/index.js:328:13)
0|trilium  |     at /home/trilium/trilium/node_modules/express/lib/router/index.js:286:9
0|trilium  |     at Function.process_params (/home/trilium/trilium/node_modules/express/lib/router/index.js:346:12)
0|trilium  |     at next (/home/trilium/trilium/node_modules/express/lib/router/index.js:280:10)
0|trilium  |     at Layer.handle [as handle_request] (/home/trilium/trilium/node_modules/express/lib/router/layer.js:91:12)
0|trilium  |     at trim_prefix (/home/trilium/trilium/node_modules/express/lib/router/index.js:328:13)
0|trilium  |     at /home/trilium/trilium/node_modules/express/lib/router/index.js:286:9
0|trilium  |     at Function.process_params (/home/trilium/trilium/node_modules/express/lib/router/index.js:346:12) {
0|trilium  |   status: 404
0|trilium  | }
```

### Error logs

09:30:40.724 DB size: 15757 KB
09:30:41.574 Trusted reverse proxy: true
09:30:41.582 App HTTPS server starting up at port 8090
09:30:41.582 {
  "appVersion": "0.60.4",
  "dbVersion": 214,
  "syncVersion": 29,
  "buildDate": "2023-06-19T23:26:50+02:00",
  "buildRevision": "5905950c17791ce0eb278e010c2c8b3450fdb447",
  "dataDirectory": "/home/trilium/trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-09-02T13:30:40.723Z"
}
09:30:41.583 CPU model: Neoverse-N1, logical cores: 4 freq: 0 Mhz
09:30:41.589 Listening on port 8090
09:30:41.645 Becca (note cache) load took 54ms
09:30:45.650 Table counts: notes: 1726, note_revisions: 1933, branches: 1762, attributes: 1879, etapi_tokens: 0
09:30:45.706 All consistency checks passed with no errors detected (took 56ms)
09:30:59.566 Generated CSRF token JDP0VjMo-K8fyMBZJBg8WcCfPXjlM5oZLBOY with secret undefined
09:30:59.749 Error: Router not found for request /assets/v0.60.4/app-dist/mobile.js

**Comment by zadam** [comment]
Try running `npm run webpack`.

**Comment by Geekswordsman** [comment]
That did the trick!

If I might recommend this get added to the troubleshooting section?  It seems such a simple fix for something that can happen during an upgrade!

Thank you so much, I really appreciate it!

**Comment by zadam** [comment]
I've added it to the "Manual server installation", it was missing there previously.
