### ISSUE TITLE
Feature request: search in note title

### ISSUE THREAD

**Issue by msbentley** [zadam/trilium#423]
I'm  not sure if this is covered by https://github.com/zadam/trilium/issues/13 or not, but I often know the title of a note, and would like to find it quickly. Full text search brings up too many hits in this case. Is there a way to do this? Could the title be an attribute, so I could use search by attribute?

Thanks! Mark

**Comment by zadam** [comment]
There's "Jump to note" dialog specifically for this. Press `CTRL-J` and start typing the name ...

**Comment by msbentley** [comment]
D'oh - guess I should RTFM - sorry to bug you!
