### ISSUE TITLE
(Bug report) Frontend API in 0.61 can no longer get a note's creation date

### ISSUE THREAD

**Issue by mabeyj** [zadam/trilium#4232]
### Trilium Version

0.61.5-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 22H2

### Description

Before 0.61, the Frontend API had a `note.getNoteComplement` method which returned an object that included the note's creation date (`dateCreated` and `utcDateCreated`):

```js
await note.getNoteComplement()

{
    "noteId": "vfkW2wl8Mb1l",
    "content": "...",
    "contentLength": 291,
    "dateCreated": "2023-08-20 20:58:58.067-0300",
    "dateModified": "2023-08-20 20:58:58.067-0300",
    "utcDateCreated": "2023-08-20 23:58:58.067Z",
    "utcDateModified": "2023-08-20 23:58:58.067Z",
    "combinedDateModified": "2023-08-20 20:58:58.068-0300",
    "combinedUtcDateModified": "2023-08-20 23:58:58.068Z"
}
```

As of 0.61, `note.getNoteComplement` has been deprecated in favour of `note.getBlob`, both of which return an `FBlob` object. But `FBlob` does not have a creation date.

```js
await note.getBlob()

{
    "blobId": "i60MtR9KeJlB68ftEBin",
    "content": "...",
    "contentLength": 291,
    "dateModified": "2023-08-20 20:58:58.036-0300",
    "utcDateModified": "2023-08-20 23:58:58.036Z"
}
```

There currently doesn't seem to be a (documented) way to obtain a note's creation date using the Frontend API. This breaks a use case where scripts could obtain and use the creation dates of notes (https://github.com/mabeyj/trilium-collection-views/issues/41).

Can `dateCreated` and `utcDateCreated` for notes be made available somewhere in the Frontend API?

**Comment by mabeyj** [comment]
Somewhat related: There's also not an equivalent for the `combinedDateModified` and `combinedUtcDateModified` properties that were included in the Note Complement object.

I believe these were the most recent date of either the note's modified date or the content's modified date. The combined date is shown by the Note Info widget: https://github.com/zadam/trilium/blob/72b2a6ecb63a4631729549eb8f524cd552170fe3/src/public/app/widgets/ribbon_widgets/note_info_widget.js#L130-L132

Scripts can currently only get the blob's modified date which is not necessarily the same. Preferably when showing the date modified, I would want it to be the same one shown under Note Info.

Either `dateModified`/`utcDateModified` of the note itself or `combined(Utc)DateModified` properties would need to be made available as well.

**Comment by zadam** [comment]
Hello, thanks for the report. The FBlob is indeed not a replacement for the previous "notecomplement". I've added a new function `FNote.getMetadata()`, see demo:

![](https://github.com/zadam/trilium/assets/617641/31a80785-40d6-4416-90fd-2fc49a6708b0)

**Comment by zadam** [comment]
> Somewhat related: There's also not an equivalent for the `combinedDateModified` and `combinedUtcDateModified` properties that were included in the Note Complement object.

Indeed, but these "combined" dates are no longer necessary. The note storage approach was redesigned in 0.61, and because of that `note.utcDateCreated` and `note.utcDateModified` reflect both the note properties and the content. This is because now note object contains `blobId` reference. Blobs are immutable (copy on write), so if the content changes, new blobId will be used which will force note update (and therefore change of `utcDateModified`).

**Comment by mabeyj** [comment]
Awesome, thanks!
