### ISSUE TITLE
(Feature request) Consider integrating an AI API to automatically correct errors.

### ISSUE THREAD

**Issue by yaoqiangpersonal** [zadam/trilium#4237]
### Describe feature

Is there a plan to support the open AI interface? UI feels very beautiful, but it's a pity that AI cannot be used to fix errors.

**Comment by zadam** [comment]
Do you mean correct errors in Trilium code or things like spell (fact?) checking within Trilium?

I believe somebody provided some custom script to support ChatGPT. While it would be useful to have such integration in core Trilium, I'm weary of depending on one specific commercial vendor.

**Comment by yaoqiangpersonal** [comment]
> Do you mean correct errors in Trilium code or things like spell (fact?) checking within Trilium?
> 
> I believe somebody provided some custom script to support ChatGPT. While it would be useful to have such integration in core Trilium, I'm hesitant depending on one specific commercial vendor.
Sorry, I didn't take your concerns into consideration. But AI is really useful at certain moments when writing notes. It's up to you.

**Comment by yaoqiangpersonal** [comment]
> Do you mean correct errors in Trilium code or things like spell (fact?) checking within Trilium?
> 
> I believe somebody provided some custom script to support ChatGPT. While it would be useful to have such integration in core Trilium, I'm hesitant depending on one specific commercial vendor.

**Comment by yaoqiangpersonal** [comment]
> Do you mean correct errors in Trilium code or things like spell (fact?) checking within Trilium?
> 
> I believe somebody provided some custom script to support ChatGPT. While it would be useful to have such integration in core Trilium, I'm hesitant depending on one specific commercial vendor.

Sorry, I didn't take your concerns into consideration. But AI is really useful at certain moments when writing notes. It's up to you.
