### ISSUE TITLE
Low priority Trillium vs. Trilium

### ISSUE THREAD

**Issue by seigel** [zadam/trilium#424]
Maybe it was an oversight, or possibly intentional, but since the icon seems to be related to the flower "Trillium", I wanted to just point out the spelling mistake in the name of the project.

**Comment by zadam** [comment]
Yeah, that was intentional. I was running low on "l"s at the time. English can be quite wasteful with all its fancy superfluous double letters.

**Comment by seigel** [comment]
Lol!  <-- I just used two 'l's there!  Cheers!
