### ISSUE TITLE
(Bug report) Title doesn't change when entering protected session

### ISSUE THREAD

**Issue by justyns** [zadam/trilium#4244]
### Trilium Version

0.60.4

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS 13.3.1

### Description

When clicking on a `[protected]` note in the tree, the title of the window changes to `[protected]`.  

But when I enter a protected session, the title of the window (browser tab) never changes from `[protected]` to the title of the note unless I click a different note and then go back to it.

This is with the web frontend.  The tab inside of trilium does update correctly so the desktop app doesn't seem affected.

**Comment by zadam** [comment]
Thanks for reporting this bug, will be fixed in the next 0.61 release.
