### ISSUE TITLE
(Feature request) Better Documentation for Backend API

### ISSUE THREAD

**Issue by HilkopterBob** [zadam/trilium#4245]
### Describe feature

There are multiple occasions where function calls in attributes are mentioned, but i couldnt find any documentation for such calls.
It would be great to get documentation for them, as they are pretty helpfull. 

### Additional Information

Examples for such function calls:

| source | calls |
| ----- | ----- |
| #3493 | `~Author=CurrentNote.relations.Extract.relations.Author.noteId` |
| https://github.com/zadam/trilium/wiki/Default-note-title#dynamic-value | `#titleTemplate="${parentNote.getLabelValue('authorName')}'` |

**Comment by rauenzi** [comment]
The first one your referencing here I believe was a suggestion by the user in that other issue and not actually a part of Trilium. The only function calls in attributes are described fully where you linked in the second row. Is there something missing from that section of information?

**Comment by HilkopterBob** [comment]
sorry, i found your existing api docs. Sorry and thanks for your reply 🙂
