### ISSUE TITLE
(Bug report) openNoteExternally and openNoteCustom are available in the browser

### ISSUE THREAD

**Issue by SiriusXT** [zadam/trilium#4247]
### Trilium Version

0.61.5-beta

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

linux

### Description

This bug occurs on the web side
When two or more notes are opened at the same time, and then click refresh on the browser, only the openNoteExternally and openNoteCustom of the first note are unavailable, which is correct. 
![图片](https://github.com/zadam/trilium/assets/37627919/f3d9961f-677d-4c7b-84cc-a502b78a0d93)
But switching to the second note will find that openNoteExternally and openNoteCustom are available
![图片](https://github.com/zadam/trilium/assets/37627919/b989f9b6-c5e7-41a4-91ea-0fb23c204e48)

**Comment by zadam** [comment]
Thanks for the bug report, fixed.
