### ISSUE TITLE
One doubt,hope you can answer.

### ISSUE THREAD

**Issue by wwmjb** [zadam/trilium#425]
I'm not good at computer so I have a doubt.I want to change the lovation of the document,but I don't understand the wiki。

"Changing the location of the document
If you want to use some other location for the document than the default one, you may change it via TRILIUM_DATA_DIR environment variable to some other location, e.g.:
export TRILIUM_DATA_DIR=/home/myuser/data/my-trilium-data"

How to change it（windows10 ）? I love using Trilium Notes.

**Comment by zadam** [comment]
This might help you: https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10

**Comment by wwmjb** [comment]
**I solved the question.Thank you very much!**
