### ISSUE TITLE
(Bug report) Uncaught error & failed to load source map ...

### ISSUE THREAD

**Issue by JenYiet** [zadam/trilium#4258]
### Trilium Version

0.60.4

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Debian 11

### Description

![image](https://github.com/zadam/trilium/assets/69795260/62b1110f-6377-4044-af11-b50b59a5cabe)
--
![image](https://github.com/zadam/trilium/assets/69795260/609ef897-975b-4c48-8a62-efcc25d352b0)
--
![image](https://github.com/zadam/trilium/assets/69795260/01469a04-7e09-462f-8ac9-437a396debec)
--
![image](https://github.com/zadam/trilium/assets/69795260/95040b88-496b-4412-843c-212f84224647)

**Comment by zadam** [comment]
Thanks, but these are harmless debug messages.
