### ISSUE TITLE
Active pagination tab title only visible for "White" theme (Minor visual bug)

### ISSUE THREAD

**Issue by MaxInertia** [zadam/trilium#427]
Version: v0.30.1-beta

Notice the white blobs in the images for Dark and Black theme below.

## White
![image](https://user-images.githubusercontent.com/12981415/53494237-e2ee8800-3a62-11e9-8e73-f74380b3ef53.png)

## Dark
![image](https://user-images.githubusercontent.com/12981415/53494253-eaae2c80-3a62-11e9-980d-0a5c8f3fd031.png)
![image](https://user-images.githubusercontent.com/12981415/53494413-509ab400-3a63-11e9-903d-13829fa98511.png)

## Black
![image](https://user-images.githubusercontent.com/12981415/53494266-f3066780-3a62-11e9-8e01-1f79fb69ceee.png)
![image](https://user-images.githubusercontent.com/12981415/53494393-42e52e80-3a63-11e9-8f46-1cd0a457d881.png)

**Comment by zadam** [comment]
Thanks for report, this has been actually fixed yesterday in master :)
