### ISSUE TITLE
SSL LetsEncrypt Help

### ISSUE THREAD

**Issue by adoreparler** [zadam/trilium#4270]
### Trilium Version

latest docker image

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Debian 12

### Description

I am having issues with SSL
I turn it on and define the key/cert path
/etc/letsencrypt/[mydomainhere]/cert.pem & similar for privkey.pem

I am using docker
docker run .... -v {normal path for config} -v /etc/letsencrypt/[mydomainhere]:/etc/letsencrypt/[mydomainhere] .. rest of command

When I set ssl to true in the config and restart docker container I get a no such directory error for /etc/letsencrypt/[mydomainhere]/cert.pem

I can start a shell in the container and ls the directory just fine

**Comment by sottey** [comment]
It is interesting that you posted this. I am in exactly the same situation. I have also tried putting symbolic links into the trilium-data folder. This does not work either.

I am never sure if it is a bug or me not knowing what I am doing :-)

**Comment by adoreparler** [comment]
Lol I tried the symbolic links too...

**Comment by jwhonce** [comment]
maybe `-v /etc/letsencrypt/[mydomainhere]:/home/node/trilium-data/certs`  ?

**Comment by adoreparler** [comment]
I ended up just setting the SSL cert at NGINX Reverse Proxy instead of at the application it self. The proxy and the Trilium server are on the same box so encryption can end at the proxy.

**Comment by ianrego** [comment]
I have figured out the proxy configuration and it is working now. Thanks
everyone!
