### ISSUE TITLE
(Feature request) Add a "#bottom" attribute that is the inverse of the #top" attribute

### ISSUE THREAD

**Issue by sottey** [zadam/trilium#4277]
### Describe feature

Love the #top attribute functionality. I do, however, have some things that I want to keep, but I don't want them mixed in with everything else (yet, not enough to archive them).

It would be great to have a #bottom attribute that forces a note to the bottom of the parent's tree.

Thanks as always for the amazing software!

**Comment by zadam** [comment]
Implemented in master.
