### ISSUE TITLE
(Bug report) GitHub Flavored Markdown code notes don't work

### ISSUE THREAD

**Issue by rauenzi** [zadam/trilium#4279]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 v1909

### Description

When I try to use the GFM code note I get this error:

![image](https://github.com/zadam/trilium/assets/6865942/03b2c6aa-7310-45a5-83b6-f37efe0e8608)

Looks like `addon/mode/overlay.js` needs to be manually included based on this comment https://github.com/codemirror/codemirror5/issues/2015#issuecomment-579648795 but I don't think that's even included in Trilium's copy of CM5

**Comment by rauenzi** [comment]
Looks like there's a similar issue with missing dependency when it comes to `Embedded JavaScript` notes as well.

![image](https://github.com/zadam/trilium/assets/6865942/dfb34a4e-b0dd-4a7e-b32f-f93c2b56038e)

**Comment by zadam** [comment]
fixed, thx for reporting
