### ISSUE TITLE
(Feature request) Header Underline/Plain Hybrid Style

### ISSUE THREAD

**Issue by eeshaa1** [zadam/trilium#4284]
### Describe feature

I don't like the underline style of headers because it ends up just looking ugly to me, but I do like the idea of the first heading (##) having an underline, or a line on the same row as it that starts at the end of the heading text and stretches till the end of the line, while the rest of the headers (###, ####, etc.) are plain. Would it be possible to add this?

**Comment by eeshaa1** [comment]
Oh, perfect! Do you know if there's a way to also make heading 2 automatically **bold** as soon as I mark something as H2?

**Comment by eeshaa1** [comment]
Thx

**Comment by zadam** [comment]
Closing, since this won't be doen as part of Trilium.
