### ISSUE TITLE
TLS with Docker

### ISSUE THREAD

**Issue by brady77** [zadam/trilium#429]
Cannot figure out how to setup TLS with trilium Docker container. There is no ACME Shell script inside the Docker image (which is stated in the trilium documentation). I want to run the server on Google Cloud Platform from a Container-optimized Shielded VM (Ubuntu or ChromiumOS): those are very restricted hosts that don't allow to install anything but the docker image. So I suppose that acme.sh should be part of the trilium Docker container to fetch the certificates from LetsEncrypt - but there is nothing like this. I'm an end-user (no IT admin) so setting the server is probably out of my reach. But will appreciate any help.

Thanks.

**Comment by zadam** [comment]
TLS is assumed to be handled outside of the docker container, probably as some kind of reverse proxy or something. I don't have experience with GCM, but in AWS you can just put a simple load balancer in front of your VM which would terminate the SSL (it can also easily provision the certificate itself).

**Comment by brady77** [comment]
I'll give a try and let you know if I succeed with a proxy on GCP. Maybe some other user went through this issue already and will guide me briefly... Thanks anyway, zadam.

**Comment by rax-rstark** [comment]
here is a nginx reverse proxy + certbot for TLS conf that I currently use:
```
server {

  server_name example.com;
  # set to 0 for unlimited. Default is 1M.
  #client_max_body_size 100M;
  client_max_body_size 0;

  location / {
      proxy_pass http://localhost:8080/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
  }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  listen [::]:80;

  server_name example.com;
    return 404; # managed by Certbot


}
```
