### ISSUE TITLE
(Bug report) Cannot delete launcher

### ISSUE THREAD

**Issue by ReinforceZwei** [zadam/trilium#4291]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 22H2

### Description

The delete option of the launcher right-click menu in Launchbar configuration is greyed out, even for custom launcher. Pressing `delete` key on the keyboard doesn't delete the launcher.
![image](https://github.com/zadam/trilium/assets/39955851/a64029e9-0d48-4cd9-838b-5d424464e975)

![image](https://github.com/zadam/trilium/assets/39955851/a92e2144-2bc6-4457-91bc-c9328ec4bc33)

**Comment by ReinforceZwei** [comment]
> Try `Reset`.

Reset can delete the custom launcher.

If reset is the intended way for deleting custom launcher, maybe the `delete` button in the right-click menu should be removed to reduce confusion?

**Comment by zadam** [comment]
Hello, this is a bug, thanks for reporting. Fixed in the next 0.61 beta.
