### ISSUE TITLE
(Bug report) !== will auto chang to ≠  is a trouble 

### ISSUE THREAD

**Issue by ug802** [zadam/trilium#4300]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

WIN10

### Description

when i  record batch code such as
`if  !onm!==!str!  goto bfpause`

trilium will change it  to

`if  !onm≠!str!  goto bfpause`

**Comment by zadam** [comment]
Please see #2851
