### ISSUE TITLE
Importing commonmark with images from zip fails

### ISSUE THREAD

**Issue by solderdev** [zadam/trilium#4301]
### Trilium Version

0.61.8-beta docker image

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Docker image zadam/trilium:0.61-latest 948707ba8cff

### Description

Hi!

The import of a .md file directly **works** and displays the base64 encoded embedded image.

When the same **.md file is zipped and the zipfile is imported** the embedded image **fails** to show (white rectangle with "This image has been deleted  X").

**Reproduce:**
a)
import attached .zip file --> no image

b)
extract zipfile.
import .md file directly --> image shows

Imports are done by right-clicking on a note and "Import into note".

Best regards

[tree.jpg.zip](https://github.com/zadam/trilium/files/12777574/tree.jpg.zip)

Tested on clean run via Docker-image.

**Comment by zadam** [comment]
Thanks for the report and file, bug fixed.
