### ISSUE TITLE
Include Sass as a possible language for themes

### ISSUE THREAD

**Issue by kephas** [zadam/trilium#431]
I'm using Trillium 0.29.1 and it seems that I can only use CSS to create themes. I would like to port both Solarized themes, which would be easier with Sass.

**Comment by zadam** [comment]
There's no preprocessing to the CSS files and they are directly interpreted by the browser. Supporting SASS wouldn't as easy.

**Comment by kephas** [comment]
Sass can be used inside the browser, as demonstrated by their [playground](http://sass.js.org/)

**Comment by zadam** [comment]
Yes, but it still needs a preprocessing step (inside a browser or elsewhere). Browsers don't understand SASS natively.
