### ISSUE TITLE
(Bug report) Canvas notes broken due to missing JSON data

### ISSUE THREAD

**Issue by uppenatom** [zadam/trilium#4313]
### Trilium Version

trilium-linux-x64-0.61.8-beta

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Debian 12

### Description

This bug was introduced in commit aaad858.

Canvas notes made in prior versions don't have the scroll and zoom state saved in their JSON data.

Opening them in a 0.61.8-beta client seems to leave the contents of the notes untouched, but puts Excalidraw in a glitched, 'read-only' sort of state where it can't properly display or edit the contents of any canvas notes opened afterwards.

For easy reproduction, create a demo document with an older version, open it in 0.61.8-beta, and try to view the premade canvas note.

The notes can be made working again by exporting an affected note, adding `"appState":{"scrollX":0,"scrollY":0,"zoom":{"value":1}}` to the JSON, and re-importing it.

### Error logs

![log](https://github.com/zadam/trilium/assets/147258265/4b67454b-da0e-4e37-8b72-ae40acfd63cd)

**Comment by zadam** [comment]
Hi, thanks for reporting this bug.

I believe it affected only notes created in 0.61.7-beta, since that was the only version which did not save `appState`.

Will be fixed in the next version.
