### ISSUE TITLE
label

### ISSUE THREAD

**Issue by drifter75** [zadam/trilium#4315]

**Comment by zadam** [comment]
Hi, what's the use case?

**Comment by drifter75** [comment]
Got a trilium instance running locally and another one on a VPS which I could access when travelling for work. 

There are few notes which I would like to stay local only, for eg. notes containing usernames, Bank account numbers etc. 

Technical notes or articles can be public even if the VPS gets compromised you are not going to expose any confidential/private data.

**Comment by zadam** [comment]
> There are few notes which I would like to stay local only, for eg. notes containing usernames, Bank account numbers etc.

The way Trilium covers this use case is by making such notes [protected](https://github.com/zadam/trilium/wiki/Protected-notes) - that makes them encrypted and unreadable unless a password is provided, so even if your VPS is compromised, the attacker can't access them.
