### ISSUE TITLE
Bug : Recent changes not showing titles when in protected session

### ISSUE THREAD

**Issue by jaroet** [zadam/trilium#432]
When I am not in a protected session all protected notes are visible in the recent changes page as [protected]. This is fine. 

But when I am in a protected session I would expect all title in the recent changes page to be visible. But they show some kind of hash. When I hover over the title the contect of the note is shown correctly. 

I am using Trillium (version 0.29.1) on MacOS 10.14.3.

**Comment by zadam** [comment]
Thanks for report, fixed in master!

**Comment by jaroet** [comment]
I know this is already a closed ticket but I see kind of the same 'problem' when doing an export of a tree to .TAR. The protected notes are exported as [protected] allthough I was in a protected session when I exported the notes. 

While still in a protected session importing protected notes from the .tar file generates empty notes. 

This might be expected to work like this but it was not what I was expecting. I expected to export the notes with content when exporting from a protected session. 

Jeroen

**Comment by zadam** [comment]
Hello, this is definitely wrong behavior. Export "didn't notice" that protected session is active so it couldn't decrypt the notes properly. This is now fixed.

Thank you for testing and reporting!
