### ISSUE TITLE
(Bug report) Sync fails on windows system, but not on linux (ubuntu)

### ISSUE THREAD

**Issue by abc013** [zadam/trilium#4325]
### Trilium Version

0.60.4

### What operating system are you using?

Windows, Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Windows 11, Ubuntu 20.4lts

### Description

I have set up a server today and have successfully connected my ubuntu trilium client to the server. It syncs completely fine. However, i have problems with my Windows setup. Using the exact same parameters (which i, after some trying, copied over from my ubuntu setup), i can't access the server. The error states:
```
20:59:19.909 Received request to trigger sync now.
20:59:19.909 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":20233}
20:59:19.976 sync failed: Request to POST https://<DOMAIN>:8080/api/login/sync failed, error: 401 Unauthorized
stack: Error: Request to POST https://<DOMAIN>:8080/api/login/sync failed, error: 401 Unauthorized
    at generateError (C:\Program Files (x86)\Trilium\resources\app.asar\src\services\request.js:191:12)
    at ClientRequest.<anonymous> (C:\Program Files (x86)\Trilium\resources\app.asar\src\services\request.js:62:28)
    at ClientRequest.emit (node:events:394:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6816)
    at SimpleURLLoaderWrapper.emit (node:events:394:28)
    at SimpleURLLoaderWrapper.callbackTrampoline (node:internal/async_hooks:130:17)
20:59:19.977 Slow 200 POST /api/sync/now with 136 bytes took 68ms
```

I've searched for a while in the issues and the forum, but still i can't explain why the ubuntu trilium desktop instance works and the windows one doesn't.

**Comment by rauenzi** [comment]
On your windows machine can you visit `https://<DOMAIN>:8080/` in your browser and use the web instance just fine? Without any issues or warnings about certificates, etc?

**Comment by abc013** [comment]
Yes, the web instance works just fine as well. There are no warning about certificates, either.

**Comment by zadam** [comment]
Hello, sorry for late response. The common problem is that client and server have different date / time. The difference can't be larger than 5 minutes.

**Comment by abc013** [comment]
Ah, I see. That makes sense! Since I have dual boot and my time is UTC+2, Ubuntu's time is well but windows' time lags 2 hours behind. I'll test it out soon and then close the issue. Would you mind adding that minor pitfall as a note to the Synchronizing wiki page? Just so that other people won't fall over it again. Thank you!

**Comment by zadam** [comment]
Yes, it is mentioned here: https://github.com/zadam/trilium/wiki/Synchronization#different-datetime-on-client-and-server

**Comment by abc013** [comment]
Issue was fixed. Thanks again!
