### ISSUE TITLE
How do I delete all the snapshots.

### ISSUE THREAD

**Issue by xioqing** [zadam/trilium#4326]
### Describe feature

How do I delete all the snapshots. 
Thank you.

**Comment by zadam** [comment]
What do you mean by snapshots? Backups?

These are all stored in [data directory](https://github.com/zadam/trilium/wiki/Data-directory).

**Comment by xioqing** [comment]
> What do you mean by snapshots? Backups?
> 
> These are all stored in [data directory](https://github.com/zadam/trilium/wiki/Data-directory).

I mean in "option" "other" 
"Note Revisions Snapshot Interval
Note revision snapshot time interval is time in seconds after which a new note revision will be created for the note. See [wiki](https://github.com/zadam/trilium/wiki/Note-revisions) for more info.

Note revision snapshot time interval (in seconds)"

This snapshots.

**Comment by zadam** [comment]
For a specific note, it's possible to delete all revisions with a button here:

![](https://github.com/zadam/trilium/assets/617641/7d030b76-0c21-4121-9b6c-9c7be21693fb)

If you want to do that for all notes, you can do this with "search actions" - first trigger full search and add action "Delete note revisions" like this:

![](https://github.com/zadam/trilium/assets/617641/9c5b8b7a-1c20-4a6a-b71e-3b5a7792710b)

If you don't define any search criterias then all notes are matched.

Then click "Search & Execute actions".

**Comment by xioqing** [comment]
> For a specific note, it's possible to delete all revisions with a button here:
> 
> ![](https://user-images.githubusercontent.com/617641/276423050-7d030b76-0c21-4121-9b6c-9c7be21693fb.png)
> 
> If you want to do that for all notes, you can do this with "search actions" - first trigger full search and add action "Delete note revisions" like this:
> 
> ![](https://user-images.githubusercontent.com/617641/276423331-9c5b8b7a-1c20-4a6a-b71e-3b5a7792710b.png)
> 
> If you don't define any search criterias then all notes are matched.
> 
> Then click "Search & Execute actions".

I see, Thank you very much.
