### ISSUE TITLE
[Feature request] configurable FCKeditor 

### ISSUE THREAD

**Issue by dan-2019** [zadam/trilium#433]
FCKeditor in trilium currently allows markdown notation, many of my notes (I'm using CherryTree) contain html code, for example, coloring tekst (foreground and background). It would be great if FCKeditor html editing could be enabled, or configurable.

**Comment by zadam** [comment]
This is actually not configurable in CKEditor - some HTML is simply not supported and is ignored. CKEditor 5 has different approach than the older versions and doesn't allow arbitrary HTML/tags.

**Comment by dan-2019** [comment]
Sorry zadam, I wasn't aware of this.[ this stackoverflow](https://stackoverflow.com/questions/47729450/ckeditor-5-how-to-insert-some-html-aka-wheres-the-source-mode) confirms your answer.
Instead, CKEditor 5 has a way to color text [official docs](https://ckeditor.com/docs/ckeditor5/latest/features/highlight.html), maybe something that you may consider adding. Together with text alignment this should cover most use case.

**Comment by metal450** [comment]
Just to add my +1: I'm looking for a self-hosted alternative to OneNote.  I have a huge collection of existing notes, which uses custom text formatting such as alignment, font foreground/background color, and size.  Except for these few formatting options, Trilium seems nearly perfect (it's one of only a tiny handful of notes apps that actually lets you drag-and-drop your own order in the notes listing, rather than sorting by name/date!).  I'll be keeping my eye on this issue with my fingers hopefully crossed that the text-formatting options might be expanded to include these at some point :)

**Comment by zadam** [comment]
I track request for highlighting in #436 It's not difficult to add it, the one (trivial) problem is that I need to configure available highlighting combinations - i.e. tuples of background and text colors and it's not obvious to me which to choose ...

**Comment by metal450** [comment]
If there isn't a standard color-picker that already provides these options (isn't there in most UI SDKs?), could just copy OneNote's options, to make it easy :)

**Comment by metal450** [comment]
(...Also, does that mean that "font size" and "alignment" should be submitted as separate individual issues?  Those appear to be the 3 "main" ones that are missing, at least in my initial test of starting to move bits of my OneNote library over & seeing what formatting is lost ;))

**Comment by zadam** [comment]
I don't have OneNote and the ckeditor doesn't seem to offer a standard set. I'll research this a bit more.

It would be good to track those other formatting features in separate issues ...

**Comment by metal450** [comment]
>>I don't have OneNote and the ckeditor doesn't seem to offer a standard set.

It offers the same color choices as all the Office suite (i.e. Word, Outlook, etc) - if that's helpful.

>>It would be good to track those other formatting features in separate issues ...

Sure, I'll submit then :)
