### ISSUE TITLE
How to make the HIGHLIGHTS LIST hidden by default

### ISSUE THREAD

**Issue by xioqing** [zadam/trilium#4330]
### Describe feature

How to make the HIGHLIGHTS LIST hidden by default

**Comment by xioqing** [comment]
> There are two methods
> 
> 1. Uncheck all Highlights List in Options-Text Notes
> 2. If you only want to hide the Highlights List in a certain note, you can add the #hidehighlightslist tag

I see, Thank you very much.

**Comment by egyas** [comment]
> There are two methods
> 
> 1. Uncheck all Highlights List in Options-Text Notes
> 2. If you only want to hide the Highlights List in a certain note, you can add the #hidehighlightslist tag

You sir, are a gentleman and scholar!  :)
