### ISSUE TITLE
(Bug report) File picker dialog not showing, leading to unable to restore from backup

### ISSUE THREAD

**Issue by sweetyoru** [zadam/trilium#4336]
### Trilium Version

0.60.4

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Fedora 38

### Description

I try to import my backup by:
- Right click on root node (or any node) -> Import into node -> Choose files

Expect: file dialog showed and let me pick a zip file
Result: no file dialog showed

### Error logs

DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.60.4/libraries/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.60.4/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.60.4/libraries/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/ckeditor/ckeditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.60.4/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by zadam** [comment]
That's strange ... that picker is a native OS component, even the clicking is not handled by JS.

Could you try restarting the app or even computer?

**Comment by sweetyoru** [comment]
I restarted the app, and my machine, several times.

My guess is that have anything to do with the desktop environment, currently, it's stock Fedora 38 Sway spin.

One workaround is to drag-and-dropthe backup file  from another file manager (thunnar in my case) into the app, that will work.

**Comment by zadam** [comment]
Yeah, that sounds like it. Also - wayland. Trilium v0.60 has older electron version with worse wayland support. v0.61 (in beta) has a newer electron and might work better.

**Comment by sweetyoru** [comment]
I'll wait for the new version to see if it's fixed.
