### ISSUE TITLE
(Bug report) When there are many internal links in a note, the speed to open a link is very slow

### ISSUE THREAD

**Issue by m1xds** [zadam/trilium#4339]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows11

### Description

Hi Zadam:

Firstly thank you so much for your efforts, I started to love studying because of your amazing work.
Recently, when I take a long note with many links in it, the speed of opening a link or go-back-to note would be very slow(more than 5 secs, sometimes even 10).
You may find the note example here：
![image](https://github.com/zadam/trilium/assets/96166421/942cf184-b95a-4277-9952-c1257a105646)
I don't know if it's a bug or something.
And additional two points to add:
1. I launch trilium with _trilium-portable.bat_ instead of _trilium.exe_
2. If I handle the same note on the web, it goes smoothly.
Thank you so much!!!!!

**Comment by zadam** [comment]
Hi, the likely reason is that the note is too long / complex.

The difference between seeing such page on the web and within Trilium is that on web it's displayed as read-only while in Trilium it's editable in a WYSIWYG editor.

The general recommendation is therefore to keep the notes short-ish.

An alternative is to mark it as readonly:

![](https://github.com/zadam/trilium/assets/617641/5fdeccbd-b756-4cb9-80d4-ce9eaf40323a)

when you open the note, it will open in a much faster read-only view. You can still edit it by clicking on the edit button.

**Comment by m1xds** [comment]
I tried read-only, indeed, fast like F1. It's kind of solved in this way. Thank you so much！
