### ISSUE TITLE
[Feature request] search ignoring html/markdonn tags

### ISSUE THREAD

**Issue by dan-2019** [zadam/trilium#434]
When using note with styling, for example:
<strong>A</strong>lfa<br>
<strong>B</strong>ravo<br>
<strong>C</strong>harlie<br>

trilium currently does not find text seen by the user ("**A**lfa") because of the markup tags.
Would be nice if such cases would be found.

**Comment by zadam** [comment]
Yeah, this is a limitation of current simple search approach. For next release I plan overhaul of the search with proper full text which should be able to handle this.

**Comment by zadam** [comment]
fixed in master, will be in 0.31
