### ISSUE TITLE
The “tab” key does not blank out the line, it blanks out the entire front of the block. 

### ISSUE THREAD

**Issue by xioqing** [zadam/trilium#4342]
### Trilium Version

0.61.9-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

22.04

### Description

The “tab” key does not blank out the line, it blanks out the entire front of the block.

**Comment by zadam** [comment]
Do you mean "indent" instead of "blank out"?

This is intentional behavior. Trilium is fundamentally web technology and HTML isn't really "row oriented", but "paragraph/block oriented". So indentation doesn't indent just one row as in e.g. text processor, but the whole paragraph/block.

**Comment by xioqing** [comment]
> Do you mean "indent" instead of "blank out"?
> 
> This is intentional behavior. Trilium is fundamentally web technology and HTML isn't really "row oriented", but "paragraph/block oriented". So indentation doesn't indent just one row as in e.g. text processor, but the whole paragraph/block.

Is there any way to turn it into a line?

**Comment by xioqing** [comment]
> Do you mean "indent" instead of "blank out"?
> 
> This is intentional behavior. Trilium is fundamentally web technology and HTML isn't really "row oriented", but "paragraph/block oriented". So indentation doesn't indent just one row as in e.g. text processor, but the whole paragraph/block.

It's OK, I can use the space bar instead. Thank you very much.
