### ISSUE TITLE
(Feature request) Missing search ancestor depth greater than 0

### ISSUE THREAD

**Issue by Zocker1999NET** [zadam/trilium#4343]
### Describe feature

In search parameters, the ancestor search allows setting requirements to the depth. However, the case for depth greater than 0 is missing & none of other cases seems to allow the same.

### Additional Information

Essentially, I want to find all children of a note but not itself. This is because all notes under this ancestor have a promoted “did something” boolean attribute. If its label is missing or not checked, the search note should find it.

A workaround would be to check the attribute for this ancestor, but that might communicate to my later self that everything below was already processed, which is what I want to avoid.

**Comment by zadam** [comment]
Hi, I've added the "greater than 0". 

A workaround is to set the attribute `#ancestorDepth=gt0`, this limitation existed only in the UI.

![image](https://github.com/zadam/trilium/assets/617641/1a11c163-f802-4746-ba6c-132c6679506b)
