### ISSUE TITLE
[Feature Request]: Implement tray

### ISSUE THREAD

**Issue by terafo** [zadam/trilium#435]

**Comment by legion1978** [comment]
hello. is there any way to minimize to tray?

**Comment by zadam** [comment]
Not possible at the moment. Electron [seems to support it](https://electronjs.org/docs/api/tray) so I'll put it to backlog.

**Comment by nil0x42** [comment]
Thanks for putting it on the backlog. It would be awesome to have it running all time.

Just a few suggestions of related features:
* Keep running on tray when closing window (closing window just minimizes)
* Start minimized

**Comment by NoverNobida** [comment]
So there is still no solution?

**Comment by terafo** [comment]
@NoverNobida what OS do you use?

**Comment by NoverNobida** [comment]
Windows 10.

**Comment by gerroon** [comment]
Tray stuff was broken in recent Electron apps, but they are workign fine now. For instance Joplin has it working properly atm but the tray was broken due to Electron.

**Comment by Myzel394** [comment]
@zadam What should be put into the tray context?

**Comment by zadam** [comment]
Do you mean into the tray context menu? I guess we can start with "open" and "quite". But the main thing is to be able to open the app just by clicking on the tray icon ...

**Comment by Myzel394** [comment]
I took a look at this. As @zadam already said, Electron seems to be supporting Trays kind of. They should work in Windows (haven't tested it yet) - but for me they're not working on Ubuntu 20.04. [This is an issue in Electron](https://github.com/electron/electron/issues/26854). 

I guess we can still somehow implement it. At least it's better than nothing and I think most people use Windows.

Strangely though, [Signal uses the same mechanism in their electron app](https://github.com/signalapp/Signal-Desktop/blob/dcb5bb672635c4b29a51adec8a5658e3834ec8fc/app/tray_icon.ts#L15) and their tray is working fine on my computer.

**Comment by gerroon** [comment]
Also Joplin's tray work.

I use Trilium on Windows as well, and no tray icon in the latest version.

**Comment by Myzel394** [comment]
@gerroon Yes that's correct, I am currently trying to develop this functionality. But because of the fact that Electron isn't fully supporting it, I would first like to know what @zadam thinks. I personally would still implement it, because it's an issue in Electron and only the icon is missing.

**Comment by zadam** [comment]
Hi, it looks good! I'm testing on Ubuntu (21.04) with KDE and it works. With Ubuntu/GNOME I guess we can ignore it since GNOME does not support tray at all ...

Now hiding and showing from tray requires two clicks. Since this is probably the most important activity you do, maybe simple left click could toggle the visibility? In that case we might even leave out the context menu. What do you think?

**Comment by Myzel394** [comment]
That's a good idea, but I would still keep the context menu. What about:
Left Click -> Toggle visibility
Right Click -> Context menu

**Comment by legion1978** [comment]
> Hi, it looks good! I'm testing on Ubuntu (21.04) with KDE and it works. With Ubuntu/GNOME I guess we can ignore it since GNOME does not support tray at all ...

Hi there. Does this mean it will not work on cinnamon? =(

**Comment by zadam** [comment]
#2325 merged to master. Thanks @Myzel394
