### ISSUE TITLE
(Bug report) Large note lags / freezes when typing

### ISSUE THREAD

**Issue by jakebesworth** [zadam/trilium#4352]
### Trilium Version

0.60.4

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

XUbuntu 20.04.6 LTS

### Description

**Problem:**

On a fast computer with Trilium installed on Ubuntu, I'm finding that when I try to edit a 19.2 MiB text note (92365 characters with some text formatting) the text is lagging every second.

I tried to delete chunks of text (maybe 100 lines at a time) to determine if it was a note size issue. Eventually the lag does stop at a point, but it's not clear as to when I "undo" the deleted text, the lag doesn't come back immediately.

**Images / Videos**

- Video of the lag, every second the cursor stops typing, as it freezes up / lags (ignore the comment on size, it wasn't in relation to the calculated note size): https://streamable.com/cstnc3
- Profile: ![image](https://github.com/zadam/trilium/assets/10157328/52716cca-0c3b-45dc-91f9-d01eae8f15ec)

### Error logs

```
19:01:30.633 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:30.669 200 GET /api/notes/<NOTE ID> with 115386 bytes took 2ms
19:01:31.922 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:31.928 200 GET /api/notes/<NOTE ID> with 115389 bytes took 1ms
19:01:33.226 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:33.288 200 GET /api/notes/<NOTE ID> with 115413 bytes took 2ms
19:01:34.512 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:34.566 200 GET /api/notes/<NOTE ID> with 115433 bytes took 2ms
19:01:35.808 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:35.861 200 GET /api/notes/<NOTE ID> with 115459 bytes took 1ms
19:01:37.091 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:37.148 200 GET /api/notes/<NOTE ID> with 115485 bytes took 1ms
19:01:38.373 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:38.419 200 GET /api/notes/<NOTE ID> with 115503 bytes took 1ms
19:01:39.689 Slow 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 17ms
19:01:39.748 200 GET /api/notes/<NOTE ID> with 115530 bytes took 1ms
19:01:40.964 Slow 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 11ms
19:01:41.021 200 GET /api/notes/<NOTE ID> with 115548 bytes took 1ms
19:01:42.242 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:42.286 200 GET /api/notes/<NOTE ID> with 115572 bytes took 1ms
19:01:43.522 204 PUT /api/notes/<NOTE ID>/data with 0 bytes took 2ms
19:01:43.526 200 GET /api/notes/<NOTE ID> with 115587 bytes took 1ms
```

**Comment by jakebesworth** [comment]
I turned UI scaling from 1.5 to 1 and it didn't change any behavior.

**Comment by zadam** [comment]
Hi, this is unfortunately caused by the WYSIWYG component (which happens to be CKEditor, but I doubt others would fare significantly better). The limitation is not purely just size, more like overall "complexity" of the whole note / underlying HTML.

Therefore it's recommended to break down notes into smaller pieces, structure them in a note tree.
