### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by firebone-be** [zadam/trilium#4356]
### Trilium Version

0.60.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 22H2 + Arch Linux

### Description

Getting a 502 error when trying to sync.
Access online also not possible

**Comment by rauenzi** [comment]
That sounds like something wrong on your system/server. If you cannot access it through the web, try check the logs on the server.

**Comment by firebone-be** [comment]
I don´t have it setup on own server but trough the trilium site.
looks like a domain issue hence old.triulium.cc isn´t reachable either.

**Comment by rauenzi** [comment]
The https://trilium.cc website is not owned, run, or operated by @zadam you should reach out to the owner of that site to figure out what's going on.

**Comment by zadam** [comment]
This would be @sigaloid

**Comment by sigaloid** [comment]
Hi, yep, that's me. I'm working through a host migration to avoid growing pains with larger databases. By tomorrow ideally all of the hosts will be back up and working (and won't have any sporadic downtime like the past ~week for some users).

PS: I try to make it clear that Trilium.cc =/= Trilium Notes, I should make that more prominent on the site.
