### ISSUE TITLE
runOnBackend not returning after multiple calls?

### ISSUE THREAD

**Issue by adoreparler** [zadam/trilium#4357]
### Trilium Version

0.60.4

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

Mac OS Sonoma

### Description

I'll attach a zip of the render note and code below.

I have the following code that gets executed when a button is clicked in the HTML, it works the first time, but when it is clicked again it runs the server code, but never returns (never gets to the "event Dispatch Code" log statement)

```javascript
module.exports = async function(noteID, newStatus) {
    
    console.log("updateTask: noteID: " + noteID + " newStatus: " + newStatus);
    
    await api.runOnBackend(
        async (note_id, new_status) => {
            api.log("###Processing for: " + note_id + " : " + new_status);
            const taskNote = await api.getNote(note_id);
            api.log("###Got Note");
            const newParentNote = ( await taskNote.getParentNotes()[0].getParentNotes()[0].getChildNotes() ).find((m) => m.title == new_status);
            api.log("###Got New Parent Note");
            const oldParentNoteID = taskNote.getParentNotes()[0].noteId;
            api.log("###Got Old Parent Note");
            await api.toggleNoteInParent(true, taskNote.noteId, newParentNote.noteId);
            api.log("###Toggle 1 done");
            await api.toggleNoteInParent(false, taskNote.noteId, oldParentNoteID);
            api.log("###Toggle 2 done");
        },[noteID, newStatus]
    );
    
    console.log("event Dispatch Code");
    let refreshTodoList = new CustomEvent('refresh_todo_list');
    document.dispatchEvent(refreshTodoList);
    
};
```

So first time I get all of the API logs ran in the back end and even the front end "event Dispatch Code"
Second time I get all of the API logs ran in the back end, but it never runs the "event Dispatch Code" log statement until I click another note and navigate away from the render note.
[Task List App.zip](https://github.com/zadam/trilium/files/13190816/Task.List.App.zip)

### Error logs

These logs are after its clicked the second time.

11:18:08.994 [Script GkUERfhkZ6zV] ###Processing for: wQEIstlvfhND : Backlog
11:18:08.995 [Script GkUERfhkZ6zV] ###Got Note
11:18:08.995 [Script GkUERfhkZ6zV] ###Got New Parent Note
11:18:08.995 [Script GkUERfhkZ6zV] ###Got Old Parent Note
11:18:08.997 [Script v1HtfZOzk4y2] Ensured note 'wQEIstlvfhND' is in parent note 'UBwmLoFlpREe' with prefix 'null'
11:18:09.000 [Script ReaNbwpGo0IK] ###Toggle 1 done
11:18:09.002 [Script ReaNbwpGo0IK] Marking branches OU6zJg3gVN7d_wQEIstlvfhND as deleted
11:18:09.003 [Script ReaNbwpGo0IK] Ensured note 'wQEIstlvfhND' is NOT in parent note 'OU6zJg3gVN7d'
11:18:09.003 [Script ReaNbwpGo0IK] ###Toggle 2 done
11:18:09.004 200 POST /api/script/exec with 42 bytes took 9ms

**Comment by rauenzi** [comment]
The vast majority of the backend APIs are actually synchronous not async, see the [backend api](https://zadam.github.io/trilium/backend_api/BackendScriptApi.html). So I would try making the function passed to `runOnBackend` _not_ async and removing the unneeded `await` statements inside that function.

**Comment by adoreparler** [comment]
That fixed the issue, thanks
