### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by Ubuntu51** [zadam/trilium#4358]
### Trilium Version

0.60.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

DEBIAN 12

### Description

Hello,

I get PKT on Flathub  this message, what do I have to do if I can do something? Thanks

### Error logs

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.github.zadam.trilium

**Comment by rauenzi** [comment]
See this comment from zadam https://github.com/zadam/trilium/issues/4308#issuecomment-1749433653

**Comment by Ubuntu51** [comment]
Thanks
