### ISSUE TITLE
(Feature request) The directory outline automatically indents.

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#4363]
### Describe feature

I don't often use first-level headings; I mostly use headings at the third or fourth level. However, their position seems to be fixed, with a significant amount of space in front of them. Is it possible to have them automatically move to the forefront when there are no higher-level tags?
This is where he was when I used ####
![image](https://github.com/zadam/trilium/assets/45162558/90f894e5-6729-46e9-9038-b033c2c052e7)
With ## his position is very front, can he automatically promote himself to the top one when there is no higher level title?
![image](https://github.com/zadam/trilium/assets/45162558/ef33ea65-919f-443e-9483-540170f4099b)

**Comment by zadam** [comment]
Fixed, will be in 0.62.

**Comment by Joackk** [comment]
> Fixed, will be in 0.62.

0.62 is very exciting
