### ISSUE TITLE
Pull Text Files

### ISSUE THREAD

**Issue by passionate2023** [zadam/trilium#4367]
### Describe feature

Hi,

This is regarding "URL with list of text files for syncing/pull" or pulling text files from a folder link

I have a web-site URL where there are Only huge list of text files is stored. 

Is it possible to provide an option to add the URL and sync or to pull those text files to the application?

Thanks

**Comment by jwhonce** [comment]
@passionate2023 I wrote https://github.com/jwhonce/trilium-addons/tree/main/gistMirror to mirror github gists into a trilium tree. I also wanted to learn JavaScript so it may be a little rough. 

Trilium has all the hooks to make this happen and keep the content up to date. It is nice when searching, Trilium has become my internal "google".

**Comment by zadam** [comment]
This is a very custom feature request which won't get into Trilium. You need to use one of the scripting options (backend script, ETAPI) to automate the import.

**Comment by passionate2023** [comment]
if the script is simple, can you please add any back-end script or ETAPI to automate the import

**Comment by jwhonce** [comment]
@passionate2023 An example of the script I use https://github.com/jwhonce/trilium-addons/blob/main/fileNote/pushToNote.py
