### ISSUE TITLE
Revisions have all the same past date

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#437]
Hi

It seems like the revisions for a given note has all the same dates for some reason, even the ones I did today. So something is fishy there. I tested it with Linux, Windows and the Web version.

This is with 0.30.3

See the image 

[rev](https://i.imgur.com/Mr5N9mz.png)

thanks

**Comment by skanx** [comment]
Same here. All revisions seem to have the same date as the note's creation date. I also noticed that the "Date modified" attribute in Note info is always equals to "Date created", even if the note was modified days after its creation.

**Comment by zadam** [comment]
This is now fixed in master. There has been some internal changes in representation of note content and this caused lack of updating of "dateModified" field when only content has been updated. In 0.31 the changes are finalized (I hope) and this problem is fixed.
