### ISSUE TITLE
Deleting / undeleting notes (Feature request) 

### ISSUE THREAD

**Issue by zz0rk** [zadam/trilium#4370]
### Describe feature

As per Wiki documentation:
After the 7 days (configurable) the notes will be "erased" - their title, content, revisions and attributes will be erased, and it will not be possible anymore to recover them (unless you restore [backup](https://github.com/zadam/trilium/wiki/Backup)).

Where are the days configurable?

**Comment by rauenzi** [comment]
Go to `Options`
![image](https://github.com/zadam/trilium/assets/6865942/72d51c56-9d86-4bda-bd9b-f323de5d4e40)

Then `Other`
![image](https://github.com/zadam/trilium/assets/6865942/92f67969-bb86-45d0-89a6-30274757bfb5)

This section is where it is configured by number of seconds to hold the information:
![image](https://github.com/zadam/trilium/assets/6865942/cc4b9805-e036-4def-bd8c-3827b918bc1e)

Default is 7 days calculated as:

7 days x 24 hours x 60 minutes x 60 seconds = `604800` seconds

**Comment by zz0rk** [comment]
Brillian, I glanced at all the options, but I was looking for the number '7', that's why it didn't register with me. Thank you so much!

**Comment by zz0rk** [comment]
Brillian, I glanced at all of the options, but I was looking for the number '7', that's why it didn't register. Thank you so much!
