### ISSUE TITLE
(Bug report) #shareRaw inherit is not working

### ISSUE THREAD

**Issue by Dima-Kal** [zadam/trilium#4374]
### Trilium Version

0.60.4

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Docker image

### Description

Hi, I have a snippets tree that i provide the child notes with #shareRaw tag to be able to use them
If i set this attribute as owned attribute then it is working fine, but if i do it via inherited attribute then it does not work

**Comment by deajan** [comment]
Had something alike. Have you read https://github.com/zadam/trilium/issues/4282 to make sure you're not in one of the two cases described ?

**Comment by Dima-Kal** [comment]
> Had something alike. Have you read #4282 to make sure you're not in one of the two cases described ?

Were you able to solve it?

**Comment by Dima-Kal** [comment]
> ...Well read the issue ;)

> Here the sharedCSS(inheritable)=mycssfile.css is defined on a non-shared note - i.e. this attribute doesn't exist within "Shared Notes" subtree and thus "share subsystem" doesn't know it exists. Sharing breaks inheritance in the sense of inheriting attributes from outside of shared notes to shared notes (inheritance still works within shared notes).

From what i've read, if i inherit from a shared note then it should work, but it didnt

**Comment by Dima-Kal** [comment]
> ![image](https://user-images.githubusercontent.com/617641/280246987-3d6f5e52-faca-4a75-87e4-b2d48b0cbfdc.png)
> 
> This setup works for me - If I open any note in that subtree, the note opens "raw".

Hmm, yes you are correct, i was able to make it work if i created a new note tree. But if I set the same settings for an existing tree it brakes it:

![image](https://github.com/zadam/trilium/assets/39248175/c37f31cb-e9bf-4d27-8019-6b60b6ecff52)
