### ISSUE TITLE
(Bug report) Sync error of "get /api/sync/changed threw exception, Entity revisions 'JiPnugk6tG64' not found" when update to 0.61.11

### ISSUE THREAD

**Issue by mffan0922** [zadam/trilium#4379]
### Trilium Version

0.61.11

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

I update trilium from 0.60.4 to the latest 0.61.11 via docker, and I encountered the sync problem on Windows client with my server.

I found the issue #2842 which is much similar with my situation, yet the method metioned in it just don't work for me.

### Error logs

5ms
21:20:30.440 ERROR: get /api/sync/changed threw exception: 'Entity revisions 'JiPnugk6tG64' not found.', stack: Error: Entity revisions 'JiPnugk6tG64' not found.
    at getEntityChangeRow (/usr/src/app/src/services/sync.js:309:19)
    at Object.getEntityChangeRecords (/usr/src/app/src/services/sync.js:335:24)
    at getChanged (/usr/src/app/src/routes/api/sync.js:112:45)
    at Function.cb (/usr/src/app/src/routes/routes.js:443:34)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:242:52)
    at /usr/src/app/src/routes/routes.js:445:44
    at /usr/src/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)

**Comment by perfectra1n** [comment]
I ran into the same situation, my solution was to remove my local `document.db`  within my `trilium-data` directory and resync from the server.

**Comment by perfectra1n** [comment]
I also tried to various database "fixes" within Trilium (consistency checks, etc.) before opting to just toss my local `document.db`.

**Comment by zadam** [comment]
Could you please try "Fill entity changes records" button here:

![image](https://github.com/zadam/trilium/assets/617641/fce155e6-55b5-4989-bb7c-5eab4f849ccd)

**Comment by mffan0922** [comment]
> I ran into the same situation, my solution was to remove my local `document.db` within my `trilium-data` directory and resync from the server.

I also tried that, but proved no help for me......

**Comment by mffan0922** [comment]
> Could you please try "Fill entity changes records" button here:
> 
> ![image](https://user-images.githubusercontent.com/617641/280431114-fce155e6-55b5-4989-bb7c-5eab4f849ccd.png)

Yes I did that too, nothing changed, the error still exists.

**Comment by perfectra1n** [comment]
I tried that button when I was diagnosing the issue:
![image](https://github.com/zadam/trilium/assets/2390633/5bc21c61-6579-4052-9075-698309074904)

I've since then removed the deleted images (that then became attachment types), and I haven't had the issue since, so I wonder if it could've been something to do with revision changes of the deleted images?
![image](https://github.com/zadam/trilium/assets/2390633/fe7bf55e-d5cc-4994-a97c-c6e4c8751b39)

I spun up a testing environment using yesterday's backup (client + server) and I can't replicate it...

**Comment by mffan0922** [comment]
Upgrade to 0.60.12, seems everything is OK, yet I found something unexpected, which is some of my delelted notes or images, or canvas were erased, is that normal? BTW, my draft canvas text data was lost...
![image](https://github.com/zadam/trilium/assets/63949101/77dd2847-d9a3-44bd-8dcd-9062ebc0205f)
![image](https://github.com/zadam/trilium/assets/63949101/27789190-8dcf-45a2-9660-5583b0f92929)


Logs:
08:56:50.704 App db version is 227, while db version is 214. Migration needed.
08:56:50.706 DB size: 14372 KB
08:56:51.190 {
  "appVersion": "0.61.12",
  "dbVersion": 227,
  "syncVersion": 31,
  "buildDate": "2023-11-04T00:16:19+01:00",
  "buildRevision": "1ebdb0f5e1a5cc1b7f8c36af5e1f750141ab062b",
  "dataDirectory": "/home/node/trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-11-04T00:56:50.588Z"
}
08:56:51.190 CPU model: Intel(R) N100, logical cores: 4 freq: 2909 Mhz
08:56:51.191 Trusted reverse proxy: false
08:56:51.191 App HTTP server starting up at port 8080
08:56:51.195 Listening on port 8080
08:56:51.263 Created backup at /home/node/trilium-data/backup/backup-before-migration-v060.db
08:56:51.264 Attempting migration to version 215
08:56:51.267 Migration to version 215 has been successful.
08:56:51.267 Attempting migration to version 216
08:56:51.370 Migration to version 216 has been successful.
08:56:51.370 Attempting migration to version 217
08:56:51.375 Migration to version 217 has been successful.
08:56:51.375 Attempting migration to version 218
08:56:51.383 Migration to version 218 has been successful.
08:56:51.383 Attempting migration to version 219
08:56:51.384 Migration to version 219 has been successful.
08:56:51.384 Attempting migration to version 220
08:56:51.405 Becca (note cache) load took 20ms
**08:56:51.413 Marking attributes pUwndXOR0y7A as deleted
08:56:51.414 Marking branches mLPOaL0bIY9I_MXne3tmJv7OE as deleted
08:56:51.414 Deleting note 'MXne3tmJv7OE'
08:56:51.414 Marking attributes th7Vra6wZre7 as deleted
08:56:51.415 Marking notes MXne3tmJv7OE as deleted
08:56:51.415 Auto-converted note 'MXne3tmJv7OE' into attachment 'A3Qq7fFigLED'.
08:56:51.418 Marking attributes 2hk5SxsqBsMn as deleted
08:56:51.418 Marking branches w6Acc2OZyjLE_hyRs24xBJWbo as deleted
08:56:51.418 Deleting note 'hyRs24xBJWbo'
08:56:51.418 Marking attributes 6ttQxUBK5Z65 as deleted
08:56:51.419 Marking notes hyRs24xBJWbo as deleted
08:56:51.419 Auto-converted note 'hyRs24xBJWbo' into attachment '3lIEmhBwHkYa'.
08:56:51.421 Marking attributes uTEY1Nqdf5QP as deleted
08:56:51.422 Marking branches 1HWJM2I7rMvM_dP2PTjIGCogp as deleted
08:56:51.422 Deleting note 'dP2PTjIGCogp'
08:56:51.422 Marking attributes JsgIthBqO3j7 as deleted
08:56:51.422 Marking notes dP2PTjIGCogp as deleted
08:56:51.422 Auto-converted note 'dP2PTjIGCogp' into attachment '4QYGUiCxZpQA'.
08:56:51.465 Marking attributes LjHuDuFWmDhg as deleted
08:56:51.466 Marking branches 0pAT5oIQY0mt_wv2gpwEqih67 as deleted
08:56:51.466 Deleting note 'wv2gpwEqih67'
08:56:51.466 Marking attributes hDDKBQaJ15CI as deleted
08:56:51.466 Marking attributes 2Zn4jtqxP8CH as deleted
08:56:51.466 Marking notes wv2gpwEqih67 as deleted
08:56:51.467 Auto-converted note 'wv2gpwEqih67' into attachment 'floHBz0nI4pV'.
08:56:51.469 Marking attributes as0NcMVXSleJ as deleted
08:56:51.469 Marking branches Vij6GvpQBNrl_qQOdMywYB43F as deleted
08:56:51.470 Deleting note 'qQOdMywYB43F'
08:56:51.470 Marking attributes 3XFGNB6CdfCm as deleted
08:56:51.470 Marking notes qQOdMywYB43F as deleted
08:56:51.470 Auto-converted note 'qQOdMywYB43F' into attachment 'jRxyP8bKxLU5'.
08:56:51.472 Marking attributes rWx6ifpLskSZ as deleted
08:56:51.472 Marking branches OhWZwoRarMNC_mNVUZqy8f6Yl as deleted
08:56:51.472 Deleting note 'mNVUZqy8f6Yl'
08:56:51.472 Marking attributes FRHLa6WaESaY as deleted
08:56:51.473 Marking notes mNVUZqy8f6Yl as deleted
08:56:51.473 Auto-converted note 'mNVUZqy8f6Yl' into attachment 'locG4wMfFfMJ'.
08:56:51.475 Marking attributes oPL8PW15mIIb as deleted
08:56:51.475 Marking branches Uc9IsuRVBbpd_h7Ymc6Hbc5RB as deleted
08:56:51.475 Deleting note 'h7Ymc6Hbc5RB'
08:56:51.475 Marking attributes VMAL6hJBkxiD as deleted
08:56:51.476 Marking notes h7Ymc6Hbc5RB as deleted
08:56:51.476 Auto-converted note 'h7Ymc6Hbc5RB' into attachment 'KCbReM3ArVtO'.
08:56:51.478 Marking attributes pRoxbJXCWQmm as deleted
08:56:51.478 Marking branches Uc9IsuRVBbpd_4r6m8v4v93tE as deleted
08:56:51.478 Deleting note '4r6m8v4v93tE'
08:56:51.478 Marking attributes wx4aTA0bnMA2 as deleted
08:56:51.479 Marking notes 4r6m8v4v93tE as deleted
08:56:51.479 Auto-converted note '4r6m8v4v93tE' into attachment 'YeAd3l0ZNSzW'.
08:56:51.481 Marking attributes jXPB4SK4MyGM as deleted
08:56:51.481 Marking branches BC3hBSwWG1m7_pNy9rpQ1aQlZ as deleted
08:56:51.482 Deleting note 'pNy9rpQ1aQlZ'
08:56:51.482 Marking attributes EtEzAIzlWFAI as deleted
08:56:51.482 Marking notes pNy9rpQ1aQlZ as deleted
08:56:51.482 Auto-converted note 'pNy9rpQ1aQlZ' into attachment 'mDK9QZYLrNfc'.
08:56:51.484 Marking attributes TGILtA4sjoGh as deleted
08:56:51.484 Marking branches NHGhou2B8E72_aMRRa7ghixMJ as deleted
08:56:51.484 Deleting note 'aMRRa7ghixMJ'
08:56:51.484 Marking attributes fQp5gafIrEdC as deleted
08:56:51.485 Marking notes aMRRa7ghixMJ as deleted
08:56:51.485 Auto-converted note 'aMRRa7ghixMJ' into attachment 'cQdyiCxILs0f'.
08:56:51.487 Marking attributes Jf7M9bf7C8c7 as deleted
08:56:51.487 Marking branches tNb34dO8whrp_aYyNJOYVx4eE as deleted
08:56:51.487 Deleting note 'aYyNJOYVx4eE'
08:56:51.487 Marking attributes yMR0yw0GdDuE as deleted
08:56:51.488 Marking notes aYyNJOYVx4eE as deleted
08:56:51.488 Auto-converted note 'aYyNJOYVx4eE' into attachment 'dbypEE6MEBF0'.
08:56:51.490 Marking attributes kPx4L5mpzC9g as deleted
08:56:51.490 Marking branches 54yjPfeOauEb_Fnd36fvLIB9g as deleted
08:56:51.491 Deleting note 'Fnd36fvLIB9g'
08:56:51.491 Marking attributes pJLjeWEO2F3w as deleted
08:56:51.491 Marking notes Fnd36fvLIB9g as deleted
08:56:51.491 Auto-converted note 'Fnd36fvLIB9g' into attachment 'k3I7pb0mhAsU'.
08:56:51.493 Marking attributes OZF6QWYXibgU as deleted
08:56:51.493 Marking branches WijSh12hzi6l_KUWO0hDBnXQe as deleted
08:56:51.493 Deleting note 'KUWO0hDBnXQe'
08:56:51.493 Marking attributes OcUbY6T0c7op as deleted
08:56:51.493 Marking notes KUWO0hDBnXQe as deleted
08:56:51.494 Auto-converted note 'KUWO0hDBnXQe' into attachment 'hoEP6WL9f45n'.
08:56:51.495 Marking attributes y0V4pgHo83CB as deleted
08:56:51.496 Marking branches WijSh12hzi6l_urrc7SCvELoS as deleted
08:56:51.496 Deleting note 'urrc7SCvELoS'
08:56:51.496 Marking attributes wophoLmpEVKT as deleted
08:56:51.496 Marking notes urrc7SCvELoS as deleted
08:56:51.496 Auto-converted note 'urrc7SCvELoS' into attachment 'zsc0bzhc23uE'.
08:56:51.498 Marking attributes wLrXpb8JM2UP as deleted
08:56:51.498 Marking branches WijSh12hzi6l_GCABSI7Y7HdS as deleted
08:56:51.498 Deleting note 'GCABSI7Y7HdS'
08:56:51.499 Marking attributes hfPQg28zbf7O as deleted
08:56:51.499 Marking notes GCABSI7Y7HdS as deleted
08:56:51.499 Auto-converted note 'GCABSI7Y7HdS' into attachment 'V37iqWicX5U8'.
08:56:51.501 Marking attributes y62gKl36MnDH as deleted
08:56:51.501 Marking branches tiFiiplyNN58_sQMES48vEGa6 as deleted
08:56:51.502 Deleting note 'sQMES48vEGa6'
08:56:51.502 Marking attributes PFi7wlE6MFyD as deleted
08:56:51.502 Marking notes sQMES48vEGa6 as deleted
08:56:51.502 Auto-converted note 'sQMES48vEGa6' into attachment 'aXFfSHW14R7q'.
08:56:51.504 Marking attributes M4XaSOr9PjfM as deleted
08:56:51.504 Marking branches BSEqr3eX4IPd_GUlnK7CB94fe as deleted
08:56:51.504 Deleting note 'GUlnK7CB94fe'
08:56:51.504 Marking attributes E4WoD2ZzdlY1 as deleted
08:56:51.505 Marking notes GUlnK7CB94fe as deleted
08:56:51.505 Auto-converted note 'GUlnK7CB94fe' into attachment 'sRMuEdx26h2y'.
08:56:51.506 Marking attributes i2mPPg4jof9N as deleted
08:56:51.507 Marking branches YJpwtSIUaGJu_ughf9DrDsIBn as deleted
08:56:51.507 Deleting note 'ughf9DrDsIBn'
08:56:51.507 Marking attributes pmtkpzp3ibex as deleted
08:56:51.507 Marking notes ughf9DrDsIBn as deleted**
08:56:51.507 Auto-converted note 'ughf9DrDsIBn' into attachment 'lul4ouMmY2S7'.
08:56:51.507 Migration to version 220 has been successful.
08:56:51.507 Attempting migration to version 221
08:56:51.507 Migration to version 221 has been successful.
08:56:51.507 Attempting migration to version 222
08:56:51.508 Migration to version 222 has been successful.
08:56:51.508 Attempting migration to version 223
08:56:51.508 Migration to version 223 has been successful.
08:56:51.508 Attempting migration to version 224
08:56:51.540 Migration to version 224 has been successful.
08:56:51.540 Attempting migration to version 225
08:56:51.541 Migration to version 225 has been successful.
08:56:51.541 Attempting migration to version 226
08:56:51.541 Migration to version 226 has been successful.
08:56:51.541 Attempting migration to version 227
08:56:51.542 Migration to version 227 has been successful.
08:56:51.604 VACUUMing database, this might take a while ...
08:56:51.677 Slow query took 73ms: VACUUM
08:56:51.691 Becca (note cache) load took 11ms
08:56:51.696 Created option "revisionSnapshotTimeInterval" with default value "600"
08:56:51.696 Created option "highlightsList" with default value "["bold","italic","underline","color","bgColor"]"
08:56:51.697 Created option "eraseUnusedAttachmentsAfterSeconds" with default value "2592000"
08:56:51.697 Created option "promotedAttributesOpenInRibbon" with default value "true"
08:56:51.697 Created option "editedNotesOpenInRibbon" with default value "true"
08:56:51.697 Created option "keyboardShortcutsShowRevisions" with default value "[]"
08:56:51.698 Created option "keyboardShortcutsForceSaveRevision" with default value "[]"
08:56:51.798 Saving image 'a29078c0b24343dbb81c9deccba1faa8.jpeg' as attachment into note '0pAT5oIQY0mt'
08:56:51.811 ERROR: Download of 'https://img-blog.csdnimg.cn/a29078c0b24343dbb81c9deccba1faa8.jpeg' for note '0pAT5oIQY0mt' failed with error: Cannot read properties of undefined (reading 'attachmentId') TypeError: Cannot read properties of undefined (reading 'attachmentId')
    at downloadImage (/usr/src/app/src/services/notes.js:500:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
08:56:55.705 Table counts: notes: 801, revisions: 722, attachments: 19, branches: 826, attributes: 1275, etapi_tokens: 0, blobs: 1073
08:56:55.732 All consistency checks passed with no errors detected (took 28ms)
08:57:20.382 200 GET /api/health-check with 15 bytes took 3ms
08:57:50.563 200 GET /api/health-check with 15 bytes took 2ms
08:58:01.454 Serving sync seed.
08:58:01.456 200 GET /api/setup/sync-seed with 272 bytes took 2ms
08:58:01.928 200 GET /api/setup/status with 59 bytes took 2ms
08:58:02.400 200 POST /api/login/sync with 55 bytes took 3ms
08:58:02.888 Returning 431 entity changes in 20ms
08:58:02.900 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=0&logMarkerId=fKeZnzc4Ng with 1000927 bytes took 32ms
08:58:04.728 Returning 446 entity changes in 23ms
08:58:04.739 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=2611&logMarkerId=ebFi2yAYuD with 1086357 bytes took 35ms
08:58:05.687 Returning 435 entity changes in 18ms
08:58:05.697 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=4121&logMarkerId=vJewPh7mun with 1016625 bytes took 28ms
08:58:06.433 Returning 1000 entity changes in 10ms
08:58:06.440 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=11175&logMarkerId=SjjMAnqKYI with 819258 bytes took 17ms
08:58:07.025 Returning 1000 entity changes in 15ms
08:58:07.033 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=16165&logMarkerId=IkWkkFqDWY with 796219 bytes took 24ms
08:58:07.749 Returning 1000 entity changes in 9ms
08:58:07.754 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=18517&logMarkerId=jsBWLqT5vn with 278991 bytes took 14ms
08:58:08.255 Returning 1000 entity changes in 8ms
08:58:08.259 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=19796&logMarkerId=AT1hj4b5x7 with 253960 bytes took 12ms
08:58:08.761 Returning 1000 entity changes in 13ms
08:58:08.771 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=21093&logMarkerId=FsM0tfYJ2F with 938716 bytes took 24ms
08:58:09.735 Returning 497 entity changes in 19ms
08:58:09.745 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=22767&logMarkerId=a52VDtLUTk with 1011141 bytes took 29ms
08:58:10.497 Returning 688 entity changes in 14ms
08:58:10.506 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=24515&logMarkerId=q8HNm5SEwZ with 1008507 bytes took 23ms
08:58:11.069 Returning 458 entity changes in 12ms
08:58:11.078 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=27404&logMarkerId=jWjxHPydfn with 1205836 bytes took 21ms
08:58:11.858 Returning 39 entity changes in 14ms
08:58:11.868 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=28668&logMarkerId=99iHyG7VDK with 1078013 bytes took 24ms
08:58:12.684 Returning 691 entity changes in 19ms
08:58:12.693 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=29204&logMarkerId=quxfoEkNFg with 1003730 bytes took 28ms
08:58:13.275 Returning 121 entity changes in 15ms
08:58:13.285 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=31623&logMarkerId=Z5Zn5mdlBN with 1367567 bytes took 25ms
08:58:14.042 Returning 107 entity changes in 8ms
08:58:14.052 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=31898&logMarkerId=hQUWO1AZf8 with 1112595 bytes took 19ms
08:58:14.692 Returning 124 entity changes in 13ms
08:58:14.705 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=32417&logMarkerId=91fSUt5G57 with 1003958 bytes took 26ms
08:58:15.304 Returning 93 entity changes in 7ms
08:58:15.313 Slow 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=33106&logMarkerId=4YukTWbQ3A with 1163760 bytes took 17ms
08:58:16.032 Returning 134 entity changes in 5ms
08:58:16.036 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=33511&logMarkerId=JDBTIVJsXl with 422226 bytes took 9ms
08:58:16.564 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=33664&logMarkerId=T1RNu9LxpB with 72 bytes took 2ms
08:58:17.066 204 POST /api/sync/finished with 0 bytes took 3ms
08:58:17.534 Erased unused blobs: ["0sKUvpip8B1aCKbrgc0V","3XwlfV84zJAFqx9ZFtbi","4U3N5iKjY3YgoxkEXMND","6IoTeBcfrQYMPY0Xvj99","6QiJidovftJHTyxDjcoA","BtWgIu6TxsReuV6vmtTg","Bx14kBDIux9cM8avhNvc","DB9lOXKpNbJ7zLrbdKh0","DmFdlLtabGtlNXYIg0e1","FfTv4n06LcqcN9PXHAAy","FxGxGq2nisuX06U6WXHY","HGXdp71uwXgSu1Dk8x5S","IbDoNY7TFMscWDbPTSXs","KiSUyVo5gMpWns1FWyDB","LJZuhtEYRnSqpUOHARdj","MXyobZxSooEuoTduCic6","P7BqROoR8uSvD9YhB4OS","ScdkTcXacSm4WsaTbilc","SwC3ohZw0DfbBDyk7PJs","UD36iMlhUUKmR8ucH8uU","UDMSuLbGXDFEF0R6sUEo","XBJUeBG3naZyamnfahST","XVV1Y7bNIdbgvqhYENVW","XwqPPttHxKX8rZXwGvlA","Xz39iNoGSnSr7BolWxQO","YC0CpiI31BGRs4XaeV5n","YwGKlEMv5P8ZnIUVLxge","aKbtZm2XmDqsmLXziIi4","aczB6jeD9RkFjWLNKWSl","amGaNry4i1ryDlZuY9Kg","bm4CdoiVlmCWwUdU3uK8","dO5DeHZw4R6riGpDw6TX","eTv9J0H1BRADEiXTXupG","hVVGAGb0DWDDACMVMPqM","iYyglEAIH0cYvCsCSBUr","j5ZpE3C62dPzXsXlltip","j6rSutuKQpn18J5ABRPM","juptAiaUvzLfpaAU8Phi","k61MDzC3zsdqdreMk19i","kqQEDztaFC36o2w9zzoP","laPOQjvzckphRruKGYY6","m4YcBTfsrUnlTBSF3ili","m8LtOoFhSf4ImX8oFIPb","nD4MzlA7u8wLRNkYeJ9w","nZUfx8W0dNOkYipaQ41W","ohZKoESsOLrN9oxymofi","pYRgZkTAygEO35VeKW2A","qhsZLnqKdgDPyCqOgiD7","sItFGfnuYRIpq582K63g","w21oLnGp9lcGF2DTsSEx","xGjfpV0X1ODQSIaXu4IA","yI5X1HSfubmFNCNRW1fD","yS3r8RSqBMJcm6020aji","ykL1xp0QxkATr24oqRta"]
08:58:17.566 Content hash computation took 32ms
08:58:17.568 Slow 200 GET /api/sync/check with 12104 bytes took 40ms
08:58:20.774 200 GET /api/health-check with 15 bytes took 2ms
08:58:23.074 200 GET /api/setup/status with 59 bytes took 1ms
08:58:23.534 200 POST /api/login/sync with 55 bytes took 3ms
08:58:23.999 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":0}
08:58:24.000 updated: {options: [customSearchEngineName, customSearchEngineUrl]}, alreadyUpdated: 0, erased: 0, alreadyErased: 0
08:58:24.003 204 PUT /api/sync/update?logMarkerId=bOkbcxf8ET with 0 bytes took 5ms
08:58:24.466 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=33664&logMarkerId=vF2WRorF65 with 72 bytes took 1ms
08:58:24.928 204 POST /api/sync/finished with 0 bytes took 0ms
08:58:25.435 Content hash computation took 45ms
08:58:25.436 Slow 200 GET /api/sync/check with 12104 bytes took 48ms
08:58:26.081 200 GET /api/setup/status with 59 bytes took 1ms
08:58:26.538 200 POST /api/login/sync with 55 bytes took 1ms
08:58:27.781 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":0}
08:58:27.788 updated: {revisions: [Dqpk6OoJB2LD], blobs: [R6YYVoJ6/3xlJx6oJ78b, RBrn8Q9YDdHCK0xX/J7T], notes: [RZjQgr5afxkK], attachments: [kciCqlUti16x]}, alreadyUpdated: 0, erased: 0, alreadyErased: 0
08:58:27.790 204 PUT /api/sync/update?logMarkerId=oFZYHMUYhz with 0 bytes took 9ms
08:58:28.251 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=33666&logMarkerId=ZF9wlzLQzk with 72 bytes took 2ms
08:58:28.721 204 POST /api/sync/finished with 0 bytes took 2ms
08:58:29.226 Content hash computation took 15ms
08:58:29.227 Slow 200 GET /api/sync/check with 12104 bytes took 45ms
08:58:50.968 200 GET /api/health-check with 15 bytes took 1ms
08:59:18.079 200 GET /api/setup/status with 59 bytes took 2ms
08:59:18.536 200 POST /api/login/sync with 55 bytes took 2ms
08:59:19.467 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":0}
08:59:19.471 updated: {blobs: [LwaZw2X7Dw0fDlbMGBL1, pba3TEMDFk600JGM53RY], notes: [RZjQgr5afxkK], attachments: [kciCqlUti16x]}, alreadyUpdated: 0, erased: 0, alreadyErased: 0
08:59:19.473 204 PUT /api/sync/update?logMarkerId=RzPd5CXZOy with 0 bytes took 7ms
08:59:19.935 200 GET /api/sync/changed?instanceId=2ctgp8vKYoDT&lastEntityChangeId=33671&logMarkerId=FeRGFcJ6dC with 72 bytes took 2ms
08:59:20.397 204 POST /api/sync/finished with 0 bytes took 1ms
08:59:20.874 Erased unused blobs: ["R6YYVoJ6/3xlJx6oJ78b","RBrn8Q9YDdHCK0xX/J7T"]
08:59:20.896 Content hash computation took 21ms
08:59:20.898 Slow 200 GET /api/sync/check with 12104 bytes took 27ms
08:59:21.155 200 GET /api/health-check with 15 bytes took 1ms
08:59:51.336 200 GET /api/health-check with 15 bytes took 1ms
09:00:18.545 200 GET /api/setup/status with 59 bytes took 1ms
09:00:19.003 200 POST /api/login/sync with 55 bytes took 2ms

**Comment by zadam** [comment]
One thing I just realized - have you triggered this "Fill entity change records" on the client or server? Since the error seems to be happening on the server, it needs to be triggered there ...

**Comment by perfectra1n** [comment]
I believe that I had been triggering the "Fill entity change records" on the client, since I thought that the client wasn't cooperating, but I should've tried it on the server as you've said.

**Comment by mffan0922** [comment]
Emmm, no, I just do the operation on windows client side, and I tried using my previous backups created monthly(last day of last month) to reproduce this problem(update it from 0.60.4 to 0.61.11), sadly everything goes well. My other data of this month has been distroyed yesterday, so I can't do anything now.

But at this moment, trilium works perfectly, and thank you all.

**Comment by zadam** [comment]
Hi, I still don't know what's the cause of this problem unfortunately.

But the error is recoverable, so I implemented a simple recovery which should unblock the sync process and released this in 0.61.13

**Comment by perfectra1n** [comment]
Awesome, thanks so much for making such a personalized resolution @zadam! ❤️
