### ISSUE TITLE
Better delete confirmation

### ISSUE THREAD

**Issue by varunnaik** [zadam/trilium#438]
This is a minor ux problem, but when deleting a note the confirmation dialog says 

"Are you sure you want to delete select note(s) and all the sub-notes?"

This does not give much information about what is being deleted precisely - and because the tree view allows for multiple selections  you're never fully confident about what precisely it is that you're deleting, especially if the tree is large (and a selected note might be off-screen).

I suggest that a note count in the dialog, eg. "Are you sure you want to delete 2 notes with their sub-notes?" would provide more information to users about what a delete operation modifies and inspire more confidence that something isn't being deleted accidentally.

Even better would be to see the actual names of the notes about to be deleted.

**Comment by bwat47** [comment]
+1, this would make me much less apprehensive when deleting notes

**Comment by parsehex** [comment]
I wouldn't mind trying to improve this.

What if the confirmation listed the titles of the selected notes to-be-deleted? Example: "This will delete the following notes and their sub-notes: School schedule, Journal"

I think it would look better to make the titles bold or italic but the confirm dialogue function only accepts plain text and not HTML.

I tried to get a number of sub-notes for each note but I couldn't find a straightforward way to do that.

I'd like to get some feedback or suggestions before opening a pull request.

**Comment by zadam** [comment]
> What if the confirmation listed the titles of the selected notes to-be-deleted? Example: "This will delete the following notes and their sub-notes: School schedule, Journal"

Yes, that's the idea.

> I tried to get a number of sub-notes for each note but I couldn't find a straightforward way to do that.

Well, it's fundamentally a recursive operation so not trivial. But I don't think it's that important, I think it would be enough to just show list of selected notes for deletion.

**Comment by zadam** [comment]
@parsehex thanks for PR. I changed it to show the notes in unordered list which makes it a bit clearer now.
