### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4380]
### Trilium Version

0.61.11

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows11

### Description

It seems that this modification did not get compiled into the official version. 
[40ca949](https://github.com/zadam/trilium/commit/40ca949890fb7e3848d7e942545329d6a46f26b8)

**Comment by zadam** [comment]
Indeed, this is in master which will become 0.62
