### ISSUE TITLE
Crash on startup after upgrade from 0.60.4 to 0.61.11 (Bug report) 

### ISSUE THREAD

**Issue by liiyee** [zadam/trilium#4381]
### Trilium Version

0.61.11

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

macOS Monterey 12.7.1

### Description

Crash on startup after upgrade from 0.60.4 to 0.61.11

### Error logs

02:28:10.969 App db version is 226, while db version is 214. Migration needed.
02:28:10.971 DB size: 71311 KB
02:28:12.139 {
  "appVersion": "0.61.11",
  "dbVersion": 226,
  "syncVersion": 31,
  "buildDate": "2023-11-03T11:46:53+01:00",
  "buildRevision": "01093d05d7ca1ede0c9af3fe2f5b04969ade816d",
  "dataDirectory": "/Users/xxx/trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-11-03T18:28:10.968Z"
}
02:28:12.139 CPU model: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz, logical cores: 8 freq: 2200 Mhz
02:28:12.139 Trusted reverse proxy: false
02:28:12.140 App HTTP server starting up at port 37840
02:28:12.145 Listening on port 37840
02:28:14.309 Created backup at /Users/xxx/trilium-data/backup/backup-before-migration-v060.db
02:28:14.311 Attempting migration to version 215
02:28:14.314 Migration to version 215 has been successful.
02:28:14.314 Attempting migration to version 216
02:28:14.346 Slow query took 20ms: SELECT noteId, content, dateModified, utcDateModified FROM note_contents WHERE noteId = ?
02:28:14.584 Slow query took 98ms: INSERT INTO blobs ( blobId, content, dateModified, utcDateModified ) VALUES (?, ?, ?, ?)
02:28:14.829 Slow query took 64ms: INSERT INTO blobs ( blobId, content, dateModified, utcDateModified ) VALUES (?, ?, ?, ?)
02:28:15.933 Migration to version 216 has been successful.
02:28:15.933 Attempting migration to version 217
02:28:16.008 ERROR: error during migration to version 217: SqliteError: database disk image is malformed
    at Database.exec (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at Object.executeScript (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:200:25)
    at executeMigration (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/migration.js:86:13)
    at Function.<anonymous> (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/migration.js:59:17)
    at Function.sqliteTransaction (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:242:52)
    at migrate (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/migration.js:54:9)
    at async Object.migrateIfNecessary (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/migration.js:123:9)
    at async initDbConnection (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql_init.js:41:5)
02:28:16.008 ERROR: migration failed, crashing hard
02:28:16.423 TypeError: The database connection is not open

**Comment by zadam** [comment]
Hello, this doesn't really look connected to the migration or even Trilium.

"SqliteError: database disk image is malformed" is a message from SQLite saying the DB is corrupted. You need to try out some backup (Trilium automatically creates some in the `trilium-data/backup`.

Have you tried syncing the DB with tools like Dropbox or Google Drive. These were a major source of these corruptions in the past.

**Comment by liiyee** [comment]
Thanks for the reply. 

All my data is local without any synchronization tools. When I return the version to 0.60.4, the trilium is back to normal, hope this helps.

**Comment by zadam** [comment]
Could you please go to Options -> Advanced and see what "Check integrity" returns?

![image](https://github.com/zadam/trilium/assets/617641/3b0aba61-2f7b-4f68-8863-84507616c1a5)

**Comment by liiyee** [comment]
This is the output of this operation:

> Integrity check failed: [ { "integrity_check": "row 876 missing from index IDX_entity_changes_changeId" }, { "integrity_check": "row 876 missing from index IDX_entityChanges_entityName_entityId" }, { "integrity_check": "wrong # of entries in index IDX_entity_changes_changeId" } ]

It looks like it's a corrupted db file causing the problem as you said. So, I decided to export all the notes and perform the import in the new version of Trilium, so far it looks good, thanks again!
