### ISSUE TITLE
Problematic migration from 0.60.4 to 0.61.11

### ISSUE THREAD

**Issue by welrbraga** [zadam/trilium#4382]
### Trilium Version

0.61.11

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu 22.04

### Description

On my first try, updating Trilium from 0.60.4 to 0.61.11, my virtual machine running Docker crashed and it was impossible to access it after docker starts my containers.

Using my data backup I've installed everything on my desktop and repeated the process to check.

On that second try, my machine don't crashed, but the container, yes. The last message I catched was that bellow.

After a CTRL-C and restarted container with "docker compose up", everything is like ok, but I'm not sure. On production I'll keep on 0.60.4 version.

### Error logs

```
trilium-app-1  | Attempting migration to version 226
trilium-app-1  | Migration with SQL script: UPDATE attributes SET value = 'contentAndAttachmentsAndRevisionsSize' WHERE name = 'orderBy' AND value = 'noteSize';
trilium-app-1  | 
trilium-app-1  | Migration to version 226 has been successful.
trilium-app-1  | VACUUMing database, this might take a while ...
trilium-app-1  | Slow query took 1163ms: VACUUM
trilium-app-1  | ERROR: Failed to resize image 'inline image', stack: RangeError: Maximum call stack size exceeded
trilium-app-1  |     at new EventEmitter (node:events:215:21)
trilium-app-1  |     at new Jimp (/usr/src/app/node_modules/@jimp/core/dist/index.js:170:5)
trilium-app-1  |     at /usr/src/app/node_modules/@jimp/core/dist/index.js:736:5
trilium-app-1  |     at new Promise (<anonymous>)
trilium-app-1  |     at Jimp.read (/usr/src/app/node_modules/@jimp/core/dist/index.js:734:10)
trilium-app-1  |     at resize (/usr/src/app/src/services/image.js:205:30)
trilium-app-1  |     at shrinkImage (/usr/src/app/src/services/image.js:183:34)
trilium-app-1  |     at processImage (/usr/src/app/src/services/image.js:32:34)
trilium-app-1  |     at Object.saveImageToAttachment (/usr/src/app/src/services/image.js:155:5)
trilium-app-1  |     at downloadImages (/usr/src/app/src/services/notes.js:531:45)
trilium-app-1  | Becca (note cache) load took 9ms
trilium-app-1  | Created option "revisionSnapshotTimeInterval" with default value "600"
trilium-app-1  | Created option "highlightsList" with default value "["bold","italic","underline","color","bgColor"]"
trilium-app-1  | Created option "eraseUnusedAttachmentsAfterSeconds" with default value "2592000"
trilium-app-1  | Created option "promotedAttributesOpenInRibbon" with default value "true"
trilium-app-1  | Created option "editedNotesOpenInRibbon" with default value "true"
trilium-app-1  | Created option "keyboardShortcutsShowRevisions" with default value "[]"
trilium-app-1  | Created option "keyboardShortcutsForceSaveRevision" with default value "[]"

```

**Comment by zadam** [comment]
Hello, the migration seems to be successful, that's good.

The error you're seeing should not be dangerous, it should disappear if you uncheck the "Enable image compression":

![image](https://github.com/zadam/trilium/assets/617641/f057bd06-2060-41b3-b073-b296af5b20eb)

**Comment by zadam** [comment]
I'm currently releasing 0.61.12 which disables the image compression during the migration. Please try that once released.

**Comment by welrbraga** [comment]
Hi @zadam ,

I've tested the new release with the original backup from 0.60.4 and this time everything was fine. My container do not crashed and the process of migration concluded like expected. 

Really thanks, team.
