### ISSUE TITLE
(Bug report) math formula format incorrectly 

### ISSUE THREAD

**Issue by LLouver** [zadam/trilium#4387]
### Trilium Version

0.61.12

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows10 22H2

### Description

When importing `.md` files with math formula, their style was lost, or infact, the Trilium Note does't support the `.md` style math formula like this:
![图片](https://github.com/zadam/trilium/assets/49142379/de110404-4811-4b17-b22b-3e41dd812a45)

In `Typora` and other md readers, this should be shown as 
![图片](https://github.com/zadam/trilium/assets/49142379/aaedceed-0981-4df2-bf20-0cac8ac01db1)

the md code like this:
```md
#### 选择 Select 

- 单目运算，限制一些属性的域（缩小集合）

- $\sigma_P(r):=\{t|t\in r \and P(t)\}$
```
just wedge the math formula between '$$'

ps: when I wrote math formula in Trilium and export to `.md` files, the formula was not shown correctly, due to the loss of '$$'.

**Comment by dousha** [comment]
There is one (known) thing that's in the markdown spec but trilium does not support: tables. (And it's actually [in the spec](https://github.com/zadam/trilium/wiki/Markdown).) Math expression in markdown does not come for free. They depend on MathJax or other TeX math expression render libraries. (Not to mention that `$ ... $` is also an extension -- a lot of libraries actually expect `\( \)` and `\[ \]` for inline- and block-level expressions. But that would be another issue.)

However, it is a huge pain to re-type all math expressions. Poking around in the code suggests we could start [here](https://github.com/zadam/trilium/blob/master/src/services/import/markdown.js) to add math expression import.

**Comment by Nriver** [comment]
You can try to import your markdown files with [trilium-py](https://github.com/Nriver/trilium-py). It will handle your Latex equations.

![ksnip_20231107-120211](https://github.com/zadam/trilium/assets/6752679/883b37c4-88f3-422b-b20d-bf51bb568657)

Unfortunately, the `\and` symbol seems not recognized by the library used by trilium.

**Comment by dousha** [comment]
Hi. I've managed to get the things going. But there is a catch: `\and` is actually a predefined macro that is not a part of standard TeX. The "proper" way to typeset this symbol is to use `\land` (or to be more pedantic, `\wedge`). I haven't figured out how to add custom macros to KaTeX used by Trilium yet.

**Comment by zadam** [comment]
@dousha 0.61 has a new markdown library and table import works. However, I don't believe tables are in the CommonMark spec.

**Comment by LLouver** [comment]
yeah,now I've changes every `\and` `\or` into `\land` `\lor` , thx!
