### ISSUE TITLE
FR: Update the current open note if it is synced

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#439]
Hi

It would be nice if the currently open note is changed on another instance and synced back is updated without clicking around.

- Create a note edit it, keep it open, sync it

- Open another T instance on another computer, sync, and edit the same note, sync back

- Go back to the original T, the note might have been synced but there is no way to know unless you click on another note and get back to it

thanks

**Comment by zadam** [comment]
This actually works - trilium will detect change to the current note and will reload it, but it can take some time (minute or two) since the sync isn't real time.

**Comment by gerroon** [comment]
ok, I will try waiting longer to test it further.

**Comment by gerroon** [comment]
Hi

I am not sure if this is the same thing but I see that the tree is also not updated after sync with the new notes, until I manually reload it,

**Comment by zadam** [comment]
The tree should be updated during sync and when I test it then it seems to work.

But I happened to see today that it did not update like it should but I don't know why and I could not reproduce it. I will keep an eye on that.
