### ISSUE TITLE
Infinite Scroll(Feature request) 

### ISSUE THREAD

**Issue by abdukir** [zadam/trilium#4391]
### Describe feature

Being able to scroll pass the available text could be a great improvement. I like to focus on the center of the screen while writing my notes. So for now I've been adding empty lines to be able to scroll further.

**Comment by zadam** [comment]
Hi, this should be part of the new 0.61

**Comment by abdukir** [comment]
Great can't wait for the new release!

**Comment by mechanarchy** [comment]
Reference links:
* #2728 
* Commit 0e16e48db62258bc18837ca002412e3e8a306710
