### ISSUE TITLE
Show help (F1) font when using dark/black theme

### ISSUE THREAD

**Issue by AZn5ReD** [zadam/trilium#440]
Hello,

In the last version (0.30.4), there's a problem with the font in the Help (F1).
I'm on Windows 10.
I don't know if it's relevant but I used a dark theme on W10 and have dark reader on Chrome.

![Capture](https://user-images.githubusercontent.com/1781837/54074692-e7524680-4295-11e9-8a38-0aa45436adf6.JPG)

[trilium-2019-03-09.log](https://github.com/zadam/trilium/files/2948625/trilium-2019-03-09.log)

**Comment by zadam** [comment]
Hello, thanks for reporting the bug! This was related to the dark theme with which the help dialog has not been tested. It will be fixed in the next patch release.
