### ISSUE TITLE
(Bug report) 0.62 Keeps sending me error messages

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#4401]
### Trilium Version

0.62

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

wind10

### Description

It was nice to see the new beta release, but when I opened the notes while using it he kept prompting me with an error message
I did not open the server at this time, is it because I did not open the server? Did he make any difference?
![d94a4a1f36fa7300023e9e1ff8c1aec8](https://github.com/zadam/trilium/assets/45162558/3de8d053-fbd7-4ecc-8a0d-58682f63dfab)
`You're passing an async function to api.runOnBackend() which will likely not work as you intended. Either make the function synchronous (by removing 'async' keyword), or use api.runAsyncOnBackendWithManualTransactionHandling()`

**Comment by Joackk** [comment]
Oh, I confirmed the problem. One of my plugins uses this function

**Comment by rauenzi** [comment]
Do you know which plugin does this? You may want to inform the creator that they are using `runOnBackend` incorrectly.

**Comment by Joackk** [comment]
> Do you know which plugin does this? You may want to inform the creator that they are using `runOnBackend` incorrectly.

https://github.com/SiriusXT/trilium-back-to-history

**Comment by rauenzi** [comment]
Looks like they have already fixed it https://github.com/SiriusXT/trilium-back-to-history/commit/a6a1be744089ad1f5e77ef8b46cfa12f96d1c28d

**Comment by Joackk** [comment]
> Looks like they have already fixed it [SiriusXT/trilium-back-to-history@a6a1be7](https://github.com/SiriusXT/trilium-back-to-history/commit/a6a1be744089ad1f5e77ef8b46cfa12f96d1c28d)

Yes, the author and I seem to be in the same communication group, and in the morning he also encountered this problem
