### ISSUE TITLE
(Bug report) In read only mode, the title of internal link is not updated for protected notes after enter protected session

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#4404]
### Trilium Version

0.61.13

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

win10

### Description

In my production db. There is a note which contains a very long list and is readonly. There are some internal link point to protected notes.

![ksnip_20231107-142838](https://github.com/zadam/trilium/assets/6752679/ce80aa9e-2592-4255-969b-245780d7b57f)

As you can see from the shield icon with a tick, I've already in protected session. But the title still shows as `[protected]`.

Then I tried a new database. This time, the title will show up, but it is not up to date as I changed the title of the protected note.
![ksnip_20231107-144533](https://github.com/zadam/trilium/assets/6752679/d18511a7-8b2f-4ebc-8ac7-fa438410daa3)

Looks like some there is kind of cache mechanism here.

**Comment by zadam** [comment]
Thanks for the report, fixed.
