### ISSUE TITLE
(Bug report) Copying the content of a webpage will copy the formatting of the webpage and cannot be cleared

### ISSUE THREAD

**Issue by m1xds** [zadam/trilium#4406]
### Trilium Version

0.61.13

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

I just updated to the latest version, and it is very smooth, but I have one problem, like the subject.
For example, if you copy any content from these 2 websites:

[https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/indispensable](url)
[https://www.esdict.cn/dicts/es/saber](url)

In trilium notes those would be like: 
![image](https://github.com/zadam/trilium/assets/96166421/f67cf932-3f63-4361-b7f6-5330c8a8f745)
![image](https://github.com/zadam/trilium/assets/96166421/3aad2e6d-6f21-4800-b8f4-03cf4ba30dbe)
The white and orange background can't be removed, and it's clear that those are not images.
Before today, I used 0.60.4, the same content from same website was like:
![93e47c7048a05b35898820342ee2639](https://github.com/zadam/trilium/assets/96166421/d2eb3832-884f-493a-ae5f-41ac41bfa740)

**Comment by Nriver** [comment]
I can verify this by replicating the contents of the current page we're viewing.
![ksnip_20231108-094852](https://github.com/zadam/trilium/assets/6752679/2c55ddff-0dea-4ab1-9a83-c72f051c20e8)

It's frustrating that I can't remove the background within Trilium. I'm pretty sure it didn't behave this way in version 0.60.

**Comment by Alumniminium** [comment]
A workaround would be to paste it with ctrl+shift+v, that pastes as plaintext.

**Comment by m1xds** [comment]
> A workaround would be to paste it with ctrl+shift+v, that pastes as plaintext.

Yes, but all the formats and font colors will be lost. See the last pic I uploaded, the fonts colors and formats, but without the white background, strange thing is that all those were from same website,

**Comment by zadam** [comment]
Hello, I wasn't able to reproduce the exact issue, but I believe I know what would be causing this - in the CKEditor build for 0.61 I've enabled a "general HTML support" which enables tags/features which CKEditor doesn't know. I didn't realize this would be the unintended side-effect.

I've reverted the change in https://github.com/zadam/trilium/commit/0507c46ae9c37bb2ed91ea572837263d2a8b6604
