### ISSUE TITLE
(Bug report) Unable to close Highlights List close button overlaps with first item in highlight list

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#4407]
### Trilium Version

0.61.13

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

The `X` button isn't easy/possible to click when it overlaps with the first Highlights List item:
![image](https://github.com/zadam/trilium/assets/10717998/4c0bfc69-b349-4208-9937-2e917bc081ff)

Easy workarounds exist so this is a very minor issue:
- Expand highlights pane to prevent the `X` from overlapping
- Click the very top right corner of the `X` button (sometimes works for me)

A few other observations about the Highlights List that may not warrant new issues:
- The highlights sidebar cannot be re-opened unless navigating away and then back to the note
- imo, The highlights sidebar should be an option that is not on by default - I find myself closing it out more than i use it.

**Comment by cbop-dev** [comment]
This same problem exists for me on the Linux desktop version (running the debian install file of 0.61.13 on Mint 21.1, Cinnamon 5.6.8 with kernel 6.2.0-35).

**Comment by zadam** [comment]
Hi, 0.62 has different placement of the button(s) which should fix the problem.
