### ISSUE TITLE
Feature request: Backend using NoSQL/MongoDB

### ISSUE THREAD

**Issue by JLKM** [zadam/trilium#441]
Any chance Trilium would ever get an option for a NoSQL/MongoDB backend?

It's just awesome, how Trilium controls relations, attributes etc. This is really ideal for notes taken by a taxonomy- and metadata-afficionado.

But as far as I see it, Trilium might also develop into becoming the input-side of a headless CMS-system, where a frontend library like vue.js or react.js might deliver most of the output-side.

This "new" role, however, calls for input from multiple users - and perhaps a backend, that scales more than Sqlite, when it comes to digesting a considerable load of inserts and updates.

MongoDB might be the tool for just that. Any chance Trilium would ever walk down this road?

**Comment by zadam** [comment]
> But as far as I see it, Trilium might also develop into becoming the input-side of a headless CMS-system, where a frontend library like vue.js or react.js might deliver most of the output-side.

I wouldn't phrase it as "develop into" - instead Trilium could be incidentally useful as a CMS for very simple website use cases. 

> This "new" role, however, calls for input from multiple users

I don't see this happening. Multi-user support is a huge pandora's box of features unrelated to the primary focus of the application.

> and perhaps a backend, that scales more than Sqlite, when it comes to digesting a considerable load of inserts and updates.

Actually sqlite seems to be a best choice in regards to performance for such application - especially its network-less design seems to be helping considerably. Any other network database would probably bring performance regressions for the primary use case. 

I agree that there might be problems once you get to thousands of inserts/updates per second, but that's quite clearly outside of targeted use cases.

**Comment by kmahyyg** [comment]
Since currently (2021-3),  Trillium will try to download any images pasted, but embedding a lot of images in SQLite, of course, is not a good option. And you said that our products targeted situation is not for multi-user usage, can we add a support for Minio (any S3-compatible) OSS support for saving images just use an internal link, instead of  directly inserting into DB?

**Comment by kmahyyg** [comment]
I just checked Issue #457 , which denied to use MongoDB as an option. Since MongoDB has GridFS and also could use BSON to save our notes data with structural, of course will offer some options for old revisions cleaning. Could you please explain more about that?

**Comment by zadam** [comment]
@kmahyyg Hi, not sure what's your exact question. Trilium uses SQLite as a database backend, there's no DB abstraction, no possibility to use alternative DB engine. That's why MongoDb is not an option, just like any non-SQLite database.

**Comment by kmahyyg** [comment]
OMG... Fine... My question is just that my DB is about 1 Gigabyte due to too many photos... I just wanna have an OSS backend like Minio to storage photo separately...

**Comment by KaivnD** [comment]
Actually I think there is a nice example for alternative DB solution, which is strapi. Strapi is a headless CMS, strapi provides many choices  of database, which is implement by knex.js and bookshelf.js. As far as I can see, for desktop app SQLite is the best options, no arguments whit that, for server side, is that will be a option to make trilium more flexible, If so, there is lots of cloud services can be used, such as database service, file storage, etc. So, we can free our server from database prison and disk space risk, am I right? @zadam
