### ISSUE TITLE
(Bug report) Unable to preview protected canvas

### ISSUE THREAD

**Issue by SJC08** [zadam/trilium#4414]
### Trilium Version

061.13

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11

### Description

If a note's subtree contains a protected **canvas**, it cannot be previewed properly.

https://github.com/zadam/trilium/assets/101760907/76736d47-ae43-4c9e-90d7-64d1ddf13526

**Comment by zadam** [comment]
Hi, thanks for the report, fixed.
