### ISSUE TITLE
(Bug report) Image attachment filename issue in zip exports (0.61 regression)

### ISSUE THREAD

**Issue by spasche** [zadam/trilium#4415]
### Trilium Version

0.61.13

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11

### Description

Hello,

I noticed that the zip Markdown or HTML exports behavior changed in 0.61.
In particular, if a note with a long title contains an inline image, the filename used to save the image content may get truncated and lose its image file extension.
Moreover, the truncation may produce a file which ends with a space and that's causing an issue on Windows, where having files ending with spaces or periods are not allowed (see https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file for the constraints).

Here's the testcase:
- Create a note with the following title (it must be longer that 30 characters): `01234567890123456789012345678 foo`
- Insert an image into the note
- Create a markdown or zip export containing the note

Result:
- the export contains these files:
- `root/01234567890123456789012345678 .md`
- `root/01234567890123456789012345678 `

The image doesn't contain an extension (less convenient since it can't be opened directly from a file manager) and it ends with a space, causing issues on Windows which doesn't tolerate that.

Thanks,
Sylvain

**Comment by zadam** [comment]
Hi, thanks for reporting, fixed.

**Comment by gerroon** [comment]
I can confirm this in 0.62.3, not sure if it si the same problem but I get it with .pdf files.

**Comment by 0xRoM** [comment]
I think I'm having the same issue?!

test_note.md contains:
![](1down.png)

the zip contains:
- test_1down.
- test_note.md
- test_note/1down.png

is this fixed in trilium next? is there a way to downgrade trilium back to a working version?

**Comment by gerroon** [comment]
@0xRoM It is probably there, I stopped using Trilium because of this bug, most of my exports were useless.
