### ISSUE TITLE
Language support Docker-Compose

### ISSUE THREAD

**Issue by robert-girard** [zadam/trilium#4429]
### Describe feature

Love the app! I would like to see Syntax Highlighting for Docker-Compose files.  Nuff said.

**Comment by rauenzi** [comment]
Docker compose files are just `yaml` (`.yml`) files, and there is already support for that language, make sure you have it enabled in Options -> Code Notes

![image](https://github.com/zadam/trilium/assets/6865942/6a7427f6-a8eb-4ead-9b3e-5d093779ac2c)


Note: Codemirror has no special highlighting for docker compose yaml <https://codemirror.net/5/mode/>
