### ISSUE TITLE
(Bug report) v.0.61.13 and v.0.61.12 mac version cannot opening

### ISSUE THREAD

**Issue by szwss** [zadam/trilium#4430]
### Trilium Version

0.62.0, 0.61.13, 0.61.12, 0.61.11

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

Intel UHD Graphics 630 1536 MB
3.2 GHz 6-Core Intel Core i7

macOS version: 13.3.1 (a) (22E772610a)

### Description

0.62.0, 0.61.13, 0.61.12, 0.61.11 these version, app opening is exited, its cant opening,

only 0.60.4 can use,

**Comment by szwss** [comment]
this is use v0.60.4, syncing note:
![image](https://github.com/zadam/trilium/assets/584808/7ee7e6ce-970d-42a4-bb0b-d40d1ca9ddd4)

**Comment by zadam** [comment]
Hello, could you please try to run the app from terminal so that we can see what's being output as an error message?

**Comment by szwss** [comment]
> Hello, could you please try to run the app from terminal so that we can see what's being output as an error message?

Yesterday I shut down, today I turned on and re-downloaded 0.61.13 and installed it, now it can be opened, it's weird, thanks

**Comment by zadam** [comment]
Weird, but happy it works now.
