### ISSUE TITLE
(Bug report) Restore this revision You need to refresh it manually

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#4434]
### Trilium Version

0.62.0

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

wind 10

### Description

In the latest beta version, when using the restore historical snapshot feature, my page content doesn't change. I can still edit the current state, but a manual refresh is required to display the restored content correctly.

**Comment by zadam** [comment]
Hi, thanks for reporting this bug. I can reproduce it and will work on fixing it.

**Comment by Joackk** [comment]
> Hi, thanks for reporting this bug. I can reproduce it and will work on fixing it.

hi, thank you for your response.  Trilium is the best note-taking software I've ever used.  Additionally, I've encountered an issue unintentionally, but I'm not sure how to reproduce it.  The problem is as follows: while I'm editing notes, suddenly the content I've already inputted duplicates into two parts, as if an extra blank line has been inserted in between.  However, this duplicated state is not editable.  It returns to normal after refreshing the page or switching to another page.  I think both of these issues might be related to page refreshing.

**Comment by zadam** [comment]
The original issue should be fixed in the next beta.

>  The problem is as follows: while I'm editing notes, suddenly the content I've already inputted duplicates into two parts, as if an extra blank line has been inserted in between. However, this duplicated state is not editable. It returns to normal after refreshing the page or switching to another page. I think both of these issues might be related to page refreshing.

This sounds like CKEditor crashing. Normally it should recover (restart) from a crash, but this suggests it doesn't. Was this happening in the past or is that a new problem?

**Comment by Joackk** [comment]
@zadam I think this is a recent problem, because I have been using the latest beta version, and this problem has been triggered inadvertently, so I am not sure if this also exists in the old version. If I encounter it next time, I will record it.
