### ISSUE TITLE
front end script issue - currentNote

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#444]
using 0.30.4.  I created a front end script with the goal that I could select any note and add it to a reading list.  The reading list is a note with the label readingListRoot.  I add a button to to this and also alt-r keystroke to trigger.  I got the script written and "working" with one small problem.  I have a note selected in the tree and can see its contents when I click the button or enter the keystroke, but the item that gets added to the reading list is the script itself, not the note that is visible/selected.  I use the api.CurrentNote.noteId to get the note that is on the screen.  However, it seems that when I click the button or enter the keystroke the script becomes the currentNote!!!  Also tried startNote and got the same result.  I didn't see an API in the doc to get the currently selected Note.  Do we need an api.selectedNote??

**Comment by zadam** [comment]
`api.currentNote` actually holds "note being currently executed" so the behavior is as intended, but I can see how it can be confusing. 

So far there wasn't an exposed API to get "active note" so I just added one - [getActiveNote()](https://zadam.github.io/trilium/frontend_api/FrontendScriptApi.html) and it's gonna be released very soon (today).

**Comment by pcause** [comment]
thanks, that fixed it.
