### ISSUE TITLE
An exception occurred during synchronization

### ISSUE THREAD

**Issue by jinxiaoman** [zadam/trilium#4440]
### Trilium Version

0.61.13

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

Macos 13.5.1 (22G90)

### Description

An exception occurred during synchronization, and then synchronization continued. Open the server and find an error alert: 
```
Cannot find content for noteId 'AeRBW28utVy4', blobId 'yUUc0qWm2rhM7X0EFe82';
```
 After that, I queried the SQL console on the client side, but I could not find any information. 
```
SELECT title, isDeleted, isProtected FROM notes WHERE noteId = 'AeRBW28utVy4';

//  No rows have been returned for this query.
```
 How do I operate or query, must I use previous backup restore? 

### Error logs

Cannot find content for noteId 'AeRBW28utVy4', blobId 'yUUc0qWm2rhM7X0EFe82'

**Comment by zadam** [comment]
Hello, did the synchronization succeed in the end? Sometimes there are some intermittent errors, but they should self-heal automatically ...

**Comment by jinxiaoman** [comment]
> Hello, did the synchronization succeed in the end? Sometimes there are some intermittent errors, but they should self-heal automatically ...

I can roughly determine which attachment I deleted caused this error. 
I eventually deleted the data on the server, rebuilt the server, and then pushed it locally to the server. Everything is normal now

**Comment by Se9ad0r** [comment]
已经解决该问题，只需要重新启动你的docker容器即可恢复

**Comment by grotesque** [comment]
issue still exists. apparently multi client access server is not safe in trilium.
