### ISSUE TITLE
(Bug report) rendering error in children overview in 0.61.14

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#4443]
### Trilium Version

0.61.14

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Manjaro

### Description

In 0.61.14, the demo note I use in the chinese version of trilium raises an error.

You can find the file here: https://github.com/Nriver/trilium-translation/blob/main/demo-cn.zip

Import it in 0.61.13, it works well.

![ksnip_20231116-095347](https://github.com/zadam/trilium/assets/6752679/8cd8c685-b2dd-4e54-ad72-f60456b9d7d4)

In 0.61.14, it says `rendering error`.
![ksnip_20231116-095427](https://github.com/zadam/trilium/assets/6752679/b324029a-54d3-4b3b-89f5-4b5bbd800989)

Seems there is something wrong with the internal link rendering.

### Error logs

Console outputs

![ksnip_20231116-095544](https://github.com/zadam/trilium/assets/6752679/1a8f3352-6f2a-4dee-b62f-2aebef927737)

**Comment by rauenzi** [comment]
Looks like @zadam had a bit of a typo in this commit https://github.com/zadam/trilium/commit/4bdb40904f4862c7eb498e4ee4adbed3e79d777b#diff-42d04c91d416116cec98b26bf0dc9470fc1bf0eb8e13f2a82153579fec887f0bR291

**Comment by zadam** [comment]
oops, fixed
