### ISSUE TITLE
(Bug report) App DB Migration Needed

### ISSUE THREAD

**Issue by 0adapter** [zadam/trilium#4445]
### Trilium Version

Latest Docker Container

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Docker

### Description

I'm getting the following. How do I migrate?

### Error logs

No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
App db version is 227, while db version is 213. Migration needed.
ERROR: Direct migration from your current version is not supported. Please upgrade to the latest v0.60.X first and only then to this version.

**Comment by rauenzi** [comment]
As the log says:

> Please upgrade to the latest v0.60.X first and only then to this version.

You need to upgrade from <0.60 to 0.60.4 first, then to >0.60 in order to migrate the DB correctly

**Comment by 0adapter** [comment]
How do I upgrade?

**Comment by rauenzi** [comment]
You set your container name and tag to the correct version, `zadam/trilium:0.60.4`

**Comment by 0adapter** [comment]
That worked. Thank you.
