### ISSUE TITLE
Trilium Application File Does Not Run (Windows 10) (Bug report) 

### ISSUE THREAD

**Issue by crazedflamingo** [zadam/trilium#4448]
### Trilium Version

25.9.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Home 22H2

### Description

Downloaded application. Extracted files. Selected application file, Windows cursor rotates for a couple of seconds, then nothing.

**Comment by JeanPluzo** [comment]
Hi,

I don't know your exact reason to use a (very) old version of Trilium, but I'm pretty sure that, if you download the most recent version, you should be able to start Trilium.
Your old notes and everything else (the database) should update automatically.

Regards,
J.

**Comment by crazedflamingo** [comment]
Maybe I mis-specified the Trilium version, since I downloaded the most up to date version in fact. After several installing / uninstalling cycles, I thought the problem might have been with my older version of Trilium, so I uninstalled that. However, even with no existing version present, the new download does not run. I forgot to mention that Windows Defender flags the application when opening, but I over-rode it each time to open anyway, but this changes nothing.

**Comment by rauenzi** [comment]
I believe you would first need to upgrade to version 0.60.4 before upgrading to the latest version.

**Comment by crazedflamingo** [comment]
I was installing the latest version with no prior Trilium versions on the PC, so not sure about downloading 0.60.4, but happy to give it a try.

**Comment by whiteCHILamp** [comment]
I encountered the similiar issue and managed to resolve it. Here is my solution: Initially, I downloaded version 0.60.4 and launched it first. After that, I successfully launched version 0.61.14. Following these steps strictly may not necessarily resolve your issue, but you can use the details below as a reference.

For more details, I started 'trilium.exe' not in the Visualization window but in the command prompt (cmd). After I accessed the root folder, I used the command 'trilium' to start the application instead of clicking trilium.exe. Then I received an error message stating in cmd: 'App db version is 227, while db version is 213. Migration needed. ERROR: Direct migration from your current version is not supported. Please upgrade to the latest v0.60.X first and only then to this version.' Following these instructions, I resolved the problem.

 I speculate that the update process needs to be done step by step. My original version was 0.59.x, so I only needed to download versions 0.60.x and 0.61.x sequentially. If your version is lower, it may be necessary to download more previous versions. In conclusion, following the tips from the command prompt may help resolve the problem. I hope this information is useful to you.

**Comment by crazedflamingo** [comment]
Oddly, when I tried to start from cmd the result was that the trilium.exe file was not found !!

**Comment by whiteCHILamp** [comment]
> Oddly, when I tried to start from cmd the result was that the trilium.exe file was not found !!

have you entered the folder which include trilium.exe?  I mean the command like  ‘cd <your target folder>’.

**Comment by crazedflamingo** [comment]
I just typed "start trilium.exe"

**Comment by crazedflamingo** [comment]
Furthermore, I tried loading the latest version on my laptop and it worked OK. The problem must be with my desktop set up in some way...

**Comment by whiteCHILamp** [comment]
> Furthermore, I tried loading the latest version on my laptop and it worked OK. The problem must be with my desktop set up in some way...

I cannot pinpoint the exact issue with your program, but I believe examining the error messages from Trilium in the command line might be helpful. If you're willing to give it a try, you can refer to the following procedure.

you should enter the target folder first. For example, if you download trilium in 'C:\test\trilium-windows-x64-0.61.14\trilium-windows-x64'. type the command as follow:
1: 【cd C:\test\trilium-windows-x64-0.61.14\trilium-windows-x64】
2:  【trilium 】

If you download trilium in '【x】:\test\trilium-windows-x64-0.61.14\trilium-windows-x64'， where 【x】is d ，e or f etc.，type the command as follow:（here take 【x】=‘e’ for example）
1: 【e:】
2：【cd E:\test\trilium-windows-x64-0.61.14\trilium-windows-x64】
3:  【trilium】

**Comment by crazedflamingo** [comment]
Thanks. I will try this. Unfortunately, while I can use software of this type, I do not understand the details of how it works or is installed. In that respect, these kinds of problems are a limiting factor and I can see myself going back to something like Evernote as a result.

**Comment by crazedflamingo** [comment]
Wow. A lot of stuff emerged. I am totally unqualified to understand this. Any chance of a translation?

C:\Program Files\Trilium\trilium-windows-x64>
App db version is 214, while db version is 157. Migration needed.
DB size: 12017 KB
Trusted reverse proxy: false
App HTTP server starting up at port 37840
{
  "appVersion": "0.60.4",
  "dbVersion": 214,
  "syncVersion": 29,
  "buildDate": "2023-06-19T23:26:50+02:00",
  "buildRevision": "5905950c17791ce0eb278e010c2c8b3450fdb447",
  "dataDirectory": "C:\\Users\\kevin\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2023-11-19T16:05:29.326Z"
}
CPU model: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, logical cores: 8 freq: 3600 Mhz
Listening on port 37840
Created backup at C:\Users\kevin\AppData\Roaming\trilium-data\backup/backup-before-migration.db
ERROR: Direct migration from your current version is not supported. Please upgrade to the latest v0.47.X first and only then to this version.
The database connection is not open
The database connection is not open
The database connection is not open
App db version is 214, while db version is NaN. Migration needed.
Will not check hidden subtree until migration is finished.
The database connection is not open
TypeError: sql.getRawRows is not a function or its return value is not iterable
    at load (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:33:27)
    at C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:18:9
TypeError: sql.getRawRows is not a function or its return value is not iterable
    at load (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:33:27)
    at C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:18:9
Error: Option "spellCheckEnabled" doesn't exist
    at getOption (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:21:15)
    at Object.getOptionBool (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:50:17)
    at Object.createMainWindow (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\window.js:56:45)
    at App.<anonymous> (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\electron.js:33:29)
Error: Option "spellCheckEnabled" doesn't exist
    at getOption (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:21:15)
    at Object.getOptionBool (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:50:17)
    at Object.createMainWindow (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\window.js:56:45)
    at App.<anonymous> (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\electron.js:33:29)
(node:9540) UnhandledPromiseRejectionWarning: TypeError: sql.getRawRows is not a function or its return value is not iterable
    at load (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:33:27)
    at C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:18:9
(Use `trilium --trace-warnings ...` to show where the warning was created)
(node:9540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9540) UnhandledPromiseRejectionWarning: Error: Option "spellCheckEnabled" doesn't exist
    at getOption (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:21:15)
    at Object.getOptionBool (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:50:17)
    at Object.createMainWindow (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\window.js:56:45)
    at App.<anonymous> (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\electron.js:33:29)
(node:9540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
C:\Program Files\Trilium\trilium-windows-x64>
The syntax of the command is incorrect.

C:\Program Files\Trilium\trilium-windows-x64>App db version is 214, while db version is 157. Migration needed.
'App' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>DB size: 12017 KB
'DB' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>Trusted reverse proxy: false
'Trusted' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>App HTTP server starting up at port 37840
'App' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>{
'{' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "appVersion": "0.60.4",
'"appVersion":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "dbVersion": 214,
'"dbVersion":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "syncVersion": 29,
'"syncVersion":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "buildDate": "2023-06-19T23:26:50+02:00",
'"buildDate":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "buildRevision": "5905950c17791ce0eb278e010c2c8b3450fdb447",
'"buildRevision":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "dataDirectory": "C:\\Users\\kevin\\AppData\\Roaming\\trilium-data",
'"dataDirectory":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "clipperProtocolVersion": "1.0",
'"clipperProtocolVersion":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>  "utcDateTime": "2023-11-19T16:05:29.326Z"
'"utcDateTime":' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>}
'}' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>CPU model: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, logical cores: 8 freq: 3600 Mhz
'CPU' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>Listening on port 37840
'Listening' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>Created backup at C:\Users\kevin\AppData\Roaming\trilium-data\backup/backup-before-migration.db
'Created' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>ERROR: Direct migration from your current version is not supported. Please upgrade to the latest v0.47.X first and only then to this version.
'ERROR:' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>The database connection is not open
'The' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>The database connection is not open
'The' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>The database connection is not open
'The' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>App db version is 214, while db version is NaN. Migration needed.
'App' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>Will not check hidden subtree until migration is finished.
'Will' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>The database connection is not open
'The' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>TypeError: sql.getRawRows is not a function or its return value is not iterable
'TypeError:' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>    at load (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:33:27)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:18:9
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>TypeError: sql.getRawRows is not a function or its return value is not iterable
'TypeError:' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>    at load (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:33:27)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:18:9
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>Error: Option "spellCheckEnabled" doesn't exist
'Error:' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>    at getOption (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:21:15)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at Object.getOptionBool (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:50:17)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at Object.createMainWindow (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\window.js:56:45)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at App.<anonymous> (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\electron.js:33:29)
The system cannot find the file specified.

C:\Program Files\Trilium\trilium-windows-x64>Error: Option "spellCheckEnabled" doesn't exist
'Error:' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Trilium\trilium-windows-x64>    at getOption (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:21:15)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at Object.getOptionBool (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:50:17)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at Object.createMainWindow (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\services\window.js:56:45)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at App.<anonymous> (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\electron.js:33:29)
The system cannot find the file specified.

C:\Program Files\Trilium\trilium-windows-x64>(node:9540) UnhandledPromiseRejectionWarning: TypeError: sql.getRawRows is not a function or its return value is not iterable
UnhandledPromiseRejectionWarning: was unexpected at this time.

C:\Program Files\Trilium\trilium-windows-x64>    at load (C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:33:27)
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
AT [\\computername] time [/INTERACTIVE]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.


C:\Program Files\Trilium\trilium-windows-x64>    at C:\Program Files\Trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:18:9
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

**Comment by rauenzi** [comment]
This error indicates what @whiteCHILamp said but for an even older case, you need to update to 0.47.X first in order to migrate the database.

**Comment by crazedflamingo** [comment]
Thanks for de-mystifying all that. I will delete 0.60.4 and try to download 0.47.x. 

Once I have done that, and assuming it runs, can I then just download 0.60.4 and it will automatically update the older version?

**Comment by whiteCHILamp** [comment]
it seems that it is necessary to download the latest v0.47.x. once  you download it , start it from cmd and check the information from cmd again。if it says 0.48.x or higher version is need，download them ，and start them one by one.

maybe it will cost some time, but if the data in your old trilium is large and you are still want to use trilium, you can give it a try.

**Comment by crazedflamingo** [comment]
Successfully running v0.47.8. 

Now, to upgrade to v0.60.4, if I just download the files from GitHub will the application update automatically, or will I have to delete the old app version

**Comment by rauenzi** [comment]
You can just download and run that version no need to delete anything if you don't want to, but you definitely can.

**Comment by crazedflamingo** [comment]
Thanks....
