### ISSUE TITLE
Add attribute to notes created from the android app

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#445]
I know a lot of folks don't use the Android app and I hope you improve it by making it a share target, but I do use it and find it convenient.  Items are created from the app under the day in which they were added.  I wanted to create a script to take action when the notes are created, but there is no means to uniquely identify a note as created from the android app.  If you are not interested in messing with the Android app could you add a change to the routes/api/sender.js saveNote() function to add a label attribute to the screated note.  Perhaps to be more general, allow a field in the req object to be called "label" and then if that field is provided use that as the value for the label attribute and if not use somehting like "sentNote" as the value.    Should be a 2 line addition I think.

**Comment by zadam** [comment]
Since last Sender release it is possible to add a custom label. Now I've also added an extra `#sentFromSender` label.
