### ISSUE TITLE
Backup API enhancements (Feature request) 

### ISSUE THREAD

**Issue by LastTreestar** [zadam/trilium#4455]
### Describe feature

1. I am trying to trigger a backup via a widget using " api.backupNow(api.dayjs().format("YYYY-MM-DD-HHmm"));" but that isn't a valid command. I am currently backing up hourly with trilium-py through node-red. I'd like to be able to trigger a manual backup via the API and a widget.

2. Also, instead of hourly backups, I'd like a way to poll via API to see if the data is "dirty" and needs backed up, that is, "have any changes been made since the last backup", and I'll then trigger the hourly backup. Currently, often there's no new data to backup, resulting in lots of duplicates, since it's the same .db file.

### Additional Information

I donated on paypal. Amazing work so far!!

**Comment by LastTreestar** [comment]
I created a note with noteId "Backup" and I am updating its content with the datetime when I complete a backup.

Hourly in Node-red I am polling the DB for the recent notes. If the most recent is not "Backup", I let the backup proceed.

**Comment by rauenzi** [comment]
It depends on what you mean by API here. The ETAPI has the ability to perform a backup, and you can check note counts and such to see if there has been significant changes in order to create another backup.

**Comment by zadam** [comment]
I've added the `backupNow()` to the backend API.

> Also, instead of hourly backups, I'd like a way to poll via API to see if the data is "dirty" and needs backed up, that is, "have any changes been made since the last backup", and I'll then trigger the hourly backup. Currently, often there's no new data to backup, resulting in lots of duplicates, since it's the same .db file.

I guess for this we'd have to expose the "entity changes" (internal mechanism to track changes) in some way, but I'm not sure about that, it's not a good abstraction ...

**Comment by LastTreestar** [comment]
Thank you!!
