### ISSUE TITLE
Cannot escape underscores

### ISSUE THREAD

**Issue by gkralik** [zadam/trilium#446]
When trying to write something that contains underscores (eg. a DB table name like `sys_temp_files`)
there is no possibility to write the underscores. Even if I escape the underscores (like this `sys\_temp\_files`) it ends up formatting the 'temp' part as italic.

How can we use underscores without them causing italic text?

**Comment by zadam** [comment]
Hi, pressing `CTRL-Z` (as in "undo" action) will turn the just autoformatted text back into its normal form.

**Comment by gkralik** [comment]
Thanks, this works and seems like a usable workaround.

Nevertheless, it would be nice if autoformatting would not be triggered if a character is escaped with `\`.

**Comment by zadam** [comment]
No change planned here so closing.
