### ISSUE TITLE
(Bug report) Widget classes are unable to access instance attributes

### ISSUE THREAD

**Issue by BeatLink** [zadam/trilium#4462]
### Trilium Version

0.61.15

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint Cinnamon

### Description

When creating custom widgets, the methods within the widget class are unable to access instance functions or variables with the "this" keyword

**Comment by rauenzi** [comment]
Can you give an example possibly with some code? I do this frequently in my own widgets.

**Comment by BeatLink** [comment]
```javascript
/*
This is a custom widget that allows you to set the priority of a note. 
Add this to a JS Frontend file and set label of #widget. 
*/

const html = `
<div style="display: flex; flex-direction: column; padding: 10px; border-top: 1px solid var(--main-border-color); contain: none;">
    <label for="priority-dropdown">Priority</label>
    <select name="priority" id="priority-dropdown">
        <option value="3-high">High</option>
        <option value="2-medium">Medium</option>
        <option value="1-low">Low</option>
        <option value="0-none" selected>None</option>
    </select> 
</div>`;

class PriorityWidget extends api.NoteContextAwareWidget {
    
    get position() { return 1; } // higher value means position towards the bottom/right

    get parentWidget() { return 'right-pane'; }

    isEnabled() {
        return super.isEnabled() && this.note.hasLabel("label:priority")
    }

    async doRender() {
        this.$widget = $(html);
        this.$priorityDropdown = this.$widget.find('#priority-dropdown');
        this.$priorityDropdown.on('change', this.savePriorityToNote)
        return this.$widget;
    }

    async savePriorityToNote(e){
        const currentNoteID = await api.getActiveContextNote().noteId
        var priorityValue = $('#priority-dropdown').val()
        api.runOnBackend((currentNoteID, priority) => {
            api.getNote(currentNoteID).setLabel("priority", priority)           
        }, [currentNoteID, priorityValue]);
    }

    async refreshWithNote(note) {
        var currentPriority = note.getLabelValue("priority")
        $('#priority-dropdown').val(currentPriority ? currentPriority : "0-none") // <- dropdown cannot be accessed with this.$priorityDropdown
    }
    
    async entitiesReloadedEvent({loadResults}) {
        if (loadResults.isNoteContentReloaded(this.noteId)) {
            this.refresh();
        }
    }
}

module.exports = new PriorityWidget();
```

**Comment by rauenzi** [comment]
Hmm this seems to be working for me even using `this.$priorityDropdown`, are you getting an error in console? Or is it just not working as expected?

**Comment by BeatLink** [comment]
any aspect of `this.$priorityDropdown` would return as undefined for me unless its in the scope of the `doRender()` method

**Comment by rauenzi** [comment]
Perhaps zadam may have some ideas, but I could not recreate the issue with the code provided. The only change I made was to use `this.$priorityDropdown` and it worked fine.

**Comment by zadam** [comment]
I can't reproduce your problem either, but you have a mistake here:

> this.$priorityDropdown.on('change', this.savePriorityToNote)

The method will be called without access to `this`. You need to do either:

> this.$priorityDropdown.on('change', this.savePriorityToNote.bind(this))

or:

> this.$priorityDropdown.on('change', e => this.savePriorityToNote(e))

These things are just how JavaScript works, nothing Trilium-specific.

**Comment by BeatLink** [comment]
> I can't reproduce your problem either, but you have a mistake here:
> 
> > this.$priorityDropdown.on('change', this.savePriorityToNote)
> 
> The method will be called without access to `this`. You need to do either:
> 
> > this.$priorityDropdown.on('change', this.savePriorityToNote.bind(this))
> 
> or:
> 
> > this.$priorityDropdown.on('change', e => this.savePriorityToNote(e))
> 
> These things are just how JavaScript works, nothing Trilium-specific.

This works! thanks!

**Comment by BeatLink** [comment]
Kinda reminds me of python methods needing the self variable
