### ISSUE TITLE
(Feature request) Sharing Javascript code between plugins

### ISSUE THREAD

**Issue by BeatLink** [zadam/trilium#4467]
### Describe feature

Hi, I'm currently working on a recurrence plugin for trilium and there's a recurrence class that is shared between a widget and a few scripts. Right now i have to copy and paste the class to each script and the widget. Is there a way to share it without duplication?

**Comment by henrikx** [comment]
https://github.com/zadam/trilium/discussions/4266

**Comment by zadam** [comment]
The canonical way to share e.g. functions between different widgets is by putting them into a separate note and cloning them under scripts/widgets where they are meant to be used.

This is showcased in the demo document in the Statistics - find "renderPieChart" note and see how it is cloned to 2 different places in the tree:

![](https://github.com/zadam/trilium/assets/617641/a6d048d9-e546-4c19-8fd9-1dd78f2c847e)

In the screenshot you can also see that it declared CommonJS `module.exports`

This module is then automatically imported into notes into which `renderPieChart` is cloned:

![](https://github.com/zadam/trilium/assets/617641/8a124c96-ea26-41a9-b0c8-fa1e4e44c077)

**Comment by BeatLink** [comment]
Thanks!
