### ISSUE TITLE
(Bug Report) Print note to file duplicates Tex

### ISSUE THREAD

**Issue by Lerol49** [zadam/trilium#4470]
### Trilium Version

0.62.2

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

Ubuntu 20.04.6 LTS

### Description

In some of the recent updates (after November 15), printing a Note to a file with Math Tex inside broke. The Tex is displayed properly but then the content of the equation is added one more time afterwards.

![Screenshot from 2023-11-23 21-15-21](https://github.com/zadam/trilium/assets/60656700/55f461eb-811f-4c93-99ef-54327770a8c1)

**Comment by zadam** [comment]
Hi, thanks for reporting this regression, will be fixed in the next patch build.
