### ISSUE TITLE
(Bug report) Can't close highlights list section

### ISSUE THREAD

**Issue by Anuranj-Krishnan** [zadam/trilium#4471]
### Trilium Version

0.62.2

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 11

### Description

When I bold something in note, it goes to highlights list in the left section. If we try to close that section, on the mouse hover on close button, the button highlight keeps blinking and the button doesn't work i.e, I can't close that section.

**Comment by fdisamuel** [comment]
I have the same problem for a while ( App version: 0.61.13 ).

**Comment by zadam** [comment]
Hello, I could reproduce when the highlights list was too narrow. I fixed it by simply removing the tooltip title, I guess the X button is sef-explanatory enough.
