### ISSUE TITLE
api.activateNote issue

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#448]
I am creating a script that tries to make a note with a label (displayOnStart) active.   I call runOnServer and have that return a noteId of the note with the label.  On the front end I then call api.activateNote passing the noteId, as the docs say you can use a note path or noteId.  I could see how to get a notePath so just used the NoteId.  However, I see this in the console:

tree.js:181 Uncaught (in promise) TypeError: notePath.split is not a function
    at getRunPath (tree.js:181)
    at FrontendScriptApi.activateNote (tree.js:143)
    at Object.eval (eval at <anonymous> (bundle.js:16), <anonymous>:10:5)
    at eval (eval at <anonymous> (bundle.js:16), <anonymous>:16:4)
    at eval (eval at <anonymous> (bundle.js:16), <anonymous>:18:3)
    at Object.<anonymous> (bundle.js:16)
    at executeBundle (bundle.js:17)

which seems to imply I can't pass a NoteId.

**Comment by zadam** [comment]
You can pass noteId, this stacktrace looks like Trilium can't find any notePath for given noteId. I will investigate more later ...

**Comment by zadam** [comment]
One more question - has the note you're trying to activate just been created? That used to be problematic in the past since frontend keeps cached version of some basic note data for faster access.

**Comment by pcause** [comment]
yes, the note I am trying to use it the top TODO note.  I want to start trilium and have it show my outstanding todos, so displaying this note on start would do that.

**Comment by pcause** [comment]
also, just noticed that in tree.js that activateNote is async but in the fontend_spi  it is created as:

this.activateNote = treeService.activateNote

when I added an await, I get a syntax error but when I now run I get slightly different result, but still the same issue:

12:02:17 error:  Execution of 1mH0b5isKOz7 failed with error: Load of script note "displayOnStart" (1mH0b5isKOz7) failed with: notePath.split is not a function
messaging.js:14 12:02:17 Execution of 1mH0b5isKOz7 failed with error: Load of script note "displayOnStart" (1mH0b5isKOz7) failed with: notePath.split is not a function

**Comment by pcause** [comment]
My fault.  Missing an await in my code
