### ISSUE TITLE
(Feature request) how to configure oidc?

### ISSUE THREAD

**Issue by lknite** [zadam/trilium#4483]
### Describe feature

Assuming oidc is implemented, how to configure it?

If it's not implemented, here's a video speaking about it:
[oidc for contributors](https://www.youtube.com/watch?v=E3fjncdkaOI)

Via gitops it would be nice to configure the oidc values via environment variables or something similar, that way upon deploying the trilium docker image to kubernetes upon first access it would prompt for login and authentication would occur via something like keycloak (which can use whatever behind the scenes, active directory, ldap, etc ...).

**Comment by rauenzi** [comment]
There is no oidc or similar in Trilium, it is (currently) meant for personal knowledge base and only has one "user". You can absolutely put the Trilium page behind keycloak or other SSO service, I actively do this using traefik + google oauth in my docker stack.

**Comment by lknite** [comment]
ok
