### ISSUE TITLE
(Bug report) Find and replace no longer working in Text notes

### ISSUE THREAD

**Issue by perfectra1n** [zadam/trilium#4496]
### Trilium Version

0.62.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

Hi zadam,

I think that the "find and replace" functionality within text notes might've broken recently, as it's no longer able to do so. You can't select text when in the "find and replace" dialogue, but when selecting text and then opening the "find and replace" dialogue deselects your text....
![trilium_tLG0uZLwF8](https://github.com/zadam/trilium/assets/2390633/5162d864-0e42-4177-9228-e55dccab05cf)

**Comment by zadam** [comment]
I'm not sure what exactly is meant by that selecting - deselecting, but Find & Replace works. You just need to click on "Find" first, then "Replace" gets activated.
