### ISSUE TITLE
login/pass

### ISSUE THREAD

**Issue by tvortsa** [zadam/trilium#450]
Hi!

When i clone sources from git and install and run Trilium, i open localhost:8080 and get ask login/pass, but what is login/pass ?

![FireShot Capture 001 - Login - localhost](https://user-images.githubusercontent.com/78345/54435248-23c3ed80-4741-11e9-905e-ca3c21f9274b.png)

**Comment by zadam** [comment]
When you created your document for the first time you had to fill in username & password so use those.

**Comment by pihentagy** [comment]
If multiple users are not supported [^1], why do I need to have a username? It's a bit misleading.
Or is it supported to have different disjunct node "universes" with different usernames?

[^1]: https://github.com/zadam/trilium/wiki/FAQ#multi-user-support

**Comment by zadam** [comment]
You're right that logically it does not really makes sense.

IIRC I chose to have username just because people expect this during the login process. It's mostly useless but also harmless ...

**Comment by pihentagy** [comment]
> IIRC I chose to have username just because people expect this during the login process. It's mostly useless but also harmless ...

But if you ask for username, people will constantly ask how to create another user for the same db. :stuck_out_tongue:
