### ISSUE TITLE
task maneger is broken

### ISSUE THREAD

**Issue by davidbeijinho** [zadam/trilium#4505]
### Trilium Version

0.61.0-beta

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

 6.1.65-1 - x86_64 GNU/Linux

### Description

since version 0.61.0-beta to current one (0.62.4) the task manager example is broken, when you set a new due date is not added to the journal day

I tested and the last working version for this feature is 0.60-latest

### Error logs

`[Script ynOQATCPFfiq] ERROR: Execution of script "attribute changed" (ynOQATCPFfiq) failed with error: Load of script note "attribute changed" (ynOQATCPFfiq) failed with: Cannot move note to deleted parent note 'null'
`

_No response_

**Comment by clq** [comment]
I found the problem: under "attribute changed" the script is attempting to set Tasks to done even though they aren't done, causing the script to fail before non-Done tasks are moved under the right Day-note.

Search your notes for:

`const doneTargetNoteId = isTaskDone ?  api.getDayNote(doneDate).noteId : null;`

You should see the lines:

```
const doneTargetNoteId = isTaskDone ?  api.getDayNote(doneDate).noteId : null;
api.setNoteToParent(note.noteId, 'DONE', doneTargetNoteId);
```

Wrap these in an if statement, so you end up with:

```
if (isTaskDone) {
const doneTargetNoteId = isTaskDone ?  api.getDayNote(doneDate).noteId : null;
api.setNoteToParent(note.noteId, 'DONE', doneTargetNoteId);
}
```

I can't promise you that this is the best fix, but it works for me.

**Comment by zadam** [comment]
Hi, thanks for reporting this bug.

@clq was correct, API got broken which then caused this bug.
