### ISSUE TITLE
(Bug report) if the image link in the attachment is used to display the image in the note (paste the link). An error will occur

### ISSUE THREAD

**Issue by flysaber** [zadam/trilium#4509]
### Trilium Version

v0.62.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10，Ubuntu 22.04

### Description

If you choose to upload images in the attachment and then paste the image link in the attachment to your notes. After synchronization, either your server cannot display images, or your local end cannot display images.
Specifically, if you create notes locally, the server will not be able to display images after synchronization.
If you create notes on the server side, the image cannot be displayed on the local side after synchronization.
### Error logs

none

**Comment by Nriver** [comment]
I can replicate the issue you mentioned.

The link generated by the 'Copy link to clipboard' on the attachments page includes the domain information. If it originates from the client, it starts with 'http://127.0.0.1/', causing the server web to be unable to display it. Conversely, if it is generated from the server, it starts with 'https://your_domain'.

Left is client, and right is the server.
![ksnip_20231215-150521](https://github.com/zadam/trilium/assets/6752679/bcb83630-ad6a-40b3-bd93-34edbf8e3563)

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, will be fixed in the next patch release.
