### ISSUE TITLE
sqlite3

### ISSUE THREAD

**Issue by tvortsa** [zadam/trilium#451]
I cant build of trilium sources even for gitpod for this sqlite3 error (

![FireShot Capture 002 - zadam_trilium - master_ - f3dbfe1b-87fd-415b-90bf-53feb7e295c1 ws-eu0 gitpod io](https://user-images.githubusercontent.com/78345/54456530-96e45880-476f-11e9-8968-c06dc7b9de97.png)

**Comment by zadam** [comment]
Might be because you have node v8, while you actually need node v10?

**Comment by tvortsa** [comment]
no, i use node v10, imabsolutely sure it (

**Comment by damons** [comment]
After you update to node 10 you need to do a global update, then do another npm install sqlite3, then do another npm install.  

I had this same issue.  I suspect that the server and desktop versions both require some update of sqlite3, and the build somehow updates one but not the other, requiring another npm install of sqlite3, then a rebuild.  Just a hunch, tho.

I did get past this issue, but the next problem I ran into was this:

'''
Creating initial database ...
Trace: ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: table notes has no column named utcDateCreatedError
    at wrap (/Users/damon/trilium/src/services/sql.js:137:23)
'''

**Comment by damons** [comment]
(I love this app, btw).

**Comment by tvortsa** [comment]
I will tr

> After you update to node 10 you need to do a global update, then do another npm install sqlite3, then do another npm install.
> 
> I had this same issue. I suspect that the server and desktop versions both require some update of sqlite3, and the build somehow updates one but not the other, requiring another npm install of sqlite3, then a rebuild. Just a hunch, tho.
> 
> I did get past this issue, but the next problem I ran into was this:
> 
> '''
> Creating initial database ...
> Trace: ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: table notes has no column named utcDateCreatedError
> at wrap (/Users/damon/trilium/src/services/sql.js:137:23)
> '''

Thank you for your answer!
I will try (but i I thought i does it all things, reinstall again and again )))

I think sqlite is not best decide for project like Trilium, my prefer for it is Mongo DB.

Its more good if Mongo will be in Trilium as option

**Comment by zadam** [comment]
@damons it's probably better to use stable branch, master is under active development and unstable at the moment.

I'm not sure what's the problem with sqlite3 here, but in general sqlite3 is a binary which needs to be compiled for support with specific node ABI. So if you're upgrading from e.g. node 8 to node 10, it's better to just wipe node_modules and install everything from scratch, sqlite3 should then be compiled for correct node ABI and things should just work ...

**Comment by tvortsa** [comment]
> @damons it's probably better to use stable branch, master is under active development and unstable at the moment.
> 
> I'm not sure what's the problem with sqlite3 here, but in general sqlite3 is a binary which needs to be compiled for support with specific node ABI. So if you're upgrading from e.g. node 8 to node 10, it's better to just wipe node_modules and install everything from scratch, sqlite3 should then be compiled for correct node ABI and things should just work ...

I`m NOT has node 8, i have newly installed windows 10 and latest node - 10:

![image](https://user-images.githubusercontent.com/78345/54866311-35317900-4d83-11e9-91a5-c55cd3b5267a.png)

sqlite3 dependence locate on something amazon servers and i cant get acces to it ((( 
look at this - 403 code error (((

```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/electron-v4.1-win32-x64.tar.gz
node-pre-gyp http **403** https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/electron-v4.1-win32-x64.tar.gz
```

**Comment by damons** [comment]
What happens when you just do a:

`npm install sqlite3`

?

**Comment by damons** [comment]
I agree about using the stable branch.  That's a good tip.  (NPI).  :)

Also, for @tvortsa make sure to check out the build scripts in the bin dir.  Those are good guides on how to build everything.  

I did manage to do a successful build on my mac.   So, I'm happy.  :)
