### ISSUE TITLE
(Bug report) Copy images to clipboard from a note doesn't work

### ISSUE THREAD

**Issue by deajan** [zadam/trilium#4514]
### Trilium Version

0.62.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 H2

### Description

So I've made a new note, and pasted an image into that note, to use it later.
When I came back later, the image shows up well in Trilium, but when I select it and CTRL+C in order to copy it into the clipboard, the clipboard will stay empty.

Not sure if this is a bug or a "non feature", but I cannot "extract" an image from a note via copy / paste, which seems quite non functional. Of course, I still can export the note and get the image from the zip file.

### Error logs

No error logs present

**Comment by zadam** [comment]
> the clipboard will stay empty.

Do you test this by pasting into Trilium or to an external application?

The problem is that what electron (and browser) does when CTRL+C is that it copies HTML with an image reference, but this is Trilium's internal address which may not work with external applications.

**Comment by tiger7651** [comment]
> > the clipboard will stay empty.
> 
> Do you test this by pasting into Trilium or to an external application?
> 
> The problem is that what electron (and browser) does when CTRL+C is that it copies HTML with an image reference, but this is Trilium's internal address which may not work with external applications.

This will make it extremely difficult to migrate images. In fact, so far, I have no way to copy images to other software. I suggest releasing tools that can migrate data to other software as soon as possible. The current export function is almost useless for data migration. After all, notes need to be applied, not just for reading

**Comment by bwat47** [comment]
This was possible in previous versions (you could double click on the image, and then from that page you could right click on the image and there were two context menu options, one to copy the image 'reference' and one to copy the actual image".

however (unless I'm missing something), these context menu options are no longer present in version 62

**Comment by deajan** [comment]
@zadam: My test is pasting a screenshot into Trilium, and then trying to copy paste from trilium to another app.
I understand the browser limitations here, but even showing the note attachments via the context menu doesn't allow me to export the images.
So I'm kind of stuck with the images in triliium.
I know you redesigned the way attachements work, but there should be a way to get a copy of an image into the clipboard without going the export route I guess ;)

**Comment by liuxiawei** [comment]
I faced the same problem, the image is not allowed to copy to outside. Linux, Trilium 0.64.2

**Comment by zadam** [comment]
@bwat47 thanks for the hint, this was (and still is) available on the "image notes". It works only on the electron build since that's where we have the necessary APIs. This will be present in 0.63

In the meantime, the workaround is to "Open externally":

![](https://github.com/zadam/trilium/assets/617641/fefd42b5-8b9b-4176-8de2-9e83a7836b15)

**Comment by zadam** [comment]
> <table><tbody><tr><td>There's another aspect to this issue: of you copy an image from trillium then paste it into another trillium note, then delete the original image (the actual image attachment), the note where you posted the image will no longer display the image, but will instead show a placeholder image.</td></tr></tbody></table>

Are you sure this is happening with attachments? When copying attachment like this within Trilium, the attachment is actually copied, since attachments can't be "shared" between notes, they are always owned by exactly one note.

What you describe matches the behavior of "image note" ...
