### ISSUE TITLE
(Bug report) Inconsistent line endings in exported Markdown

### ISSUE THREAD

**Issue by LokiLuciferase** [zadam/trilium#4515]
### Trilium Version

0.62.4

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 22.04

### Description

Hello,

When exporting a subtree as Markdown, the resulting md files have inconsistent line endings, namely, the Heading 1 derived from the title of the note has a CRLF line ending while the rest of the note has LF line endings as expected:

![image](https://github.com/zadam/trilium/assets/22958522/51cc1262-5ac6-4fe4-b19d-887fe25ea694)

```
❯ file While\ loop.md
While loop.md: ASCII text, with CRLF, LF line terminators
```

**Comment by zadam** [comment]
Hi, Trilium uses Marked library for export, so this would have to be fixed there: https://github.com/markedjs/marked
