### ISSUE TITLE
[FEATURE REQUEST] Be able to open multiple notes simultaneously in tabs

### ISSUE THREAD

**Issue by wesrer** [zadam/trilium#453]
Hi, I think it would be really useful if some form of tab functionality could be added to trilium. Right now, if you are working on multiple notes at once, you have to keep navigating back and forth and there is no easy way to do this other than navigating the main tree repeatedly. If you could support multiple notes being open at the same time, and allow easy switching between them using some keyboard shortcuts, it would make trilium a lot more user-friendly.

**Comment by zadam** [comment]
Hi, this is planned, but it's quite major feature so it will take some time.

**Comment by metal450** [comment]
What about just opening multiple separate instances of Trilium Notes?  Doesn't that allow multiple to be open at the same time?

**Comment by zadam** [comment]
Yes, opening multiple instances of Trilium should work.

**Comment by zadam** [comment]
Tabs released in 0.32
