### ISSUE TITLE
Optimization request for upgrade process with large database

### ISSUE THREAD

**Issue by YestermorrowONill** [zadam/trilium#4535]
### Describe feature

I am currently attempting to upgrade my Trilium Notes from version 0.60.4 to 0.62.4. The process is taking an excessively long time due to my document.db file being large (15 GB) and over 70% of it consisting of images. The update has been running for over 50 hours without completion, and the background process appears to be continuously executing SQL statements. While I understand that the update involves modifying the database structure, it seems inappropriate for a database of this size to require such a significant amount of time. I kindly request an optimization of the upgrade process to address this issue.

### Additional Information

My laptop has good performance, which should not be a limiting factor for the upgrade process optimization.

**Comment by zadam** [comment]
Hello, this is unfortunate. The upgrade process should definitely not take such a long time, I fear it's stuck for some reason.

Could you post the logs? There are several migrations being done and it would help seeing where it gets stuck ...

**Comment by rodrigoalexandrecosta** [comment]
@YestermorrowONill just a side question: how is the performance when using Trilium with such database? Everything normal? I also extend that question to @zadam but I don't exactly know how large is your database. I'm asking this because I started to move some things to Trilium, like images, zip files and so on, and alongside with a lot of Canvas notes my db is already getting somewhat larger than I anticipated.

**Comment by zadam** [comment]
Architecturally, the main scaling factor is the number of notes (attributes, attachments...) rather than their size. In this regard, Trilium should work OK till ~100 000 notes.

Trilium is not designed as a large file storage, although attachments up to ~250 MB should work OK. There will be some special things where performance will be bad - e.g. Trilium makes a daily backup (by default), doing that on 15 GBs will take some time (backup can be disabled, though) ...

**Comment by YestermorrowONill** [comment]
> Hello, this is unfortunate. The upgrade process should definitely not take such a long time, I fear it's stuck for some reason.
> 
> Could you post the logs? There are several migrations being done and it would help seeing where it gets stuck ...

08:38:14.261 App db version is 227, while db version is 214. Migration needed.
08:38:14.262 DB size: 16317878 KB
08:38:14.908 {
 "appVersion": "0.62.4",
 "dbVersion": 227,
 "syncVersion": 31,
 "buildDate": "2023-12-07T00:03:59+01:00",
 "buildRevision": "2e23c521c356c2305124f5df0f474532fa5f34ce",
 "dataDirectory": "D:\\software\\my-trilium-data",
 "clipperProtocolVersion": "1.0",
 "utcDateTime": "2023-12-18T00:38:14.259Z"
}
08:38:14.909 CPU model: 12th Gen Intel(R) Core(TM) i9-12900H, logical cores: 20 freq: 2918 Mhz
08:38:14.909 Trusted reverse proxy: false
08:38:14.909 App HTTP server starting up at port 37840
08:38:14.920 Listening on port 37840
08:39:10.672 Created backup at D:\software\my-trilium-data\backup/backup-before-migration-v060.db
08:39:54.156 App db version is 227, while db version is 214. Migration needed.
08:39:54.165 DB size: 16317878 KB
08:39:54.816 {
 "appVersion": "0.62.4",
 "dbVersion": 227,
 "syncVersion": 31,
 "buildDate": "2023-12-07T00:03:59+01:00",
 "buildRevision": "2e23c521c356c2305124f5df0f474532fa5f34ce",
 "dataDirectory": "D:\\software\\my-trilium-data",
 "clipperProtocolVersion": "1.0",
 "utcDateTime": "2023-12-18T00:39:54.156Z"
}
08:39:54.817 CPU model: 12th Gen Intel(R) Core(TM) i9-12900H, logical cores: 20 freq: 2918 Mhz
08:39:54.817 Trusted reverse proxy: false
08:39:54.817 App HTTP server starting up at port 37840
08:39:54.828 Listening on port 37840
08:40:49.262 Created backup at D:\software\my-trilium-data\backup/backup-before-migration-v060.db

I’ve inspected the log files as you suggested, but they don’t seem to contain any error messages that could pinpoint the problem.
To provide more clarity, I’ve captured a screenshot from the console during the backend update process. I’ve observed that the UPDATE SQL statements are executing sequentially, with each statement taking approximately 200ms to complete. Due to this delay, the entire update process is projected to take tens of hours to finalize, which is quite concerning.
[https://imgloc.com/image/0ctaT](url)
[https://imgloc.com/image/0cg1p](url)

**Comment by YestermorrowONill** [comment]
> Hello, this is unfortunate. The upgrade process should definitely not take such a long time, I fear it's stuck for some reason.
> 
> Could you post the logs? There are several migrations being done and it would help seeing where it gets stuck ...

08:38:14.261 App db version is 227, while db version is 214. Migration needed.
08:38:14.262 DB size: 16317878 KB
08:38:14.908 {
 "appVersion": "0.62.4",
 "dbVersion": 227,
 "syncVersion": 31,
 "buildDate": "2023-12-07T00:03:59+01:00",
 "buildRevision": "2e23c521c356c2305124f5df0f474532fa5f34ce",
 "dataDirectory": "D:\\software\\my-trilium-data",
 "clipperProtocolVersion": "1.0",
 "utcDateTime": "2023-12-18T00:38:14.259Z"
}
08:38:14.909 CPU model: 12th Gen Intel(R) Core(TM) i9-12900H, logical cores: 20 freq: 2918 Mhz
08:38:14.909 Trusted reverse proxy: false
08:38:14.909 App HTTP server starting up at port 37840
08:38:14.920 Listening on port 37840
08:39:10.672 Created backup at D:\software\my-trilium-data\backup/backup-before-migration-v060.db
08:39:54.156 App db version is 227, while db version is 214. Migration needed.
08:39:54.165 DB size: 16317878 KB
08:39:54.816 {
 "appVersion": "0.62.4",
 "dbVersion": 227,
 "syncVersion": 31,
 "buildDate": "2023-12-07T00:03:59+01:00",
 "buildRevision": "2e23c521c356c2305124f5df0f474532fa5f34ce",
 "dataDirectory": "D:\\software\\my-trilium-data",
 "clipperProtocolVersion": "1.0",
 "utcDateTime": "2023-12-18T00:39:54.156Z"
}
08:39:54.817 CPU model: 12th Gen Intel(R) Core(TM) i9-12900H, logical cores: 20 freq: 2918 Mhz
08:39:54.817 Trusted reverse proxy: false
08:39:54.817 App HTTP server starting up at port 37840
08:39:54.828 Listening on port 37840
08:40:49.262 Created backup at D:\software\my-trilium-data\backup/backup-before-migration-v060.db

I’ve inspected the log files as you suggested, but they don’t seem to contain any error messages that could pinpoint the problem.
To provide more clarity, I’ve captured a screenshot from the console during the backend update process. I’ve observed that the UPDATE SQL statements are executing sequentially, with each statement taking approximately 200ms to complete. Due to this delay, the entire update process is projected to take tens of hours to finalize, which is quite concerning.
![mmexport1703988911907.png](https://github.com/zadam/trilium/assets/41185496/7915b539-b06b-4d12-a6d3-9cfa687e8511)

![mmexport1703988908393.png](https://github.com/zadam/trilium/assets/41185496/ef89aa77-decd-48e1-8b36-882f8dbf87ae)

![mmexport1703988903166.png](https://github.com/zadam/trilium/assets/41185496/74346f4c-10ba-4b4f-aa56-5d1da2d75fab)
@zadam

**Comment by YestermorrowONill** [comment]
As I mentioned earlier, my current database is around 15GB in size, with close to 140,000 notes. Beyond regular notes, it contains a significant number of images and attachments (most of which are in PDF format) related to the notes . I’m a heavy user of Trilium, dedicating at least three hours daily to it. In practice, I do experience occasional hiccups during use, where the application becomes unresponsive for about twenty seconds to a minute, which slightly disrupt my workflow. However, overall, it’s not a deal-breaker — especially when considering alternatives like Obsidian that don’t store notes in a database, where managing hundreds of thousands of files could become a nightmare. The main reason I pour so many notes into Trilium is for the convenience of searching, and Trilium truly excels in that regard. 
@rodrigoalexandrecosta

**Comment by sottey** [comment]
Confused.  There is a clear error at the top of your logs. The app db version and the server db version are different. Make sure that you are using the same app version as the server version. It may not be causing your issue, but it for sure isn't helping.

**Comment by Nriver** [comment]
> Confused.  There is a clear error at the top of your logs. The app db version and the server db version are different. Make sure that you are using the same app version as the server version. It may not be causing your issue, but it for sure isn't helping. 

That message is for upgrade, not sync. Complete local behavior, no server is involved.

**Comment by zadam** [comment]
@YestermorrowONill this is very strange, the slow queries are actually very simple ones which should be lightning fast.

I have two theories:

1.  DB is in some way corrupted. Assuming you can still run the old version, try this:

![](https://github.com/zadam/trilium/assets/617641/44ed3b0d-c11c-4e0a-a20b-d6a8378edf22)

2\. The table with slow changes should have an index, but for whatever reason it doesn't have one. This would also explain why only this specific table appears in the slow queries.

Could you try to open the database manually in some client (e.g. DB Browser for SQLite), executing following query:

```
CREATE UNIQUE INDEX `IDX_entityChanges_entityName_entityId` ON "entity_changes" (
                                                                                 `entityName`,
                                                                                 `entityId`
    );
```

And then commit / write changes. Then try the migration again ...

**Comment by YestermorrowONill** [comment]
I executed the SQL for creating the index that you provided, but after executing it, I received a “UNIQUE constraint failed: entity_changes.entityName, entity_changes.entityId” error. So, I ran another SQL to find the rows that violate the data uniqueness:
```
SELECT entityName, entityId, COUNT(*) FROM entity_changes GROUP BY entityName, entityId HAVING COUNT(*) > 1
```
The results are as displayed below (it found 228,057 entries). 
![mmexport1704795204520.png](https://github.com/zadam/trilium/assets/41185496/41d4a13d-863c-45d9-b3ee-7b0459ad242e)

What should I do? Should I delete these records and then try to create the index again?
@zadam

**Comment by zadam** [comment]
Okay, that explains it. Yes, just delete all rows from this table, add index and try the migration again. The content of this table will be re-generated again.

**Comment by YestermorrowONill** [comment]
I followed your instructions and attempted to upgrade again. It appears the upgrade process was significantly faster this time around, yet it still took nearly nine hours and, unfortunately, ended in failure. I have pasted the logs below for your review. Could you please take a look and advise me on a possible solution? Thank you so much for your help!
[trilium-log.zip](https://github.com/zadam/trilium/files/13930312/trilium-log.zip)
@zadam

**Comment by zadam** [comment]
@YestermorrowONill thanks for the logs. It did help finding a mistake in the migration process - some indexes were created only after the big migration, causing the big migration to be slow on such huge datasets.

Please try the 0.62.6 (currently being release).

**Comment by YestermorrowONill** [comment]
It took me about half an hour this time, and I finally managed to upgrade! I’m soooooo happy! Thank you so much for your help! @zadam
