### ISSUE TITLE
(Bug report) Protected notes should also encrypt note attributes and information.

### ISSUE THREAD

**Issue by Lz1y** [zadam/trilium#4537]
### Trilium Version

0.62.4

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

Macos 14.2 (23C64)

### Description

 After save web clippings to Trilium protected tree,  note attributes and information will leak note source.

<img width="1151" alt="image" src="https://github.com/zadam/trilium/assets/23468993/0c165d40-4cf8-4e90-a74e-edae0e7b57fd">

**Comment by rauenzi** [comment]
This would be more of a feature request than a bug report. It is stated in the wiki (see here https://github.com/zadam/trilium/wiki/Protected-notes#what-is-encrypted) that attributes are not encrypted.

**Comment by Lz1y** [comment]
> This would be more of a feature request than a bug report. It is stated in the wiki (see here https://github.com/zadam/trilium/wiki/Protected-notes#what-is-encrypted) that attributes are not encrypted.

I got it. Thanks for your reply.
