### ISSUE TITLE
Help needed :) Either I am too stupid or shareCss is not working

### ISSUE THREAD

**Issue by SomwareHR** [zadam/trilium#4539]
Hi all,

# Environment

+ Trilium 0.62.4 server installed on Ubuntu server
+ Windows Desktop app 0.62.4 and/or various browsers

Everything works just fine. Thanks for a great software!

# Problem

I can't get the system to use custom CSS.
The furthest I've reached is to disable system-CSS with `#shareOmitDefaultCss`
Everything else I tried - no progress at all.

# Question

Is there a video explaining the process, as it seems I'm too stupid for documentation :)

BR
Thanks

**Comment by rauenzi** [comment]
Have you ensured that the notes all have the `~shareCss` relation and that the css itself is also shared? https://github.com/zadam/trilium/wiki/Sharing#styling-the-shared-notes

**Comment by SomwareHR** [comment]
_> Have you ensured_

Thanks. Sure, that's what made me feel stupid :D

This is what I managed to understand:


# My "CSS code note"

![image](https://github.com/zadam/trilium/assets/45540611/5431102c-3823-429e-a503-685922fc861a)

 
# My note using CSS code note

![image](https://github.com/zadam/trilium/assets/45540611/71d7e546-8af5-4786-8922-a0ecc679b8ed)


# Resulting shared page

![image](https://github.com/zadam/trilium/assets/45540611/f96361d8-4a99-4fac-b197-b68bc76695c5)
 
(dark color is from browser extension; Verdana font is from browser defaults)

**Comment by rauenzi** [comment]
It looks like your css code note is a Trilium text note. You should change the type to a css code note using the drop-down menu

**Comment by Nriver** [comment]
I see a typo in `sharecCss`.

**Comment by SomwareHR** [comment]
> I see a typo in `sharecCss`.

Indeed, thanks! :) 
It ocurred only in this reiteration and was not a solution.

**Comment by SomwareHR** [comment]
_> It looks like your css code note is a Trilium text note. You should change the type to a css code note using the drop-down menu_

@rauenzi Thank you! That was it! my CSS code note was not correct type "Code" and "CSS". 

![image](https://github.com/zadam/trilium/assets/45540611/ca51a799-831d-495c-aabf-38b386687780)


And not only that I had to change it to correct type, I had to re-create a relationship after that, I had to re-add "~shareCss(inheritable)=MyCSSCodeNote" in my 'real note', this time without typo, as @Nriver observed :)

Back to business. Thanks for help and thanks again for a wonderful software!

BR
