### ISSUE TITLE
[Bug] The subtree indicator does not disappear even when the note has no sub-tree

### ISSUE THREAD

**Issue by wesrer** [zadam/trilium#454]
version - 0.30.5

This bug only appears when you move a subtree to a separate location using drag and drop. The parent note continues to show a sub-tree indicator even though it is now a leaf node. 

Steps to Replicate bug

1. Create a new node
2. Create a new child node inside the previous node
3. Drag the child node to be the child of some other node in the tree, such that the node created in step 1 is now childless
4. The indicator doesn't go away

[Haven't included log data because there doesn't seem to be anything relevant to this bug on the logs].

**Comment by zadam** [comment]
Thanks for reporting this, it has been fixed and will be released in 0.31
