### ISSUE TITLE
(Bug Report) Problem installing on ubuntu server 22.04

### ISSUE THREAD

**Issue by bonnepioche** [zadam/trilium#4544]
### Trilium Version

0.62.4

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu server 22.04

### Description

Hi,
Just discovered Trilium and imported my notes from Evernote and OneNote. I love it.
I want to host my own Trilium server on Ubuntu server 22.04. 
I choose 'packaged server installation' and:

-  If I use the .tar.xz file, I got this error message while executing trilium-safe-mode.sh:

`error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory`

- If I use the .deb file, I got this error message while installing trilium:
`sudo dpkg -i trilium_0.62.4_amd64.deb 
Sélection du paquet trilium précédemment désélectionné.
(Lecture de la base de données... 74292 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de trilium_0.62.4_amd64.deb ...
Dépaquetage de trilium (0.62.4) ...
dpkg: des problèmes de dépendances empêchent la configuration de trilium :
 trilium dépend de libgtk-3-0 ; cependant :
  Le paquet libgtk-3-0 n'est pas installé.
 trilium dépend de libnotify4 ; cependant :
  Le paquet libnotify4 n'est pas installé.
 trilium dépend de libxtst6 ; cependant :
  Le paquet libxtst6 n'est pas installé.
 trilium dépend de xdg-utils ; cependant :
  Le paquet xdg-utils n'est pas installé.
 trilium dépend de libatspi2.0-0 ; cependant :
  Le paquet libatspi2.0-0 n'est pas installé.
 trilium dépend de libgbm1 ; cependant :
  Le paquet libgbm1 n'est pas installé.
 trilium dépend de libxcb-dri3-0 ; cependant :
  Le paquet libxcb-dri3-0 n'est pas installé.
`

- I then tried to install the dependences by hand:
 sudo apt install libgtk-3-0 libnotify4 libxtst6  xdg-utils libatspi2.0-0  libgbm1 libxcb-dri3-0

but got:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Vous pouvez lancer « apt --fix-broken install » pour corriger ces problèmes.
Les paquets suivants contiennent des dépendances non satisfaites :
 libatspi2.0-0 : Depends: libxi6 (>= 2:1.2.99.4) mais ne sera pas installé
                 Recommends: at-spi2-core (= 2.44.0-3) mais ne sera pas installé
 libgbm1 : Depends: libwayland-server0 (>= 1.15.0) mais ne sera pas installé
 libgtk-3-0 : Depends: adwaita-icon-theme mais ne sera pas installé
              Depends: hicolor-icon-theme mais ne sera pas installé
              Depends: libatk-bridge2.0-0 (>= 2.5.3) mais ne sera pas installé
              Depends: libatk1.0-0 (>= 2.35.1) mais ne sera pas installé
              Depends: libcairo-gobject2 (>= 1.14.0) mais ne sera pas installé
              Depends: libcairo2 (>= 1.14.0) mais ne sera pas installé
              Depends: libcolord2 (>= 0.1.10) mais ne sera pas installé
              Depends: libcups2 (>= 2.3~b6) mais ne sera pas installé
              Depends: libepoxy0 (>= 1.4.3) mais ne sera pas installé
              Depends: libfontconfig1 (>= 2.12.6) mais ne sera pas installé
              Depends: libgdk-pixbuf-2.0-0 (>= 2.40.0) mais ne sera pas installé
              Depends: libharfbuzz0b (>= 2.2.0) mais ne sera pas installé
              Depends: libpango-1.0-0 (>= 1.45.5) mais ne sera pas installé
              Depends: libpangocairo-1.0-0 (>= 1.44.0) mais ne sera pas installé
              Depends: libpangoft2-1.0-0 (>= 1.44.0) mais ne sera pas installé
              Depends: libwayland-client0 (>= 1.20.0) mais ne sera pas installé
              Depends: libwayland-cursor0 (>= 1.14.91) mais ne sera pas installé
              Depends: libwayland-egl1 (>= 1.15.0) mais ne sera pas installé
              Depends: libxcomposite1 (>= 1:0.4.5) mais ne sera pas installé
              Depends: libxcursor1 (> 1.1.2) mais ne sera pas installé
              Depends: libxdamage1 (>= 1:1.1) mais ne sera pas installé
              Depends: libxfixes3 mais ne sera pas installé
              Depends: libxi6 (>= 2:1.2.99.4) mais ne sera pas installé
              Depends: libxinerama1 (>= 2:1.1.4) mais ne sera pas installé
              Depends: libxkbcommon0 (>= 0.5.0) mais ne sera pas installé
              Depends: libxrandr2 (>= 2:1.5.0) mais ne sera pas installé
              Depends: libgtk-3-common (>= 3.24.33-1ubuntu2) mais ne sera pas installé
              Recommends: libgtk-3-bin mais ne sera pas installé
              Recommends: librsvg2-common mais ne sera pas installé
 libnotify4 : Depends: libgdk-pixbuf-2.0-0 (>= 2.22.0) mais ne sera pas installé
 libxtst6 : Depends: x11-common mais ne sera pas installé
```
Looks like, there are some dependencies with X11, which should not be present on a server. Any ideas anyone?

Many thanks and Merry Christmas!

**Comment by zadam** [comment]
Hi, `trilium_0.62.4_amd64.deb` is a desktop build, which explains the missing dependencies.

> error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

I don't remember seeing such problem, but maybe trying to install the libatk might help.

If this fails, there's a docker image which should work for server deployments.

**Comment by bonnepioche** [comment]
Hi!
Let me give it another try.
Thx

**Comment by bonnepioche** [comment]
Hi!
I gave it another try and everything is good. I had choosen the wrong package last time, silly me!
Sorry for the annoyance.
Bug can be closed!
Thx
