### ISSUE TITLE
[Triium.cc] How to reset everything?

### ISSUE THREAD

**Issue by bonnepioche** [zadam/trilium#4548]
### Trilium Version

0.62.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

KDE Neon 22.04

### Description

Dear all,

I have got a paid  trilium.cc domain to sync my Trilium notes between 2 computers. Happy to contribute to this great software!

Sync has been complicated to setup, and while password protecting the notes, looks like I wrote down wrongly the password.

On top of this, I apparently have mis-written the password used for trilium.cc. Weird but let's say the bug is between the chair and the table :)

As I am new to Trilium, that is not a big deal, as I am migrating from evernote (and onenote!) and all my notes are in .exex format so I can re-upload at will. I am still in my evaluation phase and I have not created any new note.

I would therefore like to start completely over: brand new local database (that I know how to do by removing the trilium-data directory), but also reset of trilium.cc database and password. I tried emailing 'admin' and 'trilium' at trilium.cc, but no reply so far (it has been a day only to be fair).

I do realize this is more of a trilium.cc issue, but I raise it as a bug as I would consider that resetting the password on the (hosted) sync server should be user actionable. If it is the case, I have not been able to find the procedure in the documentation.
Feel free to change the classification as you see fit of course.

So,  @sigaloid would you be kind enough to reset everything for domain '[redacted]'? You have an email in your mailbox from the email address used for registration and paiment as confirmation. 

Many thanks,

Pat

**Comment by sigaloid** [comment]
Hi, I did see your mail and was checking through the logs to see if I could identify an issue. I forgot to actually reset it though! I'll do so within a few hours when I get access to a terminal and respond to your mail.

**Comment by bonnepioche** [comment]
Hi, many thanks for your quick reply. Let me know when it is done.

Keep on the good work! Trilium is the best alternative to Evernote that I have found so far (and I have looked at a lot of apps!)

Cheers,

Pat

**Comment by 456dev** [comment]
just letting you know that edit history for github comments are public, you need to explicitly redact / remove the revisions to remove non-public infomation

**Comment by bonnepioche** [comment]
> just letting you know that edit history for github comments are public, you need to explicitly redact / remove the revisions to remove non-public infomation

=> Many thanks, I never noticed! 
Happy new year!
