### ISSUE TITLE
How to bring back highlight/TOC list again ?

### ISSUE THREAD

**Issue by Supreme-Darkness** [zadam/trilium#4552]
### Trilium Version

0.62.4

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 11

### Description

What button do I press to show the highlight list/TOC for the current note? I couldn't find anything which would allow me to access the highlight/TOC list once it has been closed.

**Comment by Nriver** [comment]
Reopen the note or refresh with F5

**Comment by Supreme-Darkness** [comment]
But isn't that a hack ? Shouldn't there be a shortcut for the left pane too just like the right pane ? Or a button ? Almost every pkm system has it.

**Comment by Supreme-Darkness** [comment]
@meichthys I did confuse it with that... multiple times !

**Comment by markbj71** [comment]
Check at https://github.com/zadam/trilium/wiki/Attributes:
Standard labels
The following labels are used for advanced configuration:
toc - #toc or #toc=show will force the table of contents to be shown, #toc=hide will force hiding it.

**Comment by Supreme-Darkness** [comment]
@markbj71 I am looking for a shortcut to open and close right pane on demand, just like left pane. This doesn't help in my purpose.

**Comment by Supreme-Darkness** [comment]
I closed it by mistake

**Comment by zadam** [comment]
Hello, I've added the possibility of defining a keyboard shortcut for toggling the right pane (which includes the TOC). Will be in the next 0.63 release.
