### ISSUE TITLE
(Feature request) Link in canvas object links to other pages from the tree

### ISSUE THREAD

**Issue by samuelsstewart** [zadam/trilium#4553]
### Describe feature

Hey! Would it be possible to add a feature that allows to add links into my canvas diagram objects that when clicked open up the corresponding page from the tree in Trillium and not browser? 
![image_2024-01-02_135234149](https://github.com/zadam/trilium/assets/78820335/8d6761d3-ecdd-408f-a571-f098292f038b)

(not a programmer, I'm just a new fan of Trillium)

**Comment by Nriver** [comment]
Create a link like this /#root/your_note_id

**Comment by samuelsstewart** [comment]
> Create a link like this /#root/your_note_id

It works, thank You!
