### ISSUE TITLE
(Bug report) Missing api in /etapi/etapi.openapi.yaml

### ISSUE THREAD

**Issue by coldwinds** [zadam/trilium#4559]
### Trilium Version

v0.62.4

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Win10

### Description

For example, can not find attachments operation in

https://github.com/zadam/trilium/blob/master/src/etapi/etapi.openapi.yaml

which exists in

https://github.com/zadam/trilium/blob/master/src/etapi/attachments.js

**Comment by zadam** [comment]
Hello, you're right, I backfilled the API spec for attachments.
