### ISSUE TITLE
(Bug report) The edited content was not saved correctly

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#4560]
### Trilium Version

0.62.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows10

### Description

I've encountered this situation several times. I create a new note. Then write the content I need to record in it. But when I switch to another page or refresh, I find that the content of the note is not saved correctly. For example, I wrote ten paragraphs, but only the first two paragraphs were recorded, and the rest of the content was not saved. I also didn't encounter any error prompts. I want to know what caused this? Because of this problem, I can't reproduce it correctly either. If possible, please tell me what part of the log I should provide to determine the problem the next time I encounter it?

**Comment by Joackk** [comment]
I encountered this problem using the desktop client, but other users have reported encountering the same problem on the web version.

**Comment by Joackk** [comment]
> I have seen this before on the web client. If the web client sits idle for a long time, the user may not be logged in, even though the page is loaded and The user is able to compose text, But when trying to save the text, it will fail because there is no connection to the server. For me, usually logging back in works.

I have been using the local client, so there should be no login issues.

**Comment by hulmgulm** [comment]
I've seen this too with the Windows 0.62.3 client.

**Comment by chncho** [comment]
It appears to me too, when I use the linux  0.60, and an older version too

**Comment by Joackk** [comment]
@hulmgulm @chncho It seems that everyone has encountered this problem before. Can you reproduce it? Or there may be a log that records a portion of the time

**Comment by zadam** [comment]
Historically these issues were caused by CKEditor crashing (silently) and the not producing "update" events.

However, in recent versions there's a "watchdog" which should detect this crash and re-initialize CKEditor transparently. If you have a reproduction case, please send it to me.

**Comment by Joackk** [comment]
> Historically these issues were caused by CKEditor crashing (silently) and the not producing "update" events.
> 
> However, in recent versions there's a "watchdog" which should detect this crash and re-initialize CKEditor transparently. If you have a reproduction case, please send it to me.

What do photocopies refer to? Watchdog? Or the lost notes?

**Comment by Potjoe-97** [comment]
I've also encountered the issue several times since April 2023 (first time I noticed it). It is hard to reproduce, since it happens randomly. There is no apparent signs that the note is not being recorded, just going back and forth different notes reset it to a previous state with no indications in note revisions.

**Comment by Joackk** [comment]
> I've also encountered the issue several times with local client (both linux and windows) several times since April 2023 (first time I noticed it). It is hard to reproduce, since it happens randomly. There is no apparent signs that the note is not being recorded, just going back and forth different notes reset it to a previous state with no indications in note revisions. For a while, I had suspicions with the sync to the server, since when disabled, the issue never occured. I am now used to keep sync disabled, and acticate it once in a while in the settings to save db.

I am the same, only occasionally synchronizing, but I also encounter this problem when I am not synchronized. So it may not be a synchronization issue

**Comment by Lightirius** [comment]
I had a similar problem that I traced back to a broken widget I was exerimenting with at some point. It stopped happening after I removed "#widget" attribute from it

**Comment by Joackk** [comment]
@Lightirius Which widget is it? I also installed some plugins, but there are no error messages

**Comment by Lightirius** [comment]
@Joackk It was my own. I was experimenting with writing a widget, left it enabled in a broken state and forgot about it. It was never finished and publicly available.

Found out that it's still enabled because of errors in the Dev Tools console

**Comment by Joackk** [comment]
> @Joackk It was my own. I was experimenting with writing a widget, left it enabled in a broken state and forgot about it. It was never finished and publicly available.
> 
> Found out that it's still enabled because of errors in the Dev Tools console

I see, maybe it has nothing to do with the plugin, I have not been receiving the plugin error, but sometimes I have encountered this problem

**Comment by Potjoe-97** [comment]
I have encountered this problem whereas I do not use any plugin.

**Comment by Joackk** [comment]
As of now, I'm experiencing this troublesome issue in both the historical version and the current latest version. Since there are no alerts or errors, it's hard for him to be caught wondering if there are any unsaved notes of mine

**Comment by Joackk** [comment]
I think I know the cause of the problem, which seems to be an auto-read-only problem. When a newly created note is edited for the first time, if it exceeds the auto-read-only size, subsequent edits will not take effect. I haven't had this problem in a while after I made the read-only notes setting very large
