### ISSUE TITLE
(Bug report) Duplicated shortcut default value

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#4570]
### Trilium Version

0.62.5

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Manjaro

### Description

The default keyboard shortcut for `Reset zoom level` and `Activates the last tab in the list` are both `Ctrl+0`. Pressing `Ctrl+0` will trigger both shortcuts.

**Comment by zadam** [comment]
Thanks for the report, removed the "Activates the last tab in the list" since that was added recently. This is just the default and won't modify existing documents.
