### ISSUE TITLE
(Bug report) Canvas image cannot be loaded (404) in shared note when note title contains '/'

### ISSUE THREAD

**Issue by deajan** [zadam/trilium#4578]
### Trilium Version

0.62.5

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Almalinux 9.3

### Description

Some of my canvas notes didn't show up properly in a shared note, so I investigated, and found that `/` character isn't escaped in the URL tofetch the canvas image. Same applies to `\` character, and probably others.

## Notename containing `/` 
![image](https://github.com/zadam/trilium/assets/4681318/1806a1cb-ded8-4b55-b9a4-d82401f2e4e6)
## Shared image cannot be loaded (404) in browser:
![image](https://github.com/zadam/trilium/assets/4681318/1da36b75-955a-4246-9f71-5c54ac3b31b1)

## Sane note name
![image](https://github.com/zadam/trilium/assets/4681318/94de310f-c272-44ed-905d-fc8107032911)
## Produces sane shared output
![image](https://github.com/zadam/trilium/assets/4681318/71aaa060-ca57-4184-8bf6-66cee83b8a0e)

### Error logs

Navigator inspection log when note is called `test note from 09/01/2024`
```
GET https://notes.local/share/api/images/zf1jTwY0N1kL/test%20note%20from%2009/01/2024?2024-01-09%2013:52:17.925Z 404
```

**Comment by zadam** [comment]
Hello, thank you for reporting this bug, fixed.
