### ISSUE TITLE
[FEATURE REQUEST] Backup the Data Base in something like dropbox

### ISSUE THREAD

**Issue by tvortsa** [zadam/trilium#459]
For bug reports, please mention **version of the application** and include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
What's stopping you to setup your dropbox or whatever app to backup your trilium data dir? Not sure what should be done here ...

**Comment by tvortsa** [comment]
I believe that trilium is the best solution for schoolchildren, but they often don’t even quite understand what a file is and the path to the file)

**Comment by zadam** [comment]
Closing as I consider this to be out of scope for Trilium.
