### ISSUE TITLE
(Bug report)   top_right pin icon click display issue report/fix

### ISSUE THREAD

**Issue by connectluole** [zadam/trilium#4595]
### Trilium Version

0.62.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

windows10 

### Description

hello @zadam,

I hit a display issue in the trilium win_app(0.62.5), which is :

the app top right corner's Pin icon will display like below pic shown , which happens once i click down on it .

![image](https://github.com/zadam/trilium/assets/16472308/e373cc50-0953-4a07-82c5-785286c3735a)

2. throuh debug , we ( with my girlfriend ) found this is due to one css error,which is  bootstrap.min.css :

![image](https://github.com/zadam/trilium/assets/16472308/31fe0c7f-9bb3-4ef4-aed2-be40154b8672)

3. some operation gif like below

![display_issue](https://github.com/zadam/trilium/assets/16472308/64dfdeaf-75e0-4220-ade2-05b8d2938f97)

**Comment by connectluole** [comment]
For the work around to temp fix it , i just add below line to my css note, ( just create a code note ,type is css, then add the attribute #appCss ):
```
:root {
    /* fix the pin icon click display issue */
    .btn.focus,.btn:focus {
        box-shadow: None;
    }
}
```

then it's ok know

**Comment by zadam** [comment]
Hi, thanks for the report, fixed.
