### ISSUE TITLE
[FEATURE REQUEST] Add to editor : "task list"

### ISSUE THREAD

**Issue by tvortsa** [zadam/trilium#460]
Its will be useful to add "task list" to triliun editor ^^

![image](https://user-images.githubusercontent.com/78345/54867395-d07d1b00-4d90-11e9-9188-b67b907575fd.png)

**Comment by tsinhi** [comment]
i also need it.

**Comment by zadam** [comment]
Cool artwork :+1: This is already tracked in #264 so closing as a duplicate.
