### ISSUE TITLE
(Feature request) PWA behind authorization

### ISSUE THREAD

**Issue by Lightirius** [zadam/trilium#4611]
### Describe feature

I have Trilium server instaled behind reverse proxy with centralized authorization for all of my services.
Right now I don't have a button to install Trilum as PWA in Chrome.

Access to manifest file https://<hostname>/manifest.webmanifest requires authorization, but authorization cookie is not sent with this request by the browser. I don't want to disable authorization on this path

I am not a web developer but based on this documentation https://developer.mozilla.org/en-US/docs/Web/Manifest there must be a crossorigin="use-credentials" attribute on the manifest link for it to work behind authorization.
If I manualy modify the link attribute on the web page in Chrome Dev Tools - I can install PWA and it seems to work fine after that

**Comment by Tibael** [comment]
Same trouble here 

If a developper want to fix this I succed to do so by modifying : 
src/views/desktop.ejs, line 6 to : `<link rel="manifest" crossorigin="use-credentials" href="manifest.webmanifest">`
src/views/mobile.ejs, line 9 to : `<link rel="manifest" crossorigin="use-credentials" href="manifest.webmanifest">`

And with this modifications icon doesn't load anymore so I modify this : 
src/public/manifest.webmanifest, line 11 to 20 : 
```
{
      "src": "favicon.ico",
      "sizes": "180x180 512x512",
      "type": "image/x-icon"
}
```

**Comment by zadam** [comment]
I've made changes as you suggested.
