### ISSUE TITLE
Quick copying of images

### ISSUE THREAD

**Issue by FordringWang** [zadam/trilium#4614]
### Describe feature

Dear zadam,
Copy images to export notes is very difficult, I have an example my friend asked me for a note and this note has a lot of pictures. I want to quickly copy and paste to the word document, I found that images could not be copied, I just copy the images one by one I think this is a big job...I haven't thought any good way for this yet. It would be even greater if future Trilium Notes could support quick copying of images, I really like this note by the way.

**Comment by zadam** [comment]
Hello, 0.63 (currently in beta) allows you to copy the image via a context menu:

![](https://github.com/zadam/trilium/assets/617641/94873f27-ccb9-46a9-ba6c-484add829ad0)

**Comment by FordringWang** [comment]
> Hello, 0.63 (currently in beta) allows you to copy the image via a context menu:
> 
> ![](https://private-user-images.githubusercontent.com/617641/300601626-94873f27-ccb9-46a9-ba6c-484add829ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODIyMTksIm5iZiI6MTcwNjU4MTkxOSwicGF0aCI6Ii82MTc2NDEvMzAwNjAxNjI2LTk0ODczZjI3LWNjYjktNDZhOS1iYTZjLTQ4NGFkZDgyOWFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMjMxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWU5ODUzMzcxNTYzZWE2Mjc1ZTE1MjU4MThlOTA4Yjg4ZjgyNzdhYTZhYmI2ZDg5MzQ5NTJjN2U2NTIzNGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.plL-nLRToEPMmdZT-xBINaKzKK1JH-YiTpQX8Y9zlsQ)

Dear zadam, Thanks for share information.

**Comment by Nriver** [comment]
You can use the `share` feature in Trilium. The shared note can be open in your browser and you can copy and paste it to word document effortlessly.

**Comment by FordringWang** [comment]
> You can use the `share` feature in Trilium. The shared note can be opened in your browser. Then you can copy the whole note with mixed texts and images and paste them into word document effortlessly.

Dear Nriver, this is a good idea I'll try, Thank you ! If Trilium can just use Ctrl + A, Ctrl + C  quickly copy all information like Joplin notes, I think this may be a useful feature.
