### ISSUE TITLE
(Bug report) Server continues to report sync errors on login

### ISSUE THREAD

**Issue by dpguoming** [zadam/trilium#4615]
### Trilium Version

server: docker-0.62.6-latest
client: 0.62.6

### What operating system are you using?

linux

### What is your setup?

Server and Client access

### Operating System Version

centos7

### Description

Server continues to report errors
clients cannot async well, but website can return right things.

### Error logs
- clients

```
Sync in progress
Sync has been correctly set up. It will take some time for the initial sync to finish. Once it's done, you'll be redirected to the login page.
Outstanding sync items: 0
```

- server

```js
Sync failed: 'Sync server has instance ID 'xpn8AyG9ce6c' which is also local. This usually happens when the sync client is (mis)configured to sync with itself (URL points back to client) instead of the correct sync server.', stack: Error: Sync server has instance ID 'xpn8AyG9ce6c' which is also local. This usually happens when the sync client is (mis)configured to sync with itself (URL points back to client) instead of the correct sync server.
    at doLogin (/usr/src/app/src/services/sync.js:110:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async login (/usr/src/app/src/services/sync.js:93:12)
    at async /usr/src/app/src/services/sync.js:35:37
    at async Object.doExclusively (/usr/src/app/src/services/sync_mutex.js:13:16)
    at async sync (/usr/src/app/src/services/sync.js:27:16)
```

**Comment by zadam** [comment]
Hello, as the error indicates, this is caused by the misconfiguration.

Make sure that on your **server instance**, the field "server instance address" is empty:

![](https://github.com/zadam/trilium/assets/617641/a3d25e86-81fb-48d2-b462-569ea1178dee)

**Comment by dpguoming** [comment]
Now it's stuck in the setup interface, where can I modify it
<img width="703" alt="image" src="https://github.com/zadam/trilium/assets/93116962/69e69f71-0219-44b8-8e20-d44630be5373">

**Comment by foozzi** [comment]
> Now it's stuck in the setup interface, where can I modify it <img alt="image" width="703" src="https://private-user-images.githubusercontent.com/93116962/300670590-69e69f71-0219-44b8-8e20-d44630be5373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NzUxMzIsIm5iZiI6MTcwNjY3NDgzMiwicGF0aCI6Ii85MzExNjk2Mi8zMDA2NzA1OTAtNjllNjlmNzEtMDIxOS00NGI4LThlMjAtZDQ0NjMwYmU1MzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA0MjAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMGZmYzY1ZTM1MDA1OGU4ZDhmZTQxNzFiNmM4ODIwOTMyMTdkNGJjY2YzNzhkMzUxZjcyNGYyOWJjMDFlOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._BwbTP7IzvwUEL8e2Vte8zR_s8p3j2S3Bg4OwiLKhF8">

Hi,
You can edit it in the Trilium database located at this path (if you are using Mac or Linux) - `/home/USER/.local/share/trilium-data/backup/` 

Then open a database file with name like `backup-*.db`

In the `options` table you should find the necessary fields:
![Screenshot_20240130_232333](https://github.com/zadam/trilium/assets/1178208/1baa7242-c3c2-462f-9639-302dbce1c3b7)

For editing a `sqlite` database, you can use - [sqlbrowser](https://sqlitebrowser.org/)

**Comment by zadam** [comment]
I'm too late, but since the client DB is empty, I'd just delete the `trilium-data` and start the sync process again from scratch.

**Comment by dpguoming** [comment]
it works, very thx!
