### ISSUE TITLE
Feature Request: Add superscript and subscript support to "Type: Text"

### ISSUE THREAD

**Issue by PostPollux** [zadam/trilium#462]
I think it would be very helpful, if it were possible in the main md editor (Type: Text) to mark some stuff as superscript or subscript.

I wanted to take some notes of a Cryptography lesson and there it would be very helpful if I coud write stuff like k<sub>e</sub> and k<sub>d</sub>. But I didn't find a way to do that in Trilium. Here on Github it is possible by just use `<sup> some text </sup>` or `<sub> some text </sub>`. 

E.g.:  test<sup> some text</sup>, test<sub> some text</sub>

Just exactly like here would be perfect: https://ckeditor.com/docs/ckeditor5/latest/features/basic-styles.html

**Comment by zadam** [comment]
Hi. just added super/sub script, will be in 0.31

**Comment by PostPollux** [comment]
Now that was fast! Awesome! Thank you so much. I really love Trilium so far. It is exactly what I was looking for for a long time. You are the man!
