### ISSUE TITLE
Enabling TLS causes "unable to connect"  in browser because privkey.pem not found

### ISSUE THREAD

**Issue by PDiracDelta** [zadam/trilium#4623]
### Trilium Version

0.62.5

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

5.15.0-92-generic #102-Ubuntu SMP

### Description

I run trilium server via docker on raspberry pi.
I can access trilium via web browser if TLS is disabled.

After enabling TLS in `/mnt/hdd/trilium/config.ini`, the connection via browser is not possible (immediately Firefox says "_can’t establish a connection to the server at my.web.server:8080_" ). Here is my config.ini excerpt. Note: there is also another service making use of these keys (on same domain name but different port):
```
# true for TLS/SSL/HTTPS (secure), false for HTTP (insecure).
https=true
# path to certificate (run "bash bin/generate-cert.sh" to generate self-signed certificate). Relevant only if https=true
certPath=/mnt/hdd/trilium/certs/cert.pem
keyPath=/mnt/hdd/trilium/certs/privkey.pem
```
Logs show nothing(!?)

This is not about the Trilium app access (which also doesn't work - despite using `export NODE_TLS_REJECT_UNAUTHORIZED=0`) but purely about browser access. I assume fixing browser access will also resolve the app access issue.

**Comment by PDiracDelta** [comment]
UPDATE: it seems I had to access the Docker logs, not the trilium/logs logs...
It seems it cannot find my privkey.pem
I do not understand why as it is in the trilium folder? Can Docker not see it?

**Comment by sigaloid** [comment]
You have to manually allow docker to access outside files and folders - search docker volumes for more info.

**Comment by PDiracDelta** [comment]
Fixed - thanks! 
Solution: I had to use the **DOCKER** path, not the **HOST** path for the files involved.

**Comment by exitwounds1977** [comment]
> h, not the **HOST** path for the files involved.

what's DOCKER path is?
