### ISSUE TITLE
The code is too difficulty for me to read(understand).Can you give me a simple one?

### ISSUE THREAD

**Issue by ffywhxf** [zadam/trilium#463]
I just want run in windows without network sever.
Just using it for a Desktop software.  And i want to translate it to  another language.
Can you give me a simple code that i can Electron it in a simple way.  e.g the code just include main.js & index.html & package.json.
I translated it , I'll share it.
Thanks.

**Comment by zadam** [comment]
Not sure what you mean by simpler code. But UI translation (or any localization) is not supported at the moment.
