### ISSUE TITLE
Excuse me, how can I make it support multiple languages?

### ISSUE THREAD

**Issue by denisding** [zadam/trilium#4638]
### Describe feature

Excuse me, how can I make it support multiple languages?
For example, I want to add Chinese support. lan code is zh_CN. What should I do？
Think you！

**Comment by Nriver** [comment]
Dynamic language switch is not possible.

If you want a chinese version, check here.  https://github.com/Nriver/trilium-translation

**Comment by ForumLiker** [comment]
@Nriver Can you specify the location of the translation file? I want to translate into another language
