### ISSUE TITLE
(Bug report) Unable to search between text in different formats

### ISSUE THREAD

**Issue by ckw-123** [zadam/trilium#4661]
### Trilium Version

0.63.2-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 version 1809

### Description

text:  abcabc
note search "bca"  OK

Format first "abc" ：
[span style="color:hsl(120, 75%, 60%);"]
		abc
[/span]
abc

or

[span class="text-big"]
		abc
[/span]
abc

or

[span style="background-color:hsl(0, 75%, 60%);"]
		abc
[/span]
abc

[=<  ,  ]=>
search "bca" ，“No notes have been found for given search parameters.”

**Comment by zadam** [comment]
Hello, thank you for reporting this problem, it should be fixed in the next 0.63 release.
