### ISSUE TITLE
Cant find the default password.

### ISSUE THREAD

**Issue by Pin-Lui** [zadam/trilium#4663]
### Trilium Version

latest

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Portainer / Docker

### Description

i pulled the img in portainer. When visited the Trilium page it asked for a password. I searched way too long and found nothing. 
where is the default password?

**Comment by Nriver** [comment]
There is no default password.

**Comment by Pin-Lui** [comment]
yeah I'm kind of an idiot. i had trillium installed a long time ago, and when i reinstalled the container it automatically took the old configs. so the password was one of my passworts. yaiks

**Comment by Pin-Lui** [comment]
i had Trilium installed a long time ago, and when I pulled the container it took the old configs with the set password. I'm kind of an idiot I'm sorry xD
