### ISSUE TITLE
(Bug report) To-do list checkboxes are invisible on the dark theme

### ISSUE THREAD

**Issue by st3iny** [zadam/trilium#4672]
### Trilium Version

0.63.3 (Flatpak)

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

6.1.74-gentoo-x86_64

### Description

The checkboxes on to-do lists are not visible since updating to 0.63.3. They looked fine right before the update. I updated from 0.62.6 to 0.63.3.

Trilium is installed via Flatpak in a KDE desktop environment.

| Bug | Theme settings |
| --- | --- |
| ![grafik](https://github.com/zadam/trilium/assets/1479486/76aa5793-10bd-48c5-9a46-37df4c5dec90) | ![grafik](https://github.com/zadam/trilium/assets/1479486/75fbb354-5a43-49e2-bd29-67813ccc8323) |

**Comment by diyoyo** [comment]
Same bug here. All the previous unchecked boxes are invisible too, not only the newly created ones.

**Comment by cbop-dev** [comment]
Same problem here, in 0.63.3 on Linux Desktop version and web server, and only in dark mode. NB: checkboxes look fine in Light and Steel Blue themes. 

Opening dev tools and inspecting shows the CSS properties include `1px solid #333` which is the problem, since `#333` is the same as the dark background (or very close to it): `rgb(51,51,51)`.

**Comment by cbop-dev** [comment]
Correction: the problem is with the _unchecked_ box in dark mode, and is caused by a combination of the checkbox border color being `#333` and the background of the same being transparent, while the` <body>` background is also `#333`. Perhaps the checkbox background is supposed to be (off-)white?

> Same problem here, in 0.63.3 on Linux Desktop version and web server, and only in dark mode. NB: checkboxes look fine in Light and Steel Blue themes.
> 
> Opening dev tools and inspecting shows the CSS properties include `1px solid #333` which is the problem, since `#333` is the same as the dark background (or very close to it): `rgb(51,51,51)`.
