### ISSUE TITLE
Note tree context menu closes immediately (Firefox-Ubuntu)

### ISSUE THREAD

**Issue by parsehex** [zadam/trilium#468]
Trilium 0.30.5
I don't think logs are necessary since this is a frontend issue.

In the latest Firefox 66.0.1 on Ubuntu 18.10 when you right-click any note in the left sidebar the context menu opens for a fraction of a second and closes. Holding down right click keeps the menu open until releasing the button.

Nothing gets logged in the console when this happens.

The issue seems to only be in a recent version of Firefox on Linux. Firefox 63 (the version Ubuntu 18.10 ships with) works normally as well as Chrome. Tested in Windows 10 and no browser has this issue.

This was in a fresh install of Trilium from the stable branch and a new Firefox profile.

Let me know if there's any additional info I can provide.

**Comment by zadam** [comment]
Thank you for reporting this issue - I fixed it and will release it soon.
