### ISSUE TITLE
Unable to sync another device

### ISSUE THREAD

**Issue by MatejPetrik007** [zadam/trilium#4683]
### Trilium Version

latest(0.63.3)

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Kubuntu 23.10

### Description

i setup the server and added pc(windows) wanted to add notebook(Kubuntu) but i recive a error log but i am able to connect to the server via Firefox password is setted up

### Error logs

Sync server handshake failed, error: Request to POST http://192.168.100.100:8000/api/login/sync failed, error: 400 Bad Request Sync login credentials are incorrect. It looks like you're trying to sync two different initialized documents which is not possible.

**Comment by Nriver** [comment]
`two different initialized documents` is the problem. You should initialize on server, then sync with server on client's first run.

You need to delete client's database to solve this.

**Comment by MatejPetrik007** [comment]
resolved by reinstall app and also client's database thx for help

**Comment by gasmsy2023** [comment]
Please  how do you start trilium afresh on windows? I had started it using the "I am a new user option". Now establishing sync throws an error and it is not successful. I have deleted the unzipped folder, cleaned the registry for all trilium keys and yet when I start the program, it opens on the last windows the previous version closed.

**Comment by Nriver** [comment]
You can delete the data directory if you are sure there is nothing important in it. https://github.com/zadam/trilium/wiki/Data-directory

**Comment by gasmsy2023** [comment]
Thanks a million. Synced like magic.
