### ISSUE TITLE
escaping of @ symbol not working

### ISSUE THREAD

**Issue by ajcallegari** [zadam/trilium#4684]
### Trilium Version

0.62.5

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

Ventura OS X 13

### Description

When taking notes on recommender systems I need to talk about metrics like precision @K.  This notation automatically created some sort of link.  So I tried escaping by enclosing in quotations, which did not work.  I then escaped using backslash \, which works to prevent link formation but is not rendered correctly (the backslash remains visible but should be invisible).

**Comment by zadam** [comment]
Closing in favor of #4692
