### ISSUE TITLE
(Bug report) Invisible tick boxes and weird type cursor

### ISSUE THREAD

**Issue by dasrocky** [zadam/trilium#4686]
### Trilium Version

0.63.3

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu 22.04.3 LTS Pro

### Description

I have noticed weird issues in trillium notes deployment.
Bugs noticed:
* Invisible round border for tick box
* Spacing issue on empty text after tick box 
* Typing Cursor weird line

![image](https://github.com/zadam/trilium/assets/61043834/aa7642d4-2ab9-444c-aaa4-3290efe0788b)

System Spec:
* PC: Beelink GTR 7 Pro
* OS: Ubuntu 22.04.3 LTS Pro
* RAM: 32 GB
* Deployment: Docker 

### Error logs

![image](https://github.com/zadam/trilium/assets/61043834/201d8253-dfeb-4ee1-a2bd-e2125b878ac2)

**Comment by dasrocky** [comment]
I have noticed that i am not facing similar issue with light and steel blue theme. So for now I am switching to theme steel blue. 
![image](https://github.com/zadam/trilium/assets/61043834/6ea085ce-9eb1-4020-82e9-911a8881e51a)
![image](https://github.com/zadam/trilium/assets/61043834/5520ef8d-854f-4c52-8f24-d70d1c530517)

**Comment by Nriver** [comment]
It's been fixed in https://github.com/zadam/trilium/pull/4676. You can either wait for the next release.

**Comment by diyoyo** [comment]
When is the next release due?
