### ISSUE TITLE
Lost information in protected notes while switching versions.

### ISSUE THREAD

**Issue by terafo** [zadam/trilium#469]
Consistency check error. Couldn't see content of protected notes on 30.0.6(and only on 30.0.6). After removing protection from notes can't see information in previously protected notes. Everything worked fine until 30.0.6 was introduced.
[log.zip](https://github.com/zadam/trilium/files/3025441/log.zip)

**Comment by jaroet** [comment]
I have the same issue. Nothing is shown when entering protected session. 
Very inconvenient :-(

**Comment by zadam** [comment]
Hello, 0.30.6 introduced a bug in electron (desktop) version. There's no data loss. You can go back to 0.30.5, I will release new version with fix soon.

@terafo you have also secondary issue with the data consistency, I will send further instructions on that.

**Comment by zadam** [comment]
@terafo please update to 0.30.7 which should fix the inconsistency. Detailed explanation is on the [release page](https://github.com/zadam/trilium/releases/tag/v0.30.7).

**Comment by jaroet** [comment]
Thanks, data is available again ... 👍
