### ISSUE TITLE
(Bug report) js error Parsing error: The keyword 'const' is reserved

### ISSUE THREAD

**Issue by yoyoset** [zadam/trilium#4696]
### Trilium Version

0.63.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

windows11+docker

### Description

word count widget , there is a error there ,and also the Custom request handler widget has the same error.
![2024-03-15 211655](https://github.com/zadam/trilium/assets/114843259/280d4a0a-48f9-4d99-9c58-4b6ecc9ab99a)

**Comment by yoyoset** [comment]
This is not a bug. The functionality is working normally.

**Comment by zadam** [comment]
Trilium has a builtin ESLint for JS notes. These are hints, it doesn't mean real errors. I'm not sure why ESLint thinks this is wrong.

**Comment by xiongzhp** [comment]
> This is not a bug. The functionality is working normally.

But the word count widget is not working.

**Comment by eliandoran** [comment]
Fixed in TriliumNext in https://github.com/TriliumNext/Notes/pull/1092.
