### ISSUE TITLE
Dark Theme No Scrollbar, No Scrollbar visible  with solution

### ISSUE THREAD

**Issue by CobriMediaJulien** [zadam/trilium#4699]
### Trilium Version

0.63.0-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win 11

### Description

Hello together,

in case sb. wonders why his sidebar is not shown when he does access trillium via browser.

The trees sidebarbar´s css is not set correctly. The scrollbar has the wrong backgroundcolor:

`
--scrollbar-background-color: #333;
`

Css should be:

`
    --scrollbar-background-color: #666;

`
![NoScrollbar](https://github.com/zadam/trilium/assets/56324041/c93648ff-7714-4b2c-bb9e-6237eb5f0d5b)

**Comment by zadam** [comment]
Hello, have you used desktop app or browser? (which one?) I can't replicate your behavior ...

**Comment by CobriMediaJulien** [comment]
I used the browser (Brave, Edge). Maybe It´s the server application. I can check the version later. The color of the scrollbar in the desktop app are correct. The problem appeared only in the browser. I will see if i can replicate it and post again.

**Comment by CobriMediaJulien** [comment]
Here is my Info about the server Version:

![image](https://github.com/zadam/trilium/assets/56324041/d4c74670-4ea0-4dc1-b217-f13dce69abf1)

Build date:	2024-01-04T00:49:06+01:00
Build revision:	[394530921e3f7ddd852fa4ceb1ac4585447df35e]

I can replicate the problem for me in dark mode. Light mode works normal. It´s a minor thing anyway. I just wanted to inform Users.

In my server version the variable for the scrollbar background color is just set to 333 instead of 666:

![image](https://github.com/zadam/trilium/assets/56324041/9148468e-f2fe-4f10-be86-1259dd5adb02)
