### ISSUE TITLE
 error: 401 Auth request time is out of sync, please check that both client and server have correct time. 

### ISSUE THREAD

**Issue by Gurdt55lol** [zadam/trilium#4704]
### Trilium Version

v0.63.3

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 Home, however same issue on ubuntu

### Description

Error started happenind when I migrated from V.0.60.0 to 0.63.3

So. I have trilium notes desktop app installed and it refuses to sync with the server. ( Running on docker behind traefik )

Error code: `Error: Request to POST https://trilliumnotes.duckdns.org/api/login/sync failed, error: 401  Auth request time is out of sync, please check that both client and server have correct time. The difference between clocks has to be smaller than 5 minutes.`

How ever I have checked the date on the server, docker container and the client systems and they are just fine. Also the web interface is working so I can manage a while with this.

This is literally only thing in my homelab that I use daily. Please help 🤞

### Error logs

[when trying reinstall.txt](https://github.com/zadam/trilium/files/14640927/when.trying.reinstall.txt)
[before reinstall attemp.txt](https://github.com/zadam/trilium/files/14640928/before.reinstall.attemp.txt)
ub.com/zadam/trilium/files/14640920/when.trying.reinstall.txt)

**Comment by Gurdt55lol** [comment]
Anyone?

**Comment by Nriver** [comment]
As the error message says, your time is not correct. You can use [ntpdate](https://en.wikipedia.org/wiki/Ntpdate) to correct your machine's time.

**Comment by Gurdt55lol** [comment]
It basicly gets stuk in the sync in progress part of the setup

**Comment by sigaloid** [comment]
You can try deleting the server's database and restarting sync. Or manually copying the database.db to the server, to "kickstart" the sync..

**Comment by Gurdt55lol** [comment]
Going to try it

**Comment by Gurdt55lol** [comment]
You were right about the time thing. Windows had screved up the timing and it also affected to my wsl. Restart fixed it.
