### ISSUE TITLE
(Bug report) #hideHighlightWidget doesn't work in v0.63.3

### ISSUE THREAD

**Issue by ckw-123** [zadam/trilium#4709]
### Trilium Version

v0.63.3

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 1809 64bit

### Description

#hideHighlightWidget doesn't work in v0.63.3.

**Comment by zadam** [comment]
Hmm, can you show your setup (how you define attribute and the shown panel)? Just tried it and seems to work fine.

**Comment by ckw-123** [comment]
Sorry, my mistake, I thought #hideHighlightWidget could control both “Highlights List” and “Table of Contents”.

**Comment by ckw-123** [comment]
#hideHighlightWidget works fine.
