### ISSUE TITLE
(Bug report) Script #run=frontendStartup not working

### ISSUE THREAD

**Issue by phanhavn** [zadam/trilium#4712]
### Trilium Version

0.63.3

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Ubuntu

### Description

I created simple script to change the menu icon

`$( "div.tree:not('.fancytree-ext-filter.fancytree-ext-filter-hide') li.fancytree-lastsib ul li[role='treeitem'] span.fancytree-custom-icon" ).each(function(  ) {
		$(this).css("color", '#' + Math.floor(Math.random()*16777215).toString(16));
});`

And set properties: #run=frontendStartup
While run directly, the script effect. But it not working while I refresh the page.
Do I missed something? Please help to check.
Thank you so much!

### Error logs

no error log

**Comment by Nriver** [comment]
Interesting idea :)

The code works for me when refresh with `ctrl + r` and `f5`.

**Comment by phanhavn** [comment]
> Interesting idea :)
> 
> The code works for me when refresh with `ctrl + r` and `f5`.

Thank you,
I've checked. It's not bug, It's my failure, I built wrong way. So sorry.
