### ISSUE TITLE
(Bug report) Math not showing in shared page

### ISSUE THREAD

**Issue by Zeleznyj** [zadam/trilium#4713]
### Trilium Version

0.63.3

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Local running on Ubuntu 22.04 using flatpak, server running on Debian 12 using Docker

### Description

Page containing math show correctly on the server itself, but when sharing the page, the math is not rendered and instead just shown as latex commands.

The issue seems to be in loading the katex related assets, as shown in the attached log file.

The server is running under domain/trilium and I think the issue is related to that. The path for katex assets starts with ../../assets, which translates to domain/assets... whereas the correct path is domain/trilium/assets.

### Error logs

[console-export-2024-3-26_11-27-44.txt](https://github.com/zadam/trilium/files/14756900/console-export-2024-3-26_11-27-44.txt)

**Comment by zadam** [comment]
Do you have a non-docker installation? Perhaps you didn't run `npm install` after upgrade?

Math seems to work fine for me:

![](https://github.com/zadam/trilium/assets/617641/d520ce13-9c23-465d-b4c8-5a5117baf332)

**Comment by Zeleznyj** [comment]
I'm using docker. You can see the shared page where the math doesn't work [here](https://zeleznyj.fzu.cz/trilium/share/9ndg0Anu8V23). With the katex.min.js for example the problem is that it's loading the asset from https://zeleznyj.fzu.cz/assets/v0.63.3/node_modules/katex/dist/katex.min.js, but the correct path is https://zeleznyj.fzu.cz/trilium/assets/v0.63.3/node_modules/katex/dist/katex.min.js.

**Comment by zadam** [comment]
I see, I didn't notice the path segment "trilium". Should be fixed in the next patch release.
