### ISSUE TITLE
How to render markdown?

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#472]
Hi

How do I render a markdown page in Trilium wihtout exporting and opening in another viewer?

thanks

**Comment by zadam** [comment]
Out of the box this is not supported, but it should be possible to write a plugin (script) which would do it for you.

**Comment by gerroon** [comment]
Thanks, I am not skilled enough to do that. It would be nice if you consider this as a feature request.

**Comment by pcause** [comment]
not sure what you mean by render markdown.

**Comment by gerroon** [comment]
As in seeing the final result of the page instead of the actual markdown version

**Comment by nhaouari** [comment]
You can past Markdown directly on your page.
![image](https://user-images.githubusercontent.com/9850722/56411231-5e5d0080-6280-11e9-9b33-d2b90599a361.png)

**Comment by felipefm** [comment]
Taking advantage of the topic, does Trillium accept TOC marking?

**Comment by zadam** [comment]
Not sure what "TOC marking" is, but [CKEditor does not support Table of Contents](https://github.com/ckeditor/ckeditor5/issues/966) yet.

**Comment by zadam** [comment]
TOC has been implemented recently, rendering markdown is out of scope, closing.

**Comment by testbenchcc** [comment]
I'm aware of the button on the toolbar, as @nhaouari mentioned, but it would be helpful to have the option to render actual markdown notes without needing to convert or duplicate.

It could be done similarly to viewing a note's source in the top-right menu dropdown. Even better, it could open in a split window.

**Comment by Nriver** [comment]
You can try this one https://github.com/zerebos/Trilium-MarkdownPreview, it renders the markdown side by side.

More interesting plugins can be found here https://github.com/Nriver/awesome-trilium.
