### ISSUE TITLE
(Feature request) Transition from SQLite database to MariaDB/Postgree

### ISSUE THREAD

**Issue by miltuss** [zadam/trilium#4723]
### Describe feature

Trilium is defined as a database that can contain large databases containing all kinds of information. But trilium uses sqlite which has countless limitations such as the size of stored files, data reading performance...

 Why not use a MariaDB or Postgree database for trilium?

 This could solve several problems on Trilium!

**Comment by Nriver** [comment]
SQLite is good enough for personal use.

**Comment by miltuss** [comment]
> SQLite is good enough for personal use.

Trilium is supposed to be the largest self-hosted knowledge base. You can't just ask for personal use.

Even for personal use, sqlite quickly reaches its limits, as you can't upload files over 250 MB.

**Comment by Nriver** [comment]
SQLite is said to be able to handle terabyte-level data. It's already overkill. All of your mobile phone apps use SQLite databases to store data. I believe it's well-tested for personal use.

However, it's not a good practice to store large single files in a database.

Trilium is not designed for large file storage. The limit of 250MB is set to protect your data. You can bypass it, but there is no guarantee everything will work.

**Comment by zadam** [comment]
As others mentioned, SQLite is good enough. Closing since this is not going to change.
