### ISSUE TITLE
how can I translate it？

### ISSUE THREAD

**Issue by ffywhxf** [zadam/trilium#474]
Dear zadam
My system is Windows.
My idea is that : 
1. I download the "trilium-windows-x64",and I find the "app.asar".
2. I "asar extract app.asar ./"   and I find the ui , translate to Chinese.
3. I “npm install electron-packager -g”    and packager to exe.

But i failed,  cry loudly.
There's so many Erro.
It's there an easy way to do that?

**Comment by zadam** [comment]
It would be easier to do this translation on the source files and then build it.

But currently this is not supported. Actually there's no recommended way to translate Trilium, yet. This might change in the future.
