### ISSUE TITLE
(Bug report) Cant install.. node not found

### ISSUE THREAD

**Issue by 9acca9** [zadam/trilium#4743]
### Trilium Version

0.63.5

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Alpine container in Proxmox

### Description

Hi. i download the last release.
Im trying to install in a lxc alpine (proxmox) but im getting this error:
```
trilium:~/trilium-linux-x64-server# ls
LICENSE                 db                      node                    src
README.md               dump-db                 node_modules            trilium.sh
anonymize-database.sql  images                  package-lock.json
config-sample.ini       libraries               package.json
trilium:~/trilium-linux-x64-server# ./trilium.sh 
./trilium.sh: line 2: ./node/bin/node: not found
```
What could be the problem?
i look for node in that location and...... it is there. So... what im missing?
Thanks!

**Comment by CrO2Cl2** [comment]
probably a permissions thing, have you tried running it with sudo?

**Comment by 9acca9** [comment]
im root. this is a server and by default you just got root.
But anyway, i dont remember how i install it but i already did, im looking and see that it is installed in a LXC debian so, maybe was something related to Alpine.
But, anyway, thanks!
I will close this because it is already installed.
