### ISSUE TITLE
(Bug report) No port is listerning after upgrade server from 0.60.4 to 0.63.5

### ISSUE THREAD

**Issue by printff** [zadam/trilium#4765]
### Trilium Version

0.63.5

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 20.04(just upgraded from 18.04)

### Description

No port is listerning after upgrade server from 0.60.4 to 0.63.5 using file trilium-linux-x64-server-0.63.5.tar.xz.
The port 8080 is not listerning. While before upgraded(0.60.4), it woks.
After killing the node process and restart serveral times, it remains the same.

The process is running:
ps -elf|grep node
```
0 S xxx        23704   23703  1  80   0 - 194059 ep_pol 14:43 pts/1   00:00:07 ./node/bin/node src/www
```

### Error logs

In the log file, it shows this message: 14:44:08.935 TypeError: Cannot read properties of undefined (reading 'set')

[trilium-2024-05-09.log](https://github.com/zadam/trilium/files/15258878/trilium-2024-05-09.log)

**Comment by printff** [comment]
[trilium-2024-05-09.log](https://github.com/zadam/trilium/files/15258867/trilium-2024-05-09.log)

**Comment by zadam** [comment]
This is only a guess, but what node version are you using? An upgrade to v18 or v20 might be worth trying.

**Comment by printff** [comment]
It works after I cleared out all the old version files.
Previously, I merely overwrite them with the new versions without deleting the old ones.
