### ISSUE TITLE
(Feature request) Question: Is it possible to add geolocation to a note in Trilium?

### ISSUE THREAD

**Issue by kotlasu** [zadam/trilium#4766]
### Describe feature

Option to add a geotag that will lead/show openstreetmap in `[Place Name or and address](geo:lat,long)` format.
Copy of a Obsidian.md community plugin: [https://github.com/esm7/obsidian-map-view](url).

### Additional Information

Hello amazing people!

Can I add a geolocation tag/link to a note?
There's incredibly useful plugin for Obsidian.md [https://github.com/esm7/obsidian-map-view](https://github.com/zadam/trilium/issues/url) that I've been using so far but I'm tempted by fancy Trilium features and the self-host option.

I've searched far and long for the answer and it's nowhere to be found.

It would be really nice to add a geotag to a note via search or manual copy-paste like so:
[Very Nice Place](geo:52.5111669,13.4430356)

Yes, I'm aware that Trilium is in maintenance mode and there won't be any new big features but maybe I've missed a script or extension for Trilium (or it's a possible feature "Trilium Next").

**Comment by eliandoran** [comment]
@kotlasu , a first version of this feature has been released in [TriliumNext v0.91.4-beta](https://github.com/TriliumNext/Notes/releases/tag/v0.91.4-beta).
