### ISSUE TITLE
v0.30.7 packaged server install -- client doesn't start

### ISSUE THREAD

**Issue by sunrez** [zadam/trilium#477]
-  I did a completely fresh install of v.30.7 packaged release on a Debian Stretch x86-64 machine. 
- Node starts, but when I try to access ip:8080, both Firefox & Waterfox just show a blank page
- Console shows "DB not initialized, please visit setup page to see instructions on how to initialize Trilium" but nothing happens in the browser
- I have tried to re-start the server, I have tried running as root and as a local user, the effects are the same
- Have deleted source, unpackaged and tried to run, same results

=================================
```
trilium@trilium:~/trilium-data/log$ ls -la
total 12
drwx------ 2 trilium trilium 4096 Apr  4 03:33 .
drwx------ 4 trilium trilium 4096 Apr  4 03:33 ..
-rw-r--r-- 1 trilium trilium 1945 Apr  4 03:37 trilium-2019-04-04.log
trilium@trilium:~/trilium-data/log$ cat trilium-2019-04-04.log
03:33:04.213 INFO  Generated session secret
03:33:04.213 INFO  Generated sourceId=2fDZryhtZllN
03:33:04.214 INFO  App HTTP server starting up at port 8080
03:33:04.214 INFO  {
  "appVersion": "0.30.7",
  "dbVersion": 127,
  "syncVersion": 6,
  "buildDate": "2019-03-30T20:13:53+01:00",
  "buildRevision": "c240fb98967d11ea3925c2c39b44138bb8e46f58",
  "dataDirectory": "/home/trilium/trilium-data"
}
03:33:04.224 INFO  DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
03:33:20.304 INFO  GET /
03:33:20.384 INFO  GET /setup
03:34:05.658 INFO  GET /
03:34:05.724 INFO  GET /setup
03:34:06.343 INFO  GET /favicon.ico
03:34:23.839 INFO  GET /
03:34:23.894 INFO  GET /setup
03:34:24.809 INFO  GET /favicon.ico
03:35:49.830 INFO  Generated sourceId=IVmPunEq3JIX
03:35:49.830 INFO  App HTTP server starting up at port 8080
03:35:49.830 INFO  {
  "appVersion": "0.30.7",
  "dbVersion": 127,
  "syncVersion": 6,
  "buildDate": "2019-03-30T20:13:53+01:00",
  "buildRevision": "c240fb98967d11ea3925c2c39b44138bb8e46f58",
  "dataDirectory": "/home/trilium/trilium-data"
}
03:35:49.841 INFO  DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
03:35:54.099 INFO  GET /setup
03:35:56.642 INFO  GET /
03:35:56.709 INFO  GET /setup
03:36:07.685 INFO  GET /favicon.ico
03:36:10.470 INFO  GET /
03:36:10.538 INFO  GET /setup
03:37:47.911 INFO  Generated sourceId=y2BRk0D66lP1
03:37:47.911 INFO  App HTTP server starting up at port 8080
03:37:47.911 INFO  {
  "appVersion": "0.30.7",
  "dbVersion": 127,
  "syncVersion": 6,
  "buildDate": "2019-03-30T20:13:53+01:00",
  "buildRevision": "c240fb98967d11ea3925c2c39b44138bb8e46f58",
  "dataDirectory": "/home/trilium/trilium-data"
}
03:37:47.921 INFO  DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
03:37:52.159 INFO  GET /
03:37:52.252 INFO  GET /setup
```

**Comment by zadam** [comment]
After opening ip:8080, can you open developer console to see if there's any JS error or some other error? Since on the backend log everything looks just fine ...

**Comment by sunrez** [comment]
Hi,

Sorry for the delay.  I opened the console and didn't see any overt errors.  Attaching screenshots.






![Screen Shot 2019-04-15 at 2 52 07 PM](https://user-images.githubusercontent.com/17105174/56157838-8867a780-5f8e-11e9-8a53-942ee5b3a997.png)
![Screen Shot 2019-04-15 at 2 52 17 PM](https://user-images.githubusercontent.com/17105174/56157839-89003e00-5f8e-11e9-8116-c3be3be49c3a.png)
![Screen Shot 2019-04-15 at 2 52 25 PM](https://user-images.githubusercontent.com/17105174/56157842-89003e00-5f8e-11e9-8826-e46c9eab9c51.png)
![Screen Shot 2019-04-15 at 2 52 33 PM](https://user-images.githubusercontent.com/17105174/56157843-89003e00-5f8e-11e9-9e4c-938518c5a380.png)

**Comment by sunrez** [comment]
Hello,

I tried ""0.31.1-beta" and see the same thing (hosted installation).  I will try it on another computer to see if this is something machine / setup related.

**Comment by sunrez** [comment]
I tried 0.31.1-beta on another Debian 9.6 Stretch machine (no virtual machine, LXC containers, etc) and see the same result : a redirect to /setup but nothing comes up.  No errors in the Javascript console.

**Comment by sunrez** [comment]
Hi,

I tried the instructions here (https://github.com/zadam/trilium/wiki/Manual-server-installation) on a Debian Stretch machine, got Node installed from NodeSource (see below for exact versions) and I get the same error in Waterfox / Firefox when trying to access Trilium:

trilium@trilium:~/trilium$ node src/www
Generated session secret
Generated sourceId=8sWhR6JzUjoT
App HTTP server starting up at port 8080
{
  "appVersion": "0.30.7",
  "dbVersion": 127,
  "syncVersion": 6,
  "buildDate": "2019-03-30T20:13:53+01:00",
  "buildRevision": "c240fb98967d11ea3925c2c39b44138bb8e46f58",
  "dataDirectory": "/home/trilium/trilium-data"
}
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
^C

trilium@trilium:~/trilium$ nodejs --version
v10.15.3
trilium@trilium:~/trilium$

trilium@trilium:~/trilium$ npm --version
6.4.1
trilium@trilium:~/trilium$

**Comment by zadam** [comment]
Hello, this might be a stupid question, but do you have JavaScript enabled? That's the only reason for this I can think of ...

**Comment by sunrez** [comment]
Hi,

Yes, I have tried with and without NoScript .  Javascript is enabled, you can see from the console it's fetched a bunch of JS.  I self host a bunch of other stuff (Horde, Confluence) which of course use Javascript and run without issue.

Do most users utilize a Docker image or run with Chrome by chance?  I can also try with an Ubuntu container setup to see if it's something Debian related (unlikely, but possible).

**Comment by sunrez** [comment]
Hi,

I think this bug should be re-opened, but the issue is with Trilium and Firefox / Waterfox (56.26) .

I used the "Falkon" browser, installed from a Flatpak and I am able to successfully run through the first-time user and log into the Trilium instance.  However I log into the same instance with Firefox 54 or Waterfox 56 then the UI does not properly come up.

Attached are screenshots.

![Screen Shot 2019-04-15 at 11 20 48 PM](https://user-images.githubusercontent.com/17105174/56179901-5594d200-5fd5-11e9-9041-9c116173924e.png)
![Screen Shot 2019-04-15 at 11 21 03 PM](https://user-images.githubusercontent.com/17105174/56179910-5af21c80-5fd5-11e9-870d-49d2aaca9448.png)

**Comment by zadam** [comment]
Oh, I see. So the reason is that your browser versions are pretty old.

Trilium uses some of the new features, like CSS grid of JS modules and needs newer version (IIRC at least FF 60). I regularly test only with up to date FF and Chromium.
