### ISSUE TITLE
Missing files - trilium-windows-x64-0.63.6.zip

### ISSUE THREAD

**Issue by memo-567** [zadam/trilium#4770]
### Trilium Version

0.63.6

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

The packed archive of the Windows version is missing files. It's also only a size of 3.92MB.

**Comment by elmaester** [comment]
Can confirm, .exe file is missing

**Comment by capi** [comment]
As a workaround, until zadam comes around fixing it: I've built the Windows version based on the release tag and attached it on a release in my fork. It's the first time I'm building a release myself, so please use at your own risk. It seems to run fine on my machine here.
https://github.com/capi/trilium/releases/tag/v0.63.6

**Comment by chielmi** [comment]
@capi thank you for sharing a temporary fix, I can confirm it is working fine!

**Comment by memo-567** [comment]
Exactly like this - works  👍

**Comment by GitTimeraider** [comment]
> As a workaround, until zadam comes around fixing it: I've built the Windows version based on the release tag and attached it on a release in my fork. It's the first time I'm building a release myself, so please use at your own risk. It seems to run fine on my machine here. https://github.com/capi/trilium/releases/tag/v0.63.6

Does work fine yep.
Do hope the official one gets updated as well

**Comment by zadam** [comment]
Apologies, will release a fix today.
