### ISSUE TITLE
(Bug report) Windows release zip doesn't contain the full release.

### ISSUE THREAD

**Issue by dada051** [zadam/trilium#4776]
### Trilium Version

0.63.6

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

The 0.63.6 release for Windows doesn't contain all the necessary files for the update, and even more, make it unusable for a fresh install.

**Comment by capi** [comment]
As a workaround, until zadam comes around fixing it: I've built the Windows version based on the release tag and attached it on a release in my fork. It's the first time I'm building a release myself, so please use at your own risk. It seems to run fine on my machine here.
https://github.com/capi/trilium/releases/tag/v0.63.6

**Comment by zadam** [comment]
Apologies, will release a fix today.
