### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by doobes** [zadam/trilium#4777]
### Trilium Version

0.63.5

### What operating system are you using?

Ubuntu

### What is your setup?

Local (no sync)

### Operating System Version

W10

### Description

[https://github.com/zadam/trilium/wiki/Onenote](url)

This describes the usage of Evernote Legacy to import OneNote data.  The Evernote Legacy "system" has been deprecated and the app no longer functions.

**Comment by zadam** [comment]
I added a disclaimer on top of the page.
