### ISSUE TITLE
Latest release not available for flatpak (Bug report) 

### ISSUE THREAD

**Issue by Lolabird** [zadam/trilium#4781]
### Trilium Version

0.63.5

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora 40 (Local)

### Description

I don't know if this is a bug exactly, but I haven't seen an update for 0.63.6 for Flatpak and wanted to know if an update was planned for that.

**Comment by zadam** [comment]
Will be fixed in the next release (today likely).
