### ISSUE TITLE
Can't install flatpak (Bug report) 

### ISSUE THREAD

**Issue by d03j** [zadam/trilium#4787]
### Trilium Version

flatpak

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

ubuntu 24.04 + KDE

### Description

I can't install the flatpak. I get a "Secure Connection Failed. An error occurred during a connection to dl.flathub.org. PR_END_OF_FILE_ERROR" through https://flathub.org/apps/com.github.zadam.trilium and "Could not find 'app/com.github.zadam.trilium/x86_64/stable' in 'flathub'; please make sure it's available." when using KDE's discover.

**Comment by rom1dep** [comment]
could it be a configuration problem on your side/a bug with KDE's discover? I could install it fine from the CLI, and the rate of installations from https://flathub.org/apps/com.github.zadam.trilium don't seem to indicate that something's wrong

**Comment by d03j** [comment]
Not sure. Today I tried gain and it worked without a problem. No changes to my system, so maybe there was something weird going on at flathub at the time?
