### ISSUE TITLE
Restoring back up issue

### ISSUE THREAD

**Issue by Micolashh** [zadam/trilium#4789]
![Screenshot 2024-06-02 140947](https://github.com/zadam/trilium/assets/67989636/1a1a20f0-d949-43e4-95ec-eb298af07a58)

What am I doing wrong? I previously just had the single file, a renamed backup-weekly to document.db, after experimenting with other methods I can't restore the backup. 
Also, just to be sure, I opened the db file with a txt viewer to confirm that my notes were indeed there.

**Comment by Nriver** [comment]
You need to put it in the `trilium-data` folder.

**Comment by Micolashh** [comment]
![Screenshot 2024-06-02 21285622](https://github.com/zadam/trilium/assets/67989636/83d34f58-427d-487e-ae29-926117b41b1d)
