### ISSUE TITLE
Option to disable global shortcut(s)

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#48]

**Comment by thisredone** [comment]
jeez, that would be helpful. It's really annoying because some of them hijack shortcuts from other apps such as sublime making it impossible to use the two at the same time

**Comment by thisredone** [comment]
Yeah, that's the one I'm talking about. It triggers instead of "Switch Project" in Sublime

**Comment by zadam** [comment]
Keyboard shortcuts are configurable in 0.38 so global shortcuts can be disabled.
