### ISSUE TITLE
[FEATURE REQUEST] Support Ctrl+Cmd+F to switch into Fullscreen mode on OSX

### ISSUE THREAD

**Issue by dongido001** [zadam/trilium#480]
Currently, I have to click on the expand icon in the left upper corner of the Brackets window to expand into Fullscreen mode. Switching back to the previous mode requires to click the expand icon in the top menubar.

I think it would be nice to have the short-cut to make switches quickly without much mouse movement.

**Comment by zadam** [comment]
Fullscreen should not be possible with F11 (configurable in Options).
