### ISSUE TITLE
Trilium won't start at all

### ISSUE THREAD

**Issue by supermayx** [zadam/trilium#4803]
### Trilium Version

0.63.7 and 0.63.5

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 Pro 22H2 19045.4529

### Description

Server side updated to v0.63.7, but local app(tried both 0.63.7 and 0.63.5) won't start.
After double-click, nothing happens, tried safemode.bat and others, no response, please help!
Thanks!

**Comment by Nriver** [comment]
Run it in CMD and see the logs.

**Comment by supermayx** [comment]
> Run it in CMD and see the logs.

Thanks a lot, in CMD, it shows that db version is too old and need migration with the help of v0.60.4, I'll try this right away.

**Comment by supermayx** [comment]
work as charm! thanks!
