### ISSUE TITLE
preview always in front ！！

### ISSUE THREAD

**Issue by Johnson-yue** [zadam/trilium#481]
trilium version is 0.31.0-beta
OS is MacOs 10.14.4. 

when I use preview function for some notes, like this:
<img width="1440" alt="屏幕快照 2019-04-10 下午9 52 34" src="https://user-images.githubusercontent.com/10268274/55885319-50eaab00-5bdc-11e9-9ebf-152486a7b132.png">
there is a window of preview for note, but when it go to other note, this window of preview not close ,  

And. If I resize the application main window, the preview window have two position
like, this:
<img width="1115" alt="屏幕快照 2019-04-10 下午9 53 32" src="https://user-images.githubusercontent.com/10268274/55885598-d706f180-5bdc-11e9-9cb5-11afb25a8726.png">

**Comment by zadam** [comment]
Hello, thanks for testing the beta version! The popup should hide when you move out your cursor out of the link. If it doesn't happen then it's wrong.

I can't replicate the behavior though. Does the popup stay open everytime you hover over cursor or only sometime?

**Comment by Johnson-yue** [comment]
everytime !!!!
if it popup  , whether I move out my cursor or not,  it still open and can not close  anyway

**Comment by zadam** [comment]
Unfortunately, I did not manage to replicate this at all, popups disappear correctly on all OSs, including Mac :-/

**Comment by villamilmedia** [comment]
Hello Johnson-yue I can confirm your problem as I experience the same on v0.31.0 as in v0.31.1 on MacOS 10.14.4

**Comment by Johnson-yue** [comment]
Yes！！！ Me， too。 but,  @zadam can not replicate it .  It so sad

**Comment by zadam** [comment]
Hello, I think I managed to reproduce & fix this issue. Fix will be in the next beta.
