### ISSUE TITLE
 I recently studied the API. When getting content through the interface, the picture prompts: Logged in session not found.

### ISSUE THREAD

**Issue by openapphub** [zadam/trilium#4828]
### Trilium Version

0.63.7

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macos

### Description

Get the img tag node through the `/notes/{noteId}/content` interface`<img style="aspect-ratio:1012/1185;" src="api/attachments/OfFAHS3RFFOC/image/8-8.jpg" alt = "image.png" width="1012" height="1185">`, when rendering with rich text, it prompts: "Logged in session not established".

I tried
- Via a reverse proxy, pointing the image address to the config address and adding the request header "Authorization", but still showing the "Login session not found" prompt.
- When developing locally, point the proxy to the local http://127.0.0.1:37840 and access it at this time, which is normal.

Please give me some advice on how to load image resources correctly?

**Comment by rauenzi** [comment]
Are you trying to use Trilium as an image CDN? Why are you trying to access the image directly like that? You should put the image in a share (perhaps a share raw depending on the usecase)

**Comment by openapphub** [comment]
> Are you trying to use Trilium as an image CDN? Why are you trying to access the image directly like that? You should put the image in a share (perhaps a share raw depending on the usecase)

It is not used as an image CDN, but `content` is obtained through the interface. The information returned by the `content` interface is prompted when I render this information (rich text) for display. Picture cannot be echoed

**Comment by rauenzi** [comment]
I'm still unclear on what exactly you're trying to do here, but you should not be remotely hotlinking the images stored in Trilium outside of share trees.

**Comment by openapphub** [comment]
My idea is this, to develop a page that shows the daily events.
Get all the notes in a topic directory through a custom interface, and display the note content. Basically, I've done everything I need, but I don't know how to display the pictures.
<img width="576" alt="image" src="https://github.com/user-attachments/assets/1eb8de70-5784-4aa0-8616-31896ab463de">

**Comment by openapphub** [comment]
I tried several times and found that some pictures don't work and some work fine, so I'm even more puzzled~. Re-uploaded the photo that required logging in and found it didn't need to be verified.

Accessing the database, comparing the fields of both looks similar, nothing special.



#### login required

https://note.xxx.com/api/attachments/ua1ttd4hgYsh/image/640.jpg
https://note.xxx.com/api/attachments/OfFAHS3RFFOC/image/8-8.jpg

#### direct access

https://note.xxx.com/api/attachments/4I07nIUxpsAV/image/image.png

**Comment by rauenzi** [comment]
> My idea is this, to develop a page that shows the daily events. Get all the notes in a topic directory through a custom interface, and display the note content. Basically, I've done everything I need, but I don't know how to display the pictures. <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/175949671/352964544-1eb8de70-5784-4aa0-8616-31896ab463de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjg2NzUsIm5iZiI6MTcyMjI2ODM3NSwicGF0aCI6Ii8xNzU5NDk2NzEvMzUyOTY0NTQ0LTFlYjhkZTcwLTU3ODQtNGFhMC04NjE2LTMxODk2YWI0NjNkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxNTUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTJlOWI4MjYyNTRkMWMyZjYxMTg5ZTNmZTdiNGUzNmE2MGFkNzhiMDdmNTA2ZjBkOGY0YzdmYTgzYThlOTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-HpdBQRhowjAeaYiNnuZt1mpSv3DWc8FRgPVLjcmZV4">

It sounds like you're recreating the shared notes feature essentially.

**Comment by openapphub** [comment]
> > My idea is this, to develop a page that shows the daily events. Get all the notes in a topic directory through a custom interface, and display the note content. Basically, I've done everything I need, but I don't know how to display the pictures. <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/175949671/352964544-1eb8de70-5784-4aa0-8616-31896ab463de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjg2NzUsIm5iZiI6MTcyMjI2ODM3NSwicGF0aCI6Ii8xNzU5NDk2NzEvMzUyOTY0NTQ0LTFlYjhkZTcwLTU3ODQtNGFhMC04NjE2LTMxODk2YWI0NjNkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxNTUyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTJlOWI4MjYyNTRkMWMyZjYxMTg5ZTNmZTdiNGUzNmE2MGFkNzhiMDdmNTA2ZjBkOGY0YzdmYTgzYThlOTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-HpdBQRhowjAeaYiNnuZt1mpSv3DWc8FRgPVLjcmZV4">
> 
> It sounds like you're recreating the shared notes feature essentially.

Hmmmmmmmmm .... ~, it does seem to be the case, I see . Analyzing first will add the share path, so it's OK.
