### ISSUE TITLE
文本note中代码块高亮像csdn的代码块那样的样式

### ISSUE THREAD

**Issue by 403705726** [zadam/trilium#4831]
### Describe feature

可不可以增加一个功能，文本note中代码块高亮像csdn的代码块那样的样式

**Comment by eliandoran** [comment]
Hi, @403705726 .

> Can you add a feature to highlight the code blocks in the text note like the code blocks in csdn?

Syntax highlighting will not be added to Trilium Notes as it is in maintenance mode. For your information, we have added this feature in https://github.com/TriliumNext/Notes .
