### ISSUE TITLE
Trilium.exe not launching after updating to v0.63.7

### ISSUE THREAD

**Issue by CassieDingo** [zadam/trilium#4836]
### Trilium Version

v0.63.7 release

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 19045.4651

### Description

This is a bit hard to give accurate repro steps on but general description; I updated to v0.63.7 release today and attempting to run trilium.exe is resulting in nothing happening. The wheel loads for a second but I can not spot any discernible events that are occurring. Im not sure where trillium spits its error logs to either. 

I have attempted to restore from back ups but every time i do restore from a back up and run trilium portable nothing happens. If i make a fresh instance i still can not run Trilium.exe even after that, Not sure what to do here at this point but it is becoming rather difficult since I use trillium for alot of documentation and planning related work.

Thanks to anyone who can help in advance!

**Comment by Nriver** [comment]
run the exe in cmd, see the logs

**Comment by CassieDingo** [comment]
![image](https://github.com/user-attachments/assets/59223d5b-6e59-4797-bd4d-d01fd85c6f0c)

ah it looks like my DB needs an incremental update, that might explain it... 
i'll run through the flow and see what happens.

**Comment by CassieDingo** [comment]
Ah yup that was the case! Im now on the latest with no issues and can launch successfully! 

It might be worth seeing if the wiki can be updated to mention this? My prior version was 2022 and i couldn't find any documentation/mentions of this potentially being a troubleshoot method. Again though massive thank you! Saved my day! <3
