### ISSUE TITLE
(Bug report) Windows 10 application does not start

### ISSUE THREAD

**Issue by egidijus** [zadam/trilium#4840]
### Trilium Version

0.63.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10  10.0.19045 Build 19045

### Description

I have been using trillium on multiple osses, linux, windows, osx, server without problem, for over a year.
Today, the windows install would not start, I installed latest build, still, does not start:

The window does not open, no feedback at all.
Starting application in terminal shows this, and then the process exits:
```
DB size: 27652 KB
{
  "appVersion": "0.63.7",
  "dbVersion": 228,
  "nodeVersion": "v18.15.0",
  "syncVersion": 32,
  "buildDate": "2024-05-30T06:59:06+02:00",
  "buildRevision": "95d46b7ce7e0036eeb72b43e1815cc5c00dc214c",
  "dataDirectory": "C:\\Users\\egidijus\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-08-09T11:29:43.292Z"
}
CPU model: AMD Ryzen 9 5950X 16-Core Processor            , logical cores: 32 freq: 3400 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Port 37840 requires elevated privileges. It's recommended to use port above 1024.
```
- I usually start trillium with this shortcut `trilium-windows-x64\trilium.exe --ignore-certificate-errors`
- None of the included bats work.
- I checked windows defender, and it does not seem to be blocking/detecting anything.
- I checked event viewer, there are no events.
- When inspecting trillium with sysinternals Procmon64, I do see it start, I do see it try to do things, and then it exits.
- The log written to `C:\Users\egidijus\AppData\Roaming\trilium-data\log` is empty.
- I have recently updated my nvidia drivers to : `v560.81`

### Error logs

DB size: 27652 KB
{
  "appVersion": "0.63.7",
  "dbVersion": 228,
  "nodeVersion": "v18.15.0",
  "syncVersion": 32,
  "buildDate": "2024-05-30T06:59:06+02:00",
  "buildRevision": "95d46b7ce7e0036eeb72b43e1815cc5c00dc214c",
  "dataDirectory": "C:\\Users\\egidijus\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2024-08-09T11:29:43.292Z"
}
CPU model: AMD Ryzen 9 5950X 16-Core Processor            , logical cores: 32 freq: 3400 Mhz
Trusted reverse proxy: false
App HTTP server starting up at port 37840
Port 37840 requires elevated privileges. It's recommended to use port above 1024.

**Comment by Br0kenSilos** [comment]
Maybe try this.  Right-click your shortcut. Then click the Advanced button and set it to run as Administrator. See if that makes any difference.

**Comment by egidijus** [comment]
> Maybe try this. Right-click your shortcut. Then click the Advanced button and set it to run as Administrator. See if that makes any difference.

Running as admin does not fix it.

**Comment by non-npc** [comment]
I am running v0.63.7 on windows 10 and it runs fine

**Comment by egidijus** [comment]
I feel dumb saying this, but a restart fixed it.
I had restarted before, and it did not fix the issue initially, but today, it's all good.
I cannot reproduce the issue, sorry to waste your time.
