### ISSUE TITLE
New desktop install will not sync with server.

### ISSUE THREAD

**Issue by Phalen** [zadam/trilium#4845]
### Trilium Version

0.63.7

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win 10 19045.4651 & mx linux

### Description

MX linux works fine and is properly synched.  I closed out of that client and then ran the windows client on my win pc.  the win install I selected the sync from server.  It accepted the right user/pass after i put the wrong one in and now is stuck on synching with 0 items left to sync. logs dont show any thing usefull. 

### Error logs

09:40:13.019 Returning sync stats: {"initialized":false,"outstandingPullCount":0}
09:40:13.019 304 GET /api/sync/stats with 46 bytes took 0ms

**Comment by xmzml** [comment]
I also encountered this problem. It got stuck when syncing to a fixed number, Outstanding sync items: 819, and it stayed here forever.

**Comment by xmzml** [comment]
Maybe I should change to a different version first. Any suggestions other than 0.63.7?

**Comment by Phalen** [comment]
@xmzml Thanks so much for that as that resolved the issue.  

@meichthys Now that i realize it is available I just upgraded my desktop to that version.  the 2nd system that was having this issue did not care which version you used it got the same error.  ironically the server was next even though I didn't realize it. I greatly appreciate the link as that has helped me as well.
