### ISSUE TITLE
(Bug report) export note to Markdown ，”||“ will miss when title contain these characters

### ISSUE THREAD

**Issue by wayne-pq** [zadam/trilium#4856]
### Trilium Version

v0.63.7

### What operating system are you using?

Other (specify below)

### What is your setup?

Local (no sync)

### Operating System Version

install in docker in windows 10

### Description

my note title as "JavaScript基础-运算符"||"和"&&"的使用技巧", but when i export note to Markdown , my file in local will miss  ”||“ in file title,such as "JavaScript基础-运算符和&&的使用技巧.md"

**Comment by Nriver** [comment]
The `|` character is not allowed in file names on Windows OS. To preserve the original title, export the file as a ZIP. The title will be stored in the `!!!meta.json` file, which can be accessed and read by Trilium.

**Comment by wayne-pq** [comment]
> The `|` character is not allowed in file names on Windows OS. To preserve the original title, export the file as a ZIP. The title will be stored in the `!!!meta.json` file, which can be accessed and read by Trilium.

thanks a lot
