### ISSUE TITLE
Delete hoisted note does weird stuff

### ISSUE THREAD

**Issue by simonszu** [zadam/trilium#488]
Steps to reproduce:
1. Hoist a note
2. Delete the hoisted note, say: The root of the hoisted tree. 

Results: A popup with a HTTP Error 404 appears, the sidebar is empty, there is no way to exit the hoisted view. 

Version: Latest docker image as of today.

**Comment by zadam** [comment]
Thank you for reporting this. It is now not possible to delete currently hoisted note.
