### ISSUE TITLE
(Bug report) API search using limit doesn't acknowledge value?

### ISSUE THREAD

**Issue by ptmorris1** [zadam/trilium#4881]
### Trilium Version

0.90.12

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 23H2

### Description

I am currently working with the ETAPI, specifically using the /notes search API. While I am able to run queries without issues, I am encountering a problem when using the limit parameter. Even though I set the limit to 2, I am still receiving 5 results. Is this behavior expected or am I missing something here? I am basing my implementation on the OpenAPI YAML documentation provided.

`curl -X 'GET' 'https://notes.domain.com/etapi/notes?search=rav4&limit=2' -H 'accept: application/json; charset=utf-8' -H 'Authorization: ETAPITOKEN'
`

This command works for me but returns all values and does not limit to 2.

Thank you.

### Error logs

No errors, just not returning the correct number when using limit.

**Comment by Nriver** [comment]
You need a `orderBy` to make `limit` working. A valid search would be like this
```
http://127.0.0.1:37840/etapi/notes?notes?orderBy=title&limit=2&search=01
```

**Comment by ptmorris1** [comment]
Thanks, that is what I was missing, orderBy.

And to anyone who see this in the future, just correcting the url Nriver posted.   removed the extras `notes?`

`http://127.0.0.1:37840/etapi/notes?orderBy=title&limit=2&search=01`
