### ISSUE TITLE
Chinese search no longer working

### ISSUE THREAD

**Issue by tanghongdao** [zadam/trilium#489]
[trilium-2019-04-18.log](https://github.com/zadam/trilium/files/3092359/trilium-2019-04-18.log)

Version 0.30.7 worked fine when searching in Chinese, but does not work in version trilium-windows-x64-0.31.1-beta.

**Comment by zadam** [comment]
Thank you for reporting this issue. 0.31 has a big fulltext search change, but it looks like there are some significant issues so I will probably revert back to the old one (supporting chinese search) in the next beta.
