### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#495]
I just installed trilium_0.30.8_amd64.deb on debian buster and that is the message I have in a blank page when I start it. It does not start at all. It was working fine before the new upgrade

**Comment by gerroon** [comment]
Never mind I assumed it was an upgrade but it was a downgrade apperatntly from 31 to 30

**Comment by zadam** [comment]
sorry for confusion, 0.30.8 was mistakenly tagged as latest
