### ISSUE TITLE
How to set TLS for Trilium server on a sub-domain?

### ISSUE THREAD

**Issue by hervehobbes** [zadam/trilium#497]
Hello,

First thank you very much for this program.
Secondly, I'm using a VPS with Apache and I'd like to put the server version of Trilium on a sub-domain (for example http://notes.example.com)

When I launch Trilium with the `nohup node src/www &` command I can see Trilium on port 8080 but what do I have to do with Let's Encrypt to have a certificate?

Thanks

**Comment by zadam** [comment]
Hello, in such a case you need to configure the TLS/Let's encrypt on the Apache level so TLS is terminated on Apache and from Apache to Trilium it's just a standard HTTP. I don't use Apache for this, but there should be plenty of documentation online how to setup TLS with Let's encrypt.

**Comment by hervehobbes** [comment]
Hello,

Thank you for your answer. Just one last question, do I have to use a reverse proxy?

**Comment by zadam** [comment]
It depends on your setup - Trilium doesn't need reverse proxy, but then it will occupy the whole hostname-port. If you need to run multiple sites on the same hostname/port, then you need reverse proxy.

**Comment by hervehobbes** [comment]
Thank you, this issue can be closed.
