### ISSUE TITLE
[CSS][Bug] Dark/Black theme doesn't show the table correctly.

### ISSUE THREAD

**Issue by Belphemur** [zadam/trilium#499]
# Bug
Here the header are unreadable, but not only that, you can't see what you're writing when editing a row.
![image](https://user-images.githubusercontent.com/197810/56819303-6e905500-6817-11e9-8062-8a431d74d411.png)
## Version
0.30.8

**Comment by zadam** [comment]
This is fixed in 0.31.X (soon to go stable).
