### ISSUE TITLE
No scroll bar in ALT+M mode

### ISSUE THREAD

**Issue by mohamedhagag** [zadam/trilium#500]
Versions 0.30.7 and 8

1st I would like to appreciate the great efforts and the nice app.

I'm using it for about 3 weeks now as my main notes app, it's great.

Regarding the issue, when in non-distraction ALT+M mode the scroll bars are hidden even with long notes.
Also moving the cursor using the keyboard doesn't update the view and doesn't show the content of the note.

Regards & best wishes.

**Comment by zadam** [comment]
Hello, this has been fixed in the latest 0.31.3, please try it out.
