### ISSUE TITLE
Selected line has left side of text cut off

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#502]
Trilium 0.31.3
Windows 10

I noticed that in the 0.31.3 update, on the currently selected line the left side of the first letter gets cut off by the paragraph icon. Not a big deal, but looks a bit wonky. Screenshot example:

![image](https://user-images.githubusercontent.com/1442520/56905690-ae04ae80-6a6e-11e9-890f-3a0b532787db.png)

You'll see that the left side of the letter O gets cut off

**Comment by zadam** [comment]
Should be fixed now. This happens only for smaller detail font sizes.
