### ISSUE TITLE
Ability to disable search tips popup

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#503]
Could there be a preference to disable the search tips bubble that shows to the right of the search box when performing searches in trilium 0.31.3?

It's useful at first to see information on the new search functionality, but I find it a little annoying that it's always displayed whenever I perform a search (too much visual noise)

**Comment by zadam** [comment]
I don't plan to make this configurable. Every configuration has non-trivial price in maintenance.

I'll wait a bit for some more feedback. I might hide this tooltip behind explicit help button.

**Comment by zadam** [comment]
There's no popup now.
