### ISSUE TITLE
[Feature Request] Extract citations.

### ISSUE THREAD

**Issue by light42** [zadam/trilium#504]
I really want to switch to this from Zotero, but Zotero is still easier for extracting citations.

The features that I really miss the most is:
1. Extract detailed citation's metadata from document/webpage automatically.
2. Save snapshot of webpage I want to cite.

**Comment by zadam** [comment]
I'm not familiar with these citation management softwares, but the way I understand it is that there's no uniform way of representing these citations in web pages / documents and there needs to be some sophisticated algorithm or even custom parsers for each web page. As such this seems like out of scope of a general note taking app and it's more appropriate to use a specialized software ...

For the second point, it is planned to implement a web clipper extension which would make it easy to save snapshots of web pages ...

**Comment by zadam** [comment]
Considered as out of scope so closing.

**Comment by BrandonKMLee** [comment]
Please check https://github.com/zadam/trilium/issues/1386
