### ISSUE TITLE
Focus change issue with note attributes UI

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#505]
Trilium 0.31.3
Windows 10

Steps to Re-create:
1. select a note
2.  click on note actions | attributes
3.  as quickly as possible after clicking attributes, click in the 'name' field

Expected: Focus should go to the Name field (and it should stay focused on the name field unless the user clicks another field or tabs to another field)

Actual: Right after focusing the name field, it switches focus to the Type field

Note: This is timing specific. if you wait a few seconds before clicking in the name field, there is no issue.

**Comment by zadam** [comment]
Yes, selecting the "type" field of the last attribute is supposed to give a quick and easy way to add another attribute. IIRC the rendering of the form was asynchronous and it wasn't possible to catch the exact moment where it can be focused so that's why there's 1 second delay in focusing it.
