### ISSUE TITLE
Apache 2 ubuntu virtual host configuration

### ISSUE THREAD

**Issue by cculbreath** [zadam/trilium#508]
First, I wanted to say that I *love* trilium; I feel like it was written with me in mind. I couldn't have designed something better myself. Second, I want to share my apache virtual host configuration and setup procedure (which seems to be working) for running dockerized trilium on an ubuntu server that has other web serving duties. It might be a worthwhile addition to the wiki. 

I've assumed you have created a DNS A record for `trilium.yourdomain.com` that you want to use for your trilium server.

1. Download docker image and create container
		
		docker pull zadam/trilium:[VERSION]
		
		docker create --name trilium -t -p 8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:[VERSION]

1. Configure Apache proxy and websocket proxy
	1. Enable apache proxy modules
	
			a2enmod ssl
			a2enmod proxy
			a2enmod proxy_http
			a2enmod proxy_wstunnel
			
	2. Create a new let's encrypt certificate
		
			sudo certbot certonly -d trilium.mydomain.com
		
		Choose standalone (2) and note the location of the created certificates (typically /etc/letsencrypt/live/...)

	3. Create a new virtual host file for apache (you may want to use `apachectl -S` to determine the server root location, mine is /etc/apahce2)
	
			sudo nano /etc/apache2/sites-available/trilium.yourdomain.com.conf
			
		Paste (and customize) the following text into the configuration file
		
			<VirtualHost *:80>
			    ServerName http://trilium.yourdomain.com
				RewriteEngine on
			        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
			</VirtualHost>
			<VirtualHost *:443>
			    ServerName https://trilium.yourdomain.com
			    RewriteEngine On
				RewriteCond %{HTTP:Connection} Upgrade [NC]
				RewriteCond %{HTTP:Upgrade} websocket [NC]
				RewriteRule /(.*) ws://localhost:8080/$1 [P,L]
			    ProxyPass / http://localhost:8080/
			    ProxyPassReverse / http://localhost:8080/
			    SSLCertificateFile /etc/letsencrypt/live/trilium.yourdomain.com/fullchain.pem
			    SSLCertificateKeyFile /etc/letsencrypt/live/trilium.yourdomain.com/privkey.pem
			    Include /etc/letsencrypt/options-ssl-apache.conf
			</VirtualHost>
			
			
	4. Enable the virtual host with `sudo a2ensite trilium.yourdomain.com.conf`
	5. Reload apache2 with `sudo systemctl reload apache2`
	
1. Create and enable a systemd service to start the docker container on boot
	1. Create a new empty file called `/lib/systemd/system/trilium.service` with the contents
	
			[Unit]
			Description=Trilium Server
			Requires=docker.service
			After=docker.service
				
			[Service]
			Restart=always
			ExecStart=/usr/bin/docker start -a trilium
			ExecStop=/usr/bin/docker stop -t 2 trilium
				
			[Install]
			WantedBy=local.target
	
	2. Install, enable and start service
		 
			sudo systemctl daemon-reload
			sudo systemctl enable trilium.service
			sudo systemctl start trilium.service

**Comment by cculbreath** [comment]
Well, I take that back, it *was* working. But then I upgraded to 0.31.3 and it seems that there's something different in the way that protected sessions are handled. I'm now getting a 502 proxy error. I suspect that it has something to do with the fact that I'm handling the SSL through apache2, and trilium doesn't like it. My understanding is that since the proxy is entirely on the same machine that there's no threat of a man-in-the-middle type attack, so handing the SSL with the proxy is okay, security-wise. I'll do some digging and see what I can figure out.

**Comment by zadam** [comment]
Hello, SSL termination on apache is an expected setup and should not be a problem in itself. 

There has been changes in the protected session handling, now the token is passed in cookie (previously in headers). 502 looks like an apache error after encountering something unexpected.

**Comment by cculbreath** [comment]
I haven't dug too far, but it looks to me that the protected notes are now requested with  "Referrer Policy: no-referrer-when-downgrade" — I think it's hanging on browser-level protections.

**Comment by cculbreath** [comment]
I think that protected notes have a bug in the newest release unrelated to my attempts at apache. I'm going to start a new issue/bug report.

**Comment by cculbreath** [comment]
In light of #510, I believe that these virtual-host-configuration/docker-installation instructions are correct, and complete. The wiki doesn't seem to be configured to accept public edits (understandably)-- which is why I posted these here— it's neither a bug or a feature request, so this issue can be closed.

**Comment by zadam** [comment]
Thanks for writing this up! I added your guide to https://github.com/zadam/trilium/wiki/Server-installation

I didn't actually know it's possible to allow public edits to the wiki, it should be now easier to add/fix things there.
