### ISSUE TITLE
Direct-Edit Attachments

### ISSUE THREAD

**Issue by metal450** [zadam/trilium#514]
Often, it's useful to have note attachments with "editable" content - i.e. .xls, .doc, etc.  Currently, (I believe) editing such attachments requires you to save it to a separate location, do the edits, delete the original attachment in Trilium, then reattach the modified copy.

Would it be possible to have the ability to "Direct-Edit?" The way other notes apps handles this is when you double-click an attachment, behind the scenes it "extracts" it to a temporary location & launches the editor - then when the editor is closed, it updates the attachment & deletes the temporary file.  You can see examples of this in i.e. OneNote or [CherryTree](https://github.com/giuspen/cherrytree).

**Comment by zadam** [comment]
Hello, currently this is not possible, but I can see how it would be useful. I'll add this to the backlog.

**Comment by anthony-zg** [comment]
If you save the attachment as a file in the specified directory instead of putting the content directly into the SQLite database, this problem may be solved easily

**Comment by ehamminga** [comment]
Hi Anthony, Can you elaborate on that please? As far as I'm aware, you cannot link directly to a windows file system in Trilium

**Comment by ehamminga** [comment]
@zadam Do you have any updates on this implementation?

**Comment by zadam** [comment]
what @anthony-zg suggest is the idea that SQLite database has just metadata and the notes (attachments, images...) themselves are stored in a filesystem as normal files. Then this direct-edit issue does not exist anymore since you can just open the file in any app. But this is not really planned ...

**Comment by zadam** [comment]
This has been implemented a while ago:

![image](https://user-images.githubusercontent.com/617641/152647755-1fd7bd7c-dfa0-4ab8-9aeb-eb7f8d095e37.png)

Closing.
