### ISSUE TITLE
[Feature Request] shortcut to get headings

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#519]
A simple Alt+[1..3] would work wonders to set up a doc structure really fast. This is a tiny thing but it improves workflow.

**Comment by zadam** [comment]
Did you try [autoformat](https://github.com/zadam/trilium/wiki/Text-editor#autoformat), which makes it easy to quickly create headings?

**Comment by quesada** [comment]
Yes, I like it.
The shorcut is infinitely better though to create an outline.
