### ISSUE TITLE
[Feature Request] Highlighting format

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#520]
It may sound silly, but People who thought hard about notetaking like @fortelabs (Tiago Forte) seem to recommend to do multiple passes on a note, first bolding, later highlighting, to process it (kinda summarization). I'd love to try this within Trilium.

**Comment by zadam** [comment]
Yes, highlighting is planned relatively soon, possibly in 0.33

**Comment by zadam** [comment]
Highlighting has been implemented for some time.
