### ISSUE TITLE
Any way to 'mass apply' a template?

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#522]
I have a 'person' template I'd like to apply to 100s of notes. Is there any way to do this?

**Comment by zadam** [comment]
There's few options:

* You can set the person template as inheritable to the parent note, then it's inherited automatically to all the child notes - see [https://github.com/zadam/trilium/wiki/Attribute-inheritance](wiki). Or you can use copy inheritance, but that only works for new notes IIRC.
* In these cases I often write a small script note - adding a link to all notes under a certain parent note is a few lines usually:

```javascript
const parentNote = await api.getNote('parent-note-id');

for (const childNote of await parentNote.getChildNotes()) {
     await childNote.setRelation('template', 'template-note-id');
}
```

Save as code note with "JavaScript backend" type and execute. I did not check this though and it's just from the top of my head.
