### ISSUE TITLE
Inserting an internote link does a full page refresh and is very disconcerting

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#523]
It might be on pages that are long enough to need scrolling (otherwise the refresh is not noticeable), but this is distracting nonetheless and breaks my workflow as I use internote linking a lot.

Thanks!

**Comment by zadam** [comment]
I'll check this out, adding a link should not trigger refresh.

**Comment by zadam** [comment]
Thank you for reporting this bug, it has been fixed and will be released soon.
