### ISSUE TITLE
[Feature request] Multi select notes to cut them and paste them in a different part of the tree

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#528]
Even using 'lazy organization', this operation happens multiple times per day. Compared to a file manager, the sidebar where notes are is missing some key features. This is one: multi select notes to cut them and paste them in a different part of the tree.

**Comment by zadam** [comment]
You can select multiple notes either by ctrl+click or by shift+arrows. You can then use clipboard (CTRL-X, CTRL-V) or drag them to a new location (while holding ctrl).

**Comment by quesada** [comment]
thanks, didn't know that!

**Comment by yannduran** [comment]
I was searching for exactly this! However, CTRL-click was my first instinct. That doesn't seem to work, hence the search for how to do it. SHIFT-arrow did allow me to select **contiguous** notes, but doesn't allow me to select **non-contiguous** notes.

Any idea why this isn't working? I'm using the Windows desktop app (v0.59.4).

I can't believe how easy this has made saving information. And more importantly being able to FIND that information again. You've done such a GREAT job with this program! Thank you so much for writing it, and for also making it open source, and free!!!

**Comment by zadam** [comment]
@yannduran some time ago, the key modifiers changed:

* shift allows contiguous selection as you noted
* alt allows non-contiguous selection

Ctrl is not used, because Trilium is a web app and the expected behavior of Ctrl+click is to open a link in a new tab.

**Comment by yannduran** [comment]
Yes that makes perfect sense. Thanks for your very quick reply.
