### ISSUE TITLE
Do server and desktop versions need to be the same?

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#531]
Or do we simply not get the features in the new version if the server is not updated?

**Comment by zadam** [comment]
This depends on the sync protocol compatibility. Currently, it's guaranteed to be compatible across patch versions in one minor versions - so all 0.31.X versions should be compatible and it should not matter that you have 0.31.1 on a server and 0.31.6 on the desktop. But 0.31 with 0.30 is not compatible.

However as the database format and protocol stabilizes, I expect more compatibility - e.g. the upcoming 0.32 will be compatible with 0.31.
