### ISSUE TITLE
[Feature Request] Shortcut to go to today's date in the calendar tree

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#532]
Trilium has a very useful shortcut (ctrl + alt + p) that automatically creates a new note under today's date in a calendar tree

It would be useful if there was also a shortcut that would automatically bring you to today's date in the calendar tree (without creating a new note).

For example, I might want to review notes that I've created under today's date, but if I had previously collapsed all trees, I have to manually expand each level of the calendar which is a bit cumbersome

**Comment by zadam** [comment]
Hello, this is not supported by Trilium itself, but it's easy to add it using script API by creating frontend JavaScript code note with label `@run=frontendStartup`:

```javascript
api.addButtonToToolbar({
    title: 'Today',
    icon: 'calendar',
    shortcut: 'alt+t',
    action: async function() {
        const todayDateStr = api.formatDateISO(new Date());

        const todayNote = await api.runOnServer(async todayDateStr => {
            return await api.getDateNote(todayDateStr);
        }, [todayDateStr]);

        api.activateNote(todayNote.noteId);
    }
});
```

It will have `alt+t` shortcut, however it's not global (so it works only when Trilium window is active).

**Comment by bwat47** [comment]
Thanks! 

Just tried it and this does exactly what I was looking for :)
