### ISSUE TITLE
Scenario where un-hoisting can break tree view navigation

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#535]
Trilium 0.31.6
Windows 10

Steps to Re-create:
1. Create multiple levels of folders, e.g.

TOPTEST
>>>>SUBTEST
>>>>>>>>SUBTEST NOTES

2. Select TOPTEST and then do ctrl + h to host it

3. Click on subtest so that it's the selected folder

4. Expand the SUBTEST folder tree

5. Click the un-hoist button on the top of the tree view.

6. Click the collapse note tree button (or use the shortcut alt + c)

At this point, if you attempt to click on any notes in the tree nothing happens. You can still expand/collapse folders, but clicking on any note does not bring up the note in the right pane.

If you do ctrl + r to reload the frontend, it starts behaving normally again

**Comment by zadam** [comment]
Thank you for the report. I tested this in 0.32.X which has hoisting refactored (together with much other frontend functionality) and I think it's fixed there. 0.32 should go soon stable so I won't try to fix this in 0.31

**Comment by bwat47** [comment]
I can verify that this cannot be re-created in 0.32 beta :)
