### ISSUE TITLE
[Feature request] searching for label value

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#538]
It is great to be able to search by label, but I want to search by label value.  I use a GTD methodology and locations are indicated by @xxx (@nyc, @sd, @office).  Rather than search for the label @location and then find the notes with value @office I'd like to search for:

@label=value

Since there is an API for this (getNoteWithLabel) I assume the parsing in parse_filter.js needs changing, perhaps the regex and also the logic that handles the @ case.

**Comment by zadam** [comment]
Hello, exactly this syntax: `@Label=value` is supported for searching notes with given label-value.

**Comment by pcause** [comment]
I search for:

@location=@office 

and get nothing matching.  I do have a node called @office.

**Comment by zadam** [comment]
Is the value of the label really `@office` or is it `office`?

If it is "office", then you need to search with `@location=office`, if it is really "@office", then you need to search with `@location="@office"` (at symbol is special so the value needs to be surrounded with quotes).

**Comment by pcause** [comment]
Yes it is @office.  GTD to do method uses @xxx to indicate where you expect to do the taks
