### ISSUE TITLE
32.1 beta script issue

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#543]
I have a simple script to show the todo's on startup.  In the 32 betas It opens a new tab and the tab isn't selected.  The note from the previous session is selected.  Is there a new API to make the tab the focused tab?  Likely a race condition I suspect,

Script:

const startNoteId = await api.runOnServer( async () => { 
        const startNote = await api.getNoteWithLabel('showOnStart');
    return startNote.noteId;
});

if (startNoteId != null && startNoteId != "")
    await api.activateNote(startNoteId);

**Comment by zadam** [comment]
Hello, you're right this is probably race condition. I will make a change that the startup scripts will be executed only after the frontend is fully initialized which should fix the problem.
