### ISSUE TITLE
【0.31.6 issue】where is  **today** button in Mac version

### ISSUE THREAD

**Issue by Johnson-yue** [zadam/trilium#544]
Hi,  where is  **today** button , I am using Mac version
![image](https://user-images.githubusercontent.com/10268274/58538676-3a4df100-8228-11e9-86dd-38780cffa8fd.png)

**Comment by zadam** [comment]
It looks like you deleted it. "Today" is not a built-in feature, rather a simple script included in the demo document. Easiest way to get it back is to import the [demo document](https://github.com/zadam/trilium/raw/master/db/demo.tar) again.

**Comment by Johnson-yue** [comment]
@zadam I don't deleted anything,  I just download 0.31.6 dmg and install it.
B.T.W  how to use this **demo document**, How to import this ??

**Comment by zadam** [comment]
After new installation, there's a note called "Trilium Demo" which contains bunch of things, including "Today" script. Since it's not visible in the screenshot, you must have deleted it at some point.

You can download the file, right click on some place in the tree and click Importl

**Comment by Johnson-yue** [comment]
Maybe I have delete something before, but when I download a the file  **0.31.6-mac.zip** and unzip 
when I open new install file , it is the same with before , I remember I truly delete demo "Trilium Demo"
But , when I install with new file , it can not be fixed this problem.
How I should do ?
