### ISSUE TITLE
I seem to have lost edit history (revisions) for all notes. Using server version

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#545]
Desktop: latest as in AUR
Server: one version prior to latest

For notes that were imported from txt, there's no edit history. That's fine of course
For notes I wrote in Trilium, you see dates on the left, and the title is displayed when using the button 'versions'... but not the body text. That's strange.

Can anyone reproduce?
Do you need to look into my server install? Any data I need to provide?

**Comment by zadam** [comment]
I don't think the data is lost, this is never being deleted ... Could you open the debug console with CTRL-SHIFT-I if there's maybe some JavaScript error?
