### ISSUE TITLE
Hide images from tree view

### ISSUE THREAD

**Issue by CrashLaker** [zadam/trilium#546]
Hi all. 

I've been wondering If there's a way to hide the images from being shown on the tree view menu.

This becomes unbrowsable with many subfolders + images like the image below:
![image](https://user-images.githubusercontent.com/4432491/58566097-580a5e80-8206-11e9-8773-a9787925342d.png)

thank you

**Comment by zadam** [comment]
Unfortunately not possible right now, although I understand the pain. 

There are some mitigations, you can e.g. create note "Images" and move all your uploaded images there (image don't have to stay at the same location) so they don't litter your text notes.

**Comment by CrashLaker** [comment]
Hi @zadam 
thank you for your reply.

Is there a way to move all images to a "folder" note through scripting?

**Comment by zadam** [comment]
Since cca 0.42 images are by default hidden from tree view if linked from the parent:

![](https://user-images.githubusercontent.com/617641/93762850-9e13de80-fc10-11ea-9cbe-ce405a073377.png)

**Comment by MrOctocat** [comment]
![image](https://github.com/zadam/trilium/assets/140259479/a5081f3e-21f9-4393-8b5b-6ac9cec32e70)
Has that option been moved somewhere else? Using latest Trilium as of Nov 27 '23.

**Comment by zadam** [comment]
It has been removed, because since 0.61, the images are by default stored as attachments and thus are not visible in the tree.
