### ISSUE TITLE
Synchronized changes to note attributes do not trigger a note reload

### ISSUE THREAD

**Issue by spantaleev** [zadam/trilium#551]
I've set up syncing between 2 servers running the `0.32.2-beta` Docker image.

This required a change to `src/views/setup.ejs`, so that it would let me use the "I have server instance up and I want to setup sync with it" option on server-2.

Removing the `data-bind="if: instanceType == 'desktop'"` part is enough to trick it.

---------

Sync is set up and works. Both clients have Today's note open.

I'm only doing changes on server-2 and manually pressing the **Sync** button to see them synchronized to server-1.

This is OK:
- change note content on server-2
- press **Sync**
- observe that the note is refreshed on server-1

This is OK:
- change note attribute (the default `weight` attribute) on server-2
- change note content on server-2
- press **Sync**
- observe that the note is refreshed on server-1. The promoted `weight` attribute had also been updated.

This is **not OK**:
- change note attribute (the default `weight` attribute) on server-2
- (don't do other changes!)
- press **Sync**
- observe that the note **is not** refreshed on server-1. The promoted `weight` attribute still contains its old value
- close the note tab
- open the same note again
- observe that the note is refreshed on server-1. The promoted `weight` attribute had also been updated.

Looks like the same applies in the reverse direction. If I change attributes only on server-1 (master), the note on server-2 (slave) doesn't update until I re-open it.

**Comment by zadam** [comment]
Thank you for the bug report, this has been fixed.

However there are still cases which are not covered, e.g. with inherited attributes etc. In general it's difficult to trace what all views should be refreshed so I'm just trying to cover main use cases.
