### ISSUE TITLE
Synchronization causes tabs to behave strange

### ISSUE THREAD

**Issue by spantaleev** [zadam/trilium#552]
I have the same setup as in #551 using `0.32.2-beta`.

This is OK (single server usage):
- open Today's note (opens in a tab)
- notice that it's highlighted (bold) in the sidebar
- press the X button on the tab to close it
- notice that it's not highlighted in the sidebar anymore
- click to open Today's note again (from the sidebar or from the Today button)
- notice that it's highlighted (bold) in the sidebar

This is **not OK** (multi-server server usage):
- open Today's note on both servers (opens in a tab)
- notice that it's highlighted (bold) in the sidebar on both servers
- make a change to the note contents on server-2 (slave)
- press **Sync** from server-2
- observe that the note had been updated on server-1 (master)
- observe that on server-1 (master), the sidebar no longer has the note highlighted in bold
- press the X button on the tab to close it
- click to open Today's note again (from the sidebar or from the Today button)
- notice that it won't open
- (workaround) press the X button on the empty "New tab" tab to close it
- (workaround) click to open Today's note again (from the sidebar or from the Today button)
- (workaround) note that this time the note managed to open

**Comment by zadam** [comment]
Thank you for the bug report - I've been struggling with these issues for some time. I hope this is fixed now.
