### ISSUE TITLE
Can you please add .py as a recognized format for imports?

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#554]
Hi

Anytime I want to import a .py file as a recognized note with systax highlight, all I get is an as an attacment to the parent note. It would be nice if I can import .py files as is and make it recognize as a .py note with syntax hightlighted.

thanks

**Comment by zadam** [comment]
Hello, this has been fixed and will be released soon. Used mime library did not recognize .py as python.

**Comment by gerroon** [comment]
thanks for the fix, I will test it out.
