### ISSUE TITLE
[Bug / GUI] Enter/Leave protected session button does nothing after entering protected session directly from protected note

### ISSUE THREAD

**Issue by kadadot216** [zadam/trilium#555]
trilium-linux-x64 v.**0.32.3**
on _Fedora 28 x86_64_, kernel v.4.15.8-300

Hello, and thank you again for this very cool application!

I am reporting an recent issue with the latest version (0.32.3) concerning the GUI button Enter/Leave protected session. I haven't tested the betas versions of 0.32, but I think the functionality was fine in 0.31.6.

When I get into protected session directly from the protected note's prompt. The button Enter/Leave protected session becomes unresponsive, preventing me to leave the session.
It works fine thought when I'm always using the button and by never touching the protected note's prompt.

Steps to reproduce:
1. Open trilium
2. Navigate to a protected note
3. Enter protected session mode through the protected note's prompt.
3.a. (Once in protected mode, the button's text is still "_Enter protected session_")
4. Try to leave protected mode by clicking the Enter/Leave protected session button.

The functionality is still working fine if we do this:
1. Open trilium
2. Navigate to a protected note
3. Enter protected session mode through the _Enter protected session_ button.
3.a. (In this case, the button switches normally to "_Leave protected session_")
4. Try to leave protected mode by clicking the _Leave protected session_ button again.

Log file:
```
16:23:21.676 info  generated sourceid=u6uoeqemlw1g 
16:23:21.676 info  app http server starting up at port 37507 
16:23:21.676 info  {
  "appversion": "0.32.3",
  "dbversion": 136,
  "syncversion": 9,
  "builddate": "2019-06-02t14:04:32+02:00",
  "buildrevision": "fbfb7b3b306d48ba9e7c09b7218af7354c58a3d1",
  "datadirectory": "/home/me/.local/share/trilium-data"
} 
16:23:21.851 info  db ready. 
16:23:21.871 info  get / 
16:23:21.879 info  db size: 4349 kb 
16:23:21.894 info  generated csrf token eglzbk86-lvs8nsymigtzbshaqyx_evtxmsi with secret _csrf=r6smc1iuj6mg4-afbzjjrpnr; path=/ 
16:23:21.894 info  generated sourceid=fh9bloj0fjhx 
16:23:22.418 info  get /api/options 
16:23:22.443 info  get /api/notes/download/sbbszioy2ftu 
16:23:22.444 info  get /api/notes/download/lrj2ulix3qki 
16:23:22.447 info  get /api/tree 
16:23:22.500 info  get /custom/fonts/roboto.woff2 
16:23:22.508 info  get /api/notes/2w09btopcsye 
16:23:22.575 info  get /api/notes/2w09btopcsye/attributes 
16:23:22.661 info  get /api/script/relation/2w09btopcsye/runonnoteview 
16:23:22.684 info  get /api/notes/uqqolj90mbu3 
16:23:22.738 info  get /api/notes/uqqolj90mbu3/attributes 
16:23:22.742 info  get /api/script/relation/uqqolj90mbu3/runonnoteview 
16:23:22.766 info  get /api/notes/xc8qjrz7kfpz 
16:23:22.819 info  get /api/notes/xc8qjrz7kfpz/attributes 
16:23:22.821 info  get /api/script/relation/xc8qjrz7kfpz/runonnoteview 
16:23:22.869 info  get /api/script/startup 
16:23:22.882 info  post /api/tree/load 
16:23:22.904 info  post /api/tree/load 
16:23:22.914 info  post /api/tree/load 
16:23:22.921 info  post /api/tree/load 
16:23:22.925 info  post /api/tree/load 
16:23:22.936 info  post /api/tree/load 
16:23:27.577 info  post /api/recent-notes 
16:23:27.738 info  post /api/recent-notes 
16:23:27.820 info  post /api/recent-notes 
16:23:30.989 info  post /api/login/protected 
16:23:31.190 info  get /api/tree 
16:23:31.240 info  get /api/notes/2w09btopcsye 
16:23:31.251 info  get /api/notes/2w09btopcsye/attributes 
16:23:31.652 info  get /api/script/relation/2w09btopcsye/runonnoteview 
16:23:31.659 info  get /api/notes/uqqolj90mbu3 
16:23:31.670 INFO  GET /api/notes/uqQOLJ90mBu3/attributes 
16:23:31.708 INFO  All consistency checks passed (took 19ms) 
16:23:31.836 INFO  GET /api/script/relation/uqQOLJ90mBu3/runOnNoteView 
16:23:31.844 INFO  GET /api/notes/xC8qJRz7KfPZ 
16:23:31.850 INFO  GET /api/notes/xC8qJRz7KfPZ/attributes 
16:23:31.985 INFO  GET /api/script/relation/xC8qJRz7KfPZ/runOnNoteView 
```

**Comment by kadadot216** [comment]
I tested it on multiple tabs and single note open too.

**Comment by zadam** [comment]
Yes, you're correct. Much of the frontend code had to be refactored for the tab support and this is one resulting regression ...

I will fix this soon, in the meantime, the workaround is pressing CTRL-R or (F5) which will reload the app frontend, thus effectively leaving the protected session (alternatively click on global menu -> reload).

**Comment by kadadot216** [comment]
Thank you for your swift response!
