### ISSUE TITLE
Feature request: error message

### ISSUE THREAD

**Issue by zYeoman** [zadam/trilium#559]
I think there should be an error message if the initial sync failed.

I have setup my trilium server, and it works fine with browser.  But I cannot sync to my server use the client. After select ` I have server instance up and I want to setup sync with it`, it just shows 
```
Sync in progress
Sync has been correctly set up. It will take some time for the initial sync to finish. Once it's done, you'll be redirected to the login page.
Outstanding sync items: 0
```
and never finish. And I cannot open the app once more.
Until just now, when I start it on linux, I find out that it's because that my client has newer version. But no error message told me about that.

**Comment by zadam** [comment]
Hello, thank you for reporting this issue.

You're right that this is not checked during initial handshake and then it silently fails once the sync is triggered. Fixing this is backwards incompatible in regards to the sync protocol, so it will be in the next minor version - 0.33.X.
