### ISSUE TITLE
Edit-branch-prefix feature does not autofocus the textbox

### ISSUE THREAD

**Issue by spantaleev** [zadam/trilium#560]
I frequently use the Clone/Paste feature, followed by renaming the new note clone (`F2`).

After pressing `F2`, I expect to begin typing a new name immediately.
(as would anyone who has used `F2` to rename a file on their computer).

However, when the "Edit Branch Prefix" dialog opens, the textbox is not focused, causing me to need to reach for the mouse, aim at the textbox and click on it (using `Tab` 3 times seems to be another alternative).

This is just a minor annoyance that degrades the UX.

**Comment by zadam** [comment]
Hello, this is now fixed and will be in the next patch release.

**Comment by spantaleev** [comment]
Thanks for the quick response!
