### ISSUE TITLE
Note revisions improvements

### ISSUE THREAD

**Issue by zadam** [zadam/trilium#561]
* revision overview should have some basic information about added/removed/changed lines to quickly see when the big changes happened
* clicking on a revision should ideally show both the state at that time and inline diff from revision before
* it should be possible to select two revision items, in such case the same view as above shows up, but of course shows the different between selected revisions
* there might be a button to restore the revision or at least make it easy to select the text at revision (might be difficult because of inline diff)
* it should be possible to "clean up" all revisions - probably just removing the payloads since we can't delete whole entity because of sync.

**Comment by sahil48** [comment]
Would it be possible to have named revisions, where we can also add a comment on what was changed? At 3 points revising the document, I may want to save them as a rev-A, rev-B, and rev-C document.

**Comment by zadam** [comment]
That's not planned. Revisions are supposed to be really transparent without user intervention.

If you want to make a named revision, you might just create subnote "rev-A" instead ...

**Comment by sahil48** [comment]
I'm fine with that. In that case, it would be nice to be able to diff two separate notes (ex. the active note and the rev-A subnote).

**Comment by zadam** [comment]
Closing, most of these have been implemented in 0.37 with the notable omission of diff which is covered in #334.
