### ISSUE TITLE
Connecting to server fails

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#563]
I have the server working with 3 other machines.

THis is ubuntu:

/trilium &
q@q ~/D/trilium-linux-x64> Generated sourceId=bw4Nwl1xcKkd
App HTTP server starting up at port 45455
{
  "appVersion": "0.32.4",
  "dbVersion": 136,
  "syncVersion": 9,
  "buildDate": "2019-06-05T22:53:34+02:00",
  "buildRevision": "97a258c0c61177f7a3578f41691d2bd9a600f5b8",
  "dataDirectory": "/home/q/.local/share/trilium-data"
}
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.

The app asked me for credentials, connected to the web, but showed zero notes to sync.

I also get:

`node:2141) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Getting document options from sync server.
Creating database for sync
Schema and not synced options generated.
Triggering sync.
sync failed: Request to POST https://retreatai.com:8080/api/login/sync failed, error: 400 Bad RequestError: Request to POST https://retreatai.com:8080/api/login/sync failed, error: 400 Bad Request
    at generateError (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:115:12)
    at ClientRequest.request.on.response (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:61:28)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/home/q/Downloads/trilium-linux-x64/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
`

**Comment by zadam** [comment]
Hello, is the server instance also 0.32? Unfortunately this is not checked/reported during the initial handshake and then sync just fails (#559).

**Comment by quesada** [comment]
No, it was 0.31.5. Thanks, that explains things.
So I guess I have to upgrade the server then
