### ISSUE TITLE
[Feature Request] Use selected text to create todo

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#567]
If there is text currently selected, I'd like the "new todo" button create the todo with the selected text as its contents.  ideally also add an internal link from the selected text to the todo and vice versa.

NOTE:  I am not sure how to get selected text as I assume that is controlled by the editor component or I'd have taken a crack at the code to modify the todo code to do this.

**Comment by zadam** [comment]
Interestingly, there has been a similar feature, which extracted selected text and created a child note. It has been deactivated because of issues with CKEditor, but it might be brought back.

**Comment by pcause** [comment]
if you had a trilium front-end API to get the selected test from the editor, it would be a very easy change.  might also add: delete selected text and replace selected text

**Comment by Grymas** [comment]
This might have been answered somewhere else but I would love the ability that has been deactivated, i.e. creating a new note with an internal link directly from selected text.

**Comment by a22a-dev** [comment]
I don't know when it was deactivated and reactivated, but it is available now. Just select the and a balloon shows up, where extreme right in balloon there is scissor iconed button call cut & paste selection to sub-note. I think this is what you want.
