### ISSUE TITLE
Wiki incorrect on where trilium data is stored / Linux

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#568]
The wiki says:

For server installations, you might want to configure e.g. port or TLS. This is done in the Trilium config file, by default it's in ~/trilium-data/config.ini (where ~ is your home directory).

but on Linux it seems to be ~/.local/share/trilium-data

should likely also say on Windows is  /Users/yourname/Appdata/Roaming/trilium-data

**Comment by zadam** [comment]
Thanks for the report. I fixed this by changing all those references to point to [data directory](https://github.com/zadam/trilium/wiki/Data-directory) page with complete description.
