### ISSUE TITLE
(0.33 beta) Search dropdown can get stuck overlaying the current selected note

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#569]
Steps to Re-create (0.33 beta):
1. Open Trilium
2. select a top level folder, press ctrl + p to create a child note
3. Shift click the child note to select it
4. press delete to delete the note
5. at this point you'll be brought to the 'new tab' screen, with the search dropdown showing suggestions
6. click any other note, and you'll see the search dropdown is overlayed on top (see screenshot)

![image](https://user-images.githubusercontent.com/1442520/59460490-33f57280-8ded-11e9-9663-fa225e4bc163.png)

**Comment by zadam** [comment]
Hello, I managed to reproduce this in a different way, hopefully it also fixes your problem.

**Comment by bwat47** [comment]
I can still re-create the issue with the 0.33.3 release: https://youtu.be/hpU4ha2sbgE

**Comment by zadam** [comment]
Thanks, I will take a look at this again then. These UI glitches are annoying.

**Comment by bwat47** [comment]
I can no longer re-create this in 0.33.4

**Comment by zadam** [comment]
Yes, I managed to reproduce it (strangely it was happening only on windows). Thanks for confirmation.
