### ISSUE TITLE
cannot paste from PW manager

### ISSUE THREAD

**Issue by peterschussheim** [zadam/trilium#570]
Just downloaded the mac version and am already having a bad experience.  Related: #267

**Comment by zadam** [comment]
Hello, unfortunately, Mac build is in a bad state and it is unlikely to change in the short term.

Until now, this was not properly communicated, so now I marked the Mac build on the README page as "unsupported" and created a [FAQ entry for this](https://github.com/zadam/trilium/wiki/FAQ#mac-os-support).

Thank you for understanding.
