### ISSUE TITLE
Protected notes auto-lock?

### ISSUE THREAD

**Issue by legion1978** [zadam/trilium#571]
Hello.
The wiki (and the Patterns of personal knowledge base) suggest that after some inactivity time, the notes will lock themselves. this time is set in the options, correct? but no matter what the value (secs) is, protected notes always stay open. if i ctrl+r Trillium does lock them up (or clicking on "leave protected session"). so maybe im missing something? i think it may be some UI issue, since i also noticed, for instance, "hoist note" works (it hides every other note) but clicking "unhoist" does nothing, only after a refresh.

thanks

**Comment by zadam** [comment]
Hello, thank you for reporting this, it really has been a bug. This will be fixed in the next 0.33 beta.

Regarding the unhoisting - IIRC this was a bug as well and it has been already fixed in 0.33.X.

**Comment by legion1978** [comment]
great!
