### ISSUE TITLE
[Question] Sqlite install problems during server installation on raspberry pi 

### ISSUE THREAD

**Issue by hakanu** [zadam/trilium#572]
Hi there,

I have been looking for a solution for this problem for a while but can not find anything.
So as last resort I'm asking here. I'm in a weird situation. I was happy with my server v0.31 and desktop client v0.31. And then I intended to try tabbed version :) So I added some notes and stuff. After a while realized there is version mismatch so syncing is no more possible. I have decided to upgrade server to v0.33 and failed due to npm-sqlite package installation failure on raspberry pi. Then I thought I can live without tabs so went back to v0.31 desktop client but that doesn't open at all in trilium logs I can see that v0.33 desktop client made the local database version to .33 so .31 is no more compliant :) My changes are trapped there, can not sync. So only way to save both sides is that I need to upgrade my server to v0.33. However, after I run ./trilium.sh I keep receiving this or similar sqlite related errors:
I'm sure this has nothing to do with trilium codebase itself. I'm more like seeking some wisdom on how to overcome this problem.

```
$ node -v
v12.4.0
$ npm -v
6.9.0
```

```
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-bu
ild --module=/home/pi/trilium-linux-x64-server_033_1/trilium-linux-x64-server/node_modules/sqlite3/lib/binding/node-v72
-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/trilium-linux-x64-server_033_1/trilium-l
inux-x64-server/node_modules/sqlite3/lib/binding/node-v72-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_
version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.9 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I have tried deleting node_modules, reinstalling; I have also tried npm install build from source, npm install prepublished sqlite etc. None of them worked. Each one takes so much time and then fails :/

Any idea is welcome. Thanks.

**Comment by zadam** [comment]
Unfortunately I don't know what's causing the error - there isn't many details anyway.

You might try 0.32.X which should be compatible with 0.33 (which brought some library upgrades including the sqlite). Another option is to export your notes into .tar, downgrade to previously working 0.31 and import your notes again.

**Comment by hakanu** [comment]
Awesome thanks, sorry for littering here.
