### ISSUE TITLE
pasting cut/copied notes no longer works (v 0.33.1 beta)

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#573]
Steps to Re-create:
1. Select a Note and press ctrl + c or ctrl + x to copy (or cut) the note. You'll see a notification that the note has been copied to the clipbpard as exected
2. Select some other folder and do ctrl + v to paste (or try pasting via the right click context menu)

Expected: The note should be pasted

Actual: Nothing happens when you press ctrl + v. In the context menu the past options are grayed out

**Comment by meiok1** [comment]
the same issue.

**Comment by meiok1** [comment]
![图片](https://user-images.githubusercontent.com/22992097/59703528-9d7de280-922c-11e9-8fd4-754f4c8e7c47.png)
docker version : 0.33.1-beta

**Comment by zadam** [comment]
Hello, thanks for reporting this. This is a regression which has been fixed already in master and will be in the next beta. 0.33 changed a lot in terms of selected/focused/active notes and this is one of the regressions.
