### ISSUE TITLE
[Feature Request] Possible to have multiple trilium (synced or not on differents backend)

### ISSUE THREAD

**Issue by Auroch** [zadam/trilium#575]
Hello,
I try to use Trilium with my colleague (as a shared knowledge base) through synchronization and it is a real success.
But before that, I used it for my personal needs.
So I currently have to choose between using it professionally or personally.
Would it not be possible to open a different database with its own synchronization parameters depending on the needs? And ideally, in this case, to be able to open 2 instances of Trilium each accessing a different database?

Thanks anyway already for this great tool!

**Comment by zadam** [comment]
Hello, you can have totally separate instance on the same computer by instructing Trilium to use a different [data directory](https://github.com/zadam/trilium/wiki/Data-directory). Data directory is configurable through an environment variable - I'd do it like this (on Linux):

```sh
TRILIUM_DATA_DIR=/home/user/trilium-data-private trilium
```

This will set the environment variable to a specific value only for this process. Of course it would be advisable to create a short script for that. I'm pretty sure you can do it similarly in windows as well (with .bat).

**Comment by Auroch** [comment]
Perfect, Thanks a lot !
