### ISSUE TITLE
[Feature Request] Today note template

### ISSUE THREAD

**Issue by zYeoman** [zadam/trilium#576]
Can I use a template with content? For example, `Day template`:
```markdown
### READ
### DONE
```
or some more complex template.

**Comment by spantaleev** [comment]
I was wondering the same.

Reading the wiki page on [Template](https://github.com/zadam/trilium/wiki/Template) leads me to believe that it might be possible:

> note content is copied from the template note to the instance note (if the instance note content is empty at the time of template attribute assignment)

However, this issue still being open and me failing to observe this behavior leads me to believe that:
- this feature might not have been implemented yet
- the wiki text is misleading

**Comment by zadam** [comment]
Hello, this has been implemented in 0.35.0-beta.
