### ISSUE TITLE
Mac: Trilium seemingly not respecting custom data dir

### ISSUE THREAD

**Issue by xingped** [zadam/trilium#578]
OS: Mac
Trilium Version: 0.33.3 (also happened on 0.32.4)

Today I opened up Trilium and suddenly it's not respecting the $TRILIUM_DATA_DIR environment variable. The variable is still set the same as it has always been (in ~/.bash_profile and `echo $TRILIUM_DATA_DIR` is correct) and it was working fine previously until it randomly stopped working. 

Not sure how to include a file, but below is the log tail for one load.

<details>
<summary>Details</summary>

20:07:57.831 INFO  Generated sourceId=HT89JeTdQUYl 
20:07:57.832 INFO  App HTTP server starting up at port 49297 
20:07:57.832 INFO  {
  "appVersion": "0.33.3",
  "dbVersion": 136,
  "syncVersion": 9,
  "buildDate": "2019-06-24T20:47:50+02:00",
  "buildRevision": "1b831f94a98dbbb7184048f329ea89175841dec2",
  "dataDirectory": "/Users/xingped/Library/Application Support/trilium-data"
} 
20:07:58.116 INFO  DB ready. 
20:07:58.125 INFO  GET / 
20:07:58.133 INFO  DB size: 897 KB 
20:07:58.133 INFO  Slow query took 205ms: INSERT  INTO source_ids(sourceId, utcDateCreated) VALUES (?, ?) 
20:07:58.140 INFO  Generated CSRF token g4xqHZUt-5S4b_TjxF_VoRtQcOrAby8gjMVs with secret _csrf=lnGdsZd2-6P-J6RjP1Urinuy; Path=/ 
20:07:58.141 INFO  Generated sourceId=UCi5JwSYxL0v 
20:07:58.584 INFO  GET /api/options 
20:07:58.602 INFO  GET /api/notes/download/Qqnp17dMuSfT 
20:07:58.606 INFO  GET /api/tree 
20:07:58.684 INFO  GET /api/notes/Qhvk5vKCGGmx 
20:07:58.753 INFO  GET /api/notes/Qhvk5vKCGGmx/attributes 
20:07:59.243 INFO  GET /api/images/75KqWLPavKj8/trilium-small.png 
20:07:59.308 INFO  GET /api/script/relation/Qhvk5vKCGGmx/runOnNoteView 
20:07:59.335 INFO  GET /api/script/startup 
20:07:59.342 INFO  POST /api/tree/load 
20:07:59.349 INFO  POST /api/tree/load 
20:07:59.354 INFO  POST /api/tree/load 
20:07:59.360 INFO  POST /api/tree/load 
20:07:59.366 INFO  POST /api/tree/load 
20:07:59.369 INFO  POST /api/tree/load 
20:07:59.377 INFO  POST /api/tree/load 
20:07:59.381 INFO  POST /api/tree/load 
20:07:59.388 INFO  POST /api/tree/load 
20:08:02.266 INFO  GET /api/app-info 
20:08:03.751 INFO  POST /api/recent-notes 
20:08:07.939 INFO  All consistency checks passed (took 19ms) 

</details>

Edit additional details: if I launch Trilium from the Terminal it works correctly, but it doesn't if I launch the app normally? Not sure why...

**Comment by zadam** [comment]
> if I launch Trilium from the Terminal it works correctly, but it doesn't if I launch the app normally? Not sure why...

That's a good hint. My guess is that when you launch Trilium "normally", your .bash_profile is not loaded so the environment variable is not set.

**Comment by xingped** [comment]
Hey, sorry to bother you with this issue since I know you don't really support the Mac version. After some more digging it seems that no Mac apps can read environment variables set in .bash_profile. Instead you need to create a file at /etc/launchd.conf with: `setenv TRILIUM_DATA_DIR /some/dir/here`

Ref: https://stackoverflow.com/questions/12165385/how-to-set-environment-variables-to-an-application-on-osx-mountain-lion/14285335#14285335

**Comment by xingped** [comment]
Actually, slight correction. As of OSX 10.10, launchd.conf is no longer used [1].

Instead, you should use a .plist file in /Library/LaunchDaemons/ [2].

[1] https://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-slash-etc-slash-launchd-dot-conf/
[2] https://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-launchd-plist/
