### ISSUE TITLE
Deleting note can break editing other notes until frontend refresh

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#582]
OS is Windows 10
Trilium version 0.33.5

Steps to Re-create:
1. Create a note structure with a top level folder and 2 notes under it:

TOPLEVEL NOTE
    CHILD NOTE 1
    CHILD NOTE 2

2. Select Child Note 2 and hit the delete key on the keyboard. Click yes when asked if you want to delete the note

3. Select Child Note 1 and try editing it

Expected: Should be able to edit the note

Actual: I can't edit the note title or note content. This is the case with any note that I select at this point.

NOTE: Reloading the front end will fix the issue

NOTE: Alt tabbing from trilium and then switching back to it will also fix the issue

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. This has been caused by bug in Electron (https://github.com/electron/electron/issues/18646), it affects only windows.

**Comment by zadam** [comment]
I implemented a workaround which doesn't use "native" confirm dialog, instead a bootstrap one which will not trigger the electron bug.
