### ISSUE TITLE
Is there a Chinese version?

### ISSUE THREAD

**Issue by shijunjie007** [zadam/trilium#583]
可否添加一个中文语言的设置呢

> Can I add a Chinese language setting?

**Comment by zadam** [comment]
Trilium Notes is english only for now. There might be some support for localization down the road, but not soon.

**Comment by bug0306** [comment]
太迫切希望来一个中文的了

**Comment by sepwolves** [comment]
> 
> 
> 太迫切希望来一个中文的了

没必要吧，看这么点英文不难啊。
能用trilium肯定都至少是本科生了。本科生还能看不懂这点英语 ？

**Comment by shijunjie007** [comment]
？？？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andy"<notifications@github.com&gt;; 
发送时间: 2021年2月3日(星期三) 上午10:25
收件人: "zadam/trilium"<trilium@noreply.github.com&gt;; 
抄送: "居士"<1035060635@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zadam/trilium] Is there a Chinese version? (#583)





  
太迫切希望来一个中文的了
  
没必要吧，看这么点英文不难啊。
 能用trilium肯定都至少是本科生了。本科生还能看不懂这点英语 ？

**Comment by BingChunMoLi** [comment]
抱歉拖国家后腿了，英语不好

**Comment by luolitao** [comment]
自己做，然后提交PR，可以吗？

**Comment by fsword** [comment]
> > 太迫切希望来一个中文的了
> 
> 没必要吧，看这么点英文不难啊。 能用trilium肯定都至少是本科生了。本科生还能看不懂这点英语 ？

localization是个正常需求，否认别人的正常需求才是“没必要”

**Comment by fsword** [comment]
> Trilium Notes is english only for now. There might be some support for localization down the road, but not soon.

Due to the lack of localization support at the moment, some coder have established a new [repo](https://github.com/Nriver/trilium-translation ) , so it is strongly recommended to support i18n/l10n to avoid fragmentation of the codebase. It'll be hoped to become the foundation for other language.
