### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by Karol-G** [zadam/trilium#587]
Hi,

I would like to request a feature. It is not possible to resize images. So if an image is small it gets shown small and vice versa. This can be very annoying at times.
It would be cool if you could implement a resize mechanic.

Best regards

**Comment by zadam** [comment]
By resize you mean just zoom, right? As in temporarily make the image larger for viewing, not really resize the image and save it as such.

As a workaround, you can zoom the whole app with `ctrl-+` which will also make images larger, although of course that's not ideal.

**Comment by Karol-G** [comment]
Hm, no I actually mean permanently resize/rescale the image. 
I often work with math equations and take images of them to paste them into Trillium.
Sometimes they are shown extremly small and barely readable and sometimes the image takes up half of the screen. This can be very annoying at times and disturbs readability.

Here are two examples:
![grafik](https://user-images.githubusercontent.com/3471895/60955655-944ed580-a301-11e9-9ba1-3243f395484a.png)

**Comment by zadam** [comment]
Okay, I think I misunderstood this a bit. This needs to be implemented on the editing component, but it looks like they are probably going to [work on this very soon](https://github.com/ckeditor/ckeditor5-image/issues/241).

**Comment by Karol-G** [comment]
Cool, that looks exactly like what I need.

**Comment by NoobAndProud-01** [comment]
Hi! I'm new here so I don't know the etiquette but if you look at the way VNote implements image notes that's the best IMO.
You paste your image and can add a size for it, then when you double click on it the image goes full size inside the note!

**Comment by zadam** [comment]
fixed in master

**Comment by zadam** [comment]
@NoobAndProud-01 I don't really have much choice in how this is implemented since it's done in the CKEditor. But I think it works quite well.
