### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by fairread** [zadam/trilium#589]
Hi I wonder as whether there is any setting to enable or adjust the text wrapping to say 80 characters only. Thanks.

**Comment by zadam** [comment]
no, there isn't, although if you know your way around CSS, it should not be difficult to [customize it yourself](https://github.com/zadam/trilium/wiki/Themes#custom-css).

**Comment by fairread** [comment]
Hi Zadam thanks for your reply. As per your suggestion, I have tried adding the body element with the word-wrap property as below:

`
body{ 
    max-width:1000px; 

}
`

But then the final words of the wrap limit were truncated instead such as 'wrapping' being wrapped as 'wrap<br>ping'

Any suggestion for this matter? Thanks again.

**Comment by zadam** [comment]
I wouldn't put this on the body, but on the editing component instead.

This quick experiment seems to do what you need:

```css
.note-detail-text {
    max-width: 1000px;
}
```
