### ISSUE TITLE
clipper?

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#590]
see lots of commits about "clipper".  is this some new capability?  web clipper?  Looked in the wiki and didn't see, but code looks to be some external app/web clipping.

**Comment by zadam** [comment]
It's a web clipper. Not release yet, coming in 0.34

**Comment by pcause** [comment]
looking forward to this!  please support firefox as well as chromium-based browsers.

**Comment by zadam** [comment]
Yes, FF and Chrome will be supported (they have the same extension model now). Other browsers based on chromium should work as well, but won't be tested etc.
