### ISSUE TITLE
Poor Download Speeds

### ISSUE THREAD

**Issue by munavirch** [zadam/trilium#591]
This is regarding the network performance of the build downloads, I'm not sure if you have any control over the same. Would you be able to get some support from GitHub. I've been trying to download the debian package since 3 days. URL expires by the time download finishes, which causes a network issue.

**Comment by zadam** [comment]
I'm afraid I can't do anything about this - it's probably a localized (and hopefully temporary) issue - for me download of latest debian build run at ~10 MB per second.
