### ISSUE TITLE
Important information about software work needed or easy to be found

### ISSUE THREAD

**Issue by ericfelipe99** [zadam/trilium#593]
I can't find something that says how software work with database. 
For example: 
Where's local database? 
Where's server scripts ? 
Can i use only local without server? 
How i can backup my local database? 

Thanks for app. It's very interesting.

**Comment by zadam** [comment]
I think most of your questions are answered in the following pages (and pages linking from it): 

* https://github.com/zadam/trilium/wiki/Data-directory 
* https://github.com/zadam/trilium/wiki/Backup

You can use the app locally, server is not required. Not sure what you mean by "server scripts".
