### ISSUE TITLE
[feature-request] sync/export markdown notes with directory structure for SCM

### ISSUE THREAD

**Issue by munavirch** [zadam/trilium#594]
I am able to export notes but in a single file. It would be great if notes can be exported in the exact same directory structure or sync notes as we go into the directories. This would help the user to store their notes in Git/SCM and share it with others. 

Otherwise, a post-export hook would also do the work since the user can decide what needs to be done after export is finished.

**Comment by zadam** [comment]
Hello,

I understand why you'd want to store your notes in SCM, but apart from the simplest cases it will just not work. Several things in trilium (clones, links/relations, attributes) are not representable by the filesystem and have to be stored inside big metadata file. Some discussion on why Trilium intentionally does not use file system is in [FAQ](https://github.com/zadam/trilium/wiki/FAQ#why-database-instead-of-flat-files).

**Comment by munavirch** [comment]
Thanks for your response. I understand why export to flat files doesn't make sense here. How about allowing the user to perform a post export hook? User can save a particular command in the hook section and trilium will automatically run the command once the export is done.

**Comment by kunaltyagi** [comment]
> Several things in trilium (clones, links/relations, attributes) are not representable by the filesystem

This is understandable. Would it be possible to create a lossy export/lossless import? As long as my imports from markdown (directory + files) work, I can stop managing two different note systems.

Similarly, if I can export in a lossy directory + files, it's ok (as long as the export function cautions the user about the pitfalls).

Some acceptable compromise IMO are:
* clones: follow what git does: duplicate the files if symlinks are not allowed by the underlying filesystem. Randomly choose one as source for the symlinks (or the first one in the hidden export queue)
* attributes: ignore, for now. Expecting a perfect export is not really sensible IMO.
* directory vs trillium hierarchy: create a file with name [directory].[random_string, say hash], on collision, fail with a notice at the end of export.

The export (and import) can be made better over-time ofc, but does this sound like a good idea? I mostly just read the FAQ and checked how git manages softlinks and hardlinks, attributes, etc.

**Comment by zadam** [comment]
@kunaltyagi you can already export to .tar file (with notes in markdown) and it works similarly to how you describe. Lossy things (attributes, real note name) are saved in a sidecar metadata file so it is actually lossless when imported back to trilium (and lossy when used by some other app).

**Comment by kunaltyagi** [comment]
Oh, thanks for that. :)
