### ISSUE TITLE
trillium note navigation issue on macOS

### ISSUE THREAD

**Issue by ryansyah** [zadam/trilium#599]
Hello,

Running Trilium App version: 0.30.7 on macOS. When interacting with a note, I can typically use my arrow  keys, or mouse/trackpad to move up/down within a given note. However, today I noticed that when I change Trilium into distraction free mode `alt+M`, I am no longer able to pan a note up/down with keyboard or mouse/trackpad. Not an issue with short notes, but makes distraction free mode inoperable when reviewing notes that span multiple pages.

**Comment by zadam** [comment]
Hello, I recommend trying latest version (0.34.1) - I checked and I believe it's working correctly now. I faintly recall this was fixed a while back.
