### ISSUE TITLE
No more trilium-data folder?

### ISSUE THREAD

**Issue by taa1** [zadam/trilium#6]
Trilium v0.3.3/0.4.0

How do I copy what used to be document.db from one PC to another?

https://github.com/zadam/trilium/wiki/Document
https://github.com/zadam/trilium/wiki/Synchronization

**Comment by zadam** [comment]
I'm not sure if I understand the question. You can simply copy the existing document.db on e.g. USB flash drive (or cloud storage like Dropbox) and from there copy the file into target computer ...

**Comment by taa1** [comment]
DOH -- I thought it would be in one of the subdirectories off the installation directory, trilium. Sorry to have bothered you.
