### ISSUE TITLE
Multiple users and multiple todo's?

### ISSUE THREAD

**Issue by raman325** [zadam/trilium#600]
Are there any roadmap plans to support multiple users and/or using the task manager plugin in multiple folders?

Re: multiple users - I want to introduce my wife to this app to see if she would like it, but I would not like to have a custom subdomain to be used for each of us uniquely. As such it would be great to have multi user support.

Re: task manager in multiple folders - I want to create separate buttons to create a personal task and to create a work task. I don't have a lot of experience with JS so maybe this is on me, but I tried duplicating the task manager folder including the Implementation folder, changing button names, and it doesn't seem to support having the same task management plugin supported twice. Any alternate suggestions would be appreciated.

Thanks!

**Comment by zadam** [comment]
Hello,

* task manager - the important thing here is that it's really just a simple example "plugin". I'm not really plan to develop it further. However I think it should not be difficult to duplicate it so it manages tasks in a different subtree. But for that some knowledge of scripting in JS would be required.
* multi user - see [item in FAQ](https://github.com/zadam/trilium/wiki/FAQ#multi-user-support)

**Comment by raman325** [comment]
Thanks! I'm sure I can figure it out eventually, I was just hoping you've come across this question before and had something you could easily point me to.
