### ISSUE TITLE
Can't see any child nodes under root on Safari Mobile

### ISSUE THREAD

**Issue by raman325** [zadam/trilium#601]
Version: v0.34.1
Browser: Safari Mobile
Issue: I can only see the `root` note and I can't figure out how to get to any of the child notes. Any idea why this is happening? I can't see any errors in the logs, just the generation of CSRF tokens

**Comment by zadam** [comment]
I noticed that sometimes it takes a long time to display the tree on the mobile and in the meantime only the root note is visible. Could it be this?

**Comment by zadam** [comment]
Hello, I investigated again and it was not what I thought originally. It's a bug in a mobile version which (depending on some conditions) does not expand the root node. I fixed it already and will release a new version soon. Thanks for reporting this.
