### ISSUE TITLE
clipper enhancement - aggregate node

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#605]
It is great that the clipper is here.  The behavior to add under the current date makes sense.  However, I'd like to have an easy way to see all clipped notes that are added.  Since a note can be in multiple places is the tree, how about having a node called "clipped" that the clipped notes are also initially linked to.  Therefor I can see all my clipped notes, but more importantly, I can then decide to "move them" from clipped to another node for filing once I get a chance to review.  The note would then be findable by either date or by where I filed them.

**Comment by zadam** [comment]
Might not be exactly what you want but all clipped notes have `@clipType` attribute so you can easily search them an even create [saved search note](https://github.com/zadam/trilium/wiki/Search#saved-search) where you can see all clipped notes ...

**Comment by pcause** [comment]
thanks.  i should be able to create a script for the server that does what I want with this.
