### ISSUE TITLE
Add ability to reorder attributes

### ISSUE THREAD

**Issue by belisama** [zadam/trilium#607]
As you add attributes over time, it's easy for them to get all jumbled together. It's especially bad for promoted attributes, since those get looked at a lot. The ability to drag-and-drop entries in the attribute dialog would fix that right up.

**Comment by zadam** [comment]
Hello, yes, actually attributes are sorted internally and there used to be a drag & drop UI, but it has been removed along the way.

I plan a UI redesign of attributes and this should be part of it.

**Comment by zadam** [comment]
Attributes can be reordered since 0.43 by changing the position of the attributes in the text box.
