### ISSUE TITLE
Feature Request: View The Content of Multiple Nodes in a Book-like Format

### ISSUE THREAD

**Issue by sahil48** [zadam/trilium#609]
I really like the functionality of this application and am planning to switch from TiddlyWiki to this application for storing my notes (https://tiddlywiki.com/). It is much more structured, is very well thought out, and easier to keep images and files in it.

One of the features of Tiddlywiki that I like is that you can view multiple notes one after another. If you have something like a journal or subject matter to review, in Trillium, it would be great to be able to select a node, right click, and select an option to view all notes in one continuous document, or shift click multiple notes and view them in a continuous stream. It would be even more amazing if documents shown in this view could be reordered and these views saved as their own nodes for future reference. Double Clicking a document in this view could open it for editing in a separate tab.

**Comment by zadam** [comment]
Interestingly I do use very similar approach for some specific notes, but using scripts and not with a built-in functionality.

But I can see how this can be generally useful, especially when you have a lot of short-ish notes. This would also partially solve my long term issue that certain type of notes are essentially folder-like - that they don't have any own content and only exists to group their children - this makes the right pane quite useless for these type of notes.

The way I imagine this is that there would be a new note type - "overview" or "book" or something and its detail pane would display its children notes - so this would be your second variant, including the ability to reorder for example. We might also add expanders for displaying sub-children.

> it would be great to be able to select a node, right click, and select an option to view all notes in one continuous document, or shift click multiple notes and view them in a continuous stream.

This does not fit as well into the trilium concepts but I think it would not be as important if the other variant exists.

**Comment by sahil48** [comment]
The variant you described sounds fine. Using the root node with your suggested approach, I would be able to implement the second idea.

**Comment by zadam** [comment]
Implemented in master as a "book" note type and will be released in 0.36
