### ISSUE TITLE
Question: Storing Backups Separate from Main File

### ISSUE THREAD

**Issue by sahil48** [zadam/trilium#610]
In the documentation, I saw that Trillium's reference to the main database can be updated. Is it possible to Trillium to backup the database to a different location (point backup to a Dropbox folder, and keep the main database in the default location on the computer)?

On a related note, if you need to recover information from a backup database, or you work on two separate databases that you decide to merge in future, what approach should be taken? I feel being able to have separate Trillium databases, one for work, one for classes, one for a book you are reading, etc, might be beneficial in the future.

**Comment by zadam** [comment]
I apologize, looks like I missed some issues. You can change the whole data directory using `TRILIUM_DATA_DIR` environment variable, but not the backup specifically. But that should be easy using symlinks.

**Comment by sahil48** [comment]
Thank you for following up. That makes sense. Good idea!
