### ISSUE TITLE
Feature Request: Button to Add Path

### ISSUE THREAD

**Issue by sahil48** [zadam/trilium#611]
![image](https://user-images.githubusercontent.com/6100774/62576133-3ebb0980-b86a-11e9-8a35-a78944372ca9.png)

When I click the dropdown of the path, I would like the option to "add a path" to the document so it is easier to place the note everywhere I would like to place it. When implementing the feature, if the path does not exist, it should be created. To do this, I would select a matching path, and add the additional parent or children notes to the beginning or end of the path.

I would use this feature to effectively add "tags" the notes more conveniently.

**Comment by zadam** [comment]
Will be in 0.39
