### ISSUE TITLE
Question: Upgrading Trilium

### ISSUE THREAD

**Issue by sahil48** [zadam/trilium#612]
Is an upgrading mechanism built into Trilium, or do I have to keep downloading the next version of Trilium from the release page. At the very least, can I check if an update is available from the app?

**Comment by zadam** [comment]
Upgrading is not handled and you have to download a new version manually every time. I don't plan implementing this feature since auto upgrades might break the sync since you should upgrade all sync instances at the same time (at least sometimes when sync protocol changes).

**Comment by sahil48** [comment]
Update check and notification sounds good. A warning that the instance is not up to date would be nice to.

Example from Keepass is below.
![image](https://user-images.githubusercontent.com/6100774/62782507-625b9b00-ba88-11e9-9b3d-ced9e9342ff8.png)
