### ISSUE TITLE
Feature Request: Duplicate Note or Subtree

### ISSUE THREAD

**Issue by sahil48** [zadam/trilium#613]
Please add an option to duplicate a note or subtree so that the duplicated copy can be edited independently of the original note.

**Comment by zadam** [comment]
Yes, this would be a logical feature. Currently cumbersome workaround is to export note (subtree) and then import again.

**Comment by zadam** [comment]
Duplicate note (not subtree) has been implemented in master.

**Comment by zadam** [comment]
If subtree duplication is still needed, it would be better to create separate issue.
