### ISSUE TITLE
Option to open note in another application

### ISSUE THREAD

**Issue by sahil48** [zadam/trilium#614]
It would be great to add a note action to open note in another application. For example, a markdown, latex, or html note could be opened in another application, like visual studio code or texmaker, which can render the document more effectively. Once edited, the document can be imported back into Trilium.

**Comment by zadam** [comment]
Yes, that would be nice. (Somebody else already requested it in another issue, but can't find it now)

However it's not obvious to me how to do the second part - detecting that the app saved the content and that I should update the trilium note ...

**Comment by sahil48** [comment]
For me, a button I click to update the trilium note, with an option to revert changes (which is already handled by the automatic versioning of files) would be sufficient for me. I can take responsibility for updating trilium when I edit the content outside of Trillium.

**Comment by zadam** [comment]
Support for opening note externally has been added a while ago:

![image](https://user-images.githubusercontent.com/617641/182666929-0a139214-4d0f-48cf-a090-fa8efd04f631.png)
