### ISSUE TITLE
Avast says Trilium is a virus

### ISSUE THREAD

**Issue by NoobAndProud-01** [zadam/trilium#622]
Windows 7
Latest version of Trilium

When clicking the .exe Avast goes crazy and tries to move the .exe to the virus vault or erase it, Trilium keeps trying to start and Avast keeps trying to stop it

**Comment by zadam** [comment]
Thanks for the info. However I probably can't do anything with it.

This might affect other electron apps as well since the executable should be very similar. If that's the case then maybe Avast might notice and fix it ...

**Comment by NoobAndProud-01** [comment]
I think Joplin is an electron app and doesn't get detected as virus, in fact, none of the 100 note apps I'm testing do. And the problem is that Trilium tries to start and Avast stops it then Trilium keeps starting and Avast keeps trying to kill it until you go to the Task Manager and stop it making it unusable.

Here's the TotalVirus scan: https://www.virustotal.com/gui/file/0f036a3bb2b60f77215f3fe1431438ed2aad35dbf7e6f59216f6111d2d312c55/detection

**Comment by jhdcruz** [comment]
The reason is **probably** this:
![Annotation 2019-09-11 144448](https://user-images.githubusercontent.com/28413338/64674263-f0b9a700-d4a2-11e9-893b-dc04f8ee0a8d.jpg)
