### ISSUE TITLE
what am I doing wrong - code note to add languages not running

### ISSUE THREAD

**Issue by ecstatic-shark** [zadam/trilium#624]
Pretty new to using this - let me know if there's a better way to get this question to you.

I'm trying to use a code note to add language support (per the example you provided on the wiki) but haven't been able to get it to work.

The note is flagged with @run=frontendStartup, but does not change anything when restarting frontend or running manually. It is set as "Type: JavaScript frontend". I've also tried moving the note to just below root and within other directories. I've done the other easy stuff, closing and reopening the program and rebooting.

Code is copied from wiki, with minor additions.
code:
`//add ocaml,posh,r
const codeMimeTypes = api.getDefaultCodeMimeTypes();
codeMimeTypes.push({
    mime: "text/x-ocaml",
    title: "OCaml"
});

codeMimeTypes.push({
    mime: "text/x-rsrc",
    title: "R"
});

codeMimeTypes.push({
    mime: "application/x-powershell",
    title: "PowerShell"
});

// sort alphabetically
codeMimeTypes.sort((a, b) => a.title > b.title ? 1 : -1);

api.setCodeMimeTypes(codeMimeTypes);`

**Comment by zadam** [comment]
Hello, I tried what you describe and as you say this doesn't work anymore - basically because it depends too much on when this script is executed which causes that old tabs don't take this into account and only new tabs are updated.

But this is kind of a hacky solution so I started working on a better replacement.

**Comment by zadam** [comment]
Hello, new, more declarative solution is described in https://github.com/zadam/trilium/wiki/Code-notes

It will be available in 0.35. Thank you for pointing out this issue!
