### ISSUE TITLE
error in cross compilation Docker ARM img

### ISSUE THREAD

**Issue by david6908** [zadam/trilium#625]
Here is error information when I cross compilation docker arm img in OSX Docker Desktop latest version. Any suggestions with thanks!

iMac$ docker buildx build --platform linux/arm64 -t trilium --push .
[+] Building 6935.6s (7/9)                                                                                                                               
[+] Building 6935.9s (8/9)                                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                                0.0s
 => => transferring dockerfile: 32B                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                   0.0s
 => => transferring context: 34B                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:12.6.0-alpine                                                                               6.1s
 => [1/5] FROM docker.io/library/node:12.6.0-alpine@sha256:182778091c2c27ffa76caa41e762b21a2555118bae00212c52b347bddbc058ba                         0.0s
 => => resolve docker.io/library/node:12.6.0-alpine@sha256:182778091c2c27ffa76caa41e762b21a2555118bae00212c52b347bddbc058ba                         0.0s
 => [internal] load build context                                                                                                                   0.0s
 => => transferring context: 52.62kB                                                                                                                0.0s
 => CACHED [2/5] WORKDIR /usr/src/app                                                                                                               0.0s
 => CACHED [3/5] COPY package.json package-lock.json ./                                                                                             0.0s
 => ERROR [4/5] RUN set -x     && apk add --no-cache --virtual .build-dependencies         autoconf         automake         g++         gcc     6929.6s
------                                                                                                                                                   
 > [4/5] RUN set -x     && apk add --no-cache --virtual .build-dependencies         autoconf         automake         g++         gcc         libtool         make         nasm         libpng-dev         python     && npm install --production     && apk del .build-dependencies:                             
#7 0.262 + apk add --no-cache --virtual .build-dependencies autoconf automake g++ gcc libtool make nasm libpng-dev python                                
#7 0.292 fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/aarch64/APKINDEX.tar.gz                                                                    
#7 15.43 fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/aarch64/APKINDEX.tar.gz                                                               
#7 31.28 (1/37) Upgrading musl (1.1.20-r4 -> 1.1.20-r5)
#7 48.68 (2/37) Installing m4 (1.4.18-r1)
#7 53.33 (3/37) Installing libbz2 (1.0.6-r7)
#7 54.84 (4/37) Installing perl (5.26.3-r0)
#7 313.6 (5/37) Installing autoconf (2.69-r2)
#7 332.9 (6/37) Installing automake (1.16.1-r0)
#7 340.9 (7/37) Installing binutils (2.31.1-r2)
#7 412.2 (8/37) Installing gmp (6.1.2-r1)
#7 422.4 (9/37) Installing isl (0.18-r0)
#7 443.9 (10/37) Installing libgomp (8.3.0-r0)
#7 445.2 (11/37) Installing libatomic (8.3.0-r0)
#7 445.5 (12/37) Installing mpfr3 (3.1.5-r1)
#7 449.8 (13/37) Installing mpc1 (1.0.3-r1)
#7 451.7 (14/37) Installing gcc (8.3.0-r0)
#7 1397. (15/37) Installing musl-dev (1.1.20-r5)
#7 1519. (16/37) Installing libc-dev (0.7.1-r0)
#7 1520. (17/37) Installing g++ (8.3.0-r0)
#7 2517. (18/37) Installing ncurses-terminfo-base (6.1_p20190105-r0)
#7 2518. (19/37) Installing ncurses-terminfo (6.1_p20190105-r0)
#7 2546. (20/37) Installing ncurses-libs (6.1_p20190105-r0)
#7 2555. (21/37) Installing readline (7.0.003-r1)
#7 2559. (22/37) Installing bash (4.4.19-r1)
#7 2579. Executing bash-4.4.19-r1.post-install
#7 2579. (23/37) Installing libltdl (2.4.6-r5)
#7 2580. (24/37) Installing libtool (2.4.6-r5)
#7 2598. (25/37) Installing make (4.2.1-r2)
#7 2602. (26/37) Installing nasm (2.13.03-r0)
#7 2624. (27/37) Installing libpng (1.6.37-r0)
#7 2630. (28/37) Installing pkgconf (1.6.0-r0)
#7 2632. (29/37) Installing zlib-dev (1.2.11-r1)
#7 2637. (30/37) Installing libpng-dev (1.6.37-r0)
#7 2641. (31/37) Installing expat (2.2.7-r0)
#7 2643. (32/37) Installing libffi (3.2.1-r6)
#7 2643. (33/37) Installing gdbm (1.13-r1)
#7 2647. (34/37) Installing sqlite-libs (3.28.0-r0)
#7 2666. (35/37) Installing python2 (2.7.16-r1)
#7 3191. (36/37) Installing .build-dependencies (0)
#7 3191. (37/37) Upgrading musl-utils (1.1.20-r4 -> 1.1.20-r5)
#7 3193. Executing busybox-1.29.3-r10.trigger
#7 3193. OK: 249 MiB in 51 packages
#7 3193. + npm install --production
#7 3194. Unknown QEMU_IFLA_INFO_KIND ipip
#7 3194. Unknown QEMU_IFLA_INFO_KIND ip6tnl
#7 3525. 
#7 3525. > sqlite3@4.1.0 install /usr/src/app/node_modules/sqlite3
#7 3525. > node-pre-gyp install --fallback-to-build
#7 3525.

**Comment by zadam** [comment]
I'm sorry, I've neither seen this issue, nor attempted compilation for ARM ...
