### ISSUE TITLE
Wiki Docker docs: persistent volume

### ISSUE THREAD

**Issue by tbnorth** [zadam/trilium#627]
https://github.com/zadam/trilium/wiki/Docker-server-installation#run-image

says 

`-v ~/trilium-data:/root/trilium-data`

for persistent data storage, but I think it should be

`-v ~/trilium-data:/home/node/trilium-data`

that's the folder About Trilium Notes reports, and that seems to work, whereas the wiki version doesn't.

**Comment by zadam** [comment]
Well, the second path is on the host system and depends on your user and where you want to mount it ... But I changed the path in the wiki since you are right that the /root/ would be incorrect in most cases ...

**Comment by zadam** [comment]
I see, you're right, I flipped it. I now remembmer the /root/ thing might be from a time where a different base OS was used which ran under a root, but then the image was changed to a lighter one and that runs with a node user. Wiki fixed, thanks!

**Comment by ovizii** [comment]
Doesn't work for me, I had to use:

`-v mylocalpath:/root/trilium-data `

and now trilium saves stuff inside mylocalpath. 
When using `:/home/node/trilium-data` nothing was saved.

This is with trilium 0.35-latest

**Comment by riclage** [comment]
Same for me on version 0.37.5. Had to run the command: 
```
sudo docker run -t -i -p 8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:0.37.5
```
