### ISSUE TITLE
Deleted attachments remain in DB even after vacuuming

### ISSUE THREAD

**Issue by mtomas7** [zadam/trilium#628]
V0.34.3 win x64

I noticed if I would attach file (I would drag video file), it would be created as sub-note, but after deletion and vacuuming DB size would still be as it has video in it. I assume this is related to internal version control, but deleted notes are not present in versions list.

**Comment by zadam** [comment]
Hello, what happens is that deletion only actually soft-deletes the note and the note content is deleted after a day. This was meant to allow undoing mistaken deletions. But yeah, it might be surprising and it's not really documented ...

(even after a day there remains a trace of a deleted note which includes some meta data)
