### ISSUE TITLE
No [Today] Button in default UI

### ISSUE THREAD

**Issue by Johnson-yue** [zadam/trilium#630]
My question is: I have error UI that did not have ** [Today]** Button.

My os is MacOS 10.14.6
My download file is **trilium-mac-x64-0.34.3.zip**

when I unzip and double-click to startup this my UI is:
![image](https://user-images.githubusercontent.com/10268274/64141220-cd0ab700-ce39-11e9-9c6b-ef3b1a5e041b.png)

whatever I choice any version , my UI always like this!!!!
I have tried many Trilium version, but always like this, I ever deleted *demo* before,  I want to use new UI, and import new UI configure file not use this!!

what should I do,  I can't use this UI !!

For bug reports, please mention **version=0.34.3** and include **log files** from following location:

* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS
Logs :

>    cat trilium-2019-09-03.log
10:43:45.839 INFO  Generated sourceId=jHhi8bfwVLaK
10:43:45.984 INFO  App HTTP server starting up at port 37840
10:43:45.984 INFO  {
  "appVersion": "0.34.3",
  "dbVersion": 136,
  "syncVersion": 9,
  "buildDate": "2019-08-13T21:48:56+02:00",
  "buildRevision": "90f1bfb3e4838cfea676c7968473c6978ecbed1b",
  "dataDirectory": "/Users/qiangyue/Library/Application Support/trilium-data",
  "clipperProtocolVersion": "1.0"
}
10:43:46.128 INFO  DB ready.
10:43:46.131 INFO  DB size: 860 KB
10:43:46.210 INFO  GET /
10:43:46.217 INFO  Generated CSRF token vlBk2BLO-fbmW3FZLUxDWSYDDXevpr1ecpaM with secret _csrf=1uWsISEe335dFExMxdIkWDMo; Path=/
10:43:46.217 INFO  Generated sourceId=PDIsMDgEZHnv
10:43:46.495 INFO  GET /api/options
10:43:46.505 INFO  GET /api/tree
10:43:46.561 INFO  GET /api/notes/fXzV6m6kEz9g
10:43:46.592 INFO  GET /api/notes/fXzV6m6kEz9g/attributes
10:43:46.844 INFO  GET /api/script/relation/fXzV6m6kEz9g/runOnNoteView
10:43:46.856 INFO  GET /api/script/startup
10:43:46.997 INFO  Created backup at /Users/qiangyue/Library/Application Support/trilium-data/backup/backup-daily.db
10:43:47.002 INFO  Created backup at /Users/qiangyue/Library/Application Support/trilium-data/backup/backup-weekly.db
10:43:47.007 INFO  Created backup at /Users/qiangyue/Library/Application Support/trilium-data/backup/backup-monthly.db
10:43:51.592 INFO  POST /api/recent-notes
10:43:56.009 INFO  All consistency checks passed (took 14ms)

**Comment by zadam** [comment]
Hello, Today button is an example script inside the demo document - if you deleted it then it disappeared. You can import the [demo document](https://github.com/zadam/trilium/raw/stable/db/demo.tar) again and it will appear after reload (CTRL-R) or restart.

**Comment by Johnson-yue** [comment]
how to import the demo document ???

**Comment by zadam** [comment]
Did you reload/restart after importing? Also I'm not sure what kind of UI changes you expect?

**Comment by Johnson-yue** [comment]
I am sure reload and restart， I only want to use 【today】 button， but it not has
