### ISSUE TITLE
Request feature manage tasks

### ISSUE THREAD

**Issue by mphat10** [zadam/trilium#631]
I want to use trilum to manage tasks.
The idea is simple, each task has two check box before the content.
so when I use, I will write contents.
every time I start a task, I check the first box, when I finish a task, I check the second box.
I know it will need something with Render Html note, but I dont know how to do.
Please help me.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/20958000/64225911-63150f00-cf18-11e9-8add-5956afe5d1de.png">

**Comment by zadam** [comment]
Hello, the good news is that checkboxes are coming in 0.35 (beta this week).

The bad news is that currently it's limited to one checkbox per line so you won't be able to have two checkboxes next to each other ...
