### ISSUE TITLE
Default option

### ISSUE THREAD

**Issue by Gadgetroch** [zadam/trilium#632]
Good morning,

It would be great if you can select default type page like markdown in settings.

Possible ?

Thank's

**Comment by gerroon** [comment]
This would be great, I think that most people might prefer markdown as the default page type given that markdown can also act as a simple txt file.

**Comment by zadam** [comment]
When you create a new note, it takes its type from a parent (works only for text and code, but that's OK for this) - so if you make root note a code note with markdown type, then all its new children will be created as MD code notes, their children as well etc.

**Comment by Gadgetroch** [comment]
It's not cool to reply only other people...

**Comment by zadam** [comment]
Sorry, that's not intentional, sometimes I overlook an issue, or read it and then forget to reply ...

**Comment by Gadgetroch** [comment]
Okay i understand. Your app is nice, anyway. I use it on my server and thank's for reply.

**Comment by gerroon** [comment]
@zadam

Is this behavior remembered across sessions? Or just for the current session?

**Comment by zadam** [comment]
Yes, it's not related to sessions - when creating note we just look at the parent note type.
