### ISSUE TITLE
New Beta 35.0:  Lost data

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#633]
I just installed the new beta and started from a web browser.  I had a part of the tree with a lot of articles.  many nodes, with children and articles.  they are gone.  Journal and todos seem there but things I added are GONE!!!!  And, it added back stuff from the sample database I deleted

**Comment by zadam** [comment]
It's unlikely that the data have been lost - there was some minor data migration but nothing which could lose notes.

More likely is that the app somehow errors out during rendering the tree or something - could you attach the application logs?

Alternatively, are you sure that the new app uses the same data directory as the old one? (can be checked with Menu -> About Trilium Notes)
