### ISSUE TITLE
Typing changes letters on mobile

### ISSUE THREAD

**Issue by tgrosinger** [zadam/trilium#636]
**Version:** 0.34.3 and 0.35-latest server in Docker
**Client:** Firefox and Firefox Focus on Android 10

**Observed Behavior:**

When typing in a note, spaces between words are replaced with the first letter of the word. For example:

Whyiistthesspacingssowweird

Here's how that line is built as I type letter by letter:

- "Why"
- "Why "
- "Why i"
- "Whyiis"
- "Whyiis "
- etc.

I tested this in Firefox Focus to ensure that my extensions in Firefox were not affecting the behavior.

Let me know if I can provide more information.

**Comment by zadam** [comment]
Hello, thanks for the report, it's a [bug in the editing component - CKEditor](https://github.com/ckeditor/ckeditor5/issues/2046).

**Comment by zadam** [comment]
Not sure what has been fixed but latest release 0.38.2 seems to work fine with latest firefox (tried standard and preview).
