### ISSUE TITLE
[Help needed] How to create tables?

### ISSUE THREAD

**Issue by simonszu** [zadam/trilium#637]
Hi,

i need a little help: How does one create tables in a note? CKEditor has the [Table](https://ckeditor.com/docs/ckeditor5/latest/features/table.html) feature, but in their demo it looks like you need a table button in the menu bar - trilium does not have such button. So i am wondering how to create a table.

**Comment by zadam** [comment]
You need to click on the "block" button:

![grafik](https://user-images.githubusercontent.com/617641/64846721-9ab54280-d60d-11e9-9911-2a6f155c2843.png)

**Comment by simonszu** [comment]
Ah, okay. Thanks a lot.

**Comment by k-byun** [comment]
This wasn't too obvious for as well.  Thanks.
