### ISSUE TITLE
[BUG] Shell type not working

### ISSUE THREAD

**Issue by akyag** [zadam/trilium#639]
I am on **0.35.0-beta**. I was adding a shell script as a note and tried to add the "shell" type in the options but it never got added to the note type list. Tried with other types and that worked. 
Log: https://www.pastery.net/nkrhgf/

**Comment by hakanu** [comment]
It's removed from the UI for some reason in 0.35.0-beta. 
I'm going with old school code blocks :/

**Comment by zadam** [comment]
Hello, there was a typo in the shell mime definition, this is fixed now. Thanks for reporting this.
