### ISSUE TITLE
Importing from HTML in TAR archive

### ISSUE THREAD

**Issue by akyag** [zadam/trilium#642]
I am on linux, using the executable 0.34.3. I was just testing around worst case scenarios and tried exporting the whole notebook and then importing back from the tar. Everything was imported except the code notes. js, xml, css for example. They were imported as files. Is this how its intended? and if so, how to turn them back into code notes?

**Comment by zadam** [comment]
Hello, this is not intended. If you export the .tar it also carries a "sidecar" file "!!!meta.json" which carries the metadata about the notes, including the type. So if you then import this .tar file again, all notes should appear exactly the same.

**Comment by akyag** [comment]
The archives had the meta.json file. I just tried it on the latest 0.35.1 release, and everything looks good when imported. Code notes have preserved their types. I will try and see if that behavior replicates.
