### ISSUE TITLE
Host value in config.ini

### ISSUE THREAD

**Issue by ovizii** [zadam/trilium#643]
Hi there,

I am running 0.35-beta via docker and am wondering what value the "host" variable accepts. 
I tried using my domain name where my trilium instance is running but that won't work. Should I use the IP? 
btw. my intance is running behind traefik as a reverse proxy in case that matters.

**Comment by zadam** [comment]
Hello, yes, IP is expected. `0.0.0.0` (listen on all IPs) should be fine for most use cases unless you want to restrict the access somehow ...

**Comment by ovizii** [comment]
Thanks.
