### ISSUE TITLE
[Feature Suggestion] Pop up tree for cloning

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#644]
Right now if you want to clone a note and link somewhere else you have to CTL-C the note and then scroll to where you want to put the note and then do paste/paste into.  Perhaps a "clone" menu entry should exist and then a dialogue box pops with a tree shown and the user can select where to paste or even multi-select.  A filter at the top to make selecting by typing the name (sort of like search) would be useful.

I think cloming is one of the most powerful features and want to make it easier to use.

**Comment by zadam** [comment]
This has been added in 0.37 IIRC.
