### ISSUE TITLE
R support for syntax highlighting

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#645]
It would be wonderful if syntax highlighting for R was supported.

**Comment by Notgnoshi** [comment]
I believe it *does* support the R language. You may have to enable R from the options menu
![Screenshot from 2019-09-20 08-50-40](https://user-images.githubusercontent.com/8878460/65336549-cc855680-db83-11e9-85f5-911c19357812.png)

**Comment by jbhanks** [comment]
Hmmm, I don't have that. In options, all I have are Appearance, Change Password, Protected Session, Note Revisions, Sync, and Advanced.
![image](https://user-images.githubusercontent.com/12942318/65347154-682abd00-dbac-11e9-81df-1aa56ccdfb51.png)

**Comment by Notgnoshi** [comment]
It must have been added in a recent version. I'm using 0.35-beta.

**Comment by jbhanks** [comment]
Oh, wonderful! I guess this can be closed.
