### ISSUE TITLE
SyntaxError: expected expression, got keyword 'import'

### ISSUE THREAD

**Issue by raphwriter** [zadam/trilium#648]
The app (0.35.1) doesn't fully load anymore. This happend to me only so far with Firefox ESR (60.9.0) on Windows 10. All I get is this: 
![grafik](https://user-images.githubusercontent.com/28687075/66029987-ad31e600-e500-11e9-918e-9bfec4732f0e.png)
(The buttons do not work)

It seems to work fine onn Linux and on a newer version of Firefox; also Chrome on Win10 works.

This is the message I get in the JS Console: `SyntaxError: expected expression, got keyword 'import'`

Edit: tested it on Win10 Firefox 69.0.1 (Quantum), works fine as well. So maybe just Firefox ESR is affected.

**Comment by zadam** [comment]
Yes, this is because in 0.35 we started using dynamic form of "import" keyword (to lazy load some components for faster / lighter load) which FF supports IIRC since 67. So old ESR (60) is not working anymore, the new ESR (68) should work fine.

**Comment by raphwriter** [comment]
I see, thanks!
ESR 60 is installed by default at my workplace but no big problem. I can use Chrome or a Portable Firefox version instead. 
Didn't know there is a new ESR Version, I'll talk to our IT department ;)
