### ISSUE TITLE
Hi, is it possible to add auto spell checking functionality to notes? 

### ISSUE THREAD

**Issue by SpunkyMaXimz** [zadam/trilium#652]
For bug reports, please mention **version of the application** and include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
Hello, yes, this is being worked on and should be released in 0.36

**Comment by zadam** [comment]
Spellcheck is provided in 0.36 (beta for now).

**Comment by VainXploits** [comment]
How do I get rid of spell check?

**Comment by zadam** [comment]
![image](https://user-images.githubusercontent.com/617641/149826202-5b8b3e6e-adcb-43e2-a229-0482411a83de.png)

**Comment by VainXploits** [comment]
Got it!
