### ISSUE TITLE
Child-Note Overview Lables Covered Up

### ISSUE THREAD

**Issue by decaby7e** [zadam/trilium#653]
![image](https://user-images.githubusercontent.com/27081624/66287195-c0e3a080-e8a2-11e9-9907-f875a8968810.png)

A picture is worth a thousand words. Is there any way to resolve this?

**Comment by zadam** [comment]
I think it's a problem of large text while the box is fixed size. So this could be tweaked via CSS.

However, this whole children overview has been already removed from master, 0.36 will have a different (hopefully better) solution.
