### ISSUE TITLE
35.2 - right click on tab

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#656]
I am using firefox nightly and when I right click on a tab I get this:

![35 2](https://user-images.githubusercontent.com/1071479/66569970-28784500-eb5c-11e9-949b-e3a9fd9f660d.png)

**Comment by bwat47** [comment]
This also effects the electron app: 
![image](https://user-images.githubusercontent.com/1442520/66581538-3fb03600-eb4e-11e9-86aa-2af0d616b164.png)
