### ISSUE TITLE
Starting on Gitpod stops with an error

### ISSUE THREAD

**Issue by PostPollux** [zadam/trilium#657]
I just tried to start the trilium workspace in gitpod and when it was automatically installing i got the following error and it didn't start up:

![trilium_gitpod_error](https://user-images.githubusercontent.com/9008901/66644831-34c6d580-ec22-11e9-86f3-b2e6f90a7565.png)

Any idea?

**Comment by PostPollux** [comment]
Hm, ok, it's the first time I'm using gitpod. And it seems to not be related to trilium at all. I just tested it with another repository and when I'm running npm install I get the same error.

I'm using Linux Manjaro. Maybe that's the problem. The problem occured both with Firefox and Brave browser.

I'm closing this issue now, as it doesn't seem to be related to trilium.

If you have any tip or idea how to fix the problem I would be happy of course.

**Comment by zadam** [comment]
This looks like missing native dependencies. These are necessary for debian/ubuntu (from [wiki](https://github.com/zadam/trilium/wiki/Manual-server-installation)):

```
sudo apt install libpng16-16 libpng-dev pkg-config autoconf libtool build-essential nasm libx11-dev libxkbfile-dev
```

**Comment by PostPollux** [comment]
Sorry I was in a hurry this morning. Actually it's not true that it also happened on the other project that I tested. I was switching between the various browser tabs and thought "shit it's happening here, too", while I was actually looking at trilium again. I feel a bit dumb right now :)
It works fine on the other app, so I guess it is related to the trilium repository.

Does it work fine on your side? Because I guess my operating system should not change anything at all, as this is all running in the browser in a virtualized environment.

**Comment by zadam** [comment]
As I mentioned above it looks like the gitpod is missing dependencies. I don't really have any experience with gitpod (it came as PR from somebody else) so I can't provide any support for that.

**Comment by PostPollux** [comment]
Hm, ok. I tried to include those dependencies by extending the gitpod docker image.

the .gitpod.yml looked like this:
```
image:
  file: .gitpod.dockerfile

tasks:
    - before: nvm install 10 && nvm use 10
      init: npm install
      command: npm run start

ports:
    - port: 8080
      onOpen: open-preview
```

And this was my .gitpod.dockerfile:
```
FROM gitpod/workspace-full

RUN sudo apt-get install -yq --no-install-recommends \
        libpng16-16 \
        libpng-dev \
        pkg-config \
        autoconf \
        libtool \
        build-essential \
        libx11-dev \
    && sudo rm -rf /var/lib/apt/lists/*
```

I had to remove the "nasm" and the "libxkbfile-dev " dependency, as they couldn't be found and resulted in an error when building the container. (E: Unable to locate package libxkbfile-dev)

So now everything started up fine with the extended container, but the error is still the same like in my first post.

I found the same problem here https://github.com/electron-userland/electron-spellchecker/issues/91

The solution there was to install "libxkbfile-dev".
Do you have any idea why I can't install that package? I'm not very versed with package managing.

Tracking the container image down shows that ubuntu:disco is the base.
MyExtendedGitpodImage <-  gitpod/workspace-full <- buildpack-deps:disco <- ubuntu:disco

But when I'm looking here it looks like this libxkbfile-dev exists for ubuntu:disco:
https://packages.ubuntu.com/disco/libxkbfile-dev

**Comment by PostPollux** [comment]
ok I missed sudo apt-get update.

```
FROM gitpod/workspace-full

RUN sudo apt-get update \
    && sudo apt-get install -yq --no-install-recommends \
        libpng16-16 \
        libpng-dev \
        pkg-config \
        autoconf \
        libtool \
        build-essential \
        nasm \
        libx11-dev \
        libxkbfile-dev \
    && sudo rm -rf /var/lib/apt/lists/*
```
This now builds fine when starting gitpod and the error I mentioned at the beginning is gone! Yeah!

But unfortunately "npm run start" now throws an error!

![trilium_gitpod2](https://user-images.githubusercontent.com/9008901/66689424-0e895000-ec8b-11e9-86b8-d6d4dfc18f46.jpg)

**Comment by PostPollux** [comment]
Ok, I finally got it working! The trick was to use "npm run start-server".
I guess the readme should be updated to reflect that, too. Because at the very bottom of the readme it says:

npm install
npm run start
