### ISSUE TITLE
"If there's only one tab, then..." option cannot be changed

### ISSUE THREAD

**Issue by sruebner** [zadam/trilium#660]
When I try to change the option "If there's only one tab, then..." from "show the tab bar" to "hide the tab bar", the change does not show any difference in tab behaviour. When I re-open the option screen, the dropdown shows the old value of "show the tab bar", so apparently, the option is not saved.

I'm using the desktop version 0.35.2 on macOS Catalina (10.15).

Here is my log file:
[trilium-2019-10-18.log](https://github.com/zadam/trilium/files/3743380/trilium-2019-10-18.log)

**Comment by zadam** [comment]
Thanks for reporting the bug. From the log I can see that the DB record for the option does not exist in the document. I will look into this.

**Comment by sruebner** [comment]
Also quickly tested this with a new database by deleting the folders "Trilium Notes" and "trilium-data" folders in my Application Support folder. Seems to happen even with a freshly created DB.
