### ISSUE TITLE
Where's the Recycle Bin?

### ISSUE THREAD

**Issue by NoobAndProud-01** [zadam/trilium#662]
If I accidentally delete an important note, where do I recover It?

**Comment by zadam** [comment]
Hello, notes are soft-deleted and hard deleted only after a day. However there is no UI to recover the soft-deleted notes and you would need to issue some SQL query(ies) to get your notes back.

However I agree this would be a useful features so I'll put this to backlog.

There's another way - Trilium automatically backs up the whole document once a day so the note could be recovered there ...

**Comment by zadam** [comment]
ability to undelete notes is available since 0.40. Some documentation is here: https://github.com/zadam/trilium/wiki/Note#deleting--undeleting-notes
