### ISSUE TITLE
Feature Request: Note-hoisting over api

### ISSUE THREAD

**Issue by crimsonland** [zadam/trilium#663]
It would be great if i can hoist note over api.

1)Now i can acivate button over frontend api
https://github.com/zadam/trilium/wiki/Scripts
https://zadam.github.io/trilium/frontend_api/FrontendScriptApi.html

```
api.addButtonToToolbar({
    title: 'inbox jump',
    icon: 'check',
    shortcut: 'alt+1',
    action: async () => {
        const taskNoteId = await api.runOnServer(async () => {
            const inboxRootNote = await api.getNoteWithLabel('inboxLabel');
            return inboxRootNote.noteId;
        });
        await api.activateNote(taskNoteId);
    }
});

```

2)Do you have any plans on adding Note-hoisting over api?
https://github.com/zadam/trilium/wiki/Note-hoisting

**Comment by zadam** [comment]
Could you explain point 1 in more detail? I'm not sure what you want to achieve.

Note hoisting can be exposed in the API - I'll take a look at this.

**Comment by zadam** [comment]
Hi, this has been implemented in master, see https://zadam.github.io/trilium/frontend_api/FrontendScriptApi.html#setHoistedNoteId

This will be in 0.36
