### ISSUE TITLE
Authentication for the trilium server?

### ISSUE THREAD

**Issue by mkg20001** [zadam/trilium#664]
Does the trilium server have any means of authentication? Or can anybody simply sync with it?

What would be cool would be to have a simple group system that would allow notes to be made accessible by the operator

**Comment by zadam** [comment]
Hi, just to add some info - yes, access to sync is authenticated, but no, [it should not be used to setup multi-user system](https://github.com/zadam/trilium/wiki/FAQ#multi-user-support).

**Comment by mkg20001** [comment]
Hrm. Multi-user XSS wouldn't be that much of a problem, if we 1) properly isolate the backend API 2) restrict code-execution to the user's own code or approved scripts 3) restrict authentication so the operator can prevent users from registering
