### ISSUE TITLE
36.1 beta - insert in text above image if first element

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#668]
If I have an image as the first thing in a note I can't put text before the image.  This applies to an image being the first thing in a note after creation or if an image is pasted before the first text element.

**Comment by zadam** [comment]
Yeah, I noticed it's a bit awkward, but what works for me is when the image is focused I can press enter and it will put the cursor before the image ...

**Comment by pcause** [comment]
tried this and it didn't work.  selected image hit enter and typed abc and the letters appeared after the image as opposed to before.

**Comment by Sytten** [comment]
With the latest version text goes before, but now we have the opposite problem of not being able to add text after if the image is at the end of the text.

**Comment by zadam** [comment]
It can happen to both before and after image actually.

Relevant CKEditor issue is this one: https://github.com/ckeditor/ckeditor5/issues/407

**Comment by MetroWind** [comment]
Looks like the upstream is fixed. Is Trilium using the fixed version?

**Comment by zadam** [comment]
Generally Trilium is using latest stable CKEditor version.

Can you point to where this is fixed in the upstream? Linked issue is still open.

It is not possible to edit the note's HTML source because then CKEditor may break on the custom HTML. See good explanation [here](https://github.com/ckeditor/ckeditor5/issues/592#issuecomment-335108129).

**Comment by MetroWind** [comment]
Oops, sorry I miss-read. Upstream's not fixed.

**Comment by zadam** [comment]
CKEditor has provided UI controls to insert before/after block elements for a while, closing.
