### ISSUE TITLE
Automatically build Linux server tar.xz for Raspberry Pi

### ISSUE THREAD

**Issue by discernment** [zadam/trilium#674]
Consider supporting ARMv7 processors in the released set of server tar.xz files so Raspbery Pi users can have a smooth experience.  There are some instructions on how to build your own [here](https://hakanu.net/python/2019/06/22/trilium-notes-on-raspberry-pi/).  But it is very slow and involved.

**Comment by zadam** [comment]
The problem is that I don't do any testing on ARM CPUs (partly since I don't have any) and releasing builds for platform I don't test would not do any good (I already have similar issue with Mac build).

**Comment by Howard3** [comment]
Hello, I've started a daily build against ODroid XU4 on ARMv7. This should not have any difficulties running on Raspberry Pi. Please check here: https://hub.docker.com/repository/docker/hlince/trilium

**Comment by jhc86** [comment]
I'm interested in something maybe related- running a Trilium server on android. This way I could sync the data locally to a mobile phone and it would be much more responsive to work off local data on Android.
I tried with Termux a number of months ago but electron seems to require dependencies that are not available for Arm right now.
I wonder if it's possible to (somewhat easily) build and run the server without Electron, but I'm not familiar enough with node or electron enough to figure it out myself yet.

**Comment by zadam** [comment]
Server version does not need electron.

There are actually (unofficial) builds for ARM: https://hub.docker.com/r/hlince/trilium
