### ISSUE TITLE
Unable to log into Server Installation

### ISSUE THREAD

**Issue by fictionalname** [zadam/trilium#677]
Hello,

I have just completed the Docker Installation of the server edition as per the instructions and the log file says:
Generated session secret
Generated sourceId=6tBBaJKDbmlT
App HTTP server starting up at port 8080
{
  "appVersion": "0.35.1",
  "dbVersion": 145,
  "syncVersion": 10,
  "buildDate": "2019-09-30T22:18:23+02:00",
  "buildRevision": "f6fc24d11d9c9a15086c0726dde30f6c382c578f",
  "dataDirectory": "/root/trilium-data",
  "clipperProtocolVersion": "1.0"
}
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.

I can't find any instructions for initialize Trilium.

When I connect to the server with port 8080 it gives me the Trilium Notes Setup page.  I am wanting to use it purely as a server based app, so I don't have a client side database with which to Sync.  Whenever I say I'm a new user and enter a username and password, it just goes back to the first page asking if I'm a new user.

Can you please tell me how to initialize Trilium so I can log into the application through the web interface and add my content.

Thanks.

**Comment by zadam** [comment]
Hi, you seem to be doing all the right steps. Could you show post what happens in the log file after you click through the setup wizard. Or is that all there is?

In that case I wonder if it might be a browser issue - what are you using? Any errors in the browser console?

**Comment by fictionalname** [comment]
Hi,

I'm totally new to Docker, so I'm not sure what other logs I can view.  That's what is coming up in the logs that Portainer shows.  

I'm now getting this:

Error: Router not found for request /users?page=&size=5

    at /usr/src/app/src/app.js:84:17

    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)

    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)

    at /usr/src/app/node_modules/express/lib/router/index.js:284:7

    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)

    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)

    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:91:12)

    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)

    at /usr/src/app/node_modules/express/lib/router/index.js:284:7

    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12) {

  status: 404

}

[session-file-store] Deleting expired sessions

[session-file-store] Deleting expired sessions

[session-file-store] Deleting expired sessions


I am also using the newest version of Chrome to connect (Version 78.0.3904.87 (Official Build) (64-bit)).

Am I right in thinking that I can just run this docker container on it's own, log in and start using Trilium without having to set up any client side installation or back end?

Hope this helps!

**Comment by zadam** [comment]
Yes, you can just run docker container without any client side installation.

Chrome 78 should be fine.

```
Error: Router not found for request /users?page=&size=5
```
This looks like some kind of interference from some other application or something since Trilium does not trigger any such calls. But this should be harmless ...

When you finish the setup wizard (after filling in the username/pass)  and it just redirects back to the setup page, do you see any errors in the browser console? (can be opened by CTRL-SHIFT-I)

**Comment by fictionalname** [comment]
Hi, 

I've launched the browser console and it is not reporting any errors which I can see when going through the wizard.  

Is it worth just deleting the container and trying again if this is not expected?

**Comment by teotwaki** [comment]
@fictionalname Is this still relevant?

**Comment by popey456963** [comment]
Closed due to lack of response.
