### ISSUE TITLE
Disable link map animation

### ISSUE THREAD

**Issue by bkidwell** [zadam/trilium#684]
I am using Trilium 0.35.1 build for Windows desktop mode.

The data in the Link Map widget in the Sidebar is useful, but the **animation is distracting**. Can the animation be disabled? If there is a toggle switch already can this be exposed easily in the Options screen?

**Comment by zadam** [comment]
Hello, I understand the concern and I would also prefer the animation to be disabled. However, this animation isn't just extra fancy feature, but it's rather necessary part of the algorithm which works in this way - it first places elements randomly on the screen and then iterates while respecting some force-directed constraints until it settles into equilibrium. Actually a nice visual positioning of graph elements is not an easy task and this force-directed algorithm usually produces nicest looking results, but has this annoying property that it takes some time.

What could be done is to have the graph show up only once it settles, but that could take few seconds. But I will also take a look if it's not possible to speed it up a bit more ...

**Comment by zadam** [comment]
I gave this a second look and managed to essentially disable the animation - if I don't render the progress, then "settling" is much faster and is done in almost all cases in under half a second. It still a bit flickers because of this lag but I think it's less distracting that the movement.
