### ISSUE TITLE
Easier way to move/link notes to other tree locations

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#687]
I have a lot of notes and when I want to move one or place the note in multiple locations in the tree it is very awkward.  I have to copy and then scroll and paste, then scroll back up, and repeat.  I have a saved search so I can see all my clipped notes but refiling is tedious.  How about a move/link item that pops up the tree and allows select or multi-select for move or link.  You already have the code to build the tree.  Alternative is to show a box with the base note name like in edit branch prefix and allow typing where you autocomplete from other notes names (you have code for this for search)

**Comment by zadam** [comment]
First a work around - my workflow for such operations is to:

 * copy / cut the note into clipboard
 * open new tab and find the target note with Jump-to dialog
 * paste the note(s) from clipboard to the target
 * optionally close the tab 

That's a bit less painful, at least your original position in the tree is preserved in the first tab.

However, just yesterday I committed new dialog called "Clone to..." which will contains a autocomplete where you select the note to which you want to clone the current note. I guess it makes sense to also include a move option as well.

**Comment by pcause** [comment]
Thanks

**Comment by zadam** [comment]
"Move to" dialog has been added as mentioned above so closing ...
