### ISSUE TITLE
Debugging script notes

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#688]
Hi !
I am trying to make some script note in trilium, an i would like to be able do *debug* displaying some variables during execution, but i could not achieve this.

This is a simple case:

I have a note `mytest` with a `mytag` promoted attribute, and `runOnAttributechange=myscript.js`
The note `myscript.js` is a javascript note containing only the following line:
```js
api.showMessage("foo");
```

If i run the script from **Execute** button (Ctrl+Enter), my message is correctly displayed.
Therefore, when it is triggered by changing the `mytag` promoted attribute from `mytest` note, no message is displayed, and instead i get this error from the logfile:
```
17:53:53.841 INFO  ERROR: Execution of script "attribute changed" (HiNIGboiHpNo) failed with error: Load of script note "attribute changed" (HiNIGboiHpNo) failed with: api.showError is not a function
```

**Comment by zadam** [comment]
This is because .showMessage() is a "frontend" API (runs in the chrome/browser process), but runOnAttributechange is a backend (node.js process) event (and backend API has no .showMessage()). This distinction between frontend and backend APIs and scripts is annoying, but there's no way around it.

**Comment by nil0x42** [comment]
Okay, but is there any way to display messages, be it in a log file or anywhere, in order to debug my backend scripts ?

**Comment by zadam** [comment]
Yes: https://zadam.github.io/trilium/backend_api/BackendScriptApi.html#log

**Comment by nil0x42** [comment]
Thank you !
