### ISSUE TITLE
Can't delete in mobile app

### ISSUE THREAD

**Issue by kalafut** [zadam/trilium#689]
Hi. Thanks for an awesome app!

One thing I've not been able to do in the mobile app is delete notes. This option is there, but it seems to do nothing. I ended up tracing it as far as this confirmation box that is called, though it never appears in mobile and no breakpoints past the `await` are hit: 
 https://github.com/zadam/trilium/blob/d3c957768f731b267bed33087c81e240fde47eb3/src/public/javascripts/services/branches.js#L103

I might poke around a bit more, but perhaps it's something simple that you'd catch right away.

Thanks.

**Comment by zadam** [comment]
Hello, thanks for reporting this bug, it has been fixed and will be released in the next patch version.
