### ISSUE TITLE
[BUG] Cannot remove note from path through API (Cannot read property 'increaseProgressCount' of undefined)

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#691]
version: v0.36.3

Error:
```js
Execution of script "attribute changed" (HiNIGboiHpNo) failed with error: Load of script note "attribute changed" (HiNIGboiHpNo) failed with: Cannot read property 'increaseProgressCount' of undefined
```

Hi ! since i downloaded trilium, in version v0.36.2 (and now still in version v0.36.3). the "Task Manager" did not work properly.
When i set the "doneDate", the note is properly cloned to `doneRootNote`, but not removed from `todoRootNote`. Also, the color remains red anyway, so the line:
```js
await note.toggleLabel(isTaskDone, "cssClass", "done");
```
seem to also fail.

Anyway, i did not want to post an issue for it at the first time, as i know the Task Manager is not really part of trilium, i supposed the original script "attribute changed" was just outdated, and i started to debug it.

After debugging i found something that seems to be clearly a bug in trilium. Indeed, on the execution of:
```
await api.ensureNoteIsAbsentFromParent(note.noteId, doneRootNote.noteId)
// OR:
await api.toggleNoteInParent(false, note.noteId, doneRootNote.noteId);
```
(in a context where doneDate is undefined),
i get the following error in logs:
```
Execution of script "attribute changed" (HiNIGboiHpNo) failed with error: Load of script note "attribute changed" (HiNIGboiHpNo) failed with: Cannot read property 'increaseProgressCount' of undefined
```

I ensured that my note was present in at least 2 paths to ensure it's not an "orphan note" issue, and the error remains.

That's why since the beginning the **Task Manager** didn't work properly on my machine. removing a note clone from path simply doesn't work.

**Comment by nil0x42** [comment]
I just found where the bug is:
https://github.com/zadam/trilium/blob/f82e99b5eddfcab3d96c9d6df7a450e4a69993e5/src/services/cloning.js#L60-L65
https://github.com/zadam/trilium/blob/f82e99b5eddfcab3d96c9d6df7a450e4a69993e5/src/services/cloning.js#L52-L56
*deleteBranch is called without **taskContext** argument*
*but it's still expected :*
https://github.com/zadam/trilium/blob/f82e99b5eddfcab3d96c9d6df7a450e4a69993e5/src/services/notes.js#L395-L396

**Comment by zadam** [comment]
Hi, thanks for reporting this issue - it has been fixed and will be released in the next patch version.
