### ISSUE TITLE
[UX Issue] Display branch prefix of book child notes

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#695]
Hi !
I have the following structure:
```
OS
    Linux
        TIPS

Tools
    Terminal
        Gnome Terminal
            TIPS

Ubuntu
    TIPS
        Desktop
        Linux - TIPS
        Gnome Terminal - TIPS
```
* `Linux - TIPS` is a clone of `OS / Linux / TIPS` (so, prefixed with 'Linux' in this branch)
* `Gnome Terminal - TIPS` is a clone of `Tools / Terminal / Gnome Terminal / TIPS` (so, prefixed with 'Gnome Terminal' in this branch)
* `Ubuntu / TIPS` is a book note

Now, when i visualize `Cheat Sheet` book, it would make sense to view note's tittles with their branch prefix. Otherwise i see many `TIPS` childs and it's really confusing.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. Yes, it makes sense to show them including their prefix. Fixed in stable branch.
