### ISSUE TITLE
Long Line Separator

### ISSUE THREAD

**Issue by graphixillusion** [zadam/trilium#697]
Hi there. I'm so sorry for the dumb question but i searched a lot but still can't find an answer. Usually in markdown, if you type --- the result will be a long line separator (similar to the `<hr>` tag) while in here the result is a very short line. The question is: how to make a long line separator? Thank you in advance...

**Comment by zadam** [comment]
Hello, unfortunately line separator is currently not supported in the trilium. While there is [such a feature in CKEditor](https://ckeditor.com/docs/ckeditor5/latest/features/horizontal-line.html) there isn't "autoformat" from `---`. I created an issue for that https://github.com/ckeditor/ckeditor5/issues/5720.

I will add the line separator to next release anyway ...
