### ISSUE TITLE
[bug]Cannot create relation ship in "Relation Map" notes

### ISSUE THREAD

**Issue by johnnli** [zadam/trilium#698]
The app version is：0.36.3

Encountering issue after drag one node to another to create relationship.

![image](https://user-images.githubusercontent.com/22266414/68538053-40d0bf00-03a9-11ea-8e46-e805448be7c0.png)

Accroding to the WIKI, there should be a prompt window while creating relationships.

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, it has been fixed and will be in the next patch release.
