### ISSUE TITLE
[BUG]: adding promoted attribute from autocompletion doesn't trigger 'runOnAttributeChange'

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#699]
version:  v0.36.4

I tested through the "Task Manager".
If i add a new location. not previously used, typing it and press enter, then 'runOnAttributeChange' is correctly triggered.
Therefore, if i select a location from the autocompletion list (so if i add a location that's already been used previously), then 'onAttributeChange' is not triggered.
Also, the added location value is not saved in note, so if i leave and re open the note, the location field is empty.

**Comment by nil0x42** [comment]
Upgrade:
i restart trilium and i am not having this issue anymore, maybe some frontend issue of electron that happened randomly...
now it weems to be working

**Comment by nil0x42** [comment]
re-upgrade:
the issue remains, sometimes it works fine, and sometimes not...

**Comment by piccobit** [comment]
I experience the same, very annoying, issue.

How can we help to get that fixed?

**Comment by nil0x42** [comment]
from now, i accepted that i need to re-type the full string each time and ignore completion. Therefore it would be really time saving to have that fixed

**Comment by zadam** [comment]
Hi, sorry for missing the bug report before, I was now able to reproduce it and fix it.
