### ISSUE TITLE
[UX] api.refreshTree() should also refresh current note "paths" list

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#700]
version: v0.36.4

There should be a way to refresh currently open note's path list.
As i am debugging the task manager, each time i add a promoted attribute, which then may clone current note into alternative paths, it's annoying to have to quit the note and re-open it each time to be able to see how many paths it has on the `path list` button.

So this button should be or auto-refreshed, or at least an api function should make allow refreshing it, without having to manually leave and re-open the note.

**Comment by zadam** [comment]
Hi, I just added refreshActiveTab() and refreshAllTabs() API methods which should solve your problem.

**Comment by nil0x42** [comment]
> Hi, I just added refreshActiveTab() and refreshAllTabs() API methods which should solve your problem.

Hi, the `refreshActiveTab()` method seems to be gone since recent versions of trilium, so is there a way to do that with new API methods ?

**Comment by zadam** [comment]
Yes, the approach changed and these heavyweight programmatic APIs disappeared.

Generally all UI components should now watch data changes and update themselves automatically. Do you have a scenario where a UI element is outdated? These would be considered a bug ...

**Comment by nil0x42** [comment]
Yes, i created an extension/shortcut which automatically promotes (or unpromotes) a personal list of attributes.

Whem i press Alt+P, my wanted attributes are promoted or unpromoted (switch).
In the past, i used refreshactivetab so my promotion became immediately visible without pressing Ctrl+R.

So, attributes promotion are not reflected in the UI, so yes it might be a bug
