### ISSUE TITLE
CKEDITOR.instances not available

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#701]
Hi ! I know you plan to add shortcuts in the future, and add some awesome features to current integration of creditor5.
Therefore, it would be very great if you provide a reference to ckeditor instance, available from script notes.
I saw that version 5 of ckeditor does not provide a globale like for ckeditor4: https://stackoverflow.com/questions/50911373/how-to-get-text-from-ckeditor-5-using-js-or-jquery
But still i would like very much to be able to interact with it from scripts, to add my own keybindings & behavior to common actions i perform with editor.

**Comment by zadam** [comment]
The problem with this approach is that there's multiple CKEditor instances (up to 1 per tab) and they change as you close and open tabs.

So the solution is probably to somehow expose the tab lifecycle events - e.g. note would have `@run=tabCreated` (there are similar events like `@run=frontendStartup`).

**Comment by nil0x42** [comment]
yes. it would make possible adding our own customisations to ckeditor.
so the ckeditor instance should be available as a property of `NoteFull` (and be null if note is a non-ckeditor type)
