### ISSUE TITLE
large HTML code note freeze

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#702]
Hi,
i have several (very) large html code notes, which i use to render html files imported from singlefile browser addon on an iframe with another render note.

Therefore, each time i accidentally click on my `content` note, the whole UI freezes several seconds because of the time needed to render a 1MB html iframe line.

To avoid this, i would like to be able to render an HTML attachment instead of HTML note, or have a confirmation before displaying large contents.

The perfect for me would be to be able to add a label to display my note in a less CPU consumming way (the very least just to be able to copy to clipboard actually)
something like @loosyDisplay

**Comment by zadam** [comment]
Relation `renderNote` does not have to point to a code note, file note works as well so you can just import your big code notes as files (as long as you don't need to edit them).

**Comment by nil0x42** [comment]
perfect!
