### ISSUE TITLE
Note.setAttribute(*) seems to break when attribute with identical value is already attached to note

### ISSUE THREAD

**Issue by jhc86** [zadam/trilium#703]
Thank you for this amazing program!!! I've dreamed of something like this for years but couldn't figure out how to make it myself. 

Note.setAttribute seems to not create an attribute and returns nothing when an attribute with identical value is already attached to note

Here is a test that should demonstrate this in 0.35.6 when run on linux via npm start-server

This is meant to be a backend JS note
[test4.zip](https://github.com/zadam/trilium/files/3829185/test4.zip)

- test4 is successful and returns an attribute
- test4b fails for me
- test4c result is identical to test4b and is redundant

I'm also attaching my workaround for this, I use setLabel(uuid, uuid) with unique uuid values for both name and value, then I use getLabel(uuid) to return an attribute object variable for that attribute, then I use the attribute object variable returned to update attribute.name and attribute.value and then call attribute.save(). 

This is meant to be a backend JS note
[test6.zip](https://github.com/zadam/trilium/files/3829233/test6.zip)

**Comment by zadam** [comment]
Hello, thank you for reporting this issue. 

Coincidentally I found and fixed the bug (in 712f67e9833c115e9119578429d53fdd5cfe86ac) on Friday, but forgot to backport to stable branch (which I now did).
