### ISSUE TITLE
[API] ability to get note paths

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#708]
Hi ! I am trying to make a search script to search some some script, but only in a specific path (because i have the same need as specified in issue https://github.com/zadam/trilium/issues/534)

A way to do it i thought about was to hoist from the API, then search and immediately unhoist. But `setHoistedNoteId()` is only available from the frontend.

Anyway, i chose to get array of matching notes with `searchForNotes()`, then check for each note is it has a path starting with my *path prefix*, and remove it from array otherwise.
Therefore, i found no easy way to get the paths for a note. Indeed, they only way i found is to build a recursive function using `getParentNotes()` to see if any of them until root have the *noteId* of my prefix path's last note element.

It looks a bit heavy so i would like to know if there is a better way to achieve this

**Comment by zadam** [comment]
I added getAllNotePaths() to note entity which will return all note paths (in the form of noteId array) for the note.

**Comment by nil0x42** [comment]
Thanks !
