### ISSUE TITLE
Dark / Night Mode?

### ISSUE THREAD

**Issue by washere** [zadam/trilium#71]
Can we have an option in settings (or in config-sample.ini) to enable a night mode please?

Such as grey font on black background?

White is like looking at a big filming light for hours, it is basically a killer on the eyes.

Thanks for the great work.

**Comment by washere** [comment]
Looks great. Is it going to be in the next release?

**Comment by zadam** [comment]
I kind of don't want to provide official "themes" at this point (even though it is planned eventually).

Instead I'll add a way for the user to define custom CSS in a note tagged with special attribute, CSS is then appended to the standard Trilium one. In GitHub documentation I'll then specify the dark mode as an example (it's like 5 lines of CSS).

**Comment by washere** [comment]
Thanks zadam. CSS .ini or whatever you finally decide would be great. Please let us know in this thread how to do it when you release it. Thanks again.

**Comment by zadam** [comment]
This was released in 0.9.0-beta. See https://github.com/zadam/trilium/wiki/Theming for details.
