### ISSUE TITLE
[BUG][Search]: '@customRequestHandler' returns nothing

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#710]
Hi !
I have somes notes with the '@customRequestHandler' set.
Today i tried to search all notes with this attribute, and the search engine returned nothing.

I also tried `@customRequestHandler=*`, and still nothing.

Therefore, the doc says:
>  @abc - returns notes with label abc
(https://github.com/zadam/trilium/wiki/Search)

**Comment by zadam** [comment]
Hmm, searching with `@customRequestHandler` should work (and works for me locally). 

`@customRequestHandler=*` is not expected to work ...

**Comment by nil0x42** [comment]
sorry, i typed @customRequestHandler, while the notes i knew i had were in reality tagged with @customResourceProvider.

My bad :(
