### ISSUE TITLE
Delete confirmation for notes linked by other notes

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#714]
When deleting a note, it would be VERY interesting to show a confirmation when the note is about to be deleted with clones (or when the note has no clones).
Such confirmation will alert user which other notes link to this note, and will them have orphaned links into their contents.

When i delete a note, it's because i think it became useless, therefore other notes linking to it may remember me that it's actually relevant to keep it, or to upgrade my related notes.

**Comment by zadam** [comment]
Just to be clear - deleting a note will by default delete only its one "clone" and only delete the note itself if it is the last existing clone. There's a checkbox in the delete confirmation dialog to also force deleting all clones ...

But I get your point and it is something I have been thinking about - we have all the necessary data for this - we now which notes link this note, but it has not been yet used for warning / extra confirmation. One thing to figure out is the UI/UX, especially concerning the deletion of multiple selected notes ...
