### ISSUE TITLE
[BUG] Search: `@in=noteId1 @in!=noteId2` second filter is ignored

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#716]
Hi !
I just ran a search to look to all notes that have `noteId1` as parent, while NOT having `noteId2` as parent.
Therefore, the second filter (`@in!=noteId2`) is ignored.

If i invert the `@in` filters, it's always the second one that's ignored.

**Comment by zadam** [comment]
Yes, you're right, there was an assumption there's only one occurrence of the @in filter. I did not really think about the possibility of having more of them but your example makes sense (and there are more sensible variants as well)
