### ISSUE TITLE
[BUG] Cut/Paste Note on tree not working

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#720]
If i select a note on the tree, and copy/paste to another location with `Ctrl+C / Ctrl+V`, everything works fine.

But when i try to to the same cutting, with `Ctrl+X / Ctrl+V`, nothing happens when i paste, like if no note was in the clipboard.
That's strange, as when pressing `Ctrl+X`, i get the expected message saying `Note(s) have been cut into clipboard`

**Comment by zadam** [comment]
Are you running on the latest version? There has been some clipboard fixes in 0.37.4.

**Comment by nil0x42** [comment]
ah ok i'll try, i'm still using 0.37.3

**Comment by nil0x42** [comment]
Indeed, it's resolved as of 0.37.4 !
