### ISSUE TITLE
Show search results in notes area

### ISSUE THREAD

**Issue by jaroet** [zadam/trilium#722]
I am using the latest version and I would like to see the search result in the place where normally the note content is shown. There is much more screen estate available (specially with closed sidebar) and the presentation of the search results will be much more clearer. Specially with a deeper tree.

It is now limited to the size of the Tree and scanning a medium to long list of notes is not easy. 

Alternatively a popup windows (like the options) might be an option. 

In both cases a click on a search result might open the note to preview with ESC returning to the search result (cached). Or something like that. 

I found this ticket https://github.com/zadam/trilium/issues/108 but the status of that ticket is unclear to me. Let me know if this is something that might you might consider. 

Regards,
JeRoen

**Comment by nil0x42** [comment]
Do you suggest a display similar to the `Book note` type for `Seaved Search` notes ?
If yes it would be indeed a nice UX improvement !

**Comment by zadam** [comment]
Yeah, I have been thinking about book-like preview of saved search ...

**Comment by jaroet** [comment]
No, that is not what I suggested.

Most of the time I would like to see the same search result as currently is
shown (path and name only) ,but not in the tree-area (very small) but in
the notes area with is rather large (on desktop at least). Currently
sometimes a search result is presented over 3 rows.

Besides that, personally I do not like the card representation of empty
notes. I would prefer a simple Titles only listing with indentation for
deeper tree hierarchies. But that is just me ... :-)

Op do 28 nov. 2019 om 16:59 schreef nil0x42 <notifications@github.com>:

**Comment by nil0x42** [comment]
> Besides that, personally I do not like the card representation of empty
> notes. I would prefer a simple Titles only listing with indentation for
> deeper tree hierarchies. But that is just me ... :-)

Actually i never thought about it, but on some of my notes it would be relevant to have such display. Maybe in the future we might have different display types for empty notes, and be able to configure which one we prefer from the config, or from labels.

Anyway, trilium will soon rule the world of note-taking software, and contributors will pop to help @zadam on development

**Comment by jaroet** [comment]
My initial use case with this issue was to be able to have a better way of viewing the found notes with my search command. I was custom to use the command-S which crampes it up in the width of the tree which is difficult to read. 

I re-read "Patterns-of-personal-knowledge-base" and I can offcourse use the command-J hotkey to search for notes. Those search results are presented in a much better way. 

So my initial issue is solved. This would mean closing this issue but there is one more related issue. 

The 'advanced' search is not working in case you want search a label. For instance @year=2019 results in 0 hits in the "Jump to Note" dialog while it does give results when using the normal search window. In both cases it results in a list of notes. Would be nice to have that also working in the command-J hotkey window. 

I understand the command-J option is there to only jump to a certain note but in my point of view it has an awful lot in common with the normal search option, it only has a better way to view the results IMHO. 

Should I close this one and open another issue for adding label-search to the Jump-to-note window?

Regards,
JeRoen

**Comment by zadam** [comment]
> Should I close this one and open another issue for adding label-search to the Jump-to-note window?

No, at this point I do not plan to give this functionality to "Jump to" dialog since it has a different focus - speed - it's really about typing the name of the note you search for, the results must show up immediately, you hit enter and that's it. This requirement of instant feedback is why it does not support more advanced searching like attributes and full text which would inevitably bring slower speed.

But I have been thinking about different presentation modes of notes and one of them is "list style" or potentially "table of contents" style which would allow you to open the search results in a tab as a list.

**Comment by zadam** [comment]
"full search" now renders results in the center pane.
