### ISSUE TITLE
Bug: Right click contextual menu is cropped and not scrollable

### ISSUE THREAD

**Issue by MrEliptik** [zadam/trilium#723]
When right clicking on a note in the tree, the contextual menu is cropped and not scrollable on small screens (see attached image). For example, it's cropped on my 1080p 13" laptop but fine on my 1440p 27" screen. 

![fRAVGvb9ET](https://user-images.githubusercontent.com/24484962/69635375-87364700-1054-11ea-969f-1918bda99332.png)

Noticed that with v0.37.4.

**Comment by zadam** [comment]
Hello, thanks for reporting this issue, I fixed it by making the context menu scrollable if it exceeds the total height of the window.

Another way to mitigate this issue is to play with the theme, since the menu in the screenshots looks pretty spacious with large font/padding.
