### ISSUE TITLE
[BUG] Protected pages appear as [object Object] in the sidebar

### ISSUE THREAD

**Issue by FelixII** [zadam/trilium#724]
Hi,

I've noticed a bug with protected pages in the last few updates.

Thanks for taking a look at this issue and your great app!

Cheers,

Felix

---

**Environment**

Trilium version 0.37.5 in Docker on Ubuntu 18.04

**Steps to Reproduce**

1. Create a new page
2. Enable protection for the new page. Enter your password if requested
3. Leave the protected session
4. Enter your password to start a new protected session

**Expected Result**

The page title appears in the sidebar.

**Actual Result**

All protected notes appear as [object Object] in the sidebar.
![Screenshot 2019-11-26 at 17 14 06](https://user-images.githubusercontent.com/5102728/69651335-36344c00-1070-11ea-8b93-7849f39a4804.jpg)

**Comment by zadam** [comment]
Hello, thank you for reporting this bug, it has been fixed.

Interestingly this bug occurs only in the server/web installation which is the reason why I didn't notice for a while.
