### ISSUE TITLE
Evernote Import Loses Original DateCreated and DateModified Values

### ISSUE THREAD

**Issue by MYX-GitHub** [zadam/trilium#725]
**version of the application** appVersion": "0.37.5"

Importing an enex file from Evernote v6.13.14.7474 results in all imported notes having their dateCreated and dateModified values set to the time of import into Trilium.

The enex file, however, contains "created" and "updated" tags with valid timestamps for when the notes were created and modified in Evernote.

I would LOVE to abandon Evernote in favor of Trilium, however, losing the original timestamp values on all my notes is a critical omission that makes Trilium a non-starter.

Please advise.

Mike

**Comment by zadam** [comment]
Fixed in 0.37.6

**Comment by MYX-GitHub** [comment]
Phenomenal work, zadam, thank you!
