### ISSUE TITLE
Deleting  a note enables sidebar

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#727]
Hi

I do not know what the logic behind this but anytime I delete a note the shidebar shows back even if I hide it. Is it possible to make this optional?

I am using the latest version on Debian X64, .deb version

thanks

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. The problem was that after deleting the note we removed all tabs of deleted notes, including the active one, but by doing that we resetted the active tab state (closed sidebar). This is now fixed.

**Comment by gerroon** [comment]
Hi,

The sidebar shows up after opening a captured  (via the web clipper ) page. Not sure if this is a separate issue.

thanks

**Comment by zadam** [comment]
new tabs are controlled by the "Show sidebar in new tab" in the Options
