### ISSUE TITLE
[Feature Request] Attribute to hide note from sidebar

### ISSUE THREAD

**Issue by decaby7e** [zadam/trilium#729]
Just throwing this out there so it is on the record:

It would be nice to hide certain notes from view like those associated with themes and self-made plugins. Perhaps an attribute could accomplish this? If this is already possible I'm open to suggestions on how to go about this!

Thanks!

\- decaby7e

**Comment by zadam** [comment]
This sometimes comes up, but how would you then find the plugins/themes again to modify them?

Instead I recommend creating a top level note, something like "system stuff" and you can move all such notes there so they don't take too much space ...

**Comment by decaby7e** [comment]
They could be only accessible through the search interface, linking, etc. but only hidden from the sidebar. I've already done as you recommended and made a top level note called 'Trilium Files' but this idea was a step on top of that.

**Comment by jaroet** [comment]
And I have even a software note on the top level and within it is Trilium
Notes and beneath that note are all my system stuff. So I almost never even
see it unless I specifically have to use it.

Op vr 29 nov. 2019 om 00:42 schreef decaby7e <notifications@github.com>:

**Comment by generic-user** [comment]
Can't u just add the label `#archived `, and make use of the hide archived notes option in the sidebar settings?
![image](https://user-images.githubusercontent.com/1516035/95178164-60da4f80-07bf-11eb-9723-08246e2dd103.png)

**Comment by decaby7e** [comment]
This feature didn't exist when the issue was opened, but I believe it addresses the problem well!
