### ISSUE TITLE
Export HTML is stuck for large roots

### ISSUE THREAD

**Issue by hakanu** [zadam/trilium#731]
For bug reports, please mention **version of the application** and include **log files** from following location:

Version: 0.37.6

While exporting the root or even one of the large notes, app becomes frozen, counter doesn't go forward and log doesn't have anything. Is there a limit? It's always stuck at the same number for a node. sometimes 1500+, sometimes 900+

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

22:09:49.019 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"","taskType":"export","progressCount":752} 
22:09:49.318 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"","taskType":"export","progressCount":841} 
22:09:51.416 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"","taskType":"export","progressCount":885} 
22:09:51.828 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"","taskType":"export","progressCount":894} 
22:10:02.590 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"","taskType":"export","progressCount":913}

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. I just tried this and for me the export slows down to a crawl around 1000th note. Might be the same issue as what you describe. I will investigate further ...

**Comment by zadam** [comment]
Actually now I'm on 10 000 mark and export runs on a relatively steady pace so I'm thinking it might have been caused by larger notes.

Do you have some largish notes (e.g. attachments of 1 MB or larger) in the exported subtree?

**Comment by zadam** [comment]
I did some optimizations and I see roughly 10 times speed up and no stalling. This is in master branch, so future 0.38

**Comment by hakanu** [comment]
Thanks. Looking forward to that version!

**Comment by hakanu** [comment]
Sadly this is happening in 0.38-beta.
I left the PC open in the morning. It turned out to be not responding in the export folder selection :/

**Comment by zadam** [comment]
I see. Would it be possible to create an anonymized version of the document and send it to zadam.apps@gmail.com? You can create an anonymized dump in Options -> Advanced -> Save anonymized database and then you will find it in the ~/trilium-data/anonymized

This would help finding if there is perhaps some issue in the data structure ...

**Comment by hakanu** [comment]
Thanks for the troubleshooting, just gave another try today with 0.39-beta and everything was buttery smooth, no stutter at all. Thanks for fixing it.
