### ISSUE TITLE
Trilium server slowed down after large imports

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#732]
Hi

I have been using it lightly but I decided to import all my ntoes from other apps ( I do not remember exactly but not less than couple thousand notes), it seemed to work but now Trilium is regularly loosing connection to the server "lost connection to the server" and I get these in the server log.

It seems like the slowing down also makes the Trilium apps to be unresponsive. i want to give you all the details but I am unable to open the settings pages on Linx and Win versions. They both are from couple days ago release.

I am using the Docker as my server with the :latest tag.

```

ws.js:151 17:34:24 Lost connection to server
ws.js:151 17:34:25 Lost connection to server
ws.js:151 17:34:26 Lost connection to server

```

```
Slow query took 4234ms: BEGIN
Slow query took 2940ms: COMMIT
Slow query took 2826ms: BEGIN
All consistency checks passed (took 214943ms)
Slow query took 1952ms: INSERT OR REPLACE INTO note_revisions(noteRevisionId, noteId, title, contentLength, isErased, isProtected, utcDateLastEdited, utcDateCreated, utcDateModified, dateLastEdited, dateCreated,
 type, mime, hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Slow query took 463ms: INSERT OR REPLACE INTO sync(entityName, entityId, utcSyncDate, sourceId) VALUES (?, ?, ?, ?)
Update/sync note revision nJiJ8Pe1jZMz
Slow query took 229ms: INSERT OR REPLACE INTO note_revision_contents(noteRevisionId, content, hash, utcDateModified) VALUES (?, ?, ?, ?)
Update/sync note revision content nJiJ8Pe1jZMz
Slow query took 980ms: INSERT OR REPLACE INTO notes(noteId, title, contentLength, isProtected, type, mime, hash, isDeleted, isErased, dateCreated, dateModified, utcDateCreated, utcDateModified) VALUES (?, ?, ?, 
?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Update/sync note Lp195Q4E5XTT
Update/sync note content for noteId=Lp195Q4E5XTT
Update/sync note revision ZCNsrnMhT7ZZ
Update/sync note revision content ZCNsrnMhT7ZZ
Slow query took 419ms: INSERT OR REPLACE INTO notes(noteId, title, contentLength, isProtected, type, mime, hash, isDeleted, isErased, dateCreated, dateModified, utcDateCreated, utcDateModified) VALUES (?, ?, ?, 
?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Update/sync note QAhVV03Q2Phe
Update/sync note content for noteId=QAhVV03Q2Phe
Update/sync note revision K7aLgO7ThE9x
Update/sync note revision content K7aLgO7ThE9x
Update/sync note B2N8vxLJIwPz
Update/sync note content for noteId=B2N8vxLJIwPz
Slow query took 556ms: INSERT OR REPLACE INTO sync(entityName, entityId, utcSyncDate, sourceId) VALUES (?, ?, ?, ?)
Slow query took 11021ms: COMMIT
Slow query took 261ms: INSERT OR REPLACE INTO recent_notes(noteId, notePath, hash, utcDateCreated, isDeleted) VALUES (?, ?, ?, ?, ?)
Slow query took 647ms: INSERT OR REPLACE INTO sync(entityName, entityId, utcSyncDate, sourceId) VALUES (?, ?, ?, ?)
Update/sync note revision s2f0Mdx5nuOU
Update/sync note revision content s2f0Mdx5nuOU
Slow query took 1035ms: INSERT OR REPLACE INTO notes(noteId, title, contentLength, isProtected, type, mime, hash, isDeleted, isErased, dateCreated, dateModified, utcDateCreated, utcDateModified) VALUES (?, ?, ?,
 ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Update/sync note vju1CnxR3omQ
Update/sync note content for noteId=vju1CnxR3omQ
Slow query took 29352ms: COMMIT
Slow query took 4291ms: BEGIN
Slow query took 2471ms: COMMIT
DB ready.
Slow query took 2923ms: COMMIT
DB ready.
Slow query took 2297ms: COMMIT
Slow query took 357ms: BEGIN
Content hash computation took 639402ms

```

I seem to have also these in the server logs

```
Slow query took 1164ms: BEGIN
Slow query took 697ms: COMMIT
All consistency checks passed (took 227701ms)
DB ready.
Slow query took 673ms: COMMIT
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/L0PBBqX4f7XLdvm2m8nzjvhh4liV5hmP.json'
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/L0PBBqX4f7XLdvm2m8nzjvhh4liV5hmP.json'

```

**Comment by zadam** [comment]
Hello, thanks for the report - is the Trilium slow only immediately after import or does it continue being slow also after app restart?

**Comment by gerroon** [comment]
It seems to slow down after a restart though not right away, I feel like the sync speed got a big hit, even for small changes

**Comment by gerroon** [comment]
I also just saw that the Trilium  Docker container is constantly using about %40-%50 cpu which I never saw.  And it seems like it is not going to stop, even I am not using Trilium at all. 

I wil have to take this container down

`          trilium                   45.66%     `

It seems like doing some stuff constantly

```
DB ready.
Slow query took 263ms: COMMIT
Content hash computation took 321ms
DB ready.
Slow query took 235ms: COMMIT
Content hash computation took 356ms
DB ready.
Slow query took 390ms: COMMIT
Content hash computation took 334ms
DB ready.
Slow query took 323ms: COMMIT
Content hash computation took 322ms
DB ready.
Slow query took 361ms: COMMIT
Content hash computation took 392ms
DB ready.
Slow query took 307ms: COMMIT
Content hash computation took 326ms
DB ready.
Slow query took 300ms: COMMIT
Content hash computation took 383ms
DB ready.
Slow query took 329ms: COMMIT
Content hash computation took 324ms
DB ready.
Slow query took 702ms: COMMIT
Content hash computation took 376ms
DB ready.
Slow query took 294ms: COMMIT
Content hash computation took 383ms
DB ready.
Slow query took 322ms: COMMIT
Content hash computation took 389ms


```

**Comment by gerroon** [comment]
Ohh well, not just that but the latest sync flattened the whole note tree into long single list of notes wiht thousands of notes. 

This happened right after I opened a Trilium client on Windows, this was the first time I opened it since I imported massive amounts of notes.

I am pretty sure that I lost all my notes at th momenet since a single flat list is not any use to me :( I started using Trilium because it was the best tree hierarchy type note taker.

My guess is that long syncs are prone to mess up Triliums thinking.

**Comment by gerroon** [comment]
I think the devs should test Trilium with about 10.000 notes to  figure out how stable this is really.

**Comment by gerroon** [comment]
I keepo diggin on this. When add a new client to the current server, I see something like 55000 outsanding  syncs and the database is about 500mb. I am wondering why the numbers are high. 

I am not sure how I can see the total number of notes but i doubt that I have 55k notes there.

**Comment by zadam** [comment]
That does not sound good :(

These two lines are suspicious:

```
All consistency checks passed (took 214943ms)
Content hash computation took 639402ms
```

First one is done on the startup and the second one periodically during sync - but they are way too slow - my document has more than 10 000 notes and both take under a second. This explains why there's activity when you don't do anything ...

So there seems to be something very wrong with the document. I recommend recovering a backup - trilium automatically backs up daily, weekly and monthly from ~/trilium-data/backup/ but it might be useful to keep the current corrupted one around for later analysis.

**Comment by zadam** [comment]
Could you also pls send complete logs from before the import until now to zadam.apps@gmail.com? That would help me to track down what went wrong. Thanks.

**Comment by gerroon** [comment]
I also see that it did massive amount reading from the drive. 200gb under half a day of reading of the disk sounds a bit too much.

A single databse on the client is a bout 500mb, so I do not know how it got to read 200gb of data under half a day.

` 208.34 G      2.56 G  0.00 %  4.37 % node ./src/www`

Is there  a way to optimize this?

**Comment by zadam** [comment]
Hello, thanks for the logs, I'm looking into them.

**Comment by zadam** [comment]
Not sure if you want to go to such lengths but I'll give it a shot anyway - it would be **extremely helpful** if you could send me an anonymized database (document.db). Here's how you could do that:

Download https://sqlitebrowser.org/

Open the app and open your document.db in the app (it is recommended to backup first since the next steps will be destructive).

Execute following anonymization SQL queries:

```sql
UPDATE notes SET title = 'title';
UPDATE note_contents SET content = 'text';
UPDATE note_revisions SET title = 'title';
UPDATE note_revision_contents SET content = 'title';
UPDATE attributes SET name = 'name', value = 'value' WHERE type = 'label';
UPDATE attributes SET name = 'name' WHERE type = 'relation';
UPDATE branches SET prefix = 'prefix' WHERE prefix IS NOT NULL;
UPDATE options SET value = 'anonymized' WHERE name IN ('documentSecret', 'encryptedDataKey', 'passwordVerificationHash', 'passwordVerificationSalt', 'passwordDerivedKeySalt');
VACUUM;
```

And then send me the resulting document.db

**Comment by gerroon** [comment]
Hi

Before going that route I would like to know if there is a way to restore a client's db to the server. A linux client that was opened all day read about 20mb of data vs close to 300gb the server reads. 

If I can restore all that data back to the server and keeping the user/pass etc, I would like to do that.  

It might also be something to do with Docker installation. I will try to install the regular version, but need to see how easy that is on my system.

**Comment by zadam** [comment]
There are backups under `~/trilium-data/backup`, you can just overwrite the `~/trilium-data/document.db with one of the files in that directory and restart trilium.

**Comment by gerroon** [comment]
Ok thanks, because it was the server app I thought that the data would be under the server's app folder not the user folder. It is clear now.

**Comment by zadam** [comment]
Copying the DB file is enough. Session secret is relevant for HTTP sessions only and can stay as it is ...
