### ISSUE TITLE
What about donation/sponsorship?

### ISSUE THREAD

**Issue by MrEliptik** [zadam/trilium#737]
This is not a bug but rather a simple question: **How can I give you a donation?** 
I've been using Trilium for a few months now and it's simply amazing. Also, you're very active and new updates are often bringing interesting features or tweaks. It would mean a lot to me to be able to show my gratitude by contributing to your work financially. 
I can't find any link to a patreon, buymeacoffee or anything else like that, is that a choice?

Regards,
Victor

**Comment by zadam** [comment]
Hello, so far there isn't anything setup yet. I might look into GitHub sponsor thing since that looks pretty low maintenance.

**Comment by MrEliptik** [comment]
Yes and the first year GitHub will match the donation if I recall correctly.

Also, a simple link to https://www.buymeacoffee.com/ or paypal doesn't require much work.

Anyway, thanks again for your work, and I hope to be able to contribute soon, either with a pull request or a donation.

**Comment by leoossa** [comment]
+1

**Comment by JureSencar** [comment]
+1

**Comment by zadam** [comment]
GitHub sponsor profile is now set up for the repo!
