### ISSUE TITLE
[FEATURE] Search notes by number of clones

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#738]
Hi !
While slowly migrating my stuff to trilium, i take care of having a consistent, and easy to classify database.
A common thing i do, is importing notes from the web clipper. This saves my note as a child of current day note, so i can classify them later.
Therefore, i frequently run out of time to classify my saved clips in the same day, and forget i have stuff from past days to classify,

To handle this, i created a saved search `Unclassified Clips` (`@in=vVtY4yPNDpVv @clipType`)
It searches for notes that are a child of `Journal`, and have `@clipType` attribute set.
It helps me searching for remaining clipped notes on my daynotes.

Therefore, a lot of these have already been classified somewhere else, by cloning them without removing from their original location, so i would like my saved search to show only clipped notes that were not already clonned elsewhere.

That long text was just a concrete use case of such feature.

**Note:**
> There is also a potential problem in implementing this, because as soon as my notes become available as a result of my saved search, they become cloned into it, and then stops being unique...

**Comment by zadam** [comment]
Hello, it should be possible to add such search query operator.

> There is also a potential problem in implementing this, because as soon as my notes become available as a result of my saved search, they become cloned into it, and then stops being unique...

This should not be a problem since from a database perspective the note is not actually cloned into the saved search.
