### ISSUE TITLE
QA: Respecting Sleep?

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#743]
Hi

My laptop wakes up sleep whenever I have Trilium running in the background. I think that the sync functionality is waking up the compouter because when I just close Trilium the laptop's sleep mode is not interrupted. It seems like the laptop goes to sleep for some minutes then wakes up again.

Is there a way to make sure that Trilium truely respects the sleep mode?

My laptop runs Win 10 X64.

**Comment by zadam** [comment]
I don't think any app can wake up the laptop from the standard S3 sleep.

Not sure about the new "modern standby" where apps probably can wake up the laptop but I expect only through some special API and not by mistake ...

**Comment by gerroon** [comment]
Thanks, I will do more testing and see if there is a way to debug this really.
