### ISSUE TITLE
ckeditor5 16.0 is out (code blocks feature)

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#747]
Hi !
The most awaited `code blocks` feature is out on just released ckeditor5 version:
https://github.com/ckeditor/ckeditor5/releases/tag/v16.0.0
> We are happy to announce the release of CKEditor 5 v16.0.0. This release introduces one of the most community-requested features: code blocks. We included a new restricted editing plugin, too.

You are probably already aware of it, but i had to express myself about how much i am exited :)

Related issues:
https://github.com/zadam/trilium/issues/386
https://github.com/zadam/trilium/issues/196
https://github.com/zadam/trilium/issues/220

**Comment by zadam** [comment]
Yes, I was awaiting the release eagerly as well. CKEditor with code blocks is in the 0.38.0-beta.
