### ISSUE TITLE
[script] singlefile2trilium: Save faithful copy of a web page with SingleFile web extension. 

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#750]
That's not a real issue, but more like an advertising to communicate about an integration SingleFile -> Trilium i just pushed here: https://github.com/nil0x42/singlefile2trilium

It allows the user to save a faithful copy of a web page in Trilium notes with SingleFile web extension:
![](https://raw.githubusercontent.com/nil0x42/singlefile2trilium/master/img/small-demo.png)

---

Anyway, as trilium grows, and with it's obviously great capacity to adapt and be scripted in many ways, maybe a Wiki page dedicated to external trilium scripts & resources could be useful to help newcomers to get on overview of how one can adapt trilium to its specific needs.

Because guys like be writing scripts they wish to release are happy to share them with other trilium users, and from now the only way i got was to post an issue (and that's not the purpose of issues).

**Comment by gerroon** [comment]
Looks nice, this should be part of Trilium for sure, maybe the web clipper can also have an option for this.

**Comment by nil0x42** [comment]
You are probably using trilium v0.37.X, as the [README](https://github.com/nil0x42/trilium-utils/blob/master/singlefile2trilium/README.md) says, it depends on trilium >= v0.38 (latest beta).

This is because i use the new refactored API (which is less confusing & more complete)

**Comment by nil0x42** [comment]
> maybe the web clipper can also have an option for this.
SingleFile is a bit complex extension. One possibility would be to fork SingleFile into a `lite` version and merge it with `trilium-web-clipper`.
But to be worth the work, such feature should have a large demand. Time will tell...

**Comment by gerroon** [comment]
I use the 0.38 

LIke I said I think something about the scanning in the .py script makes the import impossible because I made a hack version of it and feed the .html manually then all works and the js backend extension seem to do its job.

I will take a look at the .py script to see why it is failing on my system.

**Comment by nil0x42** [comment]
Okay, i would like very much to know what's going wrong, so keep me updated if u find.
It might be related to the 'mtime' optimization if you use a different filesystem

**Comment by Rogerzhoume** [comment]
how to import a 'singlefile' file to trilium and render it prettily like yours manually?

**Comment by nil0x42** [comment]
Hi ! You go here: https://github.com/nil0x42/trilium-utils/blob/master/singlefile2trilium/README.md and follow the instructions.

**Comment by gerroon** [comment]
@nil0x42 

Do you know any way to make Trilium to respect the page format when importing singlefile htmls? As of now all the images are messed up and they break the page formatting badly, like all images are centered vertiocally and do not allow multiple images side by side (which I something I reported as well). 

The singlefile output looks good, but looks terrible inside Trilium :(

**Comment by nil0x42** [comment]
@gerroon it might look terrible, but having an inline iframe containing the contents of singlefile is the only way i kow to have a formatting totally independent from the html classes of trilium.

If your goal is to have the exact same formatting as original page, singlefile2trilium is the way to go.
For html imports directly into trilium, it will always depend on trilium theme. Some things might probably render better, but it will depend on how each site formats its content.

**Comment by gerroon** [comment]
@nil0x42 

Thanks for the reply.  

Why does not Trilium by default capture the pages into iframe by default then? It seems to me that the results are superior.

**Comment by zadam** [comment]
> Why does not Trilium by default capture the pages into iframe by default then? It seems to me that the results are superior.

The answer is that it is simply not a goal to capture pages with all the design details, the goal is rather to extract the actual semantic content with minimal styling.

**Comment by gerroon** [comment]
Well sure but that is really debatable in my view, styling affects how we perceive information. A broken style in a document makes the information less legible in my opinion. 

The current capture is good for text but not so for mixed content to be honest.

**Comment by nil0x42** [comment]
that's why i made singlefile2trilium, this hack allows integrating fully rendered pages in your trilium.

At start i though about forking singlefile addon to fully integrate with trilium, but the development cycle of singlefile is too high to be easily forkable while maintaining upstream updates in the long term. That's why i chose to make an external script.

**Comment by gerroon** [comment]
I like this addition for sure, I am slowly trying to  rethink my flow around this.

Also a weird question, do you think a Tiddlywiki html file can be properly embedded in Trilium?

**Comment by nil0x42** [comment]
@gerroon tiddlywiki was indeed how i got the idea to embed the singlefile contents into an iframe. I mostly copy-pasted the way they do.

**Comment by popey456963** [comment]
Hm, we really do need a 'store' for these :)
