### ISSUE TITLE
"Sync check failed" warning, but syncing seems OK

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#753]
On one of Trilium desktop installations, I keep getting annoying messages that say "Sync check failed". However, as far as I can tell, all the changes I make are in fact being synced to the server (If I go to the server via the web, they are there immediately)

In the log I see: 

`23:01:05.690 INFO  Finished pull
23:01:05.692 INFO  Nothing to push
23:01:05.752 INFO  Content hash computation took 5ms
23:01:05.753 INFO  Sending message to all clients: {"type":"sync-hash-check-failed"}
23:01:05.753 INFO  Sending message to all clients: {"type":"sync-hash-check-failed"}
23:01:05.753 INFO  Sending message to all clients: {"type":"sync-hash-check-failed"}
23:01:05.754 INFO  Sending message to all clients: {"type":"sync-hash-check-failed"}

`

Is there a way I can find out which note has the unexpected hash?

**Comment by zadam** [comment]
Hello, it is possible that the sync errors comes just from metadata (e.g. date of last modification) so everything might actually look correct from the user point of view.

Unfortunately it's not that easy to figure out which note exactly caused the problem.

You can try to trigger full sync via Options -> Advanced -> Force full sync which should hopefully fix the problem.

**Comment by gerroon** [comment]
I get the same issue :(

I feel like the sync is the weakest link in the chain. I had many instances of large data imports (couple hundred mbs) that needs to be distributed to multiple cliens (that are online and offline at different times causing massive sync issues, and this is issue I get is one of them.

**Comment by jbhanks** [comment]
Forcing a full sync seems to have worked. Caused the appearance of a bunch of mystery notes though under "recovered projects". They must have been demo notes that I had previously deleted, because they were definitely not mine.

**Comment by gerroon** [comment]
I also get hundreds of recovered notes sometimes, that is when I have to revert to backups since it is not easy to deal withn hundreds of unwanted notes :(
