### ISSUE TITLE
Docker SSL Key issue

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#754]
OS: Ubuntu 18.04.3 (LTS) x64 on DigitalOcean Droplet
Version: Docker 38
Log: `trilium-data` doesn't exist in `share`

I got it running and created a user account, then went to add TLS as recommended, but when I created the cert it gives and error when running:

```
~$ sudo docker run -t -i -p 8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:0.38-latest

Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/EXAMPLE.com/privkey.pem'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at startTrilium (/usr/src/app/src/www:55:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/etc/letsencrypt/live/EXAMPLE.com/privkey.pem'
}
Generated sourceId=guex8a9fjAdr
Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/EXAMPLE.com/privkey.pem'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at startTrilium (/usr/src/app/src/www:55:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/etc/letsencrypt/live/EXAMPLE.com/privkey.pem'
}
```

I've tried re-creating the cert (3 times now) and still get this issue.

Any ideas? As stated previously, there is no `trilium-data` folder in `~/.local/share/`

Cheers,
Josh

**Comment by joshcsullivan** [comment]
Switched to Packaged Server Install and it worked immediately.

Closing this out as I am no longer using Docker.

**Comment by jbhanks** [comment]
I had this issue too, and resolved it the same way. I'd still like to know how to set up encryption with the Docker installation since that is recommended.

**Comment by chenw191** [comment]
Finally solved this problem!!! I find a similar issue:[https://github.com/ccarney16/pterodactyl-containers/issues/16](url) and fixed it by adding -v /etc/letsencrypt:/etc/letsencrypt.
