### ISSUE TITLE
attributes can't support utf_8

### ISSUE THREAD

**Issue by lbgws2** [zadam/trilium#757]
For bug reports, please mention **version of the application** and include **log files** from following location:

versidon:0.37.6
i'm chinese ,when i use  attributes,it's can not support utf_8,

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
Can you be more specific? I can create attributes with Chinese characters:

![image](https://user-images.githubusercontent.com/617641/70392948-5a374c00-19e5-11ea-8aa2-319f13d00a0c.png)

**Comment by lbgws2** [comment]
Sorry, I made a mistake. I mean, using UTF-8 for label search  is not supported,

![image](https://user-images.githubusercontent.com/3014778/70448996-30148580-1adc-11ea-870f-d61ccb087564.png)

![image](https://user-images.githubusercontent.com/3014778/70449430-f1cb9600-1adc-11ea-87d6-ae21c37dea91.png)
Search results are not related to label at all.....

**Comment by zadam** [comment]
The problem was that chinese characters were not recognized in regex as characters. As a temporary workaround you can use quotes, e.g. `@"你好"`.

This is now fixed.
