### ISSUE TITLE
Correct Way to Update Packaged Server Install

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#758]
New to Trilium, I have it running on a DigitalOcean droplet with the packaged server install. I just wanted to check on what the correct process for updating the server install?

I read I should update all clients at the same time, that's fine, but didn't see any instructions on updating the server install.

Any advice, or somewhere you can point me to instructions? I just want to make sure when I do the update it won't wipe out any data, don't worry I have more backups than probably necessary. (BSTS)

Cheers,
Josh

**Comment by zadam** [comment]
The update is just deleting the old directory (created by unzipping the .tar.xz) and unzipping the new version. Actual data are stored separately and should not be affected.

**Comment by joshcsullivan** [comment]
Thanks!
