### ISSUE TITLE
Nodejs 12:  When can we expect an upgrade to this LTS version?

### ISSUE THREAD

**Issue by rewireWI** [zadam/trilium#759]
For bug reports, please mention **version of the application** and include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
Not sure what you mean - desktop build use electron 6 with bundled nodejs 12.4 IIRC, the server build has latest 12.13.1
