### ISSUE TITLE
Markdown Questions

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#761]
Couple questions regarding markdown:

1. When importing a markdown document, tables are not formatted at all, is this not possible yet (or ever), a bug, or should be a feature request?
2. Is there a way to create a keyboard shortcut for the Import markdown from clipboard?

Cheers,
Josh

**Comment by zadam** [comment]
Hi Josh,

1. I think it's because Trilium uses CommonMark to parse Markdown and CommonMark spec does not contain support for tables.

2. Not yet, but might be easy to add. I will take a look.

**Comment by zadam** [comment]
Added a possibility to define a shortcut for pasting markdown from clipboard.

**Comment by WaytrueDeng** [comment]
I have met the same problem, I have many forms in my .md，this issue stops me using this excellent program.
