### ISSUE TITLE
Recommended Backup Process for Server Install

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#763]
I wanted to check if there is a recommended backup process for the server side data?

I currently use Duplicati and rsync to backup my entire home directory to BackBlaze and Wasabi respectively. If this is a good way of backing up Trilium, I will let it continue, but if there is a better or recommended way, I'll set that up as well.

Cheers,
Josh

PS. Not sure if all these smaller questions are best asked here or somewhere else, so let me know if there is a better place for them, thanks!

**Comment by zadam** [comment]
I don't have any particular recommendation. Just backup your `trilium-data` dir or even just `trilium-data/document.db` in whatever way and that should be enough. Other people might chime in with their recommendations.

Currently there's no other place to ask questions so it's fine for me to use issues.

**Comment by gerroon** [comment]
I recommend Borg or Restic instead since these cna do data duplication.

**Comment by joshcsullivan** [comment]
Thank you @zadam!

And thank you @gerroon, I've just installed and set up restic. I think I should be covered now.
