### ISSUE TITLE
FR: Ability to paste image data directly

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#765]
Hi

It seems like pasting images into a note is not supported at the moment. I think it is  very beneficial to have this functionality

- Open an image inside a browser ( I use FF)

- Right click `Copy Image`

- Open Trilium and Ctrl-v

Nothing happens, it seems to me that this kind of clipboard isn ot supported

thanks

**Comment by zadam** [comment]
Hmm this should work. Is that some specific image or all images? Do you press CTRL-V while in a text note?

**Comment by gerroon** [comment]
That seems to paste the image url nott he image as a new file attachment itselfs.

**Comment by gerroon** [comment]
That seems to paste the image url nott he image as a new file attachment itselfs.

**Comment by gerroon** [comment]
@zadam I cant get Trilium to paste the actual image content into Tirilium when using Ctrl-V

Copy the Linux Penguin (right click - copy image) here and just paste into a note. Turn off your internet, and you will see the image loading will be broken.

**Comment by zadam** [comment]
Yes, this is quite annoying. When you click copy image, what really gets into the clipboard is just the HTML image element referencing the image on the web and not the real image data.

So to get it saved locally there would have to be some extra processing to parse out the image, download it and save it.

Workaround I use is to save the image from the browser as a file and then drag & drop it in Trilium.

**Comment by zadam** [comment]
One more update - I was originally waiting if there's some solution from CKEditor side - this was discussed e.g. in https://github.com/ckeditor/ckeditor5/issues/5152.

But since little has happened since then I will probably tackle this soon on the Trilium side

**Comment by zadam** [comment]
Implemented in master and will be in 0.41. Now the content is parsed for image references which are then downloaded locally.

**Comment by gerroon** [comment]
HI
I tested this on Linux 0.41 beta and it does not work. It still paste the actual image and I do not see the image downloaded as sub note, like it does for local images

Try this image

https://blenderartists.org/uploads/default/original/4X/b/a/f/baf70ea18f3ab3607470ba77a5d07a0a356c736d.jpg

**Comment by zadam** [comment]
It does not require restart, however it happens asynchronously (in the background) since downloading images is potentially time consuming operation.

**Comment by gerroon** [comment]
Well I do not think it is the download time, after  the restart it took less than a second. before the restart it was pasting the url image not the actual image.
