### ISSUE TITLE
Code type `Shell` missing

### ISSUE THREAD

**Issue by pboos** [zadam/trilium#772]
Version: 0.38.2

It seems `Shell` is missing for notes (and code blocks). I know this was there before. I use it in many places. Where I used it, it still shows up. But somehow right below "Code". For new code blocks and new notes, I can not find it in the list though.

Was it removed on purpose or is this a mistake?

Cheers, Patrick

**Comment by zadam** [comment]
Selection of languages has been made configurable few releases ago and shell is by default not enabled. You can enable it in the Options -> Code notes.

**Comment by pboos** [comment]
Thanks for the REALLY QUICK (wow are you fast!) answer!

Didn't know about that. But that is perfect. Thanks!
