### ISSUE TITLE
Day note shortcut changes all open tabs to "new tab"

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#773]
Trilium 0.38.2
[trilium-2019-12-19.log](https://github.com/zadam/trilium/files/3985305/trilium-2019-12-19.log)

Steps to Re-create:
1. Open any note
2. Use the ctrl + alt + p shortcut which opens a new day note in a new tab

Expected: The day note should be opened in a new tab. All existing open tabs should remain as they are

Actual: All existing open tabs switch to the 'New Note' page as soon as the Ctrl + alt + p shortcut is invoked.

NOTE: This issue seems new to the 0.38 version. I did not see the issue in prior versions

**Comment by bwat47** [comment]
Also, another (possibly related) issue that I noticed is that when you use Ctrl + alt + p, the title field is not automatically focused when the new note is created, so I have to manually click in the title field before I can change the note's title from "new note" to something else.

Both of these issues are new to the 0.38.x version

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, should be fixed now and will be released soon.
