### ISSUE TITLE
empty checkboxes hidden in dark mode.

### ISSUE THREAD

**Issue by InflamedSebi** [zadam/trilium#775]
I usually use a dark theme (not black) since it is way less stressful to use over long period.
Sadly there is no way to detect checkboxes in dark mode.
![image](https://user-images.githubusercontent.com/1872197/71301682-b9606d80-23a2-11ea-8bcf-5018face7d38.png)

Is there anything i can do about this? I really like this theme, but i also like checkboxes ....

**Comment by zadam** [comment]
Hello, thanks for reporting this, issue, this has been fixed and will be released soon:

![image](https://user-images.githubusercontent.com/617641/71307442-c86d0d00-23ee-11ea-9790-acfc49e38f0f.png)
