### ISSUE TITLE
"Open link in new tab", does not do so.

### ISSUE THREAD

**Issue by InflamedSebi** [zadam/trilium#779]
v0.38.2
* When you left-click on an internal link, this little popup shows up "Open link in new tab" but neigter another left-click, nor middle-click on that popped-up link opens it in a new tab, it is always the current active tab getting overwritten.
* A direct middle-click on external links does nothing while a direct middle-click on internal links, does open a new tab. For consistency also external links should open with a middle-click.

**Comment by zadam** [comment]
Hello, thanks for reporting these issues, they have been fixed and will be released soon.
