### ISSUE TITLE
OPML

### ISSUE THREAD

**Issue by washere** [zadam/trilium#78]
All software for note taking in structured ways usually function in a chain of several software.

Which is why import and export is so important. Basically adequate import/export is an absolute necessity.

The main format these days for structured tree outline is OPML. It is very simple, It is basically HTML and each node or sub level node is bracketed by <outline> and </outline>. Lower level sub-nodes are nested < outline > tags within it. (I am putting spaces after < and before > so they show in comment)

Example:

< outline >Note 1
< outline >sub note level 2

< outline >level 3 sub note</ outline >

</ outline >
</ outline >

which is this tree:

-Note 1
--sub note level 2
---level 3 sub note

Very easy, just nested < outline > tags within an html format. For any tree editor, OPML import/export is basically a matter of life or death. OPML works with other software as import/export of tree structures than any other tree, and with less problems too. Can we have OPML import/export please? 

OMPL (sub XML format) Specs:
https://en.wikipedia.org/wiki/OPML#External_links

**Comment by zadam** [comment]
Hi, thanks for suggestion. I understand the need for at least basic level of interop. Trilium has currently export/import in tar format which preserves all data/metadata, but that's not usable for interop. I'll look into OMPL.

**Comment by washere** [comment]
Thanks zadam. OPML is the "Open Sesame" of outliner tree editors. Works best and with most, more than any other format. Also it is increasingly becoming the standard i/o for tree editors and is the future of tree outliners. Even just the basic nested < outline > tags for nodes/subnodes basically does the job. In fact the simpler OPML format, the more it is successfully imported/exported. The most basic OPML is the most crucial issue for any tree outliner editor IMHO these days. Thanks again for the great work.

**Comment by washere** [comment]
There are quite a few tags within outline. The main two are:

Text
_note

Text is the name of the node in tree pane on the left
_note is the content of the note in right data pane

That's it. In fact one does not use the other tags within OPML outline standard, the more softwares successfully import/export OPML. 

So for example a tree node name and it's data is simply:
`<outline text="Node 1" _note="Text of node 1">`

This is a OPML tree I generated in Android Outliner app:

https://ibb.co/iujv3S

This is how it looks in Android Halna app where the inline note is shown in the right data pane like Trilium:

https://ibb.co/gwvwA7

This is the code generated by Outliner app, very easy:

`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<opml version="2.0">
  <head>
    <title><![CDATA[Simple]]>
    </title>
    <expansionState>0,1,2,3</expansionState>
  </head>
  <body>

    <outline text="Node 1" _note="Text of node 1">
      <outline text="Child of node 1" _note="Inline text of child node">
        <outline text="Grandchild of node 1" _note="inline text for Grandchild of node 1" />
      </outline>
    </outline>

    <outline text="Sibling root node 2" _note="Data text of inline for node 2" />

  </body>
</opml>`

To generate OPML in Outliner app, press ... menu, file share, export, filetype OPML (I remember correctly). Halna imports/exports OPML too, change filetype to OPML. Can use them to generated OPML code to test, I have had their paid versions for a long time. OPML export/import lets me use numerous mindmaps, heavier text editors etc etc. It is the most crucial aspect for any tree outliner app, otherwise it will be an island and doomed.

https://play.google.com/store/apps/developer?id=Alfred+Fritz

https://play.google.com/store/apps/developer?id=halna

**Comment by washere** [comment]
To correct last post on import/export of sample OPML code in the two apps:

**Outliner app:**
Open the file (or create anew one)
3 ... dots (menu, top right of screen)
Action
Export Outline (or Import Outline)
FileType (top drop-down menu)
Opml OPML

_____________________________________________

**Halna app:**
3 ... dots (menu, top right of screen)
File
Export (or Import)
File Type (bottom left drop-down menu)
OPML

**Comment by zadam** [comment]
implemented and release OPML v1 some time ago
