### ISSUE TITLE
FR: avoid opening the same node multiple times

### ISSUE THREAD

**Issue by InflamedSebi** [zadam/trilium#781]
When opening a tab any way (node in tree or link in text & left or middle) that is already opened, should switch to that tab, instead of opening it another time in background.

**Comment by zadam** [comment]
I don't think this is necessarily desirable - you might want to have the same note opened two times with different scrolling position for example ...

**Comment by InflamedSebi** [comment]
Huh, it is just the way I m used to work, since most IDEs do it that way and I prefer navigating in the tree instead of the tabs itself, due to tabs sometimes cannot display the full title, while sidebars usually can do so:
![image](https://user-images.githubusercontent.com/1872197/71443670-aa641d00-270c-11ea-8244-021474351172.png)

Tabs being to small to display enough of the title to identify them properly gets even worse when opening more an more tabs. Sidebars instead just stay consistent.
Which leads me to https://github.com/zadam/trilium/commit/e0368e395c4a12b630777368a476e0c357c85318 why did you remove resizing?

BTW: Have a nice Christmas :) If you drop a paypal or patron link, I would love to buy you a coffee!
This project is amazing!

**Comment by zadam** [comment]
What you say makes sense to me, I will think about it.

About the resizing - actually it's just re-implemented to be much easier so that commit just cleaned up old implementation.
