### ISSUE TITLE
html export/print is incorrect for tables

### ISSUE THREAD

**Issue by InflamedSebi** [zadam/trilium#782]
If you print a table, the result is not equivalent to the editor:
- headers are centered
- no borders are shown
- no shading for header cells
- the small grey 'table border indicator square' is massive

Exporting gives the same result except from the grey 'table border indicator square', which is left out instead.

![image](https://user-images.githubusercontent.com/1872197/71428074-b88b4c80-26be-11ea-867e-86f20477d20c.png)

Maybe there should be a theme selector for html exporting or use the app theme for now?

**Comment by zadam** [comment]
Hello, thanks for reporting the issue. I just committed a change which makes printing much closer to the look of the content in editor - especially removing the huge handle. There are still some differences - I think there is some optimizations for printing (ink saving) so e.g. cell backrounds are not printed.

These changes are not applied to the HTML export though. I think it does not necessarily have to provide exact same look as is in the editor, instead I think the main focus is on providing semantic HTML. I mean, it would still be beneficial for it to look good by default but there are some practical annoyances - in case of HTML export to tar we could include the css file into it and reference it from the individual HTML files but in case of single note HTML export we would have to import it directly into the page source (as a style element) which would blow up any export significantly ...

**Comment by InflamedSebi** [comment]
This sounds reasonable. As long as printing looks fine by default, I don't care about HTML export.
Ty :)
