### ISSUE TITLE
Sidebar doesn't scroll all the way down (v0.39 beta)

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#788]
In version 39 beta, I noticed that the sidebar doesn't seem to scroll all the way down. this is the case regardless of whether the window is maximized or not:

![image](https://user-images.githubusercontent.com/1442520/71523424-05c21680-2897-11ea-9c49-8a1acbf89f25.png)

Also tested native titlebar enabled vs disabled and the behavior is the same either way

**Comment by zadam** [comment]
Unfortunately I can't reproduce this issue (on windows or linux). Is it possible that it is the window itself which is too large?

**Comment by zadam** [comment]
Hello, I managed to reproduce and fix the issue. Thanks for reporting!
