### ISSUE TITLE
Change Default Note Type for Day Notes

### ISSUE THREAD

**Issue by ttlequals0** [zadam/trilium#789]
Is it possible to change the default note type for day notes to Plain Text? In the past when i created a new note it would be a Type:code. I was able to do this by changing the parent folder to type:code but recently all new day notes are being created as type:TEXT

**Comment by zadam** [comment]
To give some answer - the way notes are created changed a bit and it is not possible to set this anymore by changing the parent note.

Probably the easiest way to do what you want is by changing e.g. the Today button implementation in the way that it would call the standard API method to create the day note and then change its type. Something like this (untested):

```
pi.addButtonToToolbar({
    title: 'Today',
    icon: 'calendar',
    shortcut: 'alt+t',
    action: async function() {
        const todayDateStr = api.formatDateISO(new Date());

        const todayNote = await api.runOnServer(async todayDateStr => {
            const dayNote = await api.getDateNote(todayDateStr);

            dayNote.type = 'code';
            dayNote.mime = 'text/plain';
            await dayNote.save();

            return dayNote;
        }, [todayDateStr]);

        api.activateNote(todayNote.noteId);
    }
});
```

**Comment by ttlequals0** [comment]
This seems to work, thank you
