### ISSUE TITLE
39-1 beta won't sync

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#790]
loaded the new windows 39-1 beta.  The fix got me to the sync with server settings.  I am accessing the server via an SSH tunnel on port 999.  Checked in browser and could get the server via 9999 just fine.  Entered http://localhost:9999/ as server and ente)red the username and password.  BTW, there is no way to see if you've made an error in password entry.  There should be a "test" button that lets the user know if the data worked.  Anyway, I got sent to a page that said if set up correctly it would sync.  Showed 0 items!  Logged into server via browser again and checked and it is 39-1.  

Went to log and this is what I see;

10:29:27.384 INFO  Generated sourceId=9tnKFXvjt0CR
10:29:27.412 INFO  App HTTP server starting up at port 37840
10:29:27.412 INFO  {
  "appVersion": "0.39.1-beta",
  "dbVersion": 155,
  "syncVersion": 13,
  "buildDate": "2019-12-27T21:21:57+01:00",
  "buildRevision": "3d95d69f80805311816acd5adf677350c3ff22b8",
  "dataDirectory": "C:\\Users\\foo\\AppData\\Roaming/trilium-data",
  "clipperProtocolVersion": "1.0"
}
10:29:27.665 INFO  DB not initialized, please visit setup page to see instructions on how to initialize Trilium.        10:29:28.725 INFO  GET /
10:29:28.749 INFO  GET /setup
10:30:01.411 INFO  POST /api/setup/sync-from-server
10:30:01.466 INFO  Getting document options from sync server.
10:30:01.843 INFO  Creating database for sync
10:30:01.919 INFO  Schema and not synced options generated.
10:30:01.920 INFO  Triggering sync.
10:30:01.958 INFO  sync failed: Request to POST http://localhost:9999//api/login/sync failed, error: 400 Bad RequestError: Request to POST http://localhost:9999//api/login/sync failed, error: 400 Bad Request
    at generateError (C:\tools\trilium-windows-x64\resources\app.asar\src\services\request.js:121:12)
    at ClientRequest.<anonymous> (C:\tools\trilium-windows-x64\resources\app.asar\src\services\request.js:51:28)            at ClientRequest.emit (events.js:200:13)
    at URLRequest.<anonymous> (C:\tools\trilium-windows-x64\resources\electron.asar\browser\api\net.js:221:18)
    at URLRequest.emit (events.js:200:13

**Comment by zadam** [comment]
Actually if you enter wrong username and password you will get an error message and won't be able to finish the setup so it looks like you entered correct credentials.

But then it fails on login/sync - one extra thing which is happening there is a timing check to mitigate possible replay attack. Is it possible that the system clock of the client and server are out of sync?

**Comment by pcause** [comment]
That could be but timezone only not utc time.  Will fix and try again

**Comment by pcause** [comment]
Just retried and with the timezones matching it worked

**Comment by zadam** [comment]
Hmm, but that is quite strange since this check is based on unix timestamps and UTC which should not be affected by the local timezones.
