### ISSUE TITLE
How can I recover my notes witch deleted careless

### ISSUE THREAD

**Issue by chncho** [zadam/trilium#793]
How can I recover my notes witch deleted careless, I cannot found this at "recent changes".

**Comment by zadam** [comment]
When you delete a note, it is actually only marked for hard-deletion (and not shown on UI) which is then done after 48 hours so it is possible to recover deleted note within that time period. However there isn't a built-in UI to do that (yet). You would need to go into SQL to do that ...

Maybe easier would be to recover backup - Trilium automatically backs up the document once a data (inside trilium-data/backup).

**Comment by chncho** [comment]
Thanks, I ' ll try it .

**Comment by zadam** [comment]
ability to undelete notes is available since 0.40. Some documentation is here: https://github.com/zadam/trilium/wiki/Note#deleting--undeleting-notes
