### ISSUE TITLE
[BUG] Zen Mode (Alt+M) broken on v0.39.1-beta

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#794]
Hi ! I just installed v0.39.1-beta and zen mode hides panes, but instead of expanding main view, it has an equivalent empty space at right.

Before pressing Alt+M:
![before](https://user-images.githubusercontent.com/3504393/71560402-774dc080-2a61-11ea-8157-3a5287bdd89b.png)
After pressing Alt+M:
![after](https://user-images.githubusercontent.com/3504393/71560407-803e9200-2a61-11ea-991b-8ef9cbc679b5.png)

**Comment by zadam** [comment]
Thanks for reporting this bug, it has been fixed.
