### ISSUE TITLE
New Linked Note Creation

### ISSUE THREAD

**Issue by wisdomlight** [zadam/trilium#795]
Maybe this is already possible but I do not know how to do it???
Create a new linked note from a highlighted text.
This means - while writing a note and highlighting a few words in it - then CTL L should allow me to create a new note with the same title as the highlighted words.
Thanks

**Comment by zadam** [comment]
There was actually a functionality similar to what you describe: https://github.com/zadam/trilium/wiki/Text-editor#cut-selection-to-sub-note

However it was disabled because of some issues but I could take a look if it's possible to reintroduce it.

**Comment by zadam** [comment]
Hello, I checked again and found a way to re-enable this. It will be available from 0.39.3. By default there is no keyboard shortcut assigned for this action, but this is configurable in the options.

**Comment by wisdomlight** [comment]
Thank you for your efforts

**Comment by wisdomlight** [comment]
Previously I isntalled Trillium
I know have a new system and trying to install it - I am totally in the blank 
could you explain to me how to install it please?

I downloaded the .zip file form the Github Extracted it - but I can't find any install file???
What am I missing
Thanks
