### ISSUE TITLE
Do Journal have wrong label?

### ISSUE THREAD

**Issue by qrsp** [zadam/trilium#799]
Hello, In the latest windows version, Journal has a label `child:sorted:sorted` in the example document.
If I click `Today` button, all child notes have correct labels.  But when I try to create child note manually, Journal's child has a label `sorted:sorted` but not `child:sorted`. I know it's not a normal use case, but it just confuses newbie like me.

Thank your hard work on this project.

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. `child:sorted:sorted` was a typo, `child:child:sorted` was intended -  which meant that children (year notes) should get `child:sorted` label and "grand-children` (month notes) would get `sorted` label.

However `sorted` is actually added also in the code handling journal so I removed this `child:child:sorted` from the demo document.

**Comment by qrsp** [comment]
Thanks for quickly fixing!
Just in case, I found the same attribute described in the [wiki](https://github.com/zadam/trilium/wiki/Day-notes) page, it may also need to be modified.
