### ISSUE TITLE
Searching attribute has multivalue will get an empty result

### ISSUE THREAD

**Issue by qrsp** [zadam/trilium#800]
Hello, when I search `@tag=christmas @tag=shopping` in the example document, I get an empty result. What I expected is searching for notes that have both tag `christmas` and `shopping`.  Do I misunderstand the syntax?

**Comment by zadam** [comment]
Hello, yes, it is intended to work as you describe, however the implementation did not work like that. This is now fixed, thanks for reporting this issue
