### ISSUE TITLE
api.removeAttribute have a unused parameter "name"

### ISSUE THREAD

**Issue by qrsp** [zadam/trilium#804]
Hello, when I tried to create a simple script to change all my typo of attributes. I noticed that removeAttribute(type, name, value) deleted all labels in notes. Here is my script.

```javascript
const filteredNotes = await api.searchForNotes('@test');

for (let i = 0; i < filteredNotes.length; i++) {
    const note = filteredNotes[i];

    let attribute = await note.getOwnedAttribute('label', 'test')
    await note.setAttribute('label', 'testing', attribute.value)
    await note.removeAttribute('label', 'test', attribute.value)
}
```

the parameter `name` wasn't checked, it checked only `type` and `value`. I am sorry that if it's intended to do so, but it's weird to me.

**Comment by zadam** [comment]
Hello, thank you for reporting this bug, it has been fixed.
