### ISSUE TITLE
Zen mode (v0.39.3): dysfunctional 'Show sidebar' button remains visible

### ISSUE THREAD

**Issue by louwers** [zadam/trilium#805]
v0.39.3

I came across this piece of software yesterday. Color me impressed! Very nicely made.
A small bug I came across: in 'Zen mode' the 'Show sidebar' button remains visible, even though it doesn't do anything.

Maybe relates to  #794

**Comment by zadam** [comment]
Hello, thanks for reporting this issue, it has been fixed.
