### ISSUE TITLE
[Feature request] Integration with code highlighters

### ISSUE THREAD

**Issue by qrsp** [zadam/trilium#806]
Hello, I'm happy that CKEditor provides code block feature, but it doesn't provide code highlight by default. According to [this]( https://ckeditor.com/docs/ckeditor5/latest/features/code-blocks.html#integration-with-code-highlighters ), it can be integrated with external code highlighters (e.g. highlight.js or Prism).

I tried to import prism.css then add attribute `appCss` and create a note that has relation `runOnNoteView` to prism.js. Despite I add class `language-css` into `<code>`, it didn't work properly. Can anyone give me some hints?

And after all, it's a dirty way, I hope the feature can be integrated into trilium eventually. I know that which color scheme and language should be enabled by default is a hard decision, maybe need to provide APIs or locations that allow users to customize what they want is a solution. Anyway, thank you for the great project.

**Comment by zadam** [comment]
The link you reference talks about integrating code highlighter for the frontend display of the rendered HTML without CKEditor. But in Trilium there's no view of the page without CKEditor - both viewing and editing are done together inside CKEditor. And these highlighters like prism.js won't work with CKEditor and I don't think this is easily fixable.

So for the foreseeable future I think code blocks will have to stay without highlighting - for that you will need to use code notes.

**Comment by qrsp** [comment]
OK, I will change the way how I take note or just use markdown.
