### ISSUE TITLE
Add explanation of restoring from backup

### ISSUE THREAD

**Issue by popey456963** [zadam/trilium#808]
I can't see any documentation anywhere on how to restore a backup for the Docker installation.

**Comment by zadam** [comment]
Hello, I added some info on how to restore the backup here: https://github.com/zadam/trilium/wiki/Backup#restoring-backup

**Comment by popey456963** [comment]
Looks great to me, thanks!

**Comment by popey456963** [comment]
Restored from backup based on the instructions, worked great! :)
