### ISSUE TITLE
Add explanation of updating trilium

### ISSUE THREAD

**Issue by popey456963** [zadam/trilium#809]
I cannot see any update steps for the Docker version.

**Comment by zadam** [comment]
Hello, I added some upgrading info here: https://github.com/zadam/trilium/wiki/Upgrading-Trilium

**Comment by popey456963** [comment]
Looks great to me, thanks!

**Comment by popey456963** [comment]
Updated based on the instructions, worked great! :+1:

Thanks for making such a fantastic knowledge base.
