### ISSUE TITLE
Crash after importing the demo .tar

### ISSUE THREAD

**Issue by MMarinov97** [zadam/trilium#812]
![imagen](https://user-images.githubusercontent.com/36660169/71901521-6c311980-3160-11ea-9be7-1c5fde54040e.png)
I deleted the demo but now I want to restore it but when I do so the server crashes completely.

**Comment by zadam** [comment]
Hello, could you please include the log?

For bug reports, please mention **version of the application** and include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by popey456963** [comment]
Closed due to no response.
