### ISSUE TITLE
Disable text wrapping

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#813]
Hi

It seems like there is some inherint text wrapping in the text block area, evident in markdown and text. It would be nice if one could disable this. because it messes up indented blocks if the width of the text is wider than the text area, which makes it look like broken text blocks.

thanks

**Comment by gerroon** [comment]
Here is a screenshot showing the issue, as you see the indented text is wrapped around and breaks the indented look, below I indented the same text in Vim, at least it should be smilar to that.

Even better it would be nice if the text wrapping is done within tht inddented block and does not cross the block line

![gvim_WcStQSqLY3](https://user-images.githubusercontent.com/8519469/72298818-cc263500-3624-11ea-8f6c-825207a56dad.jpg)

**Comment by gerroon** [comment]
@zadam

Is there any way I can get this reoslved by ediitng some file, adding some code somewhere? This is the main par tI am having hard time handling, since it messes up my note formatting badly.

thanks

**Comment by zadam** [comment]
Right now it's not possible switch off wrap on the user level. In the CodeMirror it's possible to change it with `lineWrapping: false` but that option is not propagated to the user ATM.

CodeMirror also seems to support something like indented wrap: https://codemirror.net/demo/indentwrap.html

**Comment by gerroon** [comment]
Do you know if this indenting is avail for all text types? 

Also how cna I use that hack?

**Comment by gerroon** [comment]
Ok I just replaces all the lineWrapping: true to false in the files(except .js ones) and this si exactly what I need. This is really cool!

However I built the server (based on tehw read me instrucions).  How can I build the desktop client? 

Also do you know if it is possible to build Win clients in Linux?

**Comment by zadam** [comment]
There are bin/build-win-x64.sh, bin/build-linux-x64.sh scripts in the repo which produces desktop builds.

I build all the binaries on linux, so yes, it is possible to build windows desktop build on linux.

**Comment by gerroon** [comment]
Hmm that did not work so well for me.


`bin/build-linux-x64.sh `

```
mkdir: cannot create directory ‘./dist/trilium-linux-x64-src’: No such file or directory
Copying Trilium to build directory ./dist/trilium-linux-x64-src
cp: cannot create directory './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create directory './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create directory './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create directory './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64-src/': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64-src/': No such file or directory
./bin/copy-trilium.sh: line 27: cd: ./dist/trilium-linux-x64-src: No such file or directory
rm: cannot remove './dist/trilium-linux-x64-src/node_modules/cld/deps': No such file or directory
find: ‘./dist/trilium-linux-x64-src/libraries’: No such file or directory
find: ‘./dist/trilium-linux-x64-src/libraries’: No such file or directory
Copying required linux-x64 binaries
rm: cannot remove './dist/trilium-linux-x64-src/node_modules/sqlite3/lib/binding/*': No such file or directory
rm: cannot remove './dist/trilium-linux-x64-src/node_modules/pngquant-bin/vendor/*': No such file or directory
rm: cannot remove './dist/trilium-linux-x64-src/node_modules/@felixrieseberg/spellchecker/build/Release/*': No such file or directory
cp: target './dist/trilium-linux-x64-src/node_modules/sqlite3/lib/binding/' is not a directory
cp: cannot create regular file './dist/trilium-linux-x64-src/node_modules/pngquant-bin/vendor/': No such file or directory
cp: target './dist/trilium-linux-x64-src/node_modules/@felixrieseberg/spellchecker/build/Release/' is not a directory
Packaging app for platform linux x64 using electron v6.0.12
ENOENT: no such file or directory, stat './dist/trilium-linux-x64-src'
mv: cannot stat './dist/Trilium Notes-linux-x64': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64/icon.png': No such file or directory
rm: cannot remove './dist/trilium-linux-x64/swiftshader': No such file or directory
Packaging linux x64 electron distribution...
bin/build-linux-x64.sh: line 35: cd: dist: No such file or directory
tar: trilium-linux-x64: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
bin/build-linux-x64.sh: line 41: bin/build-debian.sh: No such file or directory
```

**Comment by gerroon** [comment]
Some progres, it seemed like it is not finding dist folder so I created  that fodler, not sure why the script was not creating ther folder.But that did not lean to successful build either

```> mozjpeg@6.0.1 postinstall /tmp/kursad/trilium_desktops/dist/trilium-linux-x64-src/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> pngquant-bin@5.0.2 postinstall /tmp/kursad/trilium_desktops/dist/trilium-linux-x64-src/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
added 1032 packages from 650 contributors and audited 7128 packages in 76.84s

5 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (5 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.13.4 → 6.13.6       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.6   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Copying required linux-x64 binaries
bin/build-linux-x64.sh: line 20: ./node_modules/.bin/electron-packager: No such file or directory
mv: cannot stat './dist/Trilium Notes-linux-x64': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64/icon.png': No such file or directory
rm: cannot remove './dist/trilium-linux-x64/swiftshader': No such file or directory
Packaging linux x64 electron distribution...
tar: trilium-linux-x64: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Packaging debian x64 distribution...
bin/build-debian.sh: line 7: ./node_modules/.bin/electron-installer-debian: No such file or directory


```

**Comment by gerroon** [comment]
Some progres, it seemed like it is not finding dist folder so I created that fodler, not sure why the script was not creating ther folder.But that did not lead to successful build either



> mozjpeg@6.0.1 postinstall /tmp/USER/trilium_desktops/dist/trilium-linux-x64-src/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> pngquant-bin@5.0.2 postinstall /tmp/USER/trilium_desktops/dist/trilium-linux-x64-src/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
added 1032 packages from 650 contributors and audited 7128 packages in 76.84s

5 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (5 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.13.4 → 6.13.6       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.6   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Copying required linux-x64 binaries
bin/build-linux-x64.sh: line 20: ./node_modules/.bin/electron-packager: No such file or directory
mv: cannot stat './dist/Trilium Notes-linux-x64': No such file or directory
cp: cannot create regular file './dist/trilium-linux-x64/icon.png': No such file or directory
rm: cannot remove './dist/trilium-linux-x64/swiftshader': No such file or directory
Packaging linux x64 electron distribution...
tar: trilium-linux-x64: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Packaging debian x64 distribution...
bin/build-debian.sh: line 7: ./node_modules/.bin/electron-installer-debian: No such file or directory

**Comment by gerroon** [comment]
More progress. it seems like  Ihaev to run nmp install first. I am able to build the Linux desktop version but I cant get it to build the Win version, at least I see no win version there.

```
 ✔ pngquant pre-build test passed successfully
added 1032 packages from 650 contributors and audited 7128 packages in 67.064s

5 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (5 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
Copying required windows binaries
Packaging app for platform win32 x64 using electron v6.0.12
spawn wine64 ENOENT
mv: cannot stat './dist/Trilium Notes-win32-x64': No such file or directory
rm: cannot remove './dist/trilium-windows-x64/swiftshader': No such file or directory
Zipping windows x64 electron distribution...
        zip warning: name not matched: trilium-windows-x64

zip error: Nothing to do! (try: zip -r9 trilium-windows-x64-0.40.0-beta.zip . -i trilium-windows-x64)

```

**Comment by gerroon** [comment]
If anyone is interested in the linewrap disabling here is a simple script i made. I still have issues with the Win builds but this is the basic procedure for making a build wiht text wrapping disabled

```
mkdir -pv  /tmp//trilium_build

cd /tmp/trilium_build/trilium_build

git clone https://github.com/zadam/trilium.git trilium_desktops

cd trilium_desktops

mkdir dist

find  -type f -exec sed  -i 's/lineWrapping: true/lineWrapping: false/g' "{}" \;

npm install electron-builder --save-dev

npm install

nice -n19 bin/build-linux-x64.sh

nice -n19 bin/build-server.sh

nice -n19 bin/build-win-x64.sh
```

**Comment by gerroon** [comment]
Another thing I see as an issue with text wrapping is that it even does text wrapping in Python mode, I mean no editor viewer should allow wrapping in a Python file given that Python works with indents and wrapped text can make the code confusing.

**Comment by zadam** [comment]
> In any case I am wondering if it is possible to add css type thign to handle word wrap, linewrap, indented wrap in the session? I have no idea about web programming, so I have to bug you about this.

In normal content this is controllable with CSS pretty easily but I think CodeMirror component must bend the DOM so much that this has to be done programatically.

**Comment by gerroon** [comment]
Thanks for the repoly, it makes sense. I can live with it except that I also would like to have 

>CodeMirror also seems to support something like indented wrap: https://codemirror.net/demo/indentwrap.html

Could you direct me about how to achieve this since I do not understand what I should do to get such feature?
