### ISSUE TITLE
Docker fails to build

### ISSUE THREAD

**Issue by Miosame** [zadam/trilium#815]
After git-cloning this repo and bringing it up with docker-compose:

`ERROR: Service 'trilium' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builderxxxx/server-package.json: no such file or directory`

It's throwing because of that line, since the file does not exist: https://github.com/zadam/trilium/blob/master/Dockerfile#L6 - replacing it with just "package.json" seems to make it go past the error, but fails later on.

**Comment by zadam** [comment]
To build the docker image you need to use bin/build-docker.sh script which will generate that server-package.json file.

**Comment by LivingWithHippos** [comment]
Hello, I just ran `build-docker.sh`

I got 

```
./build-docker.sh: line 3: jq: command not found
cat: package.json: No such file or directory
[sudo] password for user: 
invalid argument "zadam/trilium:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Error parsing reference: "zadam/trilium:" is not a valid repository/tag: invalid reference format
```

I installed `jq` and re-run it, i got

```
jq: error: Could not open file package.json: No such file or directory
cat: package.json: No such file or directory
invalid argument "zadam/trilium:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Error parsing reference: "zadam/trilium:" is not a valid repository/tag: invalid reference format
```
Since the first line of `bin/build-docker.sh` is

`jq -r ".version" package.json`


Where do I get the `package.json` to be read/ what am I doing wrong?

Also docker-compose.yml still has 
`
    volumes:
      - trilium:/data
`
as volume, I think that's `/root/trilium-data` now?

**Comment by zadam** [comment]
package.json is in the project root directory - bash script assumes it's being run from the root trilium directory.
