### ISSUE TITLE
[UX] Automatically convert pasted URLs into web-links

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#818]
I spend half of my time in trilium pasting URLs. Therefore, they are not converted to links automatically, which is annoying.

So each time i paste a link, i need to:
1. highlight the link
2. press Ctrl+C
3. press Ctrl+K
4. press Ctrl+V

Converting pasted links to web-links automatically would be a great time saver

**Comment by zadam** [comment]
I agree this would be very useful, but it is mostly an editing component feature. This is tracked in https://github.com/ckeditor/ckeditor5/issues/4715

**Comment by safesparrow** [comment]
I would really like that feature too.

https://github.com/ckeditor/ckeditor5/issues/4715 seems to be ignored by the ckeditor team for a few years now, which seems weird as it appears to be a simple change.
Given that CKEditor is not an open source project (?), would it be possible to hack this functionality into Trilium itself?
I guess that would require intercepting 'paste' events on the editor component and using either https://www.npmjs.com/package/linkifyjs or https://github.com/twitter/twitter-text/tree/master/js but shouldn't be too bad. If it gets tricky or doesn't work properly 100% of the time, it would be a good fit for an optional feature controlled through the config. If that's something that you would consider @zadam , I can have a look into hacking this and raise a PR.

Does the current use of CKEditor allow for this kind of manipulation? (I guess so, as you can do it outside of the editor component and not touch anything inside).

**Comment by zadam** [comment]
You can give it a go. Ideally this would be in the form of a CKEditor plugin.

BTW, CKEditor is licensed under GPL 2+ and as such is fully open source. You can find all the source code on github.

**Comment by safesparrow** [comment]
Could you point me to the source code project?
https://github.com/ckeditor/ckeditor5 doesn't contain the source - just examples and docs (whcih are GPL 2+). Possible that I'm missing something obvious, sorry.

**Comment by zadam** [comment]
CKEditor is built on plugin architecture, every plugin as a separate repo, e.g. https://github.com/ckeditor/ckeditor5-engine https://github.com/ckeditor/ckeditor5-link https://github.com/ckeditor/ckeditor5-code-blocks etc.

**Comment by zadam** [comment]
Fixed in stable branch.
