### ISSUE TITLE
[Question] How to insert text by frontend api

### ISSUE THREAD

**Issue by cmuench** [zadam/trilium#819]
I try to add a new shortcut which inserts content in the current active tab editor.
Currently I am not finding a solution to access the active editor in a JS frontend script.

Is that possible via frontend script api?

**Comment by zadam** [comment]
Hello, I added these two API methods to cover this use case:

* api.addTextToActiveTabEditor(text) - adds text (no HTML) to current cursor position
* api.getActiveTabTextEditor() - returns CKEditor instance for full flexibility. However the API is relatively complex.

**Comment by cmuench** [comment]
@zadam Thanks.
