### ISSUE TITLE
Steel blue theme table background changes midway through table

### ISSUE THREAD

**Issue by popey456963** [zadam/trilium#827]
> Trilium Version 0.39.3

It appears that after the 12th row of a table the background colour changes to a lighter colour, identical to the base colour of the page.

![image](https://user-images.githubusercontent.com/1338129/72550850-8cad5200-388b-11ea-8766-7746a435215f.png)

**Comment by Sytten** [comment]
That is because you set the header row for all rows above 12, I did the same thing the fist time I used it.

**Comment by popey456963** [comment]
Ah, interesting. Thanks for the information!
