### ISSUE TITLE
Importing big tar file messes up  custom order of the folders under the root

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#829]
It seems like Trilium messes up the order of the sub folders in the root after a large import. I like to do manual ordering of my root folders based on my own priority however Trilium does not like that here and there and resets the order, I cant thell if the rset is based on date or alphabetical because I have alot of folders with custom characters.

it would be nice if Trilium holds onto the custom order no matter what is going on.

thanks

**Comment by zadam** [comment]
Just to clarify - you have a .tar file (produced by Trilium), you import it into Trilium and the order of notes is not the same as before it was exported by Trilium?

Order of notes should be preserved and this works from my experience. This of course won't work if the .tar file is not produced by Trilium or the `!!!meta.json` file is somehow corrupted.

**Comment by gerroon** [comment]
The tar file was produced by Boostnote and the import was done into an existing Trilium note structure (to the root)

**Comment by zadam** [comment]
Ok, but then it's not clear to me what exactly happened - does the ordering problem happen with existing (not imported) notes or with the notes just imported notes from tar?

To be clear, .tar archive (and filesystems in general) don't store file order so when you import your notes from boostnote, it can appear differently in Trilium since file order is simply not stored anywhere (maybe boostnote has its own metadata somewhere)

**Comment by gerroon** [comment]
I am sorry if I was not explaining this properly.

What I did was this.

- I deleted a note folder with couple hundred notes under

- I imported a new version of that note stucture as a tar.

- After sometime the whole order of the note tree has changed, this only affected the main note folders under the root folder. So notes under the sub notes were fine.

**Comment by zadam** [comment]
Do you have any `@sorted` labels on the notes (you can use search to find them). This is the only case where Trilium changes order of notes ...

**Comment by gerroon** [comment]
I do not have @sorted at all, but it seems to me that after ever tar import the whole tree is reordered alphebetically which is quite a hurdle because I havre to reorganize my stuff.
