### ISSUE TITLE
TypeError: Cannot destructure property `noteId` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#830]
Trilium Version: 0.39.5

Hi ! I launched trilium today, and after some seconds/minutes using it some keyboard shortcuts stoped working or behaving normally.

Then i opened logs, and there is an error being thrown every second:
```
10:11:22.254 INFO  Cannot destructure property `noteId` of 'undefined' or 'null'.
{}
TypeError: Cannot destructure property `noteId` of 'undefined' or 'null'.
    at sendPing (/lib/trilium/trilium-linux-x64-0.39.5/resources/app.asar/src/services/ws.js:86:19)
    at async /lib/trilium/trilium-linux-x64-0.39.5/resources/app.asar/src/services/ws.js:42:60
    at async Object.doExclusively (/lib/trilium/trilium-linux-x64-0.39.5/resources/app.asar/src/services/sync_mutex.js:13:16)
```

I closed and re-opened trilium, and had no error, until this error started again being thrown every second.

**Comment by zadam** [comment]
Hello, thanks for reporting this issue. Unfortunately I don't know what is the underlying issue but I made the code more robust so that it does not get stuck in this error state and should recover better.
