### ISSUE TITLE
Add permanent delition

### ISSUE THREAD

**Issue by terafo** [zadam/trilium#833]
Since now there is a way to restore deleted notes there should be a way to permanently delete note. Standart shortcut for this is Shift+Delete.

**Comment by meichthys** [comment]
@terafo There is a way to restore deleted notes? Could you explain how to do that?

**Comment by zadam** [comment]
It's in "Recent changes", more info is here: https://github.com/zadam/trilium/wiki/Note#deleting--undeleting-notes

**Comment by meichthys** [comment]
@zadam Thanks for the lightning quick reply! ⚡️
Unfortunately i don't see the deleted note in Recent Changes :/
Even if i re-create a test note and delete it, it doesn't show up in the Recent changes.

**Comment by popey456963** [comment]
@meichthys It could be that it doesn't seem to get save to `Recent Changes` straight away?

**Comment by meichthys** [comment]
@popey456963  My issue was resolved here: #994

**Comment by popey456963** [comment]
Oh, perfect!  If it's fixed I'll close this issue then? :)

**Comment by zadam** [comment]
I will reopen this since the original issue is about permanent deletion which is not implemented.

**Comment by zadam** [comment]
It's possible to choose to erase note during deletion:

![image](https://user-images.githubusercontent.com/617641/182668382-289fd525-4405-40c3-a321-7c249da9dcb2.png)
