### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by cimpresovec** [zadam/trilium#835]
I followed the the instruction on configuring Trilium with a self signed certificate (for personal use, so no domain only a public IP) and was not able to get through to the running instance with Firefox. I also tried to manually import the generated certificate file into Firefox and still wasn't able to get it working. I used the included script to generate the cert files.

Trilium starts without error but I can't get a connection through. I'm running on an Ubuntu instance on DigitalOcean, tried with the docker image and packaged server installation. I'm probably missing something so if someone can help me I'd be grateful.

**Comment by joshcsullivan** [comment]
Are you allowing HTTPS connections through the droplet firewall?

**Comment by cimpresovec** [comment]
I forgot to mention that I disabled UFW while testing to eliminate this possibility.

**Comment by cimpresovec** [comment]
After some additional testing I found the issue. I used the `generate-cert.sh` command but that produces certificates that are rejected by latest browsers. The `-sha256` option is probably the key. For example I used the following command: `openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out cert.crt -keyout key.key`.

**Comment by zadam** [comment]
Cool, thanks for getting back with the solution, I updated the script accordingly
