### ISSUE TITLE
Clip note with the url

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#837]
Hi

I like the note clipper but it would be nice if the url and/or the page title of the page  that the clipper is used (whatever page is open that that time) can be appended to the note title or as a label automatically.

thanks

**Comment by zadam** [comment]
URL is saved automatically in the @pageUrl label ..

**Comment by gerroon** [comment]
It is saved if the clip is doen as save whole page not when it is a "create text note", which only adds cliptype=note

**Comment by joshcsullivan** [comment]
I'm seeing the same thing as @gerroon when using Create Text Note, it only adds `@clipType=note` to the attributes.

When I clip whole Page, it adds the `@pageUrl=https://www.example.com` attribute. 

When I clip a screenshot, it adds the `@pageUrl=` to the attributes of the parent note (of the screenshot), but the attribute value is blank

I think it would be useful for all clippings to add the pageUrl to the attributes.

**Comment by nil0x42** [comment]
I agree that such feature is important.
I think that initially, the `Create text note` was meant to quickly add some thought or idea you have, directly from the browser, and to be independent from currently opened URL.
Therefore, i think most people (including me) tend to open trilium and create a new note for their thoughts, and only use the web clipper when their note (even text one) is directly related to the current URL thei are browsing.

**Comment by chee** [comment]
this was [fixed](https://github.com/zadam/trilium-web-clipper/commit/0811276fbbf0625575f2d4904dd59141a6e0a2e0) in trilium-web-clipper and [released](https://github.com/zadam/trilium-web-clipper/releases/tag/v0.3.0) in the current version.

i think this issue can be closed?

**Comment by zadam** [comment]
Yes, closing ...
