### ISSUE TITLE
Task completion bug?

### ISSUE THREAD

**Issue by apg-dev** [zadam/trilium#842]
Hello - brand new Trilium user here. Absolutely love what I see so far! Ran into a problem that I'm not sure is a bug or user error.

When I complete two of the sample todo's (from the demo document), the first completion (setting doneDate to an actual date) correctly moves the task from TODO into Done, but it leaves the task in red (not green). That task is "Send invites for christmas party." Completing a second task (Buy milk) leaves that 2nd task still in TODO and adds it to Done, and again leaving it in red. See image.

From the log file, I see instances of the following error:
17:08:02.847 INFO  ERROR: Execution of script "attribute changed" (dyDrUwT3TFv3) failed with error: Load of script note "attribute changed" (dyDrUwT3TFv3) failed with: Cannot read property 'increaseProgressCount' of undefined 
17:08:02.847 INFO  Sending message to all clients: {"type":"task-progress-count","progressCount":0} 

And, in Task manager > Implementation > attribute changed, I see the following error message on line 5: "Parsing error: Unexpected token api".

I can reliably reproduce this by removing document.db, re-loading the app (version 0.40.1; DB 157; Build date: 2020-01-19T15:45:06+01:00) going into the demo data and adding a dateDone for both of those tasks noted above.

Appreciate any guidance. Looking forward to considering Trilium for both my task/project manager and a full knowledge management system.

Thank you!

<img width="1561" alt="trilium-task-bug" src="https://user-images.githubusercontent.com/55888411/73310844-0f6ecf00-41f3-11ea-9035-a75c8dc019db.png">

**Comment by zadam** [comment]
Hello, this might very well be a bug in the "Task manager" script.

The problem is that this Task manager was never intended as a "production ready" task managing solution - rather it was supposed to be an example of how can you script the interaction with Trilium.

I hesitate to provide more support for this script also because I have some plans to replace it with simpler task system...

**Comment by apg-dev** [comment]
Hello - thank you for the clarification.
