### ISSUE TITLE
Possibility to insert entities in a specific tree position

### ISSUE THREAD

**Issue by leoossa** [zadam/trilium#843]
I tried to make a theme for trilium, but I don't want to use external URL's for custom fonts like in other themes I saw. 
I've seen that some fonts are in specific position like Steel Blue:
`src: url('/custom/fonts/raleway.woff2') format('woff2')`
I would like to have a possibility to put font from (file) note in specific place like: /custom/fonts/ or other url and then load them like in an example above.
I've search through API but found no such possibility.

**Comment by zadam** [comment]
Hello, I assume you want [Custom resource provider](https://github.com/zadam/trilium/wiki/Custom-request-handler#custom-resource-provider) (which is used in Steel Blue theme).

You just need to attach `customResourceProvider` label with the desired path which you can then reference in the CSS. You can take a look how this label is used in the Steel Blue fonts.

**Comment by leoossa** [comment]
Yes, that was what I was looking for. Thank you!
