### ISSUE TITLE
Create new linked note from within existing note

### ISSUE THREAD

**Issue by apg-dev** [zadam/trilium#844]
When editing a note, it would be nice if there was a way to create a new note that the first note will automatically link to. I realize the “Cut & Paste Selection to Sub-Note” will create a new note, but there are a few challenges with that:

- It takes you out and away from the original note - opening the new note in the same tab.
- While Meta+Left takes you back to the original note, it takes you back to the top of the note, not where you had just extracted the new note text. For long notes, this is quite painful.
- And perhaps most challenging, it doesn't create a link between the original note and the new note.

One way to solve this would be to allow @new_note_title to create a new linked note. Right now, the @ link only lets you link to existing notes. But it would be great if the note title didn't exist that Trilium would create a new note with that title. That would also solve the tab issue since the new link (new note) could be opened in a new tab by right-clicking on it. And the two notes would then be linked without any additional work required by the user.

Thank you!

**Comment by zadam** [comment]
Hello, Trilium currently has this limitation that you can link only to existing page but it would not be easy to "fix" this.

Your problem could be solved by having an additional option "Create and link a sub-note 'abc'" in the list when typing `@abc`. In other words you can choose from the list of notes matching the search for "abc" or you could directly from there create a note.

**Comment by apg-dev** [comment]
Hello @zadam - that additional option "Create and link a sub-note 'abc'" when typing @abc would be perfect! And if the new note opened in a new tab, that would be even better! Thank you again for this product.

**Comment by EvanCarroll** [comment]
This is what Zim does. This would be a really great feature. At my Linux Users Group we had Trilium come up as a suggestion and one of our users isn't using it for precisely this reason.

I imagine this is popular demand.

In all wiki-note taking software I've used creating links to notes that don't exist yet is a pretty major part of the work flow (like in zim). Either that or reflowing all text when a new note is created to automagically link notes (like in gnote).

**Comment by Jayddo** [comment]
that would make my workflow immensely faster as it would just allow me to jolt things down as concepts to then work on later on their own page.

ideally I could see such a page created while linking to it in some sort of inbox or something, so you can put it in the proper category later. 

That would make it easier to organize for it, if it's possible.

**Comment by zadam** [comment]
Released in 0.44.4.

More details in #1237
