### ISSUE TITLE
FR: Ability to easily see and quickly jump to notes with the same tags

### ISSUE THREAD

**Issue by apg-dev** [zadam/trilium#848]
If using tag attributes (e.g. @tag=productivity, @tag=note-taking), it would be helpful for a Link Tag Map widget to show all notes that contain the same tags as the current note → ideally with each of them hyperlinkable. 

Otherwise, only other option is to search for “@tag=tagname”. But that won't quickly show all notes with all tags that are within the current note. You have to search one tag at a time and mentally build your own link tag map.

**Comment by zadam** [comment]
I like that idea. In general I plan to work on making related notes more discoverable - so far this is done through link map (relations) and "similar notes" (looks for similar note titles), in the future I plan to add more advanced content analysis and also this label based context (which would be also pretty simple).

**Comment by apg-dev** [comment]
Ty. I love the idea of more advanced content analysis and label based context.

In the short-term, any chance we can get a Link Tag Map widget (similar to Link Map widget) that shows all notes that have the same attribute of tag = tagname?

**Comment by zadam** [comment]
Short term probably no, I'm now fully focused on 0.41 branch which contains big refactoring of the frontend and will take few more weeks to finish.

**Comment by apg-dev** [comment]
Makes sense. Appreciate all you're doing.
