### ISSUE TITLE
Can you search by inherited attributes?

### ISSUE THREAD

**Issue by dtomlinson91** [zadam/trilium#850]
Say I have a parent note that is tagged with `project` and I set this to be inheritable. I also create a child note under this parent note.:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/53234158/73600928-e8e0c900-454f-11ea-87ed-7e4f6e0fe775.png">

I search by `@project` and I can see the parent note:

![image](https://user-images.githubusercontent.com/53234158/73600943-0d3ca580-4550-11ea-82b9-34cbba22cc64.png)

But not the child note which has inherited this attribute:

![image](https://user-images.githubusercontent.com/53234158/73600945-204f7580-4550-11ea-877b-88de04bd9b71.png)

Have I misunderstood how inheritance is supposed to work? If I can't search by inherited attributes I don't see the point in them - surely this means I have to manually create everything underneath the note with the same attribute to be able to search by them. What are they used for in this case?

**Comment by dtomlinson91** [comment]
I did think about doing something like:

```javascript
const parentNote = await api.getNote('FVbYrIr1xnaM');

for (const childNote of await parentNote.getChildNotes()) {
     await childNote.setLabel('project', 'home');
}
```
to force it to apply non-inherited attributes to all notes in this tree (as an example), and I could extend this to run whenever I open the book and make sure everything has a tag linking it to this project - but this _seems_ to be what inherited attributes is for.

**Comment by zadam** [comment]
Hello, you are right that inherited attributes are not considered when searching. Inheritance is "computed" in runtime and has some costs - this is fine when checking inherited attributes for couple of notes, but not for potentially hundreds of thousands of notes. Which means it is not currently applied on mass operations like search.

One of the typical use cases of inherited attributes would be e.g. `@archived` label or `@template` relation which will mostly affect presentation of the note.

Perhaps other solutions would be more useful for your use case - there's a [copying inheritance](https://github.com/zadam/trilium/wiki/Attribute-inheritance#copying-inheritance) which will reflect in the search or you might want to use `@in=[noteid]` virtual attribute in the saved search ...

**Comment by dtomlinson91** [comment]
Ah copying inheritance works like a charm - I thought you could _only_ use it with a relation attribute I didn't realise you could use it in a Label as well.

I can't thank you enough for the scripting api - implementing these tags now on my existing notes is a breeze thanks to your hard work. Thanks!
