### ISSUE TITLE
Right Click Advanced Menu Almost Hidden

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#853]
Whether using the desktop version or browser version, when right clicking and trying to accessing the Advanced Menu if it is too far down on the tree, you can only see the `Collapse Subtree` option:

![image](https://user-images.githubusercontent.com/5774100/73669112-ecba3b80-4674-11ea-89dc-7562d492e607.png)

**Comment by zadam** [comment]
Hello, this would be non-trivial to fix "correctly" so for now I worked around the issue by putting the "advanced" item more towards the middle instead of at the end which will guarantee it won't be hidden.
