### ISSUE TITLE
FR: Change Default Web Clipper Location

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#854]
I'd love to have an option to change the default web clipper save location. I don't really use the Calendar feature for daily notes, instead I have a Inbox note, and under that all new notes are created.

I would rather be able to select this Inbox note as the default save location for the web clipper so that all new clippings end up there, which is where I go for note processing at the end of the day.

Cheers,
Josh

**Comment by zadam** [comment]
Good suggestion, I think I'll make this configurable by attaching a label like `@clipperInbox` to the desired parent note.

**Comment by casidiablo** [comment]
This is a good feature. Thanks, and thanks for the project in general. I'm really enjoying using Trilium.

**Comment by jbhanks** [comment]
When I first tried this, I set both the name and the value of the label to `@clipperInbox`. The clips kept going into the day folder until I removed the `@` from the name.

**Comment by davidnsw** [comment]
@jbhanks, thanks for your reply. I have same issue. I resolve the issue based on your answer.
