### ISSUE TITLE
Markdown Table Not Imported Correctly

### ISSUE THREAD

**Issue by decaby7e** [zadam/trilium#855]
When attempting to import a markdown table from a .md file, the following happens:

| test | 1 | 2 | | ----- | ----- | ----- | | test1 | test2 | test3 | | test4 | test5 | test6 | | test7 | test8 | test9 |

![image](https://user-images.githubusercontent.com/27081624/73717917-157c1880-46e9-11ea-92d5-9d886262e5e5.png)

Here is the original file:
```md
| test  | 1     | 2     |
| ----- | ----- | ----- |
| test1 | test2 | test3 |
| test4 | test5 | test6 |
| test7 | test8 | test9 |
```

![image](https://user-images.githubusercontent.com/27081624/73717934-24fb6180-46e9-11ea-8f0c-d4cdc3ac7547.png)

**Comment by joshcsullivan** [comment]
See: https://github.com/zadam/trilium/issues/761#issuecomment-564068468

Trillium uses CommonMark for markdown which doesn’t have table support.
