### ISSUE TITLE
[Feature Request] Daily Checklist Reset

### ISSUE THREAD

**Issue by heliomass** [zadam/trilium#857]
Hello,

It would be nice to have the option of a checklist resetting itself every day. For example, if you have a daily checklist you action each morning the checked items could clear automatically at midnight.

Cheers.

**Comment by zadam** [comment]
You might want to take a look [here](https://github.com/zadam/trilium/wiki/Day-notes#templates) - day notes + template might do what you want.

**Comment by heliomass** [comment]
Thanks! I've not explored the template functionality, but it sounds like this would do the trick.
