### ISSUE TITLE
Drawing support for better concept mapping?

### ISSUE THREAD

**Issue by Nanodragon999** [zadam/trilium#858]
Hi,

So i thought it would be great to have drawing support, so one could have the same freedom as using pen and paper -- basically writing etc as usual, then drawing if one want too (freestyle) for better concept mapping/or any other purpose.

I mainly plan to use this for concept/mind mapping, since that's what i usually do on paper.

Drawing with the mouse would be mandatory -- but maybe making preset/template for some forms, like boxes/arrows, so those could be put in place by a key-bind instead of using the mouse.

**Comment by Heniker** [comment]
Maybe we can look towards UML diagrams? Those might be more suitable.
Not sure if CKEditor supports them though..

**Comment by thfrei** [comment]
Suggestion: close this, since Feature branch was merged? #2798
