### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by tvortsa** [zadam/trilium#860]
For bug reports, please mention **version of the application** and include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
any details?

**Comment by popey456963** [comment]
Closing as no new details have been given.
