### ISSUE TITLE
Opening and closing "Jump to note" or search form from within editor view loses cursor position and focus

### ISSUE THREAD

**Issue by safesparrow** [zadam/trilium#861]
First of all: thank you very much for the app. I only started using it today but it looks extremely promising and matching the way I imagined an ideal note-taking app to work! It loks very impressive compared to all other apps I've seen so far. I hope I will be able to find some piece of work I can contribute to at some point.

I'm using v0.40.2 of the app.
Steps to reproduce:
- Edit a note
- Use `Ctrl+J` shortcut to open `Jump to note` dialog
  - alternatively use `Ctrl+S` shortcut to open/focus on the search pane
- Hit `Esc` or click `x` button to close the `Jump to note` dialog (or `Ctrl+S` again to close the search pane)

Now the focus is no longer on the editor view and you can't continue typing/editing.
Actually I'm not sure where the focus is exactly as I can't navigate the tree either. I think it's somewhere between the last link in the `Similar Notes` section and the note title box (inferred when clicking `TAB` and `SHIFT+TAB` after closing the dialog.

Would it be able to change this behaviour so that one can continue their editing without interruption?
Thank you!

**Comment by zadam** [comment]
Hello, you are right, I noticed this too before and it is a bit annoying. Now this is fixed - focus is returned to the element which was focused before the dialog was opened.

However this works only with keyboard shortcuts - when you open the dialog by mouse click then you are explicitly focusing the button and then opening the dialog. But when you use mouse to open the dialog then it's not so weird you need to use mouse to get back to the editor ...
