### ISSUE TITLE
Dark mode for web view

### ISSUE THREAD

**Issue by aashish108** [zadam/trilium#863]
Hello again. Is it possible to get a dark mode for web view mobile pls? I  looked around and couldn't see anything.

Cheers

**Comment by skyperkloze** [comment]
Unsubscribe

**Comment by zadam** [comment]
Dark mode (or any theming) is currently not supported on the mobile frontend.

**Comment by gerroon** [comment]
try the DarkReader addon.

**Comment by good-praxis** [comment]
Oh hey, I fixed this in #1374
