### ISSUE TITLE
Can't figure out out check-box lists?

### ISSUE THREAD

**Issue by EvanCarroll** [zadam/trilium#864]
The Demo app says,

> Create easy TODO-lists with checkboxes:

Yet, I can't figure it out. From a new note, how do I create a checkboxes? The only thing I can guess is that we're supposed to render the HTML and paste it into a new note?

What I would expect is that typing `[ ] foo` or the like would create a check box, but that doesn't seem to work either.

**Comment by zadam** [comment]
Click on the block toolbar and then "todo list":

![image](https://user-images.githubusercontent.com/617641/74106561-4d131680-4b68-11ea-9b37-f86038d5d0d0.png)

**Comment by EvanCarroll** [comment]
Cool cool. That works. I certainly would have never figured that out without you telling me.
