### ISSUE TITLE
linux: gui window fails to display

### ISSUE THREAD

**Issue by quesada** [zadam/trilium#865]
When running ./trilium  gui window fails to display

Version:
0.40,.3

07:22:39.017 INFO  Generated sourceId=HO0SjNn3uAzb 
07:22:39.027 INFO  App HTTP server starting up at port 37840 
07:22:39.027 INFO  {
  "appVersion": "0.40.3",
  "dbVersion": 157,
  "syncVersion": 14,
  "buildDate": "2020-02-09T10:48:23+01:00",
  "buildRevision": "88bd65c6798609a39206722305fab4f8d91d618b",
  "dataDirectory": "/home/q/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
} 
07:22:39.038 INFO  App db version is 157, while db version is 136. Migration needed. 
07:22:39.038 INFO  Created backup at /home/q/.local/share/trilium-data/backup/backup-before-migration.db 
07:22:39.041 INFO  Attempting migration to version 137 
07:22:39.067 INFO  Migration to version 137 has been successful. 
07:22:39.067 INFO  Attempting migration to version 138 
07:22:39.081 INFO  Migration to version 138 has been successful. 
07:22:39.081 INFO  Attempting migration to version 139 
07:22:39.096 INFO  Migration to version 139 has been successful. 
07:22:39.096 INFO  Attempting migration to version 140 
07:22:39.109 INFO  Migration to version 140 has been successful. 
07:22:39.109 INFO  Attempting migration to version 141 
07:22:39.126 INFO  Migration to version 141 has been successful. 
07:22:39.126 INFO  Attempting migration to version 142 
07:22:39.138 INFO  Migration to version 142 has been successful. 
07:22:39.138 INFO  Attempting migration to version 143 
07:22:39.152 INFO  Migration to version 143 has been successful. 
07:22:39.152 INFO  Attempting migration to version 144 
07:22:39.167 INFO  Migration to version 144 has been successful. 
07:22:39.167 INFO  Attempting migration to version 145 
07:22:39.187 INFO  Migration to version 145 has been successful. 
07:22:39.187 INFO  Attempting migration to version 146 
07:22:39.201 INFO  Migration to version 146 has been successful. 
07:22:39.202 INFO  Attempting migration to version 147 
07:22:39.221 INFO  Migration to version 147 has been successful. 
07:22:39.221 INFO  Attempting migration to version 148 
07:22:39.245 INFO  Migration to version 148 has been successful. 
07:22:39.245 INFO  Attempting migration to version 149 
07:22:39.267 INFO  Migration to version 149 has been successful. 
07:22:39.267 INFO  Attempting migration to version 150 
07:22:39.288 INFO  Migration to version 150 has been successful. 
07:22:39.289 INFO  Attempting migration to version 151 
07:22:39.314 INFO  Migration to version 151 has been successful. 
07:22:39.314 INFO  Attempting migration to version 152 
07:22:39.343 INFO  Migration to version 152 has been successful. 
07:22:39.343 INFO  Attempting migration to version 153 
07:22:39.371 INFO  Migration to version 153 has been successful. 
07:22:39.371 INFO  Attempting migration to version 154 
07:22:39.389 INFO  Migration to version 154 has been successful. 
07:22:39.390 INFO  Attempting migration to version 155 
07:22:39.411 INFO  Migration to version 155 has been successful. 
07:22:39.412 INFO  Attempting migration to version 156 
07:22:39.450 INFO  Migration to version 156 has been successful. 
07:22:39.451 INFO  Attempting migration to version 157 
07:22:39.478 INFO  Migration to version 157 has been successful. 
07:22:39.512 INFO  Created missing option "imageMaxWidthHeight" with default value "1200" 
07:22:39.530 INFO  Created missing option "imageJpegQuality" with default value "75" 
07:22:39.548 INFO  Created missing option "autoFixConsistencyIssues" with default value "true" 
07:22:39.569 INFO  Created missing option "leftPaneWidth" with default value "25" 
07:22:39.585 INFO  Created missing option "rightPaneWidth" with default value "25" 
07:22:39.601 INFO  Created missing option "rightPaneVisible" with default value "true" 
07:22:39.616 INFO  Created missing option "nativeTitleBarVisible" with default value "false" 
07:22:39.641 INFO  Created missing option "eraseNotesAfterTimeInSeconds" with default value "604800" 
07:22:39.660 INFO  Created missing option "keyboardShortcutsBackInNoteHistory" with default value "["Alt+Left"]" 
07:22:39.676 INFO  Created missing option "keyboardShortcutsForwardInNoteHistory" with default value "["Alt+Right"]" 
07:22:39.692 INFO  Created missing option "keyboardShortcutsJumpToNote" with default value "["Ctrl+J"]" 
07:22:39.708 INFO  Created missing option "keyboardShortcutsScrollToActiveNote" with default value "["Ctrl+."]" 
07:22:39.730 INFO  Created missing option "keyboardShortcutsSearchNotes" with default value "["Ctrl+S"]" 
07:22:39.745 INFO  Created missing option "keyboardShortcutsSearchInSubtree" with default value "["Ctrl+Shift+S"]" 
07:22:39.760 INFO  Created missing option "keyboardShortcutsCollapseTree" with default value "["Alt+C"]" 
07:22:39.773 INFO  Created missing option "keyboardShortcutsCollapseSubtree" with default value "["Alt+-"]" 
07:22:39.794 INFO  Created missing option "keyboardShortcutsActivateParentNote" with default value "["Backspace"]" 
07:22:39.812 INFO  Created missing option "keyboardShortcutsSortChildNotes" with default value "["Alt+S"]" 
07:22:39.825 INFO  Created missing option "keyboardShortcutsCreateNoteAfter" with default value "["Ctrl+O"]" 
07:22:39.841 INFO  Created missing option "keyboardShortcutsCreateNoteInto" with default value "["Ctrl+P"]" 
07:22:39.861 INFO  Created missing option "keyboardShortcutsCreateNoteIntoDayNote" with default value "["global:Ctrl+Alt+P"]" 
07:22:39.880 INFO  Created missing option "keyboardShortcutsDeleteNotes" with default value "["Delete"]" 
07:22:39.899 INFO  Created missing option "keyboardShortcutsMoveNoteUp" with default value "["Ctrl+Up"]" 
07:22:39.914 INFO  Created missing option "keyboardShortcutsMoveNoteDown" with default value "["Ctrl+Down"]" 
07:22:39.934 INFO  Created missing option "keyboardShortcutsMoveNoteUpInHierarchy" with default value "["Ctrl+Left"]" 
07:22:39.949 INFO  Created missing option "keyboardShortcutsMoveNoteDownInHierarchy" with default value "["Ctrl+Right"]" 
07:22:39.970 INFO  Created missing option "keyboardShortcutsEditNoteTitle" with default value "["Enter"]" 
07:22:39.986 INFO  Created missing option "keyboardShortcutsEditBranchPrefix" with default value "["F2"]" 
07:22:40.001 INFO  Created missing option "keyboardShortcutsCloneNotesTo" with default value "["Ctrl+Shift+C"]" 
07:22:40.024 INFO  Created missing option "keyboardShortcutsMoveNotesTo" with default value "["Ctrl+Shift+X"]" 
07:22:40.037 INFO  Created missing option "keyboardShortcutsCopyNotesToClipboard" with default value "["Ctrl+C"]" 
07:22:40.057 INFO  Created missing option "keyboardShortcutsPasteNotesFromClipboard" with default value "["Ctrl+V"]" 
07:22:40.071 INFO  Created missing option "keyboardShortcutsCutNotesToClipboard" with default value "["Ctrl+X"]" 
07:22:40.089 INFO  Created missing option "keyboardShortcutsSelectAllNotesInParent" with default value "["Ctrl+A"]" 
07:22:40.102 INFO  Created missing option "keyboardShortcutsAddNoteAboveToSelection" with default value "["Shift+Up"]" 
07:22:40.116 INFO  Created missing option "keyboardShortcutsAddNoteBelowToSelection" with default value "["Shift+Down"]" 
07:22:40.133 INFO  Created missing option "keyboardShortcutsOpenNewTab" with default value "["Ctrl+T"]" 
07:22:40.154 INFO  Created missing option "keyboardShortcutsCloseActiveTab" with default value "["Ctrl+W"]" 
07:22:40.174 INFO  Created missing option "keyboardShortcutsActivateNextTab" with default value "["Ctrl+Tab"]" 
07:22:40.193 INFO  Created missing option "keyboardShortcutsActivatePreviousTab" with default value "["Ctrl+Shift+Tab"]" 
07:22:40.208 INFO  Created missing option "keyboardShortcutsShowAttributes" with default value "["Alt+A"]" 
07:22:40.228 INFO  Created missing option "keyboardShortcutsShowNoteInfo" with default value "[]" 
07:22:40.246 INFO  Created missing option "keyboardShortcutsShowNoteSource" with default value "[]" 
07:22:40.264 INFO  Created missing option "keyboardShortcutsShowLinkMap" with default value "[]" 
07:22:40.280 INFO  Created missing option "keyboardShortcutsShowOptions" with default value "[]" 
07:22:40.298 INFO  Created missing option "keyboardShortcutsShowNoteRevisions" with default value "[]" 
07:22:40.314 INFO  Created missing option "keyboardShortcutsShowRecentChanges" with default value "[]" 
07:22:40.333 INFO  Created missing option "keyboardShortcutsShowSQLConsole" with default value "["Alt+O"]" 
07:22:40.352 INFO  Created missing option "keyboardShortcutsShowBackendLog" with default value "[]" 
07:22:40.368 INFO  Created missing option "keyboardShortcutsShowHelp" with default value "["F1"]" 
07:22:40.387 INFO  Created missing option "keyboardShortcutsAddLinkToText" with default value "["Ctrl+L"]" 
07:22:40.405 INFO  Created missing option "keyboardShortcutsInsertDateTimeToText" with default value "["Alt+T"]" 
07:22:40.423 INFO  Created missing option "keyboardShortcutsPasteMarkdownIntoText" with default value "[]" 
07:22:40.439 INFO  Created missing option "keyboardShortcutsCutIntoNote" with default value "[]" 
07:22:40.452 INFO  Created missing option "keyboardShortcutsPrintActiveNote" with default value "[]" 
07:22:40.471 INFO  Created missing option "keyboardShortcutsRunActiveNote" with default value "["Ctrl+Enter"]" 
07:22:40.486 INFO  Created missing option "keyboardShortcutsToggleNoteHoisting" with default value "["Alt+H"]" 
07:22:40.503 INFO  Created missing option "keyboardShortcutsReloadFrontendApp" with default value "["F5","Ctrl+R"]" 
07:22:40.518 INFO  Created missing option "keyboardShortcutsOpenDevTools" with default value "["Ctrl+Shift+I"]" 
07:22:40.533 INFO  Created missing option "keyboardShortcutsFindInText" with default value "["Ctrl+F"]" 
07:22:40.554 INFO  Created missing option "keyboardShortcutsToggleFullscreen" with default value "["F11"]" 
07:22:40.576 INFO  Created missing option "keyboardShortcutsToggleZenMode" with default value "["Alt+M"]" 
07:22:40.591 INFO  Created missing option "keyboardShortcutsZoomOut" with default value "["Ctrl+-"]" 
07:22:40.607 INFO  Created missing option "keyboardShortcutsZoomIn" with default value "["Ctrl+="]" 
07:22:40.634 INFO  Created missing option "keyboardShortcutsCopyWithoutFormatting" with default value "["Ctrl+Alt+C"]" 
07:22:40.635 INFO  DB ready. 
07:22:40.771 INFO  DB size: 770 KB 
07:22:40.776 INFO  DB ready. 
07:22:40.790 INFO  GET / 
07:22:40.796 INFO  Registered global shortcut Ctrl+Alt+P for action CreateNoteIntoDayNote 
07:22:40.804 INFO  Generated CSRF token gJPy1qxW-XH3Vd1LDptv2Hmu2qpMU0A64hmw with secret _csrf=V-rKDvyYKRkW99ENr8WPh1yA; Path=/ 
07:22:40.805 INFO  Generated sourceId=IaQ1x5POYvRj 
07:22:41.196 INFO  GET /api/keyboard-actions 
07:22:41.209 INFO  GET /api/keyboard-shortcuts-for-notes 
07:22:41.211 INFO  GET /api/options 
07:22:41.229 INFO  GET /api/notes/download/2TvFaoM2lAEu 
07:22:41.232 INFO  GET /api/notes/download/7BCm7zHG4xeS 
07:22:41.237 INFO  GET /api/tree 
07:22:41.311 INFO  GET /api/notes/KRondimZU9W6 
07:22:41.329 INFO  GET /api/notes/vWSbokJ0IbhK 
07:22:41.347 INFO  GET /api/notes/KUpcgiCmmLUx 
07:22:41.373 INFO  GET /api/script/startup 
07:22:41.534 INFO  POST /api/tree/load 
07:22:41.633 INFO  POST /api/tree/load 
07:22:41.648 INFO  GET /api/notes/vWSbokJ0IbhK/attributes 
07:22:41.677 INFO  GET /api/notes/vWSbokJ0IbhK/attributes 
07:22:42.214 INFO  GET /api/script/relation/vWSbokJ0IbhK/runOnNoteView 
07:22:42.252 INFO  GET /api/notes/vWSbokJ0IbhK/revisions 
07:22:42.253 INFO  GET /api/similar-notes/vWSbokJ0IbhK 
07:22:42.344 INFO  POST /api/notes/vWSbokJ0IbhK/link-map 
07:22:43.254 INFO  PUT /api/options 
07:22:47.214 INFO  POST /api/recent-notes 
07:23:06.591 INFO  Generated sourceId=JHE148NiMWlW 
07:23:42.886 INFO  Generated sourceId=VBHML5gALCNA 
07:23:42.896 INFO  App HTTP server starting up at port 37840 
07:23:42.896 INFO  {
  "appVersion": "0.40.3",
  "dbVersion": 157,
  "syncVersion": 14,
  "buildDate": "2020-02-09T10:48:23+01:00",
  "buildRevision": "88bd65c6798609a39206722305fab4f8d91d618b",
  "dataDirectory": "/home/q/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
} 
07:23:42.911 INFO  DB ready. 
07:23:42.933 INFO  DB size: 770 KB 
07:23:43.038 INFO  GET / 
07:23:43.047 INFO  Registered global shortcut Ctrl+Alt+P for action CreateNoteIntoDayNote 
07:23:43.056 INFO  Generated CSRF token nlts8mw6-wsxfEy4QIQqxANLbmXrinHO0lQA with secret _csrf=10YUMHUMrG6B7GUfmDlJAQpJ; Path=/ 
07:23:43.057 INFO  Generated sourceId=u47mLq6YuF5s 
07:23:43.568 INFO  GET /api/keyboard-actions 
07:23:43.577 INFO  GET /api/keyboard-shortcuts-for-notes 
07:23:43.578 INFO  GET /api/options 
07:23:43.593 INFO  GET /api/notes/download/2TvFaoM2lAEu 
07:23:43.595 INFO  GET /api/notes/download/7BCm7zHG4xeS 
07:23:43.598 INFO  GET /api/tree 
07:23:43.673 INFO  GET /api/notes/KRondimZU9W6 
07:23:43.695 INFO  GET /api/notes/vWSbokJ0IbhK 
07:23:43.714 INFO  GET /api/notes/KUpcgiCmmLUx 
07:23:43.737 INFO  GET /api/script/startup 
07:23:43.750 INFO  POST /api/tree/load 
07:23:43.912 INFO  POST /api/tree/load 
07:23:43.948 INFO  GET /api/notes/vWSbokJ0IbhK/attributes 
07:23:44.583 INFO  GET /api/script/relation/vWSbokJ0IbhK/runOnNoteView 
07:23:44.612 INFO  GET /api/notes/vWSbokJ0IbhK/attributes 
07:23:44.651 INFO  GET /api/notes/vWSbokJ0IbhK/revisions 
07:23:44.653 INFO  GET /api/similar-notes/vWSbokJ0IbhK 
07:23:44.784 INFO  POST /api/notes/vWSbokJ0IbhK/link-map 
07:23:45.653 INFO  PUT /api/options 
07:23:49.583 INFO  POST /api/recent-notes 
07:24:00.188 INFO  Generated sourceId=C1kboTzOghzC 
07:24:33.217 INFO  Generated sourceId=Yicpe1FFMVdI 
07:25:53.666 INFO  Created backup at /home/q/.local/share/trilium-data/backup/backup-daily.db 
07:25:53.667 INFO  sync failed: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUTError: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUT
    at generateError (/usr/lib/trilium/resources/app.asar/src/services/request.js:121:12)
    at ClientRequest.<anonymous> (/usr/lib/trilium/resources/app.asar/src/services/request.js:47:47)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest._emitRequestEvent (/usr/lib/trilium/resources/electron.asar/browser/api/net.js:114:28) 
07:25:53.670 INFO  Notes deleted: 0, not deleted 101 
07:25:53.671 INFO  Note revisions deleted: 0, not deleted 6 
07:25:53.672 INFO  Branches deleted: 0, not deleted 115 
07:25:53.687 INFO  Attributes deleted: 10, not deleted 173 
07:25:53.689 INFO  API tokens deleted: 0, not deleted 0 
07:25:53.739 INFO  All consistency checks passed (took 65ms) 
07:28:04.729 INFO  sync failed: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUTError: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUT
    at generateError (/usr/lib/trilium/resources/app.asar/src/services/request.js:121:12)
    at ClientRequest.<anonymous> (/usr/lib/trilium/resources/app.asar/src/services/request.js:47:47)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest._emitRequestEvent (/usr/lib/trilium/resources/electron.asar/browser/api/net.js:114:28) 
07:30:09.105 INFO  Generated sourceId=6GnMn19Mjzo7 
07:30:09.116 INFO  App HTTP server starting up at port 37840 
07:30:09.116 INFO  {
  "appVersion": "0.40.3",
  "dbVersion": 157,
  "syncVersion": 14,
  "buildDate": "2020-02-09T10:48:23+01:00",
  "buildRevision": "88bd65c6798609a39206722305fab4f8d91d618b",
  "dataDirectory": "/home/q/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
} 
07:30:09.128 INFO  DB ready. 
07:30:09.240 INFO  DB size: 770 KB 
07:30:09.250 INFO  GET / 
07:30:09.256 INFO  Registered global shortcut Ctrl+Alt+P for action CreateNoteIntoDayNote 
07:30:09.265 INFO  Generated CSRF token 6UbgMg2c-p-K8C7hQ4R8Uk6_EHR6cAhi6uaE with secret _csrf=iqa_SHtIpNcOG-t1goTxebPb; Path=/ 
07:30:09.266 INFO  Generated sourceId=l0vCfleQLmZL 
07:30:09.774 INFO  GET /api/keyboard-actions 
07:30:09.787 INFO  GET /api/keyboard-shortcuts-for-notes 
07:30:09.789 INFO  GET /api/options 
07:30:09.810 INFO  GET /api/notes/download/2TvFaoM2lAEu 
07:30:09.813 INFO  GET /api/notes/download/7BCm7zHG4xeS 
07:30:09.817 INFO  GET /api/tree 
07:30:09.894 INFO  GET /api/notes/KRondimZU9W6 
07:30:09.916 INFO  GET /api/notes/vWSbokJ0IbhK 
07:30:09.936 INFO  GET /api/notes/KUpcgiCmmLUx 
07:30:09.962 INFO  GET /api/script/startup 
07:30:10.119 INFO  POST /api/tree/load 
07:30:10.150 INFO  POST /api/tree/load 
07:30:10.176 INFO  GET /api/notes/vWSbokJ0IbhK/attributes 
07:30:10.207 INFO  GET /api/notes/vWSbokJ0IbhK/attributes 
07:30:10.336 INFO  GET /api/notes/vWSbokJ0IbhK/revisions 
07:30:10.352 INFO  GET /api/similar-notes/vWSbokJ0IbhK 
07:30:10.719 INFO  GET /api/script/relation/vWSbokJ0IbhK/runOnNoteView 
07:30:10.819 INFO  POST /api/notes/vWSbokJ0IbhK/link-map 
07:30:11.746 INFO  PUT /api/options 
07:30:15.720 INFO  POST /api/recent-notes 
07:32:20.752 INFO  Created backup at /home/q/.local/share/trilium-data/backup/backup-weekly.db 
07:32:20.754 INFO  sync failed: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUTError: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUT
    at generateError (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:121:12)
    at ClientRequest.<anonymous> (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:47:47)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest._emitRequestEvent (/home/q/Downloads/trilium-linux-x64/resources/electron.asar/browser/api/net.js:114:28) 
07:32:20.758 INFO  Notes deleted: 0, not deleted 101 
07:32:20.760 INFO  Note revisions deleted: 0, not deleted 6 
07:32:20.762 INFO  Branches deleted: 0, not deleted 115 
07:32:20.775 INFO  Attributes deleted: 10, not deleted 173 
07:32:20.775 INFO  API tokens deleted: 0, not deleted 0 
07:32:20.793 INFO  All consistency checks passed (took 43ms) 
07:34:31.798 INFO  sync failed: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUTError: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUT
    at generateError (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:121:12)
    at ClientRequest.<anonymous> (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:47:47)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest._emitRequestEvent (/home/q/Downloads/trilium-linux-x64/resources/electron.asar/browser/api/net.js:114:28) 
07:36:42.888 INFO  sync failed: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUTError: Request to GET https://retreatai.com:8080/api/setup/status failed, error: Error: net::ERR_CONNECTION_TIMED_OUT
    at generateError (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:121:12)
    at ClientRequest.<anonymous> (/home/q/Downloads/trilium-linux-x64/resources/app.asar/src/services/request.js:47:47)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest._emitRequestEvent (/home/q/Downloads/trilium-linux-x64/resources/electron.asar/browser/api/net.js:114:28) 
07:36:42.889 INFO  Created backup at /home/q/.local/share/trilium-data/backup/backup-monthly.db

**Comment by quesada** [comment]
Tried:
/home/q/.local/share
q@q ~/.l/share> mv trilium-data/ hold-trilium  

Didn't help. It shows a popup saying it will create a new DB. I do. then there's a spot on the taskbar with the trilium icon, but no window anywhere.



 trilium &                                                                (base) 
q@q ~/.l/share> Generated session secret                                                 (base) 
Generated sourceId=DbrutZTxgoir
App HTTP server starting up at port 37840
{
  "appVersion": "0.40.3",
  "dbVersion": 157,
  "syncVersion": 14,
  "buildDate": "2020-02-09T10:48:23+01:00",
  "buildRevision": "88bd65c6798609a39206722305fab4f8d91d618b",
  "dataDirectory": "/home/q/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.

(trilium:22078): Gdk-WARNING **: 07:42:17.734: gdk_window_set_user_time called on non-toplevel

Creating initial database ...
One of the tagRootNote, doneRootNote or todoRootNote does not exist
One of the tagRootNote, doneRootNote or todoRootNote does not exist
One of the tagRootNote, doneRootNote or todoRootNote does not exist
One of the tagRootNote, doneRootNote or todoRootNote does not exist
One of the tagRootNote, doneRootNote or todoRootNote does not exist
Created 148 missing sync records for notes.
Created 148 missing sync records for note_contents.
Created 165 missing sync records for branches.
Created 422 missing sync records for attributes.
Created 5 missing sync records for options.
Schema and initial content generated.
Created missing option "noteRevisionSnapshotTimeInterval" with default value "600"
Created missing option "protectedSessionTimeout" with default value "600"
Created missing option "hoistedNoteId" with default value "root"
Created missing option "zoomFactor" with default value "1.0"
Created missing option "mainFontSize" with default value "100"
Created missing option "treeFontSize" with default value "100"
Created missing option "detailFontSize" with default value "110"
Created missing option "calendarWidget" with default value "{"enabled":true,"expanded":true,"position":20}"
Created missing option "editedNotesWidget" with default value "{"enabled":true,"expanded":true,"position":50}"
Created missing option "noteInfoWidget" with default value "{"enabled":true,"expanded":true,"position":100}"
Created missing option "attributesWidget" with default value "{"enabled":true,"expanded":true,"position":200}"
Created missing option "linkMapWidget" with default value "{"enabled":true,"expanded":true,"position":300}"
Created missing option "noteRevisionsWidget" with default value "{"enabled":true,"expanded":true,"position":400}"
Created missing option "whatLinksHereWidget" with default value "{"enabled":false,"expanded":true,"position":500}"
Created missing option "similarNotesWidget" with default value "{"enabled":true,"expanded":true,"position":600}"
Created missing option "spellCheckEnabled" with default value "true"
Created missing option "spellCheckLanguageCode" with default value "en-US"
Created missing option "imageMaxWidthHeight" with default value "1200"
Created missing option "imageJpegQuality" with default value "75"
Created missing option "autoFixConsistencyIssues" with default value "true"
Created missing option "codeNotesMimeTypes" with default value "["text/x-csrc","text/x-c++src","text/x-csharp","text/css","text/x-go","text/x-groovy","text/x-haskell","text/html","message/http","text/x-java","application/javascript;env=frontend","application/javascript;env=backend","application/json","text/x-kotlin","text/x-markdown","text/x-perl","text/x-php","text/x-python","text/x-ruby",null,"text/x-sql","text/x-swift","text/xml","text/x-yaml"]"
Created missing option "leftPaneWidth" with default value "25"
Created missing option "rightPaneWidth" with default value "25"
Created missing option "rightPaneVisible" with default value "true"
Created missing option "nativeTitleBarVisible" with default value "false"
Created missing option "eraseNotesAfterTimeInSeconds" with default value "604800"
Created missing option "keyboardShortcutsBackInNoteHistory" with default value "["Alt+Left"]"
Created missing option "keyboardShortcutsForwardInNoteHistory" with default value "["Alt+Right"]"
Created missing option "keyboardShortcutsJumpToNote" with default value "["Ctrl+J"]"
Created missing option "keyboardShortcutsScrollToActiveNote" with default value "["Ctrl+."]"
Created missing option "keyboardShortcutsSearchNotes" with default value "["Ctrl+S"]"
Created missing option "keyboardShortcutsSearchInSubtree" with default value "["Ctrl+Shift+S"]"
Created missing option "keyboardShortcutsCollapseTree" with default value "["Alt+C"]"
Created missing option "keyboardShortcutsCollapseSubtree" with default value "["Alt+-"]"
Created missing option "keyboardShortcutsActivateParentNote" with default value "["Backspace"]"
Created missing option "keyboardShortcutsSortChildNotes" with default value "["Alt+S"]"
Created missing option "keyboardShortcutsCreateNoteAfter" with default value "["Ctrl+O"]"
Created missing option "keyboardShortcutsCreateNoteInto" with default value "["Ctrl+P"]"
Created missing option "keyboardShortcutsCreateNoteIntoDayNote" with default value "["global:Ctrl+Alt+P"]"
Created missing option "keyboardShortcutsDeleteNotes" with default value "["Delete"]"
Created missing option "keyboardShortcutsMoveNoteUp" with default value "["Ctrl+Up"]"
Created missing option "keyboardShortcutsMoveNoteDown" with default value "["Ctrl+Down"]"
Created missing option "keyboardShortcutsMoveNoteUpInHierarchy" with default value "["Ctrl+Left"]"
Created missing option "keyboardShortcutsMoveNoteDownInHierarchy" with default value "["Ctrl+Right"]"
Created missing option "keyboardShortcutsEditNoteTitle" with default value "["Enter"]"
Created missing option "keyboardShortcutsEditBranchPrefix" with default value "["F2"]"
Created missing option "keyboardShortcutsCloneNotesTo" with default value "["Ctrl+Shift+C"]"
Created missing option "keyboardShortcutsMoveNotesTo" with default value "["Ctrl+Shift+X"]"
Created missing option "keyboardShortcutsCopyNotesToClipboard" with default value "["Ctrl+C"]"
Created missing option "keyboardShortcutsPasteNotesFromClipboard" with default value "["Ctrl+V"]"
Created missing option "keyboardShortcutsCutNotesToClipboard" with default value "["Ctrl+X"]"
Created missing option "keyboardShortcutsSelectAllNotesInParent" with default value "["Ctrl+A"]"
Created missing option "keyboardShortcutsAddNoteAboveToSelection" with default value "["Shift+Up"]"
Created missing option "keyboardShortcutsAddNoteBelowToSelection" with default value "["Shift+Down"]"
Created missing option "keyboardShortcutsOpenNewTab" with default value "["Ctrl+T"]"
Created missing option "keyboardShortcutsCloseActiveTab" with default value "["Ctrl+W"]"
Created missing option "keyboardShortcutsActivateNextTab" with default value "["Ctrl+Tab"]"
Created missing option "keyboardShortcutsActivatePreviousTab" with default value "["Ctrl+Shift+Tab"]"
Created missing option "keyboardShortcutsShowAttributes" with default value "["Alt+A"]"
Created missing option "keyboardShortcutsShowNoteInfo" with default value "[]"
Created missing option "keyboardShortcutsShowNoteSource" with default value "[]"
Created missing option "keyboardShortcutsShowLinkMap" with default value "[]"
Created missing option "keyboardShortcutsShowOptions" with default value "[]"
Created missing option "keyboardShortcutsShowNoteRevisions" with default value "[]"
Created missing option "keyboardShortcutsShowRecentChanges" with default value "[]"
Created missing option "keyboardShortcutsShowSQLConsole" with default value "["Alt+O"]"
Created missing option "keyboardShortcutsShowBackendLog" with default value "[]"
Created missing option "keyboardShortcutsShowHelp" with default value "["F1"]"
Created missing option "keyboardShortcutsAddLinkToText" with default value "["Ctrl+L"]"
Created missing option "keyboardShortcutsInsertDateTimeToText" with default value "["Alt+T"]"
Created missing option "keyboardShortcutsPasteMarkdownIntoText" with default value "[]"
Created missing option "keyboardShortcutsCutIntoNote" with default value "[]"
Created missing option "keyboardShortcutsPrintActiveNote" with default value "[]"
Created missing option "keyboardShortcutsRunActiveNote" with default value "["Ctrl+Enter"]"
Created missing option "keyboardShortcutsToggleNoteHoisting" with default value "["Alt+H"]"
Created missing option "keyboardShortcutsReloadFrontendApp" with default value "["F5","Ctrl+R"]"
Created missing option "keyboardShortcutsOpenDevTools" with default value "["Ctrl+Shift+I"]"
Created missing option "keyboardShortcutsFindInText" with default value "["Ctrl+F"]"
Created missing option "keyboardShortcutsToggleFullscreen" with default value "["F11"]"
Created missing option "keyboardShortcutsToggleZenMode" with default value "["Alt+M"]"
Created missing option "keyboardShortcutsZoomOut" with default value "["Ctrl+-"]"
Created missing option "keyboardShortcutsZoomIn" with default value "["Ctrl+="]"
Created missing option "keyboardShortcutsCopyWithoutFormatting" with default value "["Ctrl+Alt+C"]"
DB ready.
DB size: 1531 KB
Registered global shortcut Ctrl+Alt+P for action CreateNoteIntoDayNote
Note cache load took 87ms
Triggering sync.
Generated CSRF token qzk4VuCw-zwYkDBBaxZI0ivbPi-_hR0mNY5s with secret _csrf=beQdB6omzxNrZjynL4znE3No; Path=/
Generated sourceId=hPcRMsSWBdiQ
websocket client connected
Notes deleted: 0, not deleted 148
Note revisions deleted: 0, not deleted 0
Branches deleted: 0, not deleted 165
Attributes deleted: 0, not deleted 422
API tokens deleted: 0, not deleted 0
All consistency checks passed (took 56ms)

**Comment by quesada** [comment]
This is linux mint mate 19.1 in case it matters

**Comment by zadam** [comment]
Hello, this looks to me like some windows management issue - based on the log everything is going fine. So far if frontend crashes for some reason then the window is blank, but there is a window. Could the window be rendered on some different workspace or something?

**Comment by quesada** [comment]
Hmm, window manager is marco. There's no window at all. Update: found it by unplugging and plugging the monitor again. Strange.

**Comment by zadam** [comment]
If I understand this correctly, you managed to find the window after all so I'll close this.
