### ISSUE TITLE
Script API - Table

### ISSUE THREAD

**Issue by colingarbutt** [zadam/trilium#869]
Using Windows version 0.40.2.
I'm writing a script to fill in values in a table in the CKEditor.
All is fine except I have been defeated trying to align the text in a table cell left or right.
Should this be possible?
Colin Garbutt

**Comment by zadam** [comment]
Hello, advanced cell styling like text alignment is not possible as far as I know.

**Comment by colingarbutt** [comment]
Thanks for the reply.
I've gone with a monospace font so I can do it with spaces.

**Comment by zadam** [comment]
Actually I just checked CKEditor project and seems that support for [table styling has just been merged](https://github.com/ckeditor/ckeditor5/issues/3287) and will be in the next release.
