### ISSUE TITLE
Collapse/Expand Tree/Subtree

### ISSUE THREAD

**Issue by washere** [zadam/trilium#87]
We have **Collapse Subtree** option, as icon and Right-Mouse-Click Menu option. Can we have as in some tree outliners the other 3 options usually found too:

**Expand Subtree**
+
**Exapnd Tree** (whole tree, not just subtree)
**Collapse Tree**

Keyboard Shortcuts assigning for them can be added later, not the main thing.

I'll be making another thread on shortcuts.
+
Also a general Misc. ever-open thread for comments etc would be nice. 
I liked to post some ides on the Dark Mode issue (now closed), it is working well for me, thanks. 
I think a general comments thread (issue) would be good for users to interact and feedback etc.

Thanks for the great work.

**Comment by zadam** [comment]
Collapse tree already exists in the icons above the tree.

I'm not sure about global "expand tree" option. Trilium is geared towards quite large number of notes - I want it to scale to at least tens of thousands notes and triggering (even accidentally) such action on such large number of notes might kill the whole application. Expand sub-tree would be a bit safer here ...

For the general discussion/comments - I think for this github issues isn't the best place - I think gitter might be a better platform for that so I created an account for Trilium - https://gitter.im/trilium-notes/Lobby Feel free to join and comment.

Another option is to just add comment/reopen the issue about Dark mode.

**Comment by washere** [comment]
Yes I mentioned the collapse tree cion (& right-mouse click) in my first sentence.

On the second point I meant Expand Tree Branch only for the note we Right-Mouse-Click so it shows as an option like: "Collapse sub-tree   Alt+

So it expands only highllighted right-clicked note. This is quite normal on some tree apps.

Collapse sub-tree ICON, actually collapses all notes in tree currently, not just highlighted note or sub-tree. Right-mouse-click menu & Alt+- correctly collpases only the highlighted note.

I think the tree & sub-tree terminology has to be changed. We can either have Note & Sub-Note or Branch & Sub-Branch. Tree should mean the whole notes.

Lets say we call a root level note a Note/Branch and sub-parts of it Sub-Note/Branches. Then we can get 4 options for each note which is usual,

* Expand Note/Branch
* Collapse Note/Branch
* Expand Sub-Note/Sub-Branch
* Collapse Sub-Note/Sub-Branch 

> These come up in the menu when right-mouse clicking a note or sub-note
> The last two only expand/collapse the sub-note (or sub-branch) which is right-mouse-clicked

Just some ideas.

Finally thanks for the forum in gitter. Please post a link to it on homepage at the bottom so users see it. I'll try to post some stuff there during next week.

Thanks for the superb work. I think Trilium, with it's server features, will be huge.

Have a good week.

**Comment by zadam** [comment]
I'm doing currently some refactoring of internal structures and will rename tree to branches.

New terminology should be a bit more consistent:

Tree and branches are terms relating mostly to the left pane where:
* tree refers exclusively to the whole tree structure
* branch is what was previously called sub-tree or children etc.

Note is then what's in the right pane (content mainly). This division reflects internal data structures quite well.

I'm afraid I won't be able to avoid the ambiguity entirely - e.g. on the right click there's "Insert child note" and I can't really rephrase it with "branch" without sounding weird.

**Comment by popey456963** [comment]
Closing as this seems to be implemented in the latest version.
