### ISSUE TITLE
When the file is in GIF format, can it not be compressed? Otherwise you won't be able to display GIF images properly

### ISSUE THREAD

**Issue by chncho** [zadam/trilium#870]
When the file is in GIF format, can it not be compressed? Otherwise you won't be able to display GIF images properly.

**Comment by zadam** [comment]
GIFs are recompressed as JPEGs if they cross certain size limit (IIRC 200 KB but not sure). Currently this is not configurable.

**Comment by chncho** [comment]
Thanks a lot. Are there any plan to improve it?

**Comment by zadam** [comment]
Yes, I'll put this into backlog, but no promises since I have some more pressing issues...

**Comment by chncho** [comment]
Thanks very much, and I will have a try to read the code and contribute together.

**Comment by zadam** [comment]
This has been working for some time already - Trilium detects if the image is animated, in that case it is not recompressed.
