### ISSUE TITLE
Book scales images wrong

### ISSUE THREAD

**Issue by Karol-G** [zadam/trilium#871]
App version: 0.40.3
OS: Windows 10

Hi,

when I insert an image in a note and view the parent note as book with the trillium window maximized everything is fine.
But as soon as I resize the Trillium window (for example half size) the image is being cut off.

Example:

![grafik](https://user-images.githubusercontent.com/3471895/74562430-19226180-4f6b-11ea-86a8-3743731c14f9.png)

![grafik](https://user-images.githubusercontent.com/3471895/74562506-45d67900-4f6b-11ea-8a67-5d3a5c9be71e.png)

The text is wrapped correctly, but images are simply cut off. I don't know if this behavior is intended or not. But I would have expected the images to simply become smaller.

Best,
Karol

**Comment by zadam** [comment]
Hello, this should now be fixed and will be released in the next version.
