### ISSUE TITLE
api.createNote() - only text or code possible.

### ISSUE THREAD

**Issue by KuroSaru** [zadam/trilium#873]
So TLDR: the createNote backend API completely ignores the extra option for type.

source: https://zadam.github.io/trilium/backend_api/services_backend_script_api.js.html#line240

it will only create a type of code if parent note type is code, else regardless of paramter passed note will be of type text.

**Comment by zadam** [comment]
hello, please use `createNewNote()` API function which has more options.

`createNote()` is old API and is deprecated (although now I can see it's not marked as such)

**Comment by KuroSaru** [comment]
Awesome, swapped over. will avoid this API going foward.
