### ISSUE TITLE
Protected notes cannot be found in search

### ISSUE THREAD

**Issue by Piggeldi2013** [zadam/trilium#876]
**Version:** 0.40.3

**Description:**
I have a journal with a lot of notes protected.
I found out that search isn't possible for protected notes, even when I enter the protected session.
Maybe this behaviour is intended - but is, afaik, even not described in the Wiki.

**How to reproduce:**
I tried to reproduce the behaviour on a new empty document.
Created a note and a child note, protected it and executed a search - no results found.
Unprotected the notes - note can be found in search again.

**Expected:**
As there is a protected session, search should also consider protected notes.

**Comment by Heniker** [comment]
It is intended and described in wiki. Please check this - https://github.com/zadam/trilium/wiki/Search.
> full text search - search in text and code note content. Since this is implemented as a database search, this works only for not protected notes (doesn't matter if you're in protected session or not)

**Comment by Piggeldi2013** [comment]
Thanks for answering.

A hint at the protected notes section would, from my point of view, make sense then.
I didn't search for the search in the wiki.

Closing here then.

Thanks,
Carsten

**Comment by zadam** [comment]
Hello, I updated the wiki page on protected session since it does make sense to mention that.

BTW as a limited work around you can use Jump-To dialog (by default `CTRL-J`) which uses an in-memory search of titles only and will find protected notes if the protected session is active.

**Comment by Piggeldi2013** [comment]
Wow - thanks for the update - appreciate that!

My use case would need to search for the note content also - but I understand why this isn't possible.

Thanks for the hint and keep up the very very nice work!

Thanks,
Carsten
