### ISSUE TITLE
Error Message in Logfile

### ISSUE THREAD

**Issue by hdbeims** [zadam/trilium#877]
version 0.40.3 / macos

After first time usage (server version / node 10) I found an error message in the logfile.
[trilium-2020-02-23.log](https://github.com/zadam/trilium/files/4241004/trilium-2020-02-23.log)

**Comment by zadam** [comment]
Hello, thank you for reporting this issue. Unfortunately it's not really clear where exactly is this coming from (or rather for which request). Do you observe any problem from the user side?

**Comment by hdbeims** [comment]
I observed no problem using the client.
