### ISSUE TITLE
Mobile view not loading note content: missing loadIncludedNote definition in mobile.js

### ISSUE THREAD

**Issue by cbop-dev** [zadam/trilium#878]
Using latest server (zipped) package (version v.0.40.3) on Ubuntu 18.04, if and only if I view the _mobile_ version (both on a phone and via desktop web browser with `?mobile` flag), I repeatedly am unable to view/load notes when I click on a note node from the tree. The first note I click on after loading the page _sometimes_ loads but any subsequent note does not load, but leaves the same content from the first note in the view pane. The debugger shows the following error:

    Error: glob.loadIncludedNote is not a function

This occurs only in the mobile view; I never see the problem in the desktop view of the server web-app. So I then noticed that this function is defined only in `desktop.js`, line 46, but is not in `mobile.js`which is probably what is loaded in mobile view. And so I tried inserting lines 46-57 from `desktop.js` to line 13 of `mobile.js`, which then required adding two additional `import` statements into `mobile.js`:

    import linkService from './services/link.js';
    import noteContentRenderer from "./services/note_content_renderer.js";

When I did this, and restarted the server and reload the site--_voilà_--the problem seems to go away. I can click on and view any note.

BTW, when the problem occurs, the server log shows no errors: 
<details><summary>[Click for log file clip]:</summary>
  
    09:45:59.295 INFO  App HTTPS server starting up at port 8080 
    09:45:59.296 INFO  {
      "appVersion": "0.40.3",
      "dbVersion": 157,
      "syncVersion": 14,
      "buildDate": "2020-02-09T10:48:23+01:00",
      "buildRevision": "88bd65c6798609a39206722305fab4f8d91d618b",
      "dataDirectory": "/home/<user>/trilium-data",
      "clipperProtocolVersion": "1.0"
    } 
    09:45:59.306 INFO  DB ready. 
    09:45:59.311 INFO  DB size: 5828 KB 
    09:46:04.496 INFO  GET /login?mobile 
    09:46:11.171 INFO  GET /login?mobile 
    09:46:17.115 INFO  POST /login 
    09:46:17.318 INFO  GET / 
    09:46:17.323 INFO  Generated CSRF token ... with secret undefined 
    09:46:17.324 INFO  Generated sourceId=.... 
    09:46:19.308 INFO  Notes deleted: 6, not deleted 447 
    09:46:19.308 INFO  Note revisions deleted: 0, not deleted 26 
    09:46:19.309 INFO  Branches deleted: 8, not deleted 461 
    09:46:19.310 INFO  Attributes deleted: 24, not deleted 374 
    09:46:19.311 INFO  API tokens deleted: 0, not deleted 0 
    09:46:19.335 INFO  All consistency checks passed (took 27ms) 
    09:46:19.634 INFO  GET /api/keyboard-actions 
    09:46:20.130 INFO  GET /api/keyboard-shortcuts-for-notes 
    09:46:20.430 INFO  GET /api/options 
    09:46:20.434 INFO  GET /api/tree 
    09:46:21.136 INFO  GET /api/setup/status 
    09:46:21.192 INFO  POST /api/login/sync 
    09:46:21.253 INFO  GET /api/sync/changed?lastSyncId=3641 
    09:46:21.260 INFO  GET /api/notes/LSlnflHCZTMA 
    09:46:21.369 INFO  GET /api/sync/changed?lastSyncId=3642 
    09:46:21.434 INFO  POST /api/sync/finished 
    09:46:21.467 INFO  GET /api/sync/check 
    09:46:21.484 INFO  Content hash computation took 14ms 
    09:46:21.530 INFO  GET /api/script/startup 
    09:46:21.777 INFO  POST /api/tree/load 
    09:46:22.476 INFO  POST /api/tree/load 
    09:46:22.858 INFO  POST /api/tree/load 
    09:46:23.690 INFO  GET /api/notes/LSlnflHCZTMA/attributes 
    09:46:24.080 INFO  GET /api/script/relation/LSlnflHCZTMA/runOnNoteView 
    09:46:24.929 INFO  PUT /api/options 
    09:46:28.911 INFO  POST /api/recent-notes 
    09:46:35.329 INFO  GET /api/notes/8B6tkmW425TH 
    09:46:35.568 INFO  GET /api/notes/8B6tkmW425TH/attributes 

</details>

Thus, mobile code is calling a function (`loadIncludedNote`) which is not defined in `mobile.js`. And this problem is not unique to version 0.40.3; I get the same error with version 0.40.2. 

My `mobile.js.patch` code is below (NB: I updated the diff output below; I had done it backwards in my first edit):

<details ><summary>[mobile.js.patch]</summary>

```
--- src/public/javascripts/mobile.js.bak	2020-02-24 10:19:18.715809250 +0000
+++ src/public/javascripts/mobile.js	2020-02-24 10:33:14.387312508 +0000
@@ -7,9 +7,24 @@
 import treeChangesService from "./services/branches.js";
 import utils from "./services/utils.js";
 import treeUtils from "./services/tree_utils.js";
+import linkService from './services/link.js';
+import noteContentRenderer from "./services/note_content_renderer.js";
 
 window.glob.isDesktop = utils.isDesktop;
 window.glob.isMobile = utils.isMobile;
+window.glob.loadIncludedNote = async (noteId, el) => {
+    const note = await treeCache.getNote(noteId);
+
+    if (note) {
+        $(el).empty().append($("<h3>").append(await linkService.createNoteLink(note.noteId, {
+            showTooltip: false
+        })));
+
+        const {renderedContent} = await noteContentRenderer.getRenderedContent(note);
+
+        $(el).append(renderedContent);
+    }
+};
 
 const $leftPane = $("#left-pane");
 const $tree = $("#tree");

```
</details>

Can a developer check this and, if it does not break anything, patch the current code so that the mobile view works correctly in a subsequent release? Thanks.

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, it has been fixed and will be released in the next patch release soon.
