### ISSUE TITLE
Book view does not apply css classes

### ISSUE THREAD

**Issue by cbop-dev** [zadam/trilium#879]
The book view feature does not (as of v.0.40.3) seem to apply cssClass labels to the child nodes it inserts into a parent/Book view. Thus, any css styling (including templates) using the attributes (`cssClass`) of a book-node's children does not show up when viewing the Book node. This can be fixed with [these small changes to node_detail_book.js](https://github.com/cbop-dev/trilium/commit/15ef9dbce23e1601598c47333196c72d8fad3f08).

Please consider incorporating such a change so that the book view is even better. (I use notes with various ancient languages for which alternative fonts are important, but without css applied to children the book view is not so useful.)

**Comment by zadam** [comment]
Hello, yes, using cssClass makes sense in book as well. This is now fixed and will be released soon.
