### ISSUE TITLE
Assignable Shortcuts

### ISSUE THREAD

**Issue by washere** [zadam/trilium#88]
Would be nice to have programmable keyboard shortcuts like NoteCase Pro, so the user can change keyboard shortcuts for various commands, options etc.

But as a long term aim, well after Beta, maybe in version 2.x. As there are a lot more immediate work as outlined in issues by dev himself.

Thanks for everything.

**Comment by zadam** [comment]
Yeah, this is planned, but as you say it's not highest priority now.

**Comment by washere** [comment]
Nice, can keep this alive as a reminder in a couple of years at bottom of issues :)

**Comment by zadam** [comment]
keyboard shortcuts have been added in 0.38
