### ISSUE TITLE
Web version failing as a sync client. 

### ISSUE THREAD

**Issue by mursilsayed** [zadam/trilium#881]
I am using server instance running(Ubuntu 18) as a synchronization server for my desktop application(Kubuntu 18). Sync server is behind nginx proxy and using lets encrypt ssl certificate. This setup works perfectly for me. 

As per your release notes for `0.40.4`, you can now setup web version as a sync client. I was curious to test this functionality and I started a docker container of the application(using a seperate data directory) on my workstation and tried synchronizing it with the server that is already working for the desktop application. I am getting the following error. 

Sync setup failed: Request to get https://trilium.myservername.com/api/setup/sync-seed failed, error: Error: unable to verify the first certificate

**Comment by mursilsayed** [comment]
I was able to solve this issue. It turned out that I was not using the full chain certificate in nginx and the web version requires it.

**Comment by zadam** [comment]
Glad to hear you managed to solve the issue. Closing.
