### ISSUE TITLE
CSS Bug: `Relation Map` notes height limited to 500px

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#882]
I just noticed that relation map height is limited to 490 px (tried using a default theme in case my theme was causing this).

From what i saw with developper tools, the parent `note-detail-component-wrapper` has `min-height: 500px;`, and for some reason the `relation-map-wrapper` element does not expand beyond this.

I'm using trilium v0.40.4, but the bug might be older

**Comment by zadam** [comment]
hello, thanks for reporting this, bug has been fixed. I suspect that it has been there since 0.39 which contained some layout changes, but it's weird I did not notice it yet ...
