### ISSUE TITLE
Bulk edit notes

### ISSUE THREAD

**Issue by sharifkhalladi** [zadam/trilium#883]
It would be useful to be able to bulk edit notes, for example to add a Label attribute or apply a template through a Relation attribute.

**Comment by zadam** [comment]
Hmm, what would be the flow for this?

One thing I can think of is to use search to select the notes and then e.g. add the attribute. But this would work well for attributes only, any other use case for bulk editing?

**Comment by sharifkhalladi** [comment]
Yes, the use case I had in mind here would be for attributes specifically. In fact, this suggestion stems from my other feature request to [exclude notes from the link map](https://github.com/zadam/trilium/issues/885) through a label based solution.

**Comment by mursilsayed** [comment]
Search and replace text in notes will be a useful functionality.

**Comment by meichthys** [comment]
@mursilsayed see #679 - It's difficult to implement.

**Comment by zadam** [comment]
Since 0.53 there's "Bulk actions": 
![image](https://user-images.githubusercontent.com/617641/182669622-bd3ea5da-2924-43b6-aad8-cde1f1c95683.png)
