### ISSUE TITLE
Exclude notes from Link Map

### ISSUE THREAD

**Issue by sharifkhalladi** [zadam/trilium#885]
It would be useful to have the ability to hide notes from the Link Map.

An example use case would be for notes that are merely used as a template, i.e. when creating a "Person" template and setting it as a "template" Relation attribute, this shows up in the Link Map which is then extended to all other notes that use this template - even though there may be no other relationship between these notes (and thus cluttering the link map).  

Another example use case would be for clipped articles that have a large number of embedded images - these all show up on the link map making it a lot harder to navigate.

A proposed solution would be the ability to hide notes through a filter on the Link Map view (i.e. hide images) or by adding an attribute on the notes that you'd like to hide, similar to how the `archived` label hides notes from the autocomplete-based search.

**Comment by zadam** [comment]
Hello, I agree this would make sense. Especially the use case with clipped page and a lot of images. I would prefer label based solution (as you mentioned similar to `archived`), but I'm not sure how practical this would be in the case of e.g. this clipped page - you would have to add this label to all such images (or template). Using inherited attribute would be only a partial solution ...

**Comment by lerone-b** [comment]
+ strong plus one!

for me the 'link map' (relation graph) is one of the 3 to 5 real critical aspects that set Trilium apart + make it so useful.
I also notice by now, that the clutter-effects that @sharifkhalladi describes spot-on are really 'eating up' the potential huge benefits of the 'link map' (esp in scenarios where template + image use is big part of the routine)

**Comment by zadam** [comment]
This was added few months ago in the form of `#excludeFromNoteMap` label.
