### ISSUE TITLE
Synching to a server over SSL is not working

### ISSUE THREAD

**Issue by gramster** [zadam/trilium#887]
I have SSL certs from let's encrypt. There is actually three files: cert.pem, chain.pem, and key.pem. 

If I configure Trilium server to just use cert.pem and key.pem, I can connect to the server fine over HTTPS in a browser and the certificate checks out. But if I try to connect/sync a client instance of Trilium to that server, I get:

```
Trace: ERROR: Sync failed: Request to get https://geekraver.synology.me:8443/api/setup/sync-seed failed, error: Error: unable to verify the first certificate
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at Object.setupSyncFromSyncServer (/usr/src/app/src/services/setup.js:96:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

which suggests to me it is because the chain is incomplete (although it's odd that Chrome has no issue with the cert).

If, on the other hand, I append the chain.pem file to cert.pem, I can't open the server from a browser, and I get:

```
Sync setup failed: Request to get https://<myhost>:443/api/setup/sync-seed failed, error: Error: Client network socket disconnected before secure TLS connection was established
```

Any ideas of how to get around this?

**Comment by zadam** [comment]
Most people setup Trilium behind reverse proxy which handles the TLS termination so you might try that: https://github.com/zadam/trilium/wiki/Server-installation#reverse-proxy-setup

**Comment by gramster** [comment]
I'll give that a try this weekend and report back.

**Comment by gramster** [comment]
I set up the reverse proxy. Again, I can connect fine through Chrome to the server instance. On the local instance, I now see in the browser:

```
Sync has been correctly set up. It will take some time for the initial sync to finish. Once it's done, you'll be redirected to the login page
```

however, the logs on the command line show:

```
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
Getting document options from sync server.
Creating database for sync
Schema and not synced options generated.
Triggering sync.
No connection to sync server.
```

and nothing happens.

**Comment by gramster** [comment]
This may have something to do with the enterprise VPN software I have to use. If I disable that and connect via my phone hotspot it looks like it works.

I'm hoping that occasional syncs will be enough to get by and this will unblock me.

**Comment by zadam** [comment]
Trilium supports proxy however the problem with corporate proxies is that they are usually authenticated through NTLM. You can try e.g. [px](https://github.com/genotrance/px) proxy which manages the proxy auth part and then you just configure Trilium to use unauthenticated proxy `localhost:3128` exposed by the proxy.
