### ISSUE TITLE
Order of 'insert row <position>' opposite of what it should be?

### ISSUE THREAD

**Issue by tylwright** [zadam/trilium#888]
Not sure if this is an improvement for Trilium or the WYSIWYG editor.  Forgive me if it is not related to Trilium itself.

Does anyone get confused with the order of the 'insert row  above/below' menu items?  I always click on the bottom choice thinking that it's 'insert row below' but it's the opposite.  Seems like 'insert row below' should be on the bottom of the list and 'insert row above' should be on the top of the list.

![trilium-order](https://user-images.githubusercontent.com/4140387/75599535-c9b45900-5a73-11ea-987d-93316fe1899a.PNG)

**Comment by zadam** [comment]
I guess this might be because "insert row below" is just more frequently used and thus is the first item ... But you're right in that it's not really a Trilium thing, but more of a [CKEditor](https://github.com/ckeditor/ckeditor5).

**Comment by tylwright** [comment]
Thanks for confirming, @zadam!  Due to that, closing.
