### ISSUE TITLE
Wiki Docker server installation can lead to security problems

### ISSUE THREAD

**Issue by Koseng** [zadam/trilium#889]
First of all thank you for your great software, I love it.

Please change the Docker Run Image command in your wiki documentation to:

sudo docker run -t -i **-p 127.0.0.1:8080:8080** -v ~/trilium-data:/root/trilium-data zadam/trilium:latest

Docker adds its own rules to the linux iptables firewall. -p 8080:8080 exposes port 8080 directly to the internet. The whole reverse proxy setup is then useless. Trilium can be directly accessed via myIpAddress:8080. 

Even if other firewall configuration packages like UFW are used and port 8080 is blocked via UFW configuration, it is still accessible because the docker iptables entry has priority.

=> using the -p command in docker without 127.0.0.1 leads to a lot of security problems on many systems and is one reason for accidentally exposed data in the internet.

**Comment by zadam** [comment]
Hello, thanks for info, I was not aware. I updated the [docker wiki page](https://github.com/zadam/trilium/wiki/Docker-server-installation).
