### ISSUE TITLE
Resize Tree Pane

### ISSUE THREAD

**Issue by washere** [zadam/trilium#89]
Would be nice to have standard resize option for left pane: Tree outline window pane.

As it is usual for this genre of software.

So when hovering on the border between the 2 window panes, resize becomes available by dragging left or right. 

So if Tree node names are short in the left window pane, can drag the border left and make it smaller and give more space to the data pane on the right.

Thanks for everything.

**Comment by zadam** [comment]
Currently the tree pane is set to be 2/7 width of the whole window. If we want to have it resizable then I think the good solution would be to also use relative width instead of setting the width to some absolute pixel value.

This ratio should then be persisted (and synced).

Some resources how to do this:
* https://stackoverflow.com/questions/46931103/making-a-dragbar-to-resize-divs-inside-css-grids
* https://developer.mozilla.org/en-US/docs/Web/CSS/resize

**Comment by washere** [comment]
Good links, thanks. The more I think about it, it seems this is really a needed feature as notes are added, specially on laptops.

**Comment by washere** [comment]
I hope this gets done in Final Release of 0.13. It will look professional like other Tree Outliner editors.

Also saves quite abit of screen acrage.

**Comment by zadam** [comment]
Unfortunately I don't see it happening for a while since it's not easy in web platform and IMHO not that critical right now.

But if you just want to make the left pane smaller permanently it should be possible to just redefine that 2/7 ratio in custom CSS.

**Comment by washere** [comment]
Thanks for the reply zadam.

It is not just setting it to a set size. 

Resizing the tree pane column is an ongoing feature usage by regular Outliner Tree users.

As node names change in length, new sub nodes or deeper level nodes created etc.

Basically it is critical to use maximum screen acreage. Many outliner users use this genre on laptops at home or on the go. The resizing hence is critical for them. Often the tree outliner apps are not used at home on large monitors or dual monitors.

As a result I do not see myself using it anymore until addressed. It is a decision based on time and data investment.

Thanks for the great work. 

Good luck and best wishes.

**Comment by zadam** [comment]
fixed in #176
