### ISSUE TITLE
CKEditor 5 v17.0.0 is now available; need to update what is packaged with Trilium

### ISSUE THREAD

**Issue by tylwright** [zadam/trilium#890]
CKEditor 5 v17.0.0 is now available.  We should merge it in.

Release notes and assets can be found here: https://github.com/ckeditor/ckeditor5/releases/tag/v17.0.0

**Comment by leoossa** [comment]
Moreover - those features added could be useful in 
https://github.com/zadam/trilium/issues/822 
(still - tables, API for tables and databases are really **a thing** to have)

**Comment by zadam** [comment]
ckeditor 17 has already been added to m41 branch which will be later released as 0.41.
