### ISSUE TITLE
Cant get data directory path to change

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#891]
I followed the instructions in the wiki and set the environment variable, but when I try to start Trilium server, it still lists my old one. Did I misunderstand something?

```
:~$ export TRILIUM_DATA_DIR=/home/james-admin/trilium-data
:~$ echo $TRILIUM_DATA_DIR 
/home/james-admin/trilium-data
:~$ sudo docker run -t -i -p 127.0.0.1:8080:8080 -v ~/trilium-data:/home/james-admin/trilium-data zadam/trilium:latest
Generated session secret
Generated sourceId=njVM0YDENlue
App HTTP server starting up at port 8080
{
  "appVersion": "0.40.4",
  "dbVersion": 157,
  "syncVersion": 14,
  "buildDate": "2020-02-24T22:59:22+01:00",
  "buildRevision": "fb55cdaea6b1367129e11118b8b6fd2eadebad5f",
  "dataDirectory": "/root/trilium-data",
  "clipperProtocolVersion": "1.0"
}
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
```

**Comment by zadam** [comment]
Hello, you first export statement does nothing since you then use docker and environment variables don't propagate to the docker containers.

But otherwise it seems to do what you want - inside docker it uses /root/trilium-data which is mapped to the /home/james-admin/trilium-data in the host system.

**Comment by jbhanks** [comment]
Ah ok, I'm new to Docker. So just to be clear, I should get a trilium-data directory in `james-admin` and not in `/root` if I start it for the first time with this command?:
```sudo docker run -t -i -p 127.0.0.1:8080:8080 -v ~/trilium-data:/home/james-admin/trilium-data zadam/trilium:latest```


It would be cool if the wiki explained the special considerations when setting up the Docker with TLS. It seems my problem has something to do with that and I incorrectly thought it wasn't working because it was using the wrong config.ini. How that all works isn't necessarily obvious to people who havent done it before. If I can't figure it out, I'll start another thread .
