### ISSUE TITLE
[Feature request] Permanent Link maps

### ISSUE THREAD

**Issue by pihentagy** [zadam/trilium#894]
Can we have a Link map **sidebar**? So it won't be a "modal dialog", but a constant sidebar on the right to aid navigation.

**Comment by zadam** [comment]
Hello, there is a small (and simplified) link map in the sidebar as visible in the screenshot:

![image](https://user-images.githubusercontent.com/617641/75867612-28c4f580-5e07-11ea-8f50-0d73726d7942.png)

Do you mean something different?

**Comment by pihentagy** [comment]
No, that's all I missed, thanks, just missed the sidebar (it's not in the menu).
