### ISSUE TITLE
Font/Font background color

### ISSUE THREAD

**Issue by tvortsa** [zadam/trilium#895]
ver. 0.40.3

Dark theme

When i do copy text from almost any web pages, and then paste text into Trilium, text have same backround color and are invisible (

![trilium_issue](https://user-images.githubusercontent.com/78345/75805640-40629680-5d93-11ea-8437-1683efaab759.gif)

Anytime i need manualy select this pasted text and do "remove color" (((

If is here some shortcut for quick do "remove text color" and "remove background text color" ? 

Or option for dont copy any color maybe?

Thank you!

**Comment by zadam** [comment]
You can use `CTRL-SHIFT-V` to paste without formatting.

**Comment by tvortsa** [comment]
Yeahhh! Thank you!
