### ISSUE TITLE
Present saved search as a book type node

### ISSUE THREAD

**Issue by pihentagy** [zadam/trilium#897]
If I have small notes (or even large notes), it would be nice if I can see the search results expanded as if it was a book type node with the search results as a children.
Can I achieve this?

**Comment by zadam** [comment]
Hello, this is not possible right now, but yes, it is planned to support list/book view of the search results, so adding to the backlog.

**Comment by pihentagy** [comment]
Thanks, cannot wait to see it in action. 👍

zadam <notifications@github.com> ezt írta (időpont: 2020. márc. 4., Sze
19:42):

**Comment by nil0x42** [comment]
Humm, looks like this feature is already present on v0.46.*-beta @zadam , di you forgot to mark this issue as `done` on backlog ?

**Comment by zadam** [comment]
Yep, closing.
