### ISSUE TITLE
trilium + magnet (macOS)

### ISSUE THREAD

**Issue by rax-rstark** [zadam/trilium#898]
Hello,

I use a program on macOS called (Magnet)[https://magnet.crowdcafe.com/], which provides handy keyboard shortcuts for resizing windows. Trillium + magnet have worked well since I began using Trilium (2019/01) with no noticeable difference between it and any other macOS applcation until I upgraded trillium to the most recent release today, 0.40.4 from 0.36.5. Now magnet menu options for only trillium are severely limited and basically non-functional.

Example magnet menu for Firefox:
<img width="238" alt="Screen Shot 2020-03-05 at 5 20 52 PM" src="https://user-images.githubusercontent.com/13769625/76034880-b981fb00-5f05-11ea-952c-ba8746936c41.png">

Notice how all the window size/position options are not greyed out.

When I use the same menu widget with the latest Trillium, i get:
<img width="234" alt="Screen Shot 2020-03-05 at 5 21 04 PM" src="https://user-images.githubusercontent.com/13769625/76034897-c1da3600-5f05-11ea-8729-5c46237f506c.png">

Note only the 'Previous Display', and 'Center' options work for Trillium 0.40.4, all other options are greyed out and non-functional. :(

Going to do some additional research on my end but figured I would report here. Loving trillium, loving magnet. Not being able to resize/reposition via keyboard shortcut is a major bummer to my workflows.

Thanks for any insight or review you may be able to provide!

**Comment by rax-rstark** [comment]
From Magnet FAQ - https://magnet.crowdcafe.com/faq.html :

> Why is my window not resizing?
> 
> Magnet can handle all standard resizable windows in OS X for you. Magnet can not do anything with non-standard windows used by some developers. Fortunately, such windows are quite rare. Adobe Creative Suite & Creative Cloud apps older than 2017 version is not supported exactly for this reason.

**Comment by zadam** [comment]
Since 0.39 Trilium does not use native title bar by default which seems like a potential candidate for this problem. You can go to Options -> Appearance and re-enable native title bar (restart needed) and perhaps that might fix the problem?

**Comment by rax-rstark** [comment]
Hello!

Thanks for your prompt response. I can confirm that changing the option to re-enable the title bar does in fact resolve this issue.

\o/
