### ISSUE TITLE
can not open in safari

### ISSUE THREAD

**Issue by iyjian** [zadam/trilium#904]
For bug reports, please mention **version of the application** and include **log files** from following location:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

after I run `npm run start-server ` and registered as a new user, I found the follow error in safari console.

![image](https://user-images.githubusercontent.com/466985/76212235-fe2dcf00-6242-11ea-9bf5-a5195136b92c.png)

and I found the javascript file, It seems that safari do not have window.addEventEvent method. I am not sure is it a bug.

https://github.com/zadam/trilium/blob/master/src/public/javascripts/widgets/tab_row.js#L290

**Comment by zadam** [comment]
Hello, thanks for reporting this issue, this looks like a bug introduced after refactoring, I will fix that.

BTW, it looks like you are using master branch which is not yet completely stable. You might want to use `stable` branch instead.

**Comment by iyjian** [comment]
many thanks. I appreciate your opensource project! I like it!!!!!

**Comment by iyjian** [comment]
btw, I am using safari, and there is no scroll bar on the left panel, I am trying to figure it out.


![image](https://user-images.githubusercontent.com/466985/76220354-4bfe0380-6252-11ea-97eb-311abb8f3056.png)

**Comment by iyjian** [comment]
![image](https://user-images.githubusercontent.com/466985/76221577-43a6c800-6254-11ea-8f6d-1cffddfc1905.png)

It seems that, it is a css bug of fancytree, I'll investigate it.

**Comment by iyjian** [comment]
could you tell me how do you generate the jquery.fancytree-all-deps.js file?

**Comment by iyjian** [comment]
could you let me know how do you generate the jquery.fancytree-all-deps.js? I use fancytree js as standalone but the scroll is ok in safari, I am going to do more investigate on the issue.

**Comment by zadam** [comment]
The missing scrollbar is probably not caused by the fancytree itself, but by the surrounding layout.

**Comment by zadam** [comment]
Also one note - Safari is generally not well supported (since it's available only on Mac, I can't use it to test) so you might encounter various issues. I will fix bugs as far as I can (which is not much with my inability to test), but generally I would recommend using Chrome or Firefox instead.

**Comment by iyjian** [comment]
it is absolutely ok.
