### ISSUE TITLE
[Feature Request] Update the text for the link to a note if the linked note title changes

### ISSUE THREAD

**Issue by danielpferreira** [zadam/trilium#905]
Currently, by typing @ you get a dropdown that filters down through the notes as you type, then adds a link to that note using its title as text.

However, if you change the title of the linked note, this isn't reflected in the link text (ie. the text for the link is static).

Are there plans to implement this? (It seems doable, as it seems to be very similar to what happens when using Include Note. The difference is that instead of including the full note within a box, in a new block, you'd include only the note title, inline with the text.)

This would be very practical for recurring terms that need to be kept consistent (such as a character name for worldbuilding, for example). If at any point it needs to be changed, all instances would reflect that.

**Comment by zadam** [comment]
Hello, currently the note links are standard HTML hyper text links which separate the target URL and the label of the link. Thus, when a target note is renamed, the link label is not updated.

But when I think about this, I agree that it would be a useful features when this would be in sync, actually I would go as far as to claim that in most cases you want to keep the link label and note title in sync and only in special cases you want to keep this separation and flexibility to label the link with whatever you want.

As you mention, this could be implemented similarly as include note, this time with an [inline widget](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#demo).

I'm adding this to the backlog.

**Comment by zadam** [comment]
This was implemented in master and will be released in 0.41.
