### ISSUE TITLE
copying text with formatting 

### ISSUE THREAD

**Issue by stolzoffd9** [zadam/trilium#91]
It loses the text formatting of the webpage in text type i.e. spacings, tabs and new line.

**Comment by zadam** [comment]
Yes, this is a known issue with the CKEditor 5 which is used as editing component. There's a new release coming soon, hopefully it will be fixed.

**Comment by stolzoffd9** [comment]
excellent work though. Needed a sublime/Keep note kind of environment with image integration. Need a good Keepnote replacement.

**Comment by stolzoffd9** [comment]
and if you can integrate Notes plugin in sublime.
https://packagecontrol.io/packages/Notes
