### ISSUE TITLE
Bug?: After closing app, many instances stay open and need to be closed before relaunch is possible.

### ISSUE THREAD

**Issue by danielpferreira** [zadam/trilium#912]
After I close the app, I can't relaunch it without killing some processes in Task Manager first.

In Task Manager:
While app is running, I see Trilium Notes under Apps.
Once I close the app, I see many instances of Trilium persist under Background Processes (they're never actually taking up any resources - CPU, Memory etc are all 0).
Every time I try to launch the app again, it doesn't work, and a new instance appears (under Background Processes).
I have to kill at least some of these in order for launch to work again.

Is this a bug or might I be doing something wrong?

**Comment by leoossa** [comment]
Same for me, it's not crucial for me - I just kill it, but you're right - it definitely needs fixing

**Comment by zadam** [comment]
This is a platform bug, this was already reported in e.g. #778. 

(unreleased) v0.41 upgrades Electron to version 9 which I hope will fix this issue.

**Comment by danielpferreira** [comment]
Thanks! Sorry, I should have searched before posting!

(Do I close this issue myself or do you?)
