### ISSUE TITLE
sync/backup the document.db without using the built-in sync?

### ISSUE THREAD

**Issue by jchalifour** [zadam/trilium#913]
I use a cloud backup service to backup (and synchronize) files between a few computers (e.g. office and home). I'm wondering if it would be a bad thing to use this service to synchronize the Trilium document.db so that I can access the same content on multiple computers without setting up a Trilium server sync? I use these computers one at a time, I wouldn't be changing things on them at the same time. 

I tried it briefly and it seemed ok but I'm not sure if there's something I'm not thinking of which will make this a big problem down the road. 

Thank you.

**Comment by zadam** [comment]
Sync using generic cloud backup service can be fine as long as there's never a sync conflict. If you use your computers one at a time, it might work, but there's still a bunch of things which might go wrong:

e.g. you use Trilium on computer A, but you don't notice it's offline so these changes are not synced/backuped. You then change things on computer B (connected to internet) and you have a conflict once computer A connects to internet. Or your cloud sync is somehow delayed or is not immediate.

Once this happens, you have a conflict and your cloud sync service does not know how to resolve the conflict. And it's not easily resolvable manually either so you'll just have to decide if you want to keep version from computer A or computer B.

**Comment by jchalifour** [comment]
Good points, thank you for raising those things to consider.
