### ISSUE TITLE
Trilium does not import Evernote exported .enex file

### ISSUE THREAD

**Issue by hubitor** [zadam/trilium#914]
I tried to import an Evernote exported .enex (~17 MB) file into Trilium, but no notes were imported. I could see a bunch of errors in the terminal.

"appVersion": "0.40.4

Log file: [https://zerobin.net/?a0cbeb5e36a0b8d8#WSa4Ho4x9K44RJ5iN+wzsfeWC0vDq+DZLY/nf0WhgzE=](url)

**Comment by zadam** [comment]
Hello, could you please try again with 0.40.6? Although I could not reproduce the problem, I tried to avoid this issue.

**Comment by hubitor** [comment]
Hi and many thanks! Just tested with 0.40.6. and it seems that all items were successfully imported.
