### ISSUE TITLE
Extract text pattern from a note using JavaScript and Script API

### ISSUE THREAD

**Issue by ygbillet** [zadam/trilium#915]
Hi,
I wonder if it's possible, through the API, to parse the content of a note.

I want to use Trilium as my meeting report. To do so, I must be able to find some text patterns (e.g. : `@todo NRO 12/03/2020 Launch workgroup`) and aggregate them in another note.

Ideally, it's all in Trilium (JS code using Script API). 
The other way around is to use the API from my server or read the database.

Cheers,

**Comment by zadam** [comment]
Yes, this is possible, e.g. like this with [backend API](https://zadam.github.io/trilium/backend_api/BackendScriptApi.html):

```javascript
for (const note of await api.searchForNotes("@notesToScan")) {
	const htmlContent = await note.getContent();
	
        const result = scanNoteContent(htmlContent); // todo

	await api.createTextNote('root', 'scan result', result);
}
```

You might want to use some JS function to strip HTML tags for easier parsing ...
