### ISSUE TITLE
Ampersand in code blocks is recursively changed to `&amp;` each save

### ISSUE THREAD

**Issue by myii** [zadam/trilium#917]
**Version: 0.40.5**

Steps to reproduce:

* In a text note, add a code block with a single ampersand, i.e.

```
&
```

* Navigate to another note and then come back to this note and now it will be displayed as:

```
&amp;
```

* Add any other text to the note so that another save takes place; navigate away and then back to the note and now it will be displayed as:

```
&amp;amp;
```

* This continues recursively each time the note is saved until you can even end up with:

```
&amp;amp;amp;amp;amp;amp;amp;
```

* In my actual use-case with a bash snippet containing `&&`, I've now got:

```
... &amp;amp;amp;amp;amp;amp;amp;&amp;amp;amp;amp;amp;amp;amp; ...
```

**Comment by zadam** [comment]
Hello, yes, this is a known issue in CKEditor - see https://github.com/ckeditor/ckeditor5/issues/5901

It is quite unfortunate that this has not been fixed yet.

**Comment by myii** [comment]
Thanks for the prompt response, @zadam.  Ouch, that's a nasty bug upstream.  Have you come across any workarounds for this?

**Comment by zadam** [comment]
I don't know any workaround unfortunately.

**Comment by dtomlinson91** [comment]
The workaround I'm using is create a js frontend note say `replaceamp`

```
var find_0 = '&amp;amp;&amp;amp;'
var find_1 = '&amp;&amp;'

var repl = '&';

var re_0 = new RegExp(find_0, 'g');
var re_1 = new RegExp(find_1, 'g');

document.getElementsByClassName('language-text-x-sh')[0].innerText = document.getElementsByClassName('language-text-x-sh')[0].innerText.replace(re_0, repl)

document.getElementsByClassName('language-text-x-sh')[0].innerText = document.getElementsByClassName('language-text-x-sh')[0].innerText.replace(re_1, repl)
```

then use `@runOnNoteView=replaceamp` as a tag on the note you want.

You can change the css class `language-text-x-sh` to whatever code it is or loop through all possibilities.

**Comment by myii** [comment]
@dtomlinson91 That looks like a useful snippet.  Surely we could use a loop to work through all of the relevant elements on the page.  If I get a chance, I'll try at my end.

BTW, there's a slight difference between my findings (`-`) and yours (`+`):

```diff
-&amp;amp;
+&amp;&amp;
```

**Comment by KodaCHC** [comment]
Thank you.

> You can change the css class language-text-x-sh to whatever code it is or loop through all possibilities.

Can you help me with this step?
I have set up a new note with name "replaceamp". The Type is JS frontend

Then I have set up the attribute on my note but I have allways &amp; and not &.

I have this issue not only with &amp;. The same with &nbsp;. I hope on a fix :)

**Comment by dtomlinson91** [comment]
> Thank you.
> 
> > You can change the css class language-text-x-sh to whatever code it is or loop through all possibilities.
> 
> Can you help me with this step?
> I have set up a new note with name "replaceamp". The Type is JS frontend
> 
> Then I have set up the attribute on my note but I have allways & and not &.
> 
> I have this issue not only with &. The same with  . I hope on a fix :)

Can you post the contents of the js frontend note you're using. Also posting some text from the note you want to run it on showing what you're trying to replace.

**Comment by KodaCHC** [comment]
I have copy your replaceamp content.
My issue are around in 50 or 60 notes with different ampersands for Codesnippeds or linux commands.

The most Ampersands are from HTML Chars and commands. Also &, &&, &nbsb; and other.. And allways when this will changed to &amp; i will replace it.

Very rarely I have a &amp;, but I think I have to ignore this for now

I hope this will be fixed soon

**Comment by myii** [comment]
There's been quite a bit of activity on the upstream issue so hopefully there's a solution around the corner:

* https://github.com/ckeditor/ckeditor5/issues/5901

**Comment by myii** [comment]
Good news, the upstream bug has been fixed (apparently) -- will this reach the next released version of Trilium, @zadam?

**Comment by zadam** [comment]
First CKEditor needs to make a release (I think they have one planned within a week).

**Comment by myii** [comment]
OK, at least we know it's in the pipeline.  Thanks for the ongoing development!

**Comment by zadam** [comment]
Fixed in 0.42.4.

**Comment by myii** [comment]
Lovely, thanks @zadam!  Quick question if you get a chance: with no find & replace, is it OK to run queries against the database itself or can that mess things up, like note revisions?

**Comment by zadam** [comment]
changing `note_contents.content` should be OK via query (only notes with `isProtected=0`)

**Comment by myii** [comment]
> changing `note_contents.content` should be OK via query (only notes with `isProtected=0`)

Thanks, that's useful to know.
