### ISSUE TITLE
OPML export is not recursive for book notes

### ISSUE THREAD

**Issue by idelem** [zadam/trilium#919]
I use version v0.40.6 on windows 10. 

I selected "this note and all of its descendants" option, but both OPML formats fail to export the subtree. 

log:
```
11:58:27.939 INFO  Sending message to all clients: {"type":"task-progress-count","taskId":"u0yOCzFWU9","taskType":"export","progressCount":0} 
11:58:27.942 INFO  Sending message to all clients: {"type":"task-succeeded","taskId":"u0yOCzFWU9","taskType":"export"} 
```
---
**edit: it occurs when I export book notes.**

**Comment by zadam** [comment]
Hello, I just tested this and the whole subtree is exported inside the OPML file. What kind of notes do you have in the subtree? OPML does not include binary files ...

**Comment by idelem** [comment]
@zadam It seems that only the "book" notes are exported incorrectly, others work fine just as you described. I didn't realize this earlier because many of my notes are in book format. 
Here is an example output:
```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
<head>
<title>Trilium export</title>
</head>
<body></body>
</opml>
```

**Comment by zadam** [comment]
I see, you are right. OPML did not take book notes into account, this is now fixed. Thanks for reporting this bug!
