### ISSUE TITLE
Inserting existing images does not resize correctly

### ISSUE THREAD

**Issue by nigelsim** [zadam/trilium#922]
I'm using 0.40.6 hosted in Docker. I've imported a markdown directory structure, which includes a number of images that I want to embed in my document.

When I insert the images by "Inserting Note" the image is displayed at it's original size, and there is no way to scroll sideways.

Inserting new images via drag and drop works as expected.

Is this the correct way to insert an existing image?

**Comment by zadam** [comment]
Hello,

"include note" is not the expected/standard way to insert an existing image into the text document. Instead the normal flow is to either copy & paste from another note where this image is inserted or go to the image note itself and there's a "copy to clipboard" button and then you can just paste it in the document.

However the overflow of the image when you use "include note" is a bug and has been fixed Thanks for reporting this!
