### ISSUE TITLE
Feature Request - add words to spellchecking dictionary

### ISSUE THREAD

**Issue by Mariner171** [zadam/trilium#923]
It would be helpful if words the automatic spellchecker does not recognize could be added to its dictionary so it will recognize them in the future. Many word processors and text editors allow you to add words to their spell-checking dictionary or add your own custom dictionary to extend the built-in dictionary. Typically, you right-click on the word and a context menu would let you add the word to the dictionary.

**Comment by zadam** [comment]
Hello, yes, (not yet released) 0.41 has reworked spellchecking and supports adding words through right click to the system dictionary

**Comment by Mariner171** [comment]
Great news! Thank you!
