### ISSUE TITLE
How to create notes automatically by CLI or API?

### ISSUE THREAD

**Issue by martinmurciego** [zadam/trilium#928]
Could pass examples, I would like to be able to create notes by command line or api. I have notes in many flat text files but also in many other applications. I would like it even as a way to integrate into another app. Especially dealing with the installed desktop version.

**Comment by zadam** [comment]
Hello, there isn't an official REST / command line API (although REST API is planned), but you can relatively easily use [custom request handler](https://github.com/zadam/trilium/wiki/Custom-request-handler#create-note-from-outside-trilium) using which you kind of define your own custom API for what exactly you need ...

**Comment by zadam** [comment]
Trilium now has REST API: https://github.com/zadam/trilium/wiki/ETAPI
