### ISSUE TITLE
Ability to connect to multiple knowledge bases from desktop client

### ISSUE THREAD

**Issue by terafo** [zadam/trilium#929]
Now it's possible only in browser, which is annoying since I think that desktop client is mostly better.

**Comment by zadam** [comment]
This is probably not going to happen. You can however run two instances in parallel on different "documents", when you correctly configure the `TRILIUM_DATA_DIR` for each instance.

**Comment by terafo** [comment]
How do I do that?

**Comment by zadam** [comment]
I wrote a short guide here: https://github.com/zadam/trilium/wiki/FAQ#how-to-open-multiple-documents-in-one-trilium-instance
