### ISSUE TITLE
Trilium automatically compresses images so it isn't possible to paste screenshot of full webpage(or any other image with text) to note

### ISSUE THREAD

**Issue by terafo** [zadam/trilium#930]
https://giphy.com/gifs/fw3SKn9ciqvgVlq37z

**Comment by zadam** [comment]
You can tweak the image compression in the Options according to your needs.

**Comment by terafo** [comment]
There is no way to disable width limit and no way to disable auto compression to jpeg.

**Comment by zadam** [comment]
If you set the limit to e.g. 100000 pixels, then it's effectively disabled.

Also you can try to use the import dialog (from Note Actions) and uncheck "shrink images" which will then import images as they are.

**Comment by fivestones** [comment]
I'd still like to have the ability in options to disable any image compression or resizing. Or maybe the ability to disable on any notes that have a certain attribute set.

**Comment by Myzel394** [comment]
I would also love to see that, @zadam should I create a PR?

**Comment by zadam** [comment]
Yes, please. IMHO the scope should be simply turning off the compression resizing completely globally. There's an option in import dialog to disable it per import, this checkbox should be removed/deactivated when the global compression/resizing is disabled.

**Comment by Myzel394** [comment]
@zadam quick question in general: Could you assign yourself to issues you are working on, please? This way, I and other people know what issues we don't need to take a look at and can focus on other ones. It just happened that I was working on an issue and then suddenly found out that you already pushed a fix for it.

I think this would just help everyone make Trilium Notes better :)

**Comment by zadam** [comment]
To be honest, it's a conscious choice to not invest a lot of time into keeping the issue tracker in a polished state. Such administrative time is not fun and cuts directly from the actual development effort.

**Comment by fivestones** [comment]
To be honest, I understand, but I've also moved to logseq. It's more fun to use a product that is invested in by a team that keeps the issue tracker in a polished state.
Thanks so much for what you made here. It was my introduction to much better note making tools, and the first step that led me to obsidian, roam, athens, and now logseq.
