### ISSUE TITLE
UI: Error when inserting image from Android phone

### ISSUE THREAD

**Issue by nigelsim** [zadam/trilium#931]
When trying to add an image to a note from my photos I get an error.

I did not see any network traffic using the Chrome remote debugger to suggest that an upload had actually occurred either, but I don't have a dev build with source maps handy to proceed any further today.

Steps to reproduce
-------------------------
1. Using an Android phone, either Chrome or Firefox (same error on both)
2. Go to Trilium and find an existing note
3. Use the toolbar to insert an image
4. Select an existing photo 

Expected
-------------
The photo to be inserted

Actual
---------
The error **TypeError: glob.getActiveNode is not a function.** is displayed

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, this bug has been fixed and will be released soon.
