### ISSUE TITLE
UI: Toolbar is not usable on a phone in portrait mode

### ISSUE THREAD

**Issue by nigelsim** [zadam/trilium#932]
On an Anrdoid phone (Pixel 2) in both Firefox and Chrome, portrait mode, it is not possible to see all the buttons on the editor toolbar.

![Screenshot_20200321-113608](https://user-images.githubusercontent.com/2869/77812831-c6060780-70ef-11ea-8dad-49e657e1e544.png)

Trilium Version: 0.40.6

**Comment by zadam** [comment]
CKEditor recently fixed this in the inline toolbar, but the [block toolbar remains unresponsive](https://github.com/ckeditor/ckeditor5/issues/6449).

**Comment by nigelsim** [comment]
![Screenshot_20200510-143141](https://user-images.githubusercontent.com/2869/81490927-23829c00-92cb-11ea-827e-c86e5c3732f6.png)

Resolved in 0.42.1
