### ISSUE TITLE
UI: Bottom of editor panel is not accessible on a phone in landscape mode 

### ISSUE THREAD

**Issue by nigelsim** [zadam/trilium#933]
On an Anrdoid phone (Pixel 2) in both Firefox and Chrome, landscape mode, it is not possible to see scroll to the bottom of the editor panel. The cause is a `min-height: 500px` on the element. It looks like a shared CSS class so I'm hesitant to just change it without knowing more first.

I need to go into landscape mode to access the editor toolbar, as per #932

Trilium Version: 0.40.6

P.S., I really do like the way Trilium works, and I hope to be able to help out more directly  (PRs) in the future.

**Comment by zadam** [comment]
Hello, thanks for reporting this issue, bug has been fixed and will be released soon.

BTW, frontend code in 0.40.X is in quite bad shape and this was one of the consequences. Upcoming 0.41 has almost completely rewritten frontend code and did not have this issue ...

**Comment by nigelsim** [comment]
Thanks for the quick resolution. Is there an ETA on 0.41, and is the dev branch for it in a testable state?

**Comment by zadam** [comment]
First beta should come in about 1/2 weeks. Currently the master branch is in testable state though (meaning it starts up and the basic functionality works).
