### ISSUE TITLE
[Feature Request] Side by side text

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#935]
First, Trilium is awesome. Thank you for a great application.

What i'm looking for is the ability to split the text area of a note into blocks, so that you can place text or objects side by side. A few examples:

Microsoft Onenote allows you to move the text boxes around
Notion and Nimbus Note allows you to arrange objects side by side, and adjust the width of each

**Comment by Engr-AllanG** [comment]
I see this is similar to issue #319 , and your response was that it is a limitation of CK editor

**Comment by zadam** [comment]
I'm not really sure what you're asking for. Could you perhaps attach a screenshot of some of the mentioned apps with the proposed feature?

**Comment by Engr-AllanG** [comment]
See attached screenshots. The vertical bar next to the text on the right allows you to resize the horizontal space as shown in the second picture. The resizing ability isn't necessarily the key feature, its the fact that you can have text or objects next to each other horizontally that don't interact with each other. 

![Text blocks](https://user-images.githubusercontent.com/3161759/77833277-57c64280-70f9-11ea-8c24-d6ff76bfe9a6.JPG)
![Text blocks 2](https://user-images.githubusercontent.com/3161759/77833304-9d830b00-70f9-11ea-9103-5242eb922bd0.JPG)

**Comment by zadam** [comment]
Thanks for the screenshot, now I know what you mean.

So yes, this is mainly an editor feature and I'm not in a position to implement such advanced features alone, so I'm kind of observing what recent development has been done in CKEditor and try to use that.

**Comment by Mike97M** [comment]
A work around for this would be: instead of having only 1 instance of CKEditor, add more for every page that someone wants to split.
![image](https://user-images.githubusercontent.com/22031757/77850350-997aea00-71da-11ea-8c8e-e9756daeeeb7.png)
Something like the image, but with the ability to edit each note, add more columns/rows

PS: Great work with Trilium, you're doing an amazing job!

**Comment by Engr-AllanG** [comment]
@Mike97M I had the same thought. Considering the limitation of CKEditor, maybe multiple instances could work...

**Comment by Engr-AllanG** [comment]
Closing this because although it may be a nice to have feature, it has become less of a 'need' for me and there are other items on your road map #1165 that I would like to see implemented sooner
