### ISSUE TITLE
Create note from attribute relation

### ISSUE THREAD

**Issue by sambbaron** [zadam/trilium#939]
It would be helpful to be able to create a new note when setting an existing note's relation.

In general for note creation, it would be helpful to be able to set the note's location when it's created. The "cut selection to sub-note" feature is great, but I almost always have to move the note that is created since I prefer a flatter note hierarchy with lots of internal links.

**Comment by zadam** [comment]
There are plans to be able to create a note directly from autocomplete ... So as you type it offers you existing note matching the typed pattern but additionally allow you to create a new note with the title you entered.

I'm not sure how that idea about setting a new note's location would work though ...

**Comment by fivestones** [comment]
I'm excited for the ability to create a note directly from autocomplete. Thanks for working on this!

**Comment by sambbaron** [comment]
@zadam Regarding note creation and moving at the same time, could you combine the `Add note link` and `Move notes to` dialogs? The `Target Parent Note` could default to the current note (assuming the default is to add a child note to the current note).

Something like this (pardon the hacky image):
![trilium-create-move](https://user-images.githubusercontent.com/10456742/80313549-56dc0b80-87a0-11ea-888a-7006b8d137d7.png)

**Comment by zadam** [comment]
Released in 0.44.4.

More details in #1237
