### ISSUE TITLE
0.41 Bug - Sidebar options missing

### ISSUE THREAD

**Issue by sambbaron** [zadam/trilium#942]
In 0.41-beta, the sidebar options are missing from the options dialog.

![sidebar-options](https://user-images.githubusercontent.com/10456742/78403423-2ba33980-75b1-11ea-86e9-850a05df46a8.png)

**Comment by zadam** [comment]
Yes, this was removed. The only thing really lost is the ability to reorder widgets on the sidebar, other things (hiding the sidebar, collapsing individual widgets) should still be doable directly from the sidebar.

0.41 is internally way more flexible regarding the UI organization - it is relatively easy to reorder, remove, add widgets etc. (see [the whole definition of desktop layout](https://github.com/zadam/trilium/blob/master/src/public/javascripts/widgets/desktop_layout.js)). However the price for that was the current sidebar settings.

I still plan to expose the ability to customize the layout also to the (advanced) users in some way.

**Comment by sambbaron** [comment]
Yes, components all the way. Great job! It would be cool if you exposed hooks into certain components, but that seems low priority. 

As a user, I do find certain widgets more helpful than others. The note info is not useful to me, and I can get it from the "Note Actions" menu.

**Comment by zadam** [comment]
If you click on the title "NOTE INFO", then widget collapses so it does not take too much space (collapsed state is also saved)
