### ISSUE TITLE
Day template do not working

### ISSUE THREAD

**Issue by danielnbalasoiu** [zadam/trilium#943]
Hi!

First of all I'd like to congratulate you for this great project! You rock! \m/

I've tested the stable and the latest beta desktop application and there's a bug when `Day template` runs: changes in template ar not present when a new day is being created.

OS: Linux
Steps to reproduce:
- edit `Day template` and add some tasks
- go to `Today` icon and click on a random day in the future.

Expected result: tasks from `Day template` should be in the newly create page
Actual result: The page is empty.

Another way to reproduce it is by using [gitpod.io](gitpod.io). Same behaviour as desktop application.

When the applications runs under docker or with npm and accessed using the browser, template feature works fine.

Let me know if you need more information.
Keep up the great work you're doing!

**Comment by zadam** [comment]
Hello, I assume the problem appeared for you on 0.41, there I managed to reproduce it and fix it. 0.40.X did not have this problem.

Thanks for reporting.
