### ISSUE TITLE
0.41 Bug - Promoted labels not in note

### ISSUE THREAD

**Issue by sambbaron** [zadam/trilium#944]
In 0.41 beta, I am not seeing any promoted labels in notes. As an aside, it would be helpful to be able to show/hide promoted labels.

![Annotation 2020-04-04 094140](https://user-images.githubusercontent.com/10456742/78456470-c30f9780-7658-11ea-95c7-23209fbc1bd5.png)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, this was a bug introduced in 0.41 and has now been fixed.
