### ISSUE TITLE
0.41 Websocket Connection Failed

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#946]
Running .41 on Linux Server edition, web version in the browser console, I'm seeing failures for websocket connection:

```
WebSocket connection to 'wss://DOMAIN.COM/' failed: Error during WebSocket handshake: Unexpected response code: 200

connectWebSocket @ ws.js:162
sendPing @ ws.js:184
```

Nothing appears in the log for this, and I'm not sure if this was there in previous versions since I didn't have a reason to go into the console until today.

Any ideas?

**Comment by zadam** [comment]
Looks like a proxy issue, if you use nginx, you could try: https://github.com/websockets/ws/issues/979#issuecomment-337934638

**Comment by joshcsullivan** [comment]
Thanks, that worked!
