### ISSUE TITLE
[Feature Request] Collapse or expand bullet points

### ISSUE THREAD

**Issue by danielnbalasoiu** [zadam/trilium#947]
[Roam](https://roamreserch.com) has the feature of collapsing or expanding notes with child bullet points.
Over time I've noticed this is very useful when I work because it keeps a clean work space.

This note
![image](https://user-images.githubusercontent.com/46020698/78501143-ed8d4d80-7749-11ea-8822-68389e7877fe.png)
would become 
![image](https://user-images.githubusercontent.com/46020698/78501223-54ab0200-774a-11ea-9152-1450efc1ac95.png)

Thank you!

**Comment by zadam** [comment]
So I think philosophy of Roam and Trilium are a bit different regarding this - in Trilium primary way to represent structure is the note tree and there you can collapse as you wish.

Then in a note you can create (nested) lists as you wish, but they are not really expected to get huge that you would need to collapse them etc. In such case it would make more sense to break the note into multiple separate notes in a hierarchy.

Having said that, I'm not necessarily against such feature, but this is a matter of the text editing component (CKEditor) and there I'm mostly limited to what it supports or sometimes I can write small plugins where it makes sense. This however does not seem lie something I could easily implement without having to alter the CKEditor core components ...

**Comment by danielnbalasoiu** [comment]
Yes, now that you've mentioned that you're using CKEditor it makes total sense. 
I'll try to change my workflow and adapt with Trilium's way of doing things :D

Thank you for your prompt response.

**Comment by tredondo** [comment]
@zadam Maybe you don't want to collapse bullet points, but collapsing headings/sections (like in Obsidian) would be very useful.
