### ISSUE TITLE
[Feature request] mermaid diagrams

### ISSUE THREAD

**Issue by BigGitWorld** [zadam/trilium#948]
First of all
@zadam
Thank you for this nice note taking app.
I wonder why the number of stars of this app is less than its competitors (like the Notable).
I was comparing the trilium vs the Notable and see the later supports the [mermaid diagrams](https://github.com/mermaid-js/mermaid)  which is very useful for at least developers.
Can we use the mermaid in the trilium now?

**Comment by zadam** [comment]
Hello, yes, I do have plans in this direction, but I'm trying to get "basics" right first and then I will work on adding more note types (besides diagrams I'd also like to add math/latex support).

**Comment by BigGitWorld** [comment]
Thank you very much
Nice job!

**Comment by aniston** [comment]
@zadam  just checking on this mermaid diagrams Feature Request, any update or is this already possible ?

From a user point of use, lovely work with bringing us 'trilium', thanks ! first try and like it, looking forward towards the multiple user and public  interface possibility.

cheers,
Aniston
