### ISSUE TITLE
How to create a folder?

### ISSUE THREAD

**Issue by BigGitWorld** [zadam/trilium#949]
I have installed the trilium and want to create a folder to be parent of my notes.
but there is not any option for creating a folder. while in the trilium screenshots, there is folder icons too.
How can I create a folder?

OS: Linux Ubuntu 16.04
Trilium version : 0.40.7

**Comment by zadam** [comment]
Hello, there is no distinction between a note and a folder - note can have both text content and children. So right-click on any note in the tree and click on "Insert child note".

**Comment by Heniker** [comment]
What you actually want is called Book type.
More info here - https://github.com/zadam/trilium/wiki/Book-note

**Comment by BigGitWorld** [comment]
> What you actually want is called Book type.
> More info here - https://github.com/zadam/trilium/wiki/Book-note

The Book note differs. you can refer to the default trilium structure that exists with the installation (or screenshots in the wiki) and see the difference between their icons.

**Comment by BigGitWorld** [comment]
> Hello, there is no distinction between a note and a folder - note can have both text content and children. So right-click on any note in the tree and click on "Insert child note".

Hello @zadam 
I think creating a visual difference between a folder and a file makes better sense to the user.
You can do it for example by an attribute simply.

**Comment by popey456963** [comment]
As Zadam pointed out above, should a folder just be defined as something that contains other files?  What if the folder itself is a file, should it be displayed as a file or a folder.
