### ISSUE TITLE
Duplicate notes in sidebar

### ISSUE THREAD

**Issue by nigelsim** [zadam/trilium#951]
Using the Docker version 0.41-beta, revision 4b24d9562c79c01e9c1b1489a42e01a4c5c20683 I get duplicate notes in the side bar. When I click on either copy the top-most one is selected (i.e., they seem to have the same ID)

![image](https://user-images.githubusercontent.com/2869/78839022-d5b01500-7a3a-11ea-821d-420a01727cce.png)

The original structure was imported from a `tar` file full of MarkDown files under 0.40.x, but the issue persists on notes created entirely in Trilium.

What additional diagnostics can I do to help?

**Comment by danielnbalasoiu** [comment]
I have the same behaviour sometimes and I _fix it_ by `Ctrl + Shift + R`.

**Comment by zadam** [comment]
Hello, please upgrade to 0.41.1-beta. 

New version of tree component (fancytree) had this bug, so I downgraded it to a version without it.

**Comment by nigelsim** [comment]
I will. Any chance you can push 0.41.1-beta to Docker hub?

**Comment by zadam** [comment]
Sorry, I didn't realize the image was not pushed. It's fixed now.

**Comment by nigelsim** [comment]
I can confirm this is fixed in 0.41.1-beta
