### ISSUE TITLE
New fonts look strange

### ISSUE THREAD

**Issue by danielnbalasoiu** [zadam/trilium#953]
I've create a docker image from your latest commit `v0.41.1-beta-50d3928dd5` and I noticed icons are no very explicit. 

New version
![image](https://user-images.githubusercontent.com/46020698/78859744-f37c7a80-7a38-11ea-97b5-307976ddc367.png)

With docker images from DockerHub with tag `latest`

![image](https://user-images.githubusercontent.com/46020698/78859864-579f3e80-7a39-11ea-911d-4d545d5ec8ff.png)

Is something wrong with my fonts? What's the name of the new fonts. Maybe installing them will fix the issue.

Thank you!

**Comment by danielnbalasoiu** [comment]
Installing [BoxIcons](https://gumroad.com/d/f44ad088a065db81a1c0d7f904169a46) fixed it.

**Comment by zadam** [comment]
This is usually a browser cache problem and force refresh helps (CTRL-F5).
