### ISSUE TITLE
Running a local server in a browser and not an electron window? 

### ISSUE THREAD

**Issue by wadbr** [zadam/trilium#954]
First I want to say that this is one of the best optimized electron apps I have seen, it's fast and responsive and the cpu/ram usage is basically perfect compared to the normal electron story of eating 10% cpu of an i7 while sitting idle. 

But I still want to be able to run Trilium locally (without docker is possible), is that possible? 

To elaborate, I'm thinking of an exe that will start a background server and I can access my instance by going to localhost:9000 or something similar. 

The why:  Way less resources usage, and it allows interacting with all of my browser addons and scripts.

**Comment by zadam** [comment]
You can do that, for linux there's a [build](https://github.com/zadam/trilium/releases/download/v0.41.1-beta/trilium-linux-x64-server-0.41.1-beta.tar.xz) for that.

There isn't a ready made package available for windows although it should not be difficult to get it running. Just clone the repo, run `npm install` and then `node src/www` (assuming you have node installed ...)

**Comment by wadbr** [comment]
This worked perfectly, thank you very much, 

PS: For anyone trying this on Windows, you don't have to have VS2015 installed, if you have a VS2015 error do an `npm rebuild` after `npm install` and the server will run with `node src/www`

**Comment by popey456963** [comment]
Closed as appears solved.
