### ISSUE TITLE
generate automatic externalLink attribute

### ISSUE THREAD

**Issue by KodaCHC** [zadam/trilium#955]
Hi

Gives a way to generate automatic externalLInk attribute? I will have a list with all external Links in a note. Internal Link will generate automatic internallink attribut.

I found this one https://github.com/zadam/trilium/commit/88bd65c6798609a39206722305fab4f8d91d618b
But I'm not sure if this the same. I try the 0.41.1 and not find the automatic generated external Link Attribute.

Koda

**Comment by zadam** [comment]
Hello, this functionality existed but this was disabled in 0.41.1-beta.

Reason for that is that some pasted content has literally thousands on links (e.g. this [clipped page](https://en.wikipedia.org/wiki/2019%E2%80%9320_coronavirus_pandemic) has 6000) and at that point it has serious implications on performance and usability ...

What is your use case for parsed externalLink?

**Comment by KodaCHC** [comment]
Thank you four your fast answer. That is no problem.
It is not a specific use case.
I thought it might be helpful to use this as a "link collection" if you have a large text and would search for a specific link. But in this case (I only have 2 or 3 links) I can insert this by hand.
