### ISSUE TITLE
Docker Autostart of Trilium

### ISSUE THREAD

**Issue by KodaCHC** [zadam/trilium#956]
Hi

I want autostart Trilium so that I have insert a service for my docker

```
[Unit]
Description=Some service
Requires=docker.service
After=docker.service

[Service]
Restart=always
ExecStart=/usr/bin/docker start -a priceless_ride
ExecStop=/usr/bin/docker stop -t 2 priceless_ride

[Install]
WantedBy=multi-user.target
```

This work great. But is this the right way? docker ps show me as name priceless_ride as name for the docker and I'm a little bit confuesd about this :)

Thank you

Koda

**Comment by zadam** [comment]
I think docker generates random names like "priceless_ride" as a better handle than random UUID or hash.

Otherwise there isn't really an official recommended way to do autostart so whatever works for you ...

**Comment by gerroon** [comment]
You can set Docker containers to autostart with flags or in docker-compose.yml, you do not need to run a Systemd service for it.

**Comment by KodaCHC** [comment]
> You can set Docker containers to autostart with flags or in docker-compose.yml, you do not need to run a Systemd service for it. Let Docker handle it.

Thank you. Habe yo samples for this? Docker is new for me

**Comment by gerroon** [comment]
https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by danielnbalasoiu** [comment]
Like @gerroon suggested docker documentation is your friend.
I start it like this:
`docker run --restart unless-stopped -dit -p 127.0.0.1:6677:8080 -v /home/$USER/sync/trilium-sync:/root/trilium-data trilium:v0.41.1-beta-62bc0513`
You should replace `v0.41.1-beta-62bc0513` tag with `latest` unless you've built your docker image.

**Comment by KodaCHC** [comment]
Thank you. This works fine.
