### ISSUE TITLE
Trilium convert special Chars

### ISSUE THREAD

**Issue by KodaCHC** [zadam/trilium#961]
I use the newest non Beta Version 0.40.7
When I insert a Code Block with special Chars, Trilium Convert. Unfortunately I only noticed it after more than 100 entries.

I have tested this on the Webinterface from Server install, and the WIndows installation with Sync.

When I insert a Code Block with this Content:
apt-get update && apt-get upgrade
I see the right character. When I go to another Note and go back, the & is an other char

`apt-get update &amp;&amp; apt-get upgrade`
The same for different other entries. Example:

`&amp;amp;amp;nbsp;`

Is this a bug where is fixed in beta, and givs a change to rescure my notes?

Thank you for help

EDIT:
1. I have try with the newest Beta 0.41.1 beta and had the same issue
2. I don't know when, but from time to time more masks come suddenly because it replaces the special characters again. Then you see e.g. like this

`apt-get update &amp;amp;amp;amp;amp;amp;amp;&amp;amp;amp;amp;amp;amp;amp; apt-get`

**Comment by zadam** [comment]
Duplicate of #917
