### ISSUE TITLE
v0.41.1-beta - No support for Kiwi Browser

### ISSUE THREAD

**Issue by KodaCHC** [zadam/trilium#962]
HI

With the newest Beta, I can login with my Smartphone, but I don't see any notes/categories. On Windows Desktop I don't have a problem.

When I go back to the latest Version (0.40.7) it works on smartphone.

Koda

**Comment by zadam** [comment]
Hello, I'm not sure if this is exactly the same issue but for me the mobile version would load, it would just take very long time.

In 0.41.2-beta I added a spinner and sped up loading by packaging the application files in a bundle using webpack. Could you please try this new version and report what's happening?

Thanks.

**Comment by KodaCHC** [comment]
Hi

Thank you. But on two Samsung Note 10 plus i have the same issue. I attached an image of mobile view on smartphone.
![Screenshot_20200413-123458_Kiwi Browser](https://user-images.githubusercontent.com/61413942/79115675-c1478180-7d86-11ea-9a7a-34731f23646c.jpg)

**Comment by zadam** [comment]
I see, so that is a different problem. Would it be possible to provide log file from ~/trilium-data/log/[latest log file]?

Thanks!

**Comment by KodaCHC** [comment]
I think it is a Browser Problem. When i Use google Chrome it works. When I use Kiwi Browser for Android i had this problem with the Beta.

The last entries of Log File

`16:00:20.619 INFO  GET /api/clipper/handshake 
16:01:23.132 INFO  Generated sourceId=BC9DcDPRFI3e 
16:01:23.135 INFO  App HTTP server starting up at port 8080 
16:01:23.135 INFO  {
  "appVersion": "0.41.2-beta",
  "dbVersion": 158,
  "syncVersion": 14,
  "buildDate": "2020-04-13T10:30:11+02:00",
  "buildRevision": "87510fd72ba7ec9a8b83cd8a00dbe1d12b5e8a3f",
  "dataDirectory": "/root/trilium-data",
  "clipperProtocolVersion": "1.0"
} 
16:01:23.315 INFO  DB ready. 
16:01:23.321 INFO  DB size: 844546 KB 
16:01:24.130 INFO  GET / 
16:01:24.496 INFO  GET /login 
16:01:28.945 INFO  POST /login 
16:01:29.549 INFO  GET / 
16:01:29.560 INFO  Generated CSRF token XXXX with secret undefined 
16:01:29.561 INFO  Generated sourceId=XXXXX 
16:01:30.373 INFO  GET /api/options 
16:01:30.376 INFO  GET /api/tree 
16:01:30.377 INFO  GET /api/keyboard-actions 
16:01:30.380 INFO  GET /api/keyboard-shortcuts-for-notes 
16:01:42.355 INFO  GET / 
16:01:42.370 INFO  GET /login 
16:01:42.502 INFO  GET /favicon.ico 
16:01:43.318 INFO  Notes deleted: 219, not deleted 474 
16:01:43.320 INFO  Note revisions deleted: 0, not deleted 22 
16:01:43.322 INFO  Branches deleted: 258, not deleted 474 
16:01:43.323 INFO  Attributes deleted: 537, not deleted 429 
16:01:43.325 INFO  API tokens deleted: 0, not deleted 1 
16:01:44.877 INFO  Slow query took 1518ms: 
                    SELECT noteId
                    FROM notes
                             JOIN note_contents USING (noteId)
                    WHERE isDeleted = 0
                      AND isProtected = 0
                      AND content IS NULL 
16:01:44.877 INFO  Slow query took 1483ms: SELECT * FROM options WHERE name = ? 
16:01:44.877 INFO  Slow query took 481ms: SELECT * FROM options WHERE name = ? 
16:01:44.894 INFO  All consistency checks passed (took 1576ms) 
16:01:46.113 INFO  POST /login 
16:01:46.272 INFO  GET / 
16:01:46.288 INFO  Generated CSRF token XXXXXX; Path=/ 
16:01:46.289 INFO  Generated sourceId=XXXX 
16:01:47.127 INFO  GET /api/tree 
16:01:47.130 INFO  GET /api/options 
16:01:47.134 INFO  GET /api/keyboard-actions 
16:01:47.142 INFO  GET /api/keyboard-shortcuts-for-notes 
16:01:47.288 INFO  GET /api/notes/XXXX 
16:01:52.321 INFO  POST /api/recent-notes 
16:02:20.625 INFO  GET /api/clipper/handshake 
`

**Comment by zadam** [comment]
Oh, I see. In general I support (read: test) only Firefox and Chrome (but of course patches for other browsers are welcome).
