### ISSUE TITLE
'Include Note' Create Relation

### ISSUE THREAD

**Issue by sambbaron** [zadam/trilium#963]
When I use the 'Include Note' feature, I expect to create a relation between the two notes. This would occur similarly to adding note links.

**Comment by zadam** [comment]
Hello, thanks for reporting this bug. Yes, normally `includeNoteLink` relation is created however new sizing options added in 0.41.2-beta broke parsing the include note link. This is now fixed.

**Comment by sambbaron** [comment]
Awesome, thank you for the quick fix!
