### ISSUE TITLE
Feature Request: Outline for code blocks in Book note

### ISSUE THREAD

**Issue by TheObserver6995** [zadam/trilium#967]
In the book note, there is no way to differentiate between plain text and code blocks (or block quotes). Would it be possible to at least add an outline to it to make it more distinguishable from regular text?

**Comment by zadam** [comment]
I assume you're using 0.40, since this should be fixed in 0.41 (beta):

![image](https://user-images.githubusercontent.com/617641/79378622-ecd09480-7f5d-11ea-9f1f-e98e646c96bb.png)

**Comment by TheObserver6995** [comment]
Nice to hear, that this should already be fixed. However I am using the docker image `zadam/trilium:0.41-latest`, which seems to be the same as the beta image available on dockerhub, but it doesn't look like in your screenshots.

**Comment by zadam** [comment]
Can you specify which exact version are you running?

**Comment by TheObserver6995** [comment]
Never mind, you are right. This was added in the new release 10 hours ago (docker image digest `5bfe0477dff7`). 

Thanks for your help!

**Comment by zadam** [comment]
For the record, it was added before that (perhaps 0.41.1 or 0.41.2, can't remember).
