### ISSUE TITLE
[Feature Request] Add Always on top to Trilium window

### ISSUE THREAD

**Issue by jetacpp** [zadam/trilium#968]
I routinely take notes when browsing with browser full screen and Trilium in small window. It would be great if Trilium can Stay On Top. I am using Linux so ability to stay on top is available for regular windows but not for Trilium application. :)

**Comment by zadam** [comment]
As a workaround you can activate standard window title bar (in Options -> Appearance) and use your standard window manager feature ...

**Comment by jetacpp** [comment]
Thank you! I am perfectly happy with the workaround solution :)
