### ISSUE TITLE
I want to change custom font but i don't know CSS

### ISSUE THREAD

**Issue by varvir** [zadam/trilium#972]
I want to use custom font but i don't know CSS.

I'd like to switch custom like "Menu - Options - Appearance - Theme" procedure.

https://github.com/zadam/trilium/issues/257#issuecomment-568246561

well... I have to learn CSS?

**Comment by zadam** [comment]
Fonts are currently considered part of themes which are defined in CSS.

So yes, there isn't any other way to choose custom font other than by editing some CSS ...

**Comment by varvir** [comment]
thanks for the reply.
