### ISSUE TITLE
One click copy to clipboard for code block.

### ISSUE THREAD

**Issue by projectrk** [zadam/trilium#973]
Feature Request: 
- One click copy to clipboard for code block.
- Link code notes to text note instead of code block.

Trilium Linux v 0.40.7
--

**Comment by zadam** [comment]
Hello, could you explain "Link code notes to text note instead of code block." - I don't understand what you mean ...

**Comment by projectrk** [comment]
It's like framing it to the page at the same time there is also a click button for copy the whole code to the clipboard.

1) I will create a "code/python" page I will put my code there name it as cisco.py.
2) On my "text" page, I will just insert like <iframe>cisco.py</iframe> then it will display as part of that "text" page.

Whatever changes I made in my cisco.py code page, it will reflect also to my "text" page.

**Comment by zadam** [comment]
Yes, this is already possible with ["include note"](https://github.com/zadam/trilium/wiki/Text-notes#include-note). There won't be syntax highlighting though.

![image](https://user-images.githubusercontent.com/617641/80679551-5a7fd300-8abd-11ea-83a4-af47862502cb.png)

**Comment by projectrk** [comment]
Here is the image of what I am talking about. when you click the clipboard icon on the far right of it. it will copy the content inside the box to the clipboard automatically.
![oneclick01](https://user-images.githubusercontent.com/15811696/82859131-7c4b6900-9f48-11ea-9d29-9ba2134e3769.png)

The syntax on how you create content into it. formatting is plain-text
![oneclick02](https://user-images.githubusercontent.com/15811696/82859206-ad2b9e00-9f48-11ea-9505-9c9aa9f80de6.png)

This can also be use for code formatting. for python
![oneclick03](https://user-images.githubusercontent.com/15811696/82859399-2e833080-9f49-11ea-8748-1546081a64b9.png)

**Comment by zhdenny** [comment]
I would also like for an easy way to copy the contents of a code block OUT of Trilium....exactly how @projectrk shows in his latest screenshots

**Comment by liukun** [comment]
This script add a button on the toolbar to copy the content of an active note to the clipboard.

```
api.addButtonToToolbar({
    title: "Copy Content",
    icon: "copy",
    shortcut: "ctrl+alt+c",
    action: async () => {
        let note = api.getActiveTabNote()
        let content = await note.getContent()
        navigator.clipboard.writeText(content)
        api.showMessage("Copied `"+note.title+"`")
    }
})
```

Not too good as a button on a code block, but may be convenient under some circumstances.

**Comment by liukun** [comment]
Just for reference, a plugin for Obsidian with the same functionality https://github.com/jdbrice/obsidian-code-block-copy .

**Comment by TuffG** [comment]
+1 for this feature

**Comment by Nriver** [comment]
Refer to https://github.com/Nriver/copy-code-block-widget

**Comment by eliandoran** [comment]
Done in https://github.com/TriliumNext/Notes/pull/2023, it's not one-click copy, but two click (first to focus the code block, second to copy). In read-only notes, it's one click only.
