### ISSUE TITLE
Feature Request: Multiple spellchecking languages

### ISSUE THREAD

**Issue by TheObserver6995** [zadam/trilium#974]
Since I use multiple (2) languages in my Trilium Notebook, it would be handy if the spellchecking would support multiple languages as well. I tried to use a coma / semicolon seperated list, but this didn't work and I find no documentation of it, so I assume this isn't the case yet.

**Comment by zadam** [comment]
Hello, this is a bug, multiple languages should be supported just by entering multiple language codes separated by comma. This will be fixed in the next version.
