### ISSUE TITLE
How to configure the right sidebar in 0.41.5

### ISSUE THREAD

**Issue by jaroet** [zadam/trilium#975]
I just installed the 0.41.5 release this morning and had some issue's with it. 

First off all it looks like all the default widget in the right sidebar are reset (visible and on a different order then the order I had them in). I am also unable to find where to hide/re-order them. I thought in the Options screen but it is not there anymore. 

I also used the script (zie https://github.com/zadam/trilium/issues/715) to show the alwaysVisible widget with my notes but that does not seem to work anymore although the codenote is still there. 

On a personal note I would like the path to be visible at the bottom of the middle part of the screen. At the top of the left side is 1. very much in your face. 2. As I guess most people have a relative small left sidebar (mayby like 20% of screen width) the path is almost always incomplete. Specially with large and deep trees the benefits is not so big. At the bottom would show more info. 

Regard,
Jeroen

**Comment by jaroet** [comment]
Hello, 
Sorry for compacting 3 issues in one. Will seperate them if it happens in the future. Good to know that the order of widget's was lost in the rewrite. No big deal but I thought it might be a bug of something. 

About the widget visibility ... the toggle for "Notes revisions" is not working for me. All other widgets toggle like you described. 

Look forward to the manual to see if I can fix the script. What is the best way to debug it?

Regards,
Jeroen

**Comment by zadam** [comment]
I added a minimal example of a new widget - should not be too difficult to change the existing custom widget to the new API: https://github.com/zadam/trilium/releases/tag/v0.41.5

> About the widget visibility ... the toggle for "Notes revisions" is not working for me. All other widgets toggle like you described.

That's weird, for me toggling note revisions works as well. Is there perhaps any error in the console? (`CTRL-SHIFT-I`)?

**Comment by sambbaron** [comment]
@zadam The `Note Revisions` widget is not toggling for me either. Using 0.41.5 on Windows. Nothing in the console.

**Comment by zadam** [comment]
Thanks for info, it's really weird. I will have to test this on windows, on linux everything seems fine ...

**Comment by jaroet** [comment]
For me the notes revisions are not working and I am on a Mac.

Op zo 26 apr. 2020 om 21:46 schreef zadam <notifications@github.com>:

**Comment by jaroet** [comment]
Sorry, the folding of the note revisions is not working to be clear ...

Op ma 27 apr. 2020 om 10:56 schreef jeroen ophetweb <
jeroenophetweb@gmail.com>:

**Comment by zadam** [comment]
Thanks to all, I can reproduce the issue now.

**Comment by jaroet** [comment]
Hello, I just upgraded to 0.41.6 and the 'note revisions' widget in the right sidebar is folding now. I will keep this one open for now as @sambbaron might have different experience but looks fixed.

**Comment by sambbaron** [comment]
0.41.6 fixes it for me

**Comment by zadam** [comment]
Yes, this has been fixed. Caused by WebPack mangling class names while the code used the class name as an option index ...
