### ISSUE TITLE
Shortcuts for indent increase/decrease in text documents

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#978]
Hi

It would be very helpful if the indenting functions can be tied to easy to access shortcuts. it is abit tedious to constantly click on line icon to access them from the menu.

thanks

**Comment by gerroon** [comment]
Any way to do this with existing methods like using some js etc which I have no idea how to do it myself,

**Comment by zadam** [comment]
Hi, this was discussed here: ckeditor/ckeditor5#7541

With the advice given it should be easy to implement.

**Comment by gerroon** [comment]
@zadam 

 Thanks for the reply. I assume you mean this will need to be in Trilium to be useful.

**Comment by zadam** [comment]
Yes, I will add it.

**Comment by gerroon** [comment]
Thanks, that sounds very good.
