### ISSUE TITLE
Windows client fails to sync

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#979]
Hi

I use Trilium on Windows and Linux. Today the Win client sudedenly refusing to sync. This was fine last night and I did not change anything on the server, I just added couple notes since then on the Win client. 

I can login to the server in Chromium from the same Win pc, so this is definetely not a network issue. Also the Linux client has no problem with the sync.

Both the Linux and the Win clients are 0.41.5

This is what I see in the server's log when I press sync on the Win client

`POST /api/login/sync returned 400 with response {"message":"Auth request time is out of sync"}`

Version

```
Homepage:	https://github.com/zadam/trilium
App version:	0.41.5
DB version:	158
Sync version:	14
Build date:	2020-04-20T22:40:02+02:00
Build revision:	a86177bb597c752fbc96a24d4be7ab5ae6c0344d
Data directory:	C:\Users\user\AppData\Roaming/trilium-data

```

Log

```
10:41:02.356 INFO  GET /api/options 
10:41:02.378 INFO  GET /api/keyboard-actions 
10:41:02.379 INFO  GET /api/options/user-themes 
10:41:03.187 INFO  POST /api/recent-notes 
10:41:05.568 INFO  POST /api/sync/test 
10:41:17.776 INFO  Notes deleted: 14088, not deleted 3778 
10:41:17.778 INFO  Note revisions deleted: 111, not deleted 384 
10:41:17.782 INFO  Branches deleted: 14425, not deleted 3780 
10:41:17.784 INFO  Attributes deleted: 7906, not deleted 767 
10:41:17.784 INFO  API tokens deleted: 0, not deleted 10 
10:41:18.003 INFO  All consistency checks passed (took 227ms) 
10:42:04.663 INFO  Generated sourceId=vGjPZs4m4Ct2 
10:42:04.674 INFO  App HTTP server starting up at port 37840 
10:42:04.675 INFO  {
  "appVersion": "0.41.5",
  "dbVersion": 158,
  "syncVersion": 14,
  "buildDate": "2020-04-20T22:40:02+02:00",
  "buildRevision": "a86177bb597c752fbc96a24d4be7ab5ae6c0344d",
  "dataDirectory": "C:\\Users\\user\\AppData\\Roaming/trilium-data",
  "clipperProtocolVersion": "1.0"
} 
10:42:04.687 INFO  DB ready. 


DB size: 127217 KB
Note cache load took 120ms
Registered global shortcut Ctrl+Alt+P for action createNoteIntoDayNote
Generated CSRF token v6NZ8nOi--BA_cGzv5KTMrCgz5Yleeq0HB_k with secret _csrf=5DD31WdkNTXQy_c66xl9jUzO; Path=/
Generated sourceId=gUxJoycofdTy
websocket client connected
sync failed: Request to POST http://192.168.1.100:4090/api/login/sync failed, error: 400 Bad RequestError: Request to POST http://192.168.1.100:4090/api/login/sync failed, error: 400 Bad Request
    at generateError (D:\DRIVE2\trilium\resources\app.asar\src\services\request.js:170:12)
    at ClientRequest.<anonymous> (D:\DRIVE2\trilium\resources\app.asar\src\services\request.js:52:28)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2553:12)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)

```

**Comment by gerroon** [comment]
Weird, even a fresh sync with deleted db produces the same error. I wonder if this is  a server/win client bug

**Comment by zadam** [comment]
Based on the error message the server and client's clock seem to be out of sync - the leeway is 5 minutes so the difference must be greater than that.

**Comment by gerroon** [comment]
This is really weird than. Time of my computers is the last thing I would touch, infact never touch them once they are set. 

I tried your point and the Win pc was about 5 mins later however I did not touch it, this was working fine last night which is very weird.

**Comment by zadam** [comment]
It's quite normal that computer clocks drift slowly and then can cross the 5 minute difference without you doing anything wrong. Computer clocks are not very precise and require frequent synchronization via NTP (which can break).
