### ISSUE TITLE
Cannot find module '/usr/src/app/trilium'

### ISSUE THREAD

**Issue by roadcode** [zadam/trilium#981]
using the image **zadam/trilium       0.41-latest**
`docker run -t -i -p 127.0.0.1:8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:latest`

throw the error:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/usr/src/app/trilium'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by zadam** [comment]
Hello, thank you for your report.

It's very weird though, I can't reproduce this. For me exact same command succeeds correctly ...

Can you perhaps reference exact version 0.41.5 instead of :latest tag?

**Comment by roadcode** [comment]
@zadam use image 0.41.5, 0.41-latest and latest, same error. my env is Ubuntu 18.04.4 LTS

**Comment by popey456963** [comment]
Hm, tried on a Ubuntu 16 and Ubuntu 20 box and was unable to reproduce.  Do you have any content within `~/trilium-data`?  If you tried an alternative directory does it work?

**Comment by roadcode** [comment]
sorry，i use the wrong command
