### ISSUE TITLE
[bug?] drag + drop in OSX install not working

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#984]
hello,

it seems I can´t drag and drop anything in the tree – while moving via keyboard command or 'move' function works.

I am not really code-savvy, so I can´t tell whether there are external dependencies that could cause this with OSX-install.

so, wanted to check, whether it´s only me, whether there are things I could check – or whether it really is a bug.

thx + best!
[trilium-2020-04-26.log](https://github.com/zadam/trilium/files/4535977/trilium-2020-04-26.log)

----------------------
Version 0.41.5 (0.41.5)

**Comment by zadam** [comment]
Hello, looks like you found another bug from 0.41 refactoring! This has been now fixed and will be in 0.41.6. Thanks for reporting.

**Comment by lerone-b** [comment]
I am a natural fan of bugs and beetles... maybe that´s why :-D

– thx for taking care!

**Comment by lerone-b** [comment]
uhm... sorry... but can it be this has been 're-broken'?

at least I can´t dragNdrop any longer after updating to 0.41.6

thx for checking

**Comment by zadam** [comment]
Just to be clear, are you trying to do this? That is recorded on 0.41.6

![](https://user-images.githubusercontent.com/617641/81480786-15317300-922c-11ea-99a0-c086df39a5eb.gif)

**Comment by lerone-b** [comment]
yes. that it is. 
I recorded this.
![Trilium_no-reFold](https://user-images.githubusercontent.com/11589804/81487056-1c6f7580-925a-11ea-90b9-ef586e78c989.gif)

**Comment by lerone-b** [comment]
hey,

thx for fixing!
I assume you did, as things now work like a grace again, after downloading  v0.42.1 :-)
