### ISSUE TITLE
internal link: impossible to chose linking direction in v0.41.5/osx

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#985]
hello,

getting into usage I am irritated that the (fabulous) internal link functions for notes seems depracated here vis-a-vis the documentation.

in the wiki there is a screenshot showing one could chose the link direction for a note after calling up the dialog (e.g. via meta-L/cmd-L).
here it looks like one can still chose link-title (analog to html-links) but not (any longer?) chose link-direction for the inter-note-link.

I very much looked forward to using this advanced / swift option for interlinking.
so wondering: has it be deprecated? is that specific to osx-version? something else?

thx again + best!
[trilium-2020-04-26.log](https://github.com/zadam/trilium/files/4535981/trilium-2020-04-26.log)
<img width="974" alt="internal-link-dialog_osx-0-41-5_what-i-see" src="https://user-images.githubusercontent.com/11589804/80314105-ad246b00-87ef-11ea-821f-a86336b7cd4a.png">
![internal-link-dialog_trilium-wiki-documentation](https://user-images.githubusercontent.com/11589804/80314107-aeee2e80-87ef-11ea-9281-617f865dd3be.png)

----------------------
Version 0.41.5 (0.41.5)

**Comment by zadam** [comment]
Sorry, I don't get your question. Internal links always have clear / defined direction.

UI of the dialog changed in time compared to GIF/screenshot, but no functionality has been lost.

Can you please clarify what you mean?

**Comment by lerone-b** [comment]
hello Zadam,

sure - and sry if I should have confused things on my side, by making false assumptions.

what I took from the image in the wiki is that there is/was(?) a way to chose whether a note should be a _source_ or the _target_ of a link-relation.

I took that from the alternative bullet-options "add selected note to current note" vs. "add current note to selected note".
– did I get that wrong? maybe that is the old way of including notes that I misread here? :-?

... but then it seemed to make sense to me to be able to chose working in a note and thinking it should be linked, which direction that link should have (even without leaving the note).

**Comment by zadam** [comment]
> "add selected note to current note" vs. "add current note to selected note"

Those options actually represented cloning since "clones" are in an abstract sense also a link (between parent and child). But since then I decided to separate the concepts so it's not possible to clone from "add link" dialog.

As a result it was never possible to choose direction of an internalLink - but I also kind of struggle to understand the need for that. Internal link is basically a HTML hyper link which always points from its "occurrence" to a target page. But on the other hand (and differently from HTML hyperlinks), it's easy to find which notes link to current note (i.e. backlinks) so the direction does not matter that much ...

**Comment by lerone-b** [comment]
probably you are right, meaning I am **inclined to join your opinion on second thought**.
– I think initially I was assuming there is some relevant difference in representation in relation graph or other information fields... but maybe not so in any relevant way.

what I **probably weaved into my assumption** _unconsciously_, making me see such a thing/need, is **the parent-child-relation of the tree and its (non-)relation to the relation graph**. 
i.e. I guess I was assuming one could from within a note easily do two thing at once: 
a) create a link, 
b) decide this note is either parent or child of another note in the tree hierarchy (in the sense of a clone of the note becoming child/parent of another)

... but **maybe I was/am confusing things uneccessarily here**, or simply not yet getting the depths of Trilium-structuring options/possibilities...

... but then I am somehow also still trying to get my head around what to think / make of the fact that **parent/child-relations of the tree are not represented in the relation graph** (_while on the other hand inclusion in the relation map is represented_ etc.)....

... so its probably mostly me trying to get into Trilium – and my head around it... :-}
sorry in case that needlessly consumes bandwidths...!

**Comment by lerone-b** [comment]
... **keeping a note**, that I share danielnbalasoiu´s sentiment that there is **some sense in representing parent-child relations (somehow) in the relation map**. (see #945 )
– especially taking into account _it´s central role / meaning in any overview of a notes overall/holistic topological position_ in the notebook...

but also _closing this particular issue_, as it turned out to be **a non-issue**, really :-)
