### ISSUE TITLE
link map missing represenation of link to relation map (0.41.5-osx)

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#987]
[sorry for frequency of 'issues' - happens in _starting up_ w/ Trilium... ]

the link map I see for the demo-content of 'Prince Charles' seems to present a different graph than what the documentaion says/shows. 

I was  very happy to see there that inclusion of a note in a relation map leads to a representation in a notes linkmap (which is a very potent function for cognizing). when I look at the very same link map for the same note in the current osx-version this linked relation map ('My Family Tree') is not registered/represented.

very best! o

----------------------
Version 0.41.5 (0.41.5)
----------------------

<img width="1285" alt="linkmap_v0-41-5-osx" src="https://user-images.githubusercontent.com/11589804/80314741-93852280-87f3-11ea-9513-48fb9a67a3d3.png">
![linkmap_wiki-documentation](https://user-images.githubusercontent.com/11589804/80314745-96801300-87f3-11ea-95f5-d2ab87b0b5d7.png)

[trilium-2020-04-26.log](https://github.com/zadam/trilium/files/4536037/trilium-2020-04-26.log)

**Comment by zadam** [comment]
Weird, here what Charles' link map shows for me (from clean installation):

![image](https://user-images.githubusercontent.com/617641/80318464-9ccdb980-880a-11ea-9dbc-ded930a86383.png)

Does the relation map of the family work correctly for you - did you perhaps change something there?

**Comment by lerone-b** [comment]
hey,

uhm - no, nothing relevant changed that I am aware of.
and, yes, the relation map of the family seems all fine. 

I moved the branch around and some other file (saved search) out of the Family Tree Branch... 
and now I see the relation map again in the graph. uhm strange.
definitely was not there before (see last screenshot), and I did definitely not change the relation map... but can´t now really reproduce the structure that broke things...

so: it´s good to see that relation maps *are in there*! yay!
and: I will report back if I see such strange behaviour (omission) again.

thx for checking back!

**Comment by lerone-b** [comment]
... another question to the same (broader) context of link map representation (and I hope this is not hijacking my own issue thread): have you ever given thought to represent the icons of a node/note as part of the title in the link map?
– asking because I think it would greatly improve the representational value of the link map  without compromising simplicity/clarity.; e.g. seeing the _template_/_person_ icons, the _relation map_ icon, and possible others alongside the note title and the arrows would immediately give the user a deeper grasp of the relational meaning of the graph.

**Comment by zadam** [comment]
> have you ever given thought to represent the icons of a node/note as part of the title in the link map?

Yes, actually I've been thinking about this very thing recently :-) So I do plan to implement this but not sure when exactly ...
