### ISSUE TITLE
[bug] note export not leaving a trace

### ISSUE THREAD

**Issue by lerone-b** [zadam/trilium#990]
hey - I am not sure this is user stupidity, or trivial – or both...
but I _did consult_ documentation / forum / available settings to no solution.

**every export I am trying does not leave any trace of the export** ( a) no UI feedback b) no trace of any exported file (either in the expectable locations or findable via Spotlight index).
I tried all kinds of exports (html/zip, Markup,...)

as this is a very _basic_ thing, I am currently assuming it is _an issue with OSX instance of Trilium_, but that´s just wild guessing... might still be some idiosyncratic thing with my setup.
and I am aware OSX app is not really supported - but this seams _very basic for usability_, so I raise it.

... in any way, any hint appreciated on how to get export right – for inclusion of Trilium in my OSX-workflow, as well as for being better with supporting any issue cases w/ note export... (see #980 for example)

thx!!
[trilium-2020-04-27.log](https://github.com/zadam/trilium/files/4538644/trilium-2020-04-27.log)

**Comment by zadam** [comment]
Hello, thanks for reporting, I can reproduce the issue and will fix it soon. I think the bug was introduced in one of the betas of 0.41.X
