### ISSUE TITLE
Feature request: Add "expand subtree" to complement "collapse subtree"

### ISSUE THREAD

**Issue by dtomlinson91** [zadam/trilium#993]
I use nested notes a lot - the tree design of Trilium is incredibly useful to create organised and structured content this way.

I often find myself wanting an overview of all notes under the parent (recursively relative to the top most parent note).

As there is no concept of a table of contents, and it wouldn't make sense anyway with the tree design, it would be nice if when you right click a note and click advanced, there was an expand subtree in addition the collapse subtree currently present. This expand could do the exact inverse of collapse, recursively go to each child note and expand it.

Then I have a quick and easy visualisation of all notes under a certain heading.

An example of where this could come in handy:

![image](https://user-images.githubusercontent.com/53234158/80546704-4ac59900-89ae-11ea-8377-2e3728d76eb9.png)

And the current collapse note functionality:

![image](https://user-images.githubusercontent.com/53234158/80546720-5618c480-89ae-11ea-9a09-cd07e86e116b.png)

**Comment by zadam** [comment]
Hello, yes, makes sense to be able to expand subtrees. I added this option to context menu, will be in 0.42
