### ISSUE TITLE
Cannot Undelete Notes

### ISSUE THREAD

**Issue by meichthys** [zadam/trilium#994]
@zadam I'm moving my issue here so i don't hijack the other issue.

I'm running v0.41beta

I opened Trilium and noticed that a note was duplicated (not a clone) so i deleted the duplicate note which ended up deleting both notes (even though the note was not a clone). Now i can't seem to recover the deleted note.

Unfortunately i don't see the deleted note in Recent Changes.
Even if i re-create a test note and delete it, it doesn't show up in the Recent changes.

**Comment by zadam** [comment]
Hello, thank you for reporting this bug - 0.41 has a new feature for displaying recent changes also on subtree, unfortunately this broke the undeleting. I just committed the fix, it will be in 0.41.7

**Comment by meichthys** [comment]
Ok, makes sense. Thanks for the quick fix!
