### ISSUE TITLE
Broken custom themes

### ISSUE THREAD

**Issue by ultrafine** [zadam/trilium#996]
Currently using Trillium v0.41.6 and some custom themes seem broken when applied.

[Original Melon Theme](https://github.com/raphwriter/trilium-theme-melon/raw/master/trilium-theme-melon.png)
[Broken Melon Theme](https://gofile.io/?c=JrrKpe)

Same thing happens with Material-Dark-Trilium theme by ZMonk91.

**Comment by zadam** [comment]
Most probably they were hooking up to the internal CSS classes which are not part of the theming contract and can change between releases. 0.41 release contained big frontend refactoring, so I'm not surprised themes which relied on specific classes/ids broke.

Trilium provides stable theming API in the form of CSS variables as specified [here](https://github.com/zadam/trilium/wiki/Themes) but it is rather limited ...
