### ISSUE TITLE
Create new note doesn't automatically enable editing the name

### ISSUE THREAD

**Issue by kekePower** [zadam/trilium#997]
Hey!

Thanks for making this awesome program. It's a life saver in many ways :-)

Now to the issue.

I'm using 0.41.6, both client and server, on Linux and every time I create a new note it doesn't automatically enable renaming the note as it did before.
Now I have to manually click on the name to edit it and it would be great to get back the old behavior or guide me to a HOWTO so I can fix it myself.

Thanks!

**Comment by zadam** [comment]
Hello, thank you for reporting this issue - yes, focusing the title has been inconsistent depending on the method used to create the note. I was using mostly keyboard shortcuts (like `ctrl+p`) which focuses the title so I didn't notice it.

Anyway, this is now fixed and will be in the next release. Thanks again.

**Comment by kekePower** [comment]
Hey.

This issue has surfaced again with version 0.42.6.
